Add advection-dominated stabilization examples
idaholab/moose pull request #10028
Opened 2017-10-05 14:38 UTC by lindsayad

Includes:
  - SUPG stabilization with Q2Q1
  - SUPG,PSPG stabilization with Q1Q1

Closes #10027

2017-10-05 14:56 UTC, moosebuild commented
Job [Documentation](https://www.moosebuild.org/job/122865/) on 086e351 wanted to post the following:

View the site [here](http://mooseframework.org/docs/PRs/10028/site)

This comment will be updated on new commits.

2017-10-05 15:17 UTC, jwpeterson requested changes

2017-10-05 15:17 UTC, jwpeterson commented on modules/navier_stokes/src/kernels/INSBase.C
> +                              9. * (4. * nu / (h * h)) * (4. * nu / (h * h)));
This (and especially in the Jacobian) is a lot of duplicated code just to turn off the one contribution...
```
Real transient_part = _transient_term ? 4. / (_dt * _dt) : 0.;
return _alpha / std::sqrt(transient_part + ...);
```
seems cleaner.

2017-10-05 15:17 UTC, jwpeterson commented on modules/navier_stokes/src/kernels/INSBase.C
> +                              9. * (4. * nu / (h * h)) * (4. * nu / (h * h)));
The above also switches to the more common 2/dt form.

2017-10-05 15:17 UTC, jwpeterson commented on modules/navier_stokes/test/tests/ins/mms/supg/supg_pspg_adv_dominated_mms.i
> +  elem_type = QUAD9
This problem should use QUAD4s, right?. Besides this and the `pspg=true` parameter, are there any other differences between the two input files? Seems like they should just be combined into one and the tests controlled with CLI args.

2017-10-05 15:46 UTC, lindsayad commented
@jwpeterson Changing to 2/dt required regolding of the transient mms tests and adding the 1/rho to PSPG stabilization required regolding of all other mms tests involving PSPG. I'm going to re-run our paper's convergence studies and make sure our results are still the same.

2017-10-05 16:49 UTC, jwpeterson commented
> @jwpeterson Changing to 2/dt required regolding of the transient mms tests and adding the 1/rho to PSPG stabilization required regolding of all other mms tests involving PSPG. I'm going to re-run our paper's convergence studies and make sure our results are still the same.

OK, you can save those changes for another PR then if you want?

2017-10-06 19:24 UTC, jwpeterson approved these changes

2017-10-06 19:25 UTC, merged