Add documentation for GraintTracker ICs
idaholab/moose pull request #10020
Opened 2017-10-04 21:36 UTC by permcody

refs #10000

2017-10-04 21:58 UTC, moosebuild commented
Job [Documentation](https://www.moosebuild.org/job/122662/) on 43e382f wanted to post the following:

View the site [here](http://mooseframework.org/docs/PRs/10020/site)

This comment will be updated on new commits.

2017-10-05 13:40 UTC, aeslaughter requested changes
Looks good, just one small comment to consider.

2017-10-05 13:40 UTC, aeslaughter commented on docs/content/documentation/systems/Postprocessors/phase_field/PolycrystalEBSD.md
> +a reduced order parameter model from electron backscatter data. More information about this capability can be found [here]((ICs/EBSD.md).
I don't like using "here", also you seem to have an extra (.

 I would prefer something like:
```
...this capability is provided in the [EBSD](ICs/EBSD.md) object description.
```

2017-10-05 13:40 UTC, aeslaughter commented on docs/hidden.yml
> -    - /Postprocessors/PolycrystalVoronoi
It is really nice to see a few of these to start to disappear, thanks!

2017-10-05 19:19 UTC, permcody commented
Ready to review again @aeslaughter

2017-10-05 22:17 UTC, aeslaughter approved these changes

2017-10-05 22:18 UTC, aeslaughter commented
@permcody If this passes I will do a squash and merge, which might be the better way to make these tiny doc fixes rather than go through the process of typing the change or pull in the content.

2017-10-06 14:36 UTC, merged