Update getting started pages
idaholab/moose pull request #10070
Opened 2017-10-11 18:49 UTC by aeslaughter

Updates to the MooseDocs getting started pages.
(refs #9638)

2017-10-13 10:55 UTC, moosebuild commented
Job [Documentation](https://www.moosebuild.org/job/123945/) on bcd7c7f wanted to post the following:

View the site [here](http://mooseframework.org/docs/PRs/10070/site)

This comment will be updated on new commits.

2017-10-16 21:00 UTC, aeslaughter commented
Whoever wants to take a look, the new "Getting Started" instructions can be found here: http://mooseframework.org/docs/PRs/10070/site/getting_started/installation/mac_os/index.html

2017-10-17 18:40 UTC, brianmoose requested changes
None of the package links seem to work

2017-10-19 15:32 UTC, brianmoose submitted a review, later dismissed

2017-10-19 15:32 UTC, brianmoose commented
The package links seem to work now, @milljm should probably review the content

2017-10-19 18:18 UTC, milljm submitted a review, later dismissed
Everything else looks fine!

2017-10-19 18:18 UTC, milljm commented on docs/content/getting_started/installation/mac_pre_req.md
> +xcode-select
I believes its:
```bash
xcode-select --install
```

2017-10-20 17:13 UTC, permcody submitted a review, later dismissed
Looks OK except you should change Pre-Requisite back to prerequisite throughout.

2017-10-24 15:37 UTC, permcody approved these changes

2017-10-24 15:37 UTC, merged