Add cracking_function test for tm closes #10051
idaholab/moose pull request #10131
Opened 2017-10-23 19:55 UTC by bwspenc

This moves over the cracking_function test from solid_mechanics to tensor_mechanics. This is the last of the smeared cracking regression tests to be moved over.

2017-10-23 20:13 UTC, moosebuild commented
Job [Documentation](https://www.moosebuild.org/job/126883/) on 5911060 wanted to post the following:

View the site [here](http://mooseframework.org/docs/PRs/10131/site)

This comment will be updated on new commits.

2017-10-24 15:44 UTC, dschwen requested changes

2017-10-24 15:50 UTC, bwspenc commented on modules/tensor_mechanics/test/tests/smeared_cracking/cracking_function.i
> +    value = 'if(x > 0.667, 1.1e6, 0) + if(x<=0.667, 1.2e6, 0)'
Cuz we love obfuscation? I fixed it.

2017-10-24 21:51 UTC, bwspenc commented
@dschwen I addressed the issue you pointed out.

2017-10-25 16:54 UTC, dschwen approved these changes

2017-10-25 16:54 UTC, merged