Add an accessor to retrieve the dimension of SolutionUserObject
idaholab/moose pull request #10140
Opened 2017-10-24 16:59 UTC by vincentlaboure

closes #10139

2017-10-24 17:17 UTC, moosebuild commented
Job [Documentation](<WSGIRequest: POST '/client/job_finished/1051070556/hpcbuild4_0/127393/'>) on ae8551f wanted to post the following:

View the site [here](http://mooseframework.org/docs/PRs/10140/site)

This comment will be updated on new commits.

2017-10-24 18:36 UTC, andrsd commented
Before merging this, let me check that this works with RELAP-7. We do not have a test case that would be using SolutionFunction + SolutionUserObject, but we have to be able to take 2D rattlesnake solution and use it in our setup where we have 1D and 2D elements. We claim our meshes are actually 3D (because they actual are).  We are "transferring" the 2D solution read from a file onto our 2D heat structure elements, which kosher, but I think this check would break this.

2017-10-24 18:39 UTC, vincentlaboure commented
I see your point: I can remove that check and have it only in our own `Function` in Rattlesnake

2017-10-24 21:34 UTC, andrsd commented
So, this breaks RELAP-7. I built a test for this and when it gets in the RELAP-7's devel, we can re-run the tests to see it.

2017-10-25 20:10 UTC, andrsd requested changes

2017-10-25 20:10 UTC, andrsd commented on framework/include/userobject/SolutionUserObject.h
> +  /// Return the spatial dimension of the mesh file
This should be `/** ... */` with `@return` etc.

2017-10-26 15:06 UTC, YaqiWang commented
Is this ready? There is a MR in Rattlesnake depending on this.

2017-10-26 15:16 UTC, andrsd commented
Yeah, it is fine now. Thanks for the ping @YaqiWang

2017-10-26 15:17 UTC, andrsd approved these changes

2017-10-26 15:17 UTC, merged