add a test to check PerformanceData Postprocessor for other events
idaholab/moose pull request #10197
Opened 2017-11-01 23:56 UTC by jessecarterMOOSE

Adds a test to check a PerformanceData Postprocessor output _value_, not just the presence of output, for an event other than runtime.

ref#10196

2017-11-01 23:57 UTC, jessecarterMOOSE commented
@permcody I'd like to get this merged soon, pretty please.

2017-11-02 00:03 UTC, permcody commented
See my comment on #10196 - YOU can initiate a libMesh update. Just update your submodule and push it up along with this PR.

2017-11-02 00:20 UTC, moosebuild commented
Job [Documentation](https://www.moosebuild.org/job/130617/) on 1d09196 wanted to post the following:

View the site [here](http://mooseframework.org/docs/PRs/10197/site)

This comment will be updated on new commits.

2017-11-02 00:42 UTC, jessecarterMOOSE commented
Agreed, but I figured the test was beneficial enough to merge as-is. But am I right in that if this goes in, future libmesh PR's will start failing?

2017-11-02 00:47 UTC, jessecarterMOOSE commented
Note: there is no "fix" here, just the test.

2017-11-02 14:13 UTC, roystgnr commented
This certainly ought to be merged separately from and prior to the libMesh update, but it would definitely be more convenient if I got the fix to the libMesh bug it exposes done before either.  Testing that now.

2017-11-02 17:53 UTC, permcody requested changes
Whoa! This should be triggering a bug in the TestHarness (race condition on output). We might have a regression in the TestHarness. @milljm - can you take a look? `print_perf_data.i` is used twice here and that file definitely writes output files and there is no prereq!

2017-11-02 18:00 UTC, jessecarterMOOSE commented
Is it because the test types are different? One is RunApp and one is CheckFiles. Are these test types documented anywhere?

Also, all I'm really after (I think) is making sure that the output isn't just a bunch of zeroes. Is there something better than `absent_out` ?

2017-11-02 18:04 UTC, permcody commented
@jessecarterMOOSE - That's exactly it. The TestHarness only runs that test on any `Tester` that claims to be reading from output files. `RunApp` by definition doesn't make any claims about dealing with output files so it's ignored. However, this use case shows a hole in our logic because this new test can definitely interfere with the old test (`CheckFiles`). We may have to rethink this a bit.

I don't want that to hold up this PR. So to fix, just add this to the test spec:
`cli_args = 'Outputs/exodus=false Outputs/csv=false'`, or put a prereq in there on the first test so that they get serialized. I'll open yet another ticket to look more closely at this kind of case.

2017-11-02 19:17 UTC, jessecarterMOOSE commented
Alright I went the route of turning off output files because this test doesn't really have a prereq in the sense that it needs something from another test. Also changed the test name to make a little more sense.

2017-11-02 22:14 UTC, permcody approved these changes

2017-11-02 22:15 UTC, merged