parser: make filepaths in input relative to input file dir
idaholab/moose pull request #10200
Opened 2017-11-02 18:35 UTC by rwcarlsen

All input parameters that are typed FileName, FileNameNoExtension, or
MeshFileName (and vectors of these types) are treated as relative to the
directly the input file itself resides in.  The parser now prepends a
file path prefix to enforce this.

This will help with benchmarking and also pave the way for sandboxing of
tests/benchmarks in the future if we decide it is worth while.

ref #9834

2017-11-02 19:04 UTC, moosebuild commented
Job [Documentation](https://www.moosebuild.org/job/130727/) on c3a4240 wanted to post the following:

View the site [here](http://mooseframework.org/docs/PRs/10200/site)

This comment will be updated on new commits.

2017-11-06 20:40 UTC, moosebuild commented
Job [App tests](https://www.moosebuild.org/job/131219/) on 5beccee : invalidated by @rwcarlsen

2017-11-07 22:22 UTC, moosebuild commented
Job [App tests](https://www.moosebuild.org/job/131721/) on 1379d18 : invalidated by @rwcarlsen

2017-11-08 16:38 UTC, permcody commented
@idaholab/moose-team - I'd like buy-off before we merge this.

This PR enables MOOSE to move away from using CWD for finding resources and instead locates finding resources (meshes, other input files) relative to the input file instead. This is a significant change but as you can see it's a low impact change as it went through without a lot of fuss.

Opinions? Thoughts?

2017-11-08 17:01 UTC, jwpeterson commented
Seems fine to me, there's no way this can surprise users, right? What if they have an input file with 
```
mesh = `/some/absolute/path/foo.e`
```
and they have both a `foo.e` in the working directory of a given input file *and* a different `foo.e` at the location above?

2017-11-08 17:10 UTC, rwcarlsen commented
@jwpeterson - absolute paths are left alone by this PR - they will continue working exactly as they do now.

2017-11-08 17:18 UTC, andrsd requested changes
Method comments should use `/**...*/` style comments with things like `@param`.

2017-11-08 17:19 UTC, andrsd commented
This is fine with me when the comment style issue is addressed.

2017-11-08 20:22 UTC, rwcarlsen commented
@andrsd - done.

2017-11-08 20:40 UTC, lindsayad commented
Works for me

On Wed, Nov 8, 2017 at 1:22 PM, Robert Carlsen <notifications@github.com>
wrote:

> @andrsd <https://github.com/andrsd> - done.
>
> —
> You are receiving this because you are on a team that was mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/idaholab/moose/pull/10200#issuecomment-342947419>, or mute
> the thread
> <https://github.com/notifications/unsubscribe-auth/AJxgcMUWWrY8dk3rrDl_hO3GA7UndBUzks5s0g2MgaJpZM4QQJ-u>
> .
>

2017-11-08 21:10 UTC, andrsd commented
> @andrsd - done.

I am assuming you did not add `@param`s, because the other methods do not have them either?

2017-11-08 21:36 UTC, rwcarlsen commented
Basically - yes.

On Wed, Nov 8, 2017 at 2:10 PM, David Andrs <notifications@github.com>
wrote:

> @andrsd <https://github.com/andrsd> - done.
>
> I am assuming you did not add @params, because the other methods do not
> have them either?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/idaholab/moose/pull/10200#issuecomment-342960769>, or mute
> the thread
> <https://github.com/notifications/unsubscribe-auth/ABSeSoH1KeKqRF6q7PymDpDs6sH8QLn8ks5s0hjTgaJpZM4QQJ-u>
> .
>

2017-11-09 15:02 UTC, andrsd approved these changes

2017-11-09 19:42 UTC, merged