Support LATEST in [Mesh] section
idaholab/moose pull request #10215
Opened 2017-11-06 22:10 UTC by permcody

Like the title says. This adds support for LATEST in the Mesh/file parameters.

2017-11-06 22:37 UTC, moosebuild commented
Job [Documentation](https://www.moosebuild.org/job/131662/) on 542b996 wanted to post the following:

View the site [here](http://mooseframework.org/docs/PRs/10215/site)

This comment will be updated on new commits.

2017-11-09 14:53 UTC, permcody commented
Looks like a lot of changes, but it's mostly refactoring so that we can reuse our existing "find the latest file" code for meshes too.

2017-11-09 17:46 UTC, jwpeterson requested changes

2017-11-09 17:46 UTC, jwpeterson commented on framework/include/utils/MooseUtils.h
> + * @param
Empty param line?

2017-11-09 17:46 UTC, jwpeterson commented on framework/src/utils/MooseUtils.C
> +    if (find_if(extensions.begin(), extensions.end(), [cp_file](std::string ext) {
OK, I'm not an expert with lambdas, but should the `ext` arg be a const reference here?

2017-11-09 20:09 UTC, jwpeterson approved these changes

2017-11-09 20:09 UTC, merged