Improvement for EshelbyTensor calculation
idaholab/moose pull request #10223
Opened 2017-11-08 18:29 UTC by jiangwen84

Added total strain option
Replaced F with H
Regold tests
Added one regression test for the small strain formulation which uses total_strain (actually mechanical_strain)

closes #10222

2017-11-08 18:52 UTC, moosebuild commented
Job [Documentation](https://www.moosebuild.org/job/132124/) on ca42f96 wanted to post the following:

View the site [here](http://mooseframework.org/docs/PRs/10223/site)

This comment will be updated on new commits.

2017-11-08 20:43 UTC, bwspenc commented on modules/tensor_mechanics/src/materials/EshelbyTensor.C
> +  RankTwoTensor FTP = H.transpose() * P;
Name this HTP

2017-11-08 22:47 UTC, jiangwen84 commented
@bwspenc  Can you further review this PR? Thanks.

2017-11-08 23:19 UTC, bwspenc requested changes
The code changes in tensor_mechanics look good.  I'd prefer that you make the same changes in solid_mechanics and keep the symlinks to the results files.

Also, there's a documentation page on this in:
moose/docs/content/documentation/systems/Materials/tensor_mechanics/EshelbyTensor.md that needs a minor update to reflect these changes.

2017-11-08 23:19 UTC, bwspenc commented on modules/solid_mechanics/test/tests/domain_integral_thermal/gold/j_integral_2d_out.e
> -../../../../../tensor_mechanics/test/tests/domain_integral_thermal/gold/j_integral_2d_out.e
It looks like these were all symlinks, and you replaced them with new gold files.  We should be able to still symlink to the tensor_mechanics results to make sure they produce the same results, shouldn't we?

2017-11-08 23:19 UTC, bwspenc commented on modules/tensor_mechanics/src/materials/EshelbyTensor.C
> +    mooseError("EshelbyTensor cannot find eigher mechanical_strain or strain_increment material "
eigher->either

2017-11-14 15:18 UTC, jiangwen84 commented
@bwspenc all the comments are addressed :-)

2017-11-14 16:35 UTC, bwspenc approved these changes

2017-11-14 16:35 UTC, merged