Migrated three j-integral related regression tests to TM
idaholab/moose pull request #10232
Opened 2017-11-09 20:46 UTC by jiangwen84

The three tests are 

solid_mechanics/test/tests/domain_integral_thermal/j_integral_2d_ctefunc.i
solid_mechanics/test/tests/domain_integral_thermal/j_integral_2d_inst_ctefunc.i
solid_mechanics/test/tests/domain_integral_thermal/j_integral_2d_mean_ctefunc.i

ref #10230

2017-11-09 21:17 UTC, moosebuild commented
Job [Documentation](https://www.moosebuild.org/job/132803/) on 76cc45b wanted to post the following:

View the site [here](http://mooseframework.org/docs/PRs/10232/site)

This comment will be updated on new commits.

2017-11-10 00:00 UTC, permcody commented
I'm going to assign this to @bwspenc - My only comment on this PR is that I'd prefer to see less usage of "file_base" in test files. We like the connection where the input file name determines the output file name when looking through tests. Using file_base makes it harder to match up inputs and outputs when you aren't familiar with the tests.

2017-11-11 05:07 UTC, bwspenc requested changes
This looks good.  Just make the changes to the output file names, and this will be ready to go.

2017-11-11 05:07 UTC, bwspenc commented on modules/tensor_mechanics/test/tests/domain_integral_thermal/tests
> +    csvdiff = 'mean_out.csv'
I agree with @permcody: skip the `file_base` commands in the input files, and have this file be `j_integral_2d_mean_ctefunc_out.csv` (the default).

2017-11-11 05:07 UTC, bwspenc commented on modules/tensor_mechanics/test/tests/domain_integral_thermal/tests
> +    csvdiff = 'inst_out.csv'
Same with this one

2017-11-11 16:52 UTC, jiangwen84 commented
file_base has been removed :-)

2017-11-13 18:18 UTC, bwspenc approved these changes
Looks good. Thanks for addressing the file_base issue!

2017-11-13 18:18 UTC, merged