PorousFlowDarcyVelocityComponentLowerDimensional added
idaholab/moose pull request #10401
Opened 2017-12-14 03:35 UTC by WilkAndy

This allows users to record Darcy velocity in a lower-dimensional block in their mesh, such as a block representing a fracture.

Fixes #10269

2017-12-14 03:36 UTC, moosebuild commented
Job [Precheck](https://www.moosebuild.org/job/141021/) on f1aef9d wanted to post the following:

Your code requires style changes.  

A patch was auto generated and copied [here](http://mooseframework.org/docs/PRs/10401/style.patch)  
You can directly apply the patch by running, in the top level of your repository:

`curl -s http://mooseframework.org/docs/PRs/10401/style.patch | git apply -v`

2017-12-14 03:43 UTC, WilkAndy commented
This is finally done, @philippschaedle

2017-12-14 04:02 UTC, moosebuild commented
Job [Documentation](https://www.moosebuild.org/job/141030/) on c2208cf wanted to post the following:

View the site [here](http://mooseframework.org/docs/PRs/10401/site)

This comment will be updated on new commits.

2017-12-14 16:03 UTC, permcody commented on modules/porous_flow/src/auxkernels/PorousFlowDarcyVelocityComponentLowerDimensional.C
> +      _subproblem.assembly(_tid).getFE(FEType(), elem_dim)->get_dxyzdxi();
@andrsd or @friedmud, before this gets merged in, do you have any opinions. This is pretty specialized so we don't have a better interface in MOOSE.

2017-12-14 17:06 UTC, andrsd commented on modules/porous_flow/src/auxkernels/PorousFlowDarcyVelocityComponentLowerDimensional.C
> +      _subproblem.assembly(_tid).getFE(FEType(), elem_dim)->get_dxyzdxi();
I think there might be a problem calling this the very first time. This gets out FE from libMesh and requests an additional quantity (dxyzdxi/zeta). But reinit was already called, so my guess would be that you get some zero values back. The next time through it is probably fine.

Code-wise: you can do `_assembly.getFE(...)` instead of `_subproblem.assembly(_tid)`. That would be cleaner.

As far as user-friendly API goes, requesting values from FE happens deep in `Assembly::buildFE` and we do not provide users to pick what values they want. We pick `phi`, `dphi`, `d2phi` and `xyz` for them. Not sure if providing more flexibility would be useful.

Thinking more about this, may be a better approach is to get the references (actually pointers) as early as in the c-tor for all dimensions (0 - _mesh_dimension) and here just use something like `_tang1[elem_dim]`. That may fix the problem I described in paragraph 1 (is that was even a problem at all).

2017-12-14 23:22 UTC, WilkAndy commented on modules/porous_flow/src/auxkernels/PorousFlowDarcyVelocityComponentLowerDimensional.C
> +      _subproblem.assembly(_tid).getFE(FEType(), elem_dim)->get_dxyzdxi();
OK, i'll try the things mentioned above, thank you.  By the way, i just copied that line from ```/tensor_mechanics/src/kernels/StressDivergenceTensorsTruss.C```.  The reason i didn't get the reference in the constructor was because i was considering deforming meshes, where the tangent vectors might change direction.  But perhaps that's just silly, and certainly silly if at some stage the above code gives tang1=0 !

2017-12-14 23:48 UTC, WilkAndy commented on modules/porous_flow/src/auxkernels/PorousFlowDarcyVelocityComponentLowerDimensional.C
> +      _subproblem.assembly(_tid).getFE(FEType(), elem_dim)->get_dxyzdxi();
I get a seg-fault when the ctor contains:
```
 _tang1(_assembly.getFE(FEType(), _current_elem->dim())->get_dxyzdxi())
```
Any advice?

2017-12-15 00:13 UTC, WilkAndy commented on modules/porous_flow/src/auxkernels/PorousFlowDarcyVelocityComponentLowerDimensional.C
> +      _subproblem.assembly(_tid).getFE(FEType(), elem_dim)->get_dxyzdxi();
It's the ```_current_elem->dim()``` that gives the seg-fault

2017-12-15 00:28 UTC, andrsd commented on modules/porous_flow/src/auxkernels/PorousFlowDarcyVelocityComponentLowerDimensional.C
> +      _subproblem.assembly(_tid).getFE(FEType(), elem_dim)->get_dxyzdxi();
Right, you cannot do `_current_elem->dim()` in the constructor, because `_current_elem` is set during the loop over the mesh. The `_tang1` need to become an array of pointers to the values, 0th index for 0D elements, 1st index for 1D, etc. up to LIBMESH_DIM. Then, do a loop to initialize each item. Then, in compute node use `_current_elem->dim()` to index into `_tang1`. Make more sense?

2017-12-15 02:53 UTC, WilkAndy commented on modules/porous_flow/src/auxkernels/PorousFlowDarcyVelocityComponentLowerDimensional.C
> +      _subproblem.assembly(_tid).getFE(FEType(), elem_dim)->get_dxyzdxi();
Thank @andrsd .   This "hassle" is exactly the feature i want to exploit in this AuxKernel !   I'll attempt to implement what you write above.

2017-12-15 02:58 UTC, andrsd commented on modules/porous_flow/src/auxkernels/PorousFlowDarcyVelocityComponentLowerDimensional.C
> +      _subproblem.assembly(_tid).getFE(FEType(), elem_dim)->get_dxyzdxi();
Yeah, I know. I was just trying to say, that it may seem like a hassle to get 4 references, when you really are going to use just one of them...

2017-12-15 03:08 UTC, moosebuild commented
Job [Precheck](https://www.moosebuild.org/job/141327/) on ada15b3 wanted to post the following:

Your code requires style changes.  

A patch was auto generated and copied [here](http://mooseframework.org/docs/PRs/10401/style.patch)  
You can directly apply the patch by running, in the top level of your repository:

`curl -s http://mooseframework.org/docs/PRs/10401/style.patch | git apply -v`

2017-12-15 18:16 UTC, andrsd requested changes

2017-12-15 18:16 UTC, andrsd commented on modules/porous_flow/test/tests/aux_kernels/darcy_velocity_lower_except.i
> +    #block = 3
remove this line, it looks like a left over from debugging

2017-12-19 22:04 UTC, WilkAndy commented
Is this good to go now @andrsd ?

2017-12-19 23:15 UTC, andrsd approved these changes

2017-12-19 23:15 UTC, merged

2017-12-19 23:34 UTC, WilkAndy commented
Thanks for the review and merge, @andrsd

2017-12-20 14:24 UTC, brianmoose commented
Hmm, the Intel target for this seems to be reliably broken which has prevented this from getting onto the master branch: https://www.moosebuild.org/job/142739/
PR #10437 has the same errors which start after this was merged.
Maybe an integration issue with #9832?

2017-12-20 16:29 UTC, brianmoose commented
Hmm, nevermind, looks like just a flaky test. It seems to be passing on the latest devel testing.