Completely remove raw pointers from AppFactory
idaholab/moose pull request #10445
Opened 2017-12-21 22:51 UTC by permcody

refs #7714

2017-12-21 23:14 UTC, moosebuild commented
Job [Documentation](https://www.moosebuild.org/job/143390/) on 32efe35 wanted to post the following:

View the site [here](http://mooseframework.org/docs/PRs/10445/site)

This comment will be updated on new commits.

2018-01-12 19:47 UTC, moosebuild commented
Job [Test Intel](https://www.moosebuild.org/job/145245/) on ce996e5 : invalidated by @permcody

Odd Exodiff, shouldn&#39;t be there. Checking for repeatability

2018-01-12 21:33 UTC, permcody commented
@andrsd - Will you take a look and hopefully merge. This PR fails Tiamat, but I have a build working on my desktop now so I've fixed the deprecated API. The tests don't pass on my local system but I think that's just because these tests are so brittle. Once this is merged, I'll push the patch to test against Tiamat (which has a MOOSE submodule) and see if I can get it working.

2018-01-12 22:32 UTC, andrsd requested changes

2018-01-12 22:32 UTC, andrsd commented on unit/include/PorousFlowBrineCO2Test.h
> +  std::shared_ptr<MooseApp> _app;
`MooseAppPtr`?

2018-01-12 22:32 UTC, andrsd commented on unit/include/PorousFlowFluidStateFlashTest.h
> +  std::shared_ptr<MooseApp> _app;
`MooseAppPtr`

2018-01-12 22:32 UTC, andrsd commented on unit/include/PorousFlowWaterNCGTest.h
> +  std::shared_ptr<MooseApp> _app;
`MooseAppPtr`

2018-01-17 15:22 UTC, permcody commented
This should be ready for merge. I'll fixup Tiamat-mock when this is in.

2018-01-17 15:37 UTC, andrsd approved these changes

2018-01-17 15:37 UTC, merged