disallow setting parameters not registered in validParams
idaholab/moose pull request #10547
Opened 2018-01-17 20:28 UTC by rwcarlsen

There were several places in moose and the modules where we were inserting parameters that weren't logged in validParams functions that had to be fixed.  All setting of the ``_fe_problem`` special parameter was also consolidated/refactored to reside inside the factory.

2018-01-17 20:40 UTC, moosebuild commented
Job [Documentation](https://www.moosebuild.org/job/146592/) on 61afe70 wanted to post the following:

View the site [here](http://mooseframework.org/docs/PRs/10547/site)

This comment will be updated on new commits.

2018-02-19 19:46 UTC, permcody commented
Closing due to inactivity - Note: I definitely want this in the framework when you have time. Looks like you'll need to rebase and squash anyway.

2018-02-26 20:51 UTC, rwcarlsen commented
Picking this back up.

2018-02-26 20:53 UTC, moosebuild commented
Job [Precheck](https://www.moosebuild.org/job/160790/) on 65caae1 wanted to post the following:

Your code requires style changes.  

A patch was auto generated and copied [here](http://mooseframework.org/docs/PRs/10547/style.patch)  
You can directly apply the patch by running, in the top level of your repository:

`curl -s http://mooseframework.org/docs/PRs/10547/style.patch | git apply -v`  

Alternatively, with your repository up to date and in the top level of your repository:

`git clang-format c7f5c1ffd61b2104870ff1ca34019584c53911d8`

2018-02-27 15:47 UTC, moosebuild commented
Job [Modules debug](https://www.moosebuild.org/job/160959/) on 6ea4d31 : invalidated by @rwcarlsen

2018-03-22 14:57 UTC, moosebuild commented
Job [App tests](https://civet.inl.gov/job/168516/) on afc42cf : invalidated by @rwcarlsen

2018-03-27 16:47 UTC, moosebuild commented
Job [App tests](https://civet.inl.gov/job/170465/) on 9c1a873 : invalidated by @rwcarlsen

2018-03-28 22:54 UTC, moosebuild commented
Job [Private App tests](https://civet.inl.gov/job/170468/) on 9c1a873 : invalidated by @rwcarlsen

2018-03-28 23:25 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/172088/) on d49e1d9 wanted to post the following:

Your code requires style changes.  

A patch was auto generated and copied [here](http://mooseframework.inl.gov/docs/PRs/10547/style.patch)  
You can directly apply the patch by running, in the top level of your repository:

`curl -s http://mooseframework.inl.gov/docs/PRs/10547/style.patch | git apply -v`  

Alternatively, with your repository up to date and in the top level of your repository:

`git clang-format 710036da7dfca4e1b663809fc55bdd0b00d62b3e`

2018-03-29 20:05 UTC, moosebuild commented
Job [Private App tests](https://civet.inl.gov/job/172433/) on 00790bd : invalidated by @rwcarlsen

2018-04-02 18:03 UTC, moosebuild commented
Job [Private App tests](https://civet.inl.gov/job/172433/) on 00790bd : invalidated by @rwcarlsen

2018-04-02 21:30 UTC, rwcarlsen commented
ping - this should be ready. @permcody

2018-04-02 22:50 UTC, permcody requested changes
This looks good! Let's figure out why the internal app is failing, and fixup the PETSc options.

2018-04-02 22:50 UTC, permcody commented on framework/src/actions/CreateProblemAction.C
> +#endif
Hmm, this isn't quite right. These parameters should be added through this method:
https://github.com/idaholab/moose/blob/devel/framework/src/utils/PetscSupport.C#L758-L803

2018-04-26 19:02 UTC, moosebuild commented
Job [External App tests](https://civet.inl.gov/job/181430/) on 087a344 : invalidated by @rwcarlsen

2018-04-26 22:27 UTC, moosebuild commented
Job [App tests](https://civet.inl.gov/job/182045/) on 20c7f75 : invalidated by @rwcarlsen

2018-04-26 22:56 UTC, permcody approved these changes

2018-04-26 22:56 UTC, merged