Adjust HEMFluidProperties for use in Bison.
idaholab/moose pull request #10550
Opened 2018-01-17 23:44 UTC by jasondhales

A matching merge request is in for IAPWS95.
References #10549

2018-01-17 23:56 UTC, moosebuild commented
Job [Documentation](https://www.moosebuild.org/job/146767/) on beb3ac6 wanted to post the following:

View the site [here](http://mooseframework.org/docs/PRs/10550/site)

This comment will be updated on new commits.

2018-01-18 15:02 UTC, andrsd requested changes

2018-01-18 15:02 UTC, andrsd commented on modules/fluid_properties/include/userobjects/HEMFluidProperties.h
> +  virtual Real quality_Tsat_h(Real Tsat, Real h) const = 0;
Add doco for this method.

2018-01-18 15:02 UTC, andrsd commented on modules/fluid_properties/include/userobjects/HEMFluidProperties.h
> +  virtual Real rho(Real pressure, Real temperature, Real quality) const = 0;
Add `@param quality ...` doco.

2018-01-18 15:02 UTC, andrsd commented on modules/fluid_properties/include/userobjects/HEMFluidProperties.h
> +  virtual Real h(Real pressure, Real temperature, Real quality) const = 0;
Add `@param quality ...` doco.

2018-01-18 21:29 UTC, jasondhales commented
I added the documentation.

2018-01-18 23:05 UTC, andrsd approved these changes

2018-01-18 23:05 UTC, moosebuild commented
Job [Test Intel](https://www.moosebuild.org/job/147151/) on 215d720 : invalidated by @andrsd

Timeout

2018-01-22 14:20 UTC, merged