Restrict class search to listed directories
idaholab/moose pull request #10585
Opened 2018-01-23 15:51 UTC by aeslaughter

(refs #10560)

2018-01-23 16:06 UTC, moosebuild commented
Job [Documentation](https://www.moosebuild.org/job/148206/) on 58529a3 wanted to post the following:

View the site [here](http://mooseframework.org/docs/PRs/10585/site)

This comment will be updated on new commits.

2018-01-23 23:16 UTC, brianmoose requested changes

2018-01-23 23:16 UTC, brianmoose commented on docs/website.yml
> +      - framework/include
Need to include modules and app include files

2018-01-24 16:11 UTC, aeslaughter commented
See #10593 for a simpler solution.

2018-01-24 16:11 UTC, closed without merging