Updating SLIB namespace to be unique.
idaholab/moose pull request #10760
Opened 2018-02-12 21:27 UTC by mbairdphys

2018-02-12 21:32 UTC, permcody requested changes
Thanks for the contribution. We have a pretty stringent SQA process to follow though which involves creating an issue (right here through Github) and then referencing that ticket in your commit message (refs or closes #\<ticket number\>). Put in detail about why you are changing this. It's important to be specific because this doesn't affect MOOSE so we'll want to know what this is some time down the road when we want to update Exodiff and it has consequences that we can't readily see.

2018-02-12 21:56 UTC, mbairdphys commented
I opened up issue #10761 to cover this, and I amended the commit message.  If I am missing something, please let me know.  Thanks!

2018-02-12 22:08 UTC, moosebuild commented
Job [Documentation](https://www.moosebuild.org/job/156040/) on 827e17d wanted to post the following:

View the site [here](http://mooseframework.org/docs/PRs/10760/site)

This comment will be updated on new commits.

2018-02-13 14:23 UTC, permcody approved these changes

2018-02-13 14:24 UTC, merged