Add time derivative of a variable gradient
idaholab/moose pull request #10933
Opened 2018-03-01 17:27 UTC by lindsayad

Also refactor some variable related things.

 - Adds calculation of the time derivative of a gradient to moose variables
   - This is tested by an input file which solves the Coulomb gauge formulation of
     Maxwell's equations which contains the time derivative of the gradient of a coupled
     standard MooseVariable
     - Consequently this test also demonstrates coupling of a standard MooseVariable in a
       VectorKernel. Previously we had only tested coupling of a VectorMooseVariable to a
       Kernel
  - While building the new test, it was discovered that coupling a MooseVariable into a
    VectorKernel (or VectorIntegratedBC) would seg-fault because of a bad indexing
    operation, attributable to the fact that we iterate through j's up to
    `_phi.size()`. In the case of this new coupling, the size of the VectorMooseVariable
    is greater than the size of the coupled MooseVariable
    - Consequently, the off diagonal computing routines for kernels and boundary
      conditions were modified to actually take the moose variable as the method
      argument. Then j's can be iterated through up to the size of the coupled variable
  - Templated MooseVariableField was also split into .h and .C files to enable faster
    re-compilation when its methods are modified
    - Explicit instantiations of MooseVariableField<Real> (MooseVariable)
      and MooseVariableField<RealVectorValue> (VectorMooseVariable) are then provided at
      the end of the .C file
      - These explicit instantiations required generalization of the curl methods in moose
        variable and Assembly

Closes #10861

2018-03-01 17:39 UTC, moosebuild commented
Job [Documentation](https://www.moosebuild.org/job/162134/) on 65b5dbb wanted to post the following:

View the site [here](http://mooseframework.org/docs/PRs/10933/site)

This comment will be updated on new commits.

2018-03-01 19:48 UTC, friedmud requested changes
I'm against the API change to `offDiagJacobian`... it puts too much in the user's hands.

Let's brainstorm ideas about what can be done.

2018-03-01 20:03 UTC, andrsd submitted a review, later dismissed

2018-03-01 20:03 UTC, andrsd commented on test/src/kernels/VectorCoeffReaction.C
> +/****************************************************************/
old header

2018-03-01 20:03 UTC, andrsd commented on framework/src/base/MooseVariableField.C
> +#include "MooseVariableField.h"
missing header

2018-03-01 20:03 UTC, andrsd commented on test/include/bcs/VectorPenaltyDirichletBC.h
> +#ifndef VECTORPENALTYDIRICHLETBC_H
No header

2018-03-01 20:03 UTC, andrsd commented on test/src/bcs/VectorPenaltyDirichletBC.C
> +#include "VectorPenaltyDirichletBC.h"
No header

2018-03-01 20:14 UTC, lindsayad commented
@friedmud We could add an additional argument to `computeOffDiagJacobian` corresponding to `_phi.size()`?

2018-03-01 22:04 UTC, friedmud commented
@lindsayad that's kind of what I was thinking.  Can we make it default to something useful so we don't have to change every object in the whole system?

2018-03-01 22:05 UTC, friedmud commented
BTW: Keep in mind that whatever solution we come up with here - might help us solve our `ArrayKernel` issues...

2018-03-08 16:45 UTC, lindsayad commented
@friedmud What do you mean by changing every object in the system? You mean every object that overrides `computeOffDiagJacobian`? If we add a second argument, even with a default, we'll still have to change the method signatures of all of those objects that are overriding `computeOffDiagJacobian`.

For me a default argument doesn't make sense because all of these objects with `computeOffDiagJacobian` are getting called from `ComputeFullJacobianThread` where I would be providing the second argument.

2018-03-13 19:49 UTC, lindsayad commented
@friedmud I think this should be ready to go

2018-03-26 19:35 UTC, friedmud commented
Wait - I still don't understand why we have to change the interface here.  `_phi` should get traded out to be the coupled variable's `phi` when doing off-diagonal calculations... so the size of `_phi` should be the right thing.

2018-03-26 19:38 UTC, lindsayad commented
Not if the coupled variable is a fundamentally different kind of variable, e.g. a `MooseVariable` vs. a `VectorMooseVariable`. In this case, `_phi` is of type `VariablePhiValue`; we can't covert it to type `VectorVariablePhiValue`

2018-03-26 19:44 UTC, friedmud commented
Hmmm.  That makes sense - but is also a bummer.  I guess there is no confusion because if you're coupling to a vector variable then you're definitely going to need to use a different shape function for the computeQpOffDiagJacobian statements.

How well documented is this?  Is there documentation that spells out when you need to use one of the `_V_` member variables?  (BTW: I'm not in love with the `_V_` prefix... but I also can't think of much better besides writing out `_vector_` instead...)

2018-03-26 21:14 UTC, lindsayad commented
Hmm...I'm not in love with `_V` because it breaks the C++ standard, so I'm going to change that. I think I will add some documentation to kernels/boundary conditions specifying when additional "phi" members ar needed

2018-03-27 15:37 UTC, lindsayad commented
@friedmud 72fc25f has significant documentation added. The finite element principles come from the wiki

2018-03-27 17:02 UTC, friedmud approved these changes

2018-03-27 17:02 UTC, friedmud commented
Looks good - thanks for all the doco!

2018-03-27 17:02 UTC, merged