Get_Repo_Revision.py: about twice as fast, more work to do
idaholab/moose pull request #10970
Opened 2018-03-07 18:39 UTC by permcody

refs #10969

2018-03-07 22:21 UTC, friedmud requested changes
Needs `.md` documentation for this new Makefile parameter... including how to turn it on and an example of how to use what it generates.

2018-03-08 15:24 UTC, permcody commented
More notes for reviewer:
The changes to `get_repo_revision.py` are not as extensive as they appear. I made the script into a class so that I could cache a few of the shell calls that are made repeatedly so almost the entire script has been indented. I also change the odd spacing (e.g. "method( arg )" -> "method(arg)") throughout and of course had to add `self` in several places do to the promotion from functions to methods. The only real changes are at the bottom of the `writeRevision` method where we do extra stuff when the revision does **not** change.

Stork now defaults to **not** building a revision file.

2018-03-08 19:45 UTC, friedmud approved these changes

2018-03-08 19:45 UTC, merged

2018-03-08 21:27 UTC, brianmoose commented
```
Traceback (most recent call last):
  File "/opt/civet/build_0/moose/framework/scripts/get_repo_revision.py", line 217, in <module>
    version_info.writeRevision(repo_location, app_name, header_file)
  File "/opt/civet/build_0/moose/framework/scripts/get_repo_revision.py", line 207, in writeRevision
    shellCommand("touch -r " + revision_header + " " + touch_file)
  File "/opt/civet/build_0/moose/framework/scripts/get_repo_revision.py", line 28, in shellCommand
    raise Exception()
Exception
```
Seems to show up on all the apps while building...