explicitly call python2
idaholab/moose pull request #11091
Opened 2018-03-22 18:50 UTC by MartinLuethi

Newer Linux distributions have symlinked /usr/bin/python3 to /usr/bin/python,
such that "/usr/bin/env python" calls python3 instead of python2.

Changes:
- replace "/usr/bin/env python" with "/usr/bin/env python2" in all *.py files

- this change choses explicitly the python version (currently python2)

- this patch enables the gradual transition to python3, since python3 scripts
  can be marked with "/usr/bin/env python2"

- it is unlikely that this patch breaks anything on Linux or MacOS X, since
  /usr/bin/env should find the corresponding python version.

2018-03-22 18:56 UTC, brianmoose commented
Looks like you rebased your branch against master which is why you have all those merge commits.
You'll want to rebase against the devel branch and repush.

2018-03-22 19:09 UTC, MartinLuethi commented
Not sure if something went wrong. I rebased on devel, and did the pull request with respect to devel.
Everything like described on the web page. 
Should I try a new pull request?

2018-03-22 19:52 UTC, brianmoose commented
You probably don't need a new PR, you just need to fix up your branch. I guess you added your commit to a branch based of master. You need to add it to a branch based on devel.
Don't know the quickest way, but this might work (assuming you have the "upstream" remote):
```
git checkout env_python2 # start in the current branch
git checkout -b env_python2-orig # make a copy in case something goes wrong
git fetch upstream # get up to date with idaholab/moose
git checkout -b tmp-branch upstream/devel # create a temporary branch based on idaholab/moose:devel
git cherry-pick dfebf5a # put your commit onto the branch
git branch -f -m tmp-branch env_python2 # overwrite the old branch with the temporary branch
git push -f origin env_python2 # force push back to github.
```
If something goes horribly wrong then you still have your commit in the `env_python2-orig` branch

2018-03-22 20:00 UTC, MartinLuethi commented
thanks a lot for your detailed instructions
I now did exactly that, hope the commit is correct now.

Best, Martin

2018-03-22 20:08 UTC, brianmoose requested changes

2018-03-22 20:08 UTC, brianmoose commented on modules/combined/doc/moosedocs.py
> +#!/usr/bin/env python222222222222222222
bad python

2018-03-22 20:08 UTC, brianmoose commented on python/peacock/BasePeacockMainWindow.py
> +#!/usr/bin/env python22
bad python in all the `python/peacock` files

2018-03-22 20:08 UTC, brianmoose commented on test/tools/large_subdomain_gen/_output_cubit_commands.py
> +#!/usr/bin/env python2.52
bad python

2018-03-22 20:08 UTC, brianmoose commented on test/tools/large_subdomain_gen/large_sub_gen.py
> +#!/usr/bin/env python2.52
bad python

2018-03-22 20:19 UTC, andrsd commented
Yeah, or just:
```
git rebase --onto devel HEAD~1 env_python2
```
(assuming devel has the current HEAD)

2018-03-23 10:25 UTC, MartinLuethi commented
Sorry, I should have checked all files by hand, which I did now. Some were changed several times, maybe due to symlinks pointing to the same file.

Anyway, the changes should be clean now, /usr/bin/env python2 everywhere.

2018-03-23 12:46 UTC, permcody commented
Martin, Nice meeting you this week. Thanks for the PR!

2018-03-23 13:12 UTC, moosebuild commented
Job [Documentation](https://civet.inl.gov/job/169170/) on e51bcf8 wanted to post the following:

View the site [here](http://mooseframework.inl.gov/docs/PRs/11091/site)

This comment will be updated on new commits.

2018-03-23 13:14 UTC, brianmoose approved these changes

2018-03-26 15:55 UTC, permcody approved these changes
Martin, Thanks for the contribution.

2018-03-26 15:55 UTC, merged