Strain energy density fix in SM.
idaholab/moose pull request #11182
Opened 2018-04-03 23:43 UTC by acasagran

Changes to strain energy density calculation in SolidModel to use the mechanical strain increment (i.e., elastic plus inelastic) in order to match the computation in tensor mechanics. Adding tests for elastic and elastic-plastic materials to match those in tensor mechanics. Issue #10972.

2018-04-03 23:44 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/173538/) on 6e8a3a4 wanted to post the following:

Your code requires style changes.  

A patch was auto generated and copied [here](http://mooseframework.inl.gov/docs/PRs/11182/style.patch)  
You can directly apply the patch by running, in the top level of your repository:

`curl -s http://mooseframework.inl.gov/docs/PRs/11182/style.patch | git apply -v`  

Alternatively, with your repository up to date and in the top level of your repository:

`git clang-format 61a49de6b2036a01a45681bf7ccde9a367c325dd`

2018-04-04 00:13 UTC, moosebuild commented
Job [Documentation](https://civet.inl.gov/job/173554/) on 2b93353 wanted to post the following:

View the site [here](http://mooseframework.inl.gov/docs/PRs/11182/site)

This comment will be updated on new commits.

2018-04-04 15:32 UTC, bwspenc requested changes
Looks good, and I'm glad it was this easy to fix it. I would just add the suggested comments to clarify what these strain increments are.

2018-04-04 15:32 UTC, bwspenc commented on modules/solid_mechanics/include/materials/SolidModel.h
>    SymmTensor _strain_increment;
Let's put comments on these three variables to clarify what they are:
/// Total strain increment, including mechanical strains and eigenstrains
SymmTensor _total_strain_increment;
/// Mechanical strain increment, which is the total strain increment minus eigenstrains
SymmTensor _mechanical_strain_increment;
/// In most models, this is the mechanical strain increment, but for inelastic models, it has the inelastic
/// compontent subtracted from it, so it is the elastic strain increment.
SymmTensor _strain_increment;

2018-04-04 17:44 UTC, acasagran commented
@bwspenc Done.

2018-04-04 22:58 UTC, bwspenc approved these changes

2018-04-04 22:58 UTC, merged