[WIP] Adding override parameters to CSVDiff.
idaholab/moose pull request #11251
Opened 2018-04-11 22:47 UTC by acasagran

Adding override parameters and checks to the CSVDiff tester. Issue #11250.

2018-04-11 23:04 UTC, permcody commented
Tag @brianmoose and @milljm - We need to help Al get some testing going with this PR.

2018-04-12 13:34 UTC, brianmoose reviewed
There are some existing tests at the bottom of `CSVDiffer` (that never get run). We can move those into some python unittests and then add some more to test this new functionality.

2018-04-12 13:34 UTC, brianmoose commented on python/TestHarness/CSVDiffer.py
> +    def __init__(self, custom_columns, custom_rel_err, custom_abs_zero, test_dir, out_files, abs_zero=1e-11, relative_error=5.5e-6, gold_dir='gold'):
Can we move these new parameters to the end with a suitable default so existing calls don't break (and nicer calling semantics)? Ie something like:
`def __init__(self, test_dir, out_files, abs_zero=1e-11, relative_error=5.5e-6, gold_dir='gold', custom_columns=[], custom_rel_err=[], custom_abs_zero=[]):`

Maybe put some comments in on how these are to be used...

2018-04-12 13:34 UTC, brianmoose commented on python/TestHarness/CSVDiffer.py
> +            if len(self.custom_columns) > 0:
can just use `if self.custom_columns:`

2018-04-12 13:34 UTC, brianmoose commented on python/TestHarness/CSVDiffer.py
> +                    if len(self.custom_columns) > 0:
same

2018-04-12 13:34 UTC, brianmoose commented on python/TestHarness/CSVDiffer.py
> +                    if len(self.custom_columns) > 0:
same

2018-04-12 13:34 UTC, brianmoose commented on python/TestHarness/CSVDiffer.py
> +        if len(self.custom_columns) > 0:
same

2018-04-12 20:20 UTC, brianmoose requested changes
My other pr #11254 got merged so you will probably need a rebase.
You mentioned you had a failing `TestHarness.tests.diff`? Seems to work for me.

2018-04-16 21:58 UTC, moosebuild commented
Job [Documentation](https://civet.inl.gov/job/177702/) on 0a94393 wanted to post the following:

View the site [here](http://mooseframework.inl.gov/docs/PRs/11251/site)

This comment will be updated on new commits.

2018-04-16 22:06 UTC, brianmoose commented on python/TestHarness/testers/CSVDiff.py
> +#          return False
If you add a `return FileTester.checkRunnable(self, options)` at the end (at the same level as the if) it seems to work for me.
If you uncomment this block, be sure to fix the indentation as well.

2018-04-17 13:09 UTC, milljm commented on python/TestHarness/testers/CSVDiff.py
> +           self.setStatus(self.bucket_skip.status, self.bucket_fail)
Do you mean to skip this test and supply a caveat as to the reason why? Or fail it?

Fail method:
```python
self.setStatus('Override inputs not the same length', self.bucket_fail)
```

Skip method:
```python
self.addCaveats('Override inputs not the same length')
self.setStatus(self.bucket_skip.status, self.bucket_skip)
```

2018-04-17 16:03 UTC, brianmoose submitted a review, later dismissed

2018-04-17 17:18 UTC, acasagran commented
@brianmoose Not sure why the dry_run python test is failing. Did I do something or is it just a glitch?

2018-04-17 17:31 UTC, brianmoose commented
Yeah, we are talking about this.
Now that `checkRunnable` is correctly setting it to failed, dry run seems to handle this a bit differently than what we are used to. Most of the time `checkRunnable` marks them as skipped but yours marks it as failed.
You can either fix the dry run test or break out your `test_csvdiff` test to another test spec file and test that.
@milljm Any other suggestions?

2018-04-17 18:28 UTC, milljm commented
I don't have a solution for checkRunnable to set failed statuses unfortunately.
These two options are clearly in conflict with each other. I am not sure which option we want to supersede the other.

I feel we should error, due to a parsing issue which should never enter the repository, even in the event dry-run normally returns a zero exit code. Which means I think we should adjust the unittest to pass for this one instance (use a different spec file for unittest).

2018-04-17 19:23 UTC, brianmoose approved these changes

2018-04-17 20:14 UTC, merged