Add and fix documentation
idaholab/moose pull request #11322
Opened 2018-04-19 20:38 UTC by dschwen

Refs #7909

2018-04-19 21:11 UTC, moosebuild commented
Job [Documentation](https://civet.inl.gov/job/179542/) on 94eb7ef wanted to post the following:

View the site [here](http://mooseframework.inl.gov/docs/PRs/11322/site)

This comment will be updated on new commits.

2018-04-20 15:35 UTC, laagesen requested changes

2018-04-20 15:35 UTC, laagesen commented on modules/phase_field/doc/content/documentation/modules/phase_field/Phase_Field_Equations.md
> +- [Actions](phase_field/Actions.md) - Simplify the setup of of teh phase field equations using MOOSE actions
typo teh->the

2018-04-20 15:35 UTC, laagesen commented on modules/phase_field/doc/content/documentation/systems/Kernels/CoupledMaterialDerivative.md
> +This kernel addss the first derivative $\frac{\partial F}{\partial v}$ of a given
typo addss->adds

2018-04-20 15:35 UTC, laagesen commented on modules/phase_field/doc/content/documentation/systems/Kernels/SimpleCoupledACInterface.md
> +for the gradient contribution in a couple Allen-Cahn equation.
couple->coupled

2018-04-20 19:28 UTC, dschwen commented
@laagesen seems to be pretty swamped. Would you mind taking a look at this @amjokisaari ? I'd like to get this in to avoid conflicts with other doc work.

2018-04-20 19:29 UTC, dschwen commented
Oh, darn, should have reloaded the page. I didn't see you commented already @laagesen !

2018-04-20 21:00 UTC, laagesen approved these changes

2018-04-20 21:16 UTC, aeslaughter approved these changes

2018-04-20 21:16 UTC, merged