Small generalizations to SingleVariableReturnMappingSolution
idaholab/moose pull request #11349
Opened 2018-04-24 15:22 UTC by tophmatthews

Moved outputIterInfo to private and made it a virtual.
Removed const from initialGuess

Closes #11348

2018-04-24 15:53 UTC, moosebuild commented
Job [Documentation](https://civet.inl.gov/job/180957/) on 937c3f4 wanted to post the following:

View the site [here](http://mooseframework.inl.gov/docs/PRs/11349/site)

This comment will be updated on new commits.

2018-04-24 15:55 UTC, tophmatthews commented
ping @bwspenc, couple of small changes to SingleVariableReturnMappingSolution

2018-04-24 21:04 UTC, bwspenc requested changes

2018-04-25 08:38 UTC, dschwen commented
You mean moved to _protected_?

2018-04-25 13:34 UTC, bwspenc approved these changes

2018-04-25 13:35 UTC, bwspenc commented
@dschwen Yes, it was moved to protected, not private.

2018-04-25 13:35 UTC, merged