Control system re-factor
idaholab/moose pull request #11363
Opened 2018-04-26 18:30 UTC by aeslaughter

2018-04-26 18:31 UTC, aeslaughter commented
@cbolisetti @colejust If creating a pull request counts has having something done, then I lived up to my word that I would have this done by Thursday.

2018-04-26 18:31 UTC, aeslaughter commented
@permcody I will update the Control documentation if you think this design is better.

2018-04-26 18:34 UTC, aeslaughter commented
@permcody I also need to fix execution for threads, I forgot about that.

2018-04-30 19:00 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/182908/) on 444c222 wanted to post the following:

Your code requires style changes.  

A patch was auto generated and copied [here](http://mooseframework.inl.gov/docs/PRs/11363/style.patch)  
You can directly apply the patch by running, in the top level of your repository:

`curl -s http://mooseframework.inl.gov/docs/PRs/11363/style.patch | git apply -v`  

Alternatively, with your repository up to date and in the top level of your repository:

`git clang-format df03b0d4f8e48ca193bdffc9243c21cbf73ff1a4`

2018-04-30 19:51 UTC, andrsd requested changes
A general rant is that everything that derives from a `MooseObject` should say its name in `mooseError`s. This greatly helps users to track down and fix their input file errors. Another benefit is that when people know how to fix their problems, they do not have to email the mailing list...

2018-04-30 19:51 UTC, andrsd commented on framework/include/controls/Control.h
> +//#include "InputParameterWarehouse.h"
Leftover -> remove

2018-04-30 19:51 UTC, andrsd commented on framework/include/controls/Control.h
> +   * @return A copy to the first parameter that matches the given name.
"A copy __of__..."

2018-04-30 19:51 UTC, andrsd commented on framework/include/controls/ControllableItem.h
> +// libMesh includes
cpt. Obvious.

2018-04-30 19:51 UTC, andrsd commented on framework/include/controls/ControllableItem.h
> +// MOOSE includes
cpt. Obvious

2018-04-30 19:51 UTC, andrsd commented on framework/include/controls/ControllableItem.h
> + * input parameter, with differing names.
"...input parameter __s__ with __different__ names."

2018-04-30 19:51 UTC, andrsd commented on framework/include/controls/ControllableItem.h
> + * are generated automatically. If a parameters is controlled on one of these objects it is
"...If a __parameter__ is..."

2018-04-30 19:51 UTC, andrsd commented on framework/include/controls/ControllableItem.h
> +  /*
`/**`

2018-04-30 19:51 UTC, andrsd commented on framework/include/controls/ControllableItem.h
> +  /// Flag for ControlOutput
This does not really help. If the comment was not here, I would be able to get the same information just by reading the code. May be you want to say, for example, under what circumstances is this flag changed, or so.

2018-04-30 19:51 UTC, andrsd commented on framework/include/controls/ControllableParameter.h
> +  // Produce a warning, if the flag is true, when multiple parameters have differing values
"...different..."

2018-04-30 19:51 UTC, andrsd commented on framework/include/controls/ControllableParameter.h
> +    // Loop over all other parameter values
For this comment to be true, the loop would have to start from index 1 which it does not.

But, I do not even see any reason to have this and the above comment in the code. The code is easy to read and understand.

2018-04-30 19:51 UTC, andrsd commented on framework/include/utils/InputParameterWarehouse.h
> +// Google Test
cpt. Obvious

2018-04-30 19:51 UTC, andrsd commented on framework/include/utils/InputParameterWarehouse.h
> +    bool error_on_empty = true);
Weird indentation in case clang-format did not catch this

2018-04-30 19:51 UTC, andrsd commented on framework/include/utils/InputParameterWarehouse.h
> +  /***
`/**`

2018-04-30 19:51 UTC, andrsd commented on framework/include/utils/InputParameterWarehouse.h
> +  /// used to avoid creating multiple copies. All access to the objects are done via
"...access ... __is__ done..."

2018-04-30 19:51 UTC, andrsd commented on framework/include/utils/InputParameterWarehouse.h
> +   * This method is private, because only the factories thatc are creating objects should be
change this back to "that"

2018-04-30 19:51 UTC, andrsd commented on framework/include/utils/InputParameterWarehouse.h
> +   * Returns a ControllableItem iterator, if the name is located.
What is returned if the name is __not__ located?

2018-04-30 19:51 UTC, andrsd commented on framework/src/controls/ControllableItem.C
> +                 " 'and cannot be connected to the parameter (",
The space should be after `'` not in front of it.

2018-04-30 19:51 UTC, andrsd commented on framework/src/outputs/ControlOutput.C
> +    // Extract InputParameter objects from warehouse
cpt. Obvious

2018-04-30 19:51 UTC, andrsd commented on framework/src/outputs/ControlOutput.C
> +    // The stream to build
cpt. Obvious

2018-04-30 19:51 UTC, andrsd commented on unit/src/ControllableItemTest.C
> +// MOOSE includes
cpt. Obvious

2018-04-30 19:51 UTC, andrsd commented on unit/src/ControllableParameterTest.C
> +// MOOSE includes
cpt. Obvious

2018-04-30 19:51 UTC, andrsd commented on unit/src/InputParameterWarehouseTest.C
> +// MOOSE includes
cpt. Obvious

2018-04-30 19:51 UTC, andrsd commented on framework/include/controls/ControllableItem.h
> +   * Return true if the template argument is valid for ALL itemes.
"...items."

2018-04-30 19:51 UTC, andrsd commented on framework/include/controls/ControllableItem.h
> +  */
If this is not needed for anything, then let's remove it.

2018-05-01 14:08 UTC, permcody commented
Actually, I'll go one further than @andrsd's comment. You should be using `paramError()` when possible. I know with the controllable system it's often not, but just skimming through your PR, I do see a few cases where `paramError()` can replace a few of your `mooseErrors()`.

2018-05-02 15:27 UTC, aeslaughter commented
There is only one error in an actual MooseObject (Control), I will update it to include the name. All other errors come from the InputParameterWarehouse, ControllableItem, and ControllableParameter. All of these are stand alone objects, they cannot use paramError or have a name. However, the errors in these objects include the MooseObjectName, which includes the name of the parameter and object when it is output.

2018-05-02 22:48 UTC, permcody commented
@aeslaughter - you missed a few of @andrsd's comments because the got trimmed from this page (you might have to expand them).

2018-05-03 19:58 UTC, aeslaughter commented
I used the web-interface to make the conflict edit, just do a squash when merging this and that commit will go away.

2018-05-04 13:46 UTC, permcody approved these changes

2018-05-04 13:47 UTC, permcody commented
This PR will require an update to Relap-7 and dependent codes. I'll let @andrsd merge when he's ready.

2018-05-04 18:27 UTC, andrsd approved these changes

2018-05-04 18:28 UTC, merged