Test Chorin code in Navier Stokes module
idaholab/moose pull request #11400
Opened 2018-05-01 16:49 UTC by lindsayad

- Input file already existed, but was not getting tested.
- Removes unused options in input file
- Changes comma to space delimiter for `MooseEnum`

Closes #11398

2018-05-01 18:29 UTC, jwpeterson commented
Hmm... looks like the test takes a bit too long in debug mode? Maybe `num_steps = 5`?

2018-05-02 13:58 UTC, permcody requested changes

2018-05-02 13:58 UTC, permcody commented on modules/navier_stokes/src/kernels/INSChorinPredictor.C
> +    _predictor_enum("OLD NEW STAR INVALID", _predictor_type),
This should be fixed. You are reading in a string and then populating an enum. I'd recommend that you setup the enum in the validParams (gives the user a picklist and validates entry), and then get the enum back out like this:
https://github.com/idaholab/moose/blob/devel/framework/src/postprocessors/NumDOFs.C#L32

2018-05-02 13:58 UTC, permcody commented on modules/navier_stokes/src/kernels/INSChorinPredictor.C
> +    _predictor_enum("OLD NEW STAR INVALID", _predictor_type),
Minor: I'd also recommend setting up an enum for the component too, but I'll leave that up to you. We do that in GeneratedMesh. You can also just do a rangedChecked param if you like the integer representations.

2018-05-02 15:13 UTC, permcody approved these changes

2018-05-02 16:45 UTC, merged