Repair MooseDocs --generate
idaholab/moose pull request #11501
Opened 2018-05-10 23:22 UTC by aeslaughter

(closes #11375)

2018-05-10 23:53 UTC, moosebuild commented
Job [Documentation](https://civet.inl.gov/job/189629/) on 22cad3b wanted to post the following:

View the site [here](http://mooseframework.inl.gov/docs/PRs/11501/site)

This comment will be updated on new commits.

2018-05-17 22:09 UTC, dschwen commented
How do I generate framework documentation?!

```
[13][schwd][~/Programs/moose/test/doc]> ./moosedocs.py check --generate
MooseDocs.extensions.appsyntax: Reading MOOSE application syntax.
MooseDocs.extensions.appsyntax: Building MOOSE class database.
MooseDocs.tree.syntax: The /Materials/DerivativeParsedMaterial object is not associated with the MooseTestApp, it is associated with MooseApp. It is not possible to generate stub pages for this object.
CRITICAL:0 ERROR:1 WARNING:0
```

```
[13][schwd][~/Programs/moose/modules/combined/doc]> ./moosedocs.py check --generate
MooseDocs.extensions.appsyntax: Reading MOOSE application syntax.
MooseDocs.extensions.appsyntax: Building MOOSE class database.
MooseDocs.tree.syntax: The /Materials/DerivativeParsedMaterial object is not associated with the CombinedTestApp, it is associated with MooseApp. It is not possible to generate stub pages for this object.
CRITICAL:0 ERROR:1 WARNING:0
```

```
[13][schwd][~/Programs/moose/site]> ./moosedocs.py check --generate
Traceback (most recent call last):
  File "./moosedocs.py", line 20, in <module>
    sys.exit(MooseDocs.moosedocs())
AttributeError: 'module' object has no attribute 'moosedocs'
```

```
[13][schwd][~/Programs/moose/docs/.moosedocs]> ./moosedocs.py check --generate
Traceback (most recent call last):
  File "./moosedocs.py", line 6, in <module>
    import utils
ImportError: No module named utils
```

I'm confused.

2018-05-17 22:12 UTC, dschwen requested changes
Generating stubs for framework objects does not seem to work.

2018-06-27 15:57 UTC, aeslaughter commented
I am adding this to a different PR.

2018-06-27 15:57 UTC, closed without merging