Update moose package versions
idaholab/moose pull request #11516
Opened 2018-05-15 17:12 UTC by milljm

update manual installation instructions, as they were getting
a bit stale.

Removed LLVM instructions from the Manual Installation instructions. I would rather not add that level of complexity to a manual build. GCC is just fine, as most users using the Manual Installation instructions are going to be Linux users (not Darwin users).

Closes #11514

2018-05-15 17:27 UTC, andrsd commented
> Removed LLVM instructions from the Manual Installation instructions.

I sometimes look at those when I build my llvm. Are the gone-gone or can I find them somewhere else?

2018-05-15 17:34 UTC, milljm commented
We can create another page supporting an LLVM build I suppose. If not the only other location LLVM/Clang instructions can be found, are in the [package_builder/build_from_source/template/llvm](https://github.com/idaholab/package_builder/tree/master/build_from_source) repo.

2018-05-15 17:38 UTC, moosebuild commented
Job [Documentation](https://civet.inl.gov/job/190557/) on 5ca22f1 wanted to post the following:

View the site [here](http://mooseframework.inl.gov/docs/PRs/11516/site)

This comment will be updated on new commits.

2018-05-15 18:08 UTC, milljm commented
How and where should we place the following instructions: https://github.com/idaholab/package_builder/blob/master/build_from_source/template/llvm
in our Getting Started pages? Or somewhere else... If anyone has a good spot for these, I will gladly create the documentation page.

2018-05-15 19:05 UTC, milljm commented
Do not merge...
Going to add an LLVM support page.

2018-05-15 19:39 UTC, brianmoose commented
@milljm  #11518 closed this by accident

2018-05-15 21:45 UTC, milljm commented
I still need to run through the instructions for LLVM. There are probably some typos in some of the environmental exports.

2018-05-21 19:46 UTC, brianmoose requested changes

2018-05-21 19:46 UTC, brianmoose commented on framework/doc/content/getting_started/installation/manual_installation_gcc.md
> +!include getting_started/minimum_requirements.md
This was already included at the top

2018-05-22 20:51 UTC, brianmoose approved these changes

2018-05-22 20:52 UTC, merged