Document passing in debugger commands
idaholab/moose pull request #11539
Opened 2018-05-17 20:47 UTC by dschwen

This made parallel debugging a lot more convenient for me.

Refs #11170

2018-05-17 20:50 UTC, permcody approved these changes

2018-05-17 21:10 UTC, permcody requested changes

2018-05-17 21:10 UTC, permcody commented on framework/doc/content/documentation/application_development/debugging.md
> +The above command will set breakpoints that halt on thrown exceptions. Replace `break set -E C++` with `b MPI_Abort` to break on MOOSE errors. The `-o cont` option will automatically run the app afte
s/teh/the/

2018-05-17 21:10 UTC, dschwen commented on framework/doc/content/documentation/application_development/debugging.md
> +The above command will set breakpoints that halt on thrown exceptions. Replace `break set -E C++` with `b MPI_Abort` to break on MOOSE errors. The `-o cont` option will automatically run the app afte
ARGH!!!

2018-05-17 21:12 UTC, permcody approved these changes

2018-05-17 21:19 UTC, dschwen commented
Btw. I put a `sudo` in the docs to appease @friedmud. I run this without it and don't enter a password anywhere. My computer must be sprinkled with magic fairy dust... or the new moose environment package I have installed really does _not_ require sudo anymore... 

¯\_(ツ)_/¯

2018-05-17 21:29 UTC, jwpeterson commented
@dschwen is `which lldb` == `/usr/bin/lldb` for you?

This one does not require me to type my password for some reason...

2018-05-17 21:36 UTC, permcody commented
> This one does not require me to type my password for some reason...

The some reason is because the lldb distributed from Apple prompts you on-screen for the password the very first time you try to run it and then never requires a password again. @milljm hasn't figured out how to make that work for the one he supplies in the MOOSE-package. It would be cool if that did work. I routinely find myself forgetting sudo and then the debugger just doesn't work (even though it runs).

2018-05-17 21:40 UTC, moosebuild commented
Job [Documentation](https://civet.inl.gov/job/191933/) on b986ee6 wanted to post the following:

View the site [here](http://mooseframework.inl.gov/docs/PRs/11539/site)

This comment will be updated on new commits.

2018-05-17 22:34 UTC, merged

2018-05-23 17:08 UTC, permcody commented
It was a joke. We genuinely want to know why that works when it doesn't work for anyone else who's using the new package. That's the place we'd like to reach. 

So are you using our lldb or the system lldb? If you are using system lldb, then that explains it, if you are using our lldb, the next question is, which package number? If it's older, that would also explain it. It was more recently when we started building our own from source. The reason is because while the old lldb mostly works, we found a few specific cases where it fails to print out vector values (I can dig those up if you are interested).

So at the end of the day, I would expect that you would have the same problem as we do if you install the latest version of the package and use our lldb (not the system's). This is the problem we'd like to solve.

2018-05-23 18:14 UTC, dschwen commented
I know @permcody, I'm just giving you a hard time. I also didn't see the comments after yours as I still had the page open in a stale tab.

Check this out:

```
> which lldb
/usr/bin/lldb
```

```
> find /opt/ | grep lldb
>
```

there is no `lldb` in `/opt/moose` or anywhere underneath `/opt`. What's up with that?

> and then never requires a password again.

Yeah, that's my observation. It didn't even ask me after the power outage last week (contrary to Derek's suggestion that mac lldb gets _"elevated privileges and it sticks for a while (I think 30 minutes by default)"_).

2018-05-23 18:16 UTC, milljm commented
I don't know why I didn't see an email until today. Sorry guys...

we need sudo when using our version of lldb (/opt/moose).

...we still need sudo when using Apple's lldb. Sort of. Once you prove to Apple you're a super user (by means of a graphical pop-up prompt which in all intent and purposes _is_ sudo), it doesn't ask again... Ever (which means Its probably tied to the keychain somehow).

Ever since I have been imaging machines for you guys here at the lab, I have always (and trained the other techs here to do the same) added users to the '_developer' group:

```bash
  dscl . -append /Groups/admin GroupMemebership <your user id>  #<-- for sudo
  dscl . -append /Groups/_developer GroupMemebership <your user id> #<-- prevents further need of sudo
```

If you all check your account via `id` you will see you are apart of these groups (namely the _developers group) [You can read about this group, and what it does here](https://forums.developer.apple.com/thread/44758).

2018-05-23 18:16 UTC, permcody commented
```
$ which lldb
/opt/moose/llvm-5.0.1/bin/lldb
```

2018-05-23 18:17 UTC, dschwen commented
Could this be relevant, too?

https://gcc.gnu.org/onlinedocs/gcc-4.8.1/gnat_ugn_unw/Codesigning-the-Debugger.html

2018-05-23 18:27 UTC, milljm commented
@dschwen Unfortunately I don't think we can 're-distribute' the type of certificate required (Mac Development) to tell all machines using our binaries that they do not require sudo to do sudo things on other peoples machines :) That would be awesome.. and scary right?

We do own, and can distribute, a Developer ID Installer certificate. Which tells the OS "Yes. This app is trusted and can be installed... so long as YOU have sudo rights to do so".

Reference: https://help.apple.com/xcode/mac/current/#/dev80c6204ec

2018-05-23 19:00 UTC, milljm commented
I have tried to look into this in the past, and still come to the same conclusion today. That it aint easy.

https://stackoverflow.com/questions/28542582/xcode-custom-lldb-or-adding-args-to-existing-one
http://lldb.llvm.org/build.html#BuildingLldbOnMacOSX

The latter 'Official' instructions from LLVM.org are explaining how to _replace_ a users system (Xcode) LLDB. That is something that will get us murdered by other Mac developers.

While I agree it would be nice to figure out how to run lldb without sudo, I do not know how. Not with out breaking some serious security holes.

2018-05-23 19:23 UTC, friedmud commented
I’m not personally bothered by the sudo - since that’s effectively what’s
happening with Apple’s binary anyway...

I just want our directions to be consistent with our package.

Derek
On Wed, May 23, 2018 at 1:00 PM Jason Miller <notifications@github.com>
wrote:

> I have tried to look into this in the past, and still come to the same
> conclusion today. That it aint easy.
>
>
> https://stackoverflow.com/questions/28542582/xcode-custom-lldb-or-adding-args-to-existing-one
> http://lldb.llvm.org/build.html#BuildingLldbOnMacOSX
>
> The latter 'Official' instructions from LLVM.org are explaining how to
> *replace* a users system (Xcode) LLDB. That is something that will get us
> murdered by other Mac developers.
>
> While I agree it would be nice to figure out how to run lldb without sudo,
> I do not know how. Not with out breaking some serious security holes.
>
> —
> You are receiving this because you were mentioned.
>
>
> Reply to this email directly, view it on GitHub
> <https://github.com/idaholab/moose/pull/11539#issuecomment-391460163>, or mute
> the thread
> <https://github.com/notifications/unsubscribe-auth/AA1JMUrumGaz63zi3cplXBDOu2l0-I2Vks5t1bG2gaJpZM4UDv9B>
> .
>

2018-05-23 19:47 UTC, permcody commented
The only problem with forcing sudo is that it's not clear why it's not working when you forget. I'd rather have a message that says "run with sudo" instead of just not working.

2018-05-23 22:38 UTC, permcody commented
Jason may have solved this - Andrew is reporting that it's working after the newest, newest package and a reboot.

2018-05-24 12:40 UTC, milljm commented
There is more to it than this... no one should be installing the latest package to get access to non-sudo lldb. I still need to work out the installation portion of it all. I am also not sure what happens when we do certain things twice. Or when there is a new version of LLDB being built do we need to re-install the code-signing cert thats in play. There is also the issue with the cert only lasting one year. Can this be extended or, do we even care because we pump out multiple packages a year, etc etc...

But, I did get it working yes.