Make interface kernels work with boundary restricted stateful materials
idaholab/moose pull request #11587
Opened 2018-05-24 18:05 UTC by lindsayad

- Interface kernels are fundamentally different from DG, so should not set `_doing_dg = true`
    - Allows working stateful since not trying to access stateful neighbor material properties that don't exist
- deletes some duplicate code in `ComputeMaterialObjects::onInternalSide`
- Add documentation of interface kernels taken from web-site
- Should remove need to comment out code in #11575

Closes #11258

2018-05-24 18:47 UTC, moosebuild commented
Job [Documentation](https://civet.inl.gov/job/195258/) on 31fe083 wanted to post the following:

View the site [here](http://mooseframework.inl.gov/docs/PRs/11587/site)

This comment will be updated on new commits.

2018-05-24 21:04 UTC, arovinelli commented
Just to le let you know, this also fix #11575

2018-05-24 21:04 UTC, andrsd requested changes

2018-05-24 21:04 UTC, andrsd commented on framework/doc/content/documentation/systems/InterfaceKernels/index.md
> +where $$$D_i$$$ is the diffusion coefficient of specie $$$i$$$ in subdomain $$$i$$$, and $$$c_i$$$ is the concentration of specie $$$i$$$ in subdomain $$$i$$$. An example of this condition is shown i
Moose -> MOOSE

2018-05-24 21:04 UTC, andrsd commented on framework/doc/content/documentation/systems/InterfaceKernels/index.md
> +[coupled_value_coupled_flux.i](https://github.com/idaholab/moose/blob/devel/test/tests/interfacekernels/1d_interface/coupled_value_coupled_flux.i)
@aeslaughter Is this how we link files in the MooseDocs? I thought there was a syntax for this...

2018-05-25 17:08 UTC, aeslaughter requested changes

2018-05-25 17:08 UTC, aeslaughter commented on framework/doc/content/documentation/systems/InterfaceKernels/index.md
> +$$$-D_0 \frac{\partial c_0}{\partial x} = -D_1 \frac{\partial c_1}{\partial x}$$$
```
\begin{equation}

\end{equation}
```

2018-05-25 17:08 UTC, aeslaughter commented on framework/doc/content/documentation/systems/InterfaceKernels/index.md
> +where $$$D_i$$$ is the diffusion coefficient of specie $$$i$$$ in subdomain $$$i$$$, and $$$c_i$$$ is the concentration of specie $$$i$$$ in subdomain $$$i$$$. An example of this condition is shown i
`$D_i$`

2018-05-30 21:58 UTC, permcody commented
@andrsd - Perhaps some of the changes here overlap @arovinelli. We may introduce merge conflicts that will have to be resolved depending on which of these goes in first.

2018-05-31 13:12 UTC, andrsd approved these changes

2018-05-31 13:55 UTC, aeslaughter approved these changes

2018-05-31 13:57 UTC, merged