improve positiveProjectionEigenDecomposition
idaholab/moose pull request #11639
Opened 2018-06-05 16:05 UTC by hugary1995

closes #11638 

Now RankTwoTensor::positiveProjectionEigenDecomposition takes in references to eigval and eigvec and computes them inside. This way, in ComputeIsotropicLinearElasticPFFractureStress the eigenvalue decomposition of mechanical_strain is not solved twice, and efficiency will be improved.

2018-06-05 16:06 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/198347/) on 2ea88c0 wanted to post the following:

Your code requires style changes.  

A patch was auto generated and copied [here](http://mooseframework.inl.gov/docs/PRs/11639/style.patch)  
You can directly apply the patch by running, in the top level of your repository:

`curl -s http://mooseframework.inl.gov/docs/PRs/11639/style.patch | git apply -v`  

Alternatively, with your repository up to date and in the top level of your repository:

`git clang-format 6acf89de14c56d14ed8db75addb9d55c07d87e5e`

2018-06-05 17:09 UTC, moosebuild commented
Job [Documentation](https://civet.inl.gov/job/198368/) on bf4d4bb wanted to post the following:

View the site [here](http://mooseframework.inl.gov/docs/PRs/11639/site)

This comment will be updated on new commits.

2018-06-05 17:11 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/198378/) on a8450b9 wanted to post the following:

Your code requires style changes.  

A patch was auto generated and copied [here](http://mooseframework.inl.gov/docs/PRs/11639/style.patch)  
You can directly apply the patch by running, in the top level of your repository:

`curl -s http://mooseframework.inl.gov/docs/PRs/11639/style.patch | git apply -v`  

Alternatively, with your repository up to date and in the top level of your repository:

`git clang-format 6acf89de14c56d14ed8db75addb9d55c07d87e5e`

2018-06-06 21:17 UTC, jwpeterson requested changes
This looks OK to me but you need to squash everything down to a single commit and write a properly formatted commit message, following [this format](https://chris.beams.io/posts/git-commit/) for example.

2018-06-06 22:48 UTC, jwpeterson commented
> I've squashed those commits. Let me know what else I should do.

The history still isn't right. It contains 2 commits and a merge commit, but you should only see a single commit on this PR.

2018-06-06 23:03 UTC, hugary1995 commented
@jwpeterson Sorry my mistake.. It's one commit now.

2018-06-07 13:59 UTC, jwpeterson approved these changes

2018-06-07 13:59 UTC, merged