TM docs for last of stress update models
idaholab/moose pull request #11657
Opened 2018-06-07 21:39 UTC by sapitts

Adds documentation for the last undocumented radial return stress update material model in tensor mechanics and the last two undocumented TM post processors most likely to use in Bison/Grizzly simulations.

The regolded temperature dependent regression test reflects the change in the aux variable name from `total_strain_yy` to `strain_yy` that occurred when I updated the test to use the tensor mechanics master action.

@gambka would you please review this content before I ask @aeslaughter or @jwpeterson to merge this pull request?

Refs #10516

2018-06-07 21:40 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/199585/) on 607e0af wanted to post the following:

Your code requires style changes.  

A patch was auto generated and copied [here](http://mooseframework.inl.gov/docs/PRs/11657/style.patch)  
You can directly apply the patch by running, in the top level of your repository:

`curl -s http://mooseframework.inl.gov/docs/PRs/11657/style.patch | git apply -v`  

Alternatively, with your repository up to date and in the top level of your repository:

`git clang-format 5a2f370d09c9355f4349998d80817e81cf0234b4`

2018-06-07 22:11 UTC, moosebuild commented
Job [Documentation](https://civet.inl.gov/job/199595/) on 172b52b wanted to post the following:

View the site [here](http://mooseframework.inl.gov/docs/PRs/11657/site)

This comment will be updated on new commits.

2018-06-09 14:39 UTC, gambka requested changes

2018-06-09 14:39 UTC, gambka commented on modules/tensor_mechanics/doc/content/documentation/systems/Materials/TemperatureDependentHardeningStressUpdate.md
> +plasticity class also computes the plastic strain as a stateful material property.
The previous sentence is defines the class I do not think you need to repeat 

> This temperature-dependent hardening isotropic
> plasticity class also computes the plastic strain as a stateful material property

I the sentence would be just fine as `The plastic strain is computed as a stateful material property`

2018-06-09 14:39 UTC, gambka commented on modules/tensor_mechanics/include/materials/TemperatureDependentHardeningStressUpdate.h
> +  ///@{The function names and expressions for hardening as a functio of temperature
functio -> function

2018-06-09 14:39 UTC, gambka commented on modules/tensor_mechanics/include/materials/TemperatureDependentHardeningStressUpdate.h
> +   * of the piecewise hardening function. This hardening temperature faction is
faction -> fraction

2018-06-11 16:17 UTC, sapitts commented
Comments addressed; thanks for the review @gambka

2018-06-11 16:18 UTC, sapitts commented
@aeslaughter or @jwpeterson  would one of you please review this pull request for merging?

2018-06-11 16:18 UTC, jwpeterson approved these changes

2018-06-11 16:18 UTC, merged

2018-06-11 16:20 UTC, sapitts commented
Thanks @jwpeterson