Set up time step limit in DamageBase classes
idaholab/moose pull request #11663
Opened 2018-06-11 14:00 UTC by agiorla

`DamageBase` and derived classes now provides a time step limit as the `UpdateStressBase` classes do.

Closes #11662

2018-06-11 14:01 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/199772/) on 38da880 wanted to post the following:

Your code requires style changes.  

A patch was auto generated and copied [here](http://mooseframework.inl.gov/docs/PRs/11663/style.patch)  
You can directly apply the patch by running, in the top level of your repository:

`curl -s http://mooseframework.inl.gov/docs/PRs/11663/style.patch | git apply -v`  

Alternatively, with your repository up to date and in the top level of your repository:

`git clang-format 5a2f370d09c9355f4349998d80817e81cf0234b4`

2018-06-11 14:10 UTC, agiorla commented
Tagging @bwspenc

2018-06-11 14:32 UTC, moosebuild commented
Job [Documentation](https://civet.inl.gov/job/199788/) on df69d30 wanted to post the following:

View the site [here](http://mooseframework.inl.gov/docs/PRs/11663/site)

This comment will be updated on new commits.

2018-06-12 22:59 UTC, bwspenc requested changes
Looks good -- just one comment.

2018-06-12 22:59 UTC, bwspenc commented on modules/tensor_mechanics/include/materials/DamageBase.h
> +  virtual Real computeTimeStepLimit() = 0;
I would prefer to follow the pattern in StressUpdateBase where we have this implemented in the base class, and it returns `std::numeric_limits<Real>::max()`. That would avoid the issue of temporarily breaking BlackBear.

2018-06-14 21:14 UTC, bwspenc approved these changes

2018-06-14 21:14 UTC, merged