New phase field cracking material that modifies existing stress
idaholab/moose pull request #11686
Opened 2018-06-14 20:12 UTC by tonkmr

I added a new material that implements the phase field cracking model by modifying the existing stress rather than computing the stress and modifying it in the same material. I also improved the Jacobian in the existing implementation of the anisotropic fracture model. 

@jiangwen84 please review.

Closes #11685.

2018-06-14 20:31 UTC, tonkmr commented
@dschwen I would like to modify the TensorMechanicsAction to automatically know which base_name to use for output for the stresses and strains, but I am having trouble figuring out how to accomplish that. Any thoughts?

2018-06-14 20:41 UTC, moosebuild commented
Job [Documentation](https://civet.inl.gov/job/201162/) on dfde0e7 wanted to post the following:

View the site [here](http://mooseframework.inl.gov/docs/PRs/11686/site)

This comment will be updated on new commits.

2018-06-15 16:03 UTC, tonkmr commented
I don't think the app test failure was caused by these changes.

2018-06-15 16:20 UTC, permcody commented
Agreed - @YaqiWang - Have you seen that test fail before?

2018-06-18 14:48 UTC, jiangwen84 commented
@tonkmr Do you think we still need to keep ```ComputeLinearElasticPFFractureStress```? It seems the ```ComputeCrackedStress``` can be used for linear elastic materials too.

2018-06-18 15:35 UTC, YaqiWang commented
Not for a while. But since it is from cpr, I am not very surprised. I guess invalidating it will possible fix.

2018-06-18 18:57 UTC, tonkmr commented
@jiangwen84, I think we do not need ComputeLinearElasticPFFractureStress long term, but I didn't want to eliminate it right away. People may be still using it and there may be more issues we need to address with ComputeCrackedStress. Still, I would be open to deleting it if we want to.

2018-06-18 18:58 UTC, moosebuild commented
Job [App tests](https://civet.inl.gov/job/201460/) on b36ce60 : invalidated by @tonkmr

Module fail not caused by these changes

2018-06-18 20:56 UTC, jiangwen84 reviewed
It looks good to me. I made a few minor comments. Beside, I wonder if it is worth creating a base class from which the ```ComputeCrackedStress```, ```ComputeLinearElasticPFFractureStres``` and ```ComputeIsotropicLinearElasticPFFractureStress``` derive to avoid code and variable duplications.

2018-06-18 20:56 UTC, jiangwen84 commented on modules/tensor_mechanics/include/materials/ComputeCrackedStress.h
> +  const MaterialProperty<RankFourTensor> & _uncracked_Jacobian_mult;
Did you modify the _uncracked_Jacobian_mult? If not, we should delete 'modified here' from the comment.

2018-06-18 20:56 UTC, jiangwen84 commented on modules/tensor_mechanics/src/materials/ComputeCrackedStress.C
> +  // Compute interpolation function and derivatives
I would call it degradation function in the pf fracture context.

2018-06-18 20:56 UTC, jiangwen84 commented on modules/tensor_mechanics/src/materials/ComputeLinearElasticPFFractureStress.C
> +  // Compute interpolation function and derivatives
same here, degradation function

2018-06-19 18:43 UTC, jwpeterson requested changes
Just updating the review status of the PR.

Please address @jiangwen84's comments.

2018-06-19 20:23 UTC, tonkmr commented on modules/tensor_mechanics/src/materials/ComputeCrackedStress.C
> +  Real G0_pos = (stress0pos).doubleContraction(_mechanical_strain[_qp]) / 2.0;
Now that I think about this, shouldn't it be the elastic strain? The elastic strain dotted into the elastic stress is the elastic energy, which is what is causing the brittle fracture. @jiangwen84 what do you think? 

In Pritam's HyperElasticPhaseFieldIsoDamage I think he uses the elastic energy (he calls it _ee).

2018-06-19 21:16 UTC, tonkmr commented
@jiangwen84 I am currently using FiniteStrainPlasticMaterial in my plastic test. Is there a better plastic material that I should be using instead? The solve doesn't seem very robust in that material. I just want what is considered the best yield stress based model.

2018-06-19 23:38 UTC, jiangwen84 commented
@tonkmr , did you try ```IsotropicPlasticityStressUpdate``` together with ```ComputeMultipleInelasticStress```. One test can be found:  tensor_mechanics/test/tests/recompute_radial_return/isotropic_plasticity_finite_strain.i

2018-06-20 20:03 UTC, tonkmr commented
@jiangwen84 those files worked better, thanks. I changed the plasticity test to use those materials. I ran it to full extension of the crack and it worked.

2018-06-20 20:06 UTC, tonkmr commented on modules/tensor_mechanics/include/materials/ComputeCrackedStress.h
> +
I added the comment

2018-06-27 18:08 UTC, tonkmr commented
@jwpeterson I think that this may be ready to be merged. @jiangwen84 seems happy with the current state.

2018-06-27 18:20 UTC, jwpeterson approved these changes

2018-06-27 18:21 UTC, merged