Update some of our more 'dated' instructions
idaholab/moose pull request #11727
Opened 2018-06-20 15:33 UTC by milljm

Update the version of PETSc we were asking users to install.
Update the Windows 10 instructions. As well as alert the user as to its current supportability.

Closes #11724

2018-06-20 15:59 UTC, moosebuild commented
Job [Documentation](https://civet.inl.gov/job/203347/) on 18f6151 wanted to post the following:

View the site [here](http://mooseframework.inl.gov/docs/PRs/11727/site)

This comment will be updated on new commits.

2018-06-20 16:08 UTC, aeslaughter commented
@milljm It would be simple to add an extension to use a file for the PETSc version, then in the markdown you could do something like:

```markdown
This is really cool, the current version of PETSc is !!package petsc!!, ...
```

I can help you get started, the "python/MooseDocs/extensions/acroynm.py" does something similar.

http://www.mooseframework.org/moose/utilities/MooseDocs/extensions/acronym.html#bef8d33b-4513-4f57-b8e8-ddeac08fcccd

2018-06-20 16:10 UTC, aeslaughter commented
You can add this feature to the "package.py" extension.

2018-06-20 16:51 UTC, aeslaughter commented
Another thing, while you are in here, the "getting started" instructions should be moved into modules/combined/doc/content... since they are specific for our website. That is, other applications (BISON, MASTODON, etc.) have their own set of instructions.

This will also allow us to remove the "packages" extension being available by default, since again this is really a MOOSE specific thing.

2018-06-21 22:24 UTC, aeslaughter requested changes
Please add comments to these classes and methods

2018-06-26 15:07 UTC, jwpeterson reviewed
@milljm I just found a few grammatical things I'd like to fix. If it's OK with you I will just push a commit directly to your branch that fixes them up.

2018-06-26 15:07 UTC, jwpeterson commented on framework/doc/content/getting_started/installation/cluster.md
> +Verify that somewhere among all the other modules installed, you see: 'moose-dev-gcc' among them.
typo: remove "among them" from end of sentence.

2018-06-26 15:07 UTC, jwpeterson commented on framework/doc/content/getting_started/installation/windows10.md
> +Begin by performing the following external sets of instructions. Do note, that when it comes time to deciding what distribution of Linux you want, you should try and choose a flavor listed among our
typo: "comes time to deciding" -> "comes time to decide"

2018-06-26 18:49 UTC, aeslaughter approved these changes

2018-06-26 18:49 UTC, merged