PETSc partitioner
idaholab/moose pull request #11741
Opened 2018-06-21 20:24 UTC by fdkong

We are supporting all PETSc external partitioners, `parmetis`, `chaco`, `party` and `ptscotch`.

2018-06-21 20:56 UTC, moosebuild commented
Job [Documentation](https://civet.inl.gov/job/204060/) on 87686c7 wanted to post the following:

View the site [here](http://mooseframework.inl.gov/docs/PRs/11741/site)

This comment will be updated on new commits.

2018-06-25 16:06 UTC, moosebuild commented on libmesh
> +Subproject commit 0bc2791720d43ea8fa8dc3fd5193aacbc1847669
**Caution!** This contains a submodule update

2018-06-25 17:19 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/204487/) on 6df4b6a wanted to post the following:

Your code requires style changes.  

A patch was auto generated and copied [here](http://mooseframework.inl.gov/docs/PRs/11741/style.patch)  
You can directly apply the patch by running, in the top level of your repository:

`curl -s http://mooseframework.inl.gov/docs/PRs/11741/style.patch | git apply -v`  

Alternatively, with your repository up to date and in the top level of your repository:

`git clang-format 5a2f370d09c9355f4349998d80817e81cf0234b4`

2018-06-25 17:23 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/204498/) on c874988 wanted to post the following:

Your code requires style changes.  

A patch was auto generated and copied [here](http://mooseframework.inl.gov/docs/PRs/11741/style.patch)  
You can directly apply the patch by running, in the top level of your repository:

`curl -s http://mooseframework.inl.gov/docs/PRs/11741/style.patch | git apply -v`  

Alternatively, with your repository up to date and in the top level of your repository:

`git clang-format 5a2f370d09c9355f4349998d80817e81cf0234b4`

2018-06-26 14:40 UTC, fdkong commented
@friedmud  Could you consider merging this PR? Then your changes can be based on this. I will add the weighting interface based on your changes.

Please let me know what do you think.

2018-06-28 16:41 UTC, fdkong commented
Waiting for Libmesh update

2018-07-02 16:30 UTC, permcody commented on test/tests/partitioners/petsc_partitioner/tests
> +    requirement = 'MOOSE need more partitioning options'
These are not good requirement statements. I would suggest saying something like this instead.
"MOOSE shall support the <partitioner> mesh partitioner"

Requirements should be specific, testable, unique, etc:
https://qracorp.com/write-clear-requirements-document/

2018-07-02 16:33 UTC, moosebuild commented
All [jobs](https://civet.inl.gov/event/31441/) on 3e19cb6 : invalidated by @fdkong

Libmesh updates are done

2018-07-05 22:07 UTC, friedmud requested changes
Ok - here's a big one: can we rename `PetscMatPartitioner` to just `PetscPartitioner`?  The fact that it's through the "mat" interface in PETSc doesn't mean anything to users of MOOSE... all we care is that we are using PETSc's interface to the partitioners.

2018-07-05 22:07 UTC, friedmud commented on framework/doc/content/documentation/systems/Mesh/Partitioner/PartitionerWeight.md
> +It is a test `partitioner` to demonstrate how to assign the vertex weights and the edge weights to the graph.
Let's remove `vertex` from the documentation... that means "nodes" to many people.  Let's just talk about "element weights" and "side weights" for now.

2018-07-05 22:07 UTC, friedmud commented on framework/doc/content/documentation/systems/Mesh/Partitioner/PartitionerWeight.md
> +The vertex weights (corresponding to word load) could be assigned by overriding `computeElementWeight`. The edge
`word` -> `work`

2018-07-05 22:07 UTC, friedmud commented on test/include/partitioner/PartitionerWeight.h
> +class PartitionerWeight;
Can you please name this `PartitionerWeightTest`... just so that it's clear that it's a "test" object?

2018-07-09 22:06 UTC, fdkong commented
Any more suggestions @friedmud

2018-07-09 22:59 UTC, friedmud approved these changes

2018-07-09 22:59 UTC, merged