Clean up interface diffusion
idaholab/moose pull request #11769
Opened 2018-06-28 21:05 UTC by lindsayad

- Add new `PenaltyInterfaceDiffusion` test object; this object displays second order convergence rates for first order LAGRANGE elements
- Modify existing `InterfaceDiffusion` object so that its more clear what it's trying to do; note that this object combined with a `MatchedValueBC` is convergent but not optimal (e.g. it does not display second order convergence for first order LAGRANGE)
- Update most tests to use the `PenaltyInterfaceDiffusion` object
- Make `1d_interface` test get properties from volume and neighbor materials instead of boundary material. This is more like reality

Closes #11765

2018-06-28 21:35 UTC, moosebuild commented
Job [Documentation](https://civet.inl.gov/job/205820/) on d7c526a wanted to post the following:

View the site [here](http://mooseframework.inl.gov/docs/PRs/11769/site)

This comment will be updated on new commits.

2018-06-29 16:07 UTC, permcody requested changes
Looks good, just add the override keyword in your new test class.

2018-06-29 16:07 UTC, permcody commented on test/include/interfacekernels/PenaltyInterfaceDiffusion.h
> +  virtual Real computeQpResidual(Moose::DGResidualType type);
`override`

2018-07-02 09:12 UTC, mlesueur commented
Thanks for clarifying the way to implement the InterfaceKernels @lindsayad . Thanks to that we managed to fix the jacobians of our custom InterfaceKernel and improve the convergence!

2018-07-02 14:29 UTC, lindsayad commented
Great to hear!

2018-07-02 15:01 UTC, permcody approved these changes

2018-07-02 15:01 UTC, merged