Concentric circle
idaholab/moose pull request #11794
Opened 2018-07-03 17:29 UTC by lee7632

The first draft of a concentric circle mesh C file is completed. It is for generating mesh for typical LWR fuels. 
- Error exists with element 7 and element 8 sharing the same mid point. 
- 'Windmill' approach might need to be applied to produce refine meshes at the corners of the unit cell.

2018-07-03 22:14 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/208011/) on 884de08 wanted to post the following:

Your code requires style changes.  

A patch was auto generated and copied [here](http://mooseframework.inl.gov/docs/PRs/11794/style.patch)  
You can directly apply the patch by running, in the top level of your repository:

`curl -s http://mooseframework.inl.gov/docs/PRs/11794/style.patch | git apply -v`  

Alternatively, with your repository up to date and in the top level of your repository:

`git clang-format 5a2f370d09c9355f4349998d80817e81cf0234b4`

2018-07-05 14:50 UTC, moosebuild commented
Job [Documentation](https://civet.inl.gov/job/208028/) on fbc9e9a wanted to post the following:

View the site [here](http://mooseframework.inl.gov/docs/PRs/11794/site)

This comment will be updated on new commits.

2018-07-05 19:58 UTC, friedmud requested changes
This is a really great start!  But there is definitely more to do before we merge it.

1.  It needs to be generalized.  I understand why you started with fuel/gap/clad... but for this to go into MOOSE it needs to just be a list of radii (an arbitrary number of them)
2.  We need to be able to generate any portion of the unit square.  We started with the quarter cell because it is easiest to think about - but now that you have that going... let's make a `MooseEnum` called `portion` that takes as options: `full top_right top_left bottom_left bottom_right right_half top_half left_half bottom_half`... with the default being `full`.  I've thought a lot about whether we wanted to just generate the quarter and flip/rotate/stitch it - or just generate the piece that we want... and I think that we want to just generate the piece that we want directly.
3.  Volume preserving should be optional (just add a `bool` parameter to turn it on and off)
4.  I can make it segfault with some combinations of options.  For instance: `num_sectors=6, nr=4, num_intervals_unit_cell=3`.  Are these cases that need error messages - or is there a logic problem?

Again: REALLY great start... but let's keep going!

2018-07-05 20:00 UTC, friedmud commented
Oh: one more... it would be great if we could generate this _without_ the moderator... i.e. just the circles.

2018-07-09 14:33 UTC, snschune commented
For completeness for the TODO list:
the current strategy creates large elements in the corners of the square. For LWR analysis these cause a bad representation of the scattering source leading to generally inaccurate answers. French LWR analysis uses a [windmill approach](https://www.researchgate.net/publication/270898751_New_Modelling_of_LWR_Assemblies_using_the_APOLLO2_Code_Package?_sg=GXO4Tyi5AdtuTBR5S5U7n5BMHBFM1V1dure3xv1y-tRwoeuEK-2h10KfrDJlYXAivKBXivKncg). This is fairly LWR specific and might need to go into a derived class in RSN. Even for general purpose the corner elements should be meshed a bit finer.

2018-07-09 16:05 UTC, friedmud commented
@snschune ummm - those "meshes" don't look like meshes.

The current method has a variable size for the elements in the "square" in the middle - so you can make it as fine as you want it.

2018-07-09 16:30 UTC, snschune commented
But it would invariable lead to larger elements in the corner away from the center (if you do the upper right quarter, then the elements adjacent go the upper right corner are large). The windmill approach simply cuts of a triangle adjacent to the corners by a diagonal line - it's the French sanctioned pin cell meshing scheme as far as I know. The depicted meshes may not be a great example though.

2018-07-11 15:07 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/209893/) on a98a0fc wanted to post the following:

Your code requires style changes.  

A patch was auto generated and copied [here](http://mooseframework.inl.gov/docs/PRs/11794/style.patch)  
You can directly apply the patch by running, in the top level of your repository:

`curl -s http://mooseframework.inl.gov/docs/PRs/11794/style.patch | git apply -v`  

Alternatively, with your repository up to date and in the top level of your repository:

`git clang-format 5a2f370d09c9355f4349998d80817e81cf0234b4`

2018-07-11 16:01 UTC, brianmoose commented
@lee7632 An invitation has been sent to you to join the "MOOSE Users" github team. Once you accept the invitation then civet testing will happen automatically without a developer activating them manually.

2018-07-12 23:52 UTC, friedmud commented
@snschune I don't understand what you're saying.  Let's get together and chat about it tomorrow.

2018-07-13 16:01 UTC, lee7632 commented
@friedmud @snschune @YaqiWang 

I have addressed all four comments that Derek made. The windmill approach is currently not added, but adding the moderator part is optional. Users must provide the list of radii. In this way, mesh refinement on particular regions can be easily performed. MooseEnum called portion is added. BoundaryIDs and their names have been fixed. In addition, the volume preserving function is optional. Its documentation will be completed sometime today.

2018-07-13 16:07 UTC, YaqiWang commented
@lee7632 can you attach few sample pictures of this mesh with different numbers of radii and different radii?

2018-07-13 16:33 UTC, brianmoose commented
@lee7632  I resent the invitation, you should get an email. If not, you can try https://github.com/idaholab/moose/invitations or it might show up on https://github.com/idaholab/moose

2018-07-13 16:44 UTC, lee7632 commented
@brianmoose @permcody 
I have received your email and accepted the invitation. Thank you!

2018-07-13 16:48 UTC, lee7632 commented
@YaqiWang Here are some sample pictures. 

![screen shot 2018-07-13 at 9 12 41 am](https://user-images.githubusercontent.com/21227967/42703568-2e852f90-868a-11e8-8a3e-49675d39390d.png)
![screen shot 2018-07-13 at 9 19 21 am](https://user-images.githubusercontent.com/21227967/42703569-2eacc370-868a-11e8-9e6a-3e55501b5f1e.png)
![screen shot 2018-07-13 at 9 21 05 am](https://user-images.githubusercontent.com/21227967/42703570-2ecd1896-868a-11e8-8012-0e8766fdd5fd.png)
![screen shot 2018-07-13 at 9 24 26 am](https://user-images.githubusercontent.com/21227967/42703571-2eeb27a0-868a-11e8-9710-bc002bb765ea.png)
![screen shot 2018-07-13 at 10 29 45 am](https://user-images.githubusercontent.com/21227967/42703572-2f0ea1bc-868a-11e8-8bc0-046d44c4fc64.png)
![screen shot 2018-07-13 at 10 30 26 am](https://user-images.githubusercontent.com/21227967/42703573-2f36e834-868a-11e8-9f8a-665f04645d2a.png)
![screen shot 2018-07-13 at 10 30 52 am](https://user-images.githubusercontent.com/21227967/42703574-2f5ba2be-868a-11e8-8a3c-01a822b952aa.png)
![screen shot 2018-07-13 at 10 31 19 am](https://user-images.githubusercontent.com/21227967/42703576-2fd5a60e-868a-11e8-9e77-d6824a5e8127.png)
![screen shot 2018-07-13 at 10 32 00 am](https://user-images.githubusercontent.com/21227967/42703577-2ff88354-868a-11e8-808f-6ee667082b75.png)
![screen shot 2018-07-13 at 10 32 22 am](https://user-images.githubusercontent.com/21227967/42703578-30143d4c-868a-11e8-8782-38ba5643b9b8.png)
![screen shot 2018-07-13 at 10 35 56 am](https://user-images.githubusercontent.com/21227967/42703579-303448c6-868a-11e8-9fa5-11e9b386e657.png)

2018-07-13 17:02 UTC, YaqiWang commented
Thanks @lee7632 . I see few problems but I also do not have good suggestions on solution:
1. the elements at outer rings have larger area than the inner elements;
2. elements outsize the rings at the square corner have larger areas than others;
3. aspect ratio of elements in thin rings is not good.

@friedmud showed me few nice pin mesh generated by Cubit. Can we somehow borrow the ideas from there to add the nodes? I know it is hard because the arbitrary distribution of radii.

2018-07-13 17:03 UTC, friedmud commented
These look awesome!  Great job!

On Fri, Jul 13, 2018 at 10:48 AM lee7632 <notifications@github.com> wrote:

> @YaqiWang <https://github.com/YaqiWang> Here are some sample pictures.
>
> [image: screen shot 2018-07-13 at 9 12 41 am]
> <https://user-images.githubusercontent.com/21227967/42703568-2e852f90-868a-11e8-8a3e-49675d39390d.png>
> [image: screen shot 2018-07-13 at 9 19 21 am]
> <https://user-images.githubusercontent.com/21227967/42703569-2eacc370-868a-11e8-9e6a-3e55501b5f1e.png>
> [image: screen shot 2018-07-13 at 9 21 05 am]
> <https://user-images.githubusercontent.com/21227967/42703570-2ecd1896-868a-11e8-8012-0e8766fdd5fd.png>
> [image: screen shot 2018-07-13 at 9 24 26 am]
> <https://user-images.githubusercontent.com/21227967/42703571-2eeb27a0-868a-11e8-9710-bc002bb765ea.png>
> [image: screen shot 2018-07-13 at 10 29 45 am]
> <https://user-images.githubusercontent.com/21227967/42703572-2f0ea1bc-868a-11e8-8bc0-046d44c4fc64.png>
> [image: screen shot 2018-07-13 at 10 30 26 am]
> <https://user-images.githubusercontent.com/21227967/42703573-2f36e834-868a-11e8-9f8a-665f04645d2a.png>
> [image: screen shot 2018-07-13 at 10 30 52 am]
> <https://user-images.githubusercontent.com/21227967/42703574-2f5ba2be-868a-11e8-8a3c-01a822b952aa.png>
> [image: screen shot 2018-07-13 at 10 31 19 am]
> <https://user-images.githubusercontent.com/21227967/42703576-2fd5a60e-868a-11e8-9e77-d6824a5e8127.png>
> [image: screen shot 2018-07-13 at 10 32 00 am]
> <https://user-images.githubusercontent.com/21227967/42703577-2ff88354-868a-11e8-808f-6ee667082b75.png>
> [image: screen shot 2018-07-13 at 10 32 22 am]
> <https://user-images.githubusercontent.com/21227967/42703578-30143d4c-868a-11e8-8782-38ba5643b9b8.png>
> [image: screen shot 2018-07-13 at 10 35 56 am]
> <https://user-images.githubusercontent.com/21227967/42703579-303448c6-868a-11e8-9fa5-11e9b386e657.png>
>
> —
> You are receiving this because you were mentioned.
>
>
> Reply to this email directly, view it on GitHub
> <https://github.com/idaholab/moose/pull/11794#issuecomment-404889533>, or mute
> the thread
> <https://github.com/notifications/unsubscribe-auth/AA1JMVT0YWwbYVjOb_Mr4xjMzEzUE_0Mks5uGM9hgaJpZM4VBWeb>
> .
>

2018-07-13 17:37 UTC, YaqiWang commented
Right, we can distribute rings with equal volumes for 1. For 2, we can add more nodes close to the four corners. Aspect ratio is defined as the max ratio of side areas and element volume. If we have thin rings, I guess we have to live with elements with large aspect ratios.

2018-07-13 19:18 UTC, friedmud commented
This code is just want it needs to be.  The connectivity is perfect.  We
can use smoothing algorithms (either explicit - or run something like a
Laplacian smoother) to get better gradation within and without the circles
(which is how Cubit gets to its meshes)... but that's beyond the scope of
this work.

Derek

On Fri, Jul 13, 2018 at 11:37 AM Yaqi <notifications@github.com> wrote:

> Right, we can distribute rings with equal volumes for 1. For 2, we can add
> more nodes close to the four corners. Aspect ratio is defined as the max
> ratio of side areas and element volume. If we have thin rings, I guess we
> have to live with elements with large aspect ratios.
>
> —
> You are receiving this because you were mentioned.
>
>
> Reply to this email directly, view it on GitHub
> <https://github.com/idaholab/moose/pull/11794#issuecomment-404902577>, or mute
> the thread
> <https://github.com/notifications/unsubscribe-auth/AA1JMSn4P-GXiHNc8coqoXy8PsJiDhxiks5uGNrxgaJpZM4VBWeb>
> .
>

2018-07-13 19:37 UTC, YaqiWang commented
It will be nice to have that smoother. Yes setting up connectivity is more important. Can we adjust the connectivity at the four corners so that if the smoother is in place, we will have a better mesh?

2018-07-13 19:44 UTC, friedmud commented
I don't know which corners you're worried about.  Check out the code and play with the options first... even as it is it can generate some nice meshes.

The biggest trouble area is the transition from the square to the circles.  That can be easily smoothed out with a little more work.

2018-07-13 19:46 UTC, YaqiWang commented
I am referring the corners related with the windmill approach @snschune mentioned.

2018-07-13 20:41 UTC, friedmud commented
The "windmill" is not a good idea - it doesn't really solve the large element in the corner problem... and it generates a triangle.

The "windmill" paper is not generating  a mesh - it's solid geometry.

That said: I just tried out the code and we are missing some options @lee7632 .

Look at this mesh:

![screen shot 2018-07-13 at 2 38 38 pm](https://user-images.githubusercontent.com/870705/42712834-633b7314-86aa-11e8-8ab4-8b5d46e86289.png)

Here are some issues:
1.  There is no way to set the size of the inner "square"
2.  There is no way to set the number of "rings" in the inner circle 
3.  We should be able to set the number of rings (radial subdivisions) in each circle - either with equal spacing or equal volume
4.  We should be able to set the number of rings in the outer part (again with equal spacing or equal volume).

Right now you can achieve (3) and (4) manually... but it's a pretty big pain (and you have to do the calculations yourself.  (2) would be possible right now if (1) were implemented... but there should be some shortcut syntax for it anyway.

2018-07-13 20:42 UTC, friedmud commented
BTW: I plan on working on the "smoothing" issue... I talked to @jwpeterson about it this afternoon and it might be possible to do with libMesh's built in smoothers without too much trouble.

2018-07-13 20:57 UTC, YaqiWang commented
How about we do this?
![a](https://user-images.githubusercontent.com/6607496/42713386-8aca560a-86ac-11e8-8174-df7eb3277ed2.png)
Basically add a small square at the corners.

2018-07-13 21:32 UTC, lee7632 commented
@friedmud @YaqiWang @snschune 
Can we have a meeting sometime next week to discuss about the details of the code built and additional modification that I need to make? 
It would be great to have a good plan that everyone can agree on and pursue through.

2018-07-13 22:00 UTC, friedmud commented
Here's what the laplacian smoother does:

![screen shot 2018-07-13 at 4 00 56 pm](https://user-images.githubusercontent.com/870705/42715816-d8221db2-86b5-11e8-8f53-c89f1e904d0b.png)

It look ok - now I just need to make it honor block boundaries...

2018-07-13 22:22 UTC, YaqiWang commented
Some of nodes (hard nodes for preserving volumes) should be never moved, some can. The nodes for the grid inside the innermost ring are the example of soft nodes, but those for drawing the rings are hard. If we have subdivisions on rings, those nodes on the subdivisions are also soft. I still believe we should add few more soft nodes close to the corners to give more freedom to the smoother. The smoothed mesh does look a lot better.

2018-07-13 22:58 UTC, friedmud commented
Right - which why I said: "now I just need to make it honor block boundaries..."

I already did it too.  Here is what the mesh looks like now:

![screen shot 2018-07-13 at 4 58 39 pm](https://user-images.githubusercontent.com/870705/42717401-dea60bb4-86bd-11e8-938d-b356a24a3baa.png)

This will be going in as a new mesh modifier (but we can also just call the function from `ConcentricCircleMesh` too)

2018-07-15 05:04 UTC, YaqiWang commented
This looks really nice! We will see how our discretization error will be and AMG solver will perform on these meshes. If the smoother can do smoothing with volume constraints, we can make all nodes soft. We can create second order mesh easily.

2018-07-15 14:46 UTC, friedmud commented
I agree - Let’s have a meeting to discuss all of this early next week.

2018-07-19 01:07 UTC, lee7632 commented
@friedmud 

Derek, would you mind helping me to solve the problem with 'test debug' ? I am not sure what errors mean. I tried fixing it, but not much progress.

Thank you, 
Jieun

2018-07-24 15:39 UTC, snschune requested changes

2018-07-24 15:39 UTC, snschune commented on framework/src/mesh/ConcentricCircleMesh.C
> +          _radii.at(_radii.size() - 1) +
use `std::vector<T>::back()`

2018-07-24 15:39 UTC, snschune commented on framework/src/mesh/ConcentricCircleMesh.C
> +  int index = 0;
use `unsigned int`, `index >= 0`, right?

2018-07-24 15:39 UTC, snschune commented on framework/src/mesh/ConcentricCircleMesh.C
> +  {
remove brackets in else if branch.

2018-07-24 15:39 UTC, snschune commented on framework/src/mesh/ConcentricCircleMesh.C
> +  {
remove all brackets here.

2018-07-24 15:39 UTC, snschune commented on framework/src/mesh/ConcentricCircleMesh.C
> +    Elem * elem = mesh.add_elem(new Quad4);
good start here with Quad4, but we should also think how to accommodate second order meshes. Any thoughts on that?

2018-07-24 15:39 UTC, snschune commented on framework/src/mesh/ConcentricCircleMesh.C
> +
remove this blank line.

2018-07-24 15:39 UTC, snschune commented on framework/src/mesh/ConcentricCircleMesh.C
> +    {
remove `{`

2018-07-24 15:39 UTC, snschune commented on framework/src/mesh/ConcentricCircleMesh.C
> +    ReplicatedMesh & original_mesh = cast_ref<ReplicatedMesh &>(getMesh());
you already have a reference to the `MeshBase` object called `mesh`. Couldn't you simply have `mesh` be of type `ReplicatedMesh` and cast it first thing in the `build` function. That makes this cast here redundant.

2018-07-24 15:39 UTC, snschune commented on framework/src/mesh/ConcentricCircleMesh.C
> +    mesh.prepare_for_use(false);
also why do you need to call this when you have already called it on the cast `ReplicatedMesh` objects which are the exact same objects?

2018-07-30 17:00 UTC, friedmud commented
Is everyone ok with where this is now?

I think it's good enough to go in like it is.  Anything more that we want to do to it we can do later.

@lee7632 Are you happy with the way it is right now - or do you have something more that you're working on?

2018-07-30 17:06 UTC, snschune commented
👍

2018-07-30 17:37 UTC, lee7632 commented
@ friedmud @snschune @YaqiWang I think its good to go for now! 

I am currently looking into the smoothing technique, refinement on moderator, and some test cases with rattlesnake. I talked to Mark last week, and I might be able to work on it more when I go to Texas A&M. I believe if there are more updates in future, we can incorporate them later. 

Thank you, everyone!

2018-07-30 17:55 UTC, YaqiWang commented
This is very good to me. We definitely can grow this mesh generation capability in MOOSE and applications later. One thing I was thinking is to allow users assign data to elements easily, for example, depletion zone ID. I think if each of this mesher can have an interface like `std::vector<const Elem *> parts(const MultiMooseEnum & allowed_region_identifiers)`. Anyway, this is a really good start point.

2018-07-31 17:46 UTC, friedmud commented
Ok - I've looked through the code and I'll merge it once mooseframework.org comes back online.

2018-08-01 15:07 UTC, friedmud approved these changes

2018-08-01 15:07 UTC, merged