Fix New Intel
idaholab/moose pull request #11837
Opened 2018-07-11 22:47 UTC by friedmud

refs #11835

2018-07-11 23:21 UTC, moosebuild commented
Job [Documentation](https://civet.inl.gov/job/210341/) on c8a8e4d wanted to post the following:

View the site [here](http://mooseframework.inl.gov/docs/PRs/11837/site)

This comment will be updated on new commits.

2018-07-12 22:55 UTC, permcody requested changes

2018-07-12 22:55 UTC, permcody commented on test/tests/outputs/variables/tests
> -    exodiff = 'intel_show_hide_out.e.2.0 intel_show_hide_out.e.2.1'
You need to delete these files too!

2018-07-13 00:49 UTC, friedmud commented
Ok - this can go in.  Feel free to squash merge it 😄

2018-07-13 02:10 UTC, permcody approved these changes

2018-07-13 02:10 UTC, merged

2018-07-13 02:11 UTC, permcody commented
Merged. Retest your other branch