Threaded General User Objects
idaholab/moose pull request #11834
Opened 2018-07-11 21:56 UTC by andrsd

Allow creating threaded copies of general user objects

2018-07-11 21:58 UTC, andrsd commented
@jasondhales Can you test this branch with your BISON changes to see if that fixes the threading problem you described in #11731? Thanks!

2018-07-11 21:59 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/210306/) on 01115f6 wanted to post the following:

Your code requires style changes.  

A patch was auto generated and copied [here](http://mooseframework.inl.gov/docs/PRs/11834/style.patch)  
You can directly apply the patch by running, in the top level of your repository:

`curl -s http://mooseframework.inl.gov/docs/PRs/11834/style.patch | git apply -v`  

Alternatively, with your repository up to date and in the top level of your repository:

`git clang-format dd25ade99989c5f0075b570090833010a1df89af`

2018-07-11 22:59 UTC, jasondhales commented
If I change "threaded_copies" to "threaded" in FluidProperties.C, it works.

2018-07-12 13:52 UTC, andrsd commented
Thanks for catching that!

2018-07-12 14:29 UTC, moosebuild commented
Job [Documentation](https://civet.inl.gov/job/210566/) on c103549 wanted to post the following:

View the site [here](http://mooseframework.inl.gov/docs/PRs/11834/site)

This comment will be updated on new commits.

2018-07-12 15:09 UTC, friedmud requested changes
Some issues with execution

2018-07-12 15:09 UTC, friedmud commented on framework/src/loops/ComputeThreadedGeneralUserObjectsThread.C
> +    const auto & objects = _user_objects.getActiveObjects();
I don't get it - won't this make every thread execute every object?

2018-07-12 15:09 UTC, friedmud commented on framework/src/problems/FEProblemBase.C
> +    Threads::parallel_reduce(EmptyRange(), ctguot);
This is what I was saying we shouldn't do.  You need to actually pass the range of userobjects here to ensure they all get executed.

2018-07-13 14:53 UTC, moosebuild commented
Job [App tests](https://civet.inl.gov/job/210800/) on d732de0 : invalidated by @andrsd

grizzly is up-to-date

2018-07-16 19:14 UTC, rwcarlsen commented
This makes me sad - I will have to rewrite this code and resolve lots of conflicts :-/

2018-07-17 20:32 UTC, jasondhales commented
I'm not sure why this is an issue for @rwcarlsen, but I'm eager to see this merged.

2018-07-18 16:18 UTC, friedmud requested changes
The code here looks good - but I would like to see one test of it.  Can you dream up something that would test this?

2018-07-18 20:44 UTC, andrsd commented
> The code here looks good - but I would like to see one test of it. Can you dream up something that would test this?

I flipped the "threaded" flag for the `FluidProperty` class, so this would be tested whenever we run tests in the `fluid_property` module. If that is not enough, I could build an user object that has some state, so that when it runs threaded and does not have the `threaded` flag on, it would produce a wrong result. If we get "lucky". Other than that, I am not sure how else to test this.

2018-07-18 21:32 UTC, rwcarlsen commented
It would be helpful if we have a reliable test (that fails without this
fix/feature) - if we don't I'm likely to introduce regressions soon when I
rework the code.

On Wed, Jul 18, 2018 at 2:44 PM, David Andrs <notifications@github.com>
wrote:

> The code here looks good - but I would like to see one test of it. Can you
> dream up something that would test this?
>
> I flipped the "threaded" flag for the FluidProperty class, so this would
> be tested whenever we run tests in the fluid_property module. If that is
> not enough, I could build an user object that has some state, so that when
> it runs threaded and does not have the threaded flag on, it would produce
> a wrong result. If we get "lucky". Other than that, I am not sure how else
> to test this.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/idaholab/moose/pull/11834#issuecomment-406068145>, or mute
> the thread
> <https://github.com/notifications/unsubscribe-auth/ABSeSqhK2YuGVjJdBata72T5ip-Pm-k1ks5uH54pgaJpZM4VL6Je>
> .
>

2018-07-18 21:38 UTC, andrsd commented
The problem is that the result would depend on the thread scheduler which we have no control over, so the test could sometimes pass even if there was something wrong :-(

2018-07-18 21:43 UTC, friedmud commented
The thread scheduler doesn't matter here - every threaded object will get
executed... even if not on separate threads.  All we need to verify is that
each one gets executed...

And, yes, I would like a reliable test in moose_test before this can go
in.  It's a tricky enough capability that we need to make sure it stays
working correctly.

On Wed, Jul 18, 2018 at 3:38 PM David Andrs <notifications@github.com>
wrote:

> The problem is that the result would depend on the thread scheduler which
> we have no control over, so the test could sometimes pass even if there was
> something wrong :-(
>
> —
> You are receiving this because you were assigned.
>
>
> Reply to this email directly, view it on GitHub
> <https://github.com/idaholab/moose/pull/11834#issuecomment-406082690>, or mute
> the thread
> <https://github.com/notifications/unsubscribe-auth/AA1JMfo1FVlhePg6xYhsMWv9QkRonJWaks5uH6rqgaJpZM4VL6Je>
> .
>

2018-07-19 18:09 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/213922/) on 2986d2e wanted to post the following:

Your code requires style changes.  

A patch was auto generated and copied [here](http://mooseframework.inl.gov/docs/PRs/11834/style.patch)  
You can directly apply the patch by running, in the top level of your repository:

`curl -s http://mooseframework.inl.gov/docs/PRs/11834/style.patch | git apply -v`  

Alternatively, with your repository up to date and in the top level of your repository:

`git clang-format dd25ade99989c5f0075b570090833010a1df89af`

2018-07-19 18:12 UTC, andrsd commented
(Hopefully) reliable test added...

2018-07-27 14:03 UTC, permcody commented
ping @friedmud? 8 days no action

2018-07-30 15:07 UTC, friedmud requested changes
Issue with interdependencies between these objects.

2018-07-30 15:07 UTC, friedmud commented on framework/src/problems/FEProblemBase.C
> +    Threads::parallel_reduce(ThreadIdRange(thread_ids.begin(), thread_ids.end()), ctguot);
Ok - the new comment is that this doesn't work with interdependencies.  Each ThreadedGeneralUserObject needs its own thread loop - then call `threadjoin()` and `finalize()` on it before starting the next one.

2018-08-08 15:06 UTC, friedmud approved these changes
👍

2018-08-08 15:06 UTC, merged

2018-08-08 15:35 UTC, brianmoose commented
Looks like our minimum clang testing has a problem with this PR: https://civet.inl.gov/job/218243/

2018-08-08 16:31 UTC, andrsd commented
#11961 should fix that