update link to module specific systems pages
idaholab/moose pull request #11899
Opened 2018-07-23 21:23 UTC by sapitts

Minor update to modules to set the docs system list pages to the full app name.

@aeslaughter please review

Closes #11897

2018-07-23 21:55 UTC, moosebuild commented
Job [Documentation](https://civet.inl.gov/job/214759/) on e111e6c wanted to post the following:

View the site [here](http://mooseframework.inl.gov/docs/PRs/11899/site)

This comment will be updated on new commits.

2018-07-23 21:59 UTC, aeslaughter requested changes

2018-07-23 21:59 UTC, aeslaughter commented on modules/tensor_mechanics/doc/content/modules/tensor_mechanics/systems.md
> +!syntax complete group=TensorMechanicsApp
Making it consistent would be great. Thanks for picking up my slack on this.

2018-07-23 22:12 UTC, sapitts commented
@aeslaughter just kidding, we use the `systems.md` pages to create separate pages for the lists in tensor mechanics and phase field. Since these modules have a lot of classes, I think having the separate `systems.md` pages makes more sense

2018-07-24 20:47 UTC, sapitts commented on modules/tensor_mechanics/doc/content/modules/tensor_mechanics/systems.md
> +!syntax complete group=TensorMechanicsApp
@aeslaughter When I went through this commit after your review, I realized that we need the `systems.md` pages in tensor mechanics and phase field to be able to provide the links to the separate systems linking pages.

Is there anything else you'd like me to change with this pr?

2018-07-24 21:00 UTC, aeslaughter approved these changes

2018-07-24 21:00 UTC, merged