Implemented ScalarDamageBase
idaholab/moose pull request #11938
Opened 2018-08-02 14:21 UTC by agiorla

Added a `ScalarDamageBase` class that is inherited by `ScalarMaterialDamage` so that its code can be reused.

Closes #11937

2018-08-02 14:29 UTC, agiorla commented
@bwspenc I am not sure if we should leave the check in `ScalarDamageBase::updateDamage()` (as it is right now) or in `ScalarMaterialDamage::updateQpDamageIndex()`. Maybe we want to avoid doing too many checks for actual damage models such as the Mazars damage model.

2018-08-02 14:43 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/216821/) on 6e6928e wanted to post the following:

Your code requires style changes.  

A patch was auto generated and copied [here](http://mooseframework.inl.gov/docs/PRs/11938/style.patch)  
You can directly apply the patch by running, in the top level of your repository:

`curl -s http://mooseframework.inl.gov/docs/PRs/11938/style.patch | git apply -v`  

Alternatively, with your repository up to date and in the top level of your repository:

`git clang-format af8ec8e6cf0e693710321ab79c1e71a454fff4be`

2018-08-02 15:37 UTC, moosebuild commented
Job [Documentation](https://civet.inl.gov/job/216888/) on 7af9dca wanted to post the following:

View the site [here](http://mooseframework.inl.gov/docs/PRs/11938/site)

This comment will be updated on new commits.

2018-08-02 18:12 UTC, agiorla commented
Tagging @bwspenc

2018-08-06 20:49 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/217530/) on faf0da3 wanted to post the following:

Your code requires style changes.  

A patch was auto generated and copied [here](http://mooseframework.inl.gov/docs/PRs/11938/style.patch)  
You can directly apply the patch by running, in the top level of your repository:

`curl -s http://mooseframework.inl.gov/docs/PRs/11938/style.patch | git apply -v`  

Alternatively, with your repository up to date and in the top level of your repository:

`git clang-format af8ec8e6cf0e693710321ab79c1e71a454fff4be`

2018-08-09 20:01 UTC, permcody commented
This looks ok to me. Commit history is messing though 😉

2018-08-11 00:15 UTC, bwspenc requested changes
Overall, this looks good to me.  Sorry for taking so long to get to this!  I just saw a couple of minor things to address.  If you could take care of those and squash your commits while you are at it, that would be great!

2018-08-11 00:15 UTC, bwspenc commented on modules/tensor_mechanics/include/materials/CombinedScalarDamage.h
> +    Multiply
Would 'Product' be more appropriate?

2018-08-11 00:15 UTC, bwspenc commented on modules/tensor_mechanics/src/materials/CombinedScalarDamage.C
> +                                                     "the damage index ");
Drop trailing space after 'index'

2018-08-13 14:34 UTC, agiorla commented
@bwspenc No problem I know summer can be a busy time. I tried to squash the commits but I'm not sure it really did something...

2018-08-14 01:55 UTC, bwspenc commented on modules/tensor_mechanics/doc/content/source/materials/CombinedScalarDamage.md
> +    \mathrm{Multiply:} & d = & 1 - \Prod\limits_{i=1}^{N} (1 - d_i)
Multiply->Product

2018-08-14 01:59 UTC, bwspenc commented
Just noticed one spot where you missed the name change. To rebase, do something like this:
```
git rebase -i HEAD~12
```
where `HEAD~12` is a commit before your full commit history.  That will put you in an editor, and you'll need to change all of the 'pick' words to 's' after your first commit in the series.  That will squash all of the commits marked 's' into the last one in the list marked 'pick'. You'll have a chance to edit the combined commit message.

It's not strictly necessary to do that, but it's really good to not clutter up the MOOSE commit history with a bunch of work in progress commits. Sometimes it makes sense to break a big change set into multiple commits for various reasons, but they should all be in a clean state.

2018-08-14 13:26 UTC, agiorla commented
@bwspenc Thanks for the help. I had to do the rebase in sudo mode otherwise files were not overwritten properly for some reason, but it seems it worked.

2018-08-15 05:45 UTC, bwspenc approved these changes

2018-08-15 05:45 UTC, merged

2018-08-15 13:36 UTC, agiorla commented
Thanks @bwspenc