give threaded general user objects their own subclass
idaholab/moose pull request #11979
Opened 2018-08-10 17:40 UTC by rwcarlsen

Since a threaded (vs not) object requires very specific code handling,
we do not generally want the ability for objects to be dynamically
toggled between threaded vs not handling - this could easily result in
unintentional, subtle errors.  Also, the new general warehouse handling
of user objects will be much better served by this as an explicit
separate class.

ref #11834

2018-08-10 20:20 UTC, friedmud commented on framework/include/userobject/GeneralUserObject.h
> +class ThreadedGeneralUserObject : public GeneralUserObject
Please put this in its own file

2018-08-10 20:22 UTC, friedmud requested changes
Just the one change

2018-08-10 21:44 UTC, rwcarlsen commented on framework/include/userobject/GeneralUserObject.h
> +class ThreadedGeneralUserObject : public GeneralUserObject
done

2018-08-10 21:45 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/219701/) on 5c7df5a wanted to post the following:

Your code requires style changes.  

A patch was auto generated and copied [here](http://mooseframework.inl.gov/docs/PRs/11979/style.patch)  
You can directly apply the patch by running, in the top level of your repository:

`curl -s http://mooseframework.inl.gov/docs/PRs/11979/style.patch | git apply -v`  

Alternatively, with your repository up to date and in the top level of your repository:

`git clang-format 9d425eb47c0ca0d58545d9bc9b8d8ed48df37e22`

2018-08-10 22:44 UTC, friedmud approved these changes

2018-08-10 22:44 UTC, friedmud commented
Looks good set to automerge...

On Fri, Aug 10, 2018 at 3:45 PM MOOSE Build <notifications@github.com>
wrote:

> Job Precheck <https://civet.inl.gov/job/219701/> on 5c7df5a
> <https://github.com/idaholab/moose/commit/5c7df5a3e77dfdb73e921b4324e947d95067a785>
> wanted to post the following:
>
> Your code requires style changes.
>
> A patch was auto generated and copied here
> <http://mooseframework.inl.gov/docs/PRs/11979/style.patch>
> You can directly apply the patch by running, in the top level of your
> repository:
>
> curl -s http://mooseframework.inl.gov/docs/PRs/11979/style.patch | git
> apply -v
>
> Alternatively, with your repository up to date and in the top level of
> your repository:
>
> git clang-format 9d425eb47c0ca0d58545d9bc9b8d8ed48df37e22
>
> —
> You are receiving this because your review was requested.
>
>
> Reply to this email directly, view it on GitHub
> <https://github.com/idaholab/moose/pull/11979#issuecomment-412214860>, or mute
> the thread
> <https://github.com/notifications/unsubscribe-auth/AA1JMe20TyExQMMhcdO_QaoxY26oYcFrks5uPf8JgaJpZM4V4kTl>
> .
>

2018-08-13 14:41 UTC, andrsd approved these changes

2018-08-13 14:41 UTC, merged

2018-08-13 14:59 UTC, brianmoose commented
A bunch of min clang problems: https://civet.inl.gov/job/219922/