Improve MooseDocs docs
idaholab/moose pull request #11991
Opened 2018-08-14 13:30 UTC by aeslaughter

closes #11948

2018-08-14 13:31 UTC, aeslaughter commented
@brianmoose Can you add MooseDocs testing to the stork target, please.

2018-08-14 14:27 UTC, moosebuild commented
Job [Documentation](https://civet.inl.gov/job/220458/) on c0503be wanted to post the following:

View the site [here](http://mooseframework.inl.gov/docs/PRs/11991/site)

This comment will be updated on new commits.

2018-08-14 16:37 UTC, brianmoose requested changes

2018-08-14 16:37 UTC, brianmoose commented on framework/doc/content/utilities/MooseDocs/config.md
> +files are combined in the destination directory (
weird (

2018-08-14 16:37 UTC, brianmoose commented on framework/doc/content/utilities/MooseDocs/setup.md
> +pip install --user pybtex livereload pylatexenc anytree pandas
Do we need to use `livereload==2.5.1`?

2018-08-15 14:00 UTC, brianmoose approved these changes

2018-08-15 14:00 UTC, merged

2018-08-15 14:06 UTC, dschwen commented
A cool improvement would also be to have a working `./moosedocs.py check --generate` (#11375)... :-)