Add capability to group variables for ReferenceResidualProblem
idaholab/moose pull request #12054
Opened 2018-08-28 21:31 UTC by jiangwen84

closes Ref #12053

2018-08-28 22:04 UTC, moosebuild commented
Job [Documentation](https://civet.inl.gov/job/224887/) on bb46401 wanted to post the following:

View the site [here](http://mooseframework.inl.gov/docs/PRs/12054/site)

This comment will be updated on new commits.

2018-08-29 19:54 UTC, bwspenc requested changes
Just some minor stuff.  Overall, I really like this!

2018-08-29 19:54 UTC, bwspenc commented on modules/contact/include/ReferenceResidualProblem.h
> +  std::vector<std::string> _group_solnVarNames;
Follow the MOOSE naming conventions for member variables (something like `_group_soln_var_names`),

2018-08-29 19:54 UTC, bwspenc commented on modules/contact/include/ReferenceResidualProblem.h
> +  std::vector<std::string> _group_solnVarNames;
It looks like we weren't following those conventions on some of the other variables before (like _solnVarNames). It probably makes sense to go ahead and change those as well.

2018-08-29 19:54 UTC, bwspenc commented on modules/contact/src/ReferenceResidualProblem.C
> +                 "variables to different groups.");
Change this message to:
```
A variable cannot be included in multiple groups in the 'group_variables' parameter

2018-08-29 19:54 UTC, bwspenc commented on modules/contact/src/ReferenceResidualProblem.C
> +        mooseError("For group_variables parameter, variable ",
For group_variables' parameter -> In the 'group_variables parameter

2018-08-29 19:54 UTC, bwspenc commented on modules/contact/src/ReferenceResidualProblem.C
> +                     " tries to group standard variables with scalar variables.");
"In the 'group_variables' parameter, standard variables and scalar variables are grouped together in group ", i

2018-08-29 19:54 UTC, bwspenc commented on modules/contact/src/ReferenceResidualProblem.C
> +    _group_resid[_variable_group_num_index[i]] += pow(_resid[i], 2);
Use something like `libMesh::Utility::pow<2>(_resid[i])` everywhere you are raising things to integer powers.

2018-08-29 21:04 UTC, bwspenc requested changes
Almost there.  Just change the wording on the requirements as noted.

2018-08-29 21:04 UTC, bwspenc commented on modules/combined/test/tests/reference_residual/tests
> +      requirement = 'For ReferenceResidualProblem, groups two standard variables and two scalar variables, respectively.'
A little rewording on these requirements:

The reference residual based convergence checking system shall permit the norm of independent groups of either scalar and standard solution variables to be compared against reference quantities provided through the norms of groups of auxiliary variables.

2018-08-29 21:04 UTC, bwspenc commented on modules/combined/test/tests/reference_residual/tests
> +      requirement = 'Test error for ReferenceResidualProblem, variable disp_x is duplicated in the group_variables.'
The reference residual based convergence checking system shall generate an error if a variable is added to multiple groups.

2018-08-29 21:04 UTC, bwspenc commented on modules/combined/test/tests/reference_residual/tests
> +      requirement = 'Test error for ReferenceResidualProblem, variable disp_x is not grouped with other variable.'
The reference residual based convergence checking system shall generate an error if a group containing a single variable is defined.

2018-08-29 21:18 UTC, bwspenc approved these changes

2018-08-30 20:57 UTC, jiangwen84 commented
ReferenceResidualProblem will not improve the convergence but just give a better way (for some cases) to check the convergence. This PR just adds a new capability to group several variables together, such as group scalar variables or all the displacements.

2018-09-04 16:09 UTC, merged