Implement APIs in ReferenceResidualProblem to add variables and group_variables
idaholab/moose pull request #12069
Opened 2018-09-04 19:00 UTC by jiangwen84

closes #12068

2018-09-04 19:43 UTC, moosebuild commented
Job [Documentation](https://civet.inl.gov/job/226243/) on 5c26c30 wanted to post the following:

View the site [here](http://mooseframework.inl.gov/docs/PRs/12069/site)

This comment will be updated on new commits.

2018-09-04 20:37 UTC, jiangwen84 commented
@bwspenc I have another PR in BISON. Maybe you want to take a look at that too.

2018-09-06 04:20 UTC, bwspenc requested changes

2018-09-06 19:05 UTC, jiangwen84 commented
@bwspenc comments are addressed. thanks!

2018-09-06 19:51 UTC, bwspenc approved these changes

2018-09-06 19:52 UTC, bwspenc approved these changes
Looks good to me.  It just needs to pass the tests. Those failures look unrelated to your code, so whenever that gets sorted out, this can be merged.

2018-09-08 01:22 UTC, merged