Update dynamics documentation #12087
idaholab/moose pull request #12088
Opened 2018-09-06 16:56 UTC by sveerara

Moved dynamics documentation from mooseframework wiki page to the new documentation system. 

Fixed bug in DynamicStressDivergenceTensors jacobian.

closes #12087 and #9431.

2018-09-06 16:57 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/227848/) on 9bff217 wanted to post the following:

Your code requires style changes.  

A patch was auto generated and copied [here](http://mooseframework.inl.gov/docs/PRs/12088/style.patch)  
You can directly apply the patch by running, in the top level of your repository:

`curl -s http://mooseframework.inl.gov/docs/PRs/12088/style.patch | git apply -v`  

Alternatively, with your repository up to date and in the top level of your repository:

`git clang-format 74e2d25fd927c4bfe28871af9263a28f4a74b37a`

2018-09-06 17:58 UTC, moosebuild commented
Job [Documentation](https://civet.inl.gov/job/227872/) on 136c88e wanted to post the following:

View the site [here](http://mooseframework.inl.gov/docs/PRs/12088/site)

This comment will be updated on new commits.

2018-09-06 18:16 UTC, bwspenc requested changes
Looks good.  Just a few minor things to touch up.

2018-09-06 18:16 UTC, bwspenc commented on modules/tensor_mechanics/doc/content/modules/tensor_mechanics/Dynamics.md
> +In the moose framework, the mass and stiffness matrices are not explicitly calculated. Only the residuals are calculated. To get the residual, the equation of motion (with Rayleigh damping and HHT ti
moose -> MOOSE

2018-09-06 18:16 UTC, bwspenc commented on modules/tensor_mechanics/doc/content/modules/tensor_mechanics/Dynamics.md
> +Dynamic problems like response of a multi degree of freedom structure to external forcing and wave propagation in a medium can also be solved using the Tensor Mechanics module.
'like response' -> 'like the response'

2018-09-06 18:16 UTC, bwspenc commented on modules/tensor_mechanics/doc/content/modules/tensor_mechanics/Dynamics.md
> +The next two terms to the left involving $\sigma$ are calculated in DynamicStressDivergenceTensors.C.
Replace this with a link: `[DynamicStressDivergenceTensors](/DynamicStressDivergenceTensors.md)`

2018-09-06 20:12 UTC, sveerara commented
@bwspenc , thanks for reviewing the PR. I have addressed your comments. I have also added an additional warning stating that DynamicStressDivergenceTensors uses undisplaced mesh whereas InertialForce kernel and Pressure BC use the displaced mesh. 

Bighorn, mammoth and rattlesnake tests are failing. I don't think those tests are failing because of this PR.

2018-09-08 01:03 UTC, bwspenc approved these changes

2018-09-10 21:33 UTC, moosebuild commented
Job [Private App tests](https://civet.inl.gov/job/227983/) on 769263c : invalidated by @permcody

Apps updated

2018-09-10 22:05 UTC, merged