Add design, requirements and issue to all the beam tests #9638
idaholab/moose pull request #12120
Opened 2018-09-12 22:39 UTC by sveerara

2018-09-12 23:14 UTC, moosebuild commented
Job [Documentation](https://civet.inl.gov/job/230434/) on 724b72b wanted to post the following:

View the site [here](http://mooseframework.inl.gov/docs/PRs/12120/site)

This comment will be updated on new commits.

2018-09-12 23:33 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/230489/) on 19b8281 wanted to post the following:

Your code requires style changes.  

A patch was auto generated and copied [here](http://mooseframework.inl.gov/docs/PRs/12120/style.patch)  
You can directly apply the patch by running, in the top level of your repository:

`curl -s http://mooseframework.inl.gov/docs/PRs/12120/style.patch | git apply -v`  

Alternatively, with your repository up to date and in the top level of your repository:

`git clang-format 0766f263fc902818829f1d43b6a4a8108a7c6ffd`

2018-09-12 23:36 UTC, sveerara commented
@bwspenc and @aeslaughter, please review this PR when you get a chance. This PR covers tests within beam and dynamics folders.

2018-09-12 23:56 UTC, bwspenc requested changes

2018-09-12 23:56 UTC, bwspenc commented on modules/tensor_mechanics/test/tests/beam/action/tests
> +
@aeslaughter Does it work if we split these across multiple lines with quotes around them like this (and is that acceptable formatting)?

2018-09-12 23:56 UTC, bwspenc commented on modules/tensor_mechanics/test/tests/beam/action/tests
> +    requirement = "The LineElementAction class shall correctly create the beam/truss input blocks"
The LineElementAction class shall correctly create the objects required for a mechanics simulation using beam or truss elements.

2018-09-12 23:56 UTC, bwspenc commented on modules/tensor_mechanics/test/tests/beam/action/tests
> +
```
The LineElementAction class shall produce an error if the number of variables listed in the `save_in` parameter differs from the number of displacement variables.

2018-09-12 23:56 UTC, bwspenc commented on modules/tensor_mechanics/test/tests/beam/action/tests
> +                  " variables differs from the number of displacement variables."
```
The LineElementAction class shall produce an error if the number of variables listed in the `diag_save_in` parameter differs from the number of displacement variables.

2018-09-12 23:56 UTC, bwspenc commented on modules/tensor_mechanics/test/tests/beam/action/tests
> +                  " differs from the number of displacements variables."
displacements->displacement

2018-09-12 23:56 UTC, bwspenc commented on modules/tensor_mechanics/test/tests/beam/action/tests
> +    requirement = "The LineElementAction class shall produce an error if dynamic simulation"
This makes it sound like there's a 'dynamic simulation' input parameter, but there isn't one.

2018-09-12 23:56 UTC, bwspenc commented on modules/tensor_mechanics/test/tests/beam/dynamic/tests
> +    requirement = "The dynamic system shall correctly predict the natural frequencies"
The mechanics system shall correctly predict the natural frequencies of an Euler-Bernoulli beam modeled using beam elements with consistent mass/inertia.

2018-09-12 23:56 UTC, bwspenc commented on modules/tensor_mechanics/test/tests/beam/dynamic/tests
> +    requirement = "The dynamic system shall correctly predict the natural frequencies"
I think I would change all of these to refer to the 'mechanics' system, rather than the dynamic system.

2018-09-12 23:56 UTC, bwspenc commented on modules/tensor_mechanics/test/tests/beam/dynamic/tests
> +                  " of a Timoshenko beam with consistent mass/inertia."
The mechanics system shall correctly predict the natural frequencies of a Timoshenko beam modeled using beam elements with consistent mass/inertia.

2018-09-12 23:56 UTC, bwspenc commented on modules/tensor_mechanics/test/tests/beam/dynamic/tests
> +                  " and numerical damping induced by HHT time integration."
The mechanics system shall correctly predict the natural frequencies of an Euler-Bernoulli beam modeled using beam elements in the presence of Rayleigh damping and numerical damping introduced by Hilber-Hughes-Taylor (HHT) time integration.

2018-09-12 23:56 UTC, bwspenc commented on modules/tensor_mechanics/test/tests/beam/dynamic/tests
> +                  " at the ends."
The mechanics system shall correctly predict the natural frequencies of a massless Euler-Bernoulli beam modeled using beam elements with a nodal masses placed at the ends.

2018-09-12 23:56 UTC, bwspenc commented on modules/tensor_mechanics/test/tests/beam/dynamic/tests
> +                  " the location and values of the masses are provided using a csv file."
dynamic -> mechanics, beam -> 'beam modeled using beam elements'

2018-09-12 23:56 UTC, bwspenc commented on modules/tensor_mechanics/test/tests/beam/dynamic/tests
> +                  " applied to the beam."
The dynamic system shall correctly model the response of a beam modeled using beam elements when gravitational force (proportional to nodal mass) is applied to the beam.

2018-09-12 23:56 UTC, bwspenc commented on modules/tensor_mechanics/test/tests/beam/dynamic/tests
> +                  " provided using a csv file."
dynamic -> mechanics, 'the beam's response' -> 'the response of a beam modeled using beam elements'

2018-09-12 23:56 UTC, bwspenc commented on modules/tensor_mechanics/test/tests/beam/dynamic/tests
> +                  " velocities and accelerations required for a dynamic beam simulation."
... simulation using beam elements.

2018-09-12 23:56 UTC, bwspenc commented on modules/tensor_mechanics/test/tests/beam/dynamic/tests
> +                  " in the presence of nodal mass, nodal inertia and Rayleigh damping."
dynamic -> mechanics, 'the beam's response' -> 'the response of a beam modeled using beam elements'

2018-09-12 23:56 UTC, bwspenc commented on modules/tensor_mechanics/test/tests/beam/dynamic/tests
> +                  " in the form of HHT time integration."
'... beam simulation using beam elements and a consistent ...'

2018-09-12 23:56 UTC, bwspenc commented on modules/tensor_mechanics/test/tests/beam/dynamic/tests
> +    design = "C0TimoshenkoBeam.md LineElementMaster/index.md"
'... beam simulation using beam elements and nodal ...'

2018-09-12 23:56 UTC, bwspenc commented on modules/tensor_mechanics/test/tests/beam/dynamic/tests
> +                  " of a cantilever beam with a mass at the free end."
dynamic -> mechanics, beam -> 'beam modeled using beam elements'

2018-09-12 23:56 UTC, bwspenc commented on modules/tensor_mechanics/test/tests/beam/dynamic/tests
> +                  " provided for rotations differ that provided for displacements."
'number of' -> 'number of variables', differ -> 'differs from'

2018-09-12 23:56 UTC, bwspenc commented on modules/tensor_mechanics/test/tests/beam/dynamic/tests
> +                  " the user provided nodal inertia is not positive definite."
remove a 'the'

2018-09-12 23:56 UTC, bwspenc commented on modules/tensor_mechanics/test/tests/beam/dynamic/tests
> +                  " options are set to true."
Put backticks around parameter names. The system lets you do that and they show up in the typewriter font.

2018-09-12 23:56 UTC, bwspenc commented on modules/tensor_mechanics/test/tests/beam/static/tests
> +                  " deformations in the y direction."
Add something like 'beam modeled using beam elements' to all of these.

2018-09-12 23:56 UTC, bwspenc commented on modules/tensor_mechanics/test/tests/beam/static/tests
> +    requirement = "The LineElementAction class shall accruately create the input blocks"
'create the input blocks' -> 'create the objects', 'accruately'->'accurately'

2018-09-12 23:56 UTC, bwspenc commented on modules/tensor_mechanics/test/tests/beam/static/tests
> +    requirement = "The LineElementAction class shall accurately create the input blocks"
'create the input blocks' -> 'create the objects'

2018-09-12 23:56 UTC, bwspenc commented on modules/tensor_mechanics/test/tests/dynamics/acceleration_bc/tests
> +                  " the acceleration at the given boundary."
the the

2018-09-12 23:56 UTC, bwspenc commented on modules/tensor_mechanics/test/tests/dynamics/prescribed_displacement/tests
> +                  " the displacement at the given boundary."
the the

2018-09-12 23:56 UTC, bwspenc commented on modules/tensor_mechanics/test/tests/dynamics/prescribed_displacement/tests
> +                  " the first few time steps to equilibrate the system under gravity"
'the first few time steps' -> 'a small number of time steps'

2018-09-12 23:56 UTC, bwspenc commented on modules/tensor_mechanics/test/tests/dynamics/rayleigh_damping/tests
> +                  " damping resulting from HHT time integration."
HHT -> Hilber-Hughes-Taylor (HHT)

2018-09-12 23:56 UTC, bwspenc commented on modules/tensor_mechanics/test/tests/dynamics/rayleigh_damping/tests
> +                  " damping resulting from HHT time integration."
dynamic -> mechanics

2018-09-12 23:56 UTC, bwspenc commented on modules/tensor_mechanics/test/tests/dynamics/rayleigh_damping/tests
> +    requirement = "The dynamic system shall accurately predict the dynamic response"
dynamic -> mechanics

2018-09-12 23:56 UTC, bwspenc commented on modules/tensor_mechanics/test/tests/dynamics/time_integration/tests
> +                  " of a linear elastic system using HHT time integration."
dynamic->mechanics, spell out HHT

2018-09-12 23:56 UTC, bwspenc commented on modules/tensor_mechanics/test/tests/dynamics/time_integration/tests
> +                  " of a linear elastic system using Newmark time integration."
dynamics->mechanics

2018-09-12 23:56 UTC, bwspenc commented on modules/tensor_mechanics/test/tests/dynamics/wave_1D/tests
> +                   " from HHT time integration."
dynamic->mechanics, spell out HHT

2018-09-12 23:56 UTC, bwspenc commented on modules/tensor_mechanics/test/tests/dynamics/wave_1D/tests
> +                   " damping."
dynamic->mechanics

2018-09-12 23:56 UTC, bwspenc commented on modules/tensor_mechanics/test/tests/dynamics/wave_1D/tests
> +                   " numerical damping resulting from HHT time integration."
dynamic->mechanics, spell out HHT

2018-09-12 23:56 UTC, bwspenc commented on modules/tensor_mechanics/test/tests/dynamics/wave_1D/tests
> +                   " in a linear elastic material with Rayleigh damping."
dynamic->mechanics

2018-09-13 21:15 UTC, bwspenc approved these changes
Looks good.  Thanks for making those changes!

2018-09-13 21:15 UTC, bwspenc commented on modules/tensor_mechanics/test/tests/beam/action/tests
> +
We talked about this, and we can do this either way at this point. There's an input file formatter in the works that will reformat these all according to established style guides pretty soon anyway, so no need to worry about this.

2018-09-13 21:15 UTC, merged