Some tensor mechanics test requirements, issues, and design page links
idaholab/moose pull request #12122
Opened 2018-09-12 22:48 UTC by sapitts

Includes the sqa documentation for the design and requirements for a small set of isotropic elastic tensor mechanics tests.

Refs #9638

2018-09-12 22:50 UTC, sapitts commented
pinging @aeslaughter and @bwspenc for review please

2018-09-13 00:02 UTC, bwspenc commented on modules/tensor_mechanics/test/tests/1D_spherical/tests
> +    requirement = 'The ComputeRSphericalSmallStrain class, called through the TensorMechanicsMaster action, shall find the total linearized solution for the displacement of a solid isotropic elastic
This seems to me like we're getting a little too specific with the equation. I'd suggest something like this:

The mechanics system shall be capable of accurately computing the displacement of a thick-walled sphere with a pressure applied to the outer surface using a 1D spherical symmetric representation with elastic, total small strain assumptions.

2018-09-13 14:26 UTC, bwspenc requested changes

2018-09-13 14:26 UTC, bwspenc commented on modules/tensor_mechanics/test/tests/anisotropic_patch/tests
> +    requirement = 'The ComputeLinearElasticStress class shall compute and output the xx, yy, zz, xy, yz, and zx stress components on an irregular hex mesh compused of seven elements which form a unit
That comment in the .i file doesn't really say what this is testing.  I'd go with something like this:

The mechanics system shall be capable of accurately computing the elastic response of an anisotropic elastic material where 9 components of a symmetric elasticity tensor are specified on an irregular patch of elements with total small strain assumptions.

2018-09-13 14:26 UTC, bwspenc commented on modules/tensor_mechanics/test/tests/finite_strain_elastic/tests
> +    reuirement = 'The ComputeFiniteStrainElasticStress class shall compute the elastic stress for a finite strain formulation found with the Taylor expansion from Rashid, Numerical Methods in Enginee
I think I'd  just refer to the reference as 'Rashid (1993)' to keep it shorter.

2018-09-13 14:26 UTC, bwspenc commented on modules/tensor_mechanics/test/tests/1D_spherical/tests
> +    requirement = 'The ComputeRSphericalIncrementalStrain class, called through the TensorMechanicsMaster action, shall find the linearized incremental strain displacement of a solid isotropic elasti
similar deal on these other ones

2018-09-13 14:26 UTC, bwspenc commented on modules/tensor_mechanics/test/tests/finite_strain_elastic/tests
> +    requirement = 'The ComputeFiniteStrainElasticStress class shall compute the elastic stress based on a finite strain fomulation and then follow the stress as the mesh is rotated 90 degrees in acco
Shorten the reference to 'Kamojjala et al. (2015)'

2018-09-13 14:26 UTC, bwspenc commented on modules/tensor_mechanics/test/tests/finite_strain_elastic/tests
> +    requirement = 'The ComputeFiniteStrainElasticStress class shall compute the elastic stress based on a finite strain fomulation and then follow the stress as the mesh is rotated 90 degrees in acco
same deal with the reference

2018-09-13 14:26 UTC, bwspenc commented on modules/tensor_mechanics/test/tests/finite_strain_elastic/tests
> +    reuirement = 'The ComputeFiniteStrainElasticStress class shall compute the elastic stress for a finite strain formulation found with the eigen-strain solution on a unit 3D cube in a Cartesian sys
'found with the eigen-strain solution' -> 'using a direct eigensolution to perform the polar decomposition of stretch and rotation'

2018-09-13 14:26 UTC, bwspenc commented on modules/tensor_mechanics/test/tests/finite_strain_elastic/tests
> +    requirement = 'The ComputeFiniteStrainElasticStress class shall compute the elastic stress for a finite strain formulation found with the eigen-strain solution on a unit 3D cube in a Cartesian sy
same deal with the eigen-strain text replacement

2018-09-13 14:26 UTC, bwspenc commented on modules/tensor_mechanics/test/tests/finite_strain_elastic/tests
> +    requirement = 'The ComputeLinearElasticStress class shall error if a user attempts to run a problem using ComputeLinearElasticStress with a finite strain formulation.'
The ComputeLinearElasticStress class shall generate an error if a user attempts to run a problem using ComputeLinearElasticStress with a finite strain formulation.

2018-09-13 14:26 UTC, bwspenc commented on modules/tensor_mechanics/test/tests/pressure/tests
> +    requirement = 'The pressure boundary condition action shall compute pressure loads on three faces of an elastic small strain isotropic unit cube to create a hydrostatic pressure which corresponds
The Pressure boundary condition action shall create the objects needed to apply pressure boundary conditions on a 3D model as demonstrated by correctly computing the response of an elastic small-strain isotropic unit cube with pressure applied on three faces to create a hydrostatic pressure.

2018-09-13 14:26 UTC, bwspenc commented on modules/tensor_mechanics/test/tests/pressure/tests
> +    requirement = 'The pressure boundary condition action shall compute pressure loads on three faces of an elastic small strain isotropic unit cube to create a hydrostatic pressure which corresponds
The Pressure boundary condition action shall create the objects needed to apply pressure boundary conditions on a 3D model as demonstrated by correctly computing the response of an elastic small-strain isotropic unit cube with pressure applied on three faces to create a hydrostatic pressure using the volumetric locking correction b-bar formulation.

2018-09-13 21:18 UTC, bwspenc submitted a review, later dismissed

2018-09-13 21:18 UTC, bwspenc commented on modules/tensor_mechanics/test/tests/pressure/pressure_test.i
> -  # Comment
👍

2018-09-13 21:27 UTC, sapitts commented on modules/tensor_mechanics/test/tests/1D_spherical/tests
> +    issues = '#6256 7555'
obviously it's c ;-) thanks for catching this

2018-09-13 23:38 UTC, bwspenc approved these changes

2018-09-13 23:38 UTC, merged