Suppressions
idaholab/moose pull request #12137
Opened 2018-09-17 14:27 UTC by lindsayad

Add suppressions necessary for running valgrind in parallel. Relevant valgrind bug report [here](https://bugs.kde.org/show_bug.cgi?id=287862)

2018-09-17 15:37 UTC, permcody requested changes

2018-09-17 15:37 UTC, permcody commented on python/TestHarness/suppressions/errors.supp
> +   Unadressable_bytes_debug_2
My experience has been that these really specific traces tend to fail a lot as small things change on the system over time. Have you looked at putting in wildcard expressions to simplify and reduce the number of suppressions? Take a look at the existing file where we basically capture just the name of the function that we know to be bad and just wildcard most of the rest. At the very least all of these `_n` expressions can be collapsed into a single suppression.

2018-09-17 22:52 UTC, permcody approved these changes

2018-09-17 22:58 UTC, merged

2018-09-18 12:46 UTC, brianmoose commented
This broke a bunch of valgrind testing: https://civet.inl.gov/event/34252/