consolidate LATEST checkpoint file name handling
idaholab/moose pull request #12403
Opened 2018-10-29 21:03 UTC by rwcarlsen

Be more consistent about how we handle unspecified restart/recover base file
paths.

Fixes #10494.

2018-10-29 21:38 UTC, moosebuild commented
Job [Documentation](https://civet.inl.gov/job/250053/) on 522ba16 wanted to post the following:

View the site [here](http://mooseframework.inl.gov/docs/PRs/12403/site)

This comment will be updated on new commits.

2018-10-29 21:48 UTC, rwcarlsen commented
@gardnerru - can you confirm whether this fixes #10494?

2018-10-30 16:50 UTC, gardnerru commented
Looks good from here, tested on the examples/restart in bison

2018-10-30 17:37 UTC, permcody requested changes
This looks good, but you are fixing a specific bug. Can you add a test so that we avoid a regression in the future? There should be a few "LATEST" tests checked in. Just adding another variation of the test that passes this on the CLI should be enough. Thanks!

2018-11-06 20:25 UTC, permcody approved these changes

2018-11-06 20:25 UTC, merged