Add method to extract _elem_crack_origin_direction_map. Closes #12435.
idaholab/moose pull request #12438
Opened 2018-11-05 20:55 UTC by gambka

Adding method to extract data in an existing map in XFEM.C for use in other MOOSE objects.

Closes #12435.

2018-11-05 20:56 UTC, gambka commented
@jiangwen84 @bwspenc

2018-11-05 21:31 UTC, moosebuild commented
Job [Documentation](https://civet.inl.gov/job/253045/) on 292d961 wanted to post the following:

View the site [here](http://mooseframework.inl.gov/docs/PRs/12438/site)

This comment will be updated on new commits.

2018-11-05 22:56 UTC, moosebuild commented
Job [Test Tiamat](https://civet.inl.gov/job/253051/) on 292d961 : invalidated by @milljm

updated recipes to allow Tiamat to fail

2018-11-06 16:11 UTC, jiangwen84 commented on modules/xfem/include/base/XFEM.h
> +  virtual std::map<const Elem *, std::vector<Point>> getCrackTipOriginMap() const
I think this function does not need to be virtual.

2018-11-06 20:28 UTC, permcody commented
The problem with this PR is that there's a new method (just an accessor) added, but no test and the method is not used in MOOSE nor the modules...   

I could remove this tomorrow and still pass all MOOSE and modules testing. I would really prefer that there was a test added (even if that means making a pure test object in the XFEM module, even if that object is a little contrived) that requires this API.

2018-11-07 15:08 UTC, gambka commented
Where would be the best place to store the .md documentation for these pure test objects? There is no `doc` directory beside `include` and `src` in `test/`.  I thought the purpose of pure test objects is to for testing and not to be used by users.  I haven't seen pure test objects documented elsewhere as of yet.  Is there a special grouping on the documentation webpage for these objects to ensure users are aware to not use them?

2018-11-07 19:35 UTC, permcody commented
> Where would be the best place to store the .md documentation for these pure test objects? There is no doc directory beside include and src in test/. 

Don't document the pure test objects. That's our current thinking.

> I thought the purpose of pure test objects is to for testing and not to be used by users. I haven't seen pure test objects documented elsewhere as of yet. 

Right!

Is there a special grouping on the documentation webpage for these objects to ensure users are aware to not use them?

Nope! Users can use pure test objects if they really want. There's the "--allow-test-objects" flag that makes them available to instantiate from a normal run. Normally, you won't use this unless you really want to use a "test" object in a production run (whatever that means).

2018-11-07 19:37 UTC, gambka commented
The reason I asked is because the testing system failed the documentation because I didn't have .md files for the pure test object.

2018-11-07 20:00 UTC, permcody commented
It shouldn't fail. If it does again, I'll have @aeslaughter take a look. Thanks for working on this!

2018-11-08 00:23 UTC, permcody requested changes

2018-11-08 18:44 UTC, permcody approved these changes

2018-11-08 18:44 UTC, permcody commented
Excellent work Kyle! Thanks for jumping through all these extra hoops.

2018-11-08 18:44 UTC, merged