Ensure that curl shape functions are available on elems/faces
idaholab/moose pull request #12461
Opened 2018-11-08 21:03 UTC by lindsayad

This addresses the issue reported by a user [here](https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/moose-users/5xEiiYeFVMU/DA1qKXtZBQAJ).

Refs #10238

2018-11-08 21:41 UTC, moosebuild commented
Job [Documentation](https://civet.inl.gov/job/255052/) on 8f1ebcf wanted to post the following:

View the site [here](http://mooseframework.inl.gov/docs/PRs/12461/site)

This comment will be updated on new commits.

2018-11-12 16:52 UTC, permcody commented
Do we not have any tests that hit this? How is this working now?

2018-11-12 17:55 UTC, rwcarlsen requested changes
This should have a test.

2018-11-12 21:38 UTC, lindsayad commented
You have to have a very specific set of circumstances to run into a problem (before this PR). You would need:
- At least one `VectorKernel` for variable `u`
- At least one `IntegratedBCBase`
- No `VectorIntegratedBCs` for variable `u`

2018-11-12 22:33 UTC, rwcarlsen submitted a review, later dismissed

2018-11-13 00:31 UTC, permcody approved these changes

2018-11-13 00:31 UTC, merged