Build DoF indices in front for variables to be zeroed during residual evaluation
idaholab/moose pull request #12478
Opened 2018-11-13 23:35 UTC by YaqiWang

Close #12451.

2018-11-13 23:38 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/256695/) on 0ac1b79 wanted to post the following:

Your code requires style changes.  

A patch was auto generated and copied [here](http://mooseframework.inl.gov/docs/PRs/12478/style.patch)  
You can directly apply the patch by running, in the top level of your repository:

`curl -s http://mooseframework.inl.gov/docs/PRs/12478/style.patch | git apply -v`  

Alternatively, with your repository up to date and in the top level of your repository:

`git clang-format 0451d809ae3f48eafed79c49335eaf63a68443e4`

2018-11-19 15:06 UTC, permcody commented
This looks ok to me, @friedmud - any comments?

2018-12-10 15:34 UTC, permcody commented
@fdkong - Can you take a look at this optimization? Make sure that you are ok with the two new closes in here. This only happens on MeshChanged so it should be a lot less frequent than doing this during the solve.

2018-12-10 16:02 UTC, fdkong requested changes

2018-12-10 16:02 UTC, fdkong commented on framework/src/systems/SystemBase.C
> +
Not sure why we need a `close` here.  I would like to remote this one.

2018-12-10 16:07 UTC, fdkong commented on framework/src/problems/FEProblemBase.C
> +  _aux->clearDofIndicesToZero();
You might do the same thing for the` displaced  system` .  Create a ` _displ_sys->clearDofIndicesToZero()`

2019-01-10 23:52 UTC, closed without merging