Generic fluid state material and IC
idaholab/moose pull request #12486
Opened 2018-11-15 10:33 UTC by cpgr

Basically implements a generic version of the current specialised materials and ICs, and deprecates these specialised versions

Closes #12485

2018-11-15 11:03 UTC, moosebuild commented
Job [Documentation](https://civet.inl.gov/job/257129/) on 8c1388b wanted to post the following:

View the site [here](http://mooseframework.inl.gov/docs/PRs/12486/site)

This comment will be updated on new commits.

2018-11-16 03:54 UTC, cpgr commented
I had forgotten how long it takes to build a non-unity executable!

2018-11-19 17:49 UTC, andrsd requested changes

2018-11-19 17:49 UTC, andrsd commented on modules/porous_flow/test/tests/fluidstate/tests
> +    requirement = 'PorousFlowWaterNCG shall correctly calculate the properties of the liquid phase'
You should not refer to class names in `requirements`. Requirements are first, then design where class names appear. That's what you have correctly in `design`.  You want to say "Porous flow module shall calculate...". 

Also, I would not use the word "correctly" in a requirement (think about this statement "I want to compute an incorrect value of quantity XYZ" - see?).

2018-11-19 17:49 UTC, andrsd commented on modules/porous_flow/include/ics/PorousFlowFluidStateIC.h
> +  const VariableValue & _xnacl;
I noticed you use `_Xnacl` in the other classes. May be make them consistent with each other.

2018-11-26 19:14 UTC, andrsd approved these changes

2018-11-26 19:14 UTC, merged