Remove store_stress_old and store_stress_older
idaholab/moose pull request #12577
Opened 2018-12-03 18:21 UTC by bwspenc

closes #12574

2018-12-03 18:22 UTC, bwspenc commented
@sveerara I haven't looked at Mastodon, but I'm guessing that this will fail the Mastodon tests. If you could remove all usage of 'store_stress_old' and 'store_stress_older' in Mastodon, that would be great.

2018-12-03 18:43 UTC, moosebuild commented
Job [Documentation](https://civet.inl.gov/job/263779/) on fec8a16 wanted to post the following:

View the site [here](http://mooseframework.inl.gov/docs/PRs/12577/site)

This comment will be updated on new commits.

2018-12-03 18:49 UTC, sveerara requested changes
I have made minor comments on the PR. The Dynamics documentation (Dynamics.md in modules/tensor_mechanics) also contains a couple of lines on using store_stress_old. Can you please remove that as well? Thanks!

2018-12-03 18:49 UTC, sveerara commented on modules/combined/test/tests/solid_mechanics/Rayleigh_damping/Newmark_time_integration/Rayleigh_Newmark.i
>  # The system will come to steady state slowly after the pressure
becomes constant.

2018-12-03 18:49 UTC, sveerara commented on modules/combined/test/tests/solid_mechanics/Time_integration/HHT_time_integration/HHT_test.i
>  # becomes constant.  Alpha equal to zero will result in Newmark
time integration.

2018-12-03 21:09 UTC, bwspenc commented
@sveerara Sure, I'll fix those things.  Let me know when you get the Mastodon test fixes merged in, and then I'll push in my changes. That will trigger the tests getting run again, and they should pass at that point.

2018-12-04 16:31 UTC, sveerara commented
@bwspenc, the Mastodon test fixes have been merged.

2018-12-05 00:30 UTC, bwspenc commented
Thanks for fixing the Mastodon tests, @sveerara.  I just pushed an update that address all of your comments. Hopefully the tests will pass.

2018-12-05 02:13 UTC, sveerara approved these changes
Thanks for making these changes.

2018-12-05 16:50 UTC, dschwen approved these changes

2018-12-05 16:50 UTC, merged