External PETSc problem
idaholab/moose pull request #12598
Opened 2018-12-06 23:54 UTC by fdkong

Definitely did not get it done yet, but it is a good starting point for discussion. 

@friedmud

2018-12-06 23:56 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/265244/) on f753860 wanted to post the following:

Your code requires style changes.  

A patch was auto generated and copied [here](http://mooseframework.inl.gov/docs/PRs/12598/style.patch)  
You can directly apply the patch by running, in the top level of your repository:

`curl -s http://mooseframework.inl.gov/docs/PRs/12598/style.patch | git apply -v`  

Alternatively, with your repository up to date and in the top level of your repository:

`git clang-format c9068b4a341c5fa53a771dc8ab257bc9a40b8619`

2018-12-09 16:06 UTC, friedmud commented
Let's make sure to talk about this tomorrow...

On Thu, Dec 6, 2018 at 4:56 PM MOOSE Build <notifications@github.com> wrote:

> Job Precheck <https://civet.inl.gov/job/265244/> on f753860
> <https://github.com/idaholab/moose/commit/f7538601a554d7203aeded4a4444add572b5c318>
> wanted to post the following:
>
> Your code requires style changes.
>
> A patch was auto generated and copied here
> <http://mooseframework.inl.gov/docs/PRs/12598/style.patch>
> You can directly apply the patch by running, in the top level of your
> repository:
>
> curl -s http://mooseframework.inl.gov/docs/PRs/12598/style.patch | git
> apply -v
>
> Alternatively, with your repository up to date and in the top level of
> your repository:
>
> git clang-format c9068b4a341c5fa53a771dc8ab257bc9a40b8619
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/idaholab/moose/pull/12598#issuecomment-445073751>, or mute
> the thread
> <https://github.com/notifications/unsubscribe-auth/AA1JMbNT3eqOQB94S3ZNLXEi6aFCm-oEks5u2a6lgaJpZM4ZHiTA>
> .
>

2019-01-09 18:06 UTC, YaqiWang commented
I can see that this is a nice tool for me to learn PETSc. Is there any other purpose for this PR besides educational? Just curious.

2019-01-09 18:30 UTC, fdkong commented
> I can see that this is a nice tool for me to learn PETSc. Is there any other purpose for this PR besides educational? Just curious.

It is used to demonstrate how to couple an external APP through MOOSE APP Wrapper (External problem).

2019-01-09 20:01 UTC, moosebuild commented
Job [Documentation](https://civet.inl.gov/job/272631/) on 9f9b114 wanted to post the following:

View the site [here](http://mooseframework.inl.gov/docs/PRs/12598/site)

This comment will be updated on new commits.

2019-01-10 23:12 UTC, permcody requested changes
Getting really close.

2019-01-10 23:12 UTC, permcody commented on modules/external_petsc_solver/test/tests/external_petsc_problem/external_petsc_master.i
> +###########################################################
Delete this header. We aren't using this @Requirement syntax anymore.

2019-01-10 23:12 UTC, permcody commented on modules/external_petsc_solver/test/tests/kernels/simple_diffusion/simple_diffusion.i
> +[Mesh]
If you have a real test, feel free to delete this simple diffusion test. It's just nice to have a single placeholder.

2019-01-10 23:12 UTC, permcody commented on modules/modules.mk
> +
Oh you need a suffix - that's super important. In fact I'm surprised any of this works without it!

2019-01-11 20:20 UTC, moosebuild commented
Job [External App tests](https://civet.inl.gov/job/273773/) on 012bdea : invalidated by @fdkong

Bahun and SiantBemard should be fixed

2019-01-11 20:51 UTC, moosebuild commented
Job [External App tests PETSc alt](https://civet.inl.gov/job/273774/) on 012bdea : invalidated by @fdkong

2019-01-17 22:33 UTC, permcody approved these changes

2019-01-17 22:34 UTC, merged