More mesh generator work
idaholab/moose pull request #12600
Opened 2018-12-10 15:54 UTC by leorachapuis

- Make the "input" parameter required for the MeshGenerators.
- Make TiledMeshGenerator compute the x,y and z widths of the mesh to repeat instead of it being user-provided.

2018-12-10 15:56 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/265642/) on 4fa7037 wanted to post the following:

Your code requires style changes.  

A patch was auto generated and copied [here](http://mooseframework.inl.gov/docs/PRs/12600/style.patch)  
You can directly apply the patch by running, in the top level of your repository:

`curl -s http://mooseframework.inl.gov/docs/PRs/12600/style.patch | git apply -v`  

Alternatively, with your repository up to date and in the top level of your repository:

`git clang-format 77542f5f9b0b978f79193192fca9b82d12cbc40c`

2018-12-10 17:22 UTC, leorachapuis commented
@friedmud Can you review this when you have time ?

2019-01-07 19:58 UTC, permcody requested changes

2019-01-07 19:58 UTC, permcody commented on framework/src/meshgenerators/TiledMeshGenerator.C
> +  BoundingBox bbox(Point(0, 0, 0), Point(0, 0, 0));
Defaulting to zero can fail if your mesh is completely in positive or completely in negative coordinates. You might want to start with a max and min that are set to the "min" and "max" respectively.

2019-01-07 20:57 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/270786/) on 16189d3 wanted to post the following:

Your code requires style changes.  

A patch was auto generated and copied [here](http://mooseframework.inl.gov/docs/PRs/12600/style.patch)  
You can directly apply the patch by running, in the top level of your repository:

`curl -s http://mooseframework.inl.gov/docs/PRs/12600/style.patch | git apply -v`  

Alternatively, with your repository up to date and in the top level of your repository:

`git clang-format 77542f5f9b0b978f79193192fca9b82d12cbc40c`

2019-01-07 21:14 UTC, permcody approved these changes

2019-01-07 21:14 UTC, permcody commented on framework/src/meshgenerators/TiledMeshGenerator.C
> +                         std::numeric_limits<Real>::lowest()));
👍

2019-01-07 22:29 UTC, merged