Create StackGenerator
idaholab/moose pull request #12662
Opened 2019-01-08 20:27 UTC by leorachapuis

Create a new MeshGenerator : StackGenerator.
It takes several 3D meshes, and stitches them on top of each other, so as to create a "stack".
Refs #11640.

2019-01-08 20:53 UTC, moosebuild commented
Job [Documentation](https://civet.inl.gov/job/271822/) on db49d33 wanted to post the following:

View the site [here](http://mooseframework.inl.gov/docs/PRs/12662/site)

This comment will be updated on new commits.

2019-01-09 19:28 UTC, friedmud requested changes
Needs to work in 2D

2019-01-09 21:19 UTC, leorachapuis commented on framework/src/meshgenerators/StackGenerator.C
> +  for (auto i = beginIndex(_meshes); i < _meshes.size(); ++i)
Doesn't PatternedMeshGenerator handle the 2D case ?

2019-01-09 22:18 UTC, friedmud commented on framework/src/meshgenerators/StackGenerator.C
> +  for (auto i = beginIndex(_meshes); i < _meshes.size(); ++i)
It doesn't - because it doesn't handle non-equally sized meshes.

2019-01-09 22:18 UTC, friedmud commented on framework/src/meshgenerators/StackGenerator.C
> +  for (auto i = beginIndex(_meshes); i < _meshes.size(); ++i)
Plus: this is a much better, more straightforward way to stack things - if that's what you're trying to do.

2019-01-09 22:20 UTC, friedmud commented on test/tests/meshgenerators/stack_generator/tests
> +    requirement = 'MOOSE shall be able to use the MeshTools modification tools.'
```suggestion
    requirement = 'MOOSE shall be able to generate meshes by stacking together multiple meshes.'
```

2019-01-09 22:20 UTC, friedmud commented on test/tests/meshgenerators/stack_generator/tests
> +    requirement = 'MOOSE shall be able to use libmesh mesh modification tools.'
```suggestion
    requirement = 'MOOSE shall be able to generate new meshes by stacking up existing meshes.'
```

2019-01-10 17:44 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/273560/) on 4871299 wanted to post the following:

Your code requires style changes.  

A patch was auto generated and copied [here](http://mooseframework.inl.gov/docs/PRs/12662/style.patch)  
You can directly apply the patch by running, in the top level of your repository:

`curl -s http://mooseframework.inl.gov/docs/PRs/12662/style.patch | git apply -v`  

Alternatively, with your repository up to date and in the top level of your repository:

`git clang-format 844e8f2c067db526da88895f33ba17c539443f60`

2019-01-13 16:03 UTC, friedmud requested changes
Thanks for doing 2D!  Only one small comment.

2019-01-13 16:03 UTC, friedmud commented on framework/src/meshgenerators/StackGenerator.C
> +    BoundingBox sub_bbox = MeshTools::create_subdomain_bounding_box(mesh, id);
I don't understand.  Can you explain all the stuff with the subdomains?  It doesn't make sense to me.  Why can't you just call `MeshTools::create_bounding_box()`?  It should give you the exactly correct bounding box (no need to union or anything).

But what am I missing?

2019-01-15 20:50 UTC, friedmud commented on framework/src/meshgenerators/StackGenerator.C
> +  BoundingBox bbox = MeshTools::create_bounding_box(mesh);
```suggestion
  auto bbox = MeshTools::create_bounding_box(mesh);
```

2019-01-16 16:24 UTC, friedmud approved these changes

2019-01-16 16:24 UTC, merged