Made computeFullJacobian thread operate only on active BCs
idaholab/moose pull request #12698
Opened 2019-01-15 15:43 UTC by joshuahansel

Closes #12627

2019-01-15 16:10 UTC, andrsd submitted a review, later dismissed

2019-01-15 17:51 UTC, permcody requested changes
Test case?

2019-01-15 20:42 UTC, joshuahansel commented
Oops, I'm gonna fail SQA checks - forgot. I'll fix that.

2019-01-16 17:49 UTC, permcody approved these changes

2019-01-16 17:49 UTC, merged