Create ComputeInterfaceStressKKS material
idaholab/moose pull request #12706
Opened 2019-01-15 21:37 UTC by laagesen

Closes #12705

2019-01-15 21:38 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/276099/) on 825105d wanted to post the following:

Your code requires style changes.  

A patch was auto generated and copied [here](http://mooseframework.inl.gov/docs/PRs/12706/style.patch)  
You can directly apply the patch by running, in the top level of your repository:

`curl -s http://mooseframework.inl.gov/docs/PRs/12706/style.patch | git apply -v`  

Alternatively, with your repository up to date and in the top level of your repository:

`git clang-format 5fe931b316b4cab9a023a637fe28ec8bef485092`

2019-01-15 22:12 UTC, moosebuild commented
Job [Documentation](https://civet.inl.gov/job/276115/) on 1f75711 wanted to post the following:

View the site [here](http://mooseframework.inl.gov/docs/PRs/12706/site)

This comment will be updated on new commits.

2019-01-15 22:42 UTC, dschwen reviewed
Maybe rename to ComputeSurfaceTensionKKS and link to ComputeInterfaceStress in the md

2019-01-21 16:21 UTC, permcody commented
Test failures are unrelated.

2019-01-22 15:49 UTC, dschwen requested changes

2019-01-22 15:49 UTC, dschwen commented on modules/combined/test/tests/surface_tension_KKS/surface_tension_KKS.i
> +    type = IterationAdaptiveDT
I suggest using a fixed dt in case future updates change the iteration count and this the time step, causing a diff

2019-01-22 15:49 UTC, dschwen commented on modules/tensor_mechanics/src/materials/ComputeSurfaceTensionKKS.C
> +  if (grad_norm_sq > libMesh::TOLERANCE)
It looks to me this if clause is not necessary here

2019-01-22 21:46 UTC, dschwen approved these changes

2019-01-23 16:16 UTC, merged