Add AuxKernel to output volumetric heating from Joule heating closes #12723
idaholab/moose pull request #12726
Opened 2019-01-17 22:23 UTC by yeh512

2019-01-17 23:19 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/278145/) on 4161660 wanted to post the following:

Your code requires style changes.  

A patch was auto generated and copied [here](http://mooseframework.inl.gov/docs/PRs/12726/style.patch)  
You can directly apply the patch by running, in the top level of your repository:

`curl -s http://mooseframework.inl.gov/docs/PRs/12726/style.patch | git apply -v`  

Alternatively, with your repository up to date and in the top level of your repository:

`git clang-format efba239ce9d0fd71112b2815aaf2b3161c38201f`

2019-01-18 00:10 UTC, bwspenc commented
@yeh512 There are a lot of extra commits here.  My guess is that you did your work on the master branch rather than the devel branch.  I'll try to swing by and help you sort that out.
Also, you'll need to run 'git clang-format'.

2019-01-18 00:52 UTC, moosebuild commented
Job [Documentation](https://civet.inl.gov/job/278240/) on 9bebdfd wanted to post the following:

View the site [here](http://mooseframework.inl.gov/docs/PRs/12726/site)

This comment will be updated on new commits.

2019-01-21 16:19 UTC, permcody requested changes
Looks really good, just a few minor changes and hopefully the Documentation target will pass!

2019-01-21 16:19 UTC, permcody commented on modules/heat_conduction/src/JouleHeatingHeatGeneratedAux.C
> +//* This file is part of the MOOSE framework
Please create an "auxkernels" directory under source and move this file into that folder.

2019-01-21 16:19 UTC, permcody commented on modules/heat_conduction/include/kernels/JouleHeatingHeatGeneratedAux.h
> +//* This file is part of the MOOSE framework
Create an "auxkernels" folder under include and move this file into that folder.

2019-01-21 16:19 UTC, permcody commented on modules/heat_conduction/doc/content/source/kernels/JouleHeatingHeatGeneratedAux.md
> +#JouleHeatingHeatGeneratedAux
Create an "auxkernels" folder under source and move this file into that location.

2019-01-21 16:19 UTC, permcody commented on modules/combined/test/tests/joule_heating_heat/tests
> +  issues = '12723'
12723 -> #12723

2019-01-21 16:19 UTC, permcody commented on modules/combined/test/tests/joule_heating_heat/tests
> +  design = 'kernels/JouleHeatingHeatGeneratedAux.md'
Update this once you move this into the new auxkernels folder.

2019-01-21 16:19 UTC, permcody commented on modules/combined/test/tests/joule_heating_heat/jouleheating_heat.i
> +  execute_on = 'initial timestep_end'
This is the default, you can remove this line if you want.

2019-01-21 16:23 UTC, bwspenc commented
The .h file should be in:
```
modules/heat_conduction/include/auxkernels/
```
and the .C file should be in:
```
modules/heat_conduction/src/auxkernels/

2019-01-22 15:51 UTC, permcody approved these changes
Very nice - Thanks for the contribution!

2019-01-22 15:51 UTC, merged