Mesh generator cleanup
idaholab/moose pull request #12782
Opened 2019-01-29 18:21 UTC by permcody

Moving towards a single and consistent way to build the right kind of Mesh between the Mesh and MeshGenerator systems. This PR changes the GeneratedMeshGenerator object to new API in MooseMesh to construct the right kind of MeshBase object.

TODO: We need to evaluate individual MeshGenerators to decide which ones need to be updated. Actually, all should be updated to use the new API, but some might need to force a particular Mesh type.

2019-01-29 18:50 UTC, moosebuild commented
Job [Documentation](https://civet.inl.gov/job/282512/) on 18828c7 wanted to post the following:

View the site [here](http://mooseframework.inl.gov/docs/PRs/12782/site)

This comment will be updated on new commits.

2019-01-30 01:40 UTC, friedmud requested changes
This is a good start - it could probably go in as it is... but I wouldn't mind if the bit about only constructing the requested kind of mesh made it in here.

Feel free to override if you'd rather do that separately.

2019-01-30 01:40 UTC, friedmud commented on framework/src/meshgenerators/GeneratedMeshGenerator.C
> +  auto mesh = _mesh->constructMeshBase();
Ok - maybe... but I think `constructMesh()` really needs to take parameters about what's acceptable to be constructed.

2019-01-30 14:37 UTC, friedmud commented
Also - I was thinking that the function name should be a bit more clear: `createMeshObject()` or something like that?  Just to differentiate it from `buildMesh()`.

But: I did think about this last night and I think it's a good idea.  It's a nice blend of the old system and the new... and will enable the Generators to pull lots of common data / input from the Mesh block.  I'm sure that will be abused too... but what can we do?

2019-01-31 16:21 UTC, friedmud requested changes
Just one small typo fix

2019-01-31 16:21 UTC, friedmud commented on framework/src/mesh/MooseMesh.C
> +                 "running with a DistributedMesh");
```suggestion
                 "running with a ReplicatedMesh");
```

2019-01-31 16:21 UTC, friedmud commented on framework/src/mesh/MooseMesh.C
> +                 "running with a DistributedMesh");
👍

2019-01-31 16:21 UTC, friedmud commented on framework/src/meshgenerators/GeneratedMeshGenerator.C
> +  auto mesh = _mesh->buildMeshBaseObject();
👍

2019-01-31 17:33 UTC, permcody commented
Cool - That suggested change thingy actually works with CIVET. This should be good now.

2019-01-31 18:27 UTC, friedmud approved these changes

2019-01-31 18:37 UTC, permcody commented
Yeah - except automerge doesn't work with allowed to fail.  That might be something that we look into now that we have this "next" branch setup. If you see it finished testing, otherwise, I'll perform the merge.

2019-01-31 19:07 UTC, merged

2019-02-04 19:34 UTC, YaqiWang commented
@permcody Looks like this PR made way to moose master branch and got pushed to Rattlesnake devel. But it is causing one distributed mesh test failing, can you check out https://moosebuild.inl.gov/job/156863/ and propose a fix? Thanks.

2019-02-04 20:55 UTC, permcody commented
I assume that the problem is here:
https://github.com/idaholab/moose/commit/5d74fe86fa61da7e93cd1cdf2db1f02b0d576ed7#diff-9f8c79ed34bec90d2c7e006fcd37eeaaR236

Note how the MooseMesh is now created _before_ "check_copy_nodal_vars" action. Considering the name of the failing test, it seems like something probably isn't getting initialized as it probably was before this change? Any idea where to look?

Just so you are clear, what happened with this change is that we are now building the MooseMesh object much earlier, **BUT** we aren't building underlying MeshBase object. The MeshBase object is being built a little bit later now. It might be a few more hours, or early tomorrow before I can take a look. If you have any ideas on where to start, please let me know.

2019-02-04 21:31 UTC, YaqiWang commented
That test is using a custom action `AddRestartedVariables`, which is registered to "check_copy_nodal_vars", "add_face_variable", "add_user_object", "add_function" and "add_ic", to facilitate loading variables from exodus file. The action is quite simple and located under `rattlesnake/src/actions/AddRestartedVariables.C`. I suppose it is related with this https://hpcgitlab.hpc.inl.gov/idaholab/rattlesnake/blob/devel/src/actions/AddRestartedVariables.C#L106-113.  I am also busy in something else currently. It will take me several hours to finish...

2019-02-04 21:51 UTC, permcody commented
Hmm... No, That action is still after the MeshBase has been constructed and set. I don't immediately see anything in that code that would have been broken.

2019-02-04 21:59 UTC, YaqiWang commented
Note this is related only with distributed mesh. Is it possible the run went through a different path?