Remove const_cast in FiniteStrainUObasedCP
idaholab/moose pull request #12827
Opened 2019-02-05 00:35 UTC by jiangwen84

closes ref #12818

2019-02-05 01:13 UTC, moosebuild commented
Job [Documentation](https://civet.inl.gov/job/286122/) on 36e30f4 wanted to post the following:

View the site [here](http://mooseframework.inl.gov/docs/PRs/12827/site)

This comment will be updated on new commits.

2019-02-05 02:34 UTC, jiangwen84 commented
@permcody thanks!

2019-02-06 00:48 UTC, bwspenc commented on modules/tensor_mechanics/doc/content/source/userobjects/CrystalPlasticityStateVarRateComponentGSS.md
> +`CrystalPlasticityStateVarRateComponentGSS` derives from `CrystalPlasticityStateVarRateComponent` which calculates individual component of the state variable evolution rate in [crystal plasticity sys
```suggestion
`CrystalPlasticityStateVarRateComponentGSS` derives from `CrystalPlasticityStateVarRateComponent` which calculates individual components of the state variable evolution rate in [crystal plasticity system](FiniteStrainUObasedCP.md). The rate component $r = r(y,\cdots, \dot{g}, \cdots)$ can be a function of state variables $y$ and slip rate $\dot{g}$.  
```

2019-02-06 00:58 UTC, bwspenc requested changes

2019-02-06 00:58 UTC, bwspenc commented on modules/tensor_mechanics/doc/content/source/materials/FiniteStrainUObasedCP.md
> +The UserObject based crystal plasticity system is designed to facilitate the implementation of different constitutive laws in a modular way. Both phenomenological constitutive models and dislocation-
```suggestion
The UserObject based crystal plasticity system is designed to facilitate the implementation of different constitutive laws in a modular way. Both phenomenological constitutive models and dislocation-based constitutive models can be implemented through this system. This system consists of one material class `FiniteStrainUObasedCP` and four UserObject classes, namely `CrystalPlasticitySlipRate`, `CrystalPlasticitySlipResistance`, `CrystalPlasticityStateVarRateComponent` and `CrystalPlasticityStateVariable`.
```

2019-02-06 00:58 UTC, bwspenc commented on modules/tensor_mechanics/doc/content/source/userobjects/CrystalPlasticitySlipRateGSS.md
> +`CrystalPlasticitySlipRateGSS` derives from `CrystalPlasticitySlipRate` which calculates slip rate in [crystal plasticity system](FiniteStrainUObasedCP.md). The slip system is read into this class. T
```suggestion
`CrystalPlasticitySlipRateGSS` derives from `CrystalPlasticitySlipRate` which calculates slip rate in the [crystal plasticity system](FiniteStrainUObasedCP.md). The slip system is read into this class. The Schmid tensor is generated in this class and the flow direction is calculated by `calcFlowDirection()`. The slip rate $\dot{g} = g(T, s\cdots, y\cdots)$ is a function of PK2 stress $$T$$, slip resistance $$s$$ and state variables $y$.
```

2019-02-06 00:58 UTC, bwspenc commented on modules/tensor_mechanics/doc/content/source/materials/FiniteStrainUObasedCP.md
> +ii. $ T^\prime=C:E^e$ which gives $\frac{\partial T^\prime}{\partial T_i}=C: \frac{\partial E^e}{\partial T_i}$.
```suggestion
ii. $T^\prime=C:E^e$ which gives $\frac{\partial T^\prime}{\partial T_i}=C: \frac{\partial E^e}{\partial T_i}$.
```

2019-02-06 00:58 UTC, bwspenc commented on modules/tensor_mechanics/doc/content/source/materials/FiniteStrainUObasedCP.md
> +ii. $ T^\prime=C:E^e$ which gives $\frac{\partial T^\prime}{\partial T_i}=C: \frac{\partial E^e}{\partial T_i}$.
This one isn't rendering correctly.  I assume it's because of the space in front of T.

2019-02-06 00:58 UTC, bwspenc commented on modules/tensor_mechanics/doc/content/source/materials/FiniteStrainUObasedCP.md
> +i. Variable dfedf calculates $\frac{\partial F^e}{\partial F}$.
```suggestion
i. Variable `dfedf` calculates $\frac{\partial F^e}{\partial F}$.
```

2019-02-06 00:58 UTC, bwspenc commented on modules/tensor_mechanics/doc/content/source/materials/FiniteStrainUObasedCP.md
> +ii. Variable deedfe calculates $\frac{\partial E^e}{\partial F^e}$.
```suggestion
ii. Variable `deedfe` calculates $\frac{\partial E^e}{\partial F^e}$.
```

2019-02-06 00:58 UTC, bwspenc commented on modules/tensor_mechanics/doc/content/source/materials/FiniteStrainUObasedCP.md
> +iii. Variable dsigspk2dfe calculates $F^{eT} C:\frac{\partial E^e}{\partial F^e} F^e$.
```suggestion
iii. Variable `dsigspk2dfe` calculates $F^{eT} C:\frac{\partial E^e}{\partial F^e} F^e$.
```

2019-02-06 00:58 UTC, bwspenc commented on modules/tensor_mechanics/doc/content/source/userobjects/CrystalPlasticityStateVariable.md
> +`CrystalPlasticityStateVariable` represents a state variable, such as dislocation density in [crystal plasticity system](FiniteStrainUObasedCP.md). The initial values of state variable are either pro
```suggestion
`CrystalPlasticityStateVariable` represents a state variable, such as dislocation density in [crystal plasticity system](FiniteStrainUObasedCP.md). The initial values of this state variable are either provided in the input file `readInitialValueFromInline()` or read from the file `readInitialValueFromFile()`. The state variable evolves as $y_{n+1} = y_n + \dot{y}\cdot dt $ where $\dot{y}$ is the state variable evolution rate. The $\dot{y}$ can have multiple components, such as $\dot{y} = a_1 r_1 + a_2 r_2 + \cdots$ where "$a_1, a_2, \cdots$" are the `scale_factor` and $r_1, r_2, \cdots$ are the individual rate components.
```

2019-02-06 20:21 UTC, bwspenc approved these changes

2019-02-06 20:21 UTC, merged