Add PlaneDeletionGenerator
idaholab/moose pull request #13066
Opened 2019-03-15 03:04 UTC by friedmud

Deletes elements above a plane - check the documentation page for more info.

closes #13046

2019-03-15 04:07 UTC, moosebuild commented
Job [Documentation](https://civet.inl.gov/job/305376/) on b564029 wanted to post the following:

View the site [here](https://mooseframework.inl.gov/docs/PRs/13066/site)

This comment will be updated on new commits.

2019-03-15 15:34 UTC, friedmud commented
Ninja commit from my phone while in the airport 🙌

2019-03-18 17:00 UTC, permcody requested changes
Looks good, but I think a few assertions are reasonable here.

2019-05-08 20:42 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/334717/) on 67046dd wanted to post the following:

Your code requires style changes.  

A patch was auto generated and copied [here](https://mooseframework.inl.gov/docs/PRs/13066/style.patch)  
You can directly apply the patch by running, in the top level of your repository:

`curl -s https://mooseframework.inl.gov/docs/PRs/13066/style.patch | git apply -v`  

Alternatively, with your repository up to date and in the top level of your repository:

`git clang-format 2a9bd1c8c3b9115b514f1f2cb9cfebf023bb5925`

2019-05-14 16:21 UTC, permcody commented
Waiting for the HPC to come back online before any more merges.

On Tue, May 14, 2019 at 10:16 AM Derek Gaston <notifications@github.com>
wrote:

> @friedmud <https://github.com/friedmud> requested your review on: #13066
> <https://github.com/idaholab/moose/pull/13066> Add PlaneDeletionGenerator.
>
> —
> You are receiving this because your review was requested.
>
>
> Reply to this email directly, view it on GitHub
> <https://github.com/idaholab/moose/pull/13066?email_source=notifications&email_token=AAXFOID3FH2FH632YE6GXG3PVLQWTA5CNFSM4G6WOSEKYY3PNVWWK3TUL52HS4DFWZEXG43VMVCXMZLOORHG65DJMZUWGYLUNFXW5KTDN5WW2ZLOORPWSZGOROCCTRQ#event-2340694470>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AAXFOID6N4GIVCG677I3NZLPVLQWTANCNFSM4G6WOSEA>
> .
>

2019-05-17 02:09 UTC, permcody approved these changes

2019-05-17 02:09 UTC, merged