12996 ad aux dot fix
idaholab/moose pull request #13105
Opened 2019-03-22 22:36 UTC by veeshy

Coupled aux variables in an AD time kernel was crashing, possibly because the AD system doesn't support aux variable derivatives but it tried anyways. 

I made a test that fails w/o the change in `MooseVariableFE.C`, I'm not sure if I hit all the relevant bits in `MooseVariableFE.C` though. Test passes with those changes so it seems like a step in the right direction.

Closes #12996.

2019-03-22 22:41 UTC, veeshy commented
@lindsayad I took a stab at this, the check to not do any AD aux stuff might be late, wasn't sure the best place to put it so I did it when the computed ad dot value gets assigned.

2019-03-22 23:19 UTC, moosebuild commented
Job [Documentation](https://civet.inl.gov/job/308406/) on 8738edc wanted to post the following:

View the site [here](https://mooseframework.inl.gov/docs/PRs/13105/site)

This comment will be updated on new commits.

2019-03-25 15:43 UTC, lindsayad requested changes

2019-03-25 15:43 UTC, lindsayad commented on test/src/kernels/ADCoupledTimeTest.C
> +  return _test[_i][_qp] * _v_dot[_qp];
This function will get multiplied internally by `_test` in order to save unnecessary operations (generally speaking; in this particular single operation case there is no savings) so you need to remove `_test`. This is the reason for the CIVET failures.

2019-03-25 15:43 UTC, lindsayad commented on framework/src/variables/MooseVariableFE.C
> +      if (is_transient && _var_kind == Moose::VAR_NONLINEAR)
I don't think is the right fix per se. There must be something stupid happening in the `TimeIntegrator::computeADTimeDerivatives` method which I'm going to look into now

2019-03-25 17:24 UTC, lindsayad commented
See lindsayad/moose commits 68416a1cc1..6f05b. I did some rebasing and autosquashing so most of my changes are included in your "Added test to show a potential fix" commit. If they look good to you, then I will force push to your branch.

2019-03-25 17:29 UTC, lindsayad commented
With the changes I've introduced we should actually be able to get a non-zero time derivative for an aux variable retrieved through `adCoupledDot`, e.g. if the aux variable is changing through the time, then we should be able to get it's correct time derivative. Would you want to update your test to show this?

2019-03-25 18:25 UTC, veeshy commented
Glad you found a smarter spot for the fix! I'll update the test to include a time varying aux after you force push.

2019-03-25 19:15 UTC, lindsayad commented
Cool. Just pushed

On Mon, Mar 25, 2019 at 12:25 PM Vishal Patel <notifications@github.com>
wrote:

> Glad you found a smarter spot for the fix! I'll update the test to include
> a time varying aux after you force push.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/idaholab/moose/pull/13105#issuecomment-476321895>, or mute
> the thread
> <https://github.com/notifications/unsubscribe-auth/AJxgcD4Wy-mwEvjtExPYwaOnwkPf9iThks5vaRSegaJpZM4cEhfy>
> .
>

2019-03-27 14:00 UTC, veeshy commented
Oops, I think I lost the point here, I still need to make a test that couples an *aux* var varying

2019-03-27 14:19 UTC, veeshy commented
Okay, test added!

2019-03-27 22:26 UTC, lindsayad commented
Looks like a different mesh was used for the gold file and the current test...

2019-03-28 00:53 UTC, veeshy commented
yup -_-, added the new gold

2019-03-28 16:26 UTC, lindsayad commented
If you're going to use FDP as a preconditioner, you'll need to specify `allow_warnings = true` in your test block

2019-03-28 17:30 UTC, veeshy commented
Hm, no reason fdp is needed, changed it to smp

2019-03-29 15:00 UTC, lindsayad approved these changes

2019-03-29 15:00 UTC, merged

2019-03-29 15:00 UTC, lindsayad commented
@veeshy Thanks for the contribution!