AdvectionBC and test
idaholab/moose pull request #13305
Opened 2019-04-24 22:00 UTC by snschune

2019-04-24 22:35 UTC, moosebuild commented
Job [Documentation](https://civet.inl.gov/job/325822/) on e329a1b wanted to post the following:

View the site [here](https://mooseframework.inl.gov/docs/PRs/13305/site)

This comment will be updated on new commits.

2019-04-25 15:07 UTC, snschune commented
closes #13283

2019-04-25 16:55 UTC, permcody requested changes

2019-04-25 16:55 UTC, permcody commented on modules/navier_stokes/src/bcs/AdvectionBC.C
> +    mooseError("Number of components of velocity_vector must match mesh dimension");
paramError()

2019-04-25 16:55 UTC, permcody commented on modules/navier_stokes/src/bcs/AdvectionBC.C
> +  if (!((vel * _normals[_qp] > 0) ^ _outflow))
Bitwise XOR? You probably want a comment here!

2019-04-25 16:55 UTC, permcody commented on modules/navier_stokes/src/bcs/AdvectionBC.C
> +      "outflow", true, "Determines if this BC is applied on outflow or outflow BCs");
Typo

2019-04-25 17:03 UTC, snschune commented
Should this BC even be allowed on inflow BCs? ping @YaqiWang

2019-04-25 17:20 UTC, permcody commented on modules/navier_stokes/src/bcs/AdvectionBC.C
> +  if (!((vel * _normals[_qp] > 0) ^ _outflow))
This should be equivalent and more clear:
`if ((vel * _normals[_qp] > 0) == _outflow)`

2019-04-29 20:09 UTC, permcody approved these changes

2019-04-29 20:09 UTC, merged