Avoid accumlation of supplied command line arguments
idaholab/moose pull request #13433
Opened 2019-05-17 16:23 UTC by aeslaughter

@jiangwen84 This should fix the slow down

(refs #13342)

2019-05-17 16:58 UTC, jiangwen84 commented
@aeslaughter That is so great! Thanks for fixing this 👍

2019-05-17 17:03 UTC, moosebuild commented
Job [Documentation](https://civet.inl.gov/job/339889/) on dfd51f6 wanted to post the following:

View the site [here](https://mooseframework.inl.gov/docs/PRs/13433/site)

This comment will be updated on new commits.

2019-05-17 17:24 UTC, rwcarlsen submitted a review, later dismissed

2019-05-17 23:38 UTC, aeslaughter commented
This is a WIP.

2019-05-22 18:20 UTC, aeslaughter commented
@rwcarlsen I can't get anything to work, would you be willing to take a stab?

2019-05-31 16:37 UTC, rwcarlsen requested changes
Looks okay.  We really should try to consolidate the redundant logic in Parser.C and CommandLine.C for characterizing command line args.  Did you look into trying that?

2019-05-31 16:37 UTC, rwcarlsen commented on framework/include/parser/Parser.h
> +  std::string hitCLIFilter(std::string appname, const std::vector<std::string> & argv);
doc comment explaining purpose of this function.

2019-05-31 16:37 UTC, rwcarlsen commented on framework/include/parser/CommandLine.h
> +  /// CLI arguments supplied
"indices of CLI args that are HIT syntax parameters"

2019-05-31 16:37 UTC, rwcarlsen commented on framework/include/parser/CommandLine.h
> +  /// CLI arguments that have been utilized
"indices of CLI args that have been marked as used"

2019-06-05 13:29 UTC, aeslaughter commented
@rwcarlsen I did think about removing the similar code, but the differences are significant enough that it wasn't trivial and I (and you) have already spent way too much time on this, but I created issue #13518.

2019-06-05 13:29 UTC, aeslaughter commented
@rwcarlsen I did think about removing the similar code, but the differences are significant enough that it wasn't trivial and I (and you) have already spent way too much time on this, but I created issue #13518.

2019-06-05 15:24 UTC, rwcarlsen approved these changes

2019-06-05 15:29 UTC, merged