AD grain growth
idaholab/moose pull request #13541
Opened 2019-06-11 17:49 UTC by dschwen

Closes #13539

2019-06-11 18:34 UTC, moosebuild commented
Job [Documentation](https://civet.inl.gov/job/349730/) on 03ebd49 wanted to post the following:

View the site [here](https://mooseframework.inl.gov/docs/PRs/13541/site)

This comment will be updated on new commits.

2019-06-19 17:24 UTC, laagesen commented
Hi Daniel- just getting back in to the office today- will try to get to this soon.

2019-06-20 21:24 UTC, laagesen requested changes

2019-06-20 22:06 UTC, dschwen commented on modules/phase_field/doc/content/source/kernels/ACGrGrPoly.md
>  !syntax description /Kernels/ACGrGrPoly
yes

2019-06-20 22:07 UTC, dschwen commented on modules/phase_field/doc/content/source/kernels/ACGrGrPoly.md
> +\left(L\mu(\eta^3-\eta+2\gamma\eta\sum_j\eta_j),\psi\right),
Ugh, I had also forgotten a square on the eta_j. Added.

2019-06-20 22:20 UTC, laagesen approved these changes

2019-06-24 20:28 UTC, permcody approved these changes

2019-06-24 21:53 UTC, merged