Update package_version
idaholab/moose pull request #13595
Opened 2019-06-17 15:27 UTC by milljm

Update package_version to use latest available moose-environment.

Closes #13594

2019-06-17 16:20 UTC, moosebuild commented
Job [Documentation](https://civet.inl.gov/job/354129/) on 8c526e6 wanted to post the following:

View the site [here](https://mooseframework.inl.gov/docs/PRs/13595/site)

This comment will be updated on new commits.

2019-06-17 17:46 UTC, milljm commented
I have more to add... based on user issues during MOOSE workshop.

2019-06-17 17:55 UTC, milljm commented
PLEASE ALERT ME BEFORE CLICKING MERGE.

Before clicking merge on this PR, I must move the files into position on the mooseframework.org server.

2019-06-17 19:26 UTC, cticenhour requested changes
The bits about bash profile modifications look good! My comments were all grammatical. Thanks again for doing this!

2019-06-17 19:26 UTC, cticenhour commented on modules/doc/content/getting_started/installation/mac_pre_req.md
> +- The first being available after clicking 'Customize' during the install. While in this pane, check the option "MOOSE Environment", and then continue by clicking 'Install'.
`The first being available` --> `The first is available` ?

2019-06-17 19:26 UTC, cticenhour commented on modules/doc/content/getting_started/installation/mac_pre_req.md
> +- The second, is after the installer has completed you will be presented with a pop-up window alerting you to either allow the installer to make this change, or to do nothing. If you choose 'Cancel'
Remove comma after `The second` and add `, where` after `completed`

2019-06-18 18:22 UTC, permcody approved these changes

2019-06-18 18:22 UTC, merged