fix AD symmetricEigenvaluesEigenvectors dead loop
idaholab/moose pull request #13653
Opened 2019-06-26 17:10 UTC by hugary1995

Kill the loop when it is not converging. Using an off-diagonal shift if diagonal entries are all zero.

refs #13652

2019-06-26 17:12 UTC, dschwen commented on framework/src/utils/RankTwoTensor.C
> +        shift = std::max(D(m - 1, m), shift);
just do nested max

2019-06-26 17:12 UTC, dschwen requested changes

2019-06-26 17:12 UTC, dschwen commented on framework/src/utils/RankTwoTensor.C
> +      if (iter > 100)
please make this a `mooseException` instead

2019-06-26 17:13 UTC, dschwen commented on framework/src/utils/RankTwoTensor.C
> +      if (iter > 100)
I mean the `mooseError` below, of course

2019-06-26 17:57 UTC, moosebuild commented
Job [Documentation](https://civet.inl.gov/job/358963/) on ac4f477 wanted to post the following:

View the site [here](https://mooseframework.inl.gov/docs/PRs/13653/site)

This comment will be updated on new commits.

2019-06-26 17:58 UTC, dschwen commented
Can you please add a test case in the unit tests where the diagonal is zero?

2019-06-26 18:00 UTC, dschwen commented
Funny enough I may have run into this issue already! I had some random models freeze up after converting them to AD...

2019-06-26 18:30 UTC, hugary1995 commented
Sure, there are also a few other test cases missing for this. I'll add them.

2019-07-01 13:06 UTC, hugary1995 commented
I've tried my best, there are simply some cases that don't work. The two failing cases have correct values but incorrect derivatives. I cannot say that the chance for those two failing cases to happen is negligible, but all my use cases work fine with the current version. Perhaps you can test this on your previously frozen application?

=====================
Good: three non-zero eigenvalues
        39.8272 {   13  }       -4.30189 {   -9  }        8.41378 {    2  }
       -4.30189 {   -9  }        20.5534 {  -22  }         4.3064 {    1  }
        8.41378 {    2  }         4.3064 {    1  }       -2.38058 {   70  }
=====================
Good: two non-zero eigenvalues
        40.0252 {   13  }       -4.10753 {   -9  }        7.45827 {    2  }
       -4.10753 {   -9  }        20.7442 {  -22  }        3.36843 {    1  }
        7.45827 {    2  }        3.36843 {    1  }        2.23063 {   70  }
=====================
Bad: One non-zero eigenvalues
        39.7135 {   13  }       -6.58244 {-57.1785  }        6.89027 {-44.0261  }
       -6.58244 {-57.1785  }        1.09103 {41.1494  }       -1.14205 {-1.88723  }
        6.89027 {-44.0261  }       -1.14205 {-1.88723  }        1.19546 {6.85064  }
=====================
Good: Diagonal matrix
             42 {   13  }   -5.85031e-16 {   -9  }              0 {    2  }
   -5.85031e-16 {   -9  }             21 {  -22  }              0 {    1  }
              0 {    2  }              0 {    1  }              0 {   70  }
=====================
Good: Off-diagonal matrix
   -5.41789e-14 {   13  }              5 {   -9  }              0 {    2  }
              5 {   -9  }    5.24025e-14 {  -22  }              0 {    1  }
              0 {    2  }              0 {    1  }              0 {   70  }
=====================
Bad: zero matrix
              0 { -4.5  }              0 {   -9  }              0 {    0  }
              0 {   -9  }              0 { -4.5  }              0 {    0  }
              0 {    0  }              0 {    0  }              0 {   70  }

2019-07-01 13:36 UTC, dschwen commented
Are we even sure the eigen decomposition is differentiable in those cases?

2019-07-01 13:49 UTC, hugary1995 commented
That's a good question, in general I think when two eigenvalues are the same, the projection is non-differentiable. You can see that in the hand-coded version, i.e. "positiveProjectionEigenDecomposition", we have an approximation using L'Hopital's rule in case of equal eigenvalues:

```c++
T theta_ab;
if (!MooseUtils::absoluteFuzzyEqual(eigval[a], eigval[b]))
  theta_ab = 0.5 * (epos[a] - epos[b]) / (eigval[a] - eigval[b]);
else
  theta_ab = 0.25 * (d[a] + d[b]);

proj_pos += theta_ab * (Gab + Gba);
```

I thought AD can catch this case automatically but now I think I might be wrong. Actually all the failing cases have repeated eigenvalues.

2019-07-01 13:56 UTC, dschwen commented
In https://www.win.tue.nl/analysis/reports/rana06-33.pdf the derivatives are derived only for non-defective matrices (that paper is also referenced in [this tensorflow issue]). This PR seems to be an improvement. Let me see if I can replicate my freezes.

2019-08-07 01:37 UTC, closed without merging