SQA tags for plane strain tests.
idaholab/moose pull request #13662
Opened 2019-06-28 20:02 UTC by jasondhales

#13634

2019-06-28 21:03 UTC, moosebuild commented
Job [Documentation](https://civet.inl.gov/job/360053/) on 39ae550 wanted to post the following:

View the site [here](https://mooseframework.inl.gov/docs/PRs/13662/site)

This comment will be updated on new commits.

2019-07-01 21:12 UTC, gambka requested changes

2019-07-02 15:03 UTC, jasondhales commented on modules/tensor_mechanics/test/tests/generalized_plane_strain/tests
> +    requirement = 'The system shall support a traditional plane strain mechanics solution'
As discussed, this language follows the example of other MOOSE tests.

2019-07-02 15:04 UTC, jasondhales commented on modules/tensor_mechanics/test/tests/generalized_plane_strain/tests
> +    requirement = 'The system shall support a traditional plane strain mechanics solution where the out of plane strain is prescribed'
Fixed.

2019-07-02 15:04 UTC, jasondhales commented on modules/tensor_mechanics/test/tests/radial_disp_aux/tests
> +    requirement = 'The system shall report an error if "axis_vector" is has length of zero'
Fixed.

2019-07-02 18:10 UTC, gambka approved these changes
Looks good to me.

2019-07-08 18:41 UTC, permcody approved these changes

2019-07-08 18:41 UTC, merged