Reimplement the coupling between scalar out-of-plane strain with disps
idaholab/moose pull request #13693
Opened 2019-07-04 20:26 UTC by hchen139

Use casheJacobianBlock() rather than reference to jacobianBlock() to avoid element matrix constraint failure.

Ref #13656

2019-07-04 20:27 UTC, hchen139 commented
@bwspenc The same has been done for PD gps models

2019-07-04 21:07 UTC, moosebuild commented
Job [Documentation](https://civet.inl.gov/job/362513/) on 442a4f3 wanted to post the following:

View the site [here](https://mooseframework.inl.gov/docs/PRs/13693/site)

This comment will be updated on new commits.

2019-07-09 14:51 UTC, moosebuild commented
All [jobs](https://civet.inl.gov/event/43822/) on 442a4f3 : invalidated by @permcody

networking issues fixed

2019-07-16 15:59 UTC, fdkong requested changes

2019-07-16 16:02 UTC, fdkong commented
Never mind. I had a right fix instead of hacking.

2019-07-16 16:02 UTC, fdkong submitted a review, later dismissed

2019-07-16 16:02 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/368455/) on 6a1a856 wanted to post the following:

Your code requires style changes.  

A patch was auto generated and copied [here](https://mooseframework.inl.gov/docs/PRs/13693/style.patch)  
You can directly apply the patch by running, in the top level of your repository:

`curl -s https://mooseframework.inl.gov/docs/PRs/13693/style.patch | git apply -v`  

Alternatively, with your repository up to date and in the top level of your repository:

`git clang-format cfcf841ec59b526ac8b1c538a1cb1b50a8811b22`

2019-07-16 18:07 UTC, moosebuild commented
Job [Modules debug PETSc alt](https://civet.inl.gov/job/368487/) on 58b5942 : invalidated by @fdkong

TIMEOUT phase_field/test:initial_conditions.PolycrystalVoronoiVoidIC_periodic_fromfile FAILED (TIMEOUT)

2019-07-16 19:48 UTC, fdkong approved these changes

2019-07-16 19:48 UTC, merged