Improve AtoZ index in MooseDocs
idaholab/moose pull request #13742
Opened 2019-07-16 14:01 UTC by aeslaughter

2019-07-16 14:47 UTC, moosebuild commented
Job [Documentation](https://civet.inl.gov/job/367924/) on 182abef wanted to post the following:

View the site [here](https://mooseframework.inl.gov/docs/PRs/13742/site)

This comment will be updated on new commits.

2019-07-17 01:15 UTC, WilkAndy requested changes
This all looks almost perfect, thank you for your super fast response!  The only problem is the alphabetizing isn't quite right!  If you look at

https://mooseframework.inl.gov/docs/PRs/13742/site/modules/porous_flow/contents.html

you'll see the alphabet goes ACBEDGFIH, etc.

2019-07-17 02:27 UTC, aeslaughter commented
That is how we do it up here in the north...I am not sure how I messed up the alphabet, it is a new low for me. I will get if fixed up.

2019-07-17 19:24 UTC, permcody approved these changes

2019-07-17 22:35 UTC, merged

2019-07-17 22:50 UTC, WilkAndy commented
Thanks for this, @aeslaughter