Do we need ``checkLinearConvergence"? Looks like we never use it
idaholab/moose pull request #13822
Opened 2019-07-29 23:01 UTC by fdkong

Closes #11970

2019-07-29 23:01 UTC, fdkong commented
Curious about if or not we are actually using `checkLinearConvergence`.

2019-07-29 23:03 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/374700/) on 34d743b wanted to post the following:

Your code requires style changes.  

A patch was auto generated and copied [here](https://mooseframework.inl.gov/docs/PRs/13822/style.patch)  
You can directly apply the patch by running, in the top level of your repository:

`curl -s https://mooseframework.inl.gov/docs/PRs/13822/style.patch | git apply -v`  

Alternatively, with your repository up to date and in the top level of your repository:

`git clang-format 1b741a9a5513b38e1936582219af19678d62db04`

2019-07-29 23:23 UTC, fdkong commented
I remembered we were actually using this function.

2019-07-29 23:50 UTC, moosebuild commented
Job [Documentation](https://civet.inl.gov/job/374725/) on e1dadac wanted to post the following:

View the site [here](https://mooseframework.inl.gov/docs/PRs/13822/site)

This comment will be updated on new commits.

2019-07-30 15:22 UTC, fdkong commented
@idaholab/moose-team  Anyone happens to know why we introduced  `FEProblemBase::checkLinearConvergence` at the first place? I was asking because it looks like we do not call this function by default.

2019-07-30 19:29 UTC, friedmud commented
I think it's used in some of the custom problems.  Check with the BISON
guys.

On Tue, Jul 30, 2019 at 9:22 AM Fande Kong <notifications@github.com> wrote:

> @idaholab/moose-team <https://github.com/orgs/idaholab/teams/moose-team>
> Anyone happens to know why we introduced
> FEProblemBase::checkLinearConvergence at the first place? I was asking
> because it looks like we do not call this function by default.
>
> —
> You are receiving this because you are on a team that was mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/idaholab/moose/pull/13822?email_source=notifications&email_token=AAGUSMJ76LMQV5FGHUKZHQ3QCBMB3A5CNFSM4IHW5KUKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD3EKWCY#issuecomment-516467467>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AAGUSMJ6ENXPYYWA2XI7FD3QCBMB3ANCNFSM4IHW5KUA>
> .
>

2019-07-30 19:34 UTC, fdkong commented
> I think it's used in some of the custom problems. Check with the BISON guys

@bwspenc Are you using this function? `FEProblemBase::checkLinearConvergence`

2019-07-31 22:19 UTC, fdkong commented
I did NOT see anything in bison.

2019-10-11 20:32 UTC, fdkong commented
@lindsayad  I just deleted the linear checker without any issue. Do you know why we need a customized linear checker? Who is using it?

2019-10-11 20:34 UTC, lindsayad commented
I don’t know. I agree that we should just delete it if we can

> On Oct 11, 2019, at 1:32 PM, Fande Kong <notifications@github.com> wrote:
> 
> @lindsayad I just deleted the linear checker without any issue. Do you know why we need a customized linear checker? Who is using it?
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or unsubscribe.

2019-10-11 20:36 UTC, fdkong commented
> I don’t know. I agree that we should just delete it if we can

OK. I am going to delete it. I believe civet will tell us if we are able to do that.

2019-10-11 20:41 UTC, fdkong commented
OK. We should just delete it.

2019-10-11 22:48 UTC, lindsayad requested changes

2019-10-11 22:48 UTC, lindsayad commented on framework/src/executioners/FEProblemSolve.C
> -  params.addDeprecatedParam<Real>(
Rattlesnake is failing because of this deletion

2019-10-11 22:48 UTC, lindsayad commented on framework/src/problems/FEProblemBase.C
> +      // oss << "Converged due to function norm " << fnorm << " < "
Why did you comment this out? I don't think we want to do this...?

2019-10-11 22:48 UTC, lindsayad commented on framework/src/utils/PetscSupport.C
> +  /*{
Instead of commenting this out, we just want to remove it right?

2019-10-15 20:53 UTC, fdkong commented
I do not see any user case right now. And PETSc does not call the linear checker from v3.10.

It is better to just remove it to avoid confusing.

2019-10-15 23:18 UTC, fdkong commented
@lindsayad  It is ready for review

2019-10-16 01:44 UTC, lindsayad approved these changes

2019-10-16 01:44 UTC, merged