Petsc option database, and Picard iteration using Eigen executioner
idaholab/moose pull request #13839
Opened 2019-07-31 19:01 UTC by fdkong

(1) Support PETSc option database  #13623

(2) Support Picard iteration in eigen executioner    #12767. Eigen executioner can serve as a  master or a sub.

2019-07-31 19:09 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/375676/) on 7036f35 wanted to post the following:

Your code requires style changes.  

A patch was auto generated and copied [here](https://mooseframework.inl.gov/docs/PRs/13839/style.patch)  
You can directly apply the patch by running, in the top level of your repository:

`curl -s https://mooseframework.inl.gov/docs/PRs/13839/style.patch | git apply -v`  

Alternatively, with your repository up to date and in the top level of your repository:

`git clang-format 7fbfb28125c4f5c0e6dc7ed3c069a941228faaf5`

2019-07-31 19:54 UTC, moosebuild commented
Job [Documentation](https://civet.inl.gov/job/375701/) on 860e65b wanted to post the following:

View the site [here](https://mooseframework.inl.gov/docs/PRs/13839/site)

This comment will be updated on new commits.

2019-08-06 14:11 UTC, moosebuild commented
Job [Test PETSc master](https://civet.inl.gov/job/375719/) on 860e65b : invalidated by @fdkong

Verify if it compiles against  petsc-master

2019-08-07 22:09 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/378558/) on 3e95ade wanted to post the following:

Your code requires style changes.  

A patch was auto generated and copied [here](https://mooseframework.inl.gov/docs/PRs/13839/style.patch)  
You can directly apply the patch by running, in the top level of your repository:

`curl -s https://mooseframework.inl.gov/docs/PRs/13839/style.patch | git apply -v`  

Alternatively, with your repository up to date and in the top level of your repository:

`git clang-format 03d4a4ef4da9da23830045ec74fa9caf3cc0a767`

2019-08-07 22:21 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/378619/) on 1778865 wanted to post the following:

Your code requires style changes.  

A patch was auto generated and copied [here](https://mooseframework.inl.gov/docs/PRs/13839/style.patch)  
You can directly apply the patch by running, in the top level of your repository:

`curl -s https://mooseframework.inl.gov/docs/PRs/13839/style.patch | git apply -v`  

Alternatively, with your repository up to date and in the top level of your repository:

`git clang-format 03d4a4ef4da9da23830045ec74fa9caf3cc0a767`

2019-08-20 22:49 UTC, moosebuild commented
Job [Test PETSc master](https://civet.inl.gov/job/378674/) on 1196e38 : invalidated by @fdkong

Check if new PETSc URL works

2019-10-15 21:22 UTC, fdkong commented
I need to get this in

2019-10-17 19:40 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/412309/) on 3cb2f01 wanted to post the following:

Your code requires style changes.  

A patch was auto generated and copied [here](https://mooseframework.inl.gov/docs/PRs/13839/style.patch)  
You can directly apply the patch by running, in the top level of your repository:

`curl -s https://mooseframework.inl.gov/docs/PRs/13839/style.patch | git apply -v`  

Alternatively, with your repository up to date and in the top level of your repository:

`git clang-format fea29a7f040f75258bfb0226955b54a09eb4be89`

2019-10-18 01:43 UTC, lindsayad requested changes
Looks good other than the small suggestions

2019-10-18 01:43 UTC, lindsayad commented on framework/include/systems/NonlinearEigenSystem.h
> +  NumericVector<Number> & ResidualVectorAX();
This method name should start lower case to distinguish it from a class and to be consistent with our style

2019-10-18 01:43 UTC, lindsayad commented on framework/include/systems/NonlinearEigenSystem.h
> +  NumericVector<Number> & ResidualVectorBX();
Same here

2019-10-18 20:40 UTC, lindsayad approved these changes

2019-10-18 21:34 UTC, merged