PorousFlow doesn't need to use RDG
idaholab/moose pull request #13872
Opened 2019-08-08 08:46 UTC by cpgr

Closes #13871

2019-08-08 09:25 UTC, moosebuild commented
Job [Documentation](https://civet.inl.gov/job/378802/) on 3df1825 wanted to post the following:

View the site [here](https://mooseframework.inl.gov/docs/PRs/13872/site)

This comment will be updated on new commits.

2019-08-08 12:52 UTC, andrsd requested changes
You also need to modify `modules.mk`
1. there is a section like this:
    ```
    ifeq ($(POROUS_FLOW),yes)
            TENSOR_MECHANICS            := yes
            FLUID_PROPERTIES            := yes
            CHEMICAL_REACTIONS          := yes
            RDG                         := yes
    endif
    ```
    So, remove the RDG line from there.

2. Another section below looks like:
    ```
    ifeq ($(POROUS_FLOW),yes)
      APPLICATION_DIR    := $(MOOSE_DIR)/modules/porous_flow
      APPLICATION_NAME   := porous_flow

      DEPEND_MODULES     := tensor_mechanics fluid_properties chemical_reactions rdg
      SUFFIX             := pflow
      include $(FRAMEWORK_DIR)/app.mk
    endif
    ```
    So remove `rdg` from `DEPEND_MODULES`.

2019-08-08 15:52 UTC, permcody submitted a review, later dismissed

2019-08-08 21:52 UTC, cpgr commented
Thanks @andrsd. I couldn't find that bit in the Makefile

2019-08-09 13:12 UTC, andrsd approved these changes

2019-08-09 13:13 UTC, merged