Complete requirements for the framework
idaholab/moose pull request #13917
Opened 2019-08-16 00:44 UTC by aeslaughter

2019-08-16 00:44 UTC, aeslaughter commented
@permcody I made some mistake with a rebase, I will fix it next week.

2019-08-16 00:46 UTC, aeslaughter commented
```
test/tests
                   Complete: 100.0%
      Total Number of Files: 720
    Files with Requirements: 0
      Total Number of Tests: 1873
    Tests with Requirements: 1784
           Deprecated Tests: 89
            Tests Remaining: 0
```

2019-08-16 01:23 UTC, moosebuild commented
Job [Documentation](https://civet.inl.gov/job/383545/) on 922f903 wanted to post the following:

View the site [here](https://mooseframework.inl.gov/docs/PRs/13917/site)

This comment will be updated on new commits.

2019-08-20 19:09 UTC, permcody requested changes
Let's get issues into those last few tests. If you look at them in the diff view they all seem to be clustered at the bottom.

2019-08-20 19:09 UTC, permcody commented on test/tests/variables/block_aux_kernel/tests
> +  issues = ''
Odd - from here on down you supplied no issue. I thought MooseDocs didn't allow this anymore?

2019-08-20 19:09 UTC, permcody commented on test/tests/postprocessors/vector_postprocessor_comparison/tests
> +[]
It looks like you have a lot of files without newlines now. It'd be nice to fix these up.

2019-08-20 21:13 UTC, permcody submitted a review, later dismissed

2019-08-20 23:06 UTC, permcody approved these changes

2019-08-21 15:14 UTC, merged