Improve jvar map interface
idaholab/moose pull request #13956
Opened 2019-08-22 22:32 UTC by dschwen

Closes #13951

2019-08-22 23:17 UTC, moosebuild commented
Job [Documentation](https://civet.inl.gov/job/386833/) on 1b2210b wanted to post the following:

View the site [here](https://mooseframework.inl.gov/docs/PRs/13956/site)

This comment will be updated on new commits.

2019-08-23 16:11 UTC, permcody requested changes
Typo!

2019-08-23 16:11 UTC, permcody commented on test/tests/interfaces/jvarmap/tests
> +    requirement = 'The system shall buyild a bijective map between variable numbers and their couple variable indices.'
buyild -> build

2019-08-23 16:18 UTC, dschwen commented on test/tests/interfaces/jvarmap/tests
> +    requirement = 'The system shall buyild a bijective map between variable numbers and their couple variable indices.'
Noooooooooooooooooo!

2019-08-23 18:21 UTC, permcody approved these changes

2019-08-23 21:26 UTC, dschwen commented
<sub>preeeessss theeeee buuuutooon...</sub>

2019-08-24 00:00 UTC, permcody commented
You can always merge an approved PR even if it’s your own. Also you have merge rights in general but I’ll hit the button for you.

2019-08-24 00:00 UTC, merged

2019-08-24 01:49 UTC, dschwen commented
Ok, good to know. Thanks!