Use SMP full by default with solve_type=LINEAR
idaholab/moose pull request #14066
Opened 2019-09-19 18:20 UTC by loganharbour

Closes #14065

As it seems like the tests are passing (nothing using `LINEAR` with coupling), there should probably be a simple test for this. Will add in a bit.

2019-09-19 19:47 UTC, moosebuild commented
Job [Documentation](https://civet.inl.gov/job/399662/) on c613756 wanted to post the following:

View the site [here](https://mooseframework.inl.gov/docs/PRs/14066/site)

This comment will be updated on new commits.

2019-09-19 22:15 UTC, moosebuild commented
Job [Modules debug PETSc submodule](https://civet.inl.gov/job/399677/) on c613756 : invalidated by @permcody

Bitbucket opened

2019-09-19 22:15 UTC, moosebuild commented
Job [Test debug PETSc submodule](https://civet.inl.gov/job/399679/) on c613756 : invalidated by @permcody

Bitbucket opened

2019-09-20 20:08 UTC, friedmud requested changes
Needs a test.

Find a test that will give the wrong answer if the jacobian isn't there.  Even just a coupled convection diffusion something.

2019-09-25 20:22 UTC, loganharbour commented
@friedmud good now, but not sure what to put for design in tests.

2019-10-21 18:30 UTC, friedmud approved these changes
👍

2019-10-21 18:30 UTC, merged