Update SparseOps.h to add missing #endif
idaholab/moose pull request #14081
Opened 2019-09-24 18:19 UTC by veeshy

Closes #14080

2019-09-24 18:30 UTC, andrsd requested changes

2019-09-24 18:30 UTC, andrsd commented on framework/include/utils/SparseOps.h
> +#endif
This should be moved 2 lines up.

2019-09-24 18:55 UTC, andrsd commented
It is still wrong. You moved it just 1 line up. There are 2 `{` outside the `#ifdef`, so there needs to be 2 `}` after the `#endif`.

And,  please, squash the patches into a single commit, we really do not need 3 commits for a one line change...

2019-09-24 19:35 UTC, veeshy commented
Third try is the charm ::facepalm::, also made it back into 1 commit

2019-09-25 13:05 UTC, andrsd commented
BTW: you need to reference the issue number in your commit message, the precheck will fail if it is just in the PR description...

2019-09-25 17:23 UTC, veeshy commented
Tagged the issue in the commit

2019-09-25 17:24 UTC, andrsd approved these changes

2019-09-25 18:02 UTC, moosebuild commented
Job [Documentation](https://civet.inl.gov/job/401900/) on f56053b wanted to post the following:

View the site [here](https://mooseframework.inl.gov/docs/PRs/14081/site)

This comment will be updated on new commits.

2019-09-25 19:10 UTC, merged