Allow use of coupled chemical potential in split Cahn-Hilliard equation
idaholab/moose pull request #14202
Opened 2019-10-21 19:16 UTC by dschwen

With this users can implement the terms containing off-diagonal the Onsager phenomenological transport matrix coefficients.

Closes #14140

2019-10-21 20:09 UTC, moosebuild commented
Job [Documentation](https://civet.inl.gov/job/414183/) on 0bcf88c wanted to post the following:

View the site [here](https://mooseframework.inl.gov/docs/PRs/14202/site)

This comment will be updated on new commits.

2019-10-22 14:05 UTC, dschwen commented
There seems to be some communication error between civet and github. All tests passed. @milljm

2019-10-22 14:09 UTC, milljm commented
The server in which Civet is running, is slow at times. Indeed, more often than not, I have to re-send my webhook payload when I create a PR into the package_builder. This sort of communication issue seems to increase depending on how many targets there are.

2019-10-22 16:18 UTC, permcody submitted a review, later dismissed

2019-10-22 16:29 UTC, laagesen requested changes
Looks good, just a couple of typos

2019-10-22 16:29 UTC, laagesen commented on modules/phase_field/test/tests/phase_field_kernels/SplitCHWRes.i
> +# with two concentration variables and cuopling through off-diagonal Onsager
typo cuopling

2019-10-22 16:29 UTC, laagesen commented on modules/phase_field/doc/content/source/kernels/SplitCHWRes.md
> +phenomenologicsal transport coefficients model the driving force resulting from
typo phenomenologicsal

2019-11-03 16:43 UTC, moosebuild commented on libmesh
> +Subproject commit 5db42ee857f6f5e1ab522c7f2ca8ae599f1e8b56
**Caution!** This contains a submodule update

2019-11-04 15:50 UTC, permcody approved these changes

2019-11-04 15:50 UTC, merged