Migrate a set of glued contact tests in combined to use TM
idaholab/moose pull request #14402
Opened 2019-11-19 19:52 UTC by recuero

ref #6978

2019-11-19 19:59 UTC, bwspenc commented
@permcody Could you please add @recuero to the INL developers group?  He's a new employee in our department.

2019-11-19 20:38 UTC, bwspenc requested changes
Just a few changes.  Looks good!

2019-11-19 20:38 UTC, bwspenc commented on modules/combined/test/tests/glued_contact/sm/glued_contact_mechanical_constraint_test_sm.i
> +  #petsc_options_iname = '-pc_type -pc_hypre_type -snes_type -snes_ls -snes_linesearch_type -ksp_gmres_restart'
Remove commented out lines

2019-11-19 20:38 UTC, bwspenc commented on modules/combined/test/tests/glued_contact/sm/glued_contact_mechanical_constraint_test_sm.i
> +
remove this blank line

2019-11-19 20:38 UTC, bwspenc commented on modules/combined/test/tests/glued_contact/sm/glued_contact_test_sm.i
> +  #petsc_options_iname = '-pc_type -pc_hypre_type -snes_type -snes_ls -snes_linesearch_type -ksp_gmres_restart'
Remove commented out lines

2019-11-19 21:00 UTC, recuero commented
Suggested format changes included in amended commit.

2019-11-19 21:21 UTC, bwspenc approved these changes

2019-11-20 20:09 UTC, moosebuild commented
Job [Documentation](https://civet.inl.gov/job/434040/) on 6e62668 wanted to post the following:

View the site [here](https://mooseframework.inl.gov/docs/PRs/14402/site)

This comment will be updated on new commits.

2019-11-20 21:28 UTC, moosebuild commented
Job [Boost enabled, Pthreads only](https://civet.inl.gov/job/434036/) on 6e62668 : invalidated by @bwspenc

Failures unrelated to this PR

2019-11-21 20:18 UTC, moosebuild commented
Job [Documentation](https://civet.inl.gov/job/434040/) on 6e62668 : invalidated by @bwspenc

Showing up as pending after the tests seem to be run successfully

2019-11-21 22:51 UTC, merged