Migrate tests in combined module to Tensor Mechanics.
idaholab/moose pull request #14431
Opened 2019-11-22 20:05 UTC by recuero

Refs. #6978.

2019-11-22 22:14 UTC, dschwen commented on modules/combined/test/tests/catch_release/catch_release.i
> +    use_displaced_mesh = true
I would strongly suggest to set these tests up with the Master action rather than the old deprecated action.

2019-11-22 22:14 UTC, dschwen commented on modules/combined/test/tests/catch_release/catch_release.i
>      variable = stress_yy
This block would be generated automatically with the master action with 

```
generate_outputs = 'stress_yy'
```

2019-11-22 22:15 UTC, dschwen commented on modules/combined/test/tests/catch_release/catch_release.i
> +  [../]
those classes could just be active on both block 1 and 2!

2019-11-22 22:16 UTC, dschwen commented on modules/combined/test/tests/catch_release/sm/catch_release_sm.i
> +  [../]
Master action creates those variables for you with 
```
add_variables = true
```

2019-11-22 22:16 UTC, dschwen commented on modules/combined/test/tests/catch_release/sm/catch_release_sm.i
> +[]
again, this block and the aux kernel below would be created by the master action

2019-11-22 22:17 UTC, dschwen commented on modules/combined/test/tests/catch_release/sm/catch_release_sm.i
> +  [../]
Oh, wait, this one is solid mechanics test...

2019-11-22 22:18 UTC, dschwen commented on modules/combined/test/tests/contact/4ElemTensionRelease.i
> +    block = '2'
as above no need to have two identical materials block restricted to different blocks. There should only be one ComputeSmallStrain and one ComputeLinearElasticStress. The ComputeSmallStrain should be added through the master action.

2019-11-22 22:19 UTC, dschwen commented on modules/combined/test/tests/power_law_hardening/PowerLawHardening.i
> +  [../]
Here the variable should be set up by the master action

2019-11-22 22:20 UTC, dschwen commented on modules/combined/test/tests/power_law_hardening/PowerLawHardening.i
> +  file_base = PowerLawHardening_out
why is a file base specified here?

2019-11-22 22:23 UTC, dschwen requested changes
I'd like to see the master action used in the TM tests. Please avoid the use of file_base in tests and make sure the block names in the `tests` file are the same as the .i names (where possible - sometimes cli_args require a name postfix) and use the default output file names. These guidelines make it much easier to find the input and output files for a given test (i.e. you see a failure in run_tests and know what input_and file to look at without digging through a tests file.

2019-11-23 17:37 UTC, recuero commented
@dschwen  Changes made.

2019-11-23 20:32 UTC, dschwen commented
Ok, thanks for the changes. Did you talk with @bwspenc about this? I see a lot of added(?) solid mechanics tests here. What's the idea here? I though we wanted to get rid of stuff, but this PR adds stuff.

2019-11-23 22:14 UTC, recuero commented
Yes. For each existing SM test, there is now an additional, equivalent TM test. The SM tests are in an 'sm' folder which will be deleted whenever final removal happens. I think the idea is to keep having coverage for deprecated modules/formulations until we pull the plug.

2019-11-25 17:52 UTC, moosebuild commented
Job [Documentation](https://civet.inl.gov/job/435608/) on 83a0b1c wanted to post the following:

View the site [here](https://mooseframework.inl.gov/docs/PRs/14431/site)

This comment will be updated on new commits.

2019-12-14 07:02 UTC, bwspenc approved these changes

2019-12-16 16:41 UTC, dschwen approved these changes

2019-12-16 16:41 UTC, merged