Initial inclusion of standards document Ref #14513
idaholab/moose pull request #14514
Opened 2019-12-11 20:58 UTC by tophmatthews

This just captures the standards document I shared earlier. It'll need a bit of work, and decisions are needed to add what where, but it's something to start talking over. @novasr @permcody @bwspenc @dschwen

2019-12-11 21:42 UTC, moosebuild commented
Job [Documentation](https://civet.inl.gov/job/443410/) on b7a797b wanted to post the following:

View the site [here](https://mooseframework.inl.gov/docs/PRs/14514/site)

This comment will be updated on new commits.

2019-12-14 07:31 UTC, bwspenc commented on modules/doc/content/framework_development/code_standards.md
> +-	Utility::pow<n> shall be used in place of std::pow(x,n) if the power is constant
if the power is a constant integer.  If the power is non-constant integer, use MathUtils::pow(x,n).

2019-12-14 07:32 UTC, bwspenc commented on modules/doc/content/framework_development/code_standards.md
> +-	MOOSE SQA standards shall always be followed
I think this needs to be more specific.

2019-12-14 07:33 UTC, bwspenc commented on modules/doc/content/framework_development/code_standards.md
> +-	Default values shall be overridden in the test file whenever possible.
Not sure what you mean by this. Do you mean in the .i file or the 'tests' file.  Also, why is that important?

2019-12-14 07:35 UTC, bwspenc commented on modules/doc/content/framework_development/code_standards.md
> +-	All input files should be as simple as possible, with any unnecessary physics, input file fluff, and variables removed (e.g. `solve = false` for tests on materials only)
I definitely agree that making tests that are as close to unit tests as possible is good, but it's probably to say that 'all input files' should do that. We also need integration tests (as you say below)

2020-01-13 20:48 UTC, bwspenc commented
Not stale. This just needs a small amount of tweaking.

2020-02-03 16:23 UTC, dschwen requested changes

2020-02-03 16:23 UTC, dschwen commented on modules/doc/content/framework_development/code_standards.md
> +-	Input parameters should always use MooseEnum instead of unsigned int
Needs to be more specific. Maybe "input parameters accepting a finite set of permitted options" (then again the number of unsigned int values is finite as well :-D )

2020-02-03 16:23 UTC, dschwen commented on modules/doc/content/framework_development/code_standards.md
> +    - The only exceptions are for inline functions for speed and templates.
"inline functions for speed" is misleading. This is not what inline does these days (it is what it used to do in the '90s :-D)

2020-02-03 16:23 UTC, dschwen commented on modules/doc/content/framework_development/code_standards.md
> +- Thou shall use range-based loops or MooseIndex() based loops for iteration
Yeah, cute, but not appropriate language for a document like this

2020-02-03 16:23 UTC, dschwen commented on modules/doc/content/framework_development/code_standards.md
> +-	mooseException should be used in favor of mooseError when checking run time conditions
No. It should be used where aborting a solve could recover from the error.

2020-02-03 16:23 UTC, dschwen commented on modules/doc/content/framework_development/code_standards.md
> +-	Hand calculations, either as simple comments in the input file, added as functions in the input file, or in an adjoining python/excel file should always be included where possible. The equations us
I'd rather leave excel out of this document. Python covers us fully and can be run automatically by the test harness.

2020-02-03 16:23 UTC, dschwen commented on modules/doc/content/framework_development/code_standards.md
> +-	All tests should be tested using CSVDiff unless Exodiff is required to capture the change during the simulation caused by the new code.
Hard to say that in advance. We mainly want to protect against breakage from _future_ modifications. I'd strike this point or weaken it considerably.

2020-02-03 16:23 UTC, dschwen commented on modules/doc/content/framework_development/code_standards.md
> +- Best practices used for journal publications should be adopted
at least provide a link to such a best practices document

2020-02-03 18:54 UTC, tophmatthews commented
All great suggestions @dschwen. My original intent was to get up a document we discussed on a call with @bwspenc, @permcody, and @novasr, and have everyone contribute. That document was targeted for BISON originally, but @permcody identified most of the bullets are relevant to all MOOSE apps. How about everyone just adding/removing the things you think relevant directly? I think you all can do that to my branch?

2020-03-05 20:59 UTC, permcody commented
I don't want to lose this. @tophmatthews - do you want me to take ownership of this? I can push changes that I want (and incorporate Ben and Daniel's) ideas as well. I think most of what you have is fine. I might change a few things, but I do want most of this at the MOOSE level.

2020-03-10 14:22 UTC, tophmatthews commented
> do you want me to take ownership of this

That would be great @permcody, it's probably better this says what you'd like to see. Thanks!

2020-04-10 22:49 UTC, closed without merging