Salt properties Cp and Cv derivatives and missing AD functions
idaholab/moose pull request #14566
Opened 2020-01-02 22:25 UTC by aprilnovak

Adds `Cp` and `Cv` derivatives with respect to `v` and `e` to flibe and flinak fluid properties, as well as `DualReal` versions of the `p_from_v_e`, `T_from_v_e`, and `rho_from_p_T` functions.

Refs #14565

2020-01-02 22:26 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/449159/) on 9c5d6b9 wanted to post the following:

Your code requires style changes.  

A patch was auto generated and copied [here](https://mooseframework.inl.gov/docs/PRs/14566/style.patch)  
You can directly apply the patch by running, in the top level of your repository:

`curl -s https://mooseframework.inl.gov/docs/PRs/14566/style.patch | git apply -v`  

Alternatively, with your repository up to date and in the top level of your repository:

`git clang-format a5c9234557f71bcf7c923fba2a2e9cd278c932c8`

2020-01-06 15:00 UTC, andrsd requested changes

2020-01-06 15:02 UTC, andrsd commented
Adding the `override` should fix the doco target. Then, we can merge...

2020-01-06 17:12 UTC, aprilnovak commented on modules/fluid_properties/include/userobjects/FlibeFluidProperties.h
> +                           DualReal & dcv_de) const;
good catch, thanks!

2020-01-06 17:31 UTC, andrsd commented on modules/fluid_properties/include/userobjects/FlibeFluidProperties.h
> +                           DualReal & dcv_de) const;
That was actually caught by CIVET :-) That's why the doco target failed...

2020-01-06 17:32 UTC, andrsd approved these changes

2020-01-06 18:02 UTC, moosebuild commented
Job [Documentation](https://civet.inl.gov/job/449657/) on a1a5982 wanted to post the following:

View the site [here](https://mooseframework.inl.gov/docs/PRs/14566/site)

This comment will be updated on new commits.

2020-01-07 15:05 UTC, merged