Updated test to work with PETSc 3.11.4, closes issue #14598
idaholab/moose pull request #14620
Opened 2020-01-21 21:53 UTC by frombs

2020-01-21 23:46 UTC, moosebuild commented
Job [Documentation](https://civet.inl.gov/job/454844/) on 0581e4b wanted to post the following:

View the site [here](https://mooseframework.inl.gov/docs/PRs/14620/site)

This comment will be updated on new commits.

2020-01-23 21:23 UTC, frombs commented
@fdkong, this is ready for review.

2020-01-28 17:02 UTC, permcody commented
Ping @fdkong for review. @frombs - I'm a little confused about this test. Does it require that the problem fails to converge to properly test? I admit I haven't really dug into it.

2020-01-28 17:04 UTC, fdkong commented
@permcody @frombs  I will re-investigate  the test.  I would like to make sure the test is robust

2020-01-28 18:04 UTC, frombs commented
@permcody, that is correct...in order to test the nl_divergence_tolerance, I had to develop a simple test that would diverge quickly. I did that by poorly scaling the variables.  It appears that either changes to PETSc or something in the MOOSE framework improved the convergence so I had to scale the variables further to get it to diverge again.

2020-01-28 19:09 UTC, permcody commented
Ok - good. @fdkong - Can you give Brad a few suggestions on how to test this? I think that the current strategy is always going to be touchy.

2020-01-28 21:23 UTC, fdkong requested changes

2020-01-28 21:23 UTC, fdkong commented on test/tests/executioners/nl_divergence_tolerance/nl_divergence_tolerance.i
@frombs `make nl_div_tol = 1.0e+4 small ` will have the test more robust. Change to `nl_div_tol=10`

Here we just want to make sure nobody delete `nl_div_tol`

2020-01-29 16:27 UTC, frombs commented
The `peridynamics/test:auxkernels.stretch_NOSPD` test is timing out.

2020-01-29 16:28 UTC, permcody commented
That test was reduced in size yesterday - it's merged into next. Don't worry about that.

2020-01-29 16:29 UTC, permcody commented
@fdkong - is this what you wanted?

2020-01-29 16:51 UTC, fdkong approved these changes

2020-01-29 16:51 UTC, merged