Multi index 14650
idaholab/moose pull request #14652
Opened 2020-01-28 18:13 UTC by snschune

@permcody @YaqiWang as discussed. tagging @dschwen

2020-01-28 20:00 UTC, moosebuild commented
Job [Documentation](https://civet.inl.gov/job/457355/) on 57daab8 wanted to post the following:

View the site [here](https://mooseframework.inl.gov/docs/PRs/14652/site)

This comment will be updated on new commits.

2020-01-28 22:17 UTC, permcody requested changes
The rest of this looks fine. I suppose it should be if it's been in Magpie for awhile.

2020-01-28 22:17 UTC, permcody commented on framework/include/utils/MultiIndex.h
> +/* MAGPIE - Mesoscale Atomistic Glue Program for Integrated Execution */
This header needs to be dropped.

2020-01-29 00:13 UTC, snschune commented
> The rest of this looks fine. I suppose it should be if it's been in Magpie for awhile.

Only the finest is good enough for the Magpie as @dschwen knows.

2020-01-29 15:13 UTC, moosebuild commented
Job [Modules debug PETSc submodule](https://civet.inl.gov/job/457864/) on 2b084f7 : invalidated by @permcody

network failure

2020-01-29 15:13 UTC, moosebuild commented
Job [Test debug PETSc submodule](https://civet.inl.gov/job/457866/) on 2b084f7 : invalidated by @permcody

network failure

2020-01-29 15:14 UTC, moosebuild commented
Job [Modules debug PETSc alt](https://civet.inl.gov/job/457863/) on 2b084f7 : invalidated by @permcody

timeout x2

2020-01-29 22:47 UTC, moosebuild commented
Job [Test debug PETSc submodule](https://civet.inl.gov/job/457866/) on 2b084f7 : invalidated by @snschune

2020-01-30 20:51 UTC, snschune commented
@permcody I am pretty sure that this failure is not related to this PR. I haven't even added documentation.

2020-02-05 21:16 UTC, moosebuild commented
Job [Documentation](https://civet.inl.gov/job/457856/) on 2b084f7 : invalidated by @snschune

2020-02-06 19:42 UTC, moosebuild commented
Job [Documentation](https://civet.inl.gov/job/457856/) on 2b084f7 : invalidated by @permcody

2020-02-06 19:45 UTC, permcody approved these changes

2020-02-06 19:45 UTC, merged