Aux user object dependency resolving
idaholab/moose pull request #14672
Opened 2020-01-30 16:23 UTC by YaqiWang

Close #14664.

2020-01-30 16:24 UTC, YaqiWang commented
I have not pushed the last commit in (having it ready now), but want to check if moving few interfaces down to the base class is ok or not first.

2020-01-30 17:46 UTC, moosebuild commented
Job [Documentation](https://civet.inl.gov/job/458728/) on f8d4996 wanted to post the following:

View the site [here](https://mooseframework.inl.gov/docs/PRs/14672/site)

This comment will be updated on new commits.

2020-01-30 18:02 UTC, YaqiWang commented
OK, looks everything is clean. Reviewers, please be noted that the first two commits does not fail any tests. Now I am going to push my last two commits.

2020-01-30 18:06 UTC, YaqiWang commented on framework/src/auxkernels/AuxKernel.C
> +AuxKernelTempl<ComputeValueType>::getUserObjectBaseByName(const UserObjectName & name)
This function is missing before which can be really bad.

2020-01-30 18:09 UTC, YaqiWang commented
The only arguable code is in the third commit. I suggest to have this in first and then work on the ideal way later on. I personally think that this patches a quite large hole in the framework.

2020-01-30 19:15 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/458917/) on 9161f48 wanted to post the following:

Your code requires style changes.  

A patch was auto generated and copied [here](https://mooseframework.inl.gov/docs/PRs/14672/style.patch)  
You can directly apply the patch by running, in the top level of your repository:

`curl -s https://mooseframework.inl.gov/docs/PRs/14672/style.patch | git apply -v`  

Alternatively, with your repository up to date and in the top level of your repository:

`git clang-format 0a45fb12a467a40dbbe81cde336b98677c2aa13f`

2020-01-31 00:16 UTC, YaqiWang commented
@dschwen Possibly the failing phase field test is done by your team, so I asking you to take a look why `grain_volumes` supposes to be a vector postprocessor, but I cannot find any input for adding it?

2020-01-31 00:30 UTC, YaqiWang commented
That test could be just a copy-paste error suggested by @dschwen , so we just added a missing vector postprocessor in the input.

2020-02-04 19:52 UTC, YaqiWang commented
This is ready for review. Thanks.

2020-02-06 19:56 UTC, permcody requested changes
So I think the improvement in functionality is good, but I don't agree with putting a bunch of UserObject and Postprocessor functions staring into the MooseObject class. I'd prefer to see those flow down from the UserObjectInterface and PostprocessorInterface classes as they did before. Was there a problem with that organization?

2020-02-20 19:29 UTC, YaqiWang commented
I do not understand the comment. I will stop by sometime.

2020-02-21 17:40 UTC, YaqiWang commented
@permcody Just to let you know that I cannot mark those functions with override because they are not virtual in the base class. We basically are not doing overriding but hiding. Same in the `AuxKernel.h`. Unless you want me to make those functions virtual in the base class, we cannot add override here. But I feel it is a rather large change. Theoretically speaking, we should resolve the dependency in warehouse, the codes I did here and the codes in `AuxKernel` are all temporary bandage.

2020-02-21 22:45 UTC, permcody approved these changes

2020-02-21 22:46 UTC, merged