Faux PolycrystalVoronoi
idaholab/moose pull request #14698
Opened 2020-02-07 00:08 UTC by fdkong

When the number of grains equal to the number of order parameters, a faux PolycrystalVoronoi
is useful for avoiding calling unnecessary FeatureFloodCount

Close #14697

2020-03-08 05:06 UTC, fdkong commented
Don’t close

2020-04-08 14:37 UTC, fdkong commented
Open it

2020-04-09 20:33 UTC, moosebuild commented
Job [Documentation](https://civet.inl.gov/job/499015/) on 55edcb2 wanted to post the following:

View the site [here](https://mooseframework.inl.gov/docs/PRs/14698/site)

This comment will be updated on new commits.

2020-04-13 16:31 UTC, lindsayad requested changes
just fix the `validParams`

2020-04-13 16:31 UTC, lindsayad commented on modules/phase_field/include/userobjects/FauxPolycrystalVoronoi.h
> +InputParameters validParams<FauxPolycrystalVoronoi>();
Use the `static` class method instead. The function template specialization is deprecated

2020-04-14 19:40 UTC, lindsayad approved these changes

2020-04-14 19:40 UTC, merged