updated inlhpcconnectivity url and Linux instructions
idaholab/moose pull request #14767
Opened 2020-02-21 20:18 UTC by dhill2522

This is a simple update to the INL HPC Connectivity docs. It fixes a broken url and adds Linux instructions for the SSH Config.

2020-02-21 22:09 UTC, permcody submitted a review, later dismissed

2020-02-21 23:07 UTC, permcody commented
Something is wrong with the PR. We may need to rebase this before merging. It doesn't reference a ticket yet it is passing our pre-check. We can do this internally if you don't have time to fix it.

2020-02-21 23:11 UTC, dhill2522 commented
Do you want me to make a ticket and reference it then? I am not exactly sure what you are looking for.

2020-02-21 23:12 UTC, dhill2522 commented
I am also fine if you just handle it internally. Mostly I am just hoping future Linux devs don't run into the same issues I did.

2020-02-21 23:52 UTC, moosebuild commented
Job [Documentation](https://civet.inl.gov/job/468150/) on 65ffb25 wanted to post the following:

View the site [here](https://mooseframework.inl.gov/docs/PRs/14767/site)

This comment will be updated on new commits.

2020-02-22 00:09 UTC, dhill2522 commented
It looks like the markdown to html renderer being used wanted another newline in the file, so the published docs don't render the second code block properly. Are you looking to handle this internally or should I update it? It is literally just one missing newline before line 27 as far as I can tell. Sorry to bother you about this.

2020-02-24 15:53 UTC, permcody commented
Thanks, I have fixed both of these issues. Thanks for your contribution!

2020-02-24 15:53 UTC, permcody submitted a review, later dismissed

2020-02-24 20:18 UTC, loganharbour commented
Something's goofed up in formatting:
https://mooseframework.inl.gov/docs/PRs/14767/site/help/inlhpcconnectivity.html

2020-02-24 20:19 UTC, loganharbour requested changes

2020-02-24 20:19 UTC, loganharbour commented on modules/doc/content/help/inlhpcconnectivity.md
> +For Linux Systems use the following instead:
```suggestion
For Linux Systems use the following instead:

```

2020-02-24 20:21 UTC, loganharbour approved these changes

2020-02-24 20:24 UTC, permcody approved these changes

2020-02-24 20:24 UTC, merged

2020-03-19 17:22 UTC, loganharbour commented
@dhill2522 which distro were you using that required this change?

See: https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/moose-users/k6N8PZzd2Pk/ISPFpfJnAAAJ

2020-03-19 17:36 UTC, dhill2522 commented
Fedora 31

That is very interesting. I guess I assumed wrongly that my config would generally work for Linux systems.