Grain Velocity Computation
idaholab/moose pull request #14887
Opened 2020-03-12 20:55 UTC by killerpenguin12

2020-03-12 21:00 UTC, dschwen commented
"Add files via upload" is not an acceptable commit message.

2020-03-12 21:06 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/480756/) on f8e9409 wanted to post the following:

Your code requires style changes.  

A patch was auto generated and copied [here](https://mooseframework.inl.gov/docs/PRs/14887/style.patch)  
You can directly apply the patch by running, in the top level of your repository:

`curl -s https://mooseframework.inl.gov/docs/PRs/14887/style.patch | git apply -v`  

Alternatively, with your repository up to date and in the top level of your repository:

`git clang-format 784625b6bb1587037a99caa2d2a8a6e0b8bdfdd0`

2020-03-12 21:33 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/480787/) on 823f3fb wanted to post the following:

Your code requires style changes.  

A patch was auto generated and copied [here](https://mooseframework.inl.gov/docs/PRs/14887/style.patch)  
You can directly apply the patch by running, in the top level of your repository:

`curl -s https://mooseframework.inl.gov/docs/PRs/14887/style.patch | git apply -v`  

Alternatively, with your repository up to date and in the top level of your repository:

`git clang-format 784625b6bb1587037a99caa2d2a8a6e0b8bdfdd0`

2020-03-13 20:47 UTC, dschwen requested changes

2020-03-13 20:47 UTC, dschwen commented on modules/phase_field/include/auxkernels/calcVelocityAux.h
> +class calcVelocityAux : public AuxKernel
We use CamelCase for class names. I suggest renaming to `GrainBoundaryVelocity`

2020-03-13 20:47 UTC, dschwen commented on modules/phase_field/src/auxkernels/calcVelocityAux.C
> +  params.addParam<Real>("eta_top", 0.80, "end point on area of eta we are interested in.");
this is not an area but a "range"

2020-03-13 20:47 UTC, dschwen commented on modules/phase_field/src/auxkernels/calcVelocityAux.C
> +      new_val = (1 / ((*_grad_eta[i])[_qp].norm())) * ((*deta_dt[i])[_qp]);
there are way too many parenthesis in this line

2020-03-13 20:47 UTC, dschwen commented on modules/phase_field/src/auxkernels/calcVelocityAux.C
> +    deta_dt(_op_num),
missing leading underscore

2020-03-13 20:47 UTC, dschwen commented on modules/phase_field/src/auxkernels/calcVelocityAux.C
> +validParams<calcVelocityAux>()
please use the new static member scheme for validParams

2020-03-13 20:47 UTC, dschwen commented on modules/phase_field/src/auxkernels/calcVelocityAux.C
> +//#include "FEProblem.h"
remove

2020-03-13 20:47 UTC, dschwen commented on modules/phase_field/include/auxkernels/calcVelocityAux.h
> +//#include "DerivativeMaterialInterface.h"
remove

2020-03-13 20:47 UTC, dschwen commented on modules/phase_field/src/auxkernels/calcVelocityAux.C
> +      "calculate the velocity of grains while avoiding numerical instability.");
The "while avoiding numerical instability" is not a particularly useful bit of information and this is rather computing the velocity of *grain boundaries*.

2020-03-16 16:48 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/482081/) on 49e1502 wanted to post the following:

Your code requires style changes.  

A patch was auto generated and copied [here](https://mooseframework.inl.gov/docs/PRs/14887/style.patch)  
You can directly apply the patch by running, in the top level of your repository:

`curl -s https://mooseframework.inl.gov/docs/PRs/14887/style.patch | git apply -v`  

Alternatively, with your repository up to date and in the top level of your repository:

`git clang-format 784625b6bb1587037a99caa2d2a8a6e0b8bdfdd0`

2020-03-16 17:36 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/482226/) on a043994 wanted to post the following:

Your code requires style changes.  

A patch was auto generated and copied [here](https://mooseframework.inl.gov/docs/PRs/14887/style.patch)  
You can directly apply the patch by running, in the top level of your repository:

`curl -s https://mooseframework.inl.gov/docs/PRs/14887/style.patch | git apply -v`  

Alternatively, with your repository up to date and in the top level of your repository:

`git clang-format 784625b6bb1587037a99caa2d2a8a6e0b8bdfdd0`

2020-03-19 19:59 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/485463/) on ac28f10 wanted to post the following:

Your code requires style changes.  

A patch was auto generated and copied [here](https://mooseframework.inl.gov/docs/PRs/14887/style.patch)  
You can directly apply the patch by running, in the top level of your repository:

`curl -s https://mooseframework.inl.gov/docs/PRs/14887/style.patch | git apply -v`  

Alternatively, with your repository up to date and in the top level of your repository:

`git clang-format 784625b6bb1587037a99caa2d2a8a6e0b8bdfdd0`

2020-03-24 18:51 UTC, dschwen commented on modules/phase_field/.atom/.apmrc
> +strict-ssl=false
remove this file

2020-03-24 18:51 UTC, dschwen commented on modules/phase_field/doc/content/source/auxkernels/calcVelocityAux.md
> +!template load file=stubs/moose_object.md.template name=calcVelocity syntax=/AuxKernels/calcVelocityAux
remove this file

2020-03-24 18:52 UTC, dschwen commented on modules/phase_field/doc/content/source/auxkernels/GrainBoundaryVelocity.md
> +!template load file=stubs/moose_object.md.template name=GrainBoundaryVelocity syntax=/AuxKernels/GrainBoundaryVelocity
Add actual documentation here!

2020-03-24 18:52 UTC, dschwen commented on modules/phase_field/src/auxkernels/GrainBoundaryVelocity.C
> +
remove blank line

2020-03-24 18:53 UTC, dschwen commented on modules/phase_field/src/auxkernels/GrainBoundaryVelocity.C
> +      _new_val = 1 / (*_grad_eta[i])[_qp].norm() * (*_deta_dt[i])[_qp];
Please distinguish whole floating point numbers from integers by adding `.0` (this is important in a small number of cases, but it's best to do it consistently)

2020-03-24 18:54 UTC, dschwen commented on modules/phase_field/test/tests/Grain_Velocity_Computation/GrainBoundaryVelocityTest.i
> +  zmax = 0
remove all the z stuff, it is unnecessary

2020-03-24 18:54 UTC, dschwen commented on modules/phase_field/test/tests/Grain_Velocity_Computation/GrainBoundaryVelocityTest.i
> +  family = MONOMIAL
indent

2020-03-24 18:54 UTC, dschwen commented on modules/phase_field/test/tests/Grain_Velocity_Computation/GrainBoundaryVelocityTest.i
> +    family = LAGRANGE
you can leave out family and order, they default to the values you're setting. Shorter files are more readable.

2020-03-24 18:55 UTC, dschwen commented on modules/phase_field/test/tests/Grain_Velocity_Computation/GrainBoundaryVelocityTest.i
> +  active = ' '
if none of those are active I'd prefer to just remove the entire block

2020-03-24 18:56 UTC, dschwen commented on modules/phase_field/test/tests/Grain_Velocity_Computation/GrainBoundaryVelocityTest.i
> +      translation = '0 1000 0'
use `auto_direction` for periodicity with generated meshes!

2020-03-24 18:56 UTC, dschwen commented on modules/phase_field/test/tests/Grain_Velocity_Computation/GrainBoundaryVelocityTest.i
> +   full = true
fix indentaton

2020-03-24 18:57 UTC, dschwen commented on modules/phase_field/test/tests/Grain_Velocity_Computation/GrainBoundaryVelocityTest.i
> +  num_steps = 5
This test is very likely to be too heavy. If it takes more than **two seconds** in opt it needs to get simplified.

2020-03-24 19:00 UTC, dschwen requested changes
See comments. You're also missing a `tests` file, so your test won't actually get run. Also, you added 3 gold files, which are two too many. My suggestion would be to drop adaptivity and uniform_refine. Just go with a simple 20x20 mesh.

2020-03-25 19:24 UTC, moosebuild commented
Job [Documentation](https://civet.inl.gov/job/488909/) on bf3f70e wanted to post the following:

View the site [here](https://mooseframework.inl.gov/docs/PRs/14887/site)

This comment will be updated on new commits.

2020-04-10 16:35 UTC, dschwen reviewed
Almost ready. Please squash your commits.

2020-04-10 16:35 UTC, dschwen commented on modules/phase_field/doc/content/source/auxkernels/GrainBoundaryVelocity.md
> +This AuxKernel only requires an AuxVariable to compute on.
Not true, it also required order parameters... I'd just remove that line

2020-04-10 16:35 UTC, dschwen commented on modules/phase_field/test/tests/Grain_Velocity_Computation/tests
> +  [../]
This needs `design` `requirements` `issues`

2020-04-13 15:58 UTC, dschwen commented
You have a merge commit in your branch now :-/

2020-04-13 16:01 UTC, dschwen commented
Do

```
git reset --hard  66cbb62
git pull --rebase upstream devel
```

To remove it and properly update your branch.
Then use

 ```
git rebase -i HEAD~19
```

to squash your commits (you may need to Google some instructions if you've never done this).
Then push your changes with 

```
git push -f
```

2020-04-23 16:23 UTC, permcody submitted a review, later dismissed

2020-04-23 16:23 UTC, permcody commented on modules/phase_field/test/tests/Grain_Velocity_Computation/tests
> +    requirement = 'We will be able to visualize the velocity in the simulation.'
```suggestion
    requirement = 'The system shall be able to provide a velocity vector field indicating grain boundary movement for visualization purposes.'
```

2020-04-23 16:32 UTC, dschwen commented on modules/phase_field/src/auxkernels/GrainBoundaryVelocity.C
> +  _new_val = 0.0;
These two variables should not be member variables. But we can fix that later.

2020-04-23 16:32 UTC, dschwen approved these changes

2020-04-23 22:47 UTC, merged