Geochemistry functionality enhanced
idaholab/moose pull request #15098
Opened 2020-04-19 10:58 UTC by WilkAndy

This is just #14978 all squashed into one commit

- free electron GWB format now parsed by gwb_reader
- free electron included in dbclass and dbconverter
- free electron and O2(g) added to unit/data/moose_testdb.json
- free electron added to GeochemicalDatabaseReader as just another secondary species
- GeochemicalDatabaseReader has the option that during database parsing the free electron can be rexpressed in terms of O2(aq) instead of O2(g).
- all python and C++ tested
Fixes #14976

data/moose_geochemdb.json added - lots of lines, wow.
Fixes #14979

MinimalGeochemicalSystem and unit tests added
This builds the minimal geochemical system of basis species, equilibium species and kinetic species that is relevant for use-supplied basis components, mineral, gases, etc.  The data is stored in a computationally-efficient way using std::vector and DenseMatrix.
Also, add to moose_testdb.json to allow testing for wacky cases.
Fixes #14948

GeochemistrySpeciesSwapper utility added
ixes #14949

GeochemicalModelRoot Userobject added: this provides a MOOSE interface to utils/MinimalGeochemicalSystem

GeochemicalModelInterrogator Userobject added: this enables querying and simple manipulations of the database
GeochemicalModelInterrogator Action added: this adds the GeochemicalModelInterrogator Userobject as well as setting up a simple Moose simulation with no timestepping, no output, etc

Lots of documentation and examples illustrating this functionality

Tests of the functionality

Fixes #14981

add GeochemistryApp to base files. Refs #14984

Changes requested by @cpgr and @loganharbour all done

Refs #14984
Refs #14981

Refs #14981

2020-04-19 11:00 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/505719/) on e08b87d wanted to post the following:

Your code requires style changes.  

A patch was auto generated and copied [here](https://mooseframework.inl.gov/docs/PRs/15098/style.patch)  
You can directly apply the patch by running, in the top level of your repository:

`curl -s https://mooseframework.inl.gov/docs/PRs/15098/style.patch | git apply -v`  

Alternatively, with your repository up to date and in the top level of your repository:

`git clang-format c3a1cdfe44c215caa66fc4c6243038659a748cf5`

2020-04-19 13:08 UTC, moosebuild commented
Job [Documentation](https://civet.inl.gov/job/505745/) on 8eed90e wanted to post the following:

View the site [here](https://mooseframework.inl.gov/docs/PRs/15098/site)

This comment will be updated on new commits.

2020-04-19 14:03 UTC, loganharbour requested changes
All very minor changes. Should be good after this. Looks like the output object was pretty straight forward!

2020-04-19 22:33 UTC, WilkAndy commented on modules/geochemistry/test/tests/interrogate_reactions/muscovite2.i
> +    database_file = "../../../database/moose_geochemdb.json"
Yea, OK.  Let's leave this for another PR, as you say.   I'm still wondering how many databases we'll have (hopefully only 1) and about their organisation

2020-04-19 22:59 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/505795/) on 8e3f38e wanted to post the following:

Your code requires style changes.  

A patch was auto generated and copied [here](https://mooseframework.inl.gov/docs/PRs/15098/style.patch)  
You can directly apply the patch by running, in the top level of your repository:

`curl -s https://mooseframework.inl.gov/docs/PRs/15098/style.patch | git apply -v`  

Alternatively, with your repository up to date and in the top level of your repository:

`git clang-format c3a1cdfe44c215caa66fc4c6243038659a748cf5`

2020-04-20 02:29 UTC, WilkAndy commented
Oh yea, all tests passed.  Good to merge, @loganharbour  ?

2020-04-20 16:34 UTC, loganharbour approved these changes

2020-04-20 16:34 UTC, merged

2020-04-20 21:24 UTC, WilkAndy commented
Woohoo, thanks @loganharbour !