Enable TheWarehouse caching and skip double lookup
idaholab/moose pull request #15108
Opened 2020-04-20 21:06 UTC by loganharbour

Closes #15017

2020-04-20 22:16 UTC, moosebuild commented
Job [Test debug PETSc alt](https://civet.inl.gov/job/506631/) on 8edffb8 : invalidated by @loganharbour

Unrelated failure

2020-04-20 22:27 UTC, moosebuild commented
Job [Documentation](https://civet.inl.gov/job/506623/) on 8edffb8 wanted to post the following:

View the site [here](https://mooseframework.inl.gov/docs/PRs/15108/site)

This comment will be updated on new commits.

2020-04-20 23:21 UTC, rwcarlsen requested changes

2020-04-20 23:35 UTC, loganharbour commented on framework/include/base/TheWarehouse.h
> +      const auto find = _cache.find(_key_tup);
alright. done

2020-04-20 23:44 UTC, rwcarlsen approved these changes

2020-04-21 16:18 UTC, rwcarlsen commented
What's up with the test debug petsc alt target:

```
misc/check_error.bad_second_order_test: *** ERROR ***
misc/check_error.bad_second_order_test: Unsupported order: 257
misc/check_error.bad_second_order_test: 
misc/check_error.bad_second_order_test: Stack frames: 7
misc/check_error.bad_second_order_test: 0: libMesh::print_trace(std::ostream&)
misc/check_error.bad_second_order_test: 1: moose::internal::mooseErrorRaw(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >)
misc/check_error.bad_second_order_test: 2: void mooseError<char const*>(char const*&&)
misc/check_error.bad_second_order_test: 3: MooseApp::run()
misc/check_error.bad_second_order_test: 4: /opt/civet/build_0/moose/test/moose_test-dbg(+0x1037b) [0x5651889e537b]
misc/check_error.bad_second_order_test: 5: __libc_start_main
misc/check_error.bad_second_order_test: 6: /opt/civet/build_0/moose/test/moose_test-dbg(+0xf189) [0x5651889e4189]
misc/check_error.bad_second_order_test: application called MPI_Abort(MPI_COMM_WORLD, 1) - process 0
misc/check_error.bad_second_order_test: [unset]: write_line error; fd=-1 buf=:cmd=abort exitcode=1
misc/check_error.bad_second_order_test: :
```

2020-04-21 16:34 UTC, fdkong commented
I am working on that crappy test

2020-04-21 22:15 UTC, rwcarlsen commented
@fdkong - what is the status of your fix?  Can this go in yet?

2020-04-21 22:18 UTC, fdkong commented
> @fdkong - what is the status of your fix? Can this go in yet?

@loganharbour  is working on

2020-04-21 22:19 UTC, loganharbour commented
It's testing now. I'll merge when confident that the fix is good

2020-04-22 14:49 UTC, merged

2020-04-22 18:08 UTC, rwcarlsen commented
You closed/ref'd the wrong issue with this - it should have been #15107 instead of #15017

2020-04-22 18:11 UTC, loganharbour commented
> You closed/ref'd the wrong issue with this - it should have been #15107 instead of #15017

Whoops... thank you