Master App should use the default petsc option database
idaholab/moose pull request #15130
Opened 2020-04-22 22:18 UTC by fdkong

The default database includes important system-level options and operations.  The default database should be used in the master app. Make `-options_left, -log_view` work beautifully.

2020-04-22 22:19 UTC, fdkong commented
@lindsayad  Could you try if this works for you? It looks like working for me.

2020-04-22 22:35 UTC, lindsayad requested changes
It works for me. It would be nice to have a test for this so we can't quietly regress. Perhaps just a `RunApp` test and use the `absent_out` parameter? E.g. if we're using `-pc_type hypre`, we could do:

```
[test_options_not_left]
  type = RunApp
  absent_out = "Option left.*value.*hypre"
[]
```
?

2020-04-22 22:48 UTC, fdkong commented
> It works for me. It would be nice to have a test for this so we can't quietly regress. Perhaps just a `RunApp` test and use the `absent_out` parameter? E.g. if we're using `-pc_type hypre`, we could do:
> 
> ```
> [test_options_not_left]
>   type = RunApp
>   absent_out = "Option left.*value.*hypre"
> []
> ```
> 
> ?

Yes. Good idea. Let me add this one.

2020-04-23 00:34 UTC, moosebuild commented
Job [Documentation](https://civet.inl.gov/job/508763/) on 772463d wanted to post the following:

View the site [here](https://mooseframework.inl.gov/docs/PRs/15130/site)

This comment will be updated on new commits.

2020-04-23 00:36 UTC, lindsayad approved these changes

2020-04-23 01:51 UTC, merged