Copy boundary info from other meshes
idaholab/moose pull request #15186
Opened 2020-04-30 21:28 UTC by dschwen

Closes #15185

2020-04-30 21:29 UTC, dschwen commented
Had to regold the test and made it `-pedantic`. That ensures the number of nodes in the sidesets is the same. We should probably add that option to a few more meshgenerator tests.

2020-04-30 23:08 UTC, moosebuild commented
Job [Documentation](https://civet.inl.gov/job/515260/) on 8eccbe3 wanted to post the following:

View the site [here](https://mooseframework.inl.gov/docs/PRs/15186/site)

This comment will be updated on new commits.

2020-05-05 00:28 UTC, bwspenc requested changes

2020-05-05 00:28 UTC, bwspenc commented on modules/contact/test/tests/mortar_tm/2d/ad_frictionless_fir/finite.i
> +    sideset_name_prefix = plank
Much better!

2020-05-05 00:59 UTC, dschwen commented on framework/src/meshgenerators/GeneratedMeshGenerator.C
> +    _sideset_name_prefix(isParamValid("sideset_name_prefix")
Yeah, not a problem.

2020-05-05 14:38 UTC, dschwen commented on framework/src/meshgenerators/GeneratedMeshGenerator.C
> +    boundary_info.nodeset_name(*rit + _sideset_id_offset) =
Yeah, I'm really not clear when to use boundary vs. sideset vs. nodeset. The existing code does not help me understand this either.

2020-05-05 14:43 UTC, dschwen commented on framework/src/meshgenerators/GeneratedMeshGenerator.C
> +      "sideset_id_offset", 0, "This offset is added to the generated boundary IDs");
No, it's actually the opposite. Both sidesets and nodesets are prefixed. So this should probably be called `boundary` everywhere. The IDs are - I believe - the same for node and sidesets (`MeshTools::Modification::change_boundary_id` changes the ID on both the nodes and the sides).

2020-05-05 14:46 UTC, dschwen commented on framework/src/meshgenerators/GeneratedMeshGenerator.C
> +    _sideset_name_prefix(isParamValid("sideset_name_prefix")
The no default scheme follows our other prefixes and allows us to more cleanly enforce a separating `_` between prefix and name,

2020-05-05 14:46 UTC, dschwen commented on framework/src/meshgenerators/GeneratedMeshGenerator.C
> +    boundary_info.nodeset_name(*rit + _sideset_id_offset) =
I guess boundary the the more general term and nodeset and sideset are the two variants of specified boundaries.

2020-05-05 15:30 UTC, bwspenc commented on framework/include/meshgenerators/GeneratedMeshGenerator.h
> +  /// prefix string for the side set names
All comments are lies!

side set -> boundary

Am I being too picky?

2020-05-05 15:30 UTC, bwspenc submitted a review, later dismissed
Other than my very pedantic comment, looks good.

2020-06-24 15:22 UTC, bwspenc commented
@dschwen I think this was pretty much ready to go. Just fix those couple of minor things and resubmit, and I'll merge it.

2020-07-07 15:28 UTC, dschwen commented
Argh, I thought I was losing my mind! I thought it had already been merged (I need that functionality now).

2020-07-08 15:38 UTC, bwspenc approved these changes

2020-07-08 15:38 UTC, merged

2020-07-09 14:20 UTC, lindsayad commented
@dschwen could you take a look at https://civet.inl.gov/job/559628/ ?