Material system and Kernel system documentation
idaholab/moose pull request #15201
Opened 2020-05-01 21:51 UTC by aeslaughter

(refs #12049)

@lindsayad Can you add some content to the newly create AD page in this PR?

2020-05-03 23:52 UTC, lindsayad commented
Ok I added some AD content!

On Fri, May 1, 2020 at 2:51 PM Andrew E Slaughter <notifications@github.com>
wrote:

> (refs #12049 <https://github.com/idaholab/moose/issues/12049>)
>
> @lindsayad <https://github.com/lindsayad> Can you add some content to the
> newly created AD page in this PR?
> ------------------------------
> You can view, comment on, or merge this pull request online at:
>
>   https://github.com/idaholab/moose/pull/15201
> Commit Summary
>
>    - Material system and Kernel system documentation
>
> File Changes
>
>    - *M* examples/ex08_materials/src/kernels/ExampleDiffusion.C
>    <https://github.com/idaholab/moose/pull/15201/files#diff-fd3d06d45313e6699579f8b2c527dca2>
>    (14)
>    - *M* examples/ex08_materials/src/materials/ExampleMaterial.C
>    <https://github.com/idaholab/moose/pull/15201/files#diff-56ec7d9f20ab34bab508574948620c9b>
>    (3)
>    - *A* framework/doc/content/automatic_differentiation/index.md
>    <https://github.com/idaholab/moose/pull/15201/files#diff-561edb316eeff3863f72824cc0f44444>
>    (1)
>    - *M* framework/doc/content/syntax/Kernels/index.md
>    <https://github.com/idaholab/moose/pull/15201/files#diff-3357a92e614a3370a842c34f6b90c1cf>
>    (111)
>    - *M* framework/doc/content/syntax/Materials/index.md
>    <https://github.com/idaholab/moose/pull/15201/files#diff-4248b800eb0f32a51ec79f11d677d68a>
>    (260)
>    - *M* modules/doc/content/examples/ex08_materials.md
>    <https://github.com/idaholab/moose/pull/15201/files#diff-e7b6117de6f5e6b38b67a1838ed0d254>
>    (10)
>    - *M* test/src/materials/NewtonMaterial.C
>    <https://github.com/idaholab/moose/pull/15201/files#diff-1423ab9bd70c3f101fd4a24a0b17a454>
>    (1)
>    - *M* test/src/materials/RecomputeMaterial.C
>    <https://github.com/idaholab/moose/pull/15201/files#diff-9bee28e7a3fdd7fae7f1e6c8f7cc2b55>
>    (1)
>
> Patch Links:
>
>    - https://github.com/idaholab/moose/pull/15201.patch
>    - https://github.com/idaholab/moose/pull/15201.diff
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/idaholab/moose/pull/15201>, or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ACOGA4APISHVEZKPNT74HQTRPM75PANCNFSM4MXMMIUQ>
> .
>

2020-05-04 13:48 UTC, aeslaughter commented on framework/doc/content/source/interfaces/Coupleable.md
> +adCupledNodalValue | Values of a coupled (vector) variable at nodes with automatic differentiation info
```suggestion
adCoupledNodalValue | Values of a coupled (vector) variable at nodes with automatic differentiation info
```

2020-05-04 16:28 UTC, moosebuild commented
Job [Documentation](https://civet.inl.gov/job/517772/) on 79b6592 wanted to post the following:

View the site [here](https://mooseframework.inl.gov/docs/PRs/15201/site)

This comment will be updated on new commits.

2020-05-04 17:54 UTC, cticenhour requested changes
Only a few suggested changed related to grammar - everything else looks good!

2020-05-04 17:54 UTC, cticenhour commented on framework/doc/content/syntax/Materials/index.md
> +allows properties to be defined in single object (a `Material`) and shared among the many other
```suggestion
allows properties to be defined in a single object (a `Material`) and shared among the many other
```

2020-05-04 17:54 UTC, cticenhour commented on framework/doc/content/syntax/Materials/index.md
> +If a material properties is declared for automatic differentiation (AD) using `declareADProperty`
```suggestion
If a material property is declared for automatic differentiation (AD) using `declareADProperty`
```

2020-05-04 17:54 UTC, cticenhour commented on framework/doc/content/syntax/Materials/index.md
> +When creating a Material object and declaring the properties that shall be computed it is often
```suggestion
When creating a Material object and declaring the properties that shall be computed, it is often
```

2020-05-04 17:54 UTC, cticenhour commented on framework/doc/content/syntax/Materials/index.md
> +by by adding an input parameter for assigning the name. For example, considering the example above
```suggestion
by adding an input parameter for assigning the name. For example, considering the example above
```

2020-05-04 17:54 UTC, cticenhour commented on framework/doc/content/syntax/Materials/index.md
> +(`Real`) properties. For example, in the above example the input file can use number or
```suggestion
(`Real`) properties. In the above example, the input file can use number or
```
Too much use of "example"

2020-05-04 20:58 UTC, cticenhour approved these changes

2020-05-04 22:48 UTC, merged

2020-05-04 22:48 UTC, aeslaughter commented
The failure (https://civet.inl.gov/job/518299/) is not related; this PR only changed comments and markdown files.