*Do* delete remote elements sometimes
idaholab/moose pull request #15223
Opened 2020-05-05 18:03 UTC by lindsayad

Based on our distributed-recover failures induced in #15049, we
*do* need to delete remote elements for distributed-mesh displaced-
problem simulations. But for the reasons outlined in #15112, I think
we should be paranoid and keep default ghosting. For example, I know
that if we delete default ghosted elements for every simulation, we
end up with > 40 failures in MOOSE test

2020-05-05 19:27 UTC, lindsayad commented
@idaholab/moose-team , this is a design decision here...

2020-05-05 19:33 UTC, lindsayad commented
Note that the failing tests are actually inaccurately reporting the number of geometrically ghosted elements. I've verified that `MeshBase::delete_remote_elements` is never called after `FEProblemBase` construction for the failing tests. The only reason they fail is because the `GhostingUserObject` loops over the existing ghosting functors during `initialSetup`. If instead it simply counted the number of `active_elements`, that number would be the same before and after this PR.

2020-05-05 19:37 UTC, lindsayad commented
Basically what this PR does is officially recognize that we don't actually remove default geometric ghosting for 99% of MOOSE simulations; and then change that 99% to 100%.

I think this PR is the right thing to do; e.g. I should re-gold the failing tests...because the current numbers being reported aren't even accurate

2020-05-05 19:46 UTC, moosebuild commented
Job [Documentation](https://civet.inl.gov/job/519456/) on 0cf5e4b wanted to post the following:

View the site [here](https://mooseframework.inl.gov/docs/PRs/15223/site)

This comment will be updated on new commits.

2020-05-05 22:18 UTC, rwcarlsen reviewed
Seems reasonable.  But I haven't spent nearly as much time thinking about this as others like maybe @friedmud and @fdkong.

2020-05-05 22:45 UTC, fdkong requested changes

2020-05-05 22:45 UTC, fdkong commented on framework/src/problems/FEProblemBase.C
> +  //   _mesh.getMesh().remove_ghosting_functor(_mesh.getMesh().default_ghosting());
Are you intending to have one layer of ghosting elements by default? Because we will have a default ghosting functor

2020-05-05 23:11 UTC, fdkong commented
> Basically what this PR does is officially recognize that we don't actually remove default geometric ghosting for 99% of MOOSE simulations; and then change that 99% to 100%.
> 
> I think this PR is the right thing to do; e.g. I should re-gold the failing tests...because the current numbers being reported aren't even accurate

Oh, I see. We are dropping that 1% .  The original motivation was to actually make "removing default ghosting" work for 99% of problems.

2020-05-05 23:35 UTC, lindsayad commented
> Oh, I see. We are dropping that 1% .

Correct.

> The original motivation was to actually make "removing default ghosting" work for 99% of problems.

The motivation a long time ago yea. I think we've successfully dropped default algebraic ghosting, but even in the beginning we didn't actually drop default geometric ghosting; we just thought we did for some reason.

2020-05-05 23:38 UTC, fdkong commented
`Magpie` failing is related to this PR? https://civet.inl.gov/job/519676/

2020-05-05 23:40 UTC, fdkong requested changes

2020-05-05 23:40 UTC, fdkong commented on framework/src/problems/FEProblemBase.C
> +  //   _mesh.getMesh().remove_ghosting_functor(_mesh.getMesh().default_ghosting());
`_mesh.getMesh().remove_ghosting_functor(_mesh.getMesh().default_ghosting());` was intending to remove BOTH geometric and algebraic ghosting functors?

2020-05-05 23:42 UTC, fdkong commented
I was talking to @roystgnr a while ago. From my understanding, we can not remove the geometric ghosting functor at all, regardless. Libmesh needs at least one layer of elements to setup node and element processor ids correctly.

2020-05-06 03:33 UTC, lindsayad commented
> `Magpie` failing is related to this PR? https://civet.inl.gov/job/519676/

No.

> _mesh.getMesh().remove_ghosting_functor(_mesh.getMesh().default_ghosting()); was intending to remove BOTH geometric and algebraic ghosting functors?

No it was only ever intended to remove it from the mesh. Algebraic ghosting is potentially removed in the `NonlinearSystemBase` constructor:
```c++
  if (!_fe_problem.defaultGhosting())
  {
    auto & dof_map = _sys.get_dof_map();
    dof_map.remove_algebraic_ghosting_functor(dof_map.default_algebraic_ghosting());
    dof_map.set_implicit_neighbor_dofs(false);
  }
```

2020-05-06 05:55 UTC, fdkong approved these changes

2020-05-06 05:55 UTC, merged

2020-05-06 13:30 UTC, roystgnr commented
> Libmesh needs at least one layer of elements to setup node and element processor ids correctly.

One layer of side neighbors, correct - and it's not just about node pids; there are other places where library code assumes that ```local_elem->neighbor_ptr(n)``` will always return a ghosted elem except on a domain boundary.  Mesh refinement, error indicators, and load balancing at least would be ruined; I'm not sure what else.

> From my understanding, we can not remove the geometric ghosting functor at all, regardless.

This is technically incorrect; you can remove the default ghosting functors safely so long as you add a replacement ghosting functor which also ensures at least one layer of side neighbors is geometrically ghosted.  That can be a reasonable thing to do to save on CPU hours evaluating redundant ghosting functors (though if there's ever a bug in the replacement functor it'll burn man hours trying to figure out what happened...).

2020-05-06 15:29 UTC, lindsayad commented
>  That can be a reasonable thing to do to save on CPU hours evaluating redundant ghosting functors (though if there's ever a bug in the replacement functor it'll burn man hours trying to figure out what happened...).

And that's what I've done once every couple months...determine that some newly triggered corner case is due to not enough ghosting. Even MOOSE developers sometimes forget to add ghosting when they need to, and then I have to figure out WTF is going on when something fails. Thanks @fdkong for merging!

2020-05-06 15:42 UTC, fdkong commented
> > From my understanding, we can not remove the geometric ghosting functor at all, regardless.
> 
> This is technically incorrect; you can remove the default ghosting functors safely so long as you add a replacement ghosting functor which also ensures at least one layer of side neighbors is geometrically ghosted. That can be a reasonable thing to do to save on CPU hours evaluating redundant ghosting functors (though if there's ever a bug in the replacement functor it'll burn man hours trying to figure out what happened...).

Sorry, I did not make it clear. I intended to say: we can not wholly remove geometric ghosting functor WITHOUT adding an equivalent replacement.  If we did that, we might run into some troubles when extra ghosting elements are needed.

2020-05-06 16:23 UTC, permcody commented
Alex, What can we do to simplify debugging? Maybe as a first step crank up
ghosting to see if the problem goes away? If it does that should help
narrow down the problem more quickly. Maybe we need a manual way to just
request "debugging extra ghosting" or something along those lines.

On Wed, May 6, 2020 at 9:42 AM Fande Kong <notifications@github.com> wrote:

> From my understanding, we can not remove the geometric ghosting functor at
> all, regardless.
>
> This is technically incorrect; you can remove the default ghosting
> functors safely so long as you add a replacement ghosting functor which
> also ensures at least one layer of side neighbors is geometrically ghosted.
> That can be a reasonable thing to do to save on CPU hours evaluating
> redundant ghosting functors (though if there's ever a bug in the
> replacement functor it'll burn man hours trying to figure out what
> happened...).
>
> Sorry, I did not make it clear. I intended to say: we can not wholly
> remove geometric ghosting functor WITHOUT adding an equivalent replacement.
> If we did that, we might run into some troubles when extra ghosting
> elements are needed.
>
> —
> You are receiving this because your review was requested.
> Reply to this email directly, view it on GitHub
> <https://github.com/idaholab/moose/pull/15223#issuecomment-624726353>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAXFOIFFE7SQEXNACPVUBL3RQGAPLANCNFSM4MZZGGLQ>
> .
>

2020-05-06 19:54 UTC, lindsayad commented
`Debug/extra_ghost_layers = x` ?

Honestly I think with this merge I shouldn't run into many more issues... fingers crossed