Allow multiple node allocation
idaholab/moose pull request #15253
Opened 2020-05-07 18:34 UTC by milljm

Some projects are asking for more cores than what is available on a single
node during testing with PBS options.

This PR allows a user to supply the core count of each individual node for
their cluster. Using math.ceil, we round up a whole number to accommodate an
additional node than otherwise allowed with an over-subscribing min_parallel
setting.

Usage:

```bash
./run_tests --pbs session --pbs-node-cpus 32
```

Closes #15234

2020-05-07 20:06 UTC, moosebuild commented
Job [Documentation](https://civet.inl.gov/job/521394/) on b35099c wanted to post the following:

View the site [here](https://mooseframework.inl.gov/docs/PRs/15253/site)

This comment will be updated on new commits.

2020-05-12 17:26 UTC, loganharbour requested changes

2020-05-12 17:26 UTC, loganharbour commented on python/TestHarness/schedulers/RunPBS.py
> +
```suggestion
        # Compute node requirement
        if self.options.pbs_node_cpus:
            ceiling = template['mpi_procs']/self.options.pbs_node_cpus
        else:
            ceiling = 1
        template['nodes'] = math.ceil(ceiling)

```

2020-05-12 17:30 UTC, loganharbour commented on python/TestHarness/schedulers/RunPBS.py
> +
Removes the `_` prefix for `_ceiling`

2020-05-12 17:46 UTC, loganharbour approved these changes

2020-05-14 17:51 UTC, moosebuild commented
Job [Boost enabled, Pthreads only](https://civet.inl.gov/job/523741/) on d9241cc : invalidated by @loganharbour

Unrelated failure

2020-05-20 21:37 UTC, bwspenc commented
Looks like this is passing and has been approved. Any reason we shouldn't merge it now?

2020-05-21 12:26 UTC, milljm commented
I thought it did get merged. Guess not!

2020-05-21 12:26 UTC, merged