Added AD versions of TwoPhaseFluidProperties interfaces
idaholab/moose pull request #15278
Opened 2020-05-13 14:45 UTC by joshuahansel

2020-05-13 17:44 UTC, moosebuild commented
Job [Documentation](https://civet.inl.gov/job/524403/) on 54249a0 wanted to post the following:

View the site [here](https://mooseframework.inl.gov/docs/PRs/15278/site)

This comment will be updated on new commits.

2020-05-13 18:14 UTC, joshuahansel commented
As discussed offline, it is probably best to use a non-test-object instead of `TestTwoPhaseFluidProperties` since this should not be used in unit tests, only regression tests.

2020-05-15 14:15 UTC, joshuahansel commented
THM-based apps will fail to compile due to #15288, so those targets will need to be invalidated after the THM fixes get to its master branch.

2020-05-15 16:51 UTC, rwcarlsen requested changes
Like the unit tests.  Just the const ref on func args.

2020-05-15 16:51 UTC, rwcarlsen commented on modules/fluid_properties/include/userobjects/TwoPhaseFluidProperties.h
> +  virtual DualReal T_sat(DualReal p) const;
`const DualReal &` here and elsewhere.

2020-05-15 19:30 UTC, joshuahansel commented
@rwcarlsen I've failed quite a few times due to those GCC overload-virtual errors (see "Modules debug" failure). I put those pragmas to ignore them in all of the 2-phase header files, but it seems that is not enough. Does it ever need to go in the source file? From the failure, it looks like it.

2020-05-15 20:45 UTC, rwcarlsen commented
Not sure - I've never needed to do that before.  Do the pragmas in the C file fix the error?

2020-05-15 20:50 UTC, joshuahansel commented
> Do the pragmas in the C file fix the error?

Let's find out with my next push. I bet it will work - I just wanted to understand those errors a bit to understand when exactly it's needed.

2020-05-15 21:12 UTC, rwcarlsen commented
I think it needs to go in wherever the implementation lives.  The hidden virtual funcs' implementation (the DualReal versions) for single phase were all in the header file (using a macro) - so it does seem to make sense that you'd need it in the C file since that is where the func bodies are.

2020-05-18 16:12 UTC, rwcarlsen approved these changes

2020-05-18 16:13 UTC, merged