Code verification problems for 1D heat conduction in multi dimensions
idaholab/moose pull request #15302
Opened 2020-05-15 20:16 UTC by atoptann

Ref #15301

2020-05-15 20:17 UTC, atoptann commented
@bwspenc

2020-05-15 20:18 UTC, atoptann commented
@gambka

2020-05-15 20:49 UTC, loganharbour commented
@atoptann you've been added to the idaholab user group so your testing should start automatically now.

2020-05-15 20:51 UTC, atoptann commented
thanks @loganharbour

2020-05-16 00:18 UTC, moosebuild commented
Job [Documentation](https://civet.inl.gov/job/527921/) on 0537628 wanted to post the following:

View the site [here](https://mooseframework.inl.gov/docs/PRs/15302/site)

This comment will be updated on new commits.

2020-05-27 14:04 UTC, andrsd submitted a review, later dismissed

2020-05-27 14:39 UTC, atoptann commented on modules/heat_conduction/test/tests/code_verification/tests
> +    required_python_packages = 'sympy'
I added now. thank you for your review.

2020-05-27 15:42 UTC, andrsd commented
@atoptann I requested review from @gambka and @bwspenc since you tagged them. I don't know if you can actually do that via github interface.

I am fine with the fixes you did that I requested.

2020-05-27 15:51 UTC, gambka requested changes
Is there a plan to include .md documentation similar to your report that details the problems and includes plots of the results?

2020-05-27 15:51 UTC, gambka commented on modules/heat_conduction/test/tests/code_verification/cartesian_test_no2.i
> +# The thermal conductivity of an infinite plate defined varies linearly
An infinite plate with a thermal conductivity that varies linearly with temperature?

2020-05-27 15:51 UTC, gambka commented on modules/heat_conduction/test/tests/code_verification/cylindrical_test_no1.i
> +# equilibrium while being exposed constant temperatures on its
while being exposed **to** constant temperatures

2020-05-27 15:58 UTC, atoptann commented
> Is there a plan to include .md documentation similar to your report that details the problems and includes plots of the results?

Not at the moment. After the journal article is published.

2020-05-27 18:30 UTC, andrsd commented
I have one more thing here. The test takes 24secs on my machine. That's way too long for a regression test. Our rule of thumb is it needs to finish under 3secs. So you have 2 options:

1. have this as a heavy test:
    you would say:
    ```
    heavy = true
    ```
    in the `tests` file

2. you would break each run into a single test that finishes under 3 secs and checks the convergence rate. You would have to do something about generating the final graph after all the tests are done, if that's really needed.

However, I don't know what is the intent with these tests, i.e. either regression or something else like what BISON does for assessment or something else.

2020-05-27 18:34 UTC, atoptann commented
> I have one more thing here. The test takes 24secs on my machine. That's way too long for a regression test. Our rule of thumb is it needs to finish under 3secs. So you have 2 options:
> 
> 1. have this as a heavy test:
>    you would say:
>    ```
>    heavy = true
>    ```
>    
>    
>    in the `tests` file
> 2. you would break each run into a single test that finishes under 3 secs and checks the convergence rate. You would have to do something about generating the final graph after all the tests are done, if that's really needed.
> 
> However, I don't know what is the intent with these tests, i.e. either regression or something else like what BISON does for assessment or something else.

The first option is fine. I prefer them to be in the same place. I pushed the changes now.

2020-05-28 23:30 UTC, bwspenc commented
How fast do the tests run now? 
I thought the rule was that they have to run in <1 second, but maybe that depends on who you ask.

2020-05-29 15:08 UTC, andrsd commented
> How fast do the tests run now?

Which ones? These new ones? The ones in `heat_conduction`? Or those in `modules`?

> I thought the rule was that they have to run in <1 second, but maybe that depends on who you ask. 

For regression tests you want as short as possible. But, to me those are not regression tests really. If you guys are testing grid convergence rate, then to break that you would need to break some fundamental stuff in MOOSE, not in the `heat_conduction` module.

2020-06-03 17:19 UTC, atoptann commented
Test failures are irrelevant and unfortunately hold this PR to be merged. No code changes are made, only new verification tests are added.

2020-06-03 17:25 UTC, loganharbour commented
Should be good in ~an hour. will invalidate then.

2020-06-03 17:29 UTC, atoptann commented
thanks @loganharbour

2020-06-03 19:06 UTC, moosebuild commented
Job [App tests](https://civet.inl.gov/job/539057/) on 7e4f334 : invalidated by @loganharbour

Patch in devel

2020-06-03 19:06 UTC, moosebuild commented
Job [External App tests](https://civet.inl.gov/job/539061/) on 7e4f334 : invalidated by @loganharbour

Patch in devel

2020-06-04 14:13 UTC, bwspenc approved these changes

2020-06-04 14:13 UTC, merged