Add tests using checkpoint restarts and multiple sub apps
idaholab/moose pull request #15337
Opened 2020-05-21 20:36 UTC by vincentlaboure

This MR:

- fixes previous tests that used checkpoints at both the master and sub-app level
- adds a steady to transient restart test with multiple sub apps
- adds a pseudo-transient to transient restart test with multiple sub apps

Close #15287

2020-05-26 13:38 UTC, moosebuild commented
Job [Documentation](https://civet.inl.gov/job/532491/) on e9db619 wanted to post the following:

View the site [here](https://mooseframework.inl.gov/docs/PRs/15337/site)

This comment will be updated on new commits.

2020-05-26 18:16 UTC, moosebuild commented on libmesh
> +Subproject commit 179e8c8c2dcbfcc01311bd6f5044a9534aa21584
**Caution!** This contains a submodule update

2020-05-26 20:34 UTC, vincentlaboure commented
This is now ready for review.

2020-06-01 14:20 UTC, vincentlaboure commented
Would anyone be willing to review this? @permcody or @fdkong ?

2020-06-01 14:30 UTC, permcody commented
Thanks @vincentlaboure. One of us will get to this. My morning is packed.

2020-06-10 23:38 UTC, loganharbour requested changes
Sorry that this sat around for so long. Behavior looks a lot better than before.

Please just remove the old steady state flag and this should be good to go.

2020-06-10 23:38 UTC, loganharbour commented on test/tests/restart/restart_transient_from_transient/restart_trans_with_2subs_sub.i
> +  # steady_state_detection = true
```suggestion
```

2020-06-11 15:43 UTC, fdkong reviewed
Looks great for me

2020-06-15 15:13 UTC, loganharbour approved these changes

2020-06-15 15:54 UTC, vincentlaboure commented
Thanks @loganharbour !

2020-06-15 16:29 UTC, merged