Distributed mesh generator works with mesh adaptivity
idaholab/moose pull request #15349
Opened 2020-05-27 20:17 UTC by fdkong

`DistributedRectilinearMeshGenerator` is a great way to generate a big mesh for parallel simulation. It is beneficial to add the mesh adaptivity for that mesh generator. The mesh adaptivity could save the simulation cost for certain applications.

2020-05-27 21:33 UTC, moosebuild commented
Job [Documentation](https://civet.inl.gov/job/534504/) on 56f96f6 wanted to post the following:

View the site [here](https://mooseframework.inl.gov/docs/PRs/15349/site)

This comment will be updated on new commits.

2020-06-21 06:50 UTC, moosebuild commented
Job [Modules debug](https://civet.inl.gov/job/549239/) on db20dac : invalidated by @fdkong

Why I can not reproduce

2020-06-21 06:50 UTC, moosebuild commented
Job [Modules debug PETSc alt](https://civet.inl.gov/job/549240/) on db20dac : invalidated by @fdkong

Why I can not reproduce

2020-06-22 16:52 UTC, lindsayad requested changes
Just the requirements suggestions, otherwise this looks good to me.

2020-06-22 16:52 UTC, lindsayad commented on modules/phase_field/test/tests/grain_growth/tests
> +    requirement = 'Distributed mesh generator should work with the mesh adaptivity when solving phase field equations'
I'd recommend rewording this to say:

"The system shall be able to apply mesh adaptivity and solve phase field equations on a mesh generated in parallel."

2020-06-22 16:52 UTC, lindsayad commented on test/tests/meshgenerators/distributed_rectilinear_mesh_generator/tests
> +    requirement = 'Distributed mesh generator should work with the mesh adaptivity'
"The system shall be able to adapt a mesh generated in parallel."

2020-06-23 03:06 UTC, fdkong commented
It is ready @lindsayad

2020-06-23 14:16 UTC, lindsayad approved these changes
beautiful code

2020-06-23 14:16 UTC, merged