Improve DisplacementAboutAxis
idaholab/moose pull request #15390
Opened 2020-06-03 17:06 UTC by arovinelli

As suggested by @bwspenc I did small changes to allow `DisplacementAboutAxis` to use an incremental formulation, thus allowing to start the rigid rotation at any time during the simulation

2020-06-03 19:19 UTC, moosebuild commented
Job [Documentation](https://civet.inl.gov/job/539287/) on 26881fc wanted to post the following:

View the site [here](https://mooseframework.inl.gov/docs/PRs/15390/site)

This comment will be updated on new commits.

2020-06-04 20:53 UTC, arovinelli commented
@jiangwen84 can you give a look at this, it's pretty quick

2020-06-08 14:31 UTC, jiangwen84 commented
I know @bwspenc recently discovered that `DisplacementAboutAxis ` needs to be ran on the undisplaced mesh. You made a change here to use incremental form and for that I think you have to use displaced mesh, is that correct?

2020-06-08 14:37 UTC, arovinelli commented
@jiangwen84 no actually you don't need to use disaplced_mesh (it would be a nightmare to do it this way). The incremental formulation adds previous solution displacements to the undisplaced node location. Then you apply the rotation as angular velocity rather than total rotation.
Basically you only need to couple in the previous displacemnts nodal solution

2020-06-08 14:40 UTC, arovinelli commented
@jiangwen84 now that you point this 

> I know @bwspenc recently discovered that `DisplacementAboutAxis ` needs to be ran on the undisplaced mesh.

Now that I think at it, this BC should error out with `use_displaced_mesh=true`

2020-06-08 14:56 UTC, arovinelli commented
> @jiangwen84 now that you point this
> 
> > I know @bwspenc recently discovered that `DisplacementAboutAxis ` needs to be ran on the undisplaced mesh.
> 
> Now that I think at it, this BC should error out with `use_displaced_mesh=true`

but you already set [use_displaced_mesh to false](https://github.com/idaholab/moose/blob/91e607fcf2d3e739ff0639ae77be4bf639f92e43/modules/tensor_mechanics/src/bcs/DisplacementAboutAxis.C#L23)

so we don't need to make other changes

2020-06-08 15:11 UTC, jiangwen84 requested changes
Looks good and a few minor comments. 

> @jiangwen84 no actually you don't need to use disaplced_mesh (it would be a nightmare to do it this way). The incremental formulation adds previous solution displacements to the undisplaced node location. Then you apply the rotation as angular velocity rather than total rotation.
> Basically you only need to couple in the previous displacemnts nodal solution

Don't you need to consider the incremental rotation that is due to finite strain when you apply your angular rotation?

2020-06-08 15:39 UTC, arovinelli commented on modules/tensor_mechanics/src/bcs/DisplacementAboutAxis.C
> +  return p_new(_component, 0) - p(_component);
> For the old case (_angular_velocity = false), looks like you changed p_old -> p, are they the same? I think they are, but I do not understand why they created p_old before. Do you know about that?

The only reason I can give you is that they wanted a 4 element array to work with rotateAroundAxis method. For the old case P_old[0:2] is the same as `p[0:2]` (initial node location).
For the new case, P_old = p + _old_dispalcements, so they are not the same anymore

> 
> Also, can you change p(_component) to p(_component, 0) to be consistent with p_new. I know they are the same for this case.

This prevents me from compiling 
```
error: no match for call to \u2018(libMesh::Point) (const int&, int)\u2019
```

2020-06-08 15:47 UTC, arovinelli commented
> Don't you need to consider the incremental rotation that is due to finite strain when you apply your angular rotation?

I don't understand the question. This is BC in which we enforce a displacement value such that a surface will rotate rigidly. So for the nodes on which this BC applies, we forget about strains.
mechanics will take care of that for free nodes

2020-06-08 15:59 UTC, jiangwen84 commented on modules/tensor_mechanics/src/bcs/DisplacementAboutAxis.C
> +  return p_new(_component, 0) - p(_component);
Ok, I forgot p is Point instead of Matrix.

2020-06-08 16:03 UTC, jiangwen84 commented
> > Don't you need to consider the incremental rotation that is due to finite strain when you apply your angular rotation?
> 
> I don't understand the question. This is BC in which we enforce a displacement value such that a surface will rotate rigidly. So for the nodes on which this BC applies, we forget about strains.
> mechanics will take care of that for free nodes

Maybe you are right. I was thinking that you might want to rotate based on  deformed configuration.

2020-06-08 16:17 UTC, arovinelli commented
> > > Don't you need to consider the incremental rotation that is due to finite strain when you apply your angular rotation?
> > 
> > 
> > I don't understand the question. This is BC in which we enforce a displacement value such that a surface will rotate rigidly. So for the nodes on which this BC applies, we forget about strains.
> > mechanics will take care of that for free nodes
> 
> Maybe you are right. I was thinking that you might want to rotate based on deformed configuration.

Well, you exactly do that by adding the old displacement values to the initial node location (thus recovering the node position at the beginning of the increment). Then, given an axis of rotation and an angular velocity, you compute the new node position at the end of the increment. However, while rotating you can't stretch (you couldn't have done this even before). Basically the major improvement of this PR is allowing rigid rotation after you imposed some arbitrary stretch.

2020-06-09 17:08 UTC, arovinelli commented
I fixed this is ready to be merged. Any second thoughts @jiangwen84 and @bwspenc ?

2020-06-12 18:10 UTC, arovinelli commented
ping @jiangwen84 and @bwspenc

2020-07-03 00:12 UTC, bwspenc approved these changes
Looks good to me. Thanks for contributing this!

2020-07-03 00:13 UTC, bwspenc commented
The tests are being re-run because I submitted a small update with some tweaks to the documentation. I'll merge it once they pass.

2020-07-03 16:16 UTC, merged

2020-07-04 18:47 UTC, arovinelli commented
@bwspenc thanks for merging this.
Always happy to contribute!