More Memory Logging
idaholab/moose pull request #15476
Opened 2020-06-18 19:03 UTC by friedmud

Work towards satisfying #15444 .  Inspired by #15446

This extends both the `TimedPrint` and `PerfGraph` capabilities to also track memory usage.

Example of new `TimedPrint`:

![image](https://user-images.githubusercontent.com/870705/85061276-c993b280-b163-11ea-85b4-1fe6747e2a25.png)

Example of new `PerfGraph`:

![image](https://user-images.githubusercontent.com/870705/85061430-08c20380-b164-11ea-8096-55044f7cc928.png)

2020-06-18 19:06 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/549262/) on f68f728 wanted to post the following:

Your code requires style changes.  

A patch was auto generated and copied [here](https://mooseframework.inl.gov/docs/PRs/15476/style.patch)  
You can directly apply the patch by running, in the top level of your repository:

`curl -s https://mooseframework.inl.gov/docs/PRs/15476/style.patch | git apply -v`  

Alternatively, with your repository up to date and in the top level of your repository:

`git clang-format e22fd5e87442c065479350100d4dd5685781fb3e`

2020-06-18 20:50 UTC, friedmud commented
Just pushed another commit.  I removed the `Children` columns from the `PerfGraph` and added `Mem` for `Self` and `Total`.  `Children` is really rarely used - and it's just `total-self` anyway.  I thought it would be better to be able to see self vs. total memory.

Here is what it looks like now:

![image](https://user-images.githubusercontent.com/870705/85070378-ef748380-b172-11ea-894c-94d25448093a.png)

2020-06-18 21:00 UTC, friedmud commented
BTW - it's straightforward to get detailed memory output for all of the actions before the solve:

```
  [pgraph]
    type = PerfGraphOutput
    level = 7
    execute_on = initial
  []
```

![image](https://user-images.githubusercontent.com/870705/85071220-63635b80-b174-11ea-8ea7-62521f0783a9.png)

2020-06-18 21:15 UTC, loganharbour requested changes

2020-06-18 21:15 UTC, loganharbour commented on framework/doc/content/source/utils/PerfGraph.md
> +`Calls` is the number of times that section was run. `Self` time is the time actually taken by the section while `Children` time is the cumulative time of all of the sub-sections below that section a
```suggestion
`Calls` is the number of times that section was run. `Self` time is the time actually taken by the section and `Total` is the sum of the `Self` time and the time of all of the sub-actions below that section.  The `Avg` and `%` columns represent the average and percent of the total run-time of the app for the number in the column to the left. `Mem` is the memory (in Megabytes) for the column to the left (Self or Total).
```

2020-06-18 21:15 UTC, loganharbour commented on framework/include/utils/PerfNode.h
> +  long int selfMemory();
```suggestion
  long int selfMemory() const;
```

2020-06-18 21:15 UTC, loganharbour commented on framework/include/utils/PerfNode.h
> +  long int childrenMemory();
```suggestion
  long int childrenMemory() const;
```

2020-06-18 21:15 UTC, loganharbour commented on framework/include/utils/PerfNode.h
> +  long int totalMemory() { return _total_memory; }
```suggestion
  long int totalMemory() const { return _total_memory; }
```

2020-06-18 21:15 UTC, loganharbour commented on framework/include/utils/PerfNode.h
> +  void addTimeAndMemory(const std::chrono::steady_clock::duration time) { _total_time += time; }
I don't think this is used. Remove?

2020-06-18 21:15 UTC, loganharbour commented on framework/src/utils/PerfNode.C
> +PerfNode::selfMemory()
```suggestion
PerfNode::selfMemory() const
```

2020-06-18 21:15 UTC, loganharbour commented on framework/src/utils/PerfNode.C
> +PerfNode::childrenMemory()
```suggestion
PerfNode::childrenMemory() const
```

2020-06-18 21:25 UTC, friedmud commented on framework/include/utils/PerfNode.h
> +  void addTimeAndMemory(const std::chrono::steady_clock::duration time) { _total_time += time; }
```suggestion
```

2020-06-18 21:26 UTC, friedmud commented on framework/include/utils/PerfNode.h
>     */
```suggestion
```

2020-06-18 21:37 UTC, YaqiWang commented
This looks pretty nice. If we can have the similar thing for `initialSetup`, I'll not insist to have my PR in. The only problem is that `initialSetup` is not like action warehouse, where we have a loop to execute all actions, thus make adding this easy. Should we add a member variable in FEProblem like
```
std::vector<std::pair<std::string, void *>> _initial_setup_functions;
```
so that we can add PerfGraph entries easily for all items?

2020-06-18 22:21 UTC, friedmud commented
@YaqiWang InitialSetup is already well represented within the `PerfGraph`.  Take a closer look at the above output.  Here is the relevant section:

![image](https://user-images.githubusercontent.com/870705/85077503-b1319100-b17f-11ea-801f-31c30a1dfa57.png)

2020-06-18 22:32 UTC, fdkong commented
Sweet

2020-06-19 17:12 UTC, YaqiWang commented
The list is not complete though and we can potentially miss something in a complicated model.

2020-06-19 17:14 UTC, loganharbour commented
@YaqiWang, that is an issue with both methods. In both cases, the developer is still responsible for adding entry points for logging. We strongly encourage PRs with additional timers and timed prints. We can easily move the entry points in #15446 here.

2020-06-22 16:35 UTC, YaqiWang commented
My way is more forgiving, users can still see something even missing items in-between the first and last message, plus the pattern created in `initialSetup` forces developers to follow the same pattern.

2020-06-22 16:38 UTC, YaqiWang commented
@friedmud I'v noted that when adding print-outs in my PR. But it is not complete, which is something I worried about. If something goes wrong, we have to spend hours to figure out where and why. With my print-out, we can simply turn on the command-line parameter and locate the hot spot really quickly. So now I am thinking, you guys should really merge my PR. It really does not hurt. We can keep improving TimedPrint and PerfGraph of course and I like them.

2020-06-22 21:17 UTC, rwcarlsen commented
@YaqiWang - if the existing time prints and perfgraph entries are missing some details you need, then we'll just add in new timed prints and perfgraph sections to cover what you need.  That will be much nicer than having the disparate logging.

2020-06-22 22:19 UTC, YaqiWang commented
How do I know something is missing if I do not have had a problem yet?

2020-06-23 14:54 UTC, friedmud commented
@YaqiWang I don't understand what you're talking about.  The TimedPrint capability prints out while the code is running - just like yours does.  Explain how yours is different (other than not using the mechanism that is already in the code and is widely used).

2020-06-23 21:10 UTC, YaqiWang commented
TimedPrint requires `CONSOLE_TIMED_PRINT` and PerfGraph requires `TIME_SECTION(a_timer)`. Mine printing the current accumulated memory and cpu time and has more samples. It shows up by a command-line parameter but not like the wait time of TimedPrint. So it is a diversified add-on in my view. Really does not hurt. TimedPrint is auto triggered so that users do not need to worry long wait without to know what is going on. I used both TimedPrint and PerfGraph. They are all good. But mine is still a great add-on.

2020-06-24 19:17 UTC, friedmud commented
@YaqiWang How does yours "have more samples"?  You have to add your statements to the code in just the same way as the others.  As we add code / capability we would still need to add more of your statements in just the same way as the existing perfgraph and timedprint.  I don't see any difference there.

Anyway: you should know that I'm working on something even better than what's presented here.  Please have a bit of patience.

Also: No, we won't be merging your PR in the interim - it is a step backward.  We need something that is _better_ than all of these solutions.  Please be patient, I think you'll like the new thing.

2020-07-26 03:53 UTC, closed without merging