Restrict tests that use MUMPS
idaholab/moose pull request #15479
Opened 2020-06-18 22:08 UTC by andrsd

Do not run tests that use MUMPS if it is not available.

2020-06-19 00:12 UTC, moosebuild commented
Job [Documentation](https://civet.inl.gov/job/549591/) on 5ef4600 wanted to post the following:

View the site [here](https://mooseframework.inl.gov/docs/PRs/15479/site)

This comment will be updated on new commits.

2020-06-19 04:02 UTC, loganharbour commented
This doesn't get tested, correct? I thought for a second that 64-bit dof builds with PETSc require disabling mumps, but clearly not on CIVET otherwise next wouldn't be passing without this.

2020-06-21 06:09 UTC, fdkong commented
> This doesn't get tested, correct? I thought for a second that 64-bit dof builds with PETSc require disabling mumps, but clearly not on CIVET otherwise next wouldn't be passing without this.

The input file is not actually using mumps: for example (coarse_3D.i), 


```
[Preconditioning]
  active = basic
  [./mumps_is_best_for_parallel_jobs]
    type = SMP
    full = true
    petsc_options_iname = '-pc_type -pc_factor_mat_solver_package'
    petsc_options_value = ' lu       mumps'
  [../]
  [./basic]
    type = SMP
    full = true
    petsc_options_iname = '-ksp_type -pc_type -sub_pc_type -sub_pc_factor_shift_type -pc_asm_overlap'
    petsc_options_value = 'gmres      asm      lu           NONZERO                   2             '
  [../]
[]
```

We should enable mumps as well in this PR.

2020-06-22 15:55 UTC, fdkong requested changes

2020-06-22 15:55 UTC, fdkong commented on modules/porous_flow/examples/flow_through_fractured_media/tests
> +    mumps = True
If we add this, should we set the input file to use mumps as well?  Do similar things for all other changes.

`Preconditioning/active=mumps_is_best_for_parallel_jobs`

2020-06-24 19:46 UTC, andrsd commented
> We should enable mumps as well in this PR.

No, that's just me doing search and replace and not checking the actual input file...

2020-06-26 01:39 UTC, fdkong approved these changes

2020-06-26 01:39 UTC, merged