Add `test_id` parameter to TestHarness.
idaholab/moose pull request #15488
Opened 2020-06-23 22:32 UTC by dylanjm

In order to track tests overtime, a unique hash can be given to a test that will
survive file-path/name changes. This is particularly important for long-running
assessment cases that gather performance data during nightly runs. Currently,
there is no 1:1 mapping relationship between test-name, test-output, or
test-results.

See Refs gitlab/idaholab/bison#1178 for more details.

@schwd

2020-06-23 22:39 UTC, dschwen commented
Thought we were calling it `unique_id`...

2020-06-24 01:35 UTC, moosebuild commented
Job [Documentation](https://civet.inl.gov/job/552085/) on 7eed3d4 wanted to post the following:

View the site [here](https://mooseframework.inl.gov/docs/PRs/15488/site)

This comment will be updated on new commits.

2020-06-24 04:45 UTC, dschwen commented
the test harness parameters `unique_id` and `unique_ids` do the _same_ thing (check if libmesh was compiled with unique IDs). Would be nice if we could deprecate one of them.

2020-06-24 20:39 UTC, dschwen requested changes

2020-06-24 20:39 UTC, dschwen commented on python/TestHarness/testers/Tester.py
> +        params.addParam('unique_id',     ['ALL'], "Deprecated. Use --unique_ids instead.")
let's do it the other way around. In MOOSE/Bison `unique_id` is used 104 times, and `unique_ids` only twice!

2020-06-24 22:24 UTC, dschwen commented on python/TestHarness/testers/Tester.py
> +        params.addParam('unique_ids',    ['ALL'], "Deprecated. Use --unique_ids instead.")
```suggestion
        params.addParam('unique_ids',    ['ALL'], "Deprecated. Use --unique_id instead.")
```

2020-06-24 22:24 UTC, dschwen commented on python/TestHarness/testers/Tester.py
> +        params.addParam('unique_ids',    ['ALL'], "Deprecated. Use --unique_ids instead.")
You could also replace the two occurrences of `unique_ids = true` in MOOSE

2020-06-25 16:01 UTC, dschwen approved these changes

2020-06-25 18:18 UTC, dylanjm commented
@aeslaughter @milljm @permcody When on of you have a moment, can I get a 'write-access' review? Thanks.

2020-06-26 17:29 UTC, merged