AD Snow example and classes
idaholab/moose pull request #15509
Opened 2020-06-27 03:20 UTC by dschwen

Closes #15508

2020-06-27 04:46 UTC, moosebuild commented
Job [Documentation](https://civet.inl.gov/job/554231/) on 89fb961 wanted to post the following:

View the site [here](https://mooseframework.inl.gov/docs/PRs/15509/site)

This comment will be updated on new commits.

2020-07-02 14:54 UTC, aeslaughter requested changes

2020-07-02 14:54 UTC, aeslaughter commented on modules/phase_field/doc/content/bib/phase_field.bib
> +issn = "0167-2789",
```suggestion
pages = "410--423",
year = "1993",
issn = "0167--2789",
```

2020-07-02 14:54 UTC, aeslaughter commented on modules/phase_field/include/kernels/ADCoefCoupledTimeDerivative.h
> +  const Real _coef;
```suggestion
  const Real & _coef;
```

2020-07-02 14:54 UTC, aeslaughter commented on modules/phase_field/include/materials/ADInterfaceOrientationMaterial.h
> +// Forward Declarations
```suggestion
```

2020-07-02 14:54 UTC, aeslaughter commented on modules/phase_field/include/materials/ADInterfaceOrientationMaterial.h
> +  Real _eps_bar;
```suggestion
  const Real & _delta;
  const unsigned int & _j;
  const Real & _theta0;
  const Real & _eps_bar;
```

2020-07-02 14:54 UTC, aeslaughter commented on modules/phase_field/src/kernels/ADCoefCoupledTimeDerivative.C
> +  params.addRequiredParam<Real>("coef", "Coefficient");
```suggestion
  params.addRequiredParam<Real>("coef", "Scaling term applied to the time derivative.");
```

2020-07-02 17:38 UTC, aeslaughter commented on modules/phase_field/doc/content/bib/phase_field.bib
> +issn = "0167-2789",
oops, that issn "fix" is wrong, don't do that little guy

2020-07-21 23:58 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/570315/) on 574ea31 wanted to post the following:

Your code requires style changes.  

A patch was auto generated and copied [here](https://mooseframework.inl.gov/docs/PRs/15509/style.patch)  
You can directly apply the patch by running, in the top level of your repository:

`curl -s https://mooseframework.inl.gov/docs/PRs/15509/style.patch | git apply -v`  

Alternatively, with your repository up to date and in the top level of your repository:

`git clang-format 13cda67befb21f45f148bf26d99f93c6e48f2145`

2020-07-28 23:16 UTC, moosebuild commented
Job [App tests](https://civet.inl.gov/job/573072/) on 852aa5b : invalidated by @joshuahansel

Sockeye fixed

2020-08-06 16:43 UTC, aeslaughter commented
Are you still working on this?

2020-09-07 00:49 UTC, closed without merging

2021-06-08 21:30 UTC, dschwen commented
This was finished and merged in #15891