Snesmf reuse base sanity
idaholab/moose pull request #15566
Opened 2020-07-08 21:56 UTC by lindsayad

Do a sanity check to make sure they really are the same. I have a few BISON
cases that fails if we reuse the base but interestingly they don't
trigger the error I put in here in debug mode. I'm find of flummoxed as
to why that is. Moreover if I actually call VecView on the initial
linear residual for cases when I reuse the base and don't reuse the
base, I can see visually that they are indeed the same, so I'm pretty
clueless as to why these BISON cases fail when I reuse the base. I'm
curious to see whether this error is triggered in any of our other
applications though.

refs #14644

2020-07-08 23:33 UTC, moosebuild commented
Job [Documentation](https://civet.inl.gov/job/560364/) on 5a9cede wanted to post the following:

View the site [here](https://mooseframework.inl.gov/docs/PRs/15566/site)

This comment will be updated on new commits.

2020-07-09 17:40 UTC, lindsayad commented
@fdkong I think this is kind of cool. We can do some detection of when it is unsafe for people to reuse the nonlinear residual for the initial linear residual.

2020-07-09 17:58 UTC, fdkong commented
Yes, it is cool. In the same PR, you could also do that non-converged prints we talked earlier.

2020-07-09 18:04 UTC, lindsayad commented
I guess that the vector I get from `KSPGetRHS` is safe to compare against the nonlinear residual, even for left-side preconditioning...?

2020-07-09 18:06 UTC, fdkong commented
> I guess that the vector I get from `KSPGetRHS` is safe to compare against the nonlinear residual, even for left-side preconditioning...? E.g. I am getting, b, and not P_inverse * b

I think so.


```
1525: PetscErrorCode  KSPGetRhs(KSP ksp,Vec *r)
1526: {
1530:   *r = ksp->vec_rhs;
1531:   return(0);
1532: }
```

2020-07-09 18:13 UTC, lindsayad commented
Does it make sense in https://civet.inl.gov/job/561047/, that the residual evaluation should be stateful (e.g. not just a function of the current solution) for the `singular_contaminated` test but not for the `singular` test? I'm not sure that it does just looking briefly at the objects involved. @fdkong it looks like you've touched these tests but the original owner is @snschune

2020-07-09 18:16 UTC, lindsayad commented
I need a sanity check on my sanity check

2020-07-09 18:38 UTC, fdkong commented
> Does it make sense in https://civet.inl.gov/job/561047/, that the residual evaluation should be stateful (e.g. not just a function of the current solution) for the `singular_contaminated` test but not for the `singular` test? I'm not sure that it does just looking briefly at the objects involved. @fdkong it looks like you've touched these tests but the original owner is @snschune

You should skip tests handling null spaces.

2020-07-09 19:48 UTC, lindsayad commented
> You should skip tests handling null spaces.

why?

2020-07-09 20:18 UTC, lindsayad commented
I think that my bitwise comparison probably is not safe in parallel. I'll need to restrict that sanity check to serial runs I think

2020-07-10 02:17 UTC, fdkong commented
> why?

`rhs` is changed because of  removing transpose null spaces

2020-07-10 17:40 UTC, lindsayad commented
Beautiful catching of contact statefulness if I try to run `reuse_base` on:
```
test:verification/patch_tests/plane_1.glued_kin ........................................................... OK
test:mortar_tm.horizontal_blocks_mortar_TM ................................................................ OK
test:verification/patch_tests/ring_1.glued_kin ............................................................ OK
test:verification/patch_tests/cyl_4.glued_kin ............................................................. OK
test:verification/patch_tests/cyl_2.glued_kin ............................................................. OK
test:verification/patch_tests/ring_2.glued_kin ............................................................ OK
test:verification/patch_tests/cyl_3.glued_kin ............................................................. OK
test:verification/patch_tests/single_pnt_2d.glued_kin ..................................................... OK
test:verification/patch_tests/plane_2.glued_kin ........................................................... OK
test:verification/patch_tests/plane_3.glued_kin ........................................................... OK
test:verification/patch_tests/ring_3.glued_kin ............................................................ OK
test:verification/patch_tests/cyl_1.glued_kin ............................................................. OK
test:verification/patch_tests/plane_4.glued_kin ........................................................... OK
test:verification/patch_tests/ring_4.glued_kin ............................................................ OK
test:verification/patch_tests/brick_1.glued_kin ........................................................... OK
test:normalized_penalty.normalized_penalty ................................................................ OK
test:verification/patch_tests/automatic_patch_update.error_test .................... [skipped dependency] SKIP
test:check_error.contact_displacements .................................................................... OK
test:nodal_area.3D ........................................................................................ OK
test:verification/patch_tests/brick_3.frictionless_kin .................................................... OK
test:mechanical-small-problem.mortar-mech ................................................................. OK
test:verification/patch_tests/brick_2.glued_kin ........................................................... OK
test:verification/patch_tests/plane_1.glued_pen ........................................................... OK
test:verification/patch_tests/ring_1.glued_pen ............................................................ OK
test:verification/patch_tests/cyl_2.glued_pen ............................................................. OK
test:verification/patch_tests/cyl_4.glued_pen ............................................................. OK
test:verification/patch_tests/ring_2.glued_pen ............................................................ OK
test:verification/patch_tests/plane_2.glued_pen ........................................................... OK
test:verification/patch_tests/cyl_3.glued_pen ............................................................. OK
test:verification/patch_tests/single_pnt_2d.glued_pen ..................................................... OK
test:verification/patch_tests/plane_3.glued_pen ........................................................... OK
test:verification/patch_tests/ring_3.glued_pen ............................................................ OK
test:verification/patch_tests/cyl_1.glued_pen ............................................................. OK
test:verification/patch_tests/brick_1.glued_pen ........................................................... OK
test:verification/patch_tests/ring_1.frictionless_kin ..................................................... OK
test:verification/patch_tests/plane_1.frictionless_kin .................................................... OK
test:verification/patch_tests/cyl_2.frictionless_kin ...................................................... OK
test:mechanical-small-problem.frictionless-nodal-lm-mortar-disp ........................................... OK
test:verification/patch_tests/plane_2.frictionless_kin .................................................... OK
test:verification/patch_tests/ring_4.glued_pen ............................................................ OK
test:verification/patch_tests/cyl_4.frictionless_kin ...................................................... OK
test:verification/patch_tests/plane_4.glued_pen ........................................................... OK
test:verification/patch_tests/ring_2.frictionless_kin ..................................................... OK
test:verification/patch_tests/brick_2.glued_pen ........................................................... OK
test:verification/patch_tests/cyl_3.frictionless_kin ...................................................... OK
test:verification/patch_tests/single_pnt_2d.frictionless_kin .............................................. OK
test:verification/patch_tests/plane_3.frictionless_kin .................................................... OK
test:verification/patch_tests/brick_4.glued_kin ........................................................... OK
test:verification/patch_tests/ring_3.frictionless_kin ..................................................... OK
test:verification/patch_tests/cyl_1.frictionless_kin ...................................................... OK
test:nodal_area.3D2Proc ...................................................................... [min_cpus=2] OK
test:fieldsplit.mortar-FS ................................................................................. OK
test:verification/patch_tests/brick_1.frictionless_kin .................................................... OK
test:verification/patch_tests/plane_1.frictionless_pen .................................................... OK
test:verification/patch_tests/ring_1.frictionless_pen ..................................................... OK
test:verification/patch_tests/plane_2.frictionless_pen .................................................... OK
test:verification/patch_tests/cyl_2.frictionless_pen ...................................................... OK
test:verification/patch_tests/ring_2.frictionless_pen ..................................................... OK
test:verification/patch_tests/ring_4.frictionless_kin ..................................................... OK
test:verification/patch_tests/plane_4.frictionless_kin .................................................... OK
test:verification/patch_tests/cyl_3.frictionless_pen ...................................................... OK
test:verification/patch_tests/single_pnt_2d.frictionless_pen .............................................. OK
test:mechanical-small-problem.frictionless-nodal-lm-mortar-disp-action .................................... OK
test:nodal_area.2D ........................................................................................ OK
test:verification/patch_tests/brick_2.frictionless_kin .................................................... OK
test:verification/patch_tests/cyl_1.frictionless_pen ...................................................... OK
test:normalized_penalty.normalized_penalty_Q8 ............................................................. OK
test:verification/patch_tests/brick_1.frictionless_pen .................................................... OK
test:verification/patch_tests/single_pnt_2d.frictionless_pen_contact_line_search .......................... OK
test:incremental_slip.slip ................................................................................ OK
test:tension_release.4ElemTensionRelease ..................................................... [min_cpus=4] OK
test:verification/patch_tests/brick_2.f [...]

2020-07-10 17:46 UTC, lindsayad commented
Also for thermal contact:
```
test:homogenization.heatConduction_test ...................................................... FAILED (ERRMSG)
test:heat_conduction/2d_quadrature_gap_heat_transfer.moving .................................. FAILED (ERRMSG)
test:heat_conduction/3d_quadrature_gap_heat_transfer.moving .................................. FAILED (ERRMSG)
--------------------------------------------------------------------------------------------------------------
```
Interesting about the homogenization failure. Are periodic bcs maybe stateful?

2020-07-11 00:13 UTC, lindsayad commented
It turns out that MOOSE is not the right place to do this because we apply constraints in libmesh after completing `FEProblemBase::computeResidualSys`. That is the reason for all the failures observable on the most recent round of testing related to adaptivity and periodic boundary conditions.

2020-07-11 04:48 UTC, moosebuild commented on libmesh
> +Subproject commit 77b5d9b600bf4c7d60dc0161ed4294a3d1052998
**Caution!** This contains a submodule update

2020-07-13 16:40 UTC, moosebuild commented on libmesh
> +Subproject commit 77b5d9b600bf4c7d60dc0161ed4294a3d1052998
**Caution!** This contains a submodule update

2020-07-14 22:15 UTC, fdkong requested changes

2020-07-14 22:15 UTC, fdkong commented on framework/src/utils/PetscSupport.C
> +  petsc_options.flags.erase("-ksp_converged_reason");
Could you remind me what reason we can not print out the colorful converged reason?

Can we set up our own reason view?

2020-07-15 00:11 UTC, lindsayad commented
Per my slack comment (
https://moosedevelopers.slack.com/archives/D0103R1901Z/p1594397950015900),
I don't think you can set a custom convergence reason viewer. You can
obviously set a custom convergence check, but I don't think you can set a
custom reason viewer.

On Tue, Jul 14, 2020 at 3:15 PM Fande Kong <notifications@github.com> wrote:

> *@fdkong* requested changes on this pull request.
> ------------------------------
>
> In framework/src/utils/PetscSupport.C
> <https://github.com/idaholab/moose/pull/15566#discussion_r454676777>:
>
> > @@ -927,6 +933,22 @@ colorAdjacencyMatrix(PetscScalar * adjacency_matrix,
>    ISColoringDestroy(&iscoloring);
>  }
>
> +void
> +disableNonlinearConvergedReason(FEProblemBase & fe_problem)
> +{
> +  auto & petsc_options = fe_problem.getPetscOptions();
> +
> +  petsc_options.flags.erase("-snes_converged_reason");
> +}
> +
> +void
> +disableLinearConvergedReason(FEProblemBase & fe_problem)
> +{
> +  auto & petsc_options = fe_problem.getPetscOptions();
> +
> +  petsc_options.flags.erase("-ksp_converged_reason");
>
> Could you remind me what reason we can not print out the colorful
> converged reason?
>
> Can we set up our own reason view?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/idaholab/moose/pull/15566#pullrequestreview-448504054>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ACOGA4C6CBV35XBACTAKKOTR3TKJPANCNFSM4OU7T4VA>
> .
>

2020-07-15 00:13 UTC, lindsayad commented
You're the PETSc expert. I'll defer to your knowledge.

On Tue, Jul 14, 2020 at 5:11 PM Alexander Lindsay <alexlindsay239@gmail.com>
wrote:

> Per my slack comment (
> https://moosedevelopers.slack.com/archives/D0103R1901Z/p1594397950015900),
> I don't think you can set a custom convergence reason viewer. You can
> obviously set a custom convergence check, but I don't think you can set a
> custom reason viewer.
>
> On Tue, Jul 14, 2020 at 3:15 PM Fande Kong <notifications@github.com>
> wrote:
>
>> *@fdkong* requested changes on this pull request.
>> ------------------------------
>>
>> In framework/src/utils/PetscSupport.C
>> <https://github.com/idaholab/moose/pull/15566#discussion_r454676777>:
>>
>> > @@ -927,6 +933,22 @@ colorAdjacencyMatrix(PetscScalar * adjacency_matrix,
>>    ISColoringDestroy(&iscoloring);
>>  }
>>
>> +void
>> +disableNonlinearConvergedReason(FEProblemBase & fe_problem)
>> +{
>> +  auto & petsc_options = fe_problem.getPetscOptions();
>> +
>> +  petsc_options.flags.erase("-snes_converged_reason");
>> +}
>> +
>> +void
>> +disableLinearConvergedReason(FEProblemBase & fe_problem)
>> +{
>> +  auto & petsc_options = fe_problem.getPetscOptions();
>> +
>> +  petsc_options.flags.erase("-ksp_converged_reason");
>>
>> Could you remind me what reason we can not print out the colorful
>> converged reason?
>>
>> Can we set up our own reason view?
>>
>> —
>> You are receiving this because you were mentioned.
>> Reply to this email directly, view it on GitHub
>> <https://github.com/idaholab/moose/pull/15566#pullrequestreview-448504054>,
>> or unsubscribe
>> <https://github.com/notifications/unsubscribe-auth/ACOGA4C6CBV35XBACTAKKOTR3TKJPANCNFSM4OU7T4VA>
>> .
>>
>

2020-07-15 00:36 UTC, lindsayad commented
I guess I should bring back the linear convergence check again, and we can just print the reason from the convergence check. Right now in the nonlinear convergence check we generate a message that we put into `PetscInfo`. That doesn't seem very useful, e.g. our users will never look at that. We could just do `_console` output I'm assuming from `FEProblemBase::checkLinearConvergence` (if I brought it back). And then we could change the messaging in `FEProblemBase::checkNonlinearConvergence` to go to `_console` as well instead of to `PetscInfo`. But then we will be printing a Moose convergence reason instead of a PETSc one, which is perhaps what we want?

2020-07-16 05:08 UTC, fdkong commented
Looks good for me. I do not have requirements on color things.

2020-07-16 05:08 UTC, fdkong approved these changes

2020-07-16 05:09 UTC, merged

2020-07-16 05:10 UTC, fdkong commented
Bringing  LinearChecker back is too much