Adding pyhit as a conda package
idaholab/moose pull request #15583
Opened 2020-07-10 18:06 UTC by milljm

Closes #15582

2020-07-10 18:45 UTC, moosebuild commented
All [jobs](https://civet.inl.gov/event/56825/) on 02f37f7 : invalidated by @milljm

fixed upstream moose-pyhit Makefile.

2020-07-10 20:29 UTC, moosebuild commented
Job [Documentation](https://civet.inl.gov/job/562669/) on 02f37f7 wanted to post the following:

View the site [here](https://mooseframework.inl.gov/docs/PRs/15583/site)

This comment will be updated on new commits.

2020-07-13 17:05 UTC, lindsayad requested changes

2020-07-13 17:05 UTC, lindsayad commented on conda/pyhit/meta.yaml
> +{% set version = "2020.09.10" %}
The version is in the future?

2020-07-13 17:07 UTC, milljm commented on conda/pyhit/meta.yaml
> +{% set version = "2020.09.10" %}
Uggh... that sucks...

2020-07-13 17:13 UTC, lindsayad approved these changes

2020-07-13 19:23 UTC, merged