Make ExtraNodesetGenerator work with distributed mesh
idaholab/moose pull request #15729
Opened 2020-08-07 02:18 UTC by YaqiWang

Close #15728.

2020-08-07 03:45 UTC, moosebuild commented
Job [Documentation](https://civet.inl.gov/job/580177/) on 71fb89b wanted to post the following:

View the site [here](https://mooseframework.inl.gov/docs/PRs/15729/site)

This comment will be updated on new commits.

2020-08-07 14:57 UTC, loganharbour requested changes

2020-08-07 14:57 UTC, loganharbour commented on framework/src/meshgenerators/ExtraNodesetGenerator.C
>    for (const auto & node_id : nodes)
Can you do this instead?

```
for (const auto & node_id : nodes)
{
  const Node * node_ptr = mesh->query_node_ptr(node_id);
  if (node_ptr)
    for (const auto boundary_id : boundary_ids)
      boundary_info.add_node(node_ptr, boundary_id);
}
```

We're adding boundary_ids.size() extra node queries with what's currently there.

2020-08-07 16:02 UTC, moosebuild commented
Job [Mac Test](https://civet.inl.gov/job/580184/) on 71fb89b : invalidated by @loganharbour

unrelated?

2020-08-07 16:39 UTC, loganharbour approved these changes
Thanks @YaqiWang 👍🏼 

I'm good with this when it's green.

2020-08-08 03:00 UTC, YaqiWang commented
Why is this still testing?!

2020-08-08 16:19 UTC, loganharbour approved these changes
This passed: https://civet.inl.gov/pr/11592/

The CIVET hook to updating github wasn't working too well yesterday.

2020-08-08 16:19 UTC, merged

2020-08-09 19:36 UTC, YaqiWang commented
Thanks @loganharbour.