Adding lexer to pyhit interface for HIT input file editor
idaholab/moose pull request #15890
Opened 2020-10-02 18:26 UTC by aeslaughter

2020-10-02 23:24 UTC, moosebuild commented
Job [Documentation](https://civet.inl.gov/job/586429/) on e8935e5 wanted to post the following:

View the site [here](https://mooseframework.inl.gov/docs/PRs/15890/site)

This comment will be updated on new commits.

2020-10-03 02:04 UTC, moosebuild commented
Job [Test Heavy](https://civet.inl.gov/job/586440/) on e8935e5 : invalidated by @loganharbour

2020-10-03 02:04 UTC, moosebuild commented
Job [Pthreads+OpenMP Test](https://civet.inl.gov/job/586427/) on e8935e5 : invalidated by @loganharbour

2020-10-05 15:13 UTC, rwcarlsen requested changes
Just the one doc comment fix.

2020-10-05 15:13 UTC, rwcarlsen commented on framework/contrib/hit/lex.h
> +std::vector<Token> tokenize(const std::string & fname, const std::string & input);
This doc comment needs to be updated/fixed.  The name of the function is `tokenize` not `lex` - which is what the (copy pasted) doc comment implies.

2020-10-06 15:00 UTC, rwcarlsen approved these changes

2020-10-06 15:00 UTC, merged

2020-10-15 14:16 UTC, aeslaughter commented
closes #15889