call meshChanged() earlier
idaholab/moose pull request #15935
Opened 2020-10-13 19:19 UTC by hugary1995

This allows the ghosting inside EqualValueBoundaryConstraint::meshChanged() to take effect.

close #15934

2020-10-13 19:26 UTC, hugary1995 commented
Without this patch, wrong result in parallel (the constraint is only enforced on-processor):
<img src="https://user-images.githubusercontent.com/31555204/95906169-c69e7c80-0d67-11eb-8575-2aad1c7ff7ba.png" width="300" />
With this patch:
<img src="https://user-images.githubusercontent.com/31555204/95906184-cf8f4e00-0d67-11eb-9b49-a891067610e0.png" width="300" />

For details please refer to the test I added.

@lindsayad this is the change I was mentioning earlier on slack, could you please review this? I understand we are moving towards RM-based constraint system, but I need to fix this bug now for a project (given that this change doesn't break existing tests).

2020-10-13 20:06 UTC, lindsayad requested changes
Just the code comment request. And might as well squash the fixup commit into the original commit (in the future you can make use of `git commit --fixup` and `git rebase --autosquash` if you weren't aware of those commands)

2020-10-13 20:06 UTC, lindsayad commented on framework/src/problems/FEProblemBase.C
> +    mci->meshChanged();
It would be great if you could put some code comment here on why this has to be where it is

2020-10-14 01:29 UTC, hugary1995 commented
Thanks Alex, these commands are useful. I added a comment explaining why I had to do this.
I also restricted the test to replicated mesh only -- I am not sure if that is cheating but I see some precedents in some other constraint tests.

2020-10-14 17:50 UTC, lindsayad commented
> I also restricted the test to replicated mesh only -- I am not sure if that is cheating but I see some precedents in some other constraint tests.

Was your test failing in distributed mode?

2020-10-14 18:38 UTC, hugary1995 commented
Yes it was failing some distributed mesh tests.

2020-10-14 18:45 UTC, lindsayad commented
> Yes it was failing some distributed mesh tests.

Ok we won't make you figure out the root cause of that. You didn't alter any existing test specs, so you didn't break any existing distributed mesh tests with this change.

2020-10-14 18:45 UTC, lindsayad approved these changes

2020-10-14 18:45 UTC, merged