Fixup API to add generate_outputs to TMA
idaholab/moose pull request #15959
Opened 2020-10-15 23:36 UTC by dschwen

Sorry @aeslaughter , I think this version is a bit better.

Refs #15926

2020-10-16 01:17 UTC, moosebuild commented
Job [Documentation](https://civet.inl.gov/job/595926/) on cdaf22d wanted to post the following:

View the site [here](https://mooseframework.inl.gov/docs/PRs/15959/site)

This comment will be updated on new commits.

2020-10-16 02:50 UTC, aeslaughter requested changes

2020-10-16 02:50 UTC, aeslaughter commented on modules/tensor_mechanics/src/actions/TensorMechanicsActionBase.C
> +  if (prop_name == "")
```suggestion
  if (prop_name.empty())
```

2020-10-16 15:17 UTC, dschwen commented on modules/tensor_mechanics/src/actions/TensorMechanicsActionBase.C
> +  if (prop_name == "")
Yeah, I like that!

2020-10-17 02:53 UTC, aeslaughter approved these changes

2020-10-17 02:53 UTC, merged