Material id interface for material
idaholab/moose pull request #16006
Opened 2020-10-26 23:10 UTC by YaqiWang

Close #16005.

2020-10-26 23:12 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/603167/) on ac380b9 wanted to post the following:

Your code requires style changes.  

A patch was auto generated and copied [here](https://mooseframework.inl.gov/docs/PRs/16006/style.patch)  
You can directly apply the patch by running, in the top level of your repository:

`curl -s https://mooseframework.inl.gov/docs/PRs/16006/style.patch | git apply -v`  

Alternatively, with your repository up to date and in the top level of your repository:

`git clang-format 87beb7fc6778f4e154c3c747615b2268a98047bd`

2020-10-26 23:12 UTC, YaqiWang commented on test/tests/auxkernels/mesh_integer/tests
> +    issues = '#16005'
Note: this test will generate wrong results if we do not have this fix.

2020-10-27 00:57 UTC, moosebuild commented
Job [Documentation](https://civet.inl.gov/job/603224/) on 0235eaa wanted to post the following:

View the site [here](https://mooseframework.inl.gov/docs/PRs/16006/site)

This comment will be updated on new commits.

2020-10-27 01:02 UTC, YaqiWang commented
This is ready for review. @lindsayad You are probably the right one for reviewing this. It is a small PR.

2020-10-27 01:10 UTC, lindsayad requested changes
Looks pretty good to me. Just the small requested changes

2020-10-27 01:10 UTC, lindsayad commented on test/tests/auxkernels/mesh_integer/tests
>      requirement = "MOOSE shall include the ability to use extra element integers."
These are two different tests, so the requirements should be different

2020-10-27 01:10 UTC, lindsayad commented on framework/include/materials/Material.h
> +   *       to call the functions in ElementIDInterface properly.
delete `to`

2020-10-27 01:10 UTC, lindsayad commented on framework/include/materials/Material.h
> +               "calling getElementID");
"Directly calling 'getElementIDNeighbor' is not allowed for materials. Please call 'getElementID' instead."

2020-10-27 01:10 UTC, lindsayad commented on framework/include/materials/Material.h
> +               "calling getElementIDByName");
"Directly calling 'getElementIDNeighborByName' is not allowed for materials. Please call 'getElementIDByName' instead."

2020-10-27 03:34 UTC, YaqiWang commented
Comments are addressed.

2020-10-27 05:54 UTC, lindsayad approved these changes
Thank you for the additional documentation as well!

2020-10-27 05:54 UTC, merged

2020-10-27 06:20 UTC, YaqiWang commented
Thank you @lindsayad !