Add FV support for Dirac Kernels
idaholab/moose pull request #16034
Opened 2020-10-30 00:17 UTC by cpgr

Let me know if I got this correct @lindsayad 

Closes #16033

2020-10-30 01:58 UTC, moosebuild commented
Job [Documentation](https://civet.inl.gov/job/607519/) on 279a7d5 wanted to post the following:

View the site [here](https://mooseframework.inl.gov/docs/PRs/16034/site)

This comment will be updated on new commits.

2020-10-30 17:17 UTC, lindsayad requested changes
Looks good @cpgr . Just the novel for you to read (and change to `NEWTON`) and the requirement change.

2020-10-30 21:27 UTC, cpgr commented on test/tests/dirackernels/constant_point_source/1d_point_source_fv.i
> +  []
No, it isn't. I just copied the existing test here and changed to FV variables. I'll remove this.

2020-10-30 21:27 UTC, cpgr commented on test/tests/dirackernels/constant_point_source/1d_point_source_fv.i
> +  solve_type = 'PJFNK'
Makes sense. Thanks for letting me know.

2020-11-02 02:06 UTC, lindsayad approved these changes
Awesome, thanks @cpgr !

2020-11-02 02:06 UTC, merged

2020-11-02 21:34 UTC, lindsayad commented
This is failing with distributed mesh with 5 procs (and only 5 procs). Weird. I guess I should probably look into this

2020-11-03 03:40 UTC, lindsayad commented
@cpgr do you think you've ever run any Dirac kernel simulations in which your point source is actually on a processor boundary? That is the circumstance when we have 5 procs here. I'm thinking this failure is probably  not related to the fact that is FV...thinking this might also cause issues for a pure FE simulation

2020-11-03 03:54 UTC, cpgr commented
Not intentionally. Was this just a case of bad luck in this test? And why isn't the equivalent FE test failing too for the same reason? I think the point source is in the same spot (I just copied this test and changed to FV variables and kernels).

2020-11-03 07:14 UTC, lindsayad commented
Good point...

On Mon, Nov 2, 2020 at 7:54 PM Chris Green <notifications@github.com> wrote:

> Not intentionally. Was this just a case of bad luck in this test? And why
> isn't the equivalent FE test failing too for the same reason? I think the
> point source is in the same spot (I just copied this test and changed to FV
> variables and kernels).
>
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly, view it on GitHub
> <https://github.com/idaholab/moose/pull/16034#issuecomment-720890642>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ACOGA4EMGM64SAGCMJALP33SN55HDANCNFSM4TEMEB4Q>
> .
>

2020-11-03 09:09 UTC, lindsayad commented
Ok, so this is a discontinuous discretization problem. Consider this code:
```c++
const Elem *
DiracKernelInfo::findPoint(Point p, const MooseMesh & mesh)
{
  // If the PointLocator has never been created, do so now.  NOTE - WE
  // CAN'T DO THIS if findPoint() is only called on some processors,
  // PointLocatorBase::build() is a 'parallel_only' method!
  if (_point_locator.get() == NULL)
  {
    _point_locator = PointLocatorBase::build(TREE_LOCAL_ELEMENTS, mesh);
    _point_locator->enable_out_of_mesh_mode();
  }

  // Check that the PointLocator is ready to start locating points.
  // So far I do not have any tests that trip this...
  if (_point_locator->initialized() == false)
    mooseError("Error, PointLocator is not initialized!");

  // Note: The PointLocator object returns NULL when the Point is not
  // found within the Mesh.  This is not considered to be an error as
  // far as the DiracKernels are concerned: sometimes the Mesh moves
  // out from the Dirac point entirely and in that case the Point just
  // gets "deactivated".
  const Elem * elem = (*_point_locator)(p);

  // The processors may not agree on which Elem the point is in.  This
  // can happen if a Dirac point lies on the processor boundary, and
  // two or more neighboring processors think the point is in the Elem
  // on *their* side.
  dof_id_type elem_id = elem ? elem->id() : DofObject::invalid_id;

  // We are going to let the element with the smallest ID "win", all other
  // procs will return NULL.
  dof_id_type min_elem_id = elem_id;
  mesh.comm().min(min_elem_id);

  return min_elem_id == elem_id ? elem : NULL;
}
```
Note that we let the lowest element ID determine which element gets to apply the impulse from the Dirac point. Here's our global element numbering for a replicated mesh for your test:
![replicated](https://user-images.githubusercontent.com/10248304/97966458-b7ac5800-1d70-11eb-9145-d081ea7854d1.png)
and then here is with a distributed mesh with 5 processors
![distributed-5-procs](https://user-images.githubusercontent.com/10248304/97966450-b67b2b00-1d70-11eb-8f13-ba6395636c88.png)
So in replicated mesh mode, your point source at 0.2 will be applied to the element with bounds [0.1, 0.2]; however, for the distributed 5-proc case, your point source at 0.2 will be applied to the element with bounds [0.2, 0.3]. For a continuous finite element discretization it makes no difference what element the point source will be applied to. But for a discontinuous formulation, one element and its elemental dof gets the whole source. This understandably changes the solution