Improve stub generate command and associated testing
idaholab/moose pull request #16156
Opened 2020-11-11 22:14 UTC by aeslaughter

2020-11-11 22:15 UTC, aeslaughter commented
@iwhalvic Can you try this out for me?

2020-11-11 22:15 UTC, aeslaughter commented
You now use: `./moosedocs.py generate StochasticToolsApp`

2020-11-12 00:11 UTC, moosebuild commented
Job [Documentation](https://civet.inl.gov/job/621103/) on 2ecbdec wanted to post the following:

View the site [here](https://mooseframework.inl.gov/docs/PRs/16156/site)

This comment will be updated on new commits.

2020-11-12 00:12 UTC, iwhalvic requested changes

2020-11-12 00:15 UTC, aeslaughter commented on framework/doc/content/source/mesh/MeshGeneratorMesh.md
> +# MeshGeneratorMesh
It is, I noticed that this file is just empty in MOOSE now.

2020-11-12 00:16 UTC, aeslaughter commented on python/MooseDocs/commands/syntax.py
> +    parser = subparser.add_parser('syntax',
It doesn't, it will just dump all the syntax that exists for the executable. The previous dump did some other, un-necessary stuff

2020-11-12 01:20 UTC, iwhalvic submitted a review, later dismissed

2020-11-18 23:35 UTC, aeslaughter commented
The failure is from a test target that no longer exists.

2020-11-19 04:29 UTC, loganharbour commented on python/MooseDocs/commands/generate.py
> +#from ..tree import syntax
Remove? same in syntax.py

2020-11-19 04:29 UTC, loganharbour requested changes
Just a small request. Looks good to me otherwise - I'm glad I actually understand what you're doing here.

2020-11-19 18:47 UTC, aeslaughter commented on python/MooseDocs/commands/generate.py
> +#from ..tree import syntax
```suggestion
```

2020-11-23 22:01 UTC, loganharbour approved these changes

2020-11-23 22:01 UTC, merged