Restricting MultiAppUserObjectTransfer to boundaries and blocks
idaholab/moose pull request #16244
Opened 2020-11-18 21:20 UTC by andrsd

Closes #16241

2020-11-18 21:22 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/627802/) on c948e0b wanted to post the following:

Your code requires style changes.  

A patch was auto generated and copied [here](https://mooseframework.inl.gov/docs/PRs/16244/style.patch)  
You can directly apply the patch by running, in the top level of your repository:

`curl -s https://mooseframework.inl.gov/docs/PRs/16244/style.patch | git apply -v`  

Alternatively, with your repository up to date and in the top level of your repository:

`git clang-format 8a8611e83313980938c2ec60cfdd2f37fcc55bc8`

2020-11-18 21:25 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/627832/) on 1638c28 wanted to post the following:

Your code requires style changes.  

A patch was auto generated and copied [here](https://mooseframework.inl.gov/docs/PRs/16244/style.patch)  
You can directly apply the patch by running, in the top level of your repository:

`curl -s https://mooseframework.inl.gov/docs/PRs/16244/style.patch | git apply -v`  

Alternatively, with your repository up to date and in the top level of your repository:

`git clang-format 8a8611e83313980938c2ec60cfdd2f37fcc55bc8`

2020-11-19 15:48 UTC, aeslaughter reviewed
What are you not using the BlockRestrictable interface class?

2020-11-19 17:40 UTC, andrsd commented
> What are you not using the BlockRestrictable interface class?

I started with that, but ran into the following problems: The block-/boundary-restrictable classes are designed to work with the mesh/variables of "this" `FEProblem`. So that works only for transfers from sub-app to master app. The other direction does not work, because (a) there can be multiple instances of the sub-apps, (b) at the time of creating the transfer the sub-app infrastructure is not in place yet. That is also the reason the block/boundary restriction is checked/inited/set every time we call `execute` (the same approach is done in other transfers that can be restricted to blocks/boundaries).

2020-11-19 18:46 UTC, aeslaughter commented
Can you add that reason to the class comments please.

2020-11-19 19:23 UTC, andrsd commented
Yeah, that's a good idea...

2020-11-19 19:31 UTC, andrsd commented
The doxygen for this class is wrong - seems like a copy-paste from some other class, so I will fix that as well...

2020-11-19 21:44 UTC, moosebuild commented
Job [Documentation](https://civet.inl.gov/job/628721/) on c576d7e wanted to post the following:

View the site [here](https://mooseframework.inl.gov/docs/PRs/16244/site)

This comment will be updated on new commits.

2020-12-02 04:20 UTC, loganharbour requested changes
Minor changes.

2020-12-02 04:20 UTC, loganharbour commented on framework/include/transfers/MultiAppUserObjectTransfer.h
> +  std::set<BoundaryID> _bnd_ids;
These really should be private.

2020-12-02 04:20 UTC, loganharbour commented on framework/src/transfers/MultiAppUserObjectTransfer.C
> +          _bnd_ids.empty();
```suggestion
          _blk_ids.clear();
          _bnd_ids.clear();
```

2020-12-02 04:20 UTC, loganharbour commented on framework/src/transfers/MultiAppUserObjectTransfer.C
> +      _bnd_ids.empty();
```suggestion
      _blk_ids.clear();
      _bnd_ids.clear();
```

2020-12-02 04:23 UTC, loganharbour commented
The more that I think about it - why can the block/boundary IDs not be set in the constructor and then verified in `execute()`? Or maybe even earlier?

2020-12-02 13:23 UTC, andrsd commented on framework/src/transfers/MultiAppUserObjectTransfer.C
> +          _bnd_ids.empty();
Good catch. Thanks!

2020-12-02 13:28 UTC, andrsd commented on framework/include/transfers/MultiAppUserObjectTransfer.h
> +  std::set<BoundaryID> _bnd_ids;
Ok.

2020-12-02 13:32 UTC, andrsd commented
It is also explained the class doxygen. Nobody cares about doco 🙃

2020-12-03 15:05 UTC, loganharbour approved these changes

2020-12-04 13:48 UTC, merged