Create a shell script for civet to compile petsc-alt
idaholab/moose pull request #16356
Opened 2020-12-01 18:59 UTC by fdkong

Closes #16355

2020-12-01 19:00 UTC, fdkong commented
One thing I worry about is that users abuse this script. Anyway to forbidden users from using this script?

2020-12-01 19:05 UTC, milljm commented
This is no different than users abusing:

```bash
conda install some-odd-version-of-something
# like:
conda install moose-petsc=3.11.4
```

Or with the older moose-environment package:

```bash
module load moose-dev-clang-alt
# or
module load moose-dev-gcc-alt
```

I wouldn't worry.

2020-12-01 19:23 UTC, loganharbour commented
I'll add some meowbuild tests to try this out shortly.

2020-12-01 19:58 UTC, loganharbour commented
Can you get it to work with the additional options?

2020-12-01 20:06 UTC, fdkong commented
> Can you get it to work with the additional options?

What additional options you want to use?

2020-12-01 21:31 UTC, loganharbour commented
https://civet.inl.gov/job/637535/
https://civet.inl.gov/job/637537/
https://civet.inl.gov/job/637536/

Works like a charm with the new recipes.

2020-12-01 21:42 UTC, loganharbour requested changes

2020-12-01 21:42 UTC, loganharbour commented on scripts/update_and_rebuild_petsc_alt.sh
> +# Civet recipe should directly call update_and_rebuild_petsc_alt.sh
```suggestion
# This script is intended for INTERNAL use only by CIVET testing.
#
# It is recommended for all users to use our default version of PETSc,
# which can be compiled using scripts/update_and_rebuild_petsc.sh
#
# If you wish to use an alternate version of PETSc, you should compile
# it on your own and set PETSC_DIR and PETSC_ARCH.
```

2020-12-01 21:42 UTC, loganharbour commented on scripts/update_and_rebuild_petsc_alt.sh
> +echo "update_and_rebuild_petsc_alt is used for civet only, please do not use it!!!!!"
```suggestion
echo "*** WARNING ***"
echo "scripts/update_and_rebuild_petsc_alt.sh is intended for internal"
echo "use only. Please use scripts/update_and_rebuild_petsc.sh instead."
```

2020-12-01 23:48 UTC, moosebuild commented
Job [Documentation](https://civet.inl.gov/job/637716/) on 3d89325 wanted to post the following:

View the site [here](https://mooseframework.inl.gov/docs/PRs/16356/site)

This comment will be updated on new commits.

2020-12-02 00:30 UTC, loganharbour approved these changes
Merging before test completion - the pending tests are optional tests on the new test boxes.

2020-12-02 00:30 UTC, merged