Update conventional plane stress formulation in peridynamics module
idaholab/moose pull request #16653
Opened 2021-01-09 15:28 UTC by hchen139

closes #16652

2021-01-09 15:32 UTC, hchen139 commented
@bwspenc One component of the stiffness tensor for the conventional plane stress formulation was wrongly set to zero. I have made the correction and updated some other input parameter requirements for a PD auxkernel that postprocess the stress tensor for BPD and OSPD models.

2021-01-09 16:46 UTC, moosebuild commented
Job [Documentation](https://civet.inl.gov/job/656595/) on 4f5fbeb wanted to post the following:

View the site [here](https://mooseframework.inl.gov/docs/PRs/16653/site)

This comment will be updated on new commits.

2021-01-11 22:25 UTC, bwspenc requested changes

2021-01-11 22:25 UTC, bwspenc commented on modules/peridynamics/src/auxkernels/NodalRankTwoPD.C
> +    _youngs_modulus = getParam<Real>("youngs_modulus");
```
if (_rank_two_tensor == "stress")
{
  check for defined parameters
  ...
}

2021-01-11 22:25 UTC, bwspenc commented on modules/peridynamics/src/auxkernels/NodalRankTwoPD.C
> +  {
Same rearrangement of logic as above

2021-01-18 17:34 UTC, bwspenc approved these changes

2021-01-18 17:34 UTC, bwspenc commented on modules/peridynamics/src/auxkernels/NodalRankTwoPD.C
> +    else
You don't actually need to put the following lines of code inside the `else` block, but it doesn't hurt anything, so I'll let that slide.

2021-01-18 17:34 UTC, merged