Add explanation of csv file format in PiecewiseBilinear function
idaholab/moose pull request #16725
Opened 2021-01-18 17:29 UTC by GiudGiud

Closes #16724

Minor improvements to documentation.
Not sure what the markdown will look like yet, with these '-' for making a list.

2021-01-18 19:34 UTC, moosebuild commented
Job [Documentation](https://civet.inl.gov/job/661124/) on 90ba03c wanted to post the following:

View the site [here](https://mooseframework.inl.gov/docs/PRs/16725/site)

This comment will be updated on new commits.

2021-01-18 21:38 UTC, aeslaughter requested changes, later dismissed
Use MooseDocs list format

2021-01-18 21:38 UTC, aeslaughter commented on framework/doc/content/source/functions/PiecewiseBilinear.md
> +all values of `x`.
```suggestion
- first line holds the `x` values.
- each subsequent line holds the `y` value then the list of `z` values for this `y` and
  all values of `x`.
```

2021-03-19 03:56 UTC, loganharbour approved these changes

2021-03-19 03:57 UTC, merged