Create NearestRadiusLayeredAverage
idaholab/moose pull request #16832
Opened 2021-01-28 21:50 UTC by vincentlaboure

Closes #16829

2021-01-28 22:01 UTC, loganharbour requested changes

2021-01-28 22:01 UTC, loganharbour commented on framework/src/userobject/NearestRadiusLayeredAverage.C
> +defineLegacyParams(NearestRadiusLayeredAverage);
```suggestion
```

2021-01-28 22:01 UTC, loganharbour commented on framework/src/userobject/NearestRadiusLayeredAverage.C
> +  params.set<MooseEnum>("dist_norm") = "radius";
Should this not be suppressed too?

2021-01-28 22:51 UTC, vincentlaboure commented
Comments should be addressed. Thanks for the quick review @loganharbour!

2021-01-28 23:51 UTC, loganharbour approved these changes

2021-01-29 00:19 UTC, moosebuild commented
Job [Documentation](https://civet.inl.gov/job/669709/) on 43e105d wanted to post the following:

View the site [here](https://mooseframework.inl.gov/docs/PRs/16832/site)

This comment will be updated on new commits.

2021-01-29 04:14 UTC, merged

2021-02-01 15:27 UTC, vincentlaboure commented
Thanks @loganharbour!