Make aux kernel work properly for high-order boundary restriction
idaholab/moose pull request #16896
Opened 2021-02-04 20:12 UTC by YaqiWang

And issue an error when multiple sides on boundary touching the same elements.

Close #16895 and #5061.

2021-02-04 21:24 UTC, moosebuild commented
Job [Documentation](https://civet.inl.gov/job/673644/) on 3b941ba wanted to post the following:

View the site [here](https://mooseframework.inl.gov/docs/PRs/16896/site)

This comment will be updated on new commits.

2021-02-04 22:42 UTC, YaqiWang commented
Tag @bwspenc

2021-02-05 02:08 UTC, loganharbour requested changes

2021-02-05 02:08 UTC, loganharbour commented on framework/src/auxkernels/AuxKernel.C
> +          mooseError("Boundary restricted auxiliary kernel ",
```suggestion
          mooseError("Boundary restricted auxiliary kernel '",
```

2021-02-05 02:08 UTC, loganharbour commented on framework/src/auxkernels/AuxKernel.C
> +                     " has element (ID=",
```suggestion
                     "' has element (id = ",
```

2021-02-05 02:08 UTC, loganharbour commented on framework/src/auxkernels/AuxKernel.C
> +                     "multiple auxilary variables/kernels each on a part of the boundaries.");
```suggestion
                     ") that has multiple boundary sides.\nSee the AuxKernel documentation on boundary restricted aux kernels for understanding this error.");
```

2021-02-05 02:08 UTC, loganharbour commented on test/tests/auxkernels/element_aux_boundary/tests
> +    requirement = "MOOSE shall support boundary restricted auxilary elemental variables with high order shape functions."
```suggestion
    requirement = "MOOSE shall support boundary restricted auxiliary elemental variables with high order shape functions."
```

2021-02-05 02:08 UTC, loganharbour commented on test/tests/auxkernels/element_aux_boundary/tests
> +    requirement = "MOOSE shall error if a boundary restricted elemental auxilary kernel evaluates on multple sides touching the same elements."
```suggestion
    requirement = "MOOSE shall error if a boundary restricted elemental auxiliary kernel is evaluated on an element with multiple boundary sides."
```

2021-02-05 02:08 UTC, loganharbour commented on framework/src/auxkernels/AuxKernel.C
> +                     "multiple auxilary variables/kernels each on a part of the boundaries.");
We're looking into being able to link to documentation from within source... would be nice

2021-02-05 02:14 UTC, YaqiWang commented on framework/doc/content/syntax/AuxKernels/index.md
> +Because of this, the auxiliary variable will only have meaningful values on the boundaries even though it is defined on mesh subdomains.
Not for this change because aux variable is not boundary restricted.

2021-02-05 02:16 UTC, YaqiWang commented on framework/src/auxkernels/AuxKernel.C
> +        if (!stat.second)
There multiple versions of `std::set::insert` with different returned values, so I am not sure if `auto` here can work.

2021-02-05 03:08 UTC, YaqiWang commented on framework/src/auxkernels/AuxKernel.C
> +        if (!stat.second)
Surprisingly `auto` works here. I will make the change.

2021-02-05 03:16 UTC, YaqiWang commented
Comments are addressed. We will need to wait for @bwspenc 's answer on how to patch BISON.

2021-02-09 03:12 UTC, YaqiWang commented
@loganharbour I want this to get in first. Looks like fixing Bison will take some time so I replaced that error with a warning. Because of this I did not close that old issue. We can revert the second commit after Bison is fixed in the future.

2021-02-09 03:18 UTC, loganharbour commented
A warning won't work. It'll still fail tests.

2021-02-09 04:35 UTC, YaqiWang commented
Nope, it passed.

2021-02-09 18:08 UTC, YaqiWang commented
@loganharbour can this be merged?

2021-02-10 17:05 UTC, YaqiWang commented
Ok, remove the second commit since we will see app patched soon.

2021-02-10 21:02 UTC, loganharbour approved these changes
Once the bison fix makes its way into master, we'll get this in.

2021-02-11 18:41 UTC, moosebuild commented
Job [Internal App tests](https://civet.inl.gov/job/679463/) on 6d98b5e : invalidated by @YaqiWang

seems unrelated

2021-02-11 19:09 UTC, merged

2021-02-11 19:35 UTC, YaqiWang commented
This closed #5061 as well.