Remove an input file
idaholab/moose pull request #16975
Opened 2021-02-12 02:27 UTC by YaqiWang

This file is not covered by any test and is almost the same as the other one in the folder. I suspect it was accidentally checked in.

This also can close #15767.

2021-02-12 03:59 UTC, moosebuild commented
Job [Documentation](https://civet.inl.gov/job/681648/) on a34f281 wanted to post the following:

View the site [here](https://mooseframework.inl.gov/docs/PRs/16975/site)

This comment will be updated on new commits.

2021-02-13 17:42 UTC, GiudGiud requested changes
This file was added to address #13020
Unfortunately, the person who added this file forgot to add the test and this was not caught by the review. 

I think the fix here is to add the test to tests, not delete the file.

Though if possible, you could use cli_args to use a single input file for both tests.

2021-02-15 18:01 UTC, YaqiWang commented
I see. I suggest to open that issue. I will keep the files and remove that wrong param in the file. Note that I did not see the difference of this file and the other input in the same folder.

2021-02-16 22:53 UTC, moosebuild commented
Job [Internal App tests](https://civet.inl.gov/job/682711/) on 5aa0325 : invalidated by @YaqiWang

unrelated?

2021-02-18 05:52 UTC, YaqiWang commented
This should be ready. Just want to close #15767 here.

2021-02-18 13:05 UTC, GiudGiud commented
Inner mesh fraction is still a parameter: (https://github.com/idaholab/moose/blob/next/framework/src/mesh/ConcentricCircleMesh.C)

Not only that but inner mesh fraction is also in this input file
(https://github.com/idaholab/moose/blob/next/test/tests/mesh/concentric_circle_mesh/concentric_circle_mesh.i)

2021-02-18 15:59 UTC, YaqiWang commented
That is the old mesh but not the corresponding mesh generator here.

2021-02-18 16:03 UTC, GiudGiud approved these changes

2021-02-18 16:03 UTC, merged

2021-02-18 16:06 UTC, GiudGiud commented
you're right. All good then. Re-opened the issue related to this input file.