Fixed a bug in Eigenvalue executioner when free_power_iterations=0
idaholab/moose pull request #17029
Opened 2021-02-17 00:58 UTC by fdkong

Closes #17026

2021-02-17 00:59 UTC, fdkong commented
@YaqiWang Could you check if it works in griffin? And any other issues?

2021-02-17 02:39 UTC, moosebuild commented
Job [Documentation](https://civet.inl.gov/job/684859/) on 904c30c wanted to post the following:

View the site [here](https://mooseframework.inl.gov/docs/PRs/17029/site)

This comment will be updated on new commits.

2021-02-17 09:05 UTC, YaqiWang commented
This works fine for Griffin. But why the old petsc produces different (better) convergence to the correct eigenvalue? I am concerned. I have noticed that the new eigenvalue executioner requires more nonlinear iterations than the old eigenvalue executioner.

2021-02-17 17:27 UTC, YaqiWang requested changes
Looks good to me. You said old slepc always does free power iteration internally. How many of that? We do not have a command-line option to control that number?

2021-02-17 17:49 UTC, loganharbour requested changes

2021-02-17 17:49 UTC, loganharbour commented on test/tests/problems/eigen_problem/initial_condition/tests
> +    requirement = "The system shall work correctly when use no free power iteration."
```suggestion
    requirement = "The system shall support eigenvalue execution without free power iterations."
```

2021-02-18 05:51 UTC, YaqiWang submitted a review, later dismissed

2021-02-18 21:16 UTC, fdkong commented
@loganharbour Ready for review again

2021-02-18 21:27 UTC, loganharbour approved these changes

2021-02-19 04:08 UTC, merged