Use parallel push/pull in MultiAppTransfer
idaholab/moose pull request #17110
Opened 2021-02-23 21:20 UTC by fdkong

Refs #16879

2021-02-23 22:45 UTC, moosebuild commented
Job [Documentation](https://civet.inl.gov/job/690299/) on 94acd49 wanted to post the following:

View the site [here](https://mooseframework.inl.gov/docs/PRs/17110/site)

This comment will be updated on new commits.

2021-02-24 02:20 UTC, loganharbour requested changes
All looks great - very beautiful code.

Small changes. Mostly involves reserving in vectors and changing variable names like `i_proc` to something more useful now that we don't index contiguously but use a map.

2021-02-24 02:20 UTC, loganharbour commented on framework/src/transfers/MultiAppNearestNodeTransfer.C
> +#include "timpi/communicator.h"
All MooseObjects are ParallelObjects - you shouldn't ever need to include the comm includes

2021-02-24 02:20 UTC, loganharbour commented on framework/src/transfers/MultiAppNearestNodeTransfer.C
> +      std::copy(qps.begin(), qps.end(), std::back_inserter(incoming_qps_from_pid));
```suggestion
      incoming_qps_from_pid.reserve(incoming_qps_from_pid.size() + qps.size());
      std::copy(qps.begin(), qps.end(), std::back_inserter(incoming_qps_from_pid));
```

2021-02-24 02:20 UTC, loganharbour commented on framework/src/transfers/MultiAppNearestNodeTransfer.C
> +      for (unsigned int qp = 0; qp < qps.second.size(); qp++)
```suggestion
      for (std::size_t qp = 0; qp < qps.second.size(); qp++)
```

2021-02-24 02:20 UTC, loganharbour commented on framework/src/transfers/MultiAppNearestNodeTransfer.C
> +      processor_id_type i_proc = qps.first;
Now that you're moving a map, you should switch `i_proc -> pid` for everything in this loop. I think that you can

```suggestion
      const processor_id_type pid = qps.first;
```

2021-02-24 02:20 UTC, loganharbour commented on framework/src/transfers/MultiAppNearestNodeTransfer.C
> +    std::copy(evals.begin(), evals.end(), std::back_inserter(incoming_evals_for_pid));
```suggestion
    incoming_evals_for_pid.reserve(incoming_evals_for_pid.size() + evals.size());
    std::copy(evals.begin(), evals.end(), std::back_inserter(incoming_evals_for_pid));
```

2021-02-24 02:20 UTC, loganharbour commented on framework/src/transfers/MultiAppNearestNodeTransfer.C
> +            auto i_from = evals.first;
Same here - you should switch this to being named `pid` or something of the sort.

2021-02-24 02:20 UTC, loganharbour commented on framework/src/transfers/MultiAppProjectionTransfer.C
> +#include "timpi/communicator.h"
Should be able to remove

2021-02-24 02:20 UTC, loganharbour commented on framework/src/transfers/MultiAppProjectionTransfer.C
> +      std::copy(qps.begin(), qps.end(), std::back_inserter(incoming_qps_from_pid));
```suggestion
      incoming_qps_from_pid.reserve(incoming_qps_from_pid.size() + qps.size());
      std::copy(qps.begin(), qps.end(), std::back_inserter(incoming_qps_from_pid));
```

2021-02-24 02:20 UTC, loganharbour commented on framework/src/transfers/MultiAppProjectionTransfer.C
> +    processor_id_type i_proc = qps.first;
Same here - name `pid` or something of the sort

2021-02-24 02:20 UTC, loganharbour commented on framework/src/transfers/MultiAppProjectionTransfer.C
> +        std::copy(evals.begin(), evals.end(), std::back_inserter(incoming_evals_ids_for_pid));
```suggestion
        incoming_evals_ids_for_pid.reserve(incoming_evals_ids_for_pid.size() + evals.size());
        std::copy(evals.begin(), evals.end(), std::back_inserter(incoming_evals_ids_for_pid));
```

2021-02-24 02:20 UTC, loganharbour commented on framework/src/transfers/MultiAppProjectionTransfer.C
> +          processor_id_type i_proc = values_ids.first;
Switch to `pid`

2021-02-25 14:53 UTC, loganharbour approved these changes
BeautifuL!

2021-02-25 14:55 UTC, loganharbour commented
I added the parallel sweep tests. Would like to see them pass before getting this in.

2021-02-25 15:58 UTC, fdkong commented
Good idea

2021-02-25 17:33 UTC, loganharbour commented
I say we hold for a little bit until we figure out what to do about the failures.

2021-03-03 00:17 UTC, fdkong commented
@rui-hu, Do you have suggestions on SAM failures here?

2021-03-03 20:27 UTC, merged