Make member vars between Density and ADDensity consistent
idaholab/moose pull request #17230
Opened 2021-03-04 16:05 UTC by loganharbour

Closes #17229

@dschwen ask and thou shall receive

2021-03-04 17:36 UTC, moosebuild commented
Job [Documentation](https://civet.inl.gov/job/697764/) on 0a3ed1b wanted to post the following:

View the site [here](https://mooseframework.inl.gov/docs/PRs/17230/site)

This comment will be updated on new commits.

2021-03-04 18:15 UTC, dschwen submitted a review, later dismissed

2021-03-04 18:18 UTC, dschwen requested changes

2021-03-04 18:18 UTC, dschwen commented on modules/misc/src/materials/Density.C
> +    _grad_disp(_is_coupled ? coupledGradients("") : std::vector<const VariableGradient *>()),
```suggestion
    _grad_disp(_is_coupled ? coupledGradients("displacements") : std::vector<const VariableGradient *>()),
```

2021-03-04 18:23 UTC, loganharbour commented on modules/misc/src/materials/Density.C
> +    _grad_disp(_is_coupled ? coupledGradients("") : std::vector<const VariableGradient *>()),
oops I'm bad at this

2021-03-04 18:25 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/697916/) on de9669d wanted to post the following:

Your code requires style changes.  

A patch was auto generated and copied [here](https://mooseframework.inl.gov/docs/PRs/17230/style.patch)  
You can directly apply the patch by running, in the top level of your repository:

`curl -s https://mooseframework.inl.gov/docs/PRs/17230/style.patch | git apply -v`  

Alternatively, with your repository up to date and in the top level of your repository:

`git clang-format a3511e84f92dd59c3f7c4f5ea61a4431e4d57cf3`

2021-03-05 16:23 UTC, loganharbour commented
@dschwen where'd ya go

2021-03-09 01:31 UTC, dschwen approved these changes
:+1:

2021-03-09 01:31 UTC, merged