Remove execute_on dependency from conservative transfer
idaholab/moose pull request #17232
Opened 2021-03-04 21:02 UTC by fdkong

Closes #17186

2021-03-04 21:11 UTC, lindsayad requested changes
So this allows someone to compute a user object regardless of where you are in the simulation (e.g. regardless of whether I'm computing a residual, Jacobian, at the beginning of a timestep, etc.)? This seems like it could be dangerous. What if a user object only works at a particular stage of the simulation? I don't actually even know what `EXEC_NONE` means

2021-03-04 21:11 UTC, lindsayad commented on framework/src/problems/FEProblemBase.C
> +  computeUserObjectsInternal(EXEC_NONE, Moose::POST_AUX, query);
`POST_AUX` here seems pretty arbitrary

2021-03-04 21:11 UTC, lindsayad commented on framework/src/problems/FEProblemBase.C
> +  computeUserObjectsInternal(EXEC_NONE, Moose::POST_AUX, query);
Can you add an argument to this new API that can control the second argument to `computeUserObjectsInternal`?

2021-03-04 22:26 UTC, moosebuild commented
Job [Documentation](https://civet.inl.gov/job/698091/) on 8e51115 wanted to post the following:

View the site [here](https://mooseframework.inl.gov/docs/PRs/17232/site)

This comment will be updated on new commits.

2021-03-09 19:43 UTC, fdkong commented
@lindsayad It is ready for review again

2021-03-09 22:53 UTC, lindsayad approved these changes
Beautiful changes, beautiful code

2021-03-09 22:53 UTC, lindsayad commented on framework/src/transfers/MultiAppConservativeTransfer.C
> +                   "make sure that execute_on options are not hardcoded in the code \n");
Love it!

2021-03-10 17:18 UTC, aeslaughter approved these changes
I like it!

2021-03-10 17:19 UTC, merged