Allow target_boundary for elemental nearest point transfers
idaholab/moose pull request #17248
Opened 2021-03-08 20:44 UTC by aprilnovak

This adds the capability to set a `target_boundary` for CONSTANT MONOMIAL transfers in `MultiAppNearestNodeTransfer`. Before this PR, the object parameter `target_boundary` wasn't actually used if you were transferring to an elemental variable, which could lead to some unexpected behavior as described in #17214. So, this PR extends the nodal `target_boundary` feature to cover CONSTANT MONOMIAL target variables. Specifically, this PR includes:

- Added `getTargetLocalNodes` just to combine some repeated code that was used for nodal transfers
- Added `getTargetLocalElems` to find the elements to transfer to on the target boundary
- A test that transfers CONSTANT MONOMIAL to/from a master application with boundary restriction

Two important notes:

1. This PR does not address the issues I have seen with FIRST MONOMIAL transfers as described in #17246. So, the boundary restriction, just like non-restricted transfers for FIRST MONOMIAL, also do not work here.
2. I used the `getTargetLocalElems` function both in the nearest-neighbor identification part, as well as in the variable-filling part, of this transfer. I would appreciate a careful review of this here, because I replaced the 

`for (auto & elem : to_mesh.active_local_element_ptr_range())` 

with 

`for (auto & elem: as_range(to_mesh.local_elements_begin(), to_mesh.local_elements_end())`

I'm not 100% sure of the difference between local elements and *active* local elements, but changing this line so that I could use `getTargetLocalElems` in *two* locations in the `MultiAppNearestNodeTransfer` didn't seem to have any bad effect because the transfer works as expected. Anyways, just trying to be explicit about one location that needs careful review!

2021-03-08 22:36 UTC, moosebuild commented
Job [Documentation](https://civet.inl.gov/job/700539/) on 34ca99d wanted to post the following:

View the site [here](https://mooseframework.inl.gov/docs/PRs/17248/site)

This comment will be updated on new commits.

2021-03-08 23:28 UTC, aprilnovak commented
Ok I feel like this debug failure is revealing a new bug/deficiency in MOOSE - locally, I replaced the mesh generator stuff in each file with a `FileMesh` that I got by running each input with `--mesh-only`, and then there's no longer a debug mode error. 

```
[Mesh]
  type = FileMesh
  file = file_I_generated_from_running_with_meshonly.e
[]
```

So the error seems just to do with having the mesh generators, and nothing to do with what the test is actually covering. The transfer tests only have the following mesh generators covered:

- GeneratedMeshGenerator
- SubdomainBoundingBoxGenerator
- FileMeshGenerator
- ElementSubdomainGenerator
- SideSetsBetweenSubdomainsGenerator

So it seems something is up with either the `AnnularMeshGenerator`, `CombinerGenerator`, `FancyExtruderGenerator`, or `RenameBoundaryGenerator`, which would all be firsts to be tested with the transfers.

2021-03-11 16:35 UTC, loganharbour reviewed
I'm slowly fishing through this - it'll probably be a little while.

There are quite a few improvements to be made and this is a pretty great start. It's gonna take a bit to remind myself how this transfer works :) and I'm getting through it.

I believe there is an issue with using a Node ID for indexing incoming evaluations for elemental values (because these IDs are not unique at spatial nodes for elemental variables). This is partially discussed in #17273, but is still a WIP.

2021-03-11 17:13 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/703043/) on 7a6fff4 wanted to post the following:

Your code requires style changes.  

A patch was auto generated and copied [here](https://mooseframework.inl.gov/docs/PRs/17248/style.patch)  
You can directly apply the patch by running, in the top level of your repository:

`curl -s https://mooseframework.inl.gov/docs/PRs/17248/style.patch | git apply -v`  

Alternatively, with your repository up to date and in the top level of your repository:

`git clang-format 62bbfbbb5aa17a8822ac5801e6dafd3529ffcbf1`

2021-03-11 17:14 UTC, aprilnovak commented
Per our discussion, I've inserted errors for anyone using FIRST or higher order MONOMIAL for both the sending and receiving variable, since this transfer incorrectly set the elemental DOFs based on the (spatial) element nodes. This should be much simpler now - mostly just cutting out duplicated code and putting it in member functions, plus boundary target for elemental.

2021-03-11 19:55 UTC, moosebuild commented
Job [Modules debug](https://civet.inl.gov/job/703071/) on 7eb897e : invalidated by @loganharbour

Fix merged to next

2021-04-07 21:53 UTC, moosebuild commented
Job [Modules debug](https://civet.inl.gov/job/703071/) on 7eb897e : invalidated by @lindsayad

Hopefully fix made it into devel in the last month

2021-04-07 21:54 UTC, lindsayad commented
Is there anything left to do here?

2021-04-07 21:56 UTC, aprilnovak commented
There's not any more development on my end, so as long as the changes have been reviewed by someone then this should be good to go!

2021-04-08 15:14 UTC, lindsayad commented
I am less familiar with transfers so going to leave this to @loganharbour or @fdkong

2021-04-08 22:08 UTC, loganharbour commented
I had a review up for this... but it disappeared. Boo. It's on my list.

2021-04-13 17:22 UTC, fdkong requested changes
We do want to support higher order elemental  variables other than the constant variable.

We did not do projection on local elements completely right, but we were doing something that was useful.

I was surprised that we did not break any tests by removing that

2021-04-13 17:34 UTC, aprilnovak commented
I'm not sure anything useful was being done before for higher order aux (but I could be wrong on that), see the figures here: https://github.com/idaholab/moose/issues/17246

My take is: the higher order elemental cases didn't make sense because we were computing the interpolation based on the solution at points associated with the element nodes. But elemental auxvariables have DOFs that aren't associated with those nodes at all, so the transfer was conflating a spatial dependence via nodes with DOFs that are independent of nodes. 

Do you agree with this interpretation? 

I was also surprised that no tests broke, which shows that no one was using the feature in the first place and there weren't any tests covering it (which is a prereq for something being wrong with the transfer, but existing in the framework nonetheless).

2021-04-19 17:15 UTC, fdkong commented
Yes,  I feel shamed because my original implementation was wrong. 

@roystgnr will do a generic implementation soon. So I am fine with this PR.

2021-04-20 20:25 UTC, fdkong commented
Oh, it is blue crab. The blue crab might use an out-of-date SAM. 

Let me invalidate 

```
Compiling C++ (in opt mode) /opt/civet/build_0/blue_crab/SAM/build/unity_src/components_Unity.C...
Compiling C++ (in opt mode) /opt/civet/build_0/blue_crab/SAM/build/unity_src/materials_Unity.C...
Compiling C++ (in opt mode) /opt/civet/build_0/blue_crab/SAM/build/unity_src/eos_Unity.C...
In file included from /opt/civet/build_0/blue_crab/SAM/build/unity_src/transfer_Unity.C:2:
/opt/civet/build_0/blue_crab/SAM/src/transfer/MultiAppCoordSwitchNearestNodeTransfer.C: In member function 'virtual void MultiAppCoordSwitchNearestNodeTransfer::execute()':
/opt/civet/build_0/blue_crab/SAM/src/transfer/MultiAppCoordSwitchNearestNodeTransfer.C:370:21: error: 'class std::map<unsigned int, std::vector<unsigned int> >' has no member named 'resize'; did you mean 'size'?
  370 |       _cached_froms.resize(n_processors());
      |                     ^~~~~~
      |                     size
/opt/civet/build_0/blue_crab/SAM/src/transfer/MultiAppCoordSwitchNearestNodeTransfer.C:371:23: error: 'class std::map<unsigned int, std::vector<unsigned int> >' has no member named 'resize'; did you mean 'size'?
  371 |       _cached_dof_ids.resize(n_processors());
      |                       ^~~~~~
      |                       size
Compiling C++ (in opt mode) /opt/civet/build_0/blue_crab/bison/build/unity_src/constraints_Unity.C...
Compiling C++ (in opt mode) /opt/civet/build_0/blue_crab/bison/build/unity_src/mesh_Unity.C...
Compiling C++ (in opt mode) /opt/civet/build_0/blue_crab/bison/build/unity_src/postprocessors_Unity.C...
Compiling C++ (in opt mode) /opt/civet/build_0/blue_crab/bison/build/unity_src/userobject_Unity.C...
make: *** [/opt/civet/build_0/moose/framework/build.mk:118: /opt/civet/build_0/blue_crab/SAM/build/unity_src/transfer_Unity.x86_64-pc-linux-gnu.opt.lo] Error 1
make: *** Waiting for unfinished jobs....
ERROR: exiting with code 2
```

2021-04-20 20:25 UTC, moosebuild commented
Job [Controlled App tests PETSc alt](https://civet.inl.gov/job/703080/) on 7eb897e : invalidated by @fdkong

2021-04-20 20:26 UTC, moosebuild commented
Job [Controlled App tests](https://civet.inl.gov/job/703077/) on 7eb897e : invalidated by @fdkong

2021-04-20 23:59 UTC, fdkong commented
OK, we are good now.

@loganharbour @lindsayad If you guys do not have any further suggestions, I am going to merge it this in tomorrow morning

2021-04-21 15:18 UTC, fdkong approved these changes

2021-04-21 15:18 UTC, merged

2021-04-21 20:34 UTC, fdkong commented
@aprilnovak  There are some test diffs in the integration process (next branch). Could you take a look?

```
   OK transfers/multiapp_nearest_node_transfer.boundary_tomaster [recover]
transfers/multiapp_nearest_node_transfer.boundary_elemental: Working Directory: /opt/civet/build_0/moose/test/tests/transfers/multiapp_nearest_node_transfer
transfers/multiapp_nearest_node_transfer.boundary_elemental: Running command: mpiexec -n 15 /opt/civet/build_0/moose/test/moose_test-opt -i boundary_elemental_master.i --recover --recoversuffix cpr --error --error-unused --error-override --no-gdb-backtrace
transfers/multiapp_nearest_node_transfer.boundary_elemental: 
transfers/multiapp_nearest_node_transfer.boundary_elemental: 
transfers/multiapp_nearest_node_transfer.boundary_elemental: 
transfers/multiapp_nearest_node_transfer.boundary_elemental: *** Info ***
transfers/multiapp_nearest_node_transfer.boundary_elemental: Using boundary_elemental_master_out_cp/0001 for recovery.
transfers/multiapp_nearest_node_transfer.boundary_elemental: Creating MultiApp sub of type MooseTestApp of level 1 and number 0:
transfers/multiapp_nearest_node_transfer.boundary_elemental: sub0: 
transfers/multiapp_nearest_node_transfer.boundary_elemental: 
transfers/multiapp_nearest_node_transfer.boundary_elemental: Running App: main
transfers/multiapp_nearest_node_transfer.boundary_elemental: 
transfers/multiapp_nearest_node_transfer.boundary_elemental: Framework Information:
transfers/multiapp_nearest_node_transfer.boundary_elemental: MOOSE Version:           git commit ea6ce2b25e on 2021-04-21
transfers/multiapp_nearest_node_transfer.boundary_elemental: LibMesh Version:         27141d18f3137f77e33cdb3d565fd38ebfbfc46f
transfers/multiapp_nearest_node_transfer.boundary_elemental: PETSc Version:           3.14.2
transfers/multiapp_nearest_node_transfer.boundary_elemental: SLEPc Version:           3.14.0
transfers/multiapp_nearest_node_transfer.boundary_elemental: Current Time:            Wed Apr 21 13:59:41 2021
transfers/multiapp_nearest_node_transfer.boundary_elemental: Executable Timestamp:    Wed Apr 21 12:42:38 2021
transfers/multiapp_nearest_node_transfer.boundary_elemental: 
transfers/multiapp_nearest_node_transfer.boundary_elemental: Parallelism:
transfers/multiapp_nearest_node_transfer.boundary_elemental:   Num Processors:          15
transfers/multiapp_nearest_node_transfer.boundary_elemental:   Num Threads:             1
transfers/multiapp_nearest_node_transfer.boundary_elemental: 
transfers/multiapp_nearest_node_transfer.boundary_elemental: Mesh: 
transfers/multiapp_nearest_node_transfer.boundary_elemental:   Parallel Type:           replicated
transfers/multiapp_nearest_node_transfer.boundary_elemental:   Mesh Dimension:          3
transfers/multiapp_nearest_node_transfer.boundary_elemental:   Spatial Dimension:       3
transfers/multiapp_nearest_node_transfer.boundary_elemental:   Nodes:                   
transfers/multiapp_nearest_node_transfer.boundary_elemental:     Total:                 125
transfers/multiapp_nearest_node_transfer.boundary_elemental:     Local:                 18
transfers/multiapp_nearest_node_transfer.boundary_elemental:   Elems:                   
transfers/multiapp_nearest_node_transfer.boundary_elemental:     Total:                 64
transfers/multiapp_nearest_node_transfer.boundary_elemental:     Local:                 4
transfers/multiapp_nearest_node_transfer.boundary_elemental:   Num Subdomains:          1
transfers/multiapp_nearest_node_transfer.boundary_elemental:   Num Partitions:          1
transfers/multiapp_nearest_node_transfer.boundary_elemental:   Partitioner:             metis
transfers/multiapp_nearest_node_transfer.boundary_elemental: 
transfers/multiapp_nearest_node_transfer.boundary_elemental: Nonlinear System:
transfers/multiapp_nearest_node_transfer.boundary_elemental:   Num DOFs:                125
transfers/multiapp_nearest_node_transfer.boundary_elemental:   Num Local DOFs:          18
transfers/multiapp_nearest_node_transfer.boundary_elemental:   Variables:               "dummy" 
transfers/multiapp_nearest_node_transfer.boundary_elemental:   Finite Element Types:    "LAGRANGE" 
transfers/multiapp_nearest_node_transfer.boundary_elemental:   Approximation Orders:    "FIRST" 
transfers/multiapp_nearest_node_transfer.boundary_elemental: 
transfers/multiapp_nearest_node_transfer.boundary_elemental: Auxiliary System:
transfers/multiapp_nearest_node_transfer.boundary_elemental:   Num DOFs:                317
transfers/multiapp_nearest_node_transfer.boundary_elemental:   Num Local DOFs:          30
transfers/multiapp_nearest_node_transfer.boundary_elemental:   Variables:               "u" { "w_from_sub_left_to_left" "w_from_sub_top_to_top" "w_from_sub_right_to_bottom" 
transfers/multiapp_nearest_node_transfer.boundary_elemental:                              } 
transfers/multiapp_nearest_node_transfer.boundary_elemental:   Finite Element Types:    "LAGRANGE" "MONOMIAL" 
transfers/multiapp_nearest_node_transfer.boundary_elemental:   Approximation Orders:    "FIRST" "CONSTANT" 
transfers/multiapp_nearest_node_transfer.boundary_elemental: 
transfers/multiapp_nearest_node_transfer.boundary_elemental: Execution Information:
transfers/multiapp_nearest_node_transfer.boundary_elemental:   Executioner:             Transient
transfers/multiapp_nearest_node_transfer.boundary_elemental:   TimeStepper:             ConstantDT
transfers/multiapp_nearest_node_transfer.boundary_elemental:   Solver Mode:             Preconditioned JFNK
transfers/multiapp_nearest_node_transfer.boundary_elemental: 
transfers/multiapp_nearest_node_transfer.boundary_elemental: Initializing All MultiApps
transfers/multiapp_nearest_node_transfer.boundary_elemental: sub0: 
transfers/multiapp_nearest_node_transfer.boundary_elemental: sub0: Running App: sub0
transfers/multiapp_nearest_node_transfer.boundary_elemental: sub0: Parallelism:
transfers/multiapp_nearest_node_transfer.boundary_elemental: sub0:   Num Processors:          15
transfers/multiapp_nearest_node_transfer.boundary_elemental: sub0:   Num Threads:             1
transfers/multiapp_nearest_node_transfer.boundary_elemental: sub0: 
transfers/multiapp_nearest_node_transfer.boundary_elemental: sub0: Mesh: 
transfers/multiapp_nearest_node_transfer.boundary_elemental: sub0:   Parallel Type:           replicated
transfers/multiapp_nearest_node_transfer.boundary_elemental: sub0:   Mesh Dimension:          3
transfers/multiapp_nearest_node_transfer.boundary_elemental: sub0:   Spatial Dimension:       3
transfers/multiapp_nearest_node_transfer.boundary_elemental: sub0:   Nodes:                   
transfers/multiapp_nearest_node_transfer.boundary_elemental: sub0:     Total:                 343
transfers/multiapp_nearest_node_transfer.boundary_elemental: sub0:     Local:                 64
transfers/multiapp_nearest_node_transfer.boundary_elemental: sub0:   Elems:                   
transfers/multiapp_nearest_node_transfer.boundary_elemental: sub0:     Total:                 216
transfers/multiapp_nearest_node_transfer.boundary_elemental: sub0:     Local:                 15
transfers/multiapp_nearest_node_transfer.boundary_elemental: sub0:   Num Subdomains:          1
transfers/multiapp_nearest_node_transfer.boundary_elemental: sub0:   Num Partitions:          15
transfers/multiapp_nearest_node_transfer.boundary_elemental: sub0:   Partitioner:             metis
transfers/multiapp_nearest_node_transfer.boundary_elemental: sub0: 
transfers/multiapp_nearest_node_transfer.boundary_elemental: sub0: Nonlinear System:
transfers/multiapp_nearest_node_transfer.boundary_elemental: sub0:   Num DOFs:                343
transfers/multiapp_nearest_node_transfer.boundary_elemental: sub0:   Num Local DOFs:          64
transfers/multiapp_nearest_node_transfer.boundary_elemental: sub0:   Variables:               "dummy" 
transfers/multiapp_nearest_node_transfer.boundary_elemental: sub0:   Finite Element Types:    "LAGRANGE" 
transfers/multia [...]

2021-04-21 21:36 UTC, aprilnovak commented
How do I duplicate this locally? I pulled the latest `next` and the test passes for me. Is there something else I need to do?

2021-04-21 21:39 UTC, fdkong commented
Did you try "mpirun -n 15"?

2021-04-21 21:41 UTC, aprilnovak commented
I tried with 4 (all my machine has):

```
(moose) {16:41}~/projects/moose/test:next ✗ ➭ ./run_tests --parallel 4 --re=boundary_elemental
transfers/multiapp_nearest_node_transfer.boundary_elemental ................................... [OVERSIZED] OK
--------------------------------------------------------------------------------------------------------------
Ran 1 tests in 2.4 seconds. Average test time 0.4 seconds, maximum test time 0.4 seconds.
1 passed, 0 skipped, 0 pending, 0 failed
```

2021-04-21 21:42 UTC, aprilnovak commented
Huh, but I see that trying 15 does fail...

2021-04-21 21:45 UTC, fdkong commented
> What's weird is that it works for 4, 8, 9, and 20 processes (just random values I tried), but not for others...

Yes, it only fail with 15 cores in civet so far

2021-04-21 21:56 UTC, aprilnovak commented
Hmmm, this may take me some time to debug. I'm out of the office tomorrow (getting second Pfizer) - am I holding you guys up with this?

2021-04-21 22:24 UTC, aprilnovak commented
What is the difference between

`to_mesh.active_local_element_ptr_range()`

and

`as_range(to_mesh.local_elements_begin(), to_mesh.local_elements_end())`

I did make one change with where this function was used just for convenience purposes.

2021-04-21 22:42 UTC, roystgnr commented
On a mesh that's been refined (including uniformly, not just adaptively), the `active_` ranges only loop over the refined elements, while the ranges and iterators without `active_` loop over their overlapping coarser parents (and higher ancestors if applicable) too.

2021-04-21 22:50 UTC, aprilnovak commented
First - why would this transfer ever _not_ use the `active_` ranges? 

Second, there's no uniform or adaptive refinement in this test, so that strikes this function difference out of potential explanations.

If this is messing with you guys getting `next` integrating, feel free to revert this PR in the meantime.

2021-04-21 23:17 UTC, fdkong commented
> If this is messing with you guys getting next integrating, feel free to revert this PR in the meantime.

It would be fine if we could get something in within a couple of days

2021-04-26 13:59 UTC, loganharbour commented
Any word on this, or do we need to revert in the interim?

2021-04-26 14:04 UTC, aprilnovak commented
Sorry for the delay, I was out of the office the end of last week. I'm going to try to figure out what's going on this morning - if I don't figure it out by lunchtime then I think revert it - I'm 100% puzzled on this.

I've encountered bugs where the results are different for _every_ change in number of procs, but for this test to only fail with 15 is really weird...

2021-04-26 14:05 UTC, loganharbour commented
Sounds good. I'll put a revert up so that we pass tests and can get it in if needed mid day.

And don't be too troubled - non-deterministic parallel behavior is unfortunately too easy to find 😆

2021-04-26 14:45 UTC, aprilnovak commented
Yeah I think revert this for now :/

I made the test simpler, and it doesn't seem to work at all in parallel. But I made so little changes, and basically just followed the pattern for target nodes for Lagrange-type variables, nothing is popping out as a culprit...

Basically, the transferred field is wrong if the nearest node for an element on (rank 0, master app) should map to a point on (rank 1, sub app). I think my previous test was just lucky and didn't encounter this situation for some values of nprocs.

If this works for a `target_boundary` for nodal variables:

```
     ConstBndNodeRange & bnd_nodes = *(_to_meshes[to_problem_id])->getBoundaryNodeRange();
     for (const auto & bnode : bnd_nodes)
       if (bnode->_bnd_id == target_bnd_id && bnode->_node->processor_id() == processor_id())
         target_local_nodes.push_back(bnode->_node);
```

Then is there something glaringly wrong with doing this for elemental variables?

```
     ConstBndElemRange & bnd_elems = *(_to_meshes[to_problem_id])->getBoundaryElementRange();
     for (const auto & belem : bnd_elems)
       if (belem->_bnd_id == target_bnd_id && belem->_elem->processor_id() == processor_id())
         target_local_elems.push_back(belem->_elem);
```