Promise is a Promise
idaholab/moose pull request #17342
Opened 2021-03-17 03:21 UTC by tophmatthews

Change moosebuild.inl.gov to moosebuild.hpc.inl.gov
Ref #15914

2021-03-17 03:21 UTC, tophmatthews commented
ping @loganharbour

2021-03-17 04:56 UTC, moosebuild commented
Job [Documentation](https://civet.inl.gov/job/706172/) on 00e5490 wanted to post the following:

View the site [here](https://mooseframework.inl.gov/docs/PRs/17342/site)

This comment will be updated on new commits.

2021-03-17 15:27 UTC, loganharbour requested changes

2021-03-17 15:27 UTC, loganharbour commented on modules/doc/content/help/inl/hpc_remote.md
> +Host sawtooth1 sawtooth2 falcon1 falcon2 lemhi1 lemhi2 rod moosebuild.hpc.inl.gov hpcgitlab.hpc.inl.gov hpcsc.inl.gov
```suggestion
Host sawtooth1 sawtooth2 falcon1 falcon2 lemhi1 lemhi2 rod moosebuild.hpc.inl.gov hpcgitlab.hpc.inl.gov hpcsc.hpc.inl.gov
```

2021-03-17 15:27 UTC, loganharbour commented on modules/doc/content/help/inl/hpc_remote_different_user.md
> +Host sawtooth1 sawtooth2 falcon1 falcon2 lemhi1 lemhi2 rod moosebuild.hpc.inl.gov hpcgitlab.hpc.inl.gov hpcsc.inl.gov
```suggestion
Host sawtooth1 sawtooth2 falcon1 falcon2 lemhi1 lemhi2 rod moosebuild.hpc.inl.gov hpcgitlab.hpc.inl.gov hpcsc.hpc.inl.gov
```

2021-03-18 14:58 UTC, loganharbour approved these changes

2021-03-18 14:58 UTC, merged