Prevent strong chance of failed physical point inversion
idaholab/moose pull request #17355
Opened 2021-03-17 19:40 UTC by lindsayad

Right now when someone calls `FEProblemBase::reinitElemPhys` with a
vector of physical points, we will attempt to invert those physical
points into the reference element space for both undisplaced and
displaced meshes if the latter exists. It is not difficult to imagine
that for a given set of physical points you may easily fall off the
displaced mesh for large enough displacements/deformations. Let's see if
this makes anything fail

2021-03-17 20:53 UTC, tophmatthews commented
Need to comment out `suppress_displaced_init` in the call

2021-03-18 16:54 UTC, lindsayad commented
If this `reinitElemPhys` patch passes all tests maybe we can wait to do `reinitNeighborPhys` in a later PR. Does that sound good @tophmatthews ?

2021-03-18 17:18 UTC, loganharbour commented on framework/src/problems/FEProblemBase.C
> -                              bool suppress_displaced_init)
This isn't used in the DisplacedProblem method either - can we remove it? Or are there other applications that still pass something in here?

2021-03-18 18:33 UTC, moosebuild commented
Job [Documentation](https://civet.inl.gov/job/707789/) on 620fec6 wanted to post the following:

View the site [here](https://mooseframework.inl.gov/docs/PRs/17355/site)

This comment will be updated on new commits.

2021-03-23 18:05 UTC, tophmatthews commented
Whats up with this?

2021-03-23 20:09 UTC, lindsayad commented
Divided human resource :smile:

2021-03-24 19:22 UTC, lindsayad commented
Trying to get it through though! Made some progress...

2021-03-24 21:49 UTC, lindsayad commented
This is a nightmare. A total nightmare. The `Constraint` system and its associated logic in `NonlinearSystemBase` never ceases to horrify me. It's the single biggest time-suck trying to sort through these problems. Never-ending streams of coding without encapsulating. Always going through `_fe_problem`.... Aaaaaaaaaaaaaaaaaaaarrrrrrrrrrrrrrrrrrrgggggggggggggggghhhhhhhhhhhhhhhhh

2021-03-25 16:27 UTC, lindsayad commented
Oh it's looking like a great success!

2021-03-25 17:06 UTC, lindsayad commented
@tophmatthews have you tried this on your problematic case?

2021-03-25 17:06 UTC, lindsayad commented
If it works, can you review/approve this?

2021-03-25 17:07 UTC, tophmatthews commented
> If it works, can you review/approve this?

I've been staying away due to all the red in civet, but it looks good now, let me test it.

2021-03-25 22:17 UTC, lindsayad commented
@loganharbour unless @tophmatthews comes back with bad news, I think this is ready to review/go

2021-03-25 22:32 UTC, tophmatthews commented
Ugg...I'm trying to reproduce...taking longer than I thought...

2021-03-26 17:10 UTC, loganharbour requested changes
All code style requests, I think.

Removing the extra calls from the reinit methods in FEProblemBase makes this read SO much better

2021-03-26 17:10 UTC, loganharbour commented on framework/src/problems/DisplacedProblem.C
> +              "Are you calling this method with a undisplaced mesh element?");
Beautiful assertions 🙌🏼 

FYI in the future for even less code, we have the `MooseMesh::queryElemPtr()` API

2021-03-26 17:10 UTC, loganharbour commented on framework/src/problems/FEProblemBase.C
> +  clearAllDofIndices();
I think the reasoning is clear, but I think it's still a good idea to put a comment here as to why you ended up needing to do this

2021-03-26 17:10 UTC, loganharbour commented on framework/src/systems/NonlinearSystemBase.C
> +              "displaced problem");
```suggestion
  if (displaced)
    mooseAssert(_fe_problem.getDisplacedProblem().get(),
               "If we're calling this method with displaced = true, then we better well have a "
               "displaced problem");
```

With the assertion opt being:

```
if (displaced)
  (void)0
```

this is fine and will be removed by the compiler. I used to do this, but the ternary assertion with a true just looks like hot trash IMO

2021-03-26 17:10 UTC, loganharbour commented on framework/src/systems/NonlinearSystemBase.C
> +              "displaced problem");
Same here

2021-03-26 17:10 UTC, loganharbour commented on framework/src/systems/NonlinearSystemBase.C
> +              "displaced problem");
And here

2021-03-26 17:10 UTC, loganharbour commented on framework/src/systems/SystemBase.C
> +    _vars[tid].clearAllDofIndices();
```suggestion
  for (auto & var_warehouse : _vars)
    var_warehouse.clearAllDofIndices();
```

Why not?

2021-03-27 14:38 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/712904/) on 849054e wanted to post the following:

Your code requires style changes.  

A patch was auto generated and copied [here](https://mooseframework.inl.gov/docs/PRs/17355/style.patch)  
You can directly apply the patch by running, in the top level of your repository:

`curl -s https://mooseframework.inl.gov/docs/PRs/17355/style.patch | git apply -v`  

Alternatively, with your repository up to date and in the top level of your repository:

`git clang-format 4f46dad974776ed8ad65a193e985d076a81e5495`

2021-03-29 13:12 UTC, loganharbour approved these changes

2021-03-29 16:03 UTC, lindsayad commented
@tophmatthews how you doing over there?

2021-03-29 16:34 UTC, tophmatthews commented
I'm trying...I have so many balls in the air, I can't find a reproducible case that fails obviously to really test this. I'll keep looking, but if tests pass then, don't wait for me...

2021-03-29 16:57 UTC, merged

2021-03-30 13:13 UTC, tophmatthews commented
Wow, it took forever, but yes, can confirm 👍 

You da 💣  @lindsayad