Fix suppressing of controllable parameters
idaholab/moose pull request #17404
Opened 2021-03-22 21:27 UTC by andrsd

Unmark parameter as controllable when suppressing it.

Closes #17403

2021-03-22 22:53 UTC, moosebuild commented
Job [Documentation](https://civet.inl.gov/job/710034/) on af53f6f wanted to post the following:

View the site [here](https://mooseframework.inl.gov/docs/PRs/17404/site)

This comment will be updated on new commits.

2021-03-23 15:09 UTC, loganharbour commented
Unit test? :-)

2021-03-23 15:09 UTC, loganharbour requested changes
Unit test? :-)

2021-03-23 16:44 UTC, andrsd commented
I was thinking about a different one, but I thought it would not work. Now, I am thinking it would. 
But, you are right - I might be able to do just a unit test. Good idea. Thanks!

2021-03-23 22:38 UTC, loganharbour approved these changes

2021-03-23 22:59 UTC, merged