add --copy-tests flag for copying installed tests to curr dir.
idaholab/moose pull request #17428
Opened 2021-03-24 20:57 UTC by rwcarlsen

This is necessary for people with only level-1 access to various moose
apps/codes - the tests will be installed into a location where they
don't have write access - so the test harness can't run them there.
Running this flag copies the installed tests out to an appname_tests dir
that users can cd into and then run them.

ref #16411

2021-03-24 22:24 UTC, moosebuild commented
Job [Documentation](https://civet.inl.gov/job/712166/) on a93a618 wanted to post the following:

View the site [here](https://mooseframework.inl.gov/docs/PRs/17428/site)

This comment will be updated on new commits.

2021-03-29 15:59 UTC, moosebuild commented
Job [Make Install](https://civet.inl.gov/job/713006/) on a93a618 : invalidated by @rwcarlsen

2021-03-29 16:30 UTC, moosebuild commented
Job [Moose Install Target Tests](https://civet.inl.gov/job/713005/) on a93a618 : invalidated by @rwcarlsen

2021-03-29 16:30 UTC, moosebuild commented
Job [Make Install](https://civet.inl.gov/job/713006/) on a93a618 : canceled by @rwcarlsen

2021-03-30 17:17 UTC, moosebuild commented
Job [Moose Install Target Tests](https://civet.inl.gov/job/713005/) on a93a618 : invalidated by @rwcarlsen

2021-03-31 14:53 UTC, loganharbour requested changes
All minor. Looks good to me

2021-03-31 14:54 UTC, loganharbour commented
What will happen if someone runs `--copy-tests` on a binary that hasn't been installed?

2021-03-31 15:02 UTC, rwcarlsen commented on framework/src/base/MooseApp.C
> +    int ret = system(cmd.c_str());
windows.

2021-03-31 15:02 UTC, rwcarlsen commented on framework/src/base/MooseApp.C
> +    int ret = system(cmd.c_str());
Or anything without `cp`

2021-03-31 15:25 UTC, rwcarlsen commented
Good catch - I just pushed up some checks to handle that case more gracefully.

2021-03-31 21:04 UTC, moosebuild commented
Job [Moose Install Target Tests](https://civet.inl.gov/job/714881/) on ceae4bd : invalidated by @rwcarlsen

2021-03-31 21:15 UTC, loganharbour commented
> Good catch - I just pushed up some checks to handle that case more gracefully.

Shouldn't the error be a little more friendly?

2021-03-31 21:19 UTC, rwcarlsen commented
What would you suggest for the message?  There could be multiple reasons that error is hit - I don't want to write a novel about all of them.  Maybe permissions just got messed up somehow, or maybe there isn't an installed binary, or maybe something else went wrong, etc.

2021-04-01 04:54 UTC, loganharbour commented
> What would you suggest for the message? There could be multiple reasons that error is hit - I don't want to write a novel about all of them. Maybe permissions just got messed up somehow, or maybe there isn't an installed binary, or maybe something else went wrong, etc.

Fair enough, I think this is valid then.

2021-04-01 04:55 UTC, loganharbour approved these changes

2021-04-01 14:32 UTC, merged