Allow for multiple timestep limiting functions
idaholab/moose pull request #17653
Opened 2021-04-20 18:24 UTC by dschwen

Closes #17642

2021-04-20 19:53 UTC, moosebuild commented
Job [Documentation](https://civet.inl.gov/job/726804/) on a101ec0 wanted to post the following:

View the site [here](https://mooseframework.inl.gov/docs/PRs/17653/site)

This comment will be updated on new commits.

2021-04-21 14:32 UTC, bwspenc requested changes
Looks good! Just one minor thing as noted. I'm fine either way on the curly braces, but I'd prefer to leave them as they were.

2021-04-21 14:32 UTC, bwspenc commented on framework/src/timesteppers/IterationAdaptiveDT.C
> -  {
I know that our style guide says to not have curly braces around one-liners, but in cases like this where there's a nested multi-line block, it seems to me like including the curly braces improves readability.

2021-04-21 14:32 UTC, bwspenc commented on test/tests/time_steppers/iteration_adaptive/tests
> +    requirement = "MOOSE shall support the ability to force time steps to hit all nodes in a set of piecewide linear functions."
piecewide->piecewise

2021-04-21 18:03 UTC, dschwen commented
Suddenly an unrelated failure in Sockeye pops up :-/

2021-04-22 21:27 UTC, bwspenc approved these changes

2021-04-22 21:27 UTC, merged

2022-01-31 16:45 UTC, tophmatthews commented
I think somehow in here you cut out the ability to use `PiecewiseConstant` as a timestep limiting function @dschwen ? `PiecewiseLinear` works, `PiecewiseConstants` are accumulated, but not interrogated...

2022-01-31 16:55 UTC, dschwen commented
Hm, I went over my changes, but I don't see anything to that effect. This PR keeps the same `dynamic_cast`s. Did `PiecewiseConstant` ever work?

2022-01-31 16:56 UTC, tophmatthews commented
It may not be your changes...just that you're the last to change. Look at how `_piecewise_timestep_limiting_functions` is used vs `_piecewise_linear_timestep_limiting_functions`

2022-01-31 16:57 UTC, dschwen commented
Maybe #14221 is the culprit @tophmatthews