Enhanced the PD mesh generator for general sidesets
idaholab/moose pull request #17725
Opened 2021-05-02 17:39 UTC by hchen139

closes #17723

2021-05-02 17:39 UTC, hchen139 commented
@bwspenc This PR enhances the sideset reconstruction for PD mesh.

2021-05-17 20:21 UTC, bwspenc commented
Sorry, just noticed this PR.  Looks like the tests aren't running because of this:

```

##########################################################################
ERROR: The following files are executable but shouldn't be:
	modules/peridynamics/test/tests/mesh/2D_4blocks.e
	modules/peridynamics/test/tests/mesh/cylinder_circle.e
##########################################################################

2021-05-17 20:24 UTC, hchen139 commented
> Sorry, just noticed this PR. Looks like the tests aren't running because of this:
> 
> ```
> 
> ##########################################################################
> ERROR: The following files are executable but shouldn't be:
> 	modules/peridynamics/test/tests/mesh/2D_4blocks.e
> 	modules/peridynamics/test/tests/mesh/cylinder_circle.e
> ##########################################################################
> ```

Why the exodus files are treated as executables? These are just mesh files.

2021-05-17 22:14 UTC, bwspenc commented
Exactly -- they shouldn't have executable permission, but for some reason they do. You probably just need to do `chmod -x file.e` on both of the .e files and then commit the updates.

2021-05-18 02:59 UTC, moosebuild commented
Job [Documentation](https://civet.inl.gov/job/742246/) on e696f16 wanted to post the following:

View the site [here](https://mooseframework.inl.gov/docs/PRs/17725/site)

This comment will be updated on new commits.

2021-07-07 21:37 UTC, bwspenc commented
This test is failing in parallel: test:mesh.2D_3D_generate_sidesets_partial_boundary

2021-07-07 22:43 UTC, bwspenc requested changes

2021-07-07 22:43 UTC, bwspenc commented on modules/peridynamics/src/meshgenerators/MeshGeneratorPD.C
> +      "List of FE block pairs between which inter-block bonds will NOT be created after converted "
after being converted

2021-07-07 22:43 UTC, bwspenc commented on modules/peridynamics/src/meshgenerators/MeshGeneratorPD.C
> +      _pd_bonding_blk_pairs.insert(std::make_pair(id_pairs[i][0] + 1000, id_pairs[i][1] + 1000));
I'd suggest creating a variable called `block_offset` or something like that and setting that to 1000, and then adding `block_offset` here. That would make it more clear what that 1000 means.

2021-07-07 22:43 UTC, bwspenc commented on modules/peridynamics/src/meshgenerators/MeshGeneratorPD.C
> +          std::make_pair(id_pairs[i][0] + 1000, id_pairs[i][1] + 1000));
Same deal with the variable for the offset here.

2021-07-07 22:43 UTC, bwspenc commented on modules/peridynamics/src/meshgenerators/MeshGeneratorPD.C
> +        mooseError("Block ID ", blkit, " in the 'blocks_to_pd' doesnot exist in the FE mesh!");
does not

2021-07-07 22:43 UTC, bwspenc commented on modules/peridynamics/src/meshgenerators/MeshGeneratorPD.C
> +        mooseError("Block ID ", blkit, " in the 'blocks_as_fe' doesnot exist in the FE mesh!");
does not

2021-07-07 22:43 UTC, bwspenc commented on modules/peridynamics/src/meshgenerators/MeshGeneratorPD.C
> +                   blk_pair.first - 1000,
Use the offset variable in all these places where you're using 1000 here too.

2021-07-08 19:29 UTC, hchen139 commented
> This test is failing in parallel: test:mesh.2D_3D_generate_sidesets_partial_boundary

I don't know why this test produced "malloc(): unsorted double linked list corrupted" error during parallel execution. The mesh contains both 2D and 3D geometries. Could this be the reason? For now, my plan is to separate this test into two tests, one for 2D and one for 3D.

2021-07-30 23:03 UTC, bwspenc requested changes
Sorry I've let this sit so long. Looks fine in general. Please address the one specific comment I made. Also, check the following:
- Make sure that the documentation for MeshGeneratorPD correctly reflects these updated capabilities.
- I hate to say this because this is a pain, but you've added a lot of error messages, and those should be tested, at least if it's reasonably possible to replicate the conditions that result in them. Use 'type=RunException' and 'expect_err' to set up the tests. Because there are so many of these, they should be grouped together using the 'detail' parameter for individual tests. Look at `moose/test/tests/solution_aux/tests` and search for `detail` for an example.

2021-08-11 16:06 UTC, bwspenc commented
Looks good. I fixed a couple of minor issues in commits that got added to this. If it passes, I'll merge this.

2021-08-11 23:30 UTC, moosebuild commented
Job [Mac Test](https://civet.inl.gov/job/794702/) on b96d1b0 : invalidated by @bwspenc

Failure is unrelated to this pr

2021-08-12 19:16 UTC, bwspenc commented on modules/peridynamics/include/meshgenerators/MeshGeneratorPD.h
> +  unsigned int _pd_blk_offset_number = 1000;
I'm fine leaving this as-is for now, but this would be a good follow-on thing to do.

2021-08-12 19:16 UTC, bwspenc approved these changes

2021-08-12 19:17 UTC, merged