Fix TypeError: 'map' object is not subscriptable
idaholab/moose pull request #17971
Opened 2021-05-31 17:36 UTC by rksin8

(refs #17558)

2021-05-31 19:33 UTC, moosebuild commented
Job [Documentation](https://civet.inl.gov/job/750839/) on fa4540f wanted to post the following:

View the site [here](https://mooseframework.inl.gov/docs/PRs/17971/site)

This comment will be updated on new commits.

2021-06-03 01:26 UTC, GiudGiud approved these changes

2021-06-03 01:28 UTC, loganharbour requested changes
Where is this ran? If we could get it tested that would be ideal

2021-06-03 02:33 UTC, GiudGiud commented
Looks like it s a repeat of https://github.com/idaholab/moose/pull/17573 ?

2021-06-25 06:52 UTC, GiudGiud commented
@loganharbour looks like there s zero traction on this. Let s just merge this fix.

2021-06-25 13:58 UTC, loganharbour approved these changes

2021-06-25 13:58 UTC, merged