new Biot coefficient added to PorousFlowPorosity
idaholab/moose pull request #18029
Opened 2021-06-08 09:27 UTC by WilkAndy

Fixes #18028

2021-06-08 11:06 UTC, moosebuild commented
Job [Documentation](https://civet.inl.gov/job/754884/) on ff83ff6 wanted to post the following:

View the site [here](https://mooseframework.inl.gov/docs/PRs/18029/site)

This comment will be updated on new commits.

2021-06-08 22:00 UTC, cpgr requested changes
Looks ok to me. Two suggestions though:

- Add alpha_B' to the nomenclature page
- Add a subheading in porosity.md like 'Evolution of porosity in fractures' or something to make it easier to spot

Feel free to ignore though!

2021-06-08 23:53 UTC, cpgr approved these changes
Thanks Andy

2021-06-09 01:01 UTC, loganharbour approved these changes

2021-06-09 01:13 UTC, merged