More code owners
idaholab/moose pull request #18074
Opened 2021-06-11 20:13 UTC by GiudGiud

See https://github.com/idaholab/moose/pull/18059

2021-06-11 21:48 UTC, moosebuild commented
Job [Documentation](https://civet.inl.gov/job/757903/) on 0dc821c wanted to post the following:

View the site [here](https://mooseframework.inl.gov/docs/PRs/18074/site)

This comment will be updated on new commits.

2021-06-11 21:58 UTC, loganharbour requested changes

2021-06-11 21:58 UTC, loganharbour commented on CODEOWNERS
> +/framework/*/executioners/*Solve* @GiudGiud
Come on man... it's in alphabetical order

2021-06-11 23:38 UTC, loganharbour submitted a review, later dismissed

2021-06-11 23:43 UTC, GiudGiud commented
let s wait a bit to see if @bwspenc @roystgnr @jiangwen84 @joshuahansel or @dschwen want to join in on this

2021-06-15 14:47 UTC, roystgnr commented
The pattern globbing here is limited to filenames, yes?  I'd love something that screams at me any time someone modifies a line matching "DistributedMesh" or possibly even just "distributed", but I don't think there's particular whole-file-matches I'd want to tag myself on.

2021-06-15 14:57 UTC, dschwen commented on CODEOWNERS
> +/modules/navier_stokes @lindsayad @GiudGiud
```suggestion
/modules/navier_stokes @lindsayad @GiudGiud
/modules/phase_field @dschwen
```

2021-06-15 15:01 UTC, dschwen commented on CODEOWNERS
> +/modules/navier_stokes @lindsayad @GiudGiud
Also put me in for 

```
/framework/*/utils/Units* @dschwen
/framework/*/materials/Derivative* @dschwen
/framework/*/materials/Parsed* @dschwen
```

Thanks!`

2021-06-15 19:13 UTC, loganharbour commented
@GiudGiud get rid of that merge commit... come on

2021-06-15 20:21 UTC, loganharbour commented
> The pattern globbing here is limited to filenames, yes?

Correct, unfortunately.

2021-06-15 20:21 UTC, loganharbour approved these changes, later dismissed

2021-06-16 23:50 UTC, GiudGiud commented
I think we re good to merge now?

2021-06-28 19:34 UTC, loganharbour approved these changes

2021-06-28 22:32 UTC, merged