First attempt at a few NCRC gettings started pages
idaholab/moose pull request #18144
Opened 2021-06-22 22:57 UTC by permcody

refs #000

## Reason

## Design

## Impact

2021-06-23 03:12 UTC, moosebuild commented
Job [Documentation](https://civet.inl.gov/job/763432/) on e92c4da wanted to post the following:

View the site [here](https://mooseframework.inl.gov/docs/PRs/18144/site)

This comment will be updated on new commits.

2021-06-24 00:25 UTC, rpodgorney commented
I made major changes to this PR but somehow broke it when I tried to rebase and push......I'll need some help tomorrow morning...

2021-06-24 00:27 UTC, rpodgorney commented
git push --set-upstream origin pullrequest
remote: Permission to idaholab/moose.git denied to rpodgorney.
fatal: unable to access 'https://github.com/idaholab/moose.git/': The requested URL returned error: 403

2021-06-24 05:24 UTC, GiudGiud requested changes
had a quick look

2021-06-24 05:24 UTC, GiudGiud commented on modules/doc/content/ncrc/ncrc_binary.md
> +login nodes (e.g., `ssh sawtooth2). Change directories to the location of the script
```suggestion
login nodes (e.g., `ssh sawtooth2`). Change directory to the location of the script
```

2021-06-24 05:24 UTC, GiudGiud commented on modules/doc/content/ncrc/ncrc_ondemand.md
> +If you are more comforatable using the command line than the on demand interface, you may follow the instructions [here](ncrc/ncrc_binary.md)
```suggestion
If you are more comfortable using the command line than the on demand interface, you may follow the instructions [here](ncrc/ncrc_binary.md)
```

2021-06-24 15:35 UTC, moosebuild commented on large_media
> +Subproject commit 4ef7042ee17cc6beb78c0dcf6a44ee0f7ee02a10
**Caution!** This contains a submodule update

2021-06-24 16:56 UTC, rpodgorney commented
Is this close?

2021-06-24 19:12 UTC, permcody commented
Rob, Did you intend to update the large_media hash? I'm guessing not. I'll help you with this when I get off my _very long call_.

2021-06-24 19:25 UTC, rpodgorney commented
I had added some large media files when I was working on the Falcon doco pages—but in the end the images ended up in the Falcon media folder

We can reject that change


--
Robert K. Podgorney
Chief Computational Scientist
Advanced Scientific Computing Division
Idaho National Laboratory

Office: 208-526-1524<tel:208-526-1524>
Cell: 208-520-9361<tel:208-520-9361>
email: ***@***.******@***.***>
Statement of Confidentiality
The contents of this e-mail message and any attachments are confidential and are intended solely for addressee. The information may also be legally privileged. This transmission is sent in trust, for the sole purpose of delivery to the intended recipient. If you have received this transmission in error, any use, reproduction or dissemination of this transmission is strictly prohibited. If you are not the intended recipient, please immediately notify the sender by reply e-mail or phone and delete this message and its attachments, if any.


From: Cody Permann ***@***.***>
Date: Thursday, June 24, 2021 at 1:12 PM
To: idaholab/moose ***@***.***>
Cc: Robert K. Podgorney ***@***.***>, Comment ***@***.***>
Subject: [EXTERNAL] Re: [idaholab/moose] First attempt at a few NCRC gettings started pages (#18144)

Rob, Did you intend to update the large_media hash? I'm guessing not. I'll help you with this when I get off my very long call.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fidaholab%2Fmoose%2Fpull%2F18144%23issuecomment-867887281&data=04%7C01%7Crobert.podgorney%40inl.gov%7Cfdd65c8e416c459ccd9b08d9374404f7%7C4cf464b7869a42368da2a98566485554%7C0%7C0%7C637601587544677244%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=iQNIBKzLD9Xc9XVSPEXFo5O8f0iaIkEOpamCeiH2sus%3D&reserved=0>, or unsubscribe<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FACWGDTYRISVTDRFYSOFIH63TUN7SBANCNFSM47ETUEVQ&data=04%7C01%7Crobert.podgorney%40inl.gov%7Cfdd65c8e416c459ccd9b08d9374404f7%7C4cf464b7869a42368da2a98566485554%7C0%7C0%7C637601587544687210%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=%2BKoLtxIcFPxbJd8hIP2jxDwMkURuaseALZZuRqfm4q4%3D&reserved=0>.

2021-06-24 20:12 UTC, moosebuild commented on large_media
> +Subproject commit 4ef7042ee17cc6beb78c0dcf6a44ee0f7ee02a10
**Caution!** This contains a submodule update

2021-06-24 20:16 UTC, permcody commented on modules/doc/content/ncrc/ncrc_binary.md
> +#PBS -P moose
Good question: I'll do some checking but will leave this as-is for now.

2021-06-24 22:37 UTC, permcody commented
@GiudGiud - Can we get another review and hopefully an approval? We kind of would like this site in place even if it's not perfect since the new NCRC site references it.

2021-06-24 22:48 UTC, GiudGiud submitted a review, later dismissed

2021-06-24 22:48 UTC, GiudGiud commented on modules/doc/content/ncrc/gen_ondemand.md
> +If you are more comforatable using the command line than the on demand interface, you may follow the instructions [here](ncrc/ncrc_binary.md)
```suggestion
If you are more comfortable using the command line than the on demand interface, you may follow the instructions [here](ncrc/ncrc_binary.md)
```

2021-06-25 04:22 UTC, rpodgorney commented
can someone merge this in the AM?

2021-06-25 04:28 UTC, GiudGiud commented
I ll merge it tonight after the test suite reruns for that typo

2021-06-25 04:50 UTC, GiudGiud approved these changes, later dismissed

2021-06-25 05:08 UTC, GiudGiud commented
Actually @permcody can you do it tomorrow? Not sure what the final call was on this large media submodule update

2021-06-25 14:07 UTC, loganharbour commented
This changes the repo by almost 3 MB - I'm going to move the screenshots into large_media.

2021-06-25 14:14 UTC, loganharbour commented
Looks like you didn't even use two images; we can remove them from large_media after.

2021-06-25 14:15 UTC, moosebuild commented on large_media
> +Subproject commit 901c9f1ba4e258fa7047a02812d3038f0dbc8e9e
**Caution!** This contains a submodule update

2021-06-25 14:15 UTC, rpodgorney commented
Those images will be needed later—as the doco expands/becomes more complete


--
Robert K. Podgorney, PhD
Chief Computational Scientist
Advanced Scientific Computing Division
Idaho National Laboratory

Office: 208-526-1524<tel:208-526-1524>
Cell: 208-520-9361<tel:208-520-9361>
email: ***@***.******@***.***>
Statement of Confidentiality
The contents of this e-mail message and any attachments are confidential and are intended solely for addressee. The information may also be legally privileged. This transmission is sent in trust, for the sole purpose of delivery to the intended recipient. If you have received this transmission in error, any use, reproduction or dissemination of this transmission is strictly prohibited. If you are not the intended recipient, please immediately notify the sender by reply e-mail or phone and delete this message and its attachments, if any.


From: Logan Harbour ***@***.***>
Date: Friday, June 25, 2021 at 8:14 AM
To: idaholab/moose ***@***.***>
Cc: Robert K. Podgorney ***@***.***>, Comment ***@***.***>
Subject: [EXTERNAL] Re: [idaholab/moose] First attempt at a few NCRC gettings started pages (#18144)

Looks like you didn't even use two images; we can remove them from large_media after.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fidaholab%2Fmoose%2Fpull%2F18144%23issuecomment-868531366&data=04%7C01%7Crobert.podgorney%40inl.gov%7Cc34d974f4b5446c004dd08d937e39287%7C4cf464b7869a42368da2a98566485554%7C0%7C0%7C637602272829859248%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=5KbKBWTvRQRaq7BKYN4Dbb3JH%2Fl2QIOXyML9FeU9b9M%3D&reserved=0>, or unsubscribe<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FACWGDT7L4RE2OLGDXXQEOSDTUSFNBANCNFSM47ETUEVQ&data=04%7C01%7Crobert.podgorney%40inl.gov%7Cc34d974f4b5446c004dd08d937e39287%7C4cf464b7869a42368da2a98566485554%7C0%7C0%7C637602272829869204%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=0GmBWMtQ2y%2FiyWGMS%2BHR016qSfaj1HfYBZjfsH4jXkk%3D&reserved=0>.

2021-06-25 14:20 UTC, moosebuild commented on large_media
> +Subproject commit 901c9f1ba4e258fa7047a02812d3038f0dbc8e9e
**Caution!** This contains a submodule update

2021-06-25 16:14 UTC, GiudGiud approved these changes

2021-06-25 16:59 UTC, merged