A system to build multiple MooseDocs configurations simultaneously
idaholab/moose pull request #18211
Opened 2021-06-30 06:48 UTC by crswong888

@aeslaughter, please take a look at this when you get the chance. To demonstrate the results you can run something like the following, which builds the test site, workshop, and a new test site all at the same time with cross-linking capabilities:

```
cd ~/projects/moose/python/MooseDocs/test
./moosedocs.py build --serve --subconfigs ../../../tutorials/darcy_thermo_mech/doc/config.yml subconfig/config.yml
```

I still need to set up the live server routines and a comprehensive testing system. Please make any requests for changes that you have at this point.

(closes #18137) (refs #18136)

2021-06-30 07:55 UTC, moosebuild commented
Job [Documentation](https://civet.inl.gov/job/768905/) on f8a7e9e wanted to post the following:

View the site [here](https://mooseframework.inl.gov/docs/PRs/18211/site)

This comment will be updated on new commits.

2021-06-30 15:42 UTC, aeslaughter requested changes
Made some comments on the main changes, this is a great start. Thanks for the work on this, it will be really great when it is done. It will be another strong feature that will set MooseDocs apart from other similar tools.

2021-07-13 21:17 UTC, crswong888 commented on python/MooseDocs/commands/build.py
> +                self._translator.addContent(page) # shoudldn't this be addPage()???
I'll double-check this once I get into modifying the live server

2021-07-13 21:18 UTC, crswong888 commented on python/MooseDocs/base/executioners.py
> +            page._Page__unique_id = len(self._page_objects)
we shall handle this one at a later time

2021-07-14 20:56 UTC, milljm commented
@crswong888  I am looking into the conda issues. It has to do with the recent use of `mamba`

2021-07-14 20:57 UTC, crswong888 commented
@milljm No worries! Do you mind if I do another force-push and restart these tests though?

2021-07-14 23:21 UTC, crswong888 commented
@aeslaughter, this is ready for your review. The top 4 commits are new.

Basically, there's no such thing as a "primary" translator anymore, each are treated equally and the result should be the same no matter what order they are loaded in. Each configuration should specify unique content, otherwise, `load_configs()` will raise an exception, and every translator shares the same exact pool of content. Pretty much everything new I did is in support of this idea that no translator should be special. Additonally, I addressed your comments in the best way that I could.

2021-07-30 02:51 UTC, crswong888 commented
The live server is now operational.

Additionally, executioners store translator data in dictionaries now and do not modify the Page.uid attribute. Pages may be added during any part of the build procedure and are no longer blocked, including during a live serve. Although, pages added during a live serve of multiple configurations are ignored since it is not possible to determine which translator should be responsible.

It seems that all executioners are now stable and so I have enabled their tests. Whether or not this is because of changes made here is not clear. I am also not sure how to reproduce the steps described in #15887.

2021-08-03 19:23 UTC, aeslaughter approved these changes

2021-08-03 19:46 UTC, merged

2021-08-04 14:47 UTC, milljm commented
@crswong888 sorry, it seems I ignored one of your comments! Wasn't intentional.

I am here because this is all very interesting. I am thinking about the ways we can take advantage of this in Civet...

2021-08-04 16:27 UTC, crswong888 commented
@milljm No worries. Let me know what your ideas are and I can help.

The possibilities for our web design have grown by a lot with this new system. A single page could have its own unique configuration entirely independent from others. This is by no means limited to just slides. For example, take a look at `python/MooseDocs/test/subsite_config.yml`