Wall functions bc
idaholab/moose pull request #18273
Opened 2021-07-06 22:27 UTC by freiler

<!--
"refs #18272 "

2021-07-06 22:28 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/772012/) on 6deb8ae wanted to post the following:

Your code requires style changes.  

A patch was auto generated and copied [here](https://mooseframework.inl.gov/docs/PRs/18273/style.patch)  
You can directly apply the patch by running, in the top level of your repository:

`curl -s https://mooseframework.inl.gov/docs/PRs/18273/style.patch | git apply -v`  

Alternatively, with your repository up to date and in the top level of your repository:

`git clang-format f59e5424802e6b294e602ea4597ce6e78bfa08ed`

2021-07-07 14:04 UTC, GiudGiud requested changes
Congrats on your first contribution to MOOSE!
You need to add a tests file so that your test is run. You ll find it in the folders near where you placed your test. Look for an Exodiff example

2021-07-07 14:04 UTC, GiudGiud commented on modules/navier_stokes/src/fvbcs/INSFVWallFunctionBC.C
> +  //direction of the tangential velocity component (parallel_dir)
```suggestion
  // direction of the tangential velocity component (parallel_dir)
```

2021-07-07 15:47 UTC, GiudGiud commented on modules/navier_stokes/src/auxkernels/WallFunctionWallShearStressAux.C
> +find_u_star3(Real mu, Real rho, ADReal u, Real dist)
you ll need to convert that to Camel case btw
findUStar3

2021-07-07 17:53 UTC, GiudGiud commented on modules/navier_stokes/src/fvbcs/INSFVWallFunctionBC.C
> +  ADReal u_star = Find_U_Star(_mu[_qp].value(), _rho, parallel_speed, dist);
```suggestion
  ADReal u_star = findUStar(_mu[_qp].value(), _rho, parallel_speed, dist);
```

2021-07-07 18:17 UTC, moosebuild commented
Job [Documentation](https://civet.inl.gov/job/772771/) on 8804f09 wanted to post the following:

View the site [here](https://mooseframework.inl.gov/docs/PRs/18273/site)

This comment will be updated on new commits.

2021-07-07 22:02 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/773151/) on 010a5a8 wanted to post the following:

Your code requires style changes.  

A patch was auto generated and copied [here](https://mooseframework.inl.gov/docs/PRs/18273/style.patch)  
You can directly apply the patch by running, in the top level of your repository:

`curl -s https://mooseframework.inl.gov/docs/PRs/18273/style.patch | git apply -v`  

Alternatively, with your repository up to date and in the top level of your repository:

`git clang-format f59e5424802e6b294e602ea4597ce6e78bfa08ed`

2021-07-08 15:14 UTC, freiler commented on modules/navier_stokes/src/auxkernels/WallFunctionWallShearStressAux.C
> +{
like INSCourant.C?

2021-07-08 15:23 UTC, freiler commented on modules/navier_stokes/src/auxkernels/WallFunctionWallShearStressAux.C
> +  if (!std::isfinite(parallel_speed.value()))
pending

2021-07-08 15:23 UTC, freiler commented on modules/navier_stokes/src/auxkernels/WallFunctionWallShearStressAux.C
> +  for (unsigned int i_side = 0; i_side < elem.n_sides(); ++i_side)
pending

2021-07-15 19:24 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/778228/) on b1c698c wanted to post the following:

Your code requires style changes.  

A patch was auto generated and copied [here](https://mooseframework.inl.gov/docs/PRs/18273/style.patch)  
You can directly apply the patch by running, in the top level of your repository:

`curl -s https://mooseframework.inl.gov/docs/PRs/18273/style.patch | git apply -v`  

Alternatively, with your repository up to date and in the top level of your repository:

`git clang-format a969d327c03b526dd25c1af5b93f3b3aeabe2814`

2021-07-18 21:53 UTC, GiudGiud requested changes

2021-07-18 21:53 UTC, GiudGiud commented on modules/navier_stokes/src/auxkernels/WallFunctionWallShearStressAux.C
> +findUStar3(Real mu, Real rho, ADReal u, Real dist)
these should all be const arguments

move this routine to an include/INSFVMethods file so it can be shared between all WallFunction stuff

2021-07-18 21:53 UTC, GiudGiud commented on modules/navier_stokes/src/auxkernels/WallFunctionWallShearStressAux.C
> +  for (int i = 0; i < MAX_ITERS; ++i)
Add a comment about what you're doing in the loop like "Newton solve for the intersection..."

2021-07-18 21:53 UTC, GiudGiud commented on modules/navier_stokes/src/auxkernels/WallFunctionWallShearStressAux.C
> +{
in the same style, but not the same code\
Thinking something like
```
if (_mesh.dimension() >= 2 && !isParamValid('v')
  mooseError(
if (_mesh.dimension() < 2 && isParamValid('v'))
  paramError(

2021-07-18 21:53 UTC, GiudGiud commented on modules/navier_stokes/src/fvbcs/INSFVWallFunctionBC.C
> +  // walls");
```suggestion
```

2021-07-18 21:53 UTC, GiudGiud commented on modules/navier_stokes/src/fvbcs/INSFVWallFunctionBC.C
> +  }
```suggestion
  if (_axis_index == 0)
    return tau * parallel_dir(0);
  else if (_axis_index == 1)
    return tau * parallel_dir(1);
  else
    return tau * parallel_dir(2);
```

2021-07-20 18:01 UTC, lindsayad commented
Please mention me if you want any additional review

2021-07-21 23:15 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/781701/) on 35428e6 wanted to post the following:

Your code requires style changes.  

A patch was auto generated and copied [here](https://mooseframework.inl.gov/docs/PRs/18273/style.patch)  
You can directly apply the patch by running, in the top level of your repository:

`curl -s https://mooseframework.inl.gov/docs/PRs/18273/style.patch | git apply -v`  

Alternatively, with your repository up to date and in the top level of your repository:

`git clang-format 3fe62bc3d128d5b7b656e7a7f9fe3acd69acd477`

2021-07-22 13:59 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/782002/) on 1f7e95f wanted to post the following:

Your code requires style changes.  

A patch was auto generated and copied [here](https://mooseframework.inl.gov/docs/PRs/18273/style.patch)  
You can directly apply the patch by running, in the top level of your repository:

`curl -s https://mooseframework.inl.gov/docs/PRs/18273/style.patch | git apply -v`  

Alternatively, with your repository up to date and in the top level of your repository:

`git clang-format 3fe62bc3d128d5b7b656e7a7f9fe3acd69acd477`

2021-08-02 15:52 UTC, GiudGiud commented on modules/navier_stokes/doc/content/modules/navier_stokes/rans_theory.md
> +
what are the figures you used in the poster exactly? Do you think it could fit here

2021-08-02 15:53 UTC, GiudGiud commented
@freiler the new test now diffs. I m thinking it's the symmetry pressure BC.
You will have to re-gold the file.
If possible, squash the commits so that there is only one version of the exodus file in the commit history. 

Let's talk about how one would use this to re-do the validation at the meeting. I think we would want to leave some 4 bullet point instructions on the input file

2021-08-07 17:00 UTC, GiudGiud approved these changes

2021-08-07 17:01 UTC, merged