Add generic vector function material
idaholab/moose pull request #18373
Opened 2021-07-19 03:59 UTC by GiudGiud

Closes #18372

2021-07-19 04:00 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/779157/) on 7b796b4 wanted to post the following:

Your code requires style changes.  

A patch was auto generated and copied [here](https://mooseframework.inl.gov/docs/PRs/18373/style.patch)  
You can directly apply the patch by running, in the top level of your repository:

`curl -s https://mooseframework.inl.gov/docs/PRs/18373/style.patch | git apply -v`  

Alternatively, with your repository up to date and in the top level of your repository:

`git clang-format a969d327c03b526dd25c1af5b93f3b3aeabe2814`

2021-07-19 05:39 UTC, moosebuild commented
Job [Documentation](https://civet.inl.gov/job/779183/) on f4fa0de wanted to post the following:

View the site [here](https://mooseframework.inl.gov/docs/PRs/18373/site)

This comment will be updated on new commits.

2021-07-26 00:16 UTC, GiudGiud commented
Well this is an interesting failure. Looks like there's something wrong with threads here.

2021-08-05 00:26 UTC, GiudGiud commented
ah the tensor maths is wrong is what is happening.

2021-11-16 23:58 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/892408/) on ba888b4 wanted to post the following:

Your code requires style changes.  

A patch was auto generated and copied [here](https://mooseframework.inl.gov/docs/PRs/18373/style.patch)  
You can directly apply the patch by running, in the top level of your repository:

`curl -s https://mooseframework.inl.gov/docs/PRs/18373/style.patch | git apply -v`  

Alternatively, with your repository up to date and in the top level of your repository:

`git clang-format 44d8c685e45727d1bec41d4a56196a157d1a5e58`

2021-11-17 02:39 UTC, moosebuild commented
Job [Coverage](https://civet.inl.gov/job/892467/) on 2124ab1 wanted to post the following:


## Framework coverage

<table>
  <thead>
    <tr>
      <th></th>
      <th>44d8c6</th>
      <th colspan=4>#18373 2124ab</th>
    </tr>
    <tr>
      <th></th>
      <th>Total</th>
      <th>Total</th>
      <th>+/-</th>
      <th>New</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><b>Rate</b></td>
      <td>81.95%</td>
      <td>81.96%</td>
      <td>+0.00%</td>
      <td>86.84%</td>
    </tr>
    <tr>
      <td><b>Hits</b></td>
      <td>72274</td>
      <td>72307</td>
      <td>+33</td>
      <td>33</td>
    </tr>
    <tr>
      <td><b>Misses</b></td>
      <td>15915</td>
      <td>15920</td>
      <td>+5</td>
      <td>5</td>
    </tr>
  </tbody>
</table>

[Diff coverage report](https://mooseframework.inl.gov/docs/PRs/18373/coverage_diff/framework.html)

[Full coverage report](https://mooseframework.inl.gov/docs/PRs/18373/coverage/framework)


## Modules coverage

Coverage did not change

## Full coverage reports

<details>
<summary>Reports</summary>

- [`framework`](https://mooseframework.inl.gov/docs/PRs/18373/coverage/framework)
- [`chemical_reactions`](https://mooseframework.inl.gov/docs/PRs/18373/coverage/chemical_reactions)
- [`combined`](https://mooseframework.inl.gov/docs/PRs/18373/coverage/combined)
- [`contact`](https://mooseframework.inl.gov/docs/PRs/18373/coverage/contact)
- [`external_petsc_solver`](https://mooseframework.inl.gov/docs/PRs/18373/coverage/external_petsc_solver)
- [`fluid_properties`](https://mooseframework.inl.gov/docs/PRs/18373/coverage/fluid_properties)
- [`fsi`](https://mooseframework.inl.gov/docs/PRs/18373/coverage/fsi)
- [`functional_expansion_tools`](https://mooseframework.inl.gov/docs/PRs/18373/coverage/functional_expansion_tools)
- [`geochemistry`](https://mooseframework.inl.gov/docs/PRs/18373/coverage/geochemistry)
- [`heat_conduction`](https://mooseframework.inl.gov/docs/PRs/18373/coverage/heat_conduction)
- [`level_set`](https://mooseframework.inl.gov/docs/PRs/18373/coverage/level_set)
- [`misc`](https://mooseframework.inl.gov/docs/PRs/18373/coverage/misc)
- [`navier_stokes`](https://mooseframework.inl.gov/docs/PRs/18373/coverage/navier_stokes)
- [`peridynamics`](https://mooseframework.inl.gov/docs/PRs/18373/coverage/peridynamics)
- [`phase_field`](https://mooseframework.inl.gov/docs/PRs/18373/coverage/phase_field)
- [`porous_flow`](https://mooseframework.inl.gov/docs/PRs/18373/coverage/porous_flow)
- [`ray_tracing`](https://mooseframework.inl.gov/docs/PRs/18373/coverage/ray_tracing)
- [`rdg`](https://mooseframework.inl.gov/docs/PRs/18373/coverage/rdg)
- [`reactor`](https://mooseframework.inl.gov/docs/PRs/18373/coverage/reactor)
- [`richards`](https://mooseframework.inl.gov/docs/PRs/18373/coverage/richards)
- [`stochastic_tools`](https://mooseframework.inl.gov/docs/PRs/18373/coverage/stochastic_tools)
- [`tensor_mechanics`](https://mooseframework.inl.gov/docs/PRs/18373/coverage/tensor_mechanics)
- [`xfem`](https://mooseframework.inl.gov/docs/PRs/18373/coverage/xfem)

</details>

## Warnings

- `framework` new line coverage rate 86.84% is less than the suggested 90.0%



This comment will be updated on new commits.

2021-11-17 07:25 UTC, GiudGiud commented on framework/src/materials/GenericFunctionVectorMaterial.C
> +  }
this is the same code as in GenericFunctionMaterial and it s all there is

I wonder if we re missing some code there?

2021-11-22 16:55 UTC, andrsd requested changes

2021-11-22 16:55 UTC, andrsd commented on framework/include/materials/GenericFunctionVectorMaterial.h
> +// Forward Declarations
cpt. Obvious. - probably caused by copy-and-paste => remove this.

2021-11-22 16:55 UTC, andrsd commented on framework/include/materials/GenericFunctionVectorMaterial.h
> +  std::vector<const Function *> _functions;
Missing doxygen for all the above member variables.

2021-11-22 16:55 UTC, andrsd commented on framework/src/materials/GenericFunctionVectorMaterial.C
> +
Remove this empty line

2021-11-22 16:55 UTC, andrsd commented on framework/src/materials/GenericFunctionVectorMaterial.C
> +                                  "all properties can implicitly become stateful");
Probably don't want to add a deprecated parameter in a new object. Recommended to remove and patch the code below not to use it.

2021-11-24 05:10 UTC, GiudGiud commented
Should be good now. I applied all your comments to GenericFunctionMaterial as well.

2021-11-25 05:46 UTC, GiudGiud commented on framework/src/materials/GenericFunctionVectorMaterial.C
> +  }
it s deleted. no failures. So that was deprecated code.

2021-11-29 18:02 UTC, andrsd approved these changes

2021-11-29 18:03 UTC, merged