Add a FV version of heat flux BC in the Navier Stokes module
idaholab/moose pull request #18434
Opened 2021-07-25 19:06 UTC by GiudGiud

Add related enum, test and documentation
Closes #18433

2021-07-25 19:08 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/783530/) on b3709be wanted to post the following:

Your code requires style changes.  

A patch was auto generated and copied [here](https://mooseframework.inl.gov/docs/PRs/18434/style.patch)  
You can directly apply the patch by running, in the top level of your repository:

`curl -s https://mooseframework.inl.gov/docs/PRs/18434/style.patch | git apply -v`  

Alternatively, with your repository up to date and in the top level of your repository:

`git clang-format 7a8db3f1289a439b996e20314c310e7a1a833fe0`

2021-07-25 20:32 UTC, moosebuild commented
Job [Documentation](https://civet.inl.gov/job/783587/) on c4b346b wanted to post the following:

View the site [here](https://mooseframework.inl.gov/docs/PRs/18434/site)

This comment will be updated on new commits.

2021-08-05 04:20 UTC, GiudGiud commented
@lindsayad for SANA

2021-08-05 17:17 UTC, moosebuild commented
Job [Documentation](https://civet.inl.gov/job/783810/) on cd55e9f : invalidated by @lindsayad

I&#39;&#39;m getting 404 Not Found when trying to view the doc build

2021-08-05 20:53 UTC, lindsayad requested changes

2021-08-05 20:53 UTC, lindsayad commented on modules/navier_stokes/doc/content/source/fvbcs/NSFVHeatFluxBC.md
> +among multiple phases are quite crude \cite{alazmi}.
```suggestion
among multiple phases are quite crude [!citep](alazmi).
```

2021-08-05 20:53 UTC, lindsayad commented on modules/navier_stokes/include/fvbcs/NSFVHeatFluxBC.h
> +  const NS::phase::PhaseEnum _phase;
Sigh. [General style guide](https://google.github.io/styleguide/cppguide.html#Namespace_Names) is to use lower case for namespaces which these new namespaces are doing. I wish that I had read the style guide earlier...but basically all of our namespaces to date have been capitalized. I don't love the mix of different capitalization but I'm also not going to say we shouldn't follow generally accepted styles for new namespaces. So in conclusion... I'm fine with this

2021-08-05 20:53 UTC, lindsayad commented on modules/navier_stokes/src/fvbcs/NSFVHeatFluxBC.C
> +
I don't think we need all the new lines in here

2021-08-05 20:53 UTC, lindsayad commented on modules/navier_stokes/src/fvbcs/NSFVHeatFluxBC.C
> +
```suggestion
```

2021-08-05 20:53 UTC, lindsayad commented on modules/navier_stokes/src/fvbcs/NSFVHeatFluxBC.C
> +
```suggestion
```

2021-08-05 20:53 UTC, lindsayad commented on modules/navier_stokes/src/fvbcs/NSFVHeatFluxBC.C
> +
```suggestion
```

2021-08-07 22:51 UTC, GiudGiud commented on modules/navier_stokes/src/fvbcs/NSFVHeatFluxBC.C
> +
```suggestion
```

2021-08-09 15:20 UTC, lindsayad commented
Looks like we don't have the bib entry for `alazmi`?

2021-08-09 15:26 UTC, GiudGiud commented
I ll go fetch it from pgh

2021-08-09 17:00 UTC, lindsayad approved these changes

2021-08-09 18:52 UTC, merged