Improve handling of dependencies in HistogramVectorPostprocessor
idaholab/moose pull request #18470
Opened 2021-07-29 01:00 UTC by bwspenc

closes #18459

- Generate an error if no vectors are provided in the VPP that is used
  as input.
- Move the initialization to initialSetup() to remove order dependence
  of VPPs in input file.
- Add a test of the newly-added error.
- Add empty VPP testing object used by this test.

2021-07-29 01:02 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/786186/) on 3d62906 wanted to post the following:

Your code requires style changes.  

A patch was auto generated and copied [here](https://mooseframework.inl.gov/docs/PRs/18470/style.patch)  
You can directly apply the patch by running, in the top level of your repository:

`curl -s https://mooseframework.inl.gov/docs/PRs/18470/style.patch | git apply -v`  

Alternatively, with your repository up to date and in the top level of your repository:

`git clang-format 58219425a3180a3429cc37d840a201fa3acf58f6`

2021-07-29 01:05 UTC, aeslaughter requested changes

2021-07-29 01:05 UTC, aeslaughter commented on framework/src/vectorpostprocessors/HistogramVectorPostprocessor.C
> +    mooseError("In HistogramVectorPostprocessor, the '",
paramError("vpp", ...

2021-07-29 01:57 UTC, moosebuild commented
Job [Documentation](https://civet.inl.gov/job/786228/) on d1924cf wanted to post the following:

View the site [here](https://mooseframework.inl.gov/docs/PRs/18470/site)

This comment will be updated on new commits.

2021-07-29 13:32 UTC, bwspenc commented on framework/src/vectorpostprocessors/HistogramVectorPostprocessor.C
> +    mooseError("In HistogramVectorPostprocessor, the '",
I made the switch.

2021-07-29 16:03 UTC, moosebuild commented
Job [Internal App tests](https://civet.inl.gov/job/786298/) on 973e285 : invalidated by @bwspenc

2021-07-30 19:55 UTC, moosebuild commented
Job [Internal App tests](https://civet.inl.gov/job/786298/) on 973e285 : invalidated by @bwspenc

2021-08-02 18:58 UTC, moosebuild commented
Job [Internal App tests](https://civet.inl.gov/job/786298/) on 973e285 : invalidated by @bwspenc

2021-08-03 13:56 UTC, aeslaughter approved these changes
The application failures are unrelated. When those get fixed up this is ready.

2021-08-03 23:49 UTC, moosebuild commented
Job [Internal App tests](https://civet.inl.gov/job/786298/) on 973e285 : invalidated by @bwspenc

2021-08-04 14:04 UTC, merged