Move nearest node number capability from geochemistry module to MOOSE…
idaholab/moose pull request #18505
Opened 2021-08-03 04:25 UTC by GiudGiud

closes #18504

Did I miss any files I should have moved?

2021-08-03 06:09 UTC, moosebuild commented
Job [Documentation](https://civet.inl.gov/job/788226/) on bf46198 wanted to post the following:

View the site [here](https://mooseframework.inl.gov/docs/PRs/18505/site)

This comment will be updated on new commits.

2021-08-03 08:29 UTC, WilkAndy approved these changes, later dismissed
Looks fine to me, thanks :-)

2021-08-03 15:15 UTC, loganharbour requested changes
Requirements need to be updated

2021-08-03 16:31 UTC, GiudGiud commented
ah good catch!
Should be fixed now

2021-08-03 17:25 UTC, loganharbour requested changes

2021-08-03 17:25 UTC, loganharbour commented on test/tests/postprocessors/nearest_node_number/tests
> +  [../]
All of these tests can be removed. We run with these configurations already. In addition, the reqs aren't compliant with the SQA for the framework (some duplication)

2021-08-03 17:25 UTC, loganharbour requested changes

2021-08-03 17:25 UTC, loganharbour commented on test/tests/postprocessors/nearest_node_number/tests
> +  issues = '#15749'
Add issue

2021-08-03 18:40 UTC, andrsd requested changes
Could we update the `tests` file such that it uses `[name]...[]` syntax rather the old `[./name]...[../]`?

2021-08-03 20:07 UTC, GiudGiud commented
ok I ll fix those

2021-08-04 20:07 UTC, loganharbour approved these changes

2021-08-04 20:22 UTC, andrsd approved these changes

2021-08-04 20:27 UTC, merged