Capped Mixing Length Turbulence
idaholab/moose pull request #18666
Opened 2021-08-20 21:25 UTC by freiler

2021-08-20 21:28 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/801394/) on 36bffbc wanted to post the following:

Your code requires style changes.  

A patch was auto generated and copied [here](https://mooseframework.inl.gov/docs/PRs/18666/style.patch)  
You can directly apply the patch by running, in the top level of your repository:

`curl -s https://mooseframework.inl.gov/docs/PRs/18666/style.patch | git apply -v`  

Alternatively, with your repository up to date and in the top level of your repository:

`git clang-format dfc20eba34b361f846606a16259f54919783f86e`

2021-08-21 00:21 UTC, moosebuild commented
Job [Documentation](https://civet.inl.gov/job/801631/) on ade2b50 wanted to post the following:

View the site [here](https://mooseframework.inl.gov/docs/PRs/18666/site)

This comment will be updated on new commits.

2021-08-21 22:05 UTC, GiudGiud commented
Thanks for the contribution, I ll review this soon!
Looked at the tests:
- rename INASDMixingLengthTurbulentViscosityMaterial.md to MixingLengthTurbulentViscosityMaterial.md
- new tests need to be moved from moose/test to moose/modules/navier_stokes/test

2021-08-25 00:14 UTC, GiudGiud requested changes
ins a FE folder. Use finite_volume/ins for these tests.

2021-08-25 00:14 UTC, GiudGiud commented on modules/navier_stokes/src/auxkernels/WallDistanceMixingLengthAux.C
> +  params.addParam<Real>("delta", 1e9, "");
all 3 need a description

2021-08-25 00:14 UTC, GiudGiud commented on modules/navier_stokes/src/auxkernels/WallDistanceMixingLengthAux.C
> +  }
```suggestion
  if (std::sqrt(min_sq_dist) / _delta <= _von_karman_const_0 / _von_karman_const)
    return _von_karman_const * std::sqrt(min_sq_dist);
  else
    return _von_karman_const_0 * _delta;
```

2021-08-25 00:14 UTC, GiudGiud commented on modules/navier_stokes/src/fvkernels/INSFVMixingLengthReynoldsStress.C
> +  // ADReal eddy_diff = velocity_gradient * mixing_len * mixing_len;
```suggestion
```

2021-08-25 00:14 UTC, GiudGiud commented on modules/navier_stokes/src/materials/MixingLengthTurbulentViscosityMaterial.C
> +                             "for the mixing length model.");
change description
this computes the total viscosity not just the turbulent viscosity

2021-08-25 00:14 UTC, GiudGiud commented on modules/navier_stokes/test/tests/finite_volume/ins/wall_distance_capped_mixing_length_aux/tests
> +    requirement = 'The system shall be able to impose turbulent viscosity based on the capped mixing length model.'
phrasing is weird with impose

2021-08-25 00:14 UTC, GiudGiud commented on modules/navier_stokes/test/tests/finite_volume/ins/mixing_length_total_viscosity_material/tests
> +    requirement = 'The system shall be able to calculate the total turbulent viscosity based on the capped mixing length model.'
say it s a material property

2021-08-25 00:14 UTC, GiudGiud commented on modules/navier_stokes/test/tests/finite_volume/ins/mixing_length_eddy_viscosity_aux/tests
> +    requirement = 'The system shall be able to compute the turbulent viscosity based on the capped mixing length model.'
say it s a variable

2021-08-30 06:02 UTC, GiudGiud commented
Any idea as to why your tests are diffing? Are they running fine on your machine?

2021-09-02 15:48 UTC, GiudGiud commented on modules/navier_stokes/include/auxkernels/INSFVMixingLengthTurbulentViscosityAux.h
> +class INSFVMixingLengthTurbulentViscosityAux : public AuxKernel
this is the format for whole-class header dosctring
```suggestion
class INSFVVelocityVariable;
 
 /*
   * Computes the value of the eddy viscosity for the mixing length model.
   */ 
class INSFVMixingLengthTurbulentViscosityAux : public AuxKernel
```

2021-09-02 15:48 UTC, GiudGiud commented on modules/navier_stokes/include/auxkernels/WallDistanceMixingLengthAux.h
> +// Computes the mixing length for the mixing length turbulence model.
same

2021-09-02 15:48 UTC, GiudGiud commented on modules/navier_stokes/include/materials/MixingLengthTurbulentViscosityMaterial.h
> +// mixing length model turbulent viscosity.
same

2021-09-03 15:29 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/813031/) on 77407f0 wanted to post the following:

Your code requires style changes.  

A patch was auto generated and copied [here](https://mooseframework.inl.gov/docs/PRs/18666/style.patch)  
You can directly apply the patch by running, in the top level of your repository:

`curl -s https://mooseframework.inl.gov/docs/PRs/18666/style.patch | git apply -v`  

Alternatively, with your repository up to date and in the top level of your repository:

`git clang-format 091b3c0920114d667083ef2e66ac367d022b3487`

2021-09-08 16:32 UTC, GiudGiud approved these changes

2021-09-08 16:32 UTC, merged

2021-09-08 16:33 UTC, GiudGiud commented
@lindsayad this adds some tests that will need some functor material conversion

2021-09-08 16:41 UTC, lindsayad commented
:frowning_face: