Add nearest point side layered integral user object
idaholab/moose pull request #18704
Opened 2021-08-25 22:34 UTC by aprilnovak

## Reason
Allow heat flux integrals to be computed as layered integrals of a heat flux auxiliary variable for Cardinal calculations.

## Design
Added a `NearestPointLayeredSideIntegral` userobject that is essentially identical to the average version, but with different class inheritance. The test verifies correct implementation by comparing a layered side average (already in the framework) with a layered side integral by showing that the integral userobject is equal to the average userobject multiplied by the "bin" surface area.

## Impact
New feature

Closes #18702

2021-08-31 16:00 UTC, andrsd requested changes

2021-08-31 16:02 UTC, aprilnovak commented on framework/src/userobject/NearestPointLayeredSideIntegral.C
> +  params.addClassDescription("Compute layered side integrals for nearest-point based subdomains");
Yes, I mean sideset - all of these are copy-paste issues, my bad.

2021-08-31 16:45 UTC, andrsd approved these changes

2021-09-01 03:18 UTC, GiudGiud approved these changes

2021-09-01 03:18 UTC, merged