adding average point separation postprocessor
idaholab/moose pull request #18755
Opened 2021-09-01 16:10 UTC by jain651

# Reason
Currently to calculate deformation between two points in a domain, we need to get displacement in each direction for individual points and then manually obtain the deformation.

# Design
A new postprocessor is required to obtain deformation between two points.

# Impact
Reduces the length of input file.
#18751

2021-09-01 18:11 UTC, moosebuild commented
Job [Documentation](https://civet.inl.gov/job/809754/) on f467675 wanted to post the following:

View the site [here](https://mooseframework.inl.gov/docs/PRs/18755/site)

This comment will be updated on new commits.

2021-09-01 23:17 UTC, bwspenc requested changes

2021-09-02 13:14 UTC, jain651 commented on modules/tensor_mechanics/src/postprocessors/AveragePointSeparation.C
> +                                 _system.point_value(_disp_num[j], _last_point[i], false));
I agree with the first point. I was trying to get the average deformation, but you are right I should use the total separation in the calculation. 

For second and third points:
Here, I am trying to do what we generally do in experiment. We measure the separation between a set of first points and last points, then take take an average of measurements to obtain average deformation. I am trying to do the same thing. 
For this reason, both array should have the same size. I will put a check for this too in the corrected PR.

Please let me know if you still think that we should take the average of all first point and last point array and then get the average separation.

2021-09-02 13:14 UTC, jain651 commented on modules/tensor_mechanics/doc/content/source/postprocessors/AveragePointSeparation.md
> +This `PostProcessor` computes average distance between a set of points specified in two array `first_point` and `last_point`.
Done!

2021-09-02 13:15 UTC, jain651 commented on modules/tensor_mechanics/include/postprocessors/AveragePointSeparation.h
> + * Warning: This postprocessor may result in undefined behavior if utilized with
I have removed it. It should not be here.

2021-09-02 13:15 UTC, jain651 commented on modules/tensor_mechanics/include/postprocessors/AveragePointSeparation.h
> +  /// The point to locate
Done!

2021-09-02 13:15 UTC, jain651 commented on modules/tensor_mechanics/include/postprocessors/AveragePointSeparation.h
> +  /// The value of the variable at the desired location
Done!

2021-09-02 13:15 UTC, jain651 commented on modules/tensor_mechanics/src/postprocessors/AveragePointSeparation.C
> +      "Compute the average separation between a list of two specified locations");
Done!

2021-09-02 13:19 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/810709/) on b0b51e2 wanted to post the following:

Your code requires style changes.  

A patch was auto generated and copied [here](https://mooseframework.inl.gov/docs/PRs/18755/style.patch)  
You can directly apply the patch by running, in the top level of your repository:

`curl -s https://mooseframework.inl.gov/docs/PRs/18755/style.patch | git apply -v`  

Alternatively, with your repository up to date and in the top level of your repository:

`git clang-format 9fa0a6162fd91bdec65b186da8de84bc5d891039`

2021-09-03 12:46 UTC, jain651 commented
closing as it is more suitable for BlackBear App.

2021-09-03 12:46 UTC, closed without merging