Reference residual improvements
idaholab/moose pull request #18773
Opened 2021-09-03 22:27 UTC by dschwen

Closes #18772

2021-09-04 20:49 UTC, moosebuild commented
Job [Documentation](https://civet.inl.gov/job/814216/) on 3aff604 wanted to post the following:

View the site [here](https://mooseframework.inl.gov/docs/PRs/18773/site)

This comment will be updated on new commits.

2021-09-06 23:59 UTC, tophmatthews commented on framework/src/problems/ReferenceResidualProblem.C
> +      "converge_on",
🥳

2021-09-11 22:03 UTC, moosebuild commented
Job [Generate and verify coverage](https://civet.inl.gov/job/817570/) on 2095b26 wanted to post the following:


## Framework coverage

<table>
  <thead>
    <tr>
      <th></th>
      <th>0d650f</th>
      <th colspan=4>#18773 2095b2</th>
    </tr>
    <tr>
      <th></th>
      <th>Total</th>
      <th>Total</th>
      <th>+/-</th>
      <th>New</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><b>Rate</b></td>
      <td>81.48%</td>
      <td>81.49%</td>
      <td>+0.01%</td>
      <td>73.44%</td>
    </tr>
    <tr>
      <td><b>Hits</b></td>
      <td>69323</td>
      <td>69347</td>
      <td>+24</td>
      <td>47</td>
    </tr>
    <tr>
      <td><b>Misses</b></td>
      <td>15757</td>
      <td>15750</td>
      <td>-7</td>
      <td>17</td>
    </tr>
  </tbody>
</table>

[Diff coverage report](https://mooseframework.inl.gov/docs/PRs/18773/coverage/diff/framework.html)

## Modules coverage

<table>
  <thead>
    <tr>
      <th></th>
      <th>0d650f</th>
      <th colspan=4>#18773 2095b2</th>
    </tr>
    <tr>
      <th></th>
      <th>Total</th>
      <th>Total</th>
      <th>+/-</th>
      <th>New</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><b>Rate</b></td>
      <td>86.95%</td>
      <td>86.95%</td>
      <td>-</td>
      <td>0.00%</td>
    </tr>
    <tr>
      <td><b>Hits</b></td>
      <td>90680</td>
      <td>90680</td>
      <td>-</td>
      <td>0</td>
    </tr>
    <tr>
      <td><b>Misses</b></td>
      <td>13606</td>
      <td>13606</td>
      <td>-</td>
      <td>1</td>
    </tr>
  </tbody>
</table>

[Diff coverage report](https://mooseframework.inl.gov/docs/PRs/18773/coverage/diff/modules.html)

## Full coverage reports

<details><summary>Reports</summary>

- [framework](https://mooseframework.inl.gov/docs/PRs/18773/coverage/framework)
- [chemical_reactions](https://mooseframework.inl.gov/docs/PRs/18773/coverage/chemical_reactions)
- [combined](https://mooseframework.inl.gov/docs/PRs/18773/coverage/combined)
- [contact](https://mooseframework.inl.gov/docs/PRs/18773/coverage/contact)
- [external_petsc_solver](https://mooseframework.inl.gov/docs/PRs/18773/coverage/external_petsc_solver)
- [fluid_properties](https://mooseframework.inl.gov/docs/PRs/18773/coverage/fluid_properties)
- [fsi](https://mooseframework.inl.gov/docs/PRs/18773/coverage/fsi)
- [functional_expansion_tools](https://mooseframework.inl.gov/docs/PRs/18773/coverage/functional_expansion_tools)
- [geochemistry](https://mooseframework.inl.gov/docs/PRs/18773/coverage/geochemistry)
- [heat_conduction](https://mooseframework.inl.gov/docs/PRs/18773/coverage/heat_conduction)
- [level_set](https://mooseframework.inl.gov/docs/PRs/18773/coverage/level_set)
- [misc](https://mooseframework.inl.gov/docs/PRs/18773/coverage/misc)
- [navier_stokes](https://mooseframework.inl.gov/docs/PRs/18773/coverage/navier_stokes)
- [peridynamics](https://mooseframework.inl.gov/docs/PRs/18773/coverage/peridynamics)
- [phase_field](https://mooseframework.inl.gov/docs/PRs/18773/coverage/phase_field)
- [porous_flow](https://mooseframework.inl.gov/docs/PRs/18773/coverage/porous_flow)
- [ray_tracing](https://mooseframework.inl.gov/docs/PRs/18773/coverage/ray_tracing)
- [rdg](https://mooseframework.inl.gov/docs/PRs/18773/coverage/rdg)
- [richards](https://mooseframework.inl.gov/docs/PRs/18773/coverage/richards)
- [stochastic_tools](https://mooseframework.inl.gov/docs/PRs/18773/coverage/stochastic_tools)
- [tensor_mechanics](https://mooseframework.inl.gov/docs/PRs/18773/coverage/tensor_mechanics)
- [xfem](https://mooseframework.inl.gov/docs/PRs/18773/coverage/xfem)

</details>

This comment will be updated on new commits.

2021-09-18 15:24 UTC, dschwen commented
@bwspenc Please. Review. My. Pull. Requests.

2021-09-21 17:43 UTC, bwspenc requested changes

2021-09-21 17:47 UTC, dschwen commented on framework/include/problems/ReferenceResidualProblem.h
> +   * Bison uses std::string where we prefer to use NonlinearVariableName.
disd't mean to code shame Bison...

2021-09-21 17:51 UTC, dschwen commented on framework/src/problems/ReferenceResidualProblem.C
> +    _group_resid[group] += _converge_on_var[i] ? resid : 0;
That check isn't quite so easy, as all variables are in groups (some are just in groups of size 1)

2021-09-21 17:52 UTC, dschwen commented on framework/src/problems/ReferenceResidualProblem.C
> +    _group_resid[group] += _converge_on_var[i] ? resid : 0;
actually it is easy..

2021-09-21 18:45 UTC, dschwen commented on framework/src/problems/ReferenceResidualProblem.C
> +    _group_resid[group] += _converge_on_var[i] ? resid : 0;
done

2021-09-21 18:56 UTC, bwspenc commented on framework/src/problems/ReferenceResidualProblem.C
> +    _group_resid[group] += _converge_on_var[i] ? resid : 0;
I think we wouldn't ever fall into the 0 case on line 347 now, would we? Seems like a good use for an assert.

2021-09-21 18:57 UTC, bwspenc requested changes
Minor issue with requirement being wrong. Also see my note about a potential use of an assert.

2021-09-21 19:06 UTC, dschwen commented on test/tests/problems/reference_residual_problem/tests
> +    requirement = 'The system shall have the ability to base system convergence on the convergence of a subset of variables.'
D'Uh, right, forgot to change that

2021-09-21 19:15 UTC, dschwen commented on framework/src/problems/ReferenceResidualProblem.C
> +    _group_resid[group] += _converge_on_var[i] ? resid : 0;
we absolutely will fall into that regularly when variables are excluded from the check

2021-09-21 19:45 UTC, bwspenc commented on framework/src/problems/ReferenceResidualProblem.C
> +    _group_resid[group] += _converge_on_var[i] ? resid : 0;
Oh yeah, because everything's grouped...

2021-09-21 19:46 UTC, bwspenc approved these changes

2021-09-22 13:00 UTC, merged