Always clone rms
idaholab/moose pull request #18798
Opened 2021-09-09 22:33 UTC by lindsayad

Also continue the very slow march to make relationship manager code more
readable which hopefully also means less liable to bug-ridden. This
change came about because on Jacob's 3D mortar PR he has a test that
collects two meshes into a single one using the
`MeshCollectionGenerator`. We were failing an assertion when running
with distributed mesh because a relationship manager/ghosting functor
was using the incorrect `MeshBase` object. To avoid this we should
always clone and make sure we're initializing with the correct mesh

Refs #18203

2021-09-09 23:51 UTC, moosebuild commented
Job [Documentation](https://civet.inl.gov/job/816752/) on fb1d891 wanted to post the following:

View the site [here](https://mooseframework.inl.gov/docs/PRs/18798/site)

This comment will be updated on new commits.

2021-09-15 16:00 UTC, moosebuild commented
Job [Generate and verify coverage](https://civet.inl.gov/job/819929/) on 7ca4a7e wanted to post the following:


## Framework coverage

<table>
  <thead>
    <tr>
      <th></th>
      <th>7df3b0</th>
      <th colspan=4>#18798 7ca4a7</th>
    </tr>
    <tr>
      <th></th>
      <th>Total</th>
      <th>Total</th>
      <th>+/-</th>
      <th>New</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><b>Rate</b></td>
      <td>81.50%</td>
      <td>81.50%</td>
      <td>+0.00%</td>
      <td>83.78%</td>
    </tr>
    <tr>
      <td><b>Hits</b></td>
      <td>69334</td>
      <td>69358</td>
      <td>+24</td>
      <td>31</td>
    </tr>
    <tr>
      <td><b>Misses</b></td>
      <td>15740</td>
      <td>15745</td>
      <td>+5</td>
      <td>6</td>
    </tr>
  </tbody>
</table>

[Diff coverage report](https://mooseframework.inl.gov/docs/PRs/18798/coverage/framework.html)

## Modules coverage

<table>
  <thead>
    <tr>
      <th></th>
      <th>7df3b0</th>
      <th colspan=4>#18798 7ca4a7</th>
    </tr>
    <tr>
      <th></th>
      <th>Total</th>
      <th>Total</th>
      <th>+/-</th>
      <th>New</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><b>Rate</b></td>
      <td>86.99%</td>
      <td>86.99%</td>
      <td>-</td>
      <td>-</td>
    </tr>
    <tr>
      <td><b>Hits</b></td>
      <td>90751</td>
      <td>90751</td>
      <td>-</td>
      <td>0</td>
    </tr>
    <tr>
      <td><b>Misses</b></td>
      <td>13567</td>
      <td>13567</td>
      <td>-</td>
      <td>0</td>
    </tr>
  </tbody>
</table>

[Diff coverage report](https://mooseframework.inl.gov/docs/PRs/18798/coverage/modules.html)

## Full coverage reports

<details><summary>Reports</summary>

- [framework](https://mooseframework.inl.gov/docs/PRs/18798/coverage/framework)
- [chemical_reactions](https://mooseframework.inl.gov/docs/PRs/18798/coverage/chemical_reactions)
- [combined](https://mooseframework.inl.gov/docs/PRs/18798/coverage/combined)
- [contact](https://mooseframework.inl.gov/docs/PRs/18798/coverage/contact)
- [external_petsc_solver](https://mooseframework.inl.gov/docs/PRs/18798/coverage/external_petsc_solver)
- [fluid_properties](https://mooseframework.inl.gov/docs/PRs/18798/coverage/fluid_properties)
- [fsi](https://mooseframework.inl.gov/docs/PRs/18798/coverage/fsi)
- [functional_expansion_tools](https://mooseframework.inl.gov/docs/PRs/18798/coverage/functional_expansion_tools)
- [geochemistry](https://mooseframework.inl.gov/docs/PRs/18798/coverage/geochemistry)
- [heat_conduction](https://mooseframework.inl.gov/docs/PRs/18798/coverage/heat_conduction)
- [level_set](https://mooseframework.inl.gov/docs/PRs/18798/coverage/level_set)
- [misc](https://mooseframework.inl.gov/docs/PRs/18798/coverage/misc)
- [navier_stokes](https://mooseframework.inl.gov/docs/PRs/18798/coverage/navier_stokes)
- [peridynamics](https://mooseframework.inl.gov/docs/PRs/18798/coverage/peridynamics)
- [phase_field](https://mooseframework.inl.gov/docs/PRs/18798/coverage/phase_field)
- [porous_flow](https://mooseframework.inl.gov/docs/PRs/18798/coverage/porous_flow)
- [ray_tracing](https://mooseframework.inl.gov/docs/PRs/18798/coverage/ray_tracing)
- [rdg](https://mooseframework.inl.gov/docs/PRs/18798/coverage/rdg)
- [richards](https://mooseframework.inl.gov/docs/PRs/18798/coverage/richards)
- [stochastic_tools](https://mooseframework.inl.gov/docs/PRs/18798/coverage/stochastic_tools)
- [tensor_mechanics](https://mooseframework.inl.gov/docs/PRs/18798/coverage/tensor_mechanics)
- [xfem](https://mooseframework.inl.gov/docs/PRs/18798/coverage/xfem)

</details>


This comment will be updated on new commits.

2021-09-16 19:17 UTC, fdkong requested changes
Looks good

2021-09-21 16:56 UTC, lindsayad commented
@fdkong I hope this is beautiful code now

2021-09-23 17:01 UTC, fdkong approved these changes
Look nice now

2021-09-23 18:34 UTC, merged