Functor gradient
idaholab/moose pull request #18806
Opened 2021-09-12 15:40 UTC by lindsayad

@GiudGiud you mentioned trying to do some CRAB modeling this weekend. I don't know if you were planning to use the functor system, and if yes also planning on trying to update @freiler's turbulence work to use it? If so I believe you'll need this add-on for doing functor evaluation of gradients. I'm not going to hold up the other PR with this added work, so I'm opening this new one.

2021-09-12 17:58 UTC, moosebuild commented
Job [Documentation](https://civet.inl.gov/job/817812/) on a61c2b6 wanted to post the following:

View the site [here](https://mooseframework.inl.gov/docs/PRs/18806/site)

This comment will be updated on new commits.

2021-09-12 19:08 UTC, moosebuild commented
Job [Generate and verify coverage](https://civet.inl.gov/job/817841/) on a61c2b6 wanted to post the following:


## Framework coverage

<table>
  <thead>
    <tr>
      <th></th>
      <th>0d650f</th>
      <th colspan=4>#18806 a61c2b</th>
    </tr>
    <tr>
      <th></th>
      <th>Total</th>
      <th>Total</th>
      <th>+/-</th>
      <th>New</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><b>Rate</b></td>
      <td>81.48%</td>
      <td>81.40%</td>
      <td>-0.08%</td>
      <td>75.00%</td>
    </tr>
    <tr>
      <td><b>Hits</b></td>
      <td>69323</td>
      <td>69810</td>
      <td>+487</td>
      <td>612</td>
    </tr>
    <tr>
      <td><b>Misses</b></td>
      <td>15757</td>
      <td>15951</td>
      <td>+194</td>
      <td>204</td>
    </tr>
  </tbody>
</table>

[Diff coverage report](https://mooseframework.inl.gov/docs/PRs/18806/coverage/diff/framework.html)

## Modules coverage

<table>
  <thead>
    <tr>
      <th></th>
      <th>0d650f</th>
      <th colspan=4>#18806 a61c2b</th>
    </tr>
    <tr>
      <th></th>
      <th>Total</th>
      <th>Total</th>
      <th>+/-</th>
      <th>New</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><b>Rate</b></td>
      <td>86.95%</td>
      <td>86.96%</td>
      <td>+0.01%</td>
      <td>96.83%</td>
    </tr>
    <tr>
      <td><b>Hits</b></td>
      <td>90680</td>
      <td>90767</td>
      <td>+87</td>
      <td>244</td>
    </tr>
    <tr>
      <td><b>Misses</b></td>
      <td>13606</td>
      <td>13613</td>
      <td>+7</td>
      <td>8</td>
    </tr>
  </tbody>
</table>

[Diff coverage report](https://mooseframework.inl.gov/docs/PRs/18806/coverage/diff/modules.html)

## Full coverage reports

<details><summary>Reports</summary>

- [framework](https://mooseframework.inl.gov/docs/PRs/18806/coverage/framework)
- [chemical_reactions](https://mooseframework.inl.gov/docs/PRs/18806/coverage/chemical_reactions)
- [combined](https://mooseframework.inl.gov/docs/PRs/18806/coverage/combined)
- [contact](https://mooseframework.inl.gov/docs/PRs/18806/coverage/contact)
- [external_petsc_solver](https://mooseframework.inl.gov/docs/PRs/18806/coverage/external_petsc_solver)
- [fluid_properties](https://mooseframework.inl.gov/docs/PRs/18806/coverage/fluid_properties)
- [fsi](https://mooseframework.inl.gov/docs/PRs/18806/coverage/fsi)
- [functional_expansion_tools](https://mooseframework.inl.gov/docs/PRs/18806/coverage/functional_expansion_tools)
- [geochemistry](https://mooseframework.inl.gov/docs/PRs/18806/coverage/geochemistry)
- [heat_conduction](https://mooseframework.inl.gov/docs/PRs/18806/coverage/heat_conduction)
- [level_set](https://mooseframework.inl.gov/docs/PRs/18806/coverage/level_set)
- [misc](https://mooseframework.inl.gov/docs/PRs/18806/coverage/misc)
- [navier_stokes](https://mooseframework.inl.gov/docs/PRs/18806/coverage/navier_stokes)
- [peridynamics](https://mooseframework.inl.gov/docs/PRs/18806/coverage/peridynamics)
- [phase_field](https://mooseframework.inl.gov/docs/PRs/18806/coverage/phase_field)
- [porous_flow](https://mooseframework.inl.gov/docs/PRs/18806/coverage/porous_flow)
- [ray_tracing](https://mooseframework.inl.gov/docs/PRs/18806/coverage/ray_tracing)
- [rdg](https://mooseframework.inl.gov/docs/PRs/18806/coverage/rdg)
- [richards](https://mooseframework.inl.gov/docs/PRs/18806/coverage/richards)
- [stochastic_tools](https://mooseframework.inl.gov/docs/PRs/18806/coverage/stochastic_tools)
- [tensor_mechanics](https://mooseframework.inl.gov/docs/PRs/18806/coverage/tensor_mechanics)
- [xfem](https://mooseframework.inl.gov/docs/PRs/18806/coverage/xfem)

</details>

This comment will be updated on new commits.

2021-09-12 21:37 UTC, lindsayad commented
Mac test failure because of issue documented in libmesh/libmesh#3018

2021-09-13 01:52 UTC, GiudGiud commented
Ah thank you! That would indeed come in handy. As soon as we merge this there are a few discussions asking about matprop gradients btw, self-reminder to update those
@freiler is very close to a merge on the VTB so I'm waiting on that to update his input to wcnsfv. I'm actually looking at SAM-Pgh coupling with INSFV.
Please let me know what's your next step so we dont overlap.

2021-09-13 02:37 UTC, lindsayad commented
It sounds like you’re covering both of the things we talked about doing for the crab report. Let me know if I can help at any point. 

In the meantime I’ll be shepherding PRs through that are necessary for the user object PR. Mostly the functor PRs and the libmesh update (the latter is needed for the parallel dual number communication) 

(And working on the TA report) 

> On Sep 12, 2021, at 6:52 PM, Guillaume Giudicelli ***@***.***> wrote:
> 
> ﻿
> Ah thank you! That would indeed come in handy. As soon as we merge this there are a few discussions asking about matprop gradients btw, self-reminder to update those
> @freiler is very close to a merge on the VTB so I'm waiting on that to update his input to wcnsfv. I'm actually looking at SAM-Pgh coupling with INSFV.
> Please let me know what's your next step so we dont overlap.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.
> Triage notifications on the go with GitHub Mobile for iOS or Android.

2021-09-15 14:30 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/820002/) on a5c1826 wanted to post the following:

Your code requires style changes.  

A patch was auto generated and copied [here](https://mooseframework.inl.gov/docs/PRs/18806/style.patch)  
You can directly apply the patch by running, in the top level of your repository:

`curl -s https://mooseframework.inl.gov/docs/PRs/18806/style.patch | git apply -v`  

Alternatively, with your repository up to date and in the top level of your repository:

`git clang-format 7df3b095f66fb205a46d4afc6aa4a23e4b394a95`

2021-09-15 17:41 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/820411/) on 6e880f5 wanted to post the following:

Your code requires style changes.  

A patch was auto generated and copied [here](https://mooseframework.inl.gov/docs/PRs/18806/style.patch)  
You can directly apply the patch by running, in the top level of your repository:

`curl -s https://mooseframework.inl.gov/docs/PRs/18806/style.patch | git apply -v`  

Alternatively, with your repository up to date and in the top level of your repository:

`git clang-format 7df3b095f66fb205a46d4afc6aa4a23e4b394a95`

2021-09-15 19:01 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/820533/) on ad10f5e wanted to post the following:

Your code requires style changes.  

A patch was auto generated and copied [here](https://mooseframework.inl.gov/docs/PRs/18806/style.patch)  
You can directly apply the patch by running, in the top level of your repository:

`curl -s https://mooseframework.inl.gov/docs/PRs/18806/style.patch | git apply -v`  

Alternatively, with your repository up to date and in the top level of your repository:

`git clang-format 7df3b095f66fb205a46d4afc6aa4a23e4b394a95`

2021-09-15 20:09 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/820764/) on c42bc6d wanted to post the following:

Your code requires style changes.  

A patch was auto generated and copied [here](https://mooseframework.inl.gov/docs/PRs/18806/style.patch)  
You can directly apply the patch by running, in the top level of your repository:

`curl -s https://mooseframework.inl.gov/docs/PRs/18806/style.patch | git apply -v`  

Alternatively, with your repository up to date and in the top level of your repository:

`git clang-format 7df3b095f66fb205a46d4afc6aa4a23e4b394a95`

2021-09-16 05:51 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/821315/) on f839102 wanted to post the following:

Your code requires style changes.  

A patch was auto generated and copied [here](https://mooseframework.inl.gov/docs/PRs/18806/style.patch)  
You can directly apply the patch by running, in the top level of your repository:

`curl -s https://mooseframework.inl.gov/docs/PRs/18806/style.patch | git apply -v`  

Alternatively, with your repository up to date and in the top level of your repository:

`git clang-format 7b42ecd3a731e49a38c8cb5f154d628e771ac5e4`

2021-09-16 06:25 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/821347/) on 59c5152 wanted to post the following:

Your code requires style changes.  

A patch was auto generated and copied [here](https://mooseframework.inl.gov/docs/PRs/18806/style.patch)  
You can directly apply the patch by running, in the top level of your repository:

`curl -s https://mooseframework.inl.gov/docs/PRs/18806/style.patch | git apply -v`  

Alternatively, with your repository up to date and in the top level of your repository:

`git clang-format 7b42ecd3a731e49a38c8cb5f154d628e771ac5e4`

2021-09-16 06:31 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/821379/) on d14543f wanted to post the following:

Your code requires style changes.  

A patch was auto generated and copied [here](https://mooseframework.inl.gov/docs/PRs/18806/style.patch)  
You can directly apply the patch by running, in the top level of your repository:

`curl -s https://mooseframework.inl.gov/docs/PRs/18806/style.patch | git apply -v`  

Alternatively, with your repository up to date and in the top level of your repository:

`git clang-format 7b42ecd3a731e49a38c8cb5f154d628e771ac5e4`

2021-09-16 06:45 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/821446/) on a4a5fb2 wanted to post the following:

Your code requires style changes.  

A patch was auto generated and copied [here](https://mooseframework.inl.gov/docs/PRs/18806/style.patch)  
You can directly apply the patch by running, in the top level of your repository:

`curl -s https://mooseframework.inl.gov/docs/PRs/18806/style.patch | git apply -v`  

Alternatively, with your repository up to date and in the top level of your repository:

`git clang-format 7b42ecd3a731e49a38c8cb5f154d628e771ac5e4`

2021-09-16 17:22 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/821727/) on 241f5ea wanted to post the following:

Your code requires style changes.  

A patch was auto generated and copied [here](https://mooseframework.inl.gov/docs/PRs/18806/style.patch)  
You can directly apply the patch by running, in the top level of your repository:

`curl -s https://mooseframework.inl.gov/docs/PRs/18806/style.patch | git apply -v`  

Alternatively, with your repository up to date and in the top level of your repository:

`git clang-format 7b42ecd3a731e49a38c8cb5f154d628e771ac5e4`

2021-09-17 06:24 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/822483/) on 38af140 wanted to post the following:

Your code requires style changes.  

A patch was auto generated and copied [here](https://mooseframework.inl.gov/docs/PRs/18806/style.patch)  
You can directly apply the patch by running, in the top level of your repository:

`curl -s https://mooseframework.inl.gov/docs/PRs/18806/style.patch | git apply -v`  

Alternatively, with your repository up to date and in the top level of your repository:

`git clang-format da4fe72e01a3d9059012746105368f24c3e5f416`

2021-09-20 21:20 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/824647/) on fb65dc6 wanted to post the following:

Your code requires style changes.  

A patch was auto generated and copied [here](https://mooseframework.inl.gov/docs/PRs/18806/style.patch)  
You can directly apply the patch by running, in the top level of your repository:

`curl -s https://mooseframework.inl.gov/docs/PRs/18806/style.patch | git apply -v`  

Alternatively, with your repository up to date and in the top level of your repository:

`git clang-format b9a47a04f1981f6c931ea4ae97a940025724adb5`

2021-09-20 21:45 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/824751/) on 720e7be wanted to post the following:

Your code requires style changes.  

A patch was auto generated and copied [here](https://mooseframework.inl.gov/docs/PRs/18806/style.patch)  
You can directly apply the patch by running, in the top level of your repository:

`curl -s https://mooseframework.inl.gov/docs/PRs/18806/style.patch | git apply -v`  

Alternatively, with your repository up to date and in the top level of your repository:

`git clang-format b9a47a04f1981f6c931ea4ae97a940025724adb5`

2021-09-21 03:43 UTC, moosebuild commented
Job [Generate and verify coverage](https://civet.inl.gov/job/825260/) on cc8d449 wanted to post the following:


The following coverage requirement(s) failed:
- navier_stokes coverage rate 76.80% is less than the required 77%

2021-09-22 18:50 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/827235/) on b0af98e wanted to post the following:

Your code requires style changes.  

A patch was auto generated and copied [here](https://mooseframework.inl.gov/docs/PRs/18806/style.patch)  
You can directly apply the patch by running, in the top level of your repository:

`curl -s https://mooseframework.inl.gov/docs/PRs/18806/style.patch | git apply -v`  

Alternatively, with your repository up to date and in the top level of your repository:

`git clang-format b79d3c2f805a246394c54cd9eca37748c7d3dd5f`

2021-09-23 01:06 UTC, moosebuild commented
Job [Generate and verify coverage](https://civet.inl.gov/job/827807/) on 371f9d7 wanted to post the following:


The following coverage requirement(s) failed:
- navier_stokes coverage rate 76.80% is less than the required 77%

2021-09-24 09:46 UTC, moosebuild commented
Job [Generate and verify coverage](https://civet.inl.gov/job/829744/) on 8f99dba wanted to post the following:


The following coverage requirement(s) failed:
- fluid_properties coverage rate 82.61% is less than the required 84%
- navier_stokes coverage rate 76.80% is less than the required 77%

2021-09-27 22:10 UTC, moosebuild commented
Job [Generate and verify coverage](https://civet.inl.gov/job/831312/) on 9f22eef wanted to post the following:


The following coverage requirement(s) failed:
- `fluid_properties` coverage rate 82.61% is less than the required 84.0%
- `navier_stokes` coverage rate 76.80% is less than the required 77.0%

2021-10-15 17:47 UTC, GiudGiud requested changes

2021-10-15 19:19 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/851599/) on aa6aa2c wanted to post the following:

Your code requires style changes.  

A patch was auto generated and copied [here](https://mooseframework.inl.gov/docs/PRs/18806/style.patch)  
You can directly apply the patch by running, in the top level of your repository:

`curl -s https://mooseframework.inl.gov/docs/PRs/18806/style.patch | git apply -v`  

Alternatively, with your repository up to date and in the top level of your repository:

`git clang-format 72060375990a6b4756f4964242078db7d1371c82`

2021-10-18 18:47 UTC, GiudGiud submitted a review, later dismissed

2021-10-19 03:58 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/854798/) on 25b397b wanted to post the following:

Your code requires style changes.  

A patch was auto generated and copied [here](https://mooseframework.inl.gov/docs/PRs/18806/style.patch)  
You can directly apply the patch by running, in the top level of your repository:

`curl -s https://mooseframework.inl.gov/docs/PRs/18806/style.patch | git apply -v`  

Alternatively, with your repository up to date and in the top level of your repository:

`git clang-format a9a64a94bbe755ed68c5aef8fd06b17980d89b1d`

2021-10-19 19:00 UTC, GiudGiud submitted a review, later dismissed

2021-10-20 13:56 UTC, GiudGiud approved these changes

2021-10-20 13:58 UTC, merged