Update templates to address defeciency and suggestion from 2021 audit
idaholab/moose pull request #18821
Opened 2021-09-14 15:18 UTC by aeslaughter

Closes D-01 and S-02 from 2021 audit

(closes #18816)

2021-09-14 16:44 UTC, moosebuild commented
Job [Documentation](https://civet.inl.gov/job/819444/) on ca38e69 wanted to post the following:

View the site [here](https://mooseframework.inl.gov/docs/PRs/18821/site)

This comment will be updated on new commits.

2021-09-14 18:04 UTC, moosebuild commented
Job [Generate and verify coverage](https://civet.inl.gov/job/819473/) on ca38e69 wanted to post the following:


## Framework coverage

<table>
  <thead>
    <tr>
      <th></th>
      <th>7df3b0</th>
      <th colspan=4>#18821 ca38e6</th>
    </tr>
    <tr>
      <th></th>
      <th>Total</th>
      <th>Total</th>
      <th>+/-</th>
      <th>New</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><b>Rate</b></td>
      <td>81.50%</td>
      <td>81.50%</td>
      <td>-</td>
      <td>-</td>
    </tr>
    <tr>
      <td><b>Hits</b></td>
      <td>69334</td>
      <td>69334</td>
      <td>-</td>
      <td>0</td>
    </tr>
    <tr>
      <td><b>Misses</b></td>
      <td>15740</td>
      <td>15740</td>
      <td>-</td>
      <td>0</td>
    </tr>
  </tbody>
</table>

[Diff coverage report](https://mooseframework.inl.gov/docs/PRs/18821/coverage/diff/framework.html)

## Modules coverage

<table>
  <thead>
    <tr>
      <th></th>
      <th>7df3b0</th>
      <th colspan=4>#18821 ca38e6</th>
    </tr>
    <tr>
      <th></th>
      <th>Total</th>
      <th>Total</th>
      <th>+/-</th>
      <th>New</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><b>Rate</b></td>
      <td>86.99%</td>
      <td>86.99%</td>
      <td>-</td>
      <td>-</td>
    </tr>
    <tr>
      <td><b>Hits</b></td>
      <td>90751</td>
      <td>90751</td>
      <td>-</td>
      <td>0</td>
    </tr>
    <tr>
      <td><b>Misses</b></td>
      <td>13567</td>
      <td>13567</td>
      <td>-</td>
      <td>0</td>
    </tr>
  </tbody>
</table>

[Diff coverage report](https://mooseframework.inl.gov/docs/PRs/18821/coverage/diff/modules.html)

## Full coverage reports

<details><summary>Reports</summary>

- [framework](https://mooseframework.inl.gov/docs/PRs/18821/coverage/framework)
- [chemical_reactions](https://mooseframework.inl.gov/docs/PRs/18821/coverage/chemical_reactions)
- [combined](https://mooseframework.inl.gov/docs/PRs/18821/coverage/combined)
- [contact](https://mooseframework.inl.gov/docs/PRs/18821/coverage/contact)
- [external_petsc_solver](https://mooseframework.inl.gov/docs/PRs/18821/coverage/external_petsc_solver)
- [fluid_properties](https://mooseframework.inl.gov/docs/PRs/18821/coverage/fluid_properties)
- [fsi](https://mooseframework.inl.gov/docs/PRs/18821/coverage/fsi)
- [functional_expansion_tools](https://mooseframework.inl.gov/docs/PRs/18821/coverage/functional_expansion_tools)
- [geochemistry](https://mooseframework.inl.gov/docs/PRs/18821/coverage/geochemistry)
- [heat_conduction](https://mooseframework.inl.gov/docs/PRs/18821/coverage/heat_conduction)
- [level_set](https://mooseframework.inl.gov/docs/PRs/18821/coverage/level_set)
- [misc](https://mooseframework.inl.gov/docs/PRs/18821/coverage/misc)
- [navier_stokes](https://mooseframework.inl.gov/docs/PRs/18821/coverage/navier_stokes)
- [peridynamics](https://mooseframework.inl.gov/docs/PRs/18821/coverage/peridynamics)
- [phase_field](https://mooseframework.inl.gov/docs/PRs/18821/coverage/phase_field)
- [porous_flow](https://mooseframework.inl.gov/docs/PRs/18821/coverage/porous_flow)
- [ray_tracing](https://mooseframework.inl.gov/docs/PRs/18821/coverage/ray_tracing)
- [rdg](https://mooseframework.inl.gov/docs/PRs/18821/coverage/rdg)
- [richards](https://mooseframework.inl.gov/docs/PRs/18821/coverage/richards)
- [stochastic_tools](https://mooseframework.inl.gov/docs/PRs/18821/coverage/stochastic_tools)
- [tensor_mechanics](https://mooseframework.inl.gov/docs/PRs/18821/coverage/tensor_mechanics)
- [xfem](https://mooseframework.inl.gov/docs/PRs/18821/coverage/xfem)

</details>

This comment will be updated on new commits.

2021-09-16 04:08 UTC, cticenhour requested changes
Just a couple changes and comments.

2021-09-16 14:44 UTC, aeslaughter commented on modules/stochastic_tools/doc/content/modules/stochastic_tools/sqa/stochastic_tools_srs.md
> +STM does stuff with stuff.
```suggestion
!template load file=sqa/app_srs.md.template category=stochastic_tools app=Stochastic Tools
```

2021-09-16 14:46 UTC, aeslaughter commented on modules/stochastic_tools/doc/content/modules/stochastic_tools/sqa/stochastic_tools_srs.md
> +STM does stuff with stuff.
I will double check this behavior and fix my little test there.

2021-09-16 15:15 UTC, aeslaughter commented on modules/stochastic_tools/doc/content/modules/stochastic_tools/sqa/stochastic_tools_srs.md
> +STM does stuff with stuff.
You are correct about the behavior. That page exists for the build of the stochastic_tools site by itself, in that case those links point to the stochastic_tool versions. 

You can get to the module RTM, SRS, etc. via the list in the dependencies section of the MOOSE level documents. But, that isn't obvious so I am going to rework the template a bit to put those links up at the top.

2021-09-16 15:17 UTC, cticenhour commented on modules/stochastic_tools/doc/content/modules/stochastic_tools/sqa/stochastic_tools_srs.md
> +STM does stuff with stuff.
Sounds good - are you going to include those changes in this PR, or a follow-on?

2021-09-16 18:48 UTC, cticenhour approved these changes

2021-09-16 18:49 UTC, merged