Enforce same order/family
idaholab/moose pull request #18848
Opened 2021-09-17 23:56 UTC by dschwen

Closes #18847

The real crime here, however, seems to me is that MOOSE lets you couple a lower order AUxVariable on an higher order element and will just happily give you junk on the extra high order nodes that the low order variable has no DOFs on. 👀 

IMO this should just be a framework level error...

2021-09-18 02:03 UTC, moosebuild commented
Job [Documentation](https://civet.inl.gov/job/823219/) on 80a1337 wanted to post the following:

View the site [here](https://mooseframework.inl.gov/docs/PRs/18848/site)

This comment will be updated on new commits.

2021-09-18 02:11 UTC, moosebuild commented
Job [Generate and verify coverage](https://civet.inl.gov/job/823231/) on 80a1337 wanted to post the following:


## Framework coverage

<table>
  <thead>
    <tr>
      <th></th>
      <th>26948e</th>
      <th colspan=4>#18848 80a133</th>
    </tr>
    <tr>
      <th></th>
      <th>Total</th>
      <th>Total</th>
      <th>+/-</th>
      <th>New</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><b>Rate</b></td>
      <td>81.51%</td>
      <td>81.51%</td>
      <td>-0.00%</td>
      <td>50.00%</td>
    </tr>
    <tr>
      <td><b>Hits</b></td>
      <td>69419</td>
      <td>69419</td>
      <td>-</td>
      <td>1</td>
    </tr>
    <tr>
      <td><b>Misses</b></td>
      <td>15747</td>
      <td>15749</td>
      <td>+2</td>
      <td>1</td>
    </tr>
  </tbody>
</table>

[Diff coverage report](https://mooseframework.inl.gov/docs/PRs/18848/coverage_diff/framework.html)

## Modules coverage

<table>
  <thead>
    <tr>
      <th></th>
      <th>26948e</th>
      <th colspan=4>#18848 80a133</th>
    </tr>
    <tr>
      <th></th>
      <th>Total</th>
      <th>Total</th>
      <th>+/-</th>
      <th>New</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><b>Rate</b></td>
      <td>87.04%</td>
      <td>87.04%</td>
      <td>-</td>
      <td>-</td>
    </tr>
    <tr>
      <td><b>Hits</b></td>
      <td>91056</td>
      <td>91056</td>
      <td>-</td>
      <td>0</td>
    </tr>
    <tr>
      <td><b>Misses</b></td>
      <td>13553</td>
      <td>13553</td>
      <td>-</td>
      <td>0</td>
    </tr>
  </tbody>
</table>

[Diff coverage report](https://mooseframework.inl.gov/docs/PRs/18848/coverage_diff/modules.html)

## Full coverage reports

<details><summary>Reports</summary>

- [framework](https://mooseframework.inl.gov/docs/PRs/18848/coverage/framework)
- [chemical_reactions](https://mooseframework.inl.gov/docs/PRs/18848/coverage/chemical_reactions)
- [combined](https://mooseframework.inl.gov/docs/PRs/18848/coverage/combined)
- [contact](https://mooseframework.inl.gov/docs/PRs/18848/coverage/contact)
- [external_petsc_solver](https://mooseframework.inl.gov/docs/PRs/18848/coverage/external_petsc_solver)
- [fluid_properties](https://mooseframework.inl.gov/docs/PRs/18848/coverage/fluid_properties)
- [fsi](https://mooseframework.inl.gov/docs/PRs/18848/coverage/fsi)
- [functional_expansion_tools](https://mooseframework.inl.gov/docs/PRs/18848/coverage/functional_expansion_tools)
- [geochemistry](https://mooseframework.inl.gov/docs/PRs/18848/coverage/geochemistry)
- [heat_conduction](https://mooseframework.inl.gov/docs/PRs/18848/coverage/heat_conduction)
- [level_set](https://mooseframework.inl.gov/docs/PRs/18848/coverage/level_set)
- [misc](https://mooseframework.inl.gov/docs/PRs/18848/coverage/misc)
- [navier_stokes](https://mooseframework.inl.gov/docs/PRs/18848/coverage/navier_stokes)
- [peridynamics](https://mooseframework.inl.gov/docs/PRs/18848/coverage/peridynamics)
- [phase_field](https://mooseframework.inl.gov/docs/PRs/18848/coverage/phase_field)
- [porous_flow](https://mooseframework.inl.gov/docs/PRs/18848/coverage/porous_flow)
- [ray_tracing](https://mooseframework.inl.gov/docs/PRs/18848/coverage/ray_tracing)
- [rdg](https://mooseframework.inl.gov/docs/PRs/18848/coverage/rdg)
- [richards](https://mooseframework.inl.gov/docs/PRs/18848/coverage/richards)
- [stochastic_tools](https://mooseframework.inl.gov/docs/PRs/18848/coverage/stochastic_tools)
- [tensor_mechanics](https://mooseframework.inl.gov/docs/PRs/18848/coverage/tensor_mechanics)
- [xfem](https://mooseframework.inl.gov/docs/PRs/18848/coverage/xfem)

</details>


This comment will be updated on new commits.

2021-09-20 15:05 UTC, lindsayad approved these changes, later dismissed

2021-09-20 15:28 UTC, bwspenc requested changes, later dismissed
Looks good, but we should add a test.

2021-09-20 16:37 UTC, dschwen commented
> Looks good, but we should add a test.

Test added

2021-09-20 20:19 UTC, lindsayad approved these changes

2021-09-20 21:09 UTC, merged