Support variable coefficients in ADMatchedValueBC and MatchedValueBC
idaholab/moose pull request #19013
Opened 2021-10-05 21:58 UTC by fdkong

Closes #19012

2021-10-05 22:03 UTC, lindsayad commented
You decided not to combine them in one class?

2021-10-05 22:19 UTC, fdkong commented
> You decided not to combine them in one class?

I was too lazy. This change is good for the project at this moment.

2021-10-05 22:31 UTC, lindsayad requested changes
LGTM

2021-10-05 22:31 UTC, lindsayad commented on framework/src/bcs/MatchedValueBC.C
> +    return -1.0 * _v_coeff;
```suggestion
    return -_v_coeff;
```

2021-10-05 22:31 UTC, lindsayad commented on test/tests/interfacekernels/hybrid/tests
> +    requirement = "The system shall support interface conditions: Dirichlet and Neumann"
```suggestion
    requirement = "The system shall support Dirichlet and Neumann interface conditions."
```

2021-10-05 22:31 UTC, lindsayad commented on test/tests/interfacekernels/hybrid/tests
> +    requirement = "The system shall support interface conditions: penalty"
```suggestion
    requirement = "The system shall support penalty interface conditions."
```

2021-10-05 22:31 UTC, lindsayad commented on test/tests/interfacekernels/hybrid/tests
> +    requirement = "The system shall support matched-value interface with different variable coefficients with AD"
```suggestion
    requirement = "The system shall support matched-value interface with different variable coefficients with automatic differentiation."
```

2021-10-05 22:31 UTC, lindsayad commented on test/tests/interfacekernels/hybrid/tests
> +    requirement = "The system shall support matched-value interface with different variable coefficients"
```suggestion
    requirement = "The system shall support matched-value interface with different variable coefficients."
```

2021-10-06 00:51 UTC, moosebuild commented
Job [Generate and verify coverage](https://civet.inl.gov/job/842113/) on db43381 wanted to post the following:


## Framework coverage

<table>
  <thead>
    <tr>
      <th></th>
      <th>bf8224</th>
      <th colspan=4>#19013 db4338</th>
    </tr>
    <tr>
      <th></th>
      <th>Total</th>
      <th>Total</th>
      <th>+/-</th>
      <th>New</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><b>Rate</b></td>
      <td>81.62%</td>
      <td>81.62%</td>
      <td>+0.00%</td>
      <td>100.00%</td>
    </tr>
    <tr>
      <td><b>Hits</b></td>
      <td>69711</td>
      <td>69721</td>
      <td>+10</td>
      <td>14</td>
    </tr>
    <tr>
      <td><b>Misses</b></td>
      <td>15702</td>
      <td>15701</td>
      <td>-1</td>
      <td>0</td>
    </tr>
  </tbody>
</table>

[Diff coverage report](https://mooseframework.inl.gov/docs/PRs/19013/coverage_diff/framework.html)

[Full coverage report](https://mooseframework.inl.gov/docs/PRs/19013/coverage/framework)


## Modules coverage

Coverage did not change

## Full coverage reports

<details>
<summary>Reports</summary>

- [`framework`](https://mooseframework.inl.gov/docs/PRs/19013/coverage/framework)
- [`chemical_reactions`](https://mooseframework.inl.gov/docs/PRs/19013/coverage/chemical_reactions)
- [`combined`](https://mooseframework.inl.gov/docs/PRs/19013/coverage/combined)
- [`contact`](https://mooseframework.inl.gov/docs/PRs/19013/coverage/contact)
- [`external_petsc_solver`](https://mooseframework.inl.gov/docs/PRs/19013/coverage/external_petsc_solver)
- [`fluid_properties`](https://mooseframework.inl.gov/docs/PRs/19013/coverage/fluid_properties)
- [`fsi`](https://mooseframework.inl.gov/docs/PRs/19013/coverage/fsi)
- [`functional_expansion_tools`](https://mooseframework.inl.gov/docs/PRs/19013/coverage/functional_expansion_tools)
- [`geochemistry`](https://mooseframework.inl.gov/docs/PRs/19013/coverage/geochemistry)
- [`heat_conduction`](https://mooseframework.inl.gov/docs/PRs/19013/coverage/heat_conduction)
- [`level_set`](https://mooseframework.inl.gov/docs/PRs/19013/coverage/level_set)
- [`misc`](https://mooseframework.inl.gov/docs/PRs/19013/coverage/misc)
- [`navier_stokes`](https://mooseframework.inl.gov/docs/PRs/19013/coverage/navier_stokes)
- [`peridynamics`](https://mooseframework.inl.gov/docs/PRs/19013/coverage/peridynamics)
- [`phase_field`](https://mooseframework.inl.gov/docs/PRs/19013/coverage/phase_field)
- [`porous_flow`](https://mooseframework.inl.gov/docs/PRs/19013/coverage/porous_flow)
- [`ray_tracing`](https://mooseframework.inl.gov/docs/PRs/19013/coverage/ray_tracing)
- [`rdg`](https://mooseframework.inl.gov/docs/PRs/19013/coverage/rdg)
- [`richards`](https://mooseframework.inl.gov/docs/PRs/19013/coverage/richards)
- [`stochastic_tools`](https://mooseframework.inl.gov/docs/PRs/19013/coverage/stochastic_tools)
- [`tensor_mechanics`](https://mooseframework.inl.gov/docs/PRs/19013/coverage/tensor_mechanics)
- [`xfem`](https://mooseframework.inl.gov/docs/PRs/19013/coverage/xfem)

</details>



This comment will be updated on new commits.

2021-10-10 19:37 UTC, lindsayad approved these changes

2021-10-10 22:00 UTC, merged