Adding TrussHeatConduction and TrussHeatConductionTimeDerivative
idaholab/moose pull request #19041
Opened 2021-10-08 05:54 UTC by jain651

ref #19027

2021-10-08 06:51 UTC, moosebuild commented
Job [Documentation](https://civet.inl.gov/job/844215/) on b302eb8 wanted to post the following:

View the site [here](https://mooseframework.inl.gov/docs/PRs/19041/site)

This comment will be updated on new commits.

2021-10-12 06:47 UTC, moosebuild commented
Job [Generate and verify coverage](https://civet.inl.gov/job/846426/) on f80c63c wanted to post the following:


## Framework coverage

<table>
  <thead>
    <tr>
      <th></th>
      <th>faff97</th>
      <th colspan=4>#19041 f80c63</th>
    </tr>
    <tr>
      <th></th>
      <th>Total</th>
      <th>Total</th>
      <th>+/-</th>
      <th>New</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><b>Rate</b></td>
      <td>81.64%</td>
      <td>81.64%</td>
      <td>+0.00%</td>
      <td>-</td>
    </tr>
    <tr>
      <td><b>Hits</b></td>
      <td>69807</td>
      <td>69808</td>
      <td>+1</td>
      <td>0</td>
    </tr>
    <tr>
      <td><b>Misses</b></td>
      <td>15702</td>
      <td>15701</td>
      <td>-1</td>
      <td>0</td>
    </tr>
  </tbody>
</table>

[Diff coverage report](https://mooseframework.inl.gov/docs/PRs/19041/coverage_diff/framework.html)

[Full coverage report](https://mooseframework.inl.gov/docs/PRs/19041/coverage/framework)


## Modules coverage

### Heat conduction

<table>
  <thead>
    <tr>
      <th></th>
      <th>faff97</th>
      <th colspan=4>#19041 f80c63</th>
    </tr>
    <tr>
      <th></th>
      <th>Total</th>
      <th>Total</th>
      <th>+/-</th>
      <th>New</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><b>Rate</b></td>
      <td>87.70%</td>
      <td>87.75%</td>
      <td>+0.04%</td>
      <td>92.59%</td>
    </tr>
    <tr>
      <td><b>Hits</b></td>
      <td>2639</td>
      <td>2664</td>
      <td>+25</td>
      <td>25</td>
    </tr>
    <tr>
      <td><b>Misses</b></td>
      <td>370</td>
      <td>372</td>
      <td>+2</td>
      <td>2</td>
    </tr>
  </tbody>
</table>

[Diff coverage report](https://mooseframework.inl.gov/docs/PRs/19041/coverage_diff/heat_conduction.html)

[Full coverage report](https://mooseframework.inl.gov/docs/PRs/19041/coverage/heat_conduction)

## Full coverage reports

<details>
<summary>Reports</summary>

- [`framework`](https://mooseframework.inl.gov/docs/PRs/19041/coverage/framework)
- [`chemical_reactions`](https://mooseframework.inl.gov/docs/PRs/19041/coverage/chemical_reactions)
- [`combined`](https://mooseframework.inl.gov/docs/PRs/19041/coverage/combined)
- [`contact`](https://mooseframework.inl.gov/docs/PRs/19041/coverage/contact)
- [`external_petsc_solver`](https://mooseframework.inl.gov/docs/PRs/19041/coverage/external_petsc_solver)
- [`fluid_properties`](https://mooseframework.inl.gov/docs/PRs/19041/coverage/fluid_properties)
- [`fsi`](https://mooseframework.inl.gov/docs/PRs/19041/coverage/fsi)
- [`functional_expansion_tools`](https://mooseframework.inl.gov/docs/PRs/19041/coverage/functional_expansion_tools)
- [`geochemistry`](https://mooseframework.inl.gov/docs/PRs/19041/coverage/geochemistry)
- [`heat_conduction`](https://mooseframework.inl.gov/docs/PRs/19041/coverage/heat_conduction)
- [`level_set`](https://mooseframework.inl.gov/docs/PRs/19041/coverage/level_set)
- [`misc`](https://mooseframework.inl.gov/docs/PRs/19041/coverage/misc)
- [`navier_stokes`](https://mooseframework.inl.gov/docs/PRs/19041/coverage/navier_stokes)
- [`peridynamics`](https://mooseframework.inl.gov/docs/PRs/19041/coverage/peridynamics)
- [`phase_field`](https://mooseframework.inl.gov/docs/PRs/19041/coverage/phase_field)
- [`porous_flow`](https://mooseframework.inl.gov/docs/PRs/19041/coverage/porous_flow)
- [`ray_tracing`](https://mooseframework.inl.gov/docs/PRs/19041/coverage/ray_tracing)
- [`rdg`](https://mooseframework.inl.gov/docs/PRs/19041/coverage/rdg)
- [`richards`](https://mooseframework.inl.gov/docs/PRs/19041/coverage/richards)
- [`stochastic_tools`](https://mooseframework.inl.gov/docs/PRs/19041/coverage/stochastic_tools)
- [`tensor_mechanics`](https://mooseframework.inl.gov/docs/PRs/19041/coverage/tensor_mechanics)
- [`xfem`](https://mooseframework.inl.gov/docs/PRs/19041/coverage/xfem)

</details>



This comment will be updated on new commits.

2021-10-13 03:49 UTC, jain651 commented
Hi @dschwen, would you please merge this PR if it is ready for that?

2021-10-13 18:35 UTC, bwspenc requested changes

2021-10-18 19:22 UTC, bwspenc requested changes

2021-10-18 20:44 UTC, bwspenc approved these changes

2021-10-18 21:21 UTC, dschwen approved these changes

2021-10-18 23:05 UTC, merged