An option to use positive quadrature weights
idaholab/moose pull request #19068
Opened 2021-10-11 23:00 UTC by fdkong

Closes #19066

2021-10-11 23:54 UTC, moosebuild commented
Job [Documentation](https://civet.inl.gov/job/845862/) on a1c8fab wanted to post the following:

View the site [here](https://mooseframework.inl.gov/docs/PRs/19068/site)

This comment will be updated on new commits.

2021-10-12 00:24 UTC, lindsayad requested changes
I didn't even know this flag existed in `QBase`

2021-10-12 01:18 UTC, moosebuild commented
Job [Generate and verify coverage](https://civet.inl.gov/job/845874/) on a1c8fab wanted to post the following:


## Framework coverage

<table>
  <thead>
    <tr>
      <th></th>
      <th>2fa274</th>
      <th colspan=4>#19068 a1c8fa</th>
    </tr>
    <tr>
      <th></th>
      <th>Total</th>
      <th>Total</th>
      <th>+/-</th>
      <th>New</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><b>Rate</b></td>
      <td>81.64%</td>
      <td>81.64%</td>
      <td>+0.00%</td>
      <td>91.67%</td>
    </tr>
    <tr>
      <td><b>Hits</b></td>
      <td>69807</td>
      <td>69821</td>
      <td>+14</td>
      <td>22</td>
    </tr>
    <tr>
      <td><b>Misses</b></td>
      <td>15702</td>
      <td>15701</td>
      <td>-1</td>
      <td>2</td>
    </tr>
  </tbody>
</table>

[Diff coverage report](https://mooseframework.inl.gov/docs/PRs/19068/coverage_diff/framework.html)

[Full coverage report](https://mooseframework.inl.gov/docs/PRs/19068/coverage/framework)


## Modules coverage

Coverage did not change

## Full coverage reports

<details>
<summary>Reports</summary>

- [`framework`](https://mooseframework.inl.gov/docs/PRs/19068/coverage/framework)
- [`chemical_reactions`](https://mooseframework.inl.gov/docs/PRs/19068/coverage/chemical_reactions)
- [`combined`](https://mooseframework.inl.gov/docs/PRs/19068/coverage/combined)
- [`contact`](https://mooseframework.inl.gov/docs/PRs/19068/coverage/contact)
- [`external_petsc_solver`](https://mooseframework.inl.gov/docs/PRs/19068/coverage/external_petsc_solver)
- [`fluid_properties`](https://mooseframework.inl.gov/docs/PRs/19068/coverage/fluid_properties)
- [`fsi`](https://mooseframework.inl.gov/docs/PRs/19068/coverage/fsi)
- [`functional_expansion_tools`](https://mooseframework.inl.gov/docs/PRs/19068/coverage/functional_expansion_tools)
- [`geochemistry`](https://mooseframework.inl.gov/docs/PRs/19068/coverage/geochemistry)
- [`heat_conduction`](https://mooseframework.inl.gov/docs/PRs/19068/coverage/heat_conduction)
- [`level_set`](https://mooseframework.inl.gov/docs/PRs/19068/coverage/level_set)
- [`misc`](https://mooseframework.inl.gov/docs/PRs/19068/coverage/misc)
- [`navier_stokes`](https://mooseframework.inl.gov/docs/PRs/19068/coverage/navier_stokes)
- [`peridynamics`](https://mooseframework.inl.gov/docs/PRs/19068/coverage/peridynamics)
- [`phase_field`](https://mooseframework.inl.gov/docs/PRs/19068/coverage/phase_field)
- [`porous_flow`](https://mooseframework.inl.gov/docs/PRs/19068/coverage/porous_flow)
- [`ray_tracing`](https://mooseframework.inl.gov/docs/PRs/19068/coverage/ray_tracing)
- [`rdg`](https://mooseframework.inl.gov/docs/PRs/19068/coverage/rdg)
- [`richards`](https://mooseframework.inl.gov/docs/PRs/19068/coverage/richards)
- [`stochastic_tools`](https://mooseframework.inl.gov/docs/PRs/19068/coverage/stochastic_tools)
- [`tensor_mechanics`](https://mooseframework.inl.gov/docs/PRs/19068/coverage/tensor_mechanics)
- [`xfem`](https://mooseframework.inl.gov/docs/PRs/19068/coverage/xfem)

</details>



This comment will be updated on new commits.

2021-10-12 13:55 UTC, roystgnr submitted a review, later dismissed

2021-10-14 15:58 UTC, GiudGiud approved these changes

2021-10-14 20:40 UTC, lindsayad approved these changes

2021-10-14 20:42 UTC, merged