Add Control Drum Related Functionalities to Reactor Module #19100
idaholab/moose pull request #19102
Opened 2021-10-14 11:05 UTC by shikhar413

Closes #19100 and closes #19285

2021-10-14 13:15 UTC, miaoyinb commented
@loganharbour This is the new PR that adds the control drum related stuffs. Thanks.

PS: @shikhar413 will handle submission of this PR and future PRs of the `MOOSE Meshing Improvement project`. It would be great if he could be added to the automatic testing list.

2021-10-14 14:07 UTC, loganharbour requested changes
Here's a start. Still need to look at docs and tests.

2021-10-14 16:43 UTC, GiudGiud requested changes

2021-10-16 15:23 UTC, moosebuild commented
Job [Generate and verify coverage](https://civet.inl.gov/job/852989/) on da7a449 wanted to post the following:


The following coverage requirement(s) failed:
- Failed to generate `framework` coverage rate (required: 81.0%)

2021-10-21 17:58 UTC, GiudGiud requested changes
Can you please add to moose/modules/doc/content/citing.md for the reactor module?

2021-10-23 17:13 UTC, GiudGiud submitted a review, later dismissed
In the future when renaming an object / a file, please consider using `git mv` as this reduces the size of the diffs.
Nbd here since the renamed file is really tiny. 
@loganharbour want to have a second look?

2021-10-27 01:07 UTC, loganharbour submitted a review, later dismissed

2021-10-27 13:59 UTC, loganharbour requested changes
I missed one last thing - can you please move the image content into the `large_media` submodule? Feel free to contact me on Slack or over e-mail if you need assistance with this.

I'm looking into the distributed mesh implementation right now.

2021-11-01 14:37 UTC, miaoyinb commented
@loganharbour Please let us know if anything needs to be done on our side to solve the conflicts issue. Thanks.

2021-11-01 23:29 UTC, moosebuild commented on large_media
> +Subproject commit 81c4f06ef21e246843f34e7d4ee745b586d98d5f
**Caution!** This contains a submodule update

2021-11-03 05:02 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/872723/) on b2ecaab wanted to post the following:

Your code requires style changes.  

A patch was auto generated and copied [here](https://mooseframework.inl.gov/docs/PRs/19102/style.patch)  
You can directly apply the patch by running, in the top level of your repository:

`curl -s https://mooseframework.inl.gov/docs/PRs/19102/style.patch | git apply -v`  

Alternatively, with your repository up to date and in the top level of your repository:

`git clang-format cb148e86ddf764a74f1d8d94e014a8d3f2f61bd6`

2021-11-03 05:02 UTC, moosebuild commented on large_media
> +Subproject commit 81c4f06ef21e246843f34e7d4ee745b586d98d5f
**Caution!** This contains a submodule update

2021-11-03 05:06 UTC, loganharbour commented
@miaoyinb Replicated mesh requirements are in place. I did a lot of cleanup in 10426e8 and ca52a82. Please take a look when you have a change. I think I figured out the distributed issue.

@shikhar413 I'm getting there :-)

2021-11-03 05:06 UTC, moosebuild commented on large_media
> +Subproject commit 81c4f06ef21e246843f34e7d4ee745b586d98d5f
**Caution!** This contains a submodule update

2021-11-03 05:27 UTC, moosebuild commented on large_media
> +Subproject commit 81c4f06ef21e246843f34e7d4ee745b586d98d5f
**Caution!** This contains a submodule update

2021-11-03 13:39 UTC, miaoyinb commented
> @miaoyinb Replicated mesh requirements are in place. I did a lot of cleanup in [10426e8](https://github.com/idaholab/moose/commit/10426e8a6f86f638c49de5df336ef8f3df11522f) and [ca52a82](https://github.com/idaholab/moose/commit/ca52a826d94dd87819f4c862ae452c7e82bd3251). I removed the passing of the current node ID in most of the generation in the polygon generator because it was redundant (libmesh will keep track of this); I can add this back if needed. Let me know. Please take a look when you have a chance. I think I figured out the distributed issue.
> 
> @shikhar413 I'm getting there :-)

Thanks a lot @loganharbour. I will take a look,

2021-11-03 17:54 UTC, miaoyinb commented
@loganharbour Thank you so much for the cleanup work 👍 and figuring out the distributed issue. It looks great now. I will also apply the approaches you used to my future codes. Let us know if anything else needs to be done by us before moving forward. Thanks again.

2021-11-09 14:47 UTC, loganharbour commented
I'm going to defer the distributed recover issue for `HexagonConcentricCircleAdaptiveBoundaryMeshGenerator`. It's driving me into the wall, and I don't want to hold this back anymore. Skipping is okay for now.

blue_crab patch is almost done for the changes I made to mesh generators.

2021-11-09 14:47 UTC, loganharbour approved these changes, later dismissed
Approving content that is not my own.

2021-11-09 14:53 UTC, miaoyinb commented
> I'm going to defer the distributed recover issue for `HexagonConcentricCircleAdaptiveBoundaryMeshGenerator`. It's driving me into the wall, and I don't want to hold this back anymore. Skipping is okay for now.
> 
> blue_crab patch is almost done for the changes I made to mesh generators.

Thank you, @loganharbour

2021-11-09 15:38 UTC, GiudGiud commented on modules/reactor/include/meshgenerators/PolygonMeshGeneratorBase.h
> +   * layers
??

2021-11-09 15:43 UTC, loganharbour commented on modules/reactor/include/meshgenerators/PolygonMeshGeneratorBase.h
> +   * layers
grep has failed me

2021-11-09 15:53 UTC, loganharbour commented on modules/reactor/include/meshgenerators/PolygonMeshGeneratorBase.h
> +   * layers
```suggestion
   * @param subdomain_rings numbers of radial intervals of all involved subdomain layers
```

2021-11-09 15:55 UTC, miaoyinb commented on modules/reactor/include/meshgenerators/PolygonMeshGeneratorBase.h
> +   * @param pitch pitch size of the involbuildPeripheralMeshhexagon mesh
seems to be another one.

2021-11-09 15:56 UTC, moosebuild commented on large_media
> +Subproject commit 81c4f06ef21e246843f34e7d4ee745b586d98d5f
**Caution!** This contains a submodule update

2021-11-09 16:05 UTC, loganharbour commented on modules/reactor/include/meshgenerators/PolygonMeshGeneratorBase.h
> +   * @param pitch pitch size of the involbuildPeripheralMeshhexagon mesh
```suggestion
   * @param pitch pitch size of the involved hexagon mesh
```

2021-11-09 16:07 UTC, moosebuild commented on large_media
> +Subproject commit 81c4f06ef21e246843f34e7d4ee745b586d98d5f
**Caution!** This contains a submodule update

2021-11-09 16:13 UTC, GiudGiud commented on modules/reactor/src/meshgenerators/PolygonMeshGeneratorBase.C
> +  Real bin_radial_distance;
do you need this declared ahead of time

2021-11-09 16:25 UTC, GiudGiud approved these changes

2021-11-09 16:27 UTC, moosebuild commented on large_media
> +Subproject commit 81c4f06ef21e246843f34e7d4ee745b586d98d5f
**Caution!** This contains a submodule update

2021-11-10 03:33 UTC, merged

2021-11-10 13:55 UTC, miaoyinb commented
@GiudGiud @loganharbour Thank you so much for your review and help on this PR!