Adding documentation pages to SQA for the github backup processes for MOOSE and assorted MOOSE apps
idaholab/moose pull request #19158
Opened 2021-10-20 17:10 UTC by socratesgorilla

Closes  #19252

2021-11-01 18:38 UTC, permcody requested changes
Getting very close - Let's address the last few comments I've given and then we can get this merged and get the associated Labway issue closed (currently due 11/5). I'd rather not extend it again - Thanks!

2021-11-01 18:38 UTC, permcody commented on modules/doc/content/sqa/index.md
> +
Let's move this up above the Table and make a heading for it. I had to look at the source before I finally found the location of this link. It's pretty buried sitting underneath the table. If you haven't looked at the rendered version of your site. Go back to the PR "Conversation" page an look for the MooseBuild comment. It'll post the link to the rendered version of your page so you can see what it looks like.

2021-11-01 18:38 UTC, permcody commented on modules/doc/content/sqa/github_backup.md
> +The issues/PRs backup is accomplished by hitting the Github API for a JSON file of the issues, using internal Python tools to parse the JSON into a dictionary, then dumping the dictionary into a csv
- Let's go ahead and turn the embedded link into a link (look at the guide for how to do that in Markdown). 
- Also, let's make sure we actually list the internal location of the backups right on this page. Auditors won't consider this as a pass until we either point to a document that mentions to the location, or we point directly to the location. As it stands, an auditor would have to find an human (expert) to find the actual files.

2021-11-02 06:36 UTC, GiudGiud commented on modules/doc/content/sqa/github_backup.md
> +The issues/PRs backup is accomplished by hitting the Github API for a JSON file of the issues, using internal Python tools to parse the JSON into a dictionary, then dumping the dictionary into a csv
We strongly recommend against
is not recommended 
is not desirable
all work better

I feel like all these parsers would be written by us if it came down to it. We shouldn't say we will lose everything if we ever need to use that backup

2021-11-03 20:37 UTC, moosebuild commented
Job [End User Experience (CentOS 8)](https://civet.inl.gov/job/873351/) on d541f73 : invalidated by @socratesgorilla

2021-11-03 21:18 UTC, permcody approved these changes
Looks good - Thanks!

2021-11-04 18:47 UTC, merged