Remove support for PETSc < 3.5
idaholab/moose pull request #19197
Opened 2021-10-25 15:39 UTC by dschwen

Closes #19195

2021-10-25 16:58 UTC, fdkong approved these changes

2021-10-25 17:02 UTC, cticenhour requested changes
Please modify affected `petsc_version` parameters in tests to be `>= 3.5.0` where applicable as well. I see only a few with a quick search.

2021-10-25 17:40 UTC, fdkong requested changes
We have something like this in Moose.h

```
#ifndef LIBMESH_HAVE_PETSC
#error PETSc has not been detected, please ensure your environment is set up properly then rerun the libmesh build script and try to compile MOOSE again.
#endif
```

I think we should add a similar thing for this change as well:


```
#if PETSC_VERSION_LESS_THAN(3, 5, 0)
#error PETSc-3.5.x or newer is required, please ensure your environment have the required version of PETSc
#endif 
```

2021-10-26 15:33 UTC, cticenhour approved these changes
My comments were addressed. @fdkong, do you have any more?

2021-10-26 18:03 UTC, fdkong approved these changes

2021-10-26 18:05 UTC, merged