Add 3D mortar mechanical contact to action
idaholab/moose pull request #19211
Opened 2021-10-26 17:51 UTC by recuero

Add 3D mortar mechanical contact to the action to allow users to experiment.

Refs.  #13080

2021-10-26 18:06 UTC, dschwen submitted a review, later dismissed
Looks fine to me

2021-10-26 20:14 UTC, dschwen submitted a review, later dismissed

2021-10-27 20:40 UTC, dschwen submitted a review, later dismissed

2021-10-28 22:00 UTC, bwspenc requested changes

2021-10-31 18:30 UTC, dschwen commented on modules/contact/include/actions/ContactAction.h
> +  bool _correct_edge_dropping;
This should be made const at some point, but the action needs cleanup to remove old contact options anyways.

2021-11-03 16:59 UTC, bwspenc approved these changes
Looks good -- thanks for addressing my concerns!

2021-11-03 17:06 UTC, merged