Update libMesh to a version with ExodusII IsoGeometric Analysis support
idaholab/moose pull request #19222
Opened 2021-10-27 15:19 UTC by roystgnr

Summary of changes:

  - Tri7 and Tet14 element support
  - Reduced Basis EIM updates
  - SIDE_HIERARCHIC FE support on triangles
  - LOG_CALL() macro
  - Refactored FE derivatives FDM fallback
  - ExodusII_IO::get_sideset_data_indices() accessor
  - Fix file leak/error with some ExodusII version 8 use cases
  - ExodusII IsoGeometric Analysis file support
  - Bug fixes for distcheck, clang warnings, non-double FP,
    Elem::permute(), etc.

Refs #0

Refs #18768 - this brings in read support for Exodus IGA files

Marking this as Do Not Merge at first, since there's a chance I'll want to slip in another libMesh PR first, but I'd like to at least make sure that CI here doesn't have any problem with the changes so far.

2021-10-27 17:22 UTC, loganharbour submitted a review, later dismissed
Add to newsletter

2021-10-28 19:08 UTC, cticenhour requested changes
Looks good at first glance, only one comment. I'll take another look later at how the newsletter bit renders.

2021-10-29 20:16 UTC, moosebuild commented
All [jobs](https://civet.inl.gov/event/78176/) on ca4ff5e : invalidated by @cticenhour

Testing not triggered for some reason

2021-10-29 20:18 UTC, moosebuild commented on libmesh
> +Subproject commit c3a9eae9c19b69f9e96df2d04036e22209218f89
**Caution!** This contains a submodule update

2021-10-30 18:31 UTC, moosebuild commented on libmesh
> +Subproject commit c3a9eae9c19b69f9e96df2d04036e22209218f89
**Caution!** This contains a submodule update

2021-10-31 04:27 UTC, moosebuild commented
Job [Valgrind electromagnetics](https://civet.inl.gov/job/865873/) on ca4ff5e : invalidated by @cticenhour

Invalidating due to updated recipe. EM module doesn&#39;&#39;t yet exist.

2021-10-31 04:29 UTC, cticenhour approved these changes

2021-10-31 04:30 UTC, merged