clarify tests requirements closes #19261
idaholab/moose pull request #19262
Opened 2021-10-29 20:01 UTC by lynnmunday

closes #19261

2021-10-29 22:53 UTC, moosebuild commented
Job [Documentation](https://civet.inl.gov/job/868786/) on aec185b wanted to post the following:

View the site [here](https://mooseframework.inl.gov/docs/PRs/19262/site)

This comment will be updated on new commits.

2021-10-30 01:20 UTC, moosebuild commented
Job [Coverage](https://civet.inl.gov/job/868796/) on aec185b wanted to post the following:


## Framework coverage

<table>
  <thead>
    <tr>
      <th></th>
      <th>f70f24</th>
      <th colspan=4>#19262 aec185</th>
    </tr>
    <tr>
      <th></th>
      <th>Total</th>
      <th>Total</th>
      <th>+/-</th>
      <th>New</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><b>Rate</b></td>
      <td>81.80%</td>
      <td>81.80%</td>
      <td>+0.00%</td>
      <td>-</td>
    </tr>
    <tr>
      <td><b>Hits</b></td>
      <td>71503</td>
      <td>71504</td>
      <td>+1</td>
      <td>0</td>
    </tr>
    <tr>
      <td><b>Misses</b></td>
      <td>15914</td>
      <td>15913</td>
      <td>-1</td>
      <td>0</td>
    </tr>
  </tbody>
</table>

[Diff coverage report](https://mooseframework.inl.gov/docs/PRs/19262/coverage_diff/framework.html)

[Full coverage report](https://mooseframework.inl.gov/docs/PRs/19262/coverage/framework)


## Modules coverage

Coverage did not change

## Full coverage reports

<details>
<summary>Reports</summary>

- [`framework`](https://mooseframework.inl.gov/docs/PRs/19262/coverage/framework)
- [`chemical_reactions`](https://mooseframework.inl.gov/docs/PRs/19262/coverage/chemical_reactions)
- [`combined`](https://mooseframework.inl.gov/docs/PRs/19262/coverage/combined)
- [`contact`](https://mooseframework.inl.gov/docs/PRs/19262/coverage/contact)
- [`external_petsc_solver`](https://mooseframework.inl.gov/docs/PRs/19262/coverage/external_petsc_solver)
- [`fluid_properties`](https://mooseframework.inl.gov/docs/PRs/19262/coverage/fluid_properties)
- [`fsi`](https://mooseframework.inl.gov/docs/PRs/19262/coverage/fsi)
- [`functional_expansion_tools`](https://mooseframework.inl.gov/docs/PRs/19262/coverage/functional_expansion_tools)
- [`geochemistry`](https://mooseframework.inl.gov/docs/PRs/19262/coverage/geochemistry)
- [`heat_conduction`](https://mooseframework.inl.gov/docs/PRs/19262/coverage/heat_conduction)
- [`level_set`](https://mooseframework.inl.gov/docs/PRs/19262/coverage/level_set)
- [`misc`](https://mooseframework.inl.gov/docs/PRs/19262/coverage/misc)
- [`navier_stokes`](https://mooseframework.inl.gov/docs/PRs/19262/coverage/navier_stokes)
- [`peridynamics`](https://mooseframework.inl.gov/docs/PRs/19262/coverage/peridynamics)
- [`phase_field`](https://mooseframework.inl.gov/docs/PRs/19262/coverage/phase_field)
- [`porous_flow`](https://mooseframework.inl.gov/docs/PRs/19262/coverage/porous_flow)
- [`ray_tracing`](https://mooseframework.inl.gov/docs/PRs/19262/coverage/ray_tracing)
- [`rdg`](https://mooseframework.inl.gov/docs/PRs/19262/coverage/rdg)
- [`reactor`](https://mooseframework.inl.gov/docs/PRs/19262/coverage/reactor)
- [`richards`](https://mooseframework.inl.gov/docs/PRs/19262/coverage/richards)
- [`stochastic_tools`](https://mooseframework.inl.gov/docs/PRs/19262/coverage/stochastic_tools)
- [`tensor_mechanics`](https://mooseframework.inl.gov/docs/PRs/19262/coverage/tensor_mechanics)
- [`xfem`](https://mooseframework.inl.gov/docs/PRs/19262/coverage/xfem)

</details>



This comment will be updated on new commits.

2021-10-30 02:02 UTC, lynnmunday commented
@fdkong will you review

2021-10-30 02:29 UTC, fdkong submitted a review, later dismissed

2021-10-30 02:40 UTC, YaqiWang commented
What is that `iThe`?

2021-10-30 23:25 UTC, loganharbour requested changes

2021-10-30 23:25 UTC, loganharbour commented on test/tests/misc/petsc_option_left/tests
> +    requirement = "iThe system shall use the default PETSc option database in the master app to handle system-level PETSc parameters, such as '-log_view.' "
```suggestion
    requirement = "The system shall use the default PETSc option database in the master app to handle system-level PETSc parameters"
```

Extra detail is unnecessary for requirements. Also removes the extraneous i

2021-11-01 14:48 UTC, lynnmunday commented
thanks, I used @loganharbour commit.

2021-11-01 14:49 UTC, loganharbour approved these changes

2021-11-01 22:32 UTC, merged