Parallel Subset Simulation sampler for failure evaluation and optimization
idaholab/moose pull request #19399
Opened 2021-11-15 21:59 UTC by somu15

## Reason
Create an adaptive Monte Carlo sampler class `ParallelSubsetSimulation` to efficiently estimate probabilistic failure of expensive FE models and conduct optimization under uncertainty studies.

## Design
`ParallelSubsetSimulation` sampler class will be created in stochastic tools. In addition, `AdaptiveMonteCarloDecision` and `AdaptiveMonteCarloUtils` classes will be modified to accommodate `ParallelSubsetSimulation`. Corresponding docs and tests will also be created.

## Impact
This development of the above class should not impact the behavior of existing objects.

Closes #19398

2021-11-15 22:02 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/890643/) on 0a728a2 wanted to post the following:

Your code requires style changes.  

A patch was auto generated and copied [here](https://mooseframework.inl.gov/docs/PRs/19399/style.patch)  
You can directly apply the patch by running, in the top level of your repository:

`curl -s https://mooseframework.inl.gov/docs/PRs/19399/style.patch | git apply -v`  

Alternatively, with your repository up to date and in the top level of your repository:

`git clang-format d3e57ccfba29379e643967ccc89b637b34007001`

2021-11-15 23:33 UTC, moosebuild commented
Job [Documentation](https://civet.inl.gov/job/890750/) on 9055d0c wanted to post the following:

View the site [here](https://mooseframework.inl.gov/docs/PRs/19399/site)

This comment will be updated on new commits.

2021-11-16 00:59 UTC, moosebuild commented
Job [Coverage](https://civet.inl.gov/job/890777/) on 9055d0c wanted to post the following:


## Framework coverage

Coverage did not change


## Modules coverage

### Stochastic tools

<table>
  <thead>
    <tr>
      <th></th>
      <th>d3e57c</th>
      <th colspan=4>#19399 9055d0</th>
    </tr>
    <tr>
      <th></th>
      <th>Total</th>
      <th>Total</th>
      <th>+/-</th>
      <th>New</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><b>Rate</b></td>
      <td>89.15%</td>
      <td>89.60%</td>
      <td>+0.45%</td>
      <td>99.15%</td>
    </tr>
    <tr>
      <td><b>Hits</b></td>
      <td>4159</td>
      <td>4378</td>
      <td>+219</td>
      <td>232</td>
    </tr>
    <tr>
      <td><b>Misses</b></td>
      <td>506</td>
      <td>508</td>
      <td>+2</td>
      <td>2</td>
    </tr>
  </tbody>
</table>

[Diff coverage report](https://mooseframework.inl.gov/docs/PRs/19399/coverage_diff/stochastic_tools.html)

[Full coverage report](https://mooseframework.inl.gov/docs/PRs/19399/coverage/stochastic_tools)

## Full coverage reports

<details>
<summary>Reports</summary>

- [`framework`](https://mooseframework.inl.gov/docs/PRs/19399/coverage/framework)
- [`chemical_reactions`](https://mooseframework.inl.gov/docs/PRs/19399/coverage/chemical_reactions)
- [`combined`](https://mooseframework.inl.gov/docs/PRs/19399/coverage/combined)
- [`contact`](https://mooseframework.inl.gov/docs/PRs/19399/coverage/contact)
- [`external_petsc_solver`](https://mooseframework.inl.gov/docs/PRs/19399/coverage/external_petsc_solver)
- [`fluid_properties`](https://mooseframework.inl.gov/docs/PRs/19399/coverage/fluid_properties)
- [`fsi`](https://mooseframework.inl.gov/docs/PRs/19399/coverage/fsi)
- [`functional_expansion_tools`](https://mooseframework.inl.gov/docs/PRs/19399/coverage/functional_expansion_tools)
- [`geochemistry`](https://mooseframework.inl.gov/docs/PRs/19399/coverage/geochemistry)
- [`heat_conduction`](https://mooseframework.inl.gov/docs/PRs/19399/coverage/heat_conduction)
- [`level_set`](https://mooseframework.inl.gov/docs/PRs/19399/coverage/level_set)
- [`misc`](https://mooseframework.inl.gov/docs/PRs/19399/coverage/misc)
- [`navier_stokes`](https://mooseframework.inl.gov/docs/PRs/19399/coverage/navier_stokes)
- [`peridynamics`](https://mooseframework.inl.gov/docs/PRs/19399/coverage/peridynamics)
- [`phase_field`](https://mooseframework.inl.gov/docs/PRs/19399/coverage/phase_field)
- [`porous_flow`](https://mooseframework.inl.gov/docs/PRs/19399/coverage/porous_flow)
- [`ray_tracing`](https://mooseframework.inl.gov/docs/PRs/19399/coverage/ray_tracing)
- [`rdg`](https://mooseframework.inl.gov/docs/PRs/19399/coverage/rdg)
- [`reactor`](https://mooseframework.inl.gov/docs/PRs/19399/coverage/reactor)
- [`richards`](https://mooseframework.inl.gov/docs/PRs/19399/coverage/richards)
- [`stochastic_tools`](https://mooseframework.inl.gov/docs/PRs/19399/coverage/stochastic_tools)
- [`tensor_mechanics`](https://mooseframework.inl.gov/docs/PRs/19399/coverage/tensor_mechanics)
- [`xfem`](https://mooseframework.inl.gov/docs/PRs/19399/coverage/xfem)

</details>



This comment will be updated on new commits.

2021-11-16 15:50 UTC, somu15 commented
Not sure why `test:finite_volume/wcns/materials.transient` is exodiffing.

2021-11-16 15:58 UTC, moosebuild commented
Job [Modules Parallel PETSc Alt](https://civet.inl.gov/job/890764/) on 9055d0c : invalidated by @loganharbour

Fix to failure is in devel

2021-11-23 18:05 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/899463/) on 8367fab wanted to post the following:

Your code requires style changes.  

A patch was auto generated and copied [here](https://mooseframework.inl.gov/docs/PRs/19399/style.patch)  
You can directly apply the patch by running, in the top level of your repository:

`curl -s https://mooseframework.inl.gov/docs/PRs/19399/style.patch | git apply -v`  

Alternatively, with your repository up to date and in the top level of your repository:

`git clang-format f2f4113880736a8ce6dc2289d54efc4bf01a74a3`

2021-12-16 18:21 UTC, grmnptr commented
Do you mind if I also review this one? I am interested in the technique and would love to learn about the implementation.

2021-12-16 18:59 UTC, zachmprince commented
@grmnptr I wouldn't review it right now. I gave some changes to Som and he is still trying to make sure it didn't break anything. It would be great to get your input though!

2021-12-16 19:44 UTC, somu15 commented
@zachmprince sorry I couldn't test it on Triso this week. I will work on this next week.

2022-03-10 16:04 UTC, grmnptr requested changes
Very nice piece of work! I added a few minor suggestions/comments, just in case.

2022-03-18 20:21 UTC, somu15 commented on modules/stochastic_tools/src/samplers/ParallelSubsetSimulation.C
> +  params.addRangeCheckedParam<Real>("subset_probability",
This param is range checked. So, it's automatically tested right?

2022-03-18 20:22 UTC, somu15 commented on modules/stochastic_tools/doc/content/source/samplers/ParallelSubsetSimulation.md
> +# Parallel Subset Simulation (PSS)
Yes, this is a great idea! Right now, this class is described as being used for failure analysis and stochastic optimization. We are using it for stochastic optimization for a different numerical model. But yes, this sampler is a variance reduction method.

2022-03-18 20:23 UTC, somu15 commented on modules/stochastic_tools/src/reporters/AdaptiveMonteCarloDecision.C
> +  if (!_ais && !_pss)
Done!

2022-03-18 20:25 UTC, somu15 commented on modules/stochastic_tools/src/utils/AdaptiveMonteCarloUtils.C
>    }
Yes, as you mentioned, practically, there wouldn't be much difference between N and N-1. Unless, the user request very few samples per subset, like 10.

2022-03-22 17:56 UTC, zachmprince approved these changes

2022-03-22 18:32 UTC, merged