Function layered integral
idaholab/moose pull request #19479
Opened 2021-11-24 20:25 UTC by aprilnovak

Adds a `FunctionLayeredIntegral`, basically the same as `LayeredIntegral` except that it integrates a function instead of a variable. Needed for setting fluid temperature ICs in Cardinal based on bulk energy conservation.

Closes #19478

2021-11-24 20:27 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/900208/) on 16f4861 wanted to post the following:

Your code requires style changes.  

A patch was auto generated and copied [here](https://mooseframework.inl.gov/docs/PRs/19479/style.patch)  
You can directly apply the patch by running, in the top level of your repository:

`curl -s https://mooseframework.inl.gov/docs/PRs/19479/style.patch | git apply -v`  

Alternatively, with your repository up to date and in the top level of your repository:

`git clang-format eb93d4f097cb9a8d194f839ecfd7d5d3724f206b`

2021-11-24 21:42 UTC, moosebuild commented
Job [Documentation](https://civet.inl.gov/job/900240/) on 3d91eaf wanted to post the following:

View the site [here](https://mooseframework.inl.gov/docs/PRs/19479/site)

This comment will be updated on new commits.

2021-11-24 23:16 UTC, moosebuild commented
Job [Coverage](https://civet.inl.gov/job/900267/) on 3d91eaf wanted to post the following:


## Framework coverage

<table>
  <thead>
    <tr>
      <th></th>
      <th>eb93d4</th>
      <th colspan=4>#19479 3d91ea</th>
    </tr>
    <tr>
      <th></th>
      <th>Total</th>
      <th>Total</th>
      <th>+/-</th>
      <th>New</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><b>Rate</b></td>
      <td>82.02%</td>
      <td>82.03%</td>
      <td>+0.01%</td>
      <td>100.00%</td>
    </tr>
    <tr>
      <td><b>Hits</b></td>
      <td>72438</td>
      <td>72483</td>
      <td>+45</td>
      <td>45</td>
    </tr>
    <tr>
      <td><b>Misses</b></td>
      <td>15875</td>
      <td>15875</td>
      <td>-</td>
      <td>0</td>
    </tr>
  </tbody>
</table>

[Diff coverage report](https://mooseframework.inl.gov/docs/PRs/19479/coverage_diff/framework.html)

[Full coverage report](https://mooseframework.inl.gov/docs/PRs/19479/coverage/framework)


## Modules coverage

Coverage did not change

## Full coverage reports

<details>
<summary>Reports</summary>

- [`framework`](https://mooseframework.inl.gov/docs/PRs/19479/coverage/framework)
- [`chemical_reactions`](https://mooseframework.inl.gov/docs/PRs/19479/coverage/chemical_reactions)
- [`combined`](https://mooseframework.inl.gov/docs/PRs/19479/coverage/combined)
- [`contact`](https://mooseframework.inl.gov/docs/PRs/19479/coverage/contact)
- [`external_petsc_solver`](https://mooseframework.inl.gov/docs/PRs/19479/coverage/external_petsc_solver)
- [`fluid_properties`](https://mooseframework.inl.gov/docs/PRs/19479/coverage/fluid_properties)
- [`fsi`](https://mooseframework.inl.gov/docs/PRs/19479/coverage/fsi)
- [`functional_expansion_tools`](https://mooseframework.inl.gov/docs/PRs/19479/coverage/functional_expansion_tools)
- [`geochemistry`](https://mooseframework.inl.gov/docs/PRs/19479/coverage/geochemistry)
- [`heat_conduction`](https://mooseframework.inl.gov/docs/PRs/19479/coverage/heat_conduction)
- [`level_set`](https://mooseframework.inl.gov/docs/PRs/19479/coverage/level_set)
- [`misc`](https://mooseframework.inl.gov/docs/PRs/19479/coverage/misc)
- [`navier_stokes`](https://mooseframework.inl.gov/docs/PRs/19479/coverage/navier_stokes)
- [`peridynamics`](https://mooseframework.inl.gov/docs/PRs/19479/coverage/peridynamics)
- [`phase_field`](https://mooseframework.inl.gov/docs/PRs/19479/coverage/phase_field)
- [`porous_flow`](https://mooseframework.inl.gov/docs/PRs/19479/coverage/porous_flow)
- [`ray_tracing`](https://mooseframework.inl.gov/docs/PRs/19479/coverage/ray_tracing)
- [`rdg`](https://mooseframework.inl.gov/docs/PRs/19479/coverage/rdg)
- [`reactor`](https://mooseframework.inl.gov/docs/PRs/19479/coverage/reactor)
- [`richards`](https://mooseframework.inl.gov/docs/PRs/19479/coverage/richards)
- [`stochastic_tools`](https://mooseframework.inl.gov/docs/PRs/19479/coverage/stochastic_tools)
- [`tensor_mechanics`](https://mooseframework.inl.gov/docs/PRs/19479/coverage/tensor_mechanics)
- [`xfem`](https://mooseframework.inl.gov/docs/PRs/19479/coverage/xfem)

</details>



This comment will be updated on new commits.

2021-11-25 00:37 UTC, GiudGiud commented on framework/include/userobject/FunctionElementIntegralUserObject.h
> +InputParameters validParams<FunctionElementIntegralUserObject>();
let s no re-introduce this and use the new way for validparams

2021-11-25 00:43 UTC, GiudGiud commented
@lindsayad should we make a FunctorLayeredIntegral ?
@aprilnovak how s your timeline on this? Functors include functions, material properties and variables, so the more general interface should do what you need too

2021-11-29 16:35 UTC, aprilnovak commented
I need this feature soon. I don't know what functors are, so can't really comment on that. If someone could throw together/explain how to make a `FunctionLayeredIntegral` that does the same thing, that'd work for me.

2021-11-29 18:24 UTC, lindsayad commented
> @lindsayad should we make a FunctorLayeredIntegral ?

Perhaps so. It would have made @aprilnovak's reimplementation here for functions unnecessary. However, since if we used the functor system with a function we would have to reinit an FE object with the qrule in order to get the quad points, when that is already done in the `ComputeUserObjectsThread` loop, it probably makes sense to keep what @aprilnovak has done here because it will be faster.

2021-12-05 04:34 UTC, GiudGiud requested changes

2021-12-05 04:34 UTC, GiudGiud commented on framework/include/userobject/FunctionElementIntegralUserObject.h
> +class FunctionElementIntegralUserObject;
```suggestion
```
was for legacy params

2021-12-05 04:34 UTC, GiudGiud commented on framework/include/userobject/FunctionElementIntegralUserObject.h
> + * This postprocessor computes a volume integral of a specified function.
```suggestion
 * This user object computes a volume integral of a specified function.
```

2021-12-05 04:34 UTC, GiudGiud commented on framework/src/userobject/FunctionElementIntegralUserObject.C
> +defineLegacyParams(FunctionElementIntegralUserObject);
```suggestion
```

2021-12-05 04:34 UTC, GiudGiud commented on framework/src/userobject/FunctionLayeredIntegral.C
> +defineLegacyParams(FunctionLayeredIntegral);
```suggestion
```

2021-12-05 04:34 UTC, GiudGiud commented on test/tests/userobjects/function_layered_integral/tests
> +    requirement = 'The system shall integrate a function in layers'
```suggestion
    requirement = 'The system shall be able to integrate a function over layers'
```

2021-12-06 17:39 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/908730/) on 20c0d28 wanted to post the following:

Your code requires style changes.  

A patch was auto generated and copied [here](https://mooseframework.inl.gov/docs/PRs/19479/style.patch)  
You can directly apply the patch by running, in the top level of your repository:

`curl -s https://mooseframework.inl.gov/docs/PRs/19479/style.patch | git apply -v`  

Alternatively, with your repository up to date and in the top level of your repository:

`git clang-format fd823f7b25148d6a6482edf54a6101beee358e73`

2021-12-07 00:05 UTC, GiudGiud approved these changes

2021-12-07 00:05 UTC, merged