Add magnitude and function name interfaces. Refs #19555
idaholab/moose pull request #19556
Opened 2021-12-06 18:22 UTC by aprilnovak

Adds necessary APIs for Cardinal to set up these ICs automatically, with a subsequent IC that depends on the function provided to the `IntegralPreservingFunctionIC`.

Closes #19555

2021-12-06 18:49 UTC, loganharbour requested changes

2021-12-06 18:49 UTC, loganharbour commented on framework/include/ics/FunctionIC.h
> +  const FunctionName & functionName() const { return _function_name; }
No need to store `_function_name`, remove that member and just do

```
const FunctionName &
FunctionIC::functionName() const
{
  return _func.name();
}
```

in source

2021-12-06 19:37 UTC, loganharbour reviewed
You need to do it in the source.

`Function` isn't included in the header, it's just forward declared

2021-12-06 19:50 UTC, aprilnovak commented
> You need to do it in the source.

Will it fail a non-unity build, you mean? Because it does compile as-in in the header

2021-12-06 19:58 UTC, loganharbour commented
> > You need to do it in the source.
> 
> Will it fail a non-unity build, you mean? Because it does compile as-in in the header

Correct.

2021-12-06 20:07 UTC, loganharbour requested changes
Sorry wasn't very thorough the first time around. Good after this

2021-12-06 20:07 UTC, loganharbour commented on framework/include/ics/FunctionIC.h
> +   * @return function name
```suggestion
   * @returns The function name
```

2021-12-06 20:13 UTC, aprilnovak commented
Thanks for the quick review!

2021-12-06 21:38 UTC, moosebuild commented
Job [Documentation](https://civet.inl.gov/job/909231/) on 1b6ebba wanted to post the following:

View the site [here](https://mooseframework.inl.gov/docs/PRs/19556/site)

This comment will be updated on new commits.

2021-12-06 23:14 UTC, moosebuild commented
Job [Coverage](https://civet.inl.gov/job/909241/) on 1b6ebba wanted to post the following:


## Framework coverage

<table>
  <thead>
    <tr>
      <th></th>
      <th>fd823f</th>
      <th colspan=4>#19556 1b6ebb</th>
    </tr>
    <tr>
      <th></th>
      <th>Total</th>
      <th>Total</th>
      <th>+/-</th>
      <th>New</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><b>Rate</b></td>
      <td>82.09%</td>
      <td>82.09%</td>
      <td>-0.00%</td>
      <td>50.00%</td>
    </tr>
    <tr>
      <td><b>Hits</b></td>
      <td>72658</td>
      <td>72660</td>
      <td>+2</td>
      <td>2</td>
    </tr>
    <tr>
      <td><b>Misses</b></td>
      <td>15848</td>
      <td>15849</td>
      <td>+1</td>
      <td>2</td>
    </tr>
  </tbody>
</table>

[Diff coverage report](https://mooseframework.inl.gov/docs/PRs/19556/coverage_diff/framework.html)

[Full coverage report](https://mooseframework.inl.gov/docs/PRs/19556/coverage/framework)


## Modules coverage

Coverage did not change

## Full coverage reports

<details>
<summary>Reports</summary>

- [`framework`](https://mooseframework.inl.gov/docs/PRs/19556/coverage/framework)
- [`chemical_reactions`](https://mooseframework.inl.gov/docs/PRs/19556/coverage/chemical_reactions)
- [`combined`](https://mooseframework.inl.gov/docs/PRs/19556/coverage/combined)
- [`contact`](https://mooseframework.inl.gov/docs/PRs/19556/coverage/contact)
- [`external_petsc_solver`](https://mooseframework.inl.gov/docs/PRs/19556/coverage/external_petsc_solver)
- [`fluid_properties`](https://mooseframework.inl.gov/docs/PRs/19556/coverage/fluid_properties)
- [`fsi`](https://mooseframework.inl.gov/docs/PRs/19556/coverage/fsi)
- [`functional_expansion_tools`](https://mooseframework.inl.gov/docs/PRs/19556/coverage/functional_expansion_tools)
- [`geochemistry`](https://mooseframework.inl.gov/docs/PRs/19556/coverage/geochemistry)
- [`heat_conduction`](https://mooseframework.inl.gov/docs/PRs/19556/coverage/heat_conduction)
- [`level_set`](https://mooseframework.inl.gov/docs/PRs/19556/coverage/level_set)
- [`misc`](https://mooseframework.inl.gov/docs/PRs/19556/coverage/misc)
- [`navier_stokes`](https://mooseframework.inl.gov/docs/PRs/19556/coverage/navier_stokes)
- [`peridynamics`](https://mooseframework.inl.gov/docs/PRs/19556/coverage/peridynamics)
- [`phase_field`](https://mooseframework.inl.gov/docs/PRs/19556/coverage/phase_field)
- [`porous_flow`](https://mooseframework.inl.gov/docs/PRs/19556/coverage/porous_flow)
- [`ray_tracing`](https://mooseframework.inl.gov/docs/PRs/19556/coverage/ray_tracing)
- [`rdg`](https://mooseframework.inl.gov/docs/PRs/19556/coverage/rdg)
- [`reactor`](https://mooseframework.inl.gov/docs/PRs/19556/coverage/reactor)
- [`richards`](https://mooseframework.inl.gov/docs/PRs/19556/coverage/richards)
- [`stochastic_tools`](https://mooseframework.inl.gov/docs/PRs/19556/coverage/stochastic_tools)
- [`tensor_mechanics`](https://mooseframework.inl.gov/docs/PRs/19556/coverage/tensor_mechanics)
- [`xfem`](https://mooseframework.inl.gov/docs/PRs/19556/coverage/xfem)

</details>

## Warnings

- `framework` new line coverage rate 50.00% is less than the suggested 90.0%



This comment will be updated on new commits.

2021-12-07 00:52 UTC, loganharbour approved these changes

2021-12-07 00:52 UTC, merged