Thm merge fixes 2
idaholab/moose pull request #19916
Opened 2021-12-22 22:31 UTC by permcody

## Reason

Merging the THM repository into the MOOSE repository. It has been approved for OSS release

## Design

See the THM design documents and SDR.

## Impact

This PR adds a completely new physics module (Major)

2021-12-22 22:34 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/922067/) on 10666af wanted to post the following:

Your code requires style changes.  

A patch was auto generated and copied [here](https://mooseframework.inl.gov/docs/PRs/19916/style.patch)  
You can directly apply the patch by running, in the top level of your repository:

`curl -s https://mooseframework.inl.gov/docs/PRs/19916/style.patch | git apply -v`  

Alternatively, with your repository up to date and in the top level of your repository:

`git clang-format 1c4a0ba58e8a10e4900a0bc6dbea0ea973530207`

2021-12-22 22:34 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/922067/) on 10666af wanted to post the following:

Warning: This PR changes repo size by 11.57 MiB.

2021-12-22 22:41 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/922104/) on 89ed13b wanted to post the following:

Warning: This PR changes repo size by 11.57 MiB.

2021-12-22 22:42 UTC, loganharbour commented
- Remove `.coverage` and add to the root `.coverage` file with `[thm]` instead of `[default`]
- Remove .gitignore

2021-12-22 23:05 UTC, loganharbour commented
Script used for porting issues in case we need it later:

```python
import gitlab
from github import Github
import time
from datetime import datetime, timedelta
import re
import csv

gitlab_url = 'https://gitlab.software.inl.gov'
gitlab_token = ''
github_token = ''
repo = 'idaholab/thm'
to_repo = 'idaholab/moose'

gl = gitlab.Gitlab(gitlab_url, private_token=gitlab_token)
gh = Github(github_token)

gl_repo = gl.projects.get(repo)
gh_repo = gh.get_repo(to_repo)

# To be filled with old issue ID -> new issue ID
issue_map = {}

# Name map for the header from person -> github persona
author_map = {'Alexander Lindsay': 'lindsayad',
            'David Andrs': 'andrsd',
            'Fande Kong': 'fdkong',
            'Guillaume Giudicelli': 'GiudGiud',
            'Joshua Hansel': 'joshuahansel',
            'Logan Harbour': 'loganharbour',
            'Sebastian Schunert': 'snschune'}

# User map from gitlab -> github persona
user_map = {'hansje': 'joshuahansel',
           'balep': 'pbalest',
           'schuseba': 'snschune',
           'schus': 'snschune',
           'marcm': 'rcm59',
           'KONGF': 'fdkong',
           'lindad': 'lindsayad',
           'ortej': 'jortensi',
           'LABOVM': 'vincentlaboure',
           'rcm': 'rcm59',
           'slauae': 'aeslaughter'}

# Converts a gitlab time -> a human time (this is dirty but it works...)
def human_time(timestamp):
    created = datetime.strptime(timestamp[:-5], '%Y-%m-%dT%H:%M:%S') - timedelta(hours=7)
    return created.strftime('%b %d, %Y %I:%M%p MST')

# Replaces an author with a name to their github username
def replace_author(object):
    if object.author['name'] in author_map:
        return '@' + author_map[object.author['name']]
    return object.author['name']

# Replaces @ mentions
def replace_mentions(str):
    for from, to in user_map.items():
        str = str.replace('@' + from, '@' + to)
    return str

# Header for adding a comment for an issue/note/etc
def body_header(issue, object, extra_content=None):
    new_body = 'Imported from [{}#{}]({}) '.format(repo, issue.iid, issue.web_url)
    new_body += 'by {} at {}\n\n'.format(replace_author(object), human_time(object.created_at))
    if extra_content:
        new_body += extra_content + '\n\n'
    new_body += '------\n\n'
    return new_body

# Gets a URL to a merge request on a gitlab instance
def gitlab_merge_request_url(num):
    return gitlab_url + '/' + repo + '/-/merge_requests/{}'.format(num)

# Helper for calling a github action that can be rate limited; will try it every 30 sec
# until the rate liminting is gone
def do_github(action):
    while True:
        try:
            result = action()
            time.sleep(30)
            return result
        except:
            print('Rate limited')
            time.sleep(30)

# Issues that have uploads that we need to manually change
has_uploads = set()

issues = sorted(gl_repo.issues.list(all=True), key=lambda entry: entry.iid)
print('Importing {} issues...'.format(len(issues)))
for i in range(len(issues)):
    issue = issues[i]
    print('{}/{}: !{} "{}"'.format(i + 1, len(issues), issue.iid, issue.title))

    # Whether or not the issue was closed by a merge request
    # (to trigger a MR closed comment instead of a generic comment)
    closed_by_merge_request = None
    # The merge requests that were mentioned in the issue
    mentioned_merge_requests = set()
    # Comments we need to add
    comments = []

    # Work through all of the notes, which could be mentions or actual user comments
    for note in sorted(issue.notes.list(all=True), key=lambda entry: datetime.strptime(entry.created_at[:-5], '%Y-%m-%dT%H:%M:%S').timestamp()):
        # System notes are mentions (MRs, commits, etc)
        if note.system:
            search_closed_merge_request = re.search('closed via merge request !([0-9]+)', note.body)
            if search_closed_merge_request:
                mr_num = search_closed_merge_request.group(1)
                closed_by_merge_request = mr_num
                mentioned_merge_requests.add(mr_num)

            search_mentioned_merge_request = re.search('mentioned in merge request !([0-9]+)', note.body)
            if search_mentioned_merge_request:
                mr_num = search_mentioned_merge_request.group(1)
                mentioned_merge_requests.add(mr_num)
        # Standard comment by a user
        else:
            # Keep track of issues where we need to manually add uploads
            if '/uploads' in note.body:
                has_uploads.add(issue.iid)

            comment_body = body_header(issue, note) + replace_mentions(note.body)
            comments.append(comment_body)

    # If not closed by a MR but it was closed, add a comment as to when it was closed
    if issue.state == 'closed' and closed_by_merge_request is None:
        comments.append('Closed at {}.'.format(human_time(issue.closed_at)))

    # Create the extra content in the header for mentioned MRs
    extra_content = None
    if mentioned_merge_requests:
        extra_content = 'Mentioned merge requests:\n\n'
        for mr_num in sorted(mentioned_merge_requests):
            mr = gl_repo.mergerequests.get(mr_num)
            link = '[{} (!{})]({})'.format(mr.title, mr_num, gitlab_merge_request_url(mr_num))
            extra_content += '- ' + link + '\n'
            if mr_num == closed_by_merge_request:
                comments.append('Closed by merge request ' + link + ' at ' + human_time(mr.merged_at))

    # Keep track of issues where we need to manually add uploads
    if '/uploads' in issue.description:
        has_uploads.add(issue.iid)

    # Create the issue
    issue_body = body_header(issue, issue, extra_content) + replace_mentions(issue.description)
    create_issue = lambda: gh_repo.create_issue(title='THM: ' + issue.title, body=issue_body, labels=['C: Modules'])
    new_issue = do_github(create_issue)

    # Save the new issue number to the old -> new ID map
    with open('issue_map.csv', 'a') as f:
        csv.writer(f).writerow((issue.iid, new_issue.number))

    # Post all of the comments
    for comment in comments:
        do_github(lambda: new_issue.create_comment(comment))

    # Close the issue if it's closed
    if issue.state == 'closed':
        do_github(lambda: new_issue.edit(state='closed'))

if has_uploads:
    print('\nThe following issue(s) have uploads and will need to be edited manually:')
    for issue_id in sorted(has_uploads):
        issue = gl_repo.issues.get(issue_id)
        print('- !{} "{}"'.format(issue_id, issue.title))
```

2022-01-04 19:29 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/924060/) on 66e3aa4 wanted to post the following:

Warning: This PR changes repo size by 11.57 MiB.

2022-01-04 19:46 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/924134/) on 7233daa wanted to post the following:

Warning: This PR changes repo size by 11.57 MiB.

2022-01-04 21:45 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/924243/) on 3ce9603 wanted to post the following:

Warning: This PR changes repo size by 11.57 MiB.

2022-01-04 22:50 UTC, loganharbour requested changes
Remove

- `modules/thm/.clang-format`
- `modules/thm/.coverage`
- `modules/thm/.gitlab`
- `modules/thm/.mailmap`

2022-01-04 22:50 UTC, loganharbour commented on modules/modules.mk
> -# Modules that follow have one or more dependencies
Why remove this comment? Breaking the point where the includes aren't independent anymore I think is good

2022-01-04 22:50 UTC, loganharbour commented on modules/thm/include/base/THMApp.h
> +
I say don't even include these if we didn't have them in THM before

2022-01-04 23:48 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/924500/) on 3714d4a wanted to post the following:

Warning: This PR changes repo size by 11.57 MiB.

2022-01-05 19:34 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/924937/) on fd57bcc wanted to post the following:

Warning: This PR changes repo size by 11.57 MiB.

2022-01-05 20:32 UTC, moosebuild commented
Job [Documentation](https://civet.inl.gov/job/924936/) on fd57bcc wanted to post the following:

View the site [here](https://mooseframework.inl.gov/docs/PRs/19916/site)

This comment will be updated on new commits.

2022-01-06 16:06 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/926072/) on 885865f wanted to post the following:

Warning: This PR changes repo size by 11.56 MiB.

2022-01-06 16:26 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/926106/) on c303301 wanted to post the following:

Warning: This PR changes repo size by 11.56 MiB.

2022-01-07 22:49 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/927217/) on 3c1e9ef wanted to post the following:

Warning: This PR changes repo size by 11.56 MiB.

2022-01-10 19:35 UTC, lindsayad commented
Wow @andrsd is going to build an insurmountable commit count lead in MOOSE once this is merged 😄 ~A question I would ask is whether it's universally known that "thermal hydraulics" means essentially system thermal hydraulics. I feel like the answer is probably yes, but if it wasn't then this could be confusing to users that we now have a thermal hydraulics module that is separate from things like `heat_conduction` (whose name should probably be updated to be more like `heat_transfer`) and `navier_stokes`.~ Belay my concerns. I see that THM already pulls in those aforementioned modules, so I think it's fair to consider this to be a cohesive (albeit mostly 1D) thermal hydraulics module.

2022-01-10 20:14 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/927770/) on 5beffb4 : invalidated by @permcody

2022-01-10 20:16 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/927770/) on 5beffb4 wanted to post the following:

Warning: This PR changes repo size by 11.56 MiB.

2022-01-10 23:47 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/928073/) on 5199aeb wanted to post the following:

Warning: This PR changes repo size by 11.57 MiB.

2022-01-13 05:14 UTC, cticenhour requested changes, later dismissed
Since this is likely to be merged in before the end of the month, I wanted to add a general review/reminder to add a note about THM to the January newsletter now that `modules/doc/content/newsletter/2022_01.md` has made it to devel. Thanks!

2022-01-13 15:41 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/931448/) on 4e18938 wanted to post the following:

Warning: This PR changes repo size by 11.56 MiB.

2022-01-13 18:52 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/932108/) on c5e1979 wanted to post the following:

Warning: This PR changes repo size by 11.56 MiB.

2022-01-13 20:22 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/932192/) on b550023 wanted to post the following:

Warning: This PR changes repo size by 11.57 MiB.

2022-01-14 02:56 UTC, moosebuild commented
Job [Coverage](https://civet.inl.gov/job/932218/) on b550023 wanted to post the following:


## Framework coverage

Coverage did not change


## Modules coverage

Inconsistent report tags were found between the head and base reports.
This can happen when reports are missing from either the head or the base.

Inconsistent tags:
  module-thm
  module-thm-parallel
  module-thm-recover

### Combined

<table>
  <thead>
    <tr>
      <th></th>
      <th>50846a</th>
      <th colspan=4>#19916 b55002</th>
    </tr>
    <tr>
      <th></th>
      <th>Total</th>
      <th>Total</th>
      <th>+/-</th>
      <th>New</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><b>Rate</b></td>
      <td>37.96%</td>
      <td>74.14%</td>
      <td>+36.17%</td>
      <td>33.33%</td>
    </tr>
    <tr>
      <td><b>Hits</b></td>
      <td>41</td>
      <td>43</td>
      <td>+2</td>
      <td>3</td>
    </tr>
    <tr>
      <td><b>Misses</b></td>
      <td>67</td>
      <td>15</td>
      <td>-52</td>
      <td>6</td>
    </tr>
  </tbody>
</table>

[Diff coverage report](https://mooseframework.inl.gov/docs/PRs/19916/coverage_diff/combined.html)

[Full coverage report](https://mooseframework.inl.gov/docs/PRs/19916/coverage/combined)

## Full coverage reports

<details>
<summary>Reports</summary>

- [`framework`](https://mooseframework.inl.gov/docs/PRs/19916/coverage/framework)
- [`chemical_reactions`](https://mooseframework.inl.gov/docs/PRs/19916/coverage/chemical_reactions)
- [`combined`](https://mooseframework.inl.gov/docs/PRs/19916/coverage/combined)
- [`contact`](https://mooseframework.inl.gov/docs/PRs/19916/coverage/contact)
- [`external_petsc_solver`](https://mooseframework.inl.gov/docs/PRs/19916/coverage/external_petsc_solver)
- [`fluid_properties`](https://mooseframework.inl.gov/docs/PRs/19916/coverage/fluid_properties)
- [`fsi`](https://mooseframework.inl.gov/docs/PRs/19916/coverage/fsi)
- [`functional_expansion_tools`](https://mooseframework.inl.gov/docs/PRs/19916/coverage/functional_expansion_tools)
- [`geochemistry`](https://mooseframework.inl.gov/docs/PRs/19916/coverage/geochemistry)
- [`heat_conduction`](https://mooseframework.inl.gov/docs/PRs/19916/coverage/heat_conduction)
- [`level_set`](https://mooseframework.inl.gov/docs/PRs/19916/coverage/level_set)
- [`misc`](https://mooseframework.inl.gov/docs/PRs/19916/coverage/misc)
- [`navier_stokes`](https://mooseframework.inl.gov/docs/PRs/19916/coverage/navier_stokes)
- [`peridynamics`](https://mooseframework.inl.gov/docs/PRs/19916/coverage/peridynamics)
- [`phase_field`](https://mooseframework.inl.gov/docs/PRs/19916/coverage/phase_field)
- [`porous_flow`](https://mooseframework.inl.gov/docs/PRs/19916/coverage/porous_flow)
- [`ray_tracing`](https://mooseframework.inl.gov/docs/PRs/19916/coverage/ray_tracing)
- [`rdg`](https://mooseframework.inl.gov/docs/PRs/19916/coverage/rdg)
- [`reactor`](https://mooseframework.inl.gov/docs/PRs/19916/coverage/reactor)
- [`richards`](https://mooseframework.inl.gov/docs/PRs/19916/coverage/richards)
- [`stochastic_tools`](https://mooseframework.inl.gov/docs/PRs/19916/coverage/stochastic_tools)
- [`tensor_mechanics`](https://mooseframework.inl.gov/docs/PRs/19916/coverage/tensor_mechanics)
- [`thm`](https://mooseframework.inl.gov/docs/PRs/19916/coverage/thm)
- [`xfem`](https://mooseframework.inl.gov/docs/PRs/19916/coverage/xfem)

</details>

## Warnings

- `combined` new line coverage rate 33.33% is less than the suggested 90.0%



This comment will be updated on new commits.

2022-01-17 18:09 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/933910/) on 184c0c5 wanted to post the following:

Warning: This PR changes repo size by 11.56 MiB.

2022-01-17 18:33 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/934093/) on a3eae8e wanted to post the following:

Your code requires style changes.  

A patch was auto generated and copied [here](https://mooseframework.inl.gov/docs/PRs/19916/style.patch)  
You can directly apply the patch by running, in the top level of your repository:

`curl -s https://mooseframework.inl.gov/docs/PRs/19916/style.patch | git apply -v`  

Alternatively, with your repository up to date and in the top level of your repository:

`git clang-format 18c73d2a68537676ad966764a8a2b319843a2a5e`

2022-01-17 18:33 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/934093/) on a3eae8e wanted to post the following:

Warning: This PR changes repo size by 11.57 MiB.

2022-01-17 18:36 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/934127/) on 12e46e5 wanted to post the following:

Warning: This PR changes repo size by 11.57 MiB.

2022-01-17 19:11 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/934202/) on c9f7196 wanted to post the following:

Warning: This PR changes repo size by 11.57 MiB.

2022-01-18 02:53 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/934811/) on 0c0a85b wanted to post the following:

Warning: This PR changes repo size by 11.57 MiB.

2022-01-18 21:15 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/935283/) on 5e1ef72 wanted to post the following:

Warning: This PR changes repo size by 11.57 MiB.

2022-01-18 22:15 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/935351/) on 0102b7a wanted to post the following:

Warning: This PR changes repo size by 11.57 MiB.

2022-01-18 23:26 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/935536/) on 137ec58 wanted to post the following:

Warning: This PR changes repo size by 11.57 MiB.

2022-01-20 00:09 UTC, lindsayad commented
Any rough timeline on when we think this might be merged?

2022-01-20 15:53 UTC, andrsd commented
I resolved the doco issue yesterday, @loganharbour is still looking into some coverage issues. After that is resolved, we can merge. I think.

2022-01-21 15:53 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/937406/) on 11f53f3 wanted to post the following:

Warning: This PR changes repo size by 11.57 MiB.

2022-01-21 18:01 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/937587/) on a884d63 wanted to post the following:

Warning: This PR changes repo size by 11.57 MiB.

2022-01-21 19:45 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/937836/) on b4991a7 wanted to post the following:

Warning: This PR changes repo size by 11.57 MiB.

2022-01-21 20:19 UTC, moosebuild commented
Job [Python 3.8 Tests](https://civet.inl.gov/job/937840/) on b4991a7 : invalidated by @permcody

Error doesn&#39;&#39;t make any sense.

2022-01-25 00:30 UTC, fdkong commented
I would like to see this being merged. What can I help?

2022-01-25 17:38 UTC, permcody commented
Should we tell him @loganharbour? 😄

2022-01-25 17:45 UTC, fdkong commented
3K commits

2022-01-25 18:46 UTC, loganharbour commented
Something really weird is going on now that we've added this module. 

See the "Modules" recipe (which tests modules individually for coverage): https://civet.inl.gov/job/937847/ (6 hours) vs the current run on next https://civet.inl.gov/job/939598/ (1 hour). The difference is in the extraction of coverage. This went from taking < 20s per module to > 12m per module.

In specific, the final extraction (taking `chemical_reactions`) as an example:

```
BUILD_ROOT/moose/: lcov --gcov-tool gcov --extract /ramdisk/civet/build_0/moose_coverage/final.info \*/ramdisk/civet/build_0/moose/modules/chemical_reactions/src/\* --extract /ramdisk/civet/build_0/moose_coverage/final.info \*/ramdisk/civet/build_0/moose/modules/chemical_reactions/include/\* --output-file /ramdisk/civet/build_0/moose_coverage/coverage.info
Reading tracefile /ramdisk/civet/build_0/moose_coverage/final.info
Extracting /ramdisk/civet/build_0/moose/modules/chemical_reactions/include/auxkernels/KineticDisPreConcAux.h
Extracting /ramdisk/civet/build_0/moose/modules/chemical_reactions/include/auxkernels/KineticDisPreRateAux.h
Extracting /ramdisk/civet/build_0/moose/modules/chemical_reactions/include/utils/EquilibriumConstantFit.h
Extracting /ramdisk/civet/build_0/moose/modules/chemical_reactions/src/actions/AddCoupledEqSpeciesAction.C
Extracting /ramdisk/civet/build_0/moose/modules/chemical_reactions/src/actions/AddCoupledSolidKinSpeciesAction.C
Extracting /ramdisk/civet/build_0/moose/modules/chemical_reactions/src/actions/AddPrimarySpeciesAction.C
Extracting /ramdisk/civet/build_0/moose/modules/chemical_reactions/src/actions/AddSecondarySpeciesAction.C
Extracting /ramdisk/civet/build_0/moose/modules/chemical_reactions/src/auxkernels/AqueousEquilibriumRxnAux.C
Extracting /ramdisk/civet/build_0/moose/modules/chemical_reactions/src/auxkernels/EquilibriumConstantAux.C
Extracting /ramdisk/civet/build_0/moose/modules/chemical_reactions/src/auxkernels/KineticDisPreConcAux.C
Extracting /ramdisk/civet/build_0/moose/modules/chemical_reactions/src/auxkernels/KineticDisPreRateAux.C
Extracting /ramdisk/civet/build_0/moose/modules/chemical_reactions/src/auxkernels/PHAux.C
Extracting /ramdisk/civet/build_0/moose/modules/chemical_reactions/src/auxkernels/TotalConcentrationAux.C
Extracting /ramdisk/civet/build_0/moose/modules/chemical_reactions/src/base/ChemicalReactionsApp.C
Extracting /ramdisk/civet/build_0/moose/modules/chemical_reactions/src/bcs/ChemicalOutFlowBC.C
Extracting /ramdisk/civet/build_0/moose/modules/chemical_reactions/src/kernels/CoupledBEEquilibriumSub.C
Extracting /ramdisk/civet/build_0/moose/modules/chemical_reactions/src/kernels/CoupledBEKinetic.C
Extracting /ramdisk/civet/build_0/moose/modules/chemical_reactions/src/kernels/CoupledConvectionReactionSub.C
Extracting /ramdisk/civet/build_0/moose/modules/chemical_reactions/src/kernels/CoupledDiffusionReactionSub.C
Extracting /ramdisk/civet/build_0/moose/modules/chemical_reactions/src/kernels/DarcyFluxPressure.C
Extracting /ramdisk/civet/build_0/moose/modules/chemical_reactions/src/kernels/DesorptionFromMatrix.C
Extracting /ramdisk/civet/build_0/moose/modules/chemical_reactions/src/kernels/DesorptionToPorespace.C
Extracting /ramdisk/civet/build_0/moose/modules/chemical_reactions/src/kernels/PrimaryConvection.C
Extracting /ramdisk/civet/build_0/moose/modules/chemical_reactions/src/kernels/PrimaryDiffusion.C
Extracting /ramdisk/civet/build_0/moose/modules/chemical_reactions/src/kernels/PrimaryTimeDerivative.C
Extracting /ramdisk/civet/build_0/moose/modules/chemical_reactions/src/main.C
Extracting /ramdisk/civet/build_0/moose/modules/chemical_reactions/src/materials/LangmuirMaterial.C
Extracting /ramdisk/civet/build_0/moose/modules/chemical_reactions/src/materials/MollifiedLangmuirMaterial.C
Extracting /ramdisk/civet/build_0/moose/modules/chemical_reactions/src/postprocessors/TotalMineralVolumeFraction.C
Extracting /ramdisk/civet/build_0/moose/modules/chemical_reactions/src/utils/EquilibriumConstantFit.C
Extracted 30 files
Writing data to /ramdisk/civet/build_0/moose_coverage/coverage.info
Summary coverage rate:
  lines......: 93.3% (873 of 936 lines)
  functions..: 89.7% (96 of 107 functions)
  branches...: no data found
```

Is what takes many minutes. It will print out the summary and then hang. I have absolutely no clue what is going on here and I don't have the immediate time to debug it. Any takers? This should be able to be replicated on rod with:

```
moosebuild
module load mpich cmake lcov python vtk
git clone https://github.com/permcody/moose
cd moose
git checkout thm_merge_fixes_2
MOOSE_JOBS=32 ./scripts/update_and_rebuild_petsc.sh
METHODS=opt MOOSE_JOBS=32 ./scripts/update_and_rebuild_libmesh.sh
MOOSE_DIR=$(pwd)
cd framework
make -j 32
cd ../modules/chemical_reactions
MOOSE_HEADER_SYMLINKS=false make -j 32 coverage=true graceful=true
lcov --gcov-tool gcov --capture --initial --directory $MOOSE_DIR/modules/chemical_reactions --output-file $MOOSE_DIR/initialize.info
./run_tests -j 32
lcov --gcov-tool gcov --capture --ignore-errors gcov,source --directory $MOOSE_DIR/modules/chemical_reactions --output-file $MOOSE_DIR/covered.info
lcov --gcov-tool gcov --add-tracefile $MOOSE_DIR/initialize.info --add-tracefile $MOOSE_DIR/covered.info --output-file $MOOSE_DIR/final.info
lcov --gcov-tool gcov --extract $MOOSE_DIR/final.info $MOOSE_DIR/modules/chemical_reactions/src/* --extract $MOOSE_DIR/final.info $MOOSE_DIR/modules/chemical_reactions/include/* --output-file $MOOSE_DIR/coverage.info
```

The last command should hang. I typed all of the above without testing... it _should_ work

2022-01-25 22:27 UTC, loganharbour submitted a review, later dismissed

2022-01-25 22:29 UTC, andrsd approved these changes, later dismissed

2022-01-27 22:18 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/943531/) on 44578ce wanted to post the following:

Warning: This PR changes repo size by 11.63 MiB.

2022-01-29 20:06 UTC, loganharbour approved these changes

2022-01-29 20:10 UTC, andrsd approved these changes

2022-01-29 20:10 UTC, merged