Added an option for PiecewiseLinear to extrapolate
idaholab/moose pull request #20027
Opened 2022-01-12 16:18 UTC by joshuahansel

Closes #20024

2022-01-12 16:44 UTC, cticenhour requested changes

2022-01-12 16:44 UTC, cticenhour commented on modules/doc/content/newsletter/index.md
> +
Please remove. The index link to the page is only added at the beginning of the next month.

2022-01-12 16:44 UTC, cticenhour commented on modules/doc/content/newsletter/2022_01.md
> +  the nearest ordinate value. This is accomplished with a new parameter `extrap`.
Could you make clear to the reader that this parameter is a boolean, and that `extrap = true` is required to allow extrapolation? I know this is in the doco, but I don't think it hurts to say here.

2022-01-12 21:35 UTC, moosebuild commented
Job [Documentation](https://civet.inl.gov/job/930334/) on 3cc42fd wanted to post the following:

View the site [here](https://mooseframework.inl.gov/docs/PRs/20027/site)

This comment will be updated on new commits.

2022-01-13 01:21 UTC, moosebuild commented
Job [Coverage](https://civet.inl.gov/job/930619/) on ab065f8 wanted to post the following:


## Framework coverage

Inconsistent report tags were found between the head and base reports.
This can happen when reports are missing from either the head or the base.

Inconsistent tags:
  framework2
[Full coverage report](https://mooseframework.inl.gov/docs/PRs/20027/coverage/framework)


## Modules coverage

Inconsistent report tags were found between the head and base reports.
This can happen when reports are missing from either the head or the base.

Inconsistent tags:
  module-contact-parallel
  module-stochastic_tools-parallel
  module-tensor_mechanics-parallel
  module-xfem-parallel

## Full coverage reports

<details>
<summary>Reports</summary>

- [`framework`](https://mooseframework.inl.gov/docs/PRs/20027/coverage/framework)
- [`chemical_reactions`](https://mooseframework.inl.gov/docs/PRs/20027/coverage/chemical_reactions)
- [`combined`](https://mooseframework.inl.gov/docs/PRs/20027/coverage/combined)
- [`contact`](https://mooseframework.inl.gov/docs/PRs/20027/coverage/contact)
- [`external_petsc_solver`](https://mooseframework.inl.gov/docs/PRs/20027/coverage/external_petsc_solver)
- [`fluid_properties`](https://mooseframework.inl.gov/docs/PRs/20027/coverage/fluid_properties)
- [`fsi`](https://mooseframework.inl.gov/docs/PRs/20027/coverage/fsi)
- [`functional_expansion_tools`](https://mooseframework.inl.gov/docs/PRs/20027/coverage/functional_expansion_tools)
- [`geochemistry`](https://mooseframework.inl.gov/docs/PRs/20027/coverage/geochemistry)
- [`heat_conduction`](https://mooseframework.inl.gov/docs/PRs/20027/coverage/heat_conduction)
- [`level_set`](https://mooseframework.inl.gov/docs/PRs/20027/coverage/level_set)
- [`misc`](https://mooseframework.inl.gov/docs/PRs/20027/coverage/misc)
- [`navier_stokes`](https://mooseframework.inl.gov/docs/PRs/20027/coverage/navier_stokes)
- [`peridynamics`](https://mooseframework.inl.gov/docs/PRs/20027/coverage/peridynamics)
- [`phase_field`](https://mooseframework.inl.gov/docs/PRs/20027/coverage/phase_field)
- [`porous_flow`](https://mooseframework.inl.gov/docs/PRs/20027/coverage/porous_flow)
- [`ray_tracing`](https://mooseframework.inl.gov/docs/PRs/20027/coverage/ray_tracing)
- [`rdg`](https://mooseframework.inl.gov/docs/PRs/20027/coverage/rdg)
- [`reactor`](https://mooseframework.inl.gov/docs/PRs/20027/coverage/reactor)
- [`richards`](https://mooseframework.inl.gov/docs/PRs/20027/coverage/richards)
- [`stochastic_tools`](https://mooseframework.inl.gov/docs/PRs/20027/coverage/stochastic_tools)
- [`tensor_mechanics`](https://mooseframework.inl.gov/docs/PRs/20027/coverage/tensor_mechanics)
- [`xfem`](https://mooseframework.inl.gov/docs/PRs/20027/coverage/xfem)

</details>



This comment will be updated on new commits.

2022-01-13 14:27 UTC, andrsd approved these changes

2022-01-13 15:10 UTC, cticenhour approved these changes

2022-01-13 15:11 UTC, merged