Add 3D mortar-based thermal contact tests
idaholab/moose pull request #20090
Opened 2022-01-20 19:42 UTC by dewenyushu

Refs. issue #19286

2022-01-20 20:40 UTC, moosebuild commented
Job [Documentation](https://civet.inl.gov/job/936834/) on 394945e wanted to post the following:

View the site [here](https://mooseframework.inl.gov/docs/PRs/20090/site)

This comment will be updated on new commits.

2022-01-21 02:36 UTC, moosebuild commented
Job [Coverage](https://civet.inl.gov/job/937253/) on a48793a wanted to post the following:


## Framework coverage

<table>
  <thead>
    <tr>
      <th></th>
      <th>6b91c6</th>
      <th colspan=4>#20090 a48793</th>
    </tr>
    <tr>
      <th></th>
      <th>Total</th>
      <th>Total</th>
      <th>+/-</th>
      <th>New</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><b>Rate</b></td>
      <td>82.30%</td>
      <td>82.31%</td>
      <td>+0.00%</td>
      <td>-</td>
    </tr>
    <tr>
      <td><b>Hits</b></td>
      <td>73297</td>
      <td>73298</td>
      <td>+1</td>
      <td>0</td>
    </tr>
    <tr>
      <td><b>Misses</b></td>
      <td>15759</td>
      <td>15758</td>
      <td>-1</td>
      <td>0</td>
    </tr>
  </tbody>
</table>

[Diff coverage report](https://mooseframework.inl.gov/docs/PRs/20090/coverage_diff/framework.html)

[Full coverage report](https://mooseframework.inl.gov/docs/PRs/20090/coverage/framework)


## Modules coverage

Coverage did not change

## Full coverage reports

<details>
<summary>Reports</summary>

- [`framework`](https://mooseframework.inl.gov/docs/PRs/20090/coverage/framework)
- [`chemical_reactions`](https://mooseframework.inl.gov/docs/PRs/20090/coverage/chemical_reactions)
- [`combined`](https://mooseframework.inl.gov/docs/PRs/20090/coverage/combined)
- [`contact`](https://mooseframework.inl.gov/docs/PRs/20090/coverage/contact)
- [`external_petsc_solver`](https://mooseframework.inl.gov/docs/PRs/20090/coverage/external_petsc_solver)
- [`fluid_properties`](https://mooseframework.inl.gov/docs/PRs/20090/coverage/fluid_properties)
- [`fsi`](https://mooseframework.inl.gov/docs/PRs/20090/coverage/fsi)
- [`functional_expansion_tools`](https://mooseframework.inl.gov/docs/PRs/20090/coverage/functional_expansion_tools)
- [`geochemistry`](https://mooseframework.inl.gov/docs/PRs/20090/coverage/geochemistry)
- [`heat_conduction`](https://mooseframework.inl.gov/docs/PRs/20090/coverage/heat_conduction)
- [`level_set`](https://mooseframework.inl.gov/docs/PRs/20090/coverage/level_set)
- [`misc`](https://mooseframework.inl.gov/docs/PRs/20090/coverage/misc)
- [`navier_stokes`](https://mooseframework.inl.gov/docs/PRs/20090/coverage/navier_stokes)
- [`peridynamics`](https://mooseframework.inl.gov/docs/PRs/20090/coverage/peridynamics)
- [`phase_field`](https://mooseframework.inl.gov/docs/PRs/20090/coverage/phase_field)
- [`porous_flow`](https://mooseframework.inl.gov/docs/PRs/20090/coverage/porous_flow)
- [`ray_tracing`](https://mooseframework.inl.gov/docs/PRs/20090/coverage/ray_tracing)
- [`rdg`](https://mooseframework.inl.gov/docs/PRs/20090/coverage/rdg)
- [`reactor`](https://mooseframework.inl.gov/docs/PRs/20090/coverage/reactor)
- [`richards`](https://mooseframework.inl.gov/docs/PRs/20090/coverage/richards)
- [`stochastic_tools`](https://mooseframework.inl.gov/docs/PRs/20090/coverage/stochastic_tools)
- [`tensor_mechanics`](https://mooseframework.inl.gov/docs/PRs/20090/coverage/tensor_mechanics)
- [`xfem`](https://mooseframework.inl.gov/docs/PRs/20090/coverage/xfem)

</details>



This comment will be updated on new commits.

2022-01-21 15:34 UTC, dewenyushu commented on modules/heat_conduction/test/tests/gap_heat_transfer_mortar/gap_heat_transfer_3D_mortar.i
> +[]
Yes, I think so - The heat_balance value is on the order of 1e-15.

2022-01-21 15:39 UTC, dewenyushu commented on modules/heat_conduction/test/tests/gap_heat_transfer_mortar/gap_heat_transfer_3D_mortar.i
> +    variable = lm
Good point, especially that we are about to remove that flag. Let me try it

2022-01-21 15:50 UTC, dewenyushu commented on modules/heat_conduction/test/tests/gap_heat_transfer_mortar/gap_heat_transfer_3D_mortar.i
> +    variable = lm
This case has two blocks of the same size, however, it does not have displacements so no edge dropping would happen in theory. I just checked, it still passes the test. Do you prefer that we add the flag now and remove later?

2022-01-21 15:53 UTC, moosebuild commented
Job [Mac Test](https://civet.inl.gov/job/937247/) on a48793a : invalidated by @dewenyushu

The failed test does not seem to be caused by this PR

2022-01-21 16:27 UTC, recuero commented on modules/heat_conduction/test/tests/gap_heat_transfer_mortar/gap_heat_transfer_3D_mortar.i
> +    variable = lm
I am fine how it is since it passes regardless of that flag's setting.

2022-01-21 16:27 UTC, recuero commented on modules/heat_conduction/test/tests/gap_heat_transfer_mortar/gap_heat_transfer_3D_mortar.i
> +[]
That's pretty good!

2022-01-21 19:20 UTC, recuero requested changes
Could you reduce the mesh size for these tests? I know this may require increasing the tolerance, but I think this'd be ok. In the end, we are just comparing with node on face as a form of verification. This test appears to be the longest running in debug mode:

```20 longest running jobs:
--------------------------------------------------------------------------------------------------------------
[245.0s]       OK heat_conduction/test:gap_heat_transfer_mortar.gap_heat_transfer_3d
[204.5s]       OK tensor_mechanics/test:crystal_plasticity/user_object_based.use_substep_dt
[186.2s]       OK combined/test:additive_manufacturing.check_element_addition_by_variable
[156.5s]       OK tensor_mechanics/test:substepping.ad_power_law_substepping
[139.7s]       OK tensor_mechanics/test:crystal_plasticity/stress_update_material_based.use_substep_dt/usr/local/lib/python3.7/importlib/_bootstrap.py:219: RuntimeWarning: compiletime version 3.6 of module 'hit' does not match runtime version 3.7
  return f(*args, **kwds)

[135.3s]       OK tensor_mechanics/test:finite_strain_elastic_anisotropy.3d_bar_orthotropic_90deg_rotation_ad```

2022-01-21 22:49 UTC, recuero approved these changes
Looks good to me.

2022-01-21 22:50 UTC, recuero commented
We can probably close #19286 with this PR.

2022-01-22 00:24 UTC, merged