Protect against concurrent read/write for SectionIncrements
idaholab/moose pull request #20390
Opened 2022-02-24 02:45 UTC by lindsayad

Removes the thread sanitizer errors reported [here](https://github.com/idaholab/moose/discussions/19443#discussioncomment-2240054)

The crux of the matter is that, at run-time, there is no guarantee that the `release` (consequently changed to `relaxed` in this PR) will occur before the `acquire` (consequently changed to `relaxed` in this PR), and if it does not there is no sychronizes-with relationship between the two. See the run-time section of [Pershing](https://preshing.com/20130823/the-synchronizes-with-relation/).

2022-02-24 04:21 UTC, moosebuild commented
Job [Documentation](https://civet.inl.gov/job/966523/) on 9ac062b wanted to post the following:

View the site [here](https://mooseframework.inl.gov/docs/PRs/20390/site)

This comment will be updated on new commits.

2022-02-24 05:34 UTC, moosebuild commented
Job [Coverage](https://civet.inl.gov/job/966531/) on 9ac062b wanted to post the following:


## Framework coverage

<table>
  <thead>
    <tr>
      <th></th>
      <th>3f7be3</th>
      <th colspan=4>#20390 9ac062</th>
    </tr>
    <tr>
      <th></th>
      <th>Total</th>
      <th>Total</th>
      <th>+/-</th>
      <th>New</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><b>Rate</b></td>
      <td>82.34%</td>
      <td>82.34%</td>
      <td>+0.00%</td>
      <td>100.00%</td>
    </tr>
    <tr>
      <td><b>Hits</b></td>
      <td>73848</td>
      <td>73850</td>
      <td>+2</td>
      <td>9</td>
    </tr>
    <tr>
      <td><b>Misses</b></td>
      <td>15840</td>
      <td>15840</td>
      <td>-</td>
      <td>0</td>
    </tr>
  </tbody>
</table>

[Diff coverage report](https://mooseframework.inl.gov/docs/PRs/20390/coverage_diff/framework.html)

[Full coverage report](https://mooseframework.inl.gov/docs/PRs/20390/coverage/framework)


## Modules coverage

Coverage did not change

## Full coverage reports

<details>
<summary>Reports</summary>

- [`framework`](https://mooseframework.inl.gov/docs/PRs/20390/coverage/framework)
- [`chemical_reactions`](https://mooseframework.inl.gov/docs/PRs/20390/coverage/chemical_reactions)
- [`combined`](https://mooseframework.inl.gov/docs/PRs/20390/coverage/combined)
- [`contact`](https://mooseframework.inl.gov/docs/PRs/20390/coverage/contact)
- [`external_petsc_solver`](https://mooseframework.inl.gov/docs/PRs/20390/coverage/external_petsc_solver)
- [`fluid_properties`](https://mooseframework.inl.gov/docs/PRs/20390/coverage/fluid_properties)
- [`fsi`](https://mooseframework.inl.gov/docs/PRs/20390/coverage/fsi)
- [`functional_expansion_tools`](https://mooseframework.inl.gov/docs/PRs/20390/coverage/functional_expansion_tools)
- [`geochemistry`](https://mooseframework.inl.gov/docs/PRs/20390/coverage/geochemistry)
- [`heat_conduction`](https://mooseframework.inl.gov/docs/PRs/20390/coverage/heat_conduction)
- [`level_set`](https://mooseframework.inl.gov/docs/PRs/20390/coverage/level_set)
- [`misc`](https://mooseframework.inl.gov/docs/PRs/20390/coverage/misc)
- [`navier_stokes`](https://mooseframework.inl.gov/docs/PRs/20390/coverage/navier_stokes)
- [`peridynamics`](https://mooseframework.inl.gov/docs/PRs/20390/coverage/peridynamics)
- [`phase_field`](https://mooseframework.inl.gov/docs/PRs/20390/coverage/phase_field)
- [`porous_flow`](https://mooseframework.inl.gov/docs/PRs/20390/coverage/porous_flow)
- [`ray_tracing`](https://mooseframework.inl.gov/docs/PRs/20390/coverage/ray_tracing)
- [`rdg`](https://mooseframework.inl.gov/docs/PRs/20390/coverage/rdg)
- [`reactor`](https://mooseframework.inl.gov/docs/PRs/20390/coverage/reactor)
- [`richards`](https://mooseframework.inl.gov/docs/PRs/20390/coverage/richards)
- [`stochastic_tools`](https://mooseframework.inl.gov/docs/PRs/20390/coverage/stochastic_tools)
- [`tensor_mechanics`](https://mooseframework.inl.gov/docs/PRs/20390/coverage/tensor_mechanics)
- [`thermal_hydraulics`](https://mooseframework.inl.gov/docs/PRs/20390/coverage/thermal_hydraulics)
- [`xfem`](https://mooseframework.inl.gov/docs/PRs/20390/coverage/xfem)

</details>



This comment will be updated on new commits.

2022-02-24 20:04 UTC, lindsayad commented
I was wondering if we could make a copy of `SectionIncrement` in `PerfGraphLive` in which case you'd only have to lock for the copy, but it looks to me like we're relying on writing data to the `SectionIncrement` past where I've put the current lock (e.g. we're not just reading)

2022-02-24 23:18 UTC, friedmud requested changes
This is too slow.  We don't need them to be actually "synchronized"... the only thing that's important is that at the moment the print thread sees an update... the main thread has published all of the information about the new section.... which the existing code guarantees.

2022-03-02 18:50 UTC, closed without merging

2022-12-21 21:01 UTC, lindsayad commented
I've been thinking about this again since @grmnptr had his valgrind issues. @friedmud you said

> the only thing that's important is that at the moment the print thread sees an update... the main thread has published all of the information about the new section.... which the existing code guarantees.

How does it guarantee it? Here is text from Preshing:

<img width="698" alt="Screen Shot 2022-12-21 at 12 59 29 PM" src="https://user-images.githubusercontent.com/10248304/209001805-00c186d1-92ca-4dcb-8d53-78bbe1be5cf0.PNG">

> In the previous example, we saw how the last line of SendTestMessage synchronized-with the first line of TryReceiveMessage. But don’t fall into the trap of thinking that synchronizes-with is a relationship between statements in your source code. It isn’t! It’s a relationship between operations which occur at runtime, based on those statements.
> 
> This distinction is important, and should really be obvious when you think about it. A single source code statement can execute any number of times in a running process. And if TryReceiveMessage is called too early – before Thread 1’s store to g_guard is visible – there will be no synchronizes-with relationship whatsoever.

<img width="709" alt="Screen Shot 2022-12-21 at 12 55 04 PM" src="https://user-images.githubusercontent.com/10248304/209001141-b109530c-3523-4324-9adb-3650094ca167.PNG">

I think this is easier to conceptualize with mutex locking and unlocking. This diagram illustrates the synchronizes-with relationship when Thread A gets to the mutex before Thread B

<img width="342" alt="Screen Shot 2022-12-21 at 12 55 30 PM" src="https://user-images.githubusercontent.com/10248304/209001383-1b6b2653-43f2-4d74-9a2c-9834abb42c1c.PNG">

But you would not have the same sychronizes-with relationship if Thread B got to the lock before Thread A, e.g. writes to x and y on A would not be visible to the reads on B

2023-01-03 20:44 UTC, friedmud commented
The way this works is based on `_execution_list_end`.  If you look at `PerfGraph::addToExecutionList` at the VERY end it does:

```
_execution_list_end.store(next_execution_list_end, std::memory_order_release);
```

That is the only moment where the print thread can see that the execution list has new data in it... and the `std::memory_order_release` guarantees that all modifications to the execution list will be published before the `std::memory_order_acquire` in `PerfGraphLivePrint::start()`.

Therefore - it is not possible for the print thread to read partially published data in the execution list.

2023-01-03 20:49 UTC, friedmud commented
One more try:

There is no possibility for PGLP to read a new value of `_execution_list_end` without everything that the new value allows access to being fully published to the PGLP.