Remove `-std=c++11` in framework and replace with `-std=c++17`
idaholab/moose pull request #20397
Opened 2022-02-24 16:19 UTC by cticenhour

This PR removes entries for the C++11 standard in compiler flags and replaces it with C++17. We should be covered during compilation by the definition of CXXFLAGS in our most-recent `moose-mpich` package, but this helps ensure that the default standard is C++17 for those who do not use our packages. 

Refs #20377

2022-02-24 16:21 UTC, cticenhour commented
@loganharbour we can merge this or leave it if you want. I just did a search and found these during our earlier discussion on Slack.

2022-02-24 16:21 UTC, loganharbour requested changes
I'm not sure if we're ready for this. We need a libmesh update to be able to enforce c++17 first, and we also need to change the requirements in documentation.

2022-02-24 19:26 UTC, loganharbour commented
@cticenhour wanna add a submodule update to https://github.com/libMesh/libmesh/commit/617928abf97fb44d6af0970b91c883e1428e1e8a in libmesh? And then update the docs?

2022-02-24 19:28 UTC, cticenhour commented
Yeah, I can do that. Might not be today, as I plan to take part of the afternoon as PL, but by Monday for sure.

2022-02-24 19:29 UTC, loganharbour commented
No worries, I'll get to it this afternoon then 👍🏼

2022-02-24 20:16 UTC, loganharbour requested changes
We still need to address https://github.com/idaholab/moose/blob/next/framework/doc/packages_config.yml; haven't gotten around to it

2022-02-24 20:20 UTC, moosebuild commented on libmesh
> +Subproject commit 617928abf97fb44d6af0970b91c883e1428e1e8a
**Caution!** This contains a submodule update

2022-02-24 20:20 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/967194/) on 3a4fd8d wanted to post the following:

The following file(s) are changed:

  conda/mpich/conda_build_config.yaml

The conda configuration has changed; ping @idaholab/moose-dev-ops

2022-02-24 20:20 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/967194/) on 3a4fd8d wanted to post the following:

The following file(s) are changed:

  conda/libmesh/meta.yaml

The libmesh conda configuration has changed; ping @idaholab/moose-dev-ops

2022-02-24 21:22 UTC, moosebuild commented
Job [Test timings](https://civet.inl.gov/job/967220/) on 3a4fd8d wanted to post the following:

View timings [here](https://mooseframework.inl.gov/docs/PRs/20397/timing)

This comment will be updated on new commits.

2022-02-24 23:09 UTC, moosebuild commented
Job [Coverage](https://civet.inl.gov/job/967215/) on 3a4fd8d wanted to post the following:


## Framework coverage

<table>
  <thead>
    <tr>
      <th></th>
      <th>bc2965</th>
      <th colspan=4>#20397 3a4fd8</th>
    </tr>
    <tr>
      <th></th>
      <th>Total</th>
      <th>Total</th>
      <th>+/-</th>
      <th>New</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><b>Rate</b></td>
      <td>82.34%</td>
      <td>82.34%</td>
      <td>+0.00%</td>
      <td>-</td>
    </tr>
    <tr>
      <td><b>Hits</b></td>
      <td>73848</td>
      <td>73862</td>
      <td>+14</td>
      <td>0</td>
    </tr>
    <tr>
      <td><b>Misses</b></td>
      <td>15840</td>
      <td>15841</td>
      <td>+1</td>
      <td>0</td>
    </tr>
  </tbody>
</table>

[Diff coverage report](https://mooseframework.inl.gov/docs/PRs/20397/coverage_diff/framework.html)

[Full coverage report](https://mooseframework.inl.gov/docs/PRs/20397/coverage/framework)


## Modules coverage

### Contact

<table>
  <thead>
    <tr>
      <th></th>
      <th>bc2965</th>
      <th colspan=4>#20397 3a4fd8</th>
    </tr>
    <tr>
      <th></th>
      <th>Total</th>
      <th>Total</th>
      <th>+/-</th>
      <th>New</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><b>Rate</b></td>
      <td>89.03%</td>
      <td>89.04%</td>
      <td>+0.00%</td>
      <td>-</td>
    </tr>
    <tr>
      <td><b>Hits</b></td>
      <td>2841</td>
      <td>2842</td>
      <td>+1</td>
      <td>0</td>
    </tr>
    <tr>
      <td><b>Misses</b></td>
      <td>350</td>
      <td>350</td>
      <td>-</td>
      <td>0</td>
    </tr>
  </tbody>
</table>

[Diff coverage report](https://mooseframework.inl.gov/docs/PRs/20397/coverage_diff/contact.html)

[Full coverage report](https://mooseframework.inl.gov/docs/PRs/20397/coverage/contact)

### Heat conduction

<table>
  <thead>
    <tr>
      <th></th>
      <th>bc2965</th>
      <th colspan=4>#20397 3a4fd8</th>
    </tr>
    <tr>
      <th></th>
      <th>Total</th>
      <th>Total</th>
      <th>+/-</th>
      <th>New</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><b>Rate</b></td>
      <td>89.52%</td>
      <td>89.50%</td>
      <td>-0.03%</td>
      <td>-</td>
    </tr>
    <tr>
      <td><b>Hits</b></td>
      <td>2991</td>
      <td>2991</td>
      <td>-</td>
      <td>0</td>
    </tr>
    <tr>
      <td><b>Misses</b></td>
      <td>350</td>
      <td>351</td>
      <td>+1</td>
      <td>0</td>
    </tr>
  </tbody>
</table>

[Diff coverage report](https://mooseframework.inl.gov/docs/PRs/20397/coverage_diff/heat_conduction.html)

[Full coverage report](https://mooseframework.inl.gov/docs/PRs/20397/coverage/heat_conduction)

### Navier stokes

<table>
  <thead>
    <tr>
      <th></th>
      <th>bc2965</th>
      <th colspan=4>#20397 3a4fd8</th>
    </tr>
    <tr>
      <th></th>
      <th>Total</th>
      <th>Total</th>
      <th>+/-</th>
      <th>New</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><b>Rate</b></td>
      <td>83.61%</td>
      <td>83.62%</td>
      <td>+0.00%</td>
      <td>-</td>
    </tr>
    <tr>
      <td><b>Hits</b></td>
      <td>8348</td>
      <td>8349</td>
      <td>+1</td>
      <td>0</td>
    </tr>
    <tr>
      <td><b>Misses</b></td>
      <td>1636</td>
      <td>1636</td>
      <td>-</td>
      <td>0</td>
    </tr>
  </tbody>
</table>

[Diff coverage report](https://mooseframework.inl.gov/docs/PRs/20397/coverage_diff/navier_stokes.html)

[Full coverage report](https://mooseframework.inl.gov/docs/PRs/20397/coverage/navier_stokes)

### Peridynamics

<table>
  <thead>
    <tr>
      <th></th>
      <th>bc2965</th>
      <th colspan=4>#20397 3a4fd8</th>
    </tr>
    <tr>
      <th></th>
      <th>Total</th>
      <th>Total</th>
      <th>+/-</th>
      <th>New</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><b>Rate</b></td>
      <td>79.20%</td>
      <td>79.10%</td>
      <td>-0.10%</td>
      <td>-</td>
    </tr>
    <tr>
      <td><b>Hits</b></td>
      <td>3039</td>
      <td>3036</td>
      <td>-3</td>
      <td>0</td>
    </tr>
    <tr>
      <td><b>Misses</b></td>
      <td>798</td>
      <td>802</td>
      <td>+4</td>
      <td>0</td>
    </tr>
  </tbody>
</table>

[Diff coverage report](https://mooseframework.inl.gov/docs/PRs/20397/coverage_diff/peridynamics.html)

[Full coverage report](https://mooseframework.inl.gov/docs/PRs/20397/coverage/peridynamics)

### Phase field

<table>
  <thead>
    <tr>
      <th></th>
      <th>bc2965</th>
      <th colspan=4>#20397 3a4fd8</th>
    </tr>
    <tr>
      <th></th>
      <th>Total</th>
      <th>Total</th>
      <th>+/-</th>
      <th>New</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><b>Rate</b></td>
      <td>90.21%</td>
      <td>90.18%</td>
      <td>-0.03%</td>
      <td>-</td>
    </tr>
    <tr>
      <td><b>Hits</b></td>
      <td>11973</td>
      <td>11984</td>
      <td>+11</td>
      <td>0</td>
    </tr>
    <tr>
      <td><b>Misses</b></td>
      <td>1300</td>
      <td>1305</td>
      <td>+5</td>
      <td>0</td>
    </tr>
  </tbody>
</table>

[Diff coverage report](https://mooseframework.inl.gov/docs/PRs/20397/coverage_diff/phase_field.html)

[Full coverage report](https://mooseframework.inl.gov/docs/PRs/20397/coverage/phase_field)

### Porous flow

<table>
  <thead>
    <tr>
      <th></th>
      <th>bc2965</th>
      <th colspan=4>#20397 3a4fd8</th>
    </tr>
    <tr>
      <th></th>
      <th>Total</th>
      <th>Total</th>
      <th>+/-</th>
      <th>New</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><b>Rate</b></td>
      <td>96.23%</td>
      <td>96.23%</td>
      <td>+0.00%</td>
      <td>-</td>
    </tr>
    <tr>
      <td><b>Hits</b></td>
      <td>10531</td>
      <td>10544</td>
      <td>+13</td>
      <td>0</td>
    </tr>
    <tr>
      <td><b>Misses</b></td>
      <td>413</td>
      <td>413</td>
      <td>-</td>
      <td>0</td>
    </tr>
  </tbody>
</table>

[Diff coverage report](https://mooseframework.inl.gov/docs/PRs/20397/coverage_diff/porous_flow.html)

[Full coverage report](https://mooseframework.inl.gov/docs/PRs/20397/coverage/porous_flow)

### Ray tracing

<table>
  <thead>
    <tr>
      <th></th>
      <th>bc2965</th>
      <th colspan=4>#20397 3a4fd8</th>
    </tr>
    <tr>
      <th></th>
      <th>Total</th>
      <th>Total</th>
      <th>+/-</th>
      <th>New</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><b>Rate</b></td>
      <td>94.96%</td>
      <td>94.96%</td>
      <td>+0.00%</td>
      <td>-</td>
    </tr>
    <tr>
      <td><b>Hits</b></td>
      <td>4088</td>
      <td>4091</td>
      <td>+3</td>
      <td>0</td>
    </tr>
    <tr>
      <td><b>Misses</b></td>
      <td>217</td>
      <td>217</td>
      <td>-</td>
      <td>0</td>
    </tr>
  </tbody>
</table>

[Diff coverage report](https://mooseframework.inl.gov/docs/PRs/20397/coverage_diff/ray_tracing.html)

[Full coverage report](https://mooseframework.inl.gov/docs/PRs/20397/coverage/ray_tracing)

### Richards

<table>
  <thead>
    <tr>
      <th></th>
      <th>bc2965</th>
      <th colspan=4>#20397 3a4fd8</th>
    </tr>
    <tr>
      <th></th>
      <th>Total</th>
      <th>Total</th>
      <th>+/-</th>
      <th>New</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><b>Rate</b></td>
      <td>97.64%</td>
      <td>97.61%</td>
      <td>-0.03%</td>
      <td>-</td>
    </tr>
    <tr>
      <td><b>Hits</b></td>
      <td>3346</td>
      <td>3346</td>
      <td>-</td>
      <td>0</td>
    </tr>
    <tr>
      <td><b>Misses</b></td>
      <td>81</td>
      <td>82</td>
      <td>+1</td>
      <td>0</td>
    </tr>
  </tbody>
</table>

[Diff coverage report](https://mooseframework.inl.gov/docs/PRs/20397/coverage_diff/richards.html)

[Full coverage report](https://mooseframework.inl.gov/docs/PRs/20397/coverage/richards)

### Tensor mechanics

<table>
  <thead>
    <tr>
      <th></th>
      <th>bc2965</th>
      <th colspan=4>#20397 3a4fd8</th>
    </tr>
    <tr>
      <th></th>
      <th>Total</th>
      <th>Total [...]

2022-02-27 23:58 UTC, loganharbour commented
Nice. Looks like this is good to go other than https://github.com/idaholab/moose/pull/20397#pullrequestreview-892950550.

2022-02-28 13:57 UTC, milljm approved these changes, later dismissed
👍

2022-02-28 22:32 UTC, roystgnr commented
What all is left to be done here?  Just bumping up to `minimum_gcc: 7.5.0`, `minimum_clang: 5.0.2`, `minimum_intel: 19.0.1` in packages_config.yml?

2022-03-01 01:12 UTC, loganharbour commented
@roystgnr nothing is left now.

2022-03-01 01:13 UTC, loganharbour submitted a review, later dismissed
Approving changes that are not my own.

2022-03-01 01:13 UTC, moosebuild commented on libmesh
> +Subproject commit 617928abf97fb44d6af0970b91c883e1428e1e8a
**Caution!** This contains a submodule update

2022-03-01 01:13 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/970374/) on abd6953 wanted to post the following:

The following file(s) are changed:

  conda/mpich/conda_build_config.yaml

The conda configuration has changed; ping @idaholab/moose-dev-ops

2022-03-01 01:13 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/970374/) on abd6953 wanted to post the following:

The following file(s) are changed:

  conda/libmesh/meta.yaml

The libmesh conda configuration has changed; ping @idaholab/moose-dev-ops

2022-03-01 16:03 UTC, roystgnr commented
I'm pretty confident that this PR didn't cause `test:pressure_bc.inclined_edge_2d_pressure FAILED (EXODIFF)` in Valgrind xfem, but all the other tests are `MooseDocs.common.exceptions.MooseDocsException: The following command combination is unknown: 'package minimum_clang'.` and that actually looks like it might be our fault...

2022-03-01 16:06 UTC, cticenhour commented
Yeah, Logan discovered late last night that removing the whole package extension might be premature considering that it has been useful in propagating our minimum requirements through the documentation. The other results might be the random failures we've been seeing lately.

2022-03-01 16:08 UTC, roystgnr commented
Yeah, that's our fault.  Assuming we really want to go through with #20424 (and do we? maybe "we" manage our packages with conda, but it'd be really nice if that was a convenience not a requirement; "apt install mooseframework" would be nice to do someday and it's never going to happen if it requires conda), we need to grep through the remaining docs for `minimum_clang` etc. and replace those invocations.

2022-03-01 16:16 UTC, cticenhour commented
We went back and forth with it yesterday; an ideal world to me would be tying the versions of our conda dependencies to the documentation in a similar way as the package extension did with the old `moose-environment` package. One problem with keeping the current extension around as it is....it affects our manual installation instructions (which may be woefully out of date at this point) and just de-couples things from our well-tested configurations.

2022-03-01 16:27 UTC, loganharbour commented
I do plan on retaining the package extension now - it’ll just store less information (compilers, mpich, petsc, maybe libmesh). I’ll get around to that today.

2022-03-02 16:10 UTC, lindsayad commented
Anything I can do to help here? I'd be inclined to limit that xfem test to one timestep as it's doing everything interesting in the first timestep anyways and then after that there's barely anything to solve

2022-03-02 16:17 UTC, loganharbour commented
I'm finishing up the documentation stuff right now; should be good soon. Not sure what's going on with xfem... doesn't look deterministic

2022-03-02 16:19 UTC, lindsayad commented
It's probably not, that's why I think we should change the test at some point (doesn't have to be here)

2022-03-02 17:55 UTC, moosebuild commented on libmesh
> +Subproject commit 617928abf97fb44d6af0970b91c883e1428e1e8a
**Caution!** This contains a submodule update

2022-03-02 17:55 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/972941/) on adddd4c wanted to post the following:

The following file(s) are changed:

  conda/mpich/conda_build_config.yaml

The conda configuration has changed; ping @idaholab/moose-dev-ops

2022-03-02 17:55 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/972941/) on adddd4c wanted to post the following:

The following file(s) are changed:

  conda/libmesh/meta.yaml

The libmesh conda configuration has changed; ping @idaholab/moose-dev-ops

2022-03-02 20:33 UTC, cticenhour commented on modules/doc/content/newsletter/2022_03.md
> +
LGTM! 👍🏻

2022-03-02 20:34 UTC, loganharbour approved these changes
Approving changes that are not my own.

2022-03-02 20:34 UTC, milljm approved these changes

2022-03-02 20:34 UTC, moosebuild commented on libmesh
> +Subproject commit a7279e6a5f0ea1f621d894c55a771197241f8708
**Caution!** This contains a submodule update

2022-03-02 20:34 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/973423/) on f6a5796 wanted to post the following:

The following file(s) are changed:

  conda/mpich/conda_build_config.yaml

The conda configuration has changed; ping @idaholab/moose-dev-ops

2022-03-02 20:35 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/973423/) on f6a5796 wanted to post the following:

The following file(s) are changed:

  conda/libmesh/meta.yaml

The libmesh conda configuration has changed; ping @idaholab/moose-dev-ops

2022-03-02 21:26 UTC, lindsayad approved these changes

2022-03-03 01:41 UTC, merged