Option to explicitly provide mardown file location for objects
idaholab/moose pull request #20418
Opened 2022-02-28 20:54 UTC by zachmprince

Closes #20405

2022-02-28 22:05 UTC, moosebuild commented
Job [Documentation](https://civet.inl.gov/job/969868/) on fa91108 wanted to post the following:

View the site [here](https://mooseframework.inl.gov/docs/PRs/20418/site)

This comment will be updated on new commits.

2022-02-28 23:11 UTC, cticenhour requested changes
I like this well enough - especially since it allows app-level differences based on unique need. Would prefer in the long run something that can autodetect so we wouldn't need to manually set things, but this is not unlike the other customization we do in this extension. One suggested change noted.

2022-02-28 23:11 UTC, cticenhour commented on python/MooseDocs/extensions/appsyntax.py
> +                             "A `dict` or `dict` of `dict` including markdown files to explicitly set markdown reference (key='syntax', value='file.md')")
```suggestion
        config['markdown'] = (None,
                             "A `dict` or `dict` of `dict` including markdown files to explicitly set a custom, additional markdown reference (key='syntax', value='file.md')")
```

Would like to make it clear in the description for developers that this is custom and in addition to the tree we already build.

2022-02-28 23:28 UTC, moosebuild commented
Job [Coverage](https://civet.inl.gov/job/969891/) on fa91108 wanted to post the following:


## Framework coverage

Coverage did not change


## Modules coverage

Coverage did not change

## Full coverage reports

<details>
<summary>Reports</summary>

- [`framework`](https://mooseframework.inl.gov/docs/PRs/20418/coverage/framework)
- [`chemical_reactions`](https://mooseframework.inl.gov/docs/PRs/20418/coverage/chemical_reactions)
- [`combined`](https://mooseframework.inl.gov/docs/PRs/20418/coverage/combined)
- [`contact`](https://mooseframework.inl.gov/docs/PRs/20418/coverage/contact)
- [`external_petsc_solver`](https://mooseframework.inl.gov/docs/PRs/20418/coverage/external_petsc_solver)
- [`fluid_properties`](https://mooseframework.inl.gov/docs/PRs/20418/coverage/fluid_properties)
- [`fsi`](https://mooseframework.inl.gov/docs/PRs/20418/coverage/fsi)
- [`functional_expansion_tools`](https://mooseframework.inl.gov/docs/PRs/20418/coverage/functional_expansion_tools)
- [`geochemistry`](https://mooseframework.inl.gov/docs/PRs/20418/coverage/geochemistry)
- [`heat_conduction`](https://mooseframework.inl.gov/docs/PRs/20418/coverage/heat_conduction)
- [`level_set`](https://mooseframework.inl.gov/docs/PRs/20418/coverage/level_set)
- [`misc`](https://mooseframework.inl.gov/docs/PRs/20418/coverage/misc)
- [`navier_stokes`](https://mooseframework.inl.gov/docs/PRs/20418/coverage/navier_stokes)
- [`peridynamics`](https://mooseframework.inl.gov/docs/PRs/20418/coverage/peridynamics)
- [`phase_field`](https://mooseframework.inl.gov/docs/PRs/20418/coverage/phase_field)
- [`porous_flow`](https://mooseframework.inl.gov/docs/PRs/20418/coverage/porous_flow)
- [`ray_tracing`](https://mooseframework.inl.gov/docs/PRs/20418/coverage/ray_tracing)
- [`rdg`](https://mooseframework.inl.gov/docs/PRs/20418/coverage/rdg)
- [`reactor`](https://mooseframework.inl.gov/docs/PRs/20418/coverage/reactor)
- [`richards`](https://mooseframework.inl.gov/docs/PRs/20418/coverage/richards)
- [`stochastic_tools`](https://mooseframework.inl.gov/docs/PRs/20418/coverage/stochastic_tools)
- [`tensor_mechanics`](https://mooseframework.inl.gov/docs/PRs/20418/coverage/tensor_mechanics)
- [`thermal_hydraulics`](https://mooseframework.inl.gov/docs/PRs/20418/coverage/thermal_hydraulics)
- [`xfem`](https://mooseframework.inl.gov/docs/PRs/20418/coverage/xfem)

</details>



This comment will be updated on new commits.

2022-03-01 00:19 UTC, zachmprince commented
Thanks @cticenhour. I committed your suggestion. I agree, auto-detection would be great. I had ideas for this including looking in multiple places based on the file name, class name, and moose-object name. But I couldn't resolve how to pick the right file if more than one existed. I figure this is probably the way to go for now, since it worked 99.9% of the time before this.

2022-03-01 00:21 UTC, cticenhour approved these changes

2022-03-01 00:22 UTC, cticenhour commented
Sometimes, I think, it is best to start with a manual option just so we don't miss a corner case we didn't intend to. Thanks for tackling this @zachmprince!

2022-03-01 05:03 UTC, merged