Add rotation option to PCCMGBase
idaholab/moose pull request #20516
Opened 2022-03-09 17:51 UTC by miaoyinb

closes #20514

## Reason

## Design

## Impact

2022-03-09 19:05 UTC, moosebuild commented
Job [Documentation](https://civet.inl.gov/job/979767/) on d967611 wanted to post the following:

View the site [here](https://mooseframework.inl.gov/docs/PRs/20516/site)

This comment will be updated on new commits.

2022-03-09 20:28 UTC, moosebuild commented
Job [Coverage](https://civet.inl.gov/job/979775/) on d967611 wanted to post the following:


## Framework coverage

Coverage did not change


## Modules coverage

### Reactor

<table>
  <thead>
    <tr>
      <th></th>
      <th>43edd7</th>
      <th colspan=4>#20516 d96761</th>
    </tr>
    <tr>
      <th></th>
      <th>Total</th>
      <th>Total</th>
      <th>+/-</th>
      <th>New</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><b>Rate</b></td>
      <td>95.39%</td>
      <td>95.41%</td>
      <td>+0.02%</td>
      <td>100.00%</td>
    </tr>
    <tr>
      <td><b>Hits</b></td>
      <td>1966</td>
      <td>1975</td>
      <td>+9</td>
      <td>9</td>
    </tr>
    <tr>
      <td><b>Misses</b></td>
      <td>95</td>
      <td>95</td>
      <td>-</td>
      <td>0</td>
    </tr>
  </tbody>
</table>

[Diff coverage report](https://mooseframework.inl.gov/docs/PRs/20516/coverage_diff/reactor.html)

[Full coverage report](https://mooseframework.inl.gov/docs/PRs/20516/coverage/reactor)

## Full coverage reports

<details>
<summary>Reports</summary>

- [`framework`](https://mooseframework.inl.gov/docs/PRs/20516/coverage/framework)
- [`chemical_reactions`](https://mooseframework.inl.gov/docs/PRs/20516/coverage/chemical_reactions)
- [`combined`](https://mooseframework.inl.gov/docs/PRs/20516/coverage/combined)
- [`contact`](https://mooseframework.inl.gov/docs/PRs/20516/coverage/contact)
- [`external_petsc_solver`](https://mooseframework.inl.gov/docs/PRs/20516/coverage/external_petsc_solver)
- [`fluid_properties`](https://mooseframework.inl.gov/docs/PRs/20516/coverage/fluid_properties)
- [`fsi`](https://mooseframework.inl.gov/docs/PRs/20516/coverage/fsi)
- [`functional_expansion_tools`](https://mooseframework.inl.gov/docs/PRs/20516/coverage/functional_expansion_tools)
- [`geochemistry`](https://mooseframework.inl.gov/docs/PRs/20516/coverage/geochemistry)
- [`heat_conduction`](https://mooseframework.inl.gov/docs/PRs/20516/coverage/heat_conduction)
- [`level_set`](https://mooseframework.inl.gov/docs/PRs/20516/coverage/level_set)
- [`misc`](https://mooseframework.inl.gov/docs/PRs/20516/coverage/misc)
- [`navier_stokes`](https://mooseframework.inl.gov/docs/PRs/20516/coverage/navier_stokes)
- [`peridynamics`](https://mooseframework.inl.gov/docs/PRs/20516/coverage/peridynamics)
- [`phase_field`](https://mooseframework.inl.gov/docs/PRs/20516/coverage/phase_field)
- [`porous_flow`](https://mooseframework.inl.gov/docs/PRs/20516/coverage/porous_flow)
- [`ray_tracing`](https://mooseframework.inl.gov/docs/PRs/20516/coverage/ray_tracing)
- [`rdg`](https://mooseframework.inl.gov/docs/PRs/20516/coverage/rdg)
- [`reactor`](https://mooseframework.inl.gov/docs/PRs/20516/coverage/reactor)
- [`richards`](https://mooseframework.inl.gov/docs/PRs/20516/coverage/richards)
- [`stochastic_tools`](https://mooseframework.inl.gov/docs/PRs/20516/coverage/stochastic_tools)
- [`tensor_mechanics`](https://mooseframework.inl.gov/docs/PRs/20516/coverage/tensor_mechanics)
- [`thermal_hydraulics`](https://mooseframework.inl.gov/docs/PRs/20516/coverage/thermal_hydraulics)
- [`xfem`](https://mooseframework.inl.gov/docs/PRs/20516/coverage/xfem)

</details>



This comment will be updated on new commits.

2022-03-09 20:48 UTC, miaoyinb commented
@eshemon @shikhar413 FYI

@loganharbour @GiudGiud  Simple update to add a new feature to avert use of `TransformGenerator` after PCCMG. Thanks.

2022-03-09 20:51 UTC, GiudGiud approved these changes, later dismissed

2022-03-09 23:35 UTC, loganharbour requested changes

2022-03-10 14:51 UTC, miaoyinb commented
Ready for your review again @loganharbour

2022-03-10 17:30 UTC, loganharbour approved these changes

2022-03-10 17:30 UTC, merged

2022-03-10 17:32 UTC, miaoyinb commented
Thanks @loganharbour @GiudGiud