Documentation and test fixes
idaholab/moose pull request #20525
Opened 2022-03-10 06:45 UTC by GiudGiud

Need to rework commit history
Need to pass tests :)

2022-03-10 07:56 UTC, moosebuild commented
Job [Documentation](https://civet.inl.gov/job/980779/) on eed7259 wanted to post the following:

View the site [here](https://mooseframework.inl.gov/docs/PRs/20525/site)

This comment will be updated on new commits.

2022-03-10 09:24 UTC, moosebuild commented
Job [Coverage](https://civet.inl.gov/job/980802/) on eed7259 wanted to post the following:


## Framework coverage

<table>
  <thead>
    <tr>
      <th></th>
      <th>decd40</th>
      <th colspan=4>#20525 eed725</th>
    </tr>
    <tr>
      <th></th>
      <th>Total</th>
      <th>Total</th>
      <th>+/-</th>
      <th>New</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><b>Rate</b></td>
      <td>82.42%</td>
      <td>82.41%</td>
      <td>-0.00%</td>
      <td>83.33%</td>
    </tr>
    <tr>
      <td><b>Hits</b></td>
      <td>73437</td>
      <td>73440</td>
      <td>+3</td>
      <td>5</td>
    </tr>
    <tr>
      <td><b>Misses</b></td>
      <td>15669</td>
      <td>15670</td>
      <td>+1</td>
      <td>1</td>
    </tr>
  </tbody>
</table>

[Diff coverage report](https://mooseframework.inl.gov/docs/PRs/20525/coverage_diff/framework.html)

[Full coverage report](https://mooseframework.inl.gov/docs/PRs/20525/coverage/framework)


## Modules coverage

Coverage did not change

## Full coverage reports

<details>
<summary>Reports</summary>

- [`framework`](https://mooseframework.inl.gov/docs/PRs/20525/coverage/framework)
- [`chemical_reactions`](https://mooseframework.inl.gov/docs/PRs/20525/coverage/chemical_reactions)
- [`combined`](https://mooseframework.inl.gov/docs/PRs/20525/coverage/combined)
- [`contact`](https://mooseframework.inl.gov/docs/PRs/20525/coverage/contact)
- [`external_petsc_solver`](https://mooseframework.inl.gov/docs/PRs/20525/coverage/external_petsc_solver)
- [`fluid_properties`](https://mooseframework.inl.gov/docs/PRs/20525/coverage/fluid_properties)
- [`fsi`](https://mooseframework.inl.gov/docs/PRs/20525/coverage/fsi)
- [`functional_expansion_tools`](https://mooseframework.inl.gov/docs/PRs/20525/coverage/functional_expansion_tools)
- [`geochemistry`](https://mooseframework.inl.gov/docs/PRs/20525/coverage/geochemistry)
- [`heat_conduction`](https://mooseframework.inl.gov/docs/PRs/20525/coverage/heat_conduction)
- [`level_set`](https://mooseframework.inl.gov/docs/PRs/20525/coverage/level_set)
- [`misc`](https://mooseframework.inl.gov/docs/PRs/20525/coverage/misc)
- [`navier_stokes`](https://mooseframework.inl.gov/docs/PRs/20525/coverage/navier_stokes)
- [`peridynamics`](https://mooseframework.inl.gov/docs/PRs/20525/coverage/peridynamics)
- [`phase_field`](https://mooseframework.inl.gov/docs/PRs/20525/coverage/phase_field)
- [`porous_flow`](https://mooseframework.inl.gov/docs/PRs/20525/coverage/porous_flow)
- [`ray_tracing`](https://mooseframework.inl.gov/docs/PRs/20525/coverage/ray_tracing)
- [`rdg`](https://mooseframework.inl.gov/docs/PRs/20525/coverage/rdg)
- [`reactor`](https://mooseframework.inl.gov/docs/PRs/20525/coverage/reactor)
- [`richards`](https://mooseframework.inl.gov/docs/PRs/20525/coverage/richards)
- [`stochastic_tools`](https://mooseframework.inl.gov/docs/PRs/20525/coverage/stochastic_tools)
- [`tensor_mechanics`](https://mooseframework.inl.gov/docs/PRs/20525/coverage/tensor_mechanics)
- [`thermal_hydraulics`](https://mooseframework.inl.gov/docs/PRs/20525/coverage/thermal_hydraulics)
- [`xfem`](https://mooseframework.inl.gov/docs/PRs/20525/coverage/xfem)

</details>

## Warnings

- `framework` new line coverage rate 83.33% is less than the suggested 90.0%



This comment will be updated on new commits.

2022-03-12 00:45 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/982181/) on 1288a92 wanted to post the following:

Your code requires style changes.  

A patch was auto generated and copied [here](https://mooseframework.inl.gov/docs/PRs/20525/style.patch)  
You can directly apply the patch by running, in the top level of your repository:

`curl -s https://mooseframework.inl.gov/docs/PRs/20525/style.patch | git apply -v`  

Alternatively, with your repository up to date and in the top level of your repository:

`git clang-format 2f149d0299277a6692b6976693d2669b94a272de`

2022-03-24 21:35 UTC, GiudGiud commented
If any of the 8 people requested for review need a chill PR to taper off into the weekend... this is it

2022-03-24 21:49 UTC, cticenhour commented
Working on this now....almost done.

2022-03-24 21:50 UTC, cticenhour requested changes

2022-03-24 21:50 UTC, cticenhour commented on framework/doc/content/source/variables/MooseVariableFE.md
> +!! MOOSE Documentation Stub: Remove this line when content is added.
```suggestion
!alert construction title=Undocumented
```

2022-03-24 21:50 UTC, cticenhour commented on framework/doc/content/source/vectorpostprocessors/CSVReader.md
> +In this example, the `example.csv` file containings data for year/month/day is being read by
```suggestion
In this example, the `example.csv` file containing data for year/month/day is being read by
```

2022-03-24 21:50 UTC, cticenhour commented on framework/doc/content/source/vectorpostprocessors/LineMaterialRealSampler.md
> +- columns are ordered by alphabetical order of the properties sampled. The distance along the sampled line, and the x, y and z coordinates of the sampled points are added to the output as additional
```suggestion
- columns are ordered by alphabetical order of the properties sampled. The distance along the sampled line and the x, y and z coordinates of the sampled points are added to the output as additional columns.
```

2022-03-28 05:01 UTC, GiudGiud commented on framework/doc/content/source/outputs/OutputWarehouse.md
> +!! MOOSE Documentation Stub: Remove this line when content is added.
Sure lemme know if you want the rest of the stub. It's very temporary, I'll fill those two last classes soon

2022-03-28 05:02 UTC, GiudGiud commented
@cticenhour thanks for the review! I merged all your suggestions in.

2022-03-28 13:25 UTC, cticenhour commented on framework/doc/content/source/outputs/OutputWarehouse.md
> +!! MOOSE Documentation Stub: Remove this line when content is added.
Leaving the rest of it in should be fine!

2022-03-28 13:25 UTC, cticenhour approved these changes

2022-03-28 13:26 UTC, merged

2022-06-20 23:58 UTC, GiudGiud commented
Refs #20540 #18333 #20510 #20522 #15283 #20071 #20535 #17478