Change unused_param check default to Error
idaholab/moose pull request #20568
Opened 2022-03-16 00:16 UTC by jiangwen84

closes #20567

## Reason

## Design

## Impact

2022-03-16 02:43 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/984917/) on 855e08f : invalidated by @jiangwen84

2022-03-20 02:33 UTC, GiudGiud commented
@idaholab/moose-ccb opinions on this? This does have pretty big consequences.

I very much like being able to change input parameters, to try out things, and not worry about what becomes unused
I also end up debugging people's inputs where they had a mispelled parameter and it only returned a warning, and the wrong result
So overall I'm in favor of this, even though it could be a possible burden on users.

2022-03-20 16:29 UTC, lindsayad commented
I think @aprilnovak had some concerns about this

2022-03-21 15:10 UTC, gardnerru commented
I expected this to be contentious. Here is more background.

This was found when I was setting up a very large Monte Carlo with BISON. I made a BISON input, with the proper parameters, and tested it. I then made the driver file and tested it with a small sample size. This ran and the SamplerData CSV output showed that the params were changing as expected. With this, and that I know that BISON errors on unused, I felt my diligence was done. Turns out that there was a typo in the MC driver file that was trying to pass an unusable parameter to the BISON input, and MOOSE overrode BISON and tossed a warning. I know that someone here is going to say that I should have read my logs better. That might be so, but I wasnt expecting a behavior change and I would still be here when I saw it.  

Multiapp might be a special case but at the very least here, the MOOSE main app should use whatever the sub's defaults are. This is a trap.

Does anyone have an _actual_ reason for having an unused parameter in their input file? I get it for the old days but when you are moving more in to production, allowing unused seems like a bad idea. End of soap box.

2022-03-21 15:37 UTC, friedmud commented
Firstly, a question: @gardnerru , what app were you actually running as your main app (as in, what app did you run on the command-line?).

Secondly: I think I agree here (although I feel like I was on the other side of this when it was first decided).  The issue surrounds swapping out objects.  For instance, the current behavior is useful if you want to swap from a `FluxBC` to a `NeumannBC` and then have the ability to swap back (without commenting a bunch of stuff out and then uncommenting).

However, this just isn't the norm to do anymore.  People are changing their objects much less often these days.  The only case I can think of where people would do this often is in the Material system (swapping in and out simpler solid-mechanics materials for instance).... and if BISON has already had this as an error for a long time and no one has complained then it must be "fine".

I also think that the current behavior was useful for Peacock... which just left old parameters hanging around when you would swap objects - so that you could swap them back.  But no one uses that anyway......

I'm for changing this to be an error (until someone has a good argument in the other direction!).

2022-03-21 15:56 UTC, gardnerru commented
./bison-opt -i monte_carlo.i , where monte_carlo.i is a Stochastic module input calling a BISON input.

Hehe, using BISON as the gold standard? Careful, we might get a big head.

2022-03-21 16:02 UTC, aprilnovak commented
Thanks @lindsayad, yes this would negatively impact my workflow. I use very complex, multi-application models that share some common input. Say, Apps 1 and 2 need a parameter `diameter`, whereas Apps 2 and 3 need a parameter `conductivity`. Rather than try to remember precisely where each parameter is used in my inputs (in case I want to change them), I have a `common_input.i` that I pass via the command line to the various input files that need it, like this:

```
cardinal-opt -i common_input model.i
```

This will give unused parameter warnings, since some application inputs only need a subset of the parameters. I think from Slack I learned that I can always set a different warn/error setting in Cardinal, but I'm not sure if I could then use my `common_input.i` if I'm, say, dynamically linking to a BISON input which does set the error.

I'd be okay with this change if the preamble constants at the top of a file could be ignored.

2022-03-21 17:38 UTC, tophmatthews commented
+1 to @aprilnovak , I do the same thing (though not so complicated) and it's a pain for these out-of-block lines (or whatever they are called when they're not in []). However, the error in BISON for input parameters not being necessary has saved me in the past, so I think @aprilnovak has the right balance.

2022-03-21 17:48 UTC, lindsayad commented
I think an input file option controlling unused parameter warn/error would be sublime. Same with deprecation I think

2022-03-21 17:53 UTC, gardnerru commented
So set the moose default to error on unused params and then let the user command line flag if they need otherwise? Im fine with that. I think it may leave a small hole but it wont catch me. :)

2022-03-22 14:31 UTC, andrsd commented
Can we do an environment variable like `MOOSE_UNUSED_PARAMS={NONE|WARNING|ERROR}` and get the desired behavior via that?

2022-03-22 19:35 UTC, friedmud commented
@andrsd I don't see why we couldn't do that _as well_... no reason not to allow all the options.

2022-03-22 20:50 UTC, joshuahansel commented
> MOOSE overrode BISON and tossed a warning

Is there any reason we can't fix this part directly instead of changing defaults?

2022-03-22 20:53 UTC, joshuahansel commented
> I don't see why we couldn't do that as well... no reason not to allow all the options.

@friedmud I'd find it a bit confusing to have all of those options because it wouldn't be obvious which methods take precedence.

2022-03-22 20:56 UTC, GiudGiud commented
Precedence is:
Command line > input file > environment variable > app default
Any other order is wrong :)

2022-03-22 22:31 UTC, friedmud commented
@GiudGiud is correct.  That is how all such options should work.

2022-03-22 22:32 UTC, friedmud commented
More options are not bad - as long as the precedence is documented.

2022-03-31 14:22 UTC, bwspenc commented
I'll just chime in here in support of making error the default.

Regarding having an environment variable, I'm not aware of anything else in application execution that is controlled by environment variables. Do we actually have environment variables that control things like this now? I'd be opposed to having this be the only one, but if we have others already, then sure, do it.

2022-03-31 20:38 UTC, bwspenc commented
The downside to environment variables is that if we start using them widely, we're going to start having the program behave differently for different people. The switch we joke about to give different behavior for @tophmatthews will become a reality. I'm not saying there's never a place for it, but it will come back to bite us when somebody's complaining that a problem fails for them but it works just fine for us when we try running it. I can also see a developer with unused variables set to warnings in their environment variable checking in a test with an unused variable that fails when it runs on our build machines. Not the end of the world, but it could waste someone's time trying to figure out what's going on.

2022-04-01 00:38 UTC, permcody commented
We just need to create another environment variable in secret to overrule
all the others! I’m sure no abuse of such a system could occur as long as
we possess it.

On Thu, Mar 31, 2022 at 2:38 PM Ben Spencer ***@***.***>
wrote:

> The downside to environment variables is that if we start using them
> widely, we're going to start having the program behave differently for
> different people. The switch we joke about to give different behavior for
> @tophmatthews <https://github.com/tophmatthews> will become a reality.
> I'm not saying there's never a place for it, but it will come back to bite
> us when somebody's complaining that a problem fails for them but it works
> just fine for us when we try running it. I can also see a developer with
> unused variables set to warnings in their environment variable checking in
> a test with an unused variable that fails when it runs on our build
> machines. Not the end of the world, but it could waste someone's time
> trying to figure out what's going on.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/idaholab/moose/pull/20568#issuecomment-1085082058>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAXFOICQTGV7ZG5LHL4I6GDVCYEMPANCNFSM5Q2JMUKA>
> .
> You are receiving this because you are on a team that was mentioned.Message
> ID: ***@***.***>
>

2022-04-01 16:20 UTC, lindsayad commented
we could create a `IGNORE_ENVIRONMENT_VARIABLES` option for users, and then for system administrators who get tired of debugging cases where a user has set that, we could create for them a `IGNORE_IGNORE_ENVIRONMENT_VARIABLES`

2022-04-01 21:59 UTC, tophmatthews commented
> The switch we joke about to give different behavior for @tophmatthews will become a reality

I _KNEW_ IT!

2022-04-07 16:47 UTC, gardnerru commented
So what is the move here? Stock-holders vote or Thunderdome rules?

2022-04-07 17:41 UTC, lindsayad requested changes
While the default change is good, we must support being able to make unused parameters *not* errors

2022-04-20 19:41 UTC, gardnerru commented
@permcody was there a Tuesday morning chat about this?

2022-04-21 01:13 UTC, permcody commented
Nope… my fault. Many of us are back in the building. I’ll bring it up
tomorrow!

On Wed, Apr 20, 2022 at 1:41 PM Russell Gardner ***@***.***>
wrote:

> @permcody <https://github.com/permcody> was there a Tuesday morning chat
> about this?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/idaholab/moose/pull/20568#issuecomment-1104388367>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAXFOIB273G3AXB3XJDE2XTVGBMXPANCNFSM5Q2JMUKA>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2022-04-21 03:06 UTC, YaqiWang commented
I am late for this conversation but I am very supportive on what @bwspenc said on using environmental variables.

2022-05-03 17:24 UTC, GiudGiud commented
He forgot again. I ll remind him this afternoon haha

2022-05-03 21:31 UTC, lindsayad commented on test/tests/misc/jacobian/simple.i
> -    error = factor
what was the reason for this change?

2022-05-03 21:32 UTC, lindsayad commented
we're changing the default to error, but we need to allow downgrading. @socratesgorilla I think is going to try to push that change soon

2022-05-03 22:45 UTC, permcody commented
@socratesgorilla - This is the PR that I was talking about in staff meeting. Need to get it over the finish line.

2022-05-05 21:56 UTC, GiudGiud commented
Can you please double check that `allow_unused` in tests configuration works? Having issues with this.
maybe it s not a thing

2022-06-07 16:49 UTC, gardnerru commented
Asleep just before the finish line? I feel that I read a story like this a long time ago

2022-06-11 01:30 UTC, permcody commented
@socratesgorilla?

On Tue, Jun 7, 2022 at 10:49 AM Russell Gardner ***@***.***>
wrote:

> Asleep just before the finish line? I feel that I read a story like this a
> long time ago
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/idaholab/moose/pull/20568#issuecomment-1148921147>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAXFOIGGAUYCXN7773ZZK33VN54QTANCNFSM5Q2JMUKA>
> .
> You are receiving this because you were assigned.Message ID:
> ***@***.***>
>

2022-06-13 16:31 UTC, socratesgorilla commented
Was working on this and then got sidetracked by moving stuff - taking another look now

2022-09-08 17:25 UTC, GiudGiud commented
@jiangwen84 can we close this?
https://github.com/idaholab/moose/pull/21821 was merged

2022-09-08 22:05 UTC, GiudGiud commented
Capability was merged in another PR

2022-09-08 22:05 UTC, closed without merging

2022-09-09 00:05 UTC, lindsayad commented
> Yes. Close it

![image](https://user-images.githubusercontent.com/10248304/189246142-9af45b04-f416-4c97-b4d0-0bbac154dc1e.png)

2022-10-11 07:13 UTC, lindsayad commented
I always like an option that you can check into version control such that
an input when cloned anywhere behaves more or less the same anywhere, e.g.
the input file option. But I would support having an environment variable
*in addition* ... which I think an input (or cli argument) would override

On Tue, Mar 22, 2022 at 7:31 AM David Andrs ***@***.***>
wrote:

> Can we do an environment variable like
> MOOSE_UNUSED_PARAMS={NONE|WARNING|ERROR} and get the desired behavior via
> that?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/idaholab/moose/pull/20568#issuecomment-1075257482>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ACOGA4CTNOXF3Y3XPT2TL73VBHKUXANCNFSM5Q2JMUKA>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2022-10-11 13:13 UTC, GiudGiud commented
so we want to be able to control this with:

- [ ] input file
- [ ] CLI
- [ ] environment variable

I think it's time many of our CLIs make it to the input file anyway?

2022-10-11 17:35 UTC, lindsayad commented
I thought we wanted to forego the environment variable option?

2022-10-12 14:16 UTC, friedmud commented
I wanted all the options - but I'll settle for just command-line for now.

2022-10-12 16:32 UTC, socratesgorilla commented
I don't know why this conversation is happening on a closed PR but I believe it works on CLI and input file for sure.