THM: Parallel Junction
idaholab/moose pull request #20578
Opened 2022-03-16 20:30 UTC by andrsd

Refs #19899

2022-03-16 20:47 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/985965/) on 180db9d wanted to post the following:

Your code requires style changes.  

A patch was auto generated and copied [here](https://mooseframework.inl.gov/docs/PRs/20578/style.patch)  
You can directly apply the patch by running, in the top level of your repository:

`curl -s https://mooseframework.inl.gov/docs/PRs/20578/style.patch | git apply -v`  

Alternatively, with your repository up to date and in the top level of your repository:

`git clang-format 4ab280bda315b1c517a87a11c3f0742caab75668`

2022-03-16 20:47 UTC, moosebuild commented on large_media
> +Subproject commit cfb8800f6c47ec0e57b921be199e4c68ca6e5f83
**Caution!** This contains a submodule update

2022-03-17 00:38 UTC, moosebuild commented
Job [Documentation](https://civet.inl.gov/job/986413/) on 8fc8d35 wanted to post the following:

View the site [here](https://mooseframework.inl.gov/docs/PRs/20578/site)

This comment will be updated on new commits.

2022-03-17 19:50 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/987275/) on 46bc2a9 wanted to post the following:

The following commit(s) contain fixups:

- 46bc2a97bd: fixup! Fixing GateValve1Phase to run in parallel
- 8b76fae375: fixup! Fix JunctionOneToOne to run in parallel
- cc8599c1d8: fixup! ParallelShim.h

2022-03-25 01:26 UTC, moosebuild commented
Job [Coverage](https://civet.inl.gov/job/994682/) on 42dcb5a wanted to post the following:


## Framework coverage

<table>
  <thead>
    <tr>
      <th></th>
      <th>71e154</th>
      <th colspan=4>#20578 42dcb5</th>
    </tr>
    <tr>
      <th></th>
      <th>Total</th>
      <th>Total</th>
      <th>+/-</th>
      <th>New</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><b>Rate</b></td>
      <td>82.55%</td>
      <td>82.55%</td>
      <td>+0.00%</td>
      <td>-</td>
    </tr>
    <tr>
      <td><b>Hits</b></td>
      <td>73692</td>
      <td>73693</td>
      <td>+1</td>
      <td>0</td>
    </tr>
    <tr>
      <td><b>Misses</b></td>
      <td>15580</td>
      <td>15579</td>
      <td>-1</td>
      <td>0</td>
    </tr>
  </tbody>
</table>

[Diff coverage report](https://mooseframework.inl.gov/docs/PRs/20578/coverage_diff/framework.html)

[Full coverage report](https://mooseframework.inl.gov/docs/PRs/20578/coverage/framework)


## Modules coverage

### Thermal hydraulics

<table>
  <thead>
    <tr>
      <th></th>
      <th>71e154</th>
      <th colspan=4>#20578 42dcb5</th>
    </tr>
    <tr>
      <th></th>
      <th>Total</th>
      <th>Total</th>
      <th>+/-</th>
      <th>New</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><b>Rate</b></td>
      <td>90.76%</td>
      <td>90.92%</td>
      <td>+0.16%</td>
      <td>96.41%</td>
    </tr>
    <tr>
      <td><b>Hits</b></td>
      <td>11598</td>
      <td>11702</td>
      <td>+104</td>
      <td>161</td>
    </tr>
    <tr>
      <td><b>Misses</b></td>
      <td>1181</td>
      <td>1169</td>
      <td>-12</td>
      <td>6</td>
    </tr>
  </tbody>
</table>

[Diff coverage report](https://mooseframework.inl.gov/docs/PRs/20578/coverage_diff/thermal_hydraulics.html)

[Full coverage report](https://mooseframework.inl.gov/docs/PRs/20578/coverage/thermal_hydraulics)

## Full coverage reports

<details>
<summary>Reports</summary>

- [`framework`](https://mooseframework.inl.gov/docs/PRs/20578/coverage/framework)
- [`chemical_reactions`](https://mooseframework.inl.gov/docs/PRs/20578/coverage/chemical_reactions)
- [`combined`](https://mooseframework.inl.gov/docs/PRs/20578/coverage/combined)
- [`contact`](https://mooseframework.inl.gov/docs/PRs/20578/coverage/contact)
- [`external_petsc_solver`](https://mooseframework.inl.gov/docs/PRs/20578/coverage/external_petsc_solver)
- [`fluid_properties`](https://mooseframework.inl.gov/docs/PRs/20578/coverage/fluid_properties)
- [`fsi`](https://mooseframework.inl.gov/docs/PRs/20578/coverage/fsi)
- [`functional_expansion_tools`](https://mooseframework.inl.gov/docs/PRs/20578/coverage/functional_expansion_tools)
- [`geochemistry`](https://mooseframework.inl.gov/docs/PRs/20578/coverage/geochemistry)
- [`heat_conduction`](https://mooseframework.inl.gov/docs/PRs/20578/coverage/heat_conduction)
- [`level_set`](https://mooseframework.inl.gov/docs/PRs/20578/coverage/level_set)
- [`misc`](https://mooseframework.inl.gov/docs/PRs/20578/coverage/misc)
- [`navier_stokes`](https://mooseframework.inl.gov/docs/PRs/20578/coverage/navier_stokes)
- [`peridynamics`](https://mooseframework.inl.gov/docs/PRs/20578/coverage/peridynamics)
- [`phase_field`](https://mooseframework.inl.gov/docs/PRs/20578/coverage/phase_field)
- [`porous_flow`](https://mooseframework.inl.gov/docs/PRs/20578/coverage/porous_flow)
- [`ray_tracing`](https://mooseframework.inl.gov/docs/PRs/20578/coverage/ray_tracing)
- [`rdg`](https://mooseframework.inl.gov/docs/PRs/20578/coverage/rdg)
- [`reactor`](https://mooseframework.inl.gov/docs/PRs/20578/coverage/reactor)
- [`richards`](https://mooseframework.inl.gov/docs/PRs/20578/coverage/richards)
- [`stochastic_tools`](https://mooseframework.inl.gov/docs/PRs/20578/coverage/stochastic_tools)
- [`tensor_mechanics`](https://mooseframework.inl.gov/docs/PRs/20578/coverage/tensor_mechanics)
- [`thermal_hydraulics`](https://mooseframework.inl.gov/docs/PRs/20578/coverage/thermal_hydraulics)
- [`xfem`](https://mooseframework.inl.gov/docs/PRs/20578/coverage/xfem)

</details>



This comment will be updated on new commits.

2022-03-28 15:07 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/996888/) on 2636a05 wanted to post the following:

The following commit(s) contain fixups:

- 2636a05295: fixup! Fixing VolumeJunction1Phase to run in parallel
- 289aa53c79: fixup! Fixing ShaftConnectedTurbine1Phase to run in parallel
- 114662d200: fixup! Fixing ShaftConnectedPump1Phase to run in parallel
- d1025b8450: fixup! Fixing ShaftConnectedCompressor1Phase to run in parallel
- fe104ab30d: fixup! Fixing JunctionParallelChannels to run in parallel
- dc0c7d892d: fixup! Fix JunctionOneToOne to run in parallel
- eed274d0fb: fixup! Fixing GateValve1Phase to run in parallel
- e4a5917bf0: fixup! Fixing ShaftConnectedMotor to run in parallel

2022-03-28 20:08 UTC, andrsd commented
The restriction to replicated mesh will be removed in a follow-up PR.

2022-04-05 16:46 UTC, moosebuild commented on libmesh
> +Subproject commit 894a50ae50b7d30183385ffb964534bcaa6e9490
**Caution!** This contains a submodule update

2022-04-05 16:46 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/1004685/) on 899715b wanted to post the following:

A change of the following file(s) triggered this check:

  libmesh

The following file(s) are unchanged:

  conda/mpich/conda_build_config.yaml
  conda/libmesh/meta.yaml

The libmesh submodule or configuration was changed but the conda build config was not

2022-04-08 18:23 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/1009047/) on 480089d wanted to post the following:

Your code requires style changes.  

A patch was auto generated and copied [here](https://mooseframework.inl.gov/docs/PRs/20578/style.patch)  
You can directly apply the patch by running, in the top level of your repository:

`curl -s https://mooseframework.inl.gov/docs/PRs/20578/style.patch | git apply -v`  

Alternatively, with your repository up to date and in the top level of your repository:

`git clang-format 1a35e4abdee91fdc1cf4f887b7e4934827a64255`

2022-04-08 18:23 UTC, moosebuild commented on libmesh
> +Subproject commit 894a50ae50b7d30183385ffb964534bcaa6e9490
**Caution!** This contains a submodule update

2022-04-08 18:23 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/1009047/) on 480089d wanted to post the following:

A change of the following file(s) triggered this check:

  libmesh

The following file(s) are unchanged:

  conda/mpich/conda_build_config.yaml
  conda/libmesh/meta.yaml

The libmesh submodule or configuration was changed but the conda build config was not

2022-04-08 18:32 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/1009079/) on e036e6c wanted to post the following:

Your code requires style changes.  

A patch was auto generated and copied [here](https://mooseframework.inl.gov/docs/PRs/20578/style.patch)  
You can directly apply the patch by running, in the top level of your repository:

`curl -s https://mooseframework.inl.gov/docs/PRs/20578/style.patch | git apply -v`  

Alternatively, with your repository up to date and in the top level of your repository:

`git clang-format 1a35e4abdee91fdc1cf4f887b7e4934827a64255`

2022-04-08 18:32 UTC, moosebuild commented on libmesh
> +Subproject commit 894a50ae50b7d30183385ffb964534bcaa6e9490
**Caution!** This contains a submodule update

2022-04-08 19:02 UTC, moosebuild commented on libmesh
> +Subproject commit 894a50ae50b7d30183385ffb964534bcaa6e9490
**Caution!** This contains a submodule update

2022-04-08 19:02 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/1009143/) on d06067b wanted to post the following:

A change of the following file(s) triggered this check:

  libmesh

The following file(s) are unchanged:

  conda/mpich/conda_build_config.yaml
  conda/libmesh/meta.yaml

The libmesh submodule or configuration was changed but the conda build config was not

2022-04-08 19:51 UTC, moosebuild commented on libmesh
> +Subproject commit 894a50ae50b7d30183385ffb964534bcaa6e9490
**Caution!** This contains a submodule update

2022-04-08 19:51 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/1009224/) on bb15b91 wanted to post the following:

A change of the following file(s) triggered this check:

  libmesh

The following file(s) are unchanged:

  conda/mpich/conda_build_config.yaml
  conda/libmesh/meta.yaml

The libmesh submodule or configuration was changed but the conda build config was not

2022-04-08 21:44 UTC, moosebuild commented on libmesh
> +Subproject commit 894a50ae50b7d30183385ffb964534bcaa6e9490
**Caution!** This contains a submodule update

2022-04-08 21:44 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/1009272/) on eaa433f wanted to post the following:

A change of the following file(s) triggered this check:

  libmesh

The following file(s) are unchanged:

  conda/mpich/conda_build_config.yaml
  conda/libmesh/meta.yaml

The libmesh submodule or configuration was changed but the conda build config was not

2022-04-08 23:11 UTC, moosebuild commented on libmesh
> +Subproject commit 894a50ae50b7d30183385ffb964534bcaa6e9490
**Caution!** This contains a submodule update

2022-04-08 23:11 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/1009347/) on e7c3a4e wanted to post the following:

A change of the following file(s) triggered this check:

  libmesh

The following file(s) are unchanged:

  conda/mpich/conda_build_config.yaml
  conda/libmesh/meta.yaml

The libmesh submodule or configuration was changed but the conda build config was not

2022-04-09 00:38 UTC, moosebuild commented on libmesh
> +Subproject commit 894a50ae50b7d30183385ffb964534bcaa6e9490
**Caution!** This contains a submodule update

2022-04-09 00:38 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/1009379/) on d8f8d6f wanted to post the following:

A change of the following file(s) triggered this check:

  libmesh

The following file(s) are unchanged:

  conda/mpich/conda_build_config.yaml
  conda/libmesh/meta.yaml

The libmesh submodule or configuration was changed but the conda build config was not

2022-04-09 01:19 UTC, moosebuild commented on libmesh
> +Subproject commit 894a50ae50b7d30183385ffb964534bcaa6e9490
**Caution!** This contains a submodule update

2022-04-09 01:19 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/1009411/) on bb9a593 wanted to post the following:

A change of the following file(s) triggered this check:

  libmesh

The following file(s) are unchanged:

  conda/mpich/conda_build_config.yaml
  conda/libmesh/meta.yaml

The libmesh submodule or configuration was changed but the conda build config was not

2022-04-09 14:58 UTC, moosebuild commented on libmesh
> +Subproject commit 894a50ae50b7d30183385ffb964534bcaa6e9490
**Caution!** This contains a submodule update

2022-04-09 14:58 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/1009507/) on 9e72b35 wanted to post the following:

A change of the following file(s) triggered this check:

  libmesh

The following file(s) are unchanged:

  conda/mpich/conda_build_config.yaml
  conda/libmesh/meta.yaml

The libmesh submodule or configuration was changed but the conda build config was not

2022-04-09 15:06 UTC, moosebuild commented on libmesh
> +Subproject commit 894a50ae50b7d30183385ffb964534bcaa6e9490
**Caution!** This contains a submodule update

2022-04-09 15:06 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/1009539/) on 889476e wanted to post the following:

A change of the following file(s) triggered this check:

  libmesh

The following file(s) are unchanged:

  conda/mpich/conda_build_config.yaml
  conda/libmesh/meta.yaml

The libmesh submodule or configuration was changed but the conda build config was not

2022-04-09 17:16 UTC, moosebuild commented on libmesh
> +Subproject commit 894a50ae50b7d30183385ffb964534bcaa6e9490
**Caution!** This contains a submodule update

2022-04-09 17:16 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/1009583/) on 7a7b17f wanted to post the following:

A change of the following file(s) triggered this check:

  libmesh

The following file(s) are unchanged:

  conda/mpich/conda_build_config.yaml
  conda/libmesh/meta.yaml

The libmesh submodule or configuration was changed but the conda build config was not

2022-04-09 17:21 UTC, moosebuild commented on libmesh
> +Subproject commit 894a50ae50b7d30183385ffb964534bcaa6e9490
**Caution!** This contains a submodule update

2022-04-09 17:21 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/1009615/) on b1100a1 wanted to post the following:

A change of the following file(s) triggered this check:

  libmesh

The following file(s) are unchanged:

  conda/mpich/conda_build_config.yaml
  conda/libmesh/meta.yaml

The libmesh submodule or configuration was changed but the conda build config was not

2022-04-09 20:10 UTC, moosebuild commented on libmesh
> +Subproject commit 894a50ae50b7d30183385ffb964534bcaa6e9490
**Caution!** This contains a submodule update

2022-04-09 20:10 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/1009658/) on 49af114 wanted to post the following:

A change of the following file(s) triggered this check:

  libmesh

The following file(s) are unchanged:

  conda/mpich/conda_build_config.yaml
  conda/libmesh/meta.yaml

The libmesh submodule or configuration was changed but the conda build config was not

2022-04-09 22:29 UTC, moosebuild commented on libmesh
> +Subproject commit 894a50ae50b7d30183385ffb964534bcaa6e9490
**Caution!** This contains a submodule update

2022-04-09 22:29 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/1009690/) on 1bb9607 wanted to post the following:

A change of the following file(s) triggered this check:

  libmesh

The following file(s) are unchanged:

  conda/mpich/conda_build_config.yaml
  conda/libmesh/meta.yaml

The libmesh submodule or configuration was changed but the conda build config was not

2022-04-10 00:26 UTC, moosebuild commented on libmesh
> +Subproject commit 894a50ae50b7d30183385ffb964534bcaa6e9490
**Caution!** This contains a submodule update

2022-04-10 00:26 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/1009722/) on 9bf607f wanted to post the following:

A change of the following file(s) triggered this check:

  libmesh

The following file(s) are unchanged:

  conda/mpich/conda_build_config.yaml
  conda/libmesh/meta.yaml

The libmesh submodule or configuration was changed but the conda build config was not

2022-04-12 15:42 UTC, moosebuild commented on libmesh
> +Subproject commit 894a50ae50b7d30183385ffb964534bcaa6e9490
**Caution!** This contains a submodule update

2022-04-12 15:42 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/1010872/) on 2047a32 wanted to post the following:

The following commit(s) contain fixups:

- 2047a3228b: fixup! Enabling more tests to run in parallel

2022-04-12 17:11 UTC, moosebuild commented on libmesh
> +Subproject commit 894a50ae50b7d30183385ffb964534bcaa6e9490
**Caution!** This contains a submodule update

2022-04-12 17:11 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/1011118/) on b64eac9 wanted to post the following:

A change of the following file(s) triggered this check:

  libmesh

The following file(s) are unchanged:

  conda/mpich/conda_build_config.yaml
  conda/libmesh/meta.yaml

The libmesh submodule or configuration was changed but the conda build config was not

2022-04-12 19:31 UTC, moosebuild commented on libmesh
> +Subproject commit 894a50ae50b7d30183385ffb964534bcaa6e9490
**Caution!** This contains a submodule update

2022-04-12 19:31 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/1011395/) on 14f97fb wanted to post the following:

A change of the following file(s) triggered this check:

  libmesh

The following file(s) are unchanged:

  conda/mpich/conda_build_config.yaml
  conda/libmesh/meta.yaml

The libmesh submodule or configuration was changed but the conda build config was not

2022-04-12 21:02 UTC, moosebuild commented on libmesh
> +Subproject commit 894a50ae50b7d30183385ffb964534bcaa6e9490
**Caution!** This contains a submodule update

2022-04-12 21:02 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/1011561/) on 19588f6 wanted to post the following:

A change of the following file(s) triggered this check:

  libmesh

The following file(s) are unchanged:

  conda/mpich/conda_build_config.yaml
  conda/libmesh/meta.yaml

The libmesh submodule or configuration was changed but the conda build config was not

2022-04-13 18:38 UTC, moosebuild commented on libmesh
> +Subproject commit 894a50ae50b7d30183385ffb964534bcaa6e9490
**Caution!** This contains a submodule update

2022-04-13 18:38 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/1013528/) on a80d88f wanted to post the following:

The following commit(s) contain fixups:

- a80d88f653: fixup! Fixing heat transfer from heat structure to run in parallel
- 987d183b7d: fixup! Removing distributed mesh restriction
- c01a0f262e: fixup! Removing distributed mesh restriction
- 296a31fb4c: fixup! Removing distributed mesh restriction

2022-04-13 18:38 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/1013528/) on a80d88f wanted to post the following:

A change of the following file(s) triggered this check:

  libmesh

The following file(s) are unchanged:

  conda/mpich/conda_build_config.yaml
  conda/libmesh/meta.yaml

The libmesh submodule or configuration was changed but the conda build config was not

2022-04-13 19:02 UTC, moosebuild commented on libmesh
> +Subproject commit 894a50ae50b7d30183385ffb964534bcaa6e9490
**Caution!** This contains a submodule update

2022-04-13 19:02 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/1013627/) on 54975d0 wanted to post the following:

A change of the following file(s) triggered this check:

  libmesh

The following file(s) are unchanged:

  conda/mpich/conda_build_config.yaml
  conda/libmesh/meta.yaml

The libmesh submodule or configuration was changed but the conda build config was not

2022-04-13 22:43 UTC, moosebuild commented on libmesh
> +Subproject commit 894a50ae50b7d30183385ffb964534bcaa6e9490
**Caution!** This contains a submodule update

2022-04-13 22:43 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/1014217/) on 984c38b wanted to post the following:

A change of the following file(s) triggered this check:

  libmesh

The following file(s) are unchanged:

  conda/mpich/conda_build_config.yaml
  conda/libmesh/meta.yaml

The libmesh submodule or configuration was changed but the conda build config was not

2022-04-14 21:09 UTC, joshuahansel requested changes
Create a MOOSE newsletter entry.

2022-04-15 12:53 UTC, andrsd commented on modules/thermal_hydraulics/test/tests/components/junction_one_to_one_1phase/tests
> +    mesh_mode = 'replicated'
I will open an issue.

What is surprising me is the `junction_one_to_one/tests` file. The latest branch should not be restricting junctions, only heat transfers from heat structures.

2022-04-15 12:57 UTC, andrsd commented on modules/thermal_hydraulics/test/tests/components/junction_one_to_one_1phase/tests
> +    mesh_mode = 'replicated'
nvm, you went patch by patch and at some point there was this restriction until I removed it. *slow thinking in the morning*

2022-04-15 13:19 UTC, andrsd commented on modules/thermal_hydraulics/test/tests/components/junction_one_to_one_1phase/tests
> +    mesh_mode = 'replicated'
Issue is opened [here](https://github.com/idaholab/moose/issues/20798)

2022-04-19 18:44 UTC, joshuahansel approved these changes

2022-04-20 13:09 UTC, merged