Update tinydir.h
idaholab/moose pull request #20679
Opened 2022-03-30 21:28 UTC by dschwen

Closes #20678

2022-03-30 21:29 UTC, dschwen commented on framework/contrib/tinydir/include/tinydir.h
> +    tinydir_file * _files = nullptr;
this initialization and the one in l223 fix the warnings

2022-03-30 21:41 UTC, cticenhour requested changes
Can you take a look in `MooseUtils.C:36` and remove those ignores I added for Clang and tinydir? If you're fixing all of these up, they should be removed.

2022-03-30 22:22 UTC, dschwen commented
Ha, didn't even see those because I was working off an older devel 😊

2022-03-30 23:41 UTC, moosebuild commented
Job [Documentation](https://civet.inl.gov/job/999866/) on a6f70be wanted to post the following:

View the site [here](https://mooseframework.inl.gov/docs/PRs/20679/site)

This comment will be updated on new commits.

2022-03-31 01:13 UTC, moosebuild commented
Job [Coverage](https://civet.inl.gov/job/999874/) on a6f70be wanted to post the following:


## Framework coverage

<table>
  <thead>
    <tr>
      <th></th>
      <th>c90b1f</th>
      <th colspan=4>#20679 a6f70b</th>
    </tr>
    <tr>
      <th></th>
      <th>Total</th>
      <th>Total</th>
      <th>+/-</th>
      <th>New</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><b>Rate</b></td>
      <td>82.56%</td>
      <td>82.56%</td>
      <td>+0.00%</td>
      <td>100.00%</td>
    </tr>
    <tr>
      <td><b>Hits</b></td>
      <td>73757</td>
      <td>73760</td>
      <td>+3</td>
      <td>1</td>
    </tr>
    <tr>
      <td><b>Misses</b></td>
      <td>15581</td>
      <td>15580</td>
      <td>-1</td>
      <td>0</td>
    </tr>
  </tbody>
</table>

[Diff coverage report](https://mooseframework.inl.gov/docs/PRs/20679/coverage_diff/framework.html)

[Full coverage report](https://mooseframework.inl.gov/docs/PRs/20679/coverage/framework)


## Modules coverage

Coverage did not change

## Full coverage reports

<details>
<summary>Reports</summary>

- [`framework`](https://mooseframework.inl.gov/docs/PRs/20679/coverage/framework)
- [`chemical_reactions`](https://mooseframework.inl.gov/docs/PRs/20679/coverage/chemical_reactions)
- [`combined`](https://mooseframework.inl.gov/docs/PRs/20679/coverage/combined)
- [`contact`](https://mooseframework.inl.gov/docs/PRs/20679/coverage/contact)
- [`external_petsc_solver`](https://mooseframework.inl.gov/docs/PRs/20679/coverage/external_petsc_solver)
- [`fluid_properties`](https://mooseframework.inl.gov/docs/PRs/20679/coverage/fluid_properties)
- [`fsi`](https://mooseframework.inl.gov/docs/PRs/20679/coverage/fsi)
- [`functional_expansion_tools`](https://mooseframework.inl.gov/docs/PRs/20679/coverage/functional_expansion_tools)
- [`geochemistry`](https://mooseframework.inl.gov/docs/PRs/20679/coverage/geochemistry)
- [`heat_conduction`](https://mooseframework.inl.gov/docs/PRs/20679/coverage/heat_conduction)
- [`level_set`](https://mooseframework.inl.gov/docs/PRs/20679/coverage/level_set)
- [`misc`](https://mooseframework.inl.gov/docs/PRs/20679/coverage/misc)
- [`navier_stokes`](https://mooseframework.inl.gov/docs/PRs/20679/coverage/navier_stokes)
- [`peridynamics`](https://mooseframework.inl.gov/docs/PRs/20679/coverage/peridynamics)
- [`phase_field`](https://mooseframework.inl.gov/docs/PRs/20679/coverage/phase_field)
- [`porous_flow`](https://mooseframework.inl.gov/docs/PRs/20679/coverage/porous_flow)
- [`ray_tracing`](https://mooseframework.inl.gov/docs/PRs/20679/coverage/ray_tracing)
- [`rdg`](https://mooseframework.inl.gov/docs/PRs/20679/coverage/rdg)
- [`reactor`](https://mooseframework.inl.gov/docs/PRs/20679/coverage/reactor)
- [`richards`](https://mooseframework.inl.gov/docs/PRs/20679/coverage/richards)
- [`stochastic_tools`](https://mooseframework.inl.gov/docs/PRs/20679/coverage/stochastic_tools)
- [`tensor_mechanics`](https://mooseframework.inl.gov/docs/PRs/20679/coverage/tensor_mechanics)
- [`thermal_hydraulics`](https://mooseframework.inl.gov/docs/PRs/20679/coverage/thermal_hydraulics)
- [`xfem`](https://mooseframework.inl.gov/docs/PRs/20679/coverage/xfem)

</details>



This comment will be updated on new commits.

2022-04-01 21:50 UTC, cticenhour approved these changes
Thanks @dschwen!

2022-04-02 00:06 UTC, merged