Add shortcut action to add AuxKernel nested within an AuxVariable
idaholab/moose pull request #20754
Opened 2022-04-09 02:45 UTC by hugary1995

close #20753

This PR allows us to do
```python
[AuxVariables]
  [foo]
    order = SECOND
    [AuxKernel]
      type = bar
    []
  []
[]
```

2022-04-09 02:48 UTC, dschwen commented
I like this.

2022-04-09 02:55 UTC, hugary1995 commented
You live in github! :rofl:

2022-04-09 03:49 UTC, moosebuild commented
Job [Documentation](https://civet.inl.gov/job/1009460/) on c4f07da wanted to post the following:

View the site [here](https://mooseframework.inl.gov/docs/PRs/20754/site)

This comment will be updated on new commits.

2022-04-09 05:26 UTC, moosebuild commented
Job [Coverage](https://civet.inl.gov/job/1009468/) on c4f07da wanted to post the following:


## Framework coverage

<table>
  <thead>
    <tr>
      <th></th>
      <th>1a35e4</th>
      <th colspan=4>#20754 c4f07d</th>
    </tr>
    <tr>
      <th></th>
      <th>Total</th>
      <th>Total</th>
      <th>+/-</th>
      <th>New</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><b>Rate</b></td>
      <td>82.56%</td>
      <td>82.57%</td>
      <td>+0.00%</td>
      <td>100.00%</td>
    </tr>
    <tr>
      <td><b>Hits</b></td>
      <td>74123</td>
      <td>74136</td>
      <td>+13</td>
      <td>13</td>
    </tr>
    <tr>
      <td><b>Misses</b></td>
      <td>15654</td>
      <td>15654</td>
      <td>-</td>
      <td>0</td>
    </tr>
  </tbody>
</table>

[Diff coverage report](https://mooseframework.inl.gov/docs/PRs/20754/coverage_diff/framework.html)

[Full coverage report](https://mooseframework.inl.gov/docs/PRs/20754/coverage/framework)


## Modules coverage

Coverage did not change

## Full coverage reports

<details>
<summary>Reports</summary>

- [`framework`](https://mooseframework.inl.gov/docs/PRs/20754/coverage/framework)
- [`chemical_reactions`](https://mooseframework.inl.gov/docs/PRs/20754/coverage/chemical_reactions)
- [`combined`](https://mooseframework.inl.gov/docs/PRs/20754/coverage/combined)
- [`contact`](https://mooseframework.inl.gov/docs/PRs/20754/coverage/contact)
- [`external_petsc_solver`](https://mooseframework.inl.gov/docs/PRs/20754/coverage/external_petsc_solver)
- [`fluid_properties`](https://mooseframework.inl.gov/docs/PRs/20754/coverage/fluid_properties)
- [`fsi`](https://mooseframework.inl.gov/docs/PRs/20754/coverage/fsi)
- [`functional_expansion_tools`](https://mooseframework.inl.gov/docs/PRs/20754/coverage/functional_expansion_tools)
- [`geochemistry`](https://mooseframework.inl.gov/docs/PRs/20754/coverage/geochemistry)
- [`heat_conduction`](https://mooseframework.inl.gov/docs/PRs/20754/coverage/heat_conduction)
- [`level_set`](https://mooseframework.inl.gov/docs/PRs/20754/coverage/level_set)
- [`misc`](https://mooseframework.inl.gov/docs/PRs/20754/coverage/misc)
- [`navier_stokes`](https://mooseframework.inl.gov/docs/PRs/20754/coverage/navier_stokes)
- [`peridynamics`](https://mooseframework.inl.gov/docs/PRs/20754/coverage/peridynamics)
- [`phase_field`](https://mooseframework.inl.gov/docs/PRs/20754/coverage/phase_field)
- [`porous_flow`](https://mooseframework.inl.gov/docs/PRs/20754/coverage/porous_flow)
- [`ray_tracing`](https://mooseframework.inl.gov/docs/PRs/20754/coverage/ray_tracing)
- [`rdg`](https://mooseframework.inl.gov/docs/PRs/20754/coverage/rdg)
- [`reactor`](https://mooseframework.inl.gov/docs/PRs/20754/coverage/reactor)
- [`richards`](https://mooseframework.inl.gov/docs/PRs/20754/coverage/richards)
- [`stochastic_tools`](https://mooseframework.inl.gov/docs/PRs/20754/coverage/stochastic_tools)
- [`tensor_mechanics`](https://mooseframework.inl.gov/docs/PRs/20754/coverage/tensor_mechanics)
- [`thermal_hydraulics`](https://mooseframework.inl.gov/docs/PRs/20754/coverage/thermal_hydraulics)
- [`xfem`](https://mooseframework.inl.gov/docs/PRs/20754/coverage/xfem)

</details>



This comment will be updated on new commits.

2022-04-11 15:49 UTC, YaqiWang commented
There could be multiple aux kernels for the same aux var. But I like this syntax too.

2022-04-11 16:14 UTC, hugary1995 commented
That's a good point. I could imagine cases where multiple auxkernels for the same aux var with different execute ons or different block/boundary restrictions. The proposed syntax in this PR should be able handle those cases properly.

Looking at the current SQA, I don't see any mentions of "The framework shall support multiple boundary-restricted auxkernels for the same auxvariable..." or anything like that. That's probably a separate issue/PR.

2022-04-11 16:20 UTC, moosebuild commented
Job [Apple Silicon Stack](https://civet.inl.gov/job/1009478/) on 41e69c0 : invalidated by @hugary1995

Error during fetch and branch. Retry...

2022-04-11 16:20 UTC, moosebuild commented
Job [Modules parallel](https://civet.inl.gov/job/1009489/) on 41e69c0 : invalidated by @hugary1995

(Seemingly) unrelated failure. Retry.

2022-04-12 15:41 UTC, GiudGiud requested changes
Missing a short doc page for the action that shows the new syntax.
Tests configuration file should have the new issue and new design file attached to a new test

2022-04-12 15:41 UTC, GiudGiud commented on framework/include/actions/AddAuxKernelAction.h
> +
docstring

2022-04-12 15:41 UTC, GiudGiud commented on test/tests/auxkernels/array_aux_kernels/function_array_aux.i
> -  []
duplicate the test and make sure they compare the same
use active = '' / inactive='' to have both syntaxes in the file (and avoid duplicating the file)

2022-04-12 21:56 UTC, GiudGiud submitted a review, later dismissed

2022-04-12 23:00 UTC, GiudGiud commented
it's a reading/writing exodus with hdf5 issue. 
3 options:
- revert to an old conda to generate the file
- use an old exodus file from another test
- wait for the libmesh submodule update to be merged in, rebase, regenerate your file

Tagging @cticenhour for awareness.

2022-04-13 19:48 UTC, GiudGiud approved these changes

2022-04-13 20:34 UTC, merged