Ignoring some variables during autoscaling
idaholab/moose pull request #20814
Opened 2022-04-18 22:49 UTC by tophmatthews

Closes #19572

2022-04-18 22:51 UTC, tophmatthews commented
Here's a hack at this @lindsayad . One thing that I'm not sure of is if the scaling for the "non-ignored" variables should change if some variables are ignored. Currently, the non-ignored variables have the same scaling with and without all variables included. If feels like that shouldn't be the case...but I'm not positive.

2022-04-18 22:52 UTC, tophmatthews commented on framework/src/systems/NonlinearSystemBase.C
> +      if (field_variable_autoscaled[i])
Kinda hard to see...but the only change here is adding this new "if" statement. The rest is just formatting.

2022-04-18 22:52 UTC, GiudGiud commented on framework/src/executioners/FEProblemSolve.C
> +      "List of variables that do not participate in autoscaling.");
needs to be added to the parameter group

2022-04-18 23:11 UTC, lindsayad requested changes
Looking good

2022-04-18 23:11 UTC, lindsayad commented on framework/src/systems/NonlinearSystemBase.C
> +                     "'ignore_variables_for_autoscaling'");
I think you could do this check in `FEProblemSolve` and be able to give a `paramError` as opposed to a `mooseError`

2022-04-18 23:11 UTC, lindsayad commented on framework/src/systems/NonlinearSystemBase.C
> +  }
I would rename `setupScalingGrouping` to something like `setupScalingData` and construct `_field_variable_autoscaled` and `_scalar_variable_autoscaled` data members in there. Then you only do these O(N) algorithms once. Also make sure to use `std::find` as opposed to just `find`, unless you are using some other `find` and then please explicitly apply that scoping operator instead

2022-04-19 00:02 UTC, moosebuild commented
Job [Documentation](https://civet.inl.gov/job/1019698/) on 59f96f1 wanted to post the following:

View the site [here](https://mooseframework.inl.gov/docs/PRs/20814/site)

This comment will be updated on new commits.

2022-04-19 00:25 UTC, lindsayad requested changes
As long as coverage looks good, I'm ready to merge after this

2022-04-19 00:25 UTC, lindsayad commented on framework/src/executioners/FEProblemSolve.C
> +      const auto scaling_group_variables =
```suggestion
      const auto & ignore_variables_for_autoscaling =
          getParam<std::vector<std::string>>("ignore_variables_for_autoscaling");
      const auto & scaling_group_variables =
```

2022-04-19 00:25 UTC, lindsayad commented on framework/src/executioners/FEProblemSolve.C
> +        for (const auto & var_name : scaling_group_variables[group_index])
```suggestion
      for (const auto & group : scaling_group_variables)
        for (const auto & var_name : group)
```

2022-04-19 00:25 UTC, lindsayad commented on framework/src/executioners/FEProblemSolve.C
> +            paramError(" ignore_variables_for_autoscaling",
```suggestion
            paramError("ignore_variables_for_autoscaling",
```

2022-04-19 03:42 UTC, moosebuild commented
Job [Coverage](https://civet.inl.gov/job/1020027/) on 9476a77 wanted to post the following:


## Framework coverage

<table>
  <thead>
    <tr>
      <th></th>
      <th>00878b</th>
      <th colspan=4>#20814 9476a7</th>
    </tr>
    <tr>
      <th></th>
      <th>Total</th>
      <th>Total</th>
      <th>+/-</th>
      <th>New</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><b>Rate</b></td>
      <td>82.57%</td>
      <td>82.59%</td>
      <td>+0.01%</td>
      <td>96.08%</td>
    </tr>
    <tr>
      <td><b>Hits</b></td>
      <td>74218</td>
      <td>74252</td>
      <td>+34</td>
      <td>49</td>
    </tr>
    <tr>
      <td><b>Misses</b></td>
      <td>15663</td>
      <td>15657</td>
      <td>-6</td>
      <td>2</td>
    </tr>
  </tbody>
</table>

[Diff coverage report](https://mooseframework.inl.gov/docs/PRs/20814/coverage_diff/framework.html)

[Full coverage report](https://mooseframework.inl.gov/docs/PRs/20814/coverage/framework)


## Modules coverage

Coverage did not change

## Full coverage reports

<details>
<summary>Reports</summary>

- [`framework`](https://mooseframework.inl.gov/docs/PRs/20814/coverage/framework)
- [`chemical_reactions`](https://mooseframework.inl.gov/docs/PRs/20814/coverage/chemical_reactions)
- [`combined`](https://mooseframework.inl.gov/docs/PRs/20814/coverage/combined)
- [`contact`](https://mooseframework.inl.gov/docs/PRs/20814/coverage/contact)
- [`external_petsc_solver`](https://mooseframework.inl.gov/docs/PRs/20814/coverage/external_petsc_solver)
- [`fluid_properties`](https://mooseframework.inl.gov/docs/PRs/20814/coverage/fluid_properties)
- [`fsi`](https://mooseframework.inl.gov/docs/PRs/20814/coverage/fsi)
- [`functional_expansion_tools`](https://mooseframework.inl.gov/docs/PRs/20814/coverage/functional_expansion_tools)
- [`geochemistry`](https://mooseframework.inl.gov/docs/PRs/20814/coverage/geochemistry)
- [`heat_conduction`](https://mooseframework.inl.gov/docs/PRs/20814/coverage/heat_conduction)
- [`level_set`](https://mooseframework.inl.gov/docs/PRs/20814/coverage/level_set)
- [`misc`](https://mooseframework.inl.gov/docs/PRs/20814/coverage/misc)
- [`navier_stokes`](https://mooseframework.inl.gov/docs/PRs/20814/coverage/navier_stokes)
- [`peridynamics`](https://mooseframework.inl.gov/docs/PRs/20814/coverage/peridynamics)
- [`phase_field`](https://mooseframework.inl.gov/docs/PRs/20814/coverage/phase_field)
- [`porous_flow`](https://mooseframework.inl.gov/docs/PRs/20814/coverage/porous_flow)
- [`ray_tracing`](https://mooseframework.inl.gov/docs/PRs/20814/coverage/ray_tracing)
- [`rdg`](https://mooseframework.inl.gov/docs/PRs/20814/coverage/rdg)
- [`reactor`](https://mooseframework.inl.gov/docs/PRs/20814/coverage/reactor)
- [`richards`](https://mooseframework.inl.gov/docs/PRs/20814/coverage/richards)
- [`stochastic_tools`](https://mooseframework.inl.gov/docs/PRs/20814/coverage/stochastic_tools)
- [`tensor_mechanics`](https://mooseframework.inl.gov/docs/PRs/20814/coverage/tensor_mechanics)
- [`thermal_hydraulics`](https://mooseframework.inl.gov/docs/PRs/20814/coverage/thermal_hydraulics)
- [`xfem`](https://mooseframework.inl.gov/docs/PRs/20814/coverage/xfem)

</details>



This comment will be updated on new commits.

2022-04-19 15:09 UTC, lindsayad approved these changes

2022-04-19 15:09 UTC, merged