Improve ExtraElementIDCopyGenerator to allow copying the element id
idaholab/moose pull request #20897
Opened 2022-04-27 22:49 UTC by YaqiWang

Close #20895.

2022-04-27 23:57 UTC, moosebuild commented
Job [Documentation](https://civet.inl.gov/job/1029963/) on 6055a5b wanted to post the following:

View the site [here](https://mooseframework.inl.gov/docs/PRs/20897/site)

This comment will be updated on new commits.

2022-04-28 21:28 UTC, YaqiWang commented
This should be ready for review. The failures appear irrelevant.

2022-05-03 13:16 UTC, loganharbour approved these changes

2022-05-03 15:53 UTC, loganharbour requested changes
Look into the failures in https://civet.inl.gov/job/1029978/

2022-05-03 18:04 UTC, YaqiWang commented
Oh, that is real. I did not notice.

2022-05-03 22:23 UTC, moosebuild commented
Job [Coverage](https://civet.inl.gov/job/1035134/) on d8558e5 wanted to post the following:


## Framework coverage

<table>
  <thead>
    <tr>
      <th></th>
      <th>d67078</th>
      <th colspan=4>#20897 d8558e</th>
    </tr>
    <tr>
      <th></th>
      <th>Total</th>
      <th>Total</th>
      <th>+/-</th>
      <th>New</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><b>Rate</b></td>
      <td>82.52%</td>
      <td>82.53%</td>
      <td>+0.00%</td>
      <td>-</td>
    </tr>
    <tr>
      <td><b>Hits</b></td>
      <td>74763</td>
      <td>74767</td>
      <td>+4</td>
      <td>0</td>
    </tr>
    <tr>
      <td><b>Misses</b></td>
      <td>15836</td>
      <td>15832</td>
      <td>-4</td>
      <td>0</td>
    </tr>
  </tbody>
</table>

[Diff coverage report](https://mooseframework.inl.gov/docs/PRs/20897/coverage_diff/framework)

[Full coverage report](https://mooseframework.inl.gov/docs/PRs/20897/coverage/framework)


## Modules coverage

### Reactor

<table>
  <thead>
    <tr>
      <th></th>
      <th>d67078</th>
      <th colspan=4>#20897 d8558e</th>
    </tr>
    <tr>
      <th></th>
      <th>Total</th>
      <th>Total</th>
      <th>+/-</th>
      <th>New</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><b>Rate</b></td>
      <td>95.03%</td>
      <td>95.06%</td>
      <td>+0.03%</td>
      <td>100.00%</td>
    </tr>
    <tr>
      <td><b>Hits</b></td>
      <td>3000</td>
      <td>3003</td>
      <td>+3</td>
      <td>3</td>
    </tr>
    <tr>
      <td><b>Misses</b></td>
      <td>157</td>
      <td>156</td>
      <td>-1</td>
      <td>0</td>
    </tr>
  </tbody>
</table>

[Diff coverage report](https://mooseframework.inl.gov/docs/PRs/20897/coverage_diff/reactor)

[Full coverage report](https://mooseframework.inl.gov/docs/PRs/20897/coverage/reactor)

## Full coverage reports

<details>
<summary>Reports</summary>

- [`framework`](https://mooseframework.inl.gov/docs/PRs/20897/coverage/framework)
- [`chemical_reactions`](https://mooseframework.inl.gov/docs/PRs/20897/coverage/chemical_reactions)
- [`combined`](https://mooseframework.inl.gov/docs/PRs/20897/coverage/combined)
- [`contact`](https://mooseframework.inl.gov/docs/PRs/20897/coverage/contact)
- [`external_petsc_solver`](https://mooseframework.inl.gov/docs/PRs/20897/coverage/external_petsc_solver)
- [`fluid_properties`](https://mooseframework.inl.gov/docs/PRs/20897/coverage/fluid_properties)
- [`fsi`](https://mooseframework.inl.gov/docs/PRs/20897/coverage/fsi)
- [`functional_expansion_tools`](https://mooseframework.inl.gov/docs/PRs/20897/coverage/functional_expansion_tools)
- [`geochemistry`](https://mooseframework.inl.gov/docs/PRs/20897/coverage/geochemistry)
- [`heat_conduction`](https://mooseframework.inl.gov/docs/PRs/20897/coverage/heat_conduction)
- [`level_set`](https://mooseframework.inl.gov/docs/PRs/20897/coverage/level_set)
- [`misc`](https://mooseframework.inl.gov/docs/PRs/20897/coverage/misc)
- [`navier_stokes`](https://mooseframework.inl.gov/docs/PRs/20897/coverage/navier_stokes)
- [`peridynamics`](https://mooseframework.inl.gov/docs/PRs/20897/coverage/peridynamics)
- [`phase_field`](https://mooseframework.inl.gov/docs/PRs/20897/coverage/phase_field)
- [`porous_flow`](https://mooseframework.inl.gov/docs/PRs/20897/coverage/porous_flow)
- [`ray_tracing`](https://mooseframework.inl.gov/docs/PRs/20897/coverage/ray_tracing)
- [`rdg`](https://mooseframework.inl.gov/docs/PRs/20897/coverage/rdg)
- [`reactor`](https://mooseframework.inl.gov/docs/PRs/20897/coverage/reactor)
- [`richards`](https://mooseframework.inl.gov/docs/PRs/20897/coverage/richards)
- [`stochastic_tools`](https://mooseframework.inl.gov/docs/PRs/20897/coverage/stochastic_tools)
- [`tensor_mechanics`](https://mooseframework.inl.gov/docs/PRs/20897/coverage/tensor_mechanics)
- [`thermal_hydraulics`](https://mooseframework.inl.gov/docs/PRs/20897/coverage/thermal_hydraulics)
- [`xfem`](https://mooseframework.inl.gov/docs/PRs/20897/coverage/xfem)

</details>



This comment will be updated on new commits.

2022-05-04 02:46 UTC, loganharbour approved these changes

2022-05-04 02:46 UTC, merged