Add more potential matches for regex of input files
idaholab/moose pull request #20898
Opened 2022-04-27 23:18 UTC by GiudGiud

Attempts a bug fix for #17426 #19137

doc doesnt build locally (someone teach me maybe), so going to debug with this PR

2022-04-28 00:03 UTC, moosebuild commented
Job [Documentation](https://civet.inl.gov/job/1030018/) on 584bde6 wanted to post the following:

View the site [here](https://mooseframework.inl.gov/docs/PRs/20898/site)

This comment will be updated on new commits.

2022-04-28 02:07 UTC, moosebuild commented
Job [Coverage](https://civet.inl.gov/job/1030045/) on 584bde6 wanted to post the following:


## Framework coverage

<table>
  <thead>
    <tr>
      <th></th>
      <th>edbf9a</th>
      <th colspan=4>#20898 584bde</th>
    </tr>
    <tr>
      <th></th>
      <th>Total</th>
      <th>Total</th>
      <th>+/-</th>
      <th>New</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><b>Rate</b></td>
      <td>82.58%</td>
      <td>82.58%</td>
      <td>+0.00%</td>
      <td>-</td>
    </tr>
    <tr>
      <td><b>Hits</b></td>
      <td>74737</td>
      <td>74739</td>
      <td>+2</td>
      <td>0</td>
    </tr>
    <tr>
      <td><b>Misses</b></td>
      <td>15765</td>
      <td>15763</td>
      <td>-2</td>
      <td>0</td>
    </tr>
  </tbody>
</table>

[Diff coverage report](https://mooseframework.inl.gov/docs/PRs/20898/coverage_diff/framework)

[Full coverage report](https://mooseframework.inl.gov/docs/PRs/20898/coverage/framework)


## Modules coverage

Coverage did not change

## Full coverage reports

<details>
<summary>Reports</summary>

- [`framework`](https://mooseframework.inl.gov/docs/PRs/20898/coverage/framework)
- [`chemical_reactions`](https://mooseframework.inl.gov/docs/PRs/20898/coverage/chemical_reactions)
- [`combined`](https://mooseframework.inl.gov/docs/PRs/20898/coverage/combined)
- [`contact`](https://mooseframework.inl.gov/docs/PRs/20898/coverage/contact)
- [`external_petsc_solver`](https://mooseframework.inl.gov/docs/PRs/20898/coverage/external_petsc_solver)
- [`fluid_properties`](https://mooseframework.inl.gov/docs/PRs/20898/coverage/fluid_properties)
- [`fsi`](https://mooseframework.inl.gov/docs/PRs/20898/coverage/fsi)
- [`functional_expansion_tools`](https://mooseframework.inl.gov/docs/PRs/20898/coverage/functional_expansion_tools)
- [`geochemistry`](https://mooseframework.inl.gov/docs/PRs/20898/coverage/geochemistry)
- [`heat_conduction`](https://mooseframework.inl.gov/docs/PRs/20898/coverage/heat_conduction)
- [`level_set`](https://mooseframework.inl.gov/docs/PRs/20898/coverage/level_set)
- [`misc`](https://mooseframework.inl.gov/docs/PRs/20898/coverage/misc)
- [`navier_stokes`](https://mooseframework.inl.gov/docs/PRs/20898/coverage/navier_stokes)
- [`peridynamics`](https://mooseframework.inl.gov/docs/PRs/20898/coverage/peridynamics)
- [`phase_field`](https://mooseframework.inl.gov/docs/PRs/20898/coverage/phase_field)
- [`porous_flow`](https://mooseframework.inl.gov/docs/PRs/20898/coverage/porous_flow)
- [`ray_tracing`](https://mooseframework.inl.gov/docs/PRs/20898/coverage/ray_tracing)
- [`rdg`](https://mooseframework.inl.gov/docs/PRs/20898/coverage/rdg)
- [`reactor`](https://mooseframework.inl.gov/docs/PRs/20898/coverage/reactor)
- [`richards`](https://mooseframework.inl.gov/docs/PRs/20898/coverage/richards)
- [`stochastic_tools`](https://mooseframework.inl.gov/docs/PRs/20898/coverage/stochastic_tools)
- [`tensor_mechanics`](https://mooseframework.inl.gov/docs/PRs/20898/coverage/tensor_mechanics)
- [`thermal_hydraulics`](https://mooseframework.inl.gov/docs/PRs/20898/coverage/thermal_hydraulics)
- [`xfem`](https://mooseframework.inl.gov/docs/PRs/20898/coverage/xfem)

</details>



This comment will be updated on new commits.

2022-04-29 04:33 UTC, GiudGiud commented
@cticenhour this should be ready for review.
As the new log shows, quite a few input file objects are not matched to a class, and therefore that class' documentation does not list these inputs. I think it's just a matter of being more consistent between the C++ object names and the input file names. Might require some renaming to fix. Not the scope for this PR imo

2022-05-12 01:06 UTC, GiudGiud commented
umm only apps failures at this point
https://civet.inl.gov/job/1042583/

I think I ll need to do some patches to make it work, possibly break next

2022-05-31 17:49 UTC, GiudGiud commented
@cticenhour this is ready!
so happy rn haha

2022-05-31 17:50 UTC, cticenhour commented
I've been seeing the intense force pushes - good job! I'll give a formal review this afternoon 😄

2022-05-31 20:15 UTC, GiudGiud commented
seems I broke it haha
I ll look more. we want a lot of things from this

2022-05-31 20:17 UTC, GiudGiud commented
ok should be good now

2022-06-03 04:19 UTC, cticenhour requested changes

2022-06-03 04:19 UTC, cticenhour commented on python/MooseDocs/common/build_class_database.py
> +    # - in all cases I know of, the AD/nonAD are from the same template
Could we improve this logic by looking for and flagging dict objects post `_match_definition` that have the same matched header?

2022-06-03 04:19 UTC, cticenhour commented on python/MooseDocs/common/build_class_database.py
> +    # - in all cases I know of, the AD/nonAD are from the same template
Might be beyond the scope of this PR as you do successfully address the raised issues, and I cannot think of a case where there are AD/nonAD objects, templated or not, that have differing parameters and perform the same function.

2022-06-03 04:29 UTC, GiudGiud commented on python/MooseDocs/common/build_class_database.py
> +    # - in all cases I know of, the AD/nonAD are from the same template
sure can do, pushing a commit now

2022-06-03 05:46 UTC, cticenhour approved these changes
Comment was addressed, and new class database now functions as expected for both separate and templated AD/nonAD pairs. Thanks for doing this!

2022-06-03 15:28 UTC, merged