Explode mesh generator
idaholab/moose pull request #21061
Opened 2022-05-20 13:04 UTC by hugary1995

Add an `ExplodeMeshGenerator` that breaks all element-element interfaces in given subdomains.

closes #21060

2022-05-20 14:24 UTC, moosebuild commented
Job [Documentation](https://civet.inl.gov/job/1050683/) on 84cb869 wanted to post the following:

View the site [here](https://mooseframework.inl.gov/docs/PRs/21061/site)

This comment will be updated on new commits.

2022-05-20 16:07 UTC, loganharbour requested changes

2022-05-20 16:10 UTC, hugary1995 commented on framework/src/meshgenerators/ExplodeMeshGenerator.C
> +ExplodeMeshGenerator::buildSubdomainRestrictedNodeToElemMap(
Yeah, you are right. I can change it.

2022-05-20 16:10 UTC, hugary1995 commented on framework/src/meshgenerators/ExplodeMeshGenerator.C
> +      duplicateNode(mesh, mesh->elem_ptr(connected_elem_ids[i]), mesh->node_ptr(node_id));
:+1:

2022-05-20 16:12 UTC, hugary1995 commented on framework/src/meshgenerators/ExplodeMeshGenerator.C
> +    }
> Few things here:
> 
> let libmesh handle the ID
> don't use raw pointers for the built objects

:+1: 

> Also; is it necessary to set the processor ID?

I don't know. I was following `BreakMeshByBlockGenerator` where it assigned processor IDs. They better had a reason for that...

2022-05-20 16:13 UTC, hugary1995 commented on framework/src/meshgenerators/ExplodeMeshGenerator.C
> +  boundary_info.add_node(new_node, node_boundary_ids);
:+1:

2022-05-22 03:27 UTC, loganharbour approved these changes

2022-05-22 03:27 UTC, merged