Libmesh update
idaholab/moose pull request #21127
Opened 2022-05-24 22:19 UTC by roystgnr

- Even more internal smart pointers.  This includes changes to the `Parameter` class that may require downstream changes to match; compatibility in Moose itself has already been fixed.
- When trying to combine a low-order `Elem` with an incompatibly higher order `FE` type, the mistake is now always reported with
  comprehensible error message, even in non-debugging-mode builds.
- When a parsed function is used and the parser returns an error, we now check and report details even in non-debugging-mode builds.
- The last use of C++17-deprecated std::iterator has been fixed; a few compilers outside CI were giving us warnings about it.
- We put support for input meshes that themselves have holes into MeshedHole, so you can mesh with holes while your hole has holes.
- Bug fixes for some triangulator use cases.
- Compatibility fixes for some `PETSc` 3.17 configurations.

- MetaPhysicL updates, for evaluating `pow(negative DualNumber, integer)` operations without throwing floating point exceptions, and also evaluating binary functions faster in general when mixing DualNumber and non-DualNumber parameter types.

I mostly need this for the triangulator fixes, but the MetaPhysicL updates fix a Moose-user-reported bug.  I also want to get that `Parameters` change into Moose CI, to be completely sure it doesn't affect anything that we didn't previously catch via libMesh CI.

2022-05-24 22:31 UTC, moosebuild commented on libmesh
> +Subproject commit 945cc324f449d88c58a08fd8e2a1e521ba1b33a3
**Caution!** This contains a submodule update

2022-05-24 22:31 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/1054386/) on 4520b40 wanted to post the following:

The following file(s) are changed:

  conda/mpich/conda_build_config.yaml

The conda configuration has changed; ping @idaholab/moose-dev-ops

2022-05-24 22:31 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/1054386/) on 4520b40 wanted to post the following:

The following file(s) are changed:

  conda/libmesh/meta.yaml

The libmesh conda configuration has changed; ping @idaholab/moose-dev-ops

2022-05-24 23:50 UTC, moosebuild commented
Job [Documentation](https://civet.inl.gov/job/1054404/) on 4520b40 wanted to post the following:

View the site [here](https://mooseframework.inl.gov/docs/PRs/21127/site)

This comment will be updated on new commits.

2022-05-25 00:28 UTC, roystgnr commented
Hooray for getting things into CI early.

I saw the red X, was eagerly deciding how to castigate John for being too insistent on pushing that PR without more work on backwards compatibility ... but the breakage here has absolutely nothing to do with his `Parameters` improvements; I've regressed something in MetaPhysicL.  Looks like it won't be hard to replicate upstream and fix, at least.

2022-05-25 19:15 UTC, moosebuild commented on libmesh
> +Subproject commit 945cc324f449d88c58a08fd8e2a1e521ba1b33a3
**Caution!** This contains a submodule update

2022-05-25 19:15 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/1055556/) on 0272651 wanted to post the following:

The following file(s) are changed:

  conda/mpich/conda_build_config.yaml

The conda configuration has changed; ping @idaholab/moose-dev-ops

2022-05-25 19:29 UTC, loganharbour requested changes
Make sure to mix the submodule update + mpich yaml file change into the same commit, and put it last

2022-05-25 22:26 UTC, moosebuild commented
Job [Coverage](https://civet.inl.gov/job/1055583/) on 0272651 wanted to post the following:


## Framework coverage

Coverage did not change


## Modules coverage

### Contact

<table>
  <thead>
    <tr>
      <th></th>
      <th>74d60f</th>
      <th colspan=4>#21127 027265</th>
    </tr>
    <tr>
      <th></th>
      <th>Total</th>
      <th>Total</th>
      <th>+/-</th>
      <th>New</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><b>Rate</b></td>
      <td>89.01%</td>
      <td>89.02%</td>
      <td>+0.00%</td>
      <td>-</td>
    </tr>
    <tr>
      <td><b>Hits</b></td>
      <td>2876</td>
      <td>2877</td>
      <td>+1</td>
      <td>0</td>
    </tr>
    <tr>
      <td><b>Misses</b></td>
      <td>355</td>
      <td>355</td>
      <td>-</td>
      <td>0</td>
    </tr>
  </tbody>
</table>

[Diff coverage report](https://mooseframework.inl.gov/docs/PRs/21127/coverage_diff/contact)

[Full coverage report](https://mooseframework.inl.gov/docs/PRs/21127/coverage/contact)

### Phase field

<table>
  <thead>
    <tr>
      <th></th>
      <th>74d60f</th>
      <th colspan=4>#21127 027265</th>
    </tr>
    <tr>
      <th></th>
      <th>Total</th>
      <th>Total</th>
      <th>+/-</th>
      <th>New</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><b>Rate</b></td>
      <td>90.21%</td>
      <td>90.21%</td>
      <td>+0.00%</td>
      <td>-</td>
    </tr>
    <tr>
      <td><b>Hits</b></td>
      <td>12040</td>
      <td>12041</td>
      <td>+1</td>
      <td>0</td>
    </tr>
    <tr>
      <td><b>Misses</b></td>
      <td>1307</td>
      <td>1307</td>
      <td>-</td>
      <td>0</td>
    </tr>
  </tbody>
</table>

[Diff coverage report](https://mooseframework.inl.gov/docs/PRs/21127/coverage_diff/phase_field)

[Full coverage report](https://mooseframework.inl.gov/docs/PRs/21127/coverage/phase_field)

## Full coverage reports

<details>
<summary>Reports</summary>

- [`framework`](https://mooseframework.inl.gov/docs/PRs/21127/coverage/framework)
- [`chemical_reactions`](https://mooseframework.inl.gov/docs/PRs/21127/coverage/chemical_reactions)
- [`combined`](https://mooseframework.inl.gov/docs/PRs/21127/coverage/combined)
- [`contact`](https://mooseframework.inl.gov/docs/PRs/21127/coverage/contact)
- [`external_petsc_solver`](https://mooseframework.inl.gov/docs/PRs/21127/coverage/external_petsc_solver)
- [`fluid_properties`](https://mooseframework.inl.gov/docs/PRs/21127/coverage/fluid_properties)
- [`fsi`](https://mooseframework.inl.gov/docs/PRs/21127/coverage/fsi)
- [`functional_expansion_tools`](https://mooseframework.inl.gov/docs/PRs/21127/coverage/functional_expansion_tools)
- [`geochemistry`](https://mooseframework.inl.gov/docs/PRs/21127/coverage/geochemistry)
- [`heat_conduction`](https://mooseframework.inl.gov/docs/PRs/21127/coverage/heat_conduction)
- [`level_set`](https://mooseframework.inl.gov/docs/PRs/21127/coverage/level_set)
- [`misc`](https://mooseframework.inl.gov/docs/PRs/21127/coverage/misc)
- [`navier_stokes`](https://mooseframework.inl.gov/docs/PRs/21127/coverage/navier_stokes)
- [`peridynamics`](https://mooseframework.inl.gov/docs/PRs/21127/coverage/peridynamics)
- [`phase_field`](https://mooseframework.inl.gov/docs/PRs/21127/coverage/phase_field)
- [`porous_flow`](https://mooseframework.inl.gov/docs/PRs/21127/coverage/porous_flow)
- [`ray_tracing`](https://mooseframework.inl.gov/docs/PRs/21127/coverage/ray_tracing)
- [`rdg`](https://mooseframework.inl.gov/docs/PRs/21127/coverage/rdg)
- [`reactor`](https://mooseframework.inl.gov/docs/PRs/21127/coverage/reactor)
- [`richards`](https://mooseframework.inl.gov/docs/PRs/21127/coverage/richards)
- [`stochastic_tools`](https://mooseframework.inl.gov/docs/PRs/21127/coverage/stochastic_tools)
- [`tensor_mechanics`](https://mooseframework.inl.gov/docs/PRs/21127/coverage/tensor_mechanics)
- [`thermal_hydraulics`](https://mooseframework.inl.gov/docs/PRs/21127/coverage/thermal_hydraulics)
- [`xfem`](https://mooseframework.inl.gov/docs/PRs/21127/coverage/xfem)

</details>



This comment will be updated on new commits.

2022-05-27 17:29 UTC, cticenhour requested changes
A few news comments

2022-05-27 17:29 UTC, cticenhour commented on modules/doc/content/newsletter/2022_05.md
> +  comprehensible error message, even in non-debugging-mode builds.
```suggestion
  higher order `FE` type, the mistake is now always reported with a
  comprehensible error message, even in non-debug-mode builds.
```

2022-05-27 17:29 UTC, cticenhour commented on modules/doc/content/newsletter/2022_05.md
> +  now check and report details even in non-debugging-mode builds.
```suggestion
  now check and report details even in non-debug-mode builds.
```

2022-05-27 17:29 UTC, cticenhour commented on modules/doc/content/newsletter/2022_05.md
> +
```suggestion
```

2022-05-27 17:29 UTC, cticenhour commented on modules/doc/content/newsletter/2022_05.md
> +
```suggestion
```

2022-05-27 17:29 UTC, cticenhour commented on modules/doc/content/newsletter/2022_05.md
> +  MeshedHole, so you can mesh with holes while your hole has holes.
```suggestion
  `MeshedHole`, so you can mesh with holes while your hole has holes.
```

2022-05-28 02:16 UTC, moosebuild commented
Job [Test timings](https://civet.inl.gov/job/1059652/) on 0272651 wanted to post the following:

View timings [here](https://mooseframework.inl.gov/docs/PRs/21127/timing)

This comment will be updated on new commits.

2022-06-01 22:08 UTC, loganharbour requested changes, later dismissed
While we're at it, let's add `--enable-xdr-required` in `configure_libmesh.sh`.

2022-06-02 03:38 UTC, moosebuild commented on libmesh
> +Subproject commit b509320095f0df51177bd090548093e5b457ad61
**Caution!** This contains a submodule update

2022-06-02 03:38 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/1065066/) on af82f58 wanted to post the following:

The following file(s) are changed:

  conda/mpich/conda_build_config.yaml

The conda configuration has changed; ping @idaholab/moose-dev-ops

2022-06-02 03:38 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/1065066/) on af82f58 wanted to post the following:

The following file(s) are changed:

  conda/libmesh/meta.yaml

The libmesh conda configuration has changed; ping @idaholab/moose-dev-ops

2022-06-05 20:07 UTC, moosebuild commented on libmesh
> +Subproject commit 4747096de5d6c69ed79f28e38ce45c76546364c3
**Caution!** This contains a submodule update

2022-06-05 20:07 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/1067604/) on e00c192 wanted to post the following:

The following file(s) are changed:

  conda/mpich/conda_build_config.yaml

The conda configuration has changed; ping @idaholab/moose-dev-ops

2022-06-05 20:07 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/1067604/) on e00c192 wanted to post the following:

The following file(s) are changed:

  conda/libmesh/meta.yaml

The libmesh conda configuration has changed; ping @idaholab/moose-dev-ops

2022-06-06 01:39 UTC, roystgnr commented
> loganharbour force-pushed the libmesh_update_202205 branch from af82f58 to e00c192 5 hours ago

Wow - what just happened to get us passing the "Min clang" check!?  My workaround in MetaPhysicL was really all it took?  That's fantastic.

2022-06-06 13:10 UTC, loganharbour commented
Magic!

Just did one more push; I forgot to update the build string.

2022-06-06 13:13 UTC, moosebuild commented on libmesh
> +Subproject commit 4747096de5d6c69ed79f28e38ce45c76546364c3
**Caution!** This contains a submodule update

2022-06-06 13:13 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/1067791/) on 2997c1f wanted to post the following:

The following file(s) are changed:

  conda/mpich/conda_build_config.yaml

The conda configuration has changed; ping @idaholab/moose-dev-ops

2022-06-06 13:13 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/1067791/) on 2997c1f wanted to post the following:

The following file(s) are changed:

  conda/libmesh/meta.yaml

The libmesh conda configuration has changed; ping @idaholab/moose-dev-ops

2022-06-06 13:21 UTC, milljm approved these changes
👍

2022-06-06 17:01 UTC, cticenhour approved these changes
I will move this news update to the proper spot in June as part of my news PR. Otherwise looks good.

2022-06-06 17:03 UTC, merged