More info in NS param checking, more selective checking
idaholab/moose pull request #21280
Opened 2022-06-13 05:06 UTC by GiudGiud

This fixes errors in MSFR with the new conditions on when to check the inlet BCs for scalars

2022-06-13 05:08 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/1075836/) on 8711920 wanted to post the following:

Your code requires style changes.  

A patch was auto generated and copied [here](https://mooseframework.inl.gov/docs/PRs/21280/clang_format/style.patch)  
You can directly apply the patch by running, in the top level of your repository:

`curl -s https://mooseframework.inl.gov/docs/PRs/21280/clang_format/style.patch | git apply -v`  

Alternatively, with your repository up to date and in the top level of your repository:

`git clang-format 3ac62c91d27de925aa6b802912ff16798f79e84d`

2022-06-13 06:14 UTC, moosebuild commented
Job [Documentation](https://civet.inl.gov/job/1075899/) on f4b537f wanted to post the following:

View the site [here](https://mooseframework.inl.gov/docs/PRs/21280/site)

This comment will be updated on new commits.

2022-06-13 15:57 UTC, grmnptr submitted a review, later dismissed
Very nice change, cleans up a lot of the error messages!

2022-06-13 16:17 UTC, lindsayad requested changes

2022-06-13 16:17 UTC, lindsayad commented on modules/navier_stokes/include/actions/NSFVAction.h
> +                             std::string object_name_1);
```suggestion
                             const std::string & param_name_1,
                             const std::string & param_name_2,
                             const std::string & object_name_1);
```

2022-06-13 16:17 UTC, lindsayad commented on modules/navier_stokes/include/actions/NSFVAction.h
> +                      std::string param_name,
```suggestion
                      const std::string & param_name,
```

2022-06-13 16:17 UTC, lindsayad commented on modules/navier_stokes/include/actions/NSFVAction.h
> +                      std::string size_source_explanation);
```suggestion
                      const std::string & object_name,
                      const std::string & size_source_explanation);
```

2022-06-14 01:55 UTC, GiudGiud commented
Should be fixed now

2022-06-14 03:33 UTC, lindsayad approved these changes

2022-06-14 04:34 UTC, merged