Add extra-js to MooseDocs
idaholab/moose pull request #21323
Opened 2022-06-16 17:40 UTC by vanwdani

closes #20936

2022-06-16 18:36 UTC, moosebuild commented
Job [Documentation](https://civet.inl.gov/job/1081413/) on 9798b0c wanted to post the following:

View the site [here](https://mooseframework.inl.gov/docs/PRs/21322/site)

This comment will be updated on new commits.

2022-06-16 19:43 UTC, moosebuild commented
Job [Coverage](https://civet.inl.gov/job/1081440/) on 9798b0c wanted to post the following:


## Framework coverage

No coverage report(s) were found for the head

## Modules coverage

No coverage report(s) were found for the head

## Full coverage reports

<details>
<summary>Reports</summary>

- `framework` (FAILED)
- `chemical_reactions` (FAILED)
- `combined` (FAILED)
- `contact` (FAILED)
- `external_petsc_solver` (FAILED)
- `fluid_properties` (FAILED)
- `fsi` (FAILED)
- `functional_expansion_tools` (FAILED)
- `geochemistry` (FAILED)
- `heat_conduction` (FAILED)
- `level_set` (FAILED)
- `misc` (FAILED)
- `navier_stokes` (FAILED)
- `peridynamics` (FAILED)
- `phase_field` (FAILED)
- `porous_flow` (FAILED)
- `ray_tracing` (FAILED)
- `rdg` (FAILED)
- `reactor` (FAILED)
- `richards` (FAILED)
- `stochastic_tools` (FAILED)
- `tensor_mechanics` (FAILED)
- `thermal_hydraulics` (FAILED)
- `xfem` (FAILED)

</details>



This comment will be updated on new commits.

2022-06-16 19:43 UTC, moosebuild commented
Job [Coverage](https://civet.inl.gov/job/1081440/) on 9798b0c wanted to post the following:


The following coverage requirement(s) failed:
- Failed to generate `framework` coverage rate (required: 81.0%)
- Failed to generate `chemical_reactions` coverage rate (required: 93.0%)
- Failed to generate `combined` coverage rate (required: 37.0%)
- Failed to generate `contact` coverage rate (required: 87.0%)
- Failed to generate `external_petsc_solver` coverage rate (required: 86.0%)
- Failed to generate `fluid_properties` coverage rate (required: 84.0%)
- Failed to generate `fsi` coverage rate (required: 91.0%)
- Failed to generate `functional_expansion_tools` coverage rate (required: 83.0%)
- Failed to generate `geochemistry` coverage rate (required: 96.0%)
- Failed to generate `heat_conduction` coverage rate (required: 87.0%)
- Failed to generate `level_set` coverage rate (required: 88.0%)
- Failed to generate `misc` coverage rate (required: 55.0%)
- Failed to generate `navier_stokes` coverage rate (required: 77.0%)
- Failed to generate `peridynamics` coverage rate (required: 78.0%)
- Failed to generate `phase_field` coverage rate (required: 89.0%)
- Failed to generate `porous_flow` coverage rate (required: 96.0%)
- Failed to generate `ray_tracing` coverage rate (required: 94.0%)
- Failed to generate `rdg` coverage rate (required: 65.0%)
- Failed to generate `reactor` coverage rate (required: 90.0%)
- Failed to generate `richards` coverage rate (required: 97.0%)
- Failed to generate `stochastic_tools` coverage rate (required: 88.0%)
- Failed to generate `tensor_mechanics` coverage rate (required: 86.0%)
- Failed to generate `thermal_hydraulics` coverage rate (required: 90.0%)
- Failed to generate `xfem` coverage rate (required: 80.0%)

2022-06-16 21:26 UTC, moosebuild commented
Job [Coverage](https://civet.inl.gov/job/1081440/) on 9798b0c wanted to post the following:


The following coverage requirement(s) failed:
- Failed to generate `framework` coverage rate (required: 81.0%)
- Failed to generate `chemical_reactions` coverage rate (required: 93.0%)
- Failed to generate `combined` coverage rate (required: 37.0%)
- Failed to generate `contact` coverage rate (required: 87.0%)
- Failed to generate `external_petsc_solver` coverage rate (required: 86.0%)
- Failed to generate `fluid_properties` coverage rate (required: 84.0%)
- Failed to generate `fsi` coverage rate (required: 91.0%)
- Failed to generate `functional_expansion_tools` coverage rate (required: 83.0%)
- Failed to generate `geochemistry` coverage rate (required: 96.0%)
- Failed to generate `heat_conduction` coverage rate (required: 87.0%)
- Failed to generate `level_set` coverage rate (required: 88.0%)
- Failed to generate `misc` coverage rate (required: 55.0%)
- Failed to generate `navier_stokes` coverage rate (required: 77.0%)
- Failed to generate `peridynamics` coverage rate (required: 78.0%)
- Failed to generate `phase_field` coverage rate (required: 89.0%)
- Failed to generate `porous_flow` coverage rate (required: 96.0%)
- Failed to generate `ray_tracing` coverage rate (required: 94.0%)
- Failed to generate `rdg` coverage rate (required: 65.0%)
- Failed to generate `reactor` coverage rate (required: 90.0%)
- Failed to generate `richards` coverage rate (required: 97.0%)
- Failed to generate `stochastic_tools` coverage rate (required: 88.0%)
- Failed to generate `tensor_mechanics` coverage rate (required: 86.0%)
- Failed to generate `thermal_hydraulics` coverage rate (required: 90.0%)
- Failed to generate `xfem` coverage rate (required: 80.0%)

2022-06-17 13:39 UTC, dschwen requested changes

2022-06-17 13:42 UTC, dschwen commented
Any idea why the coverage failed to generate @loganharbour ?

2022-06-22 15:26 UTC, dschwen approved these changes

2022-06-23 00:41 UTC, GiudGiud commented
Coverage fails to generate when the PR was based off of next instead of devel usually

2022-06-23 01:18 UTC, merged