Add option to allow nodal-to-elemental coupling
idaholab/moose pull request #21436
Opened 2022-06-27 20:58 UTC by liamncarlson

Closes #21434

2022-06-27 21:01 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/1091046/) on 341c606 wanted to post the following:

Your code requires style changes.  

A patch was auto generated and copied [here](https://mooseframework.inl.gov/docs/PRs/21436/clang_format/style.patch)  
You can directly apply the patch by running, in the top level of your repository:

`curl -s https://mooseframework.inl.gov/docs/PRs/21436/clang_format/style.patch | git apply -v`  

Alternatively, with your repository up to date and in the top level of your repository:

`git clang-format 41a07d673011fdbe59b4b71450ab668c678c716e`

2022-06-27 21:03 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/1091081/) on 30be45c wanted to post the following:

Your code requires style changes.  

A patch was auto generated and copied [here](https://mooseframework.inl.gov/docs/PRs/21436/clang_format/style.patch)  
You can directly apply the patch by running, in the top level of your repository:

`curl -s https://mooseframework.inl.gov/docs/PRs/21436/clang_format/style.patch | git apply -v`  

Alternatively, with your repository up to date and in the top level of your repository:

`git clang-format 41a07d673011fdbe59b4b71450ab668c678c716e`

2022-06-28 04:11 UTC, GiudGiud requested changes

2022-06-28 04:11 UTC, GiudGiud commented on framework/include/interfaces/Coupleable.h
> +  bool const _c_allow_element_to_nodal_coupling
```suggestion
  const bool _c_allow_element_to_nodal_coupling;
```

2022-06-28 16:15 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/1092057/) on 672e34c wanted to post the following:

Your code requires style changes.  

A patch was auto generated and copied [here](https://mooseframework.inl.gov/docs/PRs/21436/clang_format/style.patch)  
You can directly apply the patch by running, in the top level of your repository:

`curl -s https://mooseframework.inl.gov/docs/PRs/21436/clang_format/style.patch | git apply -v`  

Alternatively, with your repository up to date and in the top level of your repository:

`git clang-format 41a07d673011fdbe59b4b71450ab668c678c716e`

2022-06-29 14:01 UTC, loganharbour commented
@liamncarlson you've still got some clang-formatting to take care of. come chat with me today and we can talk about docuemntation

2022-06-30 21:28 UTC, YaqiWang commented
You need to squash all commits into one. You can do
```
git reset HEAD~6
```
first and re-add the changes and commit.

2022-06-30 21:29 UTC, moosebuild commented
Job [Documentation](https://civet.inl.gov/job/1097395/) on 4ae1a11 wanted to post the following:

View the site [here](https://mooseframework.inl.gov/docs/PRs/21436/site)

This comment will be updated on new commits.

2022-06-30 22:51 UTC, moosebuild commented
Job [Coverage](https://civet.inl.gov/job/1097405/) on 4ae1a11 wanted to post the following:


## Framework coverage

<table>
  <thead>
    <tr>
      <th></th>
      <th>68a733</th>
      <th colspan=4>#21436 4ae1a1</th>
    </tr>
    <tr>
      <th></th>
      <th>Total</th>
      <th>Total</th>
      <th>+/-</th>
      <th>New</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><b>Rate</b></td>
      <td>83.49%</td>
      <td>83.49%</td>
      <td>+0.00%</td>
      <td>100.00%</td>
    </tr>
    <tr>
      <td><b>Hits</b></td>
      <td>77471</td>
      <td>77473</td>
      <td>+2</td>
      <td>3</td>
    </tr>
    <tr>
      <td><b>Misses</b></td>
      <td>15316</td>
      <td>15316</td>
      <td>-</td>
      <td>0</td>
    </tr>
  </tbody>
</table>

[Diff coverage report](https://mooseframework.inl.gov/docs/PRs/21436/coverage_diff/framework)

[Full coverage report](https://mooseframework.inl.gov/docs/PRs/21436/coverage/framework)


## Modules coverage

Coverage did not change

## Full coverage reports

<details>
<summary>Reports</summary>

- [`framework`](https://mooseframework.inl.gov/docs/PRs/21436/coverage/framework)
- [`chemical_reactions`](https://mooseframework.inl.gov/docs/PRs/21436/coverage/chemical_reactions)
- [`combined`](https://mooseframework.inl.gov/docs/PRs/21436/coverage/combined)
- [`contact`](https://mooseframework.inl.gov/docs/PRs/21436/coverage/contact)
- [`electromagnetics`](https://mooseframework.inl.gov/docs/PRs/21436/coverage/electromagnetics)
- [`external_petsc_solver`](https://mooseframework.inl.gov/docs/PRs/21436/coverage/external_petsc_solver)
- [`fluid_properties`](https://mooseframework.inl.gov/docs/PRs/21436/coverage/fluid_properties)
- [`fsi`](https://mooseframework.inl.gov/docs/PRs/21436/coverage/fsi)
- [`functional_expansion_tools`](https://mooseframework.inl.gov/docs/PRs/21436/coverage/functional_expansion_tools)
- [`geochemistry`](https://mooseframework.inl.gov/docs/PRs/21436/coverage/geochemistry)
- [`heat_conduction`](https://mooseframework.inl.gov/docs/PRs/21436/coverage/heat_conduction)
- [`level_set`](https://mooseframework.inl.gov/docs/PRs/21436/coverage/level_set)
- [`misc`](https://mooseframework.inl.gov/docs/PRs/21436/coverage/misc)
- [`navier_stokes`](https://mooseframework.inl.gov/docs/PRs/21436/coverage/navier_stokes)
- [`peridynamics`](https://mooseframework.inl.gov/docs/PRs/21436/coverage/peridynamics)
- [`phase_field`](https://mooseframework.inl.gov/docs/PRs/21436/coverage/phase_field)
- [`porous_flow`](https://mooseframework.inl.gov/docs/PRs/21436/coverage/porous_flow)
- [`ray_tracing`](https://mooseframework.inl.gov/docs/PRs/21436/coverage/ray_tracing)
- [`rdg`](https://mooseframework.inl.gov/docs/PRs/21436/coverage/rdg)
- [`reactor`](https://mooseframework.inl.gov/docs/PRs/21436/coverage/reactor)
- [`richards`](https://mooseframework.inl.gov/docs/PRs/21436/coverage/richards)
- [`stochastic_tools`](https://mooseframework.inl.gov/docs/PRs/21436/coverage/stochastic_tools)
- [`tensor_mechanics`](https://mooseframework.inl.gov/docs/PRs/21436/coverage/tensor_mechanics)
- [`thermal_hydraulics`](https://mooseframework.inl.gov/docs/PRs/21436/coverage/thermal_hydraulics)
- [`xfem`](https://mooseframework.inl.gov/docs/PRs/21436/coverage/xfem)

</details>



This comment will be updated on new commits.

2022-07-05 23:58 UTC, liamncarlson reviewed
Changes added

2022-07-06 00:00 UTC, GiudGiud approved these changes

2022-07-06 00:00 UTC, merged