Fix false positive cyclic dep error for block-restricted discrete materials
idaholab/moose pull request #21544
Opened 2022-07-09 00:58 UTC by hugary1995

close #21537

2022-07-09 02:03 UTC, moosebuild commented
Job [Documentation](https://civet.inl.gov/job/1105915/) on d0c6395 wanted to post the following:

View the site [here](https://mooseframework.inl.gov/docs/PRs/21544/site)

This comment will be updated on new commits.

2022-07-09 03:18 UTC, moosebuild commented
Job [Coverage](https://civet.inl.gov/job/1105925/) on d0c6395 wanted to post the following:


## Framework coverage

<table>
  <thead>
    <tr>
      <th></th>
      <th>195b98</th>
      <th colspan=4>#21544 d0c639</th>
    </tr>
    <tr>
      <th></th>
      <th>Total</th>
      <th>Total</th>
      <th>+/-</th>
      <th>New</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><b>Rate</b></td>
      <td>83.53%</td>
      <td>83.53%</td>
      <td>-0.00%</td>
      <td>100.00%</td>
    </tr>
    <tr>
      <td><b>Hits</b></td>
      <td>77810</td>
      <td>77806</td>
      <td>-4</td>
      <td>10</td>
    </tr>
    <tr>
      <td><b>Misses</b></td>
      <td>15339</td>
      <td>15343</td>
      <td>+4</td>
      <td>0</td>
    </tr>
  </tbody>
</table>

[Diff coverage report](https://mooseframework.inl.gov/docs/PRs/21544/coverage_diff/framework)

[Full coverage report](https://mooseframework.inl.gov/docs/PRs/21544/coverage/framework)


## Modules coverage

Coverage did not change

## Full coverage reports

<details>
<summary>Reports</summary>

- [`framework`](https://mooseframework.inl.gov/docs/PRs/21544/coverage/framework)
- [`chemical_reactions`](https://mooseframework.inl.gov/docs/PRs/21544/coverage/chemical_reactions)
- [`combined`](https://mooseframework.inl.gov/docs/PRs/21544/coverage/combined)
- [`contact`](https://mooseframework.inl.gov/docs/PRs/21544/coverage/contact)
- [`electromagnetics`](https://mooseframework.inl.gov/docs/PRs/21544/coverage/electromagnetics)
- [`external_petsc_solver`](https://mooseframework.inl.gov/docs/PRs/21544/coverage/external_petsc_solver)
- [`fluid_properties`](https://mooseframework.inl.gov/docs/PRs/21544/coverage/fluid_properties)
- [`fsi`](https://mooseframework.inl.gov/docs/PRs/21544/coverage/fsi)
- [`functional_expansion_tools`](https://mooseframework.inl.gov/docs/PRs/21544/coverage/functional_expansion_tools)
- [`geochemistry`](https://mooseframework.inl.gov/docs/PRs/21544/coverage/geochemistry)
- [`heat_conduction`](https://mooseframework.inl.gov/docs/PRs/21544/coverage/heat_conduction)
- [`level_set`](https://mooseframework.inl.gov/docs/PRs/21544/coverage/level_set)
- [`misc`](https://mooseframework.inl.gov/docs/PRs/21544/coverage/misc)
- [`navier_stokes`](https://mooseframework.inl.gov/docs/PRs/21544/coverage/navier_stokes)
- [`peridynamics`](https://mooseframework.inl.gov/docs/PRs/21544/coverage/peridynamics)
- [`phase_field`](https://mooseframework.inl.gov/docs/PRs/21544/coverage/phase_field)
- [`porous_flow`](https://mooseframework.inl.gov/docs/PRs/21544/coverage/porous_flow)
- [`ray_tracing`](https://mooseframework.inl.gov/docs/PRs/21544/coverage/ray_tracing)
- [`rdg`](https://mooseframework.inl.gov/docs/PRs/21544/coverage/rdg)
- [`reactor`](https://mooseframework.inl.gov/docs/PRs/21544/coverage/reactor)
- [`richards`](https://mooseframework.inl.gov/docs/PRs/21544/coverage/richards)
- [`stochastic_tools`](https://mooseframework.inl.gov/docs/PRs/21544/coverage/stochastic_tools)
- [`tensor_mechanics`](https://mooseframework.inl.gov/docs/PRs/21544/coverage/tensor_mechanics)
- [`thermal_hydraulics`](https://mooseframework.inl.gov/docs/PRs/21544/coverage/thermal_hydraulics)
- [`xfem`](https://mooseframework.inl.gov/docs/PRs/21544/coverage/xfem)

</details>



This comment will be updated on new commits.

2022-07-11 15:44 UTC, lindsayad requested changes
I think I prefer a solution where we simply do not try to resolve a circular graph, e.g. don't sort `_all_materials`. Did you try that?

2022-07-11 16:18 UTC, lindsayad commented
To do that you can make `sort` in `MooseObjectWarehouseBase` virtual, and then `override` in `MaterialsWarehouse`

2022-07-11 16:21 UTC, hugary1995 commented
> To do that you can make `sort` in `MooseObjectWarehouseBase` virtual, and then `override` in `MaterialsWarehouse`

I think I tried this last Friday, but I got compiling errors saying something like "In instantiation of xxx, MooseVariableBase doesn't have method getSuppliedItems", and then I didn't look into it. I'll take another look at it.

2022-07-11 17:28 UTC, hugary1995 commented
This is getting into the part of code I am unfamiliar with, and I'm afraid the solution isn't just adding enable_ifs to `sort()` or `sortDFS()`.

2022-07-11 19:15 UTC, lindsayad commented
I'll take a look

2022-07-11 19:27 UTC, lindsayad commented
Ok yea the unfortunate part of having it `virtual` is that `sort` gets instantiated for all instances of `MooseObjectWarehouseBase`. So that's not going to work without adding `DependencyResolverInterface` to a lot more systems. 

But luckly `MaterialsWarehouse` already has its own `sort`, so you can just modify that, no `virtual` required

2022-07-12 17:09 UTC, lindsayad requested changes
Looks good. Could you slightly bump the exodiff tolerance for that adaptivity test that's failing with distributed threads? Looks like it's just above our default `5.5e-6`

2022-07-12 17:09 UTC, lindsayad commented on framework/include/warehouses/MooseObjectWarehouseBase.h
> +class MaterialWarehouse;
This should be unnecessary I believe.

2022-07-12 17:09 UTC, lindsayad commented on framework/include/warehouses/MooseObjectWarehouseBase.h
> +  friend class MaterialWarehouse;
This alone should be sufficient for friend class declaration I believe

2022-07-12 19:17 UTC, lindsayad approved these changes

2022-07-13 13:48 UTC, hugary1995 commented
The auto merge label isn't working for some reason. I guess that is because I didn't resolve one of the conversation at the time civet completed all tests.

2022-07-13 13:59 UTC, merged

2022-07-13 15:40 UTC, loganharbour commented
> The auto merge label isn't working for some reason. I guess that is because I didn't resolve one of the conversation at the time civet completed all tests.

FYI, auto merge doesn't work when things fail that are allowed to fail: https://civet.inl.gov/job/1108271/