Use main branch for storking new apps
idaholab/moose pull request #21613
Opened 2022-07-18 19:00 UTC by GiudGiud

Came up live in a tutorial today :( 
refs #20124

2022-07-18 20:08 UTC, moosebuild commented
Job [Documentation](https://civet.inl.gov/job/1113515/) on ff3ece1 wanted to post the following:

View the site [here](https://mooseframework.inl.gov/docs/PRs/21613/site)

This comment will be updated on new commits.

2022-08-06 16:52 UTC, cticenhour requested changes
Should reference #16883 instead. I invalidated all of the cancelled CIVET recipes before I noticed this, so while making this change in your commit message, might want to rebase on current devel.

2022-08-06 18:04 UTC, cticenhour requested changes

2022-08-06 18:04 UTC, cticenhour commented on scripts/stork.sh
> +    (cd $dir && git init -b main && git add * .clang-format .gitignore && git commit -m"Initial files")
```suggestion
    (cd $dir && git init && git branch -m main && git add * .clang-format .gitignore && git commit -m"Initial files")
```
This change is more backwards compatible with `git < 2.28`, which did not have a `-b` flag for `git-init`.

2022-08-13 16:40 UTC, GiudGiud commented
thanks for the fix!
Changed the issue in the commit and rebased on devel. Should be good now

2022-08-13 18:27 UTC, moosebuild commented
Job [Coverage](https://civet.inl.gov/job/1141888/) on 2524b0b wanted to post the following:


The following coverage requirement(s) failed:
- Failed to generate `framework` coverage rate (required: 81.0%)

2022-08-16 21:11 UTC, GiudGiud commented
@cticenhour

2022-08-16 21:15 UTC, cticenhour commented
Still seeing the prior issue number in the commit message. Could you amend this again? Otherwise this looks good.

2022-08-16 21:20 UTC, GiudGiud commented
weird I really thought I had fixed that. Must have dreamed it.
should be good now

2022-08-16 21:25 UTC, cticenhour approved these changes

2022-08-17 17:02 UTC, merged