This is an incomplete commit. Establishes SymmetryTransformerGenerator.
idaholab/moose pull request #21718
Opened 2022-07-28 20:44 UTC by RocksSavage

Beware, the option to optionally use StitchedMeshGenerator has not been tested. Tests have not been written.
I would appreciate it if the test currently in simple.i would end up in the documentation as an example of what
default parameters are ran when the stitch option is exercised.

## Reason

## Design

## Impact

2022-11-02 19:59 UTC, GiudGiud commented
This is on hold until we can get better fixing of negative volumes in libmesh

2022-11-23 20:59 UTC, GiudGiud commented
This will be near-ready on the next libmesh submodule update.

2023-01-02 23:28 UTC, GiudGiud commented
@loganharbour this should be ready for review please

2023-01-02 23:39 UTC, GiudGiud commented
nevermind still no libmesh update

2023-01-10 23:28 UTC, GiudGiud commented
@loganharbour ready for review.

I've had to add a bit of lower quality code (const_cast) to allow for a sub-generator to run after a main generator. 
If that's not agreeable, then I reckon I want to delete the stitching and get this merged.

2023-01-11 02:02 UTC, moosebuild commented
Job [Documentation](https://civet.inl.gov/job/1294168/) on 2f17d47 wanted to post the following:

View the site [here](https://mooseframework.inl.gov/docs/PRs/21718/site)

This comment will be updated on new commits.

2023-01-11 04:38 UTC, moosebuild commented
Job [Coverage](https://civet.inl.gov/job/1294628/) on 0b2bbdf wanted to post the following:


## Framework coverage

<table>
  <thead>
    <tr>
      <th></th>
      <th>cd277b</th>
      <th colspan=4>#21718 0b2bbd</th>
    </tr>
    <tr>
      <th></th>
      <th>Total</th>
      <th>Total</th>
      <th>+/-</th>
      <th>New</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><b>Rate</b></td>
      <td>84.53%</td>
      <td>84.54%</td>
      <td>+0.01%</td>
      <td>90.91%</td>
    </tr>
    <tr>
      <td><b>Hits</b></td>
      <td>81635</td>
      <td>81687</td>
      <td>+52</td>
      <td>50</td>
    </tr>
    <tr>
      <td><b>Misses</b></td>
      <td>14936</td>
      <td>14938</td>
      <td>+2</td>
      <td>5</td>
    </tr>
  </tbody>
</table>

[Diff coverage report](https://mooseframework.inl.gov/docs/PRs/21718/coverage_diff/framework)

[Full coverage report](https://mooseframework.inl.gov/docs/PRs/21718/coverage/framework)


## Modules coverage

Coverage did not change

## Full coverage reports

<details>
<summary>Reports</summary>

- [`framework`](https://mooseframework.inl.gov/docs/PRs/21718/coverage/framework)
- [`chemical_reactions`](https://mooseframework.inl.gov/docs/PRs/21718/coverage/chemical_reactions)
- [`combined`](https://mooseframework.inl.gov/docs/PRs/21718/coverage/combined)
- [`contact`](https://mooseframework.inl.gov/docs/PRs/21718/coverage/contact)
- [`electromagnetics`](https://mooseframework.inl.gov/docs/PRs/21718/coverage/electromagnetics)
- [`external_petsc_solver`](https://mooseframework.inl.gov/docs/PRs/21718/coverage/external_petsc_solver)
- [`fluid_properties`](https://mooseframework.inl.gov/docs/PRs/21718/coverage/fluid_properties)
- [`fsi`](https://mooseframework.inl.gov/docs/PRs/21718/coverage/fsi)
- [`functional_expansion_tools`](https://mooseframework.inl.gov/docs/PRs/21718/coverage/functional_expansion_tools)
- [`geochemistry`](https://mooseframework.inl.gov/docs/PRs/21718/coverage/geochemistry)
- [`heat_conduction`](https://mooseframework.inl.gov/docs/PRs/21718/coverage/heat_conduction)
- [`level_set`](https://mooseframework.inl.gov/docs/PRs/21718/coverage/level_set)
- [`misc`](https://mooseframework.inl.gov/docs/PRs/21718/coverage/misc)
- [`navier_stokes`](https://mooseframework.inl.gov/docs/PRs/21718/coverage/navier_stokes)
- [`optimization`](https://mooseframework.inl.gov/docs/PRs/21718/coverage/optimization)
- [`peridynamics`](https://mooseframework.inl.gov/docs/PRs/21718/coverage/peridynamics)
- [`phase_field`](https://mooseframework.inl.gov/docs/PRs/21718/coverage/phase_field)
- [`porous_flow`](https://mooseframework.inl.gov/docs/PRs/21718/coverage/porous_flow)
- [`ray_tracing`](https://mooseframework.inl.gov/docs/PRs/21718/coverage/ray_tracing)
- [`rdg`](https://mooseframework.inl.gov/docs/PRs/21718/coverage/rdg)
- [`reactor`](https://mooseframework.inl.gov/docs/PRs/21718/coverage/reactor)
- [`richards`](https://mooseframework.inl.gov/docs/PRs/21718/coverage/richards)
- [`scalar_transport`](https://mooseframework.inl.gov/docs/PRs/21718/coverage/scalar_transport)
- [`solid_properties`](https://mooseframework.inl.gov/docs/PRs/21718/coverage/solid_properties)
- [`stochastic_tools`](https://mooseframework.inl.gov/docs/PRs/21718/coverage/stochastic_tools)
- [`tensor_mechanics`](https://mooseframework.inl.gov/docs/PRs/21718/coverage/tensor_mechanics)
- [`thermal_hydraulics`](https://mooseframework.inl.gov/docs/PRs/21718/coverage/thermal_hydraulics)
- [`xfem`](https://mooseframework.inl.gov/docs/PRs/21718/coverage/xfem)

</details>



This comment will be updated on new commits.

2023-01-11 15:45 UTC, loganharbour requested changes
I'm really against the subgenerator for a few reasons:

1. The implementation of the before action is poor. This is resolvable and thus is minor.
2. I think that it will be confusing if we allow the addition of subgens like this. We could end up in a position where we could end up with a wonky graph that isn't intuitive to debug. 
3. The action of the stitching is so simple and only requires copying one input to another in another MG. I think it's a poor use of the subgenerator system. It makes it look like we're okay with having a ton of meta generators - which I think is a poor idea because the best part of the MG system is its pluggability, and having to maintain all of that meta interaction sounds awful.

2023-01-11 15:45 UTC, loganharbour commented on framework/src/meshgenerators/MeshGenerator.C
> +    return _app.getMeshGeneratorOutput(name);
I've got a cleaner way to do this - I'll work on it this morning

2023-01-11 15:45 UTC, loganharbour commented on framework/src/meshgenerators/SymmetryTransformGenerator.C
> +               "components were specified.");
paramErrors

2023-01-11 15:45 UTC, loganharbour commented on framework/include/meshgenerators/SymmetryTransformGenerator.h
> +  std::vector<std::vector<std::string>> _stitch_boundaries_pairs;
Const where possible

2023-01-12 02:04 UTC, GiudGiud commented on framework/include/meshgenerators/SymmetryTransformGenerator.h
> +  std::vector<std::vector<std::string>> _stitch_boundaries_pairs;
should be max now

2023-01-12 02:04 UTC, moosebuild commented
All [jobs](https://civet.inl.gov/event/106075/) on 48111e4 : invalidated by @GiudGiud

2023-01-12 02:06 UTC, GiudGiud commented
Should be good now

2023-01-19 14:23 UTC, loganharbour approved these changes

2023-01-19 14:23 UTC, merged

2023-01-19 16:05 UTC, GiudGiud commented
Thanks for the contribution @RocksSavage !
I hope all is well in Utah