Distinguish High Angle and Low Angle GB and Assign different diffusivities or other grain parameters
idaholab/moose pull request #21753
Opened 2022-08-02 16:00 UTC by Linwitness

closes #21704

## Reason

The element diffusion will be affected by Grain Boundary (GB) type: It diffuse faster in High Angle GB (HAGB) than in Low Angle GB (LAGB). The distinguishing of the two GB types can increase the diffusion model accuracy.

## Design

The feature include two phases. In the first phase, a grain growth simulation will distinguish the GB type based on the misorientation from EBSD data and smooth the sharp GBs. As the following figure shown, LAGB is assign "1", HAGB is assign "2", and the Triple junction is assigned an interpolated value. In the second phase, a diffusion simulation will build the "bnds" for different GB types from the result of first phase. Then, we can use the different "bnds" to assign the continuous local diffusivity.
![image](https://user-images.githubusercontent.com/58009812/182419333-116ba2a2-f426-4d48-ab78-1d802e6acf1e.png)

## Impact

With the new feature, MOOSE can read the EBSD data and derive the local diffusivity or other grain parameters. Also, the more accurate effective diffusivity from the feature can be used to evaluate the influence of grain structure, like different grain size, aspect ratio, and the percentage of HAGB.

2022-08-02 16:02 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/1126192/) on 47f9d20 wanted to post the following:

Your code requires style changes.  

A patch was auto generated and copied [here](https://mooseframework.inl.gov/docs/PRs/21753/clang_format/style.patch)  
You can directly apply the patch by running, in the top level of your repository:

`curl -s https://mooseframework.inl.gov/docs/PRs/21753/clang_format/style.patch | git apply -v`  

Alternatively, with your repository up to date and in the top level of your repository:

`git clang-format d672f863d19813cf7021e6e1a044d8e445e9a340`

2022-08-02 16:06 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/1126245/) on dea6375 wanted to post the following:

Your code requires style changes.  

A patch was auto generated and copied [here](https://mooseframework.inl.gov/docs/PRs/21753/clang_format/style.patch)  
You can directly apply the patch by running, in the top level of your repository:

`curl -s https://mooseframework.inl.gov/docs/PRs/21753/clang_format/style.patch | git apply -v`  

Alternatively, with your repository up to date and in the top level of your repository:

`git clang-format d672f863d19813cf7021e6e1a044d8e445e9a340`

2022-08-02 16:07 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/1126245/) on dea6375 wanted to post the following:

Your code requires style changes.  

A patch was auto generated and copied [here](https://mooseframework.inl.gov/docs/PRs/21753/clang_format/style.patch)  
You can directly apply the patch by running, in the top level of your repository:

`curl -s https://mooseframework.inl.gov/docs/PRs/21753/clang_format/style.patch | git apply -v`  

Alternatively, with your repository up to date and in the top level of your repository:

`git clang-format d672f863d19813cf7021e6e1a044d8e445e9a340`

2022-08-02 16:07 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/1126245/) on dea6375 wanted to post the following:

Your code requires style changes.  

A patch was auto generated and copied [here](https://mooseframework.inl.gov/docs/PRs/21753/clang_format/style.patch)  
You can directly apply the patch by running, in the top level of your repository:

`curl -s https://mooseframework.inl.gov/docs/PRs/21753/clang_format/style.patch | git apply -v`  

Alternatively, with your repository up to date and in the top level of your repository:

`git clang-format d672f863d19813cf7021e6e1a044d8e445e9a340`

2022-08-02 16:08 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/1126245/) on dea6375 wanted to post the following:

Your code requires style changes.  

A patch was auto generated and copied [here](https://mooseframework.inl.gov/docs/PRs/21753/clang_format/style.patch)  
You can directly apply the patch by running, in the top level of your repository:

`curl -s https://mooseframework.inl.gov/docs/PRs/21753/clang_format/style.patch | git apply -v`  

Alternatively, with your repository up to date and in the top level of your repository:

`git clang-format d672f863d19813cf7021e6e1a044d8e445e9a340`

2022-08-02 16:09 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/1126245/) on dea6375 wanted to post the following:

Your code requires style changes.  

A patch was auto generated and copied [here](https://mooseframework.inl.gov/docs/PRs/21753/clang_format/style.patch)  
You can directly apply the patch by running, in the top level of your repository:

`curl -s https://mooseframework.inl.gov/docs/PRs/21753/clang_format/style.patch | git apply -v`  

Alternatively, with your repository up to date and in the top level of your repository:

`git clang-format d672f863d19813cf7021e6e1a044d8e445e9a340`

2022-08-02 16:09 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/1126245/) on dea6375 wanted to post the following:

Your code requires style changes.  

A patch was auto generated and copied [here](https://mooseframework.inl.gov/docs/PRs/21753/clang_format/style.patch)  
You can directly apply the patch by running, in the top level of your repository:

`curl -s https://mooseframework.inl.gov/docs/PRs/21753/clang_format/style.patch | git apply -v`  

Alternatively, with your repository up to date and in the top level of your repository:

`git clang-format d672f863d19813cf7021e6e1a044d8e445e9a340`

2022-08-02 16:10 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/1126245/) on dea6375 wanted to post the following:

Your code requires style changes.  

A patch was auto generated and copied [here](https://mooseframework.inl.gov/docs/PRs/21753/clang_format/style.patch)  
You can directly apply the patch by running, in the top level of your repository:

`curl -s https://mooseframework.inl.gov/docs/PRs/21753/clang_format/style.patch | git apply -v`  

Alternatively, with your repository up to date and in the top level of your repository:

`git clang-format d672f863d19813cf7021e6e1a044d8e445e9a340`

2022-08-02 16:10 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/1126245/) on dea6375 wanted to post the following:

Your code requires style changes.  

A patch was auto generated and copied [here](https://mooseframework.inl.gov/docs/PRs/21753/clang_format/style.patch)  
You can directly apply the patch by running, in the top level of your repository:

`curl -s https://mooseframework.inl.gov/docs/PRs/21753/clang_format/style.patch | git apply -v`  

Alternatively, with your repository up to date and in the top level of your repository:

`git clang-format d672f863d19813cf7021e6e1a044d8e445e9a340`

2022-08-02 16:11 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/1126245/) on dea6375 wanted to post the following:

Your code requires style changes.  

A patch was auto generated and copied [here](https://mooseframework.inl.gov/docs/PRs/21753/clang_format/style.patch)  
You can directly apply the patch by running, in the top level of your repository:

`curl -s https://mooseframework.inl.gov/docs/PRs/21753/clang_format/style.patch | git apply -v`  

Alternatively, with your repository up to date and in the top level of your repository:

`git clang-format d672f863d19813cf7021e6e1a044d8e445e9a340`

2022-08-02 16:12 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/1126245/) on dea6375 wanted to post the following:

Your code requires style changes.  

A patch was auto generated and copied [here](https://mooseframework.inl.gov/docs/PRs/21753/clang_format/style.patch)  
You can directly apply the patch by running, in the top level of your repository:

`curl -s https://mooseframework.inl.gov/docs/PRs/21753/clang_format/style.patch | git apply -v`  

Alternatively, with your repository up to date and in the top level of your repository:

`git clang-format d672f863d19813cf7021e6e1a044d8e445e9a340`

2022-08-02 16:12 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/1126245/) on dea6375 wanted to post the following:

Your code requires style changes.  

A patch was auto generated and copied [here](https://mooseframework.inl.gov/docs/PRs/21753/clang_format/style.patch)  
You can directly apply the patch by running, in the top level of your repository:

`curl -s https://mooseframework.inl.gov/docs/PRs/21753/clang_format/style.patch | git apply -v`  

Alternatively, with your repository up to date and in the top level of your repository:

`git clang-format d672f863d19813cf7021e6e1a044d8e445e9a340`

2022-08-02 16:13 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/1126245/) on dea6375 wanted to post the following:

Your code requires style changes.  

A patch was auto generated and copied [here](https://mooseframework.inl.gov/docs/PRs/21753/clang_format/style.patch)  
You can directly apply the patch by running, in the top level of your repository:

`curl -s https://mooseframework.inl.gov/docs/PRs/21753/clang_format/style.patch | git apply -v`  

Alternatively, with your repository up to date and in the top level of your repository:

`git clang-format d672f863d19813cf7021e6e1a044d8e445e9a340`

2022-08-02 16:13 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/1126245/) on dea6375 wanted to post the following:

Your code requires style changes.  

A patch was auto generated and copied [here](https://mooseframework.inl.gov/docs/PRs/21753/clang_format/style.patch)  
You can directly apply the patch by running, in the top level of your repository:

`curl -s https://mooseframework.inl.gov/docs/PRs/21753/clang_format/style.patch | git apply -v`  

Alternatively, with your repository up to date and in the top level of your repository:

`git clang-format d672f863d19813cf7021e6e1a044d8e445e9a340`

2022-08-02 16:14 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/1126245/) on dea6375 wanted to post the following:

Your code requires style changes.  

A patch was auto generated and copied [here](https://mooseframework.inl.gov/docs/PRs/21753/clang_format/style.patch)  
You can directly apply the patch by running, in the top level of your repository:

`curl -s https://mooseframework.inl.gov/docs/PRs/21753/clang_format/style.patch | git apply -v`  

Alternatively, with your repository up to date and in the top level of your repository:

`git clang-format d672f863d19813cf7021e6e1a044d8e445e9a340`

2022-08-02 16:15 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/1126245/) on dea6375 wanted to post the following:

Your code requires style changes.  

A patch was auto generated and copied [here](https://mooseframework.inl.gov/docs/PRs/21753/clang_format/style.patch)  
You can directly apply the patch by running, in the top level of your repository:

`curl -s https://mooseframework.inl.gov/docs/PRs/21753/clang_format/style.patch | git apply -v`  

Alternatively, with your repository up to date and in the top level of your repository:

`git clang-format d672f863d19813cf7021e6e1a044d8e445e9a340`

2022-08-02 16:16 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/1126245/) on dea6375 wanted to post the following:

Your code requires style changes.  

A patch was auto generated and copied [here](https://mooseframework.inl.gov/docs/PRs/21753/clang_format/style.patch)  
You can directly apply the patch by running, in the top level of your repository:

`curl -s https://mooseframework.inl.gov/docs/PRs/21753/clang_format/style.patch | git apply -v`  

Alternatively, with your repository up to date and in the top level of your repository:

`git clang-format d672f863d19813cf7021e6e1a044d8e445e9a340`

2022-08-02 16:16 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/1126245/) on dea6375 wanted to post the following:

Your code requires style changes.  

A patch was auto generated and copied [here](https://mooseframework.inl.gov/docs/PRs/21753/clang_format/style.patch)  
You can directly apply the patch by running, in the top level of your repository:

`curl -s https://mooseframework.inl.gov/docs/PRs/21753/clang_format/style.patch | git apply -v`  

Alternatively, with your repository up to date and in the top level of your repository:

`git clang-format d672f863d19813cf7021e6e1a044d8e445e9a340`

2022-08-02 16:17 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/1126245/) on dea6375 wanted to post the following:

Your code requires style changes.  

A patch was auto generated and copied [here](https://mooseframework.inl.gov/docs/PRs/21753/clang_format/style.patch)  
You can directly apply the patch by running, in the top level of your repository:

`curl -s https://mooseframework.inl.gov/docs/PRs/21753/clang_format/style.patch | git apply -v`  

Alternatively, with your repository up to date and in the top level of your repository:

`git clang-format d672f863d19813cf7021e6e1a044d8e445e9a340`

2022-08-02 16:18 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/1126245/) on dea6375 wanted to post the following:

Your code requires style changes.  

A patch was auto generated and copied [here](https://mooseframework.inl.gov/docs/PRs/21753/clang_format/style.patch)  
You can directly apply the patch by running, in the top level of your repository:

`curl -s https://mooseframework.inl.gov/docs/PRs/21753/clang_format/style.patch | git apply -v`  

Alternatively, with your repository up to date and in the top level of your repository:

`git clang-format d672f863d19813cf7021e6e1a044d8e445e9a340`

2022-08-02 16:18 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/1126245/) on dea6375 wanted to post the following:

Your code requires style changes.  

A patch was auto generated and copied [here](https://mooseframework.inl.gov/docs/PRs/21753/clang_format/style.patch)  
You can directly apply the patch by running, in the top level of your repository:

`curl -s https://mooseframework.inl.gov/docs/PRs/21753/clang_format/style.patch | git apply -v`  

Alternatively, with your repository up to date and in the top level of your repository:

`git clang-format d672f863d19813cf7021e6e1a044d8e445e9a340`

2022-08-02 16:19 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/1126245/) on dea6375 wanted to post the following:

Your code requires style changes.  

A patch was auto generated and copied [here](https://mooseframework.inl.gov/docs/PRs/21753/clang_format/style.patch)  
You can directly apply the patch by running, in the top level of your repository:

`curl -s https://mooseframework.inl.gov/docs/PRs/21753/clang_format/style.patch | git apply -v`  

Alternatively, with your repository up to date and in the top level of your repository:

`git clang-format d672f863d19813cf7021e6e1a044d8e445e9a340`

2022-08-02 16:19 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/1126245/) on dea6375 wanted to post the following:

Your code requires style changes.  

A patch was auto generated and copied [here](https://mooseframework.inl.gov/docs/PRs/21753/clang_format/style.patch)  
You can directly apply the patch by running, in the top level of your repository:

`curl -s https://mooseframework.inl.gov/docs/PRs/21753/clang_format/style.patch | git apply -v`  

Alternatively, with your repository up to date and in the top level of your repository:

`git clang-format d672f863d19813cf7021e6e1a044d8e445e9a340`

2022-08-02 16:20 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/1126245/) on dea6375 wanted to post the following:

Your code requires style changes.  

A patch was auto generated and copied [here](https://mooseframework.inl.gov/docs/PRs/21753/clang_format/style.patch)  
You can directly apply the patch by running, in the top level of your repository:

`curl -s https://mooseframework.inl.gov/docs/PRs/21753/clang_format/style.patch | git apply -v`  

Alternatively, with your repository up to date and in the top level of your repository:

`git clang-format d672f863d19813cf7021e6e1a044d8e445e9a340`

2022-08-02 16:21 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/1126245/) on dea6375 wanted to post the following:

Your code requires style changes.  

A patch was auto generated and copied [here](https://mooseframework.inl.gov/docs/PRs/21753/clang_format/style.patch)  
You can directly apply the patch by running, in the top level of your repository:

`curl -s https://mooseframework.inl.gov/docs/PRs/21753/clang_format/style.patch | git apply -v`  

Alternatively, with your repository up to date and in the top level of your repository:

`git clang-format d672f863d19813cf7021e6e1a044d8e445e9a340`

2022-08-02 16:21 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/1126245/) on dea6375 wanted to post the following:

Your code requires style changes.  

A patch was auto generated and copied [here](https://mooseframework.inl.gov/docs/PRs/21753/clang_format/style.patch)  
You can directly apply the patch by running, in the top level of your repository:

`curl -s https://mooseframework.inl.gov/docs/PRs/21753/clang_format/style.patch | git apply -v`  

Alternatively, with your repository up to date and in the top level of your repository:

`git clang-format d672f863d19813cf7021e6e1a044d8e445e9a340`

2022-08-02 16:22 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/1126245/) on dea6375 wanted to post the following:

Your code requires style changes.  

A patch was auto generated and copied [here](https://mooseframework.inl.gov/docs/PRs/21753/clang_format/style.patch)  
You can directly apply the patch by running, in the top level of your repository:

`curl -s https://mooseframework.inl.gov/docs/PRs/21753/clang_format/style.patch | git apply -v`  

Alternatively, with your repository up to date and in the top level of your repository:

`git clang-format d672f863d19813cf7021e6e1a044d8e445e9a340`

2022-08-02 16:22 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/1126245/) on dea6375 wanted to post the following:

Your code requires style changes.  

A patch was auto generated and copied [here](https://mooseframework.inl.gov/docs/PRs/21753/clang_format/style.patch)  
You can directly apply the patch by running, in the top level of your repository:

`curl -s https://mooseframework.inl.gov/docs/PRs/21753/clang_format/style.patch | git apply -v`  

Alternatively, with your repository up to date and in the top level of your repository:

`git clang-format d672f863d19813cf7021e6e1a044d8e445e9a340`

2022-08-02 16:23 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/1126245/) on dea6375 wanted to post the following:

Your code requires style changes.  

A patch was auto generated and copied [here](https://mooseframework.inl.gov/docs/PRs/21753/clang_format/style.patch)  
You can directly apply the patch by running, in the top level of your repository:

`curl -s https://mooseframework.inl.gov/docs/PRs/21753/clang_format/style.patch | git apply -v`  

Alternatively, with your repository up to date and in the top level of your repository:

`git clang-format d672f863d19813cf7021e6e1a044d8e445e9a340`

2022-08-03 01:14 UTC, moosebuild commented
Job [Documentation](https://civet.inl.gov/job/1126281/) on cbe1c52 wanted to post the following:

View the site [here](https://mooseframework.inl.gov/docs/PRs/21753/site)

This comment will be updated on new commits.

2022-08-03 02:12 UTC, dschwen commented
Why is there a new PR rather than using #21741?

2022-08-03 21:10 UTC, Linwitness commented
> 

Hi Daniel, the pushes of old PR are already so complex because I forget to rebase before one push. The new one with clean push can make my life easier. sorry for confusing you.

2022-08-05 18:46 UTC, dschwen requested changes

2022-08-05 18:46 UTC, dschwen commented on modules/phase_field/include/auxkernels/SolutionAuxMisorientationBoundary.h
> +  // The grain boundary type to calculate bnds parameter
```suggestion
  /// The grain boundary type to calculate bnds parameter
```

required for doxygen

2022-08-05 18:46 UTC, dschwen commented on modules/phase_field/include/auxkernels/SolutionAuxMisorientationBoundary.h
> + * solution read.
please update

2022-08-05 18:46 UTC, dschwen commented on modules/phase_field/include/materials/ComputeGBMisorientationType.h
> +  // Function to read the Misorientation angle form a file
make all of those `///`

2022-08-05 18:46 UTC, dschwen commented on modules/phase_field/include/materials/ComputeGBMisorientationType.h
> +  // Function to output specific line number in Misorientation angle file
this function does not output anything. better write "obtain line number for a given grain pair". 

Also please use parameter names in the header for self documentation purposes.

```
unsigned int getLineNum(unsigned int grain_i, unsigned int grain_j)
```

2022-08-05 18:46 UTC, dschwen commented on modules/phase_field/src/materials/ComputeGBMisorientationType.C
> +
```suggestion
```

2022-08-05 18:46 UTC, dschwen commented on modules/phase_field/src/materials/ComputeGBMisorientationType.C
> +      break;
better set `_gb_type[_qp]` to something well defined, otherwise it will keep the value from the previous QP/element.

2022-08-05 18:46 UTC, dschwen commented on modules/phase_field/src/materials/ComputeGBMisorientationType.C
> +    {
braces are not required

2022-08-05 18:46 UTC, dschwen commented on modules/phase_field/src/materials/ComputeGBMisorientationType.C
> +    _misorientation_angles.push_back(a);
You should not implement a custom file reader. And why is there only one angle? Is this only for 2D problems? Is that even an "Euler angle" in that case? Either way, bet use the DelimitedFileReader class that we already have in MOOSE

2022-08-05 18:46 UTC, dschwen commented on modules/phase_field/src/materials/ComputeGBMisorientationType.C
> +    return grain_j + (grain_i - 1) * grain_i / 2;
This does not look right.

2022-08-05 18:46 UTC, dschwen commented on modules/phase_field/src/materials/ComputeGBMisorientationType.C
> +    return grain_j + (grain_i - 1) * grain_i / 2;
I suggest one of two things:

- drop this entirely. The misorientation angles of all pairs of grains are not fully independent parameters. You can calculate the misorientations from the individual grain orientations.
- or, (if you want to stick with this potentially inconsistent formulation), use a three column csv file with grain_i,grain_j,angle and put the angles into a map indexed by grain ID pairs.

2022-08-05 18:49 UTC, dschwen commented
> As the following figure shown, LAGB is assign "1", HAGB is assign "2", and the Triple junction is assigned an interpolated value.

What are wee looking at on this image? I don't see any Boundaries being colored, it rather looks like entire grains. Also you mention 

> GB type based on the misorientation from EBSD data

but it is not in fact contained in the EBSD data file (which does have space for grain rotations).

I'm confused about this PR.

2022-08-08 20:43 UTC, Linwitness commented
Hi Daniel, the figure is for GB type, the white one is the LAGB, the red one is the HAGB. Maybe the following three figures can make it clear.
![poly_simu](https://user-images.githubusercontent.com/58009812/183220389-1db99ab7-b680-4c46-ba1d-3b44f3b9c8d9.png)
The phi1 in Euler angle of grain orientations in the polycrystal is shown in (a). And the GB type determined by misorientation angle is shown in (b). The GB type is a area to note the GB property, so the area will larger than GB to make sure the calculation for all points in GBs can use the GB type property.

Beside, I added the function to calculate the misorientation angle in the feature directly. (in previous, we read misorientation angles outputted from a python script) Let me know if you have more suggestions.

2022-08-09 01:31 UTC, moosebuild commented
Job [Coverage](https://civet.inl.gov/job/1135713/) on 7b33cc3 wanted to post the following:


## Framework coverage

<table>
  <thead>
    <tr>
      <th></th>
      <th>47ea1d</th>
      <th colspan=4>#21753 7b33cc</th>
    </tr>
    <tr>
      <th></th>
      <th>Total</th>
      <th>Total</th>
      <th>+/-</th>
      <th>New</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><b>Rate</b></td>
      <td>83.99%</td>
      <td>83.99%</td>
      <td>-0.00%</td>
      <td>-</td>
    </tr>
    <tr>
      <td><b>Hits</b></td>
      <td>78592</td>
      <td>78591</td>
      <td>-1</td>
      <td>0</td>
    </tr>
    <tr>
      <td><b>Misses</b></td>
      <td>14982</td>
      <td>14983</td>
      <td>+1</td>
      <td>0</td>
    </tr>
  </tbody>
</table>

[Diff coverage report](https://mooseframework.inl.gov/docs/PRs/21753/coverage_diff/framework)

[Full coverage report](https://mooseframework.inl.gov/docs/PRs/21753/coverage/framework)


## Modules coverage

### Phase field

<table>
  <thead>
    <tr>
      <th></th>
      <th>47ea1d</th>
      <th colspan=4>#21753 7b33cc</th>
    </tr>
    <tr>
      <th></th>
      <th>Total</th>
      <th>Total</th>
      <th>+/-</th>
      <th>New</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><b>Rate</b></td>
      <td>89.76%</td>
      <td>89.84%</td>
      <td>+0.08%</td>
      <td>96.47%</td>
    </tr>
    <tr>
      <td><b>Hits</b></td>
      <td>12284</td>
      <td>12449</td>
      <td>+165</td>
      <td>164</td>
    </tr>
    <tr>
      <td><b>Misses</b></td>
      <td>1402</td>
      <td>1408</td>
      <td>+6</td>
      <td>6</td>
    </tr>
  </tbody>
</table>

[Diff coverage report](https://mooseframework.inl.gov/docs/PRs/21753/coverage_diff/phase_field)

[Full coverage report](https://mooseframework.inl.gov/docs/PRs/21753/coverage/phase_field)

## Full coverage reports

<details>
<summary>Reports</summary>

- [`framework`](https://mooseframework.inl.gov/docs/PRs/21753/coverage/framework)
- [`chemical_reactions`](https://mooseframework.inl.gov/docs/PRs/21753/coverage/chemical_reactions)
- [`combined`](https://mooseframework.inl.gov/docs/PRs/21753/coverage/combined)
- [`contact`](https://mooseframework.inl.gov/docs/PRs/21753/coverage/contact)
- [`electromagnetics`](https://mooseframework.inl.gov/docs/PRs/21753/coverage/electromagnetics)
- [`external_petsc_solver`](https://mooseframework.inl.gov/docs/PRs/21753/coverage/external_petsc_solver)
- [`fluid_properties`](https://mooseframework.inl.gov/docs/PRs/21753/coverage/fluid_properties)
- [`fsi`](https://mooseframework.inl.gov/docs/PRs/21753/coverage/fsi)
- [`functional_expansion_tools`](https://mooseframework.inl.gov/docs/PRs/21753/coverage/functional_expansion_tools)
- [`geochemistry`](https://mooseframework.inl.gov/docs/PRs/21753/coverage/geochemistry)
- [`heat_conduction`](https://mooseframework.inl.gov/docs/PRs/21753/coverage/heat_conduction)
- [`level_set`](https://mooseframework.inl.gov/docs/PRs/21753/coverage/level_set)
- [`misc`](https://mooseframework.inl.gov/docs/PRs/21753/coverage/misc)
- [`navier_stokes`](https://mooseframework.inl.gov/docs/PRs/21753/coverage/navier_stokes)
- [`peridynamics`](https://mooseframework.inl.gov/docs/PRs/21753/coverage/peridynamics)
- [`phase_field`](https://mooseframework.inl.gov/docs/PRs/21753/coverage/phase_field)
- [`porous_flow`](https://mooseframework.inl.gov/docs/PRs/21753/coverage/porous_flow)
- [`ray_tracing`](https://mooseframework.inl.gov/docs/PRs/21753/coverage/ray_tracing)
- [`rdg`](https://mooseframework.inl.gov/docs/PRs/21753/coverage/rdg)
- [`reactor`](https://mooseframework.inl.gov/docs/PRs/21753/coverage/reactor)
- [`richards`](https://mooseframework.inl.gov/docs/PRs/21753/coverage/richards)
- [`stochastic_tools`](https://mooseframework.inl.gov/docs/PRs/21753/coverage/stochastic_tools)
- [`tensor_mechanics`](https://mooseframework.inl.gov/docs/PRs/21753/coverage/tensor_mechanics)
- [`thermal_hydraulics`](https://mooseframework.inl.gov/docs/PRs/21753/coverage/thermal_hydraulics)
- [`xfem`](https://mooseframework.inl.gov/docs/PRs/21753/coverage/xfem)

</details>



This comment will be updated on new commits.

2022-08-09 01:35 UTC, dschwen commented
You need to get rid of the Merge commits in this PR. One way is by hard resetting to devel and the using `git cherry-pick SHA` each of your commits.

2022-08-09 01:36 UTC, dschwen commented on modules/phase_field/include/materials/ComputeGBMisorientationType.h
> +  double ** sym_quat;
let's use a proper C++ container here

2022-08-09 01:38 UTC, dschwen commented on modules/phase_field/src/materials/ComputeGBMisorientationType.C
> +ComputeGBMisorientationType::getQuaternionProduct(const double qi[4],
You should use `Eigen::Quaternion<Real>` instead

2022-08-09 01:38 UTC, dschwen commented on modules/phase_field/src/materials/ComputeGBMisorientationType.C
> +        misom = fabs(miso0);
```suggestion
        misom = std::abs(miso0);
```

2022-08-09 01:39 UTC, dschwen commented on modules/phase_field/src/materials/ComputeGBMisorientationType.C
> +  if (miso0 > MY_PI)
Let's use everyone's pi (`libMesh::pi`) rather than _your_ pi.

2022-08-09 01:40 UTC, dschwen commented on modules/phase_field/src/materials/ComputeGBMisorientationType.C
> +  miso0 = 2 * acos(qmin[0]);
Please always properly specify the namespace. I.e. 
```suggestion
  miso0 = 2 * std::acos(qmin[0]);
```

2022-08-09 01:41 UTC, dschwen commented on modules/phase_field/src/materials/ComputeGBMisorientationType.C
> +  if (miso0 > MY_PI)
Also `acos` should never return a value > pi!

2022-08-09 01:44 UTC, dschwen commented on modules/phase_field/src/materials/ComputeGBMisorientationType.C
> +ComputeGBMisorientationType::eulerOrientationToQuaternion(int grain_id)
We already have code to do this in the `EulerAngles`.. which you should be using to hold Euler angles.

2022-08-09 01:46 UTC, dschwen commented on modules/phase_field/src/materials/ComputeGBMisorientationType.C
> +    eulerOrientationToQuaternion(grain_id);
```suggestion
    quat_angle[grain_id] = euler_angle[grain_id].toQuaternion()
```

and change the type of `quat_angle` accordingly.

2022-08-09 01:47 UTC, dschwen commented on modules/phase_field/include/materials/ComputeGBMisorientationType.h
> +  std::vector<std::vector<double>> quat_angle;
```suggestion
  std::vector<Eigen::Quaternion<Real>> _quat_angle;
```

remember the leasing underscore for member variable names.

2022-08-09 01:47 UTC, dschwen commented on modules/phase_field/include/materials/ComputeGBMisorientationType.h
> +  std::vector<std::vector<double>> euler_angle;
```suggestion
  std::vector<EulerAngles> _euler_angle;
```

2022-08-09 01:48 UTC, dschwen commented on modules/phase_field/src/materials/ComputeGBMisorientationType.C
> +  std::vector<Real> gb_op_pairs;
please try to avoid local `std::vector` variables in per QP functions

2022-08-09 01:50 UTC, dschwen commented on modules/phase_field/src/materials/ComputeGBMisorientationType.C
> +  }
looks iffy. use an `index_range(_vals)` instead,

2022-08-09 13:27 UTC, moosebuild commented
Job [End user mac](https://civet.inl.gov/job/1135708/) on 7b33cc3 : invalidated by @milljm

Old packages were pulled by mistake

2022-08-24 03:43 UTC, simopier commented
@dschwen @Linwitness , what is preventing this PR from being merged?

2022-08-24 03:45 UTC, dschwen commented
I activated all jobs and will look it over once more tomorrow.

2022-08-24 13:43 UTC, loganharbour commented
We need to force recreate the event on this PR. It's using recipes that are two weeks old. Too old.

2022-08-24 15:11 UTC, dschwen reviewed
I apologize for the picky review, but if you have time to make/accept the changes and also `hit format` all `*.i` and `tests` files so that they uniformely have the new syntax that'd be great.

2022-08-24 15:11 UTC, dschwen commented on modules/phase_field/doc/content/source/materials/ComputeGBMisorientationType.md
> +ComputeGBMisorientationType uses an EBSDReader object and a Grain Tracker object to calculate the grain boundary (GB) type based on the misorientation angle. There are two kind of GB type: Low Angle
```suggestion
ComputeGBMisorientationType uses an EBSDReader object and a Grain Tracker object to calculate the grain boundary (GB) type based on the misorientation angle. There are two kind of GB type: Low Angle GB (LAGB) and High Angle GB (HAGB). When the misorientation angle is smaller than the critical angle, 15˚, the GB type is defined as LAGB, and it is defined as HAGB for higher misorientation angles. The critical angle can be modified with the [!param](/AuxKernels/SolutionAuxMisorientationBoundary/angle_threshold) parameter. 
```

2022-08-24 15:11 UTC, dschwen commented on modules/phase_field/include/auxkernels/SolutionAuxMisorientationBoundary.h
> + * AuxKernel for reading a solution from file and visualize the location of
```suggestion
 * AuxKernel for reading a solution from file and visualizing the location of
```

2022-08-24 15:11 UTC, dschwen commented on modules/phase_field/include/materials/ComputeGBMisorientationType.h
> +                            Eigen::Quaternion<Real> & q);
why is this needed?

2022-08-24 15:11 UTC, dschwen commented on modules/phase_field/src/materials/ComputeGBMisorientationType.C
> +ComputeGBMisorientationType::getQuaternionProduct(const Eigen::Quaternion<Real> qi,
is the overloaded `*` operator not suitable here?

2022-08-24 15:11 UTC, dschwen commented on modules/phase_field/src/materials/ComputeGBMisorientationType.C
> +  double miso0, misom = 2 * libMesh::pi;
```suggestion
  Real miso0, misom = 2.0 * libMesh::pi;
```

2022-08-24 15:11 UTC, dschwen commented on modules/phase_field/src/materials/ComputeGBMisorientationType.C
> +  int grain_num = _ebsd_reader.getGrainNum();
```suggestion
  const auto grain_num = _ebsd_reader.getGrainNum();
```

2022-08-24 15:11 UTC, dschwen commented on modules/phase_field/src/materials/ComputeGBMisorientationType.C
> +  for (int i = 0; i < grain_num; i++)
```suggestion
  for (const auto i: make_range(grain_num))
```

2022-08-24 15:11 UTC, dschwen commented on modules/phase_field/src/materials/ComputeGBMisorientationType.C
> +  for (int j = 1; j < grain_num; j++)
```suggestion
  for (const auto j: make_range(1, grain_num))
```

2022-08-24 15:11 UTC, dschwen commented on modules/phase_field/src/materials/ComputeGBMisorientationType.C
> +    for (int i = 0; i < j; i++)
```suggestion
    for (const auto i: make_range(j))
```

2022-08-24 15:11 UTC, dschwen commented on modules/phase_field/src/materials/ComputeGBMisorientationType.C
> +      double theta = getMisorientationFromQuaternion(_quat_angle[i], _quat_angle[j]);
```suggestion
      Real theta = getMisorientationFromQuaternion(_quat_angle[i], _quat_angle[j]);
```

2022-08-24 15:11 UTC, dschwen commented on modules/phase_field/test/tests/GBType/GB_Type_Phase1.i
> +  file_base = 'Phase1_output'
any reason to use file base here? I find it rather confusing as it removes the clear relation between input and output file names.

2022-08-25 15:18 UTC, Linwitness commented
Morning, I found Logan mentioned, "we need to force recreate the event on this PR". Does that mean I need to rebase it or do other necessary operations before I make some changes?

2022-08-25 15:22 UTC, loganharbour commented
Just make the changes that Daniel mentioned above; when you push those changes it'll trigger new tests.

2022-08-25 21:45 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/1155663/) on f03e01c wanted to post the following:

Your code requires style changes.  

A patch was auto generated and copied [here](https://mooseframework.inl.gov/docs/PRs/21753/clang_format/style.patch)  
You can directly apply the patch by running, in the top level of your repository:

`curl -s https://mooseframework.inl.gov/docs/PRs/21753/clang_format/style.patch | git apply -v`  

Alternatively, with your repository up to date and in the top level of your repository:

`git clang-format de5880a5b3225bb52505bf07c3e4b5be7542c5af`

2022-08-30 17:47 UTC, simopier commented
@Linwitness, here is the error that prevented the documentation to be built:

```
/data/civet2/build/moose/modules/phase_field/doc/content/source/materials/ComputeGBMisorientationType.md:1
 ┌─────────────────────────────────────────────────────────────────────────────────────────────────┐
1│[!param](/AuxKernels/SolutionAuxMisorientationBoundary/angle_threshold)                          │
 └─────────────────────────────────────────────────────────────────────────────────────────────────┘
(...)
MooseDocs.common.exceptions.MooseDocsException: Unable to locate the parameter '/AuxKernels/SolutionAuxMisorientationBoundary/angle_threshold', did you mean:
    /AuxKernels/SolutionAuxMisorientationBoundary/gb_type_order
    /AuxKernels/SolutionAuxMisorientationBoundary/scale_factor
    /AuxKernels/SolutionAuxMisorientationBoundary/add_factor
    /AuxKernels/SolutionAuxMisorientationBoundary/execute_on
    /AuxKernels/SolutionAuxMisorientationBoundary/from_variable
```

Could you fix that up and re-push?

Thank you!

2022-09-02 00:05 UTC, dschwen approved these changes

2022-09-02 00:05 UTC, merged