HIT format multiline strings
idaholab/moose pull request #21758
Opened 2022-08-02 20:42 UTC by dschwen

Refs #15797

This PR changes `hit format` to better deal with multiline strings. The way HIT is designed it is pretty expensive (and hard) to get token column info (i.e. the column the unformatted string started on). So for now I'm using a heuristic. If the multiline string has a space as the first character we'll format the string right aligned, otherwise it will be left aligned.

```
[Block]
[./tabular]
  type = PiecewiseLinear
  xy_data = '300 11.0
             350 12.0
             400 13.0
             500 14.0
             600 15.0
             700 16.0
             800 17.0
             900 18.0
             1000 19.0
             1100 20.0
             1200 21.0
             1300 22.0'
[../]
[]
```

gets formatted as

```
[Block]
  [tabular]
    type = PiecewiseLinear
    xy_data = '300 11.0
               350 12.0
               400 13.0
               500 14.0
               600 15.0
               700 16.0
               800 17.0
               900 18.0
               1000 19.0
               1100 20.0
               1200 21.0
               1300 22.0'
  []
[]
```

and

```
[Block]
[./tabular]
  type = PiecewiseLinear
  xy_data = ' 300 11.0
              350 12.0
              400 13.0
              500 14.0
              600 15.0
              700 16.0
              800 17.0
              900 18.0
             1000 19.0
             1100 20.0
             1200 21.0
             1300 22.0'
[../]
[]
```

gets formatted as

```
[Block]
  [tabular]
    type = PiecewiseLinear
    xy_data = ' 300 11.0
                350 12.0
                400 13.0
                500 14.0
                600 15.0
                700 16.0
                800 17.0
                900 18.0
               1000 19.0
               1100 20.0
               1200 21.0
               1300 22.0'
  []
[]
```

2022-08-02 20:44 UTC, dschwen commented
In case it's not clear, the heuristic is needed to adjust the indentation of all following lines of the string if the indentation of the first line changes. Ideally we'd apply the delta in indentation from the first line, but not knowing the original indentation we cannot easily compute that.

Also, internal string indentation is always using single white-spaces.

2022-08-02 21:23 UTC, loganharbour commented
I like this.

2022-08-02 21:50 UTC, moosebuild commented
Job [Documentation](https://civet.inl.gov/job/1126936/) on d4f1882 wanted to post the following:

View the site [here](https://mooseframework.inl.gov/docs/PRs/21758/site)

This comment will be updated on new commits.

2022-08-02 22:55 UTC, dschwen commented
While this solves one problem it is not a comprehensive fix. As @cticenhour pointed out, carefully aligned long petsc option strings and ling function expressions would still get mangled. 

One option could be to differentiate string formatting behavior based on the quote type used.

- `'` no string reflow at all
- `"` reflow string using above heuristics / use existing string splitting for single line strings.

I'd also have to check how this would work with multiple hit format round trips, which we _absolutely_ want to be stable!

2022-08-02 23:10 UTC, moosebuild commented
Job [Coverage](https://civet.inl.gov/job/1126945/) on d4f1882 wanted to post the following:


## Framework coverage

<table>
  <thead>
    <tr>
      <th></th>
      <th>d672f8</th>
      <th colspan=4>#21758 d4f188</th>
    </tr>
    <tr>
      <th></th>
      <th>Total</th>
      <th>Total</th>
      <th>+/-</th>
      <th>New</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><b>Rate</b></td>
      <td>83.86%</td>
      <td>83.86%</td>
      <td>-0.00%</td>
      <td>-</td>
    </tr>
    <tr>
      <td><b>Hits</b></td>
      <td>78354</td>
      <td>78351</td>
      <td>-3</td>
      <td>0</td>
    </tr>
    <tr>
      <td><b>Misses</b></td>
      <td>15081</td>
      <td>15084</td>
      <td>+3</td>
      <td>0</td>
    </tr>
  </tbody>
</table>

[Diff coverage report](https://mooseframework.inl.gov/docs/PRs/21758/coverage_diff/framework)

[Full coverage report](https://mooseframework.inl.gov/docs/PRs/21758/coverage/framework)


## Modules coverage

Coverage did not change

## Full coverage reports

<details>
<summary>Reports</summary>

- [`framework`](https://mooseframework.inl.gov/docs/PRs/21758/coverage/framework)
- [`chemical_reactions`](https://mooseframework.inl.gov/docs/PRs/21758/coverage/chemical_reactions)
- [`combined`](https://mooseframework.inl.gov/docs/PRs/21758/coverage/combined)
- [`contact`](https://mooseframework.inl.gov/docs/PRs/21758/coverage/contact)
- [`electromagnetics`](https://mooseframework.inl.gov/docs/PRs/21758/coverage/electromagnetics)
- [`external_petsc_solver`](https://mooseframework.inl.gov/docs/PRs/21758/coverage/external_petsc_solver)
- [`fluid_properties`](https://mooseframework.inl.gov/docs/PRs/21758/coverage/fluid_properties)
- [`fsi`](https://mooseframework.inl.gov/docs/PRs/21758/coverage/fsi)
- [`functional_expansion_tools`](https://mooseframework.inl.gov/docs/PRs/21758/coverage/functional_expansion_tools)
- [`geochemistry`](https://mooseframework.inl.gov/docs/PRs/21758/coverage/geochemistry)
- [`heat_conduction`](https://mooseframework.inl.gov/docs/PRs/21758/coverage/heat_conduction)
- [`level_set`](https://mooseframework.inl.gov/docs/PRs/21758/coverage/level_set)
- [`misc`](https://mooseframework.inl.gov/docs/PRs/21758/coverage/misc)
- [`navier_stokes`](https://mooseframework.inl.gov/docs/PRs/21758/coverage/navier_stokes)
- [`peridynamics`](https://mooseframework.inl.gov/docs/PRs/21758/coverage/peridynamics)
- [`phase_field`](https://mooseframework.inl.gov/docs/PRs/21758/coverage/phase_field)
- [`porous_flow`](https://mooseframework.inl.gov/docs/PRs/21758/coverage/porous_flow)
- [`ray_tracing`](https://mooseframework.inl.gov/docs/PRs/21758/coverage/ray_tracing)
- [`rdg`](https://mooseframework.inl.gov/docs/PRs/21758/coverage/rdg)
- [`reactor`](https://mooseframework.inl.gov/docs/PRs/21758/coverage/reactor)
- [`richards`](https://mooseframework.inl.gov/docs/PRs/21758/coverage/richards)
- [`stochastic_tools`](https://mooseframework.inl.gov/docs/PRs/21758/coverage/stochastic_tools)
- [`tensor_mechanics`](https://mooseframework.inl.gov/docs/PRs/21758/coverage/tensor_mechanics)
- [`thermal_hydraulics`](https://mooseframework.inl.gov/docs/PRs/21758/coverage/thermal_hydraulics)
- [`xfem`](https://mooseframework.inl.gov/docs/PRs/21758/coverage/xfem)

</details>



This comment will be updated on new commits.

2022-08-03 15:07 UTC, dschwen commented
Ok, I updated the formatting example above. The `'..'` strings do not get reformatted now, while the `".."` strings get the heuristic treatment.

2022-08-03 17:36 UTC, cticenhour commented on framework/contrib/hit/lex.h
> -
Have you checked Peacock functionality with this change?

2022-08-03 18:56 UTC, dschwen commented
I'd like to get rid of `hit::tokenize` because I'd like to make tokens use string views referencing the original input text, rather than construct a gazillion strings on the heap. That means the original input text needs to stick around, and I'd like the Lexer to be the place for it (the Lexer already stores a copy of the input text).

However that means the Lexer needs to stick around for the Tokens to remain valid. Within the parser we can simply hang onto the Lexer in the Root Node.

2022-08-04 18:32 UTC, dschwen commented
Ok, rewind. I profiled HIT (which I should have done as step number 1), and found a big hotspot. The entire input file text was returned _by copy_ bazillions of times during lexing. A two line change made the biggest difference. A few more return as reference changes made an additional (smaller impact).

Over all this results in an over 60x speedup when parsing a half million line input file.

```
Current HIT parser

./hit profile -n 1 big512.i 
Reading input: 75 ms
Parsing input: 74403 ms

with const std::string & Lex::input()

./hit profile -n 10 big512.i 
Reading input: 74 ms
Parsing input: 1308 ms

...and with const Token &

./hit profile -n 10  big512.i
Reading input: 76 ms
Parsing input: 1207 ms
```

2022-08-04 18:43 UTC, dschwen commented
For a million line input the speedup becomes over 110x. The new version has pretty much linear scaling, while the old version does not.

2022-08-04 19:55 UTC, permcody commented
Nice!

2022-08-04 20:43 UTC, dschwen commented
Ok, now I added column position to the token objects. This allows me to do relative indentation changes (I already knew the new indentation while rendering the formatted tree, but I was missing the indentation in the original input). 

```
[Block]
[./increase]
type = TestAlignment
xy_data = "0 0.0
           1 1.0
           10 3.0
           100 2.0
           1000 4.0"
[../]
[./increase2]
type = TestAlignment
xy_data = " 0 0.0
            1 11.0
           10 33.0
          100 22.30
         1000 42.210"
[../]
[./decrease]
            type = TestAlignment
            xy_data = "100 1.0
                       200 12.0
                       300 313.0
                       400 4514.0
                       500 45615.0"
[../]
[./decrease2]
             type = TestAlignment
             xy_data = "100 1.0
  200 12.0
                        500 45615.0"
[../]
[./no_reflow]
type = TestReflow
long_vector = '10 1 20 2 30 3 40 4 50 5 60 6 70 7 80 8 90 9 110 11 120 12 130 13 140 14 150 15 160 16 170 17 180 18 190 19 210 21 220 22 230 23 240 24 250 25 260 26 270 27 280 28 290 29'
[../]
[./reflow]
type = TestReflow
long_vector = "10 1 20 2 30 3 40 4 50 5 60 6 70 7 80 8 90 9 110 11 120 12 130 13 140 14 150 15 160 16 170 17 180 18 190 19 210 21 220 22 230 23 240 24 250 25 260 26 270 27 280 28 290 29"
[../][]
```

gets formatted as

```
[Block]
  [increase]
    type = TestAlignment
    xy_data = "0 0.0
               1 1.0
               10 3.0
               100 2.0
               1000 4.0"
  []
  [increase2]
    type = TestAlignment
    xy_data = " 0 0.0
                1 11.0
               10 33.0
              100 22.30
             1000 42.210"
  []
  [decrease]
    type = TestAlignment
    xy_data = "100 1.0
               200 12.0
               300 313.0
               400 4514.0
               500 45615.0"
  []
  [decrease2]
    type = TestAlignment
    xy_data = "100 1.0
200 12.0
               500 45615.0"
  []
  [no_reflow]
    type = TestReflow
    long_vector = '10 1 20 2 30 3 40 4 50 5 60 6 70 7 80 8 90 9 110 11 120 12 130 13 140 14 150 15 160 16 170 17 180 18 190 19 210 21 220 22 230 23 240 24 250 25 260 26 270 27 280 28 290 29'
  []
  [reflow]
    type = TestReflow
    long_vector = "10 1 20 2 30 3 40 4 50 5 60 6 70 7 80 8 90 9 110 11 120 12 130 13 140 14 150 15 "
                  "160 16 170 17 180 18 190 19 210 21 220 22 230 23 240 24 250 25 260 26 270 27 280 "
                  "28 290 29"
  []
[]
```

note that one line in `decrease2` would have to get a negative indent, which is clipped at 0.

2022-08-05 20:35 UTC, cticenhour requested changes
We should add something in documentation noting that there is a difference in formatting between single quotes and double quotes. [Perhaps here?](https://mooseframework.inl.gov/application_usage/input_syntax.html)....or a new page perhaps. 

Also please add an entry noting this new HIT behavior in the August 2022 news.

2022-08-05 20:35 UTC, cticenhour commented on framework/contrib/hit/parse.cc
> +        // add the leading indentation and newline - skip it for the first first chunk of a string
```suggestion
        // add the leading indentation and newline - skip it for the first chunk of a string
```

2022-08-05 20:35 UTC, cticenhour commented on unit/src/HitTests.C
> +      {"dont't reflow single quoted long string",
```suggestion
      {"don't reflow single quoted long string",
```

2022-08-06 16:37 UTC, cticenhour requested changes

2022-08-06 16:37 UTC, cticenhour commented on modules/doc/content/application_usage/input_syntax.md
> +however behave differently when auto-formatting input files with [`hit format`](/hit.md).
```suggestion
however behave differently when auto-formatting input files with [`hit format`](hit.md).
```

2022-08-06 16:37 UTC, cticenhour commented on modules/doc/content/newsletter/2022_08.md
> +linearly with the input file length, were it previously had a square dependence. This was mostly
```suggestion
linearly with the input file length, where it previously had a square dependence. This was mostly
```

2022-08-06 16:37 UTC, cticenhour commented on modules/doc/content/newsletter/2022_08.md
> +strings. Multiline string can occur in input files for example as data tables for `PiecewiseLinear`
```suggestion
strings. Multiline string can occur in input files when data and parameter entries 
need to be represented in a particular way - for example, as data tables for `PiecewiseLinear`
```

2022-08-06 16:37 UTC, cticenhour commented on modules/doc/content/newsletter/2022_08.md
> +strings. Multiline string can occur in input files for example as data tables for `PiecewiseLinear`
Suggestion since the sentence was lacking some context for the example.

2022-08-06 16:37 UTC, cticenhour commented on modules/doc/content/newsletter/2022_08.md
> +functions. `hit format` handled such strings poorly and disruppted careful manual formatting into
```suggestion
functions. `hit format` handled such strings poorly and disrupted careful manual formatting into
```

2022-08-06 16:37 UTC, cticenhour commented on modules/doc/content/newsletter/2022_08.md
> +columns reducing the input file readability. To alleviate this two major changes were made:
```suggestion
columns, reducing the input file readability. To alleviate this, two major changes were made:
```

2022-08-06 16:37 UTC, cticenhour commented on modules/doc/content/newsletter/2022_08.md
> +1. Single quoted strings `'...'` will stay completely untouched by `hit format`. This is useful to preserve ong strings, such as PETSc options in the Executioner block, which come as parameter pairs
```suggestion
1. Single quoted strings `'...'` will stay completely untouched by `hit format`. This is useful to preserve long strings, such as PETSc options in the Executioner block, which come as parameter pairs that are often manually formatted to have corresponding key value pairs aligned to the same column positions.
```

2022-08-06 16:37 UTC, cticenhour commented on modules/doc/content/newsletter/2022_08.md
> +2. Double quoted `"..."` strings will get formatted
```suggestion
2. Double quoted `"..."` strings will get formatted in the following ways:
```

2022-08-06 16:37 UTC, cticenhour commented on modules/doc/content/newsletter/2022_08.md
> +    - Single line strings get reflowed to according to a set maximum line length (useful for long text in test spec requirements)
```suggestion
    - Single line strings get reflowed according to a set maximum line length (useful for long text in test spec requirements)
```

2022-08-06 16:37 UTC, cticenhour commented on modules/doc/content/newsletter/2022_08.md
> +    - Multiline strings will only be reindented through inserting or removing spaces on the lines following the first line, to match any changes in indentation of the first line.
```suggestion
    - Multiline strings will only be re-indented through inserting or removing spaces on the lines following the first line, to match any changes in indentation of the first line.
```

2022-08-06 17:17 UTC, dschwen commented
Thanks Casey. I learned today that you can manually put a `Co-authored-by: name <email>` into the commit message...

2022-08-06 17:31 UTC, cticenhour approved these changes
Thank you Daniel! I didn't realize you could just manually add that line either.

2022-08-06 20:17 UTC, merged