Add weight functions
idaholab/moose pull request #21963
Opened 2022-08-29 23:46 UTC by dschwen

Closes #21960

I'm still working on debugging the hang on 8 procs.

2022-08-29 23:50 UTC, bwspenc requested changes, later dismissed

2022-08-29 23:50 UTC, bwspenc commented on test/tests/userobjects/radial_average/tests
> +    requirement = 'The system shall will compute a radial average of a material that changes over time.'
These need to be unique.

2022-08-30 01:53 UTC, moosebuild commented
Job [Documentation](https://civet.inl.gov/job/1157397/) on d364de5 wanted to post the following:

View the site [here](https://mooseframework.inl.gov/docs/PRs/21963/site)

This comment will be updated on new commits.

2022-08-30 05:06 UTC, moosebuild commented
Job [Coverage](https://civet.inl.gov/job/1157520/) on 528bbfc wanted to post the following:


## Framework coverage

<table>
  <thead>
    <tr>
      <th></th>
      <th>712a86</th>
      <th colspan=4>#21963 528bbf</th>
    </tr>
    <tr>
      <th></th>
      <th>Total</th>
      <th>Total</th>
      <th>+/-</th>
      <th>New</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><b>Rate</b></td>
      <td>84.15%</td>
      <td>84.15%</td>
      <td>-0.00%</td>
      <td>100.00%</td>
    </tr>
    <tr>
      <td><b>Hits</b></td>
      <td>78901</td>
      <td>78909</td>
      <td>+8</td>
      <td>29</td>
    </tr>
    <tr>
      <td><b>Misses</b></td>
      <td>14862</td>
      <td>14865</td>
      <td>+3</td>
      <td>0</td>
    </tr>
  </tbody>
</table>

[Diff coverage report](https://mooseframework.inl.gov/docs/PRs/21963/coverage_diff/framework)

[Full coverage report](https://mooseframework.inl.gov/docs/PRs/21963/coverage/framework)


## Modules coverage

Coverage did not change

## Full coverage reports

<details>
<summary>Reports</summary>

- [`framework`](https://mooseframework.inl.gov/docs/PRs/21963/coverage/framework)
- [`chemical_reactions`](https://mooseframework.inl.gov/docs/PRs/21963/coverage/chemical_reactions)
- [`combined`](https://mooseframework.inl.gov/docs/PRs/21963/coverage/combined)
- [`contact`](https://mooseframework.inl.gov/docs/PRs/21963/coverage/contact)
- [`electromagnetics`](https://mooseframework.inl.gov/docs/PRs/21963/coverage/electromagnetics)
- [`external_petsc_solver`](https://mooseframework.inl.gov/docs/PRs/21963/coverage/external_petsc_solver)
- [`fluid_properties`](https://mooseframework.inl.gov/docs/PRs/21963/coverage/fluid_properties)
- [`fsi`](https://mooseframework.inl.gov/docs/PRs/21963/coverage/fsi)
- [`functional_expansion_tools`](https://mooseframework.inl.gov/docs/PRs/21963/coverage/functional_expansion_tools)
- [`geochemistry`](https://mooseframework.inl.gov/docs/PRs/21963/coverage/geochemistry)
- [`heat_conduction`](https://mooseframework.inl.gov/docs/PRs/21963/coverage/heat_conduction)
- [`level_set`](https://mooseframework.inl.gov/docs/PRs/21963/coverage/level_set)
- [`misc`](https://mooseframework.inl.gov/docs/PRs/21963/coverage/misc)
- [`navier_stokes`](https://mooseframework.inl.gov/docs/PRs/21963/coverage/navier_stokes)
- [`peridynamics`](https://mooseframework.inl.gov/docs/PRs/21963/coverage/peridynamics)
- [`phase_field`](https://mooseframework.inl.gov/docs/PRs/21963/coverage/phase_field)
- [`porous_flow`](https://mooseframework.inl.gov/docs/PRs/21963/coverage/porous_flow)
- [`ray_tracing`](https://mooseframework.inl.gov/docs/PRs/21963/coverage/ray_tracing)
- [`rdg`](https://mooseframework.inl.gov/docs/PRs/21963/coverage/rdg)
- [`reactor`](https://mooseframework.inl.gov/docs/PRs/21963/coverage/reactor)
- [`richards`](https://mooseframework.inl.gov/docs/PRs/21963/coverage/richards)
- [`solid_properties`](https://mooseframework.inl.gov/docs/PRs/21963/coverage/solid_properties)
- [`stochastic_tools`](https://mooseframework.inl.gov/docs/PRs/21963/coverage/stochastic_tools)
- [`tensor_mechanics`](https://mooseframework.inl.gov/docs/PRs/21963/coverage/tensor_mechanics)
- [`thermal_hydraulics`](https://mooseframework.inl.gov/docs/PRs/21963/coverage/thermal_hydraulics)
- [`xfem`](https://mooseframework.inl.gov/docs/PRs/21963/coverage/xfem)

</details>



This comment will be updated on new commits.

2022-08-30 12:37 UTC, dschwen commented
@bwspenc the failure is in an unrelated test in s parallel recipes that I should not have enabled according to @loganharbour .

2022-08-30 14:46 UTC, loganharbour approved these changes

2022-08-30 14:47 UTC, merged