Allow setting thermal conductivity components as function of temperature
idaholab/moose pull request #22028
Opened 2022-09-07 00:35 UTC by singhgp4321

Ref: #22027

## Reason
User may want to set individual components of thermal conductivity tensor as different functions of temperature.

## Design
The current model AnisoHeatConductionMaterial will be updated to allow user to input individual components. The user will set the components using input parameters which will be functions of temperature; functions will be defined in the input file.

## Impact
This update will not change the existing functionality of the code.

2022-09-07 01:56 UTC, moosebuild commented
Job [Documentation](https://civet.inl.gov/job/1164594/) on 270d452 wanted to post the following:

View the site [here](https://mooseframework.inl.gov/docs/PRs/22028/site)

This comment will be updated on new commits.

2022-09-07 12:49 UTC, dschwen commented
A better Dr resign would be to have a material like GenericFunctionMaterial that builds a rank two tensor from functions. That way not every class would have to be modified to support function dependent tensors.

2022-09-07 12:53 UTC, dschwen requested changes
Factor out function tensor material

2022-09-07 12:53 UTC, dschwen commented on modules/heat_conduction/doc/content/source/materials/AnisoHeatConductionMaterial.md
> +Another way, by which the user can provide thermal conductivity, is by providing the indivifual components `k_11`, `k_22` and `k_33` which can be either a constant value or a function of temperature.
```suggestion
Another way, by which the user can provide thermal conductivity, is by providing the individual components `k_11`, `k_22` and `k_33` which can be either a constant value or a function of temperature.  Note that if `k_22` or `k_33` are not provided then their values will be set equal to that of `k_11`. Of the three parameters `k_11`, `k_22` and `k_33`, `k_11` is mandatory and the latter two are optional.
```

2022-09-07 12:53 UTC, dschwen commented on modules/heat_conduction/src/materials/AnisoHeatConductionMaterial.C
> +  params.addParam<std::vector<Real>>("thermal_conductivity",
Numbers are a special case of functions. Those should not be different parameters. In fact the class should couple a material property instead.

2023-01-10 21:14 UTC, singhgp4321 commented
@dschwen Could you please reopen this PR? I don't seem to have the rights to open it.

2023-10-14 05:39 UTC, closed without merging