Support stateful on displaced interface
idaholab/moose pull request #22238
Opened 2022-09-27 17:42 UTC by lindsayad

Previously if there was a displaced material and interface objects and not boundary objects on the same boundary as the interface object, you could get bad computations on the displaced material because the displaced assembly would not be properly initialized (nor likely the displaced systems)

Refs #21900

2022-09-27 19:00 UTC, moosebuild commented
Job [Documentation](https://civet.inl.gov/job/1187020/) on 7dcbdfb wanted to post the following:

View the site [here](https://mooseframework.inl.gov/docs/PRs/22238/site)

This comment will be updated on new commits.

2022-09-27 19:39 UTC, moosebuild commented
Job [Coverage](https://civet.inl.gov/job/1187033/) on 7dcbdfb wanted to post the following:


## Framework coverage

<table>
  <thead>
    <tr>
      <th></th>
      <th>b740c7</th>
      <th colspan=4>#22238 7dcbdf</th>
    </tr>
    <tr>
      <th></th>
      <th>Total</th>
      <th>Total</th>
      <th>+/-</th>
      <th>New</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><b>Rate</b></td>
      <td>84.27%</td>
      <td>84.27%</td>
      <td>-0.00%</td>
      <td>100.00%</td>
    </tr>
    <tr>
      <td><b>Hits</b></td>
      <td>79945</td>
      <td>79944</td>
      <td>-1</td>
      <td>1</td>
    </tr>
    <tr>
      <td><b>Misses</b></td>
      <td>14921</td>
      <td>14922</td>
      <td>+1</td>
      <td>0</td>
    </tr>
  </tbody>
</table>

[Diff coverage report](https://mooseframework.inl.gov/docs/PRs/22238/coverage_diff/framework)

[Full coverage report](https://mooseframework.inl.gov/docs/PRs/22238/coverage/framework)


## Modules coverage

Coverage did not change

## Full coverage reports

<details>
<summary>Reports</summary>

- [`framework`](https://mooseframework.inl.gov/docs/PRs/22238/coverage/framework)
- [`chemical_reactions`](https://mooseframework.inl.gov/docs/PRs/22238/coverage/chemical_reactions)
- [`combined`](https://mooseframework.inl.gov/docs/PRs/22238/coverage/combined)
- [`contact`](https://mooseframework.inl.gov/docs/PRs/22238/coverage/contact)
- [`electromagnetics`](https://mooseframework.inl.gov/docs/PRs/22238/coverage/electromagnetics)
- [`external_petsc_solver`](https://mooseframework.inl.gov/docs/PRs/22238/coverage/external_petsc_solver)
- [`fluid_properties`](https://mooseframework.inl.gov/docs/PRs/22238/coverage/fluid_properties)
- [`fsi`](https://mooseframework.inl.gov/docs/PRs/22238/coverage/fsi)
- [`functional_expansion_tools`](https://mooseframework.inl.gov/docs/PRs/22238/coverage/functional_expansion_tools)
- [`geochemistry`](https://mooseframework.inl.gov/docs/PRs/22238/coverage/geochemistry)
- [`heat_conduction`](https://mooseframework.inl.gov/docs/PRs/22238/coverage/heat_conduction)
- [`level_set`](https://mooseframework.inl.gov/docs/PRs/22238/coverage/level_set)
- [`misc`](https://mooseframework.inl.gov/docs/PRs/22238/coverage/misc)
- [`navier_stokes`](https://mooseframework.inl.gov/docs/PRs/22238/coverage/navier_stokes)
- [`peridynamics`](https://mooseframework.inl.gov/docs/PRs/22238/coverage/peridynamics)
- [`phase_field`](https://mooseframework.inl.gov/docs/PRs/22238/coverage/phase_field)
- [`porous_flow`](https://mooseframework.inl.gov/docs/PRs/22238/coverage/porous_flow)
- [`ray_tracing`](https://mooseframework.inl.gov/docs/PRs/22238/coverage/ray_tracing)
- [`rdg`](https://mooseframework.inl.gov/docs/PRs/22238/coverage/rdg)
- [`reactor`](https://mooseframework.inl.gov/docs/PRs/22238/coverage/reactor)
- [`richards`](https://mooseframework.inl.gov/docs/PRs/22238/coverage/richards)
- [`solid_properties`](https://mooseframework.inl.gov/docs/PRs/22238/coverage/solid_properties)
- [`stochastic_tools`](https://mooseframework.inl.gov/docs/PRs/22238/coverage/stochastic_tools)
- [`tensor_mechanics`](https://mooseframework.inl.gov/docs/PRs/22238/coverage/tensor_mechanics)
- [`thermal_hydraulics`](https://mooseframework.inl.gov/docs/PRs/22238/coverage/thermal_hydraulics)
- [`xfem`](https://mooseframework.inl.gov/docs/PRs/22238/coverage/xfem)

</details>



This comment will be updated on new commits.

2022-09-28 01:46 UTC, moosebuild commented
Job [Internal app tests](https://civet.inl.gov/job/1187021/) on 7dcbdfb : invalidated by @lindsayad

2022-09-29 00:53 UTC, GiudGiud requested changes
needs a test

2022-09-29 17:50 UTC, moosebuild commented
Job [Docker](https://civet.inl.gov/job/1189038/) on 852d1d5 : invalidated by @lindsayad

2022-09-29 22:23 UTC, GiudGiud requested changes

2022-09-29 22:23 UTC, GiudGiud commented on framework/include/loops/ThreadedElementLoopBase.h
> +   * emit a relatively error message when we catch a MetaPhysicL logic error
```suggestion
   * emit a relatively clear error message when we catch a MetaPhysicL logic error
```

2022-09-29 22:23 UTC, GiudGiud commented on framework/include/loops/ThreadedElementLoopBase.h
> +      "errors include evaluating functions like sqrt (which gets called for vector norm functions) "
```suggestion
      "errors include evaluating functions where they are not defined or differentiable like sqrt (which gets called for vector norm functions) "
```

2022-09-29 22:23 UTC, GiudGiud commented on modules/fsi/test/tests/2d-finite-strain-steady/2layers_2d_midline.msh
> +$MeshFormat
document the gmsh version somewhere pls

2022-09-30 19:01 UTC, lindsayad commented on modules/fsi/test/tests/2d-finite-strain-steady/2layers_2d_midline.msh
> +$MeshFormat
It's documented right in the line below

2022-09-30 19:06 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/1190152/) on 1e56282 wanted to post the following:

Your code requires style changes.  

A patch was auto generated and copied [here](https://mooseframework.inl.gov/docs/PRs/22238/clang_format/style.patch)  
You can directly apply the patch by running, in the top level of your repository:

`curl -s https://mooseframework.inl.gov/docs/PRs/22238/clang_format/style.patch | git apply -v`  

Alternatively, with your repository up to date and in the top level of your repository:

`git clang-format 71dc08770e00d3f37c618341d5766a662819a0a9`

2022-09-30 20:05 UTC, GiudGiud commented on framework/include/loops/ThreadedElementLoopBase.h
> +   * emit a relatively error message when we catch a MetaPhysicL logic error
```suggestion
   * emit a relatively clear error message when we catch a MetaPhysicL logic error
```

2022-09-30 20:05 UTC, GiudGiud commented on modules/fsi/test/tests/2d-finite-strain-steady/2layers_2d_midline.msh
> +$MeshFormat
nice

2022-09-30 21:01 UTC, GiudGiud approved these changes

2022-09-30 23:21 UTC, moosebuild commented
Job [Modules debug](https://civet.inl.gov/job/1190322/) on 7a0e532 : invalidated by @lindsayad

2022-09-30 23:21 UTC, moosebuild commented
Job [Documentation](https://civet.inl.gov/job/1190335/) on 7a0e532 : invalidated by @lindsayad

2022-10-01 02:11 UTC, merged

2022-10-01 02:24 UTC, lindsayad commented
Thanks for the fast reviews!