Update INL Application page
idaholab/moose pull request #22297
Opened 2022-10-04 17:00 UTC by milljm

Update our application page with links to internal resources. Fix peacock tests when PyQt isn't available (freebie).

Closes #22290

2022-10-04 17:29 UTC, moosebuild commented on large_media
> +Subproject commit 337c26d2b4eb642fe4cb0268bfed78037cf6133c
**Caution!** This contains a submodule update

2022-10-04 18:47 UTC, moosebuild commented
Job [Documentation](https://civet.inl.gov/job/1192137/) on fb54bc3 wanted to post the following:

View the site [here](https://mooseframework.inl.gov/docs/PRs/22297/site)

This comment will be updated on new commits.

2022-10-04 20:08 UTC, milljm commented
And documentation will keep failing until my large_media PR gets merged: https://github.com/idaholab/large_media/pull/32

2022-10-05 15:22 UTC, joshuahansel requested changes

2022-10-05 15:22 UTC, joshuahansel commented on modules/doc/content/help/inl/applications.md
> +MARMOT is a mesoscale fuel performance code. As such, it can predict the evolution of the microstructure and material properties of fuels and claddings due to stress, temperature, and irradiation dam
- to other applications that work at a larger scale, such as Bison, which works at an engineering scale.

2022-10-05 15:22 UTC, joshuahansel commented on modules/doc/content/help/inl/applications.md
> +## Relap-7
Capitalize RELAP

2022-10-05 15:22 UTC, joshuahansel commented on modules/doc/content/help/inl/applications.md
> +A next generation nuclear systems safety code, RELAP-7 takes advantage of advances in computer architecture, software design, numerical methods, and physical models for use in the Risk Informed Safet
Replace the whole description. I suggest:

RELAP-7 is a two-phase thermal systems code based on MOOSE's thermal hydraulics module. RELAP-7 provides two-phase components suitable for LWRs provides closures for two-phase water from TRACE.

2022-10-05 15:22 UTC, joshuahansel commented on modules/doc/content/help/inl/applications.md
> +Sockeye is a MOOSE-based heat pipe simulator and analysis tool. It, therefore, provides the ability to accurately predict heat transfer for heat-pipe-cooled microreactors and other heat pipe applicat
Replace the whole description. I suggest:

Sockeye is a heat pipe analysis application geared towards heat pipes of interest in heat-pipe-cooled microreactors. Sockeye provides various transient heat pipe modeling capabilities, including a 1D, two-phase flow model and a 2D effective thermal conductivity model based on heat conduction, which leverages analytic expressions of operational limits.

2022-10-06 13:00 UTC, moosebuild commented on large_media
> +Subproject commit cf30a5de0cdbfe33502b0d4fb01cee09b9f8391d
**Caution!** This contains a submodule update

2022-10-06 17:50 UTC, moosebuild commented on large_media
> +Subproject commit cf30a5de0cdbfe33502b0d4fb01cee09b9f8391d
**Caution!** This contains a submodule update

2022-10-10 12:37 UTC, joshuahansel approved these changes

2022-10-10 12:40 UTC, merged