Add clearer error message for syntax issues when running the wrong app
idaholab/moose pull request #22340
Opened 2022-10-09 15:26 UTC by GiudGiud

refs #20062

This will be a lot more lines when running totally the wrong app with multiples actions. 
We could make it "do once" for part of the message if that s a real concern

2022-10-09 16:53 UTC, moosebuild commented
Job [Documentation](https://civet.inl.gov/job/1195701/) on cdf256b wanted to post the following:

View the site [here](https://mooseframework.inl.gov/docs/PRs/22340/site)

This comment will be updated on new commits.

2022-10-09 17:39 UTC, moosebuild commented
Job [Coverage](https://civet.inl.gov/job/1195714/) on cdf256b wanted to post the following:


## Framework coverage

<table>
  <thead>
    <tr>
      <th></th>
      <th>c948cb</th>
      <th colspan=4>#22340 cdf256</th>
    </tr>
    <tr>
      <th></th>
      <th>Total</th>
      <th>Total</th>
      <th>+/-</th>
      <th>New</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><b>Rate</b></td>
      <td>84.30%</td>
      <td>84.30%</td>
      <td>-</td>
      <td>0.00%</td>
    </tr>
    <tr>
      <td><b>Hits</b></td>
      <td>80156</td>
      <td>80156</td>
      <td>-</td>
      <td>0</td>
    </tr>
    <tr>
      <td><b>Misses</b></td>
      <td>14929</td>
      <td>14929</td>
      <td>-</td>
      <td>1</td>
    </tr>
  </tbody>
</table>

[Diff coverage report](https://mooseframework.inl.gov/docs/PRs/22340/coverage_diff/framework)

[Full coverage report](https://mooseframework.inl.gov/docs/PRs/22340/coverage/framework)


## Modules coverage

Coverage did not change

## Full coverage reports

<details>
<summary>Reports</summary>

- [`framework`](https://mooseframework.inl.gov/docs/PRs/22340/coverage/framework)
- [`chemical_reactions`](https://mooseframework.inl.gov/docs/PRs/22340/coverage/chemical_reactions)
- [`combined`](https://mooseframework.inl.gov/docs/PRs/22340/coverage/combined)
- [`contact`](https://mooseframework.inl.gov/docs/PRs/22340/coverage/contact)
- [`electromagnetics`](https://mooseframework.inl.gov/docs/PRs/22340/coverage/electromagnetics)
- [`external_petsc_solver`](https://mooseframework.inl.gov/docs/PRs/22340/coverage/external_petsc_solver)
- [`fluid_properties`](https://mooseframework.inl.gov/docs/PRs/22340/coverage/fluid_properties)
- [`fsi`](https://mooseframework.inl.gov/docs/PRs/22340/coverage/fsi)
- [`functional_expansion_tools`](https://mooseframework.inl.gov/docs/PRs/22340/coverage/functional_expansion_tools)
- [`geochemistry`](https://mooseframework.inl.gov/docs/PRs/22340/coverage/geochemistry)
- [`heat_conduction`](https://mooseframework.inl.gov/docs/PRs/22340/coverage/heat_conduction)
- [`level_set`](https://mooseframework.inl.gov/docs/PRs/22340/coverage/level_set)
- [`misc`](https://mooseframework.inl.gov/docs/PRs/22340/coverage/misc)
- [`navier_stokes`](https://mooseframework.inl.gov/docs/PRs/22340/coverage/navier_stokes)
- [`peridynamics`](https://mooseframework.inl.gov/docs/PRs/22340/coverage/peridynamics)
- [`phase_field`](https://mooseframework.inl.gov/docs/PRs/22340/coverage/phase_field)
- [`porous_flow`](https://mooseframework.inl.gov/docs/PRs/22340/coverage/porous_flow)
- [`ray_tracing`](https://mooseframework.inl.gov/docs/PRs/22340/coverage/ray_tracing)
- [`rdg`](https://mooseframework.inl.gov/docs/PRs/22340/coverage/rdg)
- [`reactor`](https://mooseframework.inl.gov/docs/PRs/22340/coverage/reactor)
- [`richards`](https://mooseframework.inl.gov/docs/PRs/22340/coverage/richards)
- [`solid_properties`](https://mooseframework.inl.gov/docs/PRs/22340/coverage/solid_properties)
- [`stochastic_tools`](https://mooseframework.inl.gov/docs/PRs/22340/coverage/stochastic_tools)
- [`tensor_mechanics`](https://mooseframework.inl.gov/docs/PRs/22340/coverage/tensor_mechanics)
- [`thermal_hydraulics`](https://mooseframework.inl.gov/docs/PRs/22340/coverage/thermal_hydraulics)
- [`xfem`](https://mooseframework.inl.gov/docs/PRs/22340/coverage/xfem)

</details>

## Warnings

- `framework` new line coverage rate 0.00% is less than the suggested 90.0%



This comment will be updated on new commits.

2022-10-11 17:38 UTC, lindsayad requested changes
test?

2022-10-11 18:43 UTC, GiudGiud commented
Added

2022-10-11 19:08 UTC, moosebuild commented
Job [Python 3.8](https://civet.inl.gov/job/1197644/) on 51015a3 : invalidated by @lindsayad

2022-10-11 20:43 UTC, GiudGiud commented
should be fine now

2022-10-11 23:04 UTC, lindsayad approved these changes

2022-10-11 23:30 UTC, merged