Add clang-format to moose-mpich base package
idaholab/moose pull request #22420
Opened 2022-10-17 14:39 UTC by milljm

Well... by `mamba install clang-format` you don't actualy get clang-format. You need to ask Conda for clang-tools in order to actually get the `git` clang-format utility.

Closes #22419

2022-10-17 14:40 UTC, loganharbour approved these changes

2022-10-17 14:41 UTC, cticenhour approved these changes, later dismissed

2022-10-17 14:42 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/1204333/) on 4df3932 wanted to post the following:

A change of the following file(s) triggered this check:

  conda/petsc

The following file(s) are unchanged:

  conda/mpich/conda_build_config.yaml

The conda build config was not changed but one or more of its dependencies have changed

2022-10-17 14:42 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/1204333/) on 4df3932 wanted to post the following:

The following file(s) are changed:

  conda/petsc/meta.yaml

The PETSc conda configuration has changed; ping @idaholab/moose-dev-ops

2022-10-17 14:42 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/1204333/) on 4df3932 wanted to post the following:

The following file(s) are changed:

  conda/libmesh/meta.yaml

The libmesh conda configuration has changed; ping @idaholab/moose-dev-ops

2022-10-17 15:48 UTC, loganharbour requested changes
Please don't merge while I'm messing with the moosebuild package

2022-10-17 16:20 UTC, moosebuild commented
Job [Documentation](https://civet.inl.gov/job/1204355/) on 4df3932 wanted to post the following:

View the site [here](https://mooseframework.inl.gov/docs/PRs/22420/site)

This comment will be updated on new commits.

2022-10-17 17:06 UTC, moosebuild commented
Job [Coverage](https://civet.inl.gov/job/1204368/) on 4df3932 wanted to post the following:


## Framework coverage

<table>
  <thead>
    <tr>
      <th></th>
      <th>fd64be</th>
      <th colspan=4>#22420 4df393</th>
    </tr>
    <tr>
      <th></th>
      <th>Total</th>
      <th>Total</th>
      <th>+/-</th>
      <th>New</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><b>Rate</b></td>
      <td>84.21%</td>
      <td>84.20%</td>
      <td>-0.01%</td>
      <td>-</td>
    </tr>
    <tr>
      <td><b>Hits</b></td>
      <td>80184</td>
      <td>80179</td>
      <td>-5</td>
      <td>0</td>
    </tr>
    <tr>
      <td><b>Misses</b></td>
      <td>15036</td>
      <td>15041</td>
      <td>+5</td>
      <td>0</td>
    </tr>
  </tbody>
</table>

[Diff coverage report](https://mooseframework.inl.gov/docs/PRs/22420/coverage_diff/framework)

[Full coverage report](https://mooseframework.inl.gov/docs/PRs/22420/coverage/framework)


## Modules coverage

Coverage did not change

## Full coverage reports

<details>
<summary>Reports</summary>

- [`framework`](https://mooseframework.inl.gov/docs/PRs/22420/coverage/framework)
- [`chemical_reactions`](https://mooseframework.inl.gov/docs/PRs/22420/coverage/chemical_reactions)
- [`combined`](https://mooseframework.inl.gov/docs/PRs/22420/coverage/combined)
- [`contact`](https://mooseframework.inl.gov/docs/PRs/22420/coverage/contact)
- [`electromagnetics`](https://mooseframework.inl.gov/docs/PRs/22420/coverage/electromagnetics)
- [`external_petsc_solver`](https://mooseframework.inl.gov/docs/PRs/22420/coverage/external_petsc_solver)
- [`fluid_properties`](https://mooseframework.inl.gov/docs/PRs/22420/coverage/fluid_properties)
- [`fsi`](https://mooseframework.inl.gov/docs/PRs/22420/coverage/fsi)
- [`functional_expansion_tools`](https://mooseframework.inl.gov/docs/PRs/22420/coverage/functional_expansion_tools)
- [`geochemistry`](https://mooseframework.inl.gov/docs/PRs/22420/coverage/geochemistry)
- [`heat_conduction`](https://mooseframework.inl.gov/docs/PRs/22420/coverage/heat_conduction)
- [`level_set`](https://mooseframework.inl.gov/docs/PRs/22420/coverage/level_set)
- [`misc`](https://mooseframework.inl.gov/docs/PRs/22420/coverage/misc)
- [`navier_stokes`](https://mooseframework.inl.gov/docs/PRs/22420/coverage/navier_stokes)
- [`peridynamics`](https://mooseframework.inl.gov/docs/PRs/22420/coverage/peridynamics)
- [`phase_field`](https://mooseframework.inl.gov/docs/PRs/22420/coverage/phase_field)
- [`porous_flow`](https://mooseframework.inl.gov/docs/PRs/22420/coverage/porous_flow)
- [`ray_tracing`](https://mooseframework.inl.gov/docs/PRs/22420/coverage/ray_tracing)
- [`rdg`](https://mooseframework.inl.gov/docs/PRs/22420/coverage/rdg)
- [`reactor`](https://mooseframework.inl.gov/docs/PRs/22420/coverage/reactor)
- [`richards`](https://mooseframework.inl.gov/docs/PRs/22420/coverage/richards)
- [`solid_properties`](https://mooseframework.inl.gov/docs/PRs/22420/coverage/solid_properties)
- [`stochastic_tools`](https://mooseframework.inl.gov/docs/PRs/22420/coverage/stochastic_tools)
- [`tensor_mechanics`](https://mooseframework.inl.gov/docs/PRs/22420/coverage/tensor_mechanics)
- [`thermal_hydraulics`](https://mooseframework.inl.gov/docs/PRs/22420/coverage/thermal_hydraulics)
- [`xfem`](https://mooseframework.inl.gov/docs/PRs/22420/coverage/xfem)

</details>



This comment will be updated on new commits.

2022-10-18 12:34 UTC, milljm commented
I am also 'messing' with live civet recipe scripts, in order to figure out building the combined-opt package via PRs...

2022-10-18 13:59 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/1204333/) on 4df3932 wanted to post the following:

The following file(s) are changed:

  conda/petsc/meta.yaml

The PETSc conda configuration has changed; ping @idaholab/moose-dev-ops

2022-10-18 13:59 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/1204333/) on 4df3932 wanted to post the following:

The following file(s) are changed:

  conda/libmesh/meta.yaml

The libmesh conda configuration has changed; ping @idaholab/moose-dev-ops

2022-10-18 14:56 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/1204333/) on 4df3932 wanted to post the following:

A change of the following file(s) triggered this check:

  conda/petsc

The following file(s) are unchanged:

  conda/mpich/conda_build_config.yaml

The conda build config was not changed but one or more of its dependencies have changed

2022-10-18 14:56 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/1204333/) on 4df3932 wanted to post the following:

The following file(s) are changed:

  conda/petsc/meta.yaml

The PETSc conda configuration has changed; ping @idaholab/moose-dev-ops

2022-10-18 14:56 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/1204333/) on 4df3932 wanted to post the following:

The following file(s) are changed:

  conda/libmesh/meta.yaml

The libmesh conda configuration has changed; ping @idaholab/moose-dev-ops

2022-10-18 16:27 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/1206402/) on f9e05d1 wanted to post the following:

A change of the following file(s) triggered this check:

  conda/petsc

The following file(s) are unchanged:

  conda/mpich/conda_build_config.yaml

The conda build config was not changed but one or more of its dependencies have changed

2022-10-18 16:27 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/1206402/) on f9e05d1 wanted to post the following:

The following file(s) are changed:

  conda/libmesh/meta.yaml

The libmesh conda configuration has changed; ping @idaholab/moose-dev-ops

2022-10-18 16:30 UTC, loganharbour approved these changes

2022-10-19 12:44 UTC, merged