Petsc 3.8 fixes
idaholab/moose pull request #22562
Opened 2022-11-01 20:37 UTC by roystgnr

This along with the next libMesh submodule update will take care of #22549.  We might wait until that's ready and merge this branch into the submodule update PR branch, but I'd like to make sure in advance that the changes here don't have any side effects that CI can catch.

## Reason
Compatibility with PETSc 3.8 and later

## Design
Fixes for bad code that PETSc 3.8 now warns about; shims and `#ifdef` clauses for perfectly fine code that PETSc just doesn't support anymore.

## Impact
There should be no external impact, we'll just be able to compile against new PETSc releases again.

2022-11-01 20:39 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/1221300/) on 0298931 wanted to post the following:

Your code requires style changes.  

A patch was auto generated and copied [here](https://mooseframework.inl.gov/docs/PRs/22562/clang_format/style.patch)  
You can directly apply the patch by running, in the top level of your repository:

`curl -s https://mooseframework.inl.gov/docs/PRs/22562/clang_format/style.patch | git apply -v`  

Alternatively, with your repository up to date and in the top level of your repository:

`git clang-format 99a16292097fa76a9ab79a423abc39303be14fd2`

2022-11-02 13:31 UTC, loganharbour commented
We don't officially support anything older than PETSc 3.11.4, and have made the decision in the past not to test anything earlier than that. Who is the customer for this?

2022-11-02 13:50 UTC, lindsayad requested changes

2022-11-02 13:50 UTC, lindsayad commented on framework/src/utils/PetscDMMoose.C
> +#if PETSC_RELEASE_LESS_THAN(3, 8, 0)
Is this 3.18 or 3.8?

2022-11-02 13:51 UTC, roystgnr commented
Yes, of course I mean 3.18.  Damn it.

2022-11-02 13:54 UTC, loganharbour commented
> Yes, of course I mean 3.18. Damn it.

![60a4fa00-41db-11eb-90c2-e18f174d8468](https://user-images.githubusercontent.com/22062133/199507635-db5cf191-953d-423f-b60b-92bb1e37b681.jpg)

2022-11-02 13:56 UTC, loganharbour reviewed
We should probably do the libmesh + petsc 3.18 update all in one go here, no?

2022-11-02 13:58 UTC, roystgnr commented
Ah, damn it, I get it.  I was copying fixes from the libMesh patches.  In the libMesh format string shim I switched to PetscInt_FMT at PETSc 3.8+ because that's when they added that macro.  But then in MOOSE I also *copied* that shim to other updates that really don't become possible until 3.18.

2022-11-02 14:00 UTC, roystgnr commented
> We should probably do the libmesh + petsc 3.18 update all in one go here, no?

That's what I was leaning towards in the description, yeah.  But the next libMesh update has other things it's waiting on, so I'm not pulling this PR yet.  I think my "I'd like to make sure in advance that the changes here don't have any side effects that CI can catch." strategy has been sadly vindicated...

2022-11-02 14:00 UTC, lindsayad commented
It would be great to do a PETSc update. But I will say that can sometimes turn into quite a task. @roystgnr do you want to take on that responsibility? Otherwise I can. I think it might be a good idea to try and segregate the petsc and libMesh updates if possible so we can more easily discern possible test failure causes

2022-11-02 14:04 UTC, roystgnr commented
Ok, I parsed "petsc 3.18 update" as "petsc 3.18 compatibility update", and I'm now guessing that isn't what was intended?

I don't actually know if there's any reason to update our PETSc modules to 3.18.  Neither "Let's have a module to cover compatibility with every possible PETSc version" nor "Let's not bother with compatibility with PETSc versions we don't have in CI" seems like a good idea to me.  I do want to try to support end users who grab the latest PETSc, but they make API-breaking changes with arbitrary minor version increments, and I don't want to try to bother maintaining software stacks and test recipes to keep up with the history of that.

2022-11-02 15:31 UTC, moosebuild commented
Job [Documentation](https://civet.inl.gov/job/1221932/) on 5dbb00f wanted to post the following:

View the site [here](https://mooseframework.inl.gov/docs/PRs/22562/site)

This comment will be updated on new commits.

2022-11-02 15:37 UTC, lindsayad commented
What about updating our module hash to the last 3.17 minor version?

2022-11-02 15:37 UTC, lindsayad commented
(in a different PR by a yet-decided author)

2022-11-02 16:21 UTC, moosebuild commented
Job [Coverage](https://civet.inl.gov/job/1221945/) on 5dbb00f wanted to post the following:


## Framework coverage

<table>
  <thead>
    <tr>
      <th></th>
      <th>99a162</th>
      <th colspan=4>#22562 5dbb00</th>
    </tr>
    <tr>
      <th></th>
      <th>Total</th>
      <th>Total</th>
      <th>+/-</th>
      <th>New</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><b>Rate</b></td>
      <td>84.36%</td>
      <td>84.35%</td>
      <td>-0.00%</td>
      <td>7.14%</td>
    </tr>
    <tr>
      <td><b>Hits</b></td>
      <td>80629</td>
      <td>80624</td>
      <td>-5</td>
      <td>3</td>
    </tr>
    <tr>
      <td><b>Misses</b></td>
      <td>14951</td>
      <td>14954</td>
      <td>+3</td>
      <td>39</td>
    </tr>
  </tbody>
</table>

[Diff coverage report](https://mooseframework.inl.gov/docs/PRs/22562/coverage_diff/framework)

[Full coverage report](https://mooseframework.inl.gov/docs/PRs/22562/coverage/framework)


## Modules coverage

Coverage did not change

## Full coverage reports

<details>
<summary>Reports</summary>

- [`framework`](https://mooseframework.inl.gov/docs/PRs/22562/coverage/framework)
- [`chemical_reactions`](https://mooseframework.inl.gov/docs/PRs/22562/coverage/chemical_reactions)
- [`combined`](https://mooseframework.inl.gov/docs/PRs/22562/coverage/combined)
- [`contact`](https://mooseframework.inl.gov/docs/PRs/22562/coverage/contact)
- [`electromagnetics`](https://mooseframework.inl.gov/docs/PRs/22562/coverage/electromagnetics)
- [`external_petsc_solver`](https://mooseframework.inl.gov/docs/PRs/22562/coverage/external_petsc_solver)
- [`fluid_properties`](https://mooseframework.inl.gov/docs/PRs/22562/coverage/fluid_properties)
- [`fsi`](https://mooseframework.inl.gov/docs/PRs/22562/coverage/fsi)
- [`functional_expansion_tools`](https://mooseframework.inl.gov/docs/PRs/22562/coverage/functional_expansion_tools)
- [`geochemistry`](https://mooseframework.inl.gov/docs/PRs/22562/coverage/geochemistry)
- [`heat_conduction`](https://mooseframework.inl.gov/docs/PRs/22562/coverage/heat_conduction)
- [`level_set`](https://mooseframework.inl.gov/docs/PRs/22562/coverage/level_set)
- [`misc`](https://mooseframework.inl.gov/docs/PRs/22562/coverage/misc)
- [`navier_stokes`](https://mooseframework.inl.gov/docs/PRs/22562/coverage/navier_stokes)
- [`peridynamics`](https://mooseframework.inl.gov/docs/PRs/22562/coverage/peridynamics)
- [`phase_field`](https://mooseframework.inl.gov/docs/PRs/22562/coverage/phase_field)
- [`porous_flow`](https://mooseframework.inl.gov/docs/PRs/22562/coverage/porous_flow)
- [`ray_tracing`](https://mooseframework.inl.gov/docs/PRs/22562/coverage/ray_tracing)
- [`rdg`](https://mooseframework.inl.gov/docs/PRs/22562/coverage/rdg)
- [`reactor`](https://mooseframework.inl.gov/docs/PRs/22562/coverage/reactor)
- [`richards`](https://mooseframework.inl.gov/docs/PRs/22562/coverage/richards)
- [`scalar_transport`](https://mooseframework.inl.gov/docs/PRs/22562/coverage/scalar_transport)
- [`solid_properties`](https://mooseframework.inl.gov/docs/PRs/22562/coverage/solid_properties)
- [`stochastic_tools`](https://mooseframework.inl.gov/docs/PRs/22562/coverage/stochastic_tools)
- [`tensor_mechanics`](https://mooseframework.inl.gov/docs/PRs/22562/coverage/tensor_mechanics)
- [`thermal_hydraulics`](https://mooseframework.inl.gov/docs/PRs/22562/coverage/thermal_hydraulics)
- [`xfem`](https://mooseframework.inl.gov/docs/PRs/22562/coverage/xfem)

</details>

## Warnings

- `framework` new line coverage rate 7.14% is less than the suggested 90.0%



This comment will be updated on new commits.

2022-11-02 16:46 UTC, roystgnr commented
>What about updating our module hash to the last 3.17 minor version?

I'm not opposed to it (or to updating to 3.18 if someone wants to), but what do we gain from it?  I see clear reasons (albeit not quite as urgent on the MOOSE side now that so many users are on our stack) to update the list of *supported* PETSc versions as fast as they come out, but I'm not sure what we get from making an update on our *supplied* PETSc versions except when there's a new feature that somebody wants.

2022-11-02 16:52 UTC, garciapintado commented
Well, at least one user (me) will immediately benefit from having PETSc 3.18 compatibility. See #22565

2022-11-02 16:59 UTC, lindsayad commented
@roystgnr is drawing a distinction between compatibility and what we provide in our submodule. He is adding the compatibility here which should be immediately beneficial to you @garciapintado. The latter point should not really be relevant to you since you already have a built PETSc 3.18

As far as what we provide ... I suppose it is not all that important until a user wants a particular feature that our supplied petsc doesn't provide. The fact that @garciapintado wants to use PETSc 3.18 could mean that such a feature already exists. I would say that most of our users use our provided PETSc, whether that comes from building it from the submodule hash or through conda which uses the submodule hash. In that vein providing a new PETSc that has all the best features (and maybe some bug fixes from previous major versions) sounds like a good thing to me.

2022-11-02 17:07 UTC, loganharbour commented
I think the issue is that with our infrastructure it's easier to test new PETSc by making it the default. Which probably isn't the best scenario... but it is the case

2022-11-02 17:09 UTC, roystgnr commented
>He is adding the compatibility here which should be immediately beneficial to you @garciapintado.

(wincing) ... for some definition of "immediately".  You'll also need to use a more recent libMesh than the current MOOSE submodule.

2022-11-02 17:14 UTC, garciapintado commented
> PETSc

No, I have not a built PETSc 3.18. The issue referred to by discussion #22565 is that I have tried to build MOOSE with its default PETSc built (3.16.6 if I'm right) in a HPC. This PETSc compilation has failed and I've sent the log files to a PETSc support e-mail. A PETSc developer has answered. He has not been very explicit, but indicated that the compilation error would be solved if I use PETSc 3.18. I'd presume that his answer comes from looking at the compilation *.log files I've sent them, and that he must have his reasons to indicate so.  That's all I can say. I have MOOSE (with PETSc 3.16) installed in other personal iMAC and linux systems without any problem. But there must be something in this HPC cluster, which appears to require later PETSc versions, according to the PETSc developer.

2022-11-02 17:29 UTC, roystgnr commented
> providing a new PETSc that has all the best features (and maybe some bug fixes from previous major versions) sounds like a good thing to me.

If it were costless, I'd agree.  Is it?  I got the impression from https://github.com/idaholab/moose/pull/22062#issuecomment-1243734954 that frequent module updates in our conda stack aren't free of annoyance.  I'm already pushing libMesh updates every month (and I'd be doing it more frequently if I thought it was costless); PETSc updates also come along around once a month, so if users need to worry about dependency updates we'd be doubling the rate of hassle.

(all that said, it's debate about the future - if our current petsc hash has a bug triggering for users then we need to update that ASAP, though I'd still want to get this in first and get a separate libMesh submodule update second)

> We should probably do the libmesh + petsc 3.18 update all in one go here, no?

And now I'd say no: if we've got users already being bitten by a 3.16 bug then I'd want to merge this ASAP to at least give a possible manual path forward.  I'll try to rush the next libMesh submodule update though.

2022-11-02 18:47 UTC, loganharbour commented
>  I'm already pushing libMesh updates every month (and I'd be doing it more frequently if I thought it was costless); PETSc updates also come along around once a month, so if users need to worry about dependency updates we'd be doubling the rate of hassle.

Sounds like the perfect opportunity to update both together.

2022-11-02 19:36 UTC, lindsayad requested changes

2022-11-02 19:36 UTC, lindsayad commented on framework/src/utils/PetscDMMoose.C
> +      ierr = PetscViewerASCIIPrintf(viewer, "(%s,%d) ", bit.first.c_str(), bit.second);
I believe this should be unsigned. I only thought of this because you changed to `u` for the `_var_ids`

2022-11-02 19:36 UTC, lindsayad commented on framework/src/utils/PetscDMMoose.C
> +      ierr = PetscViewerASCIIPrintf(viewer, "(%s,%d) ", bit.first.c_str(), bit.second);
Oops never mind I didn't read `id_types.h` close enough. Nothing to see here

2022-11-02 19:36 UTC, lindsayad commented on framework/src/utils/PetscDMMoose.C
> +DMSetFromOptions_Moose(DM dm, PetscOptionItems * /*options*/) // >= 3.8.0
```suggestion
DMSetFromOptions_Moose(DM dm, PetscOptionItems * /*options*/) // >= 3.18.0
```

2022-11-02 19:37 UTC, lindsayad commented
> I'm already dreading the first time we see an exodiff and don't even know whether it's from a libMesh change or a PETSc change, though.

Right, this is a potential developer nightmare. I suppose we are balancing a nightmare for the developer with incursions on the user

2022-11-02 19:38 UTC, lindsayad approved these changes

2022-11-02 22:13 UTC, roystgnr commented
"Failed but allowed" appears to mean "there's an unrelated compile problem in mockingbird", so I'm going to say the changes here are safe enough.

2022-11-02 22:14 UTC, merged

2022-11-03 19:45 UTC, cticenhour commented
I am suddenly getting lots of framework build failures in CI due to new compilation warnings stemming from `PetscDMMoose.C`. I am surprised these have not shown themselves in next. See https://civet.inl.gov/pr/16894/ for some examples. Note that it is not happening on every target where framework is being built - haven't looked closely at the compiler modules being loaded for those yet, but it might simply be a difference in compiler being used. Regardless, flagging here since this just went in.

2022-11-03 19:49 UTC, roystgnr commented
Oh, that's wonderful.  The previous version of `PetscOptionsBegin` started with `0;`, probably for backwards compatibility with code like our `ierr = PetscOptionsBegin`, and now that such code is broken with new PETSc, removing the `ierr =` is triggering a "statement has no effect" warning with old PETSc.

2022-11-03 20:07 UTC, cticenhour commented
OK - are you able to make a patch for this? I am available for a review.

2022-11-03 20:23 UTC, roystgnr commented
I'll give it a try.  I don't actually have an older PETSc build around anymore, though, so I'm not sure how to test the patch.  How did we not see any of those failures in the CI for *this* PR?

2022-11-03 20:25 UTC, cticenhour commented
I'm not sure about that either - I don't think we've changed any modules on the Linux CI environments in a while.

2022-11-03 20:26 UTC, cticenhour commented
If you DM be a branch - I can always cherry pick and place it in the PR I mentioned earlier as a test of it. I've been hitting this consistently today.

2022-11-03 20:27 UTC, roystgnr commented
Give https://github.com/roystgnr/moose/tree/petsc_38_fix_fixes a crack?

2022-11-03 20:36 UTC, cticenhour commented
Will do - it looks as though this PR used an available module of PETSc for targets like https://civet.inl.gov/job/1222811/ where my PR opts for the submodule being built instead (as I am making conda package changes). So I think that logic between the conda package state and the pre-built module is tied into this somehow.

2022-11-03 21:49 UTC, cticenhour commented
A previous failure is now passing with that change: https://civet.inl.gov/job/1224154/. Thanks @roystgnr!