Sphere mesh generator
idaholab/moose pull request #22594
Opened 2022-11-03 19:11 UTC by aprilnovak

Adds sphere mesh generator.

Closes #22591

2022-11-03 19:14 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/1223968/) on 36c3292 wanted to post the following:

Your code requires style changes.  

A patch was auto generated and copied [here](https://mooseframework.inl.gov/docs/PRs/22594/clang_format/style.patch)  
You can directly apply the patch by running, in the top level of your repository:

`curl -s https://mooseframework.inl.gov/docs/PRs/22594/clang_format/style.patch | git apply -v`  

Alternatively, with your repository up to date and in the top level of your repository:

`git clang-format c8ebf494b57f8d9c718405208a8445e3df28cff5`

2022-11-03 21:13 UTC, moosebuild commented
Job [Documentation](https://civet.inl.gov/job/1224067/) on 60453a5 wanted to post the following:

View the site [here](https://mooseframework.inl.gov/docs/PRs/22594/site)

This comment will be updated on new commits.

2022-11-04 03:27 UTC, GiudGiud commented
@friedmud I think you worked on a sphere mesh at some point. Any comment on that one?
anyone else who would have an opinion or needs to know?

2022-11-05 07:17 UTC, moosebuild commented
Job [Coverage](https://civet.inl.gov/job/1224759/) on 6577de5 wanted to post the following:


## Framework coverage

<table>
  <thead>
    <tr>
      <th></th>
      <th>c8ebf4</th>
      <th colspan=4>#22594 6577de</th>
    </tr>
    <tr>
      <th></th>
      <th>Total</th>
      <th>Total</th>
      <th>+/-</th>
      <th>New</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><b>Rate</b></td>
      <td>84.36%</td>
      <td>84.37%</td>
      <td>+0.01%</td>
      <td>100.00%</td>
    </tr>
    <tr>
      <td><b>Hits</b></td>
      <td>80674</td>
      <td>80702</td>
      <td>+28</td>
      <td>24</td>
    </tr>
    <tr>
      <td><b>Misses</b></td>
      <td>14956</td>
      <td>14952</td>
      <td>-4</td>
      <td>0</td>
    </tr>
  </tbody>
</table>

[Diff coverage report](https://mooseframework.inl.gov/docs/PRs/22594/coverage_diff/framework)

[Full coverage report](https://mooseframework.inl.gov/docs/PRs/22594/coverage/framework)


## Modules coverage

Coverage did not change

## Full coverage reports

<details>
<summary>Reports</summary>

- [`framework`](https://mooseframework.inl.gov/docs/PRs/22594/coverage/framework)
- [`chemical_reactions`](https://mooseframework.inl.gov/docs/PRs/22594/coverage/chemical_reactions)
- [`combined`](https://mooseframework.inl.gov/docs/PRs/22594/coverage/combined)
- [`contact`](https://mooseframework.inl.gov/docs/PRs/22594/coverage/contact)
- [`electromagnetics`](https://mooseframework.inl.gov/docs/PRs/22594/coverage/electromagnetics)
- [`external_petsc_solver`](https://mooseframework.inl.gov/docs/PRs/22594/coverage/external_petsc_solver)
- [`fluid_properties`](https://mooseframework.inl.gov/docs/PRs/22594/coverage/fluid_properties)
- [`fsi`](https://mooseframework.inl.gov/docs/PRs/22594/coverage/fsi)
- [`functional_expansion_tools`](https://mooseframework.inl.gov/docs/PRs/22594/coverage/functional_expansion_tools)
- [`geochemistry`](https://mooseframework.inl.gov/docs/PRs/22594/coverage/geochemistry)
- [`heat_conduction`](https://mooseframework.inl.gov/docs/PRs/22594/coverage/heat_conduction)
- [`level_set`](https://mooseframework.inl.gov/docs/PRs/22594/coverage/level_set)
- [`misc`](https://mooseframework.inl.gov/docs/PRs/22594/coverage/misc)
- [`navier_stokes`](https://mooseframework.inl.gov/docs/PRs/22594/coverage/navier_stokes)
- [`peridynamics`](https://mooseframework.inl.gov/docs/PRs/22594/coverage/peridynamics)
- [`phase_field`](https://mooseframework.inl.gov/docs/PRs/22594/coverage/phase_field)
- [`porous_flow`](https://mooseframework.inl.gov/docs/PRs/22594/coverage/porous_flow)
- [`ray_tracing`](https://mooseframework.inl.gov/docs/PRs/22594/coverage/ray_tracing)
- [`rdg`](https://mooseframework.inl.gov/docs/PRs/22594/coverage/rdg)
- [`reactor`](https://mooseframework.inl.gov/docs/PRs/22594/coverage/reactor)
- [`richards`](https://mooseframework.inl.gov/docs/PRs/22594/coverage/richards)
- [`scalar_transport`](https://mooseframework.inl.gov/docs/PRs/22594/coverage/scalar_transport)
- [`solid_properties`](https://mooseframework.inl.gov/docs/PRs/22594/coverage/solid_properties)
- [`stochastic_tools`](https://mooseframework.inl.gov/docs/PRs/22594/coverage/stochastic_tools)
- [`tensor_mechanics`](https://mooseframework.inl.gov/docs/PRs/22594/coverage/tensor_mechanics)
- [`thermal_hydraulics`](https://mooseframework.inl.gov/docs/PRs/22594/coverage/thermal_hydraulics)
- [`xfem`](https://mooseframework.inl.gov/docs/PRs/22594/coverage/xfem)

</details>



This comment will be updated on new commits.

2022-11-08 18:05 UTC, GiudGiud requested changes
the image needs to live in large_media 

the exodus output in the test files arent needed

2022-11-08 18:05 UTC, GiudGiud commented on test/tests/meshgenerators/sphere_mesh_generator/smooth.i
> +[]
```suggestion
```

2022-11-08 18:05 UTC, GiudGiud commented on test/tests/meshgenerators/sphere_mesh_generator/sphere.i
> +[]
```suggestion
```

2022-11-08 18:05 UTC, GiudGiud commented on test/tests/meshgenerators/sphere_mesh_generator/sphere_hex27.i
> +[]
```suggestion
```

2022-11-09 02:07 UTC, aprilnovak commented
Does large_media use git lfs? Or do I just commit the png image there?

2022-11-09 02:23 UTC, GiudGiud commented
no it s just regular git.
you just add a commit on top of master and push

2022-11-09 15:32 UTC, GiudGiud submitted a review, later dismissed

2022-11-09 16:28 UTC, moosebuild commented on large_media
> +Subproject commit 889a6e9e9bf06bdbe39220a528fc8f905b9c06df
**Caution!** This contains a submodule update

2022-11-09 16:51 UTC, GiudGiud approved these changes

2022-11-09 18:33 UTC, merged

2022-11-09 18:34 UTC, GiudGiud commented
it is
thanks for the PR!
are you going to be meshing around the spheres in MOOSE or is this for fuel sims?

2022-11-09 18:34 UTC, moosebuild commented
Job [Coverage](https://civet.inl.gov/job/1229546/) on 7175b15 wanted to post the following:


The following coverage requirement(s) failed:
- Failed to generate `tensor_mechanics` coverage rate (required: 86.0%)
- Failed to generate `thermal_hydraulics` coverage rate (required: 90.0%)
- Failed to generate `xfem` coverage rate (required: 80.0%)

2022-11-09 18:42 UTC, aprilnovak commented
This is for heat conduction cases in pebble beds. We have some mesh scripts at ANL to do the fluid space, but it's  much more challenging. We could potentially convert those to MOOSE functionalities, but I'd need to check with the authors.