Fix initializtion bug (#000)
idaholab/moose pull request #22634
Opened 2022-11-08 23:15 UTC by dschwen

## Reason
The performance test option in `hit` has a small initialization bug.

## Design
Properly initialize the loop counter to zero.

## Impact
Fix initialization

2022-11-09 01:22 UTC, moosebuild commented
Job [Coverage](https://civet.inl.gov/job/1228471/) on bc116e0 wanted to post the following:


## Framework coverage

<table>
  <thead>
    <tr>
      <th></th>
      <th>5ed496</th>
      <th colspan=4>#22634 bc116e</th>
    </tr>
    <tr>
      <th></th>
      <th>Total</th>
      <th>Total</th>
      <th>+/-</th>
      <th>New</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><b>Rate</b></td>
      <td>84.36%</td>
      <td>84.36%</td>
      <td>-0.00%</td>
      <td>-</td>
    </tr>
    <tr>
      <td><b>Hits</b></td>
      <td>80679</td>
      <td>80678</td>
      <td>-1</td>
      <td>0</td>
    </tr>
    <tr>
      <td><b>Misses</b></td>
      <td>14953</td>
      <td>14954</td>
      <td>+1</td>
      <td>0</td>
    </tr>
  </tbody>
</table>

[Diff coverage report](https://mooseframework.inl.gov/docs/PRs/22634/coverage_diff/framework)

[Full coverage report](https://mooseframework.inl.gov/docs/PRs/22634/coverage/framework)


## Modules coverage

Coverage did not change

## Full coverage reports

<details>
<summary>Reports</summary>

- [`framework`](https://mooseframework.inl.gov/docs/PRs/22634/coverage/framework)
- [`chemical_reactions`](https://mooseframework.inl.gov/docs/PRs/22634/coverage/chemical_reactions)
- [`combined`](https://mooseframework.inl.gov/docs/PRs/22634/coverage/combined)
- [`contact`](https://mooseframework.inl.gov/docs/PRs/22634/coverage/contact)
- [`electromagnetics`](https://mooseframework.inl.gov/docs/PRs/22634/coverage/electromagnetics)
- [`external_petsc_solver`](https://mooseframework.inl.gov/docs/PRs/22634/coverage/external_petsc_solver)
- [`fluid_properties`](https://mooseframework.inl.gov/docs/PRs/22634/coverage/fluid_properties)
- [`fsi`](https://mooseframework.inl.gov/docs/PRs/22634/coverage/fsi)
- [`functional_expansion_tools`](https://mooseframework.inl.gov/docs/PRs/22634/coverage/functional_expansion_tools)
- [`geochemistry`](https://mooseframework.inl.gov/docs/PRs/22634/coverage/geochemistry)
- [`heat_conduction`](https://mooseframework.inl.gov/docs/PRs/22634/coverage/heat_conduction)
- [`level_set`](https://mooseframework.inl.gov/docs/PRs/22634/coverage/level_set)
- [`misc`](https://mooseframework.inl.gov/docs/PRs/22634/coverage/misc)
- [`navier_stokes`](https://mooseframework.inl.gov/docs/PRs/22634/coverage/navier_stokes)
- [`peridynamics`](https://mooseframework.inl.gov/docs/PRs/22634/coverage/peridynamics)
- [`phase_field`](https://mooseframework.inl.gov/docs/PRs/22634/coverage/phase_field)
- [`porous_flow`](https://mooseframework.inl.gov/docs/PRs/22634/coverage/porous_flow)
- [`ray_tracing`](https://mooseframework.inl.gov/docs/PRs/22634/coverage/ray_tracing)
- [`rdg`](https://mooseframework.inl.gov/docs/PRs/22634/coverage/rdg)
- [`reactor`](https://mooseframework.inl.gov/docs/PRs/22634/coverage/reactor)
- [`richards`](https://mooseframework.inl.gov/docs/PRs/22634/coverage/richards)
- [`scalar_transport`](https://mooseframework.inl.gov/docs/PRs/22634/coverage/scalar_transport)
- [`solid_properties`](https://mooseframework.inl.gov/docs/PRs/22634/coverage/solid_properties)
- [`stochastic_tools`](https://mooseframework.inl.gov/docs/PRs/22634/coverage/stochastic_tools)
- [`tensor_mechanics`](https://mooseframework.inl.gov/docs/PRs/22634/coverage/tensor_mechanics)
- [`thermal_hydraulics`](https://mooseframework.inl.gov/docs/PRs/22634/coverage/thermal_hydraulics)
- [`xfem`](https://mooseframework.inl.gov/docs/PRs/22634/coverage/xfem)

</details>



This comment will be updated on new commits.

2022-11-09 03:10 UTC, loganharbour requested changes
actual issue? :-)

2022-11-11 23:02 UTC, dschwen commented
> actual issue? :-)

What does that mean, and what are the requested changes? Just to be clear, the SQA template does not require an issue to be opened for a PR, as long as the Reason/Design/Impact is in the PR. And this is a super obvious single character change...

2022-11-12 19:31 UTC, loganharbour approved these changes

2022-11-12 21:29 UTC, merged