Fix error checks for passive scalar inlet in NSFVAction
idaholab/moose pull request #22775
Opened 2022-11-22 16:57 UTC by grmnptr

Closes #22774

2022-11-22 17:01 UTC, GiudGiud approved these changes

2022-11-22 18:24 UTC, moosebuild commented
Job [Documentation](https://civet.inl.gov/job/1241289/) on ea1acf0 wanted to post the following:

View the site [here](https://mooseframework.inl.gov/docs/PRs/22775/site)

This comment will be updated on new commits.

2022-11-22 19:34 UTC, GiudGiud requested changes
test needs update, currently:
```
navier_stokes/test:finite_volume/ins/action/errors.passive-scalar-inlet-function-error: Size \(0\) is not the same as the number of boundaries in 'passive_scalar_inlet_types' \(size 1\)
```

2022-11-22 20:29 UTC, grmnptr commented
Oh yes, I am on it. Just needed to take care of a few things. The change will come in a few mins.

2022-11-22 23:24 UTC, moosebuild commented
Job [Coverage](https://civet.inl.gov/job/1241880/) on 6d8d4d3 wanted to post the following:


## Framework coverage

<table>
  <thead>
    <tr>
      <th></th>
      <th>9cd58a</th>
      <th colspan=4>#22775 6d8d4d</th>
    </tr>
    <tr>
      <th></th>
      <th>Total</th>
      <th>Total</th>
      <th>+/-</th>
      <th>New</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><b>Rate</b></td>
      <td>84.39%</td>
      <td>84.39%</td>
      <td>-0.01%</td>
      <td>-</td>
    </tr>
    <tr>
      <td><b>Hits</b></td>
      <td>80652</td>
      <td>80647</td>
      <td>-5</td>
      <td>0</td>
    </tr>
    <tr>
      <td><b>Misses</b></td>
      <td>14913</td>
      <td>14918</td>
      <td>+5</td>
      <td>0</td>
    </tr>
  </tbody>
</table>

[Diff coverage report](https://mooseframework.inl.gov/docs/PRs/22775/coverage_diff/framework)

[Full coverage report](https://mooseframework.inl.gov/docs/PRs/22775/coverage/framework)


## Modules coverage

### Navier stokes

<table>
  <thead>
    <tr>
      <th></th>
      <th>9cd58a</th>
      <th colspan=4>#22775 6d8d4d</th>
    </tr>
    <tr>
      <th></th>
      <th>Total</th>
      <th>Total</th>
      <th>+/-</th>
      <th>New</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><b>Rate</b></td>
      <td>85.55%</td>
      <td>85.56%</td>
      <td>+0.01%</td>
      <td>100.00%</td>
    </tr>
    <tr>
      <td><b>Hits</b></td>
      <td>9775</td>
      <td>9780</td>
      <td>+5</td>
      <td>6</td>
    </tr>
    <tr>
      <td><b>Misses</b></td>
      <td>1651</td>
      <td>1651</td>
      <td>-</td>
      <td>0</td>
    </tr>
  </tbody>
</table>

[Diff coverage report](https://mooseframework.inl.gov/docs/PRs/22775/coverage_diff/navier_stokes)

[Full coverage report](https://mooseframework.inl.gov/docs/PRs/22775/coverage/navier_stokes)

## Full coverage reports

<details>
<summary>Reports</summary>

- [`framework`](https://mooseframework.inl.gov/docs/PRs/22775/coverage/framework)
- [`chemical_reactions`](https://mooseframework.inl.gov/docs/PRs/22775/coverage/chemical_reactions)
- [`combined`](https://mooseframework.inl.gov/docs/PRs/22775/coverage/combined)
- [`contact`](https://mooseframework.inl.gov/docs/PRs/22775/coverage/contact)
- [`electromagnetics`](https://mooseframework.inl.gov/docs/PRs/22775/coverage/electromagnetics)
- [`external_petsc_solver`](https://mooseframework.inl.gov/docs/PRs/22775/coverage/external_petsc_solver)
- [`fluid_properties`](https://mooseframework.inl.gov/docs/PRs/22775/coverage/fluid_properties)
- [`fsi`](https://mooseframework.inl.gov/docs/PRs/22775/coverage/fsi)
- [`functional_expansion_tools`](https://mooseframework.inl.gov/docs/PRs/22775/coverage/functional_expansion_tools)
- [`geochemistry`](https://mooseframework.inl.gov/docs/PRs/22775/coverage/geochemistry)
- [`heat_conduction`](https://mooseframework.inl.gov/docs/PRs/22775/coverage/heat_conduction)
- [`level_set`](https://mooseframework.inl.gov/docs/PRs/22775/coverage/level_set)
- [`misc`](https://mooseframework.inl.gov/docs/PRs/22775/coverage/misc)
- [`navier_stokes`](https://mooseframework.inl.gov/docs/PRs/22775/coverage/navier_stokes)
- [`peridynamics`](https://mooseframework.inl.gov/docs/PRs/22775/coverage/peridynamics)
- [`phase_field`](https://mooseframework.inl.gov/docs/PRs/22775/coverage/phase_field)
- [`porous_flow`](https://mooseframework.inl.gov/docs/PRs/22775/coverage/porous_flow)
- [`ray_tracing`](https://mooseframework.inl.gov/docs/PRs/22775/coverage/ray_tracing)
- [`rdg`](https://mooseframework.inl.gov/docs/PRs/22775/coverage/rdg)
- [`reactor`](https://mooseframework.inl.gov/docs/PRs/22775/coverage/reactor)
- [`richards`](https://mooseframework.inl.gov/docs/PRs/22775/coverage/richards)
- [`scalar_transport`](https://mooseframework.inl.gov/docs/PRs/22775/coverage/scalar_transport)
- [`solid_properties`](https://mooseframework.inl.gov/docs/PRs/22775/coverage/solid_properties)
- [`stochastic_tools`](https://mooseframework.inl.gov/docs/PRs/22775/coverage/stochastic_tools)
- [`tensor_mechanics`](https://mooseframework.inl.gov/docs/PRs/22775/coverage/tensor_mechanics)
- [`thermal_hydraulics`](https://mooseframework.inl.gov/docs/PRs/22775/coverage/thermal_hydraulics)
- [`xfem`](https://mooseframework.inl.gov/docs/PRs/22775/coverage/xfem)

</details>



This comment will be updated on new commits.

2022-11-22 23:34 UTC, GiudGiud commented on modules/navier_stokes/test/tests/finite_volume/ins/action/errors/tests
> +    requirement = 'The system shall throw an error if the number of passive scalar inlet functions does not match the number of inlet boundaries.'
duplicate of the one above

2022-11-23 12:48 UTC, GiudGiud approved these changes

2022-11-23 19:19 UTC, merged

2022-11-23 19:19 UTC, grmnptr commented
Thanks @GiudGiud for paying a close attention to this!