More docs on VPPs and reporters
idaholab/moose pull request #22790
Opened 2022-11-25 05:09 UTC by GiudGiud

refs #22662

2022-11-25 07:25 UTC, moosebuild commented
Job [Documentation](https://civet.inl.gov/job/1244718/) on ed36afa wanted to post the following:

View the site [here](https://mooseframework.inl.gov/docs/PRs/22790/site)

This comment will be updated on new commits.

2022-11-25 08:17 UTC, moosebuild commented
Job [Coverage](https://civet.inl.gov/job/1244752/) on ed36afa wanted to post the following:


## Framework coverage

<table>
  <thead>
    <tr>
      <th></th>
      <th>6b6bc5</th>
      <th colspan=4>#22790 ed36af</th>
    </tr>
    <tr>
      <th></th>
      <th>Total</th>
      <th>Total</th>
      <th>+/-</th>
      <th>New</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><b>Rate</b></td>
      <td>84.39%</td>
      <td>84.39%</td>
      <td>+0.00%</td>
      <td>100.00%</td>
    </tr>
    <tr>
      <td><b>Hits</b></td>
      <td>80650</td>
      <td>80629</td>
      <td>-21</td>
      <td>2</td>
    </tr>
    <tr>
      <td><b>Misses</b></td>
      <td>14920</td>
      <td>14915</td>
      <td>-5</td>
      <td>0</td>
    </tr>
  </tbody>
</table>

[Diff coverage report](https://mooseframework.inl.gov/docs/PRs/22790/coverage_diff/framework)

[Full coverage report](https://mooseframework.inl.gov/docs/PRs/22790/coverage/framework)


## Modules coverage

Coverage did not change

## Full coverage reports

<details>
<summary>Reports</summary>

- [`framework`](https://mooseframework.inl.gov/docs/PRs/22790/coverage/framework)
- [`chemical_reactions`](https://mooseframework.inl.gov/docs/PRs/22790/coverage/chemical_reactions)
- [`combined`](https://mooseframework.inl.gov/docs/PRs/22790/coverage/combined)
- [`contact`](https://mooseframework.inl.gov/docs/PRs/22790/coverage/contact)
- [`electromagnetics`](https://mooseframework.inl.gov/docs/PRs/22790/coverage/electromagnetics)
- [`external_petsc_solver`](https://mooseframework.inl.gov/docs/PRs/22790/coverage/external_petsc_solver)
- [`fluid_properties`](https://mooseframework.inl.gov/docs/PRs/22790/coverage/fluid_properties)
- [`fsi`](https://mooseframework.inl.gov/docs/PRs/22790/coverage/fsi)
- [`functional_expansion_tools`](https://mooseframework.inl.gov/docs/PRs/22790/coverage/functional_expansion_tools)
- [`geochemistry`](https://mooseframework.inl.gov/docs/PRs/22790/coverage/geochemistry)
- [`heat_conduction`](https://mooseframework.inl.gov/docs/PRs/22790/coverage/heat_conduction)
- [`level_set`](https://mooseframework.inl.gov/docs/PRs/22790/coverage/level_set)
- [`misc`](https://mooseframework.inl.gov/docs/PRs/22790/coverage/misc)
- [`navier_stokes`](https://mooseframework.inl.gov/docs/PRs/22790/coverage/navier_stokes)
- [`peridynamics`](https://mooseframework.inl.gov/docs/PRs/22790/coverage/peridynamics)
- [`phase_field`](https://mooseframework.inl.gov/docs/PRs/22790/coverage/phase_field)
- [`porous_flow`](https://mooseframework.inl.gov/docs/PRs/22790/coverage/porous_flow)
- [`ray_tracing`](https://mooseframework.inl.gov/docs/PRs/22790/coverage/ray_tracing)
- [`rdg`](https://mooseframework.inl.gov/docs/PRs/22790/coverage/rdg)
- [`reactor`](https://mooseframework.inl.gov/docs/PRs/22790/coverage/reactor)
- [`richards`](https://mooseframework.inl.gov/docs/PRs/22790/coverage/richards)
- [`scalar_transport`](https://mooseframework.inl.gov/docs/PRs/22790/coverage/scalar_transport)
- [`solid_properties`](https://mooseframework.inl.gov/docs/PRs/22790/coverage/solid_properties)
- [`stochastic_tools`](https://mooseframework.inl.gov/docs/PRs/22790/coverage/stochastic_tools)
- [`tensor_mechanics`](https://mooseframework.inl.gov/docs/PRs/22790/coverage/tensor_mechanics)
- [`thermal_hydraulics`](https://mooseframework.inl.gov/docs/PRs/22790/coverage/thermal_hydraulics)
- [`xfem`](https://mooseframework.inl.gov/docs/PRs/22790/coverage/xfem)

</details>



This comment will be updated on new commits.

2022-11-28 16:10 UTC, cticenhour commented
@GiudGiud I see you added another commit after your review request - is this ready to go now?

2022-11-28 16:13 UTC, GiudGiud commented
ah yes. I was going to make a separate PR for fixups but did not find the time to add more so it's just this solo commit

2022-11-28 22:07 UTC, cticenhour requested changes
Thanks for the clean-up and adjustments here! A few suggestions and corrections to note.

2022-11-28 22:07 UTC, cticenhour commented on framework/doc/content/source/vectorpostprocessors/NodalValueSampler.md
> +and a vector named after each variable sampled, containing the variable values at each point.
```suggestion
`NodalValueSampler` declares a vector for each spatial coordinate, (`x`, `y`, `z`), of the sampled nodes,
the IDs of the nodes in a vector named `id`,
and a vector named after each variable sampled, containing the variable values at each point.
```

2022-11-28 22:07 UTC, cticenhour commented on framework/doc/content/source/vectorpostprocessors/PointValueSampler.md
> +The CSV output, with rows for each sampled point, contains the columns listed below. The vectors declared by the `PointValueSampler`
```suggestion
The CSV output, with rows for each sampled point, contains the columns listed below. The vectors declared by `PointValueSampler`
```

2022-11-28 22:07 UTC, cticenhour commented on framework/doc/content/source/vectorpostprocessors/SideValueSampler.md
>  - the id of the element the quadrature point, on the side, belongs to
```suggestion
- the id of the element that the quadrature point, on the side, belongs to
```

Adjusting this while we're here

2022-11-28 22:07 UTC, cticenhour commented on framework/doc/content/source/vectorpostprocessors/SideValueSampler.md
> +- the values of the requested variables, with a column named after the variable
```suggestion
- the values of the requested variables, with a column named after each variable
```

2022-11-28 22:07 UTC, cticenhour commented on framework/doc/content/source/vectorpostprocessors/SidesetInfoVectorPostprocessor.md
> +The `SidesetInfoVectorPostprocessor` uses the following names for the vectors / CSV column headers
```suggestion
`SidesetInfoVectorPostprocessor` uses the following names for the vectors / CSV column headers: 
```

2022-11-28 22:07 UTC, cticenhour commented on framework/doc/content/source/vectorpostprocessors/SpatialUserObjectVectorPostprocessor.md
> +The `SpatialUserObjectVectorPostprocessor` declares a vector with its own name. The full reporter name ends up being `<vpp_object_name>/<vpp_object_name>`.
```suggestion
`SpatialUserObjectVectorPostprocessor` declares a vector with its own name. The full reporter name ends up being `<vpp_object_name>/<vpp_object_name>`.
```

2022-11-28 22:07 UTC, cticenhour commented on framework/doc/content/source/vectorpostprocessors/SphericalAverage.md
> +The `SphericalAverage` declares a vector for the average shell radii, named `radius` and a vector for each variable requested, named with the variable name.
```suggestion
`SphericalAverage` declares a vector for the average shell radii, named `radius`, and a vector for each variable requested, named with the variable name.
```

2022-11-28 22:07 UTC, cticenhour commented on framework/doc/content/source/vectorpostprocessors/VariableValueVolumeHistogram.md
> +The names of the vectors declared by the `VariableValueVolumeHistogram` match the CSV output column header names.
```suggestion
The names of the vectors declared by `VariableValueVolumeHistogram` match the CSV output column header names.
```

2022-11-28 22:07 UTC, cticenhour commented on framework/doc/content/source/vectorpostprocessors/VectorOfPostprocessors.md
> +The `VectorOfPostprocessors` declares a vector with its own name. The full reporter name ends up being `<vpp_object_name>/<vpp_object_name>`.
```suggestion
`VectorOfPostprocessors` declares a vector with its own name. The full reporter name ends up being `<vpp_object_name>/<vpp_object_name>`.
```

2022-11-28 22:07 UTC, cticenhour commented on framework/doc/content/source/vectorpostprocessors/WorkBalance.md
> +The names of the vectors declared by the `WorkBalance` are the names of [!param](/VectorPostprocessors/WorkBalance/balances) requested.
```suggestion
The names of the vectors declared by `WorkBalance` are the names of the [!param](/VectorPostprocessors/WorkBalance/balances) requested.
```

2022-11-28 22:41 UTC, GiudGiud commented
applied all suggested changes!
had to squash the two commits I did for that

2022-11-28 22:53 UTC, cticenhour approved these changes

2022-11-29 01:48 UTC, merged