Add ArrayVarReductionAux
idaholab/moose pull request #22822
Opened 2022-11-30 02:54 UTC by snschune

closes #22809 

## Reason

Compute min/max/sum/average of array variables and store it in standard field variable.

## Design

AuxKernel

## Impact

None.

2022-11-30 03:01 UTC, snschune commented
@YaqiWang fyi

2022-11-30 04:24 UTC, moosebuild commented
Job [Documentation](https://civet.inl.gov/job/1248810/) on f191ff5 wanted to post the following:

View the site [here](https://mooseframework.inl.gov/docs/PRs/22822/site)

This comment will be updated on new commits.

2022-11-30 05:09 UTC, moosebuild commented
Job [Coverage](https://civet.inl.gov/job/1248844/) on f191ff5 wanted to post the following:


## Framework coverage

<table>
  <thead>
    <tr>
      <th></th>
      <th>08e161</th>
      <th colspan=4>#22822 f191ff</th>
    </tr>
    <tr>
      <th></th>
      <th>Total</th>
      <th>Total</th>
      <th>+/-</th>
      <th>New</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><b>Rate</b></td>
      <td>84.40%</td>
      <td>84.40%</td>
      <td>+0.00%</td>
      <td>100.00%</td>
    </tr>
    <tr>
      <td><b>Hits</b></td>
      <td>80682</td>
      <td>80716</td>
      <td>+34</td>
      <td>38</td>
    </tr>
    <tr>
      <td><b>Misses</b></td>
      <td>14914</td>
      <td>14918</td>
      <td>+4</td>
      <td>0</td>
    </tr>
  </tbody>
</table>

[Diff coverage report](https://mooseframework.inl.gov/docs/PRs/22822/coverage_diff/framework)

[Full coverage report](https://mooseframework.inl.gov/docs/PRs/22822/coverage/framework)


## Modules coverage

Coverage did not change

## Full coverage reports

<details>
<summary>Reports</summary>

- [`framework`](https://mooseframework.inl.gov/docs/PRs/22822/coverage/framework)
- [`chemical_reactions`](https://mooseframework.inl.gov/docs/PRs/22822/coverage/chemical_reactions)
- [`combined`](https://mooseframework.inl.gov/docs/PRs/22822/coverage/combined)
- [`contact`](https://mooseframework.inl.gov/docs/PRs/22822/coverage/contact)
- [`electromagnetics`](https://mooseframework.inl.gov/docs/PRs/22822/coverage/electromagnetics)
- [`external_petsc_solver`](https://mooseframework.inl.gov/docs/PRs/22822/coverage/external_petsc_solver)
- [`fluid_properties`](https://mooseframework.inl.gov/docs/PRs/22822/coverage/fluid_properties)
- [`fsi`](https://mooseframework.inl.gov/docs/PRs/22822/coverage/fsi)
- [`functional_expansion_tools`](https://mooseframework.inl.gov/docs/PRs/22822/coverage/functional_expansion_tools)
- [`geochemistry`](https://mooseframework.inl.gov/docs/PRs/22822/coverage/geochemistry)
- [`heat_conduction`](https://mooseframework.inl.gov/docs/PRs/22822/coverage/heat_conduction)
- [`level_set`](https://mooseframework.inl.gov/docs/PRs/22822/coverage/level_set)
- [`misc`](https://mooseframework.inl.gov/docs/PRs/22822/coverage/misc)
- [`navier_stokes`](https://mooseframework.inl.gov/docs/PRs/22822/coverage/navier_stokes)
- [`peridynamics`](https://mooseframework.inl.gov/docs/PRs/22822/coverage/peridynamics)
- [`phase_field`](https://mooseframework.inl.gov/docs/PRs/22822/coverage/phase_field)
- [`porous_flow`](https://mooseframework.inl.gov/docs/PRs/22822/coverage/porous_flow)
- [`ray_tracing`](https://mooseframework.inl.gov/docs/PRs/22822/coverage/ray_tracing)
- [`rdg`](https://mooseframework.inl.gov/docs/PRs/22822/coverage/rdg)
- [`reactor`](https://mooseframework.inl.gov/docs/PRs/22822/coverage/reactor)
- [`richards`](https://mooseframework.inl.gov/docs/PRs/22822/coverage/richards)
- [`scalar_transport`](https://mooseframework.inl.gov/docs/PRs/22822/coverage/scalar_transport)
- [`solid_properties`](https://mooseframework.inl.gov/docs/PRs/22822/coverage/solid_properties)
- [`stochastic_tools`](https://mooseframework.inl.gov/docs/PRs/22822/coverage/stochastic_tools)
- [`tensor_mechanics`](https://mooseframework.inl.gov/docs/PRs/22822/coverage/tensor_mechanics)
- [`thermal_hydraulics`](https://mooseframework.inl.gov/docs/PRs/22822/coverage/thermal_hydraulics)
- [`xfem`](https://mooseframework.inl.gov/docs/PRs/22822/coverage/xfem)

</details>



This comment will be updated on new commits.

2022-11-30 16:22 UTC, YaqiWang commented
The failure does not seem related. @lindsayad can you find someone review this PR?

2022-11-30 17:20 UTC, zachmprince requested changes
Suggestion for less code.

2022-11-30 17:20 UTC, zachmprince commented on framework/src/auxkernels/ArrayVarReductionAux.C
> +  return r;
```suggestion
  switch (_value_type)
  {
    case 0:
      return _array_variable[_qp].maxCoeff();

    case 1:
      return _array_variable[_qp].minCoeff();

    case 2:
      return _array_variable[_qp].sum();

    case 3:
      return _array_variable[_qp].mean();
  }
  
  return 0.0;
```

2022-11-30 17:20 UTC, zachmprince commented on framework/src/auxkernels/ArrayVarReductionAux.C
> +    _nentries(getArrayVar("array_variable", 0)->count()),
This member isn't necessary with my suggestion.

2022-11-30 19:57 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/1249860/) on 561903c wanted to post the following:

Your code requires style changes.  

A patch was auto generated and copied [here](https://mooseframework.inl.gov/docs/PRs/22822/clang_format/style.patch)  
You can directly apply the patch by running, in the top level of your repository:

`curl -s https://mooseframework.inl.gov/docs/PRs/22822/clang_format/style.patch | git apply -v`  

Alternatively, with your repository up to date and in the top level of your repository:

`git clang-format 2ba7c6a3d54ba1733a666a49e926b71e830b1a11`

2022-11-30 21:06 UTC, lindsayad requested changes
looks good!

2022-11-30 21:06 UTC, lindsayad commented on framework/include/auxkernels/ArrayVarReductionAux.h
> +  virtual Real computeValue();
```suggestion
  Real computeValue() override;
```

2022-11-30 21:06 UTC, lindsayad commented on framework/include/auxkernels/ArrayVarReductionAux.h
> +  /// variable for storing the array variable that needs to be processed
```suggestion
  /// the array variable value we will perform the reduction on
```

2022-11-30 21:06 UTC, lindsayad commented on test/tests/auxkernels/array_var_reduction/array_var_reduction.i
> +
```suggestion
  [min_var][]
  [max_var][]
  [sum_var][]
  [average_var][]
```

2022-11-30 22:09 UTC, lindsayad approved these changes

2022-12-01 15:09 UTC, zachmprince approved these changes

2022-12-01 16:13 UTC, merged