Generalize homogenized thermal conductivity
idaholab/moose pull request #22927
Opened 2022-12-09 00:42 UTC by snschune

## Reason

To compute homogenized thermal conductivities in non-square lattices,
we need to compute off-diagonal thermal conductivity components.
The current homogenization object do not support that.

In addition, the documentation needed some clarification and fixing
of a sign error. 

Finally, I want to make the homogenization work with anisotropic input
thermal conductivities.

## Design

Refactor `HomogenizedThermalConductivity` and clean up its input parameters.
Add anisotropic object for  `HomogenizedHeatConduction` (not complete yet).

## Impact

Some changes to input parameters. I think it's actually clearer now.

closes #22919

2022-12-09 02:50 UTC, moosebuild commented
Job [Coverage](https://civet.inl.gov/job/1260956/) on 8a53460 wanted to post the following:


## Framework coverage

<table>
  <thead>
    <tr>
      <th></th>
      <th>fd40fe</th>
      <th colspan=4>#22927 8a5346</th>
    </tr>
    <tr>
      <th></th>
      <th>Total</th>
      <th>Total</th>
      <th>+/-</th>
      <th>New</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><b>Rate</b></td>
      <td>84.50%</td>
      <td>84.50%</td>
      <td>-0.00%</td>
      <td>-</td>
    </tr>
    <tr>
      <td><b>Hits</b></td>
      <td>81145</td>
      <td>81143</td>
      <td>-2</td>
      <td>0</td>
    </tr>
    <tr>
      <td><b>Misses</b></td>
      <td>14887</td>
      <td>14889</td>
      <td>+2</td>
      <td>0</td>
    </tr>
  </tbody>
</table>

[Diff coverage report](https://mooseframework.inl.gov/docs/PRs/22927/coverage_diff/framework)

[Full coverage report](https://mooseframework.inl.gov/docs/PRs/22927/coverage/framework)


## Modules coverage

### Heat conduction

<table>
  <thead>
    <tr>
      <th></th>
      <th>fd40fe</th>
      <th colspan=4>#22927 8a5346</th>
    </tr>
    <tr>
      <th></th>
      <th>Total</th>
      <th>Total</th>
      <th>+/-</th>
      <th>New</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><b>Rate</b></td>
      <td>89.68%</td>
      <td>89.68%</td>
      <td>+0.00%</td>
      <td>83.33%</td>
    </tr>
    <tr>
      <td><b>Hits</b></td>
      <td>3370</td>
      <td>3380</td>
      <td>+10</td>
      <td>30</td>
    </tr>
    <tr>
      <td><b>Misses</b></td>
      <td>388</td>
      <td>389</td>
      <td>+1</td>
      <td>6</td>
    </tr>
  </tbody>
</table>

[Diff coverage report](https://mooseframework.inl.gov/docs/PRs/22927/coverage_diff/heat_conduction)

[Full coverage report](https://mooseframework.inl.gov/docs/PRs/22927/coverage/heat_conduction)

## Full coverage reports

<details>
<summary>Reports</summary>

- [`framework`](https://mooseframework.inl.gov/docs/PRs/22927/coverage/framework)
- [`chemical_reactions`](https://mooseframework.inl.gov/docs/PRs/22927/coverage/chemical_reactions)
- [`combined`](https://mooseframework.inl.gov/docs/PRs/22927/coverage/combined)
- [`contact`](https://mooseframework.inl.gov/docs/PRs/22927/coverage/contact)
- [`electromagnetics`](https://mooseframework.inl.gov/docs/PRs/22927/coverage/electromagnetics)
- [`external_petsc_solver`](https://mooseframework.inl.gov/docs/PRs/22927/coverage/external_petsc_solver)
- [`fluid_properties`](https://mooseframework.inl.gov/docs/PRs/22927/coverage/fluid_properties)
- [`fsi`](https://mooseframework.inl.gov/docs/PRs/22927/coverage/fsi)
- [`functional_expansion_tools`](https://mooseframework.inl.gov/docs/PRs/22927/coverage/functional_expansion_tools)
- [`geochemistry`](https://mooseframework.inl.gov/docs/PRs/22927/coverage/geochemistry)
- [`heat_conduction`](https://mooseframework.inl.gov/docs/PRs/22927/coverage/heat_conduction)
- [`level_set`](https://mooseframework.inl.gov/docs/PRs/22927/coverage/level_set)
- [`misc`](https://mooseframework.inl.gov/docs/PRs/22927/coverage/misc)
- [`navier_stokes`](https://mooseframework.inl.gov/docs/PRs/22927/coverage/navier_stokes)
- [`peridynamics`](https://mooseframework.inl.gov/docs/PRs/22927/coverage/peridynamics)
- [`phase_field`](https://mooseframework.inl.gov/docs/PRs/22927/coverage/phase_field)
- [`porous_flow`](https://mooseframework.inl.gov/docs/PRs/22927/coverage/porous_flow)
- [`ray_tracing`](https://mooseframework.inl.gov/docs/PRs/22927/coverage/ray_tracing)
- [`rdg`](https://mooseframework.inl.gov/docs/PRs/22927/coverage/rdg)
- [`reactor`](https://mooseframework.inl.gov/docs/PRs/22927/coverage/reactor)
- [`richards`](https://mooseframework.inl.gov/docs/PRs/22927/coverage/richards)
- [`scalar_transport`](https://mooseframework.inl.gov/docs/PRs/22927/coverage/scalar_transport)
- [`solid_properties`](https://mooseframework.inl.gov/docs/PRs/22927/coverage/solid_properties)
- [`stochastic_tools`](https://mooseframework.inl.gov/docs/PRs/22927/coverage/stochastic_tools)
- [`tensor_mechanics`](https://mooseframework.inl.gov/docs/PRs/22927/coverage/tensor_mechanics)
- [`thermal_hydraulics`](https://mooseframework.inl.gov/docs/PRs/22927/coverage/thermal_hydraulics)
- [`xfem`](https://mooseframework.inl.gov/docs/PRs/22927/coverage/xfem)

</details>

## Warnings

- `heat_conduction` new line coverage rate 83.33% is less than the suggested 90.0%



This comment will be updated on new commits.

2022-12-09 18:30 UTC, snschune commented
@grmnptr this is where I would like your help to check the math. It should be in the documentation + the code + the reference I added.

2022-12-13 21:29 UTC, moosebuild commented
Job [Internal app tests](https://civet.inl.gov/job/1261924/) on 774c256 : invalidated by @cticenhour

MALAMUTE patched

2022-12-19 21:03 UTC, grmnptr requested changes
Great work! Just a few questions/ideas.

2022-12-21 18:22 UTC, snschune commented on modules/heat_conduction/doc/content/source/kernels/AnisoHomogenizedHeatConduction.md
> +\int_Y \frac{\partial v}{\partial y_i}k_{ij} \frac{\partial \chi^k}{\partial y_j} = -\int_Y \frac{\partial v}{\partial y_i}k_{ik} \text{d}y
`k` is already in use for thermal conductivity. Should use `\lambda` for thermal conductivity instead.

2022-12-21 18:30 UTC, snschune commented on modules/heat_conduction/doc/content/source/postprocessors/HomogenizedThermalConductivity.md
> +MOOSE computes $-\chi^j$. This is achieved by inverting the sign of the right hand side of [eq:1]. This leads to an inversion of the sign in the parenthesis in [eq:0].
Could do that, but it is handled internally so it's not a big danger that users get that wrong.

2022-12-21 18:35 UTC, snschune commented on modules/heat_conduction/src/kernels/AnisoHomogenizedHeatConduction.C
> +  return d_times_ej * _grad_test[_i][_qp];
In the non-INL papers, the rhs is always negative. However, we are solving for `-chi`, so our rhs is positive. Then we multiply by a test function and "integrate by parts" which switches the sign (so it's negative then), and then we bring it over to the left hand side. So you have two sign changes and the above is correct.

2022-12-21 18:40 UTC, snschune commented on modules/heat_conduction/src/postprocessors/HomogenizedThermalConductivity.C
> +  if (_row >= _dim)
You can have off-diagonal diffusion coefficients if the heterogeneous coefficient is a scalar. That is for example the case in hexagonal geometries...i.e. where the principal axes are not e_x and e_y.

2022-12-21 19:32 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/1274364/) on cd39bd3 wanted to post the following:

Your code requires style changes.  

A patch was auto generated and copied [here](https://mooseframework.inl.gov/docs/PRs/22927/clang_format/style.patch)  
You can directly apply the patch by running, in the top level of your repository:

`curl -s https://mooseframework.inl.gov/docs/PRs/22927/clang_format/style.patch | git apply -v`  

Alternatively, with your repository up to date and in the top level of your repository:

`git clang-format af6972966d15adebd660174ea2dded977d12c3e5`

2022-12-21 20:04 UTC, moosebuild commented
Job [Test install](https://civet.inl.gov/job/1274459/) on 7735140 : invalidated by @snschune

2022-12-21 21:00 UTC, moosebuild commented
Job [Conda (Intel Mac)](https://civet.inl.gov/job/1274449/) on 7735140 : invalidated by @snschune

2022-12-23 22:30 UTC, grmnptr approved these changes
Great job!

2022-12-23 22:33 UTC, merged