Custom comparison
idaholab/moose pull request #22947
Opened 2022-12-12 18:54 UTC by socratesgorilla

Closes #22946

2022-12-12 23:21 UTC, moosebuild commented
Job [Coverage](https://civet.inl.gov/job/1265102/) on 210e9fc wanted to post the following:


## Framework coverage

<table>
  <thead>
    <tr>
      <th></th>
      <th>ab4a04</th>
      <th colspan=4>#22947 210e9f</th>
    </tr>
    <tr>
      <th></th>
      <th>Total</th>
      <th>Total</th>
      <th>+/-</th>
      <th>New</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><b>Rate</b></td>
      <td>84.50%</td>
      <td>84.50%</td>
      <td>-0.00%</td>
      <td>-</td>
    </tr>
    <tr>
      <td><b>Hits</b></td>
      <td>81149</td>
      <td>81148</td>
      <td>-1</td>
      <td>0</td>
    </tr>
    <tr>
      <td><b>Misses</b></td>
      <td>14885</td>
      <td>14886</td>
      <td>+1</td>
      <td>0</td>
    </tr>
  </tbody>
</table>

[Diff coverage report](https://mooseframework.inl.gov/docs/PRs/22947/coverage_diff/framework)

[Full coverage report](https://mooseframework.inl.gov/docs/PRs/22947/coverage/framework)


## Modules coverage

Coverage did not change

## Full coverage reports

<details>
<summary>Reports</summary>

- [`framework`](https://mooseframework.inl.gov/docs/PRs/22947/coverage/framework)
- [`chemical_reactions`](https://mooseframework.inl.gov/docs/PRs/22947/coverage/chemical_reactions)
- [`combined`](https://mooseframework.inl.gov/docs/PRs/22947/coverage/combined)
- [`contact`](https://mooseframework.inl.gov/docs/PRs/22947/coverage/contact)
- [`electromagnetics`](https://mooseframework.inl.gov/docs/PRs/22947/coverage/electromagnetics)
- [`external_petsc_solver`](https://mooseframework.inl.gov/docs/PRs/22947/coverage/external_petsc_solver)
- [`fluid_properties`](https://mooseframework.inl.gov/docs/PRs/22947/coverage/fluid_properties)
- [`fsi`](https://mooseframework.inl.gov/docs/PRs/22947/coverage/fsi)
- [`functional_expansion_tools`](https://mooseframework.inl.gov/docs/PRs/22947/coverage/functional_expansion_tools)
- [`geochemistry`](https://mooseframework.inl.gov/docs/PRs/22947/coverage/geochemistry)
- [`heat_conduction`](https://mooseframework.inl.gov/docs/PRs/22947/coverage/heat_conduction)
- [`level_set`](https://mooseframework.inl.gov/docs/PRs/22947/coverage/level_set)
- [`misc`](https://mooseframework.inl.gov/docs/PRs/22947/coverage/misc)
- [`navier_stokes`](https://mooseframework.inl.gov/docs/PRs/22947/coverage/navier_stokes)
- [`peridynamics`](https://mooseframework.inl.gov/docs/PRs/22947/coverage/peridynamics)
- [`phase_field`](https://mooseframework.inl.gov/docs/PRs/22947/coverage/phase_field)
- [`porous_flow`](https://mooseframework.inl.gov/docs/PRs/22947/coverage/porous_flow)
- [`ray_tracing`](https://mooseframework.inl.gov/docs/PRs/22947/coverage/ray_tracing)
- [`rdg`](https://mooseframework.inl.gov/docs/PRs/22947/coverage/rdg)
- [`reactor`](https://mooseframework.inl.gov/docs/PRs/22947/coverage/reactor)
- [`richards`](https://mooseframework.inl.gov/docs/PRs/22947/coverage/richards)
- [`scalar_transport`](https://mooseframework.inl.gov/docs/PRs/22947/coverage/scalar_transport)
- [`solid_properties`](https://mooseframework.inl.gov/docs/PRs/22947/coverage/solid_properties)
- [`stochastic_tools`](https://mooseframework.inl.gov/docs/PRs/22947/coverage/stochastic_tools)
- [`tensor_mechanics`](https://mooseframework.inl.gov/docs/PRs/22947/coverage/tensor_mechanics)
- [`thermal_hydraulics`](https://mooseframework.inl.gov/docs/PRs/22947/coverage/thermal_hydraulics)
- [`xfem`](https://mooseframework.inl.gov/docs/PRs/22947/coverage/xfem)

</details>



This comment will be updated on new commits.

2022-12-13 21:51 UTC, cticenhour requested changes
"MooseDown" Is a bit picky about needing empty lines between certain bits of content. This should fix your issue.

2022-12-13 21:51 UTC, cticenhour commented on modules/doc/content/python/TestHarness.md
> +To do this, create a Python script in the folder containing your test. The script should be blank aside from a single function named `custom_evaluation(output)`:
```suggestion
To do this, create a Python script in the folder containing your test. The script should be blank aside from a single function named `custom_evaluation(output)`:

```

2022-12-13 21:51 UTC, cticenhour commented on modules/doc/content/python/TestHarness.md
> +`output` is a string containing the test's entire output and can be manipulated as one sees fit. The function should return a boolean representing whether the test passed or not.
```suggestion

`output` is a string containing the test's entire output and can be manipulated as one sees fit. The function should return a boolean representing whether the test passed or not.
```

2022-12-13 21:51 UTC, cticenhour commented on modules/doc/content/python/TestHarness.md
> +After creating the .py file, add `custom_evaluation_script = '[filename].py'` to your test specification file. For example:
```suggestion
After creating the .py file, add `custom_evaluation_script = '[filename].py'` to your test specification file. For example:

```

2022-12-13 21:51 UTC, cticenhour commented on modules/doc/content/python/TestHarness.md
> +  [../]
```suggestion
  []
```

2022-12-13 23:14 UTC, cticenhour commented
@socratesgorilla FYI - MALAMUTE failure in `Internal App Tests` is unrelated and due to a patch for another PR. Disregard.

2022-12-14 16:09 UTC, cticenhour requested changes
This is neat! A few things to address to wrap this up.

2022-12-14 16:09 UTC, cticenhour commented on test/tests/test_harness/custom_eval
> +[Tests]
Please also test the cases where the user might supply `absent_out` or `expect_out` and an error is generated.

2022-12-14 16:09 UTC, cticenhour commented on python/TestHarness/tests/test_CustomEval.py
> +  def testCustomEval(self):
See other comment - expand this testing to hit more lines of the additional python.

2022-12-14 16:47 UTC, cticenhour reviewed
Found one more thing - the doco page builds, but doesn't look right: 

<img width="752" alt="image" src="https://user-images.githubusercontent.com/16690058/207656605-caafc004-53f2-4efc-ac84-2cad170a4121.png">

Stand by for another code adjustment once I get the site built.

2022-12-14 17:04 UTC, cticenhour requested changes

2022-12-14 17:04 UTC, cticenhour commented on modules/doc/content/python/TestHarness.md
> +```
Gah - spaces! This line has an extra space at the end of it that needs to be removed to render the section below it properly. My setup of VSCode removes trailing whitespaces by default, so I recommend checking that option (or the equivalent in your editor) to catch things like this.

2022-12-14 21:29 UTC, socratesgorilla commented
@cticenhour failing tests seem to be unrelated to me -- everything look good now?

2022-12-14 21:55 UTC, cticenhour approved these changes
CRANE failure is unrelated, and Griffin failures are related to the move to the new GitHub server. Pending another failure, I think this is good to go once testing completes.

2022-12-15 19:39 UTC, merged