Added SQA documentation for the rDG module
idaholab/moose pull request #22966
Opened 2022-12-14 23:22 UTC by joshuahansel

Refs #15968

2022-12-14 23:30 UTC, cticenhour requested changes
One typo. Otherwise looks good as far as markdown.

2022-12-14 23:30 UTC, cticenhour commented on modules/rdg/doc/content/sqa/rdg_sdd.md
> +MOOSE's pluggable systems are documented on [MOOSE website](https://mooseframework.inl.gov), and those
```suggestion
MOOSE's pluggable systems are documented on the [MOOSE website](https://mooseframework.inl.gov), and those
```

2022-12-15 00:25 UTC, lindsayad approved these changes
It's funny that this language describes exactly what we've reproduced in the FV portion of the `navier_stokes` module

2022-12-15 00:25 UTC, lindsayad commented
@joshuahansel does anyone use the rDG module that you know of?

2022-12-15 01:00 UTC, moosebuild commented
Job [Documentation](https://civet.inl.gov/job/1268506/) on 1072163 wanted to post the following:

View the site [here](https://mooseframework.inl.gov/docs/PRs/22966/site)

This comment will be updated on new commits.

2022-12-15 13:32 UTC, joshuahansel commented
> @joshuahansel does anyone use the rDG module that you know of?

I think THM may use one class from it, and then Bighorn. That's what I know of. It'd be great if it could be dissolved, if that's what you're getting at...

2022-12-15 15:18 UTC, cticenhour approved these changes

2022-12-15 15:19 UTC, cticenhour commented
Griffin failure related to GitHub Enterprise migration. OK to merge.

2022-12-15 15:19 UTC, merged