changed adjoint data structure
idaholab/moose pull request #22979
Opened 2022-12-16 00:09 UTC by lynnmunday

use vector of vectors to hold gradients for multiple types of parameters closes #22978

2022-12-16 00:11 UTC, lynnmunday commented
@zachmprince Will you look at this. For parameters = 'p1 p2' this creates a reporter called 'grad_wrt_p1 grad_wrt_p2'. I don't yet have a test where I transfer into the two different adjoint reporters, that test is still in isopod.  The tests we do have do properly create these two separate gradient reporters.

2022-12-16 01:35 UTC, moosebuild commented
Job [Documentation](https://civet.inl.gov/job/1270743/) on 468e90a wanted to post the following:

View the site [here](https://mooseframework.inl.gov/docs/PRs/22979/site)

This comment will be updated on new commits.

2022-12-16 21:26 UTC, moosebuild commented
Job [Coverage](https://civet.inl.gov/job/1271772/) on 61db1ab wanted to post the following:


## Framework coverage

<table>
  <thead>
    <tr>
      <th></th>
      <th>6fc2ee</th>
      <th colspan=4>#22979 61db1a</th>
    </tr>
    <tr>
      <th></th>
      <th>Total</th>
      <th>Total</th>
      <th>+/-</th>
      <th>New</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><b>Rate</b></td>
      <td>84.51%</td>
      <td>84.50%</td>
      <td>-0.00%</td>
      <td>-</td>
    </tr>
    <tr>
      <td><b>Hits</b></td>
      <td>81237</td>
      <td>81233</td>
      <td>-4</td>
      <td>0</td>
    </tr>
    <tr>
      <td><b>Misses</b></td>
      <td>14893</td>
      <td>14897</td>
      <td>+4</td>
      <td>0</td>
    </tr>
  </tbody>
</table>

[Diff coverage report](https://mooseframework.inl.gov/docs/PRs/22979/coverage_diff/framework)

[Full coverage report](https://mooseframework.inl.gov/docs/PRs/22979/coverage/framework)


## Modules coverage

### Optimization

<table>
  <thead>
    <tr>
      <th></th>
      <th>6fc2ee</th>
      <th colspan=4>#22979 61db1a</th>
    </tr>
    <tr>
      <th></th>
      <th>Total</th>
      <th>Total</th>
      <th>+/-</th>
      <th>New</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><b>Rate</b></td>
      <td>86.84%</td>
      <td>87.01%</td>
      <td>+0.17%</td>
      <td>100.00%</td>
    </tr>
    <tr>
      <td><b>Hits</b></td>
      <td>792</td>
      <td>797</td>
      <td>+5</td>
      <td>18</td>
    </tr>
    <tr>
      <td><b>Misses</b></td>
      <td>120</td>
      <td>119</td>
      <td>-1</td>
      <td>0</td>
    </tr>
  </tbody>
</table>

[Diff coverage report](https://mooseframework.inl.gov/docs/PRs/22979/coverage_diff/optimization)

[Full coverage report](https://mooseframework.inl.gov/docs/PRs/22979/coverage/optimization)

## Full coverage reports

<details>
<summary>Reports</summary>

- [`framework`](https://mooseframework.inl.gov/docs/PRs/22979/coverage/framework)
- [`chemical_reactions`](https://mooseframework.inl.gov/docs/PRs/22979/coverage/chemical_reactions)
- [`combined`](https://mooseframework.inl.gov/docs/PRs/22979/coverage/combined)
- [`contact`](https://mooseframework.inl.gov/docs/PRs/22979/coverage/contact)
- [`electromagnetics`](https://mooseframework.inl.gov/docs/PRs/22979/coverage/electromagnetics)
- [`external_petsc_solver`](https://mooseframework.inl.gov/docs/PRs/22979/coverage/external_petsc_solver)
- [`fluid_properties`](https://mooseframework.inl.gov/docs/PRs/22979/coverage/fluid_properties)
- [`fsi`](https://mooseframework.inl.gov/docs/PRs/22979/coverage/fsi)
- [`functional_expansion_tools`](https://mooseframework.inl.gov/docs/PRs/22979/coverage/functional_expansion_tools)
- [`geochemistry`](https://mooseframework.inl.gov/docs/PRs/22979/coverage/geochemistry)
- [`heat_conduction`](https://mooseframework.inl.gov/docs/PRs/22979/coverage/heat_conduction)
- [`level_set`](https://mooseframework.inl.gov/docs/PRs/22979/coverage/level_set)
- [`misc`](https://mooseframework.inl.gov/docs/PRs/22979/coverage/misc)
- [`navier_stokes`](https://mooseframework.inl.gov/docs/PRs/22979/coverage/navier_stokes)
- [`optimization`](https://mooseframework.inl.gov/docs/PRs/22979/coverage/optimization)
- [`peridynamics`](https://mooseframework.inl.gov/docs/PRs/22979/coverage/peridynamics)
- [`phase_field`](https://mooseframework.inl.gov/docs/PRs/22979/coverage/phase_field)
- [`porous_flow`](https://mooseframework.inl.gov/docs/PRs/22979/coverage/porous_flow)
- [`ray_tracing`](https://mooseframework.inl.gov/docs/PRs/22979/coverage/ray_tracing)
- [`rdg`](https://mooseframework.inl.gov/docs/PRs/22979/coverage/rdg)
- [`reactor`](https://mooseframework.inl.gov/docs/PRs/22979/coverage/reactor)
- [`richards`](https://mooseframework.inl.gov/docs/PRs/22979/coverage/richards)
- [`scalar_transport`](https://mooseframework.inl.gov/docs/PRs/22979/coverage/scalar_transport)
- [`solid_properties`](https://mooseframework.inl.gov/docs/PRs/22979/coverage/solid_properties)
- [`stochastic_tools`](https://mooseframework.inl.gov/docs/PRs/22979/coverage/stochastic_tools)
- [`tensor_mechanics`](https://mooseframework.inl.gov/docs/PRs/22979/coverage/tensor_mechanics)
- [`thermal_hydraulics`](https://mooseframework.inl.gov/docs/PRs/22979/coverage/thermal_hydraulics)
- [`xfem`](https://mooseframework.inl.gov/docs/PRs/22979/coverage/xfem)

</details>



This comment will be updated on new commits.

2022-12-22 01:07 UTC, zachmprince requested changes

2022-12-22 01:07 UTC, zachmprince commented on modules/optimization/src/optimizationreporters/OptimizationReporter.C
> +copyPetscVectorIntoReporter(const libMesh::PetscVector<Number> & x,
Make these static member functions in the OptimizationReporter class. Might be useful for other optimizations, so make them public.

2022-12-22 01:07 UTC, zachmprince commented on modules/optimization/src/optimizationreporters/OptimizationReporter.C
> +    _gradients.push_back(&declareValueByName<std::vector<Real>>("grad_wrt_" + _parameter_names[i],
I'd prefer without the `wrt`, but not a strong opinion.

2022-12-22 01:07 UTC, zachmprince commented on modules/optimization/test/tests/optimizationreporter/base/gold/optRep_fromCsv_out.json
> -  "reporters": {
Why are these json files changing so much??? The names of the gradient vectors should be the only thing that's changing.

2022-12-22 01:07 UTC, zachmprince commented on modules/optimization/test/tests/optimizationreporter/bc_load_linearFunction/main.i
> +  outputs=none
Why this?

2023-02-16 16:01 UTC, lynnmunday commented
@zachmprince will you review this again.  I started started over to get it to merge with your mesh reporter.

2023-02-16 19:05 UTC, zachmprince requested changes
Just a couple of minor suggestions.

2023-02-16 19:05 UTC, zachmprince commented on modules/optimization/src/optimizationreporters/OptimizationReporterBase.C
> +
I'd prefer to see these as public static functions of `OptimizationReporterBase`

2023-02-16 19:05 UTC, zachmprince commented on modules/optimization/src/optimizationreporters/ParameterMeshOptimization.C
> +  _nvalues.resize(_nparams, 0); // fixme lynn this is different from optimization reporter
I don't think the fixme comment is necessary.

2023-02-17 20:37 UTC, lynnmunday commented
@zachmprince will you review this again

2023-02-20 16:53 UTC, zachmprince approved these changes

2023-02-20 16:53 UTC, merged