Enhancement and Typos Fixing for ParsedCurveGenerator
idaholab/moose pull request #22985
Opened 2022-12-16 05:08 UTC by miaoyinb

closes #22984

## Reason

## Design

## Impact

2022-12-16 05:14 UTC, miaoyinb commented
Thanks for your comments @joshuahansel. Here is the fixing PR.
@sallustius some syntax changes FYI

2022-12-16 06:36 UTC, moosebuild commented
Job [Python 3.8](https://civet.inl.gov/job/1271313/) on b840924 : invalidated by @miaoyinb

2022-12-16 06:46 UTC, moosebuild commented
Job [Documentation](https://civet.inl.gov/job/1271305/) on b840924 wanted to post the following:

View the site [here](https://mooseframework.inl.gov/docs/PRs/22985/site)

This comment will be updated on new commits.

2022-12-16 08:01 UTC, moosebuild commented
Job [Coverage](https://civet.inl.gov/job/1271340/) on b840924 wanted to post the following:


## Framework coverage

<table>
  <thead>
    <tr>
      <th></th>
      <th>6fc2ee</th>
      <th colspan=4>#22985 b84092</th>
    </tr>
    <tr>
      <th></th>
      <th>Total</th>
      <th>Total</th>
      <th>+/-</th>
      <th>New</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><b>Rate</b></td>
      <td>84.51%</td>
      <td>84.51%</td>
      <td>+0.00%</td>
      <td>100.00%</td>
    </tr>
    <tr>
      <td><b>Hits</b></td>
      <td>81237</td>
      <td>81245</td>
      <td>+8</td>
      <td>14</td>
    </tr>
    <tr>
      <td><b>Misses</b></td>
      <td>14893</td>
      <td>14893</td>
      <td>-</td>
      <td>0</td>
    </tr>
  </tbody>
</table>

[Diff coverage report](https://mooseframework.inl.gov/docs/PRs/22985/coverage_diff/framework)

[Full coverage report](https://mooseframework.inl.gov/docs/PRs/22985/coverage/framework)


## Modules coverage

Coverage did not change

## Full coverage reports

<details>
<summary>Reports</summary>

- [`framework`](https://mooseframework.inl.gov/docs/PRs/22985/coverage/framework)
- [`chemical_reactions`](https://mooseframework.inl.gov/docs/PRs/22985/coverage/chemical_reactions)
- [`combined`](https://mooseframework.inl.gov/docs/PRs/22985/coverage/combined)
- [`contact`](https://mooseframework.inl.gov/docs/PRs/22985/coverage/contact)
- [`electromagnetics`](https://mooseframework.inl.gov/docs/PRs/22985/coverage/electromagnetics)
- [`external_petsc_solver`](https://mooseframework.inl.gov/docs/PRs/22985/coverage/external_petsc_solver)
- [`fluid_properties`](https://mooseframework.inl.gov/docs/PRs/22985/coverage/fluid_properties)
- [`fsi`](https://mooseframework.inl.gov/docs/PRs/22985/coverage/fsi)
- [`functional_expansion_tools`](https://mooseframework.inl.gov/docs/PRs/22985/coverage/functional_expansion_tools)
- [`geochemistry`](https://mooseframework.inl.gov/docs/PRs/22985/coverage/geochemistry)
- [`heat_conduction`](https://mooseframework.inl.gov/docs/PRs/22985/coverage/heat_conduction)
- [`level_set`](https://mooseframework.inl.gov/docs/PRs/22985/coverage/level_set)
- [`misc`](https://mooseframework.inl.gov/docs/PRs/22985/coverage/misc)
- [`navier_stokes`](https://mooseframework.inl.gov/docs/PRs/22985/coverage/navier_stokes)
- [`optimization`](https://mooseframework.inl.gov/docs/PRs/22985/coverage/optimization)
- [`peridynamics`](https://mooseframework.inl.gov/docs/PRs/22985/coverage/peridynamics)
- [`phase_field`](https://mooseframework.inl.gov/docs/PRs/22985/coverage/phase_field)
- [`porous_flow`](https://mooseframework.inl.gov/docs/PRs/22985/coverage/porous_flow)
- [`ray_tracing`](https://mooseframework.inl.gov/docs/PRs/22985/coverage/ray_tracing)
- [`rdg`](https://mooseframework.inl.gov/docs/PRs/22985/coverage/rdg)
- [`reactor`](https://mooseframework.inl.gov/docs/PRs/22985/coverage/reactor)
- [`richards`](https://mooseframework.inl.gov/docs/PRs/22985/coverage/richards)
- [`scalar_transport`](https://mooseframework.inl.gov/docs/PRs/22985/coverage/scalar_transport)
- [`solid_properties`](https://mooseframework.inl.gov/docs/PRs/22985/coverage/solid_properties)
- [`stochastic_tools`](https://mooseframework.inl.gov/docs/PRs/22985/coverage/stochastic_tools)
- [`tensor_mechanics`](https://mooseframework.inl.gov/docs/PRs/22985/coverage/tensor_mechanics)
- [`thermal_hydraulics`](https://mooseframework.inl.gov/docs/PRs/22985/coverage/thermal_hydraulics)
- [`xfem`](https://mooseframework.inl.gov/docs/PRs/22985/coverage/xfem)

</details>



This comment will be updated on new commits.

2022-12-29 21:28 UTC, moosebuild commented
Job [Conda (ARM Mac)](https://civet.inl.gov/job/1278360/) on 5c581c1 : invalidated by @miaoyinb

2023-01-04 04:44 UTC, moosebuild commented
Job [App documentation](https://civet.inl.gov/job/1281147/) on 7e9a26b : invalidated by @miaoyinb

2023-01-04 04:45 UTC, moosebuild commented
Job [Apptainer build](https://civet.inl.gov/job/1281150/) on 7e9a26b : invalidated by @miaoyinb

2023-01-05 15:57 UTC, miaoyinb commented
Added a new functionality that allows users to specify the number of elements in the curve section (actually a straight line) that is used to forcefully close the open curve. The related description has also been added to #22984

2023-01-05 15:58 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/1284267/) on e97aceb wanted to post the following:

Your code requires style changes.  

A patch was auto generated and copied [here](https://mooseframework.inl.gov/docs/PRs/22985/clang_format/style.patch)  
You can directly apply the patch by running, in the top level of your repository:

`curl -s https://mooseframework.inl.gov/docs/PRs/22985/clang_format/style.patch | git apply -v`  

Alternatively, with your repository up to date and in the top level of your repository:

`git clang-format cebfc510d280dbd6eee799bb1cbf857b6b6a2c2a`

2023-01-05 16:00 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/1284307/) on 0f7204e wanted to post the following:

Your code requires style changes.  

A patch was auto generated and copied [here](https://mooseframework.inl.gov/docs/PRs/22985/clang_format/style.patch)  
You can directly apply the patch by running, in the top level of your repository:

`curl -s https://mooseframework.inl.gov/docs/PRs/22985/clang_format/style.patch | git apply -v`  

Alternatively, with your repository up to date and in the top level of your repository:

`git clang-format cebfc510d280dbd6eee799bb1cbf857b6b6a2c2a`

2023-01-20 05:32 UTC, miaoyinb commented
Just a friendly reminder that this PR is still pending review.

2023-01-20 15:32 UTC, joshuahansel commented
> Just a friendly reminder that this PR is still pending review.

@friedmud I'll give this a review now.

2023-01-20 16:07 UTC, joshuahansel requested changes

2023-01-20 16:07 UTC, joshuahansel commented on framework/src/meshgenerators/ParsedCurveGenerator.C
> +                                     : 0),
Why is this needed instead of setting a default to zero?

2023-01-20 16:07 UTC, joshuahansel commented on framework/src/meshgenerators/ParsedCurveGenerator.C
> +               "Maximum oversampling points number has been exceeded. Please consider add more t "
Also, put single quotes around parameter names.

2023-01-20 17:37 UTC, miaoyinb commented on framework/src/meshgenerators/ParsedCurveGenerator.C
> +      "Numbers of segments of segments of the curve to be generated.");
Sorry for the confusion. It should be "segments (EDGE2 elements) of each section". I will add the description. I think we can keep the original parameter name but make the description more detailed.

2023-01-20 17:52 UTC, miaoyinb commented on framework/src/meshgenerators/ParsedCurveGenerator.C
>        "Critical values of the parameter 't' that will be sampled; Starting and ending values must "
Sure

2023-01-20 19:20 UTC, joshuahansel commented on framework/src/meshgenerators/ParsedCurveGenerator.C
> +      "Numbers of segments of segments of the curve to be generated.");
That's fine. "nums" is a little strange language - "num" is better, although you may be trying to convey that it's many values.

2023-01-20 19:29 UTC, miaoyinb commented on framework/src/meshgenerators/ParsedCurveGenerator.C
> +      "Numbers of segments of segments of the curve to be generated.");
Yes, this is just to indicate that the parameter is not a scalar.

2023-01-20 19:38 UTC, joshuahansel commented on framework/src/meshgenerators/ParsedCurveGenerator.C
> +      "Numbers of segments of segments of the curve to be generated.");
Ok, that's fine - it can stay.

2023-01-20 20:28 UTC, joshuahansel approved these changes

2023-01-23 12:47 UTC, merged

2023-01-23 15:19 UTC, miaoyinb commented
Thank you so much, @joshuahansel