Demonstrate how to get good ghosted solutions from a ExternalProblem
idaholab/moose pull request #23091
Opened 2023-01-06 03:18 UTC by lindsayad

We cannot simply update the parallel solution. We have to do a second step of localizing the parallel solution to the ghosted current local solution

Closes #17534

2023-01-06 03:19 UTC, lindsayad commented
@aprilnovak

2023-01-06 04:45 UTC, moosebuild commented
Job [Documentation](https://civet.inl.gov/job/1285854/) on 1c381cc wanted to post the following:

View the site [here](https://mooseframework.inl.gov/docs/PRs/23091/site)

This comment will be updated on new commits.

2023-01-06 05:38 UTC, moosebuild commented
Job [Coverage](https://civet.inl.gov/job/1285868/) on 1c381cc wanted to post the following:


## Framework coverage

Coverage did not change


## Modules coverage

Coverage did not change

## Full coverage reports

<details>
<summary>Reports</summary>

- [`framework`](https://mooseframework.inl.gov/docs/PRs/23091/coverage/framework)
- [`chemical_reactions`](https://mooseframework.inl.gov/docs/PRs/23091/coverage/chemical_reactions)
- [`combined`](https://mooseframework.inl.gov/docs/PRs/23091/coverage/combined)
- [`contact`](https://mooseframework.inl.gov/docs/PRs/23091/coverage/contact)
- [`electromagnetics`](https://mooseframework.inl.gov/docs/PRs/23091/coverage/electromagnetics)
- [`external_petsc_solver`](https://mooseframework.inl.gov/docs/PRs/23091/coverage/external_petsc_solver)
- [`fluid_properties`](https://mooseframework.inl.gov/docs/PRs/23091/coverage/fluid_properties)
- [`fsi`](https://mooseframework.inl.gov/docs/PRs/23091/coverage/fsi)
- [`functional_expansion_tools`](https://mooseframework.inl.gov/docs/PRs/23091/coverage/functional_expansion_tools)
- [`geochemistry`](https://mooseframework.inl.gov/docs/PRs/23091/coverage/geochemistry)
- [`heat_conduction`](https://mooseframework.inl.gov/docs/PRs/23091/coverage/heat_conduction)
- [`level_set`](https://mooseframework.inl.gov/docs/PRs/23091/coverage/level_set)
- [`misc`](https://mooseframework.inl.gov/docs/PRs/23091/coverage/misc)
- [`navier_stokes`](https://mooseframework.inl.gov/docs/PRs/23091/coverage/navier_stokes)
- [`optimization`](https://mooseframework.inl.gov/docs/PRs/23091/coverage/optimization)
- [`peridynamics`](https://mooseframework.inl.gov/docs/PRs/23091/coverage/peridynamics)
- [`phase_field`](https://mooseframework.inl.gov/docs/PRs/23091/coverage/phase_field)
- [`porous_flow`](https://mooseframework.inl.gov/docs/PRs/23091/coverage/porous_flow)
- [`ray_tracing`](https://mooseframework.inl.gov/docs/PRs/23091/coverage/ray_tracing)
- [`rdg`](https://mooseframework.inl.gov/docs/PRs/23091/coverage/rdg)
- [`reactor`](https://mooseframework.inl.gov/docs/PRs/23091/coverage/reactor)
- [`richards`](https://mooseframework.inl.gov/docs/PRs/23091/coverage/richards)
- [`scalar_transport`](https://mooseframework.inl.gov/docs/PRs/23091/coverage/scalar_transport)
- [`solid_properties`](https://mooseframework.inl.gov/docs/PRs/23091/coverage/solid_properties)
- [`stochastic_tools`](https://mooseframework.inl.gov/docs/PRs/23091/coverage/stochastic_tools)
- [`tensor_mechanics`](https://mooseframework.inl.gov/docs/PRs/23091/coverage/tensor_mechanics)
- [`thermal_hydraulics`](https://mooseframework.inl.gov/docs/PRs/23091/coverage/thermal_hydraulics)
- [`xfem`](https://mooseframework.inl.gov/docs/PRs/23091/coverage/xfem)

</details>



This comment will be updated on new commits.

2023-01-06 18:16 UTC, GiudGiud requested changes

2023-01-06 18:16 UTC, GiudGiud commented on test/include/problems/TransientExternalProblem.h
> +#pragma once
missing headers in these files

2023-01-06 18:16 UTC, GiudGiud commented on test/src/problems/TransientExternalProblem.C
> +registerMooseObject("MooseTestApp", TransientExternalProblem);
I would change the name. (SyncTestExternalProblem?)
The name would be great for pointing to specificities of a transient external problem

but there's no specificity here, you re just using time to get a good test output

2023-01-06 20:00 UTC, moosebuild commented
Job [Python 3.10](https://civet.inl.gov/job/1286855/) on 89d8d94 : invalidated by @lindsayad

2023-01-06 20:00 UTC, moosebuild commented
Job [Min clang](https://civet.inl.gov/job/1286882/) on 89d8d94 : invalidated by @lindsayad

2023-01-06 20:00 UTC, moosebuild commented
Job [Conda build (Intel Mac)](https://civet.inl.gov/job/1286853/) on 89d8d94 : invalidated by @lindsayad

2023-01-06 22:57 UTC, moosebuild commented
Job [Coverage](https://civet.inl.gov/job/1286887/) on 89d8d94 : invalidated by @lindsayad

2023-01-07 10:03 UTC, GiudGiud approved these changes, later dismissed

2023-01-07 15:10 UTC, moosebuild commented
All [jobs](https://civet.inl.gov/event/105333/) on 89d8d94 : invalidated by @lindsayad

2023-01-07 15:52 UTC, moosebuild commented
Job [Conda (Rocky)](https://civet.inl.gov/job/1286879/) on 89d8d94 : invalidated by @lindsayad

2023-01-08 16:10 UTC, loganharbour requested changes

2023-01-08 16:10 UTC, loganharbour commented on test/src/problems/SyncTestExternalProblem.C
> +        auto elem_ptr = mesh.query_elem_ptr(e);
Element range loop?

2023-01-09 18:38 UTC, loganharbour approved these changes
No issues from me - simple and to the point.

2023-01-09 20:19 UTC, moosebuild commented
Job [Conda (Intel Mac)](https://civet.inl.gov/job/1289946/) on 94a2197 : invalidated by @lindsayad

2023-01-09 20:19 UTC, moosebuild commented
Job [Test install](https://civet.inl.gov/job/1289957/) on 94a2197 : invalidated by @lindsayad

2023-01-09 21:19 UTC, moosebuild commented
Job [Coverage](https://civet.inl.gov/job/1289955/) on 94a2197 wanted to post the following:


The following coverage requirement(s) failed:
- Failed to generate `stochastic_tools` coverage rate (required: 88.0%)

2023-01-09 22:33 UTC, lindsayad commented
failure unrelated

2023-01-09 22:33 UTC, merged