Fix the two bugs in assembly with array variables
idaholab/moose pull request #23124
Opened 2023-01-10 07:07 UTC by YaqiWang

Close #23123.

2023-01-10 07:12 UTC, YaqiWang commented
This should pass all the tests. I will add a small test later.

2023-01-10 08:34 UTC, moosebuild commented
Job [Documentation](https://civet.inl.gov/job/1291872/) on f78105b wanted to post the following:

View the site [here](https://mooseframework.inl.gov/docs/PRs/23124/site)

This comment will be updated on new commits.

2023-01-10 09:24 UTC, moosebuild commented
Job [Coverage](https://civet.inl.gov/job/1291886/) on f78105b wanted to post the following:


## Framework coverage

<table>
  <thead>
    <tr>
      <th></th>
      <th>039cff</th>
      <th colspan=4>#23124 f78105</th>
    </tr>
    <tr>
      <th></th>
      <th>Total</th>
      <th>Total</th>
      <th>+/-</th>
      <th>New</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><b>Rate</b></td>
      <td>84.53%</td>
      <td>84.52%</td>
      <td>-0.01%</td>
      <td>29.79%</td>
    </tr>
    <tr>
      <td><b>Hits</b></td>
      <td>81635</td>
      <td>81635</td>
      <td>-</td>
      <td>14</td>
    </tr>
    <tr>
      <td><b>Misses</b></td>
      <td>14936</td>
      <td>14952</td>
      <td>+16</td>
      <td>33</td>
    </tr>
  </tbody>
</table>

[Diff coverage report](https://mooseframework.inl.gov/docs/PRs/23124/coverage_diff/framework)

[Full coverage report](https://mooseframework.inl.gov/docs/PRs/23124/coverage/framework)


## Modules coverage

Coverage did not change

## Full coverage reports

<details>
<summary>Reports</summary>

- [`framework`](https://mooseframework.inl.gov/docs/PRs/23124/coverage/framework)
- [`chemical_reactions`](https://mooseframework.inl.gov/docs/PRs/23124/coverage/chemical_reactions)
- [`combined`](https://mooseframework.inl.gov/docs/PRs/23124/coverage/combined)
- [`contact`](https://mooseframework.inl.gov/docs/PRs/23124/coverage/contact)
- [`electromagnetics`](https://mooseframework.inl.gov/docs/PRs/23124/coverage/electromagnetics)
- [`external_petsc_solver`](https://mooseframework.inl.gov/docs/PRs/23124/coverage/external_petsc_solver)
- [`fluid_properties`](https://mooseframework.inl.gov/docs/PRs/23124/coverage/fluid_properties)
- [`fsi`](https://mooseframework.inl.gov/docs/PRs/23124/coverage/fsi)
- [`functional_expansion_tools`](https://mooseframework.inl.gov/docs/PRs/23124/coverage/functional_expansion_tools)
- [`geochemistry`](https://mooseframework.inl.gov/docs/PRs/23124/coverage/geochemistry)
- [`heat_conduction`](https://mooseframework.inl.gov/docs/PRs/23124/coverage/heat_conduction)
- [`level_set`](https://mooseframework.inl.gov/docs/PRs/23124/coverage/level_set)
- [`misc`](https://mooseframework.inl.gov/docs/PRs/23124/coverage/misc)
- [`navier_stokes`](https://mooseframework.inl.gov/docs/PRs/23124/coverage/navier_stokes)
- [`optimization`](https://mooseframework.inl.gov/docs/PRs/23124/coverage/optimization)
- [`peridynamics`](https://mooseframework.inl.gov/docs/PRs/23124/coverage/peridynamics)
- [`phase_field`](https://mooseframework.inl.gov/docs/PRs/23124/coverage/phase_field)
- [`porous_flow`](https://mooseframework.inl.gov/docs/PRs/23124/coverage/porous_flow)
- [`ray_tracing`](https://mooseframework.inl.gov/docs/PRs/23124/coverage/ray_tracing)
- [`rdg`](https://mooseframework.inl.gov/docs/PRs/23124/coverage/rdg)
- [`reactor`](https://mooseframework.inl.gov/docs/PRs/23124/coverage/reactor)
- [`richards`](https://mooseframework.inl.gov/docs/PRs/23124/coverage/richards)
- [`scalar_transport`](https://mooseframework.inl.gov/docs/PRs/23124/coverage/scalar_transport)
- [`solid_properties`](https://mooseframework.inl.gov/docs/PRs/23124/coverage/solid_properties)
- [`stochastic_tools`](https://mooseframework.inl.gov/docs/PRs/23124/coverage/stochastic_tools)
- [`tensor_mechanics`](https://mooseframework.inl.gov/docs/PRs/23124/coverage/tensor_mechanics)
- [`thermal_hydraulics`](https://mooseframework.inl.gov/docs/PRs/23124/coverage/thermal_hydraulics)
- [`xfem`](https://mooseframework.inl.gov/docs/PRs/23124/coverage/xfem)

</details>

## Warnings

- `framework` new line coverage rate 29.79% is less than the suggested 90.0%



This comment will be updated on new commits.

2023-01-11 20:06 UTC, lindsayad commented
So we don't have a way to do better than the 36% coverage?

2023-01-11 21:08 UTC, YaqiWang commented
I thought I would got 100% coverage with the test lol. Let me check the report.

2023-01-11 21:12 UTC, YaqiWang commented
Looks like I just modified codes that was not covered before and those modifications are marked uncovered now. We probably have tests for some of the codes in applications.

2023-01-11 21:56 UTC, lindsayad commented
I'm just worried if you say that you are fixing two bugs but the bug fixes are not covered, how do we know we will not regress or that the bugs are fixed? It's one thing not to cover a new feature; it's another thing to say there are bugs and that you're fixing them and not to cover what are reported as bugs

2023-01-11 22:38 UTC, YaqiWang commented
The two bugs we notices are covered, one in `Assembly.h` another in `Assembly::addJacobianBlock`. While working on the later, I notices other `addJacobianBlockxxx`s had similar issue as `Assembly::addJacobianBlock`. The uncovered lines are in those functions. Supposedly if we have tests calling those functions, those lines will be covered as well, right?

2023-01-11 22:52 UTC, lindsayad commented
Of course. And clearly those tests don't exist. You are implying that it shouldn't be your responsibility to add tests for code that wasn't yours that you fixed. And that's fine. You'll just have to wait a bit longer on this PR then for me to come up with tests for those uncovered lines

2023-01-11 22:53 UTC, lindsayad commented
Or if you are in a big hurry, you can split the PR into the fixes that are relevant to Griffin which it sounds like you already have test coverage for and the fixes for which you do not yet have coverage for. And I can add tests for the latter

2023-01-11 23:40 UTC, YaqiWang commented
Yes, you got me right ;-) I might be able to switch the test to DG to have more coverage. But those nonlocal stuff will still not be covered probably.

2023-01-11 23:45 UTC, YaqiWang commented
But it is very strange to me that `Assembly::prepareBlock` must be used in existing tests, yet the changes in it shows not covered. Any idea on this?

2023-01-12 04:19 UTC, YaqiWang commented
Switched to use PBP and hopefully that will increase the coverage.

2023-01-12 18:20 UTC, lindsayad requested changes

2023-01-12 18:20 UTC, lindsayad commented on framework/include/base/Assembly.h
> +      unsigned int saved_j = j;
```suggestion
      const unsigned int saved_j = j;
```

2023-01-12 18:20 UTC, lindsayad commented on framework/src/base/Assembly.C
> +  unsigned int jcount = jv.count();
```suggestion
  const unsigned int ivn = iv.number();
  const unsigned int jvn = jv.number();
  const unsigned int icount = iv.count();
  const unsigned int jcount = jv.count();
```

2023-01-12 18:20 UTC, lindsayad commented on framework/src/base/Assembly.C
> +  unsigned int jcount = jv.count();
```suggestion
  const unsigned int ivn = iv.number();
  const unsigned int jvn = jv.number();
  const unsigned int icount = iv.count();
  const unsigned int jcount = jv.count();
```

2023-01-12 18:20 UTC, lindsayad commented on framework/src/base/Assembly.C
> +  unsigned int jvn = jv.number();
```suggestion
  const unsigned int ivn = iv.number();
  const unsigned int jvn = jv.number();
```

2023-01-12 18:20 UTC, lindsayad commented on framework/src/base/Assembly.C
> +  unsigned int j = jvar - jvn;
```suggestion
  const unsigned int i = ivar - ivn;
  const unsigned int j = jvar - jvn;
```

2023-01-12 18:20 UTC, lindsayad commented on framework/src/base/Assembly.C
> +  unsigned int jvn = jv.number();
```suggestion
  const unsigned int ivn = iv.number();
  const unsigned int jvn = jv.number();
```

2023-01-12 18:20 UTC, lindsayad commented on framework/src/base/Assembly.C
> +  unsigned int j = jvar - jvn;
```suggestion
  const unsigned int i = ivar - ivn;
  const unsigned int j = jvar - jvn;
```

2023-01-12 18:20 UTC, lindsayad commented on framework/src/base/Assembly.C
> +  unsigned int jvn = jv.number();
```suggestion
  const unsigned int ivn = iv.number();
  const unsigned int jvn = jv.number();
```

2023-01-12 18:20 UTC, lindsayad commented on framework/src/base/Assembly.C
```suggestion
  const unsigned int i = ivar - ivn;
  const unsigned int j = jvar - jvn;
```

2023-01-12 18:26 UTC, lindsayad commented
@YaqiWang if you really want the new `view_matrix` option in PBP, we can strip off that last commit. But if we do, let's create a `_view_matrix` const boolean class member so we don't have to call `getParam` every time the operator might change

2023-01-12 18:29 UTC, YaqiWang commented
> @YaqiWang if you really want the new `view_matrix` option in PBP, we can strip off that last commit. But if we do, let's create a `_view_matrix` const boolean class member so we don't have to call `getParam` every time the operator might change

Not really. I do not know we can use `-mat_view` to show the matrices.

2023-01-12 18:30 UTC, lindsayad approved these changes

2023-01-12 20:43 UTC, merged

2023-01-12 20:46 UTC, YaqiWang commented
Thanks @lindsayad !