23141 update pbs checker
idaholab/moose pull request #23151
Opened 2023-01-12 22:28 UTC by milljm

Pylint happy (I think), add argparse to allow `-w --wait` blocking ability.

2023-01-13 00:52 UTC, moosebuild commented
Job [Coverage](https://civet.inl.gov/job/1298442/) on a566e33 wanted to post the following:


## Framework coverage

<table>
  <thead>
    <tr>
      <th></th>
      <th>e4507b</th>
      <th colspan=4>#23151 a566e3</th>
    </tr>
    <tr>
      <th></th>
      <th>Total</th>
      <th>Total</th>
      <th>+/-</th>
      <th>New</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><b>Rate</b></td>
      <td>84.53%</td>
      <td>84.54%</td>
      <td>+0.00%</td>
      <td>-</td>
    </tr>
    <tr>
      <td><b>Hits</b></td>
      <td>81696</td>
      <td>81699</td>
      <td>+3</td>
      <td>0</td>
    </tr>
    <tr>
      <td><b>Misses</b></td>
      <td>14946</td>
      <td>14943</td>
      <td>-3</td>
      <td>0</td>
    </tr>
  </tbody>
</table>

[Diff coverage report](https://mooseframework.inl.gov/docs/PRs/23151/coverage_diff/framework)

[Full coverage report](https://mooseframework.inl.gov/docs/PRs/23151/coverage/framework)


## Modules coverage

Coverage did not change

## Full coverage reports

<details>
<summary>Reports</summary>

- [`framework`](https://mooseframework.inl.gov/docs/PRs/23151/coverage/framework)
- [`chemical_reactions`](https://mooseframework.inl.gov/docs/PRs/23151/coverage/chemical_reactions)
- [`combined`](https://mooseframework.inl.gov/docs/PRs/23151/coverage/combined)
- [`contact`](https://mooseframework.inl.gov/docs/PRs/23151/coverage/contact)
- [`electromagnetics`](https://mooseframework.inl.gov/docs/PRs/23151/coverage/electromagnetics)
- [`external_petsc_solver`](https://mooseframework.inl.gov/docs/PRs/23151/coverage/external_petsc_solver)
- [`fluid_properties`](https://mooseframework.inl.gov/docs/PRs/23151/coverage/fluid_properties)
- [`fsi`](https://mooseframework.inl.gov/docs/PRs/23151/coverage/fsi)
- [`functional_expansion_tools`](https://mooseframework.inl.gov/docs/PRs/23151/coverage/functional_expansion_tools)
- [`geochemistry`](https://mooseframework.inl.gov/docs/PRs/23151/coverage/geochemistry)
- [`heat_conduction`](https://mooseframework.inl.gov/docs/PRs/23151/coverage/heat_conduction)
- [`level_set`](https://mooseframework.inl.gov/docs/PRs/23151/coverage/level_set)
- [`misc`](https://mooseframework.inl.gov/docs/PRs/23151/coverage/misc)
- [`navier_stokes`](https://mooseframework.inl.gov/docs/PRs/23151/coverage/navier_stokes)
- [`optimization`](https://mooseframework.inl.gov/docs/PRs/23151/coverage/optimization)
- [`peridynamics`](https://mooseframework.inl.gov/docs/PRs/23151/coverage/peridynamics)
- [`phase_field`](https://mooseframework.inl.gov/docs/PRs/23151/coverage/phase_field)
- [`porous_flow`](https://mooseframework.inl.gov/docs/PRs/23151/coverage/porous_flow)
- [`ray_tracing`](https://mooseframework.inl.gov/docs/PRs/23151/coverage/ray_tracing)
- [`rdg`](https://mooseframework.inl.gov/docs/PRs/23151/coverage/rdg)
- [`reactor`](https://mooseframework.inl.gov/docs/PRs/23151/coverage/reactor)
- [`richards`](https://mooseframework.inl.gov/docs/PRs/23151/coverage/richards)
- [`scalar_transport`](https://mooseframework.inl.gov/docs/PRs/23151/coverage/scalar_transport)
- [`solid_properties`](https://mooseframework.inl.gov/docs/PRs/23151/coverage/solid_properties)
- [`stochastic_tools`](https://mooseframework.inl.gov/docs/PRs/23151/coverage/stochastic_tools)
- [`tensor_mechanics`](https://mooseframework.inl.gov/docs/PRs/23151/coverage/tensor_mechanics)
- [`thermal_hydraulics`](https://mooseframework.inl.gov/docs/PRs/23151/coverage/thermal_hydraulics)
- [`xfem`](https://mooseframework.inl.gov/docs/PRs/23151/coverage/xfem)

</details>



This comment will be updated on new commits.

2023-01-16 21:30 UTC, loganharbour requested changes

2023-01-16 21:31 UTC, milljm commented on scripts/are_queued_jobs_finished.py
> +def qstat_results(job_id):
yeah... I am thinking it will at line 70

2023-01-16 21:41 UTC, loganharbour commented on scripts/are_queued_jobs_finished.py
> +def qstat_results(job_id):
okay so we want a job from forever ago to be considered a finish?

2023-01-16 22:18 UTC, moosebuild commented
Job [Documentation](https://civet.inl.gov/job/1302218/) on 9a2966d wanted to post the following:

View the site [here](https://mooseframework.inl.gov/docs/PRs/23151/site)

This comment will be updated on new commits.

2023-01-17 13:49 UTC, milljm commented on scripts/are_queued_jobs_finished.py
> +def qstat_results(job_id):
I think I know where the confusion is coming from: If you check this target out, and expand on "Bison Examples", you'll see how this script is being used: https://civet.inl.gov/job/1301248/

We are using this script to try and limit the number of times we need to run `run_tests` down to only twice. One to launch jobs, and then a second time to create a finished report.

So a failing qstat command, while we don't know why it failed, its a finished job. The second time we run `./run_tests`, the heavier TestHarness process will correctly figure out the "why" of it, and report it as such.

2023-01-17 13:58 UTC, milljm commented
I'd like to investigate the `--wait` argument a bit more. Allowing for an integer in seconds to wait, would be a nice addition.

2023-01-19 13:58 UTC, loganharbour approved these changes

2023-01-19 14:00 UTC, merged