Remove forward declarations
idaholab/moose pull request #23193
Opened 2023-01-18 16:10 UTC by vovannikov

Closes #23192

2023-01-19 13:53 UTC, loganharbour commented
@vovannikov thanks for your first contribution!

2023-01-19 13:54 UTC, loganharbour requested changes

2023-01-19 13:54 UTC, loganharbour commented on framework/include/materials/Material.h
>  //* This file is part of the MOOSE framework
```suggestion
//* This file is part of the MOOSE framework
```

Please remove this newline

2023-01-19 14:29 UTC, vovannikov commented on framework/include/materials/Material.h
>  //* This file is part of the MOOSE framework
Oops, I added it accidentally.

2023-01-19 14:30 UTC, loganharbour approved these changes

2023-01-19 14:33 UTC, loganharbour requested changes
Whoops - one more thing. You need to reference the issue https://github.com/idaholab/moose/issues/23192 in at least one of your commit messages. This is one of our SQA requirements.

See https://civet.inl.gov/job/1306624/:

```

##########################################################################
ERROR: Your patch does not contain a valid ticket reference! (i.e. #1234)
Merge branch 'del_old_validParams' of https://github.com/vovannikov/moose into test
Remove line
Remove forward declarations
##########################################################################
```

2023-01-19 15:26 UTC, vovannikov commented
> Whoops - one more thing. You need to reference the issue #23192 in at least one of your commit messages. This is one of our SQA requirements.

Sorry for that, this is my first contribution here :) Thank you for the hint!

2023-01-20 23:47 UTC, moosebuild commented
Job [Documentation](https://civet.inl.gov/job/1306804/) on f5cc07c wanted to post the following:

View the site [here](https://mooseframework.inl.gov/docs/PRs/23193/site)

This comment will be updated on new commits.

2023-01-21 00:47 UTC, moosebuild commented
Job [Coverage](https://civet.inl.gov/job/1306818/) on f5cc07c wanted to post the following:


## Framework coverage

<table>
  <thead>
    <tr>
      <th></th>
      <th>9f4eda</th>
      <th colspan=4>#23193 f5cc07</th>
    </tr>
    <tr>
      <th></th>
      <th>Total</th>
      <th>Total</th>
      <th>+/-</th>
      <th>New</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><b>Rate</b></td>
      <td>84.61%</td>
      <td>84.61%</td>
      <td>-0.00%</td>
      <td>-</td>
    </tr>
    <tr>
      <td><b>Hits</b></td>
      <td>81968</td>
      <td>81965</td>
      <td>-3</td>
      <td>0</td>
    </tr>
    <tr>
      <td><b>Misses</b></td>
      <td>14906</td>
      <td>14909</td>
      <td>+3</td>
      <td>0</td>
    </tr>
  </tbody>
</table>

[Diff coverage report](https://mooseframework.inl.gov/docs/PRs/23193/coverage_diff/framework)

[Full coverage report](https://mooseframework.inl.gov/docs/PRs/23193/coverage/framework)


## Modules coverage

Coverage did not change

## Full coverage reports

<details>
<summary>Reports</summary>

- [`framework`](https://mooseframework.inl.gov/docs/PRs/23193/coverage/framework)
- [`chemical_reactions`](https://mooseframework.inl.gov/docs/PRs/23193/coverage/chemical_reactions)
- [`combined`](https://mooseframework.inl.gov/docs/PRs/23193/coverage/combined)
- [`contact`](https://mooseframework.inl.gov/docs/PRs/23193/coverage/contact)
- [`electromagnetics`](https://mooseframework.inl.gov/docs/PRs/23193/coverage/electromagnetics)
- [`external_petsc_solver`](https://mooseframework.inl.gov/docs/PRs/23193/coverage/external_petsc_solver)
- [`fluid_properties`](https://mooseframework.inl.gov/docs/PRs/23193/coverage/fluid_properties)
- [`fsi`](https://mooseframework.inl.gov/docs/PRs/23193/coverage/fsi)
- [`functional_expansion_tools`](https://mooseframework.inl.gov/docs/PRs/23193/coverage/functional_expansion_tools)
- [`geochemistry`](https://mooseframework.inl.gov/docs/PRs/23193/coverage/geochemistry)
- [`heat_conduction`](https://mooseframework.inl.gov/docs/PRs/23193/coverage/heat_conduction)
- [`level_set`](https://mooseframework.inl.gov/docs/PRs/23193/coverage/level_set)
- [`misc`](https://mooseframework.inl.gov/docs/PRs/23193/coverage/misc)
- [`navier_stokes`](https://mooseframework.inl.gov/docs/PRs/23193/coverage/navier_stokes)
- [`optimization`](https://mooseframework.inl.gov/docs/PRs/23193/coverage/optimization)
- [`peridynamics`](https://mooseframework.inl.gov/docs/PRs/23193/coverage/peridynamics)
- [`phase_field`](https://mooseframework.inl.gov/docs/PRs/23193/coverage/phase_field)
- [`porous_flow`](https://mooseframework.inl.gov/docs/PRs/23193/coverage/porous_flow)
- [`ray_tracing`](https://mooseframework.inl.gov/docs/PRs/23193/coverage/ray_tracing)
- [`rdg`](https://mooseframework.inl.gov/docs/PRs/23193/coverage/rdg)
- [`reactor`](https://mooseframework.inl.gov/docs/PRs/23193/coverage/reactor)
- [`richards`](https://mooseframework.inl.gov/docs/PRs/23193/coverage/richards)
- [`scalar_transport`](https://mooseframework.inl.gov/docs/PRs/23193/coverage/scalar_transport)
- [`solid_properties`](https://mooseframework.inl.gov/docs/PRs/23193/coverage/solid_properties)
- [`stochastic_tools`](https://mooseframework.inl.gov/docs/PRs/23193/coverage/stochastic_tools)
- [`tensor_mechanics`](https://mooseframework.inl.gov/docs/PRs/23193/coverage/tensor_mechanics)
- [`thermal_hydraulics`](https://mooseframework.inl.gov/docs/PRs/23193/coverage/thermal_hydraulics)
- [`xfem`](https://mooseframework.inl.gov/docs/PRs/23193/coverage/xfem)

</details>



This comment will be updated on new commits.

2023-01-22 18:39 UTC, loganharbour commented
> > Whoops - one more thing. You need to reference the issue #23192 in at least one of your commit messages. This is one of our SQA requirements.
> 
> Sorry for that, this is my first contribution here :) Thank you for the hint!

No worries! We're happy to support fresh contributors! Thanks again!

2023-01-22 18:39 UTC, loganharbour approved these changes

2023-01-24 01:43 UTC, merged