Fix periods in PATH causing tests to fail.
idaholab/moose pull request #23241
Opened 2023-01-24 17:28 UTC by socratesgorilla

Closes #22929 

Current Draft PR exists only to test on the full suite

2023-01-24 19:35 UTC, moosebuild commented
Job [Documentation](https://civet.inl.gov/job/1315420/) on 10d4b9d wanted to post the following:

View the site [here](https://mooseframework.inl.gov/docs/PRs/23241/site)

This comment will be updated on new commits.

2023-01-24 20:23 UTC, moosebuild commented
Job [Coverage](https://civet.inl.gov/job/1315434/) on 10d4b9d wanted to post the following:


## Framework coverage

Coverage did not change


## Modules coverage

Coverage did not change

## Full coverage reports

<details>
<summary>Reports</summary>

- [`framework`](https://mooseframework.inl.gov/docs/PRs/23241/coverage/framework)
- [`chemical_reactions`](https://mooseframework.inl.gov/docs/PRs/23241/coverage/chemical_reactions)
- [`combined`](https://mooseframework.inl.gov/docs/PRs/23241/coverage/combined)
- [`contact`](https://mooseframework.inl.gov/docs/PRs/23241/coverage/contact)
- [`electromagnetics`](https://mooseframework.inl.gov/docs/PRs/23241/coverage/electromagnetics)
- [`external_petsc_solver`](https://mooseframework.inl.gov/docs/PRs/23241/coverage/external_petsc_solver)
- [`fluid_properties`](https://mooseframework.inl.gov/docs/PRs/23241/coverage/fluid_properties)
- [`fsi`](https://mooseframework.inl.gov/docs/PRs/23241/coverage/fsi)
- [`functional_expansion_tools`](https://mooseframework.inl.gov/docs/PRs/23241/coverage/functional_expansion_tools)
- [`geochemistry`](https://mooseframework.inl.gov/docs/PRs/23241/coverage/geochemistry)
- [`heat_conduction`](https://mooseframework.inl.gov/docs/PRs/23241/coverage/heat_conduction)
- [`level_set`](https://mooseframework.inl.gov/docs/PRs/23241/coverage/level_set)
- [`misc`](https://mooseframework.inl.gov/docs/PRs/23241/coverage/misc)
- [`navier_stokes`](https://mooseframework.inl.gov/docs/PRs/23241/coverage/navier_stokes)
- [`optimization`](https://mooseframework.inl.gov/docs/PRs/23241/coverage/optimization)
- [`peridynamics`](https://mooseframework.inl.gov/docs/PRs/23241/coverage/peridynamics)
- [`phase_field`](https://mooseframework.inl.gov/docs/PRs/23241/coverage/phase_field)
- [`porous_flow`](https://mooseframework.inl.gov/docs/PRs/23241/coverage/porous_flow)
- [`ray_tracing`](https://mooseframework.inl.gov/docs/PRs/23241/coverage/ray_tracing)
- [`rdg`](https://mooseframework.inl.gov/docs/PRs/23241/coverage/rdg)
- [`reactor`](https://mooseframework.inl.gov/docs/PRs/23241/coverage/reactor)
- [`richards`](https://mooseframework.inl.gov/docs/PRs/23241/coverage/richards)
- [`scalar_transport`](https://mooseframework.inl.gov/docs/PRs/23241/coverage/scalar_transport)
- [`solid_properties`](https://mooseframework.inl.gov/docs/PRs/23241/coverage/solid_properties)
- [`stochastic_tools`](https://mooseframework.inl.gov/docs/PRs/23241/coverage/stochastic_tools)
- [`tensor_mechanics`](https://mooseframework.inl.gov/docs/PRs/23241/coverage/tensor_mechanics)
- [`thermal_hydraulics`](https://mooseframework.inl.gov/docs/PRs/23241/coverage/thermal_hydraulics)
- [`xfem`](https://mooseframework.inl.gov/docs/PRs/23241/coverage/xfem)

</details>



This comment will be updated on new commits.

2023-01-24 22:46 UTC, socratesgorilla commented
@loganharbour

2023-01-24 22:52 UTC, loganharbour requested changes

2023-01-24 22:52 UTC, loganharbour commented on python/TestHarness/TestHarness.py
> +        if os.path.exists(os.getcwd() + '/' + self.executable):
```suggestion
        if os.path.exists(os.path.join(os.getcwd(), self.executable)):
```

2023-01-31 21:51 UTC, loganharbour approved these changes

2023-02-01 21:09 UTC, merged