Add moose-opt (combined-opt) INL HPC instructions
idaholab/moose pull request #23355
Opened 2023-02-06 20:02 UTC by milljm

Add inl_hpc_prebuilt_moose.md. Detailing instructions on how to use `moose-opt` and how to view the results.

Fix grammar in clone_moose.md

Closes #23351

2023-02-06 21:58 UTC, moosebuild commented
Job [Documentation](https://civet.inl.gov/job/1334319/) on 184ac1a wanted to post the following:

View the site [here](https://mooseframework.inl.gov/docs/PRs/23355/site)

This comment will be updated on new commits.

2023-02-07 01:11 UTC, GiudGiud commented
Awesome! This will facilitate trainings like the one we gave at NIST.

2023-02-07 13:12 UTC, milljm commented
There are more changes incoming.

2023-02-07 17:46 UTC, moosebuild commented
Job [Coverage](https://civet.inl.gov/job/1337355/) on 41acc7a wanted to post the following:


## Framework coverage

<table>
  <thead>
    <tr>
      <th></th>
      <th>982f25</th>
      <th colspan=4>#23355 41acc7</th>
    </tr>
    <tr>
      <th></th>
      <th>Total</th>
      <th>Total</th>
      <th>+/-</th>
      <th>New</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><b>Rate</b></td>
      <td>84.70%</td>
      <td>84.70%</td>
      <td>+0.00%</td>
      <td>-</td>
    </tr>
    <tr>
      <td><b>Hits</b></td>
      <td>82862</td>
      <td>82865</td>
      <td>+3</td>
      <td>0</td>
    </tr>
    <tr>
      <td><b>Misses</b></td>
      <td>14966</td>
      <td>14963</td>
      <td>-3</td>
      <td>0</td>
    </tr>
  </tbody>
</table>

[Diff coverage report](https://mooseframework.inl.gov/docs/PRs/23355/coverage_diff/framework)

[Full coverage report](https://mooseframework.inl.gov/docs/PRs/23355/coverage/framework)


## Modules coverage

Coverage did not change

## Full coverage reports

<details>
<summary>Reports</summary>

- [`framework`](https://mooseframework.inl.gov/docs/PRs/23355/coverage/framework)
- [`chemical_reactions`](https://mooseframework.inl.gov/docs/PRs/23355/coverage/chemical_reactions)
- [`combined`](https://mooseframework.inl.gov/docs/PRs/23355/coverage/combined)
- [`contact`](https://mooseframework.inl.gov/docs/PRs/23355/coverage/contact)
- [`electromagnetics`](https://mooseframework.inl.gov/docs/PRs/23355/coverage/electromagnetics)
- [`external_petsc_solver`](https://mooseframework.inl.gov/docs/PRs/23355/coverage/external_petsc_solver)
- [`fluid_properties`](https://mooseframework.inl.gov/docs/PRs/23355/coverage/fluid_properties)
- [`fsi`](https://mooseframework.inl.gov/docs/PRs/23355/coverage/fsi)
- [`functional_expansion_tools`](https://mooseframework.inl.gov/docs/PRs/23355/coverage/functional_expansion_tools)
- [`geochemistry`](https://mooseframework.inl.gov/docs/PRs/23355/coverage/geochemistry)
- [`heat_conduction`](https://mooseframework.inl.gov/docs/PRs/23355/coverage/heat_conduction)
- [`level_set`](https://mooseframework.inl.gov/docs/PRs/23355/coverage/level_set)
- [`misc`](https://mooseframework.inl.gov/docs/PRs/23355/coverage/misc)
- [`navier_stokes`](https://mooseframework.inl.gov/docs/PRs/23355/coverage/navier_stokes)
- [`optimization`](https://mooseframework.inl.gov/docs/PRs/23355/coverage/optimization)
- [`peridynamics`](https://mooseframework.inl.gov/docs/PRs/23355/coverage/peridynamics)
- [`phase_field`](https://mooseframework.inl.gov/docs/PRs/23355/coverage/phase_field)
- [`porous_flow`](https://mooseframework.inl.gov/docs/PRs/23355/coverage/porous_flow)
- [`ray_tracing`](https://mooseframework.inl.gov/docs/PRs/23355/coverage/ray_tracing)
- [`rdg`](https://mooseframework.inl.gov/docs/PRs/23355/coverage/rdg)
- [`reactor`](https://mooseframework.inl.gov/docs/PRs/23355/coverage/reactor)
- [`richards`](https://mooseframework.inl.gov/docs/PRs/23355/coverage/richards)
- [`scalar_transport`](https://mooseframework.inl.gov/docs/PRs/23355/coverage/scalar_transport)
- [`solid_properties`](https://mooseframework.inl.gov/docs/PRs/23355/coverage/solid_properties)
- [`stochastic_tools`](https://mooseframework.inl.gov/docs/PRs/23355/coverage/stochastic_tools)
- [`tensor_mechanics`](https://mooseframework.inl.gov/docs/PRs/23355/coverage/tensor_mechanics)
- [`thermal_hydraulics`](https://mooseframework.inl.gov/docs/PRs/23355/coverage/thermal_hydraulics)
- [`xfem`](https://mooseframework.inl.gov/docs/PRs/23355/coverage/xfem)

</details>



This comment will be updated on new commits.

2023-02-08 20:39 UTC, cticenhour requested changes

2023-02-08 20:39 UTC, cticenhour commented on modules/doc/content/getting_started/installation/clone_moose.md
> +there using [git](https://git-scm.com/). We recommend creating a directory named projects to put all
```suggestion
there using [git](https://git-scm.com/). We recommend creating a directory named "projects" to put all
```

2023-02-08 20:39 UTC, cticenhour commented on modules/doc/content/getting_started/installation/index.md
> +system/platform or your desired method and follow the instructions:
```suggestion
system, platform, or your desired method and follow the instructions:
```

2023-02-08 20:39 UTC, cticenhour commented on modules/doc/content/getting_started/installation/inl_hpc_prebuilt_moose.md
> +built versions of MOOSE. To request access to these clusters, please follow the instructions on
```suggestion
While operating on one of the [!ac](INL) [!ac](HPC) clusters, there exists the option of using pre-built 
versions of MOOSE. To request access to these clusters, please follow the instructions on
```

2023-02-08 20:39 UTC, cticenhour commented on modules/doc/content/getting_started/installation/inl_hpc_prebuilt_moose.md
> +If you receive an error about modules not known, please make sure you are logged into either
```suggestion
If you receive an error about modules not being known, please make sure you are logged into either
```

2023-02-08 20:39 UTC, cticenhour commented on modules/doc/content/getting_started/installation/inl_hpc_prebuilt_moose.md
> +on it, and you will be presented within your web browser, your GUI Desktop. From here, you can open
```suggestion
on it, and you will be presented a [!ac](GUI) desktop within your web browser. From here, you can open
```

2023-02-08 20:39 UTC, cticenhour commented on modules/doc/content/getting_started/installation/inl_hpc_prebuilt_moose.md
> +To use Paraview, open a terminal by: Clicking `Applications` at the top left, then click
```suggestion
To use Paraview, open a terminal by clicking `Applications` at the top left, then click
```

2023-02-08 20:39 UTC, cticenhour commented on modules/doc/content/getting_started/installation/install_conda_moose.md
> +Create a unique conda environment for moose, named `moose`, and install the moose dependency
```suggestion
Create a unique conda environment for [!ac](MOOSE), named `moose`, and install the MOOSE dependency
```

2023-02-08 20:39 UTC, cticenhour commented on modules/doc/content/getting_started/installation/install_miniconda.md
> +Now that we can execute `mamba`, initailize it and then exit the terminal:
```suggestion
Now that we can execute `mamba`, initialize it and then exit the terminal:
```

2023-02-08 20:39 UTC, cticenhour commented on modules/doc/content/getting_started/installation/manual_installation_llvm.md
> +!include installation/install_peacock.md
Since this is used twice - is it better to put this content in a single file we include? Even if it results in some patching pain.

2023-02-08 20:39 UTC, cticenhour commented on modules/doc/content/help/faq/conda_issues.md
> +section, for what may look familiar, and follow those instructions:
```suggestion
section for what may look familiar, and follow those instructions:
```

2023-02-08 20:39 UTC, cticenhour commented on modules/doc/content/help/faq/conda_issues.md
> +  also mean your conda resource file (~/.condarc) is in bad shape. We have no way of diagnosing this
```suggestion
  also mean your conda resource file (`~/.condarc`) is in bad shape. We have no way of diagnosing this
```

2023-02-08 20:39 UTC, cticenhour commented on modules/doc/content/help/faq/conda_issues.md
> +  The quick fix-attempt, is to delete the faulty environment and re-install it again:
```suggestion
  The quick fix-attempt, is to delete the faulty environment and re-install it:
```

2023-02-09 03:45 UTC, cticenhour approved these changes
There doesn't appear to be a Griffin patch (I can make one shortly). 

Patches to RELAP-7, Sockeye, and Mastodon ready for a submodule update on merge.

2023-02-09 04:17 UTC, cticenhour commented
Griffin patch is ready for a submodule update: https://github.inl.gov/ncrc/griffin/pull/1056

I think we're ready to go here in the morning.

2023-02-09 13:16 UTC, milljm commented
> Griffin patch is ready for a submodule update: https://github.inl.gov/ncrc/griffin/pull/1056
> 
> I think we're ready to go here in the morning.

I had one created... this one: https://github.inl.gov/ncrc/griffin/issues/1054

2023-02-09 16:02 UTC, merged