Add the initial WebServerControl
idaholab/moose pull request #23361
Opened 2023-02-07 04:27 UTC by friedmud

Initial implementation of the `WebServerControl`

See the docs for the object (once it builds) for a full explanation.  What it does is start a webserver that exposes a REST API so that any external application/script can Control the execution of MOOSE.

Right now there are four things you can do:
- See if MOOSE is waiting for external input
- Set the value of a controlled variable
- Get the value of any Postprocessor
- Tell MOOSE to continue solving

This is only the beginning of this capability - look for more to come as people need it

refs #23359

2023-02-07 04:33 UTC, friedmud commented
A couple of things this still needs:

- [ ] Finish the test.  It's all there - just need to make a `Python` test and then put the execution of the script in the Python file.  I just don't have time tonight.

- [ ] A _bit_ of authentication.  Not much - probably just a `password` parameter that comes from the input file will be enough.

Note: this is _regular_ http - it is not secure.  It is fine if you're running both things on the same box... but if you are connecting remotely then you will need to open an ssh tunnel to tunnel the traffic through so it is not interceptable.

2023-02-07 06:41 UTC, moosebuild commented
Job [Documentation](https://civet.inl.gov/job/1336091/) on ca26e93 wanted to post the following:

View the site [here](https://mooseframework.inl.gov/docs/PRs/23361/site)

This comment will be updated on new commits.

2023-02-07 09:56 UTC, moosebuild commented
Job [Coverage](https://civet.inl.gov/job/1336459/) on 2a23e88 wanted to post the following:


## Framework coverage

<table>
  <thead>
    <tr>
      <th></th>
      <th>11b387</th>
      <th colspan=4>#23361 2a23e8</th>
    </tr>
    <tr>
      <th></th>
      <th>Total</th>
      <th>Total</th>
      <th>+/-</th>
      <th>New</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><b>Rate</b></td>
      <td>84.70%</td>
      <td>84.66%</td>
      <td>-0.04%</td>
      <td>11.54%</td>
    </tr>
    <tr>
      <td><b>Hits</b></td>
      <td>82845</td>
      <td>82851</td>
      <td>+6</td>
      <td>6</td>
    </tr>
    <tr>
      <td><b>Misses</b></td>
      <td>14965</td>
      <td>15011</td>
      <td>+46</td>
      <td>46</td>
    </tr>
  </tbody>
</table>

[Diff coverage report](https://mooseframework.inl.gov/docs/PRs/23361/coverage_diff/framework)

[Full coverage report](https://mooseframework.inl.gov/docs/PRs/23361/coverage/framework)


## Modules coverage

Coverage did not change

## Full coverage reports

<details>
<summary>Reports</summary>

- [`framework`](https://mooseframework.inl.gov/docs/PRs/23361/coverage/framework)
- [`chemical_reactions`](https://mooseframework.inl.gov/docs/PRs/23361/coverage/chemical_reactions)
- [`combined`](https://mooseframework.inl.gov/docs/PRs/23361/coverage/combined)
- [`contact`](https://mooseframework.inl.gov/docs/PRs/23361/coverage/contact)
- [`electromagnetics`](https://mooseframework.inl.gov/docs/PRs/23361/coverage/electromagnetics)
- [`external_petsc_solver`](https://mooseframework.inl.gov/docs/PRs/23361/coverage/external_petsc_solver)
- [`fluid_properties`](https://mooseframework.inl.gov/docs/PRs/23361/coverage/fluid_properties)
- [`fsi`](https://mooseframework.inl.gov/docs/PRs/23361/coverage/fsi)
- [`functional_expansion_tools`](https://mooseframework.inl.gov/docs/PRs/23361/coverage/functional_expansion_tools)
- [`geochemistry`](https://mooseframework.inl.gov/docs/PRs/23361/coverage/geochemistry)
- [`heat_conduction`](https://mooseframework.inl.gov/docs/PRs/23361/coverage/heat_conduction)
- [`level_set`](https://mooseframework.inl.gov/docs/PRs/23361/coverage/level_set)
- [`misc`](https://mooseframework.inl.gov/docs/PRs/23361/coverage/misc)
- [`navier_stokes`](https://mooseframework.inl.gov/docs/PRs/23361/coverage/navier_stokes)
- [`optimization`](https://mooseframework.inl.gov/docs/PRs/23361/coverage/optimization)
- [`peridynamics`](https://mooseframework.inl.gov/docs/PRs/23361/coverage/peridynamics)
- [`phase_field`](https://mooseframework.inl.gov/docs/PRs/23361/coverage/phase_field)
- [`porous_flow`](https://mooseframework.inl.gov/docs/PRs/23361/coverage/porous_flow)
- [`ray_tracing`](https://mooseframework.inl.gov/docs/PRs/23361/coverage/ray_tracing)
- [`rdg`](https://mooseframework.inl.gov/docs/PRs/23361/coverage/rdg)
- [`reactor`](https://mooseframework.inl.gov/docs/PRs/23361/coverage/reactor)
- [`richards`](https://mooseframework.inl.gov/docs/PRs/23361/coverage/richards)
- [`scalar_transport`](https://mooseframework.inl.gov/docs/PRs/23361/coverage/scalar_transport)
- [`solid_properties`](https://mooseframework.inl.gov/docs/PRs/23361/coverage/solid_properties)
- [`stochastic_tools`](https://mooseframework.inl.gov/docs/PRs/23361/coverage/stochastic_tools)
- [`tensor_mechanics`](https://mooseframework.inl.gov/docs/PRs/23361/coverage/tensor_mechanics)
- [`thermal_hydraulics`](https://mooseframework.inl.gov/docs/PRs/23361/coverage/thermal_hydraulics)
- [`xfem`](https://mooseframework.inl.gov/docs/PRs/23361/coverage/xfem)

</details>

## Warnings

- `framework` new line coverage rate 11.54% is less than the suggested 90.0%



This comment will be updated on new commits.

2023-02-07 14:17 UTC, loganharbour requested changes
New TestHarness tester?

2023-02-07 15:40 UTC, friedmud commented
Yeah - is that thing @socratesgorilla did in yet?  That's what I need: just the ability to run a Python script as a test (and then do a CSV diff)

Testing this will also require that we have the Python "requests" package... which we should add as a dependency of our moose package in Conda.

2023-02-07 16:29 UTC, dschwen commented
This adds a _second_ JSON library to MOSOE contrib?

2023-02-07 16:36 UTC, socratesgorilla commented
> Yeah - is that thing @socratesgorilla did in yet? That's what I need: just the ability to run a Python script as a test (and then do a CSV diff)
> 
> Testing this will also require that we have the Python "requests" package... which we should add as a dependency of our moose package in Conda.

The custom script logic is in MOOSE, just add `custom_evaluation_script = "myscript.py"` to your tests file. myscript.py should contain a function `check_output(output)` that does the logic, `output` is the stdout log of the test

2023-02-07 18:19 UTC, friedmud commented
> This adds a _second_ JSON library to MOOSE contrib?

Yeah - there was no way around that for now.  It's intertwined in that server code.  Just think of it as _part_ of the server code ;-).  If someone has some free time and wants to dig through it and replace it with our other json library that's fine... but I also think it's ok to have this truly tiny json library.

I think it's worth it for what we get.  But I'm open to suggestions of alternatives!

2023-02-07 20:51 UTC, cticenhour commented
@friedmud `requests` added to `moose-test-tools` (and therefore `moose-tools`) recipe as of 9692e93

2023-02-07 20:53 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/1338769/) on 9692e93 wanted to post the following:

A change of the following file(s) triggered this check:

  conda/tools

The following file(s) are unchanged:

  conda/mpich/conda_build_config.yaml

The conda build config was not changed but one or more of its dependencies have changed

2023-02-07 20:58 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/1338811/) on 8c3bc12 wanted to post the following:

A change of the following file(s) triggered this check:

  conda/tools

The following file(s) are unchanged:

  conda/mpich/conda_build_config.yaml

The conda build config was not changed but one or more of its dependencies have changed

2023-02-07 21:10 UTC, cticenhour commented on modules/doc/content/newsletter/2023/2023_02.md
> +A new [/Control.md] object called [/WebServerControl.md] was added to the framework that allows for external control of a MOOSE-based simulation.
```suggestion
A new [/Controls/index.md] object called [/WebServerControl.md] was added to the framework that allows for external control of a MOOSE-based simulation.
```

2023-02-08 00:17 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/1339496/) on 696d4e0 wanted to post the following:

A change of the following file(s) triggered this check:

  conda/tools

The following file(s) are unchanged:

  conda/mpich/conda_build_config.yaml

The conda build config was not changed but one or more of its dependencies have changed

2023-02-22 21:53 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/1369810/) on 6b6688e wanted to post the following:

A change of the following file(s) triggered this check:

  conda/tools

The following file(s) are unchanged:

  conda/mpich/conda_build_config.yaml

The conda build config was not changed but one or more of its dependencies have changed

2023-03-03 16:28 UTC, friedmud commented
Hmmm.  I don't quite no how to handle these test failures.  They are failing because the socket is already used.  I'm guessing that it's because multiple testers are running in parallel?  Any thoughts @milljm @loganharbour ?

2023-03-03 17:03 UTC, dschwen commented
Don't all tests in the same directory already run in serial (`parallel_scheduling` in `Tester.py` defaults to `False`)

2023-03-03 17:08 UTC, dschwen commented
This would be a lot cooler using websockets instead of busy waiting. Maybe sometime in the future ...

2023-03-03 17:59 UTC, friedmud commented
@dschwen this webserver does already have websocket support.  I chose not to use it for now due to wanting this to be simple to start... and to have maximum compatibility with everything out there (some people are going to call it from Matlab - I don't know about Matlab websocket support - but I know it can use a REST API).

After it goes in... feel free to try out the websocket support... we accept pull requests!

2023-09-28 05:39 UTC, closed without merging