Update citation for Reactor module
idaholab/moose pull request #23423
Opened 2023-02-14 16:57 UTC by GiudGiud

refs #23422

2023-02-14 16:57 UTC, GiudGiud commented
@eshemon fyi

2023-02-14 17:00 UTC, eshemon commented
thanks @GiudGiud!

2023-02-14 18:51 UTC, moosebuild commented
Job [Documentation](https://civet.inl.gov/job/1348143/) on 6a94198 wanted to post the following:

View the site [here](https://mooseframework.inl.gov/docs/PRs/23423/site)

This comment will be updated on new commits.

2023-02-15 16:26 UTC, cticenhour requested changes
One suggested change.

2023-02-15 16:26 UTC, cticenhour commented on modules/doc/content/citing.md
> +@article{doi:10.1080/00295639.2022.2149231,
```suggestion
@article{shemon2023reactor,
```
To make the label more readable.

2023-02-15 16:44 UTC, cticenhour approved these changes

2023-02-15 18:23 UTC, merged