Implement computeResidualAndJacobian for a few non-AD objects
idaholab/moose pull request #23488
Opened 2023-02-20 18:48 UTC by hugary1995

Kernel, InterfaceKernel, NodalBC and IntegratedBC

ref #23487

2023-02-20 20:48 UTC, moosebuild commented
Job [Documentation](https://civet.inl.gov/job/1362080/) on dea50a1 wanted to post the following:

View the site [here](https://mooseframework.inl.gov/docs/PRs/23488/site)

This comment will be updated on new commits.

2023-02-20 22:30 UTC, dschwen commented
Ok, I suppose the benefit here is that we evaluate material properties once for both the residual and the Jacobian?

2023-02-20 22:46 UTC, hugary1995 commented
Yes. I briefly discussed that in the issue description (I should probably do that in the PR description as well). 

This strategy is attractive only when
1. the residual evaluation is approximately as expensive as the Jacobian evaluation;
2. we can avoid a lot of computation by evaluating residual and Jacobian together.

The "expensive material evaluation" is one scenario that satisfies the above two conditions. AD is another scenario apparently.

2023-02-20 22:54 UTC, hugary1995 commented
The caveat is that we need an additional Jacobian evaluation for the final convergence check if we compute residual and Jacobian together. So for example, suppose at a given time step there are N nonlinear iterations. If we compute residual and Jacobian separately, we only need N residual evaluations + (N-1) Jacobian evaluations. However, if we compute the residual and Jacobian together, we will need N "residual+Jacobian" evaluations. Therefore, this "residual_and_jacobian_together" option is more advantageous when N gets large. 

But how large does N has to be for this option to be preferrable? That depends on how much computational cost we can avoid by evaluation residual and Jacobian together. If the cost of one "residual+Jacobian" evaluation is as expensive as one Jacobian evaluation (for example, when the cost of material evaluation dominates), then this option will always be faster.

I'll add this discussion in the docs if you guys encourage this PR.

2023-02-21 01:33 UTC, moosebuild commented
Job [Coverage](https://civet.inl.gov/job/1364037/) on 2fe2a6e wanted to post the following:


## Framework coverage

<table>
  <thead>
    <tr>
      <th></th>
      <th>3fddbb</th>
      <th colspan=4>#23488 2fe2a6</th>
    </tr>
    <tr>
      <th></th>
      <th>Total</th>
      <th>Total</th>
      <th>+/-</th>
      <th>New</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><b>Rate</b></td>
      <td>84.72%</td>
      <td>84.68%</td>
      <td>-0.05%</td>
      <td>24.32%</td>
    </tr>
    <tr>
      <td><b>Hits</b></td>
      <td>82956</td>
      <td>82967</td>
      <td>+11</td>
      <td>18</td>
    </tr>
    <tr>
      <td><b>Misses</b></td>
      <td>14959</td>
      <td>15014</td>
      <td>+55</td>
      <td>56</td>
    </tr>
  </tbody>
</table>

[Diff coverage report](https://mooseframework.inl.gov/docs/PRs/23488/coverage_diff/framework)

[Full coverage report](https://mooseframework.inl.gov/docs/PRs/23488/coverage/framework)


## Modules coverage

Coverage did not change

## Full coverage reports

<details>
<summary>Reports</summary>

- [`framework`](https://mooseframework.inl.gov/docs/PRs/23488/coverage/framework)
- [`chemical_reactions`](https://mooseframework.inl.gov/docs/PRs/23488/coverage/chemical_reactions)
- [`combined`](https://mooseframework.inl.gov/docs/PRs/23488/coverage/combined)
- [`contact`](https://mooseframework.inl.gov/docs/PRs/23488/coverage/contact)
- [`electromagnetics`](https://mooseframework.inl.gov/docs/PRs/23488/coverage/electromagnetics)
- [`external_petsc_solver`](https://mooseframework.inl.gov/docs/PRs/23488/coverage/external_petsc_solver)
- [`fluid_properties`](https://mooseframework.inl.gov/docs/PRs/23488/coverage/fluid_properties)
- [`fsi`](https://mooseframework.inl.gov/docs/PRs/23488/coverage/fsi)
- [`functional_expansion_tools`](https://mooseframework.inl.gov/docs/PRs/23488/coverage/functional_expansion_tools)
- [`geochemistry`](https://mooseframework.inl.gov/docs/PRs/23488/coverage/geochemistry)
- [`heat_conduction`](https://mooseframework.inl.gov/docs/PRs/23488/coverage/heat_conduction)
- [`level_set`](https://mooseframework.inl.gov/docs/PRs/23488/coverage/level_set)
- [`misc`](https://mooseframework.inl.gov/docs/PRs/23488/coverage/misc)
- [`navier_stokes`](https://mooseframework.inl.gov/docs/PRs/23488/coverage/navier_stokes)
- [`optimization`](https://mooseframework.inl.gov/docs/PRs/23488/coverage/optimization)
- [`peridynamics`](https://mooseframework.inl.gov/docs/PRs/23488/coverage/peridynamics)
- [`phase_field`](https://mooseframework.inl.gov/docs/PRs/23488/coverage/phase_field)
- [`porous_flow`](https://mooseframework.inl.gov/docs/PRs/23488/coverage/porous_flow)
- [`ray_tracing`](https://mooseframework.inl.gov/docs/PRs/23488/coverage/ray_tracing)
- [`rdg`](https://mooseframework.inl.gov/docs/PRs/23488/coverage/rdg)
- [`reactor`](https://mooseframework.inl.gov/docs/PRs/23488/coverage/reactor)
- [`richards`](https://mooseframework.inl.gov/docs/PRs/23488/coverage/richards)
- [`scalar_transport`](https://mooseframework.inl.gov/docs/PRs/23488/coverage/scalar_transport)
- [`solid_properties`](https://mooseframework.inl.gov/docs/PRs/23488/coverage/solid_properties)
- [`stochastic_tools`](https://mooseframework.inl.gov/docs/PRs/23488/coverage/stochastic_tools)
- [`tensor_mechanics`](https://mooseframework.inl.gov/docs/PRs/23488/coverage/tensor_mechanics)
- [`thermal_hydraulics`](https://mooseframework.inl.gov/docs/PRs/23488/coverage/thermal_hydraulics)
- [`xfem`](https://mooseframework.inl.gov/docs/PRs/23488/coverage/xfem)

</details>

## Warnings

- `framework` new line coverage rate 24.32% is less than the suggested 90.0%



This comment will be updated on new commits.

2023-02-21 01:42 UTC, lindsayad requested changes

2023-02-21 01:42 UTC, lindsayad commented on framework/src/bcs/NodalBC.C
> +    unsigned int jvar = jvariable.number();
```suggestion
  for (const auto & [ivariable, jvariable] : ce)
  {
    const unsigned int ivar = ivariable->number();
    const unsigned int jvar = jvariable->number();
```

2023-02-21 01:42 UTC, lindsayad commented on framework/src/constraints/MortarConstraintBase.C
> +      if (_assembly.computingJacobian())
```suggestion
      if (_assembly.computingJacobian() || _assembly.computingResidualAndJacobian())
```

2023-02-21 01:42 UTC, lindsayad commented on framework/src/constraints/MortarConstraintBase.C
> +      if (_assembly.computingResidual())
```suggestion
      if (_assembly.computingResidual() || _assembly.computingResidualAndJacobian())
```

2023-02-21 01:42 UTC, lindsayad commented on framework/src/bcs/IntegratedBC.C
> +    unsigned int jvar = jvariable.number();
```suggestion
  for (const auto & [ivariable, jvariable] : ce)
  {
    const unsigned int ivar = ivariable->number();
    const unsigned int jvar = jvariable->number();
```

2023-02-21 01:42 UTC, lindsayad commented on framework/src/interfacekernels/InterfaceKernel.C
> +    unsigned int jvar = jvariable->number();
```suggestion
    const unsigned int ivar = ivariable->number();
    const unsigned int jvar = jvariable->number();
```

2023-02-21 01:42 UTC, lindsayad commented on framework/src/kernels/Kernel.C
> +  for (const auto & it : ce)
```suggestion
  for (const auto & [ivariable, jvariable] : ce)
```

2023-02-21 01:42 UTC, lindsayad commented on framework/src/kernels/Kernel.C
> +    unsigned int jvar = jvariable.number();
```suggestion
    const unsigned int ivar = ivariable.number();
    const unsigned int jvar = jvariable.number();
```

2023-02-21 01:42 UTC, lindsayad commented on framework/src/constraints/MortarConstraintBase.C
> +      if (_assembly.computingJacobian())
Ah I see what you did in `FEProblemBase.C`. Ignore

2023-02-21 01:42 UTC, lindsayad commented on framework/src/constraints/MortarConstraintBase.C
> +      if (_assembly.computingResidual())
Ah I see what you did in `FEProblemBase.C`. Ignore

2023-02-21 01:43 UTC, lindsayad commented
Definitely will want more testing

2023-02-21 02:45 UTC, hugary1995 commented
The documentation in NonlinearSystem.md already does a good job at covering the case I discussed above. So I am not adding any. Let's see what the coverage report says now...

2023-02-21 02:54 UTC, hugary1995 commented
I suppose I should also clarify that I am changing the interpretation of "computing residual", "computing Jacobian", and "computing residual and Jacobian".

Prior to this PR, the three states are mutually exclusive. There was even an assertion that "computing Jacobian" and "computing residual and Jacobian" cannot both be true.

With this PR, I am redefining "computing residual and Jacobian" in the sense that when "computing residual and Jacobian" is true, both "computing residual" and "computing Jacobian" are true. However, "computing residual" == true or "computing Jacobian" == true does not imply that "computing residual and Jacobian" is true.

I find the new definition more intuitive and easier to handle programmatically. I am open to suggestions.

2023-02-21 18:42 UTC, lindsayad commented
I am fine with the semantic changes, and I really appreciate that you've made the definitions of computing-residual, computing-jacobian, etc. consistent across `SubProblem` and `Assembly`. That is one I felt guilty about 😄

2023-02-22 23:43 UTC, hugary1995 commented
This is ready for another review. The rest of the civet failures are out of my control.

2023-02-23 20:13 UTC, lindsayad approved these changes
If I don't get any other reviews by the end of the day, then I will merge

2023-02-24 01:01 UTC, merged