Improve documentation more
idaholab/moose pull request #23505
Opened 2023-02-21 20:16 UTC by GiudGiud

Add parameter groups
Refs #20535

Add some missing stubs

Fixes some typo

2023-02-21 22:33 UTC, moosebuild commented
Job [Documentation](https://civet.inl.gov/job/1366390/) on cab9aa9 wanted to post the following:

View the site [here](https://mooseframework.inl.gov/docs/PRs/23505/site)

This comment will be updated on new commits.

2023-02-22 01:35 UTC, moosebuild commented
Job [Coverage](https://civet.inl.gov/job/1366897/) on cc5ab92 wanted to post the following:


## Framework coverage

<table>
  <thead>
    <tr>
      <th></th>
      <th>3fddbb</th>
      <th colspan=4>#23505 cc5ab9</th>
    </tr>
    <tr>
      <th></th>
      <th>Total</th>
      <th>Total</th>
      <th>+/-</th>
      <th>New</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><b>Rate</b></td>
      <td>84.72%</td>
      <td>84.72%</td>
      <td>-0.00%</td>
      <td>100.00%</td>
    </tr>
    <tr>
      <td><b>Hits</b></td>
      <td>82956</td>
      <td>82974</td>
      <td>+18</td>
      <td>29</td>
    </tr>
    <tr>
      <td><b>Misses</b></td>
      <td>14959</td>
      <td>14963</td>
      <td>+4</td>
      <td>0</td>
    </tr>
  </tbody>
</table>

[Diff coverage report](https://mooseframework.inl.gov/docs/PRs/23505/coverage_diff/framework)

[Full coverage report](https://mooseframework.inl.gov/docs/PRs/23505/coverage/framework)


## Modules coverage

### Chemical reactions

<table>
  <thead>
    <tr>
      <th></th>
      <th>3fddbb</th>
      <th colspan=4>#23505 cc5ab9</th>
    </tr>
    <tr>
      <th></th>
      <th>Total</th>
      <th>Total</th>
      <th>+/-</th>
      <th>New</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><b>Rate</b></td>
      <td>92.85%</td>
      <td>92.85%</td>
      <td>-</td>
      <td>89.83%</td>
    </tr>
    <tr>
      <td><b>Hits</b></td>
      <td>1116</td>
      <td>1116</td>
      <td>-</td>
      <td>106</td>
    </tr>
    <tr>
      <td><b>Misses</b></td>
      <td>86</td>
      <td>86</td>
      <td>-</td>
      <td>12</td>
    </tr>
  </tbody>
</table>

[Diff coverage report](https://mooseframework.inl.gov/docs/PRs/23505/coverage_diff/chemical_reactions)

[Full coverage report](https://mooseframework.inl.gov/docs/PRs/23505/coverage/chemical_reactions)

### Contact

<table>
  <thead>
    <tr>
      <th></th>
      <th>3fddbb</th>
      <th colspan=4>#23505 cc5ab9</th>
    </tr>
    <tr>
      <th></th>
      <th>Total</th>
      <th>Total</th>
      <th>+/-</th>
      <th>New</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><b>Rate</b></td>
      <td>89.96%</td>
      <td>89.96%</td>
      <td>-</td>
      <td>86.96%</td>
    </tr>
    <tr>
      <td><b>Hits</b></td>
      <td>3314</td>
      <td>3314</td>
      <td>-</td>
      <td>40</td>
    </tr>
    <tr>
      <td><b>Misses</b></td>
      <td>370</td>
      <td>370</td>
      <td>-</td>
      <td>6</td>
    </tr>
  </tbody>
</table>

[Diff coverage report](https://mooseframework.inl.gov/docs/PRs/23505/coverage_diff/contact)

[Full coverage report](https://mooseframework.inl.gov/docs/PRs/23505/coverage/contact)

### Fluid properties

<table>
  <thead>
    <tr>
      <th></th>
      <th>3fddbb</th>
      <th colspan=4>#23505 cc5ab9</th>
    </tr>
    <tr>
      <th></th>
      <th>Total</th>
      <th>Total</th>
      <th>+/-</th>
      <th>New</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><b>Rate</b></td>
      <td>85.26%</td>
      <td>85.26%</td>
      <td>+0.00%</td>
      <td>83.33%</td>
    </tr>
    <tr>
      <td><b>Hits</b></td>
      <td>6690</td>
      <td>6692</td>
      <td>+2</td>
      <td>5</td>
    </tr>
    <tr>
      <td><b>Misses</b></td>
      <td>1157</td>
      <td>1157</td>
      <td>-</td>
      <td>1</td>
    </tr>
  </tbody>
</table>

[Diff coverage report](https://mooseframework.inl.gov/docs/PRs/23505/coverage_diff/fluid_properties)

[Full coverage report](https://mooseframework.inl.gov/docs/PRs/23505/coverage/fluid_properties)

### Functional expansion tools

<table>
  <thead>
    <tr>
      <th></th>
      <th>3fddbb</th>
      <th colspan=4>#23505 cc5ab9</th>
    </tr>
    <tr>
      <th></th>
      <th>Total</th>
      <th>Total</th>
      <th>+/-</th>
      <th>New</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><b>Rate</b></td>
      <td>83.05%</td>
      <td>83.05%</td>
      <td>-</td>
      <td>94.34%</td>
    </tr>
    <tr>
      <td><b>Hits</b></td>
      <td>926</td>
      <td>926</td>
      <td>-</td>
      <td>100</td>
    </tr>
    <tr>
      <td><b>Misses</b></td>
      <td>189</td>
      <td>189</td>
      <td>-</td>
      <td>6</td>
    </tr>
  </tbody>
</table>

[Diff coverage report](https://mooseframework.inl.gov/docs/PRs/23505/coverage_diff/functional_expansion_tools)

[Full coverage report](https://mooseframework.inl.gov/docs/PRs/23505/coverage/functional_expansion_tools)

### Phase field

<table>
  <thead>
    <tr>
      <th></th>
      <th>3fddbb</th>
      <th colspan=4>#23505 cc5ab9</th>
    </tr>
    <tr>
      <th></th>
      <th>Total</th>
      <th>Total</th>
      <th>+/-</th>
      <th>New</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><b>Rate</b></td>
      <td>89.56%</td>
      <td>89.56%</td>
      <td>-</td>
      <td>93.40%</td>
    </tr>
    <tr>
      <td><b>Hits</b></td>
      <td>12464</td>
      <td>12464</td>
      <td>-</td>
      <td>1273</td>
    </tr>
    <tr>
      <td><b>Misses</b></td>
      <td>1453</td>
      <td>1453</td>
      <td>-</td>
      <td>90</td>
    </tr>
  </tbody>
</table>

[Diff coverage report](https://mooseframework.inl.gov/docs/PRs/23505/coverage_diff/phase_field)

[Full coverage report](https://mooseframework.inl.gov/docs/PRs/23505/coverage/phase_field)

### Ray tracing

<table>
  <thead>
    <tr>
      <th></th>
      <th>3fddbb</th>
      <th colspan=4>#23505 cc5ab9</th>
    </tr>
    <tr>
      <th></th>
      <th>Total</th>
      <th>Total</th>
      <th>+/-</th>
      <th>New</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><b>Rate</b></td>
      <td>94.93%</td>
      <td>94.93%</td>
      <td>+0.00%</td>
      <td>100.00%</td>
    </tr>
    <tr>
      <td><b>Hits</b></td>
      <td>4098</td>
      <td>4101</td>
      <td>+3</td>
      <td>3</td>
    </tr>
    <tr>
      <td><b>Misses</b></td>
      <td>219</td>
      <td>219</td>
      <td>-</td>
      <td>0</td>
    </tr>
  </tbody>
</table>

[Diff coverage report](https://mooseframework.inl.gov/docs/PRs/23505/coverage_diff/ray_tracing)

[Full coverage report](https://mooseframework.inl.gov/docs/PRs/23505/coverage/ray_tracing)

### Thermal hydraulics

<table>
  <thead>
    <tr>
      <th></th>
      <th>3fddbb</th>
      <th colspan=4>#23505 cc5ab9</th>
    </tr>
    <tr>
      <th></th>
      <th>Total</th>
      <th>Total</th>
      <th>+/-</th>
      <th>New</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><b>Rate</b></td>
      <td>90.31%</td>
      <td>90.31%</td>
      <td>+0.00%</td>
      <td>100.00%</td>
    </tr>
    <tr>
      <td><b>Hits</b></td>
      <td>12349</td>
      <td>12352</td>
      <td>+3</td>
      <td>3</td>
    </tr>
    <tr>
      <td><b>Misses</b></td>
      <td>1325</td>
      <td>1325</td>
      <td>-</td>
      <td>0</td>
    </tr>
  </tbody>
</table>

[Diff coverage report](https://mooseframework.inl.gov/docs/PRs/23505/coverage_diff/thermal_hydraulics)

[Full coverage report](https://mooseframework.inl.gov/docs/PRs/23505/coverage/thermal_hydraulics)

## Full coverage reports

<details>
<summary>Reports</summary>

- [`framework`](https://mooseframework.inl.gov/docs/PRs/23505/coverage/framework)
- [`chemical_reactions`](https://mooseframework.inl.gov/docs/PRs/23505/coverage/chemical_reactions)
- [`combined`](https://mooseframework.inl.gov/docs/PRs/23505/coverage/combined)
- [`contact`](https://mooseframework.inl.gov/docs/PRs/23505/coverage/contact)
- [`electromagnetics`](https://mooseframework.inl.gov/docs/PRs/23505/coverage/electromagnetics)
- [`external_petsc_solver`](https://mooseframework.inl.gov/docs/PRs/23505/coverage/external_petsc_solver)
- [`fluid_properties`](https://mooseframework.inl.gov/docs/PRs/23505/coverage/fluid_properties)
- [`fsi`](https://mooseframework.inl.gov/docs/PRs/23505/coverage/fsi)
- [`functional_expansion_tools`](https://mooseframework.inl.gov/docs/PRs/23505/coverage/functional_expansion_tools)
- [`geochemistry`](https://mooseframework.inl.gov/docs/PRs/23505/coverage/geochemist [...]

2023-02-23 00:54 UTC, GiudGiud commented
All failures should be unrelated now.
Need a volunteer for reviewing among all the code owners

2023-02-28 19:39 UTC, GiudGiud commented
@joshuahansel can you please review?

2023-02-28 20:49 UTC, joshuahansel requested changes

2023-02-28 20:51 UTC, GiudGiud commented on modules/ray_tracing/src/userobjects/ConeRayStudy.C
> +      "directions", "The directions(s) of the cone(s) (points down the center of each cone).");
```suggestion
      "directions", "The directions(s) of the cone(s) (points down the center of each cone).");
```
```suggestion
      "directions", "The direction(s) of the cone(s) (points down the center of each cone).");
```

2023-02-28 20:51 UTC, GiudGiud commented on modules/contact/doc/content/source/constraints/CartesianMortarMechanicalContact.md
> +which are on both sides of the contact axis. c
```suggestion
which are on both sides of the contact axis.
```

2023-02-28 20:53 UTC, joshuahansel approved these changes, later dismissed

2023-02-28 22:53 UTC, GiudGiud commented
ugh lemme remove this merge commit

2023-03-01 00:27 UTC, dschwen submitted a review, later dismissed
I like the new parameter groups. Just for future reference, we now have the ability to add doc strings to individual moose enum items, just in case you're looking for more stuff to document...

2023-03-01 01:00 UTC, GiudGiud commented
looks like I ll have to wait for a devel merge before being able to address the merge conflict. 
That s ok though

2023-03-01 01:01 UTC, GiudGiud commented
> Just for future reference, we now have the ability to add doc strings to individual moose enum items, just in case you're looking for more stuff to document...

tempting...

2023-03-01 21:10 UTC, dschwen approved these changes
re-approve

2023-03-01 21:30 UTC, merged

2023-03-01 21:33 UTC, GiudGiud commented
Thanks!