Converted CSVDiff to use the SchemaDiff
idaholab/moose pull request #23561
Opened 2023-02-28 19:53 UTC by socratesgorilla

Closes #23522

2023-03-01 00:16 UTC, moosebuild commented
Job [Documentation](https://civet.inl.gov/job/1378857/) on b697ffe wanted to post the following:

View the site [here](https://mooseframework.inl.gov/docs/PRs/23561/site)

This comment will be updated on new commits.

2023-03-01 00:30 UTC, moosebuild commented
Job [Coverage](https://civet.inl.gov/job/1378871/) on b697ffe wanted to post the following:


## Framework coverage

<table>
  <thead>
    <tr>
      <th></th>
      <th>497639</th>
      <th colspan=4>#23561 b697ff</th>
    </tr>
    <tr>
      <th></th>
      <th>Total</th>
      <th>Total</th>
      <th>+/-</th>
      <th>New</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><b>Rate</b></td>
      <td>84.74%</td>
      <td>83.56%</td>
      <td>-1.19%</td>
      <td>-</td>
    </tr>
    <tr>
      <td><b>Hits</b></td>
      <td>83292</td>
      <td>82127</td>
      <td>-1165</td>
      <td>0</td>
    </tr>
    <tr>
      <td><b>Misses</b></td>
      <td>14996</td>
      <td>16161</td>
      <td>+1165</td>
      <td>0</td>
    </tr>
  </tbody>
</table>

[Diff coverage report](https://mooseframework.inl.gov/docs/PRs/23561/coverage_diff/framework)

[Full coverage report](https://mooseframework.inl.gov/docs/PRs/23561/coverage/framework)


## Modules coverage

Coverage did not change

## Full coverage reports

<details>
<summary>Reports</summary>

- [`framework`](https://mooseframework.inl.gov/docs/PRs/23561/coverage/framework)
- [`chemical_reactions`](https://mooseframework.inl.gov/docs/PRs/23561/coverage/chemical_reactions)
- [`combined`](https://mooseframework.inl.gov/docs/PRs/23561/coverage/combined)
- [`contact`](https://mooseframework.inl.gov/docs/PRs/23561/coverage/contact)
- [`electromagnetics`](https://mooseframework.inl.gov/docs/PRs/23561/coverage/electromagnetics)
- [`external_petsc_solver`](https://mooseframework.inl.gov/docs/PRs/23561/coverage/external_petsc_solver)
- [`fluid_properties`](https://mooseframework.inl.gov/docs/PRs/23561/coverage/fluid_properties)
- [`fsi`](https://mooseframework.inl.gov/docs/PRs/23561/coverage/fsi)
- [`functional_expansion_tools`](https://mooseframework.inl.gov/docs/PRs/23561/coverage/functional_expansion_tools)
- [`geochemistry`](https://mooseframework.inl.gov/docs/PRs/23561/coverage/geochemistry)
- [`heat_conduction`](https://mooseframework.inl.gov/docs/PRs/23561/coverage/heat_conduction)
- [`level_set`](https://mooseframework.inl.gov/docs/PRs/23561/coverage/level_set)
- [`misc`](https://mooseframework.inl.gov/docs/PRs/23561/coverage/misc)
- [`navier_stokes`](https://mooseframework.inl.gov/docs/PRs/23561/coverage/navier_stokes)
- [`optimization`](https://mooseframework.inl.gov/docs/PRs/23561/coverage/optimization)
- [`peridynamics`](https://mooseframework.inl.gov/docs/PRs/23561/coverage/peridynamics)
- [`phase_field`](https://mooseframework.inl.gov/docs/PRs/23561/coverage/phase_field)
- [`porous_flow`](https://mooseframework.inl.gov/docs/PRs/23561/coverage/porous_flow)
- [`ray_tracing`](https://mooseframework.inl.gov/docs/PRs/23561/coverage/ray_tracing)
- [`rdg`](https://mooseframework.inl.gov/docs/PRs/23561/coverage/rdg)
- [`reactor`](https://mooseframework.inl.gov/docs/PRs/23561/coverage/reactor)
- [`richards`](https://mooseframework.inl.gov/docs/PRs/23561/coverage/richards)
- [`scalar_transport`](https://mooseframework.inl.gov/docs/PRs/23561/coverage/scalar_transport)
- [`solid_properties`](https://mooseframework.inl.gov/docs/PRs/23561/coverage/solid_properties)
- [`stochastic_tools`](https://mooseframework.inl.gov/docs/PRs/23561/coverage/stochastic_tools)
- [`tensor_mechanics`](https://mooseframework.inl.gov/docs/PRs/23561/coverage/tensor_mechanics)
- [`thermal_hydraulics`](https://mooseframework.inl.gov/docs/PRs/23561/coverage/thermal_hydraulics)
- [`xfem`](https://mooseframework.inl.gov/docs/PRs/23561/coverage/xfem)

</details>



This comment will be updated on new commits.

2023-03-01 17:35 UTC, moosebuild commented on large_media
> +Subproject commit 4b985cd0520ccf45b89ca894e9cad646260dc5c5
**Caution!** This contains a submodule update

2023-03-01 18:47 UTC, moosebuild commented on large_media
> +Subproject commit 4b985cd0520ccf45b89ca894e9cad646260dc5c5
**Caution!** This contains a submodule update

2023-03-01 20:59 UTC, moosebuild commented
Job [Coverage](https://civet.inl.gov/job/1381868/) on b17eb4a wanted to post the following:


The following coverage requirement(s) failed:
- `stochastic_tools` coverage rate 72.07% is less than the required 88.0%

2023-03-03 23:32 UTC, moosebuild commented
Job [Coverage](https://civet.inl.gov/job/1388288/) on 4d079b4 wanted to post the following:


The following coverage requirement(s) failed:
- `stochastic_tools` coverage rate 70.05% is less than the required 88.0%

2023-03-07 18:19 UTC, moosebuild commented
Job [Coverage](https://civet.inl.gov/job/1388288/) on 4d079b4 wanted to post the following:


The following coverage requirement(s) failed:
- `stochastic_tools` coverage rate 73.90% is less than the required 88.0%

2023-03-09 22:39 UTC, socratesgorilla commented
Officially open for real review. Current failures are due to weird outputs in modules unrelated.

2023-03-21 17:10 UTC, loganharbour commented
Taking a look at this. Just invalidated tests

2023-04-06 17:05 UTC, GiudGiud commented
```
stochastic_tools/test:vectorpostprocessors/stochastic_results_complete_history.data/time:   File "/opt/civet0/build/moose/python/TestHarness/testers/SchemaDiff.py", line 116, in check_values
stochastic_tools/test:vectorpostprocessors/stochastic_results_complete_history.data/time:     elif abs(x-y)/max(abs(x), abs(y)) > self.rel_err:
stochastic_tools/test:vectorpostprocessors/stochastic_results_complete_history.data/time: ZeroDivisionError: float division by zero
```
seems there s a relative diff on something that is equal to 0.
Should not be too hard to track / fix. The schemadiff should be able to not die on this.

2023-04-06 17:22 UTC, socratesgorilla commented
> ```
> stochastic_tools/test:vectorpostprocessors/stochastic_results_complete_history.data/time:   File "/opt/civet0/build/moose/python/TestHarness/testers/SchemaDiff.py", line 116, in check_values
> stochastic_tools/test:vectorpostprocessors/stochastic_results_complete_history.data/time:     elif abs(x-y)/max(abs(x), abs(y)) > self.rel_err:
> stochastic_tools/test:vectorpostprocessors/stochastic_results_complete_history.data/time: ZeroDivisionError: float division by zero
> ```
> 
> seems there s a relative diff on something that is equal to 0. Should not be too hard to track / fix. The schemadiff should be able to not die on this.

The issue here is that apparently a bunch of stochastic tools tests that were formally outputting NaN are outputting 0, and Cody said that that should be looked into rather than changing the schemadiff to omit the differences

2023-04-06 17:27 UTC, GiudGiud commented
@zachmprince do you know what is going on here

2023-04-10 16:12 UTC, loganharbour requested changes

2023-04-10 16:12 UTC, loganharbour commented on test/tests/test_harness/csvdiff_tests
Can you not `git mv` this instead? it's very hard to tell whether or not you've removed tests or just moved them

2023-04-12 16:32 UTC, socratesgorilla commented on python/TestHarness/schedulers/RunParallel.py
> -            tester.setStatus(tester.error, 'PYTHON EXCEPTION')
yeah, this is a legitimate fix

2023-04-12 17:38 UTC, socratesgorilla commented on python/TestHarness/tests/test_Diff.py
> -        self.assertRegex(e.output.decode('utf-8'), r'test_harness\.csvdiff.*?FAILED \(CSVDIFF\)')
Superfluous with the new schemadiff tests

2023-04-12 17:40 UTC, socratesgorilla commented on python/doc/content/python/CSVDiff.md
This version of csvdiff doesn't work as a standalone cmd tool

2023-04-12 17:40 UTC, socratesgorilla commented on test/tests/test_harness/csvdiff_tests
These tests are either for removed functionality or their testing has been moved to the new CSVDiff tests

2023-04-12 18:11 UTC, socratesgorilla commented on python/TestHarness/testers/CSVDiff.py
> +        return SchemaDiff.processResults(self, moose_dir, options, output)
Whoops, this was an artifact from development -- at first I was attempting to do more in the derived class. Removed it.

2023-04-12 18:28 UTC, moosebuild commented on large_media
> +Subproject commit c01be34ae5ae098df9907b0b9980e075cbebe49f
**Caution!** This contains a submodule update

2023-04-12 18:28 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/1458304/) on 43d6f03 wanted to post the following:

A change of the following file(s) triggered this check:

  libmesh

The following file(s) are unchanged:

  conda/mpich/conda_build_config.yaml
  conda/libmesh/meta.yaml

The libmesh submodule or configuration was changed but the conda build config was not

2023-04-12 20:40 UTC, moosebuild commented
Job [Coverage](https://civet.inl.gov/job/1458485/) on 8e55f2e wanted to post the following:


The following coverage requirement(s) failed:
- `misc` coverage rate 34.31% is less than the required 55.0%
- `phase_field` coverage rate 86.27% is less than the required 89.0%
- `richards` coverage rate 94.75% is less than the required 97.0%
- `tensor_mechanics` coverage rate 85.21% is less than the required 86.0%

2023-04-12 23:15 UTC, moosebuild commented
Job [Coverage](https://civet.inl.gov/job/1459061/) on 604cfaa wanted to post the following:


The following coverage requirement(s) failed:
- `misc` coverage rate 34.31% is less than the required 55.0%
- `phase_field` coverage rate 86.27% is less than the required 89.0%
- `richards` coverage rate 94.75% is less than the required 97.0%
- `tensor_mechanics` coverage rate 85.21% is less than the required 86.0%

2023-04-14 20:15 UTC, GiudGiud commented
where do we stand here?

2023-04-14 20:31 UTC, loganharbour commented
We're standing.

Making sure that the error output is verbose enough compared to the old differ

2023-04-20 14:58 UTC, vanwdani commented
Is this ready?  I'm hoping to use #23965 sooner or later

2023-06-12 16:44 UTC, permcody commented
Closing in favor of #24633.

2023-06-12 16:44 UTC, closed without merging