Save-in capability in mesh generator which provides access to any saved moose meshes beside the final one
idaholab/moose pull request #23618
Opened 2023-03-06 17:26 UTC by MengnanLi91

This PR #23618 add save-in capability in mesh generator system. The intermediate meshes beside the final one can be saved in and accessed later by other moose objects.

## Reason

It fulfills the need to save and use the intermediate mesh object besides the final mesh file, so that the other moose objects can access the save-in meshes as needed.

## Design

In mesh generator system, the save-in capability, instead of only saving the final mesh pointer, saves the user selected mesh pointers and main mesh pointer in a map with mesh name as the key. In mesh dependency check, the save in condition is added to keep the branches with save-in tag even if it is independent from the final mesh.    

## Impact

This feature allows the user to save and use the intermediate meshes besides the final mesh file for certain physics modules as needed.

2023-03-06 17:28 UTC, MengnanLi91 commented
@loganharbour The new PR for save in mesh capability is here.

2023-03-07 15:16 UTC, loganharbour commented
We should investigate removing the call to creating a duplicated displaced mesh, I don't think it's necessary

2023-03-07 22:04 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/1394212/) on 5a624a4 wanted to post the following:

Your code requires style changes.  

A patch was auto generated and copied [here](https://mooseframework.inl.gov/docs/PRs/23618/clang_format/style.patch)  
You can directly apply the patch by running, in the top level of your repository:

`curl -s https://mooseframework.inl.gov/docs/PRs/23618/clang_format/style.patch | git apply -v`  

Alternatively, with your repository up to date and in the top level of your repository:

`git clang-format b9fd6b9b66ab977d28901a77a10cfb468a308b6e`

2023-03-08 00:05 UTC, moosebuild commented
Job [Documentation](https://civet.inl.gov/job/1394302/) on b917489 wanted to post the following:

View the site [here](https://mooseframework.inl.gov/docs/PRs/23618/site)

This comment will be updated on new commits.

2023-03-09 00:14 UTC, moosebuild commented
Job [Coverage](https://civet.inl.gov/job/1397285/) on e18f6c9 wanted to post the following:


## Framework coverage

<table>
  <thead>
    <tr>
      <th></th>
      <th>571e07</th>
      <th colspan=4>#23618 e18f6c</th>
    </tr>
    <tr>
      <th></th>
      <th>Total</th>
      <th>Total</th>
      <th>+/-</th>
      <th>New</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><b>Rate</b></td>
      <td>84.84%</td>
      <td>84.85%</td>
      <td>+0.01%</td>
      <td>93.90%</td>
    </tr>
    <tr>
      <td><b>Hits</b></td>
      <td>83989</td>
      <td>84046</td>
      <td>+57</td>
      <td>77</td>
    </tr>
    <tr>
      <td><b>Misses</b></td>
      <td>15004</td>
      <td>15004</td>
      <td>-</td>
      <td>5</td>
    </tr>
  </tbody>
</table>

[Diff coverage report](https://mooseframework.inl.gov/docs/PRs/23618/coverage_diff/framework)

[Full coverage report](https://mooseframework.inl.gov/docs/PRs/23618/coverage/framework)


## Modules coverage

### Peridynamics

<table>
  <thead>
    <tr>
      <th></th>
      <th>571e07</th>
      <th colspan=4>#23618 e18f6c</th>
    </tr>
    <tr>
      <th></th>
      <th>Total</th>
      <th>Total</th>
      <th>+/-</th>
      <th>New</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><b>Rate</b></td>
      <td>78.18%</td>
      <td>78.16%</td>
      <td>-0.02%</td>
      <td>0.00%</td>
    </tr>
    <tr>
      <td><b>Hits</b></td>
      <td>2999</td>
      <td>2999</td>
      <td>-</td>
      <td>0</td>
    </tr>
    <tr>
      <td><b>Misses</b></td>
      <td>837</td>
      <td>838</td>
      <td>+1</td>
      <td>2</td>
    </tr>
  </tbody>
</table>

[Diff coverage report](https://mooseframework.inl.gov/docs/PRs/23618/coverage_diff/peridynamics)

[Full coverage report](https://mooseframework.inl.gov/docs/PRs/23618/coverage/peridynamics)

## Full coverage reports

<details>
<summary>Reports</summary>

- [`framework`](https://mooseframework.inl.gov/docs/PRs/23618/coverage/framework)
- [`chemical_reactions`](https://mooseframework.inl.gov/docs/PRs/23618/coverage/chemical_reactions)
- [`combined`](https://mooseframework.inl.gov/docs/PRs/23618/coverage/combined)
- [`contact`](https://mooseframework.inl.gov/docs/PRs/23618/coverage/contact)
- [`electromagnetics`](https://mooseframework.inl.gov/docs/PRs/23618/coverage/electromagnetics)
- [`external_petsc_solver`](https://mooseframework.inl.gov/docs/PRs/23618/coverage/external_petsc_solver)
- [`fluid_properties`](https://mooseframework.inl.gov/docs/PRs/23618/coverage/fluid_properties)
- [`fsi`](https://mooseframework.inl.gov/docs/PRs/23618/coverage/fsi)
- [`functional_expansion_tools`](https://mooseframework.inl.gov/docs/PRs/23618/coverage/functional_expansion_tools)
- [`geochemistry`](https://mooseframework.inl.gov/docs/PRs/23618/coverage/geochemistry)
- [`heat_conduction`](https://mooseframework.inl.gov/docs/PRs/23618/coverage/heat_conduction)
- [`level_set`](https://mooseframework.inl.gov/docs/PRs/23618/coverage/level_set)
- [`misc`](https://mooseframework.inl.gov/docs/PRs/23618/coverage/misc)
- [`navier_stokes`](https://mooseframework.inl.gov/docs/PRs/23618/coverage/navier_stokes)
- [`optimization`](https://mooseframework.inl.gov/docs/PRs/23618/coverage/optimization)
- [`peridynamics`](https://mooseframework.inl.gov/docs/PRs/23618/coverage/peridynamics)
- [`phase_field`](https://mooseframework.inl.gov/docs/PRs/23618/coverage/phase_field)
- [`porous_flow`](https://mooseframework.inl.gov/docs/PRs/23618/coverage/porous_flow)
- [`ray_tracing`](https://mooseframework.inl.gov/docs/PRs/23618/coverage/ray_tracing)
- [`rdg`](https://mooseframework.inl.gov/docs/PRs/23618/coverage/rdg)
- [`reactor`](https://mooseframework.inl.gov/docs/PRs/23618/coverage/reactor)
- [`richards`](https://mooseframework.inl.gov/docs/PRs/23618/coverage/richards)
- [`scalar_transport`](https://mooseframework.inl.gov/docs/PRs/23618/coverage/scalar_transport)
- [`solid_properties`](https://mooseframework.inl.gov/docs/PRs/23618/coverage/solid_properties)
- [`stochastic_tools`](https://mooseframework.inl.gov/docs/PRs/23618/coverage/stochastic_tools)
- [`tensor_mechanics`](https://mooseframework.inl.gov/docs/PRs/23618/coverage/tensor_mechanics)
- [`thermal_hydraulics`](https://mooseframework.inl.gov/docs/PRs/23618/coverage/thermal_hydraulics)
- [`xfem`](https://mooseframework.inl.gov/docs/PRs/23618/coverage/xfem)

</details>

## Warnings

- `peridynamics` new line coverage rate 0.00% is less than the suggested 90.0%



This comment will be updated on new commits.

2023-03-09 15:54 UTC, moosebuild commented
Job [App documentation](https://civet.inl.gov/job/1397248/) on e18f6c9 : invalidated by @MengnanLi91

2023-03-09 17:49 UTC, MengnanLi91 commented
@loganharbour This one is ready for review! Thanks a lot!

2023-03-09 19:48 UTC, GiudGiud commented
Needs to be rebased on devel and Logan's commits must be removed.
This isnt happening automatically because Logan rebased his PR to deal with merge conflict, so his commits in devel dont match the commits that you rebased on when you rebased on his PR

2023-03-09 19:49 UTC, loganharbour commented
@MengnanLi91 you should reset this like we did with another PR yesterday:

```
git fetch upstream
git reset --hard upstream/devel
git cherry-pick eb6e5db709f701fc9879ab054b7e5768ad566ebc^..e18f6c9044239f9e99751a91699cb0714f5bf451
```

where that range of commits is the range of commits that are yours

2023-03-15 17:07 UTC, moosebuild commented
Job [Coverage](https://civet.inl.gov/job/1404783/) on 535b8c2 wanted to post the following:


The following coverage requirement(s) failed:
- Failed to generate `framework` coverage rate (required: 81.0%)

2023-03-15 19:46 UTC, loganharbour commented
Will review soon; waiting on coverage. should be running now

2023-03-16 16:03 UTC, loganharbour requested changes

2023-03-16 16:03 UTC, loganharbour commented on test/src/meshgenerators/TestSaveInMesh.C
I think that instead of making this a MeshGenerator, it should be a UserObject. it also doesn't need nemesis support. we're trying to test the action of the system, not exodus/nemesis output

2023-03-21 14:46 UTC, loganharbour commented
Can you please resolve the things that you explicitly addressed and answer the questions?

2023-03-21 15:08 UTC, MengnanLi91 commented on framework/include/mesh/MooseMesh.h
> +  void setSavedMesh(std::string, std::unique_ptr<MeshBase> mesh);
This function has been deleted.

2023-03-21 15:13 UTC, MengnanLi91 commented on test/tests/meshgenerators/save_in_meshes/tests
> +      requirement = "The system shall save a mesh that is indenpendent from final mesh generator"
This has been combined with the first test case

2023-03-21 15:15 UTC, MengnanLi91 commented on test/tests/meshgenerators/save_in_meshes/tests
> +      detail = 'Output only the A mesh block in a seperate mesh file in distributed mesh mode.'
This test is removed

2023-03-21 15:18 UTC, MengnanLi91 commented on framework/src/base/MeshGeneratorSystem.C
> +  for (auto & [name, mesh_ptr] : to_save_in_meshes)
This has bee done.

2023-03-21 15:19 UTC, MengnanLi91 commented on framework/src/mesh/MeshGeneratorMesh.C
> +  }
This should be hit now with the new test case 1

2023-03-21 17:47 UTC, loganharbour requested changes
All good after this!

2023-03-21 17:47 UTC, loganharbour commented on framework/include/actions/ActionWarehouse.h
> +
```suggestion
```

These look unused too

2023-03-21 17:47 UTC, loganharbour commented on framework/src/base/MeshGeneratorSystem.C
> +        std::find_if(save_in_generators.begin(),
It looks like this still isn't hit?

2023-03-21 17:47 UTC, loganharbour commented on framework/src/base/MeshGeneratorSystem.C
> +  // Grab the outputs from the final generator so MeshGeneratorMesh can pick them up
```suggestion
  // Grab the outputs from the final generator so MeshGeneratorMesh can pick it up
```

2023-03-21 17:47 UTC, loganharbour commented on framework/src/base/MeshGeneratorSystem.C
> +               "', said mesh has already been retreived");
Please test these errors too

2023-03-22 15:45 UTC, MengnanLi91 commented on framework/src/base/MeshGeneratorSystem.C
> +               "', said mesh has already been retreived");
I add two tests for these errors.

2023-03-22 20:31 UTC, loganharbour approved these changes

2023-03-22 20:32 UTC, merged

2023-04-10 22:40 UTC, GiudGiud commented
How does this work?

It seems adding save_with_name to a MG does not do anything.
Adding `outputs = true` does what I want though. Is there an overlap?

2023-04-10 22:46 UTC, GiudGiud commented
also it seems none of the commits reference an issue?

2023-04-10 23:17 UTC, MengnanLi91 commented
> 
We try to avoid an overlap with output intermedia mesh capability therefore `save_in_mesh` option only saves the mesh pointer in memory which can be accessed using _app.getMeshGeneratorSystem().getSavedMeshNames() and _app.getMeshGeneratorSystem().getSavedMesh(). This is an intermedia step for radiative heat transfer in the gap region(no main mesh and plan to cover with overlay mesh). We want to have an overlay mesh beside the main mesh and save both meshes in memory. The raytracing module can access and only use overlay mesh while other physics modules can use main mesh for simulation. The part I am working on is to build communications between these two meshes. This may be used for multiApp so that they can access different meshes saved in memory I guess?

2023-04-10 23:23 UTC, GiudGiud commented
Ok thanks for the explanation. I ll make a few changes to reflect that if you don't mind