Have a better error message for the classic case of a broken tree of MGs
idaholab/moose pull request #23683
Opened 2023-03-09 20:01 UTC by GiudGiud

refs #23641
 Already tested in tests/mgs/final_mg

2023-03-09 20:04 UTC, loganharbour requested changes

2023-03-09 20:04 UTC, loganharbour commented on framework/src/base/MeshGeneratorSystem.C
> +             "single final mesh. Having one wrong 'input=mg' parameter is the most common error \n"
```suggestion
             "single final mesh. Having one wrong 'input=mg' parameter is the most common error\n"
```

2023-03-09 20:04 UTC, loganharbour commented on framework/src/base/MeshGeneratorSystem.C
> +             "- if you intend to only part of the generators defined (uncommon), select the "
```suggestion
             "- if you intend to execute a subset of the defined generators (uncommon), select the "
```

2023-03-09 20:08 UTC, GiudGiud commented on framework/src/base/MeshGeneratorSystem.C
> +             "- if you intend to execute a subset of the defined generators (uncommon), select the "
```suggestion
             "- if you intend to execute a subset of the defined generators (uncommon), select the"
```

2023-03-09 22:12 UTC, moosebuild commented
Job [Documentation](https://civet.inl.gov/job/1399629/) on a79a725 wanted to post the following:

View the site [here](https://mooseframework.inl.gov/docs/PRs/23683/site)

This comment will be updated on new commits.

2023-03-09 22:26 UTC, moosebuild commented
Job [Coverage](https://civet.inl.gov/job/1399643/) on a79a725 wanted to post the following:


## Framework coverage

<table>
  <thead>
    <tr>
      <th></th>
      <th>6d8f7c</th>
      <th colspan=4>#23683 a79a72</th>
    </tr>
    <tr>
      <th></th>
      <th>Total</th>
      <th>Total</th>
      <th>+/-</th>
      <th>New</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><b>Rate</b></td>
      <td>84.83%</td>
      <td>84.83%</td>
      <td>-0.00%</td>
      <td>100.00%</td>
    </tr>
    <tr>
      <td><b>Hits</b></td>
      <td>83989</td>
      <td>83988</td>
      <td>-1</td>
      <td>1</td>
    </tr>
    <tr>
      <td><b>Misses</b></td>
      <td>15022</td>
      <td>15023</td>
      <td>+1</td>
      <td>0</td>
    </tr>
  </tbody>
</table>

[Diff coverage report](https://mooseframework.inl.gov/docs/PRs/23683/coverage_diff/framework)

[Full coverage report](https://mooseframework.inl.gov/docs/PRs/23683/coverage/framework)


## Modules coverage

Coverage did not change

## Full coverage reports

<details>
<summary>Reports</summary>

- [`framework`](https://mooseframework.inl.gov/docs/PRs/23683/coverage/framework)
- [`chemical_reactions`](https://mooseframework.inl.gov/docs/PRs/23683/coverage/chemical_reactions)
- [`combined`](https://mooseframework.inl.gov/docs/PRs/23683/coverage/combined)
- [`contact`](https://mooseframework.inl.gov/docs/PRs/23683/coverage/contact)
- [`electromagnetics`](https://mooseframework.inl.gov/docs/PRs/23683/coverage/electromagnetics)
- [`external_petsc_solver`](https://mooseframework.inl.gov/docs/PRs/23683/coverage/external_petsc_solver)
- [`fluid_properties`](https://mooseframework.inl.gov/docs/PRs/23683/coverage/fluid_properties)
- [`fsi`](https://mooseframework.inl.gov/docs/PRs/23683/coverage/fsi)
- [`functional_expansion_tools`](https://mooseframework.inl.gov/docs/PRs/23683/coverage/functional_expansion_tools)
- [`geochemistry`](https://mooseframework.inl.gov/docs/PRs/23683/coverage/geochemistry)
- [`heat_conduction`](https://mooseframework.inl.gov/docs/PRs/23683/coverage/heat_conduction)
- [`level_set`](https://mooseframework.inl.gov/docs/PRs/23683/coverage/level_set)
- [`misc`](https://mooseframework.inl.gov/docs/PRs/23683/coverage/misc)
- [`navier_stokes`](https://mooseframework.inl.gov/docs/PRs/23683/coverage/navier_stokes)
- [`optimization`](https://mooseframework.inl.gov/docs/PRs/23683/coverage/optimization)
- [`peridynamics`](https://mooseframework.inl.gov/docs/PRs/23683/coverage/peridynamics)
- [`phase_field`](https://mooseframework.inl.gov/docs/PRs/23683/coverage/phase_field)
- [`porous_flow`](https://mooseframework.inl.gov/docs/PRs/23683/coverage/porous_flow)
- [`ray_tracing`](https://mooseframework.inl.gov/docs/PRs/23683/coverage/ray_tracing)
- [`rdg`](https://mooseframework.inl.gov/docs/PRs/23683/coverage/rdg)
- [`reactor`](https://mooseframework.inl.gov/docs/PRs/23683/coverage/reactor)
- [`richards`](https://mooseframework.inl.gov/docs/PRs/23683/coverage/richards)
- [`scalar_transport`](https://mooseframework.inl.gov/docs/PRs/23683/coverage/scalar_transport)
- [`solid_properties`](https://mooseframework.inl.gov/docs/PRs/23683/coverage/solid_properties)
- [`stochastic_tools`](https://mooseframework.inl.gov/docs/PRs/23683/coverage/stochastic_tools)
- [`tensor_mechanics`](https://mooseframework.inl.gov/docs/PRs/23683/coverage/tensor_mechanics)
- [`thermal_hydraulics`](https://mooseframework.inl.gov/docs/PRs/23683/coverage/thermal_hydraulics)
- [`xfem`](https://mooseframework.inl.gov/docs/PRs/23683/coverage/xfem)

</details>



This comment will be updated on new commits.

2023-03-13 03:31 UTC, GiudGiud commented
Test failure is unrelated

2023-03-14 20:23 UTC, loganharbour approved these changes

2023-03-14 20:34 UTC, merged