Restricting coarse element ID assignment to fine mesh subdomains
idaholab/moose pull request #23718
Opened 2023-03-14 15:17 UTC by zachmprince

Closes #23708

2023-03-14 15:34 UTC, YaqiWang commented on modules/reactor/src/meshgenerators/CoarseMeshExtraElementIDGenerator.C
> +        id_offset = elem_id;
Better to add a note in the markdown file on this.

2023-03-14 15:36 UTC, YaqiWang commented on modules/reactor/src/meshgenerators/CoarseMeshExtraElementIDGenerator.C
> +  if (already_has_id && isParamValid("subdomains"))
`isParamValid("subdomains")` here will always return true, unless remove its default value in the validParams. In that case, Line 83 will need to be protected.

2023-03-14 16:11 UTC, GiudGiud requested changes

2023-03-14 16:11 UTC, GiudGiud commented on modules/reactor/src/meshgenerators/CoarseMeshExtraElementIDGenerator.C
> +  std::set<SubdomainID> include_subdomains;
```suggestion
  std::set<SubdomainID> included_subdomains;
```

2023-03-14 16:11 UTC, GiudGiud commented on modules/reactor/src/meshgenerators/CoarseMeshExtraElementIDGenerator.C
> +       MooseMeshUtils::getSubdomainIDs(*mesh, getParam<std::vector<SubdomainName>>("subdomains")))
does this fail when the subdomain is not in the mesh ? (due to a typo for example?)

2023-03-14 16:11 UTC, GiudGiud commented on modules/reactor/test/tests/meshgenerators/coarse_mesh_extra_element_id_generator/tests
> +    requirement = 'The system shall include the ability to assign extra element IDs based on a coarse mesh for subdomain-restricted elements of a fine mesh.'
```suggestion
    requirement = 'The system shall be able to assign extra element IDs based on a coarse mesh for subdomain-restricted elements of a fine mesh.'
```

2023-03-14 16:11 UTC, GiudGiud commented on modules/reactor/src/meshgenerators/CoarseMeshExtraElementIDGenerator.C
> +       MooseMeshUtils::getSubdomainIDs(*mesh, getParam<std::vector<SubdomainName>>("subdomains")))
ok it doesnt it just gives invalid_subdomain id

we need a check that are subdomain names passed are in the mesh

2023-03-14 17:12 UTC, moosebuild commented
Job [Coverage](https://civet.inl.gov/job/1403677/) on c766e9b wanted to post the following:


## Framework coverage

<table>
  <thead>
    <tr>
      <th></th>
      <th>25048c</th>
      <th colspan=4>#23718 c766e9</th>
    </tr>
    <tr>
      <th></th>
      <th>Total</th>
      <th>Total</th>
      <th>+/-</th>
      <th>New</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><b>Rate</b></td>
      <td>84.83%</td>
      <td>84.83%</td>
      <td>-0.00%</td>
      <td>-</td>
    </tr>
    <tr>
      <td><b>Hits</b></td>
      <td>84009</td>
      <td>84008</td>
      <td>-1</td>
      <td>0</td>
    </tr>
    <tr>
      <td><b>Misses</b></td>
      <td>15024</td>
      <td>15025</td>
      <td>+1</td>
      <td>0</td>
    </tr>
  </tbody>
</table>

[Diff coverage report](https://mooseframework.inl.gov/docs/PRs/23718/coverage_diff/framework)

[Full coverage report](https://mooseframework.inl.gov/docs/PRs/23718/coverage/framework)


## Modules coverage

### Reactor

<table>
  <thead>
    <tr>
      <th></th>
      <th>25048c</th>
      <th colspan=4>#23718 c766e9</th>
    </tr>
    <tr>
      <th></th>
      <th>Total</th>
      <th>Total</th>
      <th>+/-</th>
      <th>New</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><b>Rate</b></td>
      <td>95.78%</td>
      <td>95.81%</td>
      <td>+0.03%</td>
      <td>100.00%</td>
    </tr>
    <tr>
      <td><b>Hits</b></td>
      <td>4560</td>
      <td>4573</td>
      <td>+13</td>
      <td>14</td>
    </tr>
    <tr>
      <td><b>Misses</b></td>
      <td>201</td>
      <td>200</td>
      <td>-1</td>
      <td>0</td>
    </tr>
  </tbody>
</table>

[Diff coverage report](https://mooseframework.inl.gov/docs/PRs/23718/coverage_diff/reactor)

[Full coverage report](https://mooseframework.inl.gov/docs/PRs/23718/coverage/reactor)

## Full coverage reports

<details>
<summary>Reports</summary>

- [`framework`](https://mooseframework.inl.gov/docs/PRs/23718/coverage/framework)
- [`chemical_reactions`](https://mooseframework.inl.gov/docs/PRs/23718/coverage/chemical_reactions)
- [`combined`](https://mooseframework.inl.gov/docs/PRs/23718/coverage/combined)
- [`contact`](https://mooseframework.inl.gov/docs/PRs/23718/coverage/contact)
- [`electromagnetics`](https://mooseframework.inl.gov/docs/PRs/23718/coverage/electromagnetics)
- [`external_petsc_solver`](https://mooseframework.inl.gov/docs/PRs/23718/coverage/external_petsc_solver)
- [`fluid_properties`](https://mooseframework.inl.gov/docs/PRs/23718/coverage/fluid_properties)
- [`fsi`](https://mooseframework.inl.gov/docs/PRs/23718/coverage/fsi)
- [`functional_expansion_tools`](https://mooseframework.inl.gov/docs/PRs/23718/coverage/functional_expansion_tools)
- [`geochemistry`](https://mooseframework.inl.gov/docs/PRs/23718/coverage/geochemistry)
- [`heat_conduction`](https://mooseframework.inl.gov/docs/PRs/23718/coverage/heat_conduction)
- [`level_set`](https://mooseframework.inl.gov/docs/PRs/23718/coverage/level_set)
- [`misc`](https://mooseframework.inl.gov/docs/PRs/23718/coverage/misc)
- [`navier_stokes`](https://mooseframework.inl.gov/docs/PRs/23718/coverage/navier_stokes)
- [`optimization`](https://mooseframework.inl.gov/docs/PRs/23718/coverage/optimization)
- [`peridynamics`](https://mooseframework.inl.gov/docs/PRs/23718/coverage/peridynamics)
- [`phase_field`](https://mooseframework.inl.gov/docs/PRs/23718/coverage/phase_field)
- [`porous_flow`](https://mooseframework.inl.gov/docs/PRs/23718/coverage/porous_flow)
- [`ray_tracing`](https://mooseframework.inl.gov/docs/PRs/23718/coverage/ray_tracing)
- [`rdg`](https://mooseframework.inl.gov/docs/PRs/23718/coverage/rdg)
- [`reactor`](https://mooseframework.inl.gov/docs/PRs/23718/coverage/reactor)
- [`richards`](https://mooseframework.inl.gov/docs/PRs/23718/coverage/richards)
- [`scalar_transport`](https://mooseframework.inl.gov/docs/PRs/23718/coverage/scalar_transport)
- [`solid_properties`](https://mooseframework.inl.gov/docs/PRs/23718/coverage/solid_properties)
- [`stochastic_tools`](https://mooseframework.inl.gov/docs/PRs/23718/coverage/stochastic_tools)
- [`tensor_mechanics`](https://mooseframework.inl.gov/docs/PRs/23718/coverage/tensor_mechanics)
- [`thermal_hydraulics`](https://mooseframework.inl.gov/docs/PRs/23718/coverage/thermal_hydraulics)
- [`xfem`](https://mooseframework.inl.gov/docs/PRs/23718/coverage/xfem)

</details>



This comment will be updated on new commits.

2023-03-14 17:15 UTC, moosebuild commented
Job [Documentation](https://civet.inl.gov/job/1403663/) on c766e9b wanted to post the following:

View the site [here](https://mooseframework.inl.gov/docs/PRs/23718/site)

This comment will be updated on new commits.

2023-03-14 21:45 UTC, GiudGiud approved these changes

2023-03-17 21:29 UTC, moosebuild commented
Job [App documentation](https://civet.inl.gov/job/1404423/) on b46f23b : invalidated by @zachmprince

Trying again

2023-03-28 19:30 UTC, merged

2023-03-28 21:42 UTC, GiudGiud commented
@zachmprince this broke next btw

https://civet.inl.gov/event/117135/

2023-03-28 23:52 UTC, lindsayad commented
it's almost more red than green 😆