Allowed `JunctionOneToOne1Phase` to connect non-parallel channels
idaholab/moose pull request #23793
Opened 2023-03-20 21:32 UTC by joshuahansel

Closes #23790

2023-03-20 23:25 UTC, moosebuild commented
Job [Documentation](https://civet.inl.gov/job/1415220/) on ccb55b9 wanted to post the following:

View the site [here](https://mooseframework.inl.gov/docs/PRs/23793/site)

This comment will be updated on new commits.

2023-03-21 17:53 UTC, moosebuild commented
Job [Coverage](https://civet.inl.gov/job/1416517/) on dc6661b wanted to post the following:


## Framework coverage

<table>
  <thead>
    <tr>
      <th></th>
      <th>fa013b</th>
      <th colspan=4>#23793 dc6661</th>
    </tr>
    <tr>
      <th></th>
      <th>Total</th>
      <th>Total</th>
      <th>+/-</th>
      <th>New</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><b>Rate</b></td>
      <td>84.87%</td>
      <td>84.87%</td>
      <td>-0.00%</td>
      <td>-</td>
    </tr>
    <tr>
      <td><b>Hits</b></td>
      <td>84194</td>
      <td>84193</td>
      <td>-1</td>
      <td>0</td>
    </tr>
    <tr>
      <td><b>Misses</b></td>
      <td>15008</td>
      <td>15009</td>
      <td>+1</td>
      <td>0</td>
    </tr>
  </tbody>
</table>

[Diff coverage report](https://mooseframework.inl.gov/docs/PRs/23793/coverage_diff/framework)

[Full coverage report](https://mooseframework.inl.gov/docs/PRs/23793/coverage/framework)


## Modules coverage

### Thermal hydraulics

<table>
  <thead>
    <tr>
      <th></th>
      <th>fa013b</th>
      <th colspan=4>#23793 dc6661</th>
    </tr>
    <tr>
      <th></th>
      <th>Total</th>
      <th>Total</th>
      <th>+/-</th>
      <th>New</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><b>Rate</b></td>
      <td>90.37%</td>
      <td>90.37%</td>
      <td>-0.00%</td>
      <td>100.00%</td>
    </tr>
    <tr>
      <td><b>Hits</b></td>
      <td>12414</td>
      <td>12412</td>
      <td>-2</td>
      <td>1</td>
    </tr>
    <tr>
      <td><b>Misses</b></td>
      <td>1323</td>
      <td>1323</td>
      <td>-</td>
      <td>0</td>
    </tr>
  </tbody>
</table>

[Diff coverage report](https://mooseframework.inl.gov/docs/PRs/23793/coverage_diff/thermal_hydraulics)

[Full coverage report](https://mooseframework.inl.gov/docs/PRs/23793/coverage/thermal_hydraulics)

## Full coverage reports

<details>
<summary>Reports</summary>

- [`framework`](https://mooseframework.inl.gov/docs/PRs/23793/coverage/framework)
- [`chemical_reactions`](https://mooseframework.inl.gov/docs/PRs/23793/coverage/chemical_reactions)
- [`combined`](https://mooseframework.inl.gov/docs/PRs/23793/coverage/combined)
- [`contact`](https://mooseframework.inl.gov/docs/PRs/23793/coverage/contact)
- [`electromagnetics`](https://mooseframework.inl.gov/docs/PRs/23793/coverage/electromagnetics)
- [`external_petsc_solver`](https://mooseframework.inl.gov/docs/PRs/23793/coverage/external_petsc_solver)
- [`fluid_properties`](https://mooseframework.inl.gov/docs/PRs/23793/coverage/fluid_properties)
- [`fsi`](https://mooseframework.inl.gov/docs/PRs/23793/coverage/fsi)
- [`functional_expansion_tools`](https://mooseframework.inl.gov/docs/PRs/23793/coverage/functional_expansion_tools)
- [`geochemistry`](https://mooseframework.inl.gov/docs/PRs/23793/coverage/geochemistry)
- [`heat_conduction`](https://mooseframework.inl.gov/docs/PRs/23793/coverage/heat_conduction)
- [`level_set`](https://mooseframework.inl.gov/docs/PRs/23793/coverage/level_set)
- [`misc`](https://mooseframework.inl.gov/docs/PRs/23793/coverage/misc)
- [`navier_stokes`](https://mooseframework.inl.gov/docs/PRs/23793/coverage/navier_stokes)
- [`optimization`](https://mooseframework.inl.gov/docs/PRs/23793/coverage/optimization)
- [`peridynamics`](https://mooseframework.inl.gov/docs/PRs/23793/coverage/peridynamics)
- [`phase_field`](https://mooseframework.inl.gov/docs/PRs/23793/coverage/phase_field)
- [`porous_flow`](https://mooseframework.inl.gov/docs/PRs/23793/coverage/porous_flow)
- [`ray_tracing`](https://mooseframework.inl.gov/docs/PRs/23793/coverage/ray_tracing)
- [`rdg`](https://mooseframework.inl.gov/docs/PRs/23793/coverage/rdg)
- [`reactor`](https://mooseframework.inl.gov/docs/PRs/23793/coverage/reactor)
- [`richards`](https://mooseframework.inl.gov/docs/PRs/23793/coverage/richards)
- [`scalar_transport`](https://mooseframework.inl.gov/docs/PRs/23793/coverage/scalar_transport)
- [`solid_properties`](https://mooseframework.inl.gov/docs/PRs/23793/coverage/solid_properties)
- [`stochastic_tools`](https://mooseframework.inl.gov/docs/PRs/23793/coverage/stochastic_tools)
- [`tensor_mechanics`](https://mooseframework.inl.gov/docs/PRs/23793/coverage/tensor_mechanics)
- [`thermal_hydraulics`](https://mooseframework.inl.gov/docs/PRs/23793/coverage/thermal_hydraulics)
- [`xfem`](https://mooseframework.inl.gov/docs/PRs/23793/coverage/xfem)

</details>



This comment will be updated on new commits.

2023-03-22 16:02 UTC, licharlot requested changes

2023-03-22 17:21 UTC, joshuahansel commented on modules/thermal_hydraulics/test/tests/problems/natural_circulation/natural_circulation.i
> +  show = 'p T vel'
In general we know that it won't necessarily be, due to the spatial discretization, but I can check that it's more or less constant. Do you just want a plot, or do you think the gold file should actually have `rhouA`, even though {p,T,vel,A} determine rhouA?

2023-03-22 19:43 UTC, licharlot commented on modules/thermal_hydraulics/test/tests/problems/natural_circulation/natural_circulation.i
> +  show = 'p T vel'
Yes we know it won't be perfect, but we should have an idea of how good or bad it is. I think it can go in the exodus.

2023-03-23 20:34 UTC, joshuahansel commented on modules/thermal_hydraulics/test/tests/problems/natural_circulation/natural_circulation.i
> +  show = 'p T vel'
Here are the plots, where I've lined up the pipes in a single line, starting with the heated pipe:

![natural_circulation_rhouA](https://user-images.githubusercontent.com/23108676/227346794-9328fc53-bbbe-4644-ae13-ae19cba78f97.png)

![natural_circulation_T](https://user-images.githubusercontent.com/23108676/227347289-45dbbb34-b0fc-483e-8232-ef1abb6e74c7.png)

![natural_circulation_p](https://user-images.githubusercontent.com/23108676/227347363-fa23444e-318a-45c0-8082-2b9577d86abe.png)

Mass flow rate and pressure are not beautiful, as expected. If I made plots of the edge values of those, I'd expect them to look nice. I think we'd need to write a VPP to accomplish that.

2023-03-27 13:47 UTC, licharlot approved these changes

2023-03-27 14:59 UTC, merged