Fixed segmentation fault from reinitting material faces
idaholab/moose pull request #23878
Opened 2023-03-28 20:44 UTC by socratesgorilla

Closes #23348

2023-03-28 21:01 UTC, lindsayad requested changes
It would be good to add the test input that @maxnezdyur provided to ensure we don't regress in the future

2023-03-28 21:11 UTC, socratesgorilla commented
> It would be good to add the test input that @maxnezdyur provided to ensure we don't regress in the future

Just a RunApp or do you think it needs any actual output checking?

2023-03-28 21:18 UTC, lindsayad commented
I think a `RunApp` is fine

2023-03-29 17:26 UTC, lindsayad requested changes

2023-03-29 17:26 UTC, lindsayad commented on modules/combined/test/tests/misc/re_init_face.i
> +
```suggestion
```

2023-03-29 17:26 UTC, lindsayad commented on modules/combined/test/tests/misc/re_init_face.i
> +  [cause_of_failure]
```suggestion
  [side_average]
```

2023-03-29 17:26 UTC, lindsayad commented on modules/combined/test/tests/misc/re_init_face.i
> +
```suggestion
```

2023-03-29 17:26 UTC, lindsayad commented on modules/combined/test/tests/misc/tests
> +   requirement = "The system shall properly reset itself after adding a material using a displaced mesh."
```suggestion
   requirement = "The system shall be able to perform requested material computation on faces of a displaced mesh even if no other face objects are executing on the displaced mesh."
```

2023-03-29 18:02 UTC, lindsayad approved these changes

2023-03-29 20:15 UTC, merged