This enables every single parameter in a group of parameters to be specified.
idaholab/moose pull request #23896
Opened 2023-03-29 23:55 UTC by lynnmunday

closes #23867

2023-03-29 23:59 UTC, lynnmunday commented on modules/optimization/src/optimizationreporters/OptimizationReporterBase.C
> +  return _lower_bounds[i];
I started filling these completely so they don't need to be indexed into.  There are also always filled so there is no longer a need to check if bounds exist.

2023-03-29 23:59 UTC, loganharbour commented
I take it you resolved your `moose` function issue? 😆

2023-03-30 00:00 UTC, lynnmunday commented
@loganharbour I don't use for debugging anymore!

2023-03-30 00:00 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/1434109/) on d3ea89f wanted to post the following:

Your code requires style changes.  

A patch was auto generated and copied [here](https://mooseframework.inl.gov/docs/PRs/23896/clang_format/style.patch)  
You can directly apply the patch by running, in the top level of your repository:

`curl -s https://mooseframework.inl.gov/docs/PRs/23896/clang_format/style.patch | git apply -v`  

Alternatively, with your repository up to date and in the top level of your repository:

`git clang-format 9eedce8060b5450a00d114861901084b554e58d2`

2023-03-30 01:58 UTC, moosebuild commented
Job [Documentation](https://civet.inl.gov/job/1434172/) on e335b67 wanted to post the following:

View the site [here](https://mooseframework.inl.gov/docs/PRs/23896/site)

This comment will be updated on new commits.

2023-03-30 02:14 UTC, moosebuild commented
Job [Coverage](https://civet.inl.gov/job/1434186/) on e335b67 wanted to post the following:


## Framework coverage

<table>
  <thead>
    <tr>
      <th></th>
      <th>789e9b</th>
      <th colspan=4>#23896 e335b6</th>
    </tr>
    <tr>
      <th></th>
      <th>Total</th>
      <th>Total</th>
      <th>+/-</th>
      <th>New</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><b>Rate</b></td>
      <td>84.91%</td>
      <td>84.92%</td>
      <td>+0.00%</td>
      <td>-</td>
    </tr>
    <tr>
      <td><b>Hits</b></td>
      <td>84348</td>
      <td>84352</td>
      <td>+4</td>
      <td>0</td>
    </tr>
    <tr>
      <td><b>Misses</b></td>
      <td>14986</td>
      <td>14982</td>
      <td>-4</td>
      <td>0</td>
    </tr>
  </tbody>
</table>

[Diff coverage report](https://mooseframework.inl.gov/docs/PRs/23896/coverage_diff/framework)

[Full coverage report](https://mooseframework.inl.gov/docs/PRs/23896/coverage/framework)


## Modules coverage

### Optimization

<table>
  <thead>
    <tr>
      <th></th>
      <th>789e9b</th>
      <th colspan=4>#23896 e335b6</th>
    </tr>
    <tr>
      <th></th>
      <th>Total</th>
      <th>Total</th>
      <th>+/-</th>
      <th>New</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><b>Rate</b></td>
      <td>87.88%</td>
      <td>88.22%</td>
      <td>+0.34%</td>
      <td>95.45%</td>
    </tr>
    <tr>
      <td><b>Hits</b></td>
      <td>972</td>
      <td>1004</td>
      <td>+32</td>
      <td>63</td>
    </tr>
    <tr>
      <td><b>Misses</b></td>
      <td>134</td>
      <td>134</td>
      <td>-</td>
      <td>3</td>
    </tr>
  </tbody>
</table>

[Diff coverage report](https://mooseframework.inl.gov/docs/PRs/23896/coverage_diff/optimization)

[Full coverage report](https://mooseframework.inl.gov/docs/PRs/23896/coverage/optimization)

## Full coverage reports

<details>
<summary>Reports</summary>

- [`framework`](https://mooseframework.inl.gov/docs/PRs/23896/coverage/framework)
- [`chemical_reactions`](https://mooseframework.inl.gov/docs/PRs/23896/coverage/chemical_reactions)
- [`combined`](https://mooseframework.inl.gov/docs/PRs/23896/coverage/combined)
- [`contact`](https://mooseframework.inl.gov/docs/PRs/23896/coverage/contact)
- [`electromagnetics`](https://mooseframework.inl.gov/docs/PRs/23896/coverage/electromagnetics)
- [`external_petsc_solver`](https://mooseframework.inl.gov/docs/PRs/23896/coverage/external_petsc_solver)
- [`fluid_properties`](https://mooseframework.inl.gov/docs/PRs/23896/coverage/fluid_properties)
- [`fsi`](https://mooseframework.inl.gov/docs/PRs/23896/coverage/fsi)
- [`functional_expansion_tools`](https://mooseframework.inl.gov/docs/PRs/23896/coverage/functional_expansion_tools)
- [`geochemistry`](https://mooseframework.inl.gov/docs/PRs/23896/coverage/geochemistry)
- [`heat_conduction`](https://mooseframework.inl.gov/docs/PRs/23896/coverage/heat_conduction)
- [`level_set`](https://mooseframework.inl.gov/docs/PRs/23896/coverage/level_set)
- [`misc`](https://mooseframework.inl.gov/docs/PRs/23896/coverage/misc)
- [`navier_stokes`](https://mooseframework.inl.gov/docs/PRs/23896/coverage/navier_stokes)
- [`optimization`](https://mooseframework.inl.gov/docs/PRs/23896/coverage/optimization)
- [`peridynamics`](https://mooseframework.inl.gov/docs/PRs/23896/coverage/peridynamics)
- [`phase_field`](https://mooseframework.inl.gov/docs/PRs/23896/coverage/phase_field)
- [`porous_flow`](https://mooseframework.inl.gov/docs/PRs/23896/coverage/porous_flow)
- [`ray_tracing`](https://mooseframework.inl.gov/docs/PRs/23896/coverage/ray_tracing)
- [`rdg`](https://mooseframework.inl.gov/docs/PRs/23896/coverage/rdg)
- [`reactor`](https://mooseframework.inl.gov/docs/PRs/23896/coverage/reactor)
- [`richards`](https://mooseframework.inl.gov/docs/PRs/23896/coverage/richards)
- [`scalar_transport`](https://mooseframework.inl.gov/docs/PRs/23896/coverage/scalar_transport)
- [`solid_properties`](https://mooseframework.inl.gov/docs/PRs/23896/coverage/solid_properties)
- [`stochastic_tools`](https://mooseframework.inl.gov/docs/PRs/23896/coverage/stochastic_tools)
- [`tensor_mechanics`](https://mooseframework.inl.gov/docs/PRs/23896/coverage/tensor_mechanics)
- [`thermal_hydraulics`](https://mooseframework.inl.gov/docs/PRs/23896/coverage/thermal_hydraulics)
- [`xfem`](https://mooseframework.inl.gov/docs/PRs/23896/coverage/xfem)

</details>



This comment will be updated on new commits.

2023-03-30 19:45 UTC, lynnmunday commented
@zachmprince will you review?

2023-03-30 19:50 UTC, zachmprince requested changes

2023-03-30 19:50 UTC, zachmprince commented on modules/optimization/src/optimizationreporters/ParameterMeshOptimization.C
> +  std::vector<Real> constant_upper_bounds(getParam<std::vector<Real>>("upper_bounds"));
```suggestion
  const std::vector<Real> & constant_lower_bounds = getParam<std::vector<Real>>("lower_bounds");
  const std::vector<Real> & constant_upper_bounds = getParam<std::vector<Real>>("upper_bounds");
```

2023-03-30 19:50 UTC, zachmprince commented on modules/optimization/src/optimizationreporters/ParameterMeshOptimization.C
> +                         vector_of_group_upper_bound.end());
```suggestion

    // assign lower and upper bounds
    _lower_bounds.resize(_lower_bounds.size() + _nvalues[i],
                                                       constant_lower_bounds.empty()
                                                      ? std::numeric_limits<Real>::lowest()
                                                      : constant_lower_bounds[i]);
    _upper_bounds.resize(_upper_bounds.size() + _nvalues[i],
                                                       constant_upper_bounds.empty()
                                                      ? std::numeric_limits<Real>::max()
                                                      : constant_upper_bounds[i]);
```

2023-03-30 20:46 UTC, lynnmunday commented on modules/optimization/src/optimizationreporters/ParameterMeshOptimization.C
> +  std::vector<Real> constant_upper_bounds(getParam<std::vector<Real>>("upper_bounds"));
why the reference?

2023-03-30 22:50 UTC, lynnmunday commented on modules/optimization/src/optimizationreporters/OptimizationReporter.C
> +  fillBounds();
I switched to this

2023-03-30 22:54 UTC, lynnmunday commented on modules/optimization/src/optimizationreporters/ParameterMeshOptimization.C
> +  std::vector<Real> constant_upper_bounds(getParam<std::vector<Real>>("upper_bounds"));
fixed

2023-03-30 22:54 UTC, lynnmunday commented on modules/optimization/src/optimizationreporters/OptimizationReporter.C
>    }
fixed

2023-03-30 22:54 UTC, lynnmunday commented on modules/optimization/src/optimizationreporters/OptimizationReporter.C
> +  return parsedData;
fixed

2023-03-31 13:19 UTC, lynnmunday commented
@zachmprince I made the changes you suggested, will you review again.

2023-04-03 18:28 UTC, zachmprince requested changes
Just making things a little more concise. You can take or leave it.

2023-04-03 18:28 UTC, zachmprince commented on modules/optimization/src/optimizationreporters/OptimizationReporter.C
> +      }
```suggestion
      if (parsedData[i].size() == 1)
        parsedData[i].assign(_nvalues[i], parsedData[i][0])
      else if (parsedData[i].size() != _nvalues[i])
        paramError(type,
                   "When ",
                   type,
                   " are given in input file, there must either be a single value per parameter "
                   "group or a value for every parameter in the group.");
```

2023-04-03 18:28 UTC, zachmprince commented on modules/optimization/src/optimizationreporters/OptimizationReporter.C
> +    }
```suggestion
    for (const auto & params_per_group : _nvalues)
      parsed_data.emplace_back(params_per_group, default_value);
```

2023-04-04 17:42 UTC, lynnmunday commented on modules/optimization/src/optimizationreporters/OptimizationReporter.C
> +      }
finished

2023-04-04 17:46 UTC, lynnmunday commented on modules/optimization/src/optimizationreporters/OptimizationReporter.C
> +    }
done

2023-04-04 17:46 UTC, lynnmunday commented on modules/optimization/src/optimizationreporters/OptimizationReporter.C
> +  for (auto & vec : parsedData)
done

2023-04-04 20:25 UTC, zachmprince approved these changes, later dismissed

2023-04-05 14:31 UTC, moosebuild commented
Job [Python 3.9](https://civet.inl.gov/job/1443680/) on 1e57e3c : invalidated by @zachmprince

2023-04-11 13:47 UTC, zachmprince approved these changes

2023-04-11 13:47 UTC, merged