Add nemesis to output intermediate mesh
idaholab/moose pull request #23960
Opened 2023-04-04 16:47 UTC by MengnanLi91

Apply nemesis non-HDF5 output change from libmesh update to output intermediate mesh capability(#23486)

Add nemesis non-HDF5 output which was left in #23486

2023-04-04 16:48 UTC, MengnanLi91 commented
@loganharbour nemesis non-HDF5 for output intermediate mesh is here

2023-04-04 22:49 UTC, moosebuild commented
Job [Coverage](https://civet.inl.gov/job/1443903/) on 996ca78 wanted to post the following:


## Framework coverage

<table>
  <thead>
    <tr>
      <th></th>
      <th>40cceb</th>
      <th colspan=4>#23960 996ca7</th>
    </tr>
    <tr>
      <th></th>
      <th>Total</th>
      <th>Total</th>
      <th>+/-</th>
      <th>New</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><b>Rate</b></td>
      <td>84.91%</td>
      <td>84.92%</td>
      <td>+0.00%</td>
      <td>100.00%</td>
    </tr>
    <tr>
      <td><b>Hits</b></td>
      <td>84351</td>
      <td>84356</td>
      <td>+5</td>
      <td>3</td>
    </tr>
    <tr>
      <td><b>Misses</b></td>
      <td>14987</td>
      <td>14985</td>
      <td>-2</td>
      <td>0</td>
    </tr>
  </tbody>
</table>

[Diff coverage report](https://mooseframework.inl.gov/docs/PRs/23960/coverage_diff/framework)

[Full coverage report](https://mooseframework.inl.gov/docs/PRs/23960/coverage/framework)


## Modules coverage

Coverage did not change

## Full coverage reports

<details>
<summary>Reports</summary>

- [`framework`](https://mooseframework.inl.gov/docs/PRs/23960/coverage/framework)
- [`chemical_reactions`](https://mooseframework.inl.gov/docs/PRs/23960/coverage/chemical_reactions)
- [`combined`](https://mooseframework.inl.gov/docs/PRs/23960/coverage/combined)
- [`contact`](https://mooseframework.inl.gov/docs/PRs/23960/coverage/contact)
- [`electromagnetics`](https://mooseframework.inl.gov/docs/PRs/23960/coverage/electromagnetics)
- [`external_petsc_solver`](https://mooseframework.inl.gov/docs/PRs/23960/coverage/external_petsc_solver)
- [`fluid_properties`](https://mooseframework.inl.gov/docs/PRs/23960/coverage/fluid_properties)
- [`fsi`](https://mooseframework.inl.gov/docs/PRs/23960/coverage/fsi)
- [`functional_expansion_tools`](https://mooseframework.inl.gov/docs/PRs/23960/coverage/functional_expansion_tools)
- [`geochemistry`](https://mooseframework.inl.gov/docs/PRs/23960/coverage/geochemistry)
- [`heat_conduction`](https://mooseframework.inl.gov/docs/PRs/23960/coverage/heat_conduction)
- [`level_set`](https://mooseframework.inl.gov/docs/PRs/23960/coverage/level_set)
- [`misc`](https://mooseframework.inl.gov/docs/PRs/23960/coverage/misc)
- [`navier_stokes`](https://mooseframework.inl.gov/docs/PRs/23960/coverage/navier_stokes)
- [`optimization`](https://mooseframework.inl.gov/docs/PRs/23960/coverage/optimization)
- [`peridynamics`](https://mooseframework.inl.gov/docs/PRs/23960/coverage/peridynamics)
- [`phase_field`](https://mooseframework.inl.gov/docs/PRs/23960/coverage/phase_field)
- [`porous_flow`](https://mooseframework.inl.gov/docs/PRs/23960/coverage/porous_flow)
- [`ray_tracing`](https://mooseframework.inl.gov/docs/PRs/23960/coverage/ray_tracing)
- [`rdg`](https://mooseframework.inl.gov/docs/PRs/23960/coverage/rdg)
- [`reactor`](https://mooseframework.inl.gov/docs/PRs/23960/coverage/reactor)
- [`richards`](https://mooseframework.inl.gov/docs/PRs/23960/coverage/richards)
- [`scalar_transport`](https://mooseframework.inl.gov/docs/PRs/23960/coverage/scalar_transport)
- [`solid_properties`](https://mooseframework.inl.gov/docs/PRs/23960/coverage/solid_properties)
- [`stochastic_tools`](https://mooseframework.inl.gov/docs/PRs/23960/coverage/stochastic_tools)
- [`tensor_mechanics`](https://mooseframework.inl.gov/docs/PRs/23960/coverage/tensor_mechanics)
- [`thermal_hydraulics`](https://mooseframework.inl.gov/docs/PRs/23960/coverage/thermal_hydraulics)
- [`xfem`](https://mooseframework.inl.gov/docs/PRs/23960/coverage/xfem)

</details>



This comment will be updated on new commits.

2023-04-04 22:50 UTC, moosebuild commented
Job [Documentation](https://civet.inl.gov/job/1443889/) on 996ca78 wanted to post the following:

View the site [here](https://mooseframework.inl.gov/docs/PRs/23960/site)

This comment will be updated on new commits.

2023-04-05 15:15 UTC, loganharbour requested changes
Good otherwise

2023-04-05 15:15 UTC, loganharbour commented on framework/src/meshgenerators/MeshGenerator.C
> +  params.addParamNamesToGroup("show_info output", "Debug Helper");
```suggestion
  params.addParamNamesToGroup("show_info output", "Debugging");
```

2023-04-10 16:24 UTC, loganharbour approved these changes

2023-04-10 16:24 UTC, merged