Add features to TestHarness already within csvdiff
idaholab/moose pull request #23965
Opened 2023-04-04 17:51 UTC by vanwdani

Closes #23964

2023-04-04 18:50 UTC, GiudGiud requested changes
is there a test we can add for this?

2023-04-04 18:50 UTC, GiudGiud commented on python/TestHarness/testers/CSVDiff.py
> +        params.addParam('ignore_columns', [], "A list of variables which will not be included in the CSVDiffs operation.")
```suggestion
        params.addParam('ignore_columns', [], "A list of variables which will not be included in the comparison.")
```
same for the other one

2023-04-04 18:50 UTC, GiudGiud commented on python/TestHarness/testers/CSVDiff.py
> +            if self.specs.isValid('custom_columns'):
let s check the arguments passed to make sure they make sense:
an ignored column for example should not be a custom or an override column

2023-04-04 18:50 UTC, GiudGiud commented on python/TestHarness/testers/CSVDiff.py
> +            if self.specs.isValid('custom_columns'):
unless CSVDiff already errors on this nicely

2023-04-04 19:52 UTC, moosebuild commented
Job [Documentation](https://civet.inl.gov/job/1443061/) on aaa636d wanted to post the following:

View the site [here](https://mooseframework.inl.gov/docs/PRs/23965/site)

This comment will be updated on new commits.

2023-04-04 20:06 UTC, moosebuild commented
Job [Coverage](https://civet.inl.gov/job/1443075/) on aaa636d wanted to post the following:


## Framework coverage

<table>
  <thead>
    <tr>
      <th></th>
      <th>40cceb</th>
      <th colspan=4>#23965 aaa636</th>
    </tr>
    <tr>
      <th></th>
      <th>Total</th>
      <th>Total</th>
      <th>+/-</th>
      <th>New</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><b>Rate</b></td>
      <td>84.91%</td>
      <td>84.91%</td>
      <td>-0.00%</td>
      <td>-</td>
    </tr>
    <tr>
      <td><b>Hits</b></td>
      <td>84351</td>
      <td>84350</td>
      <td>-1</td>
      <td>0</td>
    </tr>
    <tr>
      <td><b>Misses</b></td>
      <td>14987</td>
      <td>14988</td>
      <td>+1</td>
      <td>0</td>
    </tr>
  </tbody>
</table>

[Diff coverage report](https://mooseframework.inl.gov/docs/PRs/23965/coverage_diff/framework)

[Full coverage report](https://mooseframework.inl.gov/docs/PRs/23965/coverage/framework)


## Modules coverage

Coverage did not change

## Full coverage reports

<details>
<summary>Reports</summary>

- [`framework`](https://mooseframework.inl.gov/docs/PRs/23965/coverage/framework)
- [`chemical_reactions`](https://mooseframework.inl.gov/docs/PRs/23965/coverage/chemical_reactions)
- [`combined`](https://mooseframework.inl.gov/docs/PRs/23965/coverage/combined)
- [`contact`](https://mooseframework.inl.gov/docs/PRs/23965/coverage/contact)
- [`electromagnetics`](https://mooseframework.inl.gov/docs/PRs/23965/coverage/electromagnetics)
- [`external_petsc_solver`](https://mooseframework.inl.gov/docs/PRs/23965/coverage/external_petsc_solver)
- [`fluid_properties`](https://mooseframework.inl.gov/docs/PRs/23965/coverage/fluid_properties)
- [`fsi`](https://mooseframework.inl.gov/docs/PRs/23965/coverage/fsi)
- [`functional_expansion_tools`](https://mooseframework.inl.gov/docs/PRs/23965/coverage/functional_expansion_tools)
- [`geochemistry`](https://mooseframework.inl.gov/docs/PRs/23965/coverage/geochemistry)
- [`heat_conduction`](https://mooseframework.inl.gov/docs/PRs/23965/coverage/heat_conduction)
- [`level_set`](https://mooseframework.inl.gov/docs/PRs/23965/coverage/level_set)
- [`misc`](https://mooseframework.inl.gov/docs/PRs/23965/coverage/misc)
- [`navier_stokes`](https://mooseframework.inl.gov/docs/PRs/23965/coverage/navier_stokes)
- [`optimization`](https://mooseframework.inl.gov/docs/PRs/23965/coverage/optimization)
- [`peridynamics`](https://mooseframework.inl.gov/docs/PRs/23965/coverage/peridynamics)
- [`phase_field`](https://mooseframework.inl.gov/docs/PRs/23965/coverage/phase_field)
- [`porous_flow`](https://mooseframework.inl.gov/docs/PRs/23965/coverage/porous_flow)
- [`ray_tracing`](https://mooseframework.inl.gov/docs/PRs/23965/coverage/ray_tracing)
- [`rdg`](https://mooseframework.inl.gov/docs/PRs/23965/coverage/rdg)
- [`reactor`](https://mooseframework.inl.gov/docs/PRs/23965/coverage/reactor)
- [`richards`](https://mooseframework.inl.gov/docs/PRs/23965/coverage/richards)
- [`scalar_transport`](https://mooseframework.inl.gov/docs/PRs/23965/coverage/scalar_transport)
- [`solid_properties`](https://mooseframework.inl.gov/docs/PRs/23965/coverage/solid_properties)
- [`stochastic_tools`](https://mooseframework.inl.gov/docs/PRs/23965/coverage/stochastic_tools)
- [`tensor_mechanics`](https://mooseframework.inl.gov/docs/PRs/23965/coverage/tensor_mechanics)
- [`thermal_hydraulics`](https://mooseframework.inl.gov/docs/PRs/23965/coverage/thermal_hydraulics)
- [`xfem`](https://mooseframework.inl.gov/docs/PRs/23965/coverage/xfem)

</details>



This comment will be updated on new commits.

2023-04-05 15:12 UTC, loganharbour commented
Woah. Hold off on this. This will change with https://github.com/idaholab/moose/pull/23561.

2023-04-05 15:12 UTC, loganharbour requested changes
Woah. Hold off on this. This will change with https://github.com/idaholab/moose/pull/23561.

2023-04-05 15:19 UTC, vanwdani commented
> Woah. Hold off on this. This will change with #23561.

How long?

2023-04-06 16:52 UTC, GiudGiud commented on python/mooseutils/csvdiff.py
> +                if self.ignore is not None:
can you avoid the large diff here?

You could do a
if self.ignore:
  continue

2023-04-06 16:54 UTC, GiudGiud commented
@socratesgorilla @loganharbour for an estimate on the other PR timeline please

2023-04-06 17:00 UTC, socratesgorilla commented
> @socratesgorilla @loganharbour for an estimate on the other PR timeline please

There's an issue with some stochastic tools tests that someone else is supposed to look at but besides that its essentially ready although I'm not the reviewer

2023-04-06 17:55 UTC, GiudGiud commented
ok we can't really merge anything right now until moose/next is fixed anyway. 

If we can't get https://github.com/idaholab/moose/pull/23561 merged in a reasonable amount of time, I think this should be merged and https://github.com/idaholab/moose/pull/23561 will need to adapt to make sure the feature used here is working as desired in SchemaDiff

2023-04-06 22:07 UTC, socratesgorilla commented
> ok we can't really merge anything right now until moose/next is fixed anyway.
> 
> If we can't get #23561 merged in a reasonable amount of time, I think this should be merged and #23561 will need to adapt to make sure the feature used here is working as desired in SchemaDiff

Asked zach and he's looking into it today supposedly should be mergeable soon hopefully

2023-04-10 14:51 UTC, moosebuild commented
Job [Apptainer build](https://civet.inl.gov/job/1450111/) on 77bcf5c : invalidated by @milljm

Updated SSL Certificate

2023-04-10 14:51 UTC, moosebuild commented
Job [Docker](https://civet.inl.gov/job/1450120/) on 77bcf5c : invalidated by @milljm

Updated SSL Certificate

2023-04-11 13:08 UTC, vanwdani commented
@milljm can you look at this and merge it?

2023-04-11 13:19 UTC, GiudGiud requested changes
I m not opposed to merging this (once that last thing has been looked at).
I think the reasonably window for the other PR has passed.

2023-04-11 13:23 UTC, milljm submitted a review, later dismissed
💯  Thank you for doing this!!

2023-04-11 13:31 UTC, milljm commented on python/mooseutils/csvdiff.py
> +                    continue
Perhaps, though this recursive for loop has additional `continue`'s and `break`'s later down. Must have been working all this time?

2023-04-11 13:35 UTC, GiudGiud commented on python/mooseutils/csvdiff.py
> +                    continue
the ones below are fine.
We continue when things match to save a little time, we break when things dont match, to error early
```suggestion
                if self.ignore and key in self.ignore:
                    break
```

2023-04-11 13:47 UTC, vanwdani commented on python/mooseutils/csvdiff.py
> +                    continue
Yeah, I agree, the else statement is unnecessary here.  I've removed it.

2023-04-11 14:27 UTC, GiudGiud approved these changes
@loganharbour your review has been addressed as far as I can tell

2023-04-12 17:18 UTC, loganharbour commented
All of these changes come with the SchemaDiff change with quite literally a few line change

2023-05-04 03:23 UTC, loganharbour approved these changes

2023-05-04 14:51 UTC, GiudGiud commented
Test failures are unrelated afaik

2023-05-04 14:51 UTC, merged

2023-05-04 14:51 UTC, GiudGiud commented
Thanks for the contribution!