Better enable split mesh for multiapp configurations
idaholab/moose pull request #24033
Opened 2023-04-11 22:14 UTC by loganharbour

refs #17318

2023-04-11 22:14 UTC, loganharbour commented
I swore my default was a draft... sorry folks.

2023-04-11 23:00 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/1456095/) on 5a8bcdf wanted to post the following:

Your code requires style changes.  

A patch was auto generated and copied [here](https://mooseframework.inl.gov/docs/PRs/24033/clang_format/style.patch)  
You can directly apply the patch by running, in the top level of your repository:

`curl -s https://mooseframework.inl.gov/docs/PRs/24033/clang_format/style.patch | git apply -v`  

Alternatively, with your repository up to date and in the top level of your repository:

`git clang-format f0c82f7eda772c976247c8b501be080b8380ceb5`

2023-04-12 00:58 UTC, moosebuild commented
Job [Coverage](https://civet.inl.gov/job/1456174/) on 043691d wanted to post the following:


## Framework coverage

<table>
  <thead>
    <tr>
      <th></th>
      <th>f0c82f</th>
      <th colspan=4>#24033 043691</th>
    </tr>
    <tr>
      <th></th>
      <th>Total</th>
      <th>Total</th>
      <th>+/-</th>
      <th>New</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><b>Rate</b></td>
      <td>85.08%</td>
      <td>85.08%</td>
      <td>+0.00%</td>
      <td>96.15%</td>
    </tr>
    <tr>
      <td><b>Hits</b></td>
      <td>86219</td>
      <td>86231</td>
      <td>+12</td>
      <td>25</td>
    </tr>
    <tr>
      <td><b>Misses</b></td>
      <td>15118</td>
      <td>15118</td>
      <td>-</td>
      <td>1</td>
    </tr>
  </tbody>
</table>

[Diff coverage report](https://mooseframework.inl.gov/docs/PRs/24033/coverage_diff/framework)

[Full coverage report](https://mooseframework.inl.gov/docs/PRs/24033/coverage/framework)


## Modules coverage

Coverage did not change

## Full coverage reports

<details>
<summary>Reports</summary>

- [`framework`](https://mooseframework.inl.gov/docs/PRs/24033/coverage/framework)
- [`chemical_reactions`](https://mooseframework.inl.gov/docs/PRs/24033/coverage/chemical_reactions)
- [`combined`](https://mooseframework.inl.gov/docs/PRs/24033/coverage/combined)
- [`contact`](https://mooseframework.inl.gov/docs/PRs/24033/coverage/contact)
- [`electromagnetics`](https://mooseframework.inl.gov/docs/PRs/24033/coverage/electromagnetics)
- [`external_petsc_solver`](https://mooseframework.inl.gov/docs/PRs/24033/coverage/external_petsc_solver)
- [`fluid_properties`](https://mooseframework.inl.gov/docs/PRs/24033/coverage/fluid_properties)
- [`fsi`](https://mooseframework.inl.gov/docs/PRs/24033/coverage/fsi)
- [`functional_expansion_tools`](https://mooseframework.inl.gov/docs/PRs/24033/coverage/functional_expansion_tools)
- [`geochemistry`](https://mooseframework.inl.gov/docs/PRs/24033/coverage/geochemistry)
- [`heat_conduction`](https://mooseframework.inl.gov/docs/PRs/24033/coverage/heat_conduction)
- [`level_set`](https://mooseframework.inl.gov/docs/PRs/24033/coverage/level_set)
- [`misc`](https://mooseframework.inl.gov/docs/PRs/24033/coverage/misc)
- [`navier_stokes`](https://mooseframework.inl.gov/docs/PRs/24033/coverage/navier_stokes)
- [`optimization`](https://mooseframework.inl.gov/docs/PRs/24033/coverage/optimization)
- [`peridynamics`](https://mooseframework.inl.gov/docs/PRs/24033/coverage/peridynamics)
- [`phase_field`](https://mooseframework.inl.gov/docs/PRs/24033/coverage/phase_field)
- [`porous_flow`](https://mooseframework.inl.gov/docs/PRs/24033/coverage/porous_flow)
- [`ray_tracing`](https://mooseframework.inl.gov/docs/PRs/24033/coverage/ray_tracing)
- [`rdg`](https://mooseframework.inl.gov/docs/PRs/24033/coverage/rdg)
- [`reactor`](https://mooseframework.inl.gov/docs/PRs/24033/coverage/reactor)
- [`richards`](https://mooseframework.inl.gov/docs/PRs/24033/coverage/richards)
- [`scalar_transport`](https://mooseframework.inl.gov/docs/PRs/24033/coverage/scalar_transport)
- [`solid_properties`](https://mooseframework.inl.gov/docs/PRs/24033/coverage/solid_properties)
- [`stochastic_tools`](https://mooseframework.inl.gov/docs/PRs/24033/coverage/stochastic_tools)
- [`tensor_mechanics`](https://mooseframework.inl.gov/docs/PRs/24033/coverage/tensor_mechanics)
- [`thermal_hydraulics`](https://mooseframework.inl.gov/docs/PRs/24033/coverage/thermal_hydraulics)
- [`xfem`](https://mooseframework.inl.gov/docs/PRs/24033/coverage/xfem)

</details>



This comment will be updated on new commits.

2023-04-12 14:51 UTC, loganharbour commented
@lindsayad if you wouldn't mind

2023-04-12 17:29 UTC, moosebuild commented
Job [Coverage](https://civet.inl.gov/job/1457339/) on a116706 wanted to post the following:


The following coverage requirement(s) failed:
- `misc` coverage rate 34.31% is less than the required 55.0%
- `phase_field` coverage rate 86.27% is less than the required 89.0%
- `richards` coverage rate 94.75% is less than the required 97.0%
- `tensor_mechanics` coverage rate 85.21% is less than the required 86.0%

2023-04-12 18:19 UTC, lindsayad requested changes

2023-04-12 18:19 UTC, lindsayad commented on test/tests/mesh/splitting/tests
> +      prereq = 'make_split'
```suggestion
      prereq = 'use_split/from_cli
```

2023-04-12 18:19 UTC, lindsayad commented on test/tests/mesh/splitting/tests
> +    prereq = 'use_split/from_cli'
```suggestion
    prereq = 'use_split/from_input'
```

2023-04-12 20:49 UTC, lindsayad approved these changes

2023-04-12 20:51 UTC, GiudGiud approved these changes
awesome. I think this finishes the work for the milestone but we can discuss that more

2023-04-12 22:38 UTC, moosebuild commented
Job [Coverage](https://civet.inl.gov/job/1459021/) on 10a8a74 wanted to post the following:


The following coverage requirement(s) failed:
- `misc` coverage rate 34.31% is less than the required 55.0%
- `phase_field` coverage rate 86.27% is less than the required 89.0%
- `richards` coverage rate 94.75% is less than the required 97.0%
- `tensor_mechanics` coverage rate 85.21% is less than the required 86.0%

2023-04-13 03:06 UTC, merged