Support absolute value tagging in Tensor Mechanics actions
idaholab/moose pull request #24249
Opened 2023-05-03 00:04 UTC by bwspenc

closes #24246

2023-05-03 01:32 UTC, moosebuild commented
Job [Documentation](https://civet.inl.gov/job/1500618/) on 25e4833 wanted to post the following:

View the site [here](https://mooseframework.inl.gov/docs/PRs/24249/site)

This comment will be updated on new commits.

2023-05-04 03:12 UTC, loganharbour reviewed
Can we get this working without changing the underlying `_xxx_tags` variables? 

I would really prefer that we make those private

2023-05-06 16:10 UTC, lindsayad requested changes
Yea we're going to make those data members private in #24206 so this will not work

2023-05-06 16:24 UTC, lindsayad commented
Man I was really hoping to lock down the getters for the tags too, but the design of `GeneralizedPlaneStrain` indicates that ship has already sailed

2023-05-06 17:44 UTC, lindsayad commented
Mmm I think I can still keep this encapsulated in the framework

2023-05-06 17:55 UTC, lindsayad commented
Ok see https://github.com/idaholab/moose/pull/24206/commits/a964f3b697d2b43199a9c9c964871b841e4258b5

2023-05-07 14:51 UTC, loganharbour commented
I talked with @bwspenc quite a while about this too. I don't think that the interface knowing about a problem is a good idea

2023-05-08 16:21 UTC, lindsayad commented
You don't think that `TaggingInterface` querying information on `ReferenceResidualProblem` is a good idea? We have already installed infrastructure in `TaggingInterface` that is specific to `ReferenceResidualProblem`

2023-05-17 00:03 UTC, bwspenc commented
Note that I rebased this against the branch that @tophmatthews and @lindsayad have been working on because this relies on the API changes there to TaggingInterface. We'll want to hold off on merging this until that one gets merged. I did this to verify that the API changes there would meet my needs, which they appear to do.

2023-05-17 00:13 UTC, loganharbour commented
> Note that I rebased this against the branch that @tophmatthews and @lindsayad have been working on because this relies on the API changes there to TaggingInterface. We'll want to hold off on merging this until that one gets merged. I did this to verify that the API changes there would meet my needs, which they appear to do.

Great. I tagged you in the other PR, in case you didn't see it. I'm glad to hear it. I'll resolve that comment.

2023-05-17 01:51 UTC, moosebuild commented
Job [Coverage](https://civet.inl.gov/job/1534035/) on 7e85dfe wanted to post the following:


## Framework coverage

<table>
  <thead>
    <tr>
      <th></th>
      <th>e8e155</th>
      <th colspan=4>#24249 7e85df</th>
    </tr>
    <tr>
      <th></th>
      <th>Total</th>
      <th>Total</th>
      <th>+/-</th>
      <th>New</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><b>Rate</b></td>
      <td>85.22%</td>
      <td>85.33%</td>
      <td>+0.11%</td>
      <td>80.36%</td>
    </tr>
    <tr>
      <td><b>Hits</b></td>
      <td>87941</td>
      <td>88033</td>
      <td>+92</td>
      <td>757</td>
    </tr>
    <tr>
      <td><b>Misses</b></td>
      <td>15247</td>
      <td>15134</td>
      <td>-113</td>
      <td>185</td>
    </tr>
  </tbody>
</table>

[Diff coverage report](https://mooseframework.inl.gov/docs/PRs/24249/coverage_diff/framework)

[Full coverage report](https://mooseframework.inl.gov/docs/PRs/24249/coverage/framework)


## Modules coverage

### Contact

<table>
  <thead>
    <tr>
      <th></th>
      <th>e8e155</th>
      <th colspan=4>#24249 7e85df</th>
    </tr>
    <tr>
      <th></th>
      <th>Total</th>
      <th>Total</th>
      <th>+/-</th>
      <th>New</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><b>Rate</b></td>
      <td>89.98%</td>
      <td>90.10%</td>
      <td>+0.11%</td>
      <td>100.00%</td>
    </tr>
    <tr>
      <td><b>Hits</b></td>
      <td>3594</td>
      <td>3640</td>
      <td>+46</td>
      <td>84</td>
    </tr>
    <tr>
      <td><b>Misses</b></td>
      <td>400</td>
      <td>400</td>
      <td>-</td>
      <td>0</td>
    </tr>
  </tbody>
</table>

[Diff coverage report](https://mooseframework.inl.gov/docs/PRs/24249/coverage_diff/contact)

[Full coverage report](https://mooseframework.inl.gov/docs/PRs/24249/coverage/contact)

### Heat conduction

<table>
  <thead>
    <tr>
      <th></th>
      <th>e8e155</th>
      <th colspan=4>#24249 7e85df</th>
    </tr>
    <tr>
      <th></th>
      <th>Total</th>
      <th>Total</th>
      <th>+/-</th>
      <th>New</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><b>Rate</b></td>
      <td>88.51%</td>
      <td>88.51%</td>
      <td>-</td>
      <td>100.00%</td>
    </tr>
    <tr>
      <td><b>Hits</b></td>
      <td>3559</td>
      <td>3559</td>
      <td>-</td>
      <td>4</td>
    </tr>
    <tr>
      <td><b>Misses</b></td>
      <td>462</td>
      <td>462</td>
      <td>-</td>
      <td>0</td>
    </tr>
  </tbody>
</table>

[Diff coverage report](https://mooseframework.inl.gov/docs/PRs/24249/coverage_diff/heat_conduction)

[Full coverage report](https://mooseframework.inl.gov/docs/PRs/24249/coverage/heat_conduction)

### Navier stokes

<table>
  <thead>
    <tr>
      <th></th>
      <th>e8e155</th>
      <th colspan=4>#24249 7e85df</th>
    </tr>
    <tr>
      <th></th>
      <th>Total</th>
      <th>Total</th>
      <th>+/-</th>
      <th>New</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><b>Rate</b></td>
      <td>83.60%</td>
      <td>83.86%</td>
      <td>+0.25%</td>
      <td>88.75%</td>
    </tr>
    <tr>
      <td><b>Hits</b></td>
      <td>10767</td>
      <td>10799</td>
      <td>+32</td>
      <td>71</td>
    </tr>
    <tr>
      <td><b>Misses</b></td>
      <td>2112</td>
      <td>2079</td>
      <td>-33</td>
      <td>9</td>
    </tr>
  </tbody>
</table>

[Diff coverage report](https://mooseframework.inl.gov/docs/PRs/24249/coverage_diff/navier_stokes)

[Full coverage report](https://mooseframework.inl.gov/docs/PRs/24249/coverage/navier_stokes)

### Peridynamics

<table>
  <thead>
    <tr>
      <th></th>
      <th>e8e155</th>
      <th colspan=4>#24249 7e85df</th>
    </tr>
    <tr>
      <th></th>
      <th>Total</th>
      <th>Total</th>
      <th>+/-</th>
      <th>New</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><b>Rate</b></td>
      <td>78.08%</td>
      <td>78.11%</td>
      <td>+0.03%</td>
      <td>85.71%</td>
    </tr>
    <tr>
      <td><b>Hits</b></td>
      <td>2999</td>
      <td>3011</td>
      <td>+12</td>
      <td>78</td>
    </tr>
    <tr>
      <td><b>Misses</b></td>
      <td>842</td>
      <td>844</td>
      <td>+2</td>
      <td>13</td>
    </tr>
  </tbody>
</table>

[Diff coverage report](https://mooseframework.inl.gov/docs/PRs/24249/coverage_diff/peridynamics)

[Full coverage report](https://mooseframework.inl.gov/docs/PRs/24249/coverage/peridynamics)

### Porous flow

<table>
  <thead>
    <tr>
      <th></th>
      <th>e8e155</th>
      <th colspan=4>#24249 7e85df</th>
    </tr>
    <tr>
      <th></th>
      <th>Total</th>
      <th>Total</th>
      <th>+/-</th>
      <th>New</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><b>Rate</b></td>
      <td>95.90%</td>
      <td>95.90%</td>
      <td>+0.00%</td>
      <td>90.00%</td>
    </tr>
    <tr>
      <td><b>Hits</b></td>
      <td>10699</td>
      <td>10700</td>
      <td>+1</td>
      <td>9</td>
    </tr>
    <tr>
      <td><b>Misses</b></td>
      <td>457</td>
      <td>457</td>
      <td>-</td>
      <td>1</td>
    </tr>
  </tbody>
</table>

[Diff coverage report](https://mooseframework.inl.gov/docs/PRs/24249/coverage_diff/porous_flow)

[Full coverage report](https://mooseframework.inl.gov/docs/PRs/24249/coverage/porous_flow)

### Ray tracing

<table>
  <thead>
    <tr>
      <th></th>
      <th>e8e155</th>
      <th colspan=4>#24249 7e85df</th>
    </tr>
    <tr>
      <th></th>
      <th>Total</th>
      <th>Total</th>
      <th>+/-</th>
      <th>New</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><b>Rate</b></td>
      <td>93.75%</td>
      <td>93.75%</td>
      <td>-</td>
      <td>100.00%</td>
    </tr>
    <tr>
      <td><b>Hits</b></td>
      <td>4078</td>
      <td>4078</td>
      <td>-</td>
      <td>1</td>
    </tr>
    <tr>
      <td><b>Misses</b></td>
      <td>272</td>
      <td>272</td>
      <td>-</td>
      <td>0</td>
    </tr>
  </tbody>
</table>

[Diff coverage report](https://mooseframework.inl.gov/docs/PRs/24249/coverage_diff/ray_tracing)

[Full coverage report](https://mooseframework.inl.gov/docs/PRs/24249/coverage/ray_tracing)

### Richards

<table>
  <thead>
    <tr>
      <th></th>
      <th>e8e155</th>
      <th colspan=4>#24249 7e85df</th>
    </tr>
    <tr>
      <th></th>
      <th>Total</th>
      <th>Total</th>
      <th>+/-</th>
      <th>New</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><b>Rate</b></td>
      <td>94.59%</td>
      <td>94.59%</td>
      <td>+0.00%</td>
      <td>100.00%</td>
    </tr>
    <tr>
      <td><b>Hits</b></td>
      <td>3249</td>
      <td>3252</td>
      <td>+3</td>
      <td>15</td>
    </tr>
    <tr>
      <td><b>Misses</b></td>
      <td>186</td>
      <td>186</td>
      <td>-</td>
      <td>0</td>
    </tr>
  </tbody>
</table>

[Diff coverage report](https://mooseframework.inl.gov/docs/PRs/24249/coverage_diff/richards)

[Full coverage report](https://mooseframework.inl.gov/docs/PRs/24249/coverage/richards)

### Tensor mechanics

<table>
  <thead>
    <tr>
      <th></th>
      <th>e8e155</th>
      <th colspan=4>#24249 7e85df</th>
    </tr>
    <tr>
      <th></th>
      <th>Total</th>
      <th>Total</th>
      <th>+/-</th>
      <th>New</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><b>Rate</b></td>
      <td>84.73%</td>
      <td>84.72%</td>
      <td>-0.02%</td>
      <td>88.89%</td>
    </tr>
    <tr>
      <td><b>Hits</b></td>
      <td>25442</td>
      <td>25446</td>
      <td>+4</td>
      <td>72</td>
    </tr>
    <tr>
      <td><b>Misses</b></td>
      <td>4584</td>
      <td>4591</td>
      <td>+7</td>
      <td>9</td>
    </tr>
  </tbody>
</table>

[Diff coverage report](https://mooseframework.inl.gov/docs/PRs/24249/coverage_diff/tensor_mechanics)

[Full coverage report](https://mooseframework.inl.gov/docs/PRs/24249/coverage/tensor_mechanics)

### Thermal hydraulics

<table>
  <thead>
    <tr>
      <th></th>
      <th>e8e155</th>
      <th colspan=4>#24249 7e85df</th>
    </tr>
    <tr>
      <th></th>
      < [...]

2023-05-22 20:49 UTC, tophmatthews commented
@bwspenc can you rebase now that the !24206 is merged? I'd like to test this out as well!

2023-05-23 21:31 UTC, bwspenc commented
> @bwspenc can you rebase now that the #24206 is merged? I'd like to test this out as well!

Yeah, just rebased. We'll see how the tests do. I didn't actually run them locally yet, but I assume they'll pass.

2023-05-24 20:45 UTC, bwspenc commented
@lindsayad @loganharbour This should be ready to go. It's showing that there are requested changes by @lindsayad, but those have been resolved now. If you don't mind giving this another review, that would be great.

2023-05-24 21:19 UTC, lindsayad requested changes

2023-05-24 21:19 UTC, lindsayad commented on modules/tensor_mechanics/src/actions/TensorMechanicsAction.C
> +      // action_params.set<std::vector<TagName>>("extra_vector_tags") =
```suggestion
```

2023-05-24 21:19 UTC, lindsayad commented on modules/tensor_mechanics/test/tests/free_expansion_abs_ref/free_expansion_abs_ref.i
> +  block = 0
Is this necessary?

2023-05-24 21:19 UTC, lindsayad commented on modules/tensor_mechanics/test/tests/free_expansion_abs_ref/tests
> +    requirement = 'The TensorMechanics Master action shall set up the mechanics kernels with the appropriate options to accumulate absolute values of the residual to a tag vector usable for relative
```suggestion
    requirement = 'The tensor mechanics action shall set up the mechanics kernels with the appropriate options to accumulate absolute values of the residual to a tag vector usable for relative convergence checks.'
```

2023-05-24 21:19 UTC, lindsayad commented on modules/tensor_mechanics/test/tests/generalized_plane_strain/tests
> +    requirement = 'The system shall support a generalized plane strain mechanics solution using the reference residual approach to check solution convergence of the field and scalar variables when th
```suggestion
    requirement = 'The system shall support a generalized plane strain mechanics solution using the reference residual approach to check solution convergence of the field and scalar variables when the reference vector is constructed using absolute value vector tags.'
```

2023-05-24 21:19 UTC, lindsayad commented on modules/tensor_mechanics/test/tests/generalized_plane_strain/tests
> +    requirement = 'The system shall support a generalized plane strain mechanics solution using the reference residual approach to check solution convergence of the field and scalar variables when th
```suggestion
    requirement = 'The system shall support a generalized plane strain mechanics solution using the reference residual approach to check solution convergence of the field and scalar variables when the reference vector is constructed using unbalanced kernel contributions.'
```

2023-05-24 21:19 UTC, lindsayad commented on modules/tensor_mechanics/test/tests/generalized_plane_strain/tests
> +  [./generalized_plane_strain_ref_resid_absolute_value_vector_tags]
```suggestion
  [generalized_plane_strain_ref_resid_absolute_value_vector_tags]
```

2023-05-24 21:19 UTC, lindsayad commented on modules/tensor_mechanics/test/tests/generalized_plane_strain/tests
> +  [./generalized_plane_strain_ref_resid_extra_vector_tags]
```suggestion
  []
  [generalized_plane_strain_ref_resid_extra_vector_tags]
```

2023-05-24 21:27 UTC, loganharbour requested changes
Nothing else from me.

2023-05-24 22:32 UTC, bwspenc commented on modules/tensor_mechanics/test/tests/free_expansion_abs_ref/free_expansion_abs_ref.i
> +  block = 0
It doesn't appear to be. I removed it.

2023-05-25 15:23 UTC, loganharbour approved these changes

2023-05-25 16:29 UTC, lindsayad approved these changes

2023-05-25 16:32 UTC, merged

2023-05-27 05:07 UTC, dschwen commented on modules/tensor_mechanics/src/actions/TensorMechanicsAction.C
> +            getParam<std::vector<TagName>>("absolute_value_vector_tags");
This could have been a one-liner with `applySpecificParameters`.