Dynamic Object Loading Bug
idaholab/moose pull request #24299
Opened 2023-05-08 17:59 UTC by dschwen

## Reason
Demonstrate a weird dynamic object loading bug, where the `[Problem]` action ends up being registered to the `add_ray_kernel` task.

## Design
Add new test that dynamically loads heat conduction.

## Impact
Demonstrate bug for @permcody

2023-05-08 19:41 UTC, moosebuild commented
Job [Documentation](https://civet.inl.gov/job/1509623/) on 163db53 wanted to post the following:

View the site [here](https://mooseframework.inl.gov/docs/PRs/24299/site)

This comment will be updated on new commits.

2023-05-08 20:54 UTC, dschwen commented
This test fails on both Mac and Linux.

2023-05-08 22:38 UTC, permcody commented
Thanks @dschwen!

2023-05-09 00:32 UTC, dschwen commented
```
section_name = Problem
registered_identifier = Problem
   CreateProblemAction  Problem
   DynamicObjectRegistrationAction  Problem
   AddRayBCAction add_ray_boundary_condition RayBCs/*
```

Ok, `Syntax::getActions("Problem")` is called in `Parser::walkRaw`. The resulting range contains at least one item whose key is _not_ `"Problem"... That's a problem. Hehehe.

2023-05-09 00:38 UTC, dschwen commented
Ah, I think I got it

2023-05-09 00:38 UTC, dschwen commented
The `DynamicObjectRegistrationAction` is built and messes up the registry/syntax, invalidating the multimap iterator.

2023-05-09 00:42 UTC, dschwen commented
If I iterate over the retuned result from `Syntax::getActions("Problem")` first, without actually creating any of the objects, I get

```
registered_identifier = Problem
Problem:  { _action: 'CreateProblemAction', _task: '' }
Problem:  { _action: 'DynamicObjectRegistrationAction', _task: '' }
```

which is sane. If I output inside the loop where objects are created I get

```
registered_identifier = Problem
Problem:  { _action: 'CreateProblemAction', _task: '' }
Problem:  { _action: 'DynamicObjectRegistrationAction', _task: '' }
RayBCs/*:  { _action: 'AddRayBCAction', _task: 'add_ray_boundary_condition' }
```

which is ... insane.
```

2023-05-09 14:53 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/1512445/) on e7414fa wanted to post the following:

Your code requires style changes.  

A patch was auto generated and copied [here](https://mooseframework.inl.gov/docs/PRs/24299/clang_format/style.patch)  
You can directly apply the patch by running, in the top level of your repository:

`curl -s https://mooseframework.inl.gov/docs/PRs/24299/clang_format/style.patch | git apply -v`  

Alternatively, with your repository up to date and in the top level of your repository:

`git clang-format 68588b86a8884599e8ff794dfe536ee828f6ab5c`

2023-05-09 14:54 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/1512445/) on e7414fa wanted to post the following:

Your code requires style changes.  

A patch was auto generated and copied [here](https://mooseframework.inl.gov/docs/PRs/24299/clang_format/style.patch)  
You can directly apply the patch by running, in the top level of your repository:

`curl -s https://mooseframework.inl.gov/docs/PRs/24299/clang_format/style.patch | git apply -v`  

Alternatively, with your repository up to date and in the top level of your repository:

`git clang-format 68588b86a8884599e8ff794dfe536ee828f6ab5c`

2023-05-09 14:56 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/1512445/) on e7414fa wanted to post the following:

Your code requires style changes.  

A patch was auto generated and copied [here](https://mooseframework.inl.gov/docs/PRs/24299/clang_format/style.patch)  
You can directly apply the patch by running, in the top level of your repository:

`curl -s https://mooseframework.inl.gov/docs/PRs/24299/clang_format/style.patch | git apply -v`  

Alternatively, with your repository up to date and in the top level of your repository:

`git clang-format 68588b86a8884599e8ff794dfe536ee828f6ab5c`

2023-05-09 14:57 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/1512445/) on e7414fa wanted to post the following:

Your code requires style changes.  

A patch was auto generated and copied [here](https://mooseframework.inl.gov/docs/PRs/24299/clang_format/style.patch)  
You can directly apply the patch by running, in the top level of your repository:

`curl -s https://mooseframework.inl.gov/docs/PRs/24299/clang_format/style.patch | git apply -v`  

Alternatively, with your repository up to date and in the top level of your repository:

`git clang-format 68588b86a8884599e8ff794dfe536ee828f6ab5c`

2023-05-09 14:57 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/1512445/) on e7414fa wanted to post the following:

Your code requires style changes.  

A patch was auto generated and copied [here](https://mooseframework.inl.gov/docs/PRs/24299/clang_format/style.patch)  
You can directly apply the patch by running, in the top level of your repository:

`curl -s https://mooseframework.inl.gov/docs/PRs/24299/clang_format/style.patch | git apply -v`  

Alternatively, with your repository up to date and in the top level of your repository:

`git clang-format 68588b86a8884599e8ff794dfe536ee828f6ab5c`

2023-05-09 14:58 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/1512445/) on e7414fa wanted to post the following:

Your code requires style changes.  

A patch was auto generated and copied [here](https://mooseframework.inl.gov/docs/PRs/24299/clang_format/style.patch)  
You can directly apply the patch by running, in the top level of your repository:

`curl -s https://mooseframework.inl.gov/docs/PRs/24299/clang_format/style.patch | git apply -v`  

Alternatively, with your repository up to date and in the top level of your repository:

`git clang-format 68588b86a8884599e8ff794dfe536ee828f6ab5c`

2023-05-09 17:23 UTC, moosebuild commented
Job [Coverage](https://civet.inl.gov/job/1512823/) on 230cfce wanted to post the following:


## Framework coverage

<table>
  <thead>
    <tr>
      <th></th>
      <th>68588b</th>
      <th colspan=4>#24299 230cfc</th>
    </tr>
    <tr>
      <th></th>
      <th>Total</th>
      <th>Total</th>
      <th>+/-</th>
      <th>New</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><b>Rate</b></td>
      <td>85.18%</td>
      <td>85.18%</td>
      <td>-0.00%</td>
      <td>100.00%</td>
    </tr>
    <tr>
      <td><b>Hits</b></td>
      <td>87211</td>
      <td>87214</td>
      <td>+3</td>
      <td>8</td>
    </tr>
    <tr>
      <td><b>Misses</b></td>
      <td>15170</td>
      <td>15173</td>
      <td>+3</td>
      <td>0</td>
    </tr>
  </tbody>
</table>

[Diff coverage report](https://mooseframework.inl.gov/docs/PRs/24299/coverage_diff/framework)

[Full coverage report](https://mooseframework.inl.gov/docs/PRs/24299/coverage/framework)


## Modules coverage

Coverage did not change

## Full coverage reports

<details>
<summary>Reports</summary>

- [`framework`](https://mooseframework.inl.gov/docs/PRs/24299/coverage/framework)
- [`chemical_reactions`](https://mooseframework.inl.gov/docs/PRs/24299/coverage/chemical_reactions)
- [`combined`](https://mooseframework.inl.gov/docs/PRs/24299/coverage/combined)
- [`contact`](https://mooseframework.inl.gov/docs/PRs/24299/coverage/contact)
- [`electromagnetics`](https://mooseframework.inl.gov/docs/PRs/24299/coverage/electromagnetics)
- [`external_petsc_solver`](https://mooseframework.inl.gov/docs/PRs/24299/coverage/external_petsc_solver)
- [`fluid_properties`](https://mooseframework.inl.gov/docs/PRs/24299/coverage/fluid_properties)
- [`fsi`](https://mooseframework.inl.gov/docs/PRs/24299/coverage/fsi)
- [`functional_expansion_tools`](https://mooseframework.inl.gov/docs/PRs/24299/coverage/functional_expansion_tools)
- [`geochemistry`](https://mooseframework.inl.gov/docs/PRs/24299/coverage/geochemistry)
- [`heat_conduction`](https://mooseframework.inl.gov/docs/PRs/24299/coverage/heat_conduction)
- [`level_set`](https://mooseframework.inl.gov/docs/PRs/24299/coverage/level_set)
- [`misc`](https://mooseframework.inl.gov/docs/PRs/24299/coverage/misc)
- [`navier_stokes`](https://mooseframework.inl.gov/docs/PRs/24299/coverage/navier_stokes)
- [`optimization`](https://mooseframework.inl.gov/docs/PRs/24299/coverage/optimization)
- [`peridynamics`](https://mooseframework.inl.gov/docs/PRs/24299/coverage/peridynamics)
- [`phase_field`](https://mooseframework.inl.gov/docs/PRs/24299/coverage/phase_field)
- [`porous_flow`](https://mooseframework.inl.gov/docs/PRs/24299/coverage/porous_flow)
- [`ray_tracing`](https://mooseframework.inl.gov/docs/PRs/24299/coverage/ray_tracing)
- [`rdg`](https://mooseframework.inl.gov/docs/PRs/24299/coverage/rdg)
- [`reactor`](https://mooseframework.inl.gov/docs/PRs/24299/coverage/reactor)
- [`richards`](https://mooseframework.inl.gov/docs/PRs/24299/coverage/richards)
- [`scalar_transport`](https://mooseframework.inl.gov/docs/PRs/24299/coverage/scalar_transport)
- [`solid_properties`](https://mooseframework.inl.gov/docs/PRs/24299/coverage/solid_properties)
- [`stochastic_tools`](https://mooseframework.inl.gov/docs/PRs/24299/coverage/stochastic_tools)
- [`tensor_mechanics`](https://mooseframework.inl.gov/docs/PRs/24299/coverage/tensor_mechanics)
- [`thermal_hydraulics`](https://mooseframework.inl.gov/docs/PRs/24299/coverage/thermal_hydraulics)
- [`xfem`](https://mooseframework.inl.gov/docs/PRs/24299/coverage/xfem)

</details>



This comment will be updated on new commits.

2023-05-10 17:00 UTC, lindsayad requested changes

2023-05-10 17:00 UTC, lindsayad commented on modules/misc/test/tests/dynamic_loading/dynamic_obj_registration/tests
> +  [./dynamic_object_loading2]
```suggestion
  [dynamic_object_loading2]
```

2023-05-22 02:13 UTC, dschwen commented on framework/src/parser/Parser.C
> +    processed_actions.insert(&it->second);
I'm open to suggestions

2023-05-22 16:52 UTC, lindsayad commented on framework/src/parser/Parser.C
> +    processed_actions.insert(&it->second);
I don't have any better ones. I'm just agreeing with my buddy

2023-05-22 16:53 UTC, lindsayad commented on modules/misc/test/tests/dynamic_loading/dynamic_obj_registration/tests
@dschwen it would be nice to get a `requirement` added here

2023-05-22 16:54 UTC, lindsayad commented
@YaqiWang @zachmprince would it be possible update that regex in the Griffin test that's failing on this PR?

2023-05-22 16:55 UTC, moosebuild commented
Job [No optional](https://civet.inl.gov/job/1540400/) on c0718e2 : invalidated by @lindsayad

2023-05-22 16:55 UTC, moosebuild commented
Job [Conda (Ubuntu)](https://civet.inl.gov/job/1540396/) on c0718e2 : invalidated by @lindsayad

2023-05-22 17:28 UTC, dschwen commented on modules/misc/test/tests/dynamic_loading/dynamic_obj_registration/tests
oh boy. I hope that does not mean adding SQA stuff for _all_ tests in that file....

2023-05-22 17:50 UTC, lindsayad commented on modules/misc/test/tests/dynamic_loading/dynamic_obj_registration/tests
It will. Do you want help?

2023-05-22 18:22 UTC, dschwen commented on modules/misc/test/tests/dynamic_loading/dynamic_obj_registration/tests
Let get started on this and I will leave out what I cannot figure out.

2023-05-24 04:12 UTC, dschwen commented on modules/misc/test/tests/dynamic_loading/dynamic_obj_registration/tests
Added all the sqa stuff

2023-05-24 04:14 UTC, GiudGiud approved these changes

2023-05-24 05:08 UTC, lindsayad approved these changes

2023-05-24 05:08 UTC, lindsayad commented on modules/misc/test/tests/dynamic_loading/dynamic_obj_registration/tests
a true hero of the people

2023-05-24 12:25 UTC, merged