Update instruments profiling instructions
idaholab/moose pull request #24332
Opened 2023-05-11 17:28 UTC by parikshitbajpai

Refs #24331

2023-05-11 17:30 UTC, parikshitbajpai commented
I can't check if the previous instructions still work on the older MacOS versions so I've left them as they were.

2023-05-11 20:04 UTC, moosebuild commented
Job [Documentation](https://civet.inl.gov/job/1519470/) on b8a29d9 wanted to post the following:

View the site [here](https://mooseframework.inl.gov/docs/PRs/24332/site)

This comment will be updated on new commits.

2023-05-14 16:44 UTC, cticenhour requested changes
Putting in an initial review of the markdown content, with a double-check of the new directions with a MOOSE app likely occurring tomorrow (maybe today if I have time). 

Thanks for updating this! Just a few changes to improve the website render.

2023-05-14 16:44 UTC, cticenhour commented on modules/doc/content/application_development/profiling.md
> +and select the processes you want to be converted, then copy the data using _Deep Copy_ in the _Edit_ menu. The copied
```suggestion
and select the processes you want to be converted, then copy the data using *Deep Copy* in the *Edit* menu. The copied
```

"MooseDown" doesn't recognize the underscores for italics, so let's switch these to asterisks.

2023-05-14 16:44 UTC, cticenhour commented on modules/doc/content/application_development/profiling.md
> +using [InstrumentsToPprof](https://github.com/google/instrumentsToPprof). To do this, open the trace in Instruments
```suggestion
using [instrumentsToPprof](https://github.com/google/instrumentsToPprof). To do this, open the trace in Instruments
```

2023-05-14 16:44 UTC, cticenhour commented on modules/doc/content/application_development/profiling.md
> +which will produce a `profile.pb.gz` which can be analyzed using `pprof` following the same instructions as above.
```suggestion
data can be piped to `instrumentsToPprof` as

```
pbpaste | instrumentsToPprof
```

which will produce a `profile.pb.gz` which can be analyzed using `pprof` following the same instructions as above.
```

Need to add some space for this to properly render as a code snippet block.

2023-05-14 16:46 UTC, cticenhour commented on modules/doc/content/application_development/profiling.md
> +data can be piped to `instrumentsToPprof` as
```suggestion
data can be piped to `instrumentsToPprof` as

```

Had to split this suggestion into two....GitHub markdown and our markdown had a bit of a conflict...

2023-05-14 16:46 UTC, cticenhour commented on modules/doc/content/application_development/profiling.md
> +which will produce a `profile.pb.gz` which can be analyzed using `pprof` following the same instructions as above.
```suggestion

which will produce a `profile.pb.gz` which can be analyzed using `pprof` following the same instructions as above.
```

2023-05-15 15:37 UTC, cticenhour approved these changes
Tested the instructions this morning - works great on Ventura 13.3.1. Pending the last test recipe passing (had to invalidate due to a bad HTTPS gateway on CIVET), this is good to go.

2023-05-15 16:21 UTC, merged