Functor thermal solid properties
idaholab/moose pull request #24351
Opened 2023-05-13 18:22 UTC by GiudGiud

For @tanoret

2023-05-13 20:06 UTC, moosebuild commented
Job [Documentation](https://civet.inl.gov/job/1526232/) on 1c191c5 wanted to post the following:

View the site [here](https://mooseframework.inl.gov/docs/PRs/24351/site)

This comment will be updated on new commits.

2023-05-13 20:07 UTC, moosebuild commented
Job [Coverage](https://civet.inl.gov/job/1526270/) on 1c191c5 wanted to post the following:


## Framework coverage

<table>
  <thead>
    <tr>
      <th></th>
      <th>b9c8e6</th>
      <th colspan=4>#24351 1c191c</th>
    </tr>
    <tr>
      <th></th>
      <th>Total</th>
      <th>Total</th>
      <th>+/-</th>
      <th>New</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><b>Rate</b></td>
      <td>85.20%</td>
      <td>85.20%</td>
      <td>-0.00%</td>
      <td>-</td>
    </tr>
    <tr>
      <td><b>Hits</b></td>
      <td>87717</td>
      <td>87713</td>
      <td>-4</td>
      <td>0</td>
    </tr>
    <tr>
      <td><b>Misses</b></td>
      <td>15238</td>
      <td>15242</td>
      <td>+4</td>
      <td>0</td>
    </tr>
  </tbody>
</table>

[Diff coverage report](https://mooseframework.inl.gov/docs/PRs/24351/coverage_diff/framework)

[Full coverage report](https://mooseframework.inl.gov/docs/PRs/24351/coverage/framework)


## Modules coverage

### Solid properties

<table>
  <thead>
    <tr>
      <th></th>
      <th>b9c8e6</th>
      <th colspan=4>#24351 1c191c</th>
    </tr>
    <tr>
      <th></th>
      <th>Total</th>
      <th>Total</th>
      <th>+/-</th>
      <th>New</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><b>Rate</b></td>
      <td>83.02%</td>
      <td>83.87%</td>
      <td>+0.85%</td>
      <td>95.65%</td>
    </tr>
    <tr>
      <td><b>Hits</b></td>
      <td>264</td>
      <td>286</td>
      <td>+22</td>
      <td>22</td>
    </tr>
    <tr>
      <td><b>Misses</b></td>
      <td>54</td>
      <td>55</td>
      <td>+1</td>
      <td>1</td>
    </tr>
  </tbody>
</table>

[Diff coverage report](https://mooseframework.inl.gov/docs/PRs/24351/coverage_diff/solid_properties)

[Full coverage report](https://mooseframework.inl.gov/docs/PRs/24351/coverage/solid_properties)

## Full coverage reports

<details>
<summary>Reports</summary>

- [`framework`](https://mooseframework.inl.gov/docs/PRs/24351/coverage/framework)
- [`chemical_reactions`](https://mooseframework.inl.gov/docs/PRs/24351/coverage/chemical_reactions)
- [`combined`](https://mooseframework.inl.gov/docs/PRs/24351/coverage/combined)
- [`contact`](https://mooseframework.inl.gov/docs/PRs/24351/coverage/contact)
- [`electromagnetics`](https://mooseframework.inl.gov/docs/PRs/24351/coverage/electromagnetics)
- [`external_petsc_solver`](https://mooseframework.inl.gov/docs/PRs/24351/coverage/external_petsc_solver)
- [`fluid_properties`](https://mooseframework.inl.gov/docs/PRs/24351/coverage/fluid_properties)
- [`fsi`](https://mooseframework.inl.gov/docs/PRs/24351/coverage/fsi)
- [`functional_expansion_tools`](https://mooseframework.inl.gov/docs/PRs/24351/coverage/functional_expansion_tools)
- [`geochemistry`](https://mooseframework.inl.gov/docs/PRs/24351/coverage/geochemistry)
- [`heat_conduction`](https://mooseframework.inl.gov/docs/PRs/24351/coverage/heat_conduction)
- [`level_set`](https://mooseframework.inl.gov/docs/PRs/24351/coverage/level_set)
- [`misc`](https://mooseframework.inl.gov/docs/PRs/24351/coverage/misc)
- [`navier_stokes`](https://mooseframework.inl.gov/docs/PRs/24351/coverage/navier_stokes)
- [`optimization`](https://mooseframework.inl.gov/docs/PRs/24351/coverage/optimization)
- [`peridynamics`](https://mooseframework.inl.gov/docs/PRs/24351/coverage/peridynamics)
- [`phase_field`](https://mooseframework.inl.gov/docs/PRs/24351/coverage/phase_field)
- [`porous_flow`](https://mooseframework.inl.gov/docs/PRs/24351/coverage/porous_flow)
- [`ray_tracing`](https://mooseframework.inl.gov/docs/PRs/24351/coverage/ray_tracing)
- [`rdg`](https://mooseframework.inl.gov/docs/PRs/24351/coverage/rdg)
- [`reactor`](https://mooseframework.inl.gov/docs/PRs/24351/coverage/reactor)
- [`richards`](https://mooseframework.inl.gov/docs/PRs/24351/coverage/richards)
- [`scalar_transport`](https://mooseframework.inl.gov/docs/PRs/24351/coverage/scalar_transport)
- [`solid_properties`](https://mooseframework.inl.gov/docs/PRs/24351/coverage/solid_properties)
- [`stochastic_tools`](https://mooseframework.inl.gov/docs/PRs/24351/coverage/stochastic_tools)
- [`tensor_mechanics`](https://mooseframework.inl.gov/docs/PRs/24351/coverage/tensor_mechanics)
- [`thermal_hydraulics`](https://mooseframework.inl.gov/docs/PRs/24351/coverage/thermal_hydraulics)
- [`xfem`](https://mooseframework.inl.gov/docs/PRs/24351/coverage/xfem)

</details>



This comment will be updated on new commits.

2023-05-13 22:44 UTC, GiudGiud commented on modules/solid_properties/src/materials/ThermalSolidPropertiesFunctorMaterial.C
> +  addFunctorProperty<ADReal>(getParam<std::string>(SolidPropertiesNames::specific_heat),
given the new conversion capability I dont think there s a need to template those on AD anymore

2023-05-15 12:56 UTC, joshuahansel requested changes
Just the typo.

2023-05-15 12:56 UTC, joshuahansel commented on modules/solid_properties/test/tests/materials/thermal_solid_functor_properties/tests
> +    requirement = "The system shall provide the ability to use functor for solid material "
```suggestion
    requirement = "The system shall provide the ability to use functors for solid material "
```

2023-05-15 12:59 UTC, GiudGiud commented
Squashed in

2023-05-15 13:01 UTC, joshuahansel approved these changes

2023-05-15 18:31 UTC, merged