Change ComposeTimeStepperAction from MooseObjectAction to Action #24422
idaholab/moose pull request #24425
Opened 2023-05-19 01:02 UTC by MengnanLi91

close #24422

2023-05-19 01:04 UTC, MengnanLi91 commented
@loganharbour The time stepper PR

2023-05-19 02:18 UTC, GiudGiud commented on framework/doc/content/syntax/Executioner/TimeSteppers/index.md
> +  type = Transient   # Here we use the Transient Executioner
```suggestion
  type = Transient
```

2023-05-19 02:19 UTC, GiudGiud commented on framework/doc/content/syntax/Executioner/TimeSteppers/index.md
> +  type = Transient   # Here we use the Transient Executioner
```suggestion
  type = Transient
```

2023-05-19 02:39 UTC, moosebuild commented
Job [Documentation](https://civet.inl.gov/job/1539460/) on 7db203e wanted to post the following:

View the site [here](https://mooseframework.inl.gov/docs/PRs/24425/site)

This comment will be updated on new commits.

2023-05-19 02:58 UTC, moosebuild commented
Job [Coverage](https://civet.inl.gov/job/1539501/) on 7db203e wanted to post the following:


## Framework coverage

<table>
  <thead>
    <tr>
      <th></th>
      <th>eec47d</th>
      <th colspan=4>#24425 7db203</th>
    </tr>
    <tr>
      <th></th>
      <th>Total</th>
      <th>Total</th>
      <th>+/-</th>
      <th>New</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><b>Rate</b></td>
      <td>85.26%</td>
      <td>85.26%</td>
      <td>-0.00%</td>
      <td>100.00%</td>
    </tr>
    <tr>
      <td><b>Hits</b></td>
      <td>88170</td>
      <td>88167</td>
      <td>-3</td>
      <td>4</td>
    </tr>
    <tr>
      <td><b>Misses</b></td>
      <td>15245</td>
      <td>15245</td>
      <td>-</td>
      <td>0</td>
    </tr>
  </tbody>
</table>

[Diff coverage report](https://mooseframework.inl.gov/docs/PRs/24425/coverage_diff/framework)

[Full coverage report](https://mooseframework.inl.gov/docs/PRs/24425/coverage/framework)


## Modules coverage

Coverage did not change

## Full coverage reports

<details>
<summary>Reports</summary>

- [`framework`](https://mooseframework.inl.gov/docs/PRs/24425/coverage/framework)
- [`chemical_reactions`](https://mooseframework.inl.gov/docs/PRs/24425/coverage/chemical_reactions)
- [`combined`](https://mooseframework.inl.gov/docs/PRs/24425/coverage/combined)
- [`contact`](https://mooseframework.inl.gov/docs/PRs/24425/coverage/contact)
- [`electromagnetics`](https://mooseframework.inl.gov/docs/PRs/24425/coverage/electromagnetics)
- [`external_petsc_solver`](https://mooseframework.inl.gov/docs/PRs/24425/coverage/external_petsc_solver)
- [`fluid_properties`](https://mooseframework.inl.gov/docs/PRs/24425/coverage/fluid_properties)
- [`fsi`](https://mooseframework.inl.gov/docs/PRs/24425/coverage/fsi)
- [`functional_expansion_tools`](https://mooseframework.inl.gov/docs/PRs/24425/coverage/functional_expansion_tools)
- [`geochemistry`](https://mooseframework.inl.gov/docs/PRs/24425/coverage/geochemistry)
- [`heat_conduction`](https://mooseframework.inl.gov/docs/PRs/24425/coverage/heat_conduction)
- [`level_set`](https://mooseframework.inl.gov/docs/PRs/24425/coverage/level_set)
- [`misc`](https://mooseframework.inl.gov/docs/PRs/24425/coverage/misc)
- [`navier_stokes`](https://mooseframework.inl.gov/docs/PRs/24425/coverage/navier_stokes)
- [`optimization`](https://mooseframework.inl.gov/docs/PRs/24425/coverage/optimization)
- [`peridynamics`](https://mooseframework.inl.gov/docs/PRs/24425/coverage/peridynamics)
- [`phase_field`](https://mooseframework.inl.gov/docs/PRs/24425/coverage/phase_field)
- [`porous_flow`](https://mooseframework.inl.gov/docs/PRs/24425/coverage/porous_flow)
- [`ray_tracing`](https://mooseframework.inl.gov/docs/PRs/24425/coverage/ray_tracing)
- [`rdg`](https://mooseframework.inl.gov/docs/PRs/24425/coverage/rdg)
- [`reactor`](https://mooseframework.inl.gov/docs/PRs/24425/coverage/reactor)
- [`richards`](https://mooseframework.inl.gov/docs/PRs/24425/coverage/richards)
- [`scalar_transport`](https://mooseframework.inl.gov/docs/PRs/24425/coverage/scalar_transport)
- [`solid_properties`](https://mooseframework.inl.gov/docs/PRs/24425/coverage/solid_properties)
- [`stochastic_tools`](https://mooseframework.inl.gov/docs/PRs/24425/coverage/stochastic_tools)
- [`tensor_mechanics`](https://mooseframework.inl.gov/docs/PRs/24425/coverage/tensor_mechanics)
- [`thermal_hydraulics`](https://mooseframework.inl.gov/docs/PRs/24425/coverage/thermal_hydraulics)
- [`xfem`](https://mooseframework.inl.gov/docs/PRs/24425/coverage/xfem)

</details>



This comment will be updated on new commits.

2023-05-20 14:57 UTC, loganharbour requested changes

2023-05-20 14:57 UTC, loganharbour commented on test/tests/time_steppers/time_stepper_system/tests
> +      detail ='input time stepper(s) is not used.'
```suggestion
      detail = 'the syntax for multiple time steppers is used without an additional nested block for the time stepper'
```

2023-05-20 14:57 UTC, loganharbour approved these changes, later dismissed

2023-05-22 16:56 UTC, moosebuild commented
Job [Conda (Ubuntu)](https://civet.inl.gov/job/1540875/) on 7a32847 : invalidated by @MengnanLi91

mooseutils/tests.civet_results FAILED (CRASH)

2023-05-22 19:35 UTC, GiudGiud approved these changes

2023-05-22 21:50 UTC, loganharbour approved these changes

2023-05-22 21:50 UTC, merged