Add POD errors for unsupported functionality
idaholab/moose pull request #24470
Opened 2023-05-24 17:20 UTC by grmnptr

refs #24464

2023-05-24 19:00 UTC, moosebuild commented
Job [Documentation](https://civet.inl.gov/job/1547448/) on 02a1c51 wanted to post the following:

View the site [here](https://mooseframework.inl.gov/docs/PRs/24470/site)

This comment will be updated on new commits.

2023-05-24 19:21 UTC, moosebuild commented
Job [Coverage](https://civet.inl.gov/job/1547466/) on 02a1c51 wanted to post the following:


## Framework coverage

<table>
  <thead>
    <tr>
      <th></th>
      <th>a7a0bd</th>
      <th colspan=4>#24470 02a1c5</th>
    </tr>
    <tr>
      <th></th>
      <th>Total</th>
      <th>Total</th>
      <th>+/-</th>
      <th>New</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><b>Rate</b></td>
      <td>85.36%</td>
      <td>85.36%</td>
      <td>+0.00%</td>
      <td>-</td>
    </tr>
    <tr>
      <td><b>Hits</b></td>
      <td>88296</td>
      <td>88299</td>
      <td>+3</td>
      <td>0</td>
    </tr>
    <tr>
      <td><b>Misses</b></td>
      <td>15149</td>
      <td>15146</td>
      <td>-3</td>
      <td>0</td>
    </tr>
  </tbody>
</table>

[Diff coverage report](https://mooseframework.inl.gov/docs/PRs/24470/coverage_diff/framework)

[Full coverage report](https://mooseframework.inl.gov/docs/PRs/24470/coverage/framework)


## Modules coverage

### Stochastic tools

<table>
  <thead>
    <tr>
      <th></th>
      <th>a7a0bd</th>
      <th colspan=4>#24470 02a1c5</th>
    </tr>
    <tr>
      <th></th>
      <th>Total</th>
      <th>Total</th>
      <th>+/-</th>
      <th>New</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><b>Rate</b></td>
      <td>90.74%</td>
      <td>90.73%</td>
      <td>-0.01%</td>
      <td>63.64%</td>
    </tr>
    <tr>
      <td><b>Hits</b></td>
      <td>6883</td>
      <td>6884</td>
      <td>+1</td>
      <td>7</td>
    </tr>
    <tr>
      <td><b>Misses</b></td>
      <td>702</td>
      <td>703</td>
      <td>+1</td>
      <td>4</td>
    </tr>
  </tbody>
</table>

[Diff coverage report](https://mooseframework.inl.gov/docs/PRs/24470/coverage_diff/stochastic_tools)

[Full coverage report](https://mooseframework.inl.gov/docs/PRs/24470/coverage/stochastic_tools)

## Full coverage reports

<details>
<summary>Reports</summary>

- [`framework`](https://mooseframework.inl.gov/docs/PRs/24470/coverage/framework)
- [`chemical_reactions`](https://mooseframework.inl.gov/docs/PRs/24470/coverage/chemical_reactions)
- [`combined`](https://mooseframework.inl.gov/docs/PRs/24470/coverage/combined)
- [`contact`](https://mooseframework.inl.gov/docs/PRs/24470/coverage/contact)
- [`electromagnetics`](https://mooseframework.inl.gov/docs/PRs/24470/coverage/electromagnetics)
- [`external_petsc_solver`](https://mooseframework.inl.gov/docs/PRs/24470/coverage/external_petsc_solver)
- [`fluid_properties`](https://mooseframework.inl.gov/docs/PRs/24470/coverage/fluid_properties)
- [`fsi`](https://mooseframework.inl.gov/docs/PRs/24470/coverage/fsi)
- [`functional_expansion_tools`](https://mooseframework.inl.gov/docs/PRs/24470/coverage/functional_expansion_tools)
- [`geochemistry`](https://mooseframework.inl.gov/docs/PRs/24470/coverage/geochemistry)
- [`heat_conduction`](https://mooseframework.inl.gov/docs/PRs/24470/coverage/heat_conduction)
- [`level_set`](https://mooseframework.inl.gov/docs/PRs/24470/coverage/level_set)
- [`misc`](https://mooseframework.inl.gov/docs/PRs/24470/coverage/misc)
- [`navier_stokes`](https://mooseframework.inl.gov/docs/PRs/24470/coverage/navier_stokes)
- [`optimization`](https://mooseframework.inl.gov/docs/PRs/24470/coverage/optimization)
- [`peridynamics`](https://mooseframework.inl.gov/docs/PRs/24470/coverage/peridynamics)
- [`phase_field`](https://mooseframework.inl.gov/docs/PRs/24470/coverage/phase_field)
- [`porous_flow`](https://mooseframework.inl.gov/docs/PRs/24470/coverage/porous_flow)
- [`ray_tracing`](https://mooseframework.inl.gov/docs/PRs/24470/coverage/ray_tracing)
- [`rdg`](https://mooseframework.inl.gov/docs/PRs/24470/coverage/rdg)
- [`reactor`](https://mooseframework.inl.gov/docs/PRs/24470/coverage/reactor)
- [`richards`](https://mooseframework.inl.gov/docs/PRs/24470/coverage/richards)
- [`scalar_transport`](https://mooseframework.inl.gov/docs/PRs/24470/coverage/scalar_transport)
- [`solid_properties`](https://mooseframework.inl.gov/docs/PRs/24470/coverage/solid_properties)
- [`stochastic_tools`](https://mooseframework.inl.gov/docs/PRs/24470/coverage/stochastic_tools)
- [`tensor_mechanics`](https://mooseframework.inl.gov/docs/PRs/24470/coverage/tensor_mechanics)
- [`thermal_hydraulics`](https://mooseframework.inl.gov/docs/PRs/24470/coverage/thermal_hydraulics)
- [`xfem`](https://mooseframework.inl.gov/docs/PRs/24470/coverage/xfem)

</details>

## Warnings

- `stochastic_tools` new line coverage rate 63.64% is less than the suggested 90.0%



This comment will be updated on new commits.

2023-05-24 22:05 UTC, GiudGiud approved these changes

2023-05-24 23:19 UTC, zachmprince requested changes

2023-05-24 23:23 UTC, grmnptr commented on modules/stochastic_tools/src/multiapps/PODFullSolveMultiApp.C
> +    paramError("max_procs_per_app", " does not support more than one processors per subapp!");
We need to have exactly 1 processor per app so I thought capping it with `max=1` would be reasonable. What do you think? Should I switch this to a regular `mooseError`?

2023-05-25 02:47 UTC, zachmprince commented on modules/stochastic_tools/src/multiapps/PODFullSolveMultiApp.C
> +    paramError("max_procs_per_app", " does not support more than one processors per subapp!");
Oh I see, that's fine.

2023-05-25 02:47 UTC, moosebuild commented
Job [Controlled app tests](https://civet.inl.gov/job/1547447/) on 02a1c51 : invalidated by @zachmprince

Unrelated thing I need to fix

2023-05-25 15:28 UTC, moosebuild commented
Job [Controlled app tests](https://civet.inl.gov/job/1547447/) on 02a1c51 : invalidated by @grmnptr

ANL gitlab working now

2023-05-25 16:36 UTC, zachmprince approved these changes

2023-05-25 17:02 UTC, merged