Parsed downselection of sidesets from other sidesets
idaholab/moose pull request #24490
Opened 2023-05-26 00:12 UTC by GiudGiud

Replaces #24363

Uses the ParsedGenerateSideset

2023-05-26 00:18 UTC, GiudGiud commented
There's a rider commit on nodeset generation. If we dont have that the nodeset gets generated from the sideset after automartically. This MG has a line setting the nodeset name, so it seems like it should generate the nodeset.

Alternatively I can remove the line setting the nodeset name at the end, or add a parameter to select if the nodeset should be generated or not.

i think it s all pretty equivalent.

2023-05-26 02:09 UTC, moosebuild commented
Job [Documentation](https://civet.inl.gov/job/1553196/) on 91f5afa wanted to post the following:

View the site [here](https://mooseframework.inl.gov/docs/PRs/24490/site)

This comment will be updated on new commits.

2023-05-28 15:28 UTC, moosebuild commented
Job [Coverage](https://civet.inl.gov/job/1556451/) on 2536f99 wanted to post the following:


## Framework coverage

<table>
  <thead>
    <tr>
      <th></th>
      <th>447dca</th>
      <th colspan=4>#24490 2536f9</th>
    </tr>
    <tr>
      <th></th>
      <th>Total</th>
      <th>Total</th>
      <th>+/-</th>
      <th>New</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><b>Rate</b></td>
      <td>85.36%</td>
      <td>85.37%</td>
      <td>+0.00%</td>
      <td>100.00%</td>
    </tr>
    <tr>
      <td><b>Hits</b></td>
      <td>88359</td>
      <td>88374</td>
      <td>+15</td>
      <td>15</td>
    </tr>
    <tr>
      <td><b>Misses</b></td>
      <td>15150</td>
      <td>15150</td>
      <td>-</td>
      <td>0</td>
    </tr>
  </tbody>
</table>

[Diff coverage report](https://mooseframework.inl.gov/docs/PRs/24490/coverage_diff/framework)

[Full coverage report](https://mooseframework.inl.gov/docs/PRs/24490/coverage/framework)


## Modules coverage

Coverage did not change

## Full coverage reports

<details>
<summary>Reports</summary>

- [`framework`](https://mooseframework.inl.gov/docs/PRs/24490/coverage/framework)
- [`chemical_reactions`](https://mooseframework.inl.gov/docs/PRs/24490/coverage/chemical_reactions)
- [`combined`](https://mooseframework.inl.gov/docs/PRs/24490/coverage/combined)
- [`contact`](https://mooseframework.inl.gov/docs/PRs/24490/coverage/contact)
- [`electromagnetics`](https://mooseframework.inl.gov/docs/PRs/24490/coverage/electromagnetics)
- [`external_petsc_solver`](https://mooseframework.inl.gov/docs/PRs/24490/coverage/external_petsc_solver)
- [`fluid_properties`](https://mooseframework.inl.gov/docs/PRs/24490/coverage/fluid_properties)
- [`fsi`](https://mooseframework.inl.gov/docs/PRs/24490/coverage/fsi)
- [`functional_expansion_tools`](https://mooseframework.inl.gov/docs/PRs/24490/coverage/functional_expansion_tools)
- [`geochemistry`](https://mooseframework.inl.gov/docs/PRs/24490/coverage/geochemistry)
- [`heat_conduction`](https://mooseframework.inl.gov/docs/PRs/24490/coverage/heat_conduction)
- [`level_set`](https://mooseframework.inl.gov/docs/PRs/24490/coverage/level_set)
- [`misc`](https://mooseframework.inl.gov/docs/PRs/24490/coverage/misc)
- [`navier_stokes`](https://mooseframework.inl.gov/docs/PRs/24490/coverage/navier_stokes)
- [`optimization`](https://mooseframework.inl.gov/docs/PRs/24490/coverage/optimization)
- [`peridynamics`](https://mooseframework.inl.gov/docs/PRs/24490/coverage/peridynamics)
- [`phase_field`](https://mooseframework.inl.gov/docs/PRs/24490/coverage/phase_field)
- [`porous_flow`](https://mooseframework.inl.gov/docs/PRs/24490/coverage/porous_flow)
- [`ray_tracing`](https://mooseframework.inl.gov/docs/PRs/24490/coverage/ray_tracing)
- [`rdg`](https://mooseframework.inl.gov/docs/PRs/24490/coverage/rdg)
- [`reactor`](https://mooseframework.inl.gov/docs/PRs/24490/coverage/reactor)
- [`richards`](https://mooseframework.inl.gov/docs/PRs/24490/coverage/richards)
- [`scalar_transport`](https://mooseframework.inl.gov/docs/PRs/24490/coverage/scalar_transport)
- [`solid_properties`](https://mooseframework.inl.gov/docs/PRs/24490/coverage/solid_properties)
- [`stochastic_tools`](https://mooseframework.inl.gov/docs/PRs/24490/coverage/stochastic_tools)
- [`tensor_mechanics`](https://mooseframework.inl.gov/docs/PRs/24490/coverage/tensor_mechanics)
- [`thermal_hydraulics`](https://mooseframework.inl.gov/docs/PRs/24490/coverage/thermal_hydraulics)
- [`xfem`](https://mooseframework.inl.gov/docs/PRs/24490/coverage/xfem)

</details>



This comment will be updated on new commits.

2023-05-29 12:34 UTC, moosebuild commented
Job [Conda (Ubuntu)](https://civet.inl.gov/job/1556443/) on 2536f99 : invalidated by @GiudGiud

unrelated

2023-05-30 17:32 UTC, lindsayad requested changes

2023-05-30 17:32 UTC, lindsayad commented on framework/src/meshgenerators/ParsedGenerateSideset.C
> +          boundary_info.add_node(&node, boundary_ids[0]);
```suggestion
```
I don't like this very much. The class is suffixed with `Sideset`. We already build node lists from side lists by default anyway after mesh generation is all done. You can remove the line in this class where we set the name of the nodeset for more consistency

2023-05-30 17:32 UTC, lindsayad commented on test/tests/meshgenerators/parsed_generate_sideset/tests
> +
```suggestion
```

2023-05-30 18:44 UTC, lindsayad approved these changes

2023-05-30 19:58 UTC, GiudGiud commented
Failures in Sodium are unrelated

2023-05-30 19:58 UTC, merged

2023-05-30 19:58 UTC, GiudGiud commented
Thanks for the review!