Additional fluid properties documentation & tests metadata
idaholab/moose pull request #24585
Opened 2023-06-03 17:15 UTC by GiudGiud

2023-06-03 18:49 UTC, moosebuild commented
Job [Documentation](https://civet.inl.gov/job/1567232/) on e3155c1 wanted to post the following:

View the site [here](https://mooseframework.inl.gov/docs/PRs/24585/site)

This comment will be updated on new commits.

2023-06-03 19:11 UTC, moosebuild commented
Job [Coverage](https://civet.inl.gov/job/1567273/) on e3155c1 wanted to post the following:


## Framework coverage

<table>
  <thead>
    <tr>
      <th></th>
      <th>968eb4</th>
      <th colspan=4>#24585 e3155c</th>
    </tr>
    <tr>
      <th></th>
      <th>Total</th>
      <th>Total</th>
      <th>+/-</th>
      <th>New</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><b>Rate</b></td>
      <td>85.40%</td>
      <td>85.39%</td>
      <td>-0.00%</td>
      <td>-</td>
    </tr>
    <tr>
      <td><b>Hits</b></td>
      <td>88702</td>
      <td>88699</td>
      <td>-3</td>
      <td>0</td>
    </tr>
    <tr>
      <td><b>Misses</b></td>
      <td>15168</td>
      <td>15171</td>
      <td>+3</td>
      <td>0</td>
    </tr>
  </tbody>
</table>

[Diff coverage report](https://mooseframework.inl.gov/docs/PRs/24585/coverage_diff/framework)

[Full coverage report](https://mooseframework.inl.gov/docs/PRs/24585/coverage/framework)


## Modules coverage

Coverage did not change

## Full coverage reports

<details>
<summary>Reports</summary>

- [`framework`](https://mooseframework.inl.gov/docs/PRs/24585/coverage/framework)
- [`chemical_reactions`](https://mooseframework.inl.gov/docs/PRs/24585/coverage/chemical_reactions)
- [`combined`](https://mooseframework.inl.gov/docs/PRs/24585/coverage/combined)
- [`contact`](https://mooseframework.inl.gov/docs/PRs/24585/coverage/contact)
- [`electromagnetics`](https://mooseframework.inl.gov/docs/PRs/24585/coverage/electromagnetics)
- [`external_petsc_solver`](https://mooseframework.inl.gov/docs/PRs/24585/coverage/external_petsc_solver)
- [`fluid_properties`](https://mooseframework.inl.gov/docs/PRs/24585/coverage/fluid_properties)
- [`fsi`](https://mooseframework.inl.gov/docs/PRs/24585/coverage/fsi)
- [`functional_expansion_tools`](https://mooseframework.inl.gov/docs/PRs/24585/coverage/functional_expansion_tools)
- [`geochemistry`](https://mooseframework.inl.gov/docs/PRs/24585/coverage/geochemistry)
- [`heat_conduction`](https://mooseframework.inl.gov/docs/PRs/24585/coverage/heat_conduction)
- [`level_set`](https://mooseframework.inl.gov/docs/PRs/24585/coverage/level_set)
- [`misc`](https://mooseframework.inl.gov/docs/PRs/24585/coverage/misc)
- [`navier_stokes`](https://mooseframework.inl.gov/docs/PRs/24585/coverage/navier_stokes)
- [`optimization`](https://mooseframework.inl.gov/docs/PRs/24585/coverage/optimization)
- [`peridynamics`](https://mooseframework.inl.gov/docs/PRs/24585/coverage/peridynamics)
- [`phase_field`](https://mooseframework.inl.gov/docs/PRs/24585/coverage/phase_field)
- [`porous_flow`](https://mooseframework.inl.gov/docs/PRs/24585/coverage/porous_flow)
- [`ray_tracing`](https://mooseframework.inl.gov/docs/PRs/24585/coverage/ray_tracing)
- [`rdg`](https://mooseframework.inl.gov/docs/PRs/24585/coverage/rdg)
- [`reactor`](https://mooseframework.inl.gov/docs/PRs/24585/coverage/reactor)
- [`richards`](https://mooseframework.inl.gov/docs/PRs/24585/coverage/richards)
- [`scalar_transport`](https://mooseframework.inl.gov/docs/PRs/24585/coverage/scalar_transport)
- [`solid_properties`](https://mooseframework.inl.gov/docs/PRs/24585/coverage/solid_properties)
- [`stochastic_tools`](https://mooseframework.inl.gov/docs/PRs/24585/coverage/stochastic_tools)
- [`tensor_mechanics`](https://mooseframework.inl.gov/docs/PRs/24585/coverage/tensor_mechanics)
- [`thermal_hydraulics`](https://mooseframework.inl.gov/docs/PRs/24585/coverage/thermal_hydraulics)
- [`xfem`](https://mooseframework.inl.gov/docs/PRs/24585/coverage/xfem)

</details>



This comment will be updated on new commits.

2023-06-04 19:41 UTC, moosebuild commented
Job [Python 3.7](https://civet.inl.gov/job/1567419/) on b4d4d55 : invalidated by @GiudGiud

unrelated

2023-06-04 22:28 UTC, moosebuild commented
Job [Python 3.7](https://civet.inl.gov/job/1567419/) on b4d4d55 : invalidated by @GiudGiud

still unrelated

2023-06-05 14:53 UTC, joshuahansel requested changes

2023-06-05 14:53 UTC, joshuahansel commented on modules/fluid_properties/doc/content/source/auxkernels/StagnationPressureAux.md
> +Stagnation pressure is the pressure the fluid would obtain if brought to rest without loss of mechanical energy. It is
```suggestion
Stagnation pressure, or *total* pressure, is the pressure the fluid would obtain if brought to rest isentropically. It is
```

2023-06-05 14:53 UTC, joshuahansel commented on modules/fluid_properties/doc/content/source/auxkernels/StagnationTemperatureAux.md
> +Stagnation points include reservoirs and pools with no flow velocity.
```suggestion
Stagnation temperature is the temperature is the temperature the fluid would obtain if brought to rest isentropically.
Stagnation points include reservoirs and pools with no flow velocity.
```

2023-06-05 15:08 UTC, GiudGiud commented on modules/fluid_properties/doc/content/source/actions/AddFluidPropertiesAction.md
> +This action adds fluid properties from the `[FluidProperties]` block.
```suggestion
This action adds fluid properties from the [`[FluidProperties]`](syntax/FluidProperties/index.md) block.
```

2023-06-05 21:37 UTC, joshuahansel approved these changes

2023-06-07 14:47 UTC, merged