CSVDiff to SchemaDiff
idaholab/moose pull request #24633
Opened 2023-06-08 19:43 UTC by milljm

Use DeepDiff for diffing routines in the TestHarness.

Unable to push to original repository, creating a new PR.

Refs# 23522

2023-06-08 21:38 UTC, moosebuild commented
Job [Documentation](https://civet.inl.gov/job/1577730/) on d01d118 wanted to post the following:

View the site [here](https://mooseframework.inl.gov/docs/PRs/24633/site)

This comment will be updated on new commits.

2023-06-12 19:05 UTC, lindsayad requested changes
Maybe a person who does python more than I do should review this 😆

2023-06-12 19:05 UTC, lindsayad commented on test/tests/test_harness/csvdiff_tests
> +    requirement = 'CSVDiff shall compare only a specific column'
```suggestion
    requirement = 'The system shall be able to diff CSV files for only a specific column.'
```

2023-06-13 22:37 UTC, moosebuild commented
Job [Coverage](https://civet.inl.gov/job/1587226/) on 263b56d wanted to post the following:


## Framework coverage

<table>
  <thead>
    <tr>
      <th></th>
      <th>4278fb</th>
      <th colspan=4>#24633 263b56</th>
    </tr>
    <tr>
      <th></th>
      <th>Total</th>
      <th>Total</th>
      <th>+/-</th>
      <th>New</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><b>Rate</b></td>
      <td>85.40%</td>
      <td>85.40%</td>
      <td>+0.00%</td>
      <td>-</td>
    </tr>
    <tr>
      <td><b>Hits</b></td>
      <td>88878</td>
      <td>88883</td>
      <td>+5</td>
      <td>0</td>
    </tr>
    <tr>
      <td><b>Misses</b></td>
      <td>15197</td>
      <td>15192</td>
      <td>-5</td>
      <td>0</td>
    </tr>
  </tbody>
</table>

[Diff coverage report](https://mooseframework.inl.gov/docs/PRs/24633/coverage_diff/framework)

[Full coverage report](https://mooseframework.inl.gov/docs/PRs/24633/coverage/framework)


## Modules coverage

Coverage did not change

## Full coverage reports

<details>
<summary>Reports</summary>

- [`framework`](https://mooseframework.inl.gov/docs/PRs/24633/coverage/framework)
- [`chemical_reactions`](https://mooseframework.inl.gov/docs/PRs/24633/coverage/chemical_reactions)
- [`combined`](https://mooseframework.inl.gov/docs/PRs/24633/coverage/combined)
- [`contact`](https://mooseframework.inl.gov/docs/PRs/24633/coverage/contact)
- [`electromagnetics`](https://mooseframework.inl.gov/docs/PRs/24633/coverage/electromagnetics)
- [`external_petsc_solver`](https://mooseframework.inl.gov/docs/PRs/24633/coverage/external_petsc_solver)
- [`fluid_properties`](https://mooseframework.inl.gov/docs/PRs/24633/coverage/fluid_properties)
- [`fsi`](https://mooseframework.inl.gov/docs/PRs/24633/coverage/fsi)
- [`functional_expansion_tools`](https://mooseframework.inl.gov/docs/PRs/24633/coverage/functional_expansion_tools)
- [`geochemistry`](https://mooseframework.inl.gov/docs/PRs/24633/coverage/geochemistry)
- [`heat_conduction`](https://mooseframework.inl.gov/docs/PRs/24633/coverage/heat_conduction)
- [`level_set`](https://mooseframework.inl.gov/docs/PRs/24633/coverage/level_set)
- [`misc`](https://mooseframework.inl.gov/docs/PRs/24633/coverage/misc)
- [`navier_stokes`](https://mooseframework.inl.gov/docs/PRs/24633/coverage/navier_stokes)
- [`optimization`](https://mooseframework.inl.gov/docs/PRs/24633/coverage/optimization)
- [`peridynamics`](https://mooseframework.inl.gov/docs/PRs/24633/coverage/peridynamics)
- [`phase_field`](https://mooseframework.inl.gov/docs/PRs/24633/coverage/phase_field)
- [`porous_flow`](https://mooseframework.inl.gov/docs/PRs/24633/coverage/porous_flow)
- [`ray_tracing`](https://mooseframework.inl.gov/docs/PRs/24633/coverage/ray_tracing)
- [`rdg`](https://mooseframework.inl.gov/docs/PRs/24633/coverage/rdg)
- [`reactor`](https://mooseframework.inl.gov/docs/PRs/24633/coverage/reactor)
- [`richards`](https://mooseframework.inl.gov/docs/PRs/24633/coverage/richards)
- [`scalar_transport`](https://mooseframework.inl.gov/docs/PRs/24633/coverage/scalar_transport)
- [`solid_properties`](https://mooseframework.inl.gov/docs/PRs/24633/coverage/solid_properties)
- [`stochastic_tools`](https://mooseframework.inl.gov/docs/PRs/24633/coverage/stochastic_tools)
- [`tensor_mechanics`](https://mooseframework.inl.gov/docs/PRs/24633/coverage/tensor_mechanics)
- [`thermal_hydraulics`](https://mooseframework.inl.gov/docs/PRs/24633/coverage/thermal_hydraulics)
- [`xfem`](https://mooseframework.inl.gov/docs/PRs/24633/coverage/xfem)

</details>



This comment will be updated on new commits.

2023-06-19 14:37 UTC, permcody approved these changes

2023-06-19 15:46 UTC, lindsayad approved these changes

2023-06-19 16:20 UTC, merged

2023-06-27 16:10 UTC, dschwen commented
We don't have any tests that actually make sure that a tester that is meant to fail will fail, do we?

2023-06-27 16:12 UTC, loganharbour commented
> We don't have any tests that actually make sure that a tester that is meant to fail will fail, do we?

Nope. But we will now.