Fix some timeouts/crashes on json testing
idaholab/moose pull request #24692
Opened 2023-06-14 19:31 UTC by GiudGiud

refs #7855 (issue introducing use of json for docs)

2023-06-14 19:32 UTC, GiudGiud commented
just a bunch of prereq. The test does a syntax dump, and if the names are the same that s not great. 

alternate fixes:
- stop parallel scheduling on the entire outputs folder
- pass a name to rename the dump, though not sure what yet

2023-06-14 21:37 UTC, moosebuild commented
Job [Coverage](https://civet.inl.gov/job/1589790/) on eef7f25 wanted to post the following:


## Framework coverage

<table>
  <thead>
    <tr>
      <th></th>
      <th>4278fb</th>
      <th colspan=4>#24692 eef7f2</th>
    </tr>
    <tr>
      <th></th>
      <th>Total</th>
      <th>Total</th>
      <th>+/-</th>
      <th>New</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><b>Rate</b></td>
      <td>85.40%</td>
      <td>85.40%</td>
      <td>+0.00%</td>
      <td>-</td>
    </tr>
    <tr>
      <td><b>Hits</b></td>
      <td>88878</td>
      <td>88882</td>
      <td>+4</td>
      <td>0</td>
    </tr>
    <tr>
      <td><b>Misses</b></td>
      <td>15197</td>
      <td>15193</td>
      <td>-4</td>
      <td>0</td>
    </tr>
  </tbody>
</table>

[Diff coverage report](https://mooseframework.inl.gov/docs/PRs/24692/coverage_diff/framework)

[Full coverage report](https://mooseframework.inl.gov/docs/PRs/24692/coverage/framework)


## Modules coverage

Coverage did not change

## Full coverage reports

<details>
<summary>Reports</summary>

- [`framework`](https://mooseframework.inl.gov/docs/PRs/24692/coverage/framework)
- [`chemical_reactions`](https://mooseframework.inl.gov/docs/PRs/24692/coverage/chemical_reactions)
- [`combined`](https://mooseframework.inl.gov/docs/PRs/24692/coverage/combined)
- [`contact`](https://mooseframework.inl.gov/docs/PRs/24692/coverage/contact)
- [`electromagnetics`](https://mooseframework.inl.gov/docs/PRs/24692/coverage/electromagnetics)
- [`external_petsc_solver`](https://mooseframework.inl.gov/docs/PRs/24692/coverage/external_petsc_solver)
- [`fluid_properties`](https://mooseframework.inl.gov/docs/PRs/24692/coverage/fluid_properties)
- [`fsi`](https://mooseframework.inl.gov/docs/PRs/24692/coverage/fsi)
- [`functional_expansion_tools`](https://mooseframework.inl.gov/docs/PRs/24692/coverage/functional_expansion_tools)
- [`geochemistry`](https://mooseframework.inl.gov/docs/PRs/24692/coverage/geochemistry)
- [`heat_conduction`](https://mooseframework.inl.gov/docs/PRs/24692/coverage/heat_conduction)
- [`level_set`](https://mooseframework.inl.gov/docs/PRs/24692/coverage/level_set)
- [`misc`](https://mooseframework.inl.gov/docs/PRs/24692/coverage/misc)
- [`navier_stokes`](https://mooseframework.inl.gov/docs/PRs/24692/coverage/navier_stokes)
- [`optimization`](https://mooseframework.inl.gov/docs/PRs/24692/coverage/optimization)
- [`peridynamics`](https://mooseframework.inl.gov/docs/PRs/24692/coverage/peridynamics)
- [`phase_field`](https://mooseframework.inl.gov/docs/PRs/24692/coverage/phase_field)
- [`porous_flow`](https://mooseframework.inl.gov/docs/PRs/24692/coverage/porous_flow)
- [`ray_tracing`](https://mooseframework.inl.gov/docs/PRs/24692/coverage/ray_tracing)
- [`rdg`](https://mooseframework.inl.gov/docs/PRs/24692/coverage/rdg)
- [`reactor`](https://mooseframework.inl.gov/docs/PRs/24692/coverage/reactor)
- [`richards`](https://mooseframework.inl.gov/docs/PRs/24692/coverage/richards)
- [`scalar_transport`](https://mooseframework.inl.gov/docs/PRs/24692/coverage/scalar_transport)
- [`solid_properties`](https://mooseframework.inl.gov/docs/PRs/24692/coverage/solid_properties)
- [`stochastic_tools`](https://mooseframework.inl.gov/docs/PRs/24692/coverage/stochastic_tools)
- [`tensor_mechanics`](https://mooseframework.inl.gov/docs/PRs/24692/coverage/tensor_mechanics)
- [`thermal_hydraulics`](https://mooseframework.inl.gov/docs/PRs/24692/coverage/thermal_hydraulics)
- [`xfem`](https://mooseframework.inl.gov/docs/PRs/24692/coverage/xfem)

</details>



This comment will be updated on new commits.

2023-06-14 21:56 UTC, moosebuild commented
Job [Documentation](https://civet.inl.gov/job/1589772/) on eef7f25 wanted to post the following:

View the site [here](https://mooseframework.inl.gov/docs/PRs/24692/site)

This comment will be updated on new commits.

2023-06-14 22:37 UTC, cticenhour requested changes
I'm kinda OK with using the prereqs param to address this, though perhaps making sure they don't generate output with the same name is better if these tests don't *really* rely on each other. I did notice a couple things I wanted to fix up re: SQA while here though.

2023-06-14 22:37 UTC, cticenhour commented on test/tests/outputs/format/tests
>      requirement = 'If a postprocessor utilizes the "outputs" parameter, but postprocessor output is disabled for the console object, the system shall warn the user.'
I know this isn't part of this PR, but can we fix this while here? 
```suggestion
    requirement = 'The system shall warn the user if a postprocessor utilizes the "outputs" parameter but postprocessor output is disabled for the console object.'
```

2023-06-14 22:40 UTC, cticenhour reviewed
A few more. Thanks for allowing these to ride along with this PR.

2023-06-14 22:40 UTC, cticenhour commented on test/tests/outputs/format/tests
>      requirement = 'If the Tecplot API is available, the system shall support Tecplot output given in Tecplot binary format.'
```suggestion
    requirement = 'The system shall support Tecplot output given in Tecplot binary format if the Tecplot API is available.'
```

2023-06-14 22:40 UTC, cticenhour commented on test/tests/outputs/format/tests
>      requirement = 'If the Tecplot API is not available, the system shall support Tecplot output given in ASCII format.'
```suggestion
    requirement = 'The system shall support Tecplot output given in ASCII format if the Tecplot API is not available.'
```

2023-06-14 22:40 UTC, cticenhour commented on test/tests/outputs/format/tests
>      requirement = 'Solution history output shall work'
```suggestion
    requirement = 'The system shall support solution history output.'
```

2023-06-15 00:17 UTC, cticenhour approved these changes

2023-06-15 01:53 UTC, merged