Create Element and Nodal Reporters
idaholab/moose pull request #24707
Opened 2023-06-15 18:41 UTC by maxnezdyur

closes #24678 
## Reason

Will allow for easy reporter management when the reporter depends on a set of elements or nodes. Will be specifically used in the optimization module.
## Design

Derive off of Element/Nodal UserObjects and Reporter

## Impact

Increases Reporter usability when needing a reporter that only works on a block, boundary, etc.

2023-06-15 21:15 UTC, moosebuild commented
Job [Documentation](https://civet.inl.gov/job/1593516/) on 6248ac1 wanted to post the following:

View the site [here](https://mooseframework.inl.gov/docs/PRs/24707/site)

This comment will be updated on new commits.

2023-06-15 21:23 UTC, maxnezdyur commented
I don't think reporters will work with threading? @zachmprince

2023-06-19 20:05 UTC, zachmprince requested changes

2023-06-19 20:05 UTC, zachmprince commented on test/tests/reporters/ele_nodal_reporters/element_reporter/tests
Let's remove the `ele_nodal_reporters` folder and just have `element_reporter` and `nodal_reporter`.

2023-06-19 20:10 UTC, maxnezdyur commented on framework/src/reporters/CoupledVarStatsElementReporter.C
> +registerMooseObject("MooseApp", CoupledVarStatsElementReporter);
No apologies, don't like the name either. So `ElementVariableStatistics` and the base class `ElementStatistics`?

2023-06-20 20:18 UTC, maxnezdyur commented
I see the problem. In 
```
void
FEProblemBase::addUserObject(const std::string & user_object_name,
                             const std::string & name,
                             InputParameters & parameters)
{
  // Add the _subproblem and _sys parameters depending on use_displaced_mesh
  addObjectParamsHelper(parameters, name);

  UserObject * primary = nullptr;
  for (THREAD_ID tid = 0; tid < libMesh::n_threads(); ++tid)
  {
    // Create the UserObject
    std::shared_ptr<UserObject> user_object =
        _factory.create<UserObject>(user_object_name, name, parameters, tid);
    if (tid == 0)
      primary = user_object.get();
    else
      user_object->setPrimaryThreadCopy(primary);

    // TODO: delete this line after apps have been updated to not call getUserObjects
    _all_user_objects.addObject(user_object, tid);

    theWarehouse().add(user_object);

    // Attempt to create all the possible UserObject types
    auto euo = std::dynamic_pointer_cast<ElementUserObject>(user_object);
    auto suo = std::dynamic_pointer_cast<SideUserObject>(user_object);
    auto isuo = std::dynamic_pointer_cast<InternalSideUserObject>(user_object);
    auto iuob = std::dynamic_pointer_cast<InterfaceUserObjectBase>(user_object);
    auto nuo = std::dynamic_pointer_cast<NodalUserObject>(user_object);
    auto duo = std::dynamic_pointer_cast<DomainUserObject>(user_object);
    auto guo = std::dynamic_pointer_cast<GeneralUserObject>(user_object);
    auto tguo = std::dynamic_pointer_cast<ThreadedGeneralUserObject>(user_object);
    auto muo = std::dynamic_pointer_cast<MortarUserObject>(user_object);

    // Account for displaced mesh use
    if (_displaced_problem && parameters.get<bool>("use_displaced_mesh"))
    {
      if (euo || nuo || duo)
        _reinit_displaced_elem = true;
      else if (suo)
        // shouldn't we add isuo
        _reinit_displaced_face = true;
      else if (iuob)
        _reinit_displaced_neighbor = true;
    }

    if ((guo && !tguo) || muo)
      break;
  }
} 
```
 we break when for general user objects which is why general reporter doesn't have this problem. Not sure about the best fix but I could add a member to `UserObject` that defaults to true, but can be made to be false for reporters and use that to break out.

2023-06-20 23:12 UTC, maxnezdyur commented
From my initial tests, I think I see two ways to do this.
1) Having only the "root" thread declare the reporter but still added the UO on the other threads and then in `threadJoin` making sure we save the data correctly.
2) Somehow having these reporterUO not go into the threadedUO loops and just have one reporterUO that loops over all the elements/nodes. 

The problem with my initial solution (break out of the for loop for the ele/nodalReporters) was that the UO was only added for one "thread" and then the reporter would only get 1/n data, even with threadJoin overrided to correctly add to the reporter. Will try to look at the least invasive way to do this. 
Is there some way to force a Element/NodalUO to not be threaded?

2023-06-26 18:06 UTC, maxnezdyur commented on framework/src/outputs/JSONOutput.C
We need to create multiple objects for the threading capabilities but only the first object contains the correct data. Not sure how to error check  multiple reporters with same name but not of the threaded variety.

2023-06-26 18:08 UTC, maxnezdyur commented on framework/include/reporters/Reporter.h
Use the UnusedValue to provide provide a reference for the threaded objects that will not get declared. Not sure if there is a better way to do this. This is very similar to how vectorpostprocessors work in declareValue.

2023-06-26 20:43 UTC, moosebuild commented
Job [Coverage](https://civet.inl.gov/job/1618266/) on ff58872 wanted to post the following:


## Framework coverage

<table>
  <thead>
    <tr>
      <th></th>
      <th>080096</th>
      <th colspan=4>#24707 ff5887</th>
    </tr>
    <tr>
      <th></th>
      <th>Total</th>
      <th>Total</th>
      <th>+/-</th>
      <th>New</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><b>Rate</b></td>
      <td>85.58%</td>
      <td>85.60%</td>
      <td>+0.02%</td>
      <td>100.00%</td>
    </tr>
    <tr>
      <td><b>Hits</b></td>
      <td>89021</td>
      <td>89156</td>
      <td>+135</td>
      <td>133</td>
    </tr>
    <tr>
      <td><b>Misses</b></td>
      <td>14997</td>
      <td>14995</td>
      <td>-2</td>
      <td>0</td>
    </tr>
  </tbody>
</table>

[Diff coverage report](https://mooseframework.inl.gov/docs/PRs/24707/coverage_diff/framework)

[Full coverage report](https://mooseframework.inl.gov/docs/PRs/24707/coverage/framework)


## Modules coverage

Coverage did not change

## Full coverage reports

<details>
<summary>Reports</summary>

- [`framework`](https://mooseframework.inl.gov/docs/PRs/24707/coverage/framework)
- [`chemical_reactions`](https://mooseframework.inl.gov/docs/PRs/24707/coverage/chemical_reactions)
- [`combined`](https://mooseframework.inl.gov/docs/PRs/24707/coverage/combined)
- [`contact`](https://mooseframework.inl.gov/docs/PRs/24707/coverage/contact)
- [`electromagnetics`](https://mooseframework.inl.gov/docs/PRs/24707/coverage/electromagnetics)
- [`external_petsc_solver`](https://mooseframework.inl.gov/docs/PRs/24707/coverage/external_petsc_solver)
- [`fluid_properties`](https://mooseframework.inl.gov/docs/PRs/24707/coverage/fluid_properties)
- [`fsi`](https://mooseframework.inl.gov/docs/PRs/24707/coverage/fsi)
- [`functional_expansion_tools`](https://mooseframework.inl.gov/docs/PRs/24707/coverage/functional_expansion_tools)
- [`geochemistry`](https://mooseframework.inl.gov/docs/PRs/24707/coverage/geochemistry)
- [`heat_conduction`](https://mooseframework.inl.gov/docs/PRs/24707/coverage/heat_conduction)
- [`level_set`](https://mooseframework.inl.gov/docs/PRs/24707/coverage/level_set)
- [`misc`](https://mooseframework.inl.gov/docs/PRs/24707/coverage/misc)
- [`navier_stokes`](https://mooseframework.inl.gov/docs/PRs/24707/coverage/navier_stokes)
- [`optimization`](https://mooseframework.inl.gov/docs/PRs/24707/coverage/optimization)
- [`peridynamics`](https://mooseframework.inl.gov/docs/PRs/24707/coverage/peridynamics)
- [`phase_field`](https://mooseframework.inl.gov/docs/PRs/24707/coverage/phase_field)
- [`porous_flow`](https://mooseframework.inl.gov/docs/PRs/24707/coverage/porous_flow)
- [`ray_tracing`](https://mooseframework.inl.gov/docs/PRs/24707/coverage/ray_tracing)
- [`rdg`](https://mooseframework.inl.gov/docs/PRs/24707/coverage/rdg)
- [`reactor`](https://mooseframework.inl.gov/docs/PRs/24707/coverage/reactor)
- [`richards`](https://mooseframework.inl.gov/docs/PRs/24707/coverage/richards)
- [`scalar_transport`](https://mooseframework.inl.gov/docs/PRs/24707/coverage/scalar_transport)
- [`solid_properties`](https://mooseframework.inl.gov/docs/PRs/24707/coverage/solid_properties)
- [`stochastic_tools`](https://mooseframework.inl.gov/docs/PRs/24707/coverage/stochastic_tools)
- [`tensor_mechanics`](https://mooseframework.inl.gov/docs/PRs/24707/coverage/tensor_mechanics)
- [`thermal_hydraulics`](https://mooseframework.inl.gov/docs/PRs/24707/coverage/thermal_hydraulics)
- [`xfem`](https://mooseframework.inl.gov/docs/PRs/24707/coverage/xfem)

</details>



This comment will be updated on new commits.

2023-06-27 18:45 UTC, zachmprince requested changes
Great work!! I'm impressed you figured out the threading issue. Just a few minor requests, then I'll merge.

2023-06-27 18:45 UTC, zachmprince commented on framework/include/reporters/ElementVariableStatistics.h
> +  virtual Real computeValue();
```suggestion
  virtual Real computeValue() override;

    /// The coupled variable used.
  const VariableValue & _v;
```

2023-06-27 18:45 UTC, zachmprince commented on framework/include/reporters/NodalVariableStatistics.h
> +  virtual Real computeValue();
```suggestion
  virtual Real computeValue() override;

    /// The coupled variable used.
  const VariableValue & _v;
```

2023-06-27 18:45 UTC, zachmprince commented on framework/src/reporters/ElementStatistics.C
> +ElementStatistics::initialize()
I'm surprised formatting didn't pick this up
```suggestion
{
}

void
ElementStatistics::initialize()
```

2023-06-27 18:45 UTC, zachmprince commented on framework/src/reporters/ElementVariableStatistics.C
> +ElementVariableStatistics::computeValue()
```suggestion
{
}

Real
ElementVariableStatistics::computeValue()
```

2023-06-27 18:45 UTC, zachmprince commented on framework/src/reporters/NodalStatistics.C
> +NodalStatistics::initialize()
```suggestion
{
}

void
NodalStatistics::initialize()
```

2023-06-27 18:45 UTC, zachmprince commented on framework/src/reporters/NodalVariableStatistics.C
> +NodalVariableStatistics::computeValue()
```suggestion
}

Real
NodalVariableStatistics::computeValue()
```

2023-06-27 18:45 UTC, zachmprince commented on test/tests/reporters/element_reporter/elem_stats.i
> +[]
```suggestion
[Mesh]
  [gmg]
    type = GeneratedMeshGenerator
    dim = 2
    xmax = 2
    ymax = 2
    nx = 10
    ny = 10
  []
[]
```

2023-06-27 18:45 UTC, zachmprince commented on test/tests/reporters/nodal_reporter/nodal_stats.i
> +[]
```suggestion
[Mesh]
  [gmg]
    type = GeneratedMeshGenerator
    dim = 2
    xmax = 2
    ymax = 2
    nx = 10
    ny = 10
  []
[]
```

2023-06-27 18:58 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/1622889/) on aad4ad0 wanted to post the following:

Your code requires style changes.  

A patch was auto generated and copied [here](https://mooseframework.inl.gov/docs/PRs/24707/clang_format/style.patch)  
You can directly apply the patch by running, in the top level of your repository:

`curl -s https://mooseframework.inl.gov/docs/PRs/24707/clang_format/style.patch | git apply -v`  

Alternatively, with your repository up to date and in the top level of your repository:

`git clang-format d2489239f0f53384d7fa76101f156031e46e7c5a`

2023-06-28 20:55 UTC, zachmprince approved these changes

2023-06-28 20:56 UTC, merged