Fix contact test doing csv diff with node ids
idaholab/moose pull request #24837
Opened 2023-06-27 18:48 UTC by lindsayad

Don't renumber for both replicated and distributed meshes so that results are reproducible

Refs #24829 

@dewenyushu @loganharbour @milljm

2023-06-27 19:15 UTC, loganharbour approved these changes

2023-06-27 19:28 UTC, recuero approved these changes, later dismissed

2023-06-27 20:04 UTC, loganharbour commented
Will merge despite failures. @GiudGiud will handle the UO failures in another PR

2023-06-27 20:16 UTC, loganharbour requested changes
Diffs in serial

2023-06-27 20:33 UTC, moosebuild commented
Job [Documentation](https://civet.inl.gov/job/1622820/) on c2277ad wanted to post the following:

View the site [here](https://mooseframework.inl.gov/docs/PRs/24837/site)

This comment will be updated on new commits.

2023-06-27 21:57 UTC, moosebuild commented on large_media
> +Subproject commit bd07d54c44b9ee8ff381707e1117e365d8079096
**Caution!** This contains a submodule update

2023-06-27 21:57 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/1623490/) on 4b478b6 wanted to post the following:

A change of the following file(s) triggered this check:

  libmesh

The following file(s) are unchanged:

  conda/mpich/conda_build_config.yaml
  conda/libmesh/meta.yaml

The libmesh submodule or configuration was changed but the conda build config was not

2023-06-28 04:32 UTC, loganharbour approved these changes

2023-06-28 04:33 UTC, loganharbour commented
Failures are unrelated.

2023-06-28 04:33 UTC, merged