Fix globally valid parameters
idaholab/moose pull request #24839
Opened 2023-06-27 19:35 UTC by dschwen

Closes #24838

2023-06-27 22:35 UTC, moosebuild commented
Job [Documentation](https://civet.inl.gov/job/1623278/) on 89882ca wanted to post the following:

View the site [here](https://mooseframework.inl.gov/docs/PRs/24839/site)

This comment will be updated on new commits.

2023-06-27 22:50 UTC, moosebuild commented
Job [Coverage](https://civet.inl.gov/job/1623296/) on 89882ca wanted to post the following:


## Framework coverage

<table>
  <thead>
    <tr>
      <th></th>
      <th>d24892</th>
      <th colspan=4>#24839 89882c</th>
    </tr>
    <tr>
      <th></th>
      <th>Total</th>
      <th>Total</th>
      <th>+/-</th>
      <th>New</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><b>Rate</b></td>
      <td>85.60%</td>
      <td>85.59%</td>
      <td>-0.00%</td>
      <td>100.00%</td>
    </tr>
    <tr>
      <td><b>Hits</b></td>
      <td>89097</td>
      <td>89096</td>
      <td>-1</td>
      <td>9</td>
    </tr>
    <tr>
      <td><b>Misses</b></td>
      <td>14994</td>
      <td>14998</td>
      <td>+4</td>
      <td>0</td>
    </tr>
  </tbody>
</table>

[Diff coverage report](https://mooseframework.inl.gov/docs/PRs/24839/coverage_diff/framework)

[Full coverage report](https://mooseframework.inl.gov/docs/PRs/24839/coverage/framework)


## Modules coverage

Coverage did not change

## Full coverage reports

<details>
<summary>Reports</summary>

- [`framework`](https://mooseframework.inl.gov/docs/PRs/24839/coverage/framework)
- [`chemical_reactions`](https://mooseframework.inl.gov/docs/PRs/24839/coverage/chemical_reactions)
- [`combined`](https://mooseframework.inl.gov/docs/PRs/24839/coverage/combined)
- [`contact`](https://mooseframework.inl.gov/docs/PRs/24839/coverage/contact)
- [`electromagnetics`](https://mooseframework.inl.gov/docs/PRs/24839/coverage/electromagnetics)
- [`external_petsc_solver`](https://mooseframework.inl.gov/docs/PRs/24839/coverage/external_petsc_solver)
- [`fluid_properties`](https://mooseframework.inl.gov/docs/PRs/24839/coverage/fluid_properties)
- [`fsi`](https://mooseframework.inl.gov/docs/PRs/24839/coverage/fsi)
- [`functional_expansion_tools`](https://mooseframework.inl.gov/docs/PRs/24839/coverage/functional_expansion_tools)
- [`geochemistry`](https://mooseframework.inl.gov/docs/PRs/24839/coverage/geochemistry)
- [`heat_conduction`](https://mooseframework.inl.gov/docs/PRs/24839/coverage/heat_conduction)
- [`level_set`](https://mooseframework.inl.gov/docs/PRs/24839/coverage/level_set)
- [`misc`](https://mooseframework.inl.gov/docs/PRs/24839/coverage/misc)
- [`navier_stokes`](https://mooseframework.inl.gov/docs/PRs/24839/coverage/navier_stokes)
- [`optimization`](https://mooseframework.inl.gov/docs/PRs/24839/coverage/optimization)
- [`peridynamics`](https://mooseframework.inl.gov/docs/PRs/24839/coverage/peridynamics)
- [`phase_field`](https://mooseframework.inl.gov/docs/PRs/24839/coverage/phase_field)
- [`porous_flow`](https://mooseframework.inl.gov/docs/PRs/24839/coverage/porous_flow)
- [`ray_tracing`](https://mooseframework.inl.gov/docs/PRs/24839/coverage/ray_tracing)
- [`rdg`](https://mooseframework.inl.gov/docs/PRs/24839/coverage/rdg)
- [`reactor`](https://mooseframework.inl.gov/docs/PRs/24839/coverage/reactor)
- [`richards`](https://mooseframework.inl.gov/docs/PRs/24839/coverage/richards)
- [`scalar_transport`](https://mooseframework.inl.gov/docs/PRs/24839/coverage/scalar_transport)
- [`solid_properties`](https://mooseframework.inl.gov/docs/PRs/24839/coverage/solid_properties)
- [`stochastic_tools`](https://mooseframework.inl.gov/docs/PRs/24839/coverage/stochastic_tools)
- [`tensor_mechanics`](https://mooseframework.inl.gov/docs/PRs/24839/coverage/tensor_mechanics)
- [`thermal_hydraulics`](https://mooseframework.inl.gov/docs/PRs/24839/coverage/thermal_hydraulics)
- [`xfem`](https://mooseframework.inl.gov/docs/PRs/24839/coverage/xfem)

</details>



This comment will be updated on new commits.

2023-06-27 22:59 UTC, moosebuild commented
Job [Python 3.10 (Apptainer)](https://civet.inl.gov/job/1623262/) on 89882ca : invalidated by @lindsayad

2023-06-27 23:02 UTC, lindsayad reviewed
This looks fine to me but how does it fix the referenced issue? Is this something we can test?

2023-06-28 04:22 UTC, GiudGiud requested changes

2023-06-28 04:22 UTC, GiudGiud commented on framework/src/parser/Parser.C
> +   * create white or black lists of active/inactive sub-blocks.
```suggestion
   * create lists of active/inactive sub-blocks.
```

2023-06-28 16:05 UTC, dschwen commented
> This looks fine to me but how does it fix the referenced issue? Is this something we can test?

It fixes it by not advertising `control_tags` as valid in our syntax dump in locations where it will lead to a parse error. Not sure how to test this.

2023-06-28 16:27 UTC, GiudGiud approved these changes

2023-06-28 16:58 UTC, lindsayad approved these changes

2023-06-28 19:04 UTC, merged