June newsletter
idaholab/moose pull request #24866
Opened 2023-06-29 18:10 UTC by GiudGiud

refs #11447

@idaholab/moose-team need more content

2023-07-06 23:52 UTC, moosebuild commented
Job [Documentation](https://civet.inl.gov/job/1637534/) on 56ea373 wanted to post the following:

View the site [here](https://mooseframework.inl.gov/docs/PRs/24866/site)

This comment will be updated on new commits.

2023-07-07 12:21 UTC, joshuahansel requested changes

2023-07-07 12:21 UTC, joshuahansel commented on modules/doc/content/newsletter/2023/2023_06.md
> +- FillBetweenSidesetsGenerator and SideSetsFromPointsGenerator are now
Make the classes in this list into links (or at least typewriter font).

2023-07-07 12:21 UTC, joshuahansel commented on modules/doc/content/newsletter/2023/2023_06.md
>  # MOOSE Newsletter (June 2023)
Need the link to this page!

2023-07-07 17:03 UTC, GiudGiud commented on modules/doc/content/newsletter/2023/2023_06.md
>  # MOOSE Newsletter (June 2023)
good catch

2023-07-07 17:03 UTC, GiudGiud commented
Roy addressed everything

2023-07-07 20:55 UTC, joshuahansel approved these changes

2023-07-07 21:10 UTC, merged