Added extrapolation option to TimeSequenceStepperBase
idaholab/moose pull request #24873
Opened 2023-06-29 22:41 UTC by joshuahansel

Closes #24868

2023-06-30 00:27 UTC, moosebuild commented
Job [Coverage](https://civet.inl.gov/job/1629000/) on c5dcc33 wanted to post the following:


## Framework coverage

<table>
  <thead>
    <tr>
      <th></th>
      <th>41b2a0</th>
      <th colspan=4>#24873 c5dcc3</th>
    </tr>
    <tr>
      <th></th>
      <th>Total</th>
      <th>Total</th>
      <th>+/-</th>
      <th>New</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><b>Rate</b></td>
      <td>85.55%</td>
      <td>85.56%</td>
      <td>+0.01%</td>
      <td>100.00%</td>
    </tr>
    <tr>
      <td><b>Hits</b></td>
      <td>89150</td>
      <td>89164</td>
      <td>+14</td>
      <td>10</td>
    </tr>
    <tr>
      <td><b>Misses</b></td>
      <td>15054</td>
      <td>15049</td>
      <td>-5</td>
      <td>0</td>
    </tr>
  </tbody>
</table>

[Diff coverage report](https://mooseframework.inl.gov/docs/PRs/24873/coverage_diff/framework)

[Full coverage report](https://mooseframework.inl.gov/docs/PRs/24873/coverage/framework)


## Modules coverage

Coverage did not change

## Full coverage reports

<details>
<summary>Reports</summary>

- [`framework`](https://mooseframework.inl.gov/docs/PRs/24873/coverage/framework)
- [`chemical_reactions`](https://mooseframework.inl.gov/docs/PRs/24873/coverage/chemical_reactions)
- [`combined`](https://mooseframework.inl.gov/docs/PRs/24873/coverage/combined)
- [`contact`](https://mooseframework.inl.gov/docs/PRs/24873/coverage/contact)
- [`electromagnetics`](https://mooseframework.inl.gov/docs/PRs/24873/coverage/electromagnetics)
- [`external_petsc_solver`](https://mooseframework.inl.gov/docs/PRs/24873/coverage/external_petsc_solver)
- [`fluid_properties`](https://mooseframework.inl.gov/docs/PRs/24873/coverage/fluid_properties)
- [`fsi`](https://mooseframework.inl.gov/docs/PRs/24873/coverage/fsi)
- [`functional_expansion_tools`](https://mooseframework.inl.gov/docs/PRs/24873/coverage/functional_expansion_tools)
- [`geochemistry`](https://mooseframework.inl.gov/docs/PRs/24873/coverage/geochemistry)
- [`heat_conduction`](https://mooseframework.inl.gov/docs/PRs/24873/coverage/heat_conduction)
- [`level_set`](https://mooseframework.inl.gov/docs/PRs/24873/coverage/level_set)
- [`misc`](https://mooseframework.inl.gov/docs/PRs/24873/coverage/misc)
- [`navier_stokes`](https://mooseframework.inl.gov/docs/PRs/24873/coverage/navier_stokes)
- [`optimization`](https://mooseframework.inl.gov/docs/PRs/24873/coverage/optimization)
- [`peridynamics`](https://mooseframework.inl.gov/docs/PRs/24873/coverage/peridynamics)
- [`phase_field`](https://mooseframework.inl.gov/docs/PRs/24873/coverage/phase_field)
- [`porous_flow`](https://mooseframework.inl.gov/docs/PRs/24873/coverage/porous_flow)
- [`ray_tracing`](https://mooseframework.inl.gov/docs/PRs/24873/coverage/ray_tracing)
- [`rdg`](https://mooseframework.inl.gov/docs/PRs/24873/coverage/rdg)
- [`reactor`](https://mooseframework.inl.gov/docs/PRs/24873/coverage/reactor)
- [`richards`](https://mooseframework.inl.gov/docs/PRs/24873/coverage/richards)
- [`scalar_transport`](https://mooseframework.inl.gov/docs/PRs/24873/coverage/scalar_transport)
- [`solid_properties`](https://mooseframework.inl.gov/docs/PRs/24873/coverage/solid_properties)
- [`stochastic_tools`](https://mooseframework.inl.gov/docs/PRs/24873/coverage/stochastic_tools)
- [`tensor_mechanics`](https://mooseframework.inl.gov/docs/PRs/24873/coverage/tensor_mechanics)
- [`thermal_hydraulics`](https://mooseframework.inl.gov/docs/PRs/24873/coverage/thermal_hydraulics)
- [`xfem`](https://mooseframework.inl.gov/docs/PRs/24873/coverage/xfem)

</details>



This comment will be updated on new commits.

2023-06-30 01:11 UTC, moosebuild commented
Job [Documentation](https://civet.inl.gov/job/1628959/) on c5dcc33 wanted to post the following:

View the site [here](https://mooseframework.inl.gov/docs/PRs/24873/site)

This comment will be updated on new commits.

2023-07-03 13:58 UTC, GiudGiud requested changes

2023-07-03 13:58 UTC, GiudGiud commented on framework/doc/content/source/timesteppers/CSVTimeSequenceStepper.md
> +This time stepper derives from [TimeSequenceStepperBase.md] and provides the
I think being more explicit is better, let's point to what it inherits from that class, as users should not need to understand OOP to use MOOSE

2023-07-03 13:58 UTC, GiudGiud commented on framework/doc/content/source/timesteppers/CSVTimeSequenceStepper.md
```suggestion
If the solve fails to converge during a time step, the behavior of the
`CSVTimeSequenceStepper` is inherited from the [TimeSequenceStepperBase.md].
```

2023-07-03 13:58 UTC, GiudGiud commented on modules/doc/content/newsletter/2023/2023_06.md
> +### New option for time-stepping past the last time in time sequence steppers
let's move this to July

2023-07-03 13:58 UTC, GiudGiud commented on test/tests/time_steppers/timesequence_stepper/tests
>        detail = 'when reading the sequence from a comma-separated input file.'
```suggestion
      detail = 'when reading the sequence from a comma-separated input file, and'
```

2023-07-03 13:58 UTC, GiudGiud commented on framework/doc/content/source/timesteppers/TimeSequenceStepperBase.md
> +## Failed solves
would move this paragraph first, tends to happen more than final time step issues

2023-07-04 02:01 UTC, GiudGiud commented on framework/doc/content/source/timesteppers/ExodusTimeSequenceStepper.md
> -
same here

2023-07-04 02:02 UTC, GiudGiud commented on framework/doc/content/source/timesteppers/TimeSequenceStepper.md
> +[!param](/Executioner/TimeSteppers/TimeSequenceStepper/time_sequence).
same here

2023-07-05 15:21 UTC, GiudGiud commented
so wrt to your slack message, should this go forward?

2023-07-05 16:22 UTC, joshuahansel commented
> so wrt to your slack message, should this go forward?

It's true that I'll no longer be needing this change for any immediate work because I won't need to use this time stepper. However, I think the change could potentially still be beneficial. I don't know if anyone will ever use it, but I *think* it's an improvement.

2023-07-05 19:16 UTC, GiudGiud approved these changes

2023-07-05 21:15 UTC, merged