Another doco PR
idaholab/moose pull request #24875
Opened 2023-06-30 00:18 UTC by GiudGiud

2023-06-30 02:02 UTC, moosebuild commented
Job [Documentation](https://civet.inl.gov/job/1629456/) on 5c083e1 wanted to post the following:

View the site [here](https://mooseframework.inl.gov/docs/PRs/24875/site)

This comment will be updated on new commits.

2023-06-30 02:23 UTC, moosebuild commented
Job [Coverage](https://civet.inl.gov/job/1629497/) on 5c083e1 wanted to post the following:


## Framework coverage

<table>
  <thead>
    <tr>
      <th></th>
      <th>41b2a0</th>
      <th colspan=4>#24875 5c083e</th>
    </tr>
    <tr>
      <th></th>
      <th>Total</th>
      <th>Total</th>
      <th>+/-</th>
      <th>New</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><b>Rate</b></td>
      <td>85.55%</td>
      <td>85.56%</td>
      <td>+0.00%</td>
      <td>87.18%</td>
    </tr>
    <tr>
      <td><b>Hits</b></td>
      <td>89150</td>
      <td>89155</td>
      <td>+5</td>
      <td>34</td>
    </tr>
    <tr>
      <td><b>Misses</b></td>
      <td>15054</td>
      <td>15050</td>
      <td>-4</td>
      <td>5</td>
    </tr>
  </tbody>
</table>

[Diff coverage report](https://mooseframework.inl.gov/docs/PRs/24875/coverage_diff/framework)

[Full coverage report](https://mooseframework.inl.gov/docs/PRs/24875/coverage/framework)


## Modules coverage

### Solid properties

<table>
  <thead>
    <tr>
      <th></th>
      <th>41b2a0</th>
      <th colspan=4>#24875 5c083e</th>
    </tr>
    <tr>
      <th></th>
      <th>Total</th>
      <th>Total</th>
      <th>+/-</th>
      <th>New</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><b>Rate</b></td>
      <td>83.87%</td>
      <td>83.87%</td>
      <td>-</td>
      <td>90.55%</td>
    </tr>
    <tr>
      <td><b>Hits</b></td>
      <td>286</td>
      <td>286</td>
      <td>-</td>
      <td>182</td>
    </tr>
    <tr>
      <td><b>Misses</b></td>
      <td>55</td>
      <td>55</td>
      <td>-</td>
      <td>19</td>
    </tr>
  </tbody>
</table>

[Diff coverage report](https://mooseframework.inl.gov/docs/PRs/24875/coverage_diff/solid_properties)

[Full coverage report](https://mooseframework.inl.gov/docs/PRs/24875/coverage/solid_properties)

## Full coverage reports

<details>
<summary>Reports</summary>

- [`framework`](https://mooseframework.inl.gov/docs/PRs/24875/coverage/framework)
- [`chemical_reactions`](https://mooseframework.inl.gov/docs/PRs/24875/coverage/chemical_reactions)
- [`combined`](https://mooseframework.inl.gov/docs/PRs/24875/coverage/combined)
- [`contact`](https://mooseframework.inl.gov/docs/PRs/24875/coverage/contact)
- [`electromagnetics`](https://mooseframework.inl.gov/docs/PRs/24875/coverage/electromagnetics)
- [`external_petsc_solver`](https://mooseframework.inl.gov/docs/PRs/24875/coverage/external_petsc_solver)
- [`fluid_properties`](https://mooseframework.inl.gov/docs/PRs/24875/coverage/fluid_properties)
- [`fsi`](https://mooseframework.inl.gov/docs/PRs/24875/coverage/fsi)
- [`functional_expansion_tools`](https://mooseframework.inl.gov/docs/PRs/24875/coverage/functional_expansion_tools)
- [`geochemistry`](https://mooseframework.inl.gov/docs/PRs/24875/coverage/geochemistry)
- [`heat_conduction`](https://mooseframework.inl.gov/docs/PRs/24875/coverage/heat_conduction)
- [`level_set`](https://mooseframework.inl.gov/docs/PRs/24875/coverage/level_set)
- [`misc`](https://mooseframework.inl.gov/docs/PRs/24875/coverage/misc)
- [`navier_stokes`](https://mooseframework.inl.gov/docs/PRs/24875/coverage/navier_stokes)
- [`optimization`](https://mooseframework.inl.gov/docs/PRs/24875/coverage/optimization)
- [`peridynamics`](https://mooseframework.inl.gov/docs/PRs/24875/coverage/peridynamics)
- [`phase_field`](https://mooseframework.inl.gov/docs/PRs/24875/coverage/phase_field)
- [`porous_flow`](https://mooseframework.inl.gov/docs/PRs/24875/coverage/porous_flow)
- [`ray_tracing`](https://mooseframework.inl.gov/docs/PRs/24875/coverage/ray_tracing)
- [`rdg`](https://mooseframework.inl.gov/docs/PRs/24875/coverage/rdg)
- [`reactor`](https://mooseframework.inl.gov/docs/PRs/24875/coverage/reactor)
- [`richards`](https://mooseframework.inl.gov/docs/PRs/24875/coverage/richards)
- [`scalar_transport`](https://mooseframework.inl.gov/docs/PRs/24875/coverage/scalar_transport)
- [`solid_properties`](https://mooseframework.inl.gov/docs/PRs/24875/coverage/solid_properties)
- [`stochastic_tools`](https://mooseframework.inl.gov/docs/PRs/24875/coverage/stochastic_tools)
- [`tensor_mechanics`](https://mooseframework.inl.gov/docs/PRs/24875/coverage/tensor_mechanics)
- [`thermal_hydraulics`](https://mooseframework.inl.gov/docs/PRs/24875/coverage/thermal_hydraulics)
- [`xfem`](https://mooseframework.inl.gov/docs/PRs/24875/coverage/xfem)

</details>

## Warnings

- `framework` new line coverage rate 87.18% is less than the suggested 90.0%



This comment will be updated on new commits.

2023-07-03 14:59 UTC, joshuahansel requested changes

2023-07-03 14:59 UTC, joshuahansel commented on framework/doc/content/source/functions/PiecewiseLinearFromVectorPostprocessor.md
> +The `PiecewiseLinearFromVectorPostprocessor` function performs linear interpolations between pairs of data generated by a vector post-processor object. The abscissa (`argument_column`) and the ordina
Use `!param` for these.

2023-07-03 14:59 UTC, joshuahansel commented on framework/doc/content/source/functions/PiecewiseLinearFromVectorPostprocessor.md
> +In this example, three `PiecewiseLinearFromVectorPostprocessor` are created and take data from three distinct
```suggestion
In this example, three `PiecewiseLinearFromVectorPostprocessor`s are created and take data from three distinct
```

2023-07-03 14:59 UTC, joshuahansel commented on framework/doc/content/source/vectorpostprocessors/VectorMemoryUsage.md
> +Due to differences in the data collection method, the memory consumption different may be slightly different from
```suggestion
Due to differences in the data collection method, the memory consumption may be slightly different from
```

2023-07-04 12:44 UTC, moosebuild commented
Job [No optional](https://civet.inl.gov/job/1632929/) on 54c581e : invalidated by @GiudGiud

unrelated

2023-07-05 13:43 UTC, joshuahansel approved these changes

2023-07-05 13:53 UTC, merged

2023-07-05 13:53 UTC, GiudGiud commented
Thanks for the review!