Support flow reversal for WCNSFVEnergyFluxBC boundary (#24936)
idaholab/moose pull request #24939
Opened 2023-07-10 21:58 UTC by snschune

closes #24936

## Reason

`WCNSFVEnergyFluxBC` can support outflow conditions with small changes. This PR
adds that capability.

## Design

Based on velocity/mass flow rate, use either the provided temperature postprocessor or the 
internal temperature to compute energy flow over boundary.

## Impact

Added a parameter `temperature` that needs to be added unless `energy_pp` is used.

2023-07-10 21:58 UTC, snschune commented
@grmnptr can you give this a check for consistency of the definition of inflow/outflow faces.

2023-07-10 23:32 UTC, moosebuild commented
Job [Documentation](https://civet.inl.gov/job/1645189/) on 40eaae2 wanted to post the following:

View the site [here](https://mooseframework.inl.gov/docs/PRs/24939/site)

This comment will be updated on new commits.

2023-07-11 00:02 UTC, moosebuild commented
Job [Coverage](https://civet.inl.gov/job/1645207/) on 40eaae2 wanted to post the following:


## Framework coverage

<table>
  <thead>
    <tr>
      <th></th>
      <th>a8316c</th>
      <th colspan=4>#24939 40eaae</th>
    </tr>
    <tr>
      <th></th>
      <th>Total</th>
      <th>Total</th>
      <th>+/-</th>
      <th>New</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><b>Rate</b></td>
      <td>85.58%</td>
      <td>85.58%</td>
      <td>-0.00%</td>
      <td>-</td>
    </tr>
    <tr>
      <td><b>Hits</b></td>
      <td>89463</td>
      <td>89460</td>
      <td>-3</td>
      <td>0</td>
    </tr>
    <tr>
      <td><b>Misses</b></td>
      <td>15074</td>
      <td>15077</td>
      <td>+3</td>
      <td>0</td>
    </tr>
  </tbody>
</table>

[Diff coverage report](https://mooseframework.inl.gov/docs/PRs/24939/coverage_diff/framework)

[Full coverage report](https://mooseframework.inl.gov/docs/PRs/24939/coverage/framework)


## Modules coverage

### Navier stokes

<table>
  <thead>
    <tr>
      <th></th>
      <th>a8316c</th>
      <th colspan=4>#24939 40eaae</th>
    </tr>
    <tr>
      <th></th>
      <th>Total</th>
      <th>Total</th>
      <th>+/-</th>
      <th>New</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><b>Rate</b></td>
      <td>83.96%</td>
      <td>83.95%</td>
      <td>-0.01%</td>
      <td>78.57%</td>
    </tr>
    <tr>
      <td><b>Hits</b></td>
      <td>10944</td>
      <td>10951</td>
      <td>+7</td>
      <td>11</td>
    </tr>
    <tr>
      <td><b>Misses</b></td>
      <td>2091</td>
      <td>2094</td>
      <td>+3</td>
      <td>3</td>
    </tr>
  </tbody>
</table>

[Diff coverage report](https://mooseframework.inl.gov/docs/PRs/24939/coverage_diff/navier_stokes)

[Full coverage report](https://mooseframework.inl.gov/docs/PRs/24939/coverage/navier_stokes)

## Full coverage reports

<details>
<summary>Reports</summary>

- [`framework`](https://mooseframework.inl.gov/docs/PRs/24939/coverage/framework)
- [`chemical_reactions`](https://mooseframework.inl.gov/docs/PRs/24939/coverage/chemical_reactions)
- [`combined`](https://mooseframework.inl.gov/docs/PRs/24939/coverage/combined)
- [`contact`](https://mooseframework.inl.gov/docs/PRs/24939/coverage/contact)
- [`electromagnetics`](https://mooseframework.inl.gov/docs/PRs/24939/coverage/electromagnetics)
- [`external_petsc_solver`](https://mooseframework.inl.gov/docs/PRs/24939/coverage/external_petsc_solver)
- [`fluid_properties`](https://mooseframework.inl.gov/docs/PRs/24939/coverage/fluid_properties)
- [`fsi`](https://mooseframework.inl.gov/docs/PRs/24939/coverage/fsi)
- [`functional_expansion_tools`](https://mooseframework.inl.gov/docs/PRs/24939/coverage/functional_expansion_tools)
- [`geochemistry`](https://mooseframework.inl.gov/docs/PRs/24939/coverage/geochemistry)
- [`heat_conduction`](https://mooseframework.inl.gov/docs/PRs/24939/coverage/heat_conduction)
- [`level_set`](https://mooseframework.inl.gov/docs/PRs/24939/coverage/level_set)
- [`misc`](https://mooseframework.inl.gov/docs/PRs/24939/coverage/misc)
- [`navier_stokes`](https://mooseframework.inl.gov/docs/PRs/24939/coverage/navier_stokes)
- [`optimization`](https://mooseframework.inl.gov/docs/PRs/24939/coverage/optimization)
- [`peridynamics`](https://mooseframework.inl.gov/docs/PRs/24939/coverage/peridynamics)
- [`phase_field`](https://mooseframework.inl.gov/docs/PRs/24939/coverage/phase_field)
- [`porous_flow`](https://mooseframework.inl.gov/docs/PRs/24939/coverage/porous_flow)
- [`ray_tracing`](https://mooseframework.inl.gov/docs/PRs/24939/coverage/ray_tracing)
- [`rdg`](https://mooseframework.inl.gov/docs/PRs/24939/coverage/rdg)
- [`reactor`](https://mooseframework.inl.gov/docs/PRs/24939/coverage/reactor)
- [`richards`](https://mooseframework.inl.gov/docs/PRs/24939/coverage/richards)
- [`scalar_transport`](https://mooseframework.inl.gov/docs/PRs/24939/coverage/scalar_transport)
- [`solid_properties`](https://mooseframework.inl.gov/docs/PRs/24939/coverage/solid_properties)
- [`stochastic_tools`](https://mooseframework.inl.gov/docs/PRs/24939/coverage/stochastic_tools)
- [`tensor_mechanics`](https://mooseframework.inl.gov/docs/PRs/24939/coverage/tensor_mechanics)
- [`thermal_hydraulics`](https://mooseframework.inl.gov/docs/PRs/24939/coverage/thermal_hydraulics)
- [`xfem`](https://mooseframework.inl.gov/docs/PRs/24939/coverage/xfem)

</details>

## Warnings

- `navier_stokes` new line coverage rate 78.57% is less than the suggested 90.0%



This comment will be updated on new commits.

2023-07-12 19:17 UTC, grmnptr commented
The velocity/mass postprocessor, if on a boundary, needs to be positive if it  describes an inlet and negative if it describes an outlet. In this sense this implementation is correct. If you are on an internal boundary, however, you need to define a direction parameter. In this case the postprocessor is positive if it aligns with the direction vector and negative otherwise. This is because I couldn't figure out a way to automatically define a normal on an internal boundary. So in theory if you are on an internal boundary, checking the sign of the velocity is not enough, considering that somebody can define a direction pointing outward. A solution could be to restrict the direction to point outwards/inwards and request the user to know this somehow.

2023-07-13 23:46 UTC, moosebuild commented
Job [Conda (Intel Mac)](https://civet.inl.gov/job/1645197/) on 40eaae2 : invalidated by @snschune

2023-07-14 04:09 UTC, moosebuild commented
Job [Apptainer build rocky9](https://civet.inl.gov/job/1645169/) on 40eaae2 : invalidated by @snschune

2023-07-14 04:10 UTC, moosebuild commented
Job [Apptainer build cuda](https://civet.inl.gov/job/1645168/) on 40eaae2 : invalidated by @snschune

2023-07-14 04:10 UTC, moosebuild commented
Job [Newer gcc](https://civet.inl.gov/job/1645202/) on 40eaae2 : invalidated by @snschune

2023-07-17 13:59 UTC, lindsayad commented
What is the state of this PR? Is more development needed before review or is this ready for review?

2023-07-17 14:32 UTC, grmnptr commented
I don't think the current behavior is failsafe if we are on an internal boundary when the direction parameter is defined. I can add the last pieces if needed.

2023-07-17 14:35 UTC, grmnptr commented
A potential solution could be to require that the user always sets the normal pointing outward and document it with huge warnings. Then the current implementation works.

2023-07-17 22:04 UTC, snschune commented
@grmnptr I think the behavior before this commit is added, is not failsafe either. 
Positive postprocessor means flow goes along `direction`. However, if `direction`
points outward from the domain and the postprocessor value is positive, then you should never use a prescribed 
value in the boundary anyway. On outflow faces, you should use the computed value of
enthalpy from within the domain. 

So the added code does not make it any less failsafe, does it?
I would say that we need to emphasize that direction needs to point into the domain.

2023-07-17 22:23 UTC, grmnptr commented
Well, I agree that allowing the user to choose the direction was not an optimal solution from my side. I thought the connection between the sign of the postprocessor and the direction parameter was documented better on the website but it looks like it isn't, I am definitely at fault for that one. I like the idea of requiring the user to set the direction in a way that it always points inwards. Do you want me to add these changes or do you have time for it?

2023-07-18 01:05 UTC, snschune commented
I'll do it.

2023-07-21 15:38 UTC, snschune commented
@grmnptr looking at the code, does it really matter which direction we define `_direction`?
It is used here (see absolute value):

```
const Point incoming_vector = !_direction_specified_by_user ? _face_info->normal() : _direction;
const Real cos_angle = std::abs(incoming_vector * _face_info->normal());
```

It won't make a difference if I provide `_direction` or `-_direction`. The only definition that matters is 
`_velocity_pp` and `_mdot_pp`. In particular, `_velocity_pp > 0` does not mean velocity goes along `_direction`, but 
rather that it's inflow and vice versa for the negative case.

2023-07-21 17:18 UTC, grmnptr commented
Ahhh, you are completely right. I didn't remember putting an absolute value on the dot product. So the current implementation is even less fail-proof than I imagined because the issue remains: just by a velocity magnitude prostprocesor we don't know what direction the flow is going with respect to the mesh so we don't know if it is an outflow or inflow. The current implementation narrows it down to two directions but it still depends on the original elem-neighbor pair construction to decide which which will get a source and which will get a sink. I think this would probably solve the problem. Instead of this:

```
const Point incoming_vector = !_direction_specified_by_user ? _face_info->normal() : _direction;
const Real cos_angle = std::abs(incoming_vector * _face_info->normal());
```

we could have something this:

```
const Real cos_angle = !_direction_specified_by_user ? 1.0 : _direction*_face_info->normal();
return _scaling_factor * (*_rho)(singleSidedFaceArg(), state) * *_velocity_pp * cos_angle *
             (*_cp)(singleSidedFaceArg(), state) * T;
```
The thing is that we might have to change the mass pp option too. 

At the same time, considering that the current behavior is obviously flawed and your approach definitely works with it, I would be okay with letting this in and submitting an issue to fix the remaining directionality problems of these PPs in a different PR. What do you think @lindsayad ?

2023-07-21 18:37 UTC, snschune commented
Not sure I would push this can down the road. Let's solve this problem here before the overlapping domain coupling approach goes in.

2023-07-21 18:43 UTC, snschune commented
`_face_info->normal()` is the normal pointing outward from elem. 
`WCNSFVEnergyFluxBC` is a boundary object and therefore either `elem` or `neighbor`
have `T_fluid` (the variable that this object operates on) defined, while the other does not.
This can be queried and based on it we can flip the normal and test against direction.

2023-07-21 22:52 UTC, snschune commented
In `FVFluxBC` `_normal` is defined like this:

```
  _face_info = &fi;
  _normal = fi.normal();
  _face_type = fi.faceType(_var.name());

  // For FV flux kernels, the normal is always oriented outward from the lower-id
  // element's perspective.  But for BCs, there is only a residual
  // contribution to one element (one side of the face).  Because of this, we
  // make an exception and orient the normal to point outward from whichever
  // side of the face the BC's variable is defined on; we flip it if this
  // variable is defined on the neighbor side of the face (instead of elem) since
  // the FaceInfo normal polarity is always oriented with respect to the lower-id element.
  if (_face_type == FaceInfo::VarFaceNeighbors::NEIGHBOR)
    _normal = -_normal;
```

Does this guarantee that `_normal` always points outward?

2023-07-22 05:20 UTC, snschune commented
@grmnptr plan of attack:

1. All objects inheriting from `WCNSFVFluxBCBase` will either explicitly implement flow reversal or check for wrong flow direction and error out. 
2. `WCNSFVFluxBCBase` will couple in `vel_x, vel_y, vel_z`.
3. The flow direction is given by the sign of `_velocity_pp`, `_mdot_pp`, `_energy_pp` depending on what is provided. If the PP is positive it's inflow, if not it's outflow.
4. In case of inflow, we use `direction` if provided. We can either compute `direction * _normal` and error if positive or simply use `-abs(direction * normal)`. The latter seems easier to me.
5. In case of outflow, we compute the outflow energy/momentum/mass from velocities, temperatures etc. from within the domain. In this case we need the dot product `_normal * _vel`.
6. A problem would occur if the `_velocity_pp < 0` (outflow) and `_normal * _vel < 0` (inflow). What should happen in this case?

2023-07-25 21:57 UTC, snschune commented on modules/navier_stokes/src/fvbcs/WCNSFVFluxBCBase.C
> +  checkForInternalDirection();
@grmnptr I don't think we need to check for internal boundaries at all here since it doesn't matter for determining what direction the flow goes.

2023-07-25 21:57 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/1664751/) on 32b219b wanted to post the following:

Your code requires style changes.  

A patch was auto generated and copied [here](https://mooseframework.inl.gov/docs/PRs/24939/clang_format/style.patch)  
You can directly apply the patch by running, in the top level of your repository:

`curl -s https://mooseframework.inl.gov/docs/PRs/24939/clang_format/style.patch | git apply -v`  

Alternatively, with your repository up to date and in the top level of your repository:

`git clang-format 95b3612a8a863885645cdc717b2824139fe0b630`

2023-07-25 21:57 UTC, snschune commented
@lindsayad @grmnptr this is a demo of the design I have in mind. Before I change all the other files, can you take a look and comment?

2023-07-27 23:04 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/1667796/) on e05e1d3 wanted to post the following:

Your code requires style changes.  

A patch was auto generated and copied [here](https://mooseframework.inl.gov/docs/PRs/24939/clang_format/style.patch)  
You can directly apply the patch by running, in the top level of your repository:

`curl -s https://mooseframework.inl.gov/docs/PRs/24939/clang_format/style.patch | git apply -v`  

Alternatively, with your repository up to date and in the top level of your repository:

`git clang-format 8dace0658c8848f07ab307a0e218652d5c009505`

2023-07-27 23:38 UTC, snschune commented
@grmnptr I would like to discuss the places where the `cos` is multiplied to get inlet speeds to make sure I handled that correctly.

2023-08-03 16:35 UTC, lindsayad commented
I think @grmnptr is now on leave. Is this time sensitive?

2023-08-03 17:43 UTC, snschune commented
@lindsayad  No, it can wait. I am still waiting on changes in SAM before the blue_crab PR can go in anyway.

2023-08-29 21:40 UTC, moosebuild commented
Job [Documentation internal apps](https://civet.inl.gov/job/1676218/) on dcf769e : invalidated by @snschune

2023-08-30 17:34 UTC, lindsayad commented
@grmnptr I think this is ready for more review

2023-08-31 15:12 UTC, grmnptr requested changes
I love this! Just a few superficial changes are left.

2023-08-31 15:12 UTC, grmnptr commented on modules/navier_stokes/src/fvbcs/WCNSFVEnergyFluxBC.C
> +  params.addRequiredParam<MooseFunctorName>("temperature", "temperature functor");
I suggest using

```suggestion
  params.addRequiredParam<MooseFunctorName>(NS::T_fluid, "temperature functor");
```

or 

```suggestion
  params.addRequiredParam<MooseFunctorName>(NS::temperature, "temperature functor");
```

2023-08-31 15:12 UTC, grmnptr commented on modules/navier_stokes/src/fvbcs/WCNSFVMassFluxBC.C
> +    auto fa = singleSidedFaceArg();
```suggestion
    const auto fa = singleSidedFaceArg();
```

2023-08-31 15:12 UTC, grmnptr commented on modules/navier_stokes/src/fvbcs/WCNSFVScalarFluxBC.C
> +    return *_scalar_flux_pp >= 0;
Could you please add this logic to the documentation so that we can point the users to it? Thanks!

2023-08-31 15:12 UTC, grmnptr commented on modules/navier_stokes/include/fvbcs/WCNSFVFluxBCBase.h
> +  /// true if a boundary is an inflow boundary, false of outflow
```suggestion
  /// true if a boundary is an inflow boundary, false if outflow
```

2023-10-03 15:29 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/1804416/) on fd41caa wanted to post the following:

Your code requires style changes.  

A patch was auto generated and copied [here](https://mooseframework.inl.gov/docs/PRs/24939/clang_format/style.patch)  
You can directly apply the patch by running, in the top level of your repository:

`curl -s https://mooseframework.inl.gov/docs/PRs/24939/clang_format/style.patch | git apply -v`  

Alternatively, with your repository up to date and in the top level of your repository:

`git clang-format 750e5c6f003a38a7a770d2d745cb2231c2545e2a`

2023-10-03 23:29 UTC, snschune commented
@grmnptr I think I addressed all your comments.

2023-10-05 20:16 UTC, grmnptr approved these changes
Looks good to me, thanks for the contribution!

2023-10-05 20:16 UTC, merged