Make July 2023 news public
idaholab/moose pull request #25062
Opened 2023-07-31 14:41 UTC by cticenhour

Also adds August news template.

@idaholab/moose-ccb -- Please add any last minute additions from the last month. This edition is a bit light, so I imagine there are several!

Refs #11447

2023-07-31 16:21 UTC, moosebuild commented
Job [Documentation](https://civet.inl.gov/job/1670042/) on 4a31c2d wanted to post the following:

View the site [here](https://mooseframework.inl.gov/docs/PRs/25062/site)

This comment will be updated on new commits.

2023-07-31 18:26 UTC, YaqiWang commented
Just notice this. I will add one entry about the console time format that @GiudGiud suggested me.

2023-07-31 18:58 UTC, cticenhour commented on modules/doc/content/newsletter/2023/2023_07.md
> +- Fixes for `MeshedHole` (and thereby [XYDelaunayMeshGenerator.md]
```suggestion
- Fixes for `MeshedHole` (and thereby [XYDelaunayGenerator.md]
```

2023-08-01 16:54 UTC, lindsayad requested changes

2023-08-01 16:54 UTC, lindsayad commented on modules/doc/content/newsletter/2023/2023_07.md
> +- Parallel scalability tested upto 50 parallel proposals.
```suggestion
- Parallel scalability tested up to 50 parallel proposals.
```

2023-08-01 17:13 UTC, cticenhour commented on modules/doc/content/newsletter/2023/2023_07.md
> +how times are printed during transient simulations. Internally, MOOSE uses seconds as its unit of
Yeah good point - this is only a convenience addition to the printout. How about "Internally, MOOSE has no default unit for time, but, with this change, MOOSE can now...."?

2023-08-01 17:35 UTC, cticenhour commented on modules/doc/content/newsletter/2023/2023_07.md
> +how times are printed during transient simulations. Internally, MOOSE uses seconds as its unit of
Resolved in [1c31713](https://github.com/idaholab/moose/pull/25062/commits/1c31713c928ae912e5a19f18a27ecb8693352a2e)

2023-08-01 17:36 UTC, cticenhour commented on modules/doc/content/newsletter/2023/2023_07.md
```suggestion
```

Should remove since PETSc update is happening in August news.

2023-08-01 18:11 UTC, lindsayad approved these changes

2023-08-01 19:23 UTC, merged