Add documentation for THM kernels and scalar kernels
idaholab/moose pull request #25077
Opened 2023-08-01 22:00 UTC by GiudGiud

refs #19737

To be considered after the previous one has been merged

2023-08-02 00:04 UTC, moosebuild commented
Job [Coverage](https://civet.inl.gov/job/1673220/) on 4c4dc4d wanted to post the following:


## Framework coverage

<table>
  <thead>
    <tr>
      <th></th>
      <th>98c121</th>
      <th colspan=4>#25077 4c4dc4</th>
    </tr>
    <tr>
      <th></th>
      <th>Total</th>
      <th>Total</th>
      <th>+/-</th>
      <th>New</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><b>Rate</b></td>
      <td>85.60%</td>
      <td>85.60%</td>
      <td>-</td>
      <td>100.00%</td>
    </tr>
    <tr>
      <td><b>Hits</b></td>
      <td>89552</td>
      <td>89552</td>
      <td>-</td>
      <td>1</td>
    </tr>
    <tr>
      <td><b>Misses</b></td>
      <td>15067</td>
      <td>15067</td>
      <td>-</td>
      <td>0</td>
    </tr>
  </tbody>
</table>

[Diff coverage report](https://mooseframework.inl.gov/docs/PRs/25077/coverage_diff/framework)

[Full coverage report](https://mooseframework.inl.gov/docs/PRs/25077/coverage/framework)


## Modules coverage

### Thermal hydraulics

<table>
  <thead>
    <tr>
      <th></th>
      <th>98c121</th>
      <th colspan=4>#25077 4c4dc4</th>
    </tr>
    <tr>
      <th></th>
      <th>Total</th>
      <th>Total</th>
      <th>+/-</th>
      <th>New</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><b>Rate</b></td>
      <td>90.60%</td>
      <td>90.59%</td>
      <td>-0.01%</td>
      <td>88.46%</td>
    </tr>
    <tr>
      <td><b>Hits</b></td>
      <td>13017</td>
      <td>13033</td>
      <td>+16</td>
      <td>23</td>
    </tr>
    <tr>
      <td><b>Misses</b></td>
      <td>1351</td>
      <td>1354</td>
      <td>+3</td>
      <td>3</td>
    </tr>
  </tbody>
</table>

[Diff coverage report](https://mooseframework.inl.gov/docs/PRs/25077/coverage_diff/thermal_hydraulics)

[Full coverage report](https://mooseframework.inl.gov/docs/PRs/25077/coverage/thermal_hydraulics)

## Full coverage reports

<details>
<summary>Reports</summary>

- [`framework`](https://mooseframework.inl.gov/docs/PRs/25077/coverage/framework)
- [`chemical_reactions`](https://mooseframework.inl.gov/docs/PRs/25077/coverage/chemical_reactions)
- [`combined`](https://mooseframework.inl.gov/docs/PRs/25077/coverage/combined)
- [`contact`](https://mooseframework.inl.gov/docs/PRs/25077/coverage/contact)
- [`electromagnetics`](https://mooseframework.inl.gov/docs/PRs/25077/coverage/electromagnetics)
- [`external_petsc_solver`](https://mooseframework.inl.gov/docs/PRs/25077/coverage/external_petsc_solver)
- [`fluid_properties`](https://mooseframework.inl.gov/docs/PRs/25077/coverage/fluid_properties)
- [`fsi`](https://mooseframework.inl.gov/docs/PRs/25077/coverage/fsi)
- [`functional_expansion_tools`](https://mooseframework.inl.gov/docs/PRs/25077/coverage/functional_expansion_tools)
- [`geochemistry`](https://mooseframework.inl.gov/docs/PRs/25077/coverage/geochemistry)
- [`heat_conduction`](https://mooseframework.inl.gov/docs/PRs/25077/coverage/heat_conduction)
- [`level_set`](https://mooseframework.inl.gov/docs/PRs/25077/coverage/level_set)
- [`misc`](https://mooseframework.inl.gov/docs/PRs/25077/coverage/misc)
- [`navier_stokes`](https://mooseframework.inl.gov/docs/PRs/25077/coverage/navier_stokes)
- [`optimization`](https://mooseframework.inl.gov/docs/PRs/25077/coverage/optimization)
- [`peridynamics`](https://mooseframework.inl.gov/docs/PRs/25077/coverage/peridynamics)
- [`phase_field`](https://mooseframework.inl.gov/docs/PRs/25077/coverage/phase_field)
- [`porous_flow`](https://mooseframework.inl.gov/docs/PRs/25077/coverage/porous_flow)
- [`ray_tracing`](https://mooseframework.inl.gov/docs/PRs/25077/coverage/ray_tracing)
- [`rdg`](https://mooseframework.inl.gov/docs/PRs/25077/coverage/rdg)
- [`reactor`](https://mooseframework.inl.gov/docs/PRs/25077/coverage/reactor)
- [`richards`](https://mooseframework.inl.gov/docs/PRs/25077/coverage/richards)
- [`scalar_transport`](https://mooseframework.inl.gov/docs/PRs/25077/coverage/scalar_transport)
- [`solid_properties`](https://mooseframework.inl.gov/docs/PRs/25077/coverage/solid_properties)
- [`stochastic_tools`](https://mooseframework.inl.gov/docs/PRs/25077/coverage/stochastic_tools)
- [`tensor_mechanics`](https://mooseframework.inl.gov/docs/PRs/25077/coverage/tensor_mechanics)
- [`thermal_hydraulics`](https://mooseframework.inl.gov/docs/PRs/25077/coverage/thermal_hydraulics)
- [`xfem`](https://mooseframework.inl.gov/docs/PRs/25077/coverage/xfem)

</details>

## Warnings

- `thermal_hydraulics` new line coverage rate 88.46% is less than the suggested 90.0%



This comment will be updated on new commits.

2023-08-02 00:13 UTC, moosebuild commented
Job [Documentation](https://civet.inl.gov/job/1673177/) on 4c4dc4d wanted to post the following:

View the site [here](https://mooseframework.inl.gov/docs/PRs/25077/site)

This comment will be updated on new commits.

2023-08-05 12:44 UTC, moosebuild commented
Job [Conda MOOSE (Linux)](https://civet.inl.gov/job/1681400/) on 1e91491 : invalidated by @GiudGiud

fake failure

2023-08-06 17:38 UTC, moosebuild commented
Job [Conda MOOSE (Linux)](https://civet.inl.gov/job/1681400/) on 1e91491 : invalidated by @GiudGiud

stil fake

2023-08-07 03:17 UTC, GiudGiud commented on modules/thermal_hydraulics/doc/content/source/base/FlowModelSinglePhase.md
> +The `FlowModelSinglePhase` creates for [FlowChannel1Phase.md] components using the three equation model:
```suggestion
The `FlowModelSinglePhase` creates for [FlowChannel1Phase.md] components using the three equations model:
```

2023-08-07 03:19 UTC, GiudGiud commented on modules/thermal_hydraulics/doc/content/source/kernels/ADHeatConductionRZ.md
> +except that the residual and Jacobian contributions are derived for cylindrical coordinates, the axis and origin
```suggestion
except that the residual and Jacobian contributions are integrated with cylindrical coordinates, the axis and origin
```
prefer that?

2023-08-07 03:24 UTC, GiudGiud commented on modules/thermal_hydraulics/src/kernels/OneD3EqnMomentumFlux.C
> +  params.addClassDescription("Computes a omentum flux term for 1-phase flow");
```suggestion
  params.addClassDescription("Computes a momentum flux term for 1-phase flow");
```

2023-08-07 03:25 UTC, GiudGiud commented on modules/thermal_hydraulics/src/kernels/OneDEnergyWallHeatFlux.C
> +  params.addClassDescription("Add a heat flux along the local heated perimeter");
```suggestion
  params.addClassDescription("Adds a heat flux along the local heated perimeter");
```

2023-08-07 03:25 UTC, GiudGiud commented on modules/thermal_hydraulics/src/kernels/CoupledForceRZ.C
> +      "Add a coupled force term in XY coordinates interpreted as cylindrical coordinates");
```suggestion
      "Adds a coupled force term in XY coordinates interpreted as cylindrical coordinates");
```

2023-08-07 03:25 UTC, GiudGiud commented on modules/thermal_hydraulics/src/kernels/ADHeatConductionRZ.C
> +      "Add a heat conduction term in XY coordinates interpreted as cylindrical coordinates");
```suggestion
      "Adds a heat conduction term in XY coordinates interpreted as cylindrical coordinates");
```

2023-08-07 03:25 UTC, GiudGiud commented on modules/thermal_hydraulics/src/kernels/ADHeatConductionTimeDerivativeRZ.C
> +  params.addClassDescription("Add a time derivative term for the energy equation in XY coordinates "
```suggestion
  params.addClassDescription("Adds a time derivative term for the energy equation in XY coordinates "
```

2023-08-07 03:25 UTC, GiudGiud commented on modules/thermal_hydraulics/src/kernels/ADHeatStructureHeatSource.C
> +  params.addClassDescription("Add a heat source term for the energy equation");
```suggestion
  params.addClassDescription("Adds a heat source term for the energy equation");
```

2023-08-07 03:25 UTC, GiudGiud commented on modules/thermal_hydraulics/src/kernels/ADHeatStructureHeatSourceRZ.C
> +      "Add a heat source term in XY coordinates interpreted as cylindrical coordinates");
```suggestion
      "Adds a heat source term in XY coordinates interpreted as cylindrical coordinates");
```

2023-08-07 03:26 UTC, GiudGiud commented on modules/thermal_hydraulics/src/scalarkernels/ADShaftTimeDerivativeScalarKernel.C
> +  params.addClassDescription("Add a time derivative term to the shaft ODE");
```suggestion
  params.addClassDescription("Adds a time derivative term to the shaft ODE");
```

2023-08-07 03:26 UTC, GiudGiud commented on modules/thermal_hydraulics/src/scalarkernels/ShaftTimeDerivativeScalarKernel.C
> +  params.addClassDescription("Add a time derivative term to the shaft ODE");
```suggestion
  params.addClassDescription("Adds a time derivative term to the shaft ODE");
```

2023-08-07 03:27 UTC, GiudGiud commented
should be fairly ready for review. Civet is hosed rn

2023-08-07 03:29 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/1682244/) on 76d4af5 wanted to post the following:

Your code requires style changes.  

A patch was auto generated and copied [here](https://mooseframework.inl.gov/docs/PRs/25077/clang_format/style.patch)  
You can directly apply the patch by running, in the top level of your repository:

`curl -s https://mooseframework.inl.gov/docs/PRs/25077/clang_format/style.patch | git apply -v`  

Alternatively, with your repository up to date and in the top level of your repository:

`git clang-format 5f86f198a56ed6985d1ebc282b81da3f049af20b`

2023-08-09 14:25 UTC, joshuahansel commented on modules/thermal_hydraulics/doc/content/source/kernels/ADHeatConductionRZ.md
> +except that the residual and Jacobian contributions are derived for cylindrical coordinates, the axis and origin
Yeah

2023-08-09 15:32 UTC, joshuahansel requested changes

2023-08-09 15:32 UTC, joshuahansel commented on modules/thermal_hydraulics/doc/content/source/base/FlowModelSinglePhase.md
> +The `FlowModelSinglePhase` creates for [FlowChannel1Phase.md] components using the three equations model:
```suggestion
The `FlowModelSinglePhase` creates the following for [FlowChannel1Phase.md] components using the 3-equation model:
```

2023-08-09 15:32 UTC, joshuahansel commented on modules/thermal_hydraulics/doc/content/source/base/FlowModelSinglePhase.md
> +- kernels and DGKernels for RDG
```suggestion
- kernels and DGKernels
```

2023-08-09 16:35 UTC, GiudGiud commented on modules/thermal_hydraulics/doc/content/source/kernels/ADHeatConductionTimeDerivativeRZ.md
> +except that the residual and Jacobian contributions are derived for cylindrical coordinates, the axis and origin
```suggestion
except that the residual and Jacobian contributions are integrated with cylindrical coordinates, the axis and origin
```

2023-08-10 00:45 UTC, GiudGiud commented
fake fails

2023-08-10 12:28 UTC, joshuahansel approved these changes

2023-08-10 13:02 UTC, merged