Replace old issue templates with new yml-based issue templates
idaholab/moose pull request #25125
Opened 2023-08-07 13:46 UTC by hugary1995

close #25124

The new .yml issue templates are much more user-friendly, IMHO. It has a few advantages compared to the old .md based templates:
- Allows for textareas.
- Allows for validation (some fields are required)
- I reserved empty templates, so if you can create an issue without templates if absolutely necessary.
- There is a redirect link at the bottom pointing users to the discussion page if they want to ask questions.

2023-08-18 02:54 UTC, loganharbour commented
Thanks @hugary1995; is there not an easy way to test this?

2023-08-18 10:11 UTC, hugary1995 commented
If you view the file in the browser, I think GitHub will automatically render it. But that doesn't look the same as the real thing...

The easiest way I can think of is to test this in a dummy repo.

2023-10-02 00:05 UTC, hugary1995 commented
Here, take a look: https://github.com/hugary1995/test-issue-template

2023-10-12 16:41 UTC, cticenhour requested changes
I like this idea. The new form in the test repository looks really nice!

Only one suggestion: I noticed that the labels were missing from the bug report. Otherwise it seems like everything else we require is there.

2023-10-12 16:41 UTC, cticenhour commented on .github/ISSUE_TEMPLATE/bug-report.yml
> +
```suggestion
labels: 'T: defect, P: normal'

```

2023-10-16 09:12 UTC, hugary1995 commented
I just committed your suggestion, assuming you've tested it. If not I can make the change in the test repo.

2023-10-16 10:44 UTC, moosebuild commented
Job [Documentation](https://civet.inl.gov/job/1824320/) on e456d7b wanted to post the following:

View the site [here](https://mooseframework.inl.gov/docs/PRs/25125/site)

This comment will be updated on new commits.

2023-10-16 11:26 UTC, moosebuild commented
Job [Coverage](https://civet.inl.gov/job/1824338/) on e456d7b wanted to post the following:


## Framework coverage

<table>
  <thead>
    <tr>
      <th></th>
      <th>6d70fb</th>
      <th colspan=4>#25125 e456d7</th>
    </tr>
    <tr>
      <th></th>
      <th>Total</th>
      <th>Total</th>
      <th>+/-</th>
      <th>New</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><b>Rate</b></td>
      <td>85.77%</td>
      <td>85.77%</td>
      <td>+0.00%</td>
      <td>-</td>
    </tr>
    <tr>
      <td><b>Hits</b></td>
      <td>92086</td>
      <td>92087</td>
      <td>+1</td>
      <td>0</td>
    </tr>
    <tr>
      <td><b>Misses</b></td>
      <td>15281</td>
      <td>15280</td>
      <td>-1</td>
      <td>0</td>
    </tr>
  </tbody>
</table>

[Diff coverage report](https://mooseframework.inl.gov/docs/PRs/25125/coverage_diff/framework)

[Full coverage report](https://mooseframework.inl.gov/docs/PRs/25125/coverage/framework)


## Modules coverage

Coverage did not change

## Full coverage reports

<details>
<summary>Reports</summary>

- [`framework`](https://mooseframework.inl.gov/docs/PRs/25125/coverage/framework)
- [`chemical_reactions`](https://mooseframework.inl.gov/docs/PRs/25125/coverage/chemical_reactions)
- [`combined`](https://mooseframework.inl.gov/docs/PRs/25125/coverage/combined)
- [`contact`](https://mooseframework.inl.gov/docs/PRs/25125/coverage/contact)
- [`electromagnetics`](https://mooseframework.inl.gov/docs/PRs/25125/coverage/electromagnetics)
- [`external_petsc_solver`](https://mooseframework.inl.gov/docs/PRs/25125/coverage/external_petsc_solver)
- [`fluid_properties`](https://mooseframework.inl.gov/docs/PRs/25125/coverage/fluid_properties)
- [`fsi`](https://mooseframework.inl.gov/docs/PRs/25125/coverage/fsi)
- [`functional_expansion_tools`](https://mooseframework.inl.gov/docs/PRs/25125/coverage/functional_expansion_tools)
- [`geochemistry`](https://mooseframework.inl.gov/docs/PRs/25125/coverage/geochemistry)
- [`heat_conduction`](https://mooseframework.inl.gov/docs/PRs/25125/coverage/heat_conduction)
- [`level_set`](https://mooseframework.inl.gov/docs/PRs/25125/coverage/level_set)
- [`misc`](https://mooseframework.inl.gov/docs/PRs/25125/coverage/misc)
- [`navier_stokes`](https://mooseframework.inl.gov/docs/PRs/25125/coverage/navier_stokes)
- [`optimization`](https://mooseframework.inl.gov/docs/PRs/25125/coverage/optimization)
- [`peridynamics`](https://mooseframework.inl.gov/docs/PRs/25125/coverage/peridynamics)
- [`phase_field`](https://mooseframework.inl.gov/docs/PRs/25125/coverage/phase_field)
- [`porous_flow`](https://mooseframework.inl.gov/docs/PRs/25125/coverage/porous_flow)
- [`ray_tracing`](https://mooseframework.inl.gov/docs/PRs/25125/coverage/ray_tracing)
- [`rdg`](https://mooseframework.inl.gov/docs/PRs/25125/coverage/rdg)
- [`reactor`](https://mooseframework.inl.gov/docs/PRs/25125/coverage/reactor)
- [`richards`](https://mooseframework.inl.gov/docs/PRs/25125/coverage/richards)
- [`scalar_transport`](https://mooseframework.inl.gov/docs/PRs/25125/coverage/scalar_transport)
- [`solid_properties`](https://mooseframework.inl.gov/docs/PRs/25125/coverage/solid_properties)
- [`stochastic_tools`](https://mooseframework.inl.gov/docs/PRs/25125/coverage/stochastic_tools)
- [`tensor_mechanics`](https://mooseframework.inl.gov/docs/PRs/25125/coverage/tensor_mechanics)
- [`thermal_hydraulics`](https://mooseframework.inl.gov/docs/PRs/25125/coverage/thermal_hydraulics)
- [`xfem`](https://mooseframework.inl.gov/docs/PRs/25125/coverage/xfem)

</details>



This comment will be updated on new commits.

2024-02-01 17:20 UTC, cticenhour commented
Re-opening, as we'll need to upgrade to these eventually. Assigning myself, so I can explore them and give a proper review.

2024-03-05 22:29 UTC, cticenhour requested changes
Need to make more fields required for SQA for the Feature Request. Also made a suggested adjustment to the Questions link description.

2024-03-05 22:29 UTC, cticenhour commented on .github/ISSUE_TEMPLATE/feature-request.yml
> +    required: false
```suggestion
    required: true
```

2024-03-05 22:29 UTC, cticenhour commented on .github/ISSUE_TEMPLATE/feature-request.yml
> +    required: false
```suggestion
    required: true
```

2024-03-05 22:29 UTC, cticenhour commented on .github/ISSUE_TEMPLATE/config.yml
> +    about: Ask questions and discuss with other MOOSE community members
```suggestion
    about: Ask general questions about MOOSE and discuss with other MOOSE community members.
```

2024-03-06 15:58 UTC, cticenhour commented
@hugary1995 Do you mind squashing those last three commits? Just in case you didn't know, you can batch commit review suggestions by going into the "Files changed" tab and handling them there.

2024-03-06 16:02 UTC, hugary1995 commented
Good to know!

2024-03-06 16:07 UTC, cticenhour approved these changes

2024-03-06 17:07 UTC, lindsayad approved these changes

2024-03-06 19:13 UTC, merged