Improve grain growth model documentation
idaholab/moose pull request #25340
Opened 2023-08-29 21:50 UTC by tonkmr

Improves the documentation for the grain growth model. Also updates examples problems to represent recommended practices for running such simulations.

Closes #25144

This PR only changes documentation, example input files, and one test input file (gold file is unchanged).

2023-08-29 21:52 UTC, tonkmr commented
The best place to start with this PR is Grain_Growth_Model.md. Every documentation page linked from there now exists.

2023-08-29 23:56 UTC, moosebuild commented
Job [Coverage](https://civet.inl.gov/job/1733880/) on a3cac45 wanted to post the following:


## Framework coverage

<table>
  <thead>
    <tr>
      <th></th>
      <th>e5367e</th>
      <th colspan=4>#25340 a3cac4</th>
    </tr>
    <tr>
      <th></th>
      <th>Total</th>
      <th>Total</th>
      <th>+/-</th>
      <th>New</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><b>Rate</b></td>
      <td>85.65%</td>
      <td>85.65%</td>
      <td>+0.00%</td>
      <td>-</td>
    </tr>
    <tr>
      <td><b>Hits</b></td>
      <td>90369</td>
      <td>90373</td>
      <td>+4</td>
      <td>0</td>
    </tr>
    <tr>
      <td><b>Misses</b></td>
      <td>15142</td>
      <td>15138</td>
      <td>-4</td>
      <td>0</td>
    </tr>
  </tbody>
</table>

[Diff coverage report](https://mooseframework.inl.gov/docs/PRs/25340/coverage_diff/framework)

[Full coverage report](https://mooseframework.inl.gov/docs/PRs/25340/coverage/framework)


## Modules coverage

Coverage did not change

## Full coverage reports

<details>
<summary>Reports</summary>

- [`framework`](https://mooseframework.inl.gov/docs/PRs/25340/coverage/framework)
- [`chemical_reactions`](https://mooseframework.inl.gov/docs/PRs/25340/coverage/chemical_reactions)
- [`combined`](https://mooseframework.inl.gov/docs/PRs/25340/coverage/combined)
- [`contact`](https://mooseframework.inl.gov/docs/PRs/25340/coverage/contact)
- [`electromagnetics`](https://mooseframework.inl.gov/docs/PRs/25340/coverage/electromagnetics)
- [`external_petsc_solver`](https://mooseframework.inl.gov/docs/PRs/25340/coverage/external_petsc_solver)
- [`fluid_properties`](https://mooseframework.inl.gov/docs/PRs/25340/coverage/fluid_properties)
- [`fsi`](https://mooseframework.inl.gov/docs/PRs/25340/coverage/fsi)
- [`functional_expansion_tools`](https://mooseframework.inl.gov/docs/PRs/25340/coverage/functional_expansion_tools)
- [`geochemistry`](https://mooseframework.inl.gov/docs/PRs/25340/coverage/geochemistry)
- [`heat_conduction`](https://mooseframework.inl.gov/docs/PRs/25340/coverage/heat_conduction)
- [`level_set`](https://mooseframework.inl.gov/docs/PRs/25340/coverage/level_set)
- [`misc`](https://mooseframework.inl.gov/docs/PRs/25340/coverage/misc)
- [`navier_stokes`](https://mooseframework.inl.gov/docs/PRs/25340/coverage/navier_stokes)
- [`optimization`](https://mooseframework.inl.gov/docs/PRs/25340/coverage/optimization)
- [`peridynamics`](https://mooseframework.inl.gov/docs/PRs/25340/coverage/peridynamics)
- [`phase_field`](https://mooseframework.inl.gov/docs/PRs/25340/coverage/phase_field)
- [`porous_flow`](https://mooseframework.inl.gov/docs/PRs/25340/coverage/porous_flow)
- [`ray_tracing`](https://mooseframework.inl.gov/docs/PRs/25340/coverage/ray_tracing)
- [`rdg`](https://mooseframework.inl.gov/docs/PRs/25340/coverage/rdg)
- [`reactor`](https://mooseframework.inl.gov/docs/PRs/25340/coverage/reactor)
- [`richards`](https://mooseframework.inl.gov/docs/PRs/25340/coverage/richards)
- [`scalar_transport`](https://mooseframework.inl.gov/docs/PRs/25340/coverage/scalar_transport)
- [`solid_properties`](https://mooseframework.inl.gov/docs/PRs/25340/coverage/solid_properties)
- [`stochastic_tools`](https://mooseframework.inl.gov/docs/PRs/25340/coverage/stochastic_tools)
- [`tensor_mechanics`](https://mooseframework.inl.gov/docs/PRs/25340/coverage/tensor_mechanics)
- [`thermal_hydraulics`](https://mooseframework.inl.gov/docs/PRs/25340/coverage/thermal_hydraulics)
- [`xfem`](https://mooseframework.inl.gov/docs/PRs/25340/coverage/xfem)

</details>



This comment will be updated on new commits.

2023-08-30 00:06 UTC, moosebuild commented
Job [Documentation](https://civet.inl.gov/job/1733837/) on a3cac45 wanted to post the following:

View the site [here](https://mooseframework.inl.gov/docs/PRs/25340/site)

This comment will be updated on new commits.

2023-08-30 21:09 UTC, tonkmr commented
@dschwen, @GiudGiud, and @laagesen this is ready to review.

2023-08-31 19:44 UTC, GiudGiud commented on modules/phase_field/doc/content/source/actions/GrainGrowthAction.md
> +- [BndsCalcAux](/BndsCalcAux.md)
```suggestion
- [BndsCalcAux](/BndsCalcAux.md) use to set the grain boundaries visualization variable
```

2023-08-31 19:45 UTC, GiudGiud commented on modules/phase_field/doc/content/source/actions/GrainGrowthAction.md
> +  - Order parameter (`var_name_base`)
no clear what you mean here.
do you mean op_num variables for each var_bame_base ?

2023-08-31 19:46 UTC, GiudGiud commented on modules/phase_field/doc/content/source/actions/GrainGrowthAction.md
> +The `GrainGrowthAction` is accessed through the `Module` block, as shown below.
```suggestion
The `GrainGrowthAction` is created as shown below.
```
we no longer use the Modules/ syntax

2023-08-31 19:55 UTC, GiudGiud reviewed
didn't see much but SMEs should review

2023-09-05 16:25 UTC, laagesen requested changes
Thanks for helping improve the documentation!

2023-09-05 16:25 UTC, laagesen commented on modules/phase_field/doc/content/source/materials/GBEvolution.md
> +\mu = \frac{3}{2} \frac{\gamma}{w_{GB}}
please see previous comment about value of the prefactor and switching from \gamma to \sigma for interfacial energy

2023-09-05 17:16 UTC, tonkmr commented on modules/phase_field/doc/content/modules/phase_field/Grain_Growth_Model.md
> +An example 3D input file is also available:
It actually runs fine on 1 core, which is why I didn't put a minimum. I can give a minimum of 1, but that seemed odd.

2023-09-05 20:20 UTC, tonkmr commented
@laagesen I addressed your comments.

2023-09-05 22:23 UTC, laagesen approved these changes

2023-09-06 15:32 UTC, GiudGiud approved these changes, later dismissed
Thanks for documenting all this! Users will appreciate

2023-09-06 15:34 UTC, GiudGiud approved these changes
just rebased it

2023-09-06 17:59 UTC, merged