Switch optimizer to Adam on 4D GP example in STM
idaholab/moose pull request #25361
Opened 2023-08-30 21:10 UTC by grmnptr

Closes #25360

2023-08-30 21:13 UTC, moosebuild commented on large_media
> +Subproject commit 08357135db54e430770ee8433f5e6e9735e2c931
**Caution!** This contains a submodule update

2023-08-30 21:28 UTC, cticenhour requested changes
One typo fix - will look at rendered doco page too.

2023-08-30 21:28 UTC, cticenhour commented on modules/stochastic_tools/doc/content/modules/stochastic_tools/examples/gaussian_process_surrogate.md
> +To showcase more optimization options available in [GaussianProcessTrainer.md], we used Adam for fitting the lenght scales and signal variance
```suggestion
To showcase more optimization options available in [GaussianProcessTrainer.md], we used Adam for fitting the length scales and signal variance
```

2023-08-30 21:39 UTC, moosebuild commented on large_media
> +Subproject commit 08357135db54e430770ee8433f5e6e9735e2c931
**Caution!** This contains a submodule update

2023-08-30 23:20 UTC, moosebuild commented
Job [Documentation](https://civet.inl.gov/job/1739600/) on 9ff96b3 wanted to post the following:

View the site [here](https://mooseframework.inl.gov/docs/PRs/25361/site)

This comment will be updated on new commits.

2023-08-30 23:49 UTC, moosebuild commented
Job [Coverage](https://civet.inl.gov/job/1739643/) on 9ff96b3 wanted to post the following:


## Framework coverage

Coverage did not change


## Modules coverage

Coverage did not change

## Full coverage reports

<details>
<summary>Reports</summary>

- [`framework`](https://mooseframework.inl.gov/docs/PRs/25361/coverage/framework)
- [`chemical_reactions`](https://mooseframework.inl.gov/docs/PRs/25361/coverage/chemical_reactions)
- [`combined`](https://mooseframework.inl.gov/docs/PRs/25361/coverage/combined)
- [`contact`](https://mooseframework.inl.gov/docs/PRs/25361/coverage/contact)
- [`electromagnetics`](https://mooseframework.inl.gov/docs/PRs/25361/coverage/electromagnetics)
- [`external_petsc_solver`](https://mooseframework.inl.gov/docs/PRs/25361/coverage/external_petsc_solver)
- [`fluid_properties`](https://mooseframework.inl.gov/docs/PRs/25361/coverage/fluid_properties)
- [`fsi`](https://mooseframework.inl.gov/docs/PRs/25361/coverage/fsi)
- [`functional_expansion_tools`](https://mooseframework.inl.gov/docs/PRs/25361/coverage/functional_expansion_tools)
- [`geochemistry`](https://mooseframework.inl.gov/docs/PRs/25361/coverage/geochemistry)
- [`heat_conduction`](https://mooseframework.inl.gov/docs/PRs/25361/coverage/heat_conduction)
- [`level_set`](https://mooseframework.inl.gov/docs/PRs/25361/coverage/level_set)
- [`misc`](https://mooseframework.inl.gov/docs/PRs/25361/coverage/misc)
- [`navier_stokes`](https://mooseframework.inl.gov/docs/PRs/25361/coverage/navier_stokes)
- [`optimization`](https://mooseframework.inl.gov/docs/PRs/25361/coverage/optimization)
- [`peridynamics`](https://mooseframework.inl.gov/docs/PRs/25361/coverage/peridynamics)
- [`phase_field`](https://mooseframework.inl.gov/docs/PRs/25361/coverage/phase_field)
- [`porous_flow`](https://mooseframework.inl.gov/docs/PRs/25361/coverage/porous_flow)
- [`ray_tracing`](https://mooseframework.inl.gov/docs/PRs/25361/coverage/ray_tracing)
- [`rdg`](https://mooseframework.inl.gov/docs/PRs/25361/coverage/rdg)
- [`reactor`](https://mooseframework.inl.gov/docs/PRs/25361/coverage/reactor)
- [`richards`](https://mooseframework.inl.gov/docs/PRs/25361/coverage/richards)
- [`scalar_transport`](https://mooseframework.inl.gov/docs/PRs/25361/coverage/scalar_transport)
- [`solid_properties`](https://mooseframework.inl.gov/docs/PRs/25361/coverage/solid_properties)
- [`stochastic_tools`](https://mooseframework.inl.gov/docs/PRs/25361/coverage/stochastic_tools)
- [`tensor_mechanics`](https://mooseframework.inl.gov/docs/PRs/25361/coverage/tensor_mechanics)
- [`thermal_hydraulics`](https://mooseframework.inl.gov/docs/PRs/25361/coverage/thermal_hydraulics)
- [`xfem`](https://mooseframework.inl.gov/docs/PRs/25361/coverage/xfem)

</details>



This comment will be updated on new commits.

2023-08-31 01:35 UTC, cticenhour approved these changes

2023-08-31 03:21 UTC, somu15 approved these changes
Seems like you have changed to Adam optimization in the example, as we have discussed. Looks good to me.

2023-08-31 14:18 UTC, merged