[WIP ] Add Depletion ID Generation Capability into RGMB
idaholab/moose pull request #25398
Opened 2023-09-04 21:19 UTC by yjung-anl

closes #25396

2023-09-04 21:22 UTC, yjung-anl commented
Working in progress.

2023-09-04 22:59 UTC, moosebuild commented
Job [Documentation](https://civet.inl.gov/job/1748199/) on 4507d66 wanted to post the following:

View the site [here](https://mooseframework.inl.gov/docs/PRs/25398/site)

This comment will be updated on new commits.

2023-09-11 19:52 UTC, NamjaeChoi commented
Will this be available very soon?

2023-11-13 13:11 UTC, yjung-anl commented
@GiudGiud 
If you have the time, could you please review this?

2023-11-13 13:51 UTC, GiudGiud commented
Will do. I m at ANS right now but I ll have time Friday.

2023-11-13 20:55 UTC, moosebuild commented
Job [Coverage](https://civet.inl.gov/job/1880915/) on 67e7738 wanted to post the following:


## Framework coverage

<table>
  <thead>
    <tr>
      <th></th>
      <th>0ce1e2</th>
      <th colspan=4>#25398 67e773</th>
    </tr>
    <tr>
      <th></th>
      <th>Total</th>
      <th>Total</th>
      <th>+/-</th>
      <th>New</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><b>Rate</b></td>
      <td>85.70%</td>
      <td>85.70%</td>
      <td>+0.00%</td>
      <td>-</td>
    </tr>
    <tr>
      <td><b>Hits</b></td>
      <td>92834</td>
      <td>92835</td>
      <td>+1</td>
      <td>0</td>
    </tr>
    <tr>
      <td><b>Misses</b></td>
      <td>15488</td>
      <td>15487</td>
      <td>-1</td>
      <td>0</td>
    </tr>
  </tbody>
</table>

[Diff coverage report](https://mooseframework.inl.gov/docs/PRs/25398/coverage_diff/framework)

[Full coverage report](https://mooseframework.inl.gov/docs/PRs/25398/coverage/framework)


## Modules coverage

### Reactor

<table>
  <thead>
    <tr>
      <th></th>
      <th>0ce1e2</th>
      <th colspan=4>#25398 67e773</th>
    </tr>
    <tr>
      <th></th>
      <th>Total</th>
      <th>Total</th>
      <th>+/-</th>
      <th>New</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><b>Rate</b></td>
      <td>95.78%</td>
      <td>95.68%</td>
      <td>-0.10%</td>
      <td>83.33%</td>
    </tr>
    <tr>
      <td><b>Hits</b></td>
      <td>4920</td>
      <td>4956</td>
      <td>+36</td>
      <td>35</td>
    </tr>
    <tr>
      <td><b>Misses</b></td>
      <td>217</td>
      <td>224</td>
      <td>+7</td>
      <td>7</td>
    </tr>
  </tbody>
</table>

[Diff coverage report](https://mooseframework.inl.gov/docs/PRs/25398/coverage_diff/reactor)

[Full coverage report](https://mooseframework.inl.gov/docs/PRs/25398/coverage/reactor)

## Full coverage reports

<details>
<summary>Reports</summary>

- [`framework`](https://mooseframework.inl.gov/docs/PRs/25398/coverage/framework)
- [`chemical_reactions`](https://mooseframework.inl.gov/docs/PRs/25398/coverage/chemical_reactions)
- [`combined`](https://mooseframework.inl.gov/docs/PRs/25398/coverage/combined)
- [`contact`](https://mooseframework.inl.gov/docs/PRs/25398/coverage/contact)
- [`electromagnetics`](https://mooseframework.inl.gov/docs/PRs/25398/coverage/electromagnetics)
- [`external_petsc_solver`](https://mooseframework.inl.gov/docs/PRs/25398/coverage/external_petsc_solver)
- [`fluid_properties`](https://mooseframework.inl.gov/docs/PRs/25398/coverage/fluid_properties)
- [`fsi`](https://mooseframework.inl.gov/docs/PRs/25398/coverage/fsi)
- [`functional_expansion_tools`](https://mooseframework.inl.gov/docs/PRs/25398/coverage/functional_expansion_tools)
- [`geochemistry`](https://mooseframework.inl.gov/docs/PRs/25398/coverage/geochemistry)
- [`heat_transfer`](https://mooseframework.inl.gov/docs/PRs/25398/coverage/heat_transfer)
- [`level_set`](https://mooseframework.inl.gov/docs/PRs/25398/coverage/level_set)
- [`misc`](https://mooseframework.inl.gov/docs/PRs/25398/coverage/misc)
- [`navier_stokes`](https://mooseframework.inl.gov/docs/PRs/25398/coverage/navier_stokes)
- [`optimization`](https://mooseframework.inl.gov/docs/PRs/25398/coverage/optimization)
- [`peridynamics`](https://mooseframework.inl.gov/docs/PRs/25398/coverage/peridynamics)
- [`phase_field`](https://mooseframework.inl.gov/docs/PRs/25398/coverage/phase_field)
- [`porous_flow`](https://mooseframework.inl.gov/docs/PRs/25398/coverage/porous_flow)
- [`ray_tracing`](https://mooseframework.inl.gov/docs/PRs/25398/coverage/ray_tracing)
- [`rdg`](https://mooseframework.inl.gov/docs/PRs/25398/coverage/rdg)
- [`reactor`](https://mooseframework.inl.gov/docs/PRs/25398/coverage/reactor)
- [`richards`](https://mooseframework.inl.gov/docs/PRs/25398/coverage/richards)
- [`scalar_transport`](https://mooseframework.inl.gov/docs/PRs/25398/coverage/scalar_transport)
- [`solid_properties`](https://mooseframework.inl.gov/docs/PRs/25398/coverage/solid_properties)
- [`stochastic_tools`](https://mooseframework.inl.gov/docs/PRs/25398/coverage/stochastic_tools)
- [`tensor_mechanics`](https://mooseframework.inl.gov/docs/PRs/25398/coverage/tensor_mechanics)
- [`thermal_hydraulics`](https://mooseframework.inl.gov/docs/PRs/25398/coverage/thermal_hydraulics)
- [`xfem`](https://mooseframework.inl.gov/docs/PRs/25398/coverage/xfem)

</details>

## Warnings

- `reactor` new line coverage rate 83.33% is less than the suggested 90.0%



This comment will be updated on new commits.

2023-11-14 13:21 UTC, moosebuild commented
Job [Conda build (ARM Mac)](https://civet.inl.gov/job/1880884/) on 67e7738 : invalidated by @yjung-anl

2023-11-18 00:27 UTC, GiudGiud requested changes

2023-11-18 00:27 UTC, GiudGiud commented on modules/reactor/doc/content/source/meshgenerators/AssemblyMeshGenerator.md
> +All pins in the core have separate depletion ID values by setting [!param](/Mesh/CoreMeshGenerator/depletion_id_type) to `pin`.
```suggestion
All pins in the assembly have separate depletion ID values by setting [!param](/Mesh/CoreMeshGenerator/depletion_id_type) to `pin`.
```

2023-11-18 00:27 UTC, GiudGiud commented on modules/reactor/doc/content/source/meshgenerators/AssemblyMeshGenerator.md
> +The depletion ID generation option can be enabled by setting the  [!param](/Mesh/CoreMeshGenerator/generate_depletion_id) to true.
adapt all parameters this is not the Core

2023-11-18 00:27 UTC, GiudGiud commented on modules/reactor/doc/content/source/meshgenerators/CoreMeshGenerator.md
> +The `CoreMeshGenerator` object optionally assign depletion ID, with the extra integer name "depleiton_id".
```suggestion
The `CoreMeshGenerator` object can optionally assign a depletion ID, with the extra integer name "depletion_id".
```

2023-11-18 00:27 UTC, GiudGiud commented on modules/reactor/src/meshgenerators/ReactorGeometryMeshBuilderBase.C
> +      MooseMeshUtils::getExtraIDUniqueCombinationMap(input_mesh, block_ids, id_names);
document the convention for the ordering of the depltion ids

2023-11-18 00:27 UTC, GiudGiud commented on modules/reactor/src/meshgenerators/ReactorGeometryMeshBuilderBase.C
> +  // prepare list of blocks
do we not have a getter for the list of blocks

2023-11-18 00:27 UTC, GiudGiud commented on modules/reactor/src/meshgenerators/ReactorGeometryMeshBuilderBase.C
> +  // prepare list of blocks
also why are you block-restricting to all blocks? the routine call after will be faster if you pass an empty set (meaning not block-restricted)

2023-11-18 00:27 UTC, GiudGiud commented on modules/reactor/include/meshgenerators/ReactorGeometryMeshBuilderBase.h
> +   * @param extrude whether input mesh is extruded
add a note that says what it does if the mesh is extruded

2023-11-20 15:10 UTC, yjung-anl commented
@GiudGiud  Thank you! I will quickly address your comments.

2023-11-21 19:54 UTC, moosebuild commented
Job [OpenMPI](https://civet.inl.gov/job/1892887/) on 309450d : invalidated by @yjung-anl

2023-11-21 19:55 UTC, yjung-anl commented
@GiudGiud 
Review comments have been addressed.

2023-11-21 22:43 UTC, GiudGiud commented on modules/reactor/src/meshgenerators/ReactorGeometryMeshBuilderBase.C
> +                 "'pin' or 'pin_type' is not allowed in depletion ID generation at assembly level");
do you mean assembly is not allowed?

2023-11-22 15:33 UTC, yjung-anl commented on modules/reactor/src/meshgenerators/ReactorGeometryMeshBuilderBase.C
> +                 "'pin' or 'pin_type' is not allowed in depletion ID generation at assembly level");
Oh it's mistake. Updated as: 
```c++
      paramError("depletion_id_type",
                 "'assembly_id' or 'assembly_type_id' is not allowd in depletion ID generation at "
                 "assembly level");
```

2023-11-22 17:40 UTC, moosebuild commented
All [jobs](https://civet.inl.gov/event/154346/) on acf758c : invalidated by @yjung-anl

2023-11-22 19:01 UTC, GiudGiud approved these changes
Failures unrelated

2023-11-22 19:06 UTC, yjung-anl commented
Thank you!!

2023-11-27 17:19 UTC, moosebuild commented
All [jobs](https://civet.inl.gov/event/154346/) on acf758c : invalidated by @GiudGiud

next fixed

2023-11-27 23:14 UTC, merged

2023-11-27 23:14 UTC, GiudGiud commented
All good thanks for the contribution!