Add JSON UO reader for interaction with json data files from input
idaholab/moose pull request #25568
Opened 2023-09-24 22:45 UTC by GiudGiud

@simopier for the tritium diffusivities I was thinking that

This mirrors the CSV reading capability (though not in those particular functions, that predate the PropertyFileReader format)

@lynnmunday this could be the template for adding the reporter vectors as X Y data like you had for optimization. It would be pretty easy that way

2023-09-25 00:32 UTC, moosebuild commented
Job [Documentation](https://civet.inl.gov/job/1786733/) on bd2cd2a wanted to post the following:

View the site [here](https://mooseframework.inl.gov/docs/PRs/25568/site)

This comment will be updated on new commits.

2023-09-25 04:54 UTC, moosebuild commented
Job [Coverage](https://civet.inl.gov/job/1786928/) on 05c4d13 wanted to post the following:


## Framework coverage

<table>
  <thead>
    <tr>
      <th></th>
      <th>81a54c</th>
      <th colspan=4>#25568 05c4d1</th>
    </tr>
    <tr>
      <th></th>
      <th>Total</th>
      <th>Total</th>
      <th>+/-</th>
      <th>New</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><b>Rate</b></td>
      <td>85.68%</td>
      <td>85.66%</td>
      <td>-0.02%</td>
      <td>71.90%</td>
    </tr>
    <tr>
      <td><b>Hits</b></td>
      <td>91590</td>
      <td>91659</td>
      <td>+69</td>
      <td>87</td>
    </tr>
    <tr>
      <td><b>Misses</b></td>
      <td>15308</td>
      <td>15346</td>
      <td>+38</td>
      <td>34</td>
    </tr>
  </tbody>
</table>

[Diff coverage report](https://mooseframework.inl.gov/docs/PRs/25568/coverage_diff/framework)

[Full coverage report](https://mooseframework.inl.gov/docs/PRs/25568/coverage/framework)


## Modules coverage

Coverage did not change

## Full coverage reports

<details>
<summary>Reports</summary>

- [`framework`](https://mooseframework.inl.gov/docs/PRs/25568/coverage/framework)
- [`chemical_reactions`](https://mooseframework.inl.gov/docs/PRs/25568/coverage/chemical_reactions)
- [`combined`](https://mooseframework.inl.gov/docs/PRs/25568/coverage/combined)
- [`contact`](https://mooseframework.inl.gov/docs/PRs/25568/coverage/contact)
- [`electromagnetics`](https://mooseframework.inl.gov/docs/PRs/25568/coverage/electromagnetics)
- [`external_petsc_solver`](https://mooseframework.inl.gov/docs/PRs/25568/coverage/external_petsc_solver)
- [`fluid_properties`](https://mooseframework.inl.gov/docs/PRs/25568/coverage/fluid_properties)
- [`fsi`](https://mooseframework.inl.gov/docs/PRs/25568/coverage/fsi)
- [`functional_expansion_tools`](https://mooseframework.inl.gov/docs/PRs/25568/coverage/functional_expansion_tools)
- [`geochemistry`](https://mooseframework.inl.gov/docs/PRs/25568/coverage/geochemistry)
- [`heat_conduction`](https://mooseframework.inl.gov/docs/PRs/25568/coverage/heat_conduction)
- [`level_set`](https://mooseframework.inl.gov/docs/PRs/25568/coverage/level_set)
- [`misc`](https://mooseframework.inl.gov/docs/PRs/25568/coverage/misc)
- [`navier_stokes`](https://mooseframework.inl.gov/docs/PRs/25568/coverage/navier_stokes)
- [`optimization`](https://mooseframework.inl.gov/docs/PRs/25568/coverage/optimization)
- [`peridynamics`](https://mooseframework.inl.gov/docs/PRs/25568/coverage/peridynamics)
- [`phase_field`](https://mooseframework.inl.gov/docs/PRs/25568/coverage/phase_field)
- [`porous_flow`](https://mooseframework.inl.gov/docs/PRs/25568/coverage/porous_flow)
- [`ray_tracing`](https://mooseframework.inl.gov/docs/PRs/25568/coverage/ray_tracing)
- [`rdg`](https://mooseframework.inl.gov/docs/PRs/25568/coverage/rdg)
- [`reactor`](https://mooseframework.inl.gov/docs/PRs/25568/coverage/reactor)
- [`richards`](https://mooseframework.inl.gov/docs/PRs/25568/coverage/richards)
- [`scalar_transport`](https://mooseframework.inl.gov/docs/PRs/25568/coverage/scalar_transport)
- [`solid_properties`](https://mooseframework.inl.gov/docs/PRs/25568/coverage/solid_properties)
- [`stochastic_tools`](https://mooseframework.inl.gov/docs/PRs/25568/coverage/stochastic_tools)
- [`tensor_mechanics`](https://mooseframework.inl.gov/docs/PRs/25568/coverage/tensor_mechanics)
- [`thermal_hydraulics`](https://mooseframework.inl.gov/docs/PRs/25568/coverage/thermal_hydraulics)
- [`xfem`](https://mooseframework.inl.gov/docs/PRs/25568/coverage/xfem)

</details>

## Warnings

- `framework` new line coverage rate 71.90% is less than the suggested 90.0%



This comment will be updated on new commits.

2023-09-25 11:40 UTC, GiudGiud commented
Patches are up for 3 apps.

2023-09-25 17:11 UTC, lindsayad requested changes
Can we get more coverage of the `JSONFileReader`?

2023-09-25 18:58 UTC, GiudGiud commented
Good idea. Added a unit test

2023-09-25 20:05 UTC, lindsayad requested changes

2023-09-25 20:05 UTC, lindsayad commented on test/tests/functions/piecewise_constant/tests
> +      detail = 'parameters meant for loading data from JSON are passed for a function loading data differently,'
```suggestion
      detail = 'or if parameters meant for loading data from JSON are passed for a function loading data differently.'
```

2023-09-25 20:05 UTC, lindsayad commented on test/tests/misc/check_error/tests
> +                  "not be parsedfor the Piecewise utility."
```suggestion
                  "not be parsed by a piecewise utility."
```

2023-09-25 20:21 UTC, GiudGiud commented on framework/contrib/json/include/nlohmann/json.h
no I m fixing the docstring because it s not readable

2023-09-25 20:27 UTC, GiudGiud commented on framework/include/functions/PiecewiseTabularBase.h
> +  void buildFromJSON();
it works? we dont want derived classes using these, we're happy with the derived classes using the attributes?

2023-09-25 20:27 UTC, GiudGiud commented on framework/include/userobjects/JSONFileReader.h
> +   * @param scalar_keys the keys in descending order to access the scalar
```suggestion
   * @param scalar_keys the keys in descending order to access the scalar in the JSON tree
```

2023-09-25 20:28 UTC, GiudGiud commented on framework/include/userobjects/JSONFileReader.h
> +   * Get a scalar in the JSON file/tree
```suggestion
   * Get a scalar in the JSON file/tree using the keys in the vector
```

2023-09-25 20:33 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/1788987/) on bee8ccd wanted to post the following:

Your code requires style changes.  

A patch was auto generated and copied [here](https://mooseframework.inl.gov/docs/PRs/25568/clang_format/style.patch)  
You can directly apply the patch by running, in the top level of your repository:

`curl -s https://mooseframework.inl.gov/docs/PRs/25568/clang_format/style.patch | git apply -v`  

Alternatively, with your repository up to date and in the top level of your repository:

`git clang-format 94e06424a4098724b6cb88648d197c3187df9a07`

2023-09-25 20:35 UTC, GiudGiud commented on framework/include/userobjects/JSONFileReader.h
> +  void getScalar(const std::vector<std::string> & scalar_keys, Real & scalar) const;
added more text

2023-09-25 20:45 UTC, GiudGiud commented on framework/include/userobjects/JSONFileReader.h
> +  const FileName _filename;
I get that
```
/Users/giudgl/projects/moose/framework/src/userobjects/JSONFileReader.C:30:46: error: reference member '_filename' binds to a temporary object whose lifetime would be shorter than the lifetime of the constructed object
  : GeneralUserObject(parameters), _filename(getParam<std::string>("filename"))
```

2023-09-25 20:48 UTC, lindsayad commented on framework/include/functions/PiecewiseTabularBase.h
> +  void buildFromJSON();
but that's odd right? Methods help encapsulate data. A user of this class could just toggle `_raw_data_loaded` to false willy/nilly irrespective of what "internal" operations have happened in this class

2023-09-25 20:52 UTC, lindsayad requested changes

2023-09-25 20:52 UTC, lindsayad commented on framework/src/userobjects/JSONFileReader.C
> +  params.addRequiredParam<std::string>("filename", "The path to the file including its name");
```suggestion
  params.addRequiredParam<FileName>("filename", "The path to the file including its name");
```

2023-09-25 20:52 UTC, lindsayad commented on framework/src/userobjects/JSONFileReader.C
> +  : GeneralUserObject(parameters), _filename(getParam<std::string>("filename"))
```suggestion
  : GeneralUserObject(parameters), _filename(getParam<FileName>("filename"))
```

2023-09-25 20:54 UTC, GiudGiud commented on framework/include/functions/PiecewiseTabularBase.h
> +  void buildFromJSON();
but not the same data here.
all the data members here are from the input params, while the build holds the raw arrays

we have protected/private wrong all over MOOSE. We use protected way too much when it s commonly adivsed against
https://softwareengineering.stackexchange.com/questions/162643/why-is-clean-code-suggesting-avoiding-protected-variables

2023-09-25 20:55 UTC, GiudGiud commented on framework/include/functions/PiecewiseTabularBase.h
> +  void buildFromJSON();
but you have a point, that data should just be private. Hopefully changing the old ones wont force me to go fix too much downstream code

2023-09-25 20:59 UTC, GiudGiud commented on framework/include/functions/PiecewiseTabularBase.h
> +  void buildFromJSON();
ok all the others members are used. I moved mine to private as it should

I ll let someone else enforce removing protected data members and add proper getters/setters

2023-09-25 21:00 UTC, GiudGiud commented
ok got it for the conversion creating a temporary

2023-09-25 21:12 UTC, lindsayad commented on framework/include/functions/PiecewiseTabularBase.h
> +  void buildFromJSON();
Did you move it?

2023-09-25 21:14 UTC, GiudGiud commented on framework/include/functions/PiecewiseTabularBase.h
> +  void buildFromJSON();
I think I did?

2023-09-25 21:14 UTC, GiudGiud commented on framework/include/functions/PiecewiseTabularBase.h
> +  void buildFromJSON();
it didnt move!

2023-09-25 21:16 UTC, GiudGiud commented on framework/include/functions/PiecewiseTabularBase.h
> +  void buildFromJSON();
ok should be good now

2023-09-25 21:19 UTC, GiudGiud commented on framework/doc/content/source/userobjects/JSONFileReader.md
> +
last push was fixing this up a little

2023-09-25 21:31 UTC, GiudGiud commented
```
/data/civet1/build/moose/framework/src/functions/PiecewiseLinear.C:28:7: error: '_raw_data_loaded' is a private member of 'PiecewiseTabularBase'
  if (_raw_data_loaded)
```
protected is too nice. 

There could be write-only and read-only access with a few keywords in C++. We should not have to triplicate member - getter - setter

2023-09-25 21:59 UTC, GiudGiud commented
last commit shows the issue with protected quite well though.
we let people access _raw_x, and now we cant stop people from accessing them before the data is actually loaded.

now if they code well within our standards, they should be asserting the size of raw_x to protect themselves, but we cant enforce that

2023-09-25 22:01 UTC, GiudGiud commented
patches are up for all apps now
@joshuahansel  for sockeye: https://github.inl.gov/ncrc/sockeye/pull/727

2023-09-25 23:19 UTC, lindsayad commented
> protected is too nice.
> 
> There could be a read-only 'private' access in C++. It would be nice. We should not have to triplicate member - getter - setter

I totally agree that it can be very convenient to make data protected. It makes writing downstream code much easier, while also making it easier for downstream code to shoot themselves in the foot.

My main point was that having methods private and data protected doesn't make much sense. A downstream class could just reimplement the private method or do whatever they want with the protected data, so declaring the method as `private` in the base class is a farce as far as protecting the base class's state goes.

2023-09-25 23:29 UTC, lindsayad approved these changes

2023-09-27 02:23 UTC, moosebuild commented
Job [Internal app tests](https://civet.inl.gov/job/1789816/) on 1914bf4 : invalidated by @GiudGiud

patch propagated

2023-09-27 14:26 UTC, GiudGiud commented
All patches merged. Thank you for the review!

2023-09-27 14:26 UTC, merged