Add a general sensor postprocessor, #25590
idaholab/moose pull request #25594
Opened 2023-09-26 22:42 UTC by harterj

## Reason
This adds a basic generalized sensor postprocessor, and a thermocouple specific postprocessor. Users may desire to add sensors to multiphysics simulations to probe quantities such as fission power, temperature, pressure, or others. 

## Design
These postprocessors take signal input from another postprocessor, applies a Gaussian distribution to account for noise, also includes sensor delay and drift functions. They are designed to be upgraded in the future when a postdoc from an LDRD takes over.

## Impact
This adds a new feature.

Addresses issue #25590

2023-09-26 22:45 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/1793495/) on ad33559 wanted to post the following:

Your code requires style changes.  

A patch was auto generated and copied [here](https://mooseframework.inl.gov/docs/PRs/25594/clang_format/style.patch)  
You can directly apply the patch by running, in the top level of your repository:

`curl -s https://mooseframework.inl.gov/docs/PRs/25594/clang_format/style.patch | git apply -v`  

Alternatively, with your repository up to date and in the top level of your repository:

`git clang-format e6741bceedf8fad608a2a5d048c2d1fb09afe7c8`

2023-09-27 00:47 UTC, GiudGiud requested changes

2023-09-27 00:47 UTC, GiudGiud commented on framework/doc/content/source/postprocessors/ThermocoupleSensorPostprocessor.md
> +`ThermocoupleSensorPostprocessor` models very specific classes of thermocouples,
I think this belongs in the misc module. 

unless you are using it in a particular application? if so which one?

2023-09-27 00:47 UTC, GiudGiud commented on framework/include/postprocessors/GeneralSensorPostprocessor.h
> + * A generalized sensor Postprocessor
need to be more descriptive than the name

2023-09-27 00:47 UTC, GiudGiud commented on framework/include/postprocessors/ThermocoupleSensorPostprocessor.h
> + * A thermocouple Postprocessor
same comment

2023-09-27 00:47 UTC, GiudGiud commented on framework/src/postprocessors/GeneralSensorPostprocessor.C
> +    return _pp_old;
this doesnt seem right
if dt < delay all the time, the sensor will always be exact

2023-09-27 00:47 UTC, GiudGiud commented on framework/src/postprocessors/ThermocoupleSensorPostprocessor.C
> +                             "thermocouples, described by the 'thermocouple_type' parameter");
```suggestion
  params.addClassDescription("Models various classes of thermocouples defined by a NIST standard");
```

2023-09-27 00:47 UTC, GiudGiud commented on framework/src/postprocessors/ThermocoupleSensorPostprocessor.C
> +      if (pp_value < -543.15 || pp_value > 1273.15)
this hard codes a unit
and
-543.15 is below the absolute 0? what's going on, which unit is this?

2023-10-02 20:44 UTC, snschune commented
Summary from a discussion last week:
1. The noise should be randomly sampled from a Gaussian.
2. Delay will require to store history. 
3. We need to allow "continuous" as in the example of a thermocouple.
4. We should allow the user to specify a response function (preferable as a MOOSE function that is provided to the object).

2024-01-19 05:39 UTC, closed without merging