Update PETSc to 3.20.0
idaholab/moose pull request #25784
Opened 2023-10-19 20:18 UTC by cticenhour

Closes #25783 

CC: @lindsayad

2023-10-19 20:26 UTC, moosebuild commented on petsc
> +Subproject commit 38aca504f6ea08cc814f159b2c9bcf837a5876f3
**Caution!** This contains a submodule update

2023-10-19 20:26 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/1833297/) on ff19687 wanted to post the following:

A change of the following file(s) triggered this check:

  conda/petsc

The following file(s) are unchanged:

  conda/mpich/conda_build_config.yaml

The conda build config was not changed but one or more of its dependencies have changed

2023-10-19 20:26 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/1833297/) on ff19687 wanted to post the following:

A change of the following file(s) triggered this check:

  petsc

The following file(s) are unchanged:

  conda/mpich/conda_build_config.yaml

The PETSc submodule or configuration was changed but the conda build config was not

2023-10-19 20:26 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/1833297/) on ff19687 wanted to post the following:

The following file(s) are changed:

  conda/petsc/meta.yaml

The PETSc conda configuration has changed; ping @idaholab/moose-dev-ops

2023-10-19 20:26 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/1833297/) on ff19687 wanted to post the following:

The following file(s) are changed:

  conda/libmesh/meta.yaml

The libmesh conda configuration has changed; ping @idaholab/moose-dev-ops

2023-10-19 21:24 UTC, cticenhour commented
@loganharbour Looks like we'll need to get CMake 3.21.0 on the containers: https://civet.inl.gov/job/1833298/

2023-10-19 21:26 UTC, loganharbour commented
Just add `--download-cmake` to https://github.com/idaholab/moose/blob/1a588bd572fde1c4849fd6e1deb1bd2b67021e8c/apptainer/petsc.def#L67.

cmake comes from RHEL and we only get the current stable version for rocky 8.6 at the moment

2023-10-19 21:39 UTC, moosebuild commented on petsc
> +Subproject commit 38aca504f6ea08cc814f159b2c9bcf837a5876f3
**Caution!** This contains a submodule update

2023-10-19 21:39 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/1833428/) on 7a3cb65 wanted to post the following:

A change of the following file(s) triggered this check:

  conda/petsc

The following file(s) are unchanged:

  conda/mpich/conda_build_config.yaml

The conda build config was not changed but one or more of its dependencies have changed

2023-10-19 21:39 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/1833428/) on 7a3cb65 wanted to post the following:

A change of the following file(s) triggered this check:

  petsc

The following file(s) are unchanged:

  conda/mpich/conda_build_config.yaml

The PETSc submodule or configuration was changed but the conda build config was not

2023-10-19 21:39 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/1833428/) on 7a3cb65 wanted to post the following:

The following file(s) are changed:

  conda/petsc/meta.yaml

The PETSc conda configuration has changed; ping @idaholab/moose-dev-ops

2023-10-19 21:39 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/1833428/) on 7a3cb65 wanted to post the following:

The following file(s) are changed:

  conda/libmesh/meta.yaml

The libmesh conda configuration has changed; ping @idaholab/moose-dev-ops

2023-10-20 18:07 UTC, moosebuild commented on petsc
> +Subproject commit 38aca504f6ea08cc814f159b2c9bcf837a5876f3
**Caution!** This contains a submodule update

2023-10-20 18:07 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/1833895/) on dbae3a9 wanted to post the following:

A change of the following file(s) triggered this check:

  conda/petsc

The following file(s) are unchanged:

  conda/mpich/conda_build_config.yaml

The conda build config was not changed but one or more of its dependencies have changed

2023-10-20 18:07 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/1833895/) on dbae3a9 wanted to post the following:

A change of the following file(s) triggered this check:

  petsc

The following file(s) are unchanged:

  conda/mpich/conda_build_config.yaml

The PETSc submodule or configuration was changed but the conda build config was not

2023-10-20 18:07 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/1833895/) on dbae3a9 wanted to post the following:

The following file(s) are changed:

  conda/petsc/meta.yaml

The PETSc conda configuration has changed; ping @idaholab/moose-dev-ops

2023-10-20 18:07 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/1833895/) on dbae3a9 wanted to post the following:

The following file(s) are changed:

  conda/libmesh/meta.yaml

The libmesh conda configuration has changed; ping @idaholab/moose-dev-ops

2023-10-20 22:19 UTC, moosebuild commented
Job [Documentation](https://civet.inl.gov/job/1833917/) on dbae3a9 wanted to post the following:

View the site [here](https://mooseframework.inl.gov/docs/PRs/25784/site)

This comment will be updated on new commits.

2023-10-22 22:03 UTC, moosebuild commented
Job [Test timings](https://civet.inl.gov/job/1835594/) on dbae3a9 wanted to post the following:

View timings [here](https://mooseframework.inl.gov/docs/PRs/25784/timing)

This comment will be updated on new commits.

2023-10-22 23:43 UTC, moosebuild commented
Job [Coverage](https://civet.inl.gov/job/1833935/) on dbae3a9 wanted to post the following:


## Framework coverage

<table>
  <thead>
    <tr>
      <th></th>
      <th>3d2af0</th>
      <th colspan=4>#25784 dbae3a</th>
    </tr>
    <tr>
      <th></th>
      <th>Total</th>
      <th>Total</th>
      <th>+/-</th>
      <th>New</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><b>Rate</b></td>
      <td>85.63%</td>
      <td>85.64%</td>
      <td>+0.01%</td>
      <td>-</td>
    </tr>
    <tr>
      <td><b>Hits</b></td>
      <td>92355</td>
      <td>92368</td>
      <td>+13</td>
      <td>0</td>
    </tr>
    <tr>
      <td><b>Misses</b></td>
      <td>15498</td>
      <td>15485</td>
      <td>-13</td>
      <td>0</td>
    </tr>
  </tbody>
</table>

[Diff coverage report](https://mooseframework.inl.gov/docs/PRs/25784/coverage_diff/framework)

[Full coverage report](https://mooseframework.inl.gov/docs/PRs/25784/coverage/framework)


## Modules coverage

Coverage did not change

## Full coverage reports

<details>
<summary>Reports</summary>

- [`framework`](https://mooseframework.inl.gov/docs/PRs/25784/coverage/framework)
- [`chemical_reactions`](https://mooseframework.inl.gov/docs/PRs/25784/coverage/chemical_reactions)
- [`combined`](https://mooseframework.inl.gov/docs/PRs/25784/coverage/combined)
- [`contact`](https://mooseframework.inl.gov/docs/PRs/25784/coverage/contact)
- [`electromagnetics`](https://mooseframework.inl.gov/docs/PRs/25784/coverage/electromagnetics)
- [`external_petsc_solver`](https://mooseframework.inl.gov/docs/PRs/25784/coverage/external_petsc_solver)
- [`fluid_properties`](https://mooseframework.inl.gov/docs/PRs/25784/coverage/fluid_properties)
- [`fsi`](https://mooseframework.inl.gov/docs/PRs/25784/coverage/fsi)
- [`functional_expansion_tools`](https://mooseframework.inl.gov/docs/PRs/25784/coverage/functional_expansion_tools)
- [`geochemistry`](https://mooseframework.inl.gov/docs/PRs/25784/coverage/geochemistry)
- [`heat_transfer`](https://mooseframework.inl.gov/docs/PRs/25784/coverage/heat_transfer)
- [`level_set`](https://mooseframework.inl.gov/docs/PRs/25784/coverage/level_set)
- [`misc`](https://mooseframework.inl.gov/docs/PRs/25784/coverage/misc)
- [`navier_stokes`](https://mooseframework.inl.gov/docs/PRs/25784/coverage/navier_stokes)
- [`optimization`](https://mooseframework.inl.gov/docs/PRs/25784/coverage/optimization)
- [`peridynamics`](https://mooseframework.inl.gov/docs/PRs/25784/coverage/peridynamics)
- [`phase_field`](https://mooseframework.inl.gov/docs/PRs/25784/coverage/phase_field)
- [`porous_flow`](https://mooseframework.inl.gov/docs/PRs/25784/coverage/porous_flow)
- [`ray_tracing`](https://mooseframework.inl.gov/docs/PRs/25784/coverage/ray_tracing)
- [`rdg`](https://mooseframework.inl.gov/docs/PRs/25784/coverage/rdg)
- [`reactor`](https://mooseframework.inl.gov/docs/PRs/25784/coverage/reactor)
- [`richards`](https://mooseframework.inl.gov/docs/PRs/25784/coverage/richards)
- [`scalar_transport`](https://mooseframework.inl.gov/docs/PRs/25784/coverage/scalar_transport)
- [`solid_properties`](https://mooseframework.inl.gov/docs/PRs/25784/coverage/solid_properties)
- [`stochastic_tools`](https://mooseframework.inl.gov/docs/PRs/25784/coverage/stochastic_tools)
- [`tensor_mechanics`](https://mooseframework.inl.gov/docs/PRs/25784/coverage/tensor_mechanics)
- [`thermal_hydraulics`](https://mooseframework.inl.gov/docs/PRs/25784/coverage/thermal_hydraulics)
- [`xfem`](https://mooseframework.inl.gov/docs/PRs/25784/coverage/xfem)

</details>



This comment will be updated on new commits.

2023-10-23 01:29 UTC, loganharbour commented
These two diffs are new:

```
[53.93s]     DIFF mortar/continuity-3d-non-conforming.continuity_penalty_sphere_hex20 FAILED (EXODIFF) [FINISHED]
[56.86s]     DIFF mortar/continuity-3d-non-conforming.continuity_penalty_sphere_hex20_ad FAILED (EXODIFF) [FINISHED]
```

see https://civet.inl.gov/job/1835600/.

Mind helping @lindsayad or @recuero?

2023-10-23 03:04 UTC, loganharbour requested changes
Reminder for myself to finalize the 32bit container build and recipes before this gets in.

2023-10-23 03:40 UTC, lindsayad commented
> Mind helping @lindsayad or @recuero?

yea no problem

2023-10-23 03:41 UTC, loganharbour commented
Thanks. Feel free to push directly if you end up with a fix

On Sun, Oct 22, 2023 at 9:40 PM Alex Lindsay ***@***.***>
wrote:

> Mind helping @lindsayad <https://github.com/lindsayad> or @recuero
> <https://github.com/recuero>?
>
> yea no problem
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/idaholab/moose/pull/25784#issuecomment-1774381856>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AFIKINJEZGCAJJCRTOZQC5DYAXRLRAVCNFSM6AAAAAA6HZBERCVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMYTONZUGM4DCOBVGY>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2023-10-23 04:27 UTC, moosebuild commented on petsc
> +Subproject commit 38aca504f6ea08cc814f159b2c9bcf837a5876f3
**Caution!** This contains a submodule update

2023-10-23 04:27 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/1835953/) on 9ed0d18 wanted to post the following:

A change of the following file(s) triggered this check:

  conda/petsc

The following file(s) are unchanged:

  conda/mpich/conda_build_config.yaml

The conda build config was not changed but one or more of its dependencies have changed

2023-10-23 04:27 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/1835953/) on 9ed0d18 wanted to post the following:

A change of the following file(s) triggered this check:

  petsc

The following file(s) are unchanged:

  conda/mpich/conda_build_config.yaml

The PETSc submodule or configuration was changed but the conda build config was not

2023-10-23 04:27 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/1835953/) on 9ed0d18 wanted to post the following:

The following file(s) are changed:

  conda/petsc/meta.yaml

The PETSc conda configuration has changed; ping @idaholab/moose-dev-ops

2023-10-23 04:27 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/1835953/) on 9ed0d18 wanted to post the following:

The following file(s) are changed:

  conda/libmesh/meta.yaml

The libmesh conda configuration has changed; ping @idaholab/moose-dev-ops

2023-10-23 14:00 UTC, loganharbour submitted a review, later dismissed

2023-10-23 14:03 UTC, milljm commented on conda/libmesh/conda_build_config.yaml
> +  - moose-petsc 3.20.0 build_0
Ahhh... thats better!

2023-10-23 14:07 UTC, milljm submitted a review, later dismissed
This looks good! While we dropped moose-test-tools, which does affect moose-dev in a way, I think we're good to go as far as conda package dependencies roll.

2023-10-23 15:12 UTC, milljm submitted a review, later dismissed

2023-10-23 15:14 UTC, roystgnr commented
> sanity check on the skips in https://github.com/idaholab/moose/pull/25784 please; Jason will review the rest

The "[Limit IGA tests to 64bit dof indices](https://github.com/idaholab/moose/pull/25784/commits/ce1df363ff4ae60456b53eba475583def8cd4f3c)" commit has the flaw that it stabs to the core of my soul with a knife made of white-hot shame ... but engineering-wise it's probably the best we can do on short notice.  The updated CI here is exposing a preexisting bug, not adding a new one.

2023-10-23 15:15 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/1837014/) on ce1df36 wanted to post the following:

A change of the following file(s) triggered this check:

  conda/petsc

The following file(s) are unchanged:

  conda/mpich/conda_build_config.yaml

The conda build config was not changed but one or more of its dependencies have changed

2023-10-23 15:15 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/1837014/) on ce1df36 wanted to post the following:

A change of the following file(s) triggered this check:

  petsc

The following file(s) are unchanged:

  conda/mpich/conda_build_config.yaml

The PETSc submodule or configuration was changed but the conda build config was not

2023-10-23 15:16 UTC, loganharbour commented
> it stabs to the core of my soul with a knife made of white-hot shame 

![controlling-laugh-laughing](https://github.com/idaholab/moose/assets/22062133/4bf24953-022d-4b10-9039-0a93668cf3d7)

2023-10-23 19:38 UTC, moosebuild commented on petsc
> +Subproject commit 38aca504f6ea08cc814f159b2c9bcf837a5876f3
**Caution!** This contains a submodule update

2023-10-23 19:38 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/1837479/) on bcc9e12 wanted to post the following:

A change of the following file(s) triggered this check:

  conda/petsc

The following file(s) are unchanged:

  conda/mpich/conda_build_config.yaml

The conda build config was not changed but one or more of its dependencies have changed

2023-10-23 19:38 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/1837479/) on bcc9e12 wanted to post the following:

A change of the following file(s) triggered this check:

  petsc

The following file(s) are unchanged:

  conda/mpich/conda_build_config.yaml

The PETSc submodule or configuration was changed but the conda build config was not

2023-10-23 19:38 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/1837479/) on bcc9e12 wanted to post the following:

The following file(s) are changed:

  conda/petsc/meta.yaml

The PETSc conda configuration has changed; ping @idaholab/moose-dev-ops

2023-10-23 19:38 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/1837479/) on bcc9e12 wanted to post the following:

The following file(s) are changed:

  conda/libmesh/meta.yaml

The libmesh conda configuration has changed; ping @idaholab/moose-dev-ops

2023-10-23 19:50 UTC, moosebuild commented on petsc
> +Subproject commit 38aca504f6ea08cc814f159b2c9bcf837a5876f3
**Caution!** This contains a submodule update

2023-10-23 19:50 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/1837577/) on 66b5e9a wanted to post the following:

A change of the following file(s) triggered this check:

  conda/petsc

The following file(s) are unchanged:

  conda/mpich/conda_build_config.yaml

The conda build config was not changed but one or more of its dependencies have changed

2023-10-23 19:50 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/1837577/) on 66b5e9a wanted to post the following:

A change of the following file(s) triggered this check:

  petsc

The following file(s) are unchanged:

  conda/mpich/conda_build_config.yaml

The PETSc submodule or configuration was changed but the conda build config was not

2023-10-23 19:50 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/1837577/) on 66b5e9a wanted to post the following:

The following file(s) are changed:

  conda/petsc/meta.yaml

The PETSc conda configuration has changed; ping @idaholab/moose-dev-ops

2023-10-23 19:50 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/1837577/) on 66b5e9a wanted to post the following:

The following file(s) are changed:

  conda/libmesh/meta.yaml

The libmesh conda configuration has changed; ping @idaholab/moose-dev-ops

2023-10-23 19:53 UTC, milljm approved these changes, later dismissed
🎉

2023-10-23 19:57 UTC, moosebuild commented on petsc
> +Subproject commit 38aca504f6ea08cc814f159b2c9bcf837a5876f3
**Caution!** This contains a submodule update

2023-10-23 19:57 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/1837675/) on 1428b33 wanted to post the following:

A change of the following file(s) triggered this check:

  conda/petsc

The following file(s) are unchanged:

  conda/mpich/conda_build_config.yaml

The conda build config was not changed but one or more of its dependencies have changed

2023-10-23 19:57 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/1837675/) on 1428b33 wanted to post the following:

A change of the following file(s) triggered this check:

  petsc

The following file(s) are unchanged:

  conda/mpich/conda_build_config.yaml

The PETSc submodule or configuration was changed but the conda build config was not

2023-10-23 19:57 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/1837675/) on 1428b33 wanted to post the following:

The following file(s) are changed:

  conda/petsc/meta.yaml

The PETSc conda configuration has changed; ping @idaholab/moose-dev-ops

2023-10-23 19:57 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/1837675/) on 1428b33 wanted to post the following:

The following file(s) are changed:

  conda/libmesh/meta.yaml

The libmesh conda configuration has changed; ping @idaholab/moose-dev-ops

2023-10-23 21:12 UTC, moosebuild commented on petsc
> +Subproject commit 38aca504f6ea08cc814f159b2c9bcf837a5876f3
**Caution!** This contains a submodule update

2023-10-23 21:12 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/1837950/) on 4f0a19c wanted to post the following:

A change of the following file(s) triggered this check:

  conda/petsc

The following file(s) are unchanged:

  conda/mpich/conda_build_config.yaml

The conda build config was not changed but one or more of its dependencies have changed

2023-10-23 21:12 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/1837950/) on 4f0a19c wanted to post the following:

The following file(s) are changed:

  conda/petsc/meta.yaml

The PETSc conda configuration has changed; ping @idaholab/moose-dev-ops

2023-10-23 21:13 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/1837950/) on 4f0a19c wanted to post the following:

The following file(s) are changed:

  conda/libmesh/meta.yaml

The libmesh conda configuration has changed; ping @idaholab/moose-dev-ops

2023-10-23 21:37 UTC, lindsayad approved these changes

2023-10-24 12:25 UTC, merged