Optimization Module Top Opt Docs
idaholab/moose pull request #25869
Opened 2023-10-26 18:33 UTC by maxnezdyur

Closes #25866
Adds more documentation and examples of topology optimization for visibility.

2023-10-26 18:33 UTC, maxnezdyur commented
@lynnmunday

2023-10-26 20:17 UTC, moosebuild commented
Job [Documentation](https://civet.inl.gov/job/1845710/) on bc7ce06 wanted to post the following:

View the site [here](https://mooseframework.inl.gov/docs/PRs/25869/site)

This comment will be updated on new commits.

2023-10-26 21:43 UTC, lynnmunday requested changes
All these markdown files are already included in the combined module/examples page 
https://mooseframework.inl.gov/modules/combined/index.html
Can you delete these md files and just create links to the combined module examples from the optimization/examples/index.md. 
Make sure to add the correct figure to the combined module example write-ups like you have here..  I like the click-able movies to the examples page.

2023-10-26 21:43 UTC, lynnmunday commented on modules/optimization/doc/content/modules/optimization/examples/top_opt_main.md
> +!card! large_media/optimization/2d_mbb_pde_amr.png title=[2D Topology Optimization with PDE Filter and Adaptive Mesh Refinement](2d_mbb_pde_amr.md)
```suggestion
!card! large_media/optimization/2d_mbb_pde_amr.png title=[2D Topology Optimization with PDE Filter and Adaptive Mesh Refinement](examples/2d_mbb_pde_amr.md)
```

2023-10-26 21:43 UTC, lynnmunday commented on modules/optimization/doc/content/modules/optimization/examples/top_opt_main.md
> +!card! large_media/optimization/2d_mbb_pde.mp4 title=[2D Topology Optimization with PDE Filter and Boundary Penalty](2d_mbb_pde.md)
```suggestion
!card! large_media/optimization/2d_mbb_pde.mp4 title=[2D Topology Optimization with PDE Filter and Boundary Penalty](examples/2d_mbb_pde.md)
```

2023-10-26 21:43 UTC, lynnmunday commented on modules/optimization/doc/content/modules/optimization/examples/top_opt_main.md
> +!card! large_media/optimization/2d_mbb.mp4 title=[2D Topology Optimization with Radial Average Filter](2d_mbb.md)
```suggestion
!card! large_media/optimization/2d_mbb.mp4 title=[2D Topology Optimization with Radial Average Filter](examples/2d_mbb.md)
```

2023-10-26 21:43 UTC, lynnmunday commented on modules/optimization/doc/content/modules/optimization/examples/2d_mbb_pde.md
> +# 2D MBB Beam with a PDE Filter
delete this md file and just make a link on the index.md page to the version in the combined/examples.  Also add links in optimization/examples/index.md to the other examples in the combined app that Antonio added like the multi-material and multi-physics examples.  Also add the correct figure to the combined module write-ups that you have here.

2023-10-26 21:44 UTC, lynnmunday commented on modules/optimization/doc/content/modules/optimization/examples/top_opt_main.md
> +!card! large_media/optimization/2d_mbb.mp4 title=[2D Topology Optimization with Radial Average Filter](2d_mbb.md)
I think this will fix the documentation build fail

2023-10-30 15:20 UTC, lynnmunday commented on modules/optimization/doc/content/modules/optimization/examples/topology_optimization/multimaterial.md
Will you add these as links from the main topology examples page too with pictures like you did with the others?

2023-10-31 03:58 UTC, lynnmunday approved these changes

2023-10-31 11:48 UTC, GiudGiud approved these changes

2023-11-02 16:38 UTC, merged