Dont trust the problem for the dimension in NS Rhie Chow User Object
idaholab/moose pull request #25937
Opened 2023-11-01 20:14 UTC by GiudGiud

- on components, problem says 3D even for 2D closes #25936

Be more safe on retrieving the max dimension from the BlockRestrictable interface

## Reason

## Design

## Impact

2023-11-01 21:57 UTC, moosebuild commented
Job [Documentation](https://civet.inl.gov/job/1857480/) on 0e31361 wanted to post the following:

View the site [here](https://mooseframework.inl.gov/docs/PRs/25937/site)

This comment will be updated on new commits.

2023-11-01 22:36 UTC, moosebuild commented
Job [Coverage](https://civet.inl.gov/job/1857498/) on 0e31361 wanted to post the following:


## Framework coverage

<table>
  <thead>
    <tr>
      <th></th>
      <th>191b9d</th>
      <th colspan=4>#25937 0e3136</th>
    </tr>
    <tr>
      <th></th>
      <th>Total</th>
      <th>Total</th>
      <th>+/-</th>
      <th>New</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><b>Rate</b></td>
      <td>85.63%</td>
      <td>85.63%</td>
      <td>+0.00%</td>
      <td>50.00%</td>
    </tr>
    <tr>
      <td><b>Hits</b></td>
      <td>92451</td>
      <td>92453</td>
      <td>+2</td>
      <td>2</td>
    </tr>
    <tr>
      <td><b>Misses</b></td>
      <td>15509</td>
      <td>15509</td>
      <td>-</td>
      <td>2</td>
    </tr>
  </tbody>
</table>

[Diff coverage report](https://mooseframework.inl.gov/docs/PRs/25937/coverage_diff/framework)

[Full coverage report](https://mooseframework.inl.gov/docs/PRs/25937/coverage/framework)


## Modules coverage

### Navier stokes

<table>
  <thead>
    <tr>
      <th></th>
      <th>191b9d</th>
      <th colspan=4>#25937 0e3136</th>
    </tr>
    <tr>
      <th></th>
      <th>Total</th>
      <th>Total</th>
      <th>+/-</th>
      <th>New</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><b>Rate</b></td>
      <td>84.77%</td>
      <td>84.77%</td>
      <td>-</td>
      <td>100.00%</td>
    </tr>
    <tr>
      <td><b>Hits</b></td>
      <td>12548</td>
      <td>12548</td>
      <td>-</td>
      <td>1</td>
    </tr>
    <tr>
      <td><b>Misses</b></td>
      <td>2255</td>
      <td>2255</td>
      <td>-</td>
      <td>0</td>
    </tr>
  </tbody>
</table>

[Diff coverage report](https://mooseframework.inl.gov/docs/PRs/25937/coverage_diff/navier_stokes)

[Full coverage report](https://mooseframework.inl.gov/docs/PRs/25937/coverage/navier_stokes)

## Full coverage reports

<details>
<summary>Reports</summary>

- [`framework`](https://mooseframework.inl.gov/docs/PRs/25937/coverage/framework)
- [`chemical_reactions`](https://mooseframework.inl.gov/docs/PRs/25937/coverage/chemical_reactions)
- [`combined`](https://mooseframework.inl.gov/docs/PRs/25937/coverage/combined)
- [`contact`](https://mooseframework.inl.gov/docs/PRs/25937/coverage/contact)
- [`electromagnetics`](https://mooseframework.inl.gov/docs/PRs/25937/coverage/electromagnetics)
- [`external_petsc_solver`](https://mooseframework.inl.gov/docs/PRs/25937/coverage/external_petsc_solver)
- [`fluid_properties`](https://mooseframework.inl.gov/docs/PRs/25937/coverage/fluid_properties)
- [`fsi`](https://mooseframework.inl.gov/docs/PRs/25937/coverage/fsi)
- [`functional_expansion_tools`](https://mooseframework.inl.gov/docs/PRs/25937/coverage/functional_expansion_tools)
- [`geochemistry`](https://mooseframework.inl.gov/docs/PRs/25937/coverage/geochemistry)
- [`heat_transfer`](https://mooseframework.inl.gov/docs/PRs/25937/coverage/heat_transfer)
- [`level_set`](https://mooseframework.inl.gov/docs/PRs/25937/coverage/level_set)
- [`misc`](https://mooseframework.inl.gov/docs/PRs/25937/coverage/misc)
- [`navier_stokes`](https://mooseframework.inl.gov/docs/PRs/25937/coverage/navier_stokes)
- [`optimization`](https://mooseframework.inl.gov/docs/PRs/25937/coverage/optimization)
- [`peridynamics`](https://mooseframework.inl.gov/docs/PRs/25937/coverage/peridynamics)
- [`phase_field`](https://mooseframework.inl.gov/docs/PRs/25937/coverage/phase_field)
- [`porous_flow`](https://mooseframework.inl.gov/docs/PRs/25937/coverage/porous_flow)
- [`ray_tracing`](https://mooseframework.inl.gov/docs/PRs/25937/coverage/ray_tracing)
- [`rdg`](https://mooseframework.inl.gov/docs/PRs/25937/coverage/rdg)
- [`reactor`](https://mooseframework.inl.gov/docs/PRs/25937/coverage/reactor)
- [`richards`](https://mooseframework.inl.gov/docs/PRs/25937/coverage/richards)
- [`scalar_transport`](https://mooseframework.inl.gov/docs/PRs/25937/coverage/scalar_transport)
- [`solid_properties`](https://mooseframework.inl.gov/docs/PRs/25937/coverage/solid_properties)
- [`stochastic_tools`](https://mooseframework.inl.gov/docs/PRs/25937/coverage/stochastic_tools)
- [`tensor_mechanics`](https://mooseframework.inl.gov/docs/PRs/25937/coverage/tensor_mechanics)
- [`thermal_hydraulics`](https://mooseframework.inl.gov/docs/PRs/25937/coverage/thermal_hydraulics)
- [`xfem`](https://mooseframework.inl.gov/docs/PRs/25937/coverage/xfem)

</details>

## Warnings

- `framework` new line coverage rate 50.00% is less than the suggested 90.0%



This comment will be updated on new commits.

2023-11-02 21:38 UTC, lindsayad requested changes

2023-11-02 21:38 UTC, lindsayad commented on framework/include/interfaces/BlockRestrictable.h
> +  unsigned int blocksMaxDimension() const
move out of the class definition

2023-11-02 21:38 UTC, lindsayad commented on framework/include/interfaces/BlockRestrictable.h
> +    mooseAssert(_blk_dim != std::numeric_limits<unsigned int>::max(),
```suggestion
    mooseAssert(_blk_dim != libMesh::invalid_uint,
```

2023-11-02 21:38 UTC, lindsayad commented on framework/src/interfaces/BlockRestrictable.C
> +    _blk_dim(std::numeric_limits<unsigned int>::max())
```suggestion
    _blk_dim(libMesh::invalid_uint)
```

2023-11-02 21:38 UTC, lindsayad commented on framework/src/interfaces/BlockRestrictable.C
> +    _blk_dim(std::numeric_limits<unsigned int>::max())
```suggestion
    _blk_dim(libMesh::invalid_uint)
```

2023-11-02 21:43 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/1861449/) on 1be1324 wanted to post the following:

Your code requires style changes.  

A patch was auto generated and copied [here](https://mooseframework.inl.gov/docs/PRs/25937/clang_format/style.patch)  
You can directly apply the patch by running, in the top level of your repository:

`curl -s https://mooseframework.inl.gov/docs/PRs/25937/clang_format/style.patch | git apply -v`  

Alternatively, with your repository up to date and in the top level of your repository:

`git clang-format 191b9de91d4081667f32371afdeb531d9f0821e2`

2023-11-02 21:43 UTC, lindsayad approved these changes

2023-11-02 21:43 UTC, GiudGiud commented on framework/include/interfaces/BlockRestrictable.h
> +  unsigned int blocksMaxDimension() const
done

2023-11-03 00:42 UTC, merged