Small changes in Actions
idaholab/moose pull request #25971
Opened 2023-11-05 23:40 UTC by GiudGiud

Aside from the boundary integration / value functors which are using for connecting components and arent needed right away, this might be all I can extract from the Physics PR without actually introducing Physics

2023-11-06 01:26 UTC, moosebuild commented
Job [Documentation](https://civet.inl.gov/job/1864295/) on 21688df wanted to post the following:

View the site [here](https://mooseframework.inl.gov/docs/PRs/25971/site)

This comment will be updated on new commits.

2023-11-06 01:32 UTC, moosebuild commented
Job [Coverage](https://civet.inl.gov/job/1864313/) on 21688df wanted to post the following:


## Framework coverage

<table>
  <thead>
    <tr>
      <th></th>
      <th>b28019</th>
      <th colspan=4>#25971 21688d</th>
    </tr>
    <tr>
      <th></th>
      <th>Total</th>
      <th>Total</th>
      <th>+/-</th>
      <th>New</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><b>Rate</b></td>
      <td>85.67%</td>
      <td>85.67%</td>
      <td>-0.01%</td>
      <td>0.00%</td>
    </tr>
    <tr>
      <td><b>Hits</b></td>
      <td>92534</td>
      <td>92530</td>
      <td>-4</td>
      <td>0</td>
    </tr>
    <tr>
      <td><b>Misses</b></td>
      <td>15474</td>
      <td>15483</td>
      <td>+9</td>
      <td>6</td>
    </tr>
  </tbody>
</table>

[Diff coverage report](https://mooseframework.inl.gov/docs/PRs/25971/coverage_diff/framework)

[Full coverage report](https://mooseframework.inl.gov/docs/PRs/25971/coverage/framework)


## Modules coverage

Coverage did not change

## Full coverage reports

<details>
<summary>Reports</summary>

- [`framework`](https://mooseframework.inl.gov/docs/PRs/25971/coverage/framework)
- [`chemical_reactions`](https://mooseframework.inl.gov/docs/PRs/25971/coverage/chemical_reactions)
- [`combined`](https://mooseframework.inl.gov/docs/PRs/25971/coverage/combined)
- [`contact`](https://mooseframework.inl.gov/docs/PRs/25971/coverage/contact)
- [`electromagnetics`](https://mooseframework.inl.gov/docs/PRs/25971/coverage/electromagnetics)
- [`external_petsc_solver`](https://mooseframework.inl.gov/docs/PRs/25971/coverage/external_petsc_solver)
- [`fluid_properties`](https://mooseframework.inl.gov/docs/PRs/25971/coverage/fluid_properties)
- [`fsi`](https://mooseframework.inl.gov/docs/PRs/25971/coverage/fsi)
- [`functional_expansion_tools`](https://mooseframework.inl.gov/docs/PRs/25971/coverage/functional_expansion_tools)
- [`geochemistry`](https://mooseframework.inl.gov/docs/PRs/25971/coverage/geochemistry)
- [`heat_transfer`](https://mooseframework.inl.gov/docs/PRs/25971/coverage/heat_transfer)
- [`level_set`](https://mooseframework.inl.gov/docs/PRs/25971/coverage/level_set)
- [`misc`](https://mooseframework.inl.gov/docs/PRs/25971/coverage/misc)
- [`navier_stokes`](https://mooseframework.inl.gov/docs/PRs/25971/coverage/navier_stokes)
- [`optimization`](https://mooseframework.inl.gov/docs/PRs/25971/coverage/optimization)
- [`peridynamics`](https://mooseframework.inl.gov/docs/PRs/25971/coverage/peridynamics)
- [`phase_field`](https://mooseframework.inl.gov/docs/PRs/25971/coverage/phase_field)
- [`porous_flow`](https://mooseframework.inl.gov/docs/PRs/25971/coverage/porous_flow)
- [`ray_tracing`](https://mooseframework.inl.gov/docs/PRs/25971/coverage/ray_tracing)
- [`rdg`](https://mooseframework.inl.gov/docs/PRs/25971/coverage/rdg)
- [`reactor`](https://mooseframework.inl.gov/docs/PRs/25971/coverage/reactor)
- [`richards`](https://mooseframework.inl.gov/docs/PRs/25971/coverage/richards)
- [`scalar_transport`](https://mooseframework.inl.gov/docs/PRs/25971/coverage/scalar_transport)
- [`solid_properties`](https://mooseframework.inl.gov/docs/PRs/25971/coverage/solid_properties)
- [`stochastic_tools`](https://mooseframework.inl.gov/docs/PRs/25971/coverage/stochastic_tools)
- [`tensor_mechanics`](https://mooseframework.inl.gov/docs/PRs/25971/coverage/tensor_mechanics)
- [`thermal_hydraulics`](https://mooseframework.inl.gov/docs/PRs/25971/coverage/thermal_hydraulics)
- [`xfem`](https://mooseframework.inl.gov/docs/PRs/25971/coverage/xfem)

</details>

## Warnings

- `framework` new line coverage rate 0.00% is less than the suggested 90.0%



This comment will be updated on new commits.

2023-11-06 18:32 UTC, lindsayad commented on framework/include/actions/ActionWarehouse.h
> +      mooseError("Action with name being ",
```suggestion
      mooseError("Action with name '",
```

2023-11-06 18:32 UTC, lindsayad commented on framework/include/actions/ActionWarehouse.h
> +                 " does not exist.\n Actions that do exist:",
```suggestion
                 "' does not exist.\n These are the Actions that do exist:",
```

2023-11-06 18:32 UTC, lindsayad commented on framework/include/actions/Action.h
> +  }
Inline in the header but outside of the class definition would be my preference but as there are many other methods like this currently, it's not a requirement

2023-11-06 19:06 UTC, lindsayad requested changes

2023-11-06 19:06 UTC, lindsayad commented on framework/include/actions/Action.h
> +bool
```suggestion
inline bool
```

2023-11-07 02:20 UTC, lindsayad approved these changes
Learend something new today. In-line declaration is enough

2023-11-07 02:53 UTC, merged

2023-11-07 02:55 UTC, GiudGiud commented
but we cant inline code that is declared in the header and defined in the source right

2023-11-07 14:49 UTC, lindsayad commented
Well if you put the definition in the C file then you will probably get undefined symbols or references because the compiler won’t generate code that can be used/referred-to by other translation units