Mesh Divisions
idaholab/moose pull request #25998
Opened 2023-11-08 05:15 UTC by GiudGiud

Early PR if people are curious. 
not ready for review (or use!!)

2023-11-08 05:19 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/1871589/) on e62b7fe wanted to post the following:

Your code requires style changes.  

A patch was auto generated and copied [here](https://mooseframework.inl.gov/docs/PRs/25998/clang_format/style.patch)  
You can directly apply the patch by running, in the top level of your repository:

`curl -s https://mooseframework.inl.gov/docs/PRs/25998/clang_format/style.patch | git apply -v`  

Alternatively, with your repository up to date and in the top level of your repository:

`git clang-format f07619acc231d07003f7625ad27acd66306f4c62`

2023-11-09 05:14 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/1873952/) on 6081334 wanted to post the following:

The following commit(s) contain fixups:

- 6081334d9c: fixup!  Add doc and test for nearest positions based division

2023-11-09 16:42 UTC, moosebuild commented
Job [Documentation](https://civet.inl.gov/job/1874765/) on 641a6db wanted to post the following:

View the site [here](https://mooseframework.inl.gov/docs/PRs/25998/site)

This comment will be updated on new commits.

2023-11-11 15:46 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/1879048/) on 594824a wanted to post the following:

The following commit(s) contain fixups:

- 594824a4df: fixup!  Add doc and test for nearest positions based division

2023-11-11 18:00 UTC, moosebuild commented
Job [Coverage](https://civet.inl.gov/job/1879084/) on 594824a wanted to post the following:


## Framework coverage

<table>
  <thead>
    <tr>
      <th></th>
      <th>2f9664</th>
      <th colspan=4>#25998 594824</th>
    </tr>
    <tr>
      <th></th>
      <th>Total</th>
      <th>Total</th>
      <th>+/-</th>
      <th>New</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><b>Rate</b></td>
      <td>85.69%</td>
      <td>85.65%</td>
      <td>-0.04%</td>
      <td>76.60%</td>
    </tr>
    <tr>
      <td><b>Hits</b></td>
      <td>92782</td>
      <td>93159</td>
      <td>+377</td>
      <td>383</td>
    </tr>
    <tr>
      <td><b>Misses</b></td>
      <td>15490</td>
      <td>15607</td>
      <td>+117</td>
      <td>117</td>
    </tr>
  </tbody>
</table>

[Diff coverage report](https://mooseframework.inl.gov/docs/PRs/25998/coverage_diff/framework)

[Full coverage report](https://mooseframework.inl.gov/docs/PRs/25998/coverage/framework)


## Modules coverage

Coverage did not change

## Full coverage reports

<details>
<summary>Reports</summary>

- [`framework`](https://mooseframework.inl.gov/docs/PRs/25998/coverage/framework)
- [`chemical_reactions`](https://mooseframework.inl.gov/docs/PRs/25998/coverage/chemical_reactions)
- [`combined`](https://mooseframework.inl.gov/docs/PRs/25998/coverage/combined)
- [`contact`](https://mooseframework.inl.gov/docs/PRs/25998/coverage/contact)
- [`electromagnetics`](https://mooseframework.inl.gov/docs/PRs/25998/coverage/electromagnetics)
- [`external_petsc_solver`](https://mooseframework.inl.gov/docs/PRs/25998/coverage/external_petsc_solver)
- [`fluid_properties`](https://mooseframework.inl.gov/docs/PRs/25998/coverage/fluid_properties)
- [`fsi`](https://mooseframework.inl.gov/docs/PRs/25998/coverage/fsi)
- [`functional_expansion_tools`](https://mooseframework.inl.gov/docs/PRs/25998/coverage/functional_expansion_tools)
- [`geochemistry`](https://mooseframework.inl.gov/docs/PRs/25998/coverage/geochemistry)
- [`heat_transfer`](https://mooseframework.inl.gov/docs/PRs/25998/coverage/heat_transfer)
- [`level_set`](https://mooseframework.inl.gov/docs/PRs/25998/coverage/level_set)
- [`misc`](https://mooseframework.inl.gov/docs/PRs/25998/coverage/misc)
- [`navier_stokes`](https://mooseframework.inl.gov/docs/PRs/25998/coverage/navier_stokes)
- [`optimization`](https://mooseframework.inl.gov/docs/PRs/25998/coverage/optimization)
- [`peridynamics`](https://mooseframework.inl.gov/docs/PRs/25998/coverage/peridynamics)
- [`phase_field`](https://mooseframework.inl.gov/docs/PRs/25998/coverage/phase_field)
- [`porous_flow`](https://mooseframework.inl.gov/docs/PRs/25998/coverage/porous_flow)
- [`ray_tracing`](https://mooseframework.inl.gov/docs/PRs/25998/coverage/ray_tracing)
- [`rdg`](https://mooseframework.inl.gov/docs/PRs/25998/coverage/rdg)
- [`reactor`](https://mooseframework.inl.gov/docs/PRs/25998/coverage/reactor)
- [`richards`](https://mooseframework.inl.gov/docs/PRs/25998/coverage/richards)
- [`scalar_transport`](https://mooseframework.inl.gov/docs/PRs/25998/coverage/scalar_transport)
- [`solid_properties`](https://mooseframework.inl.gov/docs/PRs/25998/coverage/solid_properties)
- [`stochastic_tools`](https://mooseframework.inl.gov/docs/PRs/25998/coverage/stochastic_tools)
- [`tensor_mechanics`](https://mooseframework.inl.gov/docs/PRs/25998/coverage/tensor_mechanics)
- [`thermal_hydraulics`](https://mooseframework.inl.gov/docs/PRs/25998/coverage/thermal_hydraulics)
- [`xfem`](https://mooseframework.inl.gov/docs/PRs/25998/coverage/xfem)

</details>

## Warnings

- `framework` new line coverage rate 76.60% is less than the suggested 90.0%



This comment will be updated on new commits.

2023-11-12 13:23 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/1879258/) on 6bc9532 wanted to post the following:

The following commit(s) contain fixups:

- 6bc95320d7: fixup!  Add doc and test for nearest positions based division

2023-11-12 14:58 UTC, GiudGiud commented
Threaded failure is real and I'm thinking about it but otherwise this can be looked at

2023-11-15 21:29 UTC, GiudGiud commented
I can add more testing (with a new potentially useful object) once https://github.com/idaholab/moose/pull/25872 is in

2023-11-16 01:19 UTC, lindsayad requested changes
looks great!

2023-11-16 01:19 UTC, lindsayad commented on framework/src/meshdivisions/NearestPositionsDivision.C
> +      "The name of the Positions object to form the nearest-neighbor partition/division with");
```suggestion
      "The name of the Positions object to form the nearest-neighbor division with");
```

2023-11-16 01:19 UTC, lindsayad commented on framework/src/meshdivisions/NearestPositionsDivision.C
> +  bool initial = _fe_problem->getCurrentExecuteOnFlag() == EXEC_INITIAL;
```suggestion
  const bool initial = _fe_problem->getCurrentExecuteOnFlag() == EXEC_INITIAL;
```

2023-11-16 01:19 UTC, lindsayad commented on framework/src/meshdivisions/NearestPositionsDivision.C
> +  bool initial = _fe_problem->getCurrentExecuteOnFlag() == EXEC_INITIAL;
```suggestion
  const bool initial = _fe_problem->getCurrentExecuteOnFlag() == EXEC_INITIAL;
```

2023-11-16 01:19 UTC, lindsayad commented on framework/src/meshdivisions/NestedDivision.C
> +                 getParam<std::vector<MeshDivisionName>>("divisions")[i],
```suggestion
                 _divisions[i]->name(),
```

2023-11-16 01:19 UTC, lindsayad commented on framework/src/meshdivisions/NestedDivision.C
> +                 "now has zero bins");
```suggestion
                 "' has zero bins");
```

2023-11-16 01:19 UTC, lindsayad commented on framework/src/meshdivisions/NestedDivision.C
> +      mooseError("Nested division",
```suggestion
      mooseError("Nested division '",
```

2023-11-16 01:19 UTC, lindsayad commented on framework/src/meshdivisions/NestedDivision.C
> +  auto N_divs = _divisions.size();
```suggestion
  const auto N_divs = _divisions.size();
```

2023-11-16 01:19 UTC, lindsayad commented on framework/src/meshdivisions/NestedDivision.C
> +  auto N_divs = _divisions.size();
```suggestion
  const auto N_divs = _divisions.size();
```

2023-11-16 01:19 UTC, lindsayad commented on framework/src/meshdivisions/SphericalGridDivision.C
> +  unsigned int ir = not_found;
```suggestion
  auto ir = not_found;
```

2023-11-16 01:19 UTC, lindsayad commented on framework/src/postprocessors/NumMeshDivisions.C
> +#include "MeshDivision.h"
```suggestion
#include "MeshDivision.h"
#include "FEProblemBase.h"
```

2023-11-16 01:19 UTC, lindsayad commented on test/tests/meshdivisions/tests
> +      detail = 'a nesting of mesh divisions.'
```suggestion
      detail = 'and a nesting of mesh divisions.'
```

2023-11-16 01:19 UTC, lindsayad commented on unit/src/MooseServerTest.C
> +  EXPECT_EQ(47u, completions_array.size());
I agree with your issue that this is unfortunate

2023-11-16 01:19 UTC, lindsayad commented on framework/doc/content/source/meshdivisions/NearestPositionsDivision.md
> +For points laying within the standard tolerance of an internal boundary of the bins,
```suggestion
For points lying within the standard tolerance of an internal boundary of the bins,
```

2023-11-16 01:19 UTC, lindsayad commented on framework/doc/content/source/meshdivisions/SphericalGridDivision.md
> +Points that lay outside the spherical grid may be assigned to the closest grid outer bins (on the inner or outer shell)
```suggestion
Points that lie outside the spherical grid may be assigned to the closest grid outer bins (on the inner or outer shell)
```

2023-11-16 01:19 UTC, lindsayad commented on framework/doc/content/source/meshdivisions/SphericalGridDivision.md
> +We have not implemented neither binning in the azimuthal and toroidal coordinates nor restrictions in those angular coordinates.
```suggestion
We have not implemented binning in the azimuthal nor toroidal coordinates nor restrictions in those angular coordinates.
```

2023-11-16 01:19 UTC, lindsayad commented on framework/doc/content/source/meshdivisions/SphericalGridDivision.md
> +For points laying within the standard tolerance of an internal boundary of the spherical grid, this object
```suggestion
For points lying within the standard tolerance of an internal boundary of the spherical grid, this object
```

2023-11-16 20:48 UTC, GiudGiud commented on framework/include/meshdivisions/FunctorBinnedValuesDivision.h
> +protected:
```suggestion
```

2023-11-16 20:48 UTC, GiudGiud commented on framework/include/meshdivisions/FunctorBinnedValuesDivision.h
> +  unsigned int getBinIndex(Real value, const Point & pt) const;
no. moving it

2023-11-16 20:48 UTC, GiudGiud commented on framework/include/meshdivisions/FunctorBinnedValuesDivision.h
> +
```suggestion
protected:

```

2023-11-16 20:49 UTC, GiudGiud commented on framework/include/meshdivisions/MeshDivision.h
> +// libMesh
```suggestion
```

2023-11-16 20:51 UTC, GiudGiud commented on framework/src/auxkernels/MeshDivisionAux.C
> +               " unsupported for nodal variable");
```suggestion
```

2023-11-16 20:51 UTC, GiudGiud commented on framework/src/auxkernels/MeshDivisionAux.C
> +  else if (_var.feType().order != CONSTANT)
```suggestion
  if (!_var.isNodal() && _var.feType().order != CONSTANT)
```

2023-11-16 20:53 UTC, GiudGiud commented on framework/src/meshdivisions/NearestPositionsDivision.C
> +  params.addClassDescription("Divide the mesh by ");
```suggestion
  params.addClassDescription("Divide the mesh using a nearest-point / voronoi algorithm, with the points coming from a Positions object");
```

2023-11-16 21:42 UTC, lindsayad approved these changes

2023-11-19 17:21 UTC, merged