[WIP] Restore MUMPS_ARM_STR to configure_petsc.sh for manual Apple Silicon builds
idaholab/moose pull request #26023
Opened 2023-11-10 16:12 UTC by cticenhour

Removing this has been causing failures in CI. Also, increment conda packages.

Refs #25287

2023-11-10 16:27 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/1877557/) on eed3e47 wanted to post the following:

A change of the following file(s) triggered this check:

  conda/petsc

The following file(s) are unchanged:

  conda/mpich/conda_build_config.yaml

The conda build config was not changed but one or more of its dependencies have changed

2023-11-10 16:27 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/1877557/) on eed3e47 wanted to post the following:

A change of the following file(s) triggered this check:

  scripts/configure_petsc.sh

The following file(s) are unchanged:

  conda/mpich/conda_build_config.yaml

The PETSc submodule or configuration was changed but the conda build config was not

2023-11-10 16:27 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/1877557/) on eed3e47 wanted to post the following:

The following file(s) are changed:

  conda/petsc/meta.yaml

The PETSc conda configuration has changed; ping @idaholab/moose-dev-ops

2023-11-10 16:27 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/1877557/) on eed3e47 wanted to post the following:

The following file(s) are changed:

  conda/libmesh/meta.yaml

The libmesh conda configuration has changed; ping @idaholab/moose-dev-ops

2023-11-10 17:48 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/1877706/) on 01457e3 wanted to post the following:

A change of the following file(s) triggered this check:

  conda/petsc

The following file(s) are unchanged:

  conda/mpich/conda_build_config.yaml

The conda build config was not changed but one or more of its dependencies have changed

2023-11-10 17:48 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/1877706/) on 01457e3 wanted to post the following:

A change of the following file(s) triggered this check:

  scripts/configure_petsc.sh

The following file(s) are unchanged:

  conda/mpich/conda_build_config.yaml

The PETSc submodule or configuration was changed but the conda build config was not

2023-11-10 17:48 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/1877706/) on 01457e3 wanted to post the following:

The following file(s) are changed:

  conda/libmesh/meta.yaml

The libmesh conda configuration has changed; ping @idaholab/moose-dev-ops

2023-11-11 03:16 UTC, moosebuild commented
Job [Documentation](https://civet.inl.gov/job/1877702/) on 01457e3 wanted to post the following:

View the site [here](https://mooseframework.inl.gov/docs/PRs/26023/site)

This comment will be updated on new commits.

2023-11-11 03:57 UTC, moosebuild commented
Job [Coverage](https://civet.inl.gov/job/1877742/) on 01457e3 wanted to post the following:


## Framework coverage

Coverage did not change


## Modules coverage

Coverage did not change

## Full coverage reports

<details>
<summary>Reports</summary>

- [`framework`](https://mooseframework.inl.gov/docs/PRs/26023/coverage/framework)
- [`chemical_reactions`](https://mooseframework.inl.gov/docs/PRs/26023/coverage/chemical_reactions)
- [`combined`](https://mooseframework.inl.gov/docs/PRs/26023/coverage/combined)
- [`contact`](https://mooseframework.inl.gov/docs/PRs/26023/coverage/contact)
- [`electromagnetics`](https://mooseframework.inl.gov/docs/PRs/26023/coverage/electromagnetics)
- [`external_petsc_solver`](https://mooseframework.inl.gov/docs/PRs/26023/coverage/external_petsc_solver)
- [`fluid_properties`](https://mooseframework.inl.gov/docs/PRs/26023/coverage/fluid_properties)
- [`fsi`](https://mooseframework.inl.gov/docs/PRs/26023/coverage/fsi)
- [`functional_expansion_tools`](https://mooseframework.inl.gov/docs/PRs/26023/coverage/functional_expansion_tools)
- [`geochemistry`](https://mooseframework.inl.gov/docs/PRs/26023/coverage/geochemistry)
- [`heat_transfer`](https://mooseframework.inl.gov/docs/PRs/26023/coverage/heat_transfer)
- [`level_set`](https://mooseframework.inl.gov/docs/PRs/26023/coverage/level_set)
- [`misc`](https://mooseframework.inl.gov/docs/PRs/26023/coverage/misc)
- [`navier_stokes`](https://mooseframework.inl.gov/docs/PRs/26023/coverage/navier_stokes)
- [`optimization`](https://mooseframework.inl.gov/docs/PRs/26023/coverage/optimization)
- [`peridynamics`](https://mooseframework.inl.gov/docs/PRs/26023/coverage/peridynamics)
- [`phase_field`](https://mooseframework.inl.gov/docs/PRs/26023/coverage/phase_field)
- [`porous_flow`](https://mooseframework.inl.gov/docs/PRs/26023/coverage/porous_flow)
- [`ray_tracing`](https://mooseframework.inl.gov/docs/PRs/26023/coverage/ray_tracing)
- [`rdg`](https://mooseframework.inl.gov/docs/PRs/26023/coverage/rdg)
- [`reactor`](https://mooseframework.inl.gov/docs/PRs/26023/coverage/reactor)
- [`richards`](https://mooseframework.inl.gov/docs/PRs/26023/coverage/richards)
- [`scalar_transport`](https://mooseframework.inl.gov/docs/PRs/26023/coverage/scalar_transport)
- [`solid_properties`](https://mooseframework.inl.gov/docs/PRs/26023/coverage/solid_properties)
- [`stochastic_tools`](https://mooseframework.inl.gov/docs/PRs/26023/coverage/stochastic_tools)
- [`tensor_mechanics`](https://mooseframework.inl.gov/docs/PRs/26023/coverage/tensor_mechanics)
- [`thermal_hydraulics`](https://mooseframework.inl.gov/docs/PRs/26023/coverage/thermal_hydraulics)
- [`xfem`](https://mooseframework.inl.gov/docs/PRs/26023/coverage/xfem)

</details>



This comment will be updated on new commits.

2023-11-13 15:11 UTC, moosebuild commented
Job [Apple Silicon Extended Testing (WIP, Scheduled)](https://civet.inl.gov/job/1877745/) on 01457e3 : invalidated by @milljm

Updated recipe to build WASP

2023-11-13 15:24 UTC, milljm approved these changes
sigh (that this is needed)... 👍

2023-11-13 18:06 UTC, cticenhour commented
Python failure in Apple Silicon testing is related to the civet client test, and therefore unrelated to this change. Tagging @loganharbour for another set of eyes on the package version updates.

2023-11-13 18:08 UTC, loganharbour commented
Can you guys work on combining with https://github.com/idaholab/moose/pull/25992?

2023-11-14 14:15 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/1882334/) on 16c07c6 wanted to post the following:

A change of the following file(s) triggered this check:

  conda/petsc

The following file(s) are unchanged:

  conda/mpich/conda_build_config.yaml

The conda build config was not changed but one or more of its dependencies have changed

2023-11-14 14:15 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/1882334/) on 16c07c6 wanted to post the following:

A change of the following file(s) triggered this check:

  scripts/configure_petsc.sh

The following file(s) are unchanged:

  conda/mpich/conda_build_config.yaml

The PETSc submodule or configuration was changed but the conda build config was not

2023-11-14 14:15 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/1882334/) on 16c07c6 wanted to post the following:

The following file(s) are changed:

  conda/petsc/meta.yaml

The PETSc conda configuration has changed; ping @idaholab/moose-dev-ops

2023-11-14 14:15 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/1882334/) on 16c07c6 wanted to post the following:

The following file(s) are changed:

  conda/libmesh/meta.yaml

The libmesh conda configuration has changed; ping @idaholab/moose-dev-ops

2023-11-14 15:26 UTC, loganharbour requested changes
FYI still not passing

2023-11-14 15:41 UTC, cticenhour commented on conda/libmesh/conda_build_config.yaml
>    - moose-libmesh-vtk 9.2.6 build_6
```suggestion
  - moose-libmesh-vtk 9.2.6 build_7
```

2023-11-14 17:27 UTC, loganharbour approved these changes
Reminder to remove the `ONLY_ON_PR_NUM` options in the recipes for these, and also to add steps to the "Apptainer transfer" recipe on master to also transfer these images.

2023-11-14 17:28 UTC, loganharbour requested changes
Peacock was bumped which will require a versioner_hashes change due to a moose-dev bump.

2023-11-14 17:58 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/1882667/) on fa6c6a3 wanted to post the following:

A change of the following file(s) triggered this check:

  conda/petsc

The following file(s) are unchanged:

  conda/mpich/conda_build_config.yaml

The conda build config was not changed but one or more of its dependencies have changed

2023-11-14 17:58 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/1882667/) on fa6c6a3 wanted to post the following:

A change of the following file(s) triggered this check:

  scripts/configure_petsc.sh

The following file(s) are unchanged:

  conda/mpich/conda_build_config.yaml

The PETSc submodule or configuration was changed but the conda build config was not

2023-11-14 17:58 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/1882667/) on fa6c6a3 wanted to post the following:

The following file(s) are changed:

  conda/petsc/meta.yaml

The PETSc conda configuration has changed; ping @idaholab/moose-dev-ops

2023-11-14 17:58 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/1882667/) on fa6c6a3 wanted to post the following:

The following file(s) are changed:

  conda/libmesh/meta.yaml

The libmesh conda configuration has changed; ping @idaholab/moose-dev-ops

2023-11-15 20:37 UTC, milljm commented
I need to solve the issue with channel transfer before I can allow this onto next.

2023-11-16 17:35 UTC, milljm commented
>Reminder to remove the ONLY_ON_PR_NUM options in the recipes for these, and also to add steps to the "Apptainer transfer" recipe on master to also transfer these images.

will do, as soon as its merged...

2023-11-16 18:13 UTC, milljm commented
@brandonlangley may have some idea to improve our `moose.def` file. I figure that may as well wind up in this perhaps. Or, if we are chomping at the bits to get this in, the `moose.def` changes can wait for another PR...

2023-11-16 18:30 UTC, milljm commented
Okay, scratch that... we will remove the WASP section in another PR, and not hold this one up. Being that it is redundant, means we can be a little lazy and do it later...

2023-11-16 21:35 UTC, loganharbour approved these changes

2023-11-16 21:37 UTC, merged