Update mailmap to consolidate contributions
idaholab/moose pull request #26096
Opened 2023-11-17 22:04 UTC by GiudGiud

refs #22378

2023-11-17 22:11 UTC, GiudGiud commented
there are some weird lines because people have messed up their email in their git config. 
most lines are people using different emails at various times or on various machines

2023-11-18 01:25 UTC, moosebuild commented
Job [Documentation](https://civet.inl.gov/job/1888770/) on b90affc wanted to post the following:

View the site [here](https://mooseframework.inl.gov/docs/PRs/26096/site)

This comment will be updated on new commits.

2023-11-18 01:48 UTC, GiudGiud commented
Failures unrelated

2023-11-18 01:56 UTC, moosebuild commented
Job [Coverage](https://civet.inl.gov/job/1888786/) on b90affc wanted to post the following:


## Framework coverage

<table>
  <thead>
    <tr>
      <th></th>
      <th>5dfe95</th>
      <th colspan=4>#26096 b90aff</th>
    </tr>
    <tr>
      <th></th>
      <th>Total</th>
      <th>Total</th>
      <th>+/-</th>
      <th>New</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><b>Rate</b></td>
      <td>85.74%</td>
      <td>85.74%</td>
      <td>+0.00%</td>
      <td>-</td>
    </tr>
    <tr>
      <td><b>Hits</b></td>
      <td>93034</td>
      <td>93035</td>
      <td>+1</td>
      <td>0</td>
    </tr>
    <tr>
      <td><b>Misses</b></td>
      <td>15470</td>
      <td>15469</td>
      <td>-1</td>
      <td>0</td>
    </tr>
  </tbody>
</table>

[Diff coverage report](https://mooseframework.inl.gov/docs/PRs/26096/coverage_diff/framework)

[Full coverage report](https://mooseframework.inl.gov/docs/PRs/26096/coverage/framework)


## Modules coverage

Coverage did not change

## Full coverage reports

<details>
<summary>Reports</summary>

- [`framework`](https://mooseframework.inl.gov/docs/PRs/26096/coverage/framework)
- [`chemical_reactions`](https://mooseframework.inl.gov/docs/PRs/26096/coverage/chemical_reactions)
- [`combined`](https://mooseframework.inl.gov/docs/PRs/26096/coverage/combined)
- [`contact`](https://mooseframework.inl.gov/docs/PRs/26096/coverage/contact)
- [`electromagnetics`](https://mooseframework.inl.gov/docs/PRs/26096/coverage/electromagnetics)
- [`external_petsc_solver`](https://mooseframework.inl.gov/docs/PRs/26096/coverage/external_petsc_solver)
- [`fluid_properties`](https://mooseframework.inl.gov/docs/PRs/26096/coverage/fluid_properties)
- [`fsi`](https://mooseframework.inl.gov/docs/PRs/26096/coverage/fsi)
- [`functional_expansion_tools`](https://mooseframework.inl.gov/docs/PRs/26096/coverage/functional_expansion_tools)
- [`geochemistry`](https://mooseframework.inl.gov/docs/PRs/26096/coverage/geochemistry)
- [`heat_transfer`](https://mooseframework.inl.gov/docs/PRs/26096/coverage/heat_transfer)
- [`level_set`](https://mooseframework.inl.gov/docs/PRs/26096/coverage/level_set)
- [`misc`](https://mooseframework.inl.gov/docs/PRs/26096/coverage/misc)
- [`navier_stokes`](https://mooseframework.inl.gov/docs/PRs/26096/coverage/navier_stokes)
- [`optimization`](https://mooseframework.inl.gov/docs/PRs/26096/coverage/optimization)
- [`peridynamics`](https://mooseframework.inl.gov/docs/PRs/26096/coverage/peridynamics)
- [`phase_field`](https://mooseframework.inl.gov/docs/PRs/26096/coverage/phase_field)
- [`porous_flow`](https://mooseframework.inl.gov/docs/PRs/26096/coverage/porous_flow)
- [`ray_tracing`](https://mooseframework.inl.gov/docs/PRs/26096/coverage/ray_tracing)
- [`rdg`](https://mooseframework.inl.gov/docs/PRs/26096/coverage/rdg)
- [`reactor`](https://mooseframework.inl.gov/docs/PRs/26096/coverage/reactor)
- [`richards`](https://mooseframework.inl.gov/docs/PRs/26096/coverage/richards)
- [`scalar_transport`](https://mooseframework.inl.gov/docs/PRs/26096/coverage/scalar_transport)
- [`solid_properties`](https://mooseframework.inl.gov/docs/PRs/26096/coverage/solid_properties)
- [`stochastic_tools`](https://mooseframework.inl.gov/docs/PRs/26096/coverage/stochastic_tools)
- [`tensor_mechanics`](https://mooseframework.inl.gov/docs/PRs/26096/coverage/tensor_mechanics)
- [`thermal_hydraulics`](https://mooseframework.inl.gov/docs/PRs/26096/coverage/thermal_hydraulics)
- [`xfem`](https://mooseframework.inl.gov/docs/PRs/26096/coverage/xfem)

</details>



This comment will be updated on new commits.

2023-11-18 16:35 UTC, loganharbour requested changes

2023-11-18 16:35 UTC, loganharbour commented on .mailmap
> +Nathaniel Peats <nathaniel.peat@inl.gov>
```suggestion
Nathaniel Peat <76120892+socratesgorilla@users.noreply.github.com>
Nathaniel Peat <nathaniel.peat@inl.gov>
```

2023-11-18 16:48 UTC, GiudGiud commented on .mailmap
> +Nathaniel Peats <nathaniel.peat@inl.gov>
good catch

2023-11-19 00:26 UTC, loganharbour approved these changes

2023-11-19 16:45 UTC, loganharbour commented
Unrelated failures.

2023-11-19 16:46 UTC, merged