Explicitly register dependent applications for modules
idaholab/moose pull request #26331
Opened 2023-12-13 22:01 UTC by MengnanLi91

This is a patch PR to explicitly register dependent applications. It is needed for the new [Applications] block I am working on (#23741). After parsing the application types from [Applications] block, this allows us to compare the parsed app type to application registration list and determine whether the correct application input is used. 

## Reason

It is needed to support [Applications] block working properly

## Impact

Support new capability

2023-12-13 22:52 UTC, loganharbour commented
@permcody I thought that this was supposed to be satisfied by the module loader? I thought that we wanted to only enable modules in one place - the corresponding Makefile

2023-12-14 03:21 UTC, moosebuild commented
Job [Documentation](https://civet.inl.gov/job/1944732/) on 9ff02ad wanted to post the following:

View the site [here](https://mooseframework.inl.gov/docs/PRs/26331/site)

This comment will be updated on new commits.

2023-12-14 15:46 UTC, GiudGiud commented
I think this has pretty deep implications for the creation of a new app. It's no longer a trivial process of just adding a yes in the Makefile. I can see this becoming a burden on user support

2023-12-14 17:50 UTC, loganharbour commented
> I think this has pretty deep implications for the creation of a new app. It's no longer a trivial process of just adding a yes in the Makefile. I can see this becoming a burden on user support

It's not a requirement

2023-12-14 20:05 UTC, moosebuild commented
Job [Documentation controlled apps](https://civet.inl.gov/job/1946882/) on 537358d : invalidated by @MengnanLi91

Griffin fetch error

2023-12-14 20:59 UTC, moosebuild commented
Job [Coverage](https://civet.inl.gov/job/1946896/) on 537358d wanted to post the following:


## Framework coverage

<table>
  <thead>
    <tr>
      <th></th>
      <th>cfd4d8</th>
      <th colspan=4>#26331 537358</th>
    </tr>
    <tr>
      <th></th>
      <th>Total</th>
      <th>Total</th>
      <th>+/-</th>
      <th>New</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><b>Rate</b></td>
      <td>85.06%</td>
      <td>85.06%</td>
      <td>+0.00%</td>
      <td>-</td>
    </tr>
    <tr>
      <td><b>Hits</b></td>
      <td>97860</td>
      <td>97861</td>
      <td>+1</td>
      <td>0</td>
    </tr>
    <tr>
      <td><b>Misses</b></td>
      <td>17186</td>
      <td>17185</td>
      <td>-1</td>
      <td>0</td>
    </tr>
  </tbody>
</table>

[Diff coverage report](https://mooseframework.inl.gov/docs/PRs/26331/coverage_diff/framework)

[Full coverage report](https://mooseframework.inl.gov/docs/PRs/26331/coverage/framework)


## Modules coverage

### Combined

<table>
  <thead>
    <tr>
      <th></th>
      <th>cfd4d8</th>
      <th colspan=4>#26331 537358</th>
    </tr>
    <tr>
      <th></th>
      <th>Total</th>
      <th>Total</th>
      <th>+/-</th>
      <th>New</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><b>Rate</b></td>
      <td>73.77%</td>
      <td>51.14%</td>
      <td>-22.63%</td>
      <td>0.00%</td>
    </tr>
    <tr>
      <td><b>Hits</b></td>
      <td>45</td>
      <td>45</td>
      <td>-</td>
      <td>0</td>
    </tr>
    <tr>
      <td><b>Misses</b></td>
      <td>16</td>
      <td>43</td>
      <td>+27</td>
      <td>27</td>
    </tr>
  </tbody>
</table>

[Diff coverage report](https://mooseframework.inl.gov/docs/PRs/26331/coverage_diff/combined)

[Full coverage report](https://mooseframework.inl.gov/docs/PRs/26331/coverage/combined)

### Contact

<table>
  <thead>
    <tr>
      <th></th>
      <th>cfd4d8</th>
      <th colspan=4>#26331 537358</th>
    </tr>
    <tr>
      <th></th>
      <th>Total</th>
      <th>Total</th>
      <th>+/-</th>
      <th>New</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><b>Rate</b></td>
      <td>90.17%</td>
      <td>90.15%</td>
      <td>-0.02%</td>
      <td>0.00%</td>
    </tr>
    <tr>
      <td><b>Hits</b></td>
      <td>4007</td>
      <td>4007</td>
      <td>-</td>
      <td>0</td>
    </tr>
    <tr>
      <td><b>Misses</b></td>
      <td>437</td>
      <td>438</td>
      <td>+1</td>
      <td>1</td>
    </tr>
  </tbody>
</table>

[Diff coverage report](https://mooseframework.inl.gov/docs/PRs/26331/coverage_diff/contact)

[Full coverage report](https://mooseframework.inl.gov/docs/PRs/26331/coverage/contact)

### Fsi

<table>
  <thead>
    <tr>
      <th></th>
      <th>cfd4d8</th>
      <th colspan=4>#26331 537358</th>
    </tr>
    <tr>
      <th></th>
      <th>Total</th>
      <th>Total</th>
      <th>+/-</th>
      <th>New</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><b>Rate</b></td>
      <td>88.00%</td>
      <td>87.53%</td>
      <td>-0.47%</td>
      <td>0.00%</td>
    </tr>
    <tr>
      <td><b>Hits</b></td>
      <td>330</td>
      <td>330</td>
      <td>-</td>
      <td>0</td>
    </tr>
    <tr>
      <td><b>Misses</b></td>
      <td>45</td>
      <td>47</td>
      <td>+2</td>
      <td>2</td>
    </tr>
  </tbody>
</table>

[Diff coverage report](https://mooseframework.inl.gov/docs/PRs/26331/coverage_diff/fsi)

[Full coverage report](https://mooseframework.inl.gov/docs/PRs/26331/coverage/fsi)

### Heat transfer

<table>
  <thead>
    <tr>
      <th></th>
      <th>cfd4d8</th>
      <th colspan=4>#26331 537358</th>
    </tr>
    <tr>
      <th></th>
      <th>Total</th>
      <th>Total</th>
      <th>+/-</th>
      <th>New</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><b>Rate</b></td>
      <td>88.28%</td>
      <td>88.26%</td>
      <td>-0.02%</td>
      <td>0.00%</td>
    </tr>
    <tr>
      <td><b>Hits</b></td>
      <td>3932</td>
      <td>3932</td>
      <td>-</td>
      <td>0</td>
    </tr>
    <tr>
      <td><b>Misses</b></td>
      <td>522</td>
      <td>523</td>
      <td>+1</td>
      <td>1</td>
    </tr>
  </tbody>
</table>

[Diff coverage report](https://mooseframework.inl.gov/docs/PRs/26331/coverage_diff/heat_transfer)

[Full coverage report](https://mooseframework.inl.gov/docs/PRs/26331/coverage/heat_transfer)

### Navier stokes

<table>
  <thead>
    <tr>
      <th></th>
      <th>cfd4d8</th>
      <th colspan=4>#26331 537358</th>
    </tr>
    <tr>
      <th></th>
      <th>Total</th>
      <th>Total</th>
      <th>+/-</th>
      <th>New</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><b>Rate</b></td>
      <td>84.23%</td>
      <td>84.22%</td>
      <td>-0.01%</td>
      <td>33.33%</td>
    </tr>
    <tr>
      <td><b>Hits</b></td>
      <td>13194</td>
      <td>13194</td>
      <td>-</td>
      <td>1</td>
    </tr>
    <tr>
      <td><b>Misses</b></td>
      <td>2471</td>
      <td>2473</td>
      <td>+2</td>
      <td>2</td>
    </tr>
  </tbody>
</table>

[Diff coverage report](https://mooseframework.inl.gov/docs/PRs/26331/coverage_diff/navier_stokes)

[Full coverage report](https://mooseframework.inl.gov/docs/PRs/26331/coverage/navier_stokes)

### Peridynamics

<table>
  <thead>
    <tr>
      <th></th>
      <th>cfd4d8</th>
      <th colspan=4>#26331 537358</th>
    </tr>
    <tr>
      <th></th>
      <th>Total</th>
      <th>Total</th>
      <th>+/-</th>
      <th>New</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><b>Rate</b></td>
      <td>77.50%</td>
      <td>77.48%</td>
      <td>-0.02%</td>
      <td>0.00%</td>
    </tr>
    <tr>
      <td><b>Hits</b></td>
      <td>3072</td>
      <td>3072</td>
      <td>-</td>
      <td>0</td>
    </tr>
    <tr>
      <td><b>Misses</b></td>
      <td>892</td>
      <td>893</td>
      <td>+1</td>
      <td>1</td>
    </tr>
  </tbody>
</table>

[Diff coverage report](https://mooseframework.inl.gov/docs/PRs/26331/coverage_diff/peridynamics)

[Full coverage report](https://mooseframework.inl.gov/docs/PRs/26331/coverage/peridynamics)

### Porous flow

<table>
  <thead>
    <tr>
      <th></th>
      <th>cfd4d8</th>
      <th colspan=4>#26331 537358</th>
    </tr>
    <tr>
      <th></th>
      <th>Total</th>
      <th>Total</th>
      <th>+/-</th>
      <th>New</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><b>Rate</b></td>
      <td>95.32%</td>
      <td>95.30%</td>
      <td>-0.02%</td>
      <td>0.00%</td>
    </tr>
    <tr>
      <td><b>Hits</b></td>
      <td>11132</td>
      <td>11132</td>
      <td>-</td>
      <td>0</td>
    </tr>
    <tr>
      <td><b>Misses</b></td>
      <td>546</td>
      <td>549</td>
      <td>+3</td>
      <td>3</td>
    </tr>
  </tbody>
</table>

[Diff coverage report](https://mooseframework.inl.gov/docs/PRs/26331/coverage_diff/porous_flow)

[Full coverage report](https://mooseframework.inl.gov/docs/PRs/26331/coverage/porous_flow)

### Scalar transport

<table>
  <thead>
    <tr>
      <th></th>
      <th>cfd4d8</th>
      <th colspan=4>#26331 537358</th>
    </tr>
    <tr>
      <th></th>
      <th>Total</th>
      <th>Total</th>
      <th>+/-</th>
      <th>New</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><b>Rate</b></td>
      <td>91.40%</td>
      <td>85.64%</td>
      <td>-5.76%</td>
      <td>10.00%</td>
    </tr>
    <tr>
      <td><b>Hits</b></td>
      <td>170</td>
      <td>167</td>
      <td>-3</td>
      <td>1</td>
    </tr>
    <tr>
      <td><b>Misses</b></td>
      <td>16</td>
      <td>28</td>
      <td>+12</td>
      <td>9</td>
    </tr>
  </tbody>
</table>

[Diff coverage report](https://mooseframework.inl.gov/docs/PRs/26331/coverage_diff/scalar_transport)

[Full coverage report](https://mooseframework.inl.gov/docs/PRs/26331/coverage/scalar_transport)

### Solid properties

<table>
  <thead>
    <tr>
      <th></th>
      <th>cfd4d8</th>
      <th colspan=4>#26331 537358</th>
    </tr>
    <tr>
      <th></th>
      <th>Total</th>
      <th>Total</th>
      <th>+/-</th>
      <th>New< [...]

2023-12-14 20:59 UTC, moosebuild commented
Job [Coverage](https://civet.inl.gov/job/1946896/) on 537358d wanted to post the following:


The following coverage requirement(s) failed:
- `scalar_transport` coverage rate 85.64% is less than the required 90.0%

2023-12-14 21:40 UTC, GiudGiud commented
Ah ok it s just to get the Application block to work as expected? Or also the app_type block in MultiApps?

2023-12-14 22:31 UTC, MengnanLi91 commented
> Ah ok it s just to get the Application block to work as expected? Or also the app_type block in MultiApps?

This will provide the App register list we can and compare with the type input of Application block. It should work for MultiApps too

2023-12-14 23:26 UTC, permcody commented
Looks like Logan and Guillaume settled on the right answer. This change shouldn't impact anything with new or existing apps. It simply allows us to create additional "app types" for nearly every app (including the modules). Right now only BlueCRAB and Direwolf register additional applications that a user may request (and as we know that's currently limited to only the Multiapp block). This PR allows somebody in a module to be able to explicitly create a depdendent app in a Multiapp.

As we move forward, we'll be able to explicitly create that same dependent application as _the_ top-level application for a given input. After this gets merged, we should patch the applications so applications have this same consistent interface.

2023-12-18 15:13 UTC, loganharbour requested changes
You'll need to change the coverage in `.coverage` for `scalar_transport` from 90 to 85 to satisfy https://civet.inl.gov/job/1946896/

2023-12-18 17:34 UTC, loganharbour commented on .coverage
> +
Not alphabetical?! come on... :D

2023-12-18 17:34 UTC, loganharbour approved these changes

2023-12-18 18:42 UTC, loganharbour approved these changes

2023-12-18 20:45 UTC, moosebuild commented
Job [Coverage](https://civet.inl.gov/job/1951684/) on f42c60d wanted to post the following:


The following coverage requirement(s) failed:
- Failed to generate `framework` coverage rate (required: 81.0%)

2023-12-18 21:37 UTC, moosebuild commented
Job [Coverage](https://civet.inl.gov/job/1951684/) on f42c60d : invalidated by @MengnanLi91

2023-12-18 21:43 UTC, moosebuild commented
Job [Coverage](https://civet.inl.gov/job/1951684/) on f42c60d wanted to post the following:


The following coverage requirement(s) failed:
- Failed to generate `framework` coverage rate (required: 81.0%)

2023-12-19 23:44 UTC, loganharbour approved these changes

2023-12-20 03:56 UTC, merged