Fixes documentation
idaholab/moose pull request #26364
Opened 2023-12-18 20:58 UTC by oanaoana

This fixes documentation issues. 

## Reason
Wrong refs in Pseudotimestep.md and typsetting for readability in NonlinearSystem.md

## Design
MOOSE markdown

## Impact
User appeal.

2023-12-19 00:17 UTC, moosebuild commented
Job [Documentation](https://civet.inl.gov/job/1952770/) on 3857c09 wanted to post the following:

View the site [here](https://mooseframework.inl.gov/docs/PRs/26364/site)

This comment will be updated on new commits.

2023-12-19 16:41 UTC, cticenhour requested changes
A few suggestions. Thanks for adjusting the previous formatting!

2023-12-19 16:41 UTC, cticenhour commented on framework/doc/content/source/postprocessors/PseudoTimestep.md
> +- Exponential progression (EXP)
```suggestion
- +Exponential progression (EXP)+
```

2023-12-19 16:41 UTC, cticenhour commented on framework/doc/content/source/postprocessors/PseudoTimestep.md
>  where $\alpha$ is a user chosen parameter, $k$ is the current iteration step.
```suggestion
  \begin{equation}
  \Delta t_k =\Delta t_{0} \cdot \alpha^k
  \end{equation}

  where $\alpha$ is a user chosen parameter, $k$ is the current iteration step.
```

2023-12-19 16:41 UTC, cticenhour commented on framework/doc/content/source/postprocessors/PseudoTimestep.md
> +As an example this postprocessor may be implemented as
```suggestion
## Example Input File Syntax
```

This aligns with other object documentation sections.

2023-12-19 16:41 UTC, cticenhour commented on framework/doc/content/source/systems/NonlinearSystem.md
>    to solve for the coefficients $u_j, j=1,\dots,N$.
```suggestion
  to solve for the coefficients $u_j, \quad j=1,\dots,N$.
```

Let's add a bit more space here too, while we're at it.

2023-12-19 16:41 UTC, cticenhour commented on framework/doc/content/source/systems/NonlinearSystem.md
> +\end{equation}
```suggestion
\begin{equation}
- \nabla\cdot k\nabla u + \vec{\beta} \cdot \nabla u = f
\end{equation}
```

2023-12-19 16:41 UTC, cticenhour commented on framework/doc/content/source/systems/NonlinearSystem.md
> +\end{equation}
```suggestion
\begin{equation}
\dfrac{\partial f}{\partial u_j} = \cos(u_h) \phi_j
\end{equation}
```

2023-12-19 16:41 UTC, cticenhour commented on framework/doc/content/source/systems/NonlinearSystem.md
> +\end{equation}
```suggestion
\begin{equation}
\mathbf{J}\vec{v} \approx \dfrac{\vec{R}(\vec{u} + \epsilon\vec{v}) - \vec{R}(\vec{u})}{\epsilon}
\end{equation}
```

2023-12-19 16:42 UTC, GiudGiud approved these changes
looks a lot better!

2023-12-19 20:21 UTC, loganharbour commented
Please use batching for review changes (see https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/incorporating-feedback-in-your-pull-request for more info) to avoid extraneous commits and extraneous civet events in the future

2023-12-19 22:42 UTC, cticenhour approved these changes
Thanks @oanaoana!

2023-12-19 22:42 UTC, merged

2023-12-20 03:22 UTC, oanaoana commented
> Please use batching for review changes (see https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/incorporating-feedback-in-your-pull-request for more info) to avoid extraneous commits and extraneous civet events in the future

Aye Aye Sir!!!