Accessing gradient of a coupled array variable's time derivative
idaholab/moose pull request #26387
Opened 2023-12-21 11:09 UTC by yjung-anl

closes #26385

## Reason

## Design

## Impact

2023-12-21 16:08 UTC, moosebuild commented
Job [Modules parallel](https://civet.inl.gov/job/1959646/) on 1a0e3c3 : invalidated by @yjung-anl

2023-12-21 18:37 UTC, moosebuild commented
Job [Coverage](https://civet.inl.gov/job/1959664/) on 1a0e3c3 wanted to post the following:


## Framework coverage

<table>
  <thead>
    <tr>
      <th></th>
      <th>239580</th>
      <th colspan=4>#26387 1a0e3c</th>
    </tr>
    <tr>
      <th></th>
      <th>Total</th>
      <th>Total</th>
      <th>+/-</th>
      <th>New</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><b>Rate</b></td>
      <td>85.07%</td>
      <td>85.06%</td>
      <td>-0.01%</td>
      <td>0.00%</td>
    </tr>
    <tr>
      <td><b>Hits</b></td>
      <td>98358</td>
      <td>98356</td>
      <td>-2</td>
      <td>0</td>
    </tr>
    <tr>
      <td><b>Misses</b></td>
      <td>17263</td>
      <td>17273</td>
      <td>+10</td>
      <td>8</td>
    </tr>
  </tbody>
</table>

[Diff coverage report](https://mooseframework.inl.gov/docs/PRs/26387/coverage_diff/framework)

[Full coverage report](https://mooseframework.inl.gov/docs/PRs/26387/coverage/framework)


## Modules coverage

Coverage did not change

## Full coverage reports

<details>
<summary>Reports</summary>

- [`framework`](https://mooseframework.inl.gov/docs/PRs/26387/coverage/framework)
- [`chemical_reactions`](https://mooseframework.inl.gov/docs/PRs/26387/coverage/chemical_reactions)
- [`combined`](https://mooseframework.inl.gov/docs/PRs/26387/coverage/combined)
- [`contact`](https://mooseframework.inl.gov/docs/PRs/26387/coverage/contact)
- [`electromagnetics`](https://mooseframework.inl.gov/docs/PRs/26387/coverage/electromagnetics)
- [`external_petsc_solver`](https://mooseframework.inl.gov/docs/PRs/26387/coverage/external_petsc_solver)
- [`fluid_properties`](https://mooseframework.inl.gov/docs/PRs/26387/coverage/fluid_properties)
- [`fsi`](https://mooseframework.inl.gov/docs/PRs/26387/coverage/fsi)
- [`functional_expansion_tools`](https://mooseframework.inl.gov/docs/PRs/26387/coverage/functional_expansion_tools)
- [`geochemistry`](https://mooseframework.inl.gov/docs/PRs/26387/coverage/geochemistry)
- [`heat_transfer`](https://mooseframework.inl.gov/docs/PRs/26387/coverage/heat_transfer)
- [`level_set`](https://mooseframework.inl.gov/docs/PRs/26387/coverage/level_set)
- [`misc`](https://mooseframework.inl.gov/docs/PRs/26387/coverage/misc)
- [`navier_stokes`](https://mooseframework.inl.gov/docs/PRs/26387/coverage/navier_stokes)
- [`optimization`](https://mooseframework.inl.gov/docs/PRs/26387/coverage/optimization)
- [`peridynamics`](https://mooseframework.inl.gov/docs/PRs/26387/coverage/peridynamics)
- [`phase_field`](https://mooseframework.inl.gov/docs/PRs/26387/coverage/phase_field)
- [`porous_flow`](https://mooseframework.inl.gov/docs/PRs/26387/coverage/porous_flow)
- [`ray_tracing`](https://mooseframework.inl.gov/docs/PRs/26387/coverage/ray_tracing)
- [`rdg`](https://mooseframework.inl.gov/docs/PRs/26387/coverage/rdg)
- [`reactor`](https://mooseframework.inl.gov/docs/PRs/26387/coverage/reactor)
- [`richards`](https://mooseframework.inl.gov/docs/PRs/26387/coverage/richards)
- [`scalar_transport`](https://mooseframework.inl.gov/docs/PRs/26387/coverage/scalar_transport)
- [`solid_properties`](https://mooseframework.inl.gov/docs/PRs/26387/coverage/solid_properties)
- [`stochastic_tools`](https://mooseframework.inl.gov/docs/PRs/26387/coverage/stochastic_tools)
- [`tensor_mechanics`](https://mooseframework.inl.gov/docs/PRs/26387/coverage/tensor_mechanics)
- [`thermal_hydraulics`](https://mooseframework.inl.gov/docs/PRs/26387/coverage/thermal_hydraulics)
- [`xfem`](https://mooseframework.inl.gov/docs/PRs/26387/coverage/xfem)

</details>

## Warnings

- `framework` new line coverage rate 0.00% is less than the suggested 90.0%



This comment will be updated on new commits.

2023-12-21 21:20 UTC, lindsayad requested changes
Ideally we would add a test for this

2023-12-21 21:20 UTC, lindsayad commented on framework/include/interfaces/Coupleable.h
> +   * @param var_name Name of coupled vector variable
```suggestion
   * @param var_name Name of coupled array variable
```

2023-12-21 21:20 UTC, lindsayad commented on framework/include/interfaces/Coupleable.h
> +   * @param comp Component number for vector of coupled vector variables
```suggestion
   * @param comp Component number for vector of coupled array variables
```

2023-12-21 21:20 UTC, lindsayad commented on framework/include/interfaces/Coupleable.h
> +   * @return Reference to a ArrayVariableGradient containing the time derivative of the gradient of
Is it the time derivative of the gradient, or the gradient of the time derivative? Above it's the latter but here it's the former

2023-12-21 21:20 UTC, lindsayad commented on framework/src/interfaces/Coupleable.C
> +  const auto * var = getArrayVar(var_name, comp);
```suggestion
  const auto * const var = getArrayVar(var_name, comp);
```

2024-01-02 18:52 UTC, yjung-anl commented
Comments have been addressed.

2024-01-04 23:02 UTC, lindsayad approved these changes

2024-01-04 23:02 UTC, merged

2024-01-04 23:02 UTC, lindsayad commented
Thanks @yjung-anl !