Update SQA reports allowances to avoid regression
idaholab/moose pull request #26412
Opened 2023-12-23 23:59 UTC by GiudGiud

refs #12049 

This will prevent regression like in the Navier Stokes module for example, where an old FE NS implementation was merged with insufficient doco. 1 year later, it has not been contributed. 

I am also turning back on colors in the SQA reports. Everyone is really close now, that orange can just serve as extra motivation

2023-12-24 00:01 UTC, GiudGiud commented on modules/doc/sqa_reports.yml
> -        show_warning: false
the items above will have to wait for #26359 to get in

2023-12-24 01:49 UTC, moosebuild commented
Job [Documentation](https://civet.inl.gov/job/1967507/) on 919e4d2 wanted to post the following:

View the site [here](https://mooseframework.inl.gov/docs/PRs/26412/site)

This comment will be updated on new commits.

2023-12-24 02:37 UTC, moosebuild commented
Job [Coverage](https://civet.inl.gov/job/1967550/) on 919e4d2 wanted to post the following:


## Framework coverage

Coverage did not change


## Modules coverage

Coverage did not change

## Full coverage reports

<details>
<summary>Reports</summary>

- [`framework`](https://mooseframework.inl.gov/docs/PRs/26412/coverage/framework)
- [`chemical_reactions`](https://mooseframework.inl.gov/docs/PRs/26412/coverage/chemical_reactions)
- [`combined`](https://mooseframework.inl.gov/docs/PRs/26412/coverage/combined)
- [`contact`](https://mooseframework.inl.gov/docs/PRs/26412/coverage/contact)
- [`electromagnetics`](https://mooseframework.inl.gov/docs/PRs/26412/coverage/electromagnetics)
- [`external_petsc_solver`](https://mooseframework.inl.gov/docs/PRs/26412/coverage/external_petsc_solver)
- [`fluid_properties`](https://mooseframework.inl.gov/docs/PRs/26412/coverage/fluid_properties)
- [`fsi`](https://mooseframework.inl.gov/docs/PRs/26412/coverage/fsi)
- [`functional_expansion_tools`](https://mooseframework.inl.gov/docs/PRs/26412/coverage/functional_expansion_tools)
- [`geochemistry`](https://mooseframework.inl.gov/docs/PRs/26412/coverage/geochemistry)
- [`heat_transfer`](https://mooseframework.inl.gov/docs/PRs/26412/coverage/heat_transfer)
- [`level_set`](https://mooseframework.inl.gov/docs/PRs/26412/coverage/level_set)
- [`misc`](https://mooseframework.inl.gov/docs/PRs/26412/coverage/misc)
- [`navier_stokes`](https://mooseframework.inl.gov/docs/PRs/26412/coverage/navier_stokes)
- [`optimization`](https://mooseframework.inl.gov/docs/PRs/26412/coverage/optimization)
- [`peridynamics`](https://mooseframework.inl.gov/docs/PRs/26412/coverage/peridynamics)
- [`phase_field`](https://mooseframework.inl.gov/docs/PRs/26412/coverage/phase_field)
- [`porous_flow`](https://mooseframework.inl.gov/docs/PRs/26412/coverage/porous_flow)
- [`ray_tracing`](https://mooseframework.inl.gov/docs/PRs/26412/coverage/ray_tracing)
- [`rdg`](https://mooseframework.inl.gov/docs/PRs/26412/coverage/rdg)
- [`reactor`](https://mooseframework.inl.gov/docs/PRs/26412/coverage/reactor)
- [`richards`](https://mooseframework.inl.gov/docs/PRs/26412/coverage/richards)
- [`scalar_transport`](https://mooseframework.inl.gov/docs/PRs/26412/coverage/scalar_transport)
- [`solid_properties`](https://mooseframework.inl.gov/docs/PRs/26412/coverage/solid_properties)
- [`stochastic_tools`](https://mooseframework.inl.gov/docs/PRs/26412/coverage/stochastic_tools)
- [`tensor_mechanics`](https://mooseframework.inl.gov/docs/PRs/26412/coverage/tensor_mechanics)
- [`thermal_hydraulics`](https://mooseframework.inl.gov/docs/PRs/26412/coverage/thermal_hydraulics)
- [`xfem`](https://mooseframework.inl.gov/docs/PRs/26412/coverage/xfem)

</details>



This comment will be updated on new commits.

2024-01-05 00:11 UTC, lindsayad reviewed
The concept here sounds good to me, but I'm going to leave this review to @cticenhour

2024-01-05 15:56 UTC, cticenhour commented
Thanks @lindsayad. @GiudGiud are you done pushing to the PR? If so, I should be able to look at this sometime today between meetings.

2024-01-05 16:14 UTC, GiudGiud commented
yup done. Had to tackle one last little thing that s it

2024-01-05 16:46 UTC, cticenhour requested changes
Small tweaks to the new written doco, but otherwise good.

2024-01-05 16:46 UTC, cticenhour commented on modules/misc/doc/content/source/kernels/CoefDiffusion.md
> +# CoefDiffusion
Thanks for moving these off the old template!

2024-01-05 16:46 UTC, cticenhour commented on modules/misc/doc/content/source/kernels/ThermoDiffusion.md
> +where $S$ is Soret diffusion coefficient which is typically a combination of the
```suggestion
where $S$ is Soret diffusion coefficient, which is typically a combination of the
```

2024-01-05 17:06 UTC, GiudGiud commented
done

2024-01-05 17:15 UTC, cticenhour approved these changes

2024-01-05 20:34 UTC, merged

2024-01-05 20:34 UTC, GiudGiud commented
Thanks for the review!