Update ParallelSubsetSimulation docs reference #26468
idaholab/moose pull request #26469
Opened 2024-01-03 18:02 UTC by ke7kto

References #26468, clarifying the usage of the `ParallelSubsetSimulation` class for a specific use case.

## Reason
It took me a long time to figure out how to use the class in the stochastic tools module. Want to save time for future users

## Design
Added some details in the "interaction with `AdaptiveMonteCarloDecision`" section to cover pitfalls I encountered.

## Impact
Should be very low impact on codebase.

2024-01-03 18:47 UTC, loganharbour requested changes

2024-01-03 18:47 UTC, loganharbour commented on modules/stochastic_tools/doc/content/source/samplers/ParallelSubsetSimulation.md
> +If the parameter `use_absolute_value = true`, the absolute value of `output_reporter` will be maximized.
Please use the `[!param](/Samplers/ParallelSubsetSimulation/param_name)` syntax for all referenced parameters

2024-01-03 20:35 UTC, loganharbour approved these changes
Thanks for getting the other parameters too!

2024-01-03 22:25 UTC, moosebuild commented
Job [Documentation](https://civet.inl.gov/job/1976565/) on a87b694 wanted to post the following:

View the site [here](https://mooseframework.inl.gov/docs/PRs/26469/site)

This comment will be updated on new commits.

2024-01-09 22:17 UTC, grmnptr approved these changes

2024-01-09 23:04 UTC, grmnptr commented
Thanks for the additions!

2024-01-09 23:04 UTC, merged