26493 moosetest conda
idaholab/moose pull request #26526
Opened 2024-01-10 13:35 UTC by milljm

Add `moose_test-opt` to the Conda MOOSE package.

Also using this PR to troubleshot the pesky `libwasp` library missing. There are actually many more libraries missing. But libWasp happens to be the first discovered.

2024-01-10 14:23 UTC, loganharbour commented
I don't think the issue you have tagged for the test skipping is valid; we should make an issue with the problem not the issue that's set to just make things work

2024-01-10 14:25 UTC, loganharbour commented
many of these are already skipped and have a proper issue, looks like you just had an old moose:

```
  [json_full]
    type = 'PythonUnitTest'
    input = 'test_json.py'
    test_case = "TestFull"
    max_buffer_size = -1
    issues = '#7855 #7661 #2881 #10839 #12455'
    design = 'JsonInputFileFormatter.md MooseApp.md'
    installation_type = in_tree # see #26480
    requirement = 'The system shall be able to dump input file syntax in JSON format.'
    # Allow tests to pass when run out of tree #26493
    installation_type = in_tree
  []
```

https://github.com/idaholab/moose/blob/8286ffb88a987d3bacb7ad58b18620f2c4632541/test/tests/outputs/format/tests for example

2024-01-10 14:32 UTC, milljm commented
> many of these are already skipped and have a proper issue, looks like you just had an old moose:

Yes, I figured i missed a few

2024-01-10 14:32 UTC, milljm commented
> I don't think the issue you have tagged for the test skipping is valid; we should make an issue with the problem not the issue that's set to just make things work

I don't even know what the problem is. What issue shall I use?

2024-01-10 17:07 UTC, moosebuild commented
Job [Coverage](https://civet.inl.gov/job/1991379/) on aa1290b wanted to post the following:


## Framework coverage

<table>
  <thead>
    <tr>
      <th></th>
      <th>8ac5e2</th>
      <th colspan=4>#26526 aa1290</th>
    </tr>
    <tr>
      <th></th>
      <th>Total</th>
      <th>Total</th>
      <th>+/-</th>
      <th>New</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><b>Rate</b></td>
      <td>85.09%</td>
      <td>85.09%</td>
      <td>-0.00%</td>
      <td>-</td>
    </tr>
    <tr>
      <td><b>Hits</b></td>
      <td>98549</td>
      <td>98548</td>
      <td>-1</td>
      <td>0</td>
    </tr>
    <tr>
      <td><b>Misses</b></td>
      <td>17271</td>
      <td>17272</td>
      <td>+1</td>
      <td>0</td>
    </tr>
  </tbody>
</table>

[Diff coverage report](https://mooseframework.inl.gov/docs/PRs/26526/coverage_diff/framework)

[Full coverage report](https://mooseframework.inl.gov/docs/PRs/26526/coverage/framework)


## Modules coverage

Coverage did not change

## Full coverage reports

<details>
<summary>Reports</summary>

- [`framework`](https://mooseframework.inl.gov/docs/PRs/26526/coverage/framework)
- [`chemical_reactions`](https://mooseframework.inl.gov/docs/PRs/26526/coverage/chemical_reactions)
- [`combined`](https://mooseframework.inl.gov/docs/PRs/26526/coverage/combined)
- [`contact`](https://mooseframework.inl.gov/docs/PRs/26526/coverage/contact)
- [`electromagnetics`](https://mooseframework.inl.gov/docs/PRs/26526/coverage/electromagnetics)
- [`external_petsc_solver`](https://mooseframework.inl.gov/docs/PRs/26526/coverage/external_petsc_solver)
- [`fluid_properties`](https://mooseframework.inl.gov/docs/PRs/26526/coverage/fluid_properties)
- [`fsi`](https://mooseframework.inl.gov/docs/PRs/26526/coverage/fsi)
- [`functional_expansion_tools`](https://mooseframework.inl.gov/docs/PRs/26526/coverage/functional_expansion_tools)
- [`geochemistry`](https://mooseframework.inl.gov/docs/PRs/26526/coverage/geochemistry)
- [`heat_transfer`](https://mooseframework.inl.gov/docs/PRs/26526/coverage/heat_transfer)
- [`level_set`](https://mooseframework.inl.gov/docs/PRs/26526/coverage/level_set)
- [`misc`](https://mooseframework.inl.gov/docs/PRs/26526/coverage/misc)
- [`navier_stokes`](https://mooseframework.inl.gov/docs/PRs/26526/coverage/navier_stokes)
- [`optimization`](https://mooseframework.inl.gov/docs/PRs/26526/coverage/optimization)
- [`peridynamics`](https://mooseframework.inl.gov/docs/PRs/26526/coverage/peridynamics)
- [`phase_field`](https://mooseframework.inl.gov/docs/PRs/26526/coverage/phase_field)
- [`porous_flow`](https://mooseframework.inl.gov/docs/PRs/26526/coverage/porous_flow)
- [`ray_tracing`](https://mooseframework.inl.gov/docs/PRs/26526/coverage/ray_tracing)
- [`rdg`](https://mooseframework.inl.gov/docs/PRs/26526/coverage/rdg)
- [`reactor`](https://mooseframework.inl.gov/docs/PRs/26526/coverage/reactor)
- [`richards`](https://mooseframework.inl.gov/docs/PRs/26526/coverage/richards)
- [`scalar_transport`](https://mooseframework.inl.gov/docs/PRs/26526/coverage/scalar_transport)
- [`solid_properties`](https://mooseframework.inl.gov/docs/PRs/26526/coverage/solid_properties)
- [`stochastic_tools`](https://mooseframework.inl.gov/docs/PRs/26526/coverage/stochastic_tools)
- [`tensor_mechanics`](https://mooseframework.inl.gov/docs/PRs/26526/coverage/tensor_mechanics)
- [`thermal_hydraulics`](https://mooseframework.inl.gov/docs/PRs/26526/coverage/thermal_hydraulics)
- [`xfem`](https://mooseframework.inl.gov/docs/PRs/26526/coverage/xfem)

</details>



This comment will be updated on new commits.

2024-01-11 17:42 UTC, milljm commented
Looks like you nailed all the skips I needed. I had a few extras. I was expecting those to fail, but they were not. Fortunate surprise.

2024-01-15 13:08 UTC, milljm commented
This is finished. Just waiting for approval.

2024-01-15 16:59 UTC, cticenhour requested changes
Since Logan is out this week, I will take this over. Considering his comment about an appropriate issue number in an earlier commit and the fact that these changes were eventually reverted anyway, could you squash this into one commit? Please also change the title to be more descriptive of the changes, and note in the first description comment as to whether this closes #26493.

2024-01-15 19:33 UTC, cticenhour approved these changes

2024-01-15 20:36 UTC, merged