Update docker documentation
idaholab/moose pull request #26582
Opened 2024-01-17 22:46 UTC by loganharbour

Closes #26423

2024-01-17 22:48 UTC, loganharbour commented
@cticenhour this is ready.

It's not extremely detailed, but it's better than the blatantly wrong content we have right now.

2024-01-17 22:54 UTC, cticenhour requested changes
Only two items, pending a look at the render.

2024-01-17 22:54 UTC, cticenhour commented on modules/doc/content/getting_started/installation/docker.md
> +If you are building another image from this one, you may need to source the file at `/environment` first to obtain the proper environment.
Let's make this a note alert to make it stand out.

2024-01-17 22:54 UTC, cticenhour commented on modules/doc/content/getting_started/installation/docker.md
> +This imaged is versioned based on the master hash of MOOSE that it was compiled with.
```suggestion
This image is versioned based on the master hash of MOOSE that it was compiled with.
```

2024-01-18 00:49 UTC, moosebuild commented
Job [Documentation](https://civet.inl.gov/job/2007179/) on 3242333 wanted to post the following:

View the site [here](https://mooseframework.inl.gov/docs/PRs/26582/site)

This comment will be updated on new commits.

2024-01-18 15:34 UTC, cticenhour approved these changes

2024-01-18 15:34 UTC, merged