THM home page improvements
idaholab/moose pull request #26678
Opened 2024-01-29 19:38 UTC by joshuahansel

This PR does the following:

- Closes various issues created by the JOSS paper review related to THM documentation
- Makes the following improvements to THM home page:
  - Remove news
  - Clean up features/documentation
  - "Modeling guide" -> "Examples"
  - "V&V" -> "Test problems"

2024-01-29 22:19 UTC, moosebuild commented
Job [Documentation](https://civet.inl.gov/job/2032464/) on f12333b wanted to post the following:

View the site [here](https://mooseframework.inl.gov/docs/PRs/26678/site)

This comment will be updated on new commits.

2024-01-30 16:04 UTC, licharlot requested changes

2024-01-30 17:22 UTC, joshuahansel commented
https://github.inl.gov/ncrc/relap-7/pull/2561 for fixing the RELAP-7 doc failure. It can be merged before this one.

2024-01-30 17:31 UTC, licharlot approved these changes

2024-01-30 20:58 UTC, merged