extending MooseVariableFV to face and qp for transient two-phase flow…
idaholab/moose pull request #26774
Opened 2024-02-09 09:09 UTC by tanoret

Closes #26773

2024-02-09 09:10 UTC, tanoret commented
@grmnptr @MengnanLi91 I ended up coding this since I needed it for the Euler-Euler two phase model. Thanks!

2024-02-09 10:53 UTC, moosebuild commented
Job [Documentation](https://civet.inl.gov/job/2055436/) on 88c62e6 wanted to post the following:

View the site [here](https://mooseframework.inl.gov/docs/PRs/26774/site)

This comment will be updated on new commits.

2024-02-09 11:51 UTC, moosebuild commented
Job [Coverage](https://civet.inl.gov/job/2055451/) on 88c62e6 wanted to post the following:


## Framework coverage

<table>
  <thead>
    <tr>
      <th></th>
      <th>27c904</th>
      <th colspan=4>#26774 88c62e</th>
    </tr>
    <tr>
      <th></th>
      <th>Total</th>
      <th>Total</th>
      <th>+/-</th>
      <th>New</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><b>Rate</b></td>
      <td>85.26%</td>
      <td>85.24%</td>
      <td>-0.01%</td>
      <td>0.00%</td>
    </tr>
    <tr>
      <td><b>Hits</b></td>
      <td>100399</td>
      <td>100398</td>
      <td>-1</td>
      <td>0</td>
    </tr>
    <tr>
      <td><b>Misses</b></td>
      <td>17358</td>
      <td>17378</td>
      <td>+20</td>
      <td>19</td>
    </tr>
  </tbody>
</table>

[Diff coverage report](https://mooseframework.inl.gov/docs/PRs/26774/coverage_diff/framework)

[Full coverage report](https://mooseframework.inl.gov/docs/PRs/26774/coverage/framework)


## Modules coverage

### Navier stokes

<table>
  <thead>
    <tr>
      <th></th>
      <th>27c904</th>
      <th colspan=4>#26774 88c62e</th>
    </tr>
    <tr>
      <th></th>
      <th>Total</th>
      <th>Total</th>
      <th>+/-</th>
      <th>New</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><b>Rate</b></td>
      <td>84.76%</td>
      <td>84.77%</td>
      <td>+0.01%</td>
      <td>-</td>
    </tr>
    <tr>
      <td><b>Hits</b></td>
      <td>14577</td>
      <td>14579</td>
      <td>+2</td>
      <td>0</td>
    </tr>
    <tr>
      <td><b>Misses</b></td>
      <td>2621</td>
      <td>2619</td>
      <td>-2</td>
      <td>0</td>
    </tr>
  </tbody>
</table>

[Diff coverage report](https://mooseframework.inl.gov/docs/PRs/26774/coverage_diff/navier_stokes)

[Full coverage report](https://mooseframework.inl.gov/docs/PRs/26774/coverage/navier_stokes)

## Full coverage reports

<details>
<summary>Reports</summary>

- [`framework`](https://mooseframework.inl.gov/docs/PRs/26774/coverage/framework)
- [`chemical_reactions`](https://mooseframework.inl.gov/docs/PRs/26774/coverage/chemical_reactions)
- [`combined`](https://mooseframework.inl.gov/docs/PRs/26774/coverage/combined)
- [`contact`](https://mooseframework.inl.gov/docs/PRs/26774/coverage/contact)
- [`electromagnetics`](https://mooseframework.inl.gov/docs/PRs/26774/coverage/electromagnetics)
- [`external_petsc_solver`](https://mooseframework.inl.gov/docs/PRs/26774/coverage/external_petsc_solver)
- [`fluid_properties`](https://mooseframework.inl.gov/docs/PRs/26774/coverage/fluid_properties)
- [`fsi`](https://mooseframework.inl.gov/docs/PRs/26774/coverage/fsi)
- [`functional_expansion_tools`](https://mooseframework.inl.gov/docs/PRs/26774/coverage/functional_expansion_tools)
- [`geochemistry`](https://mooseframework.inl.gov/docs/PRs/26774/coverage/geochemistry)
- [`heat_transfer`](https://mooseframework.inl.gov/docs/PRs/26774/coverage/heat_transfer)
- [`level_set`](https://mooseframework.inl.gov/docs/PRs/26774/coverage/level_set)
- [`misc`](https://mooseframework.inl.gov/docs/PRs/26774/coverage/misc)
- [`navier_stokes`](https://mooseframework.inl.gov/docs/PRs/26774/coverage/navier_stokes)
- [`optimization`](https://mooseframework.inl.gov/docs/PRs/26774/coverage/optimization)
- [`peridynamics`](https://mooseframework.inl.gov/docs/PRs/26774/coverage/peridynamics)
- [`phase_field`](https://mooseframework.inl.gov/docs/PRs/26774/coverage/phase_field)
- [`porous_flow`](https://mooseframework.inl.gov/docs/PRs/26774/coverage/porous_flow)
- [`ray_tracing`](https://mooseframework.inl.gov/docs/PRs/26774/coverage/ray_tracing)
- [`rdg`](https://mooseframework.inl.gov/docs/PRs/26774/coverage/rdg)
- [`reactor`](https://mooseframework.inl.gov/docs/PRs/26774/coverage/reactor)
- [`richards`](https://mooseframework.inl.gov/docs/PRs/26774/coverage/richards)
- [`scalar_transport`](https://mooseframework.inl.gov/docs/PRs/26774/coverage/scalar_transport)
- [`solid_properties`](https://mooseframework.inl.gov/docs/PRs/26774/coverage/solid_properties)
- [`stochastic_tools`](https://mooseframework.inl.gov/docs/PRs/26774/coverage/stochastic_tools)
- [`tensor_mechanics`](https://mooseframework.inl.gov/docs/PRs/26774/coverage/tensor_mechanics)
- [`thermal_hydraulics`](https://mooseframework.inl.gov/docs/PRs/26774/coverage/thermal_hydraulics)
- [`xfem`](https://mooseframework.inl.gov/docs/PRs/26774/coverage/xfem)

</details>

## Warnings

- `framework` new line coverage rate 0.00% is less than the suggested 90.0%



This comment will be updated on new commits.

2024-02-09 15:17 UTC, GiudGiud commented on framework/src/variables/MooseVariableFV.C
> +    return evaluateDot(elem_arg, state);
for whoever goes debugging orders of convergence of time schemes in FV one day

2024-02-09 23:06 UTC, tanoret commented on framework/src/variables/MooseVariableFV.C
> +    return evaluateDot(elem_arg, state);
Something like this?

    // For extrapolated boundary faces we take the value if the time dervative at the cell in
    // contact with the face

2024-02-10 00:09 UTC, GiudGiud commented on framework/src/variables/MooseVariableFV.C
> +    return evaluateDot(elem_arg, state);
yeah
```
// For extrapolated boundary faces, note that we take the value of the time derivative at the cell in
// contact with the face
```

2024-02-10 03:27 UTC, lindsayad requested changes, later dismissed
Nice to see new dot overloads added

2024-02-10 03:27 UTC, lindsayad commented on framework/src/variables/MooseVariableFV.C
> +    return ADReal(0.0); // No time derivative is boudnary value is set
```suggestion
    return ADReal(0.0); // No time derivative if boundary value is set
```

2024-02-10 03:27 UTC, lindsayad commented on framework/src/variables/MooseVariableFV.C
> +                           /*one_is_elem*/ elem_one_is_fi_elem);
I feel like this should use the interpolation/limiting-type specified in the `FaceArg`

2024-02-10 07:25 UTC, lindsayad commented
@tanoret for some reason I can't easily submit a pull request to your branch; I can't select your fork as a base for a pull request 😦 So I've pushed [c9ccea2](https://github.com/idaholab/moose/pull/26774/commits/c9ccea213a22905e4e249637e2bacde063cdc68d) directly to your branch. See what you think of it

2024-02-11 05:57 UTC, tanoret commented
> @tanoret for some reason I can't easily submit a pull request to your branch; I can't select your fork as a base for a pull request 😦 So I've pushed [c9ccea2](https://github.com/idaholab/moose/pull/26774/commits/c9ccea213a22905e4e249637e2bacde063cdc68d) directly to your branch. See what you think of it

Thanks @lindsayad! Awesome work!

2024-02-12 15:11 UTC, GiudGiud commented on framework/include/base/MooseFunctor.h
> +template <typename T>
docstrings pls

2024-02-12 15:15 UTC, GiudGiud approved these changes

2024-02-12 19:01 UTC, moosebuild commented
Job [OpenMPI](https://civet.inl.gov/job/2058011/) on 0401576 : invalidated by @MengnanLi91

seems irrelevant test failure

2024-02-12 19:40 UTC, merged