Patched multiple procs writing to same file
idaholab/moose pull request #26936
Opened 2024-02-29 23:32 UTC by pbehne

Console objects have a parameter 'output_file', that when true, writes console output to a file. Parallel simulations would write information from all processors to the same file, which can lead to bad behavior. This commit introduces a patch that only writes console content from the head proc to the file. In the case that --keep-cout is passed to the executable, each proc writes its console content to a separate file. The same bahavior can be achieved without setting output_file to true by instead passing '--keep-cout --redirect-stdout' to the executable.

Closes Ref #26174.

2024-03-01 01:24 UTC, moosebuild commented
Job [Documentation](https://civet.inl.gov/job/2087667/) on 051de27 wanted to post the following:

View the site [here](https://mooseframework.inl.gov/docs/PRs/26936/site)

This comment will be updated on new commits.

2024-03-01 05:50 UTC, lindsayad commented
I would rebase this on next so that you get more targets passing (with all those solid mechanics changes)

2024-03-01 15:30 UTC, pbehne commented
Hmm, I rebased to upstream/next and force pushed, but for some reason, that's not showing up on this PR. Any idea why?

2024-03-04 19:03 UTC, moosebuild commented
Job [Coverage](https://civet.inl.gov/job/2092824/) on 1c61049 wanted to post the following:


## Framework coverage

<table>
  <thead>
    <tr>
      <th></th>
      <th>550348</th>
      <th colspan=4>#26936 1c6104</th>
    </tr>
    <tr>
      <th></th>
      <th>Total</th>
      <th>Total</th>
      <th>+/-</th>
      <th>New</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><b>Rate</b></td>
      <td>85.29%</td>
      <td>85.29%</td>
      <td>+0.00%</td>
      <td>100.00%</td>
    </tr>
    <tr>
      <td><b>Hits</b></td>
      <td>100890</td>
      <td>100898</td>
      <td>+8</td>
      <td>11</td>
    </tr>
    <tr>
      <td><b>Misses</b></td>
      <td>17401</td>
      <td>17402</td>
      <td>+1</td>
      <td>0</td>
    </tr>
  </tbody>
</table>

[Diff coverage report](https://mooseframework.inl.gov/docs/PRs/26936/coverage_diff/framework)

[Full coverage report](https://mooseframework.inl.gov/docs/PRs/26936/coverage/framework)


## Modules coverage

Coverage did not change

## Full coverage reports

<details>
<summary>Reports</summary>

- [`framework`](https://mooseframework.inl.gov/docs/PRs/26936/coverage/framework)
- [`chemical_reactions`](https://mooseframework.inl.gov/docs/PRs/26936/coverage/chemical_reactions)
- [`combined`](https://mooseframework.inl.gov/docs/PRs/26936/coverage/combined)
- [`contact`](https://mooseframework.inl.gov/docs/PRs/26936/coverage/contact)
- [`electromagnetics`](https://mooseframework.inl.gov/docs/PRs/26936/coverage/electromagnetics)
- [`external_petsc_solver`](https://mooseframework.inl.gov/docs/PRs/26936/coverage/external_petsc_solver)
- [`fluid_properties`](https://mooseframework.inl.gov/docs/PRs/26936/coverage/fluid_properties)
- [`fsi`](https://mooseframework.inl.gov/docs/PRs/26936/coverage/fsi)
- [`functional_expansion_tools`](https://mooseframework.inl.gov/docs/PRs/26936/coverage/functional_expansion_tools)
- [`geochemistry`](https://mooseframework.inl.gov/docs/PRs/26936/coverage/geochemistry)
- [`heat_transfer`](https://mooseframework.inl.gov/docs/PRs/26936/coverage/heat_transfer)
- [`level_set`](https://mooseframework.inl.gov/docs/PRs/26936/coverage/level_set)
- [`misc`](https://mooseframework.inl.gov/docs/PRs/26936/coverage/misc)
- [`navier_stokes`](https://mooseframework.inl.gov/docs/PRs/26936/coverage/navier_stokes)
- [`optimization`](https://mooseframework.inl.gov/docs/PRs/26936/coverage/optimization)
- [`peridynamics`](https://mooseframework.inl.gov/docs/PRs/26936/coverage/peridynamics)
- [`phase_field`](https://mooseframework.inl.gov/docs/PRs/26936/coverage/phase_field)
- [`porous_flow`](https://mooseframework.inl.gov/docs/PRs/26936/coverage/porous_flow)
- [`ray_tracing`](https://mooseframework.inl.gov/docs/PRs/26936/coverage/ray_tracing)
- [`rdg`](https://mooseframework.inl.gov/docs/PRs/26936/coverage/rdg)
- [`reactor`](https://mooseframework.inl.gov/docs/PRs/26936/coverage/reactor)
- [`richards`](https://mooseframework.inl.gov/docs/PRs/26936/coverage/richards)
- [`scalar_transport`](https://mooseframework.inl.gov/docs/PRs/26936/coverage/scalar_transport)
- [`solid_mechanics`](https://mooseframework.inl.gov/docs/PRs/26936/coverage/solid_mechanics)
- [`solid_properties`](https://mooseframework.inl.gov/docs/PRs/26936/coverage/solid_properties)
- [`stochastic_tools`](https://mooseframework.inl.gov/docs/PRs/26936/coverage/stochastic_tools)
- [`thermal_hydraulics`](https://mooseframework.inl.gov/docs/PRs/26936/coverage/thermal_hydraulics)
- [`xfem`](https://mooseframework.inl.gov/docs/PRs/26936/coverage/xfem)

</details>



This comment will be updated on new commits.

2024-03-04 23:32 UTC, GiudGiud commented on test/tests/outputs/console/tests
> +    max_parallel = 2
```suggestion
```

2024-03-04 23:32 UTC, GiudGiud commented on test/tests/outputs/console/tests
> +    max_parallel = 2
```suggestion
```

2024-03-04 23:32 UTC, GiudGiud commented on test/tests/outputs/console/tests
> +    requirement = "The system shall support outputting all processors' console information to separate files when run in parallel with --keep-cout."
```suggestion
    requirement = "The system shall support outputting all processors' console information to separate files when run in parallel with the --keep-cout command line option."
```

2024-03-04 23:33 UTC, GiudGiud requested changes
small changes. This is going to be convenient thanks for the fix

2024-03-05 17:05 UTC, GiudGiud approved these changes

2024-03-05 17:05 UTC, merged

2024-03-05 17:05 UTC, GiudGiud commented
Thanks for the fix!