Fix website moose-dev version
idaholab/moose pull request #26958
Opened 2024-03-04 15:39 UTC by milljm

The version being displayed is not correct. This PR corrects it.

Closes #26957

2024-03-04 17:36 UTC, moosebuild commented
Job [Documentation](https://civet.inl.gov/job/2092663/) on 17e58e0 wanted to post the following:

View the site [here](https://mooseframework.inl.gov/docs/PRs/26958/site)

This comment will be updated on new commits.

2024-03-04 23:28 UTC, GiudGiud approved these changes

2024-03-05 02:10 UTC, dschwen requested changes
Making sure this does not get merged prematurely. See https://github.com/idaholab/moose/pull/26944#issuecomment-1977787609

2024-03-05 14:17 UTC, milljm commented
Closing in favor of https://github.com/idaholab/moose/pull/26944

2024-03-05 14:17 UTC, closed without merging