Add ability to output specific data
idaholab/moose pull request #26982
Opened 2024-03-05 17:20 UTC by loganharbour

Closes #26979

@cticenhour - this is in support of FENIX

2024-03-05 17:23 UTC, loganharbour commented
FYI @gsgall - adds `output_data_names` and `output_aux_data_names`

2024-03-05 17:23 UTC, cticenhour commented
Great - will make a note to come back and check the CI results later today when I have time for the review. Thanks!

2024-03-05 19:16 UTC, moosebuild commented
Job [Documentation](https://civet.inl.gov/job/2095401/) on 259ec17 wanted to post the following:

View the site [here](https://mooseframework.inl.gov/docs/PRs/26982/site)

This comment will be updated on new commits.

2024-03-05 21:25 UTC, loganharbour commented
Good to go now.

2024-03-05 23:50 UTC, moosebuild commented
Job [Coverage](https://civet.inl.gov/job/2096226/) on ed91f33 wanted to post the following:


## Framework coverage

Coverage did not change


## Modules coverage

### Phase field

<table>
  <thead>
    <tr>
      <th></th>
      <th>41aaba</th>
      <th colspan=4>#26982 ed91f3</th>
    </tr>
    <tr>
      <th></th>
      <th>Total</th>
      <th>Total</th>
      <th>+/-</th>
      <th>New</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><b>Rate</b></td>
      <td>85.69%</td>
      <td>85.68%</td>
      <td>-0.01%</td>
      <td>-</td>
    </tr>
    <tr>
      <td><b>Hits</b></td>
      <td>13187</td>
      <td>13186</td>
      <td>-1</td>
      <td>0</td>
    </tr>
    <tr>
      <td><b>Misses</b></td>
      <td>2202</td>
      <td>2203</td>
      <td>+1</td>
      <td>0</td>
    </tr>
  </tbody>
</table>

[Diff coverage report](https://mooseframework.inl.gov/docs/PRs/26982/coverage_diff/phase_field)

[Full coverage report](https://mooseframework.inl.gov/docs/PRs/26982/coverage/phase_field)

### Ray tracing

<table>
  <thead>
    <tr>
      <th></th>
      <th>41aaba</th>
      <th colspan=4>#26982 ed91f3</th>
    </tr>
    <tr>
      <th></th>
      <th>Total</th>
      <th>Total</th>
      <th>+/-</th>
      <th>New</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><b>Rate</b></td>
      <td>95.29%</td>
      <td>95.28%</td>
      <td>-0.01%</td>
      <td>97.83%</td>
    </tr>
    <tr>
      <td><b>Hits</b></td>
      <td>4326</td>
      <td>4358</td>
      <td>+32</td>
      <td>90</td>
    </tr>
    <tr>
      <td><b>Misses</b></td>
      <td>214</td>
      <td>216</td>
      <td>+2</td>
      <td>2</td>
    </tr>
  </tbody>
</table>

[Diff coverage report](https://mooseframework.inl.gov/docs/PRs/26982/coverage_diff/ray_tracing)

[Full coverage report](https://mooseframework.inl.gov/docs/PRs/26982/coverage/ray_tracing)

## Full coverage reports

<details>
<summary>Reports</summary>

- [`framework`](https://mooseframework.inl.gov/docs/PRs/26982/coverage/framework)
- [`chemical_reactions`](https://mooseframework.inl.gov/docs/PRs/26982/coverage/chemical_reactions)
- [`combined`](https://mooseframework.inl.gov/docs/PRs/26982/coverage/combined)
- [`contact`](https://mooseframework.inl.gov/docs/PRs/26982/coverage/contact)
- [`electromagnetics`](https://mooseframework.inl.gov/docs/PRs/26982/coverage/electromagnetics)
- [`external_petsc_solver`](https://mooseframework.inl.gov/docs/PRs/26982/coverage/external_petsc_solver)
- [`fluid_properties`](https://mooseframework.inl.gov/docs/PRs/26982/coverage/fluid_properties)
- [`fsi`](https://mooseframework.inl.gov/docs/PRs/26982/coverage/fsi)
- [`functional_expansion_tools`](https://mooseframework.inl.gov/docs/PRs/26982/coverage/functional_expansion_tools)
- [`geochemistry`](https://mooseframework.inl.gov/docs/PRs/26982/coverage/geochemistry)
- [`heat_transfer`](https://mooseframework.inl.gov/docs/PRs/26982/coverage/heat_transfer)
- [`level_set`](https://mooseframework.inl.gov/docs/PRs/26982/coverage/level_set)
- [`misc`](https://mooseframework.inl.gov/docs/PRs/26982/coverage/misc)
- [`navier_stokes`](https://mooseframework.inl.gov/docs/PRs/26982/coverage/navier_stokes)
- [`optimization`](https://mooseframework.inl.gov/docs/PRs/26982/coverage/optimization)
- [`peridynamics`](https://mooseframework.inl.gov/docs/PRs/26982/coverage/peridynamics)
- [`phase_field`](https://mooseframework.inl.gov/docs/PRs/26982/coverage/phase_field)
- [`porous_flow`](https://mooseframework.inl.gov/docs/PRs/26982/coverage/porous_flow)
- [`ray_tracing`](https://mooseframework.inl.gov/docs/PRs/26982/coverage/ray_tracing)
- [`rdg`](https://mooseframework.inl.gov/docs/PRs/26982/coverage/rdg)
- [`reactor`](https://mooseframework.inl.gov/docs/PRs/26982/coverage/reactor)
- [`richards`](https://mooseframework.inl.gov/docs/PRs/26982/coverage/richards)
- [`scalar_transport`](https://mooseframework.inl.gov/docs/PRs/26982/coverage/scalar_transport)
- [`solid_mechanics`](https://mooseframework.inl.gov/docs/PRs/26982/coverage/solid_mechanics)
- [`solid_properties`](https://mooseframework.inl.gov/docs/PRs/26982/coverage/solid_properties)
- [`stochastic_tools`](https://mooseframework.inl.gov/docs/PRs/26982/coverage/stochastic_tools)
- [`thermal_hydraulics`](https://mooseframework.inl.gov/docs/PRs/26982/coverage/thermal_hydraulics)
- [`xfem`](https://mooseframework.inl.gov/docs/PRs/26982/coverage/xfem)

</details>



This comment will be updated on new commits.

2024-03-06 20:12 UTC, loganharbour commented
OpenMPI failure is unrelated... sigh

2024-03-07 21:44 UTC, cticenhour requested changes
A few small things. Sorry for the delay. Nearly finished this and then got distracted and didn't come back for a while.

2024-03-07 21:44 UTC, cticenhour commented on modules/ray_tracing/test/tests/outputs/ray_tracing_mesh_output/tests
> +      detail = 'when nodal data is requested to be output but segment-wise information is not cached,'
```suggestion
      detail = 'nodal data is requested to be output but segment-wise information is not cached,'
```

2024-03-07 21:44 UTC, cticenhour commented on modules/ray_tracing/test/tests/outputs/ray_tracing_mesh_output/tests
> +      detail = 'when all data and specific data are both requested,'
```suggestion
      detail = 'all data and specific data are both requested,'
```

2024-03-07 21:44 UTC, cticenhour commented on modules/ray_tracing/test/tests/outputs/ray_tracing_mesh_output/tests
> +      detail = 'when all aux data and specific aux data are both requested'
```suggestion
      detail = 'all aux data and specific aux data are both requested'
```

2024-03-14 14:52 UTC, loganharbour commented
OpenMPI failure is unrelated.

2024-03-14 14:53 UTC, cticenhour approved these changes
OpenMPI failure is unrelated. 

@gsgall - tagging you for awareness that this is merged in.

2024-03-14 14:53 UTC, merged