Add Interpolation Scheme (Steinbach-Apel's scheme)
idaholab/moose pull request #27060
Opened 2024-03-12 09:33 UTC by WooseobKHU

#closes #27056

## Reason

## Design

## Impact

2024-03-12 15:43 UTC, GiudGiud commented
@dschwen who is a good person to assign to review this?

2024-03-15 00:05 UTC, GiudGiud commented
@bwspenc same question

2024-03-21 22:45 UTC, GiudGiud commented
@laagesen

2024-03-22 15:06 UTC, laagesen commented
@simopier this is related to your recent manuscript right? If so can you please review?

2024-04-02 22:39 UTC, simopier requested changes
I added some comments in the code, but I have two major requests before this PR can be approved:
1. The new classes are not currently being tested. This PR needs to include thorough testing of the new capability. Tests should be very simple, test the capability and demonstrate that they do exactly what they were developed for. Tests also need to be run under 2 seconds. Please add a series of test to verify all the new capabilities being added in this PR. Inspiration can be found in MOOSE as many similar classes have associated tests. 
2. The new capabilities need to be documented. New documentation pages need to be created for each new class to describe the new capabilities and explain users how to use them. Again, inspiration can be found in MOOSE as many similar classes have associated  documentation. 

Thank you!

2024-04-02 22:39 UTC, simopier commented on modules/solid_mechanics/include/materials/ComputeInverseRotatedElasticityTensorBase.h
> +protected:
```suggestion
```

2024-04-02 22:39 UTC, simopier commented on modules/solid_mechanics/include/materials/ComputeSteinbachApelStrain.h
> +
```suggestion

/// derivative of the switching function
```

2024-04-02 22:39 UTC, simopier commented on modules/solid_mechanics/include/materials/ComputeSteinbachApelStrain.h
> +  const MaterialProperty<Real> & _h_eta;
```suggestion
  /// Switching function
  const MaterialProperty<Real> & _h_eta;
```

2024-04-02 22:39 UTC, simopier commented on modules/solid_mechanics/include/materials/ComputeSteinbachApelStrain.h
> +  std::string _base_B;
Please add a comment to describe what this is.

2024-04-02 22:39 UTC, simopier commented on modules/solid_mechanics/include/materials/ComputeSteinbachApelStrain.h
> +  MaterialProperty<RankFourTensor> & _ref_inv;
Please add a comment to describe what this is.

2024-04-02 22:39 UTC, simopier commented on modules/solid_mechanics/include/materials/ComputeSteinbachApelStrain.h
> +  MaterialProperty<RankFourTensor> & _identity;
```suggestion
  /// Identity matrix
  MaterialProperty<RankFourTensor> & _identity;
```

2024-04-02 22:39 UTC, simopier commented on modules/solid_mechanics/include/materials/ComputeSteinbachApelStrain.h
> +  float _identity_two[6][6];
Please add a comment to describe what this is.

2024-04-02 22:39 UTC, simopier commented on modules/solid_mechanics/include/materials/ComputeSteinbachApelStrain.h
> +  std::vector<const MaterialProperty<Real> *> _dh;
```suggestion
  std::vector<const MaterialProperty<Real> *> _dh_eta;
```

2024-04-02 22:39 UTC, simopier commented on modules/solid_mechanics/src/materials/ComputeComplianceTensorBase.C
> +  params.addParam<std::string>("base_name", "Optional parameter that allows the user to define ");
to define what?

2024-04-02 22:39 UTC, simopier commented on modules/solid_mechanics/src/materials/ComputeHarmonicElasticityTensor.C
> +      "h", "h", "Switching Function Material that provides h(eta)");
```suggestion
      "h", "h", "Switching function material that provides h(eta)");
```

2024-04-02 22:39 UTC, simopier commented on modules/solid_mechanics/src/materials/ComputeInverseElasticityTensor.C
> +  // This code is made for symmetric9
If this method does not work for other options than symmetric9, then it should return an error if another option is used.

2024-04-02 22:39 UTC, simopier commented on modules/solid_mechanics/src/materials/ComputeSteinbachApelStrain.C
> +      _compliance_tensor_A[_qp] * _elasticity_tensor_B[_qp] * _mechanical_strain_b[_qp];
Please comment the code to explain what is being done.

2024-04-02 22:39 UTC, simopier commented on modules/solid_mechanics/src/materials/TwoPhaseStrainMaterial.C
> +//* This file is part of the MOOSE framework
I'm surprised that this material class does not already exist.

2024-04-02 22:42 UTC, simopier commented
Also, the test are failing with the following errors. Make sure to initialize everything in the right order.

``` 
In file included from /data/civet1/build/moose/modules/solid_mechanics/build/unity_src/materials_Unity.C:68:
/data/civet1/build/moose/modules/solid_mechanics/src/materials/ComputeComplianceTensorBase.C:27:5: error: field '_compliance_tensor_name' will be initialized after field '_elasticity_tensor_name' [-Werror,-Wreorder-ctor]
    _compliance_tensor_name(_base_name + "compliance_tensor"),
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    _elasticity_tensor_name(_base_name + "elasticity_tensor"
/data/civet1/build/moose/modules/solid_mechanics/src/materials/ComputeComplianceTensorBase.C:41:16: note: in instantiation of member function 'ComputeComplianceTensorBaseTempl<false>::ComputeComplianceTensorBaseTempl' requested here
template class ComputeComplianceTensorBaseTempl<false>;
               ^
/data/civet1/build/moose/modules/solid_mechanics/src/materials/ComputeComplianceTensorBase.C:27:5: error: field '_compliance_tensor_name' will be initialized after field '_elasticity_tensor_name' [-Werror,-Wreorder-ctor]
    _compliance_tensor_name(_base_name + "compliance_tensor"),
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    _elasticity_tensor_name(_base_name + "elasticity_tensor"
/data/civet1/build/moose/modules/solid_mechanics/src/materials/ComputeComplianceTensorBase.C:42:16: note: in instantiation of member function 'ComputeComplianceTensorBaseTempl<true>::ComputeComplianceTensorBaseTempl' requested here
template class ComputeComplianceTensorBaseTempl<true>;
               ^
In file included from /data/civet1/build/moose/modules/solid_mechanics/build/unity_src/materials_Unity.C:97:
/data/civet1/build/moose/modules/solid_mechanics/src/materials/ComputeHarmonicElasticityTensor.C:39:5: error: initializer order does not match the declaration order [-Werror,-Wreorder-ctor]
    _base_name(isParamValid("base_name") ? getParam<std::string>("base_name") + "_" : ""),
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    _compliance(declareProperty<RankFourTensor>(_base_name + "compliance_tensor"))
/data/civet1/build/moose/modules/solid_mechanics/src/materials/ComputeHarmonicElasticityTensor.C:39:5: note: field '_base_name' will be initialized after field '_compliance'
    _base_name(isParamValid("base_name") ? getParam<std::string>("base_name") + "_" : ""),
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/data/civet1/build/moose/modules/solid_mechanics/src/materials/ComputeHarmonicElasticityTensor.C:41:5: note: field '_elasticity_name' will be initialized after field '_elasticity_tensor'
    _elasticity_name(_base_name + "elasticity_tensor"),
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/data/civet1/build/moose/modules/solid_mechanics/src/materials/ComputeHarmonicElasticityTensor.C:40:49: error: field '_base_name' is uninitialized when used here [-Werror,-Wuninitialized]
    _compliance(declareProperty<RankFourTensor>(_base_name + "compliance_tensor")),
                                                ^
/data/civet1/build/moose/modules/solid_mechanics/src/materials/ComputeHarmonicElasticityTensor.C:42:56: error: field '_base_name' is uninitialized when used here [-Werror,-Wuninitialized]
    _elasticity_tensor(declareProperty<RankFourTensor>(_base_name + "elasticity_tensor"))
                                                       ^
In file included from /data/civet1/build/moose/modules/solid_mechanics/build/unity_src/materials_Unity.C:128:
/data/civet1/build/moose/modules/solid_mechanics/src/materials/ComputeSteinbachApelStrain.C:30:5: error: initializer order does not match the declaration order [-Werror,-Wreorder-ctor]
    _h_eta(getMaterialProperty<Real>("h")),
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    _base_name(isParamValid("base_name") ? getParam<std::string>("base_name") + "_" : "")
/data/civet1/build/moose/modules/solid_mechanics/src/materials/ComputeSteinbachApelStrain.C:30:5: note: field '_h_eta' will be initialized after field '_base_name'
    _h_eta(getMaterialProperty<Real>("h")),
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/data/civet1/build/moose/modules/solid_mechanics/src/materials/ComputeSteinbachApelStrain.C:41:5: note: field '_ref_inv' will be initialized after field '_mechanical_strain_b'
    _ref_inv(declareProperty<RankFourTensor>("ref_inv")),
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/data/civet1/build/moose/modules/solid_mechanics/src/materials/ComputeSteinbachApelStrain.C:42:5: note: field '_mechanical_strain_b' will be initialized after field '_mechanical_strain_a'
    _mechanical_strain_b(declareProperty<RankTwoTensor>(_base_B + "mechanical_strain")),
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /data/civet1/build/moose/modules/solid_mechanics/build/unity_src/materials_Unity.C:144:
/data/civet1/build/moose/modules/solid_mechanics/src/materials/ElasticEnergyMaterialSAS.C:42:5: error: initializer order does not match the declaration order [-Werror,-Wreorder-ctor]
    _base_name(isParamValid("base_name") ? getParam<std::string>("base_name") + "_" : ""),
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    _prop_Fa(getMaterialProperty<Real>("fa_name"))
/data/civet1/build/moose/modules/solid_mechanics/src/materials/ElasticEnergyMaterialSAS.C:42:5: note: field '_base_name' will be initialized after field '_prop_Fa'
    _base_name(isParamValid("base_name") ? getParam<std::string>("base_name") + "_" : ""),
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/data/civet1/build/moose/modules/solid_mechanics/src/materials/ElasticEnergyMaterialSAS.C:49:5: note: field '_eigenstrain_B' will be initialized after field '_num_eta'
```

2024-04-18 04:47 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/2184947/) on 675c9d0 wanted to post the following:

Your code requires style changes.  

A patch was auto generated and copied [here](https://mooseframework.inl.gov/docs/PRs/27060/clang_format/style.patch)  
You can directly apply the patch by running, in the top level of your repository:

`curl -s https://mooseframework.inl.gov/docs/PRs/27060/clang_format/style.patch | git apply -v`  

Alternatively, with your repository up to date and in the top level of your repository:

`git clang-format a489a53bdb58ce7053c80cbebf6e2673da28fa3b`

2024-05-05 22:03 UTC, GiudGiud commented
Thanks for reviewing @simopier 
@WooseobKHU or @simopier please ping me when this is ready

2024-08-15 22:06 UTC, GiudGiud commented
@WooseobKHU @simopier any update? Or should we close this?

2024-08-16 06:33 UTC, WooseobKHU commented
I'm not in a position to do that right now, but I'll try to update when I
get a chance later. Thank you very much for your help.


2024년 8월 16일 (금) 오전 7:07, Guillaume Giudicelli ***@***.***>님이
작성:

> @WooseobKHU <https://github.com/WooseobKHU> @simopier
> <https://github.com/simopier> any update? Or should we close this?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/idaholab/moose/pull/27060#issuecomment-2292355567>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/A54H5W4NITN4JXLTRPJVQ5TZRURBHAVCNFSM6AAAAABER3KOUKVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDEOJSGM2TKNJWG4>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2025-06-08 05:42 UTC, closed without merging