Added description of wall time checkpoints to newsletter
idaholab/moose pull request #27108
Opened 2024-03-15 21:59 UTC by pbehne

Ref #26588

2024-03-15 22:05 UTC, cticenhour requested changes
Minor suggested adjustment noted below and one larger one I am noting here. This is an impactful enough change that it should be highlighted in the main MOOSE changes section as it's own subsection. Developers might miss it being in the bugfixes and minor changes list.

2024-03-15 22:05 UTC, cticenhour commented on modules/doc/content/newsletter/2024/2024_03.md
> +  output every 10 minutes of wall time, or when the current time step
```suggestion
  created every 10 minutes of wall time or when the current time step
```

2024-03-15 22:19 UTC, loganharbour commented
@pbehne was sitting next to me sans computer; asked for an apply

2024-03-15 22:21 UTC, cticenhour commented
There is a part of this review still remaining. In my opinion, this should be moved to it's own section so that it's highlighted a bit more.

2024-03-15 22:40 UTC, loganharbour approved these changes

2024-03-15 22:45 UTC, cticenhour approved these changes

2024-03-16 00:28 UTC, moosebuild commented
Job [Documentation](https://civet.inl.gov/job/2124065/) on 3351dff wanted to post the following:

View the site [here](https://mooseframework.inl.gov/docs/PRs/27108/site)

This comment will be updated on new commits.

2024-03-18 02:08 UTC, merged