Add a clear example of using the PT function FP
idaholab/moose pull request #27166
Opened 2024-03-21 18:50 UTC by GiudGiud

refs #21505

two people got confused, so we should be clear

2024-03-21 20:56 UTC, moosebuild commented
Job [Documentation](https://civet.inl.gov/job/2135053/) on 4f2826e wanted to post the following:

View the site [here](https://mooseframework.inl.gov/docs/PRs/27166/site)

This comment will be updated on new commits.

2024-03-21 21:44 UTC, moosebuild commented
Job [Coverage](https://civet.inl.gov/job/2135097/) on 4f2826e wanted to post the following:


## Framework coverage

<table>
  <thead>
    <tr>
      <th></th>
      <th>354ce6</th>
      <th colspan=4>#27166 4f2826</th>
    </tr>
    <tr>
      <th></th>
      <th>Total</th>
      <th>Total</th>
      <th>+/-</th>
      <th>New</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><b>Rate</b></td>
      <td>85.31%</td>
      <td>85.31%</td>
      <td>-0.00%</td>
      <td>-</td>
    </tr>
    <tr>
      <td><b>Hits</b></td>
      <td>101277</td>
      <td>101276</td>
      <td>-1</td>
      <td>0</td>
    </tr>
    <tr>
      <td><b>Misses</b></td>
      <td>17439</td>
      <td>17440</td>
      <td>+1</td>
      <td>0</td>
    </tr>
  </tbody>
</table>

[Diff coverage report](https://mooseframework.inl.gov/docs/PRs/27166/coverage_diff/framework)

[Full coverage report](https://mooseframework.inl.gov/docs/PRs/27166/coverage/framework)


## Modules coverage

Coverage did not change

## Full coverage reports

<details>
<summary>Reports</summary>

- [`framework`](https://mooseframework.inl.gov/docs/PRs/27166/coverage/framework)
- [`chemical_reactions`](https://mooseframework.inl.gov/docs/PRs/27166/coverage/chemical_reactions)
- [`combined`](https://mooseframework.inl.gov/docs/PRs/27166/coverage/combined)
- [`contact`](https://mooseframework.inl.gov/docs/PRs/27166/coverage/contact)
- [`electromagnetics`](https://mooseframework.inl.gov/docs/PRs/27166/coverage/electromagnetics)
- [`external_petsc_solver`](https://mooseframework.inl.gov/docs/PRs/27166/coverage/external_petsc_solver)
- [`fluid_properties`](https://mooseframework.inl.gov/docs/PRs/27166/coverage/fluid_properties)
- [`fsi`](https://mooseframework.inl.gov/docs/PRs/27166/coverage/fsi)
- [`functional_expansion_tools`](https://mooseframework.inl.gov/docs/PRs/27166/coverage/functional_expansion_tools)
- [`geochemistry`](https://mooseframework.inl.gov/docs/PRs/27166/coverage/geochemistry)
- [`heat_transfer`](https://mooseframework.inl.gov/docs/PRs/27166/coverage/heat_transfer)
- [`level_set`](https://mooseframework.inl.gov/docs/PRs/27166/coverage/level_set)
- [`misc`](https://mooseframework.inl.gov/docs/PRs/27166/coverage/misc)
- [`navier_stokes`](https://mooseframework.inl.gov/docs/PRs/27166/coverage/navier_stokes)
- [`optimization`](https://mooseframework.inl.gov/docs/PRs/27166/coverage/optimization)
- [`peridynamics`](https://mooseframework.inl.gov/docs/PRs/27166/coverage/peridynamics)
- [`phase_field`](https://mooseframework.inl.gov/docs/PRs/27166/coverage/phase_field)
- [`porous_flow`](https://mooseframework.inl.gov/docs/PRs/27166/coverage/porous_flow)
- [`ray_tracing`](https://mooseframework.inl.gov/docs/PRs/27166/coverage/ray_tracing)
- [`rdg`](https://mooseframework.inl.gov/docs/PRs/27166/coverage/rdg)
- [`reactor`](https://mooseframework.inl.gov/docs/PRs/27166/coverage/reactor)
- [`richards`](https://mooseframework.inl.gov/docs/PRs/27166/coverage/richards)
- [`scalar_transport`](https://mooseframework.inl.gov/docs/PRs/27166/coverage/scalar_transport)
- [`solid_mechanics`](https://mooseframework.inl.gov/docs/PRs/27166/coverage/solid_mechanics)
- [`solid_properties`](https://mooseframework.inl.gov/docs/PRs/27166/coverage/solid_properties)
- [`stochastic_tools`](https://mooseframework.inl.gov/docs/PRs/27166/coverage/stochastic_tools)
- [`thermal_hydraulics`](https://mooseframework.inl.gov/docs/PRs/27166/coverage/thermal_hydraulics)
- [`xfem`](https://mooseframework.inl.gov/docs/PRs/27166/coverage/xfem)

</details>



This comment will be updated on new commits.

2024-03-21 22:01 UTC, joshuahansel requested changes

2024-03-21 22:01 UTC, joshuahansel commented on modules/fluid_properties/test/tests/temperature_pressure_function/example.i
> +  [rho_avg_diff]
```suggestion
  [rho_diff]
```

2024-03-21 22:22 UTC, GiudGiud commented on modules/fluid_properties/test/tests/temperature_pressure_function/example.i
> +  # Note that diffs wont be settled until timestep 2 because of order of execution
ok done steady

2024-03-25 13:12 UTC, joshuahansel approved these changes

2024-03-25 14:30 UTC, GiudGiud commented
Test failure unrelated (in moose unit)

2024-03-25 14:30 UTC, merged