Interior penalty HDG
idaholab/moose pull request #27188
Opened 2024-03-25 17:23 UTC by lindsayad

Whereas https://github.com/idaholab/moose/pull/26477 is a mixed (value and gradient nonlinear variables) HDG method, this  is an interior penalty (no gradient nonlinear variable) one

2024-03-27 21:42 UTC, GiudGiud commented
did you think of how to differentiate them? Like prefix-wise maybe HDGIP ?

2024-03-27 23:22 UTC, lindsayad commented
I haven't. I'll give it some good thought at some point. Still heavily in the research phase

2025-02-04 00:39 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/2668026/), step Clang format on d1db7b4 wanted to post the following:

Your code requires style changes.  

A patch was auto generated and copied [here](https://mooseframework.inl.gov/docs/PRs/27188/clang_format/style.patch)  
You can directly apply the patch by running, in the top level of your repository:

`curl -s https://mooseframework.inl.gov/docs/PRs/27188/clang_format/style.patch | git apply -v`  

Alternatively, with your repository up to date and in the top level of your repository:

`git clang-format f5a14f390f39cec590003be860130561954c6b99`

2025-03-05 03:38 UTC, moosebuild commented
Job [Documentation](https://civet.inl.gov/job/2729777/), step Docs: sync website on 0df7822 wanted to post the following:

View the site [here](https://mooseframework.inl.gov/docs/PRs/27188/site)

This comment will be updated on new commits.

2025-03-20 03:58 UTC, moosebuild commented
Job [Modules parallel](https://civet.inl.gov/job/2761326/) on 019946e : invalidated by @lindsayad

2025-03-20 19:26 UTC, lindsayad commented
I'm used to waiting on this PR 😆 😢 See libmesh/libmesh#4113

2025-03-22 16:09 UTC, moosebuild commented on libmesh
> +Subproject commit 1e10fa9fb72d10531a6128f821f8d11f8032882c
**Caution!** This contains a submodule update

2025-03-22 16:09 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/2767595/), step Versioner verify on 741fb45 wanted to post the following:

### Versioner templates

Found 16 templates, 0 failed


### Versioner versions

Found 10 packages, 2 changed, 0 failed

| package   | status   | hash    | to hash   | version            | to version         |
|-----------|----------|---------|-----------|--------------------|--------------------|
| libmesh   | CHANGE   | dabc922 | 83f53c8   | 2025.02.25 build 0 | 2025.03.22 build 0 |
| moose-dev | CHANGE   | fcaa73c | 2aebace   | 2025.03.03         | 2025.03.22         |

2025-03-23 04:58 UTC, moosebuild commented on libmesh
> +Subproject commit 1e10fa9fb72d10531a6128f821f8d11f8032882c
**Caution!** This contains a submodule update

2025-03-23 04:58 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/2767863/), step Versioner verify on 47d8dde wanted to post the following:

### Versioner templates

Found 16 templates, 0 failed


### Versioner versions

Found 10 packages, 2 changed, 0 failed

| package   | status   | hash    | to hash   | version            | to version         |
|-----------|----------|---------|-----------|--------------------|--------------------|
| libmesh   | CHANGE   | dabc922 | 83f53c8   | 2025.02.25 build 0 | 2025.03.22 build 0 |
| moose-dev | CHANGE   | fcaa73c | 2aebace   | 2025.03.03         | 2025.03.22         |

2025-03-24 16:30 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/2769839/), step Versioner verify on ac6d2cd wanted to post the following:

### Versioner templates

Found 16 templates, 0 failed


### Versioner versions

Found 10 packages, 2 changed, 0 failed

| package   | status   | hash    | to hash   | version            | to version         |
|-----------|----------|---------|-----------|--------------------|--------------------|
| libmesh   | CHANGE   | c2aeeb2 | 83f53c8   | 2025.03.06 build 0 | 2025.03.22 build 0 |
| moose-dev | CHANGE   | ca0a369 | 2aebace   | 2025.03.06         | 2025.03.22         |

2025-03-24 22:02 UTC, moosebuild commented
Job [Coverage](https://civet.inl.gov/job/2769881/), step Generate coverage on ac6d2cd wanted to post the following:


## Framework coverage

No coverage report(s) were found for the base commit 55c8eb2d3e.
[Full coverage report](https://mooseframework.inl.gov/docs/PRs/27188/coverage/framework)


## Modules coverage

No coverage report(s) were found for the base commit 55c8eb2d3e.

## Full coverage reports

<details>
<summary>Reports</summary>

- [`framework`](https://mooseframework.inl.gov/docs/PRs/27188/coverage/framework)
- [`chemical_reactions`](https://mooseframework.inl.gov/docs/PRs/27188/coverage/chemical_reactions)
- [`combined`](https://mooseframework.inl.gov/docs/PRs/27188/coverage/combined)
- [`contact`](https://mooseframework.inl.gov/docs/PRs/27188/coverage/contact)
- [`electromagnetics`](https://mooseframework.inl.gov/docs/PRs/27188/coverage/electromagnetics)
- [`external_petsc_solver`](https://mooseframework.inl.gov/docs/PRs/27188/coverage/external_petsc_solver)
- [`fluid_properties`](https://mooseframework.inl.gov/docs/PRs/27188/coverage/fluid_properties)
- [`fsi`](https://mooseframework.inl.gov/docs/PRs/27188/coverage/fsi)
- [`functional_expansion_tools`](https://mooseframework.inl.gov/docs/PRs/27188/coverage/functional_expansion_tools)
- [`geochemistry`](https://mooseframework.inl.gov/docs/PRs/27188/coverage/geochemistry)
- [`heat_transfer`](https://mooseframework.inl.gov/docs/PRs/27188/coverage/heat_transfer)
- [`level_set`](https://mooseframework.inl.gov/docs/PRs/27188/coverage/level_set)
- [`misc`](https://mooseframework.inl.gov/docs/PRs/27188/coverage/misc)
- [`navier_stokes`](https://mooseframework.inl.gov/docs/PRs/27188/coverage/navier_stokes)
- [`optimization`](https://mooseframework.inl.gov/docs/PRs/27188/coverage/optimization)
- [`peridynamics`](https://mooseframework.inl.gov/docs/PRs/27188/coverage/peridynamics)
- [`phase_field`](https://mooseframework.inl.gov/docs/PRs/27188/coverage/phase_field)
- [`porous_flow`](https://mooseframework.inl.gov/docs/PRs/27188/coverage/porous_flow)
- [`ray_tracing`](https://mooseframework.inl.gov/docs/PRs/27188/coverage/ray_tracing)
- [`rdg`](https://mooseframework.inl.gov/docs/PRs/27188/coverage/rdg)
- [`reactor`](https://mooseframework.inl.gov/docs/PRs/27188/coverage/reactor)
- [`richards`](https://mooseframework.inl.gov/docs/PRs/27188/coverage/richards)
- [`scalar_transport`](https://mooseframework.inl.gov/docs/PRs/27188/coverage/scalar_transport)
- [`solid_mechanics`](https://mooseframework.inl.gov/docs/PRs/27188/coverage/solid_mechanics)
- [`solid_properties`](https://mooseframework.inl.gov/docs/PRs/27188/coverage/solid_properties)
- [`stochastic_tools`](https://mooseframework.inl.gov/docs/PRs/27188/coverage/stochastic_tools)
- [`subchannel`](https://mooseframework.inl.gov/docs/PRs/27188/coverage/subchannel)
- [`thermal_hydraulics`](https://mooseframework.inl.gov/docs/PRs/27188/coverage/thermal_hydraulics)
- [`xfem`](https://mooseframework.inl.gov/docs/PRs/27188/coverage/xfem)

</details>



This comment will be updated on new commits.

2025-03-25 19:29 UTC, moosebuild commented on libmesh
> +Subproject commit 1e10fa9fb72d10531a6128f821f8d11f8032882c
**Caution!** This contains a submodule update

2025-03-25 19:29 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/2773165/), step Versioner verify on 516a105 wanted to post the following:

### Versioner templates

Found 16 templates, 0 failed


### Versioner versions

Found 10 packages, 2 changed, 0 failed

| package   | status   | hash    | to hash   | version            | to version         |
|-----------|----------|---------|-----------|--------------------|--------------------|
| libmesh   | CHANGE   | c2aeeb2 | 83f53c8   | 2025.03.06 build 0 | 2025.03.22 build 0 |
| moose-dev | CHANGE   | ca0a369 | 2aebace   | 2025.03.06         | 2025.03.22         |

2025-03-25 19:34 UTC, moosebuild commented on libmesh
> +Subproject commit 1e10fa9fb72d10531a6128f821f8d11f8032882c
**Caution!** This contains a submodule update

2025-03-25 19:35 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/2773229/), step Versioner verify on 5fa1072 wanted to post the following:

### Versioner templates

Found 16 templates, 0 failed


### Versioner versions

Found 10 packages, 2 changed, 0 failed

| package   | status   | hash    | to hash   | version            | to version         |
|-----------|----------|---------|-----------|--------------------|--------------------|
| libmesh   | CHANGE   | bc5c687 | 420783d   | 2025.03.06 build 1 | 2025.03.25 build 0 |
| moose-dev | CHANGE   | 00b281f | f48fbee   | 2025.03.24         | 2025.03.25         |

2025-03-26 21:07 UTC, moosebuild commented on libmesh
> +Subproject commit 1e10fa9fb72d10531a6128f821f8d11f8032882c
**Caution!** This contains a submodule update

2025-03-26 21:07 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/2777451/), step Versioner verify on 3c0218c wanted to post the following:

### Versioner templates

Found 16 templates, 0 failed


### Versioner versions

Found 10 packages, 2 changed, 0 failed

| package   | status   | hash    | to hash   | version            | to version         |
|-----------|----------|---------|-----------|--------------------|--------------------|
| libmesh   | CHANGE   | bc5c687 | 420783d   | 2025.03.06 build 1 | 2025.03.25 build 0 |
| moose-dev | CHANGE   | 00b281f | f48fbee   | 2025.03.24         | 2025.03.25         |

2025-03-27 23:15 UTC, moosebuild commented on libmesh
> +Subproject commit 1e10fa9fb72d10531a6128f821f8d11f8032882c
**Caution!** This contains a submodule update

2025-03-27 23:15 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/2782131/), step Versioner verify on 74f2473 wanted to post the following:

### Versioner templates

Found 16 templates, 0 failed


### Versioner versions

Found 10 packages, 2 changed, 0 failed

| package   | status   | hash    | to hash   | version            | to version         |
|-----------|----------|---------|-----------|--------------------|--------------------|
| libmesh   | CHANGE   | bc5c687 | 420783d   | 2025.03.06 build 1 | 2025.03.25 build 0 |
| moose-dev | CHANGE   | 00b281f | f48fbee   | 2025.03.24         | 2025.03.25         |

2025-04-01 20:00 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/2792028/), step Clang format on 0a34b7f wanted to post the following:

Your code requires style changes.  

A patch was auto generated and copied [here](https://mooseframework.inl.gov/docs/PRs/27188/clang_format/style.patch)  
You can directly apply the patch by running, in the top level of your repository:

`curl -s https://mooseframework.inl.gov/docs/PRs/27188/clang_format/style.patch | git apply -v`  

Alternatively, with your repository up to date and in the top level of your repository:

`git clang-format a7b98aa272700a4a06703efd4da8a041454da026`

2025-04-01 20:00 UTC, moosebuild commented on libmesh
> +Subproject commit 1e10fa9fb72d10531a6128f821f8d11f8032882c
**Caution!** This contains a submodule update

2025-04-01 20:00 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/2792028/), step Versioner verify on 0a34b7f wanted to post the following:

### Versioner templates

Found 16 templates, 0 failed


### Versioner versions

Found 10 packages, 2 changed, 0 failed

| package   | status   | hash    | to hash   | version            | to version         |
|-----------|----------|---------|-----------|--------------------|--------------------|
| libmesh   | CHANGE   | bc5c687 | 420783d   | 2025.03.06 build 1 | 2025.03.25 build 0 |
| moose-dev | CHANGE   | 00b281f | f48fbee   | 2025.03.24         | 2025.03.25         |

2025-04-01 23:32 UTC, moosebuild commented on libmesh
> +Subproject commit 1e10fa9fb72d10531a6128f821f8d11f8032882c
**Caution!** This contains a submodule update

2025-04-01 23:32 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/2792473/), step Versioner verify on b0ed508 wanted to post the following:

### Versioner templates

Found 16 templates, 0 failed


### Versioner versions

Found 10 packages, 2 changed, 0 failed

| package   | status   | hash    | to hash   | version            | to version         |
|-----------|----------|---------|-----------|--------------------|--------------------|
| libmesh   | CHANGE   | bc5c687 | 420783d   | 2025.03.06 build 1 | 2025.03.25 build 0 |
| moose-dev | CHANGE   | 00b281f | f48fbee   | 2025.03.24         | 2025.03.25         |

2025-04-02 19:48 UTC, moosebuild commented on libmesh
> +Subproject commit 1e10fa9fb72d10531a6128f821f8d11f8032882c
**Caution!** This contains a submodule update

2025-04-02 19:48 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/2794058/), step Versioner verify on 572f438 wanted to post the following:

### Versioner templates

Found 16 templates, 0 failed


### Versioner versions

Found 10 packages, 2 changed, 0 failed

| package   | status   | hash    | to hash   | version            | to version         |
|-----------|----------|---------|-----------|--------------------|--------------------|
| libmesh   | CHANGE   | bc5c687 | 420783d   | 2025.03.06 build 1 | 2025.03.25 build 0 |
| moose-dev | CHANGE   | 00b281f | f48fbee   | 2025.03.24         | 2025.03.25         |

2025-04-02 22:00 UTC, moosebuild commented
Job [Conda (Rocky)](https://civet.inl.gov/job/2794093/) on 572f438 : invalidated by @lindsayad

2025-04-03 04:45 UTC, moosebuild commented on libmesh
> +Subproject commit 1e10fa9fb72d10531a6128f821f8d11f8032882c
**Caution!** This contains a submodule update

2025-04-03 04:45 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/2794963/), step Versioner verify on bf62c2c wanted to post the following:

### Versioner templates

Found 16 templates, 0 failed


### Versioner versions

Found 10 packages, 2 changed, 0 failed

| package   | status   | hash    | to hash   | version            | to version         |
|-----------|----------|---------|-----------|--------------------|--------------------|
| libmesh   | CHANGE   | bc5c687 | 420783d   | 2025.03.06 build 1 | 2025.03.25 build 0 |
| moose-dev | CHANGE   | 00b281f | f48fbee   | 2025.03.24         | 2025.03.25         |

2025-04-03 16:44 UTC, moosebuild commented on libmesh
> +Subproject commit 1e10fa9fb72d10531a6128f821f8d11f8032882c
**Caution!** This contains a submodule update

2025-04-03 16:44 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/2796028/), step Versioner verify on ad1132d wanted to post the following:

### Versioner templates

Found 16 templates, 0 failed


### Versioner versions

Found 10 packages, 2 changed, 0 failed

| package   | status   | hash    | to hash   | version            | to version         |
|-----------|----------|---------|-----------|--------------------|--------------------|
| libmesh   | CHANGE   | bc5c687 | 420783d   | 2025.03.06 build 1 | 2025.03.25 build 0 |
| moose-dev | CHANGE   | 00b281f | f48fbee   | 2025.03.24         | 2025.03.25         |

2025-04-03 16:59 UTC, moosebuild commented on libmesh
> +Subproject commit 1e10fa9fb72d10531a6128f821f8d11f8032882c
**Caution!** This contains a submodule update

2025-04-03 20:46 UTC, moosebuild commented
Job [Apptainer build profiling](https://civet.inl.gov/job/2796106/) on 5e2c527 : invalidated by @lindsayad

2025-04-03 21:17 UTC, moosebuild commented on libmesh
> +Subproject commit 1e10fa9fb72d10531a6128f821f8d11f8032882c
**Caution!** This contains a submodule update

2025-04-03 21:17 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/2797262/), step Versioner verify on a14a17a wanted to post the following:

### Versioner templates

Found 16 templates, 0 failed


### Versioner versions

Found 10 packages, 2 changed, 0 failed

| package   | status   | hash    | to hash   | version            | to version         |
|-----------|----------|---------|-----------|--------------------|--------------------|
| libmesh   | CHANGE   | bc5c687 | 420783d   | 2025.03.06 build 1 | 2025.03.25 build 0 |
| moose-dev | CHANGE   | 00b281f | f48fbee   | 2025.03.24         | 2025.03.25         |

2025-04-04 19:15 UTC, moosebuild commented
Job [Modules](https://civet.inl.gov/job/2797288/) on a14a17a : invalidated by @lindsayad

2025-04-07 16:19 UTC, moosebuild commented
Job [Modules recover](https://civet.inl.gov/job/2797290/) on a14a17a : invalidated by @lindsayad

2025-04-07 17:43 UTC, moosebuild commented
Job [Coverage](https://civet.inl.gov/job/2797304/), step Verify coverage on a14a17a wanted to post the following:


The following coverage requirement(s) failed:
- Failed to generate `chemical_reactions` coverage rate (required: 92.0%)
- Failed to generate `contact` coverage rate (required: 87.0%)
- Failed to generate `electromagnetics` coverage rate (required: 94.0%)
- Failed to generate `external_petsc_solver` coverage rate (required: 84.0%)
- Failed to generate `fluid_properties` coverage rate (required: 84.0%)
- Failed to generate `fsi` coverage rate (required: 85.0%)
- Failed to generate `functional_expansion_tools` coverage rate (required: 81.0%)
- Failed to generate `geochemistry` coverage rate (required: 96.0%)
- Failed to generate `heat_transfer` coverage rate (required: 87.0%)
- Failed to generate `level_set` coverage rate (required: 85.0%)
- Failed to generate `misc` coverage rate (required: 32.0%)
- Failed to generate `navier_stokes` coverage rate (required: 77.0%)
- Failed to generate `optimization` coverage rate (required: 86.0%)
- Failed to generate `peridynamics` coverage rate (required: 77.0%)
- Failed to generate `phase_field` coverage rate (required: 85.0%)
- Failed to generate `porous_flow` coverage rate (required: 95.0%)
- Failed to generate `ray_tracing` coverage rate (required: 93.0%)
- Failed to generate `rdg` coverage rate (required: 63.0%)
- Failed to generate `reactor` coverage rate (required: 90.0%)
- Failed to generate `scalar_transport` coverage rate (required: 81.0%)
- Failed to generate `solid_mechanics` coverage rate (required: 84.0%)
- Failed to generate `solid_properties` coverage rate (required: 83.0%)
- Failed to generate `stochastic_tools` coverage rate (required: 88.0%)
- Failed to generate `subchannel` coverage rate (required: 87.0%)
- Failed to generate `thermal_hydraulics` coverage rate (required: 88.0%)
- Failed to generate `xfem` coverage rate (required: 80.0%)

2025-04-07 17:55 UTC, moosebuild commented on libmesh
> +Subproject commit 1e10fa9fb72d10531a6128f821f8d11f8032882c
**Caution!** This contains a submodule update

2025-04-07 17:55 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/2802002/), step Versioner verify on 9c5e63f wanted to post the following:

### Versioner templates

Found 16 templates, 0 failed


### Versioner versions

Found 10 packages, 2 changed, 0 failed

| package   | status   | hash    | to hash   | version            | to version         |
|-----------|----------|---------|-----------|--------------------|--------------------|
| libmesh   | CHANGE   | bc5c687 | 420783d   | 2025.03.06 build 1 | 2025.03.25 build 0 |
| moose-dev | CHANGE   | 00b281f | f48fbee   | 2025.03.24         | 2025.03.25         |

2025-04-08 20:02 UTC, moosebuild commented on libmesh
> +Subproject commit 1e10fa9fb72d10531a6128f821f8d11f8032882c
**Caution!** This contains a submodule update

2025-04-08 20:02 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/2806017/), step Versioner verify on d9b47de wanted to post the following:

### Versioner templates

Found 16 templates, 0 failed


### Versioner versions

Found 10 packages, 2 changed, 0 failed

| package   | status   | hash    | to hash   | version            | to version         |
|-----------|----------|---------|-----------|--------------------|--------------------|
| libmesh   | CHANGE   | bc5c687 | 420783d   | 2025.03.06 build 1 | 2025.03.25 build 0 |
| moose-dev | CHANGE   | 00b281f | f48fbee   | 2025.03.24         | 2025.03.25         |

2025-04-08 22:16 UTC, moosebuild commented
Job [Conda (ARM Mac)](https://civet.inl.gov/job/2806051/) on d9b47de : invalidated by @lindsayad

2025-04-09 04:19 UTC, moosebuild commented
Job [Controlled apps](https://civet.inl.gov/job/2806046/) on d9b47de : invalidated by @lindsayad

2025-04-23 19:09 UTC, GiudGiud commented
How much of the previous HDG are you removing? Can we still do diffusion? NS?

2025-04-23 19:09 UTC, GiudGiud commented
I can review if you want

2025-04-23 20:14 UTC, lindsayad commented
I didn't remove any of the previous HDG capability. I added an "L" to denote the previously implemented "local" HDG method and an "IP" to denote the newly added interior penalty HDG method

I welcome any reviewers!

2025-04-23 20:31 UTC, GiudGiud reviewed
only looked at framework doco and headers. I ll probably do 2 or 3 more rounds to cover everything

2025-04-23 20:31 UTC, GiudGiud commented on framework/include/systems/NonlinearSystem.h
> -                        public libMesh::NonlinearImplicitSystem::ComputePreCheck
where did the preCheck go? or deleted? I might see it later in the review

2025-04-23 20:31 UTC, GiudGiud commented on framework/include/hdgkernels/IPHDGAssemblyHelper.h
> +//* https://www.mooseframework.org
```suggestion
//* https://www.mooseframework.inl.gov
```

2025-04-23 20:31 UTC, GiudGiud commented on framework/include/hdgkernels/IPHDGAssemblyHelper.h
> + * (IPDG-H), which is a type of HDG method, discretization of the diffusion equation. These routines
```suggestion
 * Base class that declares all the methods for assembling a hybridized interior penalty discontinuous Galerkin
 * (IPDG-H), which is a type of HDG method, discretization of an equation. These routines
```

2025-04-23 20:31 UTC, GiudGiud commented on framework/include/hdgkernels/IPHDGAssemblyHelper.h
> + * (IPDG-H), which is a type of HDG method, discretization of the diffusion equation. These routines
if this is actuallt just diffusion let's rename the class

2025-04-23 20:31 UTC, GiudGiud commented on framework/include/interfaces/TaggingInterface.h
> +struct ADResidualsPacket
docstring

Packet has communication connotations for me.

2025-04-23 20:31 UTC, GiudGiud commented on framework/include/loops/NonlinearThread.h
> +  /// don't want to double execute DG kernels
the logic seems to not match this comment?
>   return _should_execute_dg || _hdg_warehouse->hasActiveBlockObjects(_subdomain, _tid);

or do you mean "should execute dg" is false but that's ok for `shouldComputeInternalSide` because we also check the warehouse and will execute anyway?

2025-04-23 20:39 UTC, lindsayad commented on framework/include/bcs/AdvectionIPHDGOutflowBC.h
> +  virtual AdvectionIPHDGAssemblyHelper & iphdgHelper() override { return *_iphdg_helper; }
https://en.wikipedia.org/wiki/Covariant_return_type

2025-04-23 20:41 UTC, lindsayad commented on framework/include/hdgkernels/DiffusionLHDGKernel.h
> +  const MooseArray<Point> & _normals;
I would need a new class of residual objects then that are stored in warehouses and leveraged in `ComputeResidual/JacobianThread`. Because in order for these systems to be statically condensed we must be assembling on a per-element basis. DGKernels muck that up because they add into both element and neighbor residuals/Jacobians so I cannot use them

2025-04-23 20:45 UTC, lindsayad commented on framework/include/systems/NonlinearSystem.h
> -                        public libMesh::NonlinearImplicitSystem::ComputePreCheck
We don't need it any more. That's one of the very nice changes in this PR. The nonlinear system and its residual correspond to all the degrees of freedom, both interior and face degrees of freedom, instead of previously where I put the interior degrees of freedom in an auxiliary system. Then a user can choose whether they want to statically condense out the interior degrees of freedom in the *preconditioner* (leaving only the face degrees of freedom) or not.

This means a user is also free now to use any SNES algorithm they like as opposed to being limited to line-search without the line search (meaning previously you could only use `-snes_type newtonls -snes_linesearch_type basic`)

2025-04-23 20:48 UTC, lindsayad commented on framework/include/systems/NonlinearSystem.h
> -                        public libMesh::NonlinearImplicitSystem::ComputePreCheck
This is the key class for this change: https://mooseframework.inl.gov/docs/doxygen/libmesh/classlibMesh_1_1StaticCondensation.html

2025-04-23 21:01 UTC, GiudGiud commented on framework/include/bcs/AdvectionIPHDGOutflowBC.h
> +  virtual AdvectionIPHDGAssemblyHelper & iphdgHelper() override { return *_iphdg_helper; }
oh nice. I need to start doing this

2025-05-06 14:57 UTC, GiudGiud requested changes
Still have to go over the NS source still

2025-05-06 14:57 UTC, GiudGiud commented on modules/navier_stokes/include/postprocessors/AreMatricesTheSame.h
> +class AreMatricesTheSame : public GeneralPostprocessor
```suggestion
/**
 * Checks if two matrices are the same by comparing their coefficients
 */
class AreMatricesTheSame : public GeneralPostprocessor
```

2025-05-06 14:57 UTC, GiudGiud commented on modules/navier_stokes/include/kernels/GradDiv.h
> +class GradDiv : public ADKernel
docstring

2025-05-06 14:57 UTC, GiudGiud commented on python/MooseDocs/test/extensions/test_appsyntax.py
> +        self.assertSize(res, 19)
doco not built rn. what did you add to diffusion?

2025-05-06 14:57 UTC, GiudGiud commented on modules/navier_stokes/test/tests/finite_element/ins/hdg/ip/lid-driven/tests
> +    requirement = "The condensed matrix shall be symmetric, although I don't understand why. Where did the advection go?"
this wont look good in the SQA doco

advection hits the non-condensed dofs right, and should not be symmetric

maybe tolerances?

2025-05-06 14:57 UTC, GiudGiud commented on modules/navier_stokes/test/tests/finite_element/ins/hdg/ip/lid-driven/sc-lid-driven.i
> +  [momentum_x_convection]
```suggestion
  [momentum_x_advection]
```
convection is only heat/ body force driven

2025-05-06 14:57 UTC, GiudGiud commented on modules/navier_stokes/test/tests/finite_element/ins/hdg/ip/lid-driven/gold/lid-driven-fsp_out.e
let's hide the side hierarchic vsariables, not output right

2025-05-06 14:57 UTC, GiudGiud commented on modules/navier_stokes/test/tests/finite_element/ins/hdg/ip/lid-driven/gold/lid-driven_out.e
pressure has a 3e5 cell to cell jump in this file

2025-05-06 14:57 UTC, GiudGiud commented on modules/navier_stokes/include/hdgkernels/NavierStokesStressIPHDGAssemblyHelper.h
> + * (IPDG-H), which is a type of HDG method, discretization of the diffusion equation. These routines
```suggestion
 * (IPDG-H), which is a type of HDG method, discretization of the NS equation. These routines
```

2025-05-20 18:40 UTC, lindsayad commented on framework/include/loops/NonlinearThread.h
> +  /// don't want to double execute DG kernels
I've tried to clarify the comment

2025-05-20 18:47 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/2881774/), step Clang format on 8de3101 wanted to post the following:

Your code requires style changes.  

A patch was auto generated and copied [here](https://mooseframework.inl.gov/docs/PRs/27188/clang_format/style.patch)  
You can directly apply the patch by running, in the top level of your repository:

`curl -s https://mooseframework.inl.gov/docs/PRs/27188/clang_format/style.patch | git apply -v`  

Alternatively, with your repository up to date and in the top level of your repository:

`git clang-format 083e818fdf10367a54e8ba2444e70a9b273db34b`

2025-05-20 19:37 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/2882350/), step Clang format on d078f2e wanted to post the following:

Your code requires style changes.  

A patch was auto generated and copied [here](https://mooseframework.inl.gov/docs/PRs/27188/clang_format/style.patch)  
You can directly apply the patch by running, in the top level of your repository:

`curl -s https://mooseframework.inl.gov/docs/PRs/27188/clang_format/style.patch | git apply -v`  

Alternatively, with your repository up to date and in the top level of your repository:

`git clang-format 083e818fdf10367a54e8ba2444e70a9b273db34b`

2025-05-20 21:39 UTC, lindsayad commented on framework/src/hdgkernels/DiffusionLHDGAssemblyHelper.C
> +    for (const auto qp : make_range(qrule.n_points()))
I reordered the loops now to be consistent with IP-HDG

2025-05-20 21:42 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/2883214/), step Clang format on b2af9cb wanted to post the following:

Your code requires style changes.  

A patch was auto generated and copied [here](https://mooseframework.inl.gov/docs/PRs/27188/clang_format/style.patch)  
You can directly apply the patch by running, in the top level of your repository:

`curl -s https://mooseframework.inl.gov/docs/PRs/27188/clang_format/style.patch | git apply -v`  

Alternatively, with your repository up to date and in the top level of your repository:

`git clang-format 083e818fdf10367a54e8ba2444e70a9b273db34b`

2025-05-20 21:48 UTC, lindsayad commented on framework/src/loops/NonlinearThread.C
> +    // Set up Sentinel class so that, even if reinitMaterialsFace() throws, we
It's in `prepareFace`. I will update the comment to be more helpful

2025-05-20 22:38 UTC, lindsayad commented on framework/src/postprocessors/IsMatrixSymmetric.C
> +  mat->get_transpose(*_mat_transpose);
Great question. I'll give it a try

2025-05-21 17:43 UTC, lindsayad commented on framework/src/preconditioners/MooseStaticCondensationPreconditioner.C
> +  change_prefix("pc");
Good point. I've revamped this to blanketly apply the prefix to all options provided in this preconditioner's block. Importantly it also no longer applies to PETSc options provided elsewhere, like in the Executioner, which makes it so that you can set things like `-ksp_type preonly` for the global linear solve in the input file as opposed to needing to set it on the command line, which is something I often forget to do. And if I as the author forget to do it, then certainly many others would also

2025-05-21 18:24 UTC, lindsayad commented on modules/navier_stokes/include/bcs/AdvectionIPHDGPrescribedFluxBC.h
> + * Implements an outflow boundary condition for use with a hybridized discretization of
Thus far I've used it exclusively for prescribing zero advective flux conditions at wall-type boundaries but you're right that it could just as well be used for weakly prescribing an inlet advection flux. Really an outlet boundary is the only place this *shouldn't* be used! I've updated the doc

2025-05-21 19:14 UTC, lindsayad commented on modules/navier_stokes/include/bcs/NavierStokesStressIPHDGDirichletBC.h
> +class NavierStokesStressIPHDGDirichletBC : public IPHDGDirichletBC
I have added some now in `HDGKernels/index.md`

2025-05-21 19:26 UTC, lindsayad commented on python/MooseDocs/test/extensions/test_appsyntax.py
> +        self.assertSize(res, 19)
`matrix_only` was made non-private

2025-05-21 21:03 UTC, lindsayad commented on modules/navier_stokes/test/tests/finite_element/ins/hdg/ip/lid-driven/gold/lid-driven_out.e
Really? How did you determine that? The pressure field looks pretty reasonable to me
<img width="694" alt="Screenshot 2025-05-21 at 2 03 08 PM" src="https://github.com/user-attachments/assets/881d55cb-1a52-4dbc-bc64-03adb6768844" />

2025-05-21 21:29 UTC, lindsayad commented on modules/navier_stokes/src/bcs/MassFluxPenaltyBC.C
> +  const ADRealVectorValue soln_jump(_vel_x[_qp], _vel_y[_qp], 0);
I've added a Dirichlet value parameter so that this becomes the correct jump term

2025-05-21 21:36 UTC, lindsayad commented on modules/navier_stokes/src/bcs/NavierStokesLHDGOutflowBC.C
> +      _assembly, _p_lm_v_jac, _p_dof_indices, _lm_v_dof_indices, _pressure_var.scalingFactor());
what do you mean? Like `-snes_test_jacobian`?

2025-05-21 21:50 UTC, GiudGiud commented on modules/navier_stokes/src/bcs/NavierStokesLHDGOutflowBC.C
> +      _assembly, _p_lm_v_jac, _p_dof_indices, _lm_v_dof_indices, _pressure_var.scalingFactor());
ah yeah that works for BCs. 
The one that does not is the analyze-jacobian.py right?

2025-05-21 22:00 UTC, lindsayad commented on modules/navier_stokes/test/src/problems/PrintMatricesNSProblem.C
> +      // Create B
yes, I'll make that more clear. Very poor choice of variable name given that B typically represents the v-p coupling matrix

2025-05-29 04:26 UTC, GiudGiud reviewed
looked at most of the headers

2025-05-29 04:26 UTC, GiudGiud commented on framework/include/bcs/IPHDGBC.h
> +  unsigned int _my_side;
```suggestion
  unsigned int _cached_side;
```

2025-05-29 17:39 UTC, GiudGiud reviewed
Done with framework/

so in light of the discussion on features, what would you consider to be reasonable things to check that they work with HDG? block restriction? displaced mesh? h-adaptivity? explicit time integration?

- [x] block restriction
- [ ] displaced mesh
- [x] h-adaptivity following https://github.com/libMesh/libmesh/pull/4184. Added testing in lindsayad/moose@ffdc73be9f1 in #30357
- [x] explicit time integration: added error. Lagrange multipliers/face variables do not have time derivatives

2025-05-29 22:40 UTC, lindsayad commented on framework/src/hdgkernels/DiffusionIPHDGAssemblyHelper.C
> +#include "MaterialPropertyInterface.h"
I don't think I can remove all of these in all the helpers

2025-05-29 22:44 UTC, GiudGiud commented on framework/src/hdgkernels/DiffusionIPHDGAssemblyHelper.C
> +#include "MaterialPropertyInterface.h"
no they dont have the same list but they do seem longer than needed

2025-05-29 22:52 UTC, lindsayad commented on framework/src/bcs/DiffusionLHDGDirichletBC.C
> +DiffusionLHDGDirichletBC::computeOffDiagJacobian(const unsigned int)
`computeOffDiagJacobian` is always the residual object entry point from the Jacobian `NonlinearThread` unless the coupling type is `COUPLING_DIAG`, corresponding to no preconditioning block. And since I error if full coupling is not requested, there is no chance of having the entry point be directly `computeJacobian`. Related code is
https://github.com/idaholab/moose/blob/7cc8bd7530c04b73ef16019251092c5a42403fdc/framework/src/systems/NonlinearSystemBase.C#L2877-L2907

2025-05-29 23:32 UTC, GiudGiud commented on framework/src/bcs/DiffusionLHDGDirichletBC.C
> +DiffusionLHDGDirichletBC::computeOffDiagJacobian(const unsigned int)
ok that works
if doxygen lets you maybe re-do the docstring then?  They are from the RO base class and they don't match what these new classes do. 

computeJacobian is no longer
```
  /// Compute this object's contribution to the diagonal Jacobian entries
```
and computeOffDiagJacobian is not
```
   * Computes this object's contribution to off-diagonal blocks of the system Jacobian matrix
```
they both just do the full Jacobian.

2025-05-30 02:56 UTC, lindsayad commented
> so in light of the discussion on features, what would you consider to be reasonable things to check that they work with HDG? block restriction? displaced mesh? h-adaptivity? explicit time integration?

I really like the new explicit time integrator error. It catches bad uses right away
```
*** ERROR ***
CLI_ARGS:1.1:
The following error occurred in the TimeIntegrator 'ActuallyExplicitEuler:nl0' of type ActuallyExplicitEuler.

No objects contributing to the mass matrix were found for variable 'side_u'. Did you, e.g., forget a time derivative term?
```
I'll add a more HDG specific error

2025-05-30 04:07 UTC, GiudGiud commented
What if you did have a time derivative?

2025-06-02 16:39 UTC, lindsayad commented
You should not have a time derivative. While the facet variables do represent the solution on faces, their ultimate jobs are as Lagrange multipliers enforcing flux constraints on the faces

2025-06-02 17:14 UTC, GiudGiud commented
ah ok I was thinking about a time derivative in general. But I understand this will be caught by the lack of derivative on the face term. Having an error works for me

2025-06-03 01:53 UTC, GiudGiud reviewed
done with NS

2025-06-03 01:53 UTC, GiudGiud commented on framework/src/hdgkernels/DiffusionLHDGAssemblyHelper.C
> +    const auto scalar_qp_term = JxW[qp] * scalar_sol[qp];
I think we are missing _coords in all these helpers

2025-06-03 01:53 UTC, GiudGiud commented on framework/src/hdgkernels/DiffusionLHDGAssemblyHelper.C
> +    const auto scalar_qp_term = JxW[qp] * scalar_sol[qp];
maybe let's ban RZ and R-sph?

2025-06-03 01:53 UTC, GiudGiud commented on modules/navier_stokes/src/bcs/MassFluxPenaltyBC.C
> +  params.addParam<Real>("gamma", 1, "The penalty to multiply the jump");
```suggestion
  params.addParam<Real>("gamma", 1, "The penalty to multiply the jump with");
```

2025-06-03 01:53 UTC, GiudGiud commented on modules/navier_stokes/src/bcs/MassFluxPenaltyBC.C
> +  params.addClassDescription("Adds the exterior boundary contribution of penalized jumps.");
```suggestion
  params.addClassDescription("Adds the exterior boundary contribution of penalized jumps in the velocity variable in one component of the momentum equations.");
```

2025-06-03 01:53 UTC, GiudGiud commented on modules/navier_stokes/src/hdgkernels/NavierStokesLHDGAssemblyHelper.C
> +        global_lm_p_jac(0, j) -= JxW[qp] * _scalar_phi[j][qp];
so this routine is assuming that p and v use the same shape functions right?

2025-06-03 01:53 UTC, GiudGiud commented on modules/navier_stokes/src/hdgkernels/NavierStokesLHDGAssemblyHelper.C
> +        global_lm_p_jac(0, j) -= JxW[qp] * _scalar_phi[j][qp];
otherwise dp/dp_i would be a different phi

do we check for this somewhere?

2025-06-03 01:53 UTC, GiudGiud commented on modules/navier_stokes/src/hdgkernels/NavierStokesLHDGAssemblyHelper.C
> +  for (const auto i : make_range(p_lm_u_vel_jac.m()))
I d assert p_lm_u_vel_jac and p_lm_v_vel_jac same size

2025-06-03 01:53 UTC, GiudGiud commented on modules/navier_stokes/src/hdgkernels/NavierStokesLHDGAssemblyHelper.C
> +  for (const auto i : make_range(p_lm_u_vel_jac.m()))
or not. I was just getting confused at first reading the loop ranges

2025-06-03 01:53 UTC, GiudGiud commented on modules/navier_stokes/src/hdgkernels/NavierStokesLHDGAssemblyHelper.C
> +  for (const auto i : make_range(p_lm_u_vel_jac.m()))
it wont hurt though

2025-06-03 01:53 UTC, GiudGiud commented on modules/navier_stokes/src/hdgkernels/NavierStokesStressIPHDGAssemblyHelper.C
> +      _scalar_re(i) += _ip_JxW_face[qp] * _pressure_face_sol[qp] * _ip_normals[qp](_component) *
so if a user specified a dirichletBC on pressure, does that set `_pressure_face_sol` in the backend?

this is curiosity. A user should not set a dirichlet BC on pressure outside on a stress bdy/wall

2025-06-03 01:53 UTC, GiudGiud commented on modules/navier_stokes/src/dgkernels/MassFluxPenalty.C
> +  return params;
missing class description. 
maybe we should delete ADDGKernel's so we get warned of these things

2025-06-03 01:55 UTC, GiudGiud commented on modules/navier_stokes/test/tests/finite_element/ins/hdg/ip/lid-driven/gold/lid-driven_out.e
The FSP cases with constant monomial pressure show the jump in that top left corner. 

Maybe this is part of the solution? Have we always observed these two extrema in lid-driven? Is the desired magnitude of the extrema known?

2025-06-03 04:25 UTC, grmnptr commented on modules/navier_stokes/test/tests/finite_element/ins/hdg/ip/lid-driven/gold/lid-driven_out.e
With constant lid velocity we have those, analytic solution is not known. We will add some hdg cases to the flow test bed, there we can compare with validation results.

2025-06-03 22:35 UTC, lindsayad commented on framework/src/hdgkernels/DiffusionLHDGAssemblyHelper.C
> +  : NonADFunctorInterface(moose_obj),
Maybe I will change to `ADFunctorInterface` but explicitly retrieve non-AD functor types. Then instead of a silent downgrade you will get an error if using an AD functor

2025-06-04 00:33 UTC, lindsayad commented on modules/navier_stokes/src/hdgkernels/NavierStokesStressIPHDGAssemblyHelper.C
> +      _scalar_re(i) += _ip_JxW_face[qp] * _pressure_face_sol[qp] * _ip_normals[qp](_component) *
Yes. This would still have dependence on the pressure dofs but the pressure dof Jacobian rows would reflect the Dirichlet boundary condition

2025-06-05 16:12 UTC, lindsayad commented
This should be ready for further review

2025-06-05 22:27 UTC, GiudGiud approved these changes
Resolved all my comments, all addressed. Looks good to me!

2025-06-05 22:59 UTC, lindsayad commented
Thanks for a truly great review. The question about features helped highlight several areas for improvement and bug fixes

2025-06-05 22:59 UTC, merged

2025-06-06 14:14 UTC, loganharbour commented
Broke tmap8: https://civet.inl.gov/job/2923502/

2025-06-06 14:26 UTC, GiudGiud commented
on it

2025-06-06 15:41 UTC, GiudGiud commented
patch is up
https://github.com/idaholab/moose/pull/30685

TMAP8 patch is easy if we dont like my moose change