Replace no_backup_and_restore with no_restore
idaholab/moose pull request #27224
Opened 2024-03-29 00:08 UTC by loganharbour

Closes #27223 and closes #27178

I'll see if I can come up with a test. All previous behavior should still work as the lack-of-restoration was the important part to disable.

2024-03-29 00:11 UTC, loganharbour commented
@grmnptr need your input on the stochastic tools changes. I think that this still satisfies the required behavior, but a sanity check would be great.

2024-03-29 02:44 UTC, moosebuild commented
Job [Documentation](https://civet.inl.gov/job/2147240/) on 4577535 wanted to post the following:

View the site [here](https://mooseframework.inl.gov/docs/PRs/27224/site)

This comment will be updated on new commits.

2024-03-29 17:17 UTC, moosebuild commented
Job [Coverage](https://civet.inl.gov/job/2147255/) on 4577535 wanted to post the following:


## Framework coverage

<table>
  <thead>
    <tr>
      <th></th>
      <th>3a4cbc</th>
      <th colspan=4>#27224 457753</th>
    </tr>
    <tr>
      <th></th>
      <th>Total</th>
      <th>Total</th>
      <th>+/-</th>
      <th>New</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><b>Rate</b></td>
      <td>85.15%</td>
      <td>85.15%</td>
      <td>+0.00%</td>
      <td>83.33%</td>
    </tr>
    <tr>
      <td><b>Hits</b></td>
      <td>102627</td>
      <td>102630</td>
      <td>+3</td>
      <td>10</td>
    </tr>
    <tr>
      <td><b>Misses</b></td>
      <td>17900</td>
      <td>17900</td>
      <td>-</td>
      <td>2</td>
    </tr>
  </tbody>
</table>

[Diff coverage report](https://mooseframework.inl.gov/docs/PRs/27224/coverage_diff/framework)

[Full coverage report](https://mooseframework.inl.gov/docs/PRs/27224/coverage/framework)


## Modules coverage

### Stochastic tools

<table>
  <thead>
    <tr>
      <th></th>
      <th>3a4cbc</th>
      <th colspan=4>#27224 457753</th>
    </tr>
    <tr>
      <th></th>
      <th>Total</th>
      <th>Total</th>
      <th>+/-</th>
      <th>New</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><b>Rate</b></td>
      <td>90.61%</td>
      <td>90.61%</td>
      <td>-</td>
      <td>100.00%</td>
    </tr>
    <tr>
      <td><b>Hits</b></td>
      <td>7918</td>
      <td>7918</td>
      <td>-</td>
      <td>1</td>
    </tr>
    <tr>
      <td><b>Misses</b></td>
      <td>821</td>
      <td>821</td>
      <td>-</td>
      <td>0</td>
    </tr>
  </tbody>
</table>

[Diff coverage report](https://mooseframework.inl.gov/docs/PRs/27224/coverage_diff/stochastic_tools)

[Full coverage report](https://mooseframework.inl.gov/docs/PRs/27224/coverage/stochastic_tools)

## Full coverage reports

<details>
<summary>Reports</summary>

- [`framework`](https://mooseframework.inl.gov/docs/PRs/27224/coverage/framework)
- [`chemical_reactions`](https://mooseframework.inl.gov/docs/PRs/27224/coverage/chemical_reactions)
- [`combined`](https://mooseframework.inl.gov/docs/PRs/27224/coverage/combined)
- [`contact`](https://mooseframework.inl.gov/docs/PRs/27224/coverage/contact)
- [`electromagnetics`](https://mooseframework.inl.gov/docs/PRs/27224/coverage/electromagnetics)
- [`external_petsc_solver`](https://mooseframework.inl.gov/docs/PRs/27224/coverage/external_petsc_solver)
- [`fluid_properties`](https://mooseframework.inl.gov/docs/PRs/27224/coverage/fluid_properties)
- [`fsi`](https://mooseframework.inl.gov/docs/PRs/27224/coverage/fsi)
- [`functional_expansion_tools`](https://mooseframework.inl.gov/docs/PRs/27224/coverage/functional_expansion_tools)
- [`geochemistry`](https://mooseframework.inl.gov/docs/PRs/27224/coverage/geochemistry)
- [`heat_transfer`](https://mooseframework.inl.gov/docs/PRs/27224/coverage/heat_transfer)
- [`level_set`](https://mooseframework.inl.gov/docs/PRs/27224/coverage/level_set)
- [`misc`](https://mooseframework.inl.gov/docs/PRs/27224/coverage/misc)
- [`navier_stokes`](https://mooseframework.inl.gov/docs/PRs/27224/coverage/navier_stokes)
- [`optimization`](https://mooseframework.inl.gov/docs/PRs/27224/coverage/optimization)
- [`peridynamics`](https://mooseframework.inl.gov/docs/PRs/27224/coverage/peridynamics)
- [`phase_field`](https://mooseframework.inl.gov/docs/PRs/27224/coverage/phase_field)
- [`porous_flow`](https://mooseframework.inl.gov/docs/PRs/27224/coverage/porous_flow)
- [`ray_tracing`](https://mooseframework.inl.gov/docs/PRs/27224/coverage/ray_tracing)
- [`rdg`](https://mooseframework.inl.gov/docs/PRs/27224/coverage/rdg)
- [`reactor`](https://mooseframework.inl.gov/docs/PRs/27224/coverage/reactor)
- [`richards`](https://mooseframework.inl.gov/docs/PRs/27224/coverage/richards)
- [`scalar_transport`](https://mooseframework.inl.gov/docs/PRs/27224/coverage/scalar_transport)
- [`solid_mechanics`](https://mooseframework.inl.gov/docs/PRs/27224/coverage/solid_mechanics)
- [`solid_properties`](https://mooseframework.inl.gov/docs/PRs/27224/coverage/solid_properties)
- [`stochastic_tools`](https://mooseframework.inl.gov/docs/PRs/27224/coverage/stochastic_tools)
- [`thermal_hydraulics`](https://mooseframework.inl.gov/docs/PRs/27224/coverage/thermal_hydraulics)
- [`xfem`](https://mooseframework.inl.gov/docs/PRs/27224/coverage/xfem)

</details>

## Warnings

- `framework` new line coverage rate 83.33% is less than the suggested 90.0%



This comment will be updated on new commits.

2024-04-01 00:29 UTC, YaqiWang commented
Looks good to me.

2024-04-06 20:48 UTC, NamjaeChoi commented
Confirmed that it works as intended.

2024-04-16 19:11 UTC, GiudGiud requested changes

2024-04-16 19:11 UTC, GiudGiud commented on framework/src/multiapps/FullSolveMultiApp.C
> +  params.addParam<bool>(
use params.addParam params.deprecateParam instead (see ParsedAux for an example)

then you can remove the first check in the constructor

2024-04-16 19:39 UTC, GiudGiud approved these changes

2024-04-18 20:11 UTC, merged