Part 1 of finishing modules object & syntax documentation
idaholab/moose pull request #27242
Opened 2024-03-30 17:03 UTC by GiudGiud

ticking some boxes mostly but not entirely

2024-03-30 18:55 UTC, moosebuild commented
Job [Documentation](https://civet.inl.gov/job/2151436/) on e49e9f3 wanted to post the following:

View the site [here](https://mooseframework.inl.gov/docs/PRs/27242/site)

This comment will be updated on new commits.

2024-04-15 18:47 UTC, lingzou commented
@GiudGiud All looking good. I've made two minor suggestions for your consideration.

2024-04-15 19:26 UTC, lingzou reviewed
Two minor comments.

2024-04-17 16:33 UTC, lindsayad requested changes

2024-04-17 16:33 UTC, lindsayad commented on modules/navier_stokes/doc/content/source/bcs/INSFEFluidEnergyDirichletBC.md
> +This boundary condition provides a `conditional' Dirichlet temperature boundary condition for the energy equation, given that no integration by parts is applied to it.
```suggestion
This boundary condition provides a `conditional' Dirichlet temperature boundary condition for the energy equation, given that no integration by parts is applied to the energy advection term.
```

2024-04-17 16:33 UTC, lindsayad commented on modules/navier_stokes/doc/content/source/bcs/INSFEFluidEnergyDirichletBC.md
> +Without applying integration by parts, the energy equation needs either a Dirichlet temperature boundary condition for an inlet condition,
```suggestion
Without applying integration by parts to the advection term, the energy equation needs a Dirichlet temperature boundary condition for an inlet condition.
```

2024-04-17 16:33 UTC, lindsayad commented on modules/navier_stokes/doc/content/source/bcs/INSFEFluidEnergyDirichletBC.md
> +or no boundary condition for an outlet condition.
```suggestion
This object additionally introduces a natural boundary condition at outlets.
```

2024-04-17 18:03 UTC, lindsayad approved these changes

2024-04-17 19:11 UTC, merged