Added convection heat flux functor material
idaholab/moose pull request #27248
Opened 2024-03-31 21:27 UTC by joshuahansel

Closes #27244

2024-03-31 21:31 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/2152407/) on f80a98c wanted to post the following:

Your code requires style changes.  

A patch was auto generated and copied [here](https://mooseframework.inl.gov/docs/PRs/27248/clang_format/style.patch)  
You can directly apply the patch by running, in the top level of your repository:

`curl -s https://mooseframework.inl.gov/docs/PRs/27248/clang_format/style.patch | git apply -v`  

Alternatively, with your repository up to date and in the top level of your repository:

`git clang-format 8f588bb7362520f92cf17a260d2b31e1acc1ac30`

2024-03-31 21:48 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/2152454/) on 26d985b wanted to post the following:

Your code requires style changes.  

A patch was auto generated and copied [here](https://mooseframework.inl.gov/docs/PRs/27248/clang_format/style.patch)  
You can directly apply the patch by running, in the top level of your repository:

`curl -s https://mooseframework.inl.gov/docs/PRs/27248/clang_format/style.patch | git apply -v`  

Alternatively, with your repository up to date and in the top level of your repository:

`git clang-format 8f588bb7362520f92cf17a260d2b31e1acc1ac30`

2024-04-01 00:10 UTC, moosebuild commented
Job [Documentation](https://civet.inl.gov/job/2152545/) on 572fb31 wanted to post the following:

View the site [here](https://mooseframework.inl.gov/docs/PRs/27248/site)

This comment will be updated on new commits.

2024-04-01 15:23 UTC, moosebuild commented
Job [Coverage](https://civet.inl.gov/job/2153168/) on 58d12a4 wanted to post the following:


## Framework coverage

Coverage did not change


## Modules coverage

### Heat transfer

<table>
  <thead>
    <tr>
      <th></th>
      <th>b02bb1</th>
      <th colspan=4>#27248 58d12a</th>
    </tr>
    <tr>
      <th></th>
      <th>Total</th>
      <th>Total</th>
      <th>+/-</th>
      <th>New</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><b>Rate</b></td>
      <td>88.50%</td>
      <td>88.53%</td>
      <td>+0.04%</td>
      <td>95.65%</td>
    </tr>
    <tr>
      <td><b>Hits</b></td>
      <td>4077</td>
      <td>4099</td>
      <td>+22</td>
      <td>22</td>
    </tr>
    <tr>
      <td><b>Misses</b></td>
      <td>530</td>
      <td>531</td>
      <td>+1</td>
      <td>1</td>
    </tr>
  </tbody>
</table>

[Diff coverage report](https://mooseframework.inl.gov/docs/PRs/27248/coverage_diff/heat_transfer)

[Full coverage report](https://mooseframework.inl.gov/docs/PRs/27248/coverage/heat_transfer)

## Full coverage reports

<details>
<summary>Reports</summary>

- [`framework`](https://mooseframework.inl.gov/docs/PRs/27248/coverage/framework)
- [`chemical_reactions`](https://mooseframework.inl.gov/docs/PRs/27248/coverage/chemical_reactions)
- [`combined`](https://mooseframework.inl.gov/docs/PRs/27248/coverage/combined)
- [`contact`](https://mooseframework.inl.gov/docs/PRs/27248/coverage/contact)
- [`electromagnetics`](https://mooseframework.inl.gov/docs/PRs/27248/coverage/electromagnetics)
- [`external_petsc_solver`](https://mooseframework.inl.gov/docs/PRs/27248/coverage/external_petsc_solver)
- [`fluid_properties`](https://mooseframework.inl.gov/docs/PRs/27248/coverage/fluid_properties)
- [`fsi`](https://mooseframework.inl.gov/docs/PRs/27248/coverage/fsi)
- [`functional_expansion_tools`](https://mooseframework.inl.gov/docs/PRs/27248/coverage/functional_expansion_tools)
- [`geochemistry`](https://mooseframework.inl.gov/docs/PRs/27248/coverage/geochemistry)
- [`heat_transfer`](https://mooseframework.inl.gov/docs/PRs/27248/coverage/heat_transfer)
- [`level_set`](https://mooseframework.inl.gov/docs/PRs/27248/coverage/level_set)
- [`misc`](https://mooseframework.inl.gov/docs/PRs/27248/coverage/misc)
- [`navier_stokes`](https://mooseframework.inl.gov/docs/PRs/27248/coverage/navier_stokes)
- [`optimization`](https://mooseframework.inl.gov/docs/PRs/27248/coverage/optimization)
- [`peridynamics`](https://mooseframework.inl.gov/docs/PRs/27248/coverage/peridynamics)
- [`phase_field`](https://mooseframework.inl.gov/docs/PRs/27248/coverage/phase_field)
- [`porous_flow`](https://mooseframework.inl.gov/docs/PRs/27248/coverage/porous_flow)
- [`ray_tracing`](https://mooseframework.inl.gov/docs/PRs/27248/coverage/ray_tracing)
- [`rdg`](https://mooseframework.inl.gov/docs/PRs/27248/coverage/rdg)
- [`reactor`](https://mooseframework.inl.gov/docs/PRs/27248/coverage/reactor)
- [`richards`](https://mooseframework.inl.gov/docs/PRs/27248/coverage/richards)
- [`scalar_transport`](https://mooseframework.inl.gov/docs/PRs/27248/coverage/scalar_transport)
- [`solid_mechanics`](https://mooseframework.inl.gov/docs/PRs/27248/coverage/solid_mechanics)
- [`solid_properties`](https://mooseframework.inl.gov/docs/PRs/27248/coverage/solid_properties)
- [`stochastic_tools`](https://mooseframework.inl.gov/docs/PRs/27248/coverage/stochastic_tools)
- [`thermal_hydraulics`](https://mooseframework.inl.gov/docs/PRs/27248/coverage/thermal_hydraulics)
- [`xfem`](https://mooseframework.inl.gov/docs/PRs/27248/coverage/xfem)

</details>



This comment will be updated on new commits.

2024-04-01 20:28 UTC, joshuahansel commented
Self review: add newsletter entry.

2024-04-02 05:55 UTC, lindsayad requested changes

2024-04-02 05:55 UTC, lindsayad commented on modules/heat_transfer/src/functormaterials/ConvectionHeatFluxFunctorMaterial.C
> +        return _sign * htc * (T_fluid - T_solid);
I think the sign conventions here are confusing. The least confusing option to me would be to remove the sign from this functor material calculation and just define this functor material property as the heat flux in a normal direction pointing from the fluid to the solid. The documentation could then be amended to drop $\gamma$, and I would then substitute $q = -\vec{q} \cdot n_{solid}$ with $q = \vec{q} \cdot n_{fluid}$. Then a kernel can apply a sign

2024-04-08 17:51 UTC, moosebuild commented
Job [Docker moose-dev](https://civet.inl.gov/job/2165568/) on 42dd9aa : invalidated by @milljm

2024-04-08 19:03 UTC, lindsayad approved these changes

2024-04-09 12:34 UTC, merged