Documentation improvements
idaholab/moose pull request #27279
Opened 2024-04-04 13:57 UTC by nmnobre

2024-04-04 14:01 UTC, dschwen approved these changes
Thanks!

2024-04-04 16:00 UTC, moosebuild commented
Job [Documentation](https://civet.inl.gov/job/2161232/) on 94e6c7c wanted to post the following:

View the site [here](https://mooseframework.inl.gov/docs/PRs/27279/site)

This comment will be updated on new commits.

2024-04-04 22:38 UTC, moosebuild commented
Job [Coverage](https://civet.inl.gov/job/2162187/) on 16d32e1 wanted to post the following:


## Framework coverage

<table>
  <thead>
    <tr>
      <th></th>
      <th>6f586d</th>
      <th colspan=4>#27279 16d32e</th>
    </tr>
    <tr>
      <th></th>
      <th>Total</th>
      <th>Total</th>
      <th>+/-</th>
      <th>New</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><b>Rate</b></td>
      <td>85.16%</td>
      <td>85.16%</td>
      <td>-0.00%</td>
      <td>100.00%</td>
    </tr>
    <tr>
      <td><b>Hits</b></td>
      <td>102690</td>
      <td>102689</td>
      <td>-1</td>
      <td>1</td>
    </tr>
    <tr>
      <td><b>Misses</b></td>
      <td>17897</td>
      <td>17898</td>
      <td>+1</td>
      <td>0</td>
    </tr>
  </tbody>
</table>

[Diff coverage report](https://mooseframework.inl.gov/docs/PRs/27279/coverage_diff/framework)

[Full coverage report](https://mooseframework.inl.gov/docs/PRs/27279/coverage/framework)


## Modules coverage

Coverage did not change

## Full coverage reports

<details>
<summary>Reports</summary>

- [`framework`](https://mooseframework.inl.gov/docs/PRs/27279/coverage/framework)
- [`chemical_reactions`](https://mooseframework.inl.gov/docs/PRs/27279/coverage/chemical_reactions)
- [`combined`](https://mooseframework.inl.gov/docs/PRs/27279/coverage/combined)
- [`contact`](https://mooseframework.inl.gov/docs/PRs/27279/coverage/contact)
- [`electromagnetics`](https://mooseframework.inl.gov/docs/PRs/27279/coverage/electromagnetics)
- [`external_petsc_solver`](https://mooseframework.inl.gov/docs/PRs/27279/coverage/external_petsc_solver)
- [`fluid_properties`](https://mooseframework.inl.gov/docs/PRs/27279/coverage/fluid_properties)
- [`fsi`](https://mooseframework.inl.gov/docs/PRs/27279/coverage/fsi)
- [`functional_expansion_tools`](https://mooseframework.inl.gov/docs/PRs/27279/coverage/functional_expansion_tools)
- [`geochemistry`](https://mooseframework.inl.gov/docs/PRs/27279/coverage/geochemistry)
- [`heat_transfer`](https://mooseframework.inl.gov/docs/PRs/27279/coverage/heat_transfer)
- [`level_set`](https://mooseframework.inl.gov/docs/PRs/27279/coverage/level_set)
- [`misc`](https://mooseframework.inl.gov/docs/PRs/27279/coverage/misc)
- [`navier_stokes`](https://mooseframework.inl.gov/docs/PRs/27279/coverage/navier_stokes)
- [`optimization`](https://mooseframework.inl.gov/docs/PRs/27279/coverage/optimization)
- [`peridynamics`](https://mooseframework.inl.gov/docs/PRs/27279/coverage/peridynamics)
- [`phase_field`](https://mooseframework.inl.gov/docs/PRs/27279/coverage/phase_field)
- [`porous_flow`](https://mooseframework.inl.gov/docs/PRs/27279/coverage/porous_flow)
- [`ray_tracing`](https://mooseframework.inl.gov/docs/PRs/27279/coverage/ray_tracing)
- [`rdg`](https://mooseframework.inl.gov/docs/PRs/27279/coverage/rdg)
- [`reactor`](https://mooseframework.inl.gov/docs/PRs/27279/coverage/reactor)
- [`richards`](https://mooseframework.inl.gov/docs/PRs/27279/coverage/richards)
- [`scalar_transport`](https://mooseframework.inl.gov/docs/PRs/27279/coverage/scalar_transport)
- [`solid_mechanics`](https://mooseframework.inl.gov/docs/PRs/27279/coverage/solid_mechanics)
- [`solid_properties`](https://mooseframework.inl.gov/docs/PRs/27279/coverage/solid_properties)
- [`stochastic_tools`](https://mooseframework.inl.gov/docs/PRs/27279/coverage/stochastic_tools)
- [`thermal_hydraulics`](https://mooseframework.inl.gov/docs/PRs/27279/coverage/thermal_hydraulics)
- [`xfem`](https://mooseframework.inl.gov/docs/PRs/27279/coverage/xfem)

</details>



This comment will be updated on new commits.

2024-04-09 04:00 UTC, GiudGiud requested changes

2024-04-09 04:00 UTC, GiudGiud commented on framework/doc/content/source/kernels/FunctionDiffusion.md
> +  - \nabla \cdot f(\mathbf{r}, t) \nabla v
I dont think so. it's missing a few terms for that to be true, see FunctionDiffusion.C

2024-04-09 04:01 UTC, GiudGiud commented on framework/doc/content/source/kernels/FunctionDiffusion.md
> +  - \nabla \cdot f(\mathbf{r}, t) \nabla v
nevermind!

2024-04-09 04:02 UTC, GiudGiud approved these changes

2024-04-09 04:02 UTC, merged