Disallow all plane formulations with new lagrangian kernels in SM physics
idaholab/moose pull request #27366
Opened 2024-04-12 20:43 UTC by GiudGiud

refs #27340

until it s implemented in the physics action, it will fix the bad error we get now

2024-04-12 20:44 UTC, GiudGiud commented on modules/solid_mechanics/src/physics/QuasiStaticSolidMechanicsPhysics.C
> +        paramError("Plane formulation not available with Lagrangian kernels");
umm actually wrong location

2024-04-12 22:03 UTC, hugary1995 commented
Can we use that new `mooseDocumentedError` API (or whatever that is)?

You could extend it to `paramDocumentedError` while you are at it. :)

2024-04-12 22:15 UTC, GiudGiud commented
> You could extend it to paramDocumentedError while you are at it. :)

will have to be for another day. I m back from travel and catching up on a lot of stuff

2024-04-13 00:27 UTC, moosebuild commented
Job [Documentation](https://civet.inl.gov/job/2173482/) on dab41f3 wanted to post the following:

View the site [here](https://mooseframework.inl.gov/docs/PRs/27366/site)

This comment will be updated on new commits.

2024-04-13 01:11 UTC, moosebuild commented
Job [Coverage](https://civet.inl.gov/job/2173497/) on dab41f3 wanted to post the following:


## Framework coverage

<table>
  <thead>
    <tr>
      <th></th>
      <th>374a78</th>
      <th colspan=4>#27366 dab41f</th>
    </tr>
    <tr>
      <th></th>
      <th>Total</th>
      <th>Total</th>
      <th>+/-</th>
      <th>New</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><b>Rate</b></td>
      <td>85.13%</td>
      <td>85.14%</td>
      <td>+0.00%</td>
      <td>-</td>
    </tr>
    <tr>
      <td><b>Hits</b></td>
      <td>102690</td>
      <td>102691</td>
      <td>+1</td>
      <td>0</td>
    </tr>
    <tr>
      <td><b>Misses</b></td>
      <td>17931</td>
      <td>17930</td>
      <td>-1</td>
      <td>0</td>
    </tr>
  </tbody>
</table>

[Diff coverage report](https://mooseframework.inl.gov/docs/PRs/27366/coverage_diff/framework)

[Full coverage report](https://mooseframework.inl.gov/docs/PRs/27366/coverage/framework)


## Modules coverage

### Solid mechanics

<table>
  <thead>
    <tr>
      <th></th>
      <th>374a78</th>
      <th colspan=4>#27366 dab41f</th>
    </tr>
    <tr>
      <th></th>
      <th>Total</th>
      <th>Total</th>
      <th>+/-</th>
      <th>New</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><b>Rate</b></td>
      <td>84.76%</td>
      <td>84.76%</td>
      <td>-</td>
      <td>50.00%</td>
    </tr>
    <tr>
      <td><b>Hits</b></td>
      <td>27120</td>
      <td>27120</td>
      <td>-</td>
      <td>1</td>
    </tr>
    <tr>
      <td><b>Misses</b></td>
      <td>4878</td>
      <td>4878</td>
      <td>-</td>
      <td>1</td>
    </tr>
  </tbody>
</table>

[Diff coverage report](https://mooseframework.inl.gov/docs/PRs/27366/coverage_diff/solid_mechanics)

[Full coverage report](https://mooseframework.inl.gov/docs/PRs/27366/coverage/solid_mechanics)

## Full coverage reports

<details>
<summary>Reports</summary>

- [`framework`](https://mooseframework.inl.gov/docs/PRs/27366/coverage/framework)
- [`chemical_reactions`](https://mooseframework.inl.gov/docs/PRs/27366/coverage/chemical_reactions)
- [`combined`](https://mooseframework.inl.gov/docs/PRs/27366/coverage/combined)
- [`contact`](https://mooseframework.inl.gov/docs/PRs/27366/coverage/contact)
- [`electromagnetics`](https://mooseframework.inl.gov/docs/PRs/27366/coverage/electromagnetics)
- [`external_petsc_solver`](https://mooseframework.inl.gov/docs/PRs/27366/coverage/external_petsc_solver)
- [`fluid_properties`](https://mooseframework.inl.gov/docs/PRs/27366/coverage/fluid_properties)
- [`fsi`](https://mooseframework.inl.gov/docs/PRs/27366/coverage/fsi)
- [`functional_expansion_tools`](https://mooseframework.inl.gov/docs/PRs/27366/coverage/functional_expansion_tools)
- [`geochemistry`](https://mooseframework.inl.gov/docs/PRs/27366/coverage/geochemistry)
- [`heat_transfer`](https://mooseframework.inl.gov/docs/PRs/27366/coverage/heat_transfer)
- [`level_set`](https://mooseframework.inl.gov/docs/PRs/27366/coverage/level_set)
- [`misc`](https://mooseframework.inl.gov/docs/PRs/27366/coverage/misc)
- [`navier_stokes`](https://mooseframework.inl.gov/docs/PRs/27366/coverage/navier_stokes)
- [`optimization`](https://mooseframework.inl.gov/docs/PRs/27366/coverage/optimization)
- [`peridynamics`](https://mooseframework.inl.gov/docs/PRs/27366/coverage/peridynamics)
- [`phase_field`](https://mooseframework.inl.gov/docs/PRs/27366/coverage/phase_field)
- [`porous_flow`](https://mooseframework.inl.gov/docs/PRs/27366/coverage/porous_flow)
- [`ray_tracing`](https://mooseframework.inl.gov/docs/PRs/27366/coverage/ray_tracing)
- [`rdg`](https://mooseframework.inl.gov/docs/PRs/27366/coverage/rdg)
- [`reactor`](https://mooseframework.inl.gov/docs/PRs/27366/coverage/reactor)
- [`richards`](https://mooseframework.inl.gov/docs/PRs/27366/coverage/richards)
- [`scalar_transport`](https://mooseframework.inl.gov/docs/PRs/27366/coverage/scalar_transport)
- [`solid_mechanics`](https://mooseframework.inl.gov/docs/PRs/27366/coverage/solid_mechanics)
- [`solid_properties`](https://mooseframework.inl.gov/docs/PRs/27366/coverage/solid_properties)
- [`stochastic_tools`](https://mooseframework.inl.gov/docs/PRs/27366/coverage/stochastic_tools)
- [`thermal_hydraulics`](https://mooseframework.inl.gov/docs/PRs/27366/coverage/thermal_hydraulics)
- [`xfem`](https://mooseframework.inl.gov/docs/PRs/27366/coverage/xfem)

</details>

## Warnings

- `solid_mechanics` new line coverage rate 50.00% is less than the suggested 90.0%



This comment will be updated on new commits.

2024-04-13 01:19 UTC, hugary1995 requested changes
I'm guilty of this. Let's hold this off till next Monday. I may be able to _actually_ resolve this issue over the weekend. Let's merge this PR otherwise.

2024-04-13 01:19 UTC, hugary1995 commented on modules/solid_mechanics/src/physics/QuasiStaticSolidMechanicsPhysics.C
> +          "moose", 27340, "Plane formulation not available with Lagrangian kernels");
```suggestion
          "moose", 27340, "Planar formulations are not yet available through the Physics syntax with new_system = true. They can be enabled by manually setting up the appropriate objects. Please refer to the documentation and regression tests for examples.");
```

2024-04-29 14:04 UTC, hugary1995 approved these changes
I am working on rewriting the action. But this is definitely a good error message in the interim. Thanks.

2024-04-29 14:22 UTC, merged