Added FixedPointIterationTargetDT
idaholab/moose pull request #27382
Opened 2024-04-16 13:12 UTC by joshuahansel

Closes #27381

2024-04-16 15:22 UTC, moosebuild commented
Job [Documentation](https://civet.inl.gov/job/2178300/) on c030d7b wanted to post the following:

View the site [here](https://mooseframework.inl.gov/docs/PRs/27382/site)

This comment will be updated on new commits.

2024-04-16 19:49 UTC, GiudGiud commented
Instead of TargetDT, maybe AdaptiveDT, that way it follows the same naming convention as the other one?

2024-04-16 22:12 UTC, joshuahansel commented
> Instead of TargetDT, maybe AdaptiveDT, that way it follows the same naming convention as the other one?
>
> alternatively you could fold this one into the IterationAdaptiveDT ?

I'll rename. I don't think anything else should go into IterationAdaptiveDT - I think it should be decomposed into multiple classes at some point.

2024-04-16 22:13 UTC, moosebuild commented
Job [Coverage](https://civet.inl.gov/job/2179119/) on 0c48b9f wanted to post the following:


## Framework coverage

<table>
  <thead>
    <tr>
      <th></th>
      <th>6a80be</th>
      <th colspan=4>#27382 0c48b9</th>
    </tr>
    <tr>
      <th></th>
      <th>Total</th>
      <th>Total</th>
      <th>+/-</th>
      <th>New</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><b>Rate</b></td>
      <td>85.12%</td>
      <td>85.12%</td>
      <td>-0.00%</td>
      <td>83.33%</td>
    </tr>
    <tr>
      <td><b>Hits</b></td>
      <td>102894</td>
      <td>102938</td>
      <td>+44</td>
      <td>45</td>
    </tr>
    <tr>
      <td><b>Misses</b></td>
      <td>17982</td>
      <td>17993</td>
      <td>+11</td>
      <td>9</td>
    </tr>
  </tbody>
</table>

[Diff coverage report](https://mooseframework.inl.gov/docs/PRs/27382/coverage_diff/framework)

[Full coverage report](https://mooseframework.inl.gov/docs/PRs/27382/coverage/framework)


## Modules coverage

Coverage did not change

## Full coverage reports

<details>
<summary>Reports</summary>

- [`framework`](https://mooseframework.inl.gov/docs/PRs/27382/coverage/framework)
- [`chemical_reactions`](https://mooseframework.inl.gov/docs/PRs/27382/coverage/chemical_reactions)
- [`combined`](https://mooseframework.inl.gov/docs/PRs/27382/coverage/combined)
- [`contact`](https://mooseframework.inl.gov/docs/PRs/27382/coverage/contact)
- [`electromagnetics`](https://mooseframework.inl.gov/docs/PRs/27382/coverage/electromagnetics)
- [`external_petsc_solver`](https://mooseframework.inl.gov/docs/PRs/27382/coverage/external_petsc_solver)
- [`fluid_properties`](https://mooseframework.inl.gov/docs/PRs/27382/coverage/fluid_properties)
- [`fsi`](https://mooseframework.inl.gov/docs/PRs/27382/coverage/fsi)
- [`functional_expansion_tools`](https://mooseframework.inl.gov/docs/PRs/27382/coverage/functional_expansion_tools)
- [`geochemistry`](https://mooseframework.inl.gov/docs/PRs/27382/coverage/geochemistry)
- [`heat_transfer`](https://mooseframework.inl.gov/docs/PRs/27382/coverage/heat_transfer)
- [`level_set`](https://mooseframework.inl.gov/docs/PRs/27382/coverage/level_set)
- [`misc`](https://mooseframework.inl.gov/docs/PRs/27382/coverage/misc)
- [`navier_stokes`](https://mooseframework.inl.gov/docs/PRs/27382/coverage/navier_stokes)
- [`optimization`](https://mooseframework.inl.gov/docs/PRs/27382/coverage/optimization)
- [`peridynamics`](https://mooseframework.inl.gov/docs/PRs/27382/coverage/peridynamics)
- [`phase_field`](https://mooseframework.inl.gov/docs/PRs/27382/coverage/phase_field)
- [`porous_flow`](https://mooseframework.inl.gov/docs/PRs/27382/coverage/porous_flow)
- [`ray_tracing`](https://mooseframework.inl.gov/docs/PRs/27382/coverage/ray_tracing)
- [`rdg`](https://mooseframework.inl.gov/docs/PRs/27382/coverage/rdg)
- [`reactor`](https://mooseframework.inl.gov/docs/PRs/27382/coverage/reactor)
- [`richards`](https://mooseframework.inl.gov/docs/PRs/27382/coverage/richards)
- [`scalar_transport`](https://mooseframework.inl.gov/docs/PRs/27382/coverage/scalar_transport)
- [`solid_mechanics`](https://mooseframework.inl.gov/docs/PRs/27382/coverage/solid_mechanics)
- [`solid_properties`](https://mooseframework.inl.gov/docs/PRs/27382/coverage/solid_properties)
- [`stochastic_tools`](https://mooseframework.inl.gov/docs/PRs/27382/coverage/stochastic_tools)
- [`thermal_hydraulics`](https://mooseframework.inl.gov/docs/PRs/27382/coverage/thermal_hydraulics)
- [`xfem`](https://mooseframework.inl.gov/docs/PRs/27382/coverage/xfem)

</details>

## Warnings

- `framework` new line coverage rate 83.33% is less than the suggested 90.0%



This comment will be updated on new commits.

2024-04-17 13:56 UTC, GiudGiud requested changes
pretty clever. I should have added something like that when working on SAM-Pgh FPs too it would have helped

2024-04-17 13:56 UTC, GiudGiud commented on framework/src/timesteppers/FixedPointIterationAdaptiveDT.C
> +  params.addRequiredParam<Real>("dt_initial", "The initial time step size");
use rangeChecked params for all the Real

2024-04-17 13:56 UTC, GiudGiud commented on test/tests/time_steppers/fixed_point_iteration_adaptive_dt/tests
> +    requirement = "The system shall be able to increase the time step size when below the target number of fixed point iterations."
```suggestion
    requirement = "The system shall be able to increase the time step size when the simulation converges with less fixed point iterations than the target number."
```

2024-04-17 13:56 UTC, GiudGiud commented on test/tests/time_steppers/fixed_point_iteration_adaptive_dt/tests
> +    requirement = "The system shall be able to decrease the time step size when above the target number of fixed point iterations."
```suggestion
 "The system shall be able to decrease the time step size when the simulation converges with more fixed point iterations than the target number."
```

2024-04-17 13:56 UTC, GiudGiud commented on test/tests/time_steppers/fixed_point_iteration_adaptive_dt/tests
> +    requirement = 'The system shall report an error if the fixed point target time stepper is used in an application with no sub-applications.'
```suggestion
    requirement = 'The system shall report an error if the fixed point target time stepper is used in an application with no child-applications and no fixed point iterations between applications.'
```

2024-04-17 13:56 UTC, GiudGiud commented on framework/src/timesteppers/FixedPointIterationAdaptiveDT.C
> +    mooseError("This time stepper can only be used if there are MultiApps in the problem.");
need to check that fixed point iterations are in use, which the executioner would know about

2024-04-17 18:48 UTC, GiudGiud approved these changes

2024-04-22 12:16 UTC, merged