Material suffix 27440
idaholab/moose pull request #27442
Opened 2024-04-22 20:49 UTC by grmnptr

Closes #27440

2024-04-23 14:33 UTC, moosebuild commented
All [jobs](https://civet.inl.gov/event/176794/) on 8725ae3 : invalidated by @grmnptr

2024-04-24 04:21 UTC, moosebuild commented
Job [Coverage](https://civet.inl.gov/job/2189686/) on 8725ae3 wanted to post the following:


## Framework coverage

<table>
  <thead>
    <tr>
      <th></th>
      <th>4e99fa</th>
      <th colspan=4>#27442 8725ae</th>
    </tr>
    <tr>
      <th></th>
      <th>Total</th>
      <th>Total</th>
      <th>+/-</th>
      <th>New</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><b>Rate</b></td>
      <td>85.12%</td>
      <td>85.12%</td>
      <td>+0.00%</td>
      <td>100.00%</td>
    </tr>
    <tr>
      <td><b>Hits</b></td>
      <td>102933</td>
      <td>102935</td>
      <td>+2</td>
      <td>3</td>
    </tr>
    <tr>
      <td><b>Misses</b></td>
      <td>18001</td>
      <td>18001</td>
      <td>-</td>
      <td>0</td>
    </tr>
  </tbody>
</table>

[Diff coverage report](https://mooseframework.inl.gov/docs/PRs/27442/coverage_diff/framework)

[Full coverage report](https://mooseframework.inl.gov/docs/PRs/27442/coverage/framework)


## Modules coverage

Coverage did not change

## Full coverage reports

<details>
<summary>Reports</summary>

- [`framework`](https://mooseframework.inl.gov/docs/PRs/27442/coverage/framework)
- [`chemical_reactions`](https://mooseframework.inl.gov/docs/PRs/27442/coverage/chemical_reactions)
- [`combined`](https://mooseframework.inl.gov/docs/PRs/27442/coverage/combined)
- [`contact`](https://mooseframework.inl.gov/docs/PRs/27442/coverage/contact)
- [`electromagnetics`](https://mooseframework.inl.gov/docs/PRs/27442/coverage/electromagnetics)
- [`external_petsc_solver`](https://mooseframework.inl.gov/docs/PRs/27442/coverage/external_petsc_solver)
- [`fluid_properties`](https://mooseframework.inl.gov/docs/PRs/27442/coverage/fluid_properties)
- [`fsi`](https://mooseframework.inl.gov/docs/PRs/27442/coverage/fsi)
- [`functional_expansion_tools`](https://mooseframework.inl.gov/docs/PRs/27442/coverage/functional_expansion_tools)
- [`geochemistry`](https://mooseframework.inl.gov/docs/PRs/27442/coverage/geochemistry)
- [`heat_transfer`](https://mooseframework.inl.gov/docs/PRs/27442/coverage/heat_transfer)
- [`level_set`](https://mooseframework.inl.gov/docs/PRs/27442/coverage/level_set)
- [`misc`](https://mooseframework.inl.gov/docs/PRs/27442/coverage/misc)
- [`navier_stokes`](https://mooseframework.inl.gov/docs/PRs/27442/coverage/navier_stokes)
- [`optimization`](https://mooseframework.inl.gov/docs/PRs/27442/coverage/optimization)
- [`peridynamics`](https://mooseframework.inl.gov/docs/PRs/27442/coverage/peridynamics)
- [`phase_field`](https://mooseframework.inl.gov/docs/PRs/27442/coverage/phase_field)
- [`porous_flow`](https://mooseframework.inl.gov/docs/PRs/27442/coverage/porous_flow)
- [`ray_tracing`](https://mooseframework.inl.gov/docs/PRs/27442/coverage/ray_tracing)
- [`rdg`](https://mooseframework.inl.gov/docs/PRs/27442/coverage/rdg)
- [`reactor`](https://mooseframework.inl.gov/docs/PRs/27442/coverage/reactor)
- [`richards`](https://mooseframework.inl.gov/docs/PRs/27442/coverage/richards)
- [`scalar_transport`](https://mooseframework.inl.gov/docs/PRs/27442/coverage/scalar_transport)
- [`solid_mechanics`](https://mooseframework.inl.gov/docs/PRs/27442/coverage/solid_mechanics)
- [`solid_properties`](https://mooseframework.inl.gov/docs/PRs/27442/coverage/solid_properties)
- [`stochastic_tools`](https://mooseframework.inl.gov/docs/PRs/27442/coverage/stochastic_tools)
- [`thermal_hydraulics`](https://mooseframework.inl.gov/docs/PRs/27442/coverage/thermal_hydraulics)
- [`xfem`](https://mooseframework.inl.gov/docs/PRs/27442/coverage/xfem)

</details>



This comment will be updated on new commits.

2024-04-24 04:36 UTC, moosebuild commented
Job [Documentation](https://civet.inl.gov/job/2189671/) on 8725ae3 wanted to post the following:

View the site [here](https://mooseframework.inl.gov/docs/PRs/27442/site)

This comment will be updated on new commits.

2024-04-24 15:39 UTC, GiudGiud commented on framework/include/functormaterials/FunctorMaterial.h
> +      (_get_suffix == "" ? "" : _get_suffix + "_") + prop_name,
this is a prefix not a suffix

2024-04-24 15:40 UTC, GiudGiud requested changes

2024-04-24 15:40 UTC, GiudGiud commented on test/tests/functormaterials/with_suffix/tests
> +    requirement = 'The system should be able to add a generic functor material with a suffix for the properties.'
```suggestion
    requirement = 'The system should be able to add a generic functor material with a prefix for the names of the properties.'
```

2024-04-29 16:47 UTC, grmnptr commented on framework/include/functormaterials/FunctorMaterial.h
> +      (_get_suffix == "" ? "" : _get_suffix + "_") + prop_name,
ahh nice

2024-04-29 16:57 UTC, GiudGiud approved these changes

2024-04-29 18:00 UTC, lindsayad approved these changes

2024-04-29 23:50 UTC, moosebuild commented
Job [Modules parallel](https://civet.inl.gov/job/2200218/) on 8b42552 : invalidated by @grmnptr

2024-04-30 14:13 UTC, grmnptr commented
Failures were unrelated.

2024-04-30 14:13 UTC, merged