27449 update min gcc
idaholab/moose pull request #27454
Opened 2024-04-23 16:55 UTC by milljm

Update the minimum stated gcc version

Closes #27449

2024-04-23 22:08 UTC, cticenhour requested changes

2024-04-23 22:08 UTC, cticenhour commented on framework/doc/content/sqa/minimum_requirements.md
> +Macintosh machine running either of the last two releases.
```suggestion
A [!ac](POSIX) compliant Unix-like operating system. This includes any modern Linux-based operating system (e.g., Ubuntu, Fedora, Rocky, etc.), or a
Macintosh machine running either of the last two MacOS releases.
```

I still like calling them "Macintosh" too 😂

2024-04-23 22:08 UTC, cticenhour commented on framework/doc/content/sqa/minimum_requirements.md
> +| Intel | Not supported at this time |
```suggestion
| Intel (ICC / ICX) | Not supported at this time |
```

2024-04-24 05:40 UTC, moosebuild commented
Job [Documentation](https://civet.inl.gov/job/2190938/) on 63d8c64 wanted to post the following:

View the site [here](https://mooseframework.inl.gov/docs/PRs/27454/site)

This comment will be updated on new commits.

2024-04-24 15:44 UTC, GiudGiud approved these changes

2024-04-24 16:03 UTC, loganharbour approved these changes

2024-04-24 16:18 UTC, cticenhour approved these changes

2024-04-24 16:26 UTC, merged