Proposed new training
idaholab/moose pull request #27572
Opened 2024-05-08 01:18 UTC by GiudGiud

TODO at least:
- [ ] rebase
- [ ] re-add C++ content for the full version of the training
- [ ] remove all 3D slow calcs. Make training mostly 2D and make all steps work flawlessly
- [ ] add pre-checked in graphics

2024-05-08 01:23 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/2217847/) on aff2e3c wanted to post the following:

Warning: This PR changes repo size by 22.59 MiB.

2024-05-08 03:50 UTC, moosebuild commented
Job [Documentation](https://civet.inl.gov/job/2217843/) on aff2e3c wanted to post the following:

View the site [here](https://mooseframework.inl.gov/docs/PRs/27572/site)

This comment will be updated on new commits.

2024-05-08 04:23 UTC, moosebuild commented
Job [Coverage](https://civet.inl.gov/job/2217887/) on aff2e3c wanted to post the following:


## Framework coverage

<table>
  <thead>
    <tr>
      <th></th>
      <th>b3efaa</th>
      <th colspan=4>#27572 aff2e3</th>
    </tr>
    <tr>
      <th></th>
      <th>Total</th>
      <th>Total</th>
      <th>+/-</th>
      <th>New</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><b>Rate</b></td>
      <td>85.11%</td>
      <td>85.11%</td>
      <td>+0.00%</td>
      <td>-</td>
    </tr>
    <tr>
      <td><b>Hits</b></td>
      <td>103108</td>
      <td>103109</td>
      <td>+1</td>
      <td>0</td>
    </tr>
    <tr>
      <td><b>Misses</b></td>
      <td>18044</td>
      <td>18043</td>
      <td>-1</td>
      <td>0</td>
    </tr>
  </tbody>
</table>

[Diff coverage report](https://mooseframework.inl.gov/docs/PRs/27572/coverage_diff/framework)

[Full coverage report](https://mooseframework.inl.gov/docs/PRs/27572/coverage/framework)


## Modules coverage

Coverage did not change

## Full coverage reports

<details>
<summary>Reports</summary>

- [`framework`](https://mooseframework.inl.gov/docs/PRs/27572/coverage/framework)
- [`chemical_reactions`](https://mooseframework.inl.gov/docs/PRs/27572/coverage/chemical_reactions)
- [`combined`](https://mooseframework.inl.gov/docs/PRs/27572/coverage/combined)
- [`contact`](https://mooseframework.inl.gov/docs/PRs/27572/coverage/contact)
- [`electromagnetics`](https://mooseframework.inl.gov/docs/PRs/27572/coverage/electromagnetics)
- [`external_petsc_solver`](https://mooseframework.inl.gov/docs/PRs/27572/coverage/external_petsc_solver)
- [`fluid_properties`](https://mooseframework.inl.gov/docs/PRs/27572/coverage/fluid_properties)
- [`fsi`](https://mooseframework.inl.gov/docs/PRs/27572/coverage/fsi)
- [`functional_expansion_tools`](https://mooseframework.inl.gov/docs/PRs/27572/coverage/functional_expansion_tools)
- [`geochemistry`](https://mooseframework.inl.gov/docs/PRs/27572/coverage/geochemistry)
- [`heat_transfer`](https://mooseframework.inl.gov/docs/PRs/27572/coverage/heat_transfer)
- [`level_set`](https://mooseframework.inl.gov/docs/PRs/27572/coverage/level_set)
- [`misc`](https://mooseframework.inl.gov/docs/PRs/27572/coverage/misc)
- [`navier_stokes`](https://mooseframework.inl.gov/docs/PRs/27572/coverage/navier_stokes)
- [`optimization`](https://mooseframework.inl.gov/docs/PRs/27572/coverage/optimization)
- [`peridynamics`](https://mooseframework.inl.gov/docs/PRs/27572/coverage/peridynamics)
- [`phase_field`](https://mooseframework.inl.gov/docs/PRs/27572/coverage/phase_field)
- [`porous_flow`](https://mooseframework.inl.gov/docs/PRs/27572/coverage/porous_flow)
- [`ray_tracing`](https://mooseframework.inl.gov/docs/PRs/27572/coverage/ray_tracing)
- [`rdg`](https://mooseframework.inl.gov/docs/PRs/27572/coverage/rdg)
- [`reactor`](https://mooseframework.inl.gov/docs/PRs/27572/coverage/reactor)
- [`richards`](https://mooseframework.inl.gov/docs/PRs/27572/coverage/richards)
- [`scalar_transport`](https://mooseframework.inl.gov/docs/PRs/27572/coverage/scalar_transport)
- [`solid_mechanics`](https://mooseframework.inl.gov/docs/PRs/27572/coverage/solid_mechanics)
- [`solid_properties`](https://mooseframework.inl.gov/docs/PRs/27572/coverage/solid_properties)
- [`stochastic_tools`](https://mooseframework.inl.gov/docs/PRs/27572/coverage/stochastic_tools)
- [`thermal_hydraulics`](https://mooseframework.inl.gov/docs/PRs/27572/coverage/thermal_hydraulics)
- [`xfem`](https://mooseframework.inl.gov/docs/PRs/27572/coverage/xfem)

</details>



This comment will be updated on new commits.

2024-12-07 13:27 UTC, GiudGiud commented
not yet

2025-01-13 02:58 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/2633521/), step Size check on e233e0f wanted to post the following:

Warning: This PR changes repo size by 22.59 MiB.

2025-01-13 05:15 UTC, moosebuild commented
Job [Documentation](https://civet.inl.gov/job/2633517/), step Docs: sync website on e233e0f wanted to post the following:

View the site [here](https://mooseframework.inl.gov/docs/PRs/27572/site)

This comment will be updated on new commits.

2025-01-15 04:05 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/2638369/), step Size check on 5b90683 wanted to post the following:

Warning: This PR changes repo size by 25.74 MiB.

2025-01-15 07:09 UTC, moosebuild commented
Job [Coverage](https://civet.inl.gov/job/2638412/), step Generate coverage on 5b90683 wanted to post the following:


## Framework coverage

Coverage did not change


## Modules coverage

Coverage did not change

## Full coverage reports

<details>
<summary>Reports</summary>

- [`framework`](https://mooseframework.inl.gov/docs/PRs/27572/coverage/framework)
- [`chemical_reactions`](https://mooseframework.inl.gov/docs/PRs/27572/coverage/chemical_reactions)
- [`combined`](https://mooseframework.inl.gov/docs/PRs/27572/coverage/combined)
- [`contact`](https://mooseframework.inl.gov/docs/PRs/27572/coverage/contact)
- [`electromagnetics`](https://mooseframework.inl.gov/docs/PRs/27572/coverage/electromagnetics)
- [`external_petsc_solver`](https://mooseframework.inl.gov/docs/PRs/27572/coverage/external_petsc_solver)
- [`fluid_properties`](https://mooseframework.inl.gov/docs/PRs/27572/coverage/fluid_properties)
- [`fsi`](https://mooseframework.inl.gov/docs/PRs/27572/coverage/fsi)
- [`functional_expansion_tools`](https://mooseframework.inl.gov/docs/PRs/27572/coverage/functional_expansion_tools)
- [`geochemistry`](https://mooseframework.inl.gov/docs/PRs/27572/coverage/geochemistry)
- [`heat_transfer`](https://mooseframework.inl.gov/docs/PRs/27572/coverage/heat_transfer)
- [`level_set`](https://mooseframework.inl.gov/docs/PRs/27572/coverage/level_set)
- [`misc`](https://mooseframework.inl.gov/docs/PRs/27572/coverage/misc)
- [`navier_stokes`](https://mooseframework.inl.gov/docs/PRs/27572/coverage/navier_stokes)
- [`optimization`](https://mooseframework.inl.gov/docs/PRs/27572/coverage/optimization)
- [`peridynamics`](https://mooseframework.inl.gov/docs/PRs/27572/coverage/peridynamics)
- [`phase_field`](https://mooseframework.inl.gov/docs/PRs/27572/coverage/phase_field)
- [`porous_flow`](https://mooseframework.inl.gov/docs/PRs/27572/coverage/porous_flow)
- [`ray_tracing`](https://mooseframework.inl.gov/docs/PRs/27572/coverage/ray_tracing)
- [`rdg`](https://mooseframework.inl.gov/docs/PRs/27572/coverage/rdg)
- [`reactor`](https://mooseframework.inl.gov/docs/PRs/27572/coverage/reactor)
- [`richards`](https://mooseframework.inl.gov/docs/PRs/27572/coverage/richards)
- [`scalar_transport`](https://mooseframework.inl.gov/docs/PRs/27572/coverage/scalar_transport)
- [`solid_mechanics`](https://mooseframework.inl.gov/docs/PRs/27572/coverage/solid_mechanics)
- [`solid_properties`](https://mooseframework.inl.gov/docs/PRs/27572/coverage/solid_properties)
- [`stochastic_tools`](https://mooseframework.inl.gov/docs/PRs/27572/coverage/stochastic_tools)
- [`thermal_hydraulics`](https://mooseframework.inl.gov/docs/PRs/27572/coverage/thermal_hydraulics)
- [`xfem`](https://mooseframework.inl.gov/docs/PRs/27572/coverage/xfem)

</details>



This comment will be updated on new commits.

2025-01-22 20:05 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/2647681/), step Clang format on 9b1393c wanted to post the following:

Your code requires style changes.  

A patch was auto generated and copied [here](https://mooseframework.inl.gov/docs/PRs/27572/clang_format/style.patch)  
You can directly apply the patch by running, in the top level of your repository:

`curl -s https://mooseframework.inl.gov/docs/PRs/27572/clang_format/style.patch | git apply -v`  

Alternatively, with your repository up to date and in the top level of your repository:

`git clang-format bf7a391b5da0313b05c3181a855130d329ea5b12`

2025-01-22 20:19 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/2647779/), step Fixup commit check on 78b70d8 wanted to post the following:

The following commit(s) contain fixups:

- 4fa86f0721: fixup! Use flux BCs in water, reduce cp to obtain T profile faster Add postprocessing Precondition each system separately

2025-01-23 04:01 UTC, moosebuild commented on large_media
> +Subproject commit 3ba8fc30775a481abc3663171da785ce47b39bfd
**Caution!** This contains a submodule update

2025-01-23 14:40 UTC, moosebuild commented on large_media
> +Subproject commit 3ba8fc30775a481abc3663171da785ce47b39bfd
**Caution!** This contains a submodule update

2025-01-23 14:48 UTC, moosebuild commented on large_media
> +Subproject commit 3ba8fc30775a481abc3663171da785ce47b39bfd
**Caution!** This contains a submodule update

2025-01-23 16:50 UTC, moosebuild commented on large_media
> +Subproject commit 3ba8fc30775a481abc3663171da785ce47b39bfd
**Caution!** This contains a submodule update

2025-01-24 23:28 UTC, moosebuild commented on large_media
> +Subproject commit 3ba8fc30775a481abc3663171da785ce47b39bfd
**Caution!** This contains a submodule update

2025-01-25 00:29 UTC, moosebuild commented on large_media
> +Subproject commit 3ba8fc30775a481abc3663171da785ce47b39bfd
**Caution!** This contains a submodule update

2025-01-25 01:05 UTC, moosebuild commented on large_media
> +Subproject commit 3ba8fc30775a481abc3663171da785ce47b39bfd
**Caution!** This contains a submodule update

2025-01-29 19:51 UTC, moosebuild commented on large_media
> +Subproject commit 3ba8fc30775a481abc3663171da785ce47b39bfd
**Caution!** This contains a submodule update

2025-02-28 18:09 UTC, moosebuild commented on large_media
> +Subproject commit 7df25da9663f229a3a89db8e8e3bfe66caf9f712
**Caution!** This contains a submodule update

2025-03-03 16:20 UTC, moosebuild commented on large_media
> +Subproject commit 7df25da9663f229a3a89db8e8e3bfe66caf9f712
**Caution!** This contains a submodule update

2025-03-03 16:40 UTC, moosebuild commented on large_media
> +Subproject commit 7df25da9663f229a3a89db8e8e3bfe66caf9f712
**Caution!** This contains a submodule update

2025-03-03 20:03 UTC, moosebuild commented on large_media
> +Subproject commit 7df25da9663f229a3a89db8e8e3bfe66caf9f712
**Caution!** This contains a submodule update

2025-03-06 00:21 UTC, loganharbour requested changes, later dismissed

2025-03-07 21:46 UTC, moosebuild commented on large_media
> +Subproject commit af3ee20e55f7e493d807db706e473da5a7e6027d
**Caution!** This contains a submodule update

2025-05-22 13:08 UTC, zachmprince commented
> @zachmprince what were we missing here?

@GiudGiud nothing from my end, it is ready for review.

2025-05-22 13:37 UTC, GiudGiud commented
Test failure is unrelated.
We are missing testing. @loganharbour could you please help with that? We would ideally use the conda all-inclusive binary to run the tests since that's how the tutorial is meant to be ran.

Alternatively I can set something up with combined but it's less ideal

2025-05-22 13:59 UTC, GiudGiud commented
step12 results are funky because of gravity. I think it's fixable, I ll push another commit.

2025-05-23 10:35 UTC, GiudGiud commented
Testing works :)

2025-06-03 23:32 UTC, licharlot reviewed
Very nice tutorial. Some of the theoretical sections might be a bit too much for a user, but it is good to have. 
I'd suggest adding a section on the input file syntax (commenting lines, unit conversion, global parameters, etc)

2025-06-03 23:32 UTC, licharlot commented on tutorials/shield_multiphysics/doc/content/user_workshop/index.md
> +!include user_workshop/systems_user/mesh.md
Move this before the geometry definition in step 1

2025-06-03 23:32 UTC, licharlot commented on tutorials/shield_multiphysics/doc/content/user_workshop/index.md
> +!include user_workshop/systems_user/functions.md
Suggest splitting functons and materials into 2 steps.

2025-06-03 23:32 UTC, licharlot commented on tutorials/shield_multiphysics/doc/content/user_workshop/systems_user/functions.md
> +## Using a Function in our model
This part could be a step of its own in the tutorial. It would improve the flow of the tutorial as it might be confusing to have this section in the `Materials` section.

2025-06-03 23:32 UTC, licharlot commented on tutorials/shield_multiphysics/doc/content/user_workshop/problem/step05.md
> +!listing step05_auxiliary_variables/step5.i block=AuxVariables
This is confusing. From the sentence, one would expect that the water temperature will be represented as an aux variable, but heat flux components are defined in the input file.

2025-06-03 23:32 UTC, licharlot commented on tutorials/shield_multiphysics/doc/content/user_workshop/problem/step05.md
> +The primary unknown ("nonlinear variable") is the temperature
```suggestion
The primary unknown ("nonlinear variable") is the temperature.
```

2025-06-03 23:32 UTC, licharlot commented on tutorials/shield_multiphysics/doc/content/user_workshop/systems_user/timesteppers.md
> +A system for suggesting time steps for transient executioners.
I think you are using "suggesting" because the time step will be cut if it fails, but it might not be clear at this point in the presentation.

2025-06-03 23:32 UTC, licharlot commented on tutorials/shield_multiphysics/doc/content/user_workshop/problem/step04.md
> +conductivity. Instead, the [HeatConduction](HeatConduction.md) Kernel utilizes the material
`ADHeatConduction` is used in the input file. Will have to be clarified while presenting are adding an explanation here for switching to AD as this is also changing the BC objects

2025-06-03 23:32 UTC, licharlot commented on tutorials/shield_multiphysics/inputs/step07_mechanics/step7.i
> +  # NOTE: This handles thermal expansion by coupling to the displacements
Note at the wrong place

2025-06-03 23:32 UTC, licharlot commented on tutorials/shield_multiphysics/doc/content/user_workshop/problem/step10.md
> += \nabla \cdot \left(\mu_\text{eff} \left(\nabla\vec{u}_I + \left(\nabla \vec{u}_I\right)^T-\frac{2}{3}\nabla\cdot\vec{u}_I\mathbb{I}\right)\right) -\nabla p + \rho \vec{g}
Why both \vec{u} and \vec{u}_I for the velocity?

2025-06-03 23:32 UTC, licharlot commented on tutorials/shield_multiphysics/doc/content/user_workshop/problem/step10.md
> +moose-opt -i step10.i
```suggestion
moose-opt -i mesh2d.i --mesh-only
moose-opt -i step10.i
```

2025-06-03 23:32 UTC, licharlot commented on tutorials/shield_multiphysics/inputs/step11_multiapps/step11_2d_heat_conduction.i
> +    # order = CONSTANT
Are these commented lines kept on purpose?

2025-06-03 23:32 UTC, licharlot commented on tutorials/shield_multiphysics/inputs/step10_finite_volume/tests
> +    requirement = "The shield multiphysics tutorial shall demonstrate a fluids simulation with finite volume."
```suggestion
    requirement = "The shield multiphysics tutorial shall demonstrate a fluid flow simulation with finite volume."
```

2025-06-03 23:32 UTC, licharlot commented on tutorials/shield_multiphysics/inputs/step11_multiapps/tests
> +                  "fluid simulation meant for coupling individually."
```suggestion
                  "fluid flow simulation meant for coupling individually."
```

2025-06-03 23:32 UTC, licharlot commented on tutorials/shield_multiphysics/doc/content/user_workshop/index.md
> +!include user_workshop/problem/step12.md start=end-intro
This step is mixing the custom syntax and multi-system. Could be split into 2 steps.

2025-06-03 23:32 UTC, licharlot commented on tutorials/shield_multiphysics/doc/content/user_workshop/problem/step01.md
> +where $T = 300$ on the back ($z=0$), $T = 330$ on the front ($z=5.25$) and with
The name of the front and back sidesets is not intuitive since that are on top and bottom

2025-06-03 23:32 UTC, licharlot commented on tutorials/shield_multiphysics/doc/content/user_workshop/problem/step01.md
> +
Not sure the weak form is necessary here. Would be more meaningful after the fem intro

2025-06-03 23:32 UTC, licharlot commented on tutorials/shield_multiphysics/doc/content/user_workshop/problem/step01.md
> +moose-opt -i mesh.i --mesh-only
Put this execution step after the geometry definition?

2025-06-03 23:32 UTC, licharlot commented on tutorials/shield_multiphysics/doc/content/user_workshop/problem/step01.md
> +
Would be nice to have a description of the info in the console output (number of DoF, etc.)

2025-06-03 23:32 UTC, licharlot commented on tutorials/shield_multiphysics/doc/content/user_workshop/problem/step02.md
> +
In the presentation, there is a lot of content between these 2 slides. Could be nice to have a reminder. Also suggest summarizing the values of the diffusion coefficient on each block, maybe with a picture?

2025-06-03 23:32 UTC, licharlot commented on tutorials/shield_multiphysics/doc/content/user_workshop/problem/step02.md
> +!media shield_multiphysics/results/step02.png
the T fluid and T Solid labels are confusing since there is only one variable in the input file.

2025-06-03 23:32 UTC, licharlot commented on tutorials/shield_multiphysics/doc/content/user_workshop/problem/step03.md
> +
Would be nice to add a figure illustrating the BCs

2025-06-03 23:32 UTC, licharlot commented on tutorials/shield_multiphysics/doc/content/user_workshop/problem/step03.md
> +!media shield_multiphysics/results/step03_mesh.png style=width:100%;margin-left:auto;margin-right:auto;display:block
Make sure to explain `water_boundary` vs `water_boundary_inward`

2025-06-03 23:32 UTC, licharlot commented on tutorials/shield_multiphysics/doc/content/user_workshop/problem/step03.md
> +We use the same boundary condition as for with for now. When we introduce a separate variable for the
Please correct  this sentence.

2025-06-03 23:32 UTC, licharlot commented on tutorials/shield_multiphysics/doc/content/user_workshop/problem/step03.md
> +!media shield_multiphysics/results/step03.png
Need to explain that we don't solve on the water block.

2025-06-03 23:32 UTC, licharlot commented on tutorials/shield_multiphysics/doc/content/user_workshop/problem/step03.md
> +
Need to explain why some temperatures are below 300K

2025-06-04 22:23 UTC, GiudGiud commented on tutorials/shield_multiphysics/doc/content/user_workshop/index.md
> +!include user_workshop/systems_user/functions.md
moved functions with BCs. The functions description uses BCs

2025-06-04 22:25 UTC, GiudGiud commented on tutorials/shield_multiphysics/doc/content/user_workshop/systems_user/functions.md
> +## Using a Function in our model
moved with BCs. We can explain Functions after having done demos with BCs, just subtituting constants for functions

2025-06-04 22:28 UTC, GiudGiud commented on tutorials/shield_multiphysics/doc/content/user_workshop/problem/step05.md
> +!listing step05_auxiliary_variables/step5.i block=AuxVariables
It got deleted from the input smh. i re-added it. It is supposed to be an auxvariable

2025-06-04 22:28 UTC, GiudGiud commented on tutorials/shield_multiphysics/doc/content/user_workshop/systems_user/timesteppers.md
> +A system for suggesting time steps for transient executioners.
switched to computing

2025-06-04 22:42 UTC, GiudGiud commented on tutorials/shield_multiphysics/doc/content/user_workshop/problem/step04.md
> +conductivity. Instead, the [HeatConduction](HeatConduction.md) Kernel utilizes the material
I ll add a brief note. We explain AD in the fem section so this should be fine to explain

2025-06-04 23:33 UTC, GiudGiud commented on tutorials/shield_multiphysics/inputs/step07_mechanics/step7.i
> +  # NOTE: This handles thermal expansion by coupling to the displacements
unforturnately not. The thermal expansion is really handled by the density material property. There is no kernel for it

2025-06-04 23:34 UTC, GiudGiud commented on tutorials/shield_multiphysics/doc/content/user_workshop/problem/step10.md
> += \nabla \cdot \left(\mu_\text{eff} \left(\nabla\vec{u}_I + \left(\nabla \vec{u}_I\right)^T-\frac{2}{3}\nabla\cdot\vec{u}_I\mathbb{I}\right)\right) -\nabla p + \rho \vec{g}
copy-paste error. deleting _I for intersititial

2025-06-04 23:40 UTC, GiudGiud commented on tutorials/shield_multiphysics/inputs/step11_multiapps/step11_2d_heat_conduction.i
> +    # order = CONSTANT
deleted

2025-06-04 23:45 UTC, GiudGiud commented on tutorials/shield_multiphysics/doc/content/user_workshop/problem/step03.md
> +
I have no such temperatures running this locally. I think it's just the paraview colorbar

2025-06-05 00:15 UTC, GiudGiud commented on tutorials/shield_multiphysics/doc/content/user_workshop/problem/step03.md
> +
done

2025-06-05 00:17 UTC, GiudGiud commented on tutorials/shield_multiphysics/doc/content/user_workshop/problem/step03.md
> +!media shield_multiphysics/results/step03.png
done

2025-06-05 00:18 UTC, GiudGiud commented on tutorials/shield_multiphysics/doc/content/user_workshop/problem/step03.md
> +We use the same boundary condition as for with for now. When we introduce a separate variable for the
fixed

2025-06-05 02:45 UTC, GiudGiud commented on tutorials/shield_multiphysics/doc/content/user_workshop/problem/step01.md
> +where $T = 300$ on the back ($z=0$), $T = 330$ on the front ($z=5.25$) and with
ugh I never noticed this. Fixed now

2025-06-05 03:57 UTC, GiudGiud commented on tutorials/shield_multiphysics/doc/content/user_workshop/problem/step01.md
> +
you're right. deleting

2025-06-05 04:12 UTC, GiudGiud commented on tutorials/shield_multiphysics/doc/content/user_workshop/problem/step02.md
> +!media shield_multiphysics/results/step02.png
This has to be the wrong picture

2025-06-05 04:23 UTC, GiudGiud commented on tutorials/shield_multiphysics/doc/content/user_workshop/problem/step02.md
> +!media shield_multiphysics/results/step02.png
Deleted one colorbar so only one shows

2025-06-05 04:24 UTC, GiudGiud commented on tutorials/shield_multiphysics/doc/content/user_workshop/problem/step01.md
> +
adding output

2025-06-05 04:28 UTC, GiudGiud commented on tutorials/shield_multiphysics/doc/content/user_workshop/problem/step02.md
> +
Ok added a reminder.

2025-06-05 04:47 UTC, GiudGiud commented
All comments should be addressed, I just need to check that the slides still build as expected

2025-06-05 04:53 UTC, moosebuild commented on large_media
> +Subproject commit 86e24765716fc8d8bf77318877af58166d8258b2
**Caution!** This contains a submodule update

2025-06-05 14:21 UTC, moosebuild commented on large_media
> +Subproject commit 86e24765716fc8d8bf77318877af58166d8258b2
**Caution!** This contains a submodule update

2025-06-05 14:32 UTC, moosebuild commented on large_media
> +Subproject commit 86e24765716fc8d8bf77318877af58166d8258b2
**Caution!** This contains a submodule update

2025-06-05 15:14 UTC, moosebuild commented on large_media
> +Subproject commit 86e24765716fc8d8bf77318877af58166d8258b2
**Caution!** This contains a submodule update

2025-06-05 15:38 UTC, moosebuild commented on large_media
> +Subproject commit 86e24765716fc8d8bf77318877af58166d8258b2
**Caution!** This contains a submodule update

2025-06-05 23:24 UTC, moosebuild commented on large_media
> +Subproject commit 86e24765716fc8d8bf77318877af58166d8258b2
**Caution!** This contains a submodule update

2025-06-05 23:33 UTC, GiudGiud commented
Looks fine. Tests are fixed now

2025-06-06 05:20 UTC, GiudGiud commented
Test failure unrelated

2025-06-06 20:42 UTC, licharlot reviewed
I think it flows much better now! Just a few comestic details to fix

2025-06-06 20:42 UTC, licharlot commented on tutorials/shield_multiphysics/doc/content/user_workshop/problem/step02.md
> +!media shield_multiphysics/results/step02.png
For some reason, the water still has a different colorbar, even if it is not shown.

2025-06-06 20:42 UTC, licharlot commented on tutorials/shield_multiphysics/doc/content/user_workshop/problem/step10.md
> +!media step10_mesh.png
This picture is too big

2025-06-06 20:42 UTC, licharlot commented on tutorials/shield_multiphysics/doc/config.yml
> +        background_size: auto 4%
Not sure this is due to this line, but the INL footer is too small and barely visible on the slides

2025-06-06 20:48 UTC, GiudGiud commented on tutorials/shield_multiphysics/doc/content/user_workshop/problem/step02.md
> +!media shield_multiphysics/results/step02.png
@zachmprince could you please re-generate the picture? The current one does not match any step I think

2025-06-06 20:52 UTC, GiudGiud commented on tutorials/shield_multiphysics/doc/config.yml
> +        background_size: auto 4%
Swtiched to new background

2025-06-06 20:52 UTC, GiudGiud commented on tutorials/shield_multiphysics/doc/content/user_workshop/problem/step02.md
> +!media shield_multiphysics/results/step02.png
We can fix this in large_media btw, we dont need to change anything in this PR to fix the image

2025-06-06 21:07 UTC, moosebuild commented on large_media
> +Subproject commit 86e24765716fc8d8bf77318877af58166d8258b2
**Caution!** This contains a submodule update

2025-06-06 21:54 UTC, moosebuild commented on large_media
> +Subproject commit 9332e29706d1a0413b307d0d746096f6e790615a
**Caution!** This contains a submodule update

2025-06-07 06:43 UTC, moosebuild commented on large_media
> +Subproject commit 9332e29706d1a0413b307d0d746096f6e790615a
**Caution!** This contains a submodule update

2025-06-07 14:26 UTC, GiudGiud commented on tutorials/shield_multiphysics/doc/content/user_workshop/problem/step10.md
> +!media step10_mesh.png
fixed
https://mooseframework.inl.gov/docs/PRs/27572/site/user_workshop/index.html#/48/3

2025-06-09 13:21 UTC, licharlot approved these changes

2025-06-09 13:49 UTC, GiudGiud commented
Thanks for the review @licharlot !
@loganharbour if you want to take another look

2025-06-09 13:57 UTC, loganharbour commented
> Thanks for the review @licharlot ! @loganharbour if you want to take another look

Looking now

2025-06-12 21:46 UTC, GiudGiud commented on tutorials/shield_multiphysics/doc/content/user_workshop/index.md
> +!include user_workshop/problem/step12.md start=end-intro
This is how I intend Physics to be used and the case is not big enough to show that fully coupled is bad

2025-06-26 11:56 UTC, moosebuild commented on large_media
> +Subproject commit 9332e29706d1a0413b307d0d746096f6e790615a
**Caution!** This contains a submodule update

2025-06-28 07:34 UTC, moosebuild commented
Job [Coverage](https://civet.inl.gov/job/2929477/), step Verify coverage on e16cb7d wanted to post the following:


The following coverage requirement(s) failed:
- Failed to generate `chemical_reactions` coverage rate (required: 92.0%)
- Failed to generate `contact` coverage rate (required: 87.0%)
- Failed to generate `electromagnetics` coverage rate (required: 94.0%)
- Failed to generate `external_petsc_solver` coverage rate (required: 84.0%)
- Failed to generate `fluid_properties` coverage rate (required: 84.0%)
- Failed to generate `fsi` coverage rate (required: 85.0%)
- Failed to generate `functional_expansion_tools` coverage rate (required: 81.0%)
- Failed to generate `geochemistry` coverage rate (required: 96.0%)
- Failed to generate `heat_transfer` coverage rate (required: 87.0%)
- Failed to generate `level_set` coverage rate (required: 85.0%)
- Failed to generate `misc` coverage rate (required: 32.0%)
- Failed to generate `navier_stokes` coverage rate (required: 77.0%)
- Failed to generate `optimization` coverage rate (required: 86.0%)
- Failed to generate `peridynamics` coverage rate (required: 77.0%)
- Failed to generate `phase_field` coverage rate (required: 85.0%)
- Failed to generate `porous_flow` coverage rate (required: 95.0%)
- Failed to generate `ray_tracing` coverage rate (required: 93.0%)
- Failed to generate `rdg` coverage rate (required: 63.0%)
- Failed to generate `reactor` coverage rate (required: 90.0%)
- Failed to generate `scalar_transport` coverage rate (required: 81.0%)
- Failed to generate `solid_mechanics` coverage rate (required: 84.0%)
- Failed to generate `solid_properties` coverage rate (required: 83.0%)
- Failed to generate `stochastic_tools` coverage rate (required: 88.0%)
- Failed to generate `subchannel` coverage rate (required: 87.0%)
- Failed to generate `thermal_hydraulics` coverage rate (required: 88.0%)
- Failed to generate `xfem` coverage rate (required: 80.0%)

2025-06-28 13:52 UTC, GiudGiud commented
libtorch cuda and python 3.9 failures are from recipe changes (no longer exist for 3.9)

2025-06-28 13:52 UTC, merged

2025-06-28 13:54 UTC, GiudGiud commented
Thanks for the major contributions @zachmprince ! and CI support @loganharbour and review @licharlot !