Fix small improvement html.py
idaholab/moose pull request #27592
Opened 2024-05-09 23:08 UTC by aeslaughter

I was borrowing some code for a project of mine, noticed this little guy that doesn't make any difference.

## Reason

Using correct types is better.

## Design

Change from str to bool

## Impact

None

2024-05-09 23:41 UTC, cticenhour requested changes, later dismissed
Hi Andrew! 😄 Thanks for the fix!

Please add #27592 to the commit message and testing can start.

2024-05-10 00:05 UTC, aeslaughter commented
I forgot how onerous it is to change MOOSE.

2024-05-10 03:58 UTC, moosebuild commented
Job [Documentation](https://civet.inl.gov/job/2224469/) on 5d3e57b wanted to post the following:

View the site [here](https://mooseframework.inl.gov/docs/PRs/27592/site)

This comment will be updated on new commits.

2024-05-10 04:53 UTC, moosebuild commented
Job [Coverage](https://civet.inl.gov/job/2224513/) on 5d3e57b wanted to post the following:


## Framework coverage

<table>
  <thead>
    <tr>
      <th></th>
      <th>639315</th>
      <th colspan=4>#27592 5d3e57</th>
    </tr>
    <tr>
      <th></th>
      <th>Total</th>
      <th>Total</th>
      <th>+/-</th>
      <th>New</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><b>Rate</b></td>
      <td>85.08%</td>
      <td>85.08%</td>
      <td>-0.00%</td>
      <td>-</td>
    </tr>
    <tr>
      <td><b>Hits</b></td>
      <td>103065</td>
      <td>103064</td>
      <td>-1</td>
      <td>0</td>
    </tr>
    <tr>
      <td><b>Misses</b></td>
      <td>18069</td>
      <td>18070</td>
      <td>+1</td>
      <td>0</td>
    </tr>
  </tbody>
</table>

[Diff coverage report](https://mooseframework.inl.gov/docs/PRs/27592/coverage_diff/framework)

[Full coverage report](https://mooseframework.inl.gov/docs/PRs/27592/coverage/framework)


## Modules coverage

Coverage did not change

## Full coverage reports

<details>
<summary>Reports</summary>

- [`framework`](https://mooseframework.inl.gov/docs/PRs/27592/coverage/framework)
- [`chemical_reactions`](https://mooseframework.inl.gov/docs/PRs/27592/coverage/chemical_reactions)
- [`combined`](https://mooseframework.inl.gov/docs/PRs/27592/coverage/combined)
- [`contact`](https://mooseframework.inl.gov/docs/PRs/27592/coverage/contact)
- [`electromagnetics`](https://mooseframework.inl.gov/docs/PRs/27592/coverage/electromagnetics)
- [`external_petsc_solver`](https://mooseframework.inl.gov/docs/PRs/27592/coverage/external_petsc_solver)
- [`fluid_properties`](https://mooseframework.inl.gov/docs/PRs/27592/coverage/fluid_properties)
- [`fsi`](https://mooseframework.inl.gov/docs/PRs/27592/coverage/fsi)
- [`functional_expansion_tools`](https://mooseframework.inl.gov/docs/PRs/27592/coverage/functional_expansion_tools)
- [`geochemistry`](https://mooseframework.inl.gov/docs/PRs/27592/coverage/geochemistry)
- [`heat_transfer`](https://mooseframework.inl.gov/docs/PRs/27592/coverage/heat_transfer)
- [`level_set`](https://mooseframework.inl.gov/docs/PRs/27592/coverage/level_set)
- [`misc`](https://mooseframework.inl.gov/docs/PRs/27592/coverage/misc)
- [`navier_stokes`](https://mooseframework.inl.gov/docs/PRs/27592/coverage/navier_stokes)
- [`optimization`](https://mooseframework.inl.gov/docs/PRs/27592/coverage/optimization)
- [`peridynamics`](https://mooseframework.inl.gov/docs/PRs/27592/coverage/peridynamics)
- [`phase_field`](https://mooseframework.inl.gov/docs/PRs/27592/coverage/phase_field)
- [`porous_flow`](https://mooseframework.inl.gov/docs/PRs/27592/coverage/porous_flow)
- [`ray_tracing`](https://mooseframework.inl.gov/docs/PRs/27592/coverage/ray_tracing)
- [`rdg`](https://mooseframework.inl.gov/docs/PRs/27592/coverage/rdg)
- [`reactor`](https://mooseframework.inl.gov/docs/PRs/27592/coverage/reactor)
- [`richards`](https://mooseframework.inl.gov/docs/PRs/27592/coverage/richards)
- [`scalar_transport`](https://mooseframework.inl.gov/docs/PRs/27592/coverage/scalar_transport)
- [`solid_mechanics`](https://mooseframework.inl.gov/docs/PRs/27592/coverage/solid_mechanics)
- [`solid_properties`](https://mooseframework.inl.gov/docs/PRs/27592/coverage/solid_properties)
- [`stochastic_tools`](https://mooseframework.inl.gov/docs/PRs/27592/coverage/stochastic_tools)
- [`thermal_hydraulics`](https://mooseframework.inl.gov/docs/PRs/27592/coverage/thermal_hydraulics)
- [`xfem`](https://mooseframework.inl.gov/docs/PRs/27592/coverage/xfem)

</details>



This comment will be updated on new commits.

2024-05-14 14:22 UTC, GiudGiud approved these changes

2024-05-14 14:22 UTC, merged

2024-05-14 16:42 UTC, cticenhour commented
Thanks @GiudGiud. I forgot to get back to this to merge it.