Skip initialization in eigen problem when restarting
idaholab/moose pull request #27622
Opened 2024-05-15 04:43 UTC by YaqiWang

Closes #27621.

2024-05-15 07:18 UTC, moosebuild commented
Job [Documentation](https://civet.inl.gov/job/2232837/) on e549414 wanted to post the following:

View the site [here](https://mooseframework.inl.gov/docs/PRs/27622/site)

This comment will be updated on new commits.

2024-05-15 13:33 UTC, lindsayad requested changes

2024-05-15 13:33 UTC, lindsayad commented on test/tests/problems/eigen_problem/initial_condition/ne_restart.i
> +  [./u]
update to new syntax without `./` and `../`

2024-05-15 13:33 UTC, lindsayad commented on test/tests/problems/eigen_problem/initial_condition/tests
> +  [./restart]
same. You can do the same for the rest of the file or leave it, let's just make the diff clean at least

2024-05-15 14:20 UTC, YaqiWang commented
Interesting. The failed test here shows a warning message at the end `WARNING! There are options you set that were not used!`.

2024-05-15 17:50 UTC, moosebuild commented
Job [Coverage](https://civet.inl.gov/job/2233599/) on d47c4ef wanted to post the following:


## Framework coverage

<table>
  <thead>
    <tr>
      <th></th>
      <th>dc8a1f</th>
      <th colspan=4>#27622 d47c4e</th>
    </tr>
    <tr>
      <th></th>
      <th>Total</th>
      <th>Total</th>
      <th>+/-</th>
      <th>New</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><b>Rate</b></td>
      <td>85.09%</td>
      <td>85.09%</td>
      <td>+0.00%</td>
      <td>100.00%</td>
    </tr>
    <tr>
      <td><b>Hits</b></td>
      <td>103153</td>
      <td>103155</td>
      <td>+2</td>
      <td>2</td>
    </tr>
    <tr>
      <td><b>Misses</b></td>
      <td>18077</td>
      <td>18075</td>
      <td>-2</td>
      <td>0</td>
    </tr>
  </tbody>
</table>

[Diff coverage report](https://mooseframework.inl.gov/docs/PRs/27622/coverage_diff/framework)

[Full coverage report](https://mooseframework.inl.gov/docs/PRs/27622/coverage/framework)


## Modules coverage

Coverage did not change

## Full coverage reports

<details>
<summary>Reports</summary>

- [`framework`](https://mooseframework.inl.gov/docs/PRs/27622/coverage/framework)
- [`chemical_reactions`](https://mooseframework.inl.gov/docs/PRs/27622/coverage/chemical_reactions)
- [`combined`](https://mooseframework.inl.gov/docs/PRs/27622/coverage/combined)
- [`contact`](https://mooseframework.inl.gov/docs/PRs/27622/coverage/contact)
- [`electromagnetics`](https://mooseframework.inl.gov/docs/PRs/27622/coverage/electromagnetics)
- [`external_petsc_solver`](https://mooseframework.inl.gov/docs/PRs/27622/coverage/external_petsc_solver)
- [`fluid_properties`](https://mooseframework.inl.gov/docs/PRs/27622/coverage/fluid_properties)
- [`fsi`](https://mooseframework.inl.gov/docs/PRs/27622/coverage/fsi)
- [`functional_expansion_tools`](https://mooseframework.inl.gov/docs/PRs/27622/coverage/functional_expansion_tools)
- [`geochemistry`](https://mooseframework.inl.gov/docs/PRs/27622/coverage/geochemistry)
- [`heat_transfer`](https://mooseframework.inl.gov/docs/PRs/27622/coverage/heat_transfer)
- [`level_set`](https://mooseframework.inl.gov/docs/PRs/27622/coverage/level_set)
- [`misc`](https://mooseframework.inl.gov/docs/PRs/27622/coverage/misc)
- [`navier_stokes`](https://mooseframework.inl.gov/docs/PRs/27622/coverage/navier_stokes)
- [`optimization`](https://mooseframework.inl.gov/docs/PRs/27622/coverage/optimization)
- [`peridynamics`](https://mooseframework.inl.gov/docs/PRs/27622/coverage/peridynamics)
- [`phase_field`](https://mooseframework.inl.gov/docs/PRs/27622/coverage/phase_field)
- [`porous_flow`](https://mooseframework.inl.gov/docs/PRs/27622/coverage/porous_flow)
- [`ray_tracing`](https://mooseframework.inl.gov/docs/PRs/27622/coverage/ray_tracing)
- [`rdg`](https://mooseframework.inl.gov/docs/PRs/27622/coverage/rdg)
- [`reactor`](https://mooseframework.inl.gov/docs/PRs/27622/coverage/reactor)
- [`richards`](https://mooseframework.inl.gov/docs/PRs/27622/coverage/richards)
- [`scalar_transport`](https://mooseframework.inl.gov/docs/PRs/27622/coverage/scalar_transport)
- [`solid_mechanics`](https://mooseframework.inl.gov/docs/PRs/27622/coverage/solid_mechanics)
- [`solid_properties`](https://mooseframework.inl.gov/docs/PRs/27622/coverage/solid_properties)
- [`stochastic_tools`](https://mooseframework.inl.gov/docs/PRs/27622/coverage/stochastic_tools)
- [`thermal_hydraulics`](https://mooseframework.inl.gov/docs/PRs/27622/coverage/thermal_hydraulics)
- [`xfem`](https://mooseframework.inl.gov/docs/PRs/27622/coverage/xfem)

</details>



This comment will be updated on new commits.

2024-05-15 17:54 UTC, YaqiWang commented
@lindsayad more comments? The failures do not seem relevant.

2024-05-15 18:08 UTC, lindsayad approved these changes

2024-05-15 18:08 UTC, lindsayad commented
indeed, failures are not related

2024-05-15 18:08 UTC, merged

2024-05-15 18:16 UTC, YaqiWang commented
Thanks @lindsayad!

2024-05-15 22:27 UTC, loganharbour commented
Broke next https://civet.inl.gov/job/2234270/

2024-05-16 16:41 UTC, loganharbour commented
Can someone address this please

2024-05-16 16:53 UTC, YaqiWang commented
That is strange: why p3 and p7 tests pass and p5 does not? I cannot reproduce it on my mac...