Add no-merge capability to mesh combiner generator
idaholab/moose pull request #27647
Opened 2024-05-16 14:26 UTC by GiudGiud

closes #27646

This could be stuff we push upstream to libmesh tbh. It's mostly there for blocks already.

2024-05-16 16:23 UTC, moosebuild commented
Job [Documentation](https://civet.inl.gov/job/2235640/) on 0d8c34a wanted to post the following:

View the site [here](https://mooseframework.inl.gov/docs/PRs/27647/site)

This comment will be updated on new commits.

2024-05-24 14:45 UTC, dschwen commented
So now it does the same thing `MeshCollectionGenerator` does?

>   params.addClassDescription("Collects multiple meshes into a single (unconnected) mesh.");

2024-05-24 14:57 UTC, moosebuild commented
Job [Coverage](https://civet.inl.gov/job/2249389/) on fe8d30d wanted to post the following:


## Framework coverage

<table>
  <thead>
    <tr>
      <th></th>
      <th>ef92d3</th>
      <th colspan=4>#27647 fe8d30</th>
    </tr>
    <tr>
      <th></th>
      <th>Total</th>
      <th>Total</th>
      <th>+/-</th>
      <th>New</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><b>Rate</b></td>
      <td>85.10%</td>
      <td>85.10%</td>
      <td>-0.00%</td>
      <td>79.37%</td>
    </tr>
    <tr>
      <td><b>Hits</b></td>
      <td>103329</td>
      <td>103367</td>
      <td>+38</td>
      <td>50</td>
    </tr>
    <tr>
      <td><b>Misses</b></td>
      <td>18088</td>
      <td>18100</td>
      <td>+12</td>
      <td>13</td>
    </tr>
  </tbody>
</table>

[Diff coverage report](https://mooseframework.inl.gov/docs/PRs/27647/coverage_diff/framework)

[Full coverage report](https://mooseframework.inl.gov/docs/PRs/27647/coverage/framework)


## Modules coverage

Coverage did not change

## Full coverage reports

<details>
<summary>Reports</summary>

- [`framework`](https://mooseframework.inl.gov/docs/PRs/27647/coverage/framework)
- [`chemical_reactions`](https://mooseframework.inl.gov/docs/PRs/27647/coverage/chemical_reactions)
- [`combined`](https://mooseframework.inl.gov/docs/PRs/27647/coverage/combined)
- [`contact`](https://mooseframework.inl.gov/docs/PRs/27647/coverage/contact)
- [`electromagnetics`](https://mooseframework.inl.gov/docs/PRs/27647/coverage/electromagnetics)
- [`external_petsc_solver`](https://mooseframework.inl.gov/docs/PRs/27647/coverage/external_petsc_solver)
- [`fluid_properties`](https://mooseframework.inl.gov/docs/PRs/27647/coverage/fluid_properties)
- [`fsi`](https://mooseframework.inl.gov/docs/PRs/27647/coverage/fsi)
- [`functional_expansion_tools`](https://mooseframework.inl.gov/docs/PRs/27647/coverage/functional_expansion_tools)
- [`geochemistry`](https://mooseframework.inl.gov/docs/PRs/27647/coverage/geochemistry)
- [`heat_transfer`](https://mooseframework.inl.gov/docs/PRs/27647/coverage/heat_transfer)
- [`level_set`](https://mooseframework.inl.gov/docs/PRs/27647/coverage/level_set)
- [`misc`](https://mooseframework.inl.gov/docs/PRs/27647/coverage/misc)
- [`navier_stokes`](https://mooseframework.inl.gov/docs/PRs/27647/coverage/navier_stokes)
- [`optimization`](https://mooseframework.inl.gov/docs/PRs/27647/coverage/optimization)
- [`peridynamics`](https://mooseframework.inl.gov/docs/PRs/27647/coverage/peridynamics)
- [`phase_field`](https://mooseframework.inl.gov/docs/PRs/27647/coverage/phase_field)
- [`porous_flow`](https://mooseframework.inl.gov/docs/PRs/27647/coverage/porous_flow)
- [`ray_tracing`](https://mooseframework.inl.gov/docs/PRs/27647/coverage/ray_tracing)
- [`rdg`](https://mooseframework.inl.gov/docs/PRs/27647/coverage/rdg)
- [`reactor`](https://mooseframework.inl.gov/docs/PRs/27647/coverage/reactor)
- [`richards`](https://mooseframework.inl.gov/docs/PRs/27647/coverage/richards)
- [`scalar_transport`](https://mooseframework.inl.gov/docs/PRs/27647/coverage/scalar_transport)
- [`solid_mechanics`](https://mooseframework.inl.gov/docs/PRs/27647/coverage/solid_mechanics)
- [`solid_properties`](https://mooseframework.inl.gov/docs/PRs/27647/coverage/solid_properties)
- [`stochastic_tools`](https://mooseframework.inl.gov/docs/PRs/27647/coverage/stochastic_tools)
- [`thermal_hydraulics`](https://mooseframework.inl.gov/docs/PRs/27647/coverage/thermal_hydraulics)
- [`xfem`](https://mooseframework.inl.gov/docs/PRs/27647/coverage/xfem)

</details>

## Warnings

- `framework` new line coverage rate 79.37% is less than the suggested 90.0%



This comment will be updated on new commits.

2024-05-24 15:30 UTC, GiudGiud commented
The combiner has never been stitching. So imo the two objects have always been duplicating features, one with the added capability for positions (combiner) and the other one with a check on sideset names/ids

Except now there is code to prevent a merge which the MeshCollectionGenerator does not have. The mesh collection generator will still merge sidesets/blocks with the same ids if they are either unnamed or with the same name.

2024-05-24 19:45 UTC, lindsayad requested changes

2024-05-24 19:45 UTC, lindsayad commented on framework/src/meshgenerators/CombinerGenerator.C
> +                        "in the input will conserve the same sideset ids, the others will have "
```suggestion
                        "in the input will keep the same boundary ids, the others will have "
```

2024-05-26 22:39 UTC, GiudGiud commented on framework/src/meshgenerators/CombinerGenerator.C
> +      for (const auto & [source_id, source_name] : boundary.get_sideset_name_map())
ok adding

2024-05-27 04:50 UTC, GiudGiud commented on framework/src/meshgenerators/CombinerGenerator.C
> +                        "offsets. All sideset names will remain valid");
It does. I was just pointless lowering the footprint of the code by only checking the sidesets

2024-05-28 13:46 UTC, lindsayad approved these changes

2024-05-29 02:06 UTC, merged

2024-05-29 02:06 UTC, GiudGiud commented
Thanks for the review!
This will help interns with mesh generation I m fairly confident