Add symmetry boundary conditions for linear FV.
idaholab/moose pull request #27757
Opened 2024-05-31 00:21 UTC by grmnptr

Closes #27756

2024-05-31 21:26 UTC, moosebuild commented
Job [Documentation](https://civet.inl.gov/job/2257564/) on 467feae wanted to post the following:

View the site [here](https://mooseframework.inl.gov/docs/PRs/27757/site)

This comment will be updated on new commits.

2025-10-30 23:45 UTC, grmnptr commented
Updated the description, should be ready for an initial review! I'll rerun the flow test bed.

2025-10-31 00:52 UTC, moosebuild commented
Job [Test](https://civet.inl.gov/job/3350175/), step Results summary on 65d504b wanted to post the following:

## Framework test summary

Compared against 760e74c in job [civet.inl.gov/job/3344996](https://civet.inl.gov/job/3344996).

### Removed tests



### Added tests

| Test                                                              | Time (s)   |
|-------------------------------------------------------------------|------------|
| `linearfvbcs/scalar_symmetry.diffusion-2d-symmetry-nonorthogonal` | 6.95       |
| `linearfvbcs/scalar_symmetry.advection-2d-symmetry-nonorthogonal` | 6.87       |
| `linearfvbcs/scalar_symmetry.advection-2d-symmetry`               | 6.30       |
| `linearfvkernels/diffusion.mms-diffusion-2d-rz-nonorthogonal`     | 6.16       |
| `linearfvbcs/scalar_symmetry.diffusion-1d-symmetry`               | 5.86       |
| `linearfvbcs/scalar_symmetry.advection-1d-symmetry`               | 5.65       |
| `linearfvbcs/scalar_symmetry.diffusion-2d-symmetry`               | 5.60       |

### Run time changes
## Modules test summary

Compared against 760e74c in job [civet.inl.gov/job/3344996](https://civet.inl.gov/job/3344996).

### Removed tests

| Test                                                                                                          | Time (s)   |
|---------------------------------------------------------------------------------------------------------------|------------|
| `navier_stokes/test:finite_volume/ins/turbulence/channel/linear-segregated.channel_ERCOFTAC_linear`           | 5.10       |
| `navier_stokes/test:finite_volume/ins/turbulence/channel/linear-segregated.channel_ERCOFTAC_linear_scaled_Re` | 4.28       |

### Added tests

| Test                                                                                                   | Time (s)   |
|--------------------------------------------------------------------------------------------------------|------------|
| `navier_stokes/test:finite_volume/ins/turbulence/channel/linear-segregated.channel_ERCOFTAC`           | 3.94       |
| `navier_stokes/test:finite_volume/ins/turbulence/channel/linear-segregated.channel_ERCOFTAC_scaled_Re` | 3.93       |
| `navier_stokes/test:finite_volume/ins/channel-flow/linear-segregated/2d-symmetric.symmetry/cartesian`  | 3.80       |
| `navier_stokes/test:finite_volume/ins/channel-flow/linear-segregated/2d-symmetric.symmetry/rz`         | 3.53       |
| `navier_stokes/test:finite_volume/ins/turbulence/channel/linear-segregated.channel_ERCOFTAC_symmetry`  | 3.03       |
| `navier_stokes/test:finite_volume/ins/mms/linear-segregated/2d-symmetric-vortex.vortex-orthogonal`     | SKIP       |
| `navier_stokes/test:finite_volume/ins/mms/linear-segregated/2d-symmetric-vortex.vortex-nonorthogonal`  | SKIP       |

### Run time changes

2025-10-31 01:51 UTC, moosebuild commented
Job [Documentation](https://civet.inl.gov/job/3375888/), step Docs: sync website on a6bbd6c wanted to post the following:

View the site [here](https://mooseframework.inl.gov/docs/PRs/27757/site)

This comment will be updated on new commits.

2025-11-03 22:48 UTC, moosebuild commented
Job [Coverage](https://civet.inl.gov/job/3375925/), step Generate coverage on a6bbd6c wanted to post the following:


## Framework coverage

<table>
  <thead>
    <tr>
      <th></th>
      <th>7edd10</th>
      <th colspan=4>#27757 a6bbd6</th>
    </tr>
    <tr>
      <th></th>
      <th>Total</th>
      <th>Total</th>
      <th>+/-</th>
      <th>New</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><b>Rate</b></td>
      <td>85.97%</td>
      <td>85.97%</td>
      <td>-0.00%</td>
      <td>100.00%</td>
    </tr>
    <tr>
      <td><b>Hits</b></td>
      <td>124954</td>
      <td>124995</td>
      <td>+41</td>
      <td>63</td>
    </tr>
    <tr>
      <td><b>Misses</b></td>
      <td>20387</td>
      <td>20395</td>
      <td>+8</td>
      <td>0</td>
    </tr>
  </tbody>
</table>

[Diff coverage report](https://mooseframework.inl.gov/docs/PRs/27757/coverage_diff/framework)

[Full coverage report](https://mooseframework.inl.gov/docs/PRs/27757/coverage/framework)


## Modules coverage

### Navier stokes

<table>
  <thead>
    <tr>
      <th></th>
      <th>7edd10</th>
      <th colspan=4>#27757 a6bbd6</th>
    </tr>
    <tr>
      <th></th>
      <th>Total</th>
      <th>Total</th>
      <th>+/-</th>
      <th>New</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><b>Rate</b></td>
      <td>85.54%</td>
      <td>85.54%</td>
      <td>+0.00%</td>
      <td>100.00%</td>
    </tr>
    <tr>
      <td><b>Hits</b></td>
      <td>20323</td>
      <td>20414</td>
      <td>+91</td>
      <td>111</td>
    </tr>
    <tr>
      <td><b>Misses</b></td>
      <td>3436</td>
      <td>3450</td>
      <td>+14</td>
      <td>0</td>
    </tr>
  </tbody>
</table>

[Diff coverage report](https://mooseframework.inl.gov/docs/PRs/27757/coverage_diff/navier_stokes)

[Full coverage report](https://mooseframework.inl.gov/docs/PRs/27757/coverage/navier_stokes)

## Full coverage reports

<details>
<summary>Reports</summary>

- [`framework`](https://mooseframework.inl.gov/docs/PRs/27757/coverage/framework)
- [`chemical_reactions`](https://mooseframework.inl.gov/docs/PRs/27757/coverage/chemical_reactions)
- [`combined`](https://mooseframework.inl.gov/docs/PRs/27757/coverage/combined)
- [`contact`](https://mooseframework.inl.gov/docs/PRs/27757/coverage/contact)
- [`electromagnetics`](https://mooseframework.inl.gov/docs/PRs/27757/coverage/electromagnetics)
- [`external_petsc_solver`](https://mooseframework.inl.gov/docs/PRs/27757/coverage/external_petsc_solver)
- [`fluid_properties`](https://mooseframework.inl.gov/docs/PRs/27757/coverage/fluid_properties)
- [`fsi`](https://mooseframework.inl.gov/docs/PRs/27757/coverage/fsi)
- [`functional_expansion_tools`](https://mooseframework.inl.gov/docs/PRs/27757/coverage/functional_expansion_tools)
- [`geochemistry`](https://mooseframework.inl.gov/docs/PRs/27757/coverage/geochemistry)
- [`heat_transfer`](https://mooseframework.inl.gov/docs/PRs/27757/coverage/heat_transfer)
- [`level_set`](https://mooseframework.inl.gov/docs/PRs/27757/coverage/level_set)
- [`misc`](https://mooseframework.inl.gov/docs/PRs/27757/coverage/misc)
- [`navier_stokes`](https://mooseframework.inl.gov/docs/PRs/27757/coverage/navier_stokes)
- [`optimization`](https://mooseframework.inl.gov/docs/PRs/27757/coverage/optimization)
- [`peridynamics`](https://mooseframework.inl.gov/docs/PRs/27757/coverage/peridynamics)
- [`phase_field`](https://mooseframework.inl.gov/docs/PRs/27757/coverage/phase_field)
- [`porous_flow`](https://mooseframework.inl.gov/docs/PRs/27757/coverage/porous_flow)
- [`ray_tracing`](https://mooseframework.inl.gov/docs/PRs/27757/coverage/ray_tracing)
- [`rdg`](https://mooseframework.inl.gov/docs/PRs/27757/coverage/rdg)
- [`reactor`](https://mooseframework.inl.gov/docs/PRs/27757/coverage/reactor)
- [`richards`](https://mooseframework.inl.gov/docs/PRs/27757/coverage/richards)
- [`scalar_transport`](https://mooseframework.inl.gov/docs/PRs/27757/coverage/scalar_transport)
- [`solid_mechanics`](https://mooseframework.inl.gov/docs/PRs/27757/coverage/solid_mechanics)
- [`solid_properties`](https://mooseframework.inl.gov/docs/PRs/27757/coverage/solid_properties)
- [`stochastic_tools`](https://mooseframework.inl.gov/docs/PRs/27757/coverage/stochastic_tools)
- [`subchannel`](https://mooseframework.inl.gov/docs/PRs/27757/coverage/subchannel)
- [`thermal_hydraulics`](https://mooseframework.inl.gov/docs/PRs/27757/coverage/thermal_hydraulics)
- [`xfem`](https://mooseframework.inl.gov/docs/PRs/27757/coverage/xfem)

</details>



This comment will be updated on new commits.

2025-11-04 15:45 UTC, GiudGiud commented on framework/doc/content/source/linearfvbcs/LinearFVScalarSymmetryBC.md
> +# LinearFVScalarSymmetryBC
so should it be a LinearFVAdvectionDiffusionSymmetryBC then?
seems to be hardcoded for diffusion and advection

2025-11-04 15:45 UTC, GiudGiud commented on framework/doc/content/source/linearfvbcs/LinearFVScalarSymmetryBC.md
> +This object specifies a symmetry boundary condition for a diffusion equation:
```suggestion
This object specifies a symmetry boundary condition for an advection-diffusion equation:
```

2025-11-04 15:45 UTC, GiudGiud commented on framework/doc/content/source/linearfvbcs/LinearFVScalarSymmetryBC.md
> +\vec{n}_b \cdot D_b \nabla u_b~ = 0.0.
add advective too then

2025-11-04 15:45 UTC, GiudGiud commented on framework/doc/content/source/linearfvbcs/LinearFVAdvectionDiffusionScalarSymmetryBC.md
> +  convergence on meshes composed of triangles and tetrahedra.
because?

2025-11-04 15:45 UTC, GiudGiud commented on framework/include/linearfvbcs/LinearFVScalarSymmetryBC.h
> +  /// Overriding all of these
```suggestion
  // Overriding all of these
```
otherwise you override the doxygen

2025-11-04 15:45 UTC, GiudGiud commented on framework/src/linearfvbcs/LinearFVScalarSymmetryBC.C
> +  // that the zer normal gradient is respected (by subtracting the normal component).
```suggestion
  // that the zero-normal gradient is respected (by subtracting the normal component).
```

2025-11-04 15:45 UTC, GiudGiud commented on framework/src/linearfvbcs/LinearFVAdvectionDiffusionScalarSymmetryBC.C
> +    boundary_value += cell_gradient * correction_vector;
not sure I understand this.

I d expect us to remove the cell_gradient normal component instead. 
So 
cell_gradient = cell_gradient - (cell_gradient * normal) * normal);

then use that onto d_cf

2025-11-04 15:45 UTC, GiudGiud commented on framework/src/linearfvbcs/LinearFVAdvectionDiffusionScalarSymmetryBC.C
> +    boundary_value += cell_gradient * correction_vector;
right now if I do (boundary_value - cell_value) * normal = cell_gradient * (d_cf - (d_cf * normal) * normal) * normal = cell_gradient * (d_cf * normal - (d_cf * normal) * normal * normal) = 0

so I guess it works

what I propose:
 (boundary_value - cell_value) * normal = (cell_gradient - (cell_gradient * normal) * d_cf* normal)) * normal = (cell_gradient * normal - (cell_gradient * normal)  * normal * normal) * d_cf = 0 too

so should work too

2025-11-04 15:45 UTC, GiudGiud commented on framework/src/linearfvkernels/LinearFVAnisotropicDiffusion.C
> +  auto boundary_grad = _var.gradSln(*elem_info);
good catch

this might be the problem with k-epsilon

2025-11-04 15:45 UTC, GiudGiud commented on framework/src/loops/ComputeLinearFVGreenGaussGradientVolumeThread.C
> +                                                     elem_info->centroid()(rz_radial_coord);
minus?

2025-11-04 15:45 UTC, GiudGiud commented on modules/navier_stokes/doc/content/source/linearfvbcs/LinearFVVelocitySymmetryBC.md
> +\mathbf{u}_f = \mathbf{u}_P - (\mathbf{u}_P \cdot \mathbf{n}) \mathbf{n},
are you missing a gradient here

2025-11-04 15:45 UTC, GiudGiud commented on modules/navier_stokes/src/linearfvbcs/LinearFVPressureSymmetryBC.C
> +}
why no second order option

2025-11-04 15:45 UTC, GiudGiud commented on test/tests/linearfvbcs/scalar_symmetry/tests
> +    max_threads = 1 # see libmesh issue #3808
method opt on all these?

2025-11-04 15:45 UTC, GiudGiud commented on test/tests/linearfvkernels/diffusion/tests
> +    max_threads = 1 # see libmesh issue #3808
same

2025-11-04 15:45 UTC, GiudGiud commented on modules/navier_stokes/src/linearfvbcs/LinearFVVelocitySymmetryBC.C
> +  auto scaled_normal = _current_face_info->normal();
should we switch the normal sign if we have elem_info = neighborinfo here?

2025-11-04 15:45 UTC, GiudGiud commented on modules/navier_stokes/src/linearfvbcs/LinearFVVelocitySymmetryBC.C
> +  auto scaled_normal = _current_face_info->normal();
like we need the symmetry normal not the face_info normal

2025-11-04 15:45 UTC, GiudGiud commented on modules/navier_stokes/src/linearfvbcs/LinearFVVelocitySymmetryBC.C
> +  auto scaled_normal = _current_face_info->normal();
same question if normal is pointing the other side

2025-11-04 15:45 UTC, GiudGiud commented on modules/navier_stokes/src/linearfvbcs/LinearFVVelocitySymmetryBC.C
> +  auto scaled_normal = _current_face_info->normal();
sign might be canceling out actually. let s leave a comment anyway

2025-11-04 15:45 UTC, GiudGiud commented on modules/navier_stokes/src/linearfvbcs/LinearFVVelocitySymmetryBC.C
> +  // Real boundary_value_rhs = 0.0;
```suggestion
```

2025-11-04 15:45 UTC, GiudGiud commented on modules/navier_stokes/src/linearfvbcs/LinearFVVelocitySymmetryBC.C
> +}
maybe this should be the default implementation of these advection-diffusion BCs:
RHS = value - matrix * value

2025-11-05 18:31 UTC, grmnptr commented on framework/doc/content/source/linearfvbcs/LinearFVScalarSymmetryBC.md
> +# LinearFVScalarSymmetryBC
I will do it for this but I started thinking about adding some sort of checking at system level and removing the naming from all ofthese AdvectionDiffusionBCs. It just looks bad. Nothing prevents the user from adding support for more kernels and we don't have any other kernels at the moment and we are also not planning to add more. So for the content we have these are not necessary. If someone adds an egzotic kernel they can create new functions in these BCs to override. But yeah would be nice if we had an error message somewhere to remind them to do that.

2025-11-05 18:38 UTC, grmnptr commented on framework/doc/content/source/linearfvbcs/LinearFVScalarSymmetryBC.md
> +  convergence on meshes composed of triangles and tetrahedra.
No idea, the Newton-based solver gives 1st order as well. I don't have time to investigate.

2025-11-05 18:43 UTC, GiudGiud commented on framework/doc/content/source/linearfvbcs/LinearFVScalarSymmetryBC.md
> +# LinearFVScalarSymmetryBC
> . It just looks bad.

Does not matter. The user facing interface should be the physics

2025-11-05 18:45 UTC, grmnptr commented on framework/src/linearfvbcs/LinearFVAdvectionDiffusionScalarSymmetryBC.C
> +    boundary_value += cell_gradient * correction_vector;
Yeah what I am doing is that I go to the face along the normal and then use the rest of the cell gradient (zero Hessian approximation) to go towards the face centroid. And in the normal direction there should be no change.

So Something like this: 
face_value = cell_value + cell_gradient*d_cf

But this doesn't respect the boundary condition in itself which is `grad_face * normal = 0`.
So we do a split:

face_value = cell_value + cell_gradient * normal * (dcf * normal) + (dcf - dcf*normal*normal) * cell_gradient.

The first one is zero because of the boundary condition. The second one is the vector going towards the face centroid from the intersection of the face and the normal line.

Yours should work too I think, but this one is consistent with what we have in the Neumann/Robin BCs already.

2025-11-05 19:04 UTC, GiudGiud commented on framework/doc/content/source/linearfvbcs/LinearFVScalarSymmetryBC.md
> +# LinearFVScalarSymmetryBC
> Nothing prevents the user from adding support for more kernels and we don't have any other kernels at the moment and we are also not planning to add more

having APIs that work with some kernels and are wrong with others would be confusing imo
I think the actual way forward is not

> If someone adds an egzotic kernel they can create new functions in these BCs to override

but if someone adds an exotic kernel that is related to advection-diffusion, they inherit the current BCs and add or override the functions they need 
and if unrelated to advection-diffusion, then they likely create a whole new set of BCs

2025-11-05 20:40 UTC, grmnptr commented on framework/src/loops/ComputeLinearFVGreenGaussGradientVolumeThread.C
> +                                                     elem_info->centroid()(rz_radial_coord);
Yes, when we expand the gradient integral with green gauss in cylindrical coordinates we will have the 1/r pop up from the divergence operator. We have to subtact this to get the approximation for d phi / dr. 

This was a bug in the previous implementation where I got the sign wrong. It resulted in nonconverging diffusion cases where we needed the nonorthogonal correction. Now I added proper testing for that too.

2025-11-05 20:41 UTC, grmnptr commented on modules/navier_stokes/doc/content/source/linearfvbcs/LinearFVVelocitySymmetryBC.md
> +\mathbf{u}_f = \mathbf{u}_P - (\mathbf{u}_P \cdot \mathbf{n}) \mathbf{n},
No, this is first order for now. I will add a note to this.

2025-11-05 20:46 UTC, grmnptr commented on modules/navier_stokes/src/linearfvbcs/LinearFVPressureSymmetryBC.C
> +}
Adding a note that it is not available for now.

2025-11-05 20:51 UTC, grmnptr commented on modules/navier_stokes/src/linearfvbcs/LinearFVVelocitySymmetryBC.C
> +  auto scaled_normal = _current_face_info->normal();
We have normal*normal so it doesn't matter. Adding a note here.

2025-11-05 20:56 UTC, grmnptr commented on modules/navier_stokes/src/linearfvbcs/LinearFVVelocitySymmetryBC.C
> +}
In some cases it is extra work and more difficult to follow. I am not the biggest fan of this, but in this case it works. I was taking this from a book. This comment reminded me that I should have cited it.

2025-11-06 00:24 UTC, lindsayad commented on framework/doc/content/source/linearfvbcs/LinearFVAdvectionDiffusionScalarSymmetryBC.md
> +\end{equation}
For the symmetry condition, shouldn't $u_b = u_C$ ? Why offer the two term expansion option?

2025-11-06 02:17 UTC, grmnptr commented on framework/doc/content/source/linearfvbcs/LinearFVAdvectionDiffusionScalarSymmetryBC.md
> +\end{equation}
For nonorthogonal meshes the symmetry condition only says that the normal gradient vanishes. At the same time, for cell gradient computation and advection face terms we need the value at the face center. We can only say that the normal component of the gradient is zero which more or less means that u is uC on the face where line orthogonal to the face starting from the cell center intersects the face. From there we can have a gradient that is pointing somewhere on the 2D face without a normal component. We can use this gradient to go from the intersection point to the actual face center. u_b = u_c is first order. To be honest, for triangles we have first order anyways for some reason (it is the same for Newton FV as well), the error factor is just lower with this.

2025-11-10 03:05 UTC, GiudGiud reviewed
looks good to me, can approve after this

2025-11-10 03:05 UTC, GiudGiud commented on framework/src/linearfvbcs/LinearFVAdvectionDiffusionScalarSymmetryBC.C
> +  // side.
how are you making these decisions btw?
ease of implementation or following OF or ?

2025-11-10 03:05 UTC, GiudGiud commented on modules/navier_stokes/doc/content/source/linearfvbcs/LinearFVVelocitySymmetryBC.md
> +
```suggestion

!alert note
The current approximation of the face value assumes that the face centroid is
close to the point where the line from the cell center in the normal direction
intersects the face. This means that on unstructured meshes, this results
a spatially first-order discretization.

This boundary condition is typically paired with the momentum flux kernel
[LinearWCNSFVMomentumFlux.md] and [LinearFVPressureSymmetryBC.md] on symmetry planes of channel flows, as demonstrated in:

!listing /modules/navier_stokes/test/tests/finite_volume/ins/channel-flow/linear-segregated/2d-symmetric/channel.i block=LinearFVBCs/symmetry-u

```

2025-11-10 03:05 UTC, GiudGiud commented on modules/navier_stokes/include/linearfvbcs/LinearFVVelocitySymmetryBC.h
> +  /// Overriding all of these
```suggestion
  // Overriding all of these
```

2025-11-10 03:05 UTC, GiudGiud commented on modules/navier_stokes/src/linearfvbcs/LinearFVVelocitySymmetryBC.C
> +  params.addClassDescription("Adds a symmetry boundary condition for the velocity.");
```suggestion
  params.addClassDescription("Adds a symmetry boundary condition for a component of the velocity.");
```

2025-11-10 03:05 UTC, GiudGiud commented on modules/navier_stokes/src/linearfvbcs/LinearFVVelocitySymmetryBC.C
> +  // We don't have to flip the sign of the normal because we are subtacting normal*normal.
```suggestion
  // We don't have to flip the sign of the normal because we are subtracting normal*normal.
```

2025-11-10 03:05 UTC, GiudGiud commented on modules/navier_stokes/include/linearfvbcs/LinearFVVelocitySymmetryBC.h
> +  /// in the stress term
```suggestion
  /// Index x|y|z, for the symmetric velocity computation
```

2025-11-10 03:05 UTC, GiudGiud commented on modules/navier_stokes/include/userobjects/RhieChowMassFlux.h
> +
```suggestion
```

2025-11-10 03:05 UTC, GiudGiud commented on modules/navier_stokes/include/userobjects/RhieChowMassFlux.h
> +
I dont see it used

2025-11-10 18:49 UTC, grmnptr commented on framework/src/linearfvbcs/LinearFVAdvectionDiffusionScalarSymmetryBC.C
> +  // side.
This one is easy. We don't treat gradient-related terms implicitly at all, we don't have the machinery for that. So everything that uses a gradient will be explicit. Also, OF doesn't have two-term extrapolation for 99% of the content. Especially not in these cases.

2025-11-10 18:50 UTC, grmnptr commented on modules/navier_stokes/include/userobjects/RhieChowMassFlux.h
> +
Oh wow completely forgot about this guy

2025-11-10 18:50 UTC, grmnptr commented on modules/navier_stokes/include/userobjects/RhieChowMassFlux.h
> +
Nice catch!

2025-11-10 19:03 UTC, GiudGiud commented on modules/navier_stokes/src/linearfvbcs/LinearFVPressureFluxBC.C
> +         std::max(_Ainv(face_arg, determineState())(0), 1e-8);
can you check the BoundaryRHSGradient contribution please?
We might be missing Ainv?

2025-11-10 19:50 UTC, grmnptr commented on modules/navier_stokes/src/linearfvbcs/LinearFVPressureFluxBC.C
> +         std::max(_Ainv(face_arg, determineState())(0), 1e-8);
It is good, because it provides the 
1/A * grad(p)*n flux with this. This guys is overridden:

```
virtual bool includesMaterialPropertyMultiplier() const override { return true; }
```

The reason this is divided by 1/A is because this guy returns `grad(p) * n`

2025-11-10 20:28 UTC, GiudGiud approved these changes

2025-11-11 19:50 UTC, moosebuild commented
Job [Test](https://civet.inl.gov/job/3375955/), step Results summary on a6bbd6c wanted to post the following:

## Framework test summary

Compared against 7edd10c in job [civet.inl.gov/job/3374418](https://civet.inl.gov/job/3374418).

### Added tests

| Test                                                              | Time (s)   |
|-------------------------------------------------------------------|------------|
| `linearfvbcs/scalar_symmetry.diffusion-2d-symmetry-nonorthogonal` | 7.32       |
| `linearfvbcs/scalar_symmetry.advection-2d-symmetry-nonorthogonal` | 6.98       |
| `linearfvkernels/diffusion.mms-diffusion-2d-rz-nonorthogonal`     | 6.38       |
| `linearfvbcs/scalar_symmetry.advection-2d-symmetry`               | 5.59       |
| `linearfvbcs/scalar_symmetry.diffusion-2d-symmetry`               | 5.38       |
| `linearfvbcs/scalar_symmetry.advection-1d-symmetry`               | 5.30       |
| `linearfvbcs/scalar_symmetry.diffusion-1d-symmetry`               | 5.18       |
## Modules test summary

Compared against 7edd10c in job [civet.inl.gov/job/3374418](https://civet.inl.gov/job/3374418).

### Removed tests

| Test                                                                                                          | Time (s)   |
|---------------------------------------------------------------------------------------------------------------|------------|
| `navier_stokes/test:finite_volume/ins/turbulence/channel/linear-segregated.channel_ERCOFTAC_linear`           | 4.05       |
| `navier_stokes/test:finite_volume/ins/turbulence/channel/linear-segregated.channel_ERCOFTAC_linear_scaled_Re` | 4.04       |

### Added tests

| Test                                                                                                   | Time (s)   |
|--------------------------------------------------------------------------------------------------------|------------|
| `navier_stokes/test:finite_volume/ins/turbulence/channel/linear-segregated.channel_ERCOFTAC`           | 4.02       |
| `navier_stokes/test:finite_volume/ins/channel-flow/linear-segregated/2d-symmetric.symmetry/cartesian`  | 3.88       |
| `navier_stokes/test:finite_volume/ins/turbulence/channel/linear-segregated.channel_ERCOFTAC_scaled_Re` | 3.54       |
| `navier_stokes/test:finite_volume/ins/channel-flow/linear-segregated/2d-symmetric.symmetry/rz`         | 3.30       |
| `navier_stokes/test:finite_volume/ins/turbulence/channel/linear-segregated.channel_ERCOFTAC_symmetry`  | 3.24       |
| `navier_stokes/test:finite_volume/ins/mms/linear-segregated/2d-symmetric-vortex.vortex-nonorthogonal`  | SKIP       |
| `navier_stokes/test:finite_volume/ins/mms/linear-segregated/2d-symmetric-vortex.vortex-orthogonal`     | SKIP       |

2025-11-12 01:18 UTC, moosebuild commented
Job [Conda mac](https://civet.inl.gov/job/3375920/) on a6bbd6c : invalidated by @grmnptr

2025-11-12 01:18 UTC, moosebuild commented
Job [Conda moose-dev intel mac](https://civet.inl.gov/job/3375913/) on a6bbd6c : invalidated by @grmnptr

2025-11-12 01:18 UTC, moosebuild commented
Job [Conda moose-dev mac](https://civet.inl.gov/job/3375915/) on a6bbd6c : invalidated by @grmnptr

2025-11-12 16:21 UTC, freiler commented
Tests have been done for quads/hexes and triangles including:
-MMS for regular scalar symmetry and Navier Stokes
-Channels and pipes give the analytical solution of a fully developed flow.
-Turbulent channels yield the same velocity profile for a half channel with symmetry condition and a full channel.

2025-11-12 17:08 UTC, grmnptr commented
Failing tests are unrelated.

2025-11-12 17:08 UTC, grmnptr commented
Thanks everyone for the review!

2025-11-12 17:08 UTC, merged

2025-11-12 17:46 UTC, lindsayad commented
this is indirect work?

2025-11-12 17:54 UTC, GiudGiud commented
There's a ticket of someone trying to do RZ symmetry linear FV. 
@grmnptr please reach back there to let them know it’s merged

2025-11-13 04:25 UTC, GiudGiud requested changes
nvmd

2025-11-13 04:25 UTC, GiudGiud commented on modules/navier_stokes/doc/content/source/linearfvbcs/LinearFVVelocitySymmetryBC.md
> +intersects the face. This means that on unstructured meshes, this results
```suggestion
intersects the face. This means that on unstructured meshes, this results in
```

2025-11-13 04:25 UTC, GiudGiud commented on modules/navier_stokes/include/linearfvbcs/LinearFVVelocitySymmetryBC.h
> +  /// Overriding all of these
```suggestion
  // Overriding all of these
```

2025-11-13 04:25 UTC, GiudGiud commented on modules/navier_stokes/include/linearfvbcs/LinearFVVelocitySymmetryBC.h
> +  /// in the stress term
```suggestion
  /// Index x|y|z
```