Fixed assignment of u_old_old_old in ExplicitDynamicsContactConstraint
idaholab/moose pull request #27886
Opened 2024-06-12 20:23 UTC by TheGreatCid

Closes #27883 

`u_old_old_old` was not being properly defined in `ExplicitDynamicsContactConstraint.h` causing certain cases of contact to fail. Past regression tests did not catch this issue as explained in #27883.

- Changed `u_old_old_old` to be initialized by `ExplicitDynamicsContactContraint`.

2024-06-12 20:47 UTC, lindsayad commented
Can we change to refs #27883 instead of closes? I would really like to avoid use of this thrice older state if possible, e.g. I liked your proposed changes in https://github.com/idaholab/moose/issues/27883#issuecomment-2163769702

2024-06-12 20:49 UTC, lindsayad requested changes
It would be good to add a regression test to make sure that regressions introduced by changes like those I introduced in https://github.com/idaholab/moose/pull/27231 don't go unnoticed again in the future

2024-06-12 20:49 UTC, lindsayad commented on modules/contact/src/constraints/ExplicitDynamicsContactConstraint.C
> +  //  auto & u_old_old_old = _sys.solutionState(3);
```suggestion
```

2024-06-12 20:50 UTC, lindsayad commented
> It would be good to add a regression test to make sure that regressions introduced by changes like those I introduced in #27231 don't go unnoticed again in the future

Although then again there *were* diffs on my PR in #27231 🤔 Consequently I expect this PR will also introduce diffs as well

2024-06-12 20:54 UTC, TheGreatCid commented
A regression test would be good. I was only able to get the simulation to fail when the impact speed was sufficiently large, which I achieved by dropping the block from higher up. This takes around 2000 time steps, which is not great for a regression test.... I'm not sure how to go around this as to my knowledge there is no way to initialize velocity with explicit dynamics.

2024-06-12 20:54 UTC, TheGreatCid commented on modules/contact/src/constraints/ExplicitDynamicsContactConstraint.C
> +  //  auto & u_old_old_old = _sys.solutionState(3);
Fixed

2024-06-12 21:21 UTC, lindsayad commented
Indeed that goes to the meeting we had with @ddm42. Could you push on the block with a force larger than gravity to accelerate it quicker? (I'm assuming that gravity is the relevant force here since you said "dropping the block from higher")

2024-06-12 22:14 UTC, TheGreatCid commented
> Indeed that goes to the meeting we had with @ddm42. Could you push on the block with a force larger than gravity to accelerate it quicker? (I'm assuming that gravity is the relevant force here since you said "dropping the block from higher")

That's a good point. I added a regression test using that logic. However, as expected the other explicit contact regression tests fail due to the changes in this PR. 

The question is, should I regold these tests or should I look into incorporating the changes suggested in #27883 first?

2024-06-12 23:11 UTC, lindsayad commented
I leave that decision to you. I am not a subject matter expert in explicit dynamics. I believe you know better what a gold file should look like for this work

2024-06-13 01:36 UTC, moosebuild commented
Job [Documentation](https://civet.inl.gov/job/2274066/) on cf8be5d wanted to post the following:

View the site [here](https://mooseframework.inl.gov/docs/PRs/27886/site)

This comment will be updated on new commits.

2024-06-13 21:22 UTC, TheGreatCid commented
@lindsayad 
I went ahead and implemented the first order calculation of the contact displacements I suggested in #27883. It is a bit more reliable than the previous implementation. However, this is a stop gap solution as the full implementation of explicit contact still has many issues.

2024-06-13 21:44 UTC, lindsayad commented
sounds good

2024-06-17 17:30 UTC, lindsayad commented
@TheGreatCid can you re-push? I think the hook didn't get delivered to civet

2024-06-17 20:14 UTC, TheGreatCid commented
@lindsayad Done.

2024-06-17 22:11 UTC, TheGreatCid commented
It appears that the "Conda build (linux)" is failing. I'm unsure how to correct that.

2024-06-17 23:05 UTC, moosebuild commented
Job [Conda build (Linux)](https://civet.inl.gov/job/2280488/) on 08135b1 : invalidated by @lindsayad

2024-06-18 02:01 UTC, moosebuild commented
Job [Coverage](https://civet.inl.gov/job/2280523/) on 08135b1 wanted to post the following:


## Framework coverage

Coverage did not change


## Modules coverage

### Contact

<table>
  <thead>
    <tr>
      <th></th>
      <th>4db7fd</th>
      <th colspan=4>#27886 08135b</th>
    </tr>
    <tr>
      <th></th>
      <th>Total</th>
      <th>Total</th>
      <th>+/-</th>
      <th>New</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><b>Rate</b></td>
      <td>90.45%</td>
      <td>90.45%</td>
      <td>-</td>
      <td>100.00%</td>
    </tr>
    <tr>
      <td><b>Hits</b></td>
      <td>4936</td>
      <td>4936</td>
      <td>-</td>
      <td>7</td>
    </tr>
    <tr>
      <td><b>Misses</b></td>
      <td>521</td>
      <td>521</td>
      <td>-</td>
      <td>0</td>
    </tr>
  </tbody>
</table>

[Diff coverage report](https://mooseframework.inl.gov/docs/PRs/27886/coverage_diff/contact)

[Full coverage report](https://mooseframework.inl.gov/docs/PRs/27886/coverage/contact)

## Full coverage reports

<details>
<summary>Reports</summary>

- [`framework`](https://mooseframework.inl.gov/docs/PRs/27886/coverage/framework)
- [`chemical_reactions`](https://mooseframework.inl.gov/docs/PRs/27886/coverage/chemical_reactions)
- [`combined`](https://mooseframework.inl.gov/docs/PRs/27886/coverage/combined)
- [`contact`](https://mooseframework.inl.gov/docs/PRs/27886/coverage/contact)
- [`electromagnetics`](https://mooseframework.inl.gov/docs/PRs/27886/coverage/electromagnetics)
- [`external_petsc_solver`](https://mooseframework.inl.gov/docs/PRs/27886/coverage/external_petsc_solver)
- [`fluid_properties`](https://mooseframework.inl.gov/docs/PRs/27886/coverage/fluid_properties)
- [`fsi`](https://mooseframework.inl.gov/docs/PRs/27886/coverage/fsi)
- [`functional_expansion_tools`](https://mooseframework.inl.gov/docs/PRs/27886/coverage/functional_expansion_tools)
- [`geochemistry`](https://mooseframework.inl.gov/docs/PRs/27886/coverage/geochemistry)
- [`heat_transfer`](https://mooseframework.inl.gov/docs/PRs/27886/coverage/heat_transfer)
- [`level_set`](https://mooseframework.inl.gov/docs/PRs/27886/coverage/level_set)
- [`misc`](https://mooseframework.inl.gov/docs/PRs/27886/coverage/misc)
- [`navier_stokes`](https://mooseframework.inl.gov/docs/PRs/27886/coverage/navier_stokes)
- [`optimization`](https://mooseframework.inl.gov/docs/PRs/27886/coverage/optimization)
- [`peridynamics`](https://mooseframework.inl.gov/docs/PRs/27886/coverage/peridynamics)
- [`phase_field`](https://mooseframework.inl.gov/docs/PRs/27886/coverage/phase_field)
- [`porous_flow`](https://mooseframework.inl.gov/docs/PRs/27886/coverage/porous_flow)
- [`ray_tracing`](https://mooseframework.inl.gov/docs/PRs/27886/coverage/ray_tracing)
- [`rdg`](https://mooseframework.inl.gov/docs/PRs/27886/coverage/rdg)
- [`reactor`](https://mooseframework.inl.gov/docs/PRs/27886/coverage/reactor)
- [`richards`](https://mooseframework.inl.gov/docs/PRs/27886/coverage/richards)
- [`scalar_transport`](https://mooseframework.inl.gov/docs/PRs/27886/coverage/scalar_transport)
- [`solid_mechanics`](https://mooseframework.inl.gov/docs/PRs/27886/coverage/solid_mechanics)
- [`solid_properties`](https://mooseframework.inl.gov/docs/PRs/27886/coverage/solid_properties)
- [`stochastic_tools`](https://mooseframework.inl.gov/docs/PRs/27886/coverage/stochastic_tools)
- [`thermal_hydraulics`](https://mooseframework.inl.gov/docs/PRs/27886/coverage/thermal_hydraulics)
- [`xfem`](https://mooseframework.inl.gov/docs/PRs/27886/coverage/xfem)

</details>



This comment will be updated on new commits.

2024-06-18 02:05 UTC, lindsayad commented
@TheGreatCid looks like just the heavy test to fix

2024-06-18 15:50 UTC, TheGreatCid commented
Should be fixed now

2024-06-18 19:17 UTC, moosebuild commented
Job [Coverage](https://civet.inl.gov/job/2283343/) on ef97e20 wanted to post the following:


The following coverage requirement(s) failed:
- Failed to generate `framework` coverage rate (required: 81.0%)

2024-06-18 21:49 UTC, lindsayad approved these changes

2024-06-18 21:49 UTC, lindsayad commented
Thanks @TheGreatCid !

2024-06-18 21:49 UTC, merged