add_subdomain_names without add_subdomain_ids
idaholab/moose pull request #27968
Opened 2024-06-23 13:34 UTC by grunerjmeier

## Reason
Up until now, add_subdomain_names can only be used in combination with add_subdomain_ids. This forces the user to define subdomain ids by hand. To simplify the definition, it would be nice if Moose could simply assign a free ID for such additional subdomains automatically.

## Design
With this PR, Moose auto-assigns ids to subdomain names given in add_subdomain_names.

## Impact
This PR adds something new. No existing Moose model should be affected.

## Outlook
In case this PR is accepted, I'm happy to make a second, copy-pasta, one for add_sideset_names (see #27914).

2024-06-23 16:54 UTC, GiudGiud commented on test/tests/mesh/add_subdomain_ids/tests
> +    requirement = 'The system shall allow specifying valid subdomain names that do not exist on the initial mesh.'
add `exodiff_opts = '-pedantic'`
to make sure the assignements dont change

2024-06-23 16:56 UTC, GiudGiud requested changes
I think this is a great idea for this option

2024-06-23 16:56 UTC, GiudGiud commented on test/tests/mesh/add_subdomain_ids/add_subdomain_names.i
> +[]
```suggestion
```

this is an antiquated way of creating mesh tests.
We now use `cli_args = '--mesh-only'` to create tests that only check the mesh

2024-06-24 00:15 UTC, GiudGiud commented on framework/src/mesh/MooseMesh.C
> +    int offset = 0;
```suggestion
    subdomain_id_type offset = 0; 
```

2024-06-24 00:15 UTC, GiudGiud commented on framework/src/mesh/MooseMesh.C
> +      int sub_id = offset++;
```suggestion
      const auto sub_id = offset++;
```

2024-06-24 00:16 UTC, GiudGiud reviewed
looks good to me.
Please clean the commit history:
- squashing update commits
- mention changes instead of mentioning reviewer comments which are not captured outside of gh website

2024-06-24 05:40 UTC, grunerjmeier commented
> looks good to me. Please clean the commit history:
> 
> * squashing update commits
> * mention changes instead of mentioning reviewer comments which are not captured outside of gh website

Dear @GiudGiud,

I'll look into that. Please allow me to address one thing before (because it might add more commits to squash): Are you sure the test is working for our case? We create an empty subdomain and write an .e-file. Is the empty subdomain present in the .e-file? Paraview does not show it.

2024-06-24 13:29 UTC, GiudGiud commented
It does not show on the mesh yet. It shows in paraview in the list of subdomains.
Does the text exodiff is that line is removed?

2024-06-24 14:00 UTC, grunerjmeier commented
I did a small experiment with my test and I do not like the result:

When I remove "add_subdomain_names = 'MyAdditionalSubdomain'" from my test file "add_subdomain_names.i", the test is still passing (it should not). Regardless, if I have "exodiff_opts = '-pedantic'" or not.

In paraview "MyAdditionalSubdomain" is not showing up:
```
<?xml version="1.0"?>
<IOSS type="vtkDataAssembly" version="1.0" id="0">
  <element_blocks id="1">
    <block_0 id="2" label="block_0">
      <dataset id="0" />
    </block_0>
  </element_blocks>
  <node_sets id="3">
    <bottom id="4" label="bottom">
      <dataset id="1" />
    </bottom>
    <right id="5" label="right">
      <dataset id="2" />
    </right>
    <top id="6" label="top">
      <dataset id="3" />
    </top>
    <left id="7" label="left">
      <dataset id="4" />
    </left>
  </node_sets>
  <side_sets id="8">
    <bottom id="9" label="bottom">
      <dataset id="5" />
    </bottom>
    <right id="10" label="right">
      <dataset id="6" />
    </right>
    <top id="11" label="top">
      <dataset id="7" />
    </top>
    <left id="12" label="left">
      <dataset id="8" />
    </left>
  </side_sets>
</IOSS>
```

2024-06-24 17:52 UTC, grunerjmeier commented
I managed to change the test. Now I'm struggeling with squashing the commits...

2024-06-24 18:42 UTC, GiudGiud commented
See test failure
```
##########################################################################
ERROR: Your patch does not contain a valid ticket reference! (i.e. #1234)
Merge branch 'add_subdomain_names_only' of https://github.com/grunerjmeier/moose into test
allowing add_subdomain_names without add_subdomain_ids Co-authored-by: Guillaume Giudicelli <guillaume.giudicelli@gmail.com>

ERROR: The following files do not contain a newline character before EOF:
	test/tests/mesh/add_subdomain_ids/add_subdomain_names.i

Run the "delete_trailing_whitespace.sh" script in your $MOOSE_DIR/scripts directory.
##########################################################################
```

You ll want to use VScode and set your user settings as shown here so you never run into this again
https://mooseframework.inl.gov/help/development/VSCode.html

2024-06-25 02:04 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/2293732/) on 4a50480 wanted to post the following:

Your code requires style changes.  

A patch was auto generated and copied [here](https://mooseframework.inl.gov/docs/PRs/27968/clang_format/style.patch)  
You can directly apply the patch by running, in the top level of your repository:

`curl -s https://mooseframework.inl.gov/docs/PRs/27968/clang_format/style.patch | git apply -v`  

Alternatively, with your repository up to date and in the top level of your repository:

`git clang-format 95d6f4fd6c8286879312d2633ce3f0af5de48949`

2024-06-25 16:03 UTC, GiudGiud commented
looks like we still have issues with the server test. I ll investigate

2024-06-25 16:26 UTC, moosebuild commented
Job [Documentation](https://civet.inl.gov/job/2293837/) on bd05b08 wanted to post the following:

View the site [here](https://mooseframework.inl.gov/docs/PRs/27968/site)

This comment will be updated on new commits.

2024-06-25 19:48 UTC, GiudGiud commented
The recover testing is showing a real failure
See https://civet.inl.gov/job/2293872/

It seems mesh->getSubdomainId with a new name is returning a new ID instead of the expected automatically assigned id. 

I tried a little fix. If it does not work you'll have to take care of it. I'm under water rn

2024-06-25 22:30 UTC, moosebuild commented
Job [Coverage](https://civet.inl.gov/job/2295636/) on ac6060a wanted to post the following:


## Framework coverage

<table>
  <thead>
    <tr>
      <th></th>
      <th>68a347</th>
      <th colspan=4>#27968 ac6060</th>
    </tr>
    <tr>
      <th></th>
      <th>Total</th>
      <th>Total</th>
      <th>+/-</th>
      <th>New</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><b>Rate</b></td>
      <td>85.06%</td>
      <td>85.06%</td>
      <td>+0.00%</td>
      <td>100.00%</td>
    </tr>
    <tr>
      <td><b>Hits</b></td>
      <td>104403</td>
      <td>104411</td>
      <td>+8</td>
      <td>10</td>
    </tr>
    <tr>
      <td><b>Misses</b></td>
      <td>18335</td>
      <td>18336</td>
      <td>+1</td>
      <td>0</td>
    </tr>
  </tbody>
</table>

[Diff coverage report](https://mooseframework.inl.gov/docs/PRs/27968/coverage_diff/framework)

[Full coverage report](https://mooseframework.inl.gov/docs/PRs/27968/coverage/framework)


## Modules coverage

Coverage did not change

## Full coverage reports

<details>
<summary>Reports</summary>

- [`framework`](https://mooseframework.inl.gov/docs/PRs/27968/coverage/framework)
- [`chemical_reactions`](https://mooseframework.inl.gov/docs/PRs/27968/coverage/chemical_reactions)
- [`combined`](https://mooseframework.inl.gov/docs/PRs/27968/coverage/combined)
- [`contact`](https://mooseframework.inl.gov/docs/PRs/27968/coverage/contact)
- [`electromagnetics`](https://mooseframework.inl.gov/docs/PRs/27968/coverage/electromagnetics)
- [`external_petsc_solver`](https://mooseframework.inl.gov/docs/PRs/27968/coverage/external_petsc_solver)
- [`fluid_properties`](https://mooseframework.inl.gov/docs/PRs/27968/coverage/fluid_properties)
- [`fsi`](https://mooseframework.inl.gov/docs/PRs/27968/coverage/fsi)
- [`functional_expansion_tools`](https://mooseframework.inl.gov/docs/PRs/27968/coverage/functional_expansion_tools)
- [`geochemistry`](https://mooseframework.inl.gov/docs/PRs/27968/coverage/geochemistry)
- [`heat_transfer`](https://mooseframework.inl.gov/docs/PRs/27968/coverage/heat_transfer)
- [`level_set`](https://mooseframework.inl.gov/docs/PRs/27968/coverage/level_set)
- [`misc`](https://mooseframework.inl.gov/docs/PRs/27968/coverage/misc)
- [`navier_stokes`](https://mooseframework.inl.gov/docs/PRs/27968/coverage/navier_stokes)
- [`optimization`](https://mooseframework.inl.gov/docs/PRs/27968/coverage/optimization)
- [`peridynamics`](https://mooseframework.inl.gov/docs/PRs/27968/coverage/peridynamics)
- [`phase_field`](https://mooseframework.inl.gov/docs/PRs/27968/coverage/phase_field)
- [`porous_flow`](https://mooseframework.inl.gov/docs/PRs/27968/coverage/porous_flow)
- [`ray_tracing`](https://mooseframework.inl.gov/docs/PRs/27968/coverage/ray_tracing)
- [`rdg`](https://mooseframework.inl.gov/docs/PRs/27968/coverage/rdg)
- [`reactor`](https://mooseframework.inl.gov/docs/PRs/27968/coverage/reactor)
- [`richards`](https://mooseframework.inl.gov/docs/PRs/27968/coverage/richards)
- [`scalar_transport`](https://mooseframework.inl.gov/docs/PRs/27968/coverage/scalar_transport)
- [`solid_mechanics`](https://mooseframework.inl.gov/docs/PRs/27968/coverage/solid_mechanics)
- [`solid_properties`](https://mooseframework.inl.gov/docs/PRs/27968/coverage/solid_properties)
- [`stochastic_tools`](https://mooseframework.inl.gov/docs/PRs/27968/coverage/stochastic_tools)
- [`thermal_hydraulics`](https://mooseframework.inl.gov/docs/PRs/27968/coverage/thermal_hydraulics)
- [`xfem`](https://mooseframework.inl.gov/docs/PRs/27968/coverage/xfem)

</details>



This comment will be updated on new commits.

2024-06-25 22:32 UTC, GiudGiud approved these changes
recover issue fixed. 
only contributed test fixes

2024-06-25 22:32 UTC, merged

2024-06-26 04:51 UTC, grunerjmeier commented
Great! Thank you @GiudGiud!