Add missing routines and remove some issues in THM's LinearFP
idaholab/moose pull request #28026
Opened 2024-07-01 01:42 UTC by GiudGiud

refs #28025

2024-07-01 13:36 UTC, joshuahansel requested changes
This class is probably pretty error-prone even after your changes, so we should first consider removing it - do we get anything useful from this class?

If we do want to keep it, one thing that's problematic is the zero default values for mu, k, Pr. Ideally, we'd throw an error if these values tried to be used when not provided, but I'm sure there are cases when they get called and then never used. So maybe defaulting to NaNs is more appropriate?

2024-07-01 13:36 UTC, joshuahansel commented on modules/thermal_hydraulics/src/fluidproperties/LinearFluidProperties.C
> +  return _cv;
Pr, mu, and k are user parameters (though they're optional...), so this should probably be computed as `k*Pr/mu`.

2024-07-01 13:40 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/2304610/) on 75a4ee7 wanted to post the following:

Your code requires style changes.  

A patch was auto generated and copied [here](https://mooseframework.inl.gov/docs/PRs/28026/clang_format/style.patch)  
You can directly apply the patch by running, in the top level of your repository:

`curl -s https://mooseframework.inl.gov/docs/PRs/28026/clang_format/style.patch | git apply -v`  

Alternatively, with your repository up to date and in the top level of your repository:

`git clang-format 62dc981e43333a9858cf914f3e64195d7cb57d24`

2024-07-01 15:12 UTC, GiudGiud commented
> This class is probably pretty error-prone even after your changes, so we should first consider removing it - do we get anything useful from this class?

I would not remove it before it gets it first user haha
The interest came from a discussions post

2024-07-01 15:12 UTC, GiudGiud commented
I ll address your review.

2024-07-01 15:41 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/2305058/) on d4085d2 wanted to post the following:

The following commit(s) contain fixups:

- 7bb90ab809: fixup! Remove mistakes in LinearFP cp Remove mistakes in h from p T Add implementation for e_from_p_T (common need) refs #28025

2024-07-01 15:56 UTC, joshuahansel commented on modules/thermal_hydraulics/src/fluidproperties/LinearFluidProperties.C
> +  return _cv;
I see you deprecated `Pr`, so this is resolved 👍

2024-07-01 15:58 UTC, joshuahansel commented
> I would not remove it before it gets it first user

That's the best time to remove it 😆 

The discussion in question is https://github.com/idaholab/moose/discussions/28010. Regardless, these fixes are fine to be applied. We can decide afterward whether to follow-up with deprecation of the class.

2024-07-01 16:08 UTC, GiudGiud commented
> do we get anything useful from this class?

it's a nice example imo. It's almost simpler than SimpleFP and it has the potential to work with every single flow model once we figure out all the entropy routines

2024-07-01 17:49 UTC, moosebuild commented
Job [Documentation](https://civet.inl.gov/job/2305277/) on 947ec78 wanted to post the following:

View the site [here](https://mooseframework.inl.gov/docs/PRs/28026/site)

This comment will be updated on new commits.

2024-07-01 20:00 UTC, GiudGiud commented
Threaded failure is unrelated. app patch is merged. this should be good to go

2024-07-01 22:17 UTC, joshuahansel requested changes

2024-07-01 22:17 UTC, joshuahansel commented on modules/thermal_hydraulics/src/fluidproperties/LinearFluidProperties.C
>      _k(getParam<Real>("k")),
```suggestion
    _k(getParam<Real>("k"))
```

2024-07-01 22:17 UTC, joshuahansel commented on modules/thermal_hydraulics/src/fluidproperties/LinearFluidProperties.C
> +    _Pr = _cv / _k * _mu;
```suggestion
{
  if (isParamValid("Pr"))
    _Pr = getParam<Real>("Pr");
  else
    _Pr = _cv / _k * _mu;
```

2024-07-02 01:32 UTC, moosebuild commented
Job [Coverage](https://civet.inl.gov/job/2306674/) on 0a8df40 wanted to post the following:


## Framework coverage

<table>
  <thead>
    <tr>
      <th></th>
      <th>efc7cb</th>
      <th colspan=4>#28026 0a8df4</th>
    </tr>
    <tr>
      <th></th>
      <th>Total</th>
      <th>Total</th>
      <th>+/-</th>
      <th>New</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><b>Rate</b></td>
      <td>85.06%</td>
      <td>85.08%</td>
      <td>+0.01%</td>
      <td>-</td>
    </tr>
    <tr>
      <td><b>Hits</b></td>
      <td>104499</td>
      <td>104514</td>
      <td>+15</td>
      <td>0</td>
    </tr>
    <tr>
      <td><b>Misses</b></td>
      <td>18348</td>
      <td>18333</td>
      <td>-15</td>
      <td>0</td>
    </tr>
  </tbody>
</table>

[Diff coverage report](https://mooseframework.inl.gov/docs/PRs/28026/coverage_diff/framework)

[Full coverage report](https://mooseframework.inl.gov/docs/PRs/28026/coverage/framework)


## Modules coverage

### Thermal hydraulics

<table>
  <thead>
    <tr>
      <th></th>
      <th>efc7cb</th>
      <th colspan=4>#28026 0a8df4</th>
    </tr>
    <tr>
      <th></th>
      <th>Total</th>
      <th>Total</th>
      <th>+/-</th>
      <th>New</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><b>Rate</b></td>
      <td>89.14%</td>
      <td>89.15%</td>
      <td>+0.01%</td>
      <td>96.30%</td>
    </tr>
    <tr>
      <td><b>Hits</b></td>
      <td>14191</td>
      <td>14221</td>
      <td>+30</td>
      <td>52</td>
    </tr>
    <tr>
      <td><b>Misses</b></td>
      <td>1729</td>
      <td>1731</td>
      <td>+2</td>
      <td>2</td>
    </tr>
  </tbody>
</table>

[Diff coverage report](https://mooseframework.inl.gov/docs/PRs/28026/coverage_diff/thermal_hydraulics)

[Full coverage report](https://mooseframework.inl.gov/docs/PRs/28026/coverage/thermal_hydraulics)

## Full coverage reports

<details>
<summary>Reports</summary>

- [`framework`](https://mooseframework.inl.gov/docs/PRs/28026/coverage/framework)
- [`chemical_reactions`](https://mooseframework.inl.gov/docs/PRs/28026/coverage/chemical_reactions)
- [`combined`](https://mooseframework.inl.gov/docs/PRs/28026/coverage/combined)
- [`contact`](https://mooseframework.inl.gov/docs/PRs/28026/coverage/contact)
- [`electromagnetics`](https://mooseframework.inl.gov/docs/PRs/28026/coverage/electromagnetics)
- [`external_petsc_solver`](https://mooseframework.inl.gov/docs/PRs/28026/coverage/external_petsc_solver)
- [`fluid_properties`](https://mooseframework.inl.gov/docs/PRs/28026/coverage/fluid_properties)
- [`fsi`](https://mooseframework.inl.gov/docs/PRs/28026/coverage/fsi)
- [`functional_expansion_tools`](https://mooseframework.inl.gov/docs/PRs/28026/coverage/functional_expansion_tools)
- [`geochemistry`](https://mooseframework.inl.gov/docs/PRs/28026/coverage/geochemistry)
- [`heat_transfer`](https://mooseframework.inl.gov/docs/PRs/28026/coverage/heat_transfer)
- [`level_set`](https://mooseframework.inl.gov/docs/PRs/28026/coverage/level_set)
- [`misc`](https://mooseframework.inl.gov/docs/PRs/28026/coverage/misc)
- [`navier_stokes`](https://mooseframework.inl.gov/docs/PRs/28026/coverage/navier_stokes)
- [`optimization`](https://mooseframework.inl.gov/docs/PRs/28026/coverage/optimization)
- [`peridynamics`](https://mooseframework.inl.gov/docs/PRs/28026/coverage/peridynamics)
- [`phase_field`](https://mooseframework.inl.gov/docs/PRs/28026/coverage/phase_field)
- [`porous_flow`](https://mooseframework.inl.gov/docs/PRs/28026/coverage/porous_flow)
- [`ray_tracing`](https://mooseframework.inl.gov/docs/PRs/28026/coverage/ray_tracing)
- [`rdg`](https://mooseframework.inl.gov/docs/PRs/28026/coverage/rdg)
- [`reactor`](https://mooseframework.inl.gov/docs/PRs/28026/coverage/reactor)
- [`richards`](https://mooseframework.inl.gov/docs/PRs/28026/coverage/richards)
- [`scalar_transport`](https://mooseframework.inl.gov/docs/PRs/28026/coverage/scalar_transport)
- [`solid_mechanics`](https://mooseframework.inl.gov/docs/PRs/28026/coverage/solid_mechanics)
- [`solid_properties`](https://mooseframework.inl.gov/docs/PRs/28026/coverage/solid_properties)
- [`stochastic_tools`](https://mooseframework.inl.gov/docs/PRs/28026/coverage/stochastic_tools)
- [`thermal_hydraulics`](https://mooseframework.inl.gov/docs/PRs/28026/coverage/thermal_hydraulics)
- [`xfem`](https://mooseframework.inl.gov/docs/PRs/28026/coverage/xfem)

</details>



This comment will be updated on new commits.

2024-07-02 11:57 UTC, joshuahansel approved these changes

2024-07-02 12:36 UTC, merged

2024-07-02 12:36 UTC, GiudGiud commented
Thank you for the review!