improved error messages for invalid subdomain names in QuasiStaticSolidMechanicsPhysics
idaholab/moose pull request #28041
Opened 2024-07-02 09:53 UTC by grunerjmeier

If the user specifies invalid subdomain names during block restricting [Physics/Solid Mechanics/QuasiStatics], the error message does not point to the actual culprit. This PR aims to improve this error message.

closes #28040

2024-07-02 09:57 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/2307552/) on 862ba84 wanted to post the following:

Your code requires style changes.  

A patch was auto generated and copied [here](https://mooseframework.inl.gov/docs/PRs/28041/clang_format/style.patch)  
You can directly apply the patch by running, in the top level of your repository:

`curl -s https://mooseframework.inl.gov/docs/PRs/28041/clang_format/style.patch | git apply -v`  

Alternatively, with your repository up to date and in the top level of your repository:

`git clang-format 61714043f0e9dcbf822da0b852b47ef2c6a08ae2`

2024-07-02 19:11 UTC, GiudGiud requested changes
good fix.
I m a broken record but this should be handled once we transition this to inheriting from PhysicsBase

2024-07-02 19:11 UTC, GiudGiud commented on modules/solid_mechanics/src/physics/QuasiStaticSolidMechanicsPhysics.C
> +        mooseError("Subdomain \"" + name + "\" not found in mesh.");
paramError("block" ) would be more infomrative

2024-07-02 20:01 UTC, GiudGiud approved these changes

2024-07-02 20:11 UTC, GiudGiud commented
let's squash all 3 commits please

2024-07-02 22:17 UTC, moosebuild commented
Job [Documentation](https://civet.inl.gov/job/2309311/) on 86cda83 wanted to post the following:

View the site [here](https://mooseframework.inl.gov/docs/PRs/28041/site)

This comment will be updated on new commits.

2024-07-02 22:38 UTC, moosebuild commented
Job [Coverage](https://civet.inl.gov/job/2309326/) on 86cda83 wanted to post the following:


## Framework coverage

Coverage did not change


## Modules coverage

### Solid mechanics

<table>
  <thead>
    <tr>
      <th></th>
      <th>617140</th>
      <th colspan=4>#28041 86cda8</th>
    </tr>
    <tr>
      <th></th>
      <th>Total</th>
      <th>Total</th>
      <th>+/-</th>
      <th>New</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><b>Rate</b></td>
      <td>84.80%</td>
      <td>84.80%</td>
      <td>-0.00%</td>
      <td>75.00%</td>
    </tr>
    <tr>
      <td><b>Hits</b></td>
      <td>27698</td>
      <td>27700</td>
      <td>+2</td>
      <td>3</td>
    </tr>
    <tr>
      <td><b>Misses</b></td>
      <td>4964</td>
      <td>4965</td>
      <td>+1</td>
      <td>1</td>
    </tr>
  </tbody>
</table>

[Diff coverage report](https://mooseframework.inl.gov/docs/PRs/28041/coverage_diff/solid_mechanics)

[Full coverage report](https://mooseframework.inl.gov/docs/PRs/28041/coverage/solid_mechanics)

## Full coverage reports

<details>
<summary>Reports</summary>

- [`framework`](https://mooseframework.inl.gov/docs/PRs/28041/coverage/framework)
- [`chemical_reactions`](https://mooseframework.inl.gov/docs/PRs/28041/coverage/chemical_reactions)
- [`combined`](https://mooseframework.inl.gov/docs/PRs/28041/coverage/combined)
- [`contact`](https://mooseframework.inl.gov/docs/PRs/28041/coverage/contact)
- [`electromagnetics`](https://mooseframework.inl.gov/docs/PRs/28041/coverage/electromagnetics)
- [`external_petsc_solver`](https://mooseframework.inl.gov/docs/PRs/28041/coverage/external_petsc_solver)
- [`fluid_properties`](https://mooseframework.inl.gov/docs/PRs/28041/coverage/fluid_properties)
- [`fsi`](https://mooseframework.inl.gov/docs/PRs/28041/coverage/fsi)
- [`functional_expansion_tools`](https://mooseframework.inl.gov/docs/PRs/28041/coverage/functional_expansion_tools)
- [`geochemistry`](https://mooseframework.inl.gov/docs/PRs/28041/coverage/geochemistry)
- [`heat_transfer`](https://mooseframework.inl.gov/docs/PRs/28041/coverage/heat_transfer)
- [`level_set`](https://mooseframework.inl.gov/docs/PRs/28041/coverage/level_set)
- [`misc`](https://mooseframework.inl.gov/docs/PRs/28041/coverage/misc)
- [`navier_stokes`](https://mooseframework.inl.gov/docs/PRs/28041/coverage/navier_stokes)
- [`optimization`](https://mooseframework.inl.gov/docs/PRs/28041/coverage/optimization)
- [`peridynamics`](https://mooseframework.inl.gov/docs/PRs/28041/coverage/peridynamics)
- [`phase_field`](https://mooseframework.inl.gov/docs/PRs/28041/coverage/phase_field)
- [`porous_flow`](https://mooseframework.inl.gov/docs/PRs/28041/coverage/porous_flow)
- [`ray_tracing`](https://mooseframework.inl.gov/docs/PRs/28041/coverage/ray_tracing)
- [`rdg`](https://mooseframework.inl.gov/docs/PRs/28041/coverage/rdg)
- [`reactor`](https://mooseframework.inl.gov/docs/PRs/28041/coverage/reactor)
- [`richards`](https://mooseframework.inl.gov/docs/PRs/28041/coverage/richards)
- [`scalar_transport`](https://mooseframework.inl.gov/docs/PRs/28041/coverage/scalar_transport)
- [`solid_mechanics`](https://mooseframework.inl.gov/docs/PRs/28041/coverage/solid_mechanics)
- [`solid_properties`](https://mooseframework.inl.gov/docs/PRs/28041/coverage/solid_properties)
- [`stochastic_tools`](https://mooseframework.inl.gov/docs/PRs/28041/coverage/stochastic_tools)
- [`thermal_hydraulics`](https://mooseframework.inl.gov/docs/PRs/28041/coverage/thermal_hydraulics)
- [`xfem`](https://mooseframework.inl.gov/docs/PRs/28041/coverage/xfem)

</details>

## Warnings

- `solid_mechanics` new line coverage rate 75.00% is less than the suggested 90.0%



This comment will be updated on new commits.

2024-07-03 16:54 UTC, GiudGiud approved these changes

2024-07-04 05:14 UTC, grunerjmeier commented
Dear @GiudGiud,

It looks to me like the failure of the test is not due to a bug in this PR. Can you help?
> Failed to find a container to run in

Thanks & kind regards,
Jörg

2024-07-04 05:18 UTC, moosebuild commented
All [jobs](https://civet.inl.gov/event/186559/) on b8d89aa : invalidated by @GiudGiud

invalidating to get a fresh run

2024-07-04 05:18 UTC, GiudGiud commented
yes it s not related. Don't worry about it, I ll get this in when I can

2024-07-11 14:49 UTC, grunerjmeier commented
Dear Guillaume, Please excuse my pestering: Is there anything else to add to this PR from my side? Jörg

2024-07-11 15:12 UTC, merged

2024-07-11 15:13 UTC, GiudGiud commented
all good