End-to-end CUDA container
idaholab/moose pull request #28114
Opened 2024-07-11 23:04 UTC by loganharbour

2024-07-18 23:32 UTC, moosebuild commented
Job [Documentation](https://civet.inl.gov/job/2337828/) on 1ed7afa wanted to post the following:

View the site [here](https://mooseframework.inl.gov/docs/PRs/28114/site)

This comment will be updated on new commits.

2024-07-19 00:11 UTC, moosebuild commented
Job [Coverage](https://civet.inl.gov/job/2337843/) on 1ed7afa wanted to post the following:


## Framework coverage

<table>
  <thead>
    <tr>
      <th></th>
      <th>dc50da</th>
      <th colspan=4>#28114 1ed7af</th>
    </tr>
    <tr>
      <th></th>
      <th>Total</th>
      <th>Total</th>
      <th>+/-</th>
      <th>New</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><b>Rate</b></td>
      <td>85.07%</td>
      <td>85.07%</td>
      <td>-0.00%</td>
      <td>-</td>
    </tr>
    <tr>
      <td><b>Hits</b></td>
      <td>104586</td>
      <td>104585</td>
      <td>-1</td>
      <td>0</td>
    </tr>
    <tr>
      <td><b>Misses</b></td>
      <td>18359</td>
      <td>18360</td>
      <td>+1</td>
      <td>0</td>
    </tr>
  </tbody>
</table>

[Diff coverage report](https://mooseframework.inl.gov/docs/PRs/28114/coverage_diff/framework)

[Full coverage report](https://mooseframework.inl.gov/docs/PRs/28114/coverage/framework)


## Modules coverage

Coverage did not change

## Full coverage reports

<details>
<summary>Reports</summary>

- [`framework`](https://mooseframework.inl.gov/docs/PRs/28114/coverage/framework)
- [`chemical_reactions`](https://mooseframework.inl.gov/docs/PRs/28114/coverage/chemical_reactions)
- [`combined`](https://mooseframework.inl.gov/docs/PRs/28114/coverage/combined)
- [`contact`](https://mooseframework.inl.gov/docs/PRs/28114/coverage/contact)
- [`electromagnetics`](https://mooseframework.inl.gov/docs/PRs/28114/coverage/electromagnetics)
- [`external_petsc_solver`](https://mooseframework.inl.gov/docs/PRs/28114/coverage/external_petsc_solver)
- [`fluid_properties`](https://mooseframework.inl.gov/docs/PRs/28114/coverage/fluid_properties)
- [`fsi`](https://mooseframework.inl.gov/docs/PRs/28114/coverage/fsi)
- [`functional_expansion_tools`](https://mooseframework.inl.gov/docs/PRs/28114/coverage/functional_expansion_tools)
- [`geochemistry`](https://mooseframework.inl.gov/docs/PRs/28114/coverage/geochemistry)
- [`heat_transfer`](https://mooseframework.inl.gov/docs/PRs/28114/coverage/heat_transfer)
- [`level_set`](https://mooseframework.inl.gov/docs/PRs/28114/coverage/level_set)
- [`misc`](https://mooseframework.inl.gov/docs/PRs/28114/coverage/misc)
- [`navier_stokes`](https://mooseframework.inl.gov/docs/PRs/28114/coverage/navier_stokes)
- [`optimization`](https://mooseframework.inl.gov/docs/PRs/28114/coverage/optimization)
- [`peridynamics`](https://mooseframework.inl.gov/docs/PRs/28114/coverage/peridynamics)
- [`phase_field`](https://mooseframework.inl.gov/docs/PRs/28114/coverage/phase_field)
- [`porous_flow`](https://mooseframework.inl.gov/docs/PRs/28114/coverage/porous_flow)
- [`ray_tracing`](https://mooseframework.inl.gov/docs/PRs/28114/coverage/ray_tracing)
- [`rdg`](https://mooseframework.inl.gov/docs/PRs/28114/coverage/rdg)
- [`reactor`](https://mooseframework.inl.gov/docs/PRs/28114/coverage/reactor)
- [`richards`](https://mooseframework.inl.gov/docs/PRs/28114/coverage/richards)
- [`scalar_transport`](https://mooseframework.inl.gov/docs/PRs/28114/coverage/scalar_transport)
- [`solid_mechanics`](https://mooseframework.inl.gov/docs/PRs/28114/coverage/solid_mechanics)
- [`solid_properties`](https://mooseframework.inl.gov/docs/PRs/28114/coverage/solid_properties)
- [`stochastic_tools`](https://mooseframework.inl.gov/docs/PRs/28114/coverage/stochastic_tools)
- [`thermal_hydraulics`](https://mooseframework.inl.gov/docs/PRs/28114/coverage/thermal_hydraulics)
- [`xfem`](https://mooseframework.inl.gov/docs/PRs/28114/coverage/xfem)

</details>



This comment will be updated on new commits.

2024-10-12 04:32 UTC, moosebuild commented
Job [Documentation](https://civet.inl.gov/job/2492702/), step Docs: sync website on 627db04 wanted to post the following:

View the site [here](https://mooseframework.inl.gov/docs/PRs/28114/site)

This comment will be updated on new commits.

2024-10-12 05:32 UTC, moosebuild commented
Job [Coverage](https://civet.inl.gov/job/2492717/), step Generate coverage on 627db04 wanted to post the following:


## Framework coverage

<table>
  <thead>
    <tr>
      <th></th>
      <th>0a0f83</th>
      <th colspan=4>#28114 627db0</th>
    </tr>
    <tr>
      <th></th>
      <th>Total</th>
      <th>Total</th>
      <th>+/-</th>
      <th>New</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><b>Rate</b></td>
      <td>85.04%</td>
      <td>85.04%</td>
      <td>+0.00%</td>
      <td>-</td>
    </tr>
    <tr>
      <td><b>Hits</b></td>
      <td>106135</td>
      <td>106136</td>
      <td>+1</td>
      <td>0</td>
    </tr>
    <tr>
      <td><b>Misses</b></td>
      <td>18668</td>
      <td>18667</td>
      <td>-1</td>
      <td>0</td>
    </tr>
  </tbody>
</table>

[Diff coverage report](https://mooseframework.inl.gov/docs/PRs/28114/coverage_diff/framework)

[Full coverage report](https://mooseframework.inl.gov/docs/PRs/28114/coverage/framework)


## Modules coverage

Coverage did not change

## Full coverage reports

<details>
<summary>Reports</summary>

- [`framework`](https://mooseframework.inl.gov/docs/PRs/28114/coverage/framework)
- [`chemical_reactions`](https://mooseframework.inl.gov/docs/PRs/28114/coverage/chemical_reactions)
- [`combined`](https://mooseframework.inl.gov/docs/PRs/28114/coverage/combined)
- [`contact`](https://mooseframework.inl.gov/docs/PRs/28114/coverage/contact)
- [`electromagnetics`](https://mooseframework.inl.gov/docs/PRs/28114/coverage/electromagnetics)
- [`external_petsc_solver`](https://mooseframework.inl.gov/docs/PRs/28114/coverage/external_petsc_solver)
- [`fluid_properties`](https://mooseframework.inl.gov/docs/PRs/28114/coverage/fluid_properties)
- [`fsi`](https://mooseframework.inl.gov/docs/PRs/28114/coverage/fsi)
- [`functional_expansion_tools`](https://mooseframework.inl.gov/docs/PRs/28114/coverage/functional_expansion_tools)
- [`geochemistry`](https://mooseframework.inl.gov/docs/PRs/28114/coverage/geochemistry)
- [`heat_transfer`](https://mooseframework.inl.gov/docs/PRs/28114/coverage/heat_transfer)
- [`level_set`](https://mooseframework.inl.gov/docs/PRs/28114/coverage/level_set)
- [`misc`](https://mooseframework.inl.gov/docs/PRs/28114/coverage/misc)
- [`navier_stokes`](https://mooseframework.inl.gov/docs/PRs/28114/coverage/navier_stokes)
- [`optimization`](https://mooseframework.inl.gov/docs/PRs/28114/coverage/optimization)
- [`peridynamics`](https://mooseframework.inl.gov/docs/PRs/28114/coverage/peridynamics)
- [`phase_field`](https://mooseframework.inl.gov/docs/PRs/28114/coverage/phase_field)
- [`porous_flow`](https://mooseframework.inl.gov/docs/PRs/28114/coverage/porous_flow)
- [`ray_tracing`](https://mooseframework.inl.gov/docs/PRs/28114/coverage/ray_tracing)
- [`rdg`](https://mooseframework.inl.gov/docs/PRs/28114/coverage/rdg)
- [`reactor`](https://mooseframework.inl.gov/docs/PRs/28114/coverage/reactor)
- [`richards`](https://mooseframework.inl.gov/docs/PRs/28114/coverage/richards)
- [`scalar_transport`](https://mooseframework.inl.gov/docs/PRs/28114/coverage/scalar_transport)
- [`solid_mechanics`](https://mooseframework.inl.gov/docs/PRs/28114/coverage/solid_mechanics)
- [`solid_properties`](https://mooseframework.inl.gov/docs/PRs/28114/coverage/solid_properties)
- [`stochastic_tools`](https://mooseframework.inl.gov/docs/PRs/28114/coverage/stochastic_tools)
- [`thermal_hydraulics`](https://mooseframework.inl.gov/docs/PRs/28114/coverage/thermal_hydraulics)
- [`xfem`](https://mooseframework.inl.gov/docs/PRs/28114/coverage/xfem)

</details>



This comment will be updated on new commits.

2024-12-03 18:16 UTC, lindsayad commented
I'm pretty interested in this. With our recent PETSc update, we should be much closer to being able to run a clean test harness with a gpu-aware mpi/petsc

2024-12-03 19:36 UTC, loganharbour commented
Sounds good. I'll revive this today.

2024-12-05 15:57 UTC, loganharbour commented
@lindsayad can you try

```
oras://mooseharbor.hpc.inl.gov/moose-dev/moose-dev-cuda-openmpi-x86_64:pr-28114
```

when you have a moment?

2024-12-06 20:11 UTC, lindsayad commented
All the tests are failing with this message:
```
misc/check_error.missing_input: terminate called after throwing an instance of 'blas::Error'
misc/check_error.missing_input:   what():  system has unsupported display driver / cuda driver combination, in function get_device_count
```

2024-12-06 20:12 UTC, lindsayad commented
All tests are failing with this message
```
misc/check_error.missing_active_section_test: terminate called after throwing an instance of 'blas::Error'
misc/check_error.missing_active_section_test:   what():  system has unsupported display driver / cuda driver combination, in function get_device_count
```

2024-12-06 20:14 UTC, loganharbour commented
> All tests are failing with this message
> 
> ```
> misc/check_error.missing_active_section_test: terminate called after throwing an instance of 'blas::Error'
> misc/check_error.missing_active_section_test:   what():  system has unsupported display driver / cuda driver combination, in function get_device_count
> ```

What about if you run with the `--nv` option?

We shouldn't need to bind mount in the nvidia drivers here, but I think we're missing a flag with blas (or unsetting a variable) so that it doesn't try to run GPU code.

2025-01-28 18:51 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/2654743/), step Conda PETSc build config notification on dda7285 wanted to post the following:

The following file(s) are changed:

  conda/petsc/meta.yaml

The PETSc conda configuration has changed; ping @idaholab/moose-dev-ops

2025-01-28 18:51 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/2654743/), step Conda libmesh build config notification on dda7285 wanted to post the following:

The following file(s) are changed:

  conda/libmesh/meta.yaml

The libmesh conda configuration has changed; ping @idaholab/moose-dev-ops

2025-01-28 21:07 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/2655186/), step Conda build config check on 6ae7031 wanted to post the following:

A change of the following file(s) triggered this check:

  conda/peacock

The following file(s) are unchanged:

  conda/mpi/conda_build_config.yaml

The conda build config was not changed but one or more of its dependencies have changed

2025-01-28 21:07 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/2655186/), step Conda PETSc build config notification on 6ae7031 wanted to post the following:

The following file(s) are changed:

  conda/petsc/meta.yaml

The PETSc conda configuration has changed; ping @idaholab/moose-dev-ops

2025-01-28 21:07 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/2655186/), step Conda libmesh build config notification on 6ae7031 wanted to post the following:

The following file(s) are changed:

  conda/libmesh/meta.yaml

The libmesh conda configuration has changed; ping @idaholab/moose-dev-ops

2025-01-28 23:51 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/2655875/), step Conda build config check on 6a87d91 wanted to post the following:

A change of the following file(s) triggered this check:

  conda/peacock

The following file(s) are unchanged:

  conda/mpi/conda_build_config.yaml

The conda build config was not changed but one or more of its dependencies have changed

2025-01-28 23:51 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/2655875/), step Conda PETSc build config notification on 6a87d91 wanted to post the following:

The following file(s) are changed:

  conda/petsc/meta.yaml

The PETSc conda configuration has changed; ping @idaholab/moose-dev-ops

2025-01-28 23:51 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/2655875/), step Conda libmesh build config notification on 6a87d91 wanted to post the following:

The following file(s) are changed:

  conda/libmesh/meta.yaml

The libmesh conda configuration has changed; ping @idaholab/moose-dev-ops

2025-01-29 14:18 UTC, milljm commented on conda/libmesh/meta.yaml
> +{% set version = "2025.01.28" %}
I think the version should remain the same, if libmesh didn't get updated. I don't see a libmesh update in this PR.

2025-01-29 14:59 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/2657058/), step Conda build config check on b2004d5 wanted to post the following:

A change of the following file(s) triggered this check:

  conda/peacock

The following file(s) are unchanged:

  conda/mpi/conda_build_config.yaml

The conda build config was not changed but one or more of its dependencies have changed

2025-01-29 14:59 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/2657058/), step Conda PETSc build config notification on b2004d5 wanted to post the following:

The following file(s) are changed:

  conda/petsc/meta.yaml

The PETSc conda configuration has changed; ping @idaholab/moose-dev-ops

2025-01-29 15:23 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/2657114/), step Conda build config check on 71b27a8 wanted to post the following:

A change of the following file(s) triggered this check:

  conda/peacock

The following file(s) are unchanged:

  conda/mpi/conda_build_config.yaml

The conda build config was not changed but one or more of its dependencies have changed

2025-01-29 15:23 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/2657114/), step Conda PETSc build config notification on 71b27a8 wanted to post the following:

The following file(s) are changed:

  conda/petsc/meta.yaml

The PETSc conda configuration has changed; ping @idaholab/moose-dev-ops

2025-01-29 15:23 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/2657114/), step Conda libmesh build config notification on 71b27a8 wanted to post the following:

The following file(s) are changed:

  conda/libmesh/meta.yaml

The libmesh conda configuration has changed; ping @idaholab/moose-dev-ops

2025-01-29 22:00 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/2658098/), step Conda build config check on cc49bd3 wanted to post the following:

A change of the following file(s) triggered this check:

  conda/peacock

The following file(s) are unchanged:

  conda/mpi/conda_build_config.yaml

The conda build config was not changed but one or more of its dependencies have changed

2025-01-29 22:00 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/2658098/), step Conda PETSc build config notification on cc49bd3 wanted to post the following:

The following file(s) are changed:

  conda/petsc/meta.yaml

The PETSc conda configuration has changed; ping @idaholab/moose-dev-ops

2025-01-29 22:00 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/2658098/), step Conda libmesh build config notification on cc49bd3 wanted to post the following:

The following file(s) are changed:

  conda/libmesh/meta.yaml

The libmesh conda configuration has changed; ping @idaholab/moose-dev-ops

2025-01-30 05:28 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/2659498/), step Conda build config check on 1e3e71a wanted to post the following:

A change of the following file(s) triggered this check:

  conda/peacock

The following file(s) are unchanged:

  conda/mpi/conda_build_config.yaml

The conda build config was not changed but one or more of its dependencies have changed

2025-01-30 05:28 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/2659498/), step Conda PETSc build config notification on 1e3e71a wanted to post the following:

The following file(s) are changed:

  conda/petsc/meta.yaml

The PETSc conda configuration has changed; ping @idaholab/moose-dev-ops

2025-01-30 05:28 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/2659498/), step Conda libmesh build config notification on 1e3e71a wanted to post the following:

The following file(s) are changed:

  conda/libmesh/meta.yaml

The libmesh conda configuration has changed; ping @idaholab/moose-dev-ops

2025-01-30 17:07 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/2660321/), step Conda build config check on 8ccd004 wanted to post the following:

A change of the following file(s) triggered this check:

  conda/peacock

The following file(s) are unchanged:

  conda/mpi/conda_build_config.yaml

The conda build config was not changed but one or more of its dependencies have changed

2025-01-30 17:07 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/2660321/), step Conda libmesh build config notification on 8ccd004 wanted to post the following:

The following file(s) are changed:

  conda/libmesh/meta.yaml

The libmesh conda configuration has changed; ping @idaholab/moose-dev-ops

2025-02-05 23:46 UTC, lindsayad commented
is there a draft civet recipe for executing in this cuda container? Would be nice to see what progress we are making in CI

2025-02-06 03:48 UTC, loganharbour commented
> is there a draft civet recipe for executing in this cuda container? Would be nice to see what progress we are making in CI

https://civet.inl.gov/job/2675477/

This guy. It's just libtorch stuff at this point

2025-02-06 19:03 UTC, lindsayad commented
I would expect to see a lot more failures than I do

2025-02-06 20:02 UTC, loganharbour commented
> I would expect to see a lot more failures than I do

What would you expect to see? this is just libtorch moose

2025-02-06 22:50 UTC, lindsayad commented
Oh I didn't understand that basically all tests are getting excluded due to `cuda not in libtorch_devices`. Can we get all those tests running?

2025-04-03 22:09 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/2797555/), step Versioner verify on 95437f6 wanted to post the following:

### Versioner templates

Found 16 templates, 0 failed


### Versioner versions

Found 10 packages, 6 changed, 0 failed

| package     | status   | hash    | to hash   | version                         | to version                      |
|-------------|----------|---------|-----------|---------------------------------|---------------------------------|
| mpi         | CHANGE   | d5b4334 | 24718b1   | 2025.03.24                      | 2025.04.03                      |
| libmesh-vtk | CHANGE   | 83f29bc | ff2c2f4   | 9.3.0 build 6                   | 9.3.0 build 7                   |
| peacock     | CHANGE   | f8f84d6 | 52c906e   | 2025.03.24                      | 2025.04.03                      |
| petsc       | CHANGE   | caeec6b | c662a9b   | 3.22.1.193.g72c1e49ee3d build 2 | 3.22.1.193.g72c1e49ee3d build 3 |
| libmesh     | CHANGE   | bc5c687 | 85f2e0d   | 2025.03.06 build 1              | 2025.03.06 build 2              |
| moose-dev   | CHANGE   | 00b281f | 7febcc0   | 2025.03.24                      | 2025.04.03                      |

2025-04-07 16:43 UTC, moosebuild commented
Job [Apptainer build cuda](https://civet.inl.gov/job/2797606/) on 95437f6 : invalidated by @lindsayad

2025-04-07 19:09 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/2802161/), step Versioner verify on 42d6eb6 wanted to post the following:

### Versioner templates

Found 16 templates, 0 failed


### Versioner versions

Found 10 packages, 6 changed, 0 failed

| package     | status   | hash    | to hash   | version                         | to version                      |
|-------------|----------|---------|-----------|---------------------------------|---------------------------------|
| mpi         | CHANGE   | d5b4334 | 6f1203a   | 2025.03.24                      | 2025.04.07                      |
| libmesh-vtk | CHANGE   | 83f29bc | c047e39   | 9.3.0 build 6                   | 9.3.0 build 7                   |
| peacock     | CHANGE   | f8f84d6 | 28256ea   | 2025.03.24                      | 2025.04.07                      |
| petsc       | CHANGE   | caeec6b | dcd9726   | 3.22.1.193.g72c1e49ee3d build 2 | 3.22.1.193.g72c1e49ee3d build 3 |
| libmesh     | CHANGE   | bc5c687 | 8097345   | 2025.03.06 build 1              | 2025.03.06 build 2              |
| moose-dev   | CHANGE   | 00b281f | 1b5ddd2   | 2025.03.24                      | 2025.04.07                      |

2025-04-29 17:30 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/2845690/), step Versioner verify on e2897c6 wanted to post the following:

### Versioner templates

Found 16 templates, 0 failed


### Versioner versions

Found 10 packages, 6 changed, 0 failed

| package     | status   | hash    | to hash   | version                       | to version                    |
|-------------|----------|---------|-----------|-------------------------------|-------------------------------|
| mpi         | CHANGE   | a9161d1 | 1411c35   | 2025.04.17                    | 2025.04.29                    |
| libmesh-vtk | CHANGE   | 59e681e | ceaf7db   | 9.4.2 build 1                 | 9.4.2 build 2                 |
| peacock     | CHANGE   | a231b10 | 19f0d37   | 2025.04.17                    | 2025.04.29                    |
| petsc       | CHANGE   | ff9a7ec | b532617   | 3.23.0.6.gd9d7fd11dca build 1 | 3.23.0.6.gd9d7fd11dca build 2 |
| libmesh     | CHANGE   | e0eb0da | aeeb83a   | 2025.04.22 build 0            | 2025.04.22 build 1            |
| moose-dev   | CHANGE   | 8a3a8dd | 01d271e   | 2025.04.22                    | 2025.04.29                    |

2025-04-29 19:49 UTC, moosebuild commented
Job [Apptainer build cuda](https://civet.inl.gov/job/2845741/) on e2897c6 : invalidated by @milljm

updated trusts

2025-05-06 20:47 UTC, lindsayad commented
Only 22!
```
outputs/iterative.exodus ......................................................................................................... FAILED (EXODIFF)
reporters/iteration_info.info/default ......................................................................................... FAILED (SCHEMADIFF)
executioners/nullspace.test_singular ............................................................................................. FAILED (CSVDIFF)
executioners/nl_divergence_tolerance.test ........................................................................................ FAILED (EXODIFF)
multiapps/picard_catch_up.catch_up/test .......................................................................................... FAILED (EXODIFF)
multiapps/linearfv_nonlinearfv.linearfv/linearfv_mainapp ......................................................................... FAILED (EXODIFF)
outputs/iterative.iterative/exodus_steady ........................................................................................ FAILED (EXODIFF)
executioners/nullspace.test_singular_contaminated ................................................................................ FAILED (CSVDIFF)
misc/signal_handler.test_signal_recover_exodiff .................................................................................. FAILED (EXODIFF)
reporters/iteration_info.info/steady .......................................................................................... FAILED (SCHEMADIFF)
outputs/iterative.iterative/exodus_steady_sequence ............................................................................... FAILED (EXODIFF)
linearfvkernels/block-restriction.diff-react-exact ............................................................................... FAILED (CSVDIFF)
outputs/iterative.start_stop/exodus_inline ....................................................................................... FAILED (EXODIFF)
outputs/iterative.start_stop/exodus_start_time ................................................................................... FAILED (EXODIFF)
misc/signal_handler.test_signal_parallel_recover_exodiff ......................................................................... FAILED (EXODIFF)
executioners/nl_forced_its.nl_forced_its ......................................................................... FAILED (EXPECTED OUTPUT MISSING)
fvkernels/two-var-flux-and-kernel.jac ................................................................................. FAILED (INCORRECT JACOBIAN)
multiapps/petsc_options.test ..................................................................................... FAILED (EXPECTED OUTPUT MISSING)
executioners/nl_divergence_tolerance.test_abs_divtol ............................................................. FAILED (EXPECTED OUTPUT MISSING)
mortar/periodic_segmental_constraint.periodic_checker2d ........................................................................... FAILED (ERRMSG)
linearfvkernels/diffusion-reaction-advection.mms-adr-1d-outflow .................................................................... FAILED (CRASH)
preconditioners/hmg.hmg_strumpack ................................................................... [min_cpus=2] FAILED (EXPECTED OUTPUT MISSING)
---------------------------------------------------------------------------------------------------------------------------------------------------
Ran 4755 tests in 615.0 seconds. Average test time 2.9 seconds, maximum test time 487.8 seconds.
4733 passed, 122 skipped, 22 FAILED
```

2025-05-07 22:42 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/2859370/), step Clang format on 372b68e wanted to post the following:

Your code requires style changes.  

A patch was auto generated and copied [here](https://mooseframework.inl.gov/docs/PRs/28114/clang_format/style.patch)  
You can directly apply the patch by running, in the top level of your repository:

`curl -s https://mooseframework.inl.gov/docs/PRs/28114/clang_format/style.patch | git apply -v`  

Alternatively, with your repository up to date and in the top level of your repository:

`git clang-format 6c09b202ee6e7650c2b8fc51946a790cfe6a444e`

2025-05-07 22:42 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/2859370/), step Versioner verify on 372b68e wanted to post the following:

### Versioner templates

Found 16 templates, 0 failed


### Versioner versions

Found 10 packages, 6 changed, 0 failed

| package     | status   | hash    | to hash   | version                       | to version                    |
|-------------|----------|---------|-----------|-------------------------------|-------------------------------|
| mpi         | CHANGE   | a9161d1 | 1411c35   | 2025.04.17                    | 2025.04.29                    |
| libmesh-vtk | CHANGE   | 59e681e | ceaf7db   | 9.4.2 build 1                 | 9.4.2 build 2                 |
| peacock     | CHANGE   | a231b10 | 19f0d37   | 2025.04.17                    | 2025.04.29                    |
| petsc       | CHANGE   | ff9a7ec | b532617   | 3.23.0.6.gd9d7fd11dca build 1 | 3.23.0.6.gd9d7fd11dca build 2 |
| libmesh     | CHANGE   | e0eb0da | aeeb83a   | 2025.04.22 build 0            | 2025.04.22 build 1            |
| moose-dev   | CHANGE   | 8a3a8dd | 42bc548   | 2025.04.22                    | 2025.04.29                    |

2025-05-07 23:54 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/2859514/), step Versioner verify on 42c5040 wanted to post the following:

### Versioner templates

Found 16 templates, 0 failed


### Versioner versions

Found 10 packages, 6 changed, 0 failed

| package     | status   | hash    | to hash   | version                       | to version                    |
|-------------|----------|---------|-----------|-------------------------------|-------------------------------|
| mpi         | CHANGE   | a9161d1 | 1411c35   | 2025.04.17                    | 2025.04.29                    |
| libmesh-vtk | CHANGE   | 59e681e | ceaf7db   | 9.4.2 build 1                 | 9.4.2 build 2                 |
| peacock     | CHANGE   | a231b10 | 19f0d37   | 2025.04.17                    | 2025.04.29                    |
| petsc       | CHANGE   | ff9a7ec | b532617   | 3.23.0.6.gd9d7fd11dca build 1 | 3.23.0.6.gd9d7fd11dca build 2 |
| libmesh     | CHANGE   | e0eb0da | aeeb83a   | 2025.04.22 build 0            | 2025.04.22 build 1            |
| moose-dev   | CHANGE   | 8a3a8dd | 42bc548   | 2025.04.22                    | 2025.04.29                    |

2025-05-08 01:58 UTC, lindsayad commented
```
4768 passed, 109 skipped, 0 failed
```

2025-05-08 17:03 UTC, moosebuild commented
Job [Apptainer build cuda](https://civet.inl.gov/job/2859565/) on 42c5040 : invalidated by @milljm

updated trusts

2025-05-08 18:43 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/2861939/), step Versioner verify on 31a0619 wanted to post the following:

### Versioner templates

Found 16 templates, 0 failed


### Versioner versions

Found 10 packages, 6 changed, 6 failed

| package     | status    | hash    | to hash   | version                       | to version                    |
|-------------|-----------|---------|-----------|-------------------------------|-------------------------------|
| mpi         | NEED BUMP | a9161d1 | 18bc0d7   | 2025.04.17                    | 2025.04.17                    |
| libmesh-vtk | NEED BUMP | 59e681e | 2e2fffb   | 9.4.2 build 1                 | 9.4.2 build 1                 |
| peacock     | NEED BUMP | a231b10 | d30774f   | 2025.04.17                    | 2025.04.17                    |
| petsc       | NEED BUMP | ff9a7ec | 8766aea   | 3.23.0.6.gd9d7fd11dca build 1 | 3.23.0.6.gd9d7fd11dca build 1 |
| libmesh     | NEED BUMP | e0eb0da | 4a9497d   | 2025.04.22 build 0            | 2025.04.22 build 0            |
| moose-dev   | NEED BUMP | 8a3a8dd | f914820   | 2025.04.22                    | 2025.04.22                    |

Verification failed.

2025-05-08 21:16 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/2862375/), step Versioner verify on 526fcab wanted to post the following:

### Versioner templates

Found 16 templates, 0 failed


### Versioner versions

Found 10 packages, 6 changed, 0 failed

| package     | status   | hash    | to hash   | version                       | to version                    |
|-------------|----------|---------|-----------|-------------------------------|-------------------------------|
| mpi         | CHANGE   | a9161d1 | b26fa2b   | 2025.04.17                    | 2025.05.08                    |
| libmesh-vtk | CHANGE   | 59e681e | ea0e9c3   | 9.4.2 build 1                 | 9.4.2 build 2                 |
| peacock     | CHANGE   | a231b10 | 4aede21   | 2025.04.17                    | 2025.05.08                    |
| petsc       | CHANGE   | ff9a7ec | b7c7976   | 3.23.0.6.gd9d7fd11dca build 1 | 3.23.0.6.gd9d7fd11dca build 2 |
| libmesh     | CHANGE   | e0eb0da | 345bb14   | 2025.04.22 build 0            | 2025.04.22 build 1            |
| moose-dev   | CHANGE   | 8a3a8dd | 4fa6e3e   | 2025.04.22                    | 2025.05.08                    |

2025-05-09 12:14 UTC, moosebuild commented
Job [Apptainer build cuda](https://civet.inl.gov/job/2862426/) on 526fcab : invalidated by @milljm

updated trusts

2025-05-13 02:19 UTC, loganharbour commented
FYI @lindsayad - I invalidated your build after the recipe merge. Looks good.

2025-05-17 16:16 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/2876160/), step Versioner verify on 9dca28d wanted to post the following:

### Versioner templates

Found 16 templates, 0 failed


### Versioner influential files

Found 52 influential files, 15 changed, 0 added, 0 removed

| package     | status   | file                                      |
|-------------|----------|-------------------------------------------|
| mpi         | CHANGE   | apptainer/mpi.def                         |
| mpi         | CHANGE   | conda/mpi/meta.yaml                       |
| libmesh-vtk | CHANGE   | conda/libmesh-vtk/conda_build_config.yaml |
| libmesh-vtk | CHANGE   | conda/libmesh-vtk/meta.yaml               |
| peacock     | CHANGE   | conda/peacock/conda_build_config.yaml     |
| peacock     | CHANGE   | conda/peacock/meta.yaml                   |
| petsc       | CHANGE   | apptainer/petsc.def                       |
| petsc       | CHANGE   | conda/petsc/conda_build_config.yaml       |
| petsc       | CHANGE   | conda/petsc/meta.yaml                     |
| libmesh     | CHANGE   | apptainer/libmesh.def                     |
| libmesh     | CHANGE   | conda/libmesh/conda_build_config.yaml     |
| libmesh     | CHANGE   | conda/libmesh/meta.yaml                   |
| moose-dev   | CHANGE   | apptainer/moose-dev.def                   |
| moose-dev   | CHANGE   | conda/moose-dev/conda_build_config.yaml   |
| moose-dev   | CHANGE   | conda/moose-dev/meta.yaml                 |

### Versioner versions

Found 10 packages, 6 changed, 0 failed

| package     | status   | hash    | to hash   | version                       | to version                    |
|-------------|----------|---------|-----------|-------------------------------|-------------------------------|
| mpi         | CHANGE   | a9161d1 | c70f258   | 2025.04.17                    | 2025.05.15                    |
| libmesh-vtk | CHANGE   | 59e681e | 8de5ba5   | 9.4.2 build 1                 | 9.4.2 build 2                 |
| peacock     | CHANGE   | a231b10 | 2b0c7fd   | 2025.04.17                    | 2025.05.15                    |
| petsc       | CHANGE   | ff9a7ec | 2df8fce   | 3.23.0.6.gd9d7fd11dca build 1 | 3.23.0.6.gd9d7fd11dca build 2 |
| libmesh     | CHANGE   | e0eb0da | 31c6e0c   | 2025.04.22 build 0            | 2025.04.22 build 1            |
| moose-dev   | CHANGE   | 5500deb | 19ea363   | 2025.05.13                    | 2025.05.15                    |

2025-05-18 07:23 UTC, dschwen commented
Is there an issue for this? What does end-to-end mean in this context? PETSc with CUDA? I.e. "full stack CUDA"?

2025-05-27 17:15 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/2898965/), step Versioner verify on ea279ac wanted to post the following:

### Versioner templates

Found 16 templates, 0 failed


### Versioner influential files

Found 57 influential files, 15 changed, 0 added, 0 removed

| package     | status   | file                                      |
|-------------|----------|-------------------------------------------|
| mpi         | CHANGE   | apptainer/mpi.def                         |
| mpi         | CHANGE   | conda/mpi/meta.yaml                       |
| libmesh-vtk | CHANGE   | conda/libmesh-vtk/conda_build_config.yaml |
| libmesh-vtk | CHANGE   | conda/libmesh-vtk/meta.yaml               |
| peacock     | CHANGE   | conda/peacock/conda_build_config.yaml     |
| peacock     | CHANGE   | conda/peacock/meta.yaml                   |
| petsc       | CHANGE   | apptainer/petsc.def                       |
| petsc       | CHANGE   | conda/petsc/conda_build_config.yaml       |
| petsc       | CHANGE   | conda/petsc/meta.yaml                     |
| libmesh     | CHANGE   | apptainer/libmesh.def                     |
| libmesh     | CHANGE   | conda/libmesh/conda_build_config.yaml     |
| libmesh     | CHANGE   | conda/libmesh/meta.yaml                   |
| moose-dev   | CHANGE   | apptainer/moose-dev.def                   |
| moose-dev   | CHANGE   | conda/moose-dev/conda_build_config.yaml   |
| moose-dev   | CHANGE   | conda/moose-dev/meta.yaml                 |

### Versioner versions

Found 10 packages, 6 changed, 0 failed

| package     | status   | hash    | to hash   | version                       | to version                    |
|-------------|----------|---------|-----------|-------------------------------|-------------------------------|
| mpi         | CHANGE   | a9161d1 | c262069   | 2025.04.17                    | 2025.05.27                    |
| libmesh-vtk | CHANGE   | 042bd0b | b2dd0a3   | 9.4.2 build 2                 | 9.4.2 build 3                 |
| peacock     | CHANGE   | a231b10 | 3032d5d   | 2025.04.17                    | 2025.05.27                    |
| petsc       | CHANGE   | ff9a7ec | ee25d57   | 3.23.0.6.gd9d7fd11dca build 1 | 3.23.0.6.gd9d7fd11dca build 2 |
| libmesh     | CHANGE   | 982ea19 | 8b013c5   | 2025.05.23 build 0            | 2025.05.23 build 1            |
| moose-dev   | CHANGE   | 92d3c2e | 504413f   | 2025.05.23                    | 2025.05.27                    |

2025-05-27 20:41 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/2900026/), step Versioner verify on 53a60ca wanted to post the following:

### Versioner templates

Found 16 templates, 0 failed


### Versioner influential files

Found 57 influential files, 15 changed, 0 added, 0 removed

| package     | status   | file                                      |
|-------------|----------|-------------------------------------------|
| mpi         | CHANGE   | apptainer/mpi.def                         |
| mpi         | CHANGE   | conda/mpi/meta.yaml                       |
| libmesh-vtk | CHANGE   | conda/libmesh-vtk/conda_build_config.yaml |
| libmesh-vtk | CHANGE   | conda/libmesh-vtk/meta.yaml               |
| peacock     | CHANGE   | conda/peacock/conda_build_config.yaml     |
| peacock     | CHANGE   | conda/peacock/meta.yaml                   |
| petsc       | CHANGE   | apptainer/petsc.def                       |
| petsc       | CHANGE   | conda/petsc/conda_build_config.yaml       |
| petsc       | CHANGE   | conda/petsc/meta.yaml                     |
| libmesh     | CHANGE   | apptainer/libmesh.def                     |
| libmesh     | CHANGE   | conda/libmesh/conda_build_config.yaml     |
| libmesh     | CHANGE   | conda/libmesh/meta.yaml                   |
| moose-dev   | CHANGE   | apptainer/moose-dev.def                   |
| moose-dev   | CHANGE   | conda/moose-dev/conda_build_config.yaml   |
| moose-dev   | CHANGE   | conda/moose-dev/meta.yaml                 |

### Versioner versions

Found 10 packages, 6 changed, 0 failed

| package     | status   | hash    | to hash   | version                       | to version                    |
|-------------|----------|---------|-----------|-------------------------------|-------------------------------|
| mpi         | CHANGE   | a9161d1 | e10279b   | 2025.04.17                    | 2025.05.27                    |
| libmesh-vtk | CHANGE   | 042bd0b | 4c8eb27   | 9.4.2 build 2                 | 9.4.2 build 3                 |
| peacock     | CHANGE   | a231b10 | ee8b2f5   | 2025.04.17                    | 2025.05.27                    |
| petsc       | CHANGE   | ff9a7ec | 088bc00   | 3.23.0.6.gd9d7fd11dca build 1 | 3.23.0.6.gd9d7fd11dca build 2 |
| libmesh     | CHANGE   | 982ea19 | 0e90357   | 2025.05.23 build 0            | 2025.05.23 build 1            |
| moose-dev   | CHANGE   | 92d3c2e | 4bdebef   | 2025.05.23                    | 2025.05.27                    |

2025-05-28 15:39 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/2902174/), step Versioner verify on bed31c2 wanted to post the following:

### Versioner templates

Found 16 templates, 0 failed


### Versioner influential files

Found 57 influential files, 15 changed, 0 added, 0 removed

| package     | status   | file                                      |
|-------------|----------|-------------------------------------------|
| mpi         | CHANGE   | apptainer/mpi.def                         |
| mpi         | CHANGE   | conda/mpi/meta.yaml                       |
| libmesh-vtk | CHANGE   | conda/libmesh-vtk/conda_build_config.yaml |
| libmesh-vtk | CHANGE   | conda/libmesh-vtk/meta.yaml               |
| peacock     | CHANGE   | conda/peacock/conda_build_config.yaml     |
| peacock     | CHANGE   | conda/peacock/meta.yaml                   |
| petsc       | CHANGE   | apptainer/petsc.def                       |
| petsc       | CHANGE   | conda/petsc/conda_build_config.yaml       |
| petsc       | CHANGE   | conda/petsc/meta.yaml                     |
| libmesh     | CHANGE   | apptainer/libmesh.def                     |
| libmesh     | CHANGE   | conda/libmesh/conda_build_config.yaml     |
| libmesh     | CHANGE   | conda/libmesh/meta.yaml                   |
| moose-dev   | CHANGE   | apptainer/moose-dev.def                   |
| moose-dev   | CHANGE   | conda/moose-dev/conda_build_config.yaml   |
| moose-dev   | CHANGE   | conda/moose-dev/meta.yaml                 |

### Versioner versions

Found 10 packages, 6 changed, 0 failed

| package     | status   | hash    | to hash   | version                       | to version                    |
|-------------|----------|---------|-----------|-------------------------------|-------------------------------|
| mpi         | CHANGE   | a9161d1 | e10279b   | 2025.04.17                    | 2025.05.27                    |
| libmesh-vtk | CHANGE   | 042bd0b | 4c8eb27   | 9.4.2 build 2                 | 9.4.2 build 3                 |
| peacock     | CHANGE   | a231b10 | ee8b2f5   | 2025.04.17                    | 2025.05.27                    |
| petsc       | CHANGE   | ff9a7ec | 088bc00   | 3.23.0.6.gd9d7fd11dca build 1 | 3.23.0.6.gd9d7fd11dca build 2 |
| libmesh     | CHANGE   | 982ea19 | 0e90357   | 2025.05.23 build 0            | 2025.05.23 build 1            |
| moose-dev   | CHANGE   | 92d3c2e | 4bdebef   | 2025.05.23                    | 2025.05.27                    |

2025-05-29 04:06 UTC, lindsayad approved these changes
I approve the work that's not my own

2025-06-06 16:38 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/2925407/), step Versioner verify on b6c911a wanted to post the following:

### Versioner templates

Found 16 templates, 0 failed


### Versioner influential files

Found 57 influential files, 16 changed, 0 added, 0 removed

| package     | status   | file                                      |
|-------------|----------|-------------------------------------------|
| mpi         | CHANGE   | apptainer/mpi.def                         |
| mpi         | CHANGE   | conda/mpi/meta.yaml                       |
| libmesh-vtk | CHANGE   | conda/libmesh-vtk/conda_build_config.yaml |
| libmesh-vtk | CHANGE   | conda/libmesh-vtk/meta.yaml               |
| peacock     | CHANGE   | conda/peacock/conda_build_config.yaml     |
| peacock     | CHANGE   | conda/peacock/meta.yaml                   |
| petsc       | CHANGE   | apptainer/petsc.def                       |
| petsc       | CHANGE   | conda/petsc/conda_build_config.yaml       |
| petsc       | CHANGE   | conda/petsc/meta.yaml                     |
| libmesh     | CHANGE   | apptainer/libmesh.def                     |
| libmesh     | CHANGE   | conda/libmesh/conda_build_config.yaml     |
| libmesh     | CHANGE   | conda/libmesh/meta.yaml                   |
| moose-dev   | CHANGE   | apptainer/moose-dev.def                   |
| moose-dev   | CHANGE   | apptainer/remove_channels.def             |
| moose-dev   | CHANGE   | conda/moose-dev/conda_build_config.yaml   |
| moose-dev   | CHANGE   | conda/moose-dev/meta.yaml                 |

### Versioner versions

Found 10 packages, 6 changed, 0 failed

| package     | status   | hash    | to hash   | version                       | to version                    |
|-------------|----------|---------|-----------|-------------------------------|-------------------------------|
| mpi         | CHANGE   | a9161d1 | 5b9b541   | 2025.04.17                    | 2025.06.06                    |
| libmesh-vtk | CHANGE   | 042bd0b | 4794c80   | 9.4.2 build 2                 | 9.4.2 build 3                 |
| peacock     | CHANGE   | a231b10 | 7054be7   | 2025.04.17                    | 2025.06.06                    |
| petsc       | CHANGE   | ff9a7ec | 8cef30b   | 3.23.0.6.gd9d7fd11dca build 1 | 3.23.0.6.gd9d7fd11dca build 2 |
| libmesh     | CHANGE   | 982ea19 | a3176bb   | 2025.05.23 build 0            | 2025.05.23 build 1            |
| moose-dev   | CHANGE   | 92d3c2e | d851721   | 2025.05.23                    | 2025.06.06                    |

2025-06-09 22:45 UTC, lindsayad commented
Is someone looking into the torch header issue?

2025-06-09 23:26 UTC, lindsayad commented
I will look into the LOR test failures. Getting seg faults during simulation tear down out of the MFEM `MemoryManager` class
```
==66526== Invalid read of size 8
==66526==    at 0x9C07E00: std::_Hashtable<void const*, std::pair<void const* const, mfem::internal::Memory>, std::allocator<std::pair<void const* const, mfem::internal::Memory> >, std::__detail::_Select1st, std::equal_to<void const*>, std::hash<void const*>, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, std::__detail::_Prime_rehash_policy, std::__detail::_Hashtable_traits<false, false, true> >::find(void const* const&) (in /opt/mfem/lib/libmfem.so.4.8.1)
==66526==    by 0x9C016B8: mfem::MemoryManager::GetDevicePtr(void const*, unsigned long, bool) (in /opt/mfem/lib/libmfem.so.4.8.1)
==66526==    by 0x9CE195E: mfem::HypreParMatrix::Write(mfem::MemoryClass, bool, bool) (in /opt/mfem/lib/libmfem.so.4.8.1)
==66526==    by 0x9CE8594: mfem::HypreParMatrix::Destroy() (in /opt/mfem/lib/libmfem.so.4.8.1)
==66526==    by 0x9CE92E0: mfem::HypreAMS::~HypreAMS() (in /opt/mfem/lib/libmfem.so.4.8.1)
==66526==    by 0x9CE9498: mfem::HypreAMS::~HypreAMS() (in /opt/mfem/lib/libmfem.so.4.8.1)
==66526==    by 0xA5FAD03: mfem::LORSolver<mfem::HypreAMS>::~LORSolver() (in /opt/mfem/lib/libmfem.so.4.8.1)
==66526==    by 0xA5FAD48: mfem::LORSolver<mfem::HypreAMS>::~LORSolver() (in /opt/mfem/lib/libmfem.so.4.8.1)
==66526==    by 0x40655A: _M_release (shared_ptr_base.h:346)
==66526==    by 0x40655A: std::_Sp_counted_base<(__gnu_cxx::_Lock_policy)2>::_M_release() (shared_ptr_base.h:317)
==66526==    by 0x62D276C: ~__shared_count (shared_ptr_base.h:1071)
==66526==    by 0x62D276C: ~__shared_ptr (shared_ptr_base.h:1524)
==66526==    by 0x62D276C: ~shared_ptr (shared_ptr.h:175)
==66526==    by 0x62D276C: MFEMSolverBase::~MFEMSolverBase() (MFEMSolverBase.h:13)
==66526==    by 0x62D8163: ~MFEMHypreAMS (MFEMHypreAMS.h:10)
==66526==    by 0x62D8163: MFEMHypreAMS::~MFEMHypreAMS() (MFEMHypreAMS.h:10)
==66526==    by 0x4064B1: _M_release_last_use (shared_ptr_base.h:175)
==66526==    by 0x4064B1: std::_Sp_counted_base<(__gnu_cxx::_Lock_policy)2>::_M_release_last_use_cold() (shared_ptr_base.h:199)
==66526==  Address 0x18 is not stack'd, malloc'd or (recently) free'd
```
I'll be building MFEM with debugging tomorrow to dig into this more

2025-06-10 02:44 UTC, loganharbour commented
> Is someone looking into the torch header issue?

yeah

2025-06-10 13:56 UTC, loganharbour commented
> > Is someone looking into the torch header issue?
> 
> yeah

This _should_ be resolved. Failed to export `LIBTORCH_DIR` in the environment...

Building just this version now to re-test.

Added issue numbers to everything

2025-06-11 00:47 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/2937916/), step Versioner verify on 5ded131 wanted to post the following:

### Versioner templates

Found 16 templates, 0 failed


### Versioner influential files

Found 58 influential files, 17 changed, 0 added, 0 removed

| package     | status   | file                                      |
|-------------|----------|-------------------------------------------|
| mpi         | CHANGE   | apptainer/mpi.def                         |
| mpi         | CHANGE   | conda/mpi/meta.yaml                       |
| libmesh-vtk | CHANGE   | conda/libmesh-vtk/conda_build_config.yaml |
| libmesh-vtk | CHANGE   | conda/libmesh-vtk/meta.yaml               |
| peacock     | CHANGE   | conda/peacock/conda_build_config.yaml     |
| peacock     | CHANGE   | conda/peacock/meta.yaml                   |
| petsc       | CHANGE   | apptainer/petsc.def                       |
| petsc       | CHANGE   | conda/petsc/conda_build_config.yaml       |
| petsc       | CHANGE   | conda/petsc/meta.yaml                     |
| libmesh     | CHANGE   | apptainer/libmesh.def                     |
| libmesh     | CHANGE   | conda/libmesh/conda_build_config.yaml     |
| libmesh     | CHANGE   | conda/libmesh/meta.yaml                   |
| moose-dev   | CHANGE   | apptainer/files/moose-dev                 |
| moose-dev   | CHANGE   | apptainer/moose-dev.def                   |
| moose-dev   | CHANGE   | apptainer/remove_channels.def             |
| moose-dev   | CHANGE   | conda/moose-dev/conda_build_config.yaml   |
| moose-dev   | CHANGE   | conda/moose-dev/meta.yaml                 |

### Versioner versions

Found 10 packages, 6 changed, 0 failed

| package     | status   | hash    | to hash   | version                       | to version                    |
|-------------|----------|---------|-----------|-------------------------------|-------------------------------|
| mpi         | CHANGE   | a9161d1 | c149603   | 2025.04.17                    | 2025.06.10                    |
| libmesh-vtk | CHANGE   | 042bd0b | d544edd   | 9.4.2 build 2                 | 9.4.2 build 3                 |
| peacock     | CHANGE   | a231b10 | 7dcf797   | 2025.04.17                    | 2025.06.10                    |
| petsc       | CHANGE   | ff9a7ec | f4424a8   | 3.23.0.6.gd9d7fd11dca build 1 | 3.23.0.6.gd9d7fd11dca build 2 |
| libmesh     | CHANGE   | 982ea19 | afb297a   | 2025.05.23 build 0            | 2025.05.23 build 1            |
| moose-dev   | CHANGE   | 851e6ad | 8433794   | 2025.06.09                    | 2025.06.10                    |

2025-06-11 13:49 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/2939132/), step Versioner verify on 5b9afb1 wanted to post the following:

### Versioner templates

Found 16 templates, 0 failed


### Versioner influential files

Found 58 influential files, 17 changed, 0 added, 0 removed

| package     | status   | file                                      |
|-------------|----------|-------------------------------------------|
| mpi         | CHANGE   | apptainer/mpi.def                         |
| mpi         | CHANGE   | conda/mpi/meta.yaml                       |
| libmesh-vtk | CHANGE   | conda/libmesh-vtk/conda_build_config.yaml |
| libmesh-vtk | CHANGE   | conda/libmesh-vtk/meta.yaml               |
| peacock     | CHANGE   | conda/peacock/conda_build_config.yaml     |
| peacock     | CHANGE   | conda/peacock/meta.yaml                   |
| petsc       | CHANGE   | apptainer/petsc.def                       |
| petsc       | CHANGE   | conda/petsc/conda_build_config.yaml       |
| petsc       | CHANGE   | conda/petsc/meta.yaml                     |
| libmesh     | CHANGE   | apptainer/libmesh.def                     |
| libmesh     | CHANGE   | conda/libmesh/conda_build_config.yaml     |
| libmesh     | CHANGE   | conda/libmesh/meta.yaml                   |
| moose-dev   | CHANGE   | apptainer/files/moose-dev                 |
| moose-dev   | CHANGE   | apptainer/moose-dev.def                   |
| moose-dev   | CHANGE   | apptainer/remove_channels.def             |
| moose-dev   | CHANGE   | conda/moose-dev/conda_build_config.yaml   |
| moose-dev   | CHANGE   | conda/moose-dev/meta.yaml                 |

### Versioner versions

Found 10 packages, 6 changed, 0 failed

| package     | status   | hash    | to hash   | version                       | to version                    |
|-------------|----------|---------|-----------|-------------------------------|-------------------------------|
| mpi         | CHANGE   | a9161d1 | c149603   | 2025.04.17                    | 2025.06.10                    |
| libmesh-vtk | CHANGE   | 042bd0b | d544edd   | 9.4.2 build 2                 | 9.4.2 build 3                 |
| peacock     | CHANGE   | a231b10 | 7dcf797   | 2025.04.17                    | 2025.06.10                    |
| petsc       | CHANGE   | ff9a7ec | f4424a8   | 3.23.0.6.gd9d7fd11dca build 1 | 3.23.0.6.gd9d7fd11dca build 2 |
| libmesh     | CHANGE   | 982ea19 | afb297a   | 2025.05.23 build 0            | 2025.05.23 build 1            |
| moose-dev   | CHANGE   | 851e6ad | 5c1cdec   | 2025.06.09                    | 2025.06.10                    |

2025-06-11 14:10 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/2939253/), step Versioner verify on 9bd32dd wanted to post the following:

### Versioner templates

Found 14 templates, 0 failed


### Versioner influential files

Found 56 influential files, 19 changed, 0 added, 0 removed

| package     | status   | file                                      |
|-------------|----------|-------------------------------------------|
| tools       | CHANGE   | conda/tools/meta.yaml                     |
| mpi         | CHANGE   | apptainer/mpi.def                         |
| mpi         | CHANGE   | conda/mpi/meta.yaml                       |
| wasp        | CHANGE   | conda/wasp/meta.yaml                      |
| pprof       | CHANGE   | conda/pprof/meta.yaml                     |
| seacas      | CHANGE   | conda/seacas/meta.yaml                    |
| libmesh-vtk | CHANGE   | conda/libmesh-vtk/conda_build_config.yaml |
| libmesh-vtk | CHANGE   | conda/libmesh-vtk/meta.yaml               |
| petsc       | CHANGE   | apptainer/petsc.def                       |
| petsc       | CHANGE   | conda/petsc/conda_build_config.yaml       |
| petsc       | CHANGE   | conda/petsc/meta.yaml                     |
| libmesh     | CHANGE   | apptainer/libmesh.def                     |
| libmesh     | CHANGE   | conda/libmesh/conda_build_config.yaml     |
| libmesh     | CHANGE   | conda/libmesh/meta.yaml                   |
| moose-dev   | CHANGE   | apptainer/files/moose-dev                 |
| moose-dev   | CHANGE   | apptainer/moose-dev.def                   |
| moose-dev   | CHANGE   | apptainer/remove_channels.def             |
| moose-dev   | CHANGE   | conda/moose-dev/conda_build_config.yaml   |
| moose-dev   | CHANGE   | conda/moose-dev/meta.yaml                 |

### Versioner versions

Found 9 packages, 9 changed, 4 failed

| package     | status      | hash    | to hash   | version                       | to version                    |
|-------------|-------------|---------|-----------|-------------------------------|-------------------------------|
| tools       | FUTURE DATE | 827cc6f | 6751dcd   | 2025.04.17                    | 2025.06.12                    |
| mpi         | FUTURE DATE | a9161d1 | 97ccca3   | 2025.04.17                    | 2025.06.12                    |
| wasp        | CHANGE      | 43d14da | 3e37a23   | 2025.05.13 build 0            | 2025.05.13 build 1            |
| pprof       | FUTURE DATE | f8fd1e3 | 994f862   | 2025.04.17 build 0            | 2025.06.12                    |
| seacas      | CHANGE      | 5d0701b | 1278418   | 2025.02.27 build 1            | 2025.05.22 build 0            |
| libmesh-vtk | CHANGE      | 042bd0b | 6ea4f68   | 9.4.2 build 2                 | 9.4.2 build 3                 |
| petsc       | CHANGE      | ff9a7ec | 291b11c   | 3.23.0.6.gd9d7fd11dca build 1 | 3.23.0.6.gd9d7fd11dca build 2 |
| libmesh     | CHANGE      | 982ea19 | b2fd1f2   | 2025.05.23 build 0            | 2025.05.23 build 1            |
| moose-dev   | FUTURE DATE | 851e6ad | 005ea72   | 2025.06.09                    | 2025.06.12                    |

Verification failed.

2025-06-11 14:28 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/2939467/), step Versioner verify on 50fe978 wanted to post the following:

### Versioner templates

Found 14 templates, 0 failed


### Versioner influential files

Found 56 influential files, 19 changed, 0 added, 0 removed

| package     | status   | file                                      |
|-------------|----------|-------------------------------------------|
| tools       | CHANGE   | conda/tools/meta.yaml                     |
| mpi         | CHANGE   | apptainer/mpi.def                         |
| mpi         | CHANGE   | conda/mpi/meta.yaml                       |
| wasp        | CHANGE   | conda/wasp/meta.yaml                      |
| pprof       | CHANGE   | conda/pprof/meta.yaml                     |
| seacas      | CHANGE   | conda/seacas/meta.yaml                    |
| libmesh-vtk | CHANGE   | conda/libmesh-vtk/conda_build_config.yaml |
| libmesh-vtk | CHANGE   | conda/libmesh-vtk/meta.yaml               |
| petsc       | CHANGE   | apptainer/petsc.def                       |
| petsc       | CHANGE   | conda/petsc/conda_build_config.yaml       |
| petsc       | CHANGE   | conda/petsc/meta.yaml                     |
| libmesh     | CHANGE   | apptainer/libmesh.def                     |
| libmesh     | CHANGE   | conda/libmesh/conda_build_config.yaml     |
| libmesh     | CHANGE   | conda/libmesh/meta.yaml                   |
| moose-dev   | CHANGE   | apptainer/files/moose-dev                 |
| moose-dev   | CHANGE   | apptainer/moose-dev.def                   |
| moose-dev   | CHANGE   | apptainer/remove_channels.def             |
| moose-dev   | CHANGE   | conda/moose-dev/conda_build_config.yaml   |
| moose-dev   | CHANGE   | conda/moose-dev/meta.yaml                 |

### Versioner versions

Found 9 packages, 9 changed, 0 failed

| package     | status   | hash    | to hash   | version                       | to version                    |
|-------------|----------|---------|-----------|-------------------------------|-------------------------------|
| tools       | CHANGE   | 827cc6f | 67094bf   | 2025.04.17                    | 2025.06.11                    |
| mpi         | CHANGE   | a9161d1 | eac9df1   | 2025.04.17                    | 2025.06.11                    |
| wasp        | CHANGE   | 43d14da | 3e37a23   | 2025.05.13 build 0            | 2025.05.13 build 1            |
| pprof       | CHANGE   | f8fd1e3 | 00c4824   | 2025.04.17 build 0            | 2025.06.11                    |
| seacas      | CHANGE   | 5d0701b | 1278418   | 2025.02.27 build 1            | 2025.05.22 build 0            |
| libmesh-vtk | CHANGE   | 042bd0b | 0711c50   | 9.4.2 build 2                 | 9.4.2 build 3                 |
| petsc       | CHANGE   | ff9a7ec | 62455cf   | 3.23.0.6.gd9d7fd11dca build 1 | 3.23.0.6.gd9d7fd11dca build 2 |
| libmesh     | CHANGE   | 982ea19 | e649276   | 2025.05.23 build 0            | 2025.05.23 build 1            |
| moose-dev   | CHANGE   | 851e6ad | 5de85b2   | 2025.06.09                    | 2025.06.11                    |

2025-06-11 15:06 UTC, cticenhour requested changes
Conda changes look good. Also approve of the MooseDocs changes. Found an issue with a test spec requirement that should be corrected.

2025-06-11 15:06 UTC, cticenhour commented on test/tests/executioners/nl_divergence_tolerance/tests
> +    requirement = "The executioner system shall support the PETSc non-linear divergence tolerance."
```suggestion
    requirement = "The system shall support execution using the PETSc non-linear divergence tolerance."
```
Better SQA compliance.

2025-06-11 15:06 UTC, cticenhour commented on scripts/versioner.yaml
> -  peacock:
🥃 😢 RIP

2025-06-11 15:33 UTC, loganharbour commented
@lindsayad :(

2025-06-11 15:36 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/2939990/), step Versioner verify on 0e7d913 wanted to post the following:

### Versioner templates

Found 14 templates, 0 failed


### Versioner influential files

Found 56 influential files, 19 changed, 0 added, 0 removed

| package     | status   | file                                      |
|-------------|----------|-------------------------------------------|
| tools       | CHANGE   | conda/tools/meta.yaml                     |
| mpi         | CHANGE   | apptainer/mpi.def                         |
| mpi         | CHANGE   | conda/mpi/meta.yaml                       |
| wasp        | CHANGE   | conda/wasp/meta.yaml                      |
| pprof       | CHANGE   | conda/pprof/meta.yaml                     |
| seacas      | CHANGE   | conda/seacas/meta.yaml                    |
| libmesh-vtk | CHANGE   | conda/libmesh-vtk/conda_build_config.yaml |
| libmesh-vtk | CHANGE   | conda/libmesh-vtk/meta.yaml               |
| petsc       | CHANGE   | apptainer/petsc.def                       |
| petsc       | CHANGE   | conda/petsc/conda_build_config.yaml       |
| petsc       | CHANGE   | conda/petsc/meta.yaml                     |
| libmesh     | CHANGE   | apptainer/libmesh.def                     |
| libmesh     | CHANGE   | conda/libmesh/conda_build_config.yaml     |
| libmesh     | CHANGE   | conda/libmesh/meta.yaml                   |
| moose-dev   | CHANGE   | apptainer/files/moose-dev                 |
| moose-dev   | CHANGE   | apptainer/moose-dev.def                   |
| moose-dev   | CHANGE   | apptainer/remove_channels.def             |
| moose-dev   | CHANGE   | conda/moose-dev/conda_build_config.yaml   |
| moose-dev   | CHANGE   | conda/moose-dev/meta.yaml                 |

### Versioner versions

Found 9 packages, 9 changed, 0 failed

| package     | status   | hash    | to hash   | version                       | to version                    |
|-------------|----------|---------|-----------|-------------------------------|-------------------------------|
| tools       | CHANGE   | 827cc6f | 67094bf   | 2025.04.17                    | 2025.06.11                    |
| mpi         | CHANGE   | a9161d1 | eac9df1   | 2025.04.17                    | 2025.06.11                    |
| wasp        | CHANGE   | 43d14da | 3e37a23   | 2025.05.13 build 0            | 2025.05.13 build 1            |
| pprof       | CHANGE   | f8fd1e3 | 00c4824   | 2025.04.17 build 0            | 2025.06.11                    |
| seacas      | CHANGE   | 5d0701b | 1278418   | 2025.02.27 build 1            | 2025.05.22 build 0            |
| libmesh-vtk | CHANGE   | 042bd0b | 0711c50   | 9.4.2 build 2                 | 9.4.2 build 3                 |
| petsc       | CHANGE   | ff9a7ec | 62455cf   | 3.23.0.6.gd9d7fd11dca build 1 | 3.23.0.6.gd9d7fd11dca build 2 |
| libmesh     | CHANGE   | 982ea19 | e649276   | 2025.05.23 build 0            | 2025.05.23 build 1            |
| moose-dev   | CHANGE   | 851e6ad | a470351   | 2025.06.09                    | 2025.06.11                    |

2025-06-11 15:40 UTC, cticenhour approved these changes

2025-06-11 15:59 UTC, milljm commented on scripts/versioner.yaml
> -  peacock:
Donno, more like a party! 🎉

2025-06-11 18:34 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/2940709/), step Versioner verify on e474c12 wanted to post the following:

### Versioner templates

Found 14 templates, 0 failed


### Versioner influential files

Found 56 influential files, 20 changed, 0 added, 0 removed

| package     | status   | file                                      |
|-------------|----------|-------------------------------------------|
| tools       | CHANGE   | conda/tools/conda_build_config.yaml       |
| tools       | CHANGE   | conda/tools/meta.yaml                     |
| mpi         | CHANGE   | apptainer/mpi.def                         |
| mpi         | CHANGE   | conda/mpi/meta.yaml                       |
| wasp        | CHANGE   | conda/wasp/meta.yaml                      |
| pprof       | CHANGE   | conda/pprof/meta.yaml                     |
| seacas      | CHANGE   | conda/seacas/meta.yaml                    |
| libmesh-vtk | CHANGE   | conda/libmesh-vtk/conda_build_config.yaml |
| libmesh-vtk | CHANGE   | conda/libmesh-vtk/meta.yaml               |
| petsc       | CHANGE   | apptainer/petsc.def                       |
| petsc       | CHANGE   | conda/petsc/conda_build_config.yaml       |
| petsc       | CHANGE   | conda/petsc/meta.yaml                     |
| libmesh     | CHANGE   | apptainer/libmesh.def                     |
| libmesh     | CHANGE   | conda/libmesh/conda_build_config.yaml     |
| libmesh     | CHANGE   | conda/libmesh/meta.yaml                   |
| moose-dev   | CHANGE   | apptainer/files/moose-dev                 |
| moose-dev   | CHANGE   | apptainer/moose-dev.def                   |
| moose-dev   | CHANGE   | apptainer/remove_channels.def             |
| moose-dev   | CHANGE   | conda/moose-dev/conda_build_config.yaml   |
| moose-dev   | CHANGE   | conda/moose-dev/meta.yaml                 |

### Versioner versions

Found 9 packages, 9 changed, 0 failed

| package     | status   | hash    | to hash   | version                       | to version                    |
|-------------|----------|---------|-----------|-------------------------------|-------------------------------|
| tools       | CHANGE   | 827cc6f | 77ff014   | 2025.04.17                    | 2025.06.11                    |
| mpi         | CHANGE   | a9161d1 | eac9df1   | 2025.04.17                    | 2025.06.11                    |
| wasp        | CHANGE   | 43d14da | 3e37a23   | 2025.05.13 build 0            | 2025.05.13 build 1            |
| pprof       | CHANGE   | f8fd1e3 | 00c4824   | 2025.04.17 build 0            | 2025.06.11                    |
| seacas      | CHANGE   | 5d0701b | 1278418   | 2025.02.27 build 1            | 2025.05.22 build 0            |
| libmesh-vtk | CHANGE   | 042bd0b | 0711c50   | 9.4.2 build 2                 | 9.4.2 build 3                 |
| petsc       | CHANGE   | ff9a7ec | 62455cf   | 3.23.0.6.gd9d7fd11dca build 1 | 3.23.0.6.gd9d7fd11dca build 2 |
| libmesh     | CHANGE   | 982ea19 | e649276   | 2025.05.23 build 0            | 2025.05.23 build 1            |
| moose-dev   | CHANGE   | 851e6ad | aa1920f   | 2025.06.09                    | 2025.06.11                    |

2025-06-11 22:22 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/2941430/), step Versioner verify on 5f6fc04 wanted to post the following:

### Versioner templates

Found 14 templates, 0 failed


### Versioner influential files

Found 56 influential files, 20 changed, 0 added, 0 removed

| package     | status   | file                                      |
|-------------|----------|-------------------------------------------|
| tools       | CHANGE   | conda/tools/conda_build_config.yaml       |
| tools       | CHANGE   | conda/tools/meta.yaml                     |
| mpi         | CHANGE   | apptainer/mpi.def                         |
| mpi         | CHANGE   | conda/mpi/meta.yaml                       |
| wasp        | CHANGE   | conda/wasp/meta.yaml                      |
| pprof       | CHANGE   | conda/pprof/meta.yaml                     |
| seacas      | CHANGE   | conda/seacas/meta.yaml                    |
| libmesh-vtk | CHANGE   | conda/libmesh-vtk/conda_build_config.yaml |
| libmesh-vtk | CHANGE   | conda/libmesh-vtk/meta.yaml               |
| petsc       | CHANGE   | apptainer/petsc.def                       |
| petsc       | CHANGE   | conda/petsc/conda_build_config.yaml       |
| petsc       | CHANGE   | conda/petsc/meta.yaml                     |
| libmesh     | CHANGE   | apptainer/libmesh.def                     |
| libmesh     | CHANGE   | conda/libmesh/conda_build_config.yaml     |
| libmesh     | CHANGE   | conda/libmesh/meta.yaml                   |
| moose-dev   | CHANGE   | apptainer/files/moose-dev                 |
| moose-dev   | CHANGE   | apptainer/moose-dev.def                   |
| moose-dev   | CHANGE   | apptainer/remove_channels.def             |
| moose-dev   | CHANGE   | conda/moose-dev/conda_build_config.yaml   |
| moose-dev   | CHANGE   | conda/moose-dev/meta.yaml                 |

### Versioner versions

Found 9 packages, 9 changed, 0 failed

| package     | status   | hash    | to hash   | version                       | to version                    |
|-------------|----------|---------|-----------|-------------------------------|-------------------------------|
| tools       | CHANGE   | 827cc6f | 77ff014   | 2025.04.17                    | 2025.06.11                    |
| mpi         | CHANGE   | a9161d1 | eac9df1   | 2025.04.17                    | 2025.06.11                    |
| wasp        | CHANGE   | 43d14da | 3e37a23   | 2025.05.13 build 0            | 2025.05.13 build 1            |
| pprof       | CHANGE   | f8fd1e3 | 00c4824   | 2025.04.17 build 0            | 2025.06.11                    |
| seacas      | CHANGE   | 5d0701b | 1278418   | 2025.02.27 build 1            | 2025.05.22 build 0            |
| libmesh-vtk | CHANGE   | 042bd0b | 0711c50   | 9.4.2 build 2                 | 9.4.2 build 3                 |
| petsc       | CHANGE   | ff9a7ec | 62455cf   | 3.23.0.6.gd9d7fd11dca build 1 | 3.23.0.6.gd9d7fd11dca build 2 |
| libmesh     | CHANGE   | 982ea19 | e649276   | 2025.05.23 build 0            | 2025.05.23 build 1            |
| moose-dev   | CHANGE   | 851e6ad | 7b7ce3a   | 2025.06.09                    | 2025.06.11                    |

2025-06-12 14:53 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/2943848/), step Versioner verify on f62abdc wanted to post the following:

### Versioner templates

Found 14 templates, 0 failed


### Versioner influential files

Found 56 influential files, 20 changed, 0 added, 0 removed

| package     | status   | file                                      |
|-------------|----------|-------------------------------------------|
| tools       | CHANGE   | conda/tools/conda_build_config.yaml       |
| tools       | CHANGE   | conda/tools/meta.yaml                     |
| mpi         | CHANGE   | apptainer/mpi.def                         |
| mpi         | CHANGE   | conda/mpi/meta.yaml                       |
| wasp        | CHANGE   | conda/wasp/meta.yaml                      |
| pprof       | CHANGE   | conda/pprof/meta.yaml                     |
| seacas      | CHANGE   | conda/seacas/meta.yaml                    |
| libmesh-vtk | CHANGE   | conda/libmesh-vtk/conda_build_config.yaml |
| libmesh-vtk | CHANGE   | conda/libmesh-vtk/meta.yaml               |
| petsc       | CHANGE   | apptainer/petsc.def                       |
| petsc       | CHANGE   | conda/petsc/conda_build_config.yaml       |
| petsc       | CHANGE   | conda/petsc/meta.yaml                     |
| libmesh     | CHANGE   | apptainer/libmesh.def                     |
| libmesh     | CHANGE   | conda/libmesh/conda_build_config.yaml     |
| libmesh     | CHANGE   | conda/libmesh/meta.yaml                   |
| moose-dev   | CHANGE   | apptainer/files/moose-dev                 |
| moose-dev   | CHANGE   | apptainer/moose-dev.def                   |
| moose-dev   | CHANGE   | apptainer/remove_channels.def             |
| moose-dev   | CHANGE   | conda/moose-dev/conda_build_config.yaml   |
| moose-dev   | CHANGE   | conda/moose-dev/meta.yaml                 |

### Versioner versions

Found 9 packages, 9 changed, 0 failed

| package     | status   | hash    | to hash   | version                       | to version                    |
|-------------|----------|---------|-----------|-------------------------------|-------------------------------|
| tools       | CHANGE   | 827cc6f | 77ff014   | 2025.04.17                    | 2025.06.11                    |
| mpi         | CHANGE   | a9161d1 | eac9df1   | 2025.04.17                    | 2025.06.11                    |
| wasp        | CHANGE   | 43d14da | 3e37a23   | 2025.05.13 build 0            | 2025.05.13 build 1            |
| pprof       | CHANGE   | f8fd1e3 | 00c4824   | 2025.04.17 build 0            | 2025.06.11                    |
| seacas      | CHANGE   | 5d0701b | 1278418   | 2025.02.27 build 1            | 2025.05.22 build 0            |
| libmesh-vtk | CHANGE   | 042bd0b | 0711c50   | 9.4.2 build 2                 | 9.4.2 build 3                 |
| petsc       | CHANGE   | ff9a7ec | 62455cf   | 3.23.0.6.gd9d7fd11dca build 1 | 3.23.0.6.gd9d7fd11dca build 2 |
| libmesh     | CHANGE   | 982ea19 | e649276   | 2025.05.23 build 0            | 2025.05.23 build 1            |
| moose-dev   | CHANGE   | 851e6ad | e4fd990   | 2025.06.09                    | 2025.06.11                    |

2025-06-13 14:21 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/2948663/), step Clang format on 0e5c31b wanted to post the following:

Your code requires style changes.  

A patch was auto generated and copied [here](https://mooseframework.inl.gov/docs/PRs/28114/clang_format/style.patch)  
You can directly apply the patch by running, in the top level of your repository:

`curl -s https://mooseframework.inl.gov/docs/PRs/28114/clang_format/style.patch | git apply -v`  

Alternatively, with your repository up to date and in the top level of your repository:

`git clang-format 70c2594d65b70017873e06a3056c725196051dd2`

2025-06-13 14:21 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/2948663/), step Versioner verify on 0e5c31b wanted to post the following:

### Versioner templates

Found 14 templates, 0 failed


### Versioner influential files

Found 58 influential files, 20 changed, 2 added, 0 removed

| package     | status   | file                                      |
|-------------|----------|-------------------------------------------|
| tools       | CHANGE   | conda/tools/conda_build_config.yaml       |
| tools       | CHANGE   | conda/tools/meta.yaml                     |
| mpi         | CHANGE   | apptainer/mpi.def                         |
| mpi         | CHANGE   | conda/mpi/meta.yaml                       |
| wasp        | CHANGE   | conda/wasp/meta.yaml                      |
| pprof       | CHANGE   | conda/pprof/meta.yaml                     |
| seacas      | CHANGE   | conda/seacas/meta.yaml                    |
| libmesh-vtk | CHANGE   | conda/libmesh-vtk/conda_build_config.yaml |
| libmesh-vtk | CHANGE   | conda/libmesh-vtk/meta.yaml               |
| petsc       | CHANGE   | apptainer/petsc.def                       |
| petsc       | CHANGE   | conda/petsc/conda_build_config.yaml       |
| petsc       | CHANGE   | conda/petsc/meta.yaml                     |
| libmesh     | CHANGE   | apptainer/libmesh.def                     |
| libmesh     | CHANGE   | conda/libmesh/conda_build_config.yaml     |
| libmesh     | CHANGE   | conda/libmesh/meta.yaml                   |
| moose-dev   | CHANGE   | apptainer/files/moose-dev                 |
| moose-dev   | CHANGE   | apptainer/moose-dev.def                   |
| moose-dev   | CHANGE   | apptainer/remove_channels.def             |
| moose-dev   | CHANGE   | conda/moose-dev/conda_build_config.yaml   |
| moose-dev   | CHANGE   | conda/moose-dev/meta.yaml                 |
| moose-dev   | NEW      | scripts/update_and_rebuild_conduit.sh     |
| moose-dev   | NEW      | scripts/update_and_rebuild_mfem.sh        |

### Versioner versions

Found 9 packages, 9 changed, 0 failed

| package     | status   | hash    | to hash   | version                       | to version                    |
|-------------|----------|---------|-----------|-------------------------------|-------------------------------|
| tools       | CHANGE   | 827cc6f | 075abd0   | 2025.04.17                    | 2025.06.13                    |
| mpi         | CHANGE   | a9161d1 | fcdc117   | 2025.04.17                    | 2025.06.13                    |
| wasp        | CHANGE   | 43d14da | 3e37a23   | 2025.05.13 build 0            | 2025.05.13 build 1            |
| pprof       | CHANGE   | f8fd1e3 | 3d296db   | 2025.04.17 build 0            | 2025.06.13                    |
| seacas      | CHANGE   | 5d0701b | 1278418   | 2025.02.27 build 1            | 2025.05.22 build 0            |
| libmesh-vtk | CHANGE   | 042bd0b | 16265eb   | 9.4.2 build 2                 | 9.4.2 build 3                 |
| petsc       | CHANGE   | ff9a7ec | 9531950   | 3.23.0.6.gd9d7fd11dca build 1 | 3.23.0.6.gd9d7fd11dca build 2 |
| libmesh     | CHANGE   | 982ea19 | 44d69f1   | 2025.05.23 build 0            | 2025.05.23 build 1            |
| moose-dev   | CHANGE   | 851e6ad | 6416dfc   | 2025.06.09                    | 2025.06.13                    |

2025-06-13 15:27 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/2948931/), step Versioner verify on 2fd350f wanted to post the following:

### Versioner templates

Found 14 templates, 0 failed


### Versioner influential files

Found 58 influential files, 20 changed, 2 added, 0 removed

| package     | status   | file                                      |
|-------------|----------|-------------------------------------------|
| tools       | CHANGE   | conda/tools/conda_build_config.yaml       |
| tools       | CHANGE   | conda/tools/meta.yaml                     |
| mpi         | CHANGE   | apptainer/mpi.def                         |
| mpi         | CHANGE   | conda/mpi/meta.yaml                       |
| wasp        | CHANGE   | conda/wasp/meta.yaml                      |
| pprof       | CHANGE   | conda/pprof/meta.yaml                     |
| seacas      | CHANGE   | conda/seacas/meta.yaml                    |
| libmesh-vtk | CHANGE   | conda/libmesh-vtk/conda_build_config.yaml |
| libmesh-vtk | CHANGE   | conda/libmesh-vtk/meta.yaml               |
| petsc       | CHANGE   | apptainer/petsc.def                       |
| petsc       | CHANGE   | conda/petsc/conda_build_config.yaml       |
| petsc       | CHANGE   | conda/petsc/meta.yaml                     |
| libmesh     | CHANGE   | apptainer/libmesh.def                     |
| libmesh     | CHANGE   | conda/libmesh/conda_build_config.yaml     |
| libmesh     | CHANGE   | conda/libmesh/meta.yaml                   |
| moose-dev   | CHANGE   | apptainer/files/moose-dev                 |
| moose-dev   | CHANGE   | apptainer/moose-dev.def                   |
| moose-dev   | CHANGE   | apptainer/remove_channels.def             |
| moose-dev   | CHANGE   | conda/moose-dev/conda_build_config.yaml   |
| moose-dev   | CHANGE   | conda/moose-dev/meta.yaml                 |
| moose-dev   | NEW      | scripts/update_and_rebuild_conduit.sh     |
| moose-dev   | NEW      | scripts/update_and_rebuild_mfem.sh        |

### Versioner versions

Found 9 packages, 9 changed, 0 failed

| package     | status   | hash    | to hash   | version                       | to version                    |
|-------------|----------|---------|-----------|-------------------------------|-------------------------------|
| tools       | CHANGE   | 827cc6f | 075abd0   | 2025.04.17                    | 2025.06.13                    |
| mpi         | CHANGE   | a9161d1 | fcdc117   | 2025.04.17                    | 2025.06.13                    |
| wasp        | CHANGE   | 43d14da | 3e37a23   | 2025.05.13 build 0            | 2025.05.13 build 1            |
| pprof       | CHANGE   | f8fd1e3 | 3d296db   | 2025.04.17 build 0            | 2025.06.13                    |
| seacas      | CHANGE   | 5d0701b | 1278418   | 2025.02.27 build 1            | 2025.05.22 build 0            |
| libmesh-vtk | CHANGE   | 042bd0b | 16265eb   | 9.4.2 build 2                 | 9.4.2 build 3                 |
| petsc       | CHANGE   | ff9a7ec | 9531950   | 3.23.0.6.gd9d7fd11dca build 1 | 3.23.0.6.gd9d7fd11dca build 2 |
| libmesh     | CHANGE   | 982ea19 | 44d69f1   | 2025.05.23 build 0            | 2025.05.23 build 1            |
| moose-dev   | CHANGE   | 851e6ad | 6416dfc   | 2025.06.09                    | 2025.06.13                    |

2025-06-13 21:46 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/2949932/), step Versioner verify on 552c9ab wanted to post the following:

### Versioner templates

Found 14 templates, 0 failed


### Versioner influential files

Found 58 influential files, 20 changed, 2 added, 0 removed

| package     | status   | file                                      |
|-------------|----------|-------------------------------------------|
| tools       | CHANGE   | conda/tools/conda_build_config.yaml       |
| tools       | CHANGE   | conda/tools/meta.yaml                     |
| mpi         | CHANGE   | apptainer/mpi.def                         |
| mpi         | CHANGE   | conda/mpi/meta.yaml                       |
| wasp        | CHANGE   | conda/wasp/meta.yaml                      |
| pprof       | CHANGE   | conda/pprof/meta.yaml                     |
| seacas      | CHANGE   | conda/seacas/meta.yaml                    |
| libmesh-vtk | CHANGE   | conda/libmesh-vtk/conda_build_config.yaml |
| libmesh-vtk | CHANGE   | conda/libmesh-vtk/meta.yaml               |
| petsc       | CHANGE   | apptainer/petsc.def                       |
| petsc       | CHANGE   | conda/petsc/conda_build_config.yaml       |
| petsc       | CHANGE   | conda/petsc/meta.yaml                     |
| libmesh     | CHANGE   | apptainer/libmesh.def                     |
| libmesh     | CHANGE   | conda/libmesh/conda_build_config.yaml     |
| libmesh     | CHANGE   | conda/libmesh/meta.yaml                   |
| moose-dev   | CHANGE   | apptainer/files/moose-dev                 |
| moose-dev   | CHANGE   | apptainer/moose-dev.def                   |
| moose-dev   | CHANGE   | apptainer/remove_channels.def             |
| moose-dev   | CHANGE   | conda/moose-dev/conda_build_config.yaml   |
| moose-dev   | CHANGE   | conda/moose-dev/meta.yaml                 |
| moose-dev   | NEW      | scripts/update_and_rebuild_conduit.sh     |
| moose-dev   | NEW      | scripts/update_and_rebuild_mfem.sh        |

### Versioner versions

Found 9 packages, 9 changed, 0 failed

| package     | status   | hash    | to hash   | version                       | to version                    |
|-------------|----------|---------|-----------|-------------------------------|-------------------------------|
| tools       | CHANGE   | 827cc6f | 075abd0   | 2025.04.17                    | 2025.06.13                    |
| mpi         | CHANGE   | a9161d1 | fcdc117   | 2025.04.17                    | 2025.06.13                    |
| wasp        | CHANGE   | 43d14da | 3e37a23   | 2025.05.13 build 0            | 2025.05.13 build 1            |
| pprof       | CHANGE   | f8fd1e3 | 3d296db   | 2025.04.17 build 0            | 2025.06.13                    |
| seacas      | CHANGE   | 5d0701b | 1278418   | 2025.02.27 build 1            | 2025.05.22 build 0            |
| libmesh-vtk | CHANGE   | 042bd0b | 16265eb   | 9.4.2 build 2                 | 9.4.2 build 3                 |
| petsc       | CHANGE   | ff9a7ec | 9531950   | 3.23.0.6.gd9d7fd11dca build 1 | 3.23.0.6.gd9d7fd11dca build 2 |
| libmesh     | CHANGE   | 982ea19 | 44d69f1   | 2025.05.23 build 0            | 2025.05.23 build 1            |
| moose-dev   | CHANGE   | 851e6ad | 6416dfc   | 2025.06.09                    | 2025.06.13                    |

2025-06-14 18:06 UTC, loganharbour commented
Modules parallel failure is unrelated.

Libtorch CUDA recipe failure is related, but this recipe will be removed.

2025-06-14 18:16 UTC, merged