Add MCMC GP training
idaholab/moose pull request #28166
Opened 2024-07-17 20:11 UTC by xianjian-xie

closes #28103

2024-07-17 20:16 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/2334982/) on cdecc0e wanted to post the following:

Your code requires style changes.  

A patch was auto generated and copied [here](https://mooseframework.inl.gov/docs/PRs/28166/clang_format/style.patch)  
You can directly apply the patch by running, in the top level of your repository:

`curl -s https://mooseframework.inl.gov/docs/PRs/28166/clang_format/style.patch | git apply -v`  

Alternatively, with your repository up to date and in the top level of your repository:

`git clang-format 182f6e0bf02749ec553df32dda8e607a0cc589fc`

2024-07-23 19:50 UTC, somu15 requested changes
@xianjian-xie I made a first set of comments. Please address these. Let me know if you need help.

2024-07-23 19:50 UTC, somu15 commented on modules/stochastic_tools/include/utils/GaussianProcess.h
> +  struct Settings {
Please describe the different variables using comments (i.e., //)

2024-07-23 19:50 UTC, somu15 commented on modules/stochastic_tools/include/utils/GaussianProcess.h
> +  struct Initial {
Please describe the different variables using comments (i.e., //)

2024-07-23 19:50 UTC, somu15 commented on modules/stochastic_tools/include/utils/GaussianProcess.h
> +  struct Output {
Please describe the different variables using comments (i.e., //)

2024-07-23 19:50 UTC, somu15 commented on modules/stochastic_tools/include/utils/GaussianProcess.h
> +  struct SampleGResult {
Please describe the different variables using comments (i.e., //)

2024-07-23 19:50 UTC, somu15 commented on modules/stochastic_tools/include/utils/GaussianProcess.h
> +  struct SampleThetaResult {
Please describe the different variables using comments (i.e., //)

2024-07-23 19:50 UTC, somu15 commented on modules/stochastic_tools/include/utils/GaussianProcess.h
> +  struct InvDetResult {
Please describe the different variables using comments (i.e., //)

2024-07-23 19:50 UTC, somu15 commented on modules/stochastic_tools/include/utils/GaussianProcess.h
> +  struct LogLResult {
Please describe the different variables using comments (i.e., //)

2024-07-23 19:50 UTC, somu15 commented on modules/stochastic_tools/include/utils/GaussianProcess.h
> +  void logl(const RealEigenMatrix & out_vec, const RealEigenMatrix & x1, const RealEigenMatrix & x2, Real g, const RealEigenMatrix & theta,
Add description for this function. See below for example from one of my code files. You should do something similar.

/**
   * Compute the acquisition function values
   * @param acq The computed acquisition function values
   * @param gp_mean The provided GP mean values
   * @param gp_std The provided GP standard deviation values
   * @param test_inputs All the input values under which the GP has to be tested
   * @param train_inputs All the input values under which the GP has been trained
   * @param generic A generic parameter (can be output values under which the GP has been trained or threshold parameter under the U-Function etc.)
   */
  virtual void computeAcquisition(std::vector<Real> & acq,
                                  const std::vector<Real> & gp_mean,
                                  const std::vector<Real> & gp_std,
                                  const std::vector<std::vector<Real>> & test_inputs,
                                  const std::vector<std::vector<Real>> & train_inputs,
                                  const std::vector<Real> & generic) const = 0;

2024-07-23 19:50 UTC, somu15 commented on modules/stochastic_tools/include/utils/GaussianProcess.h
> +  void sample_g(const RealEigenMatrix & out_vec, const RealEigenMatrix & x1, const RealEigenMatrix & x2, Real g_t, const RealEigenMatrix theta,
Add description for this function. See the comment pertaining to the `logl` function above.

2024-07-23 19:50 UTC, somu15 commented on modules/stochastic_tools/include/utils/GaussianProcess.h
> +  void sample_theta(const RealEigenMatrix & out_vec, const RealEigenMatrix & x1, const RealEigenMatrix & x2, Real g, const RealEigenMatrix & theta_t,
Add description for this function. See the comment pertaining to the `logl` function above.

2024-07-23 19:50 UTC, somu15 commented on modules/stochastic_tools/include/utils/GaussianProcess.h
> +  void check_settings(Settings & settings);
Add description for this function. See the comment pertaining to the `logl` function above.

2024-07-23 19:50 UTC, somu15 commented on modules/stochastic_tools/include/utils/GaussianProcess.h
> +  void tuneHyperParamsMcmc(const RealEigenMatrix & training_params,
Add description for this function. See the comment pertaining to the `logl` function above.

2024-07-23 19:50 UTC, somu15 commented on modules/stochastic_tools/src/utils/GaussianProcess.C
> +    // tuneHyperParamsAdam(training_params, training_data, opts);
You must provide an option to either use Adam or MCMC. The default must me Adam. You need to add this option in the `GaussianProcessTrainer` class as a new tuning option and pass the updated tuning options to this class.

2024-07-23 20:01 UTC, grmnptr commented
I have one quick comment: we will need tests for the new code. Check the `tests` files on how to specify one. The `gold` folder contains the files that you can compare results with.

2025-01-09 14:08 UTC, GiudGiud commented
@xianjian-xie what's the status here? Do you have time to address the test failures?
There are in the "precheck recipe" and are fairly simple to address
```

ERROR: The following files do not contain a newline character before EOF:
	modules/navier_stokes/test/tests/finite_element/uq_paper/Navier_Stokes.i
	modules/stochastic_tools/test/tests/surrogates/gaussian_process/GP_squared_exponential_tuned_adam2.i
	modules/stochastic_tools/test/tests/surrogates/gaussian_process/GP_squared_exponential_tuned_adam3.i
	modules/stochastic_tools/test/tests/surrogates/gaussian_process/Navier_Stokes.i

Run the "delete_trailing_whitespace.sh" script in your $MOOSE_DIR/scripts directory.

ERROR: The following files contain banned keywords (std::cout, std::cerr, sleep, print_trace):
	modules/stochastic_tools/src/surrogates/GaussianProcessSurrogate.C
	modules/stochastic_tools/src/surrogates/TwoLayerGaussianProcessSurrogate.C
	modules/stochastic_tools/src/trainers/TwoLayerGaussianProcessTrainer.C
	modules/stochastic_tools/src/utils/GaussianProcess.C
	modules/stochastic_tools/src/utils/Standardizer.C
	modules/stochastic_tools/src/utils/TwoLayerGaussianProcess.C
##########################################################################
```

2025-01-22 16:20 UTC, grmnptr commented
I am reviewing this right now. If the timeline changes we will take this over.

2025-01-23 01:20 UTC, grmnptr requested changes
Okay, I am more or less done with the MCMC parameter tuning part. Once my comments are addressed I will move on the the 2 layer GP part.

2025-01-23 01:20 UTC, grmnptr commented on modules/stochastic_tools/include/utils/GaussianProcess.h
> +  void sample_g(const RealEigenMatrix & out_vec, const RealEigenMatrix & x1, const RealEigenMatrix & x2, Real g_t, const RealEigenMatrix theta,
To me it feels like there is no difference in tuning the noise and the scale parameters besides computing the scale parameter. I think we could create one function that can do both of these.

2025-01-23 01:20 UTC, grmnptr commented on modules/stochastic_tools/src/utils/GaussianProcess.C
> +  std::vector<Real> theta1(_num_tunable, 0.0);
We have an automated way of dealing with this through the hyper parameter maps. The scaling parameter might not be at the same location all the time. So I'd have a loop checking for it.

2025-01-23 01:20 UTC, grmnptr commented on modules/stochastic_tools/src/utils/GaussianProcess.C
> +  }
This is a regular GP so no need for this. We could create an MCMC tuner that is general enough that could be reused here and the TwoLayerGP.

2025-01-23 01:29 UTC, grmnptr requested changes
Additionally, we will need tests (see `tests` files in the stochastic tools module) and documentation (see `*.md` files in the module).

2025-06-06 18:20 UTC, grmnptr requested changes
I am done wit a first round on the full PR. 
Besides the comment other critical things we are missing:
- tests for:
  -- training and evaluating in the same input file
  -- training and then reloading the surrogate in another input file
- documentation

For @somu15 , we will need a detialed review and testing from a technical side.

2025-06-06 18:20 UTC, grmnptr commented on modules/navier_stokes/test/tests/finite_element/uq_paper/Navier_Stokes.i
> +param1 = 1.0
Remove this input file, we are not going to use it for anything here. Still nice to have it in the history though.

2025-06-06 18:20 UTC, grmnptr commented on modules/stochastic_tools/include/utils/GaussianProcess.h
> +                       const unsigned int tune_method = 0,
This should be an enum:
https://www.w3schools.com/cpp/cpp_enum.asp

2025-06-06 18:20 UTC, grmnptr commented on modules/stochastic_tools/include/utils/GaussianProcess.h
> +   * @param scale Scale.
We usually used @param when we have a function, even though technicall you could use this, please follow Som's request here. The same applies to everything else in this file.

2025-06-06 18:20 UTC, grmnptr commented on modules/stochastic_tools/include/utils/GaussianProcess.h
> +  struct Settings {
We usually used @param when we have a function, even though technicall you could use this, please follow Som's request here.

2025-06-06 18:20 UTC, grmnptr commented on modules/stochastic_tools/include/utils/GaussianProcess.h
> +  void check_settings(Settings & settings);
Functions in MOOSE should have the cammel case format so instead of 
`check_settings`, please use `checkSettings`. this applies to this whole work, so please scane for similar cases.

2025-06-06 18:20 UTC, grmnptr commented on modules/stochastic_tools/src/utils/GaussianProcess.C
> +  std::cout << "tune method is: " << opts.tune_method << " num layers is: " << opts.num_layers << std::endl;
In MOOSE you aren ot allowed to use `std::cou/cerr` etc. If you really need this output you can use `Moose:out`.

2025-06-06 18:20 UTC, grmnptr commented on modules/stochastic_tools/src/utils/GaussianProcess.C
> +      throw std::invalid_argument("Unsupported tune_method: must be 0 (Adam) or 1 (MCMC)");
This will change when you switch to an enum/MooseEnum. Also, we don't use direct throw for error handling. Use `mooseError` instead.

2025-06-06 18:20 UTC, grmnptr commented on modules/stochastic_tools/src/utils/GaussianProcess.C
> +  std::vector<Real> theta1(_num_tunable, 0.0);
This is still a standing issue.

2025-06-06 18:20 UTC, grmnptr commented on modules/stochastic_tools/src/utils/GaussianProcess.C
> +  }
You will have to use clang format to be able to merge in MOOSE. Depending on what editor you use, you can get an automatic formatter. 
Otherwise, we will give you a git patch that you will ahve to apply during the review process when the tests get past the initial checks (like trailing white space).

2025-06-06 18:20 UTC, grmnptr commented on modules/stochastic_tools/src/utils/GaussianProcess.C
> +  logl_val = -0.5 * quadterm - 0.5 * ldet;
```suggestion
  const Real logl_val = -0.5 * quadterm - 0.5 * ldet;
```

2025-06-06 18:20 UTC, grmnptr commented on modules/stochastic_tools/src/utils/GaussianProcess.C
> +  Real quadterm = (diff.transpose() * Mi * diff)(0,0);
```suggestion
  const Real ldet = std::log(_K.determinant());

  const RealEigenMatrix diff = out_vec;
  const Real quadterm = (diff.transpose() * Mi * diff)(0,0);
```

2025-06-06 18:20 UTC, grmnptr commented on modules/stochastic_tools/src/utils/GaussianProcess.C
> +  RealEigenMatrix Mi = _K.llt().solve(RealEigenMatrix::Identity(_K.rows(), _K.cols()));
```suggestion
  const RealEigenMatrix Mi = _K.llt().solve(RealEigenMatrix::Identity(_K.rows(), _K.cols()));
```

2025-06-06 18:20 UTC, grmnptr commented on modules/stochastic_tools/include/utils/GaussianProcess.h
> +  void check_settings(Settings & settings);
Also this is not a check settings, more like an initialize settings function. There are no checks in this function.

2025-06-06 18:20 UTC, grmnptr commented on modules/stochastic_tools/include/utils/GaussianProcess.h
> +          LogLResult & result, bool scale=false);
We already have a function for this: getLoss(). If you need anything else from it, I would modify that function isntead of reimplementing the likelihood computation.

2025-06-06 18:20 UTC, grmnptr commented on modules/stochastic_tools/src/utils/GaussianProcess.C
> +      scale_val = -999;
Why -999?

2025-06-06 18:20 UTC, grmnptr commented on modules/stochastic_tools/src/utils/GaussianProcess.C
> +GaussianProcess::sampleNoise(const RealEigenMatrix & out_vec, const RealEigenMatrix & x1, Real noise_t, const RealEigenMatrix lengthscale,
```suggestion
GaussianProcess::sampleNoise(const RealEigenMatrix & out_vec, const RealEigenMatrix & x1, const Real noise_t, const RealEigenMatrix lengthscale, 
```

2025-06-06 18:20 UTC, grmnptr commented on modules/stochastic_tools/src/utils/GaussianProcess.C
> +  Real noise_star = Uniform::quantile(ru1, l * noise_t / u, u * noise_t / l);
```suggestion
  const Real alpha = settings.alpha.noise;
  const Real beta = settings.beta.noise;
  const Real l = settings.l;
  const Real u = settings.u;
  const Real ru1 = MooseRandom::rand();
  const Real ru = MooseRandom::rand();
  const Real noise_star = Uniform::quantile(ru1, l * noise_t / u, u * noise_t / l);
```

2025-06-06 18:20 UTC, grmnptr commented on modules/stochastic_tools/include/utils/GaussianProcess.h
> +  struct LogLResult {
I don't think we need structs for just two reals. we can just return pairs/tupples for these purposes. I don't think this will show up in the computational time results. I am expecting it to be dominated by the log likelihood computation.

2025-06-06 18:20 UTC, grmnptr commented on modules/stochastic_tools/include/utils/GaussianProcess.h
> +   * @param x1 Input data 1.
```suggestion
   * @param x1 Input data.
```

2025-06-06 18:20 UTC, grmnptr commented on modules/stochastic_tools/include/utils/GaussianProcess.h
> +   * @param x1 Input data 1.
We only have one set of input data in this function

2025-06-06 18:20 UTC, grmnptr commented on modules/stochastic_tools/include/trainers/GaussianProcessTrainer.h
> +
I think this might be a little awkward, with this we will have a regular AND a two-layered GP in the trainer all the time. Would be better to have only one. We should think about some abstraction here. We could inherit the two-layered GP from the regular GP and override some functions (like training etc).

2025-06-06 18:20 UTC, grmnptr commented on modules/stochastic_tools/include/utils/TwoLayerGaussianProcess.h
> + * Gaussian Processes. It can be used to standardize parameters, manipulate
```suggestion
 * deep Gaussian Processes. It can be used to standardize parameters, manipulate
```

2025-06-06 18:20 UTC, grmnptr commented on modules/stochastic_tools/include/utils/TwoLayerGaussianProcess.h
> +class TwoLayerGaussianProcess
I think this should inherit from the regular GP

2025-06-06 18:20 UTC, grmnptr commented on modules/stochastic_tools/include/utils/TwoLayerGaussianProcess.h
> +  };
```suggestion
  /**
   * Parameter setting for MCMC sampling.
   */
  struct Settings {
    /// Constant parameter from the paper. (I would add something more descriptive here)
    Real l;
    /// Constant parameter from the paper. (I would add something more descriptive here)
    Real u;
    
    /// Parameters used by the gamma distribution.
    struct {
      /// Noise level.
      Real noise;
      /// Lengthscale for inner layer.
      Real lengthscale_w;
      ///  Lengthscale for outer layer.
      Real lengthscale_y;
    } alpha, beta;
  };
```

2025-06-06 18:20 UTC, grmnptr commented on modules/stochastic_tools/include/utils/TwoLayerGaussianProcess.h
> +  };
Please follow this convention everywhere.

2025-06-06 18:20 UTC, grmnptr commented on modules/stochastic_tools/include/utils/TwoLayerGaussianProcess.h
> +
```suggestion
  void multiVariateNormalSampling(const RealEigenMatrix & mean,const RealEigenMatrix & cov, const unsigned int n_dim, const unsigned int n_draw, RealEigenMatrix & final_sample_matrix);

```

2025-06-06 18:20 UTC, grmnptr commented on modules/stochastic_tools/include/utils/TwoLayerGaussianProcess.h
> +               unsigned int i, Real alpha, Real beta, Real l, Real u, SampleLengthscaleResult & result, Real ll_prev);
```suggestion
  void sampleLengthscale(const RealEigenMatrix & out_vec, const RealEigenMatrix & x1, const RealEigenMatrix & x2, Real noise, const RealEigenMatrix & lengthscale_t,
               const unsigned int i, const Real alpha, const Real beta, const Real l, const Real u, SampleLengthscaleResult & result, const Real ll_prev);
```

2025-06-06 18:20 UTC, grmnptr commented on modules/stochastic_tools/include/utils/TwoLayerGaussianProcess.h
> +              Settings & settings, Real ll_prev, SampleNoiseResult & result);
```suggestion
  void sampleNoise(const RealEigenMatrix & out_vec, const RealEigenMatrix & x1, const RealEigenMatrix & x2, const Real g_t, const RealEigenMatrix lengthscale, 
              Settings & settings, const Real ll_prev, SampleNoiseResult & result);
```

2025-06-06 18:20 UTC, grmnptr commented on modules/stochastic_tools/include/utils/TwoLayerGaussianProcess.h
> +              SampleWResult & result, Real ll_prev, const RealEigenMatrix & prior_mean);
```suggestion
  void sampleW(const RealEigenMatrix & out_vec, RealEigenMatrix & w_t, const RealEigenMatrix & w1, const RealEigenMatrix & w2, 
              const RealEigenMatrix & x1, const RealEigenMatrix & x2, const Real noise, const RealEigenMatrix & lengthscale_y, const RealEigenMatrix & lengthscale_w,
              SampleWResult & result, const Real ll_prev, const RealEigenMatrix & prior_mean);
```

2025-06-06 18:20 UTC, grmnptr commented on modules/stochastic_tools/include/utils/TwoLayerGaussianProcess.h
> +                  const RealEigenMatrix &x2,
```suggestion
  void squared_exponential_covariance(const RealEigenMatrix & x1, 
                  const RealEigenMatrix & x2, 
```

2025-06-06 18:20 UTC, grmnptr commented on modules/stochastic_tools/include/utils/TwoLayerGaussianProcess.h
> +                  RealEigenMatrix &k);
```suggestion
                  const Real scale, 
                  const RealEigenMatrix &lengthscale, 
                  const Real noise, 
                  RealEigenMatrix &k);
```

2025-06-06 18:20 UTC, grmnptr commented on modules/stochastic_tools/include/utils/TwoLayerGaussianProcess.h
> +  void squared_exponential_covariance(const RealEigenMatrix &x1,
We already have this in 
https://mooseframework.inl.gov/source/covariances/SquaredExponentialCovariance.html

2025-06-06 18:20 UTC, grmnptr commented on modules/stochastic_tools/include/utils/TwoLayerGaussianProcess.h
> +                                   RealEigenMatrix & krig_mean, RealEigenMatrix & krig_sigma);
```suggestion
  void krig(const RealEigenMatrix & y, const RealEigenMatrix & x, const RealEigenMatrix & x_new,
                                   const RealEigenMatrix & lengthscale, const Real noise, const Real scale, const bool cal_sigma,
                                   const RealEigenMatrix & prior_mean, const RealEigenMatrix & prior_mean_new, 
                                   RealEigenMatrix & krig_mean, RealEigenMatrix & krig_sigma);
```

2025-06-06 18:20 UTC, grmnptr commented on modules/stochastic_tools/include/utils/TwoLayerGaussianProcess.h
> +  void check_settings(Settings & settings);
Check setting is not necessarily what is happening, more like init setting. But this can also be entirely replaced by a default constructor on the structure object.

2025-06-06 18:20 UTC, grmnptr commented on modules/stochastic_tools/include/utils/TwoLayerGaussianProcess.h
> +  RealEigenMatrix & getY() { return _y; }
```suggestion
  const RealEigenMatrix & getNoise() { return _noise; }
  const RealEigenMatrix & getLengthscaleY() { return _lengthscale_y; }
  const RealEigenMatrix & getLengthscaleW() { return _lengthscale_w; }
  const RealEigenMatrix & getScale() { return _scale; }
  const std::vector<RealEigenMatrix> & getW() { return _w; }
  const Real & getNmcmc() {return _nmcmc;}
  const RealEigenMatrix & getX() { return _x; }
  const RealEigenMatrix & getY() { return _y; }
```

2025-06-06 18:20 UTC, grmnptr commented on modules/stochastic_tools/include/utils/TwoLayerGaussianProcess.h
> +  RealEigenMatrix & getY() { return _y; }
If possible. These should be modified from inside of this class only.

2025-06-06 18:20 UTC, grmnptr commented on modules/stochastic_tools/include/utils/TwoLayerGaussianProcess.h
> +  RealEigenMatrix _y;
We will need documentation for these, To be honest, it would be nice if we could reuse the covariance system we already have. This looks like just a general squared exponential covariance. I wil have to read up on this though.

2025-06-06 18:20 UTC, grmnptr commented on modules/stochastic_tools/include/utils/TwoLayerGaussianProcess.h
> +// void dataLoad(std::istream & stream, Eigen::LLT<RealEigenMatrix> & decomp, void * context);
```suggestion
```

2025-06-06 18:20 UTC, grmnptr commented on modules/stochastic_tools/src/surrogates/GaussianProcessSurrogate.C
> +
```suggestion
```

2025-06-06 18:20 UTC, grmnptr commented on modules/stochastic_tools/src/surrogates/TwoLayerGaussianProcessSurrogate.C
> +  params.addClassDescription("Computes and evaluates Gaussian Process surrogate model.");
```suggestion
  params.addClassDescription("Computes and evaluates a deep Gaussian Process surrogate model.");
```

2025-06-06 18:20 UTC, grmnptr commented on modules/stochastic_tools/src/trainers/GaussianProcessTrainer.C
> +                  upper_bounds);
It would be nice if we could just have one, abstract representation here isntead of two GPs in the trainer.

2025-06-06 18:20 UTC, grmnptr commented on modules/stochastic_tools/src/utils/TwoLayerGaussianProcess.C
> +// }
```suggestion
```

2025-06-06 18:20 UTC, grmnptr commented on modules/stochastic_tools/src/utils/Standardizer.C
> +  // std::cout << "input array rowwise: " << input.array().rowwise() << std::endl;
```suggestion
```

2025-06-06 18:20 UTC, grmnptr commented on modules/stochastic_tools/src/utils/Standardizer.C
> +  // std::cout << "input array2: " << input.array() <<  "," << std::endl;
```suggestion
```

2025-06-06 18:20 UTC, grmnptr commented on modules/stochastic_tools/src/utils/GaussianProcess.C
> +  if (ll_prev == -999) {
Not a good practive to introduce a random code in another function and then compare to that in another.

2025-06-06 18:20 UTC, grmnptr commented on modules/stochastic_tools/src/surrogates/TwoLayerGaussianProcessSurrogate.C
> +    w_new = RealEigenMatrix::Zero(1, _training_params.cols());
@somu15 I will need you input specifically on this

2025-06-06 18:20 UTC, grmnptr commented on modules/stochastic_tools/src/trainers/GaussianProcessTrainer.C
> +  params.addParam<unsigned int>(
Here you can just use a MooseEnum, you can find many examples in the repo, also you have a lot of examples on how to convert it into a regular enum, if you want that conversion at all.

2025-06-06 18:20 UTC, grmnptr commented on modules/stochastic_tools/src/utils/GaussianProcess.C
> +  Real lpost_threshold = ll_prev + std::log(Gamma::pdf(noise_t - 1.5e-8, alpha, beta)) +
Why 1.5E-8?

2025-06-06 18:20 UTC, grmnptr commented on modules/stochastic_tools/src/utils/GaussianProcess.C
> +    if (ll_prev == -999) {
Avoid using this method that uses -999 set at one place and then assumes it is at others. Especially with a float number.

2025-06-06 18:20 UTC, grmnptr commented on modules/stochastic_tools/src/utils/GaussianProcess.C
> +    Real ru = MooseRandom::rand();
```suggestion
    const Real alpha = settings.alpha.noise;
    const Real beta = settings.beta.noise;
    const Real l = settings.l;
    const Real u = settings.u;
    const RealEigenMatrix lengthscale_star = lengthscale_t;
    const Real ru1 = MooseRandom::rand();
    const Real ru = MooseRandom::rand();
```

2025-06-06 18:20 UTC, grmnptr commented on modules/stochastic_tools/src/utils/GaussianProcess.C
> +}
This can be just replaced by a default constructor on settings

2025-06-06 18:20 UTC, grmnptr commented on modules/stochastic_tools/src/utils/TwoLayerGaussianProcess.C
> +  Real noise_star = Uniform::quantile(ru1, l * noise_t / u, u * noise_t / l);
```suggestion
  const Real alpha = settings.alpha.noise;
  const Real beta = settings.beta.noise;
  const Real l = settings.l;
  const Real u = settings.u;

  const Real ru1 = MooseRandom::rand();
  const Real ru = MooseRandom::rand();
  const Real noise_star = Uniform::quantile(ru1, l * noise_t / u, u * noise_t / l);
```

2025-06-06 18:20 UTC, grmnptr commented on modules/stochastic_tools/src/utils/TwoLayerGaussianProcess.C
> +      scale_val = NAN;
Nah, let's not use NAN on purpose in our C++. This needs a redesign.

2025-06-06 18:20 UTC, grmnptr commented on modules/stochastic_tools/src/utils/TwoLayerGaussianProcess.C
> +  Real ru = MooseRandom::rand();
```suggestion
  const Real ru1 = MooseRandom::rand();
  const Real ru = MooseRandom::rand();
```

2025-06-06 18:20 UTC, grmnptr commented on modules/stochastic_tools/src/utils/TwoLayerGaussianProcess.C
> +  Real new_val = ll_new + std::log(Gamma::pdf(lengthscale_star(0,i), alpha, beta));
```suggestion
  const Real new_val = ll_new + std::log(Gamma::pdf(lengthscale_star(0,i), alpha, beta));
```

2025-06-06 18:20 UTC, grmnptr commented on modules/stochastic_tools/src/utils/TwoLayerGaussianProcess.C
> +  scale_new = ll_result.scale;
```suggestion
  LogLResult ll_result;
  logl(out_vec, x1, x2, noise, lengthscale_star, ll_result, true, true);
  Real ll_new = ll_result.logl;
  Real scale_new = ll_result.scale;
```

2025-06-06 18:20 UTC, grmnptr commented on modules/stochastic_tools/src/utils/TwoLayerGaussianProcess.C
> +                            std::log(ru) - std::log(lengthscale_t(0,i)) + std::log(lengthscale_star(0,i));
```suggestion
  const Real lpost_threshold = ll_prev + std::log(Gamma::pdf(lengthscale_t(0,i), alpha, beta)) + 
                            std::log(ru) - std::log(lengthscale_t(0,i)) + std::log(lengthscale_star(0,i));
```

2025-06-06 18:20 UTC, grmnptr commented on modules/stochastic_tools/src/utils/TwoLayerGaussianProcess.C
> +  ll_new = ll_result.logl;
```suggestion
  LogLResult ll_result;
  logl(out_vec, x1, x2, noise_star, lengthscale, ll_result, true, false);
   Real ll_new = ll_result.logl;
```

2025-06-06 18:20 UTC, grmnptr commented on modules/stochastic_tools/src/utils/TwoLayerGaussianProcess.C
> +  RealEigenMatrix L = cho_decomp.matrixL();
```suggestion
  const RealEigenMatrix & L = cho_decomp.matrixL();
```

2025-06-06 18:20 UTC, grmnptr commented on modules/stochastic_tools/src/utils/TwoLayerGaussianProcess.C
> +TwoLayerGaussianProcess::sampleLengthscale(const RealEigenMatrix & out_vec, const RealEigenMatrix & x1, const RealEigenMatrix & x2, Real noise, const RealEigenMatrix & lengthscale_t,
Would need input on this @somu15

2025-06-06 18:20 UTC, grmnptr commented on modules/stochastic_tools/src/utils/TwoLayerGaussianProcess.C
> +  squared_exponential_covariance(x_new, x, scale, lengthscale, noise, C_cross);
Would be nicer to use already existing capability here from our covariance system.

2025-06-06 18:20 UTC, grmnptr commented on modules/stochastic_tools/src/utils/TwoLayerGaussianProcess.C
> +}
You could replace this with a default constructor.

2025-06-06 18:20 UTC, grmnptr commented on modules/stochastic_tools/src/utils/TwoLayerGaussianProcess.C
> +  unsigned int thin = 2;
These should be controlled from an input file I believe.

2025-06-06 18:20 UTC, grmnptr commented on modules/stochastic_tools/src/utils/TwoLayerGaussianProcess.C
> +// }
```suggestion
```

2026-04-09 06:08 UTC, closed without merging