Add support for file input of list of files to read in property read file
idaholab/moose pull request #28191
Opened 2024-07-22 16:46 UTC by GiudGiud

closes #28190

@caolwec

2024-07-22 16:51 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/2344000/) on ada3924 wanted to post the following:

Your code requires style changes.  

A patch was auto generated and copied [here](https://mooseframework.inl.gov/docs/PRs/28191/clang_format/style.patch)  
You can directly apply the patch by running, in the top level of your repository:

`curl -s https://mooseframework.inl.gov/docs/PRs/28191/clang_format/style.patch | git apply -v`  

Alternatively, with your repository up to date and in the top level of your repository:

`git clang-format 4d623c8daa651cad6ba44e7772083f5a92be1172`

2024-07-22 22:35 UTC, moosebuild commented
Job [Documentation](https://civet.inl.gov/job/2345007/) on c60cba3 wanted to post the following:

View the site [here](https://mooseframework.inl.gov/docs/PRs/28191/site)

This comment will be updated on new commits.

2024-07-22 23:20 UTC, moosebuild commented
Job [Coverage](https://civet.inl.gov/job/2345022/) on c60cba3 wanted to post the following:


## Framework coverage

<table>
  <thead>
    <tr>
      <th></th>
      <th>4d623c</th>
      <th colspan=4>#28191 c60cba</th>
    </tr>
    <tr>
      <th></th>
      <th>Total</th>
      <th>Total</th>
      <th>+/-</th>
      <th>New</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><b>Rate</b></td>
      <td>85.07%</td>
      <td>85.07%</td>
      <td>+0.00%</td>
      <td>100.00%</td>
    </tr>
    <tr>
      <td><b>Hits</b></td>
      <td>104697</td>
      <td>104715</td>
      <td>+18</td>
      <td>22</td>
    </tr>
    <tr>
      <td><b>Misses</b></td>
      <td>18374</td>
      <td>18376</td>
      <td>+2</td>
      <td>0</td>
    </tr>
  </tbody>
</table>

[Diff coverage report](https://mooseframework.inl.gov/docs/PRs/28191/coverage_diff/framework)

[Full coverage report](https://mooseframework.inl.gov/docs/PRs/28191/coverage/framework)


## Modules coverage

Coverage did not change

## Full coverage reports

<details>
<summary>Reports</summary>

- [`framework`](https://mooseframework.inl.gov/docs/PRs/28191/coverage/framework)
- [`chemical_reactions`](https://mooseframework.inl.gov/docs/PRs/28191/coverage/chemical_reactions)
- [`combined`](https://mooseframework.inl.gov/docs/PRs/28191/coverage/combined)
- [`contact`](https://mooseframework.inl.gov/docs/PRs/28191/coverage/contact)
- [`electromagnetics`](https://mooseframework.inl.gov/docs/PRs/28191/coverage/electromagnetics)
- [`external_petsc_solver`](https://mooseframework.inl.gov/docs/PRs/28191/coverage/external_petsc_solver)
- [`fluid_properties`](https://mooseframework.inl.gov/docs/PRs/28191/coverage/fluid_properties)
- [`fsi`](https://mooseframework.inl.gov/docs/PRs/28191/coverage/fsi)
- [`functional_expansion_tools`](https://mooseframework.inl.gov/docs/PRs/28191/coverage/functional_expansion_tools)
- [`geochemistry`](https://mooseframework.inl.gov/docs/PRs/28191/coverage/geochemistry)
- [`heat_transfer`](https://mooseframework.inl.gov/docs/PRs/28191/coverage/heat_transfer)
- [`level_set`](https://mooseframework.inl.gov/docs/PRs/28191/coverage/level_set)
- [`misc`](https://mooseframework.inl.gov/docs/PRs/28191/coverage/misc)
- [`navier_stokes`](https://mooseframework.inl.gov/docs/PRs/28191/coverage/navier_stokes)
- [`optimization`](https://mooseframework.inl.gov/docs/PRs/28191/coverage/optimization)
- [`peridynamics`](https://mooseframework.inl.gov/docs/PRs/28191/coverage/peridynamics)
- [`phase_field`](https://mooseframework.inl.gov/docs/PRs/28191/coverage/phase_field)
- [`porous_flow`](https://mooseframework.inl.gov/docs/PRs/28191/coverage/porous_flow)
- [`ray_tracing`](https://mooseframework.inl.gov/docs/PRs/28191/coverage/ray_tracing)
- [`rdg`](https://mooseframework.inl.gov/docs/PRs/28191/coverage/rdg)
- [`reactor`](https://mooseframework.inl.gov/docs/PRs/28191/coverage/reactor)
- [`richards`](https://mooseframework.inl.gov/docs/PRs/28191/coverage/richards)
- [`scalar_transport`](https://mooseframework.inl.gov/docs/PRs/28191/coverage/scalar_transport)
- [`solid_mechanics`](https://mooseframework.inl.gov/docs/PRs/28191/coverage/solid_mechanics)
- [`solid_properties`](https://mooseframework.inl.gov/docs/PRs/28191/coverage/solid_properties)
- [`stochastic_tools`](https://mooseframework.inl.gov/docs/PRs/28191/coverage/stochastic_tools)
- [`thermal_hydraulics`](https://mooseframework.inl.gov/docs/PRs/28191/coverage/thermal_hydraulics)
- [`xfem`](https://mooseframework.inl.gov/docs/PRs/28191/coverage/xfem)

</details>



This comment will be updated on new commits.

2024-07-24 22:32 UTC, pbehne requested changes
Nice feature.

You could also update PropertyReadFile.md to show an example of the new parameter. I don't think its required, though.

2024-07-24 22:32 UTC, pbehne commented on test/tests/userobjects/property_read_file/tests
> +  # See test/tests/functions/piecewise_constant_from_csv for additional tests
Thanks for adding this comment, I would be otherwise confused as to where the previous tests are.

2024-07-24 22:32 UTC, pbehne commented on test/tests/userobjects/property_read_file/tests
> +               "with the names of each files stored in a separate CSV file."
```suggestion
      detail = "with the name of each CSV data file to read stored in a separate "
                  "CSV file. At each user object execution, the next data file is read"
```
My attempt at making this more clear. Feel free to modify. The current verbage implies that more than one csv file is read for each execution, which is not the case.

2024-07-24 22:35 UTC, GiudGiud commented
thanks for the review
@lindsayad

2024-07-25 13:04 UTC, pbehne approved these changes

2024-07-31 17:14 UTC, lindsayad approved these changes

2024-07-31 17:29 UTC, merged