Improving documentation for acquired software related to CA2024-1659
idaholab/moose pull request #28271
Opened 2024-07-30 22:57 UTC by permcody

## Reason

## Design

## Impact

2024-07-31 00:57 UTC, moosebuild commented
Job [Documentation](https://civet.inl.gov/job/2359379/) on 312641b wanted to post the following:

View the site [here](https://mooseframework.inl.gov/docs/PRs/28271/site)

This comment will be updated on new commits.

2024-08-01 22:02 UTC, cticenhour requested changes
A few requested tweaks!

2024-08-01 22:02 UTC, cticenhour commented on framework/doc/content/sqa/framework_sll.md
> ++Testing:+ [!ac](PETSc) is able to utilize the MUMP package to solve linear system matrices in parallel.
```suggestion
+Testing:+ [!ac](PETSc) is able to utilize the MUMPS package to solve linear system matrices in parallel.
```

2024-08-01 22:02 UTC, cticenhour commented on framework/doc/content/sqa/framework_sll.md
> +This acceleration is suitable for certain small to moderatley sized linear systems that are not easily
```suggestion
This acceleration is suitable for certain small-to-moderately-sized linear systems that are not easily
```

2024-08-01 22:02 UTC, cticenhour commented on framework/doc/content/sqa/framework_sll.md
> +Functional tests in the framework [framework RTM](framework_rtm.md) and module RTMs. Breaking changes
```suggestion
Functional tests in the [framework RTM](framework_rtm.md) and module RTMs. Breaking changes
```

2024-08-05 22:24 UTC, permcody commented on framework/doc/content/sqa/framework_sll.md
> +[!ac](MOOSE) can optionally use preconditioners from the HYPRE library to assist with the solvers
The website has both usages. I don't think it's an acronym.

2024-08-05 23:09 UTC, cticenhour commented on framework/doc/content/sqa/framework_sll.md
> +[!ac](MOOSE) can optionally use preconditioners from the HYPRE library to assist with the solvers
Well that's not very consistent 😂 OK we can leave this as it is!

2024-08-05 23:13 UTC, cticenhour approved these changes

2024-08-05 23:13 UTC, cticenhour commented
Free to merge when passing!

2024-08-07 22:31 UTC, merged