Enable Quadratic Elements for Patterned Peripheral Modifiers
idaholab/moose pull request #28299
Opened 2024-08-02 22:01 UTC by miaoyinb

closes #28296

2024-08-02 22:05 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/2365207/) on d971c7f wanted to post the following:

Your code requires style changes.  

A patch was auto generated and copied [here](https://mooseframework.inl.gov/docs/PRs/28299/clang_format/style.patch)  
You can directly apply the patch by running, in the top level of your repository:

`curl -s https://mooseframework.inl.gov/docs/PRs/28299/clang_format/style.patch | git apply -v`  

Alternatively, with your repository up to date and in the top level of your repository:

`git clang-format 96e8a872107eff5d6a2d6c22eedc2679a4042b44`

2024-08-03 00:26 UTC, moosebuild commented
Job [Documentation](https://civet.inl.gov/job/2365271/) on 3b647e6 wanted to post the following:

View the site [here](https://mooseframework.inl.gov/docs/PRs/28299/site)

This comment will be updated on new commits.

2024-08-03 00:52 UTC, moosebuild commented
Job [Coverage](https://civet.inl.gov/job/2365317/) on 3b647e6 wanted to post the following:


## Framework coverage

Coverage did not change


## Modules coverage

### Reactor

<table>
  <thead>
    <tr>
      <th></th>
      <th>96e8a8</th>
      <th colspan=4>#28299 3b647e</th>
    </tr>
    <tr>
      <th></th>
      <th>Total</th>
      <th>Total</th>
      <th>+/-</th>
      <th>New</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><b>Rate</b></td>
      <td>93.70%</td>
      <td>93.71%</td>
      <td>+0.01%</td>
      <td>100.00%</td>
    </tr>
    <tr>
      <td><b>Hits</b></td>
      <td>7304</td>
      <td>7314</td>
      <td>+10</td>
      <td>11</td>
    </tr>
    <tr>
      <td><b>Misses</b></td>
      <td>491</td>
      <td>491</td>
      <td>-</td>
      <td>0</td>
    </tr>
  </tbody>
</table>

[Diff coverage report](https://mooseframework.inl.gov/docs/PRs/28299/coverage_diff/reactor)

[Full coverage report](https://mooseframework.inl.gov/docs/PRs/28299/coverage/reactor)

## Full coverage reports

<details>
<summary>Reports</summary>

- [`framework`](https://mooseframework.inl.gov/docs/PRs/28299/coverage/framework)
- [`chemical_reactions`](https://mooseframework.inl.gov/docs/PRs/28299/coverage/chemical_reactions)
- [`combined`](https://mooseframework.inl.gov/docs/PRs/28299/coverage/combined)
- [`contact`](https://mooseframework.inl.gov/docs/PRs/28299/coverage/contact)
- [`electromagnetics`](https://mooseframework.inl.gov/docs/PRs/28299/coverage/electromagnetics)
- [`external_petsc_solver`](https://mooseframework.inl.gov/docs/PRs/28299/coverage/external_petsc_solver)
- [`fluid_properties`](https://mooseframework.inl.gov/docs/PRs/28299/coverage/fluid_properties)
- [`fsi`](https://mooseframework.inl.gov/docs/PRs/28299/coverage/fsi)
- [`functional_expansion_tools`](https://mooseframework.inl.gov/docs/PRs/28299/coverage/functional_expansion_tools)
- [`geochemistry`](https://mooseframework.inl.gov/docs/PRs/28299/coverage/geochemistry)
- [`heat_transfer`](https://mooseframework.inl.gov/docs/PRs/28299/coverage/heat_transfer)
- [`level_set`](https://mooseframework.inl.gov/docs/PRs/28299/coverage/level_set)
- [`misc`](https://mooseframework.inl.gov/docs/PRs/28299/coverage/misc)
- [`navier_stokes`](https://mooseframework.inl.gov/docs/PRs/28299/coverage/navier_stokes)
- [`optimization`](https://mooseframework.inl.gov/docs/PRs/28299/coverage/optimization)
- [`peridynamics`](https://mooseframework.inl.gov/docs/PRs/28299/coverage/peridynamics)
- [`phase_field`](https://mooseframework.inl.gov/docs/PRs/28299/coverage/phase_field)
- [`porous_flow`](https://mooseframework.inl.gov/docs/PRs/28299/coverage/porous_flow)
- [`ray_tracing`](https://mooseframework.inl.gov/docs/PRs/28299/coverage/ray_tracing)
- [`rdg`](https://mooseframework.inl.gov/docs/PRs/28299/coverage/rdg)
- [`reactor`](https://mooseframework.inl.gov/docs/PRs/28299/coverage/reactor)
- [`richards`](https://mooseframework.inl.gov/docs/PRs/28299/coverage/richards)
- [`scalar_transport`](https://mooseframework.inl.gov/docs/PRs/28299/coverage/scalar_transport)
- [`solid_mechanics`](https://mooseframework.inl.gov/docs/PRs/28299/coverage/solid_mechanics)
- [`solid_properties`](https://mooseframework.inl.gov/docs/PRs/28299/coverage/solid_properties)
- [`stochastic_tools`](https://mooseframework.inl.gov/docs/PRs/28299/coverage/stochastic_tools)
- [`thermal_hydraulics`](https://mooseframework.inl.gov/docs/PRs/28299/coverage/thermal_hydraulics)
- [`xfem`](https://mooseframework.inl.gov/docs/PRs/28299/coverage/xfem)

</details>



This comment will be updated on new commits.

2024-08-03 02:54 UTC, moosebuild commented
Job [Public app tests](https://civet.inl.gov/job/2365307/) on 3b647e6 : invalidated by @miaoyinb

2024-08-07 01:11 UTC, GiudGiud requested changes
looks good just this one comment

2024-08-07 01:11 UTC, GiudGiud commented on modules/reactor/src/meshgenerators/PatternedPolygonPeripheralModifierBase.C
> +      mesh->all_second_order();
let's keep track of quad8 or 9, then use all_second_order for quad8 and all_complete_order (if it exists) for quad9

2024-08-07 13:09 UTC, GiudGiud commented
so in that last commit you re-gold the file that is added in the first commit. let's try to squash that change into the 1st one so we don't make the repo grow

2024-08-07 14:04 UTC, miaoyinb commented
Done

2024-08-07 14:12 UTC, GiudGiud approved these changes

2024-08-07 19:24 UTC, moosebuild commented
Job [Modules parallel](https://civet.inl.gov/job/2373583/) on 9f009b1 : invalidated by @miaoyinb

2024-08-07 19:29 UTC, miaoyinb commented
@GiudGiud Any idea why the module parallel test is cancelled by itself?

2024-08-07 20:50 UTC, GiudGiud commented
No idea. I think there are mass cancellations buttons in civet that are used during maintenance/ to free up resources

2024-08-07 20:50 UTC, merged