Modifying the implementation of explicit contact using updated central difference method
idaholab/moose pull request #28373
Opened 2024-08-14 21:37 UTC by TheGreatCid

This PR addresses the second half of #28008. Now that #28175 has been merged the updated formulation of [Heinstein 2000](https://www.sciencedirect.com/science/article/abs/pii/S0045782599003424) can be implemented. 

This is a node-face contact method for explicit dynamics. 
With this formulation the acceleration is calculated as follows,

$a_n=M^{-1}(F^{ext}-F^{int} + \lambda^n\G^T_n)$,

where $lambda$ is the contact force and $G_n$ is the contact surface Jacobian. 

The majority of the system for this contact model was implemented by @recuero #26073 however at the time there was no central difference time integrator that calculated acceleration directly from residual forces like that used by Heinstein. As such, some workarounds had to be made to implement this contact method. Naturally, this lead to some issues with the contact model. These(I hope) have been cleaned up with the updated model. 

The updated model now computes the contact force, $\lambda_n$ which is then fed into the acceleration calculation to enforce the contact constraint, rather than performing an override of the solution variable. 

Tests have been performed to compare against implicit mortar methods to validate. 
Here an extended version of the drop tests described in `moose/modules/contact/test/tests/explicit_dynamics/settlement.i`

I NEED TO FILL THIS IN 

And here is a video of 5-body contact. The middle block is an elastic-plastic material, while the rest are elastic with varying stiffness. The bottom plate is pushing the system up in the y-dir

https://github.com/user-attachments/assets/ba707ffb-c43f-4b5c-90b1-e4b908189a41

ection.

2024-08-15 01:49 UTC, moosebuild commented
Job [Documentation](https://civet.inl.gov/job/2386273/) on a300c16 wanted to post the following:

View the site [here](https://mooseframework.inl.gov/docs/PRs/28373/site)

This comment will be updated on new commits.

2024-08-15 14:59 UTC, TheGreatCid commented
Looks like I am getting exodiffs when running parallel. I'll start looking into that, but any suggestions on direction would be much appreciated.

2024-08-16 15:27 UTC, recuero commented
Looks good to me. The agreement between implicit and explicit is great. You could even add the implicit test to the repo so that it runs for a few representative time steps. Regardless, I think the comparison shows the velocity-based contact is working as intended for verification problems.

One additional analysis that can be done in the future to assess the energy behavior of this kinematic approach is to compare it with the penalty approach. For increasingly "optimal" values of the penalty approach, both methods should converge to (sort of) the same results. Since the penalty method is available in explicit, that would allow to look into more dynamic problems and also make sure penalty works well in this setting (which I don't believe I paid much attention to). 

Happy to see this explicit dynamics work moving forward.

2024-11-14 20:14 UTC, moosebuild commented
Job [Documentation](https://civet.inl.gov/job/2396953/), step Docs: sync website on 1a795ae wanted to post the following:

View the site [here](https://mooseframework.inl.gov/docs/PRs/28373/site)

This comment will be updated on new commits.

2025-01-02 20:12 UTC, TheGreatCid commented
@maxnezdyur @dschwen 

I'm going to look at this again next week. I was hesitant to merge because of inadequacies in modeling contact between two objects of significantly different masses. 
Most likely, this is an issue with the model itself rather than a coding issue.

2025-01-02 20:14 UTC, TheGreatCid commented
Also @maxnezdyur I know you were planning on looking at this. Have you managed to make any fixes?

2025-01-02 20:51 UTC, TheGreatCid commented
Right now, the contact surfaces are sticking to each other. I'm confused because I thought I fixed this previously. I'll need to figure out if I accidentally reverted a change.

2025-01-09 18:52 UTC, TheGreatCid commented
> Right now, the contact surfaces are sticking to each other. I'm confused because I thought I fixed this previously. I'll need to figure out if I accidentally reverted a change.

I was mistaken, I had look at the data wrong. It should be fine in this regard. I did not properly regold previously.

2025-01-09 21:13 UTC, maxnezdyur commented
@TheGreatCid 
Is there a version of `settlement.i` for implicit? So I have a reference to recreate the energy graphs?

2025-01-10 13:48 UTC, TheGreatCid commented
Here ya go
[settlement_implicit.zip](https://github.com/user-attachments/files/18377936/settlement_implicit.zip)

Also, from how the tests are failing, it's clear that I need to update this PR to match some of the more recent changes on "next"

2025-01-20 13:36 UTC, maxnezdyur commented
The PR is failing due to inconsistencies between Clang and parallel processing. I suspect the issue lies within the contact module rather than the changes in this PR. The failure occurs during exodiff comparisons at time steps 70, 80, and 90. The previous test interval was 50, which may have hidden the problem by not saving these time steps, while the PR changed the interval to 10.

2025-01-20 14:21 UTC, TheGreatCid commented
It is failing in parallel specifically, which is odd.
I can look into your interval theory. I just wont be able to get to it today.

2025-01-22 16:23 UTC, maxnezdyur requested changes
You can get rid of the extra debug information that I asked you to add. Look at `high_vel.i` we can't use the system matrix as the mass matrix. What happens is that all the other kernels will also contribute to this matrix. So we can create another matrix that will be our mass matrix. The other input files need the fix I showed in `high_vel.i`

2025-01-22 16:23 UTC, maxnezdyur commented on modules/contact/test/tests/explicit_dynamics/highvel.i
> +        matrix_tags = 'system'
I found the issue with the parallel inconsistency.
We should not be using the system matrix as the "mass" matrix.
Add 
```
[Problem]
  extra_tag_matrices = 'mass'
[]
```
to the top of the file then change 
`matrix_tags = "system"` to `matrix_tags = "mass"`.

2025-01-22 16:23 UTC, maxnezdyur commented on modules/contact/test/tests/explicit_dynamics/highvel.i
> +        matrix_tags = 'system'
repeat mass matrix here

2025-01-22 16:23 UTC, maxnezdyur commented on modules/contact/test/tests/explicit_dynamics/highvel.i
> +        matrix_tags = 'system'
repeat mass matrix here

2025-01-22 16:23 UTC, maxnezdyur commented on modules/contact/test/tests/explicit_dynamics/highvel.i
> +        mass_matrix_tag = system
repeat mass matrix here

2025-01-22 17:05 UTC, TheGreatCid commented on modules/contact/test/tests/explicit_dynamics/highvel.i
> +        matrix_tags = 'system'
Hm. We use the same method in the tests for DirectCentralDifference and it does not lead to errors in parallel.
Though I can still give this a shot

2025-01-22 20:45 UTC, moosebuild commented
Job [Coverage](https://civet.inl.gov/job/2647348/), step Generate coverage on 0f87380 wanted to post the following:


## Framework coverage

<table>
  <thead>
    <tr>
      <th></th>
      <th>bf7a39</th>
      <th colspan=4>#28373 0f8738</th>
    </tr>
    <tr>
      <th></th>
      <th>Total</th>
      <th>Total</th>
      <th>+/-</th>
      <th>New</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><b>Rate</b></td>
      <td>85.25%</td>
      <td>85.24%</td>
      <td>-0.00%</td>
      <td>-</td>
    </tr>
    <tr>
      <td><b>Hits</b></td>
      <td>108117</td>
      <td>108116</td>
      <td>-1</td>
      <td>0</td>
    </tr>
    <tr>
      <td><b>Misses</b></td>
      <td>18713</td>
      <td>18714</td>
      <td>+1</td>
      <td>0</td>
    </tr>
  </tbody>
</table>

[Diff coverage report](https://mooseframework.inl.gov/docs/PRs/28373/coverage_diff/framework)

[Full coverage report](https://mooseframework.inl.gov/docs/PRs/28373/coverage/framework)


## Modules coverage

### Contact

<table>
  <thead>
    <tr>
      <th></th>
      <th>bf7a39</th>
      <th colspan=4>#28373 0f8738</th>
    </tr>
    <tr>
      <th></th>
      <th>Total</th>
      <th>Total</th>
      <th>+/-</th>
      <th>New</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><b>Rate</b></td>
      <td>90.43%</td>
      <td>90.40%</td>
      <td>-0.03%</td>
      <td>100.00%</td>
    </tr>
    <tr>
      <td><b>Hits</b></td>
      <td>4922</td>
      <td>4907</td>
      <td>-15</td>
      <td>18</td>
    </tr>
    <tr>
      <td><b>Misses</b></td>
      <td>521</td>
      <td>521</td>
      <td>-</td>
      <td>0</td>
    </tr>
  </tbody>
</table>

[Diff coverage report](https://mooseframework.inl.gov/docs/PRs/28373/coverage_diff/contact)

[Full coverage report](https://mooseframework.inl.gov/docs/PRs/28373/coverage/contact)

## Full coverage reports

<details>
<summary>Reports</summary>

- [`framework`](https://mooseframework.inl.gov/docs/PRs/28373/coverage/framework)
- [`chemical_reactions`](https://mooseframework.inl.gov/docs/PRs/28373/coverage/chemical_reactions)
- [`combined`](https://mooseframework.inl.gov/docs/PRs/28373/coverage/combined)
- [`contact`](https://mooseframework.inl.gov/docs/PRs/28373/coverage/contact)
- [`electromagnetics`](https://mooseframework.inl.gov/docs/PRs/28373/coverage/electromagnetics)
- [`external_petsc_solver`](https://mooseframework.inl.gov/docs/PRs/28373/coverage/external_petsc_solver)
- [`fluid_properties`](https://mooseframework.inl.gov/docs/PRs/28373/coverage/fluid_properties)
- [`fsi`](https://mooseframework.inl.gov/docs/PRs/28373/coverage/fsi)
- [`functional_expansion_tools`](https://mooseframework.inl.gov/docs/PRs/28373/coverage/functional_expansion_tools)
- [`geochemistry`](https://mooseframework.inl.gov/docs/PRs/28373/coverage/geochemistry)
- [`heat_transfer`](https://mooseframework.inl.gov/docs/PRs/28373/coverage/heat_transfer)
- [`level_set`](https://mooseframework.inl.gov/docs/PRs/28373/coverage/level_set)
- [`misc`](https://mooseframework.inl.gov/docs/PRs/28373/coverage/misc)
- [`navier_stokes`](https://mooseframework.inl.gov/docs/PRs/28373/coverage/navier_stokes)
- [`optimization`](https://mooseframework.inl.gov/docs/PRs/28373/coverage/optimization)
- [`peridynamics`](https://mooseframework.inl.gov/docs/PRs/28373/coverage/peridynamics)
- [`phase_field`](https://mooseframework.inl.gov/docs/PRs/28373/coverage/phase_field)
- [`porous_flow`](https://mooseframework.inl.gov/docs/PRs/28373/coverage/porous_flow)
- [`ray_tracing`](https://mooseframework.inl.gov/docs/PRs/28373/coverage/ray_tracing)
- [`rdg`](https://mooseframework.inl.gov/docs/PRs/28373/coverage/rdg)
- [`reactor`](https://mooseframework.inl.gov/docs/PRs/28373/coverage/reactor)
- [`richards`](https://mooseframework.inl.gov/docs/PRs/28373/coverage/richards)
- [`scalar_transport`](https://mooseframework.inl.gov/docs/PRs/28373/coverage/scalar_transport)
- [`solid_mechanics`](https://mooseframework.inl.gov/docs/PRs/28373/coverage/solid_mechanics)
- [`solid_properties`](https://mooseframework.inl.gov/docs/PRs/28373/coverage/solid_properties)
- [`stochastic_tools`](https://mooseframework.inl.gov/docs/PRs/28373/coverage/stochastic_tools)
- [`thermal_hydraulics`](https://mooseframework.inl.gov/docs/PRs/28373/coverage/thermal_hydraulics)
- [`xfem`](https://mooseframework.inl.gov/docs/PRs/28373/coverage/xfem)

</details>



This comment will be updated on new commits.

2025-01-24 14:39 UTC, TheGreatCid commented
@recuero @dschwen 
I would really appreciate a code review, thank you!

2025-02-01 17:25 UTC, recuero reviewed
Looks good to me. I left some comments.

The problems I had as verification tests were relatively simple. It may make sense to use more complex ones, with other geometries and conditions. Also, if things are now working as expected, I would remove the comment and warning below:

https://github.com/idaholab/moose/blob/0f8738066bbb1ef8480ed138ab4613739815ccb9/modules/contact/src/actions/ExplicitDynamicsContactAction.C#L82

2025-02-01 17:25 UTC, recuero commented on modules/contact/test/tests/explicit_dynamics/tests
> -    cli_args = 'ExplicitDynamicsContact/my_contact/overwrite_current_solution=true Outputs/file_base=test_balance_overwrite_short_out Executioner/end_time=-0.009'
If you are removing these tests, remove gold and input files as well.

2025-02-04 19:50 UTC, TheGreatCid commented
Thank you for the review @recuero!

What other geometries would you be looking for, for additional tests?

2025-02-04 19:54 UTC, dschwen commented
Let's get this merged and have @maxnezdyur fix the issues Antonio pointed out. He's working on this anyways.

2025-02-04 19:55 UTC, dschwen commented on modules/contact/src/constraints/ExplicitDynamicsContactConstraint.C
> +  Real mass_q = diag(dof_x);
@maxnezdyur will address this in a follow on PR

2025-02-04 19:55 UTC, dschwen commented on modules/contact/test/tests/explicit_dynamics/highvel.i
>      []
@maxnezdyur will address this in a later follow on PR

2025-02-04 19:55 UTC, dschwen commented on modules/contact/test/tests/explicit_dynamics/tests
> -    cli_args = 'ExplicitDynamicsContact/my_contact/overwrite_current_solution=true Outputs/file_base=test_balance_overwrite_short_out Executioner/end_time=-0.009'
@maxnezdyur will address this in a follow on PR

2025-02-04 19:56 UTC, dschwen approved these changes
Thanks David, I vote we get this in as is. Mex is feverishly working on a follow on PR already.

2025-02-04 19:58 UTC, TheGreatCid commented
> Thanks David, I vote we get this in as is. Mex is feverishly working on a follow on PR already.

Ah good to hear! I'm sure he will iron out any issues.

2025-02-05 03:27 UTC, recuero approved these changes

2025-02-05 04:52 UTC, merged