Material inverse optimization using modular NEML2
idaholab/moose pull request #28440
Opened 2024-08-20 23:15 UTC by dewenyushu

Refs #26920

2024-08-21 03:06 UTC, hugary1995 requested changes
My only major comment is regarding setting parameters in the `ExecuteNEML2Model` UO. It feel there are separate features:
1. Collect MOOSE data to use as NEML2 model parameters.
2. Request parameter gradient for certain NEML2 model parameters.

Both features are somewhat tied together in your current implementation: When we set a parameter, we immediately set its `requires_grad` to true. We should probably allow the use case where a MOOSE property/variable is used as NEML2 parameter _without_ requesting the corresponding parameter gradient.

2024-08-21 03:10 UTC, hugary1995 commented
> My only major comment is regarding setting parameters in the `ExecuteNEML2Model` UO. I feel there are two separate features:
> 
> 1. Collect MOOSE data to use as NEML2 model parameters.
> 2. Request parameter gradient for certain NEML2 model parameters.
> 
> Both features are somewhat tied together in your current implementation: When we set a parameter, we immediately set its `requires_grad` to true. We should probably allow the use case where a MOOSE property/variable is used as NEML2 parameter _without_ requesting the corresponding parameter gradient.

ugh nevermind me... I just realized that indeed you treat these two things separately.

2024-08-21 04:14 UTC, moosebuild commented
Job [Documentation](https://civet.inl.gov/job/2399648/) on eb642c0 wanted to post the following:

View the site [here](https://mooseframework.inl.gov/docs/PRs/28440/site)

This comment will be updated on new commits.

2024-08-21 19:55 UTC, dewenyushu commented on modules/solid_mechanics/include/neml2/materials/NEML2ParameterDerivativeToMOOSEMaterialProperty.h
> +  const MaterialProperty<T> * _prop0;
Yeah I agree. Let me get this removed.

2024-08-21 19:55 UTC, dewenyushu commented on modules/optimization/include/vectorpostprocessors/AdjointStrainStressGradInnerProduct.h
> + */
Good catch!

2024-08-21 19:56 UTC, dewenyushu commented on modules/combined/test/tests/optimization/invOpt_elasticity/modular/forward_modular.i
Yeah I'll remove the legacy test case in my next commit

2024-08-21 21:10 UTC, dewenyushu commented on modules/combined/test/tests/optimization/invOpt_elasticity/modular/elasticity.i
Removed!

2024-08-21 21:12 UTC, dewenyushu commented on modules/solid_mechanics/include/neml2/userobjects/ExecuteNEML2Model.h
> +  virtual void postCompute();
Functions have been renamed

2024-08-21 21:15 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/2403019/) on dc85965 wanted to post the following:

Your code requires style changes.  

A patch was auto generated and copied [here](https://mooseframework.inl.gov/docs/PRs/28440/clang_format/style.patch)  
You can directly apply the patch by running, in the top level of your repository:

`curl -s https://mooseframework.inl.gov/docs/PRs/28440/clang_format/style.patch | git apply -v`  

Alternatively, with your repository up to date and in the top level of your repository:

`git clang-format 31532df1bd0265aef00ad80d6c0b7639bfee5a13`

2024-08-22 01:05 UTC, moosebuild commented
Job [Coverage](https://civet.inl.gov/job/2403111/) on 36fb7cd wanted to post the following:


## Framework coverage

<table>
  <thead>
    <tr>
      <th></th>
      <th>31532d</th>
      <th colspan=4>#28440 36fb7c</th>
    </tr>
    <tr>
      <th></th>
      <th>Total</th>
      <th>Total</th>
      <th>+/-</th>
      <th>New</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><b>Rate</b></td>
      <td>85.01%</td>
      <td>85.01%</td>
      <td>-0.00%</td>
      <td>74.19%</td>
    </tr>
    <tr>
      <td><b>Hits</b></td>
      <td>105075</td>
      <td>105096</td>
      <td>+21</td>
      <td>23</td>
    </tr>
    <tr>
      <td><b>Misses</b></td>
      <td>18527</td>
      <td>18537</td>
      <td>+10</td>
      <td>8</td>
    </tr>
  </tbody>
</table>

[Diff coverage report](https://mooseframework.inl.gov/docs/PRs/28440/coverage_diff/framework)

[Full coverage report](https://mooseframework.inl.gov/docs/PRs/28440/coverage/framework)


## Modules coverage

### Optimization

<table>
  <thead>
    <tr>
      <th></th>
      <th>31532d</th>
      <th colspan=4>#28440 36fb7c</th>
    </tr>
    <tr>
      <th></th>
      <th>Total</th>
      <th>Total</th>
      <th>+/-</th>
      <th>New</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><b>Rate</b></td>
      <td>88.63%</td>
      <td>88.67%</td>
      <td>+0.04%</td>
      <td>94.12%</td>
    </tr>
    <tr>
      <td><b>Hits</b></td>
      <td>1980</td>
      <td>1996</td>
      <td>+16</td>
      <td>16</td>
    </tr>
    <tr>
      <td><b>Misses</b></td>
      <td>254</td>
      <td>255</td>
      <td>+1</td>
      <td>1</td>
    </tr>
  </tbody>
</table>

[Diff coverage report](https://mooseframework.inl.gov/docs/PRs/28440/coverage_diff/optimization)

[Full coverage report](https://mooseframework.inl.gov/docs/PRs/28440/coverage/optimization)

### Solid mechanics

<table>
  <thead>
    <tr>
      <th></th>
      <th>31532d</th>
      <th colspan=4>#28440 36fb7c</th>
    </tr>
    <tr>
      <th></th>
      <th>Total</th>
      <th>Total</th>
      <th>+/-</th>
      <th>New</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><b>Rate</b></td>
      <td>84.92%</td>
      <td>84.91%</td>
      <td>-0.02%</td>
      <td>79.23%</td>
    </tr>
    <tr>
      <td><b>Hits</b></td>
      <td>28037</td>
      <td>28135</td>
      <td>+98</td>
      <td>103</td>
    </tr>
    <tr>
      <td><b>Misses</b></td>
      <td>4977</td>
      <td>5002</td>
      <td>+25</td>
      <td>27</td>
    </tr>
  </tbody>
</table>

[Diff coverage report](https://mooseframework.inl.gov/docs/PRs/28440/coverage_diff/solid_mechanics)

[Full coverage report](https://mooseframework.inl.gov/docs/PRs/28440/coverage/solid_mechanics)

## Full coverage reports

<details>
<summary>Reports</summary>

- [`framework`](https://mooseframework.inl.gov/docs/PRs/28440/coverage/framework)
- [`chemical_reactions`](https://mooseframework.inl.gov/docs/PRs/28440/coverage/chemical_reactions)
- [`combined`](https://mooseframework.inl.gov/docs/PRs/28440/coverage/combined)
- [`contact`](https://mooseframework.inl.gov/docs/PRs/28440/coverage/contact)
- [`electromagnetics`](https://mooseframework.inl.gov/docs/PRs/28440/coverage/electromagnetics)
- [`external_petsc_solver`](https://mooseframework.inl.gov/docs/PRs/28440/coverage/external_petsc_solver)
- [`fluid_properties`](https://mooseframework.inl.gov/docs/PRs/28440/coverage/fluid_properties)
- [`fsi`](https://mooseframework.inl.gov/docs/PRs/28440/coverage/fsi)
- [`functional_expansion_tools`](https://mooseframework.inl.gov/docs/PRs/28440/coverage/functional_expansion_tools)
- [`geochemistry`](https://mooseframework.inl.gov/docs/PRs/28440/coverage/geochemistry)
- [`heat_transfer`](https://mooseframework.inl.gov/docs/PRs/28440/coverage/heat_transfer)
- [`level_set`](https://mooseframework.inl.gov/docs/PRs/28440/coverage/level_set)
- [`misc`](https://mooseframework.inl.gov/docs/PRs/28440/coverage/misc)
- [`navier_stokes`](https://mooseframework.inl.gov/docs/PRs/28440/coverage/navier_stokes)
- [`optimization`](https://mooseframework.inl.gov/docs/PRs/28440/coverage/optimization)
- [`peridynamics`](https://mooseframework.inl.gov/docs/PRs/28440/coverage/peridynamics)
- [`phase_field`](https://mooseframework.inl.gov/docs/PRs/28440/coverage/phase_field)
- [`porous_flow`](https://mooseframework.inl.gov/docs/PRs/28440/coverage/porous_flow)
- [`ray_tracing`](https://mooseframework.inl.gov/docs/PRs/28440/coverage/ray_tracing)
- [`rdg`](https://mooseframework.inl.gov/docs/PRs/28440/coverage/rdg)
- [`reactor`](https://mooseframework.inl.gov/docs/PRs/28440/coverage/reactor)
- [`richards`](https://mooseframework.inl.gov/docs/PRs/28440/coverage/richards)
- [`scalar_transport`](https://mooseframework.inl.gov/docs/PRs/28440/coverage/scalar_transport)
- [`solid_mechanics`](https://mooseframework.inl.gov/docs/PRs/28440/coverage/solid_mechanics)
- [`solid_properties`](https://mooseframework.inl.gov/docs/PRs/28440/coverage/solid_properties)
- [`stochastic_tools`](https://mooseframework.inl.gov/docs/PRs/28440/coverage/stochastic_tools)
- [`thermal_hydraulics`](https://mooseframework.inl.gov/docs/PRs/28440/coverage/thermal_hydraulics)
- [`xfem`](https://mooseframework.inl.gov/docs/PRs/28440/coverage/xfem)

</details>

## Warnings

- `framework` new line coverage rate 74.19% is less than the suggested 90.0%
- `solid_mechanics` new line coverage rate 79.23% is less than the suggested 90.0%



This comment will be updated on new commits.

2024-08-26 16:06 UTC, dewenyushu commented
Hi @loganharbour , would you mind helping me investigate the issues with the documentation failing in this PR? - I'm wondering if it might be solely related to the code coverage being lower than the required threshold or if there might be other issues? Thanks!

2024-08-28 01:15 UTC, loganharbour commented
It's not related to the code coverage. The primary failure can be found here https://civet.inl.gov/job/2404936/, where the app failures are stemming from the moose documentation failure

2024-08-28 01:32 UTC, hugary1995 commented
It was quite difficult to sift -- it seems like there are 9 tests missing related issues.

2024-08-28 15:56 UTC, dewenyushu commented
> It's not related to the code coverage. The primary failure can be found here https://civet.inl.gov/job/2404936/, where the app failures are stemming from the moose documentation failure

Glad to know this is at least not related to code coverage!

2024-08-28 15:57 UTC, dewenyushu commented
> It was quite difficult to sift -- it seems like there are 9 tests missing related issues.

Oh that's a good point. However, I only added/changed 7 test cases in this PR. How come there are 9 missing?

2024-08-29 20:24 UTC, dewenyushu commented
What is going on with the json file schema differences here (https://civet.inl.gov/job/2418162/)? - I see those failing on my local machine using the latest moose/devel 

Maybe @loganharbour ?

2024-08-31 12:32 UTC, hugary1995 commented
The fix is on the way: https://github.com/idaholab/moose/pull/28490

2024-09-05 12:33 UTC, moosebuild commented
All [jobs](https://civet.inl.gov/event/195489/) on 71c9e95 : invalidated by @hugary1995

next has been unbroken :)

2024-09-05 14:17 UTC, hugary1995 approved these changes
New changes since last review also look good to me.

2024-09-05 14:17 UTC, moosebuild commented
Job [OpenMPI](https://civet.inl.gov/job/2423986/) on 71c9e95 : invalidated by @hugary1995

2024-09-05 14:40 UTC, dschwen commented on modules/solid_mechanics/src/neml2/materials/NEML2ParameterDerivativeToMOOSEMaterialProperty.C
> +      "neml2_parameter_derivative", "Return the derivative of neml2_variable with respect to this");
This should be `neml2_parameter`. with doc string "Parameter to take the derivative with respect to."

2024-09-05 14:45 UTC, dschwen commented on modules/solid_mechanics/src/neml2/materials/NEML2ParameterDerivativeToMOOSEMaterialProperty.C
> +      "neml2_parameter_derivative", "Return the derivative of neml2_variable with respect to this");
I take that back!

2024-09-05 14:45 UTC, hugary1995 commented on modules/solid_mechanics/src/neml2/materials/NEML2ParameterDerivativeToMOOSEMaterialProperty.C
> +                                        "Optional material property as the initial condition");
...and remove this.

2024-09-05 14:54 UTC, dschwen approved these changes
This looks fine. I might go back and factor out a common base class for parameter and variable user objects (then both could go into `gather_uos`). Also I need to do some profiling if the `std::vector<torch::Tensor>` approach is ok.

2024-09-05 15:29 UTC, dewenyushu commented on modules/solid_mechanics/src/neml2/materials/NEML2ParameterDerivativeToMOOSEMaterialProperty.C
> +                                        "Optional material property as the initial condition");
Oh yes nice catch!

2024-09-05 15:30 UTC, dewenyushu commented
> This looks fine. I might go back and factor out a common base class for parameter and variable user objects (then both could go into `gather_uos`). Also I need to do some profiling if the `std::vector<torch::Tensor>` approach is ok.

That would be awesome. Thank you!

2024-09-05 18:56 UTC, merged