MooseVariableBase - isLowerD - mooseError to mooseWarning
idaholab/moose pull request #28586
Opened 2024-09-09 17:49 UTC by jmeier

This minimal PR just changes this mooseError into an mooseWarning as discussed [here](https://github.com/idaholab/moose/issues/28204#issuecomment-2337917769):

https://github.com/idaholab/moose/blob/6271a40236eb166e603f72aadfe474b6c06786de/framework/src/variables/MooseVariableBase.C#L151-L156

refs #28204

This PR is only a temporary solution to allow models run in dbg-mode until the underlying problem is solved:
- Why does this check take place in the fisrt place? What does ist try to avoid?
- Why only in debug mode?
- The text of the error message does not seem to match the facts being checked (contrary to its name, isLowerD does not check whether a subdomain is ‘low-dimensional’)

2024-09-09 20:21 UTC, moosebuild commented
Job [Documentation](https://civet.inl.gov/job/2433916/) on febc9a8 wanted to post the following:

View the site [here](https://mooseframework.inl.gov/docs/PRs/28586/site)

This comment will be updated on new commits.

2024-09-09 21:00 UTC, moosebuild commented
Job [Coverage](https://civet.inl.gov/job/2433931/) on febc9a8 wanted to post the following:


## Framework coverage

Coverage did not change


## Modules coverage

Coverage did not change

## Full coverage reports

<details>
<summary>Reports</summary>

- [`framework`](https://mooseframework.inl.gov/docs/PRs/28586/coverage/framework)
- [`chemical_reactions`](https://mooseframework.inl.gov/docs/PRs/28586/coverage/chemical_reactions)
- [`combined`](https://mooseframework.inl.gov/docs/PRs/28586/coverage/combined)
- [`contact`](https://mooseframework.inl.gov/docs/PRs/28586/coverage/contact)
- [`electromagnetics`](https://mooseframework.inl.gov/docs/PRs/28586/coverage/electromagnetics)
- [`external_petsc_solver`](https://mooseframework.inl.gov/docs/PRs/28586/coverage/external_petsc_solver)
- [`fluid_properties`](https://mooseframework.inl.gov/docs/PRs/28586/coverage/fluid_properties)
- [`fsi`](https://mooseframework.inl.gov/docs/PRs/28586/coverage/fsi)
- [`functional_expansion_tools`](https://mooseframework.inl.gov/docs/PRs/28586/coverage/functional_expansion_tools)
- [`geochemistry`](https://mooseframework.inl.gov/docs/PRs/28586/coverage/geochemistry)
- [`heat_transfer`](https://mooseframework.inl.gov/docs/PRs/28586/coverage/heat_transfer)
- [`level_set`](https://mooseframework.inl.gov/docs/PRs/28586/coverage/level_set)
- [`misc`](https://mooseframework.inl.gov/docs/PRs/28586/coverage/misc)
- [`navier_stokes`](https://mooseframework.inl.gov/docs/PRs/28586/coverage/navier_stokes)
- [`optimization`](https://mooseframework.inl.gov/docs/PRs/28586/coverage/optimization)
- [`peridynamics`](https://mooseframework.inl.gov/docs/PRs/28586/coverage/peridynamics)
- [`phase_field`](https://mooseframework.inl.gov/docs/PRs/28586/coverage/phase_field)
- [`porous_flow`](https://mooseframework.inl.gov/docs/PRs/28586/coverage/porous_flow)
- [`ray_tracing`](https://mooseframework.inl.gov/docs/PRs/28586/coverage/ray_tracing)
- [`rdg`](https://mooseframework.inl.gov/docs/PRs/28586/coverage/rdg)
- [`reactor`](https://mooseframework.inl.gov/docs/PRs/28586/coverage/reactor)
- [`richards`](https://mooseframework.inl.gov/docs/PRs/28586/coverage/richards)
- [`scalar_transport`](https://mooseframework.inl.gov/docs/PRs/28586/coverage/scalar_transport)
- [`solid_mechanics`](https://mooseframework.inl.gov/docs/PRs/28586/coverage/solid_mechanics)
- [`solid_properties`](https://mooseframework.inl.gov/docs/PRs/28586/coverage/solid_properties)
- [`stochastic_tools`](https://mooseframework.inl.gov/docs/PRs/28586/coverage/stochastic_tools)
- [`thermal_hydraulics`](https://mooseframework.inl.gov/docs/PRs/28586/coverage/thermal_hydraulics)
- [`xfem`](https://mooseframework.inl.gov/docs/PRs/28586/coverage/xfem)

</details>



This comment will be updated on new commits.

2024-09-10 17:19 UTC, lindsayad requested changes
Per our discussion on the issue, I would prefer to keep this as an error and instead make `MooseMesh::isLowerD` better

2024-09-10 17:26 UTC, jmeier commented
> Per our discussion on the issue, I would prefer to keep this as an error and instead make MooseMesh::isLowerD better

Agreed. Therefore, I close the PR

2024-09-10 17:26 UTC, closed without merging