Add pressure skewness correction in RC interpolation
idaholab/moose pull request #28738
Opened 2024-10-01 03:18 UTC by GiudGiud

This reduces the magnitude of oscillations Mauricio found in a model with a skewed mesh

refs #16239

2024-10-01 06:33 UTC, moosebuild commented
Job [Documentation](https://civet.inl.gov/job/2476415/), step Docs: sync website on 051126d wanted to post the following:

View the site [here](https://mooseframework.inl.gov/docs/PRs/28738/site)

This comment will be updated on new commits.

2024-10-01 07:08 UTC, moosebuild commented
Job [Coverage](https://civet.inl.gov/job/2476430/), step Generate coverage on 051126d wanted to post the following:


## Framework coverage

<table>
  <thead>
    <tr>
      <th></th>
      <th>bfd459</th>
      <th colspan=4>#28738 051126</th>
    </tr>
    <tr>
      <th></th>
      <th>Total</th>
      <th>Total</th>
      <th>+/-</th>
      <th>New</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><b>Rate</b></td>
      <td>85.05%</td>
      <td>85.04%</td>
      <td>-0.01%</td>
      <td>-</td>
    </tr>
    <tr>
      <td><b>Hits</b></td>
      <td>106006</td>
      <td>105992</td>
      <td>-14</td>
      <td>0</td>
    </tr>
    <tr>
      <td><b>Misses</b></td>
      <td>18639</td>
      <td>18653</td>
      <td>+14</td>
      <td>0</td>
    </tr>
  </tbody>
</table>

[Diff coverage report](https://mooseframework.inl.gov/docs/PRs/28738/coverage_diff/framework)

[Full coverage report](https://mooseframework.inl.gov/docs/PRs/28738/coverage/framework)


## Modules coverage

### Navier stokes

<table>
  <thead>
    <tr>
      <th></th>
      <th>bfd459</th>
      <th colspan=4>#28738 051126</th>
    </tr>
    <tr>
      <th></th>
      <th>Total</th>
      <th>Total</th>
      <th>+/-</th>
      <th>New</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><b>Rate</b></td>
      <td>84.59%</td>
      <td>84.59%</td>
      <td>+0.00%</td>
      <td>100.00%</td>
    </tr>
    <tr>
      <td><b>Hits</b></td>
      <td>16765</td>
      <td>16766</td>
      <td>+1</td>
      <td>2</td>
    </tr>
    <tr>
      <td><b>Misses</b></td>
      <td>3055</td>
      <td>3055</td>
      <td>-</td>
      <td>0</td>
    </tr>
  </tbody>
</table>

[Diff coverage report](https://mooseframework.inl.gov/docs/PRs/28738/coverage_diff/navier_stokes)

[Full coverage report](https://mooseframework.inl.gov/docs/PRs/28738/coverage/navier_stokes)

## Full coverage reports

<details>
<summary>Reports</summary>

- [`framework`](https://mooseframework.inl.gov/docs/PRs/28738/coverage/framework)
- [`chemical_reactions`](https://mooseframework.inl.gov/docs/PRs/28738/coverage/chemical_reactions)
- [`combined`](https://mooseframework.inl.gov/docs/PRs/28738/coverage/combined)
- [`contact`](https://mooseframework.inl.gov/docs/PRs/28738/coverage/contact)
- [`electromagnetics`](https://mooseframework.inl.gov/docs/PRs/28738/coverage/electromagnetics)
- [`external_petsc_solver`](https://mooseframework.inl.gov/docs/PRs/28738/coverage/external_petsc_solver)
- [`fluid_properties`](https://mooseframework.inl.gov/docs/PRs/28738/coverage/fluid_properties)
- [`fsi`](https://mooseframework.inl.gov/docs/PRs/28738/coverage/fsi)
- [`functional_expansion_tools`](https://mooseframework.inl.gov/docs/PRs/28738/coverage/functional_expansion_tools)
- [`geochemistry`](https://mooseframework.inl.gov/docs/PRs/28738/coverage/geochemistry)
- [`heat_transfer`](https://mooseframework.inl.gov/docs/PRs/28738/coverage/heat_transfer)
- [`level_set`](https://mooseframework.inl.gov/docs/PRs/28738/coverage/level_set)
- [`misc`](https://mooseframework.inl.gov/docs/PRs/28738/coverage/misc)
- [`navier_stokes`](https://mooseframework.inl.gov/docs/PRs/28738/coverage/navier_stokes)
- [`optimization`](https://mooseframework.inl.gov/docs/PRs/28738/coverage/optimization)
- [`peridynamics`](https://mooseframework.inl.gov/docs/PRs/28738/coverage/peridynamics)
- [`phase_field`](https://mooseframework.inl.gov/docs/PRs/28738/coverage/phase_field)
- [`porous_flow`](https://mooseframework.inl.gov/docs/PRs/28738/coverage/porous_flow)
- [`ray_tracing`](https://mooseframework.inl.gov/docs/PRs/28738/coverage/ray_tracing)
- [`rdg`](https://mooseframework.inl.gov/docs/PRs/28738/coverage/rdg)
- [`reactor`](https://mooseframework.inl.gov/docs/PRs/28738/coverage/reactor)
- [`richards`](https://mooseframework.inl.gov/docs/PRs/28738/coverage/richards)
- [`scalar_transport`](https://mooseframework.inl.gov/docs/PRs/28738/coverage/scalar_transport)
- [`solid_mechanics`](https://mooseframework.inl.gov/docs/PRs/28738/coverage/solid_mechanics)
- [`solid_properties`](https://mooseframework.inl.gov/docs/PRs/28738/coverage/solid_properties)
- [`stochastic_tools`](https://mooseframework.inl.gov/docs/PRs/28738/coverage/stochastic_tools)
- [`thermal_hydraulics`](https://mooseframework.inl.gov/docs/PRs/28738/coverage/thermal_hydraulics)
- [`xfem`](https://mooseframework.inl.gov/docs/PRs/28738/coverage/xfem)

</details>



This comment will be updated on new commits.

2024-10-02 18:37 UTC, grmnptr approved these changes
Nice!

2024-10-02 18:38 UTC, grmnptr requested changes

2024-10-02 18:38 UTC, grmnptr commented on modules/navier_stokes/src/userobjects/INSFVRhieChowInterpolator.C
> +  const auto correct_skewness_p = velocitySkewCorrection(tid);
```suggestion
  const auto correct_skewness_p = pressureSkewCorrection(tid);
```

2024-10-02 18:48 UTC, GiudGiud commented on modules/navier_stokes/src/userobjects/INSFVRhieChowInterpolator.C
> +  const auto correct_skewness_p = velocitySkewCorrection(tid);
done

2024-10-02 18:51 UTC, grmnptr approved these changes

2024-10-02 21:59 UTC, merged

2024-10-02 22:00 UTC, GiudGiud commented
Thanks for the review!