[WIP] Add capability to use SIMPLE with fixed point iterations betweeen multiapps.
idaholab/moose pull request #28821
Opened 2024-10-09 22:48 UTC by grmnptr

Closes #28819

2024-11-13 01:57 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/2544335/), step Clang format on ee7d3d3 wanted to post the following:

Your code requires style changes.  

A patch was auto generated and copied [here](https://mooseframework.inl.gov/docs/PRs/28821/clang_format/style.patch)  
You can directly apply the patch by running, in the top level of your repository:

`curl -s https://mooseframework.inl.gov/docs/PRs/28821/clang_format/style.patch | git apply -v`  

Alternatively, with your repository up to date and in the top level of your repository:

`git clang-format d3e2afe6dfd70bc0c565cc1f48d6eb85bc94c0f0`

2024-11-13 19:03 UTC, moosebuild commented
Job [Documentation](https://civet.inl.gov/job/2546145/), step Docs: sync website on bb7afdb wanted to post the following:

View the site [here](https://mooseframework.inl.gov/docs/PRs/28821/site)

This comment will be updated on new commits.

2024-11-18 15:23 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/2553927/), step Clang format on 03abc2c wanted to post the following:

Your code requires style changes.  

A patch was auto generated and copied [here](https://mooseframework.inl.gov/docs/PRs/28821/clang_format/style.patch)  
You can directly apply the patch by running, in the top level of your repository:

`curl -s https://mooseframework.inl.gov/docs/PRs/28821/clang_format/style.patch | git apply -v`  

Alternatively, with your repository up to date and in the top level of your repository:

`git clang-format 37b999b88168e63b60d24edc34afeda04ee57b8a`

2024-11-19 23:28 UTC, lindsayad requested changes

2024-11-19 23:28 UTC, lindsayad commented on modules/navier_stokes/src/executioners/SIMPLE.C
This executioner sure looks a lot like `Steady` now. Is there any chance for code reuse if you inherit from it?

2024-11-19 23:54 UTC, grmnptr commented on modules/navier_stokes/src/executioners/SIMPLE.C
Yeah this duplication is a bummer. The way I see is is that the only difference is that Steady uses `FEProblemSolve` whereas SIMPLE uses `SIMPLESolve`. However, there is some entanglement by adding the parameters of the SolveObject to the Executioner and then reading those parameters in the SolveObject `MooseObject(ex.parameters())`.

Ideally, it would be cool if I could just pass a SolveObject to Steady in the input file. And if I am not mistaken, something similar would be the purpose of the `Executor` system at some point in the future.

However, at the moment depending on which SolveObject Steady uses, all of the input parameters are different. I don't see an immediate way to just using SolveObjects for plug-and-play in the Steady executioner. I can try to open a new PR, and split the SolveObjects into their own MOOSE systems and then just pass those to the executioners. That might be the cleanest. At the same time, that might be a fairly big change in MOOSE, especially that we might get the Executor system soon (even though the same was said 3 years ago when I joined).

Do you see other ways to use plug-and-play SolveObjects in Steady besides splitting it into a new system?

2024-11-19 23:58 UTC, lindsayad commented on modules/navier_stokes/src/executioners/SIMPLE.C
nope haha

2024-11-20 00:00 UTC, grmnptr commented on modules/navier_stokes/src/linearfvkernels/LinearFVVolumetricHeatTransfer.C
> +                                    : _temp_solid.getElemValue(*_current_elem_info, state);
Well, the reason why these are not functors is that the functor argument takes `Elem*` whereas the linearFV loops are using `ElemInfo*`. There is a map between the two so these could be functor calls right now. However, the `ElemArg` based functor will add an `Elem->ElemInfo` lookup which can be expensive. At the same time `ElemInfo` actually has all the dof indices of the variables. So in this case this query is just fetching a value from the `NumericVector` directly. If we can change the `ElemArg` to have `ElemInfo` instead, we could use the variables in linearFV with all functors with just a little more of an overhead due to the virtuall call. I might do that in a different PR.

2024-11-20 00:00 UTC, lindsayad commented on modules/navier_stokes/src/executioners/SIMPLE.C
what about a static templated method on `Steady`? You'd have to friend the method in the downstream class

2024-11-20 00:02 UTC, grmnptr commented on modules/navier_stokes/src/linearfvkernels/LinearFVVolumetricHeatTransfer.C
> +                                    : _temp_solid.getElemValue(*_current_elem_info, state);
The functor interfaces are there for the `MooseVariableLinearFV` but some might be a little expensive due to the additional lookups.

2024-11-20 00:05 UTC, grmnptr commented on framework/src/utils/MooseUtils.C
> +converged(const std::vector<std::pair<unsigned int, Real>> & its_and_residuals,
Nice catch! In simple, they are used in the print. They should be something like this ideally:
```
Iteration 12 Residual norm: 1e-99 Number of linear iterations: 42
```
Or something similar. I am going to add it to the SolveObject responsible for the `LinearSystems`.

2024-11-20 00:05 UTC, grmnptr commented on framework/include/problems/FEProblemBase.h
> +  virtual Real computeResidualL2Norm(LinearSystem & sys);
Yes, makes sense! Will change it in the next commit.

2024-11-20 00:07 UTC, grmnptr commented on framework/include/executioners/LinearFixedPointSolve.h
Yes, I will pull in the latest changes and check how much I can reuse from Guillaume's PR. I was not paying too close of an attention up until yesterday.

2024-11-20 00:09 UTC, grmnptr commented on modules/navier_stokes/src/executioners/SIMPLE.C
Aaa, that sounds interesting! I'll give it a shot!

2024-11-21 22:09 UTC, grmnptr commented on modules/navier_stokes/src/executioners/SIMPLE.C
I didn't even have to do that, turns out `SegregatedSolverBase` is not used anymore. So I can just create a `SteadyBase` class that shares the member variables and the `execute` function. From this we have `Steady`, `SIMPLENonlinearassembly` and `SIMPLE` which override the other functions like `init()`.

2024-11-21 22:13 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/2558746/), step Clang format on c0df71c wanted to post the following:

Your code requires style changes.  

A patch was auto generated and copied [here](https://mooseframework.inl.gov/docs/PRs/28821/clang_format/style.patch)  
You can directly apply the patch by running, in the top level of your repository:

`curl -s https://mooseframework.inl.gov/docs/PRs/28821/clang_format/style.patch | git apply -v`  

Alternatively, with your repository up to date and in the top level of your repository:

`git clang-format 8a5faa96a63686f29a61c4892f0f0683024be5ea`

2024-11-23 00:09 UTC, grmnptr commented on framework/doc/content/source/executioners/LinearFixedPointSteady.md
> +# LinearFixedPointSteady
Yes it could be done! Pushing soon

2024-11-23 00:26 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/2560386/), step Clang format on cdb9512 wanted to post the following:

Your code requires style changes.  

A patch was auto generated and copied [here](https://mooseframework.inl.gov/docs/PRs/28821/clang_format/style.patch)  
You can directly apply the patch by running, in the top level of your repository:

`curl -s https://mooseframework.inl.gov/docs/PRs/28821/clang_format/style.patch | git apply -v`  

Alternatively, with your repository up to date and in the top level of your repository:

`git clang-format 367b3c0949f003788c54df28295a52302e627de4`

2024-11-23 16:13 UTC, GiudGiud reviewed
is there a way, maybe using the Debug/show_execution_order, to check that all the expected execution phases (INITIAL, TIMEStEP_BEGIN, MULTIAPP_..., TIMESTEP_END, FINAL) are all present in the new executioners?

2024-11-23 23:36 UTC, grmnptr commented on test/tests/linearfvkernels/diffusion-reaction-advection/advection-diffusion-reaction-1d.i
> +  multi_system_fixed_point_convergence=linear
Well, for some of them I can probably remove it. But others will have to solve the same linear system many times to resolve the nonorthogonal correctors, 2term expansions etc.
I also like the `converged_on_max_its` option of the used CV object.

2024-11-24 00:13 UTC, grmnptr commented on framework/src/executioners/Steady.C
> +                 system->name());
Added!

2024-11-24 00:20 UTC, grmnptr commented on test/tests/transfers/multiapp_copy_transfer/linear_sys_to_aux/linear_sub.i
> +  multi_system_fixed_point=true
I could remove it from this input, other input might need a picard iteration on the nonorthogonal correctors/two-term bcs etc which are all treated explicitly now.

2024-11-24 00:23 UTC, grmnptr commented on test/tests/linearfvkernels/diffusion-reaction-advection/advection-diffusion-reaction-1d.i
> +  multi_system_fixed_point_convergence=linear
I did a screen for occasions where I can remove them, I had to keep them for the MMS cases though.

2024-11-24 16:12 UTC, GiudGiud commented on framework/src/executioners/FEProblemSolve.C
> +          // This is for postprocessing purposes in case none of the objects
so if it s for postprcessing purpose, does it need to be performed on every multi-system iteration or could it be performed at the end of the loop ?

2024-11-25 01:52 UTC, GiudGiud approved these changes

2024-11-25 02:02 UTC, GiudGiud commented
Approving for once test failures are resolving

2024-11-25 18:18 UTC, lindsayad requested changes

2024-11-25 18:18 UTC, lindsayad commented on framework/include/executioners/SteadyBase.h
> +InputParameters validParams();
Can delete

2024-11-25 18:18 UTC, lindsayad commented on framework/include/systems/SolverSystem.h
> +   * If the system has a kernel that corresponds to a time derivative
This doxygen string could be a little better. The current one makes me expect a simple boolean as the return type

2024-11-25 18:18 UTC, lindsayad commented on framework/src/executioners/FEProblemSolve.C
> +          const unsigned int linear_sys_number = sys->number() - _problem.numNonlinearSystems();
```suggestion
          const auto linear_sys_number = cast_int<unsigned int>(sys->number() - _problem.numNonlinearSystems());
```

2024-11-25 18:18 UTC, lindsayad commented on framework/src/systems/LinearSystem.C
> +  PetscLinearSolver<Real> & linear_solver =
```suggestion
  auto & linear_solver =
```

2024-11-26 00:19 UTC, lindsayad approved these changes

2024-11-26 01:02 UTC, grmnptr commented
The update fr subchannel is here:
https://github.inl.gov/ncrc/subchannel/pull/346

2024-11-26 01:41 UTC, moosebuild commented
Job [Coverage](https://civet.inl.gov/job/2562592/), step Generate coverage on 106cad9 wanted to post the following:


## Framework coverage

<table>
  <thead>
    <tr>
      <th></th>
      <th>9446d5</th>
      <th colspan=4>#28821 106cad</th>
    </tr>
    <tr>
      <th></th>
      <th>Total</th>
      <th>Total</th>
      <th>+/-</th>
      <th>New</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><b>Rate</b></td>
      <td>85.13%</td>
      <td>85.13%</td>
      <td>+0.00%</td>
      <td>80.15%</td>
    </tr>
    <tr>
      <td><b>Hits</b></td>
      <td>107452</td>
      <td>107508</td>
      <td>+56</td>
      <td>105</td>
    </tr>
    <tr>
      <td><b>Misses</b></td>
      <td>18767</td>
      <td>18772</td>
      <td>+5</td>
      <td>26</td>
    </tr>
  </tbody>
</table>

[Diff coverage report](https://mooseframework.inl.gov/docs/PRs/28821/coverage_diff/framework)

[Full coverage report](https://mooseframework.inl.gov/docs/PRs/28821/coverage/framework)


## Modules coverage

### Navier stokes

<table>
  <thead>
    <tr>
      <th></th>
      <th>9446d5</th>
      <th colspan=4>#28821 106cad</th>
    </tr>
    <tr>
      <th></th>
      <th>Total</th>
      <th>Total</th>
      <th>+/-</th>
      <th>New</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><b>Rate</b></td>
      <td>84.78%</td>
      <td>84.82%</td>
      <td>+0.04%</td>
      <td>91.21%</td>
    </tr>
    <tr>
      <td><b>Hits</b></td>
      <td>17384</td>
      <td>17333</td>
      <td>-51</td>
      <td>778</td>
    </tr>
    <tr>
      <td><b>Misses</b></td>
      <td>3120</td>
      <td>3101</td>
      <td>-19</td>
      <td>75</td>
    </tr>
  </tbody>
</table>

[Diff coverage report](https://mooseframework.inl.gov/docs/PRs/28821/coverage_diff/navier_stokes)

[Full coverage report](https://mooseframework.inl.gov/docs/PRs/28821/coverage/navier_stokes)

## Full coverage reports

<details>
<summary>Reports</summary>

- [`framework`](https://mooseframework.inl.gov/docs/PRs/28821/coverage/framework)
- [`chemical_reactions`](https://mooseframework.inl.gov/docs/PRs/28821/coverage/chemical_reactions)
- [`combined`](https://mooseframework.inl.gov/docs/PRs/28821/coverage/combined)
- [`contact`](https://mooseframework.inl.gov/docs/PRs/28821/coverage/contact)
- [`electromagnetics`](https://mooseframework.inl.gov/docs/PRs/28821/coverage/electromagnetics)
- [`external_petsc_solver`](https://mooseframework.inl.gov/docs/PRs/28821/coverage/external_petsc_solver)
- [`fluid_properties`](https://mooseframework.inl.gov/docs/PRs/28821/coverage/fluid_properties)
- [`fsi`](https://mooseframework.inl.gov/docs/PRs/28821/coverage/fsi)
- [`functional_expansion_tools`](https://mooseframework.inl.gov/docs/PRs/28821/coverage/functional_expansion_tools)
- [`geochemistry`](https://mooseframework.inl.gov/docs/PRs/28821/coverage/geochemistry)
- [`heat_transfer`](https://mooseframework.inl.gov/docs/PRs/28821/coverage/heat_transfer)
- [`level_set`](https://mooseframework.inl.gov/docs/PRs/28821/coverage/level_set)
- [`misc`](https://mooseframework.inl.gov/docs/PRs/28821/coverage/misc)
- [`navier_stokes`](https://mooseframework.inl.gov/docs/PRs/28821/coverage/navier_stokes)
- [`optimization`](https://mooseframework.inl.gov/docs/PRs/28821/coverage/optimization)
- [`peridynamics`](https://mooseframework.inl.gov/docs/PRs/28821/coverage/peridynamics)
- [`phase_field`](https://mooseframework.inl.gov/docs/PRs/28821/coverage/phase_field)
- [`porous_flow`](https://mooseframework.inl.gov/docs/PRs/28821/coverage/porous_flow)
- [`ray_tracing`](https://mooseframework.inl.gov/docs/PRs/28821/coverage/ray_tracing)
- [`rdg`](https://mooseframework.inl.gov/docs/PRs/28821/coverage/rdg)
- [`reactor`](https://mooseframework.inl.gov/docs/PRs/28821/coverage/reactor)
- [`richards`](https://mooseframework.inl.gov/docs/PRs/28821/coverage/richards)
- [`scalar_transport`](https://mooseframework.inl.gov/docs/PRs/28821/coverage/scalar_transport)
- [`solid_mechanics`](https://mooseframework.inl.gov/docs/PRs/28821/coverage/solid_mechanics)
- [`solid_properties`](https://mooseframework.inl.gov/docs/PRs/28821/coverage/solid_properties)
- [`stochastic_tools`](https://mooseframework.inl.gov/docs/PRs/28821/coverage/stochastic_tools)
- [`thermal_hydraulics`](https://mooseframework.inl.gov/docs/PRs/28821/coverage/thermal_hydraulics)
- [`xfem`](https://mooseframework.inl.gov/docs/PRs/28821/coverage/xfem)

</details>

## Warnings

- `framework` new line coverage rate 80.15% is less than the suggested 90.0%



This comment will be updated on new commits.

2024-11-26 15:49 UTC, grmnptr commented
Okay, the [timestep begin/end/multiapp] executes are hit in the FixedPointSolve. SIMPLE iteration hits Nonlinear for the problem. The nonlinear multiapp/transfer/control/UO execs are in the `computeLinearsystemTags`.

2024-11-26 15:50 UTC, merged