Least Squares Gradient Correction for Skewed Cells
idaholab/moose pull request #28839
Opened 2024-10-11 22:12 UTC by tanoret

Close #28838

2024-10-11 22:15 UTC, tanoret commented
PB-FHR results. Results with Green-Gauss on the let, results with the new least squares on the right. The velocity is supposed to be uniform in the shown section.

![image](https://github.com/user-attachments/assets/951439b1-0ffa-4d18-b57e-d40a0ac0d593)

2024-10-11 22:16 UTC, tanoret commented
@grmnptr @GiudGiud could you also take a look please?

2024-10-11 22:17 UTC, tanoret commented
Also, FYI, for the simple FHR test (707 cells) I did not see a deterioration in performance when comparing least squares vs green gauss

2024-10-12 01:36 UTC, moosebuild commented
Job [Documentation](https://civet.inl.gov/job/2492558/), step Docs: sync website on 9753aea wanted to post the following:

View the site [here](https://mooseframework.inl.gov/docs/PRs/28839/site)

This comment will be updated on new commits.

2024-10-13 19:40 UTC, moosebuild commented
Job [Coverage](https://civet.inl.gov/job/2494026/), step Generate coverage on 22ce2ba wanted to post the following:


## Framework coverage

<table>
  <thead>
    <tr>
      <th></th>
      <th>0a0f83</th>
      <th colspan=4>#28839 22ce2b</th>
    </tr>
    <tr>
      <th></th>
      <th>Total</th>
      <th>Total</th>
      <th>+/-</th>
      <th>New</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><b>Rate</b></td>
      <td>85.04%</td>
      <td>85.04%</td>
      <td>-0.01%</td>
      <td>93.96%</td>
    </tr>
    <tr>
      <td><b>Hits</b></td>
      <td>106135</td>
      <td>106203</td>
      <td>+68</td>
      <td>140</td>
    </tr>
    <tr>
      <td><b>Misses</b></td>
      <td>18668</td>
      <td>18689</td>
      <td>+21</td>
      <td>9</td>
    </tr>
  </tbody>
</table>

[Diff coverage report](https://mooseframework.inl.gov/docs/PRs/28839/coverage_diff/framework)

[Full coverage report](https://mooseframework.inl.gov/docs/PRs/28839/coverage/framework)


## Modules coverage

Coverage did not change

## Full coverage reports

<details>
<summary>Reports</summary>

- [`framework`](https://mooseframework.inl.gov/docs/PRs/28839/coverage/framework)
- [`chemical_reactions`](https://mooseframework.inl.gov/docs/PRs/28839/coverage/chemical_reactions)
- [`combined`](https://mooseframework.inl.gov/docs/PRs/28839/coverage/combined)
- [`contact`](https://mooseframework.inl.gov/docs/PRs/28839/coverage/contact)
- [`electromagnetics`](https://mooseframework.inl.gov/docs/PRs/28839/coverage/electromagnetics)
- [`external_petsc_solver`](https://mooseframework.inl.gov/docs/PRs/28839/coverage/external_petsc_solver)
- [`fluid_properties`](https://mooseframework.inl.gov/docs/PRs/28839/coverage/fluid_properties)
- [`fsi`](https://mooseframework.inl.gov/docs/PRs/28839/coverage/fsi)
- [`functional_expansion_tools`](https://mooseframework.inl.gov/docs/PRs/28839/coverage/functional_expansion_tools)
- [`geochemistry`](https://mooseframework.inl.gov/docs/PRs/28839/coverage/geochemistry)
- [`heat_transfer`](https://mooseframework.inl.gov/docs/PRs/28839/coverage/heat_transfer)
- [`level_set`](https://mooseframework.inl.gov/docs/PRs/28839/coverage/level_set)
- [`misc`](https://mooseframework.inl.gov/docs/PRs/28839/coverage/misc)
- [`navier_stokes`](https://mooseframework.inl.gov/docs/PRs/28839/coverage/navier_stokes)
- [`optimization`](https://mooseframework.inl.gov/docs/PRs/28839/coverage/optimization)
- [`peridynamics`](https://mooseframework.inl.gov/docs/PRs/28839/coverage/peridynamics)
- [`phase_field`](https://mooseframework.inl.gov/docs/PRs/28839/coverage/phase_field)
- [`porous_flow`](https://mooseframework.inl.gov/docs/PRs/28839/coverage/porous_flow)
- [`ray_tracing`](https://mooseframework.inl.gov/docs/PRs/28839/coverage/ray_tracing)
- [`rdg`](https://mooseframework.inl.gov/docs/PRs/28839/coverage/rdg)
- [`reactor`](https://mooseframework.inl.gov/docs/PRs/28839/coverage/reactor)
- [`richards`](https://mooseframework.inl.gov/docs/PRs/28839/coverage/richards)
- [`scalar_transport`](https://mooseframework.inl.gov/docs/PRs/28839/coverage/scalar_transport)
- [`solid_mechanics`](https://mooseframework.inl.gov/docs/PRs/28839/coverage/solid_mechanics)
- [`solid_properties`](https://mooseframework.inl.gov/docs/PRs/28839/coverage/solid_properties)
- [`stochastic_tools`](https://mooseframework.inl.gov/docs/PRs/28839/coverage/stochastic_tools)
- [`thermal_hydraulics`](https://mooseframework.inl.gov/docs/PRs/28839/coverage/thermal_hydraulics)
- [`xfem`](https://mooseframework.inl.gov/docs/PRs/28839/coverage/xfem)

</details>



This comment will be updated on new commits.

2024-10-14 20:13 UTC, GiudGiud requested changes
let's remove skewCorrectedLinearInterpolation
since it's no longer used nor wont be giving the same results as the new way

2024-10-14 21:43 UTC, GiudGiud commented on framework/include/utils/GreenGaussGradient.h
> +          delta_x_list.push_back(delta_x);
Use an upper bound then to reserve enough space

2024-10-14 23:36 UTC, tanoret commented on framework/include/utils/GreenGaussGradient.h
> +          *elem_arg.elem, mesh, action_functor, coord_type, rz_radial_coord);
We needed because they are requiredby Moose::FV::loopOverElemFaceInfo. I don't think we need to overlead this function just for this

2024-10-14 23:56 UTC, tanoret commented on framework/include/utils/GreenGaussGradient.h
> +        ATA.lu_solve(ATb, grad_ls);
No. Grad is a VectorValue and I need a DenseVector for the LU solve to work

2024-10-15 00:02 UTC, tanoret commented on framework/include/utils/GreenGaussGradient.h
> +        if (MooseUtils::absoluteFuzzyEqual(MetaPhysicL::raw_value(A(sys_dim - 1, sys_dim - 1)), 0))
This is the way in which absoluteFuzzyEqual worked for me. It was the same check that we had before for GG

2024-10-15 00:08 UTC, tanoret commented on framework/include/utils/GreenGaussGradient.h
> +            ATA(d1, d2) += dx_d1 / dx_norm * dx_d2 / dx_norm;
Thanks. Changed

2024-10-15 00:09 UTC, tanoret commented on framework/include/utils/GreenGaussGradient.h
> +          delta_x_list.push_back(delta_x);
Reserved memory for all these variables above

2024-10-15 15:06 UTC, GiudGiud approved these changes

2024-10-15 15:06 UTC, merged