Add hook for custom apptainer environment
idaholab/moose pull request #28845
Opened 2024-10-14 15:49 UTC by dschwen

## Reason
I'm missing my aliases in the apptainer shells.

## Design
Add an apptainer env script that sources `$HOME/.bashrc_apptainer` if it exists.

## Impact
Permit users to set up familiar environments in apptainer containers.

2024-10-14 16:27 UTC, milljm commented
I can address this in https://github.com/idaholab/moose/issues/28813

2024-10-14 16:28 UTC, loganharbour requested changes
Need to bump the whole conda stack due to changing mpi.def (which is versioned alongside moose-mpi)

2024-10-14 16:41 UTC, milljm commented
You try the following, see if alias work:

```bash
apptainer shell -B /path/to/your/.bash_apptainer:/init oras://theimage
```
I am finding many things don't work by simply sourcing the file, as you are suggesting to do.

If the above works, then this feature is already present. We just need to be more clear as to its availability.

2024-10-14 16:53 UTC, dschwen commented on apptainer/files/mpi/.singularity.d/env/02-bashrc-apptainer.sh
> +if [ -e $HOME/.bashrc_apptainer ]; then
x is not really necessary for `source`, but I can make that change

2024-10-14 16:55 UTC, dschwen commented
> Can you try the following, see if alias work:
> 
> ```shell
> apptainer shell -B /path/to/your/.bashrc_apptainer:/init_env oras://theimage
> ```

I'm using `vscode_container`, so unless that script passes through cli args, this script would need to be patched.

2024-10-14 17:58 UTC, dschwen commented
> I am finding many things don't work by simply sourcing the file, as you are suggesting to do.

Why wouldn't that work?!

2024-10-14 18:34 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/2494894/), step Conda build config check on 3b38a76 wanted to post the following:

A change of the following file(s) triggered this check:

  conda/peacock

The following file(s) are unchanged:

  conda/mpi/conda_build_config.yaml

The conda build config was not changed but one or more of its dependencies have changed

2024-10-14 18:46 UTC, milljm commented
> > I am finding many things don't work by simply sourcing the file, as you are suggesting to do.
> 
> Why wouldn't that work?!

Here has been my experience:

```bash
$ apptainer shell -B /home/milljm/.testing:/init_env oras://mooseharbor.hpc.inl.gov/moose-dev/moose-dev-mpich-x86_64:28a1964
INFO:    Using cached SIF image
moose-dev-mpich-x86_64:28a1964 [milljm@rod: ~ ]
$ cat /init_env 
function my_test(){
  echo 'hello from my_test function'
}
alias jas='ls -latrh'
```
So the file exists inside the container well enough. But...
```bash
moose-dev-mpich-x86_64:28a1964 [milljm@rod: ~ ]
$ my_test 
bash: my_test: command not found
moose-dev-mpich-x86_64:28a1964 [milljm@rod: ~ ]
$ jas
bash: jas: command not found
```
no dice. Not until I _source it again_
```bash
moose-dev-mpich-x86_64:28a1964 [milljm@rod: ~ ]
$ . /init_env 
moose-dev-mpich-x86_64:28a1964 [milljm@rod: ~ ]
$ my_test
hello from my_test function
moose-dev-mpich-x86_64:28a1964 [milljm@rod: ~ ]
$ jas
total 195M
-rw-------  1 milljm milljm  256 Sep 18  2013 .pulse-cookie
<trimmed>
```
All the while we do seem to be doing it:
https://github.com/idaholab/moose/blob/a35543bb275d046234e6544b1e4c11563b57c710/apptainer/mpi.def#L52-L55

Perhaps what you are doing may work. As I have been experiencing different results as to when this file gets sourced.

2024-10-14 18:59 UTC, milljm commented
I am trying what you are suggesting, and it won't work. My PR I am working on should fix this. But simply "sourcing" files doesn't seem to be enough. Don't ask me why, lol.

```bash
$ apptainer shell moose-dev-mpich-x86_64_28a1964.sifw 
moose-dev-mpich-x86_64:28a1964 [milljm@rod: /data/milljm ]
$ jas
bash: jas: command not found
moose-dev-mpich-x86_64:28a1964 [milljm@rod: /data/milljm ]
$ my_test
bash: my_test: command not found
moose-dev-mpich-x86_64:28a1964 [milljm@rod: /data/milljm ]
$ echo $MYVAR
foobar
moose-dev-mpich-x86_64:28a1964 [milljm@rod: /data/milljm ]
$ cat /.singularity.d/env/02-bashrc-apptainer.sh 
if [ -e $HOME/.bashrc_apptainer ]; then
    source $HOME/.bashrc_apptainer
fi
moose-dev-mpich-x86_64:28a1964 [milljm@rod: /data/milljm ]
$ cat $HOME/.bashrc_apptainer
function my_test(){
  echo 'hello from my_test function'
}
alias jas='ls -latrh'
export MYVAR=foobar
moose-dev-mpich-x86_64:28a1964 [milljm@rod: /data/milljm ]
$ . /.singularity.d/env/02-bashrc-apptainer.sh
moose-dev-mpich-x86_64:28a1964 [milljm@rod: /data/milljm ]
$ my_test
hello from my_test function
moose-dev-mpich-x86_64:28a1964 [milljm@rod: /data/milljm ]
$ jas
total 2.2G
<trimmed>
drwxr-xr-x  3 milljm milljm   60 Oct 14 12:56 ..
moose-dev-mpich-x86_64:28a1964 [milljm@rod: /data/milljm ]
$ 
```

2024-10-14 20:48 UTC, dschwen commented
Hm... I suppose that env stuff is not sourced in my current shell, and aliases are not inherited. But why is the bash not sourcing my `.bashrc` then?

2024-10-14 21:07 UTC, dschwen commented
This new approach should surely work. After all that is how the environment in the container gets set up.

2024-10-14 21:12 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/2495578/), step Conda build config check on e44885a wanted to post the following:

A change of the following file(s) triggered this check:

  conda/peacock

The following file(s) are unchanged:

  conda/mpi/conda_build_config.yaml

The conda build config was not changed but one or more of its dependencies have changed

2024-10-18 21:23 UTC, loganharbour commented
Isn't this due to the `--norc` option or whatever we pass bash?

2025-01-27 13:43 UTC, milljm commented
@dschwen  This should be working now, with #28813 in place. Please close at your convenience.

```bash
$ apptainer shell -B '/data/milljm:/home/milljm' oras://mooseharbor.hpc.inl.gov/moose-dev/moose-dev-mpich-x86_64:5e9be02
INFO:    Using cached SIF image

moose-dev-mpich-x86_64:5e9be02 [milljm@rod: ~ ]
$ cat .bashrc_apptainer 
function test_hello(){
   echo hello from inside the container
}

moose-dev-mpich-x86_64:5e9be02 [milljm@rod: ~ ]
$ test_hello
hello from inside the container

```

2025-06-05 19:52 UTC, closed without merging