Add a versatile nodeset generator
idaholab/moose pull request #28873
Opened 2024-10-17 14:50 UTC by GiudGiud

To get around difficulties reported in #28869 using the Gmsh reader.
This is not the best motivation, but I can see this being useful regardless

2024-10-17 23:49 UTC, moosebuild commented
Job [Documentation](https://civet.inl.gov/job/2502285/), step Docs: sync website on 2824a41 wanted to post the following:

View the site [here](https://mooseframework.inl.gov/docs/PRs/28873/site)

This comment will be updated on new commits.

2024-10-18 00:48 UTC, moosebuild commented
Job [Coverage](https://civet.inl.gov/job/2502300/), step Generate coverage on 2824a41 wanted to post the following:


## Framework coverage

<table>
  <thead>
    <tr>
      <th></th>
      <th>b3924e</th>
      <th colspan=4>#28873 2824a4</th>
    </tr>
    <tr>
      <th></th>
      <th>Total</th>
      <th>Total</th>
      <th>+/-</th>
      <th>New</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><b>Rate</b></td>
      <td>85.05%</td>
      <td>84.96%</td>
      <td>-0.08%</td>
      <td>15.72%</td>
    </tr>
    <tr>
      <td><b>Hits</b></td>
      <td>106298</td>
      <td>106322</td>
      <td>+24</td>
      <td>25</td>
    </tr>
    <tr>
      <td><b>Misses</b></td>
      <td>18691</td>
      <td>18820</td>
      <td>+129</td>
      <td>134</td>
    </tr>
  </tbody>
</table>

[Diff coverage report](https://mooseframework.inl.gov/docs/PRs/28873/coverage_diff/framework)

[Full coverage report](https://mooseframework.inl.gov/docs/PRs/28873/coverage/framework)


## Modules coverage

Coverage did not change

## Full coverage reports

<details>
<summary>Reports</summary>

- [`framework`](https://mooseframework.inl.gov/docs/PRs/28873/coverage/framework)
- [`chemical_reactions`](https://mooseframework.inl.gov/docs/PRs/28873/coverage/chemical_reactions)
- [`combined`](https://mooseframework.inl.gov/docs/PRs/28873/coverage/combined)
- [`contact`](https://mooseframework.inl.gov/docs/PRs/28873/coverage/contact)
- [`electromagnetics`](https://mooseframework.inl.gov/docs/PRs/28873/coverage/electromagnetics)
- [`external_petsc_solver`](https://mooseframework.inl.gov/docs/PRs/28873/coverage/external_petsc_solver)
- [`fluid_properties`](https://mooseframework.inl.gov/docs/PRs/28873/coverage/fluid_properties)
- [`fsi`](https://mooseframework.inl.gov/docs/PRs/28873/coverage/fsi)
- [`functional_expansion_tools`](https://mooseframework.inl.gov/docs/PRs/28873/coverage/functional_expansion_tools)
- [`geochemistry`](https://mooseframework.inl.gov/docs/PRs/28873/coverage/geochemistry)
- [`heat_transfer`](https://mooseframework.inl.gov/docs/PRs/28873/coverage/heat_transfer)
- [`level_set`](https://mooseframework.inl.gov/docs/PRs/28873/coverage/level_set)
- [`misc`](https://mooseframework.inl.gov/docs/PRs/28873/coverage/misc)
- [`navier_stokes`](https://mooseframework.inl.gov/docs/PRs/28873/coverage/navier_stokes)
- [`optimization`](https://mooseframework.inl.gov/docs/PRs/28873/coverage/optimization)
- [`peridynamics`](https://mooseframework.inl.gov/docs/PRs/28873/coverage/peridynamics)
- [`phase_field`](https://mooseframework.inl.gov/docs/PRs/28873/coverage/phase_field)
- [`porous_flow`](https://mooseframework.inl.gov/docs/PRs/28873/coverage/porous_flow)
- [`ray_tracing`](https://mooseframework.inl.gov/docs/PRs/28873/coverage/ray_tracing)
- [`rdg`](https://mooseframework.inl.gov/docs/PRs/28873/coverage/rdg)
- [`reactor`](https://mooseframework.inl.gov/docs/PRs/28873/coverage/reactor)
- [`richards`](https://mooseframework.inl.gov/docs/PRs/28873/coverage/richards)
- [`scalar_transport`](https://mooseframework.inl.gov/docs/PRs/28873/coverage/scalar_transport)
- [`solid_mechanics`](https://mooseframework.inl.gov/docs/PRs/28873/coverage/solid_mechanics)
- [`solid_properties`](https://mooseframework.inl.gov/docs/PRs/28873/coverage/solid_properties)
- [`stochastic_tools`](https://mooseframework.inl.gov/docs/PRs/28873/coverage/stochastic_tools)
- [`thermal_hydraulics`](https://mooseframework.inl.gov/docs/PRs/28873/coverage/thermal_hydraulics)
- [`xfem`](https://mooseframework.inl.gov/docs/PRs/28873/coverage/xfem)

</details>

## Warnings

- `framework` new line coverage rate 15.72% is less than the suggested 90.0%



This comment will be updated on new commits.

2024-10-23 07:44 UTC, GiudGiud commented
@pbehne would you have time to review? This is very close to what you did for sidesets

2024-10-24 17:37 UTC, pbehne commented
> @pbehne would you have time to review? This is very close to what you did for sidesets

I'll take a look in the coming week!

2024-10-29 14:30 UTC, pbehne commented
Starting on this now.

2024-10-30 15:07 UTC, pbehne requested changes

2024-10-30 22:42 UTC, GiudGiud commented on framework/include/meshgenerators/NodeSetsGeneratorBase.h
> +                                  const MeshBase & mesh) const;
done

2024-10-30 22:43 UTC, GiudGiud commented on framework/include/meshgenerators/NodeSetsGeneratorBase.h
> +  bool nodeSatisfiesRequirements(const Node * node,
for sure

2024-10-30 22:44 UTC, GiudGiud commented on framework/src/meshgenerators/ParsedGenerateNodeset.C
> +    mooseError("Not implemented for distributed meshes");
not tested in any MG afaik. Here we are hopeful someone will come in and implement it

2024-10-30 22:45 UTC, GiudGiud commented on framework/src/meshgenerators/ParsedGenerateSideset.C
> +    mooseError("Invalid function\n", _function, "\n", _func_F->ErrorMsg());
made consistent

2024-10-31 02:08 UTC, GiudGiud commented on framework/src/meshgenerators/ParsedGenerateNodeset.C
> +      if (_replace)
done

2024-10-31 02:09 UTC, GiudGiud commented on framework/src/meshgenerators/ParsedGenerateNodeset.C
> +               _func_F->ErrorMsg());
added

2024-10-31 02:12 UTC, GiudGiud commented on framework/src/meshgenerators/ParsedGenerateSideset.C
> +    mooseError("Invalid function\n", _function, "\n", _func_F->ErrorMsg());
we could add a test. maybe in a dedicated PR on catching all MG exceptions missing coverage

2024-10-31 02:12 UTC, GiudGiud commented on framework/include/meshgenerators/NodeSetsGeneratorBase.h
> +  bool nodeInIncludedNodesets(const std::vector<BoundaryID> & node_nodesets) const;
done

2024-10-31 15:16 UTC, pbehne approved these changes

2024-10-31 15:29 UTC, GiudGiud commented
thanks!
@roystgnr @lindsayad for the ccb review?

2024-10-31 15:29 UTC, GiudGiud commented
or @cticenhour if you want newsletter content 📰

2024-10-31 23:51 UTC, lindsayad commented on framework/include/meshgenerators/NodeSetsGeneratorBase.h
> +  std::map<dof_id_type, std::vector<dof_id_type>> _node_to_elem_map;
```suggestion
  std::unordered_map<dof_id_type, std::vector<dof_id_type>> _node_to_elem_map;
```

2024-11-01 21:45 UTC, lindsayad approved these changes

2024-11-01 22:46 UTC, GiudGiud commented
Test failures are unrelated.

Thanks for the reviews!

2024-11-01 22:46 UTC, merged