libMesh submodule update
idaholab/moose pull request #28880
Opened 2024-10-17 21:34 UTC by roystgnr

- Support for reading (the surface triangulations defined by) STL files.  This combined with our recent tetrahedralization support also allows for creating volume meshes from STL files; however, creating high-quality volume meshes from arbitrary STL files is still a work in progress.
- Support for higher-order (up to quintic) vector-valued FE bases in the Nédélec (first kind) and Ravier-Thomas FE families.
- Better handling for odd IsoGeometric Analysis extraction operators, and better error handling for broken IGA operators.
- Better unit test coverage for NodeElem; fixes to NodeElem methods which should be no-op but instead threw errors.
- Unit test coverage for fifth-order `MONOMIAL` elements.  So far new tests have not uncovered any problems, but based on user reports of convergence issues we recommend limiting `MONOMIAL` variables to fourth-order.
- Fixes for condensed eigensolve support after mesh reinit
- Fixes for caching of FE data on sides of meshes with non-uniform p-refinement levels
- Minor fixes for compiler complaints from `nvc++` and `clang++ -fsanitize`
- Properly register `--keep-cout` and `--drop-cerr` warnings with PETSc to avoid "options you set that were not used" false positives.
- Better error messages when tetrahedralizing a non-watertight input boundary mesh.
- Refactoring in AbaqusIO, to enable subclasses in MOOSE code with experimental support for more advanced file features.
- Improvements and fixes in Reduced Basis code, particularly the Empirical Interpolation Method classes.

2024-10-17 21:43 UTC, moosebuild commented on libmesh
> +Subproject commit 5483644b60cc538a4b54d312f28835bd94107627
**Caution!** This contains a submodule update

2024-10-17 21:43 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/2502208/), step Conda build config check on fdc5361 wanted to post the following:

A change of the following file(s) triggered this check:

  conda/libmesh

The following file(s) are unchanged:

  conda/mpi/conda_build_config.yaml

The conda build config was not changed but one or more of its dependencies have changed

2024-10-17 21:43 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/2502208/), step Conda libmesh build config check on fdc5361 wanted to post the following:

A change of the following file(s) triggered this check:

  libmesh

The following file(s) are unchanged:

  conda/mpi/conda_build_config.yaml

The libmesh submodule or configuration was changed but the conda build config was not

2024-10-17 21:43 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/2502208/), step Conda libmesh build config notification on fdc5361 wanted to post the following:

The following file(s) are changed:

  conda/libmesh/meta.yaml

The libmesh conda configuration has changed; ping @idaholab/moose-dev-ops

2024-10-18 02:21 UTC, moosebuild commented
Job [Documentation](https://civet.inl.gov/job/2502203/), step Docs: sync website on fdc5361 wanted to post the following:

View the site [here](https://mooseframework.inl.gov/docs/PRs/28880/site)

This comment will be updated on new commits.

2024-10-18 02:55 UTC, moosebuild commented
Job [Coverage](https://civet.inl.gov/job/2502250/), step Generate coverage on fdc5361 wanted to post the following:


## Framework coverage

<table>
  <thead>
    <tr>
      <th></th>
      <th>b3924e</th>
      <th colspan=4>#28880 fdc536</th>
    </tr>
    <tr>
      <th></th>
      <th>Total</th>
      <th>Total</th>
      <th>+/-</th>
      <th>New</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><b>Rate</b></td>
      <td>85.05%</td>
      <td>85.00%</td>
      <td>-0.04%</td>
      <td>-</td>
    </tr>
    <tr>
      <td><b>Hits</b></td>
      <td>106298</td>
      <td>106246</td>
      <td>-52</td>
      <td>0</td>
    </tr>
    <tr>
      <td><b>Misses</b></td>
      <td>18691</td>
      <td>18743</td>
      <td>+52</td>
      <td>0</td>
    </tr>
  </tbody>
</table>

[Diff coverage report](https://mooseframework.inl.gov/docs/PRs/28880/coverage_diff/framework)

[Full coverage report](https://mooseframework.inl.gov/docs/PRs/28880/coverage/framework)


## Modules coverage

Coverage did not change

## Full coverage reports

<details>
<summary>Reports</summary>

- [`framework`](https://mooseframework.inl.gov/docs/PRs/28880/coverage/framework)
- [`chemical_reactions`](https://mooseframework.inl.gov/docs/PRs/28880/coverage/chemical_reactions)
- [`combined`](https://mooseframework.inl.gov/docs/PRs/28880/coverage/combined)
- [`contact`](https://mooseframework.inl.gov/docs/PRs/28880/coverage/contact)
- [`electromagnetics`](https://mooseframework.inl.gov/docs/PRs/28880/coverage/electromagnetics)
- [`external_petsc_solver`](https://mooseframework.inl.gov/docs/PRs/28880/coverage/external_petsc_solver)
- [`fluid_properties`](https://mooseframework.inl.gov/docs/PRs/28880/coverage/fluid_properties)
- [`fsi`](https://mooseframework.inl.gov/docs/PRs/28880/coverage/fsi)
- [`functional_expansion_tools`](https://mooseframework.inl.gov/docs/PRs/28880/coverage/functional_expansion_tools)
- [`geochemistry`](https://mooseframework.inl.gov/docs/PRs/28880/coverage/geochemistry)
- [`heat_transfer`](https://mooseframework.inl.gov/docs/PRs/28880/coverage/heat_transfer)
- [`level_set`](https://mooseframework.inl.gov/docs/PRs/28880/coverage/level_set)
- [`misc`](https://mooseframework.inl.gov/docs/PRs/28880/coverage/misc)
- [`navier_stokes`](https://mooseframework.inl.gov/docs/PRs/28880/coverage/navier_stokes)
- [`optimization`](https://mooseframework.inl.gov/docs/PRs/28880/coverage/optimization)
- [`peridynamics`](https://mooseframework.inl.gov/docs/PRs/28880/coverage/peridynamics)
- [`phase_field`](https://mooseframework.inl.gov/docs/PRs/28880/coverage/phase_field)
- [`porous_flow`](https://mooseframework.inl.gov/docs/PRs/28880/coverage/porous_flow)
- [`ray_tracing`](https://mooseframework.inl.gov/docs/PRs/28880/coverage/ray_tracing)
- [`rdg`](https://mooseframework.inl.gov/docs/PRs/28880/coverage/rdg)
- [`reactor`](https://mooseframework.inl.gov/docs/PRs/28880/coverage/reactor)
- [`richards`](https://mooseframework.inl.gov/docs/PRs/28880/coverage/richards)
- [`scalar_transport`](https://mooseframework.inl.gov/docs/PRs/28880/coverage/scalar_transport)
- [`solid_mechanics`](https://mooseframework.inl.gov/docs/PRs/28880/coverage/solid_mechanics)
- [`solid_properties`](https://mooseframework.inl.gov/docs/PRs/28880/coverage/solid_properties)
- [`stochastic_tools`](https://mooseframework.inl.gov/docs/PRs/28880/coverage/stochastic_tools)
- [`thermal_hydraulics`](https://mooseframework.inl.gov/docs/PRs/28880/coverage/thermal_hydraulics)
- [`xfem`](https://mooseframework.inl.gov/docs/PRs/28880/coverage/xfem)

</details>



This comment will be updated on new commits.

2024-10-18 19:11 UTC, loganharbour commented
Roy adds-all-the-tests Stogner. Look at this guy

2024-10-21 18:33 UTC, roystgnr commented
Yup, worked fine after the server did.

2024-10-21 18:52 UTC, milljm requested changes
Unfortunately we forgot to reset the build number... Sorry to be the bearer of bad news!

2024-10-21 18:52 UTC, milljm commented on conda/libmesh/meta.yaml
>  {% set build = 1 %}
```suggestion
# ALSO: Follow the directions in scripts/tests/versioner_hashes.yaml
{% set build = 0 %}
```

2024-10-21 18:52 UTC, milljm commented on conda/moose-dev/conda_build_config.yaml
> +  - moose-libmesh 2024.10.17 openmpi_1
```suggestion
  - moose-libmesh 2024.10.17 mpich_0
  - moose-libmesh 2024.10.17 openmpi_0
```

2024-10-21 18:57 UTC, milljm approved these changes
For my part, Conda changes look good.

2024-10-21 19:01 UTC, moosebuild commented on libmesh
> +Subproject commit 5483644b60cc538a4b54d312f28835bd94107627
**Caution!** This contains a submodule update

2024-10-21 19:01 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/2504662/), step Conda build config check on cac2635 wanted to post the following:

A change of the following file(s) triggered this check:

  conda/libmesh

The following file(s) are unchanged:

  conda/mpi/conda_build_config.yaml

The conda build config was not changed but one or more of its dependencies have changed

2024-10-21 19:01 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/2504662/), step Conda libmesh build config check on cac2635 wanted to post the following:

A change of the following file(s) triggered this check:

  libmesh

The following file(s) are unchanged:

  conda/mpi/conda_build_config.yaml

The libmesh submodule or configuration was changed but the conda build config was not

2024-10-21 19:01 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/2504662/), step Conda libmesh build config notification on cac2635 wanted to post the following:

The following file(s) are changed:

  conda/libmesh/meta.yaml

The libmesh conda configuration has changed; ping @idaholab/moose-dev-ops

2024-10-22 19:14 UTC, lindsayad commented
I would like to get the static condensation stuff into MOOSE fairly soon. I wouldn't delay this PR if we're fine doing another update soon

2024-10-22 19:24 UTC, merged

2024-10-22 19:25 UTC, roystgnr commented
I'm good with another update in a couple weeks.

2024-10-24 14:36 UTC, loganharbour commented
Please check if next is broken or not before merging environment changes