Ensure postprocessors are computed during linear solve with PJFNKMO
idaholab/moose pull request #29027
Opened 2024-11-07 21:52 UTC by lindsayad

Closes #28993

2024-11-08 00:44 UTC, moosebuild commented
Job [Documentation](https://civet.inl.gov/job/2537168/), step Docs: sync website on 5929e64 wanted to post the following:

View the site [here](https://mooseframework.inl.gov/docs/PRs/29027/site)

This comment will be updated on new commits.

2024-11-08 02:20 UTC, YaqiWang commented on test/tests/problems/eigen_problem/jfnk_mo/tests
> +    cli_args = 'Problem/bx_norm=uint'
I feel this deserve a separate test with its own requirement.

2024-11-08 02:28 UTC, YaqiWang commented on framework/src/utils/SlepcSupport.C
> +      eigen_problem->execute(EXEC_LINEAR);
I realized that we do not have a check to make sure `execute_on` of the bx_norm postprocessor includes linear. Care to add it in `EigenProblem`?

2024-11-08 02:30 UTC, YaqiWang requested changes
The code change looks good. I checked with a Griffin test and it does work as expected! Just need to address my two comments and this should be good to go.

2024-11-10 21:24 UTC, lindsayad commented
Nice suggestions. Hopefully should be addressed

2024-11-11 00:22 UTC, moosebuild commented
Job [Coverage](https://civet.inl.gov/job/2540211/), step Generate coverage on 53798d8 wanted to post the following:


## Framework coverage

<table>
  <thead>
    <tr>
      <th></th>
      <th>d3e2af</th>
      <th colspan=4>#29027 53798d</th>
    </tr>
    <tr>
      <th></th>
      <th>Total</th>
      <th>Total</th>
      <th>+/-</th>
      <th>New</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><b>Rate</b></td>
      <td>85.09%</td>
      <td>85.09%</td>
      <td>-0.00%</td>
      <td>75.00%</td>
    </tr>
    <tr>
      <td><b>Hits</b></td>
      <td>106774</td>
      <td>106782</td>
      <td>+8</td>
      <td>9</td>
    </tr>
    <tr>
      <td><b>Misses</b></td>
      <td>18703</td>
      <td>18707</td>
      <td>+4</td>
      <td>3</td>
    </tr>
  </tbody>
</table>

[Diff coverage report](https://mooseframework.inl.gov/docs/PRs/29027/coverage_diff/framework)

[Full coverage report](https://mooseframework.inl.gov/docs/PRs/29027/coverage/framework)


## Modules coverage

Coverage did not change

## Full coverage reports

<details>
<summary>Reports</summary>

- [`framework`](https://mooseframework.inl.gov/docs/PRs/29027/coverage/framework)
- [`chemical_reactions`](https://mooseframework.inl.gov/docs/PRs/29027/coverage/chemical_reactions)
- [`combined`](https://mooseframework.inl.gov/docs/PRs/29027/coverage/combined)
- [`contact`](https://mooseframework.inl.gov/docs/PRs/29027/coverage/contact)
- [`electromagnetics`](https://mooseframework.inl.gov/docs/PRs/29027/coverage/electromagnetics)
- [`external_petsc_solver`](https://mooseframework.inl.gov/docs/PRs/29027/coverage/external_petsc_solver)
- [`fluid_properties`](https://mooseframework.inl.gov/docs/PRs/29027/coverage/fluid_properties)
- [`fsi`](https://mooseframework.inl.gov/docs/PRs/29027/coverage/fsi)
- [`functional_expansion_tools`](https://mooseframework.inl.gov/docs/PRs/29027/coverage/functional_expansion_tools)
- [`geochemistry`](https://mooseframework.inl.gov/docs/PRs/29027/coverage/geochemistry)
- [`heat_transfer`](https://mooseframework.inl.gov/docs/PRs/29027/coverage/heat_transfer)
- [`level_set`](https://mooseframework.inl.gov/docs/PRs/29027/coverage/level_set)
- [`misc`](https://mooseframework.inl.gov/docs/PRs/29027/coverage/misc)
- [`navier_stokes`](https://mooseframework.inl.gov/docs/PRs/29027/coverage/navier_stokes)
- [`optimization`](https://mooseframework.inl.gov/docs/PRs/29027/coverage/optimization)
- [`peridynamics`](https://mooseframework.inl.gov/docs/PRs/29027/coverage/peridynamics)
- [`phase_field`](https://mooseframework.inl.gov/docs/PRs/29027/coverage/phase_field)
- [`porous_flow`](https://mooseframework.inl.gov/docs/PRs/29027/coverage/porous_flow)
- [`ray_tracing`](https://mooseframework.inl.gov/docs/PRs/29027/coverage/ray_tracing)
- [`rdg`](https://mooseframework.inl.gov/docs/PRs/29027/coverage/rdg)
- [`reactor`](https://mooseframework.inl.gov/docs/PRs/29027/coverage/reactor)
- [`richards`](https://mooseframework.inl.gov/docs/PRs/29027/coverage/richards)
- [`scalar_transport`](https://mooseframework.inl.gov/docs/PRs/29027/coverage/scalar_transport)
- [`solid_mechanics`](https://mooseframework.inl.gov/docs/PRs/29027/coverage/solid_mechanics)
- [`solid_properties`](https://mooseframework.inl.gov/docs/PRs/29027/coverage/solid_properties)
- [`stochastic_tools`](https://mooseframework.inl.gov/docs/PRs/29027/coverage/stochastic_tools)
- [`thermal_hydraulics`](https://mooseframework.inl.gov/docs/PRs/29027/coverage/thermal_hydraulics)
- [`xfem`](https://mooseframework.inl.gov/docs/PRs/29027/coverage/xfem)

</details>

## Warnings

- `framework` new line coverage rate 75.00% is less than the suggested 90.0%



This comment will be updated on new commits.

2024-11-11 01:42 UTC, GiudGiud approved these changes

2024-11-11 02:14 UTC, YaqiWang commented
My comments are addressed. I cannot resolve the comments by myself.

2024-11-11 05:00 UTC, merged

2024-11-11 05:00 UTC, lindsayad commented
thanks for raising the issue and the review @YaqiWang !