Coupling FE Scalar Field Variable to FV Kernels
idaholab/moose pull request #29106
Opened 2024-11-20 15:29 UTC by csdechant

## Reason
This PR will enable the coupling of FE scalar field variable values and gradients to FV kernels. This PR directly addresses issue #15062

## Design
This PR includes the following:
- Introduces `adCoupledGradientFace`, which returns gradient of a coupled variable at an element face for FV Kernel.
- Tests the coupling of FE scalar field variable values to FVElementKernel and FVFluxKernel.
- Tests the coupling of FE scalar field variable gradients to FVElementKernel and FVFluxKernel.
- Tests the coupling of FV variable gradients to FVElementKernel and FVFluxKernel.
- Introduces convergence studies for all new kernel objects as heavy tests.

## Impact
This PR will allow for great degree of user flexibility when solving multiphysics problems where some physics are favorable towards FE and other physics are favorable towards FE (e.g. coupling FE electromagnetics to FV conducting fluids).

2024-11-20 17:42 UTC, moosebuild commented
Job [Documentation](https://civet.inl.gov/job/2556720/), step Docs: sync website on 8bc7e25 wanted to post the following:

View the site [here](https://mooseframework.inl.gov/docs/PRs/29106/site)

This comment will be updated on new commits.

2024-11-20 22:19 UTC, lindsayad commented
when you say scalar, you mean scalar field right? Because MOOSE has *scalar* variables whose values are independent of position on the mesh

2024-11-20 23:48 UTC, csdechant commented
@lindsayad your absolutely correct. I use the term scalar to denote that vector variable (like Nédélec variables) are not considered in this PR, but I forgot about MOOSE's Scalar variable and kernel objects. I renamed the PR to clarify scalar field.

2024-11-22 16:44 UTC, lindsayad commented
I figured but just wanted to check. I'll start reviewing once more tests are passing

2024-11-22 20:33 UTC, GiudGiud requested changes
this looks promising
can you add a section in the Coupleable.md (most likely?) on coupling FE variables in FV objects

2024-11-22 20:33 UTC, GiudGiud commented on test/tests/fvkernels/fe-to-fv-coupling/tests
> +    requirement = 'The system shall be able to solve a diffusion problem with a FE value coupled to a FVElementKernel.'
same for the others

2024-11-22 20:33 UTC, GiudGiud commented on framework/src/variables/MooseVariableFE.C
> +    mooseError("FE to FV coupling broken.");
```suggestion
    mooseAssert(false, "FE to FV coupling broken.");
```
We dont expect to hit this in production

2024-11-22 20:33 UTC, GiudGiud commented on framework/src/variables/MooseVariableFE.C
> +  mooseError("adGradSln(const FaceInfo & fi) are only for MooseVariableFE<Real>.");
```suggestion
  mooseError("adGradSln(const FaceInfo & fi) are only implemented for MooseVariableFE<Real>.");
```

2024-11-22 20:33 UTC, GiudGiud commented on framework/src/variables/MooseVariableFE.C
> +  _ad_grad_face_avg = (_ad_grad_u_face[0] + _ad_grad_neighbor_u_face[0]) / 2.0;
this is for a FE variable right

can you think of a reason to not have equal weights?

2024-11-22 20:44 UTC, GiudGiud commented on framework/src/variables/MooseVariableData.C
> +  // to seperate face vs element averaging...
you could split it in computeADElementAveraging and computeADFaceAveraging

2024-11-22 20:45 UTC, GiudGiud commented on framework/include/base/Assembly.h
>    /// The current arbitrary quadrature rule used on element faces
if there is another solution here than doubling up the attribute, it'd be good

2024-11-23 14:02 UTC, GiudGiud commented
Maybe some high level questions,
- could we then use any routine from Coupleable in a FVKernel and get the expected computations or do we have to pick only the new ones (for elemental and flux kernels respectively). If the latter is there a way to enforce this?
- Why is the average value preferred over computing the cell centroid value? Is there some theory around this?

2024-12-04 21:05 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/2582320/), step Clang format on d1db6ab wanted to post the following:

Your code requires style changes.  

A patch was auto generated and copied [here](https://mooseframework.inl.gov/docs/PRs/29106/clang_format/style.patch)  
You can directly apply the patch by running, in the top level of your repository:

`curl -s https://mooseframework.inl.gov/docs/PRs/29106/clang_format/style.patch | git apply -v`  

Alternatively, with your repository up to date and in the top level of your repository:

`git clang-format 586fdf59d3f0efb469a3717233db6d0ed2634848`

2024-12-05 00:15 UTC, moosebuild commented
Job [Coverage](https://civet.inl.gov/job/2582676/), step Generate coverage on a947630 wanted to post the following:


## Framework coverage

<table>
  <thead>
    <tr>
      <th></th>
      <th>586fdf</th>
      <th colspan=4>#29106 a94763</th>
    </tr>
    <tr>
      <th></th>
      <th>Total</th>
      <th>Total</th>
      <th>+/-</th>
      <th>New</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><b>Rate</b></td>
      <td>85.15%</td>
      <td>85.15%</td>
      <td>-0.00%</td>
      <td>84.08%</td>
    </tr>
    <tr>
      <td><b>Hits</b></td>
      <td>107980</td>
      <td>108138</td>
      <td>+158</td>
      <td>169</td>
    </tr>
    <tr>
      <td><b>Misses</b></td>
      <td>18827</td>
      <td>18858</td>
      <td>+31</td>
      <td>32</td>
    </tr>
  </tbody>
</table>

[Diff coverage report](https://mooseframework.inl.gov/docs/PRs/29106/coverage_diff/framework)

[Full coverage report](https://mooseframework.inl.gov/docs/PRs/29106/coverage/framework)


## Modules coverage

Coverage did not change

## Full coverage reports

<details>
<summary>Reports</summary>

- [`framework`](https://mooseframework.inl.gov/docs/PRs/29106/coverage/framework)
- [`chemical_reactions`](https://mooseframework.inl.gov/docs/PRs/29106/coverage/chemical_reactions)
- [`combined`](https://mooseframework.inl.gov/docs/PRs/29106/coverage/combined)
- [`contact`](https://mooseframework.inl.gov/docs/PRs/29106/coverage/contact)
- [`electromagnetics`](https://mooseframework.inl.gov/docs/PRs/29106/coverage/electromagnetics)
- [`external_petsc_solver`](https://mooseframework.inl.gov/docs/PRs/29106/coverage/external_petsc_solver)
- [`fluid_properties`](https://mooseframework.inl.gov/docs/PRs/29106/coverage/fluid_properties)
- [`fsi`](https://mooseframework.inl.gov/docs/PRs/29106/coverage/fsi)
- [`functional_expansion_tools`](https://mooseframework.inl.gov/docs/PRs/29106/coverage/functional_expansion_tools)
- [`geochemistry`](https://mooseframework.inl.gov/docs/PRs/29106/coverage/geochemistry)
- [`heat_transfer`](https://mooseframework.inl.gov/docs/PRs/29106/coverage/heat_transfer)
- [`level_set`](https://mooseframework.inl.gov/docs/PRs/29106/coverage/level_set)
- [`misc`](https://mooseframework.inl.gov/docs/PRs/29106/coverage/misc)
- [`navier_stokes`](https://mooseframework.inl.gov/docs/PRs/29106/coverage/navier_stokes)
- [`optimization`](https://mooseframework.inl.gov/docs/PRs/29106/coverage/optimization)
- [`peridynamics`](https://mooseframework.inl.gov/docs/PRs/29106/coverage/peridynamics)
- [`phase_field`](https://mooseframework.inl.gov/docs/PRs/29106/coverage/phase_field)
- [`porous_flow`](https://mooseframework.inl.gov/docs/PRs/29106/coverage/porous_flow)
- [`ray_tracing`](https://mooseframework.inl.gov/docs/PRs/29106/coverage/ray_tracing)
- [`rdg`](https://mooseframework.inl.gov/docs/PRs/29106/coverage/rdg)
- [`reactor`](https://mooseframework.inl.gov/docs/PRs/29106/coverage/reactor)
- [`richards`](https://mooseframework.inl.gov/docs/PRs/29106/coverage/richards)
- [`scalar_transport`](https://mooseframework.inl.gov/docs/PRs/29106/coverage/scalar_transport)
- [`solid_mechanics`](https://mooseframework.inl.gov/docs/PRs/29106/coverage/solid_mechanics)
- [`solid_properties`](https://mooseframework.inl.gov/docs/PRs/29106/coverage/solid_properties)
- [`stochastic_tools`](https://mooseframework.inl.gov/docs/PRs/29106/coverage/stochastic_tools)
- [`thermal_hydraulics`](https://mooseframework.inl.gov/docs/PRs/29106/coverage/thermal_hydraulics)
- [`xfem`](https://mooseframework.inl.gov/docs/PRs/29106/coverage/xfem)

</details>

## Warnings

- `framework` new line coverage rate 84.08% is less than the suggested 90.0%



This comment will be updated on new commits.

2025-02-18 20:47 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/2697666/), step Clang format on 5cca6ad wanted to post the following:

Your code requires style changes.  

A patch was auto generated and copied [here](https://mooseframework.inl.gov/docs/PRs/29106/clang_format/style.patch)  
You can directly apply the patch by running, in the top level of your repository:

`curl -s https://mooseframework.inl.gov/docs/PRs/29106/clang_format/style.patch | git apply -v`  

Alternatively, with your repository up to date and in the top level of your repository:

`git clang-format b05d63c35c7ca2c192a7177954d5cccf1c6dbe09`

2025-03-17 15:22 UTC, csdechant commented on test/tests/fvkernels/fe-to-fv-coupling/2D_Coupling_FVGrad_to_FVFluxKernel.i
> +  []
Will do and re-gold the files with `--fixup`

2025-03-17 15:58 UTC, csdechant commented
@GiudGiud For you high level questions:

> * could we then use any routine from Coupleable in a FVKernel and get the expected computations or do we have to pick only the new ones (for elemental and flux kernels respectively). If the latter is there a way to enforce this?

I tried this at first, but I needed the face information for coupling some of the FVFluxKernels, which at the time required creating a new coupled function `adCoupledGradientFace`. That is the only new coupled functions (from a kernel/BC construction standpoint) and `adCoupledGradient`, `adCoupledValue`, and `adCoupledNeighborValue` are still be used and will calculate the correct value for either FV or FE variables. 

> * Why is the average value preferred over computing the centroid value? Is there some theory around this? I guess for the volume terms this leads to a conservative coupling. What about faces?

This is correct. If I remember correctly, just defining the centroid values for the FE variable were not resulting in the correct convergence slopes (though I don't have those results anymore, so I could be misremembering). I believe convergence issue was more pronounce when there was high variations in the value of the FE variable within a given cell. 

For face values, the face average values are calculated in `computeADFaceAveraging()` using `_assembly.adJxWFace()` when the coupled variable type is FE.

2025-03-17 17:33 UTC, csdechant commented on framework/include/loops/ComputeFVFluxThread.h
> +        _fe_problem.assembly(_tid, _nl_system_num).qRuleFace()->n_points(),
True.  To address this I defined `nqp` as the following:

> int nqp = 1;
>   if (areFE)
>     nqp = _fe_problem.assembly(_tid, _nl_system_num).qRuleFace()->n_points();

2025-03-17 18:01 UTC, GiudGiud commented on framework/src/variables/MooseVariableFE.C
> +  _ad_grad_face_avg = (_ad_grad_u_face[0] + _ad_grad_neighbor_u_face[0]) / 2.0;
> Assuming I did my math and coding correctly, the weights introduced by different mesh sizes should be accounted for during the adGradSlnAvg() and adGradSlnAvgNeighbor() calculations.

they are taken into account to compute the element average. But when computing face averages from element averages, especially for gradients, you generally ( in FV at least )  have corrections for:
- distance from the element centroid to the face
- skewness correction (when line between centroids does not go through center of face)
- orthogonality correction (when the line between centroids is not normal to the face)

I am wondering here which ones should apply

2025-03-17 18:58 UTC, csdechant commented on framework/src/variables/MooseVariableFE.C
> +  _ad_grad_face_avg = (_ad_grad_u_face[0] + _ad_grad_neighbor_u_face[0]) / 2.0;
I thought that was true only for FV because FV variables don't have information stored at the cell faces, so we have to use an interpolation method for the FV value and gradient at the cell face (which includes all the correction factors you mentioned). For FE variable, I am utilizing the face that there is FE variable information stored at the cell face (or at least at the quadrature points associated with the cell face) and I take the face average of the FE value / gradient by dividing `_ad_JxW[qp] * _ad_coord[qp]`, where `_ad_JxW = _assembly.adJxWFace()` for face calculations and `_ad_JxW = _assembly.adJxW()` for element calculations.

Since I am essential taking the FE gradient value directly at the cell face, I don't believe the correction factors you mentioned applies in this case because no centroid based interpolation methods are being used.

2025-03-18 20:26 UTC, csdechant commented on framework/src/variables/MooseVariableFE.C
> +  _ad_grad_face_avg = (_ad_grad_u_face[0] + _ad_grad_neighbor_u_face[0]) / 2.0;
To double check if there is an effect base on the orthogonality or varying cell size, I did a convergence study with meshes of right triangle elements for both uniform and nonuniform element sizes. The convergence slopes look good to me (i.e., close to the ideal slope of 2 for these variable orders), but to get a second opinion, I upload the plots to this [git branch](https://github.com/csdechant/moose/tree/FEtoFVCoupling-Triangular-Mesh-Convergence/test/tests/fvkernels/fe-to-fv-coupling-triangle-mesh).

As for a theoretical proof, below is my derivation for why I think the weighting should be 1/2 for FE variables. Please let me know if this seems logical or if the math is incorrect:

Let the following be:
- $\nabla u_{Face}$: the gradient of the variable $u$ located long a cell face/boundary
- $\nabla u_{neighbor,Face}$: the gradient of the variable $u$ located long the neighbor cell face/boundary
- $V_{Face}$: the face volume for variable $u$
- $V_{neighbor,Face}$: the neighbor face volume for variable $u$

The total average gradient value located at a cell face/boundary is defined as:
- $\frac{\nabla u_{Face,total}}{V_{Face,total}} = \frac{\nabla u_{Face} + \nabla u_{neighbor,Face}}{V_{Face} + V_{neighbor,Face}}$

Assuming that $V_{Face} = V_{neighbor,Face}$, then the above equation simplifies to:
- $\frac{\nabla u_{Face,total}}{V_{Face,total}} =  \frac{\nabla u_{Face} + \nabla u_{neighbor,Face}}{2*V_{Face}}$
- $\frac{\nabla u_{Face,total}}{V_{Face,total}} =  \frac{1}{2}\frac{\nabla u_{Face} + \nabla u_{neighbor,Face}}{V_{Face}}$
- $\frac{\nabla u_{Face,total}}{V_{Face,total}} =  \frac{1}{2} \left( \frac{\nabla u_{Face}}{V_{Face}} + \frac{\nabla u_{neighbor,Face}}{V_{Face}} \right)$

Re-substituting in $V_{neighbor,Face}$ in the second term results in:
- $\frac{\nabla u_{Face,total}}{V_{Face,total}} =  \frac{1}{2} \left( \frac{\nabla u_{Face}}{V_{Face}} + \frac{\nabla u_{neighbor,Face}}{V_{neighbor,Face}} \right)$

Converting to code results in:
> `_ad_grad_u_face = adGradSlnAvg();` $\frac{\nabla u_{Face}}{V_{Face}}$
> `_ad_grad_neighbor_u_face = adGradSlnAvgNeighbor();` $\frac{\nabla u_{neighbor,Face}}{V_{neighbor,Face}}$
> `_ad_grad_face_avg = (_ad_grad_u_face[0] + _ad_grad_neighbor_u_face[0]) / 2.0;`

Assuming that `adGradSlnAvg()` and `adGradSlnAvgNeighbor()` are correctly providing the face average gradient values.

2025-03-18 22:17 UTC, csdechant commented on framework/src/variables/MooseVariableData.C
> +// of the neighbor side.
Ok, my misunderstanding. I thought you meant relocating the function, `computeGhostValuesFace`, somewhere else. Will move the comment and fix-up the sentence grammar.

2025-03-18 22:19 UTC, lindsayad commented on framework/src/variables/MooseVariableFE.C
> +  _ad_grad_face_avg = (_ad_grad_u_face[0] + _ad_grad_neighbor_u_face[0]) / 2.0;
The weighting should be 1/2. This is what is done for DG methods

2025-03-19 03:07 UTC, GiudGiud commented on framework/src/variables/MooseVariableFE.C
> +  _ad_grad_face_avg = (_ad_grad_u_face[0] + _ad_grad_neighbor_u_face[0]) / 2.0;
I'm convinced. Thanks for checking

2025-03-19 13:38 UTC, GiudGiud commented on framework/include/loops/ComputeFVFluxThread.h
> +  for (auto var : _fv_vars)
I think that's what I meant. Was a while now

2025-03-19 13:46 UTC, GiudGiud commented on framework/src/variables/MooseVariableData.C
> +      _face_averaging = false;
> if we could retrieve that from one of the attributes above, we could have the same code for both element and face averaging?

nothing obvious to me on that front.

2025-03-19 15:49 UTC, csdechant commented on framework/src/variables/MooseVariableData.C
> +    value_temp = 0.0;
This is correct, but looking back I can simplify this using:
```
auto value_temp = _current_ad_JxW[0] * _ad_coord[0] * _ad_u[0];
for (unsigned int qp = 1; qp < nqp; qp++)
```

2025-03-19 15:59 UTC, csdechant commented on framework/src/variables/MooseVariableData.C
> +      _face_averaging = false;
That's a great point and I like the idea of consolidating the element and face averaging code! As you mention, I don't believe there is a current attribute where we can call `adJxW()`/`adJxWFace()` from. I just pushed a commit labelled "[Adding documentation to Coupleable and simplifying code edits](https://github.com/idaholab/moose/pull/29106/commits/f728400d9b94f38b3955fcac7a49448e15686867)", where I replaced `_face_averaging` with a `_current_ad_JxW`. The upside to that change is that it removes an if statement, but the downside is that `_current_ad_JxW` is populated even if we are not averaging anything. I am not sure which option is computational faster in most cases (I am assuming it heavily depends on the size of `_current_ad_JxW`).

2025-03-19 18:06 UTC, GiudGiud commented on framework/src/variables/MooseVariableData.C
> +      _face_averaging = false;
> _current_ad_JxW is populated even if we are not averaging anything

if it s just setting a reference, that s cheap and that s ok
if there s anything more involved, we should take a look

2025-03-19 20:06 UTC, csdechant commented
@GiudGiud I believe I addressed/responded to all your current conversation, and this PR is ready for a re-review whenever you are free.

2025-03-20 22:27 UTC, lindsayad commented
@csdechant I was disappointed in myself to find that I never brought up functors on this PR. When you originally did this work (2 or 3 years ago?), functors did not exist or if they did, they were still in their infancy. Now, unfortunately for all the work you've done in this PR, they are a pretty big part of the framework and are used almost exclusively in finite volume over the `Coupleable` interfaces. Additionally, I anticipate that finite element objects wishing to make use of finite volume data will likely do so through the functor interfaces going into the future.

Have you looked into the functor system? I have not looked over this particular PR in detail, but I do remember parts of your presentation you gave regarding this work years ago. To me, the most important part of your presentation was demonstrating the expected spatial convergence rates when coupling FV and FE variables. Ideally, what I would like to see, which I should have voiced months ago, is doing all FE-FV coupling through functor APIs and ensuring that we are getting the expected convergence rates which you demonstrated

2025-03-20 23:06 UTC, csdechant commented
> Have you looked into the functor system?

I am somewhat familiar with the functor system (I was at Guillaume's functor talk at the MOOSE conference and I am aware of Zach's [FE-FV interface coupling PR](https://github.com/idaholab/moose/pull/29985) that was recently merged). Currently my main question about coupling with functors is how is the gradient of variables coupled? Is it as simple as calling the gradient of a variable in a material property and inputing that through the functor system?

2025-03-21 15:01 UTC, GiudGiud commented
>  Currently my main question about coupling with functors is how is the gradient of variables coupled

the gradient of the variables are computed on the fly. So for FE, we would use the shape functions. For FV, we would use Green Gauss for element gradients and interpolations + GG for face gradients. 

But you are onto something. We have evaluateOnElement and evaluateOnElementSide(qp) and these do the gradients, but faceEvaluate does not compute the gradient at this time

2025-03-24 18:35 UTC, csdechant commented
> Yea face gradient evaluation is missing for the `MooseVariableFE` implementation of functors. Can this PR be adapted to focus on functor APIs? If you're tired of working on this PR @csdechant I could help with that.

I have no problem with that. If functors are the future of MOOSE, I need to get a better understanding of how to develop useful code / new physic with them. I will probably need help with this, but I want to give it a try first.

2025-03-24 19:13 UTC, lindsayad commented
Awesome. Don't hesitate to reach out when you need something

2025-07-07 14:50 UTC, csdechant commented
> This pull request has been automatically marked as stale because it has not had recent activity in the last 100 days. It will be closed in 7 days if no further activity occurs. Thank you for your contributions.

Still working on this. Will make it a priority.

2025-07-07 21:40 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/3022956/), step Clang format on cde330d wanted to post the following:

Your code requires style changes.  

A patch was auto generated and copied [here](https://mooseframework.inl.gov/docs/PRs/29106/clang_format/style.patch)  
You can directly apply the patch by running, in the top level of your repository:

`curl -s https://mooseframework.inl.gov/docs/PRs/29106/clang_format/style.patch | git apply -v`  

Alternatively, with your repository up to date and in the top level of your repository:

`git clang-format 2017977c9345abd748c28747c3082c81698c6620`

2025-10-20 14:27 UTC, csdechant commented
I am still here.

2026-02-05 05:56 UTC, closed without merging