Adds postprocessor to track time step number for transient problems
idaholab/moose pull request #29128
Opened 2024-11-23 19:26 UTC by anshchaube

Minor quality-of-life improvement for users who want to track time step counts during their MOOSE simulations.

closes #29127

2024-11-24 02:09 UTC, GiudGiud requested changes
nice this is almost ready

2024-11-24 02:09 UTC, GiudGiud commented on framework/doc/content/source/postprocessors/NumTimeSteps.md
> +# TimestepSize
```suggestion
# NumTimeSteps
```

2024-11-24 02:09 UTC, GiudGiud commented on framework/doc/content/source/postprocessors/NumTimeSteps.md
> +
```suggestion
```

2024-11-24 02:09 UTC, GiudGiud commented on framework/include/postprocessors/NumTimeSteps.h
> +class NumTimeSteps : public GeneralPostprocessor
```suggestion
/**
 * Reports on the number of time steps already taken in the transient
 */
class NumTimeSteps : public GeneralPostprocessor
```

2024-11-24 02:09 UTC, GiudGiud commented on test/tests/postprocessors/num_time_steps/tests
> +    requirement = 'The postprocessor `NumTimeSteps` shall count the number of time-steps accurately'
```suggestion
    requirement = 'The shall be able to count the number of time-steps that have been taken '
```

2024-11-24 02:09 UTC, GiudGiud commented on test/tests/postprocessors/num_time_steps/tests
> +                   'over the course of a transient solve'
```suggestion
                   'over the course of the simulation of a transient.'
```

2024-11-24 15:24 UTC, GiudGiud commented
let's squash all these commits togther in just a
```
address review
- updated wording
- added docstrings
```
commit message

2024-11-24 21:16 UTC, loganharbour submitted a review, later dismissed

2024-11-24 21:16 UTC, loganharbour commented on test/tests/postprocessors/num_time_steps/moose.i
> +[Mesh]
There is no need for a complex solve to test this. The test should be as minimal as possible to satisfy the requirement listed in the test spec:

> The shall be able to count the number of time-steps that have been taken over the course of the simulation of a transient

A coupled heat conduction solve and a large 27k element mesh is absolutely overkill for testing this postprocessor.

A basic problem without a solve is sufficient:

```
[Mesh/gmg]
  type = GeneratedMeshGenerator
  dim = 1
[]

[Postprocessors/timestep_ctr]
  type = NumTimeSteps
[]

[Problem]
  solve = False
[]

[Executioner]
  type = Transient
  dt = 1
  num_steps = 10
[]

[Outputs]
  csv = true
[]
```

2024-11-24 22:29 UTC, dschwen commented on test/tests/postprocessors/num_time_steps/moose.i
> +  dt = 1
I suggest setting `dt` to something that doesn't result the time being the exact same as the time step number...

2024-11-24 23:27 UTC, moosebuild commented
Job [Documentation](https://civet.inl.gov/job/2561525/), step Docs: sync website on 6066950 wanted to post the following:

View the site [here](https://mooseframework.inl.gov/docs/PRs/29128/site)

This comment will be updated on new commits.

2024-11-27 21:53 UTC, GiudGiud approved these changes

2024-12-01 09:07 UTC, moosebuild commented
Job [Coverage](https://civet.inl.gov/job/2569039/), step Generate coverage on 3c176f1 wanted to post the following:


## Framework coverage

<table>
  <thead>
    <tr>
      <th></th>
      <th>cedfd0</th>
      <th colspan=4>#29128 3c176f</th>
    </tr>
    <tr>
      <th></th>
      <th>Total</th>
      <th>Total</th>
      <th>+/-</th>
      <th>New</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><b>Rate</b></td>
      <td>85.14%</td>
      <td>85.14%</td>
      <td>+0.00%</td>
      <td>91.67%</td>
    </tr>
    <tr>
      <td><b>Hits</b></td>
      <td>107658</td>
      <td>107669</td>
      <td>+11</td>
      <td>11</td>
    </tr>
    <tr>
      <td><b>Misses</b></td>
      <td>18792</td>
      <td>18793</td>
      <td>+1</td>
      <td>1</td>
    </tr>
  </tbody>
</table>

[Diff coverage report](https://mooseframework.inl.gov/docs/PRs/29128/coverage_diff/framework)

[Full coverage report](https://mooseframework.inl.gov/docs/PRs/29128/coverage/framework)


## Modules coverage

Coverage did not change

## Full coverage reports

<details>
<summary>Reports</summary>

- [`framework`](https://mooseframework.inl.gov/docs/PRs/29128/coverage/framework)
- [`chemical_reactions`](https://mooseframework.inl.gov/docs/PRs/29128/coverage/chemical_reactions)
- [`combined`](https://mooseframework.inl.gov/docs/PRs/29128/coverage/combined)
- [`contact`](https://mooseframework.inl.gov/docs/PRs/29128/coverage/contact)
- [`electromagnetics`](https://mooseframework.inl.gov/docs/PRs/29128/coverage/electromagnetics)
- [`external_petsc_solver`](https://mooseframework.inl.gov/docs/PRs/29128/coverage/external_petsc_solver)
- [`fluid_properties`](https://mooseframework.inl.gov/docs/PRs/29128/coverage/fluid_properties)
- [`fsi`](https://mooseframework.inl.gov/docs/PRs/29128/coverage/fsi)
- [`functional_expansion_tools`](https://mooseframework.inl.gov/docs/PRs/29128/coverage/functional_expansion_tools)
- [`geochemistry`](https://mooseframework.inl.gov/docs/PRs/29128/coverage/geochemistry)
- [`heat_transfer`](https://mooseframework.inl.gov/docs/PRs/29128/coverage/heat_transfer)
- [`level_set`](https://mooseframework.inl.gov/docs/PRs/29128/coverage/level_set)
- [`misc`](https://mooseframework.inl.gov/docs/PRs/29128/coverage/misc)
- [`navier_stokes`](https://mooseframework.inl.gov/docs/PRs/29128/coverage/navier_stokes)
- [`optimization`](https://mooseframework.inl.gov/docs/PRs/29128/coverage/optimization)
- [`peridynamics`](https://mooseframework.inl.gov/docs/PRs/29128/coverage/peridynamics)
- [`phase_field`](https://mooseframework.inl.gov/docs/PRs/29128/coverage/phase_field)
- [`porous_flow`](https://mooseframework.inl.gov/docs/PRs/29128/coverage/porous_flow)
- [`ray_tracing`](https://mooseframework.inl.gov/docs/PRs/29128/coverage/ray_tracing)
- [`rdg`](https://mooseframework.inl.gov/docs/PRs/29128/coverage/rdg)
- [`reactor`](https://mooseframework.inl.gov/docs/PRs/29128/coverage/reactor)
- [`richards`](https://mooseframework.inl.gov/docs/PRs/29128/coverage/richards)
- [`scalar_transport`](https://mooseframework.inl.gov/docs/PRs/29128/coverage/scalar_transport)
- [`solid_mechanics`](https://mooseframework.inl.gov/docs/PRs/29128/coverage/solid_mechanics)
- [`solid_properties`](https://mooseframework.inl.gov/docs/PRs/29128/coverage/solid_properties)
- [`stochastic_tools`](https://mooseframework.inl.gov/docs/PRs/29128/coverage/stochastic_tools)
- [`thermal_hydraulics`](https://mooseframework.inl.gov/docs/PRs/29128/coverage/thermal_hydraulics)
- [`xfem`](https://mooseframework.inl.gov/docs/PRs/29128/coverage/xfem)

</details>



This comment will be updated on new commits.

2024-12-02 04:22 UTC, GiudGiud commented on test/tests/postprocessors/num_time_steps/tests
> +  issues = #29127
```suggestion
  issues = '#29127'
```

2024-12-03 16:01 UTC, GiudGiud commented
Test failures unrelated (fenix failures are known, unrelated tests w/ openmpi)

2024-12-03 16:01 UTC, merged