Improve pre-SMO residual console formatting
idaholab/moose pull request #29200
Opened 2024-12-04 19:58 UTC by hugary1995

This PR makes two changes to the pre-SMO residual console output:
1. Reword to say "(before solution modification)" which hopefully is easier to understand.
2. Use the same printing format as the other residual outputs.

close #29195

2024-12-04 19:58 UTC, hugary1995 commented
An example output is
```
Time Step 1, time = 0.5, dt = 0.5
 * Nonlinear |R| = 1.000000e+00 (before solution modification)
 0 Nonlinear |R| = 7.905694e-01
      0 Linear |R| = 7.905694e-01
      1 Linear |R| = 4.383697e-02
      2 Linear |R| = 2.358755e-03
      3 Linear |R| = 6.392293e-05
      4 Linear |R| = 2.921719e-06
 1 Nonlinear |R| = 2.921129e-06
      0 Linear |R| = 2.921129e-06
      1 Linear |R| = 7.029598e-08
      2 Linear |R| = 5.563024e-09
      3 Linear |R| = 5.831371e-10
      4 Linear |R| = 1.760496e-11
 2 Nonlinear |R| = 1.761345e-11
      0 Linear |R| = 1.761345e-11
      1 Linear |R| = 1.152373e-12
      2 Linear |R| = 5.038920e-14
      3 Linear |R| = 2.225679e-15
      4 Linear |R| = 6.888970e-17
 3 Nonlinear |R| = 9.910723e-17
 Solve Converged!
```
And I am open to suggestions.

2024-12-04 20:13 UTC, GiudGiud commented
how about 
```
 * Pre-SMO    |R| = 1.000000e+00
```
and let people google SMOs
"solution modification" sounds fishy

2024-12-04 20:18 UTC, hugary1995 commented
LOL you two will have to debate @bwspenc 

I think it all depends on how "analyst friendly" we would like the console output to be.

Alternatively we could remove the parenthesis altogether.

2024-12-04 20:42 UTC, bwspenc commented
Well, this whole thing started because I reached out to Gary because I couldn't remember what SMO meant! I don't think that's an acronym we should expect anyone to know.

2024-12-04 20:46 UTC, hugary1995 commented
> What if we do with @GiudGiud suggested, but replace "Pre-SMO" with "Initial", or something like that if the meaning of "Initial" is too vague.

I think it was @lindsayad who drove me away from calling it "initial residual". I think he had a good point: There should be one and only one initial residual.

2024-12-04 20:47 UTC, bwspenc commented
How about "Pre-modification"?

2024-12-04 20:48 UTC, GiudGiud commented
how about Pre-BCs ?
what other SMOs are there anyway?

2024-12-04 20:49 UTC, hugary1995 commented
```
* Pre-modification |R| = 1.000000e+00
```
might be too long to align with the rest.

And if we put it afterward like
```
* Nonlinear |R| = 1.000000e+00 (Pre-modification)
```
it circles back to @GiudGiud 's concern about it being fishy.

2024-12-04 20:49 UTC, hugary1995 commented
> how about Pre-BCs ? what other SMOs are there anyway?

Preset BCs, constraints, predictors, and potentially user-objects.

2024-12-04 20:51 UTC, bwspenc commented
So if you don't have any of those things (SMOs), is the Pre-SMO residual going to be the same as the last residual in the previous step?

2024-12-04 20:52 UTC, GiudGiud commented
(Pre-modification) sounds less fishy than solution modification.
I d be ok with (Pre-variable modification). Maybe more accurate than just "modification"

2024-12-04 20:53 UTC, bwspenc commented
Is there any way to also convey which residual is used for relative convergence?

2024-12-04 20:54 UTC, GiudGiud commented
we have space imo, we could say:
```
* Nonlinear |R| = 1.000000e+00 (Before preset-BCs, predictors and constraints)
```

2024-12-04 20:55 UTC, GiudGiud commented
>  Is there any way to also convey which residual is used for relative convergence?

I would say dont even try. Convergence is its own system, relative convergence might not even be in the list of criteria anymore in a given solve

2024-12-04 20:55 UTC, bwspenc commented
I think the problem with the current message is that it leaves the user wondering: 

1. What is an SMO?
2. Why do I care about what the residual is before or after the SMOs are applied?

I'm sure it's impossible to answer both of those questions in 9 characters, but I'd like to move toward that!

2024-12-04 20:58 UTC, GiudGiud commented
> Does it need to include UserObjects too, though?

If they are modifying the solution, they probably should be in the Correctors system?

2024-12-04 20:58 UTC, hugary1995 commented
Since this behavior never changes over the course of the entire simulation, we could print a whole paragraph (in blue?) at the beginning.

2024-12-04 20:58 UTC, GiudGiud commented
so we could have
```
* Nonlinear |R| = 1.000000e+00 (Before preset BCs, predictors/correctors and constraints)
````

2024-12-04 21:03 UTC, bwspenc commented
I vote for both @GiudGiud's latest version and a descriptive note in blue at the beginning if you're using that option.

2024-12-04 21:57 UTC, GiudGiud commented
if you're worried about having that line too often you could do mooseDoOnce on having the list (preset BCs, predictors/correctors, ...). Shows the first time, and then does not show

2024-12-04 22:22 UTC, moosebuild commented
Job [Documentation](https://civet.inl.gov/job/2582078/), step Docs: sync website on f23f97e wanted to post the following:

View the site [here](https://mooseframework.inl.gov/docs/PRs/29200/site)

This comment will be updated on new commits.

2024-12-04 23:09 UTC, moosebuild commented
Job [Coverage](https://civet.inl.gov/job/2582093/), step Generate coverage on f23f97e wanted to post the following:


## Framework coverage

<table>
  <thead>
    <tr>
      <th></th>
      <th>586fdf</th>
      <th colspan=4>#29200 f23f97</th>
    </tr>
    <tr>
      <th></th>
      <th>Total</th>
      <th>Total</th>
      <th>+/-</th>
      <th>New</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><b>Rate</b></td>
      <td>85.15%</td>
      <td>85.15%</td>
      <td>-0.00%</td>
      <td>100.00%</td>
    </tr>
    <tr>
      <td><b>Hits</b></td>
      <td>107980</td>
      <td>107981</td>
      <td>+1</td>
      <td>4</td>
    </tr>
    <tr>
      <td><b>Misses</b></td>
      <td>18827</td>
      <td>18829</td>
      <td>+2</td>
      <td>0</td>
    </tr>
  </tbody>
</table>

[Diff coverage report](https://mooseframework.inl.gov/docs/PRs/29200/coverage_diff/framework)

[Full coverage report](https://mooseframework.inl.gov/docs/PRs/29200/coverage/framework)


## Modules coverage

Coverage did not change

## Full coverage reports

<details>
<summary>Reports</summary>

- [`framework`](https://mooseframework.inl.gov/docs/PRs/29200/coverage/framework)
- [`chemical_reactions`](https://mooseframework.inl.gov/docs/PRs/29200/coverage/chemical_reactions)
- [`combined`](https://mooseframework.inl.gov/docs/PRs/29200/coverage/combined)
- [`contact`](https://mooseframework.inl.gov/docs/PRs/29200/coverage/contact)
- [`electromagnetics`](https://mooseframework.inl.gov/docs/PRs/29200/coverage/electromagnetics)
- [`external_petsc_solver`](https://mooseframework.inl.gov/docs/PRs/29200/coverage/external_petsc_solver)
- [`fluid_properties`](https://mooseframework.inl.gov/docs/PRs/29200/coverage/fluid_properties)
- [`fsi`](https://mooseframework.inl.gov/docs/PRs/29200/coverage/fsi)
- [`functional_expansion_tools`](https://mooseframework.inl.gov/docs/PRs/29200/coverage/functional_expansion_tools)
- [`geochemistry`](https://mooseframework.inl.gov/docs/PRs/29200/coverage/geochemistry)
- [`heat_transfer`](https://mooseframework.inl.gov/docs/PRs/29200/coverage/heat_transfer)
- [`level_set`](https://mooseframework.inl.gov/docs/PRs/29200/coverage/level_set)
- [`misc`](https://mooseframework.inl.gov/docs/PRs/29200/coverage/misc)
- [`navier_stokes`](https://mooseframework.inl.gov/docs/PRs/29200/coverage/navier_stokes)
- [`optimization`](https://mooseframework.inl.gov/docs/PRs/29200/coverage/optimization)
- [`peridynamics`](https://mooseframework.inl.gov/docs/PRs/29200/coverage/peridynamics)
- [`phase_field`](https://mooseframework.inl.gov/docs/PRs/29200/coverage/phase_field)
- [`porous_flow`](https://mooseframework.inl.gov/docs/PRs/29200/coverage/porous_flow)
- [`ray_tracing`](https://mooseframework.inl.gov/docs/PRs/29200/coverage/ray_tracing)
- [`rdg`](https://mooseframework.inl.gov/docs/PRs/29200/coverage/rdg)
- [`reactor`](https://mooseframework.inl.gov/docs/PRs/29200/coverage/reactor)
- [`richards`](https://mooseframework.inl.gov/docs/PRs/29200/coverage/richards)
- [`scalar_transport`](https://mooseframework.inl.gov/docs/PRs/29200/coverage/scalar_transport)
- [`solid_mechanics`](https://mooseframework.inl.gov/docs/PRs/29200/coverage/solid_mechanics)
- [`solid_properties`](https://mooseframework.inl.gov/docs/PRs/29200/coverage/solid_properties)
- [`stochastic_tools`](https://mooseframework.inl.gov/docs/PRs/29200/coverage/stochastic_tools)
- [`thermal_hydraulics`](https://mooseframework.inl.gov/docs/PRs/29200/coverage/thermal_hydraulics)
- [`xfem`](https://mooseframework.inl.gov/docs/PRs/29200/coverage/xfem)

</details>



This comment will be updated on new commits.

2024-12-04 23:26 UTC, GiudGiud requested changes
let's remove our handles from the commit message. I dont want to be emailed every single time someone rebases

grammar looks fine

2024-12-05 03:43 UTC, GiudGiud approved these changes

2024-12-05 16:02 UTC, merged