Add subchannel module
idaholab/moose pull request #29384
Opened 2024-12-10 03:13 UTC by loganharbour

Closes #28497

2024-12-10 15:40 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/2593486/), step Clang format on 7e9c71d wanted to post the following:

Your code requires style changes.  

A patch was auto generated and copied [here](https://mooseframework.inl.gov/docs/PRs/29384/clang_format/style.patch)  
You can directly apply the patch by running, in the top level of your repository:

`curl -s https://mooseframework.inl.gov/docs/PRs/29384/clang_format/style.patch | git apply -v`  

Alternatively, with your repository up to date and in the top level of your repository:

`git clang-format c900eec471c663d411d1ec23d6078aca2890278b`

2024-12-10 16:28 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/2593536/), step Size check on efb1aa2 wanted to post the following:

Warning: This PR changes repo size by 56.87 MiB.

2024-12-10 18:52 UTC, moosebuild commented
Job [Documentation](https://civet.inl.gov/job/2593531/), step Docs: sync website on efb1aa2 wanted to post the following:

View the site [here](https://mooseframework.inl.gov/docs/PRs/29384/site)

This comment will be updated on new commits.

2024-12-10 19:49 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/2593867/), step Size check on 897c71f wanted to post the following:

Warning: This PR changes repo size by 56.87 MiB.

2024-12-12 20:15 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/2596990/), step Size check on 5fe517c wanted to post the following:

Warning: This PR changes repo size by 56.87 MiB.

2024-12-13 02:50 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/2599035/), step Size check on 66cad22 wanted to post the following:

Warning: This PR changes repo size by 56.87 MiB.

2024-12-13 02:51 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/2599035/), step Size check on 66cad22 wanted to post the following:

Warning: This PR changes repo size by 56.87 MiB.

2024-12-13 03:44 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/2599113/), step Size check on a1cdca1 wanted to post the following:

Warning: This PR changes repo size by 56.87 MiB.

2024-12-13 08:35 UTC, moosebuild commented
Job [Coverage](https://civet.inl.gov/job/2599154/), step Generate coverage on a1cdca1 wanted to post the following:


## Framework coverage

Coverage did not change


## Modules coverage

Inconsistent report tags were found between the head and base reports.
This can happen when reports are missing from either the head or the base.

Inconsistent tags:
  module-subchannel
  module-subchannel-parallel
  module-subchannel-recover

### Combined

<table>
  <thead>
    <tr>
      <th></th>
      <th>f46a73</th>
      <th colspan=4>#29384 a1cdca</th>
    </tr>
    <tr>
      <th></th>
      <th>Total</th>
      <th>Total</th>
      <th>+/-</th>
      <th>New</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><b>Rate</b></td>
      <td>49.41%</td>
      <td>49.43%</td>
      <td>+0.01%</td>
      <td>50.00%</td>
    </tr>
    <tr>
      <td><b>Hits</b></td>
      <td>42</td>
      <td>43</td>
      <td>+1</td>
      <td>1</td>
    </tr>
    <tr>
      <td><b>Misses</b></td>
      <td>43</td>
      <td>44</td>
      <td>+1</td>
      <td>1</td>
    </tr>
  </tbody>
</table>

[Diff coverage report](https://mooseframework.inl.gov/docs/PRs/29384/coverage_diff/combined)

[Full coverage report](https://mooseframework.inl.gov/docs/PRs/29384/coverage/combined)

## Full coverage reports

<details>
<summary>Reports</summary>

- [`framework`](https://mooseframework.inl.gov/docs/PRs/29384/coverage/framework)
- [`chemical_reactions`](https://mooseframework.inl.gov/docs/PRs/29384/coverage/chemical_reactions)
- [`combined`](https://mooseframework.inl.gov/docs/PRs/29384/coverage/combined)
- [`contact`](https://mooseframework.inl.gov/docs/PRs/29384/coverage/contact)
- [`electromagnetics`](https://mooseframework.inl.gov/docs/PRs/29384/coverage/electromagnetics)
- [`external_petsc_solver`](https://mooseframework.inl.gov/docs/PRs/29384/coverage/external_petsc_solver)
- [`fluid_properties`](https://mooseframework.inl.gov/docs/PRs/29384/coverage/fluid_properties)
- [`fsi`](https://mooseframework.inl.gov/docs/PRs/29384/coverage/fsi)
- [`functional_expansion_tools`](https://mooseframework.inl.gov/docs/PRs/29384/coverage/functional_expansion_tools)
- [`geochemistry`](https://mooseframework.inl.gov/docs/PRs/29384/coverage/geochemistry)
- [`heat_transfer`](https://mooseframework.inl.gov/docs/PRs/29384/coverage/heat_transfer)
- [`level_set`](https://mooseframework.inl.gov/docs/PRs/29384/coverage/level_set)
- [`misc`](https://mooseframework.inl.gov/docs/PRs/29384/coverage/misc)
- [`navier_stokes`](https://mooseframework.inl.gov/docs/PRs/29384/coverage/navier_stokes)
- [`optimization`](https://mooseframework.inl.gov/docs/PRs/29384/coverage/optimization)
- [`peridynamics`](https://mooseframework.inl.gov/docs/PRs/29384/coverage/peridynamics)
- [`phase_field`](https://mooseframework.inl.gov/docs/PRs/29384/coverage/phase_field)
- [`porous_flow`](https://mooseframework.inl.gov/docs/PRs/29384/coverage/porous_flow)
- [`ray_tracing`](https://mooseframework.inl.gov/docs/PRs/29384/coverage/ray_tracing)
- [`rdg`](https://mooseframework.inl.gov/docs/PRs/29384/coverage/rdg)
- [`reactor`](https://mooseframework.inl.gov/docs/PRs/29384/coverage/reactor)
- [`richards`](https://mooseframework.inl.gov/docs/PRs/29384/coverage/richards)
- [`scalar_transport`](https://mooseframework.inl.gov/docs/PRs/29384/coverage/scalar_transport)
- [`solid_mechanics`](https://mooseframework.inl.gov/docs/PRs/29384/coverage/solid_mechanics)
- [`solid_properties`](https://mooseframework.inl.gov/docs/PRs/29384/coverage/solid_properties)
- [`stochastic_tools`](https://mooseframework.inl.gov/docs/PRs/29384/coverage/stochastic_tools)
- [`subchannel`](https://mooseframework.inl.gov/docs/PRs/29384/coverage/subchannel)
- [`thermal_hydraulics`](https://mooseframework.inl.gov/docs/PRs/29384/coverage/thermal_hydraulics)
- [`xfem`](https://mooseframework.inl.gov/docs/PRs/29384/coverage/xfem)

</details>

## Warnings

- `combined` new line coverage rate 50.00% is less than the suggested 90.0%



This comment will be updated on new commits.

2024-12-13 08:35 UTC, moosebuild commented
Job [Coverage](https://civet.inl.gov/job/2599154/), step Verify coverage on a1cdca1 wanted to post the following:


The following coverage requirement(s) failed:
- `subchannel` coverage rate 87.41% is less than the required 90.0%

2024-12-13 15:45 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/2599908/), step Size check on b8814d6 wanted to post the following:

Warning: This PR changes repo size by 56.87 MiB.

2024-12-13 15:46 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/2599908/), step Size check on b8814d6 wanted to post the following:

Warning: This PR changes repo size by 56.87 MiB.

2024-12-13 16:33 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/2599973/), step Size check on 20000d6 wanted to post the following:

Warning: This PR changes repo size by 56.87 MiB.

2024-12-17 14:29 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/2604255/), step Size check on c1eeb4d wanted to post the following:

Warning: This PR changes repo size by 56.87 MiB.

2024-12-18 00:28 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/2605871/), step Size check on 51746a7 wanted to post the following:

Warning: This PR changes repo size by 56.87 MiB.

2025-01-06 22:28 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/2626250/), step Size check on 2203882 wanted to post the following:

Warning: This PR changes repo size by 55.56 MiB.

2025-01-07 19:34 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/2627599/), step Size check on e66d7b0 wanted to post the following:

Warning: This PR changes repo size by 56.96 MiB.

2025-01-08 18:11 UTC, tanoret commented
Main review comments from the website:

- General Information / Theory: Looks great
- General Information / Running SCM input file: it is wrongly linking to user notes
- General Information / User Notes: The Python script is showing the Jupyter file, not the actual python code
- General Information / Publications List: all good

- SCM Kernels: all good

- Verification and Validation: all good

General:
Link to BISON/heat-conduction (https://mooseframework.inl.gov/modules/heat_conduction/index.html) isn borken

2025-01-13 19:56 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/2634086/), step Size check on e6b7dfa wanted to post the following:

Warning: This PR changes repo size by 56.94 MiB.

2025-01-13 20:21 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/2634254/), step Size check on cd39089 wanted to post the following:

Warning: This PR changes repo size by 56.94 MiB.

2025-01-13 20:38 UTC, tanoret approved these changes, later dismissed
Modifications to the website has been implemented. This is good with me.

2025-01-13 20:39 UTC, loganharbour commented
Still requires recipe merges first.

2025-01-14 13:45 UTC, loganharbour commented
@kyriv1980 documentation is still not passing https://civet.inl.gov/job/2634250/

2025-01-14 16:25 UTC, GiudGiud requested changes
reviewed doco, manual and examples.
The main issue is that most of the examples are not tested, and the few that are are only syntax tests. Considering the scale of subchannel tests, we should rely on CSVDiffs for most of these instead. 
Many of these inputs do not run because they use BISON/Pronghorn

I ll review source and actual tests Friday most likely

2025-01-14 16:25 UTC, GiudGiud commented on modules/doc/sqa_reports.yml
> +        log_stub_files: WARNING
I think there's only a single file to fix here

2025-01-14 16:26 UTC, GiudGiud commented on modules/doc/sqa_reports.yml
> +        log_missing: WARNING
there's a lot more to do here

2025-01-14 17:07 UTC, kyriv1980 commented on modules/combined/test/tests/subchannel_thm_coupling/THM_SC_coupling.i
> +[]
I edited the description of the input file to reflect that.

2025-01-14 17:16 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/2635626/), step Size check on 4548e24 wanted to post the following:

Warning: This PR changes repo size by 56.94 MiB.

2025-01-14 17:45 UTC, kyriv1980 commented on modules/subchannel/examples/ABTR/ABTR_core/core.i
> +    type = FunctorHexagonalLatticeHTC
@tanoret can you take care of this? I am not familiar with this example.

2025-01-14 18:05 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/2635758/), step Size check on 32a2be1 wanted to post the following:

Warning: This PR changes repo size by 56.61 MiB.

2025-01-14 18:17 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/2635824/), step Size check on bfb62ff wanted to post the following:

Warning: This PR changes repo size by 45.83 MiB.

2025-01-14 18:29 UTC, moosebuild commented on large_media
> +Subproject commit 2089825726eb2b80c841f9ae2dbc8cccb8a05208
**Caution!** This contains a submodule update

2025-01-14 18:29 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/2635890/), step Size check on b0f2340 wanted to post the following:

Warning: This PR changes repo size by 45.83 MiB.

2025-01-14 19:11 UTC, moosebuild commented on large_media
> +Subproject commit 2089825726eb2b80c841f9ae2dbc8cccb8a05208
**Caution!** This contains a submodule update

2025-01-14 19:11 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/2637152/), step Size check on a98063a wanted to post the following:

Warning: This PR changes repo size by 45.83 MiB.

2025-01-14 19:23 UTC, moosebuild commented on large_media
> +Subproject commit 2089825726eb2b80c841f9ae2dbc8cccb8a05208
**Caution!** This contains a submodule update

2025-01-14 22:35 UTC, moosebuild commented on large_media
> +Subproject commit 2089825726eb2b80c841f9ae2dbc8cccb8a05208
**Caution!** This contains a submodule update

2025-01-14 22:35 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/2637936/), step Size check on b278279 wanted to post the following:

Warning: This PR changes repo size by 45.83 MiB.

2025-01-14 23:09 UTC, cticenhour requested changes
Reviewed SQA compliance, and found several issues to resolve. Also see comments from @GiudGiud that I unresolved that overlapped with my review. It doesn't look as though those have been addressed.

2025-01-14 23:09 UTC, cticenhour commented on modules/subchannel/doc/content/modules/subchannel/sqa/subchannel_sdd.md
> +!template load file=sqa/module_sdd.md.template category=subchannel module=Porous Flow
This was not committed; unresolving.

2025-01-14 23:09 UTC, cticenhour commented on modules/subchannel/doc/content/modules/subchannel/sqa/subchannel_sdd.md
> +SQA TO DO
I would just get this, system design, and system structure out of the way now. There are lots of examples in the other modules for how these need to be done.

2025-01-14 23:09 UTC, cticenhour commented on modules/subchannel/doc/content/modules/subchannel/sqa/subchannel_srs.md
> +SQA TO DO
Yeah, let's fill these in - they don't need to be terribly long. Lots of examples in the modules.

2025-01-15 12:32 UTC, loganharbour commented
@kyriv1980 please don't move any more content. As I said before I left, this is for me to do. You didn't remove it from history.

2025-01-15 16:25 UTC, kyriv1980 commented on modules/subchannel/doc/content/modules/subchannel/sqa/subchannel_sdd.md
> +!template load file=sqa/module_sdd.md.template category=subchannel module=Porous Flow
I am pretty sure I pressed the commit suggestion button... Maybe I specifically don't have the right to do that this way and only the author of the PR can?

2025-01-15 17:26 UTC, moosebuild commented on large_media
> +Subproject commit 2089825726eb2b80c841f9ae2dbc8cccb8a05208
**Caution!** This contains a submodule update

2025-01-15 17:26 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/2638779/), step Size check on 7316ede wanted to post the following:

Warning: This PR changes repo size by 45.83 MiB.

2025-01-15 20:42 UTC, moosebuild commented on large_media
> +Subproject commit 2089825726eb2b80c841f9ae2dbc8cccb8a05208
**Caution!** This contains a submodule update

2025-01-15 20:42 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/2639304/), step Size check on 963ccd2 wanted to post the following:

Warning: This PR changes repo size by 45.83 MiB.

2025-01-15 23:30 UTC, moosebuild commented
Job [Coverage](https://civet.inl.gov/job/2639347/), step Verify coverage on 963ccd2 wanted to post the following:


The following coverage requirement(s) failed:
- Failed to generate `phase_field` coverage rate (required: 85.0%)

2025-01-16 16:22 UTC, moosebuild commented on large_media
> +Subproject commit 2089825726eb2b80c841f9ae2dbc8cccb8a05208
**Caution!** This contains a submodule update

2025-01-16 16:22 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/2639838/), step Size check on 18c2041 wanted to post the following:

Warning: This PR changes repo size by 45.83 MiB.

2025-01-16 22:07 UTC, moosebuild commented on large_media
> +Subproject commit 2089825726eb2b80c841f9ae2dbc8cccb8a05208
**Caution!** This contains a submodule update

2025-01-16 22:07 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/2640242/), step Size check on 7a430ca wanted to post the following:

Warning: This PR changes repo size by 45.85 MiB.

2025-01-17 17:43 UTC, GiudGiud commented on modules/subchannel/examples/EBR-II/subchannel_SHRT17.pptx
@loganharbour this is a good one for large media and/or deletion 
@kyriv1980 should we keep this or delete it?

2025-01-17 18:30 UTC, kyriv1980 commented on modules/subchannel/examples/EBR-II/subchannel_SHRT17.pptx
Delete.

2025-01-17 19:37 UTC, GiudGiud requested changes
almost done with headers

seems a lot of comments are being resolved without being addressed. I think maybe we are missing a commit due to force pushing?

let's create issues for the various larger issues you wont address here. 
I m thinking:
- the mesh class duplication
- the IC class duplication
- using central objects to describe triangular / quad lattices rather than duplicating in mesh generator code, mesh code, and any object that needs it

2025-01-17 19:37 UTC, GiudGiud commented on modules/subchannel/include/mesh/TriSubChannelMesh.h
> +  virtual const Real & getDuctToRodGap() const { return _duct_to_pin_gap; }
I think it's just this one

2025-01-17 19:37 UTC, GiudGiud commented on modules/subchannel/include/meshgenerators/DetailedTriPinMeshGenerator.h
> + * Mesh generator for fuel pins in a quadrilateral lattice
```suggestion
 * Mesh generator for fuel pins in a hexagonal lattice
```

2025-01-17 19:37 UTC, GiudGiud commented on modules/subchannel/include/meshgenerators/DetailedTriPinMeshGenerator.h
> +  /// Number if rings in the fuel assembly
```suggestion
  /// Number of rings in the fuel assembly
```

2025-01-17 19:37 UTC, GiudGiud commented on modules/subchannel/include/meshgenerators/DetailedTriSubChannelMeshGenerator.h
> +protected:
docstring

2025-01-17 19:37 UTC, GiudGiud commented on modules/subchannel/include/meshgenerators/QuadInterWrapperMeshGenerator.h
> +  /// Distance between the neighbor fuel assemblies, assembly pitch
```suggestion
```

2025-01-17 19:37 UTC, GiudGiud commented on modules/subchannel/include/outputs/QuadSubChannelNormalSliceValues.h
> +  const Real & _height;
docstrings

2025-01-17 19:37 UTC, GiudGiud commented on modules/subchannel/include/postprocessors/SCMPinSurfaceTemperature.h
> +protected:
docstrings

2025-01-17 19:37 UTC, GiudGiud commented on modules/subchannel/include/userobjects/PBSodiumFluidProperties.h
> +
```suggestion
```
this is easy to fix. just do const -> const override

2025-01-17 19:37 UTC, GiudGiud commented on modules/subchannel/include/userobjects/PBSodiumFluidProperties.h
> +class PBSodiumFluidProperties : public SinglePhaseFluidProperties
add docstring

2025-01-17 19:37 UTC, GiudGiud commented on modules/subchannel/include/userobjects/PBSodiumFluidProperties.h
> +  Real _Cp_Tmin;
docstring

2025-01-17 22:02 UTC, kyriv1980 commented on modules/subchannel/examples/ABTR/ABTR_core/wrapper.i
> +# [MultiApps]
@tanoret ?

2025-01-17 22:11 UTC, kyriv1980 commented on modules/subchannel/examples/verification/friction_model_verification/tests
> +    check_input = true
actually these two verification cases are also included in the test folder... so maybe I should just delete them?

2025-01-17 22:11 UTC, kyriv1980 commented on modules/subchannel/examples/ABTR/ABTR_core_transient/abtr_core_mesh.i
> +# following Advanced Burner Test Reactor Preconceptual Design Report
@tanoret

2025-01-17 22:22 UTC, kyriv1980 commented on modules/subchannel/examples/EBR-II/TTC17_nominal.csv
These are the results of the SCM simulations... I renamed them, cause I had run different configurations of the input file, the .py script plots the simulation results using these files. Maybe it would be better to just leave the SCM input files delete everything else and let the user figure things out by themselves?

2025-01-17 22:52 UTC, kyriv1980 commented on modules/subchannel/include/ics/FCTFdisplacementIC.h
> +class FCTFdisplacementIC : public TriSubChannelBaseIC
there is an example that uses this IC. Its in examples/areva_FCTF

2025-01-17 23:19 UTC, GiudGiud commented on modules/subchannel/examples/EBR-II/TTC17_nominal.csv
It would be best to put them in a gold folder. 

They can then serve for both the plotting script and a regression test

2025-01-17 23:20 UTC, GiudGiud commented on modules/subchannel/include/ics/FCTFdisplacementIC.h
> +class FCTFdisplacementIC : public TriSubChannelBaseIC
Exactly. Examples can include source code so we could move the code there. It's best to only have source code that is general to all simulations in the code that users will get

2025-01-17 23:20 UTC, GiudGiud commented on modules/subchannel/include/ics/FCTFdisplacementIC.h
> +class FCTFdisplacementIC : public TriSubChannelBaseIC
Exactly. Examples can include source code so we could move the code there. It's best to only have source code that is general to all simulations in the code that users will get

2025-01-17 23:22 UTC, kyriv1980 commented on modules/subchannel/include/mesh/QuadInterWrapperMesh.h
> +  friend class QuadPinMeshGenerator;
I think it was because these classes needed access to variables and methods from the base class.

2025-01-18 00:06 UTC, moosebuild commented on large_media
> +Subproject commit 2089825726eb2b80c841f9ae2dbc8cccb8a05208
**Caution!** This contains a submodule update

2025-01-18 00:06 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/2641525/), step Clang format on a44e29f wanted to post the following:

Your code requires style changes.  

A patch was auto generated and copied [here](https://mooseframework.inl.gov/docs/PRs/29384/clang_format/style.patch)  
You can directly apply the patch by running, in the top level of your repository:

`curl -s https://mooseframework.inl.gov/docs/PRs/29384/clang_format/style.patch | git apply -v`  

Alternatively, with your repository up to date and in the top level of your repository:

`git clang-format 38df6613c612ccf590839585fd93d1f3f97bbe15`

2025-01-18 00:06 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/2641525/), step Size check on a44e29f wanted to post the following:

Warning: This PR changes repo size by 45.84 MiB.

2025-01-19 05:03 UTC, GiudGiud reviewed
done with headers. i ll go back if I see more opportunities for const
there are quite a few unrelated commits, I think a rebase went wrong

2025-01-19 05:03 UTC, GiudGiud commented on modules/subchannel/src/actions/TriInterWrapperBuildMeshAction.C
> +#include "AddMeshGeneratorAction.h"
```suggestion
```

2025-01-19 05:03 UTC, GiudGiud commented on modules/subchannel/src/actions/TriSubChannelBuildMeshAction.C
> +#include "AddMeshGeneratorAction.h"
```suggestion
```

2025-01-19 05:05 UTC, GiudGiud commented on modules/subchannel/include/auxkernels/SCMBlockedMassFlowRateAux.h
> +  SubChannelMesh & _subchannel_mesh;
```suggestion
  const SubChannelMesh & _subchannel_mesh;
```

2025-01-19 05:06 UTC, GiudGiud commented on modules/subchannel/include/auxkernels/SCMBlockedMassFlowRateAux.h
> +  std::vector<unsigned int> _index_blockage;
```suggestion
  const std::vector<unsigned int> _index_blockage;
```

2025-01-19 13:31 UTC, GiudGiud commented on modules/subchannel/include/auxkernels/SCMBlockedMassFlowRateAux.h
> +  SubChannelMesh & _subchannel_mesh;
same for most of the other auxkernels, postprocessors etc

2025-01-19 13:33 UTC, GiudGiud commented on modules/subchannel/include/base/SubChannelApp.h
> +class SubChannelApp : public MooseApp
a subchannelapp is not a base class of itself.

Maybe something like:
"Application used when running the subchannel module directly"

2025-01-20 15:39 UTC, loganharbour commented
Going to need to redo this due to force pushing.

@kyriv1980 please never force push to someone else's branch without explicitly requesting. You should only be adding to this PR.

2025-01-20 16:52 UTC, kyriv1980 commented on modules/subchannel/include/meshgenerators/DetailedPinMeshGeneratorBase.h
> +class DetailedPinMeshGeneratorBase : public MeshGenerator
I am not comfortable doing that... The mesh generator names are already very big and I don't want to make them bigger. Can we skip this?

2025-01-20 17:13 UTC, kyriv1980 commented on modules/subchannel/include/postprocessors/SCMPlanarMean.h
> + * Calculates an overall Delta of a chosen variable for the subchannel assembly
correct, the docstring is wrong.

2025-01-20 18:04 UTC, kyriv1980 commented on modules/subchannel/include/problems/SubChannel1PhaseProblem.h
> +  CHKERRQ(ierr);
These are instances where I forgot to wrap the function with LibmeshPetscCall()

2025-01-21 00:16 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/2643368/), step Clang format on 1df03d3 wanted to post the following:

Your code requires style changes.  

A patch was auto generated and copied [here](https://mooseframework.inl.gov/docs/PRs/29384/clang_format/style.patch)  
You can directly apply the patch by running, in the top level of your repository:

`curl -s https://mooseframework.inl.gov/docs/PRs/29384/clang_format/style.patch | git apply -v`  

Alternatively, with your repository up to date and in the top level of your repository:

`git clang-format 38df6613c612ccf590839585fd93d1f3f97bbe15`

2025-01-21 00:17 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/2643368/), step Clang format on 1df03d3 wanted to post the following:

Your code requires style changes.  

A patch was auto generated and copied [here](https://mooseframework.inl.gov/docs/PRs/29384/clang_format/style.patch)  
You can directly apply the patch by running, in the top level of your repository:

`curl -s https://mooseframework.inl.gov/docs/PRs/29384/clang_format/style.patch | git apply -v`  

Alternatively, with your repository up to date and in the top level of your repository:

`git clang-format 38df6613c612ccf590839585fd93d1f3f97bbe15`

2025-01-21 00:46 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/2643500/), step Size check on 62427b8 wanted to post the following:

Warning: This PR changes repo size by 20.85 MiB.

2025-01-21 00:47 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/2643500/), step Size check on 62427b8 wanted to post the following:

Warning: This PR changes repo size by 20.85 MiB.

2025-01-21 00:54 UTC, moosebuild commented on large_media
> +Subproject commit abe47e0d60734c40af9dd2d2c4ed2600d7cb8edf
**Caution!** This contains a submodule update

2025-01-21 00:54 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/2643654/), step Size check on 0728d94 wanted to post the following:

Warning: This PR changes repo size by 20.85 MiB.

2025-01-21 15:38 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/2643990/), step Size check on be80ddc wanted to post the following:

Warning: This PR changes repo size by 20.85 MiB.

2025-01-21 17:14 UTC, moosebuild commented on large_media
> +Subproject commit abe47e0d60734c40af9dd2d2c4ed2600d7cb8edf
**Caution!** This contains a submodule update

2025-01-21 17:14 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/2644214/), step Size check on 0ff7917 wanted to post the following:

Warning: This PR changes repo size by 20.85 MiB.

2025-01-21 21:21 UTC, moosebuild commented on large_media
> +Subproject commit abe47e0d60734c40af9dd2d2c4ed2600d7cb8edf
**Caution!** This contains a submodule update

2025-01-21 21:21 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/2644620/), step Size check on 3c38aa5 wanted to post the following:

Warning: This PR changes repo size by 20.85 MiB.

2025-01-21 21:51 UTC, moosebuild commented on large_media
> +Subproject commit abe47e0d60734c40af9dd2d2c4ed2600d7cb8edf
**Caution!** This contains a submodule update

2025-01-21 21:51 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/2644958/), step Size check on d5aa670 wanted to post the following:

Warning: This PR changes repo size by 20.85 MiB.

2025-01-21 22:25 UTC, moosebuild commented on large_media
> +Subproject commit abe47e0d60734c40af9dd2d2c4ed2600d7cb8edf
**Caution!** This contains a submodule update

2025-01-21 22:25 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/2645245/), step Size check on baaa627 wanted to post the following:

Warning: This PR changes repo size by 20.85 MiB.

2025-01-21 22:36 UTC, moosebuild commented on large_media
> +Subproject commit abe47e0d60734c40af9dd2d2c4ed2600d7cb8edf
**Caution!** This contains a submodule update

2025-01-21 22:36 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/2645353/), step Size check on 18c9727 wanted to post the following:

Warning: This PR changes repo size by 20.85 MiB.

2025-01-22 03:37 UTC, moosebuild commented on large_media
> +Subproject commit abe47e0d60734c40af9dd2d2c4ed2600d7cb8edf
**Caution!** This contains a submodule update

2025-01-22 03:37 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/2645616/), step Size check on 5ea8b65 wanted to post the following:

Warning: This PR changes repo size by 20.85 MiB.

2025-01-22 03:50 UTC, moosebuild commented on large_media
> +Subproject commit abe47e0d60734c40af9dd2d2c4ed2600d7cb8edf
**Caution!** This contains a submodule update

2025-01-22 03:50 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/2645699/), step Size check on f81de62 wanted to post the following:

Warning: This PR changes repo size by 20.85 MiB.

2025-01-22 15:25 UTC, moosebuild commented on large_media
> +Subproject commit abe47e0d60734c40af9dd2d2c4ed2600d7cb8edf
**Caution!** This contains a submodule update

2025-01-22 15:25 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/2646590/), step Size check on 04829aa wanted to post the following:

Warning: This PR changes repo size by 20.85 MiB.

2025-01-22 16:34 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/2647028/), step Clang format on 2084454 wanted to post the following:

Your code requires style changes.  

A patch was auto generated and copied [here](https://mooseframework.inl.gov/docs/PRs/29384/clang_format/style.patch)  
You can directly apply the patch by running, in the top level of your repository:

`curl -s https://mooseframework.inl.gov/docs/PRs/29384/clang_format/style.patch | git apply -v`  

Alternatively, with your repository up to date and in the top level of your repository:

`git clang-format bf7a391b5da0313b05c3181a855130d329ea5b12`

2025-01-22 16:34 UTC, moosebuild commented on large_media
> +Subproject commit e37b91d3f54703f5efcf52bc5166a632e50768c1
**Caution!** This contains a submodule update

2025-01-22 16:35 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/2647028/), step Size check on 2084454 wanted to post the following:

Warning: This PR changes repo size by 20.85 MiB.

2025-01-22 16:44 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/2647094/), step Clang format on 00878a7 wanted to post the following:

Your code requires style changes.  

A patch was auto generated and copied [here](https://mooseframework.inl.gov/docs/PRs/29384/clang_format/style.patch)  
You can directly apply the patch by running, in the top level of your repository:

`curl -s https://mooseframework.inl.gov/docs/PRs/29384/clang_format/style.patch | git apply -v`  

Alternatively, with your repository up to date and in the top level of your repository:

`git clang-format bf7a391b5da0313b05c3181a855130d329ea5b12`

2025-01-22 16:44 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/2647094/), step Size check on 00878a7 wanted to post the following:

Warning: This PR changes repo size by 20.85 MiB.

2025-01-22 17:11 UTC, moosebuild commented on large_media
> +Subproject commit e37b91d3f54703f5efcf52bc5166a632e50768c1
**Caution!** This contains a submodule update

2025-01-22 17:11 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/2647231/), step Size check on 7b8ed5f wanted to post the following:

Warning: This PR changes repo size by 20.85 MiB.

2025-01-22 21:24 UTC, moosebuild commented on large_media
> +Subproject commit e37b91d3f54703f5efcf52bc5166a632e50768c1
**Caution!** This contains a submodule update

2025-01-22 21:24 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/2648052/), step Size check on 7cc07d4 wanted to post the following:

Warning: This PR changes repo size by 20.85 MiB.

2025-01-22 23:32 UTC, moosebuild commented on large_media
> +Subproject commit e37b91d3f54703f5efcf52bc5166a632e50768c1
**Caution!** This contains a submodule update

2025-01-22 23:32 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/2648225/), step Size check on 0dd78cc wanted to post the following:

Warning: This PR changes repo size by 20.85 MiB.

2025-01-23 00:46 UTC, GiudGiud commented
how is 0dd78cc a fix ?? We need to move forward here, not pull in old files

2025-01-23 00:49 UTC, kyriv1980 commented
> how is [0dd78cc](https://github.com/idaholab/moose/commit/0dd78cc8cf29a49ee2bbc1c11da476db50e31e46) a fix ?? We need to move forward here, not pull in old files

There was a test failing... so i am trying to see if that was the reason.

2025-01-23 00:55 UTC, loganharbour commented
> > how is [0dd78cc](https://github.com/idaholab/moose/commit/0dd78cc8cf29a49ee2bbc1c11da476db50e31e46) a fix ?? We need to move forward here, not pull in old files
> 
> There was a test failing... so i am trying to see if that was the reason.

Please don't push blindly and cross your fingers. You can build locally, the failure did occur on macs: https://civet.inl.gov/job/2647266/

2025-01-23 15:37 UTC, moosebuild commented on large_media
> +Subproject commit e37b91d3f54703f5efcf52bc5166a632e50768c1
**Caution!** This contains a submodule update

2025-01-23 15:37 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/2648795/), step Size check on 6861519 wanted to post the following:

Warning: This PR changes repo size by 20.85 MiB.

2025-01-23 16:22 UTC, moosebuild commented on large_media
> +Subproject commit e37b91d3f54703f5efcf52bc5166a632e50768c1
**Caution!** This contains a submodule update

2025-01-23 16:22 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/2648863/), step Size check on dca391a wanted to post the following:

Warning: This PR changes repo size by 20.85 MiB.

2025-01-23 16:39 UTC, kyriv1980 commented on modules/subchannel/include/mesh/TriInterWrapperMesh.h
> +  friend class TriInterWrapperMeshGenerator;
Yes. Friend classes are awesome.

2025-01-23 17:05 UTC, loganharbour commented on modules/subchannel/include/mesh/TriInterWrapperMesh.h
> +  friend class TriInterWrapperMeshGenerator;
No. They should not be used

2025-01-23 17:19 UTC, moosebuild commented on large_media
> +Subproject commit e37b91d3f54703f5efcf52bc5166a632e50768c1
**Caution!** This contains a submodule update

2025-01-23 17:19 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/2649172/), step Size check on 0a6d28f wanted to post the following:

Warning: This PR changes repo size by 20.85 MiB.

2025-01-23 17:26 UTC, kyriv1980 commented on modules/subchannel/include/userobjects/PBSodiumFluidProperties.h
> +
This makes some tests in CIVET to fail.

2025-01-23 17:27 UTC, moosebuild commented on large_media
> +Subproject commit e37b91d3f54703f5efcf52bc5166a632e50768c1
**Caution!** This contains a submodule update

2025-01-23 17:27 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/2649238/), step Size check on fea348c wanted to post the following:

Warning: This PR changes repo size by 20.85 MiB.

2025-01-23 17:32 UTC, kyriv1980 commented on modules/subchannel/include/problems/QuadSubChannel1PhaseProblem.h
> +  virtual Real computeAddedHeatPin(unsigned int i_ch, unsigned int iz) override;
That's not the case, because there are cases where the geometry changes and I want to edit the mesh object before the solve.

2025-01-23 17:42 UTC, moosebuild commented on large_media
> +Subproject commit e37b91d3f54703f5efcf52bc5166a632e50768c1
**Caution!** This contains a submodule update

2025-01-23 17:42 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/2649317/), step Size check on afcf458 wanted to post the following:

Warning: This PR changes repo size by 20.85 MiB.

2025-01-27 19:17 UTC, GiudGiud requested changes

2025-01-27 19:17 UTC, GiudGiud commented on modules/subchannel/scripts/index.py
add a test for that script in test/tests/scripts and use a symlink to the script

2025-01-27 19:17 UTC, GiudGiud commented on modules/subchannel/include/userobjects/PBSodiumFluidProperties.h
> +
this means there is a problem with the code then

you must delete this and fix the problem

2025-01-27 19:17 UTC, GiudGiud commented on modules/subchannel/include/userobjects/PBSodiumFluidProperties.h
> +
slakc me the error if you want

2025-01-27 19:17 UTC, GiudGiud commented on modules/subchannel/include/mesh/TriInterWrapperMesh.h
> +  friend class TriInterWrapperMeshGenerator;
delete

2025-01-27 19:17 UTC, GiudGiud commented on modules/subchannel/include/mesh/TriSubChannelMesh.h
> +  friend class TriSubChannel1PhaseProblem;
same

2025-01-27 19:17 UTC, GiudGiud commented on modules/subchannel/include/meshgenerators/DetailedPinMeshGeneratorBase.h
> +class DetailedPinMeshGeneratorBase : public MeshGenerator
it's just three letters, and it makes sense. the SCM meshes dont work for anything else, the reactor meshes work as expected very generally

let's do this now

2025-01-27 19:17 UTC, GiudGiud commented on modules/subchannel/include/meshgenerators/DetailedTriPinMeshGenerator.h
> + * Mesh generator for fuel pins in a triangualar lattice
```suggestion
 * Mesh generator for fuel pins in a triangular lattice
```

2025-01-27 19:17 UTC, GiudGiud commented on modules/subchannel/include/problems/NoSolveProblem.h
> +
```suggestion
```

2025-01-27 19:17 UTC, GiudGiud commented on modules/subchannel/include/meshgenerators/TriPinMeshGenerator.h
> +#include "QuadSubChannelMeshGenerator.h"
```suggestion
```

2025-01-27 19:17 UTC, GiudGiud commented on modules/subchannel/include/outputs/QuadSubChannelNormalSliceValues.h
> +  QuadSubChannelMesh & _mesh;
```suggestion
  const QuadSubChannelMesh & _mesh;
```

2025-01-27 19:17 UTC, GiudGiud commented on modules/subchannel/include/outputs/QuadSubChannelNormalSliceValues.h
> +#include "QuadSubChannelMesh.h"
you might be able to do a forward declaration instead

2025-01-27 19:17 UTC, GiudGiud commented on modules/subchannel/include/postprocessors/SCMPlanarMean.h
> +  SubChannelMesh & _mesh;
```suggestion
  const SubChannelMesh & _mesh;
```
same for the other PPs

2025-01-27 22:14 UTC, GiudGiud requested changes
Let's create an issue for adding parameter groups in Subchannel objects parameters too. There are none at the moment

just have to take a look at the Problem source classes now

2025-01-27 22:14 UTC, GiudGiud commented on modules/subchannel/src/meshgenerators/TriDuctMeshGenerator.C
> +                                unsigned int points_per_layer)
```suggestion
                                unsigned int points_per_layer) const
```

2025-01-27 22:14 UTC, GiudGiud commented on modules/subchannel/src/meshgenerators/TriDuctMeshGenerator.C
> +                                SubdomainID block)
```suggestion
                                SubdomainID block) const
```

2025-01-27 22:14 UTC, GiudGiud commented on modules/subchannel/src/meshgenerators/DetailedQuadSubChannelMeshGenerator.C
> +      Real offset_y = (_ny - 1) * _pitch / 2.0;
is this offset documented? If not let's add an `!alert note` to the documentation

2025-01-27 22:14 UTC, GiudGiud commented on modules/subchannel/src/meshgenerators/DetailedTriSubChannelMeshGenerator.C
> +DetailedTriSubChannelMeshGenerator::translatePoint(Point b, Point translation_vector)
```suggestion
DetailedTriSubChannelMeshGenerator::translatePoint(Point & b, Point & translation_vector)
```

2025-01-27 22:14 UTC, GiudGiud commented on modules/subchannel/src/meshgenerators/QuadInterWrapperMeshGenerator.C
> +#include "libmesh/edge_edge2.h"
same

2025-01-27 22:14 UTC, GiudGiud commented on modules/subchannel/src/meshgenerators/QuadSubChannelMeshGenerator.C
> +#include "libmesh/edge_edge2.h"
same

2025-01-27 22:14 UTC, GiudGiud commented on modules/subchannel/src/meshgenerators/QuadSubChannelMeshGenerator.C
> +  sch_mesh._subch_type = _subch_type;
umm if you dont have all these setters, maybe keep friend here for the sake of time

2025-01-29 00:18 UTC, kyriv1980 commented on modules/subchannel/src/ics/QuadInterWrapperFlowAreaIC.C
> +    // Need to modify later to include the specific side
@tanoret ?

2025-01-29 00:23 UTC, kyriv1980 commented on modules/subchannel/src/ics/QuadInterWrapperWettedPerimIC.C
> +    // Need to consider specific side - will add later
@tanoret ?

2025-01-29 00:37 UTC, kyriv1980 commented on modules/subchannel/src/ics/SCMTriFlowAreaIC.C
> +    standard_area = pitch * (pin_diameter / 2.0 + gap);
This is the default formulation. All dimensions are assumed normal and nobody is touching anything. If we have deformation (pin diameter or duct) these geometric parameters are re-calculated with the deformed dimensions before the start of the solve. This happens inside the solver class.

2025-01-29 01:15 UTC, kyriv1980 commented on modules/subchannel/src/ics/SCMTriWettedPerimIC.C
> +           2.0 / std::sqrt(3.0) * (pin_diameter / 2.0 + gap);
it what the geometry calculation boils down to.

2025-01-29 01:16 UTC, kyriv1980 commented on modules/subchannel/test/tests/problems/interwrapper/tests
> +  [quad_interwrapper]
Different solvers might have slightly different solutions.

2025-01-29 01:16 UTC, kyriv1980 commented on modules/subchannel/test/tests/problems/psbt/tests
> +[Tests]
Different solvers might have slightly different solutions.

2025-01-29 16:17 UTC, kyriv1980 commented on modules/subchannel/src/ics/SCMTriPowerIC.C
> +  _estimate_power.resize(n_rods, 1);
resize(), just gives the size of the Matrix. I removed the initialization to zero.

2025-01-29 16:27 UTC, kyriv1980 commented on modules/subchannel/test/tests/problems/SFR/EBR-II/test.exodiff
> +	w_perim relative 1e-2
I think we can. At least locally the test pass without applying  relative tolerances.

2025-01-29 16:32 UTC, kyriv1980 commented on modules/subchannel/test/tests/mesh/detailed_quad_pin_mesh/coords.i
> +    type = DetailedQuadSubChannelMeshGenerator
n_cells is equal to 2. That's already low.

2025-01-29 16:35 UTC, kyriv1980 commented on modules/subchannel/examples/ABTR/ABTR_core_low_flow/core.i
> +    type = FunctorLinearPecletHexagonalLatticeKappaFluid
@tanoret

2025-01-29 16:40 UTC, kyriv1980 commented on modules/subchannel/include/base/SubChannelApp.h
> +  /// mass flow rate
Need more guidance to do that.

2025-01-29 16:49 UTC, kyriv1980 commented on modules/subchannel/include/ics/QuadInterWrapperBaseIC.h
> +  QuadInterWrapperMesh & _mesh;
if i do this i get: 
 ```In file included from /Users/kyriv/projects/moose/modules/subchannel/build/unity_src/ics_Unity.C:9:
/Users/kyriv/projects/moose/modules/subchannel/src/ics/SCMQuadFlowAreaIC.C:28:52: error: no matching function for call to 'getMesh'
  : QuadSubChannelBaseIC(params), _subchannel_mesh(SCM::getMesh<SubChannelMesh>(_mesh))
                                                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/kyriv/projects/moose/modules/subchannel/build/header_symlinks/SCM.h:9:5: note: candidate function template not viable: no known conversion from 'const QuadSubChannelMesh' to 'MooseMesh &' for 1st argument
    getMesh(MooseMesh & mesh)
    ^
1 error generated.```

2025-01-29 17:05 UTC, kyriv1980 commented on modules/subchannel/include/ics/QuadSubChannelBaseIC.h
> +  QuadSubChannelMesh & getMesh(MooseMesh & mesh);
the third const on line 28 creates problems, but the apart from that it's ok.

2025-01-29 18:34 UTC, kyriv1980 commented on modules/subchannel/include/mesh/QuadSubChannelMesh.h
> +  friend class QuadSubChannelMeshGenerator;
Lets do that after the SCM is merged into MOOSE?

2025-01-29 19:05 UTC, kyriv1980 commented on modules/subchannel/src/ics/TriInterWrapperWettedPerimIC.C
> +      return 3.0 * element_side + 2.0 * gap * std::tan(libMesh::pi / 6.0);
I don't think so. @tanoret ?

2025-01-29 23:00 UTC, kyriv1980 commented on modules/subchannel/src/meshgenerators/TriDuctMeshGenerator.C
> +  if (!mesh_base)
```/Users/kyriv/projects/moose/modules/subchannel/src/meshgenerators/TriDuctMeshGenerator.C:57:8: error: dynamic_cast from rvalue to reference type 'TriSubChannelMesh &'
  if (!dynamic_cast<TriSubChannelMesh &>(mesh_base.get());)
       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/kyriv/projects/moose/modules/subchannel/src/meshgenerators/TriDuctMeshGenerator.C:57:8: error: 'libMesh::MeshBase *' is not a class type
  if (!dynamic_cast<TriSubChannelMesh &>(mesh_base.get());)
       ^                                 ~~~~~~~~~~~~~~~
2 errors generated.```

2025-01-29 23:11 UTC, GiudGiud commented on modules/subchannel/src/meshgenerators/TriDuctMeshGenerator.C
> +  if (!mesh_base)
never mind ignore that

2025-01-29 23:19 UTC, kyriv1980 commented on modules/subchannel/src/meshgenerators/QuadInterWrapperMeshGenerator.C
> +#include "libmesh/edge_edge2.h"
same what?

2025-01-29 23:19 UTC, kyriv1980 commented on modules/subchannel/src/meshgenerators/QuadInterWrapperMeshGenerator.C
> +#include "libmesh/edge_edge2.h"
delete all the libmesh includes?

2025-01-30 18:48 UTC, moosebuild commented on large_media
> +Subproject commit e37b91d3f54703f5efcf52bc5166a632e50768c1
**Caution!** This contains a submodule update

2025-01-30 18:48 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/2660734/), step Size check on 0687cc9 wanted to post the following:

Warning: This PR changes repo size by 16.77 MiB.

2025-01-30 19:44 UTC, moosebuild commented on large_media
> +Subproject commit e37b91d3f54703f5efcf52bc5166a632e50768c1
**Caution!** This contains a submodule update

2025-01-30 19:44 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/2660872/), step Size check on 552a259 wanted to post the following:

Warning: This PR changes repo size by 16.77 MiB.

2025-01-30 21:06 UTC, moosebuild commented on large_media
> +Subproject commit e37b91d3f54703f5efcf52bc5166a632e50768c1
**Caution!** This contains a submodule update

2025-01-30 21:06 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/2661181/), step Size check on 326aa0d wanted to post the following:

Warning: This PR changes repo size by 16.77 MiB.

2025-01-31 00:12 UTC, moosebuild commented on large_media
> +Subproject commit e37b91d3f54703f5efcf52bc5166a632e50768c1
**Caution!** This contains a submodule update

2025-01-31 00:12 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/2661721/), step Size check on dca6837 wanted to post the following:

Warning: This PR changes repo size by 16.77 MiB.

2025-01-31 16:00 UTC, moosebuild commented on large_media
> +Subproject commit e37b91d3f54703f5efcf52bc5166a632e50768c1
**Caution!** This contains a submodule update

2025-01-31 16:00 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/2663162/), step Size check on 0016b9b wanted to post the following:

Warning: This PR changes repo size by 16.77 MiB.

2025-01-31 16:30 UTC, kyriv1980 commented on modules/subchannel/src/ics/SCMTriPowerIC.C
> +  _estimate_power.resize(n_rods, 1);
Actually it seems that I shouldn't have removed the initialization to zero. Estimate power holds the estimated power of each pin. This calculation is done as a summation using the estimated values of the linear heat rate at the pin nodes and uses a trapezoidal integration scheme. This integral is usually different to the power that is assigned by the user due to discretization error, so I scale the actual linear-heat rate that gets assigned to the nodes in order for the power to be as intended by the user. I think that if i don't initialize to zero it gets a random value that messes up the integral calculation of the pin power. Can you suggest of another way to do this? I have noticed that using a PP and integrating over qprime I get the correct user defined total power. But often when I do a balance: Power = Power_out - Power_in = Sum_out (m*h) - Sum_in(m*h) i get an error of about 3-1% less power. Which often depend on the number of axial nodes.

2025-01-31 17:10 UTC, moosebuild commented on large_media
> +Subproject commit e37b91d3f54703f5efcf52bc5166a632e50768c1
**Caution!** This contains a submodule update

2025-01-31 17:10 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/2663275/), step Size check on db9e399 wanted to post the following:

Warning: This PR changes repo size by 16.77 MiB.

2025-01-31 19:04 UTC, moosebuild commented on large_media
> +Subproject commit e37b91d3f54703f5efcf52bc5166a632e50768c1
**Caution!** This contains a submodule update

2025-01-31 19:04 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/2663828/), step Size check on 5ef2365 wanted to post the following:

Warning: This PR changes repo size by 16.77 MiB.

2025-01-31 20:19 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/2663983/), step Size check on 4f6d4d1 wanted to post the following:

Warning: This PR changes repo size by 16.77 MiB.

2025-01-31 21:13 UTC, moosebuild commented on large_media
> +Subproject commit e37b91d3f54703f5efcf52bc5166a632e50768c1
**Caution!** This contains a submodule update

2025-01-31 21:13 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/2664238/), step Size check on fad84e2 wanted to post the following:

Warning: This PR changes repo size by 16.77 MiB.

2025-01-31 22:10 UTC, moosebuild commented on large_media
> +Subproject commit e37b91d3f54703f5efcf52bc5166a632e50768c1
**Caution!** This contains a submodule update

2025-01-31 22:10 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/2664359/), step Size check on 14085de wanted to post the following:

Warning: This PR changes repo size by 16.77 MiB.

2025-02-03 20:43 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/2666997/), step Size check on 6b2a94b wanted to post the following:

Warning: This PR changes repo size by 16.77 MiB.

2025-02-03 21:05 UTC, GiudGiud commented on modules/combined/test/tests/subchannel_thm_coupling/tests
> +  [SCM_check_syntax]
Let's have all of these be csvdiffs

2025-02-03 21:55 UTC, moosebuild commented on large_media
> +Subproject commit e37b91d3f54703f5efcf52bc5166a632e50768c1
**Caution!** This contains a submodule update

2025-02-03 21:55 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/2667322/), step Size check on faa6744 wanted to post the following:

Warning: This PR changes repo size by 16.79 MiB.

2025-02-03 22:01 UTC, GiudGiud requested changes

2025-02-04 05:33 UTC, GiudGiud requested changes
finishing up a second pass on the source then no more comments from me

2025-02-04 05:33 UTC, GiudGiud commented on modules/subchannel/include/postprocessors/SCMPlanarMean.h
> +protected:
docstring

2025-02-04 05:33 UTC, GiudGiud commented on modules/subchannel/src/actions/SubChannelCreateProblemAction.C
> +  params.addParam<std::string>("name", "SubChannel Problem", "The name the problem");
```suggestion
  params.addParam<std::string>("name", "SubChannel Problem", "The name of the problem");
```

2025-02-04 05:33 UTC, GiudGiud commented on modules/subchannel/src/ics/QuadInterWrapperWettedPerimIC.C
> +    // Need to consider specific side - will add later
I dont see one. let s have one

2025-02-04 06:39 UTC, GiudGiud reviewed
will review the other problems tomorrow

2025-02-04 06:39 UTC, GiudGiud commented on modules/subchannel/src/problems/TriInterWrapper1PhaseProblem.C
> +  _console
you should wrap those prints under a _verbose boolean

2025-02-04 06:39 UTC, GiudGiud commented on modules/subchannel/src/problems/TriInterWrapper1PhaseProblem.C
> +  // inlet mass flow flux
```suggestion
  // inlet mass flux
```

2025-02-04 06:39 UTC, GiudGiud commented on modules/subchannel/src/problems/TriInterWrapper1PhaseProblem.C
> +  // summmation for the pressure drop over all subchannels
```suggestion
  // summation for the pressure drop over all subchannels
```

2025-02-04 06:39 UTC, GiudGiud commented on modules/subchannel/src/problems/TriInterWrapper1PhaseProblem.C
> +  // average pressure
```suggestion
  // average pressure drop
```

2025-02-04 06:39 UTC, GiudGiud commented on modules/subchannel/src/problems/TriInterWrapper1PhaseProblem.C
> +          name(), " Computed presurre drop at the following subchannel is less than zero. ", i_ch);
```suggestion
          name(), " Computed pressure drop at the following subchannel is less than zero. ", i_ch);
```
so this problem cannot handle reversed flow?

2025-02-04 06:39 UTC, GiudGiud commented on modules/subchannel/src/problems/TriInterWrapper1PhaseProblem.C
> +    g_new(i_ch) = std::pow(dpz_ave / dpz(i_ch), 0.3) * mass_flux_i(i_ch);
where is the 0.3 coming from?

2025-02-04 06:39 UTC, GiudGiud commented on modules/subchannel/src/problems/TriInterWrapper1PhaseProblem.C
> +        // compute the radial heat conduction through gaps
```suggestion
```

2025-02-04 06:39 UTC, GiudGiud commented on modules/subchannel/src/problems/TriInterWrapper1PhaseProblem.C
> +        // i is always the smallest and first index in the mapping
what is i / ii there? the current channel?

2025-02-04 06:39 UTC, GiudGiud commented on modules/subchannel/src/problems/TriInterWrapper1PhaseProblem.C
> +      e_cond += 0.5 * (thcon_i + thcon_j) * Si * ((*_T_soln)(node_in_j) - (*_T_soln)(node_in_i)) /
@grmnptr had derived for NS that it was better to average 1/k than k iirc. might apply here too

2025-02-04 06:39 UTC, GiudGiud commented on modules/subchannel/src/problems/TriInterWrapper1PhaseProblem.C
> +  while (P_error > _P_tol && P_it < P_it_max)
so this Problem only supports the outer pressure iteration nesting blocks nesting inner temperature & cross flow iterations right?

2025-02-04 06:39 UTC, GiudGiud commented on modules/subchannel/src/problems/TriInterWrapper1PhaseProblem.C
> +  _console << "Power added to coolant is: " << power_out - power_in << " Watt" << std::endl;
```suggestion
```

2025-02-04 20:22 UTC, kyriv1980 commented on modules/subchannel/doc/content/modules/subchannel/general/subchannel_theory.md
> +There are two variations [!cite](kyriakopoulos2022development), [!cite](kyriakopoulos2023demonstration) of the algorithm presented above:
There are 3+1 options.

2025-02-04 20:43 UTC, kyriv1980 commented on modules/subchannel/doc/content/modules/subchannel/v&v/pnnl_12_pin.md
> +The experimental maximum values measured at the subchannel centers are less than the analytically predicted value of $U_{max} = 2 \times U_{average}$ for laminar flow inside a circular pipe. Where a
Where $U_{average}$ is the surface average of the flow profile which is what SCM calculates.

2025-02-04 21:02 UTC, kyriv1980 commented on modules/subchannel/include/mesh/TriSubChannelMesh.h
> +  /// stores the channel pairs for each gap
I don't think we have duct meshgenerators for quad meshes. That's why.

2025-02-04 21:23 UTC, kyriv1980 commented on modules/subchannel/src/problems/TriInterWrapper1PhaseProblem.C
> +    g_new(i_ch) = std::pow(dpz_ave / dpz(i_ch), 0.3) * mass_flux_i(i_ch);
I don't know. This is one of the two function Argonne people wanted to be created because they wanted to create a mass-flow boundary condition that would produce a uniform pressure gradient at the inlet. (given a total mass-flow rate). I vote that we get rid of these functions all-together. What do you think @tanoret ?

2025-02-04 21:28 UTC, kyriv1980 commented on modules/subchannel/src/problems/TriInterWrapper1PhaseProblem.C
> +        // i is always the smallest and first index in the mapping
i is the index of subchannel. From i, i get i_gap which is the index of the gaps around subchannel i. and ii and jj are the indexes of the subchannels around gap i_gap.

2025-02-04 21:29 UTC, kyriv1980 commented on modules/subchannel/src/problems/TriInterWrapper1PhaseProblem.C
> +      e_cond += 0.5 * (thcon_i + thcon_j) * Si * ((*_T_soln)(node_in_j) - (*_T_soln)(node_in_i)) /
@tanoret ?

2025-02-04 21:31 UTC, kyriv1980 commented on modules/subchannel/src/problems/TriInterWrapper1PhaseProblem.C
> +  while (P_error > _P_tol && P_it < P_it_max)
The pressure iteration is the post outer one.

2025-02-04 22:06 UTC, moosebuild commented on large_media
> +Subproject commit e37b91d3f54703f5efcf52bc5166a632e50768c1
**Caution!** This contains a submodule update

2025-02-04 22:06 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/2671102/), step Size check on 50a87f8 wanted to post the following:

Warning: This PR changes repo size by 17.23 MiB.

2025-02-04 22:55 UTC, kyriv1980 commented on modules/subchannel/include/mesh/QuadInterWrapperMesh.h
> +  const Real & getGap() const { return _side_bypass_length; }
the compiler says this added const makes no difference

2025-02-04 23:05 UTC, moosebuild commented on large_media
> +Subproject commit e37b91d3f54703f5efcf52bc5166a632e50768c1
**Caution!** This contains a submodule update

2025-02-04 23:05 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/2671372/), step Size check on cda5e74 wanted to post the following:

Warning: This PR changes repo size by 17.23 MiB.

2025-02-04 23:45 UTC, kyriv1980 commented on modules/subchannel/include/meshgenerators/DetailedPinMeshGeneratorBase.h
> +  /// unheated length of the fuel Pin at the entry of the assembly
Later.

2025-02-04 23:56 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/2671487/), step Clang format on 755b429 wanted to post the following:

Your code requires style changes.  

A patch was auto generated and copied [here](https://mooseframework.inl.gov/docs/PRs/29384/clang_format/style.patch)  
You can directly apply the patch by running, in the top level of your repository:

`curl -s https://mooseframework.inl.gov/docs/PRs/29384/clang_format/style.patch | git apply -v`  

Alternatively, with your repository up to date and in the top level of your repository:

`git clang-format 27ce10fc83d15195a8b4720bb40e08d912459db2`

2025-02-04 23:56 UTC, moosebuild commented on large_media
> +Subproject commit e37b91d3f54703f5efcf52bc5166a632e50768c1
**Caution!** This contains a submodule update

2025-02-04 23:56 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/2671487/), step Size check on 755b429 wanted to post the following:

Warning: This PR changes repo size by 17.23 MiB.

2025-02-05 00:25 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/2671567/), step Clang format on f602a70 wanted to post the following:

Your code requires style changes.  

A patch was auto generated and copied [here](https://mooseframework.inl.gov/docs/PRs/29384/clang_format/style.patch)  
You can directly apply the patch by running, in the top level of your repository:

`curl -s https://mooseframework.inl.gov/docs/PRs/29384/clang_format/style.patch | git apply -v`  

Alternatively, with your repository up to date and in the top level of your repository:

`git clang-format 27ce10fc83d15195a8b4720bb40e08d912459db2`

2025-02-05 00:25 UTC, moosebuild commented on large_media
> +Subproject commit e37b91d3f54703f5efcf52bc5166a632e50768c1
**Caution!** This contains a submodule update

2025-02-05 00:25 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/2671567/), step Size check on f602a70 wanted to post the following:

Warning: This PR changes repo size by 17.80 MiB.

2025-02-05 01:05 UTC, GiudGiud requested changes

2025-02-05 01:34 UTC, GiudGiud commented
The problems are clearly the least modular part of all of it. 
- tons of raw petsc calls, manual memory management
- they combine kernels, bcs, executioners (the solve methods, implicit/explicit), closures/material properties
- there's very little code re-use and a lot of copy-pasting across problems

2025-02-05 01:58 UTC, GiudGiud commented on modules/subchannel/doc/content/modules/subchannel/general/subchannel_theory.md
> +
what about the other friction factor from TK?

2025-02-05 02:27 UTC, GiudGiud commented on modules/subchannel/src/problems/SubChannel1PhaseProblem.C
> +      _T_soln->set(node, _fp->T_from_p_h((*_P_soln)(node) + _P_out, (*_h_soln)(node)));
so what is T_soln used for? strictly output or does it play a role?

2025-02-05 02:34 UTC, GiudGiud commented
The interwrapper problems are very low on coverage. Could you make a test that uses the models that are not covered now?
https://mooseframework.inl.gov/docs/PRs/29384/coverage/subchannel/src/problems/index.html

2025-02-05 02:42 UTC, GiudGiud commented on modules/subchannel/src/problems/TriInterWrapper1PhaseProblem.C
> +        // i is always the smallest and first index in the mapping
so is ii always equal to i?

2025-02-05 02:43 UTC, GiudGiud commented on modules/subchannel/include/meshgenerators/DetailedPinMeshGeneratorBase.h
> +  /// unheated length of the fuel Pin at the entry of the assembly
ok please create the issue and give the number here

2025-02-05 03:07 UTC, GiudGiud commented on modules/subchannel/doc/content/modules/subchannel/general/subchannel_theory.md
> +### Friction factor
is this the default for lateral or axial ? SHould this section be nested under one of the two ?

2025-02-05 03:07 UTC, GiudGiud commented on modules/subchannel/scripts/index.py
add testing to the script. this tester should do fine:
https://mooseframework.inl.gov/python/testers/ImageDiff.html

2025-02-05 15:57 UTC, kyriv1980 commented on modules/subchannel/src/problems/TriInterWrapper1PhaseProblem.C
> +        // i is always the smallest and first index in the mapping
Yes.

2025-02-05 18:44 UTC, kyriv1980 commented on modules/subchannel/src/problems/InterWrapper1PhaseProblem.C
> +      "interpolation_scheme", "central_difference", "Interpolation scheme used for the method.");
I don't think we have implemented this yet. @tanoret

2025-02-05 21:49 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/2674323/), step Clang format on 875d1ef wanted to post the following:

Your code requires style changes.  

A patch was auto generated and copied [here](https://mooseframework.inl.gov/docs/PRs/29384/clang_format/style.patch)  
You can directly apply the patch by running, in the top level of your repository:

`curl -s https://mooseframework.inl.gov/docs/PRs/29384/clang_format/style.patch | git apply -v`  

Alternatively, with your repository up to date and in the top level of your repository:

`git clang-format e5db198fdde4c8655f483c28e129107b678f240b`

2025-02-05 21:49 UTC, moosebuild commented on large_media
> +Subproject commit e37b91d3f54703f5efcf52bc5166a632e50768c1
**Caution!** This contains a submodule update

2025-02-05 21:49 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/2674323/), step Size check on 875d1ef wanted to post the following:

Warning: This PR changes repo size by 17.80 MiB.

2025-02-05 23:12 UTC, kyriv1980 commented on modules/subchannel/src/problems/InterWrapper1PhaseProblem.C
> +  {
this != 0 makes no sense at all, Makes scheme upstream...  when it's central_difference?

2025-02-05 23:52 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/2674751/), step Clang format on 144d262 wanted to post the following:

Your code requires style changes.  

A patch was auto generated and copied [here](https://mooseframework.inl.gov/docs/PRs/29384/clang_format/style.patch)  
You can directly apply the patch by running, in the top level of your repository:

`curl -s https://mooseframework.inl.gov/docs/PRs/29384/clang_format/style.patch | git apply -v`  

Alternatively, with your repository up to date and in the top level of your repository:

`git clang-format e5db198fdde4c8655f483c28e129107b678f240b`

2025-02-05 23:52 UTC, moosebuild commented on large_media
> +Subproject commit e37b91d3f54703f5efcf52bc5166a632e50768c1
**Caution!** This contains a submodule update

2025-02-05 23:52 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/2674751/), step Size check on 144d262 wanted to post the following:

Warning: This PR changes repo size by 17.79 MiB.

2025-02-06 00:20 UTC, kyriv1980 commented on modules/subchannel/src/problems/InterWrapper1PhaseProblem.C
> +        PetscScalar Pe = 0.5;
It's not getting used anyway. Should probably delete or calculate it/ @tanoret ?

2025-02-06 00:22 UTC, kyriv1980 commented on modules/subchannel/src/problems/InterWrapper1PhaseProblem.C
> +    LibmeshPetscCall(VecScale(unity_vec_Wij, _added_K));
@tanoret ???

2025-02-06 00:28 UTC, kyriv1980 commented on modules/subchannel/src/problems/InterWrapper1PhaseProblem.C
> +          auto perimeter = 2.0 * (_subchannel_mesh.getSideX() + _subchannel_mesh.getSideY());
The inter-wrapper solver is a variation of the subchannel solver where the whole assembly takes the role of the pin.

2025-02-06 00:50 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/2674889/), step Clang format on b287e81 wanted to post the following:

Your code requires style changes.  

A patch was auto generated and copied [here](https://mooseframework.inl.gov/docs/PRs/29384/clang_format/style.patch)  
You can directly apply the patch by running, in the top level of your repository:

`curl -s https://mooseframework.inl.gov/docs/PRs/29384/clang_format/style.patch | git apply -v`  

Alternatively, with your repository up to date and in the top level of your repository:

`git clang-format e5db198fdde4c8655f483c28e129107b678f240b`

2025-02-06 00:50 UTC, moosebuild commented on large_media
> +Subproject commit e37b91d3f54703f5efcf52bc5166a632e50768c1
**Caution!** This contains a submodule update

2025-02-06 00:50 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/2674889/), step Size check on b287e81 wanted to post the following:

Warning: This PR changes repo size by 17.79 MiB.

2025-02-06 01:24 UTC, kyriv1980 commented on modules/subchannel/src/problems/TriSubChannel1PhaseProblem.C
> +        subchannel_area += overlapping_pin_area;           // correct surface area
I have already subtracted the pin area before. If the pins are overlapping that's too much area subtracted. Need to add it back.

2025-02-06 01:44 UTC, kyriv1980 commented on modules/subchannel/src/problems/TriSubChannel1PhaseProblem.C
> +  auto w_over_d = (pin_diameter + gap) / pin_diameter;
I update the gap map and the pin diameter when I have displacement (deformation). But you are correct. I forgot to update _duct_to_pin_gap which is what getDuctToPinGap() returns.

2025-02-06 02:20 UTC, kyriv1980 commented on modules/subchannel/src/problems/TriSubChannel1PhaseProblem.C
> +      ar = libMesh::pi * (pin_diameter + wire_diameter) * wire_diameter / 4.0;
It's what the correlations say.

2025-02-06 02:41 UTC, kyriv1980 commented on modules/subchannel/src/problems/TriSubChannel1PhaseProblem.C
> +      auto ReT = 10000.0 * std::pow(10.0, 0.7 * (pitch / pin_diameter - 1));
Yes.

2025-02-06 02:43 UTC, kyriv1980 commented on modules/subchannel/src/problems/TriSubChannel1PhaseProblem.C
> +      auto ReT = 10000.0 * std::pow(10.0, 0.7 * (pitch / pin_diameter - 1));
When Equation 9.105a is used for edge and corner
subchannels, P/D is replaced by W/D, where W = rod diameter plus gap between rod and bundle wall.

2025-02-06 03:10 UTC, moosebuild commented on large_media
> +Subproject commit e37b91d3f54703f5efcf52bc5166a632e50768c1
**Caution!** This contains a submodule update

2025-02-06 03:10 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/2675297/), step Size check on 4048b20 wanted to post the following:

Warning: This PR changes repo size by 17.79 MiB.

2025-02-06 17:21 UTC, kyriv1980 commented on modules/subchannel/include/meshgenerators/DetailedPinMeshGeneratorBase.h
> +  /// unheated length of the fuel Pin at the entry of the assembly
Make an issue in SubChannel or MOOSE?

2025-02-06 17:24 UTC, GiudGiud commented on modules/subchannel/include/meshgenerators/DetailedPinMeshGeneratorBase.h
> +  /// unheated length of the fuel Pin at the entry of the assembly
MOOSE. This all belongs to moose new. Subchannel is dead, long live SCM!

2025-02-06 18:45 UTC, moosebuild commented on large_media
> +Subproject commit e37b91d3f54703f5efcf52bc5166a632e50768c1
**Caution!** This contains a submodule update

2025-02-06 18:45 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/2676359/), step Size check on e9c2933 wanted to post the following:

Warning: This PR changes repo size by 17.80 MiB.

2025-02-07 00:56 UTC, moosebuild commented on large_media
> +Subproject commit e37b91d3f54703f5efcf52bc5166a632e50768c1
**Caution!** This contains a submodule update

2025-02-07 00:56 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/2677481/), step Size check on 68b5741 wanted to post the following:

Warning: This PR changes repo size by 17.79 MiB.

2025-02-10 17:03 UTC, moosebuild commented on large_media
> +Subproject commit e37b91d3f54703f5efcf52bc5166a632e50768c1
**Caution!** This contains a submodule update

2025-02-10 17:03 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/2680374/), step Size check on a4cd0ef wanted to post the following:

Warning: This PR changes repo size by 17.79 MiB.

2025-02-10 17:39 UTC, kyriv1980 commented on modules/subchannel/doc/content/modules/subchannel/general/subchannel_theory.md
> +### Friction factor
There is no friction factor calculation for the lateral direction, only a default concentrated form-loss coefficient.

2025-02-10 20:16 UTC, moosebuild commented on large_media
> +Subproject commit e37b91d3f54703f5efcf52bc5166a632e50768c1
**Caution!** This contains a submodule update

2025-02-10 20:16 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/2680868/), step Size check on 19ee6d1 wanted to post the following:

Warning: This PR changes repo size by 17.80 MiB.

2025-02-10 21:12 UTC, moosebuild commented on large_media
> +Subproject commit e37b91d3f54703f5efcf52bc5166a632e50768c1
**Caution!** This contains a submodule update

2025-02-10 21:13 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/2681151/), step Size check on 6ad7368 wanted to post the following:

Warning: This PR changes repo size by 17.80 MiB.

2025-02-10 22:26 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/2681556/), step Size check on e546f4a wanted to post the following:

Warning: This PR changes repo size by 17.80 MiB.

2025-02-11 00:50 UTC, moosebuild commented on large_media
> +Subproject commit e37b91d3f54703f5efcf52bc5166a632e50768c1
**Caution!** This contains a submodule update

2025-02-11 00:50 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/2681965/), step Size check on 4b22a9c wanted to post the following:

Warning: This PR changes repo size by 17.80 MiB.

2025-02-12 15:46 UTC, GiudGiud commented on modules/subchannel/src/problems/SubChannel1PhaseProblem.C
> +
I think we should check here, at convergence, that the cross flow resistance term did go to zero as desired

2025-02-12 15:54 UTC, GiudGiud commented on modules/subchannel/src/problems/SubChannel1PhaseProblem.C
> +
the basis is that adding resistance to cross flows makes convergence easier, but likely biases the solution.
If there is a good reference for keeping a non-zero cross flow resistance term, we can instead point to that in the documentation

2025-02-12 15:56 UTC, tanoret commented on modules/subchannel/src/problems/SubChannel1PhaseProblem.C
> +
Yes, our multiple papers showing the validation for subchannel. We won't be doing this as I deem is not necessary unless proven otherwise

2025-02-12 16:59 UTC, joshuahansel commented on modules/subchannel/src/problems/SubChannel1PhaseProblem.C
> +
If the claim is that the term should go to zero when the solution converges, then I think the check is important, as it would indicate a significant bug.

If there is no claim that it should go to zero, but instead it's known to be artificial but beneficial to convergence, but deemed an acceptable error based on validation results, that's ok too - we just need to document it as such for clarity.

2025-02-12 19:05 UTC, moosebuild commented on large_media
> +Subproject commit e37b91d3f54703f5efcf52bc5166a632e50768c1
**Caution!** This contains a submodule update

2025-02-12 19:05 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/2685606/), step Size check on f2f94e0 wanted to post the following:

Warning: This PR changes repo size by 17.80 MiB.

2025-02-12 19:49 UTC, lindsayad commented on modules/subchannel/examples/ABR/Pr_SC_main_hc.i
> +    type = MatchedValueBC
`MatchedValueBC` lives in MOOSE FWIW

2025-02-13 18:20 UTC, moosebuild commented on large_media
> +Subproject commit e37b91d3f54703f5efcf52bc5166a632e50768c1
**Caution!** This contains a submodule update

2025-02-13 18:20 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/2688732/), step Size check on 2703058 wanted to post the following:

Warning: This PR changes repo size by 17.80 MiB.

2025-02-17 18:20 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/2695178/), step Clang format on d6643be wanted to post the following:

Your code requires style changes.  

A patch was auto generated and copied [here](https://mooseframework.inl.gov/docs/PRs/29384/clang_format/style.patch)  
You can directly apply the patch by running, in the top level of your repository:

`curl -s https://mooseframework.inl.gov/docs/PRs/29384/clang_format/style.patch | git apply -v`  

Alternatively, with your repository up to date and in the top level of your repository:

`git clang-format b05d63c35c7ca2c192a7177954d5cccf1c6dbe09`

2025-02-17 18:20 UTC, moosebuild commented on large_media
> +Subproject commit e37b91d3f54703f5efcf52bc5166a632e50768c1
**Caution!** This contains a submodule update

2025-02-17 18:20 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/2695178/), step Size check on d6643be wanted to post the following:

Warning: This PR changes repo size by 17.80 MiB.

2025-02-17 22:39 UTC, moosebuild commented on large_media
> +Subproject commit e37b91d3f54703f5efcf52bc5166a632e50768c1
**Caution!** This contains a submodule update

2025-02-17 22:39 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/2695608/), step Size check on 4f6dd1b wanted to post the following:

Warning: This PR changes repo size by 17.80 MiB.

2025-02-18 17:30 UTC, moosebuild commented on large_media
> +Subproject commit e37b91d3f54703f5efcf52bc5166a632e50768c1
**Caution!** This contains a submodule update

2025-02-18 17:30 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/2697059/), step Size check on 28b1440 wanted to post the following:

Warning: This PR changes repo size by 17.80 MiB.

2025-02-18 20:02 UTC, moosebuild commented on large_media
> +Subproject commit e37b91d3f54703f5efcf52bc5166a632e50768c1
**Caution!** This contains a submodule update

2025-02-18 20:02 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/2697430/), step Size check on 00cdf93 wanted to post the following:

Warning: This PR changes repo size by 17.80 MiB.

2025-02-19 00:10 UTC, moosebuild commented on large_media
> +Subproject commit e37b91d3f54703f5efcf52bc5166a632e50768c1
**Caution!** This contains a submodule update

2025-02-19 00:10 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/2698892/), step Size check on 22aa3be wanted to post the following:

Warning: This PR changes repo size by 17.80 MiB.

2025-02-19 00:39 UTC, moosebuild commented on large_media
> +Subproject commit e37b91d3f54703f5efcf52bc5166a632e50768c1
**Caution!** This contains a submodule update

2025-02-19 00:39 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/2698971/), step Size check on 074a814 wanted to post the following:

Warning: This PR changes repo size by 17.80 MiB.

2025-02-19 17:05 UTC, moosebuild commented on large_media
> +Subproject commit e37b91d3f54703f5efcf52bc5166a632e50768c1
**Caution!** This contains a submodule update

2025-02-19 17:06 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/2699938/), step Size check on 08f952a wanted to post the following:

Warning: This PR changes repo size by 17.80 MiB.

2025-02-19 21:51 UTC, moosebuild commented on large_media
> +Subproject commit e37b91d3f54703f5efcf52bc5166a632e50768c1
**Caution!** This contains a submodule update

2025-02-19 21:51 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/2700833/), step Clang format on 6157840 wanted to post the following:

Your code requires style changes.  

A patch was auto generated and copied [here](https://mooseframework.inl.gov/docs/PRs/29384/clang_format/style.patch)  
You can directly apply the patch by running, in the top level of your repository:

`curl -s https://mooseframework.inl.gov/docs/PRs/29384/clang_format/style.patch | git apply -v`  

Alternatively, with your repository up to date and in the top level of your repository:

`git clang-format 220ffa759e0c35da505d31601f46879b44211504`

2025-02-19 21:51 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/2700833/), step Size check on 6157840 wanted to post the following:

Warning: This PR changes repo size by 17.82 MiB.

2025-02-19 23:01 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/2701298/), step Clang format on 00eb847 wanted to post the following:

Your code requires style changes.  

A patch was auto generated and copied [here](https://mooseframework.inl.gov/docs/PRs/29384/clang_format/style.patch)  
You can directly apply the patch by running, in the top level of your repository:

`curl -s https://mooseframework.inl.gov/docs/PRs/29384/clang_format/style.patch | git apply -v`  

Alternatively, with your repository up to date and in the top level of your repository:

`git clang-format 220ffa759e0c35da505d31601f46879b44211504`

2025-02-19 23:01 UTC, moosebuild commented on large_media
> +Subproject commit e37b91d3f54703f5efcf52bc5166a632e50768c1
**Caution!** This contains a submodule update

2025-02-19 23:01 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/2701298/), step Size check on 00eb847 wanted to post the following:

Warning: This PR changes repo size by 17.82 MiB.

2025-02-20 17:26 UTC, moosebuild commented on large_media
> +Subproject commit e37b91d3f54703f5efcf52bc5166a632e50768c1
**Caution!** This contains a submodule update

2025-02-20 17:26 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/2703163/), step Size check on 08ef15c wanted to post the following:

Warning: This PR changes repo size by 17.82 MiB.

2025-02-20 18:52 UTC, moosebuild commented on large_media
> +Subproject commit e37b91d3f54703f5efcf52bc5166a632e50768c1
**Caution!** This contains a submodule update

2025-02-20 18:52 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/2703582/), step Size check on a6f96a6 wanted to post the following:

Warning: This PR changes repo size by 17.82 MiB.

2025-02-20 21:12 UTC, moosebuild commented on large_media
> +Subproject commit e37b91d3f54703f5efcf52bc5166a632e50768c1
**Caution!** This contains a submodule update

2025-02-20 21:23 UTC, moosebuild commented on large_media
> +Subproject commit e37b91d3f54703f5efcf52bc5166a632e50768c1
**Caution!** This contains a submodule update

2025-02-20 21:23 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/2704258/), step Size check on dafe128 wanted to post the following:

Warning: This PR changes repo size by 17.82 MiB.

2025-02-21 01:03 UTC, moosebuild commented on large_media
> +Subproject commit e37b91d3f54703f5efcf52bc5166a632e50768c1
**Caution!** This contains a submodule update

2025-02-21 01:03 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/2705619/), step Size check on e4b2d1c wanted to post the following:

Warning: This PR changes repo size by 17.82 MiB.

2025-02-25 01:52 UTC, GiudGiud reviewed
SQA, build (debug and non unity) and recover testing seem broken

2025-02-25 01:53 UTC, GiudGiud commented on modules/doc/sqa_reports.yml
> +        log_stub_files: WARNING
let's have this change in. There's no much to do and it's SQA related

2025-02-25 01:53 UTC, GiudGiud commented on modules/doc/sqa_reports.yml
> +        log_missing: WARNING
this should be almost resolved now. Let's have it in

2025-02-25 19:34 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/2711182/), step Size check on 344d950 wanted to post the following:

Warning: This PR changes repo size by 19.37 MiB.

2025-02-25 20:44 UTC, GiudGiud commented
please redo this last commit and use CSVDiffs not exodiffs. 
You just added 2MB to your PR

2025-02-25 21:31 UTC, moosebuild commented on large_media
> +Subproject commit e37b91d3f54703f5efcf52bc5166a632e50768c1
**Caution!** This contains a submodule update

2025-02-25 21:31 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/2712003/), step Size check on 9e36916 wanted to post the following:

Warning: This PR changes repo size by 17.87 MiB.

2025-02-25 23:56 UTC, moosebuild commented on large_media
> +Subproject commit e37b91d3f54703f5efcf52bc5166a632e50768c1
**Caution!** This contains a submodule update

2025-02-25 23:56 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/2712639/), step Size check on 2eac643 wanted to post the following:

Warning: This PR changes repo size by 17.87 MiB.

2025-02-26 18:39 UTC, moosebuild commented on large_media
> +Subproject commit e37b91d3f54703f5efcf52bc5166a632e50768c1
**Caution!** This contains a submodule update

2025-02-26 18:39 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/2714537/), step Size check on 9bf319d wanted to post the following:

Warning: This PR changes repo size by 17.87 MiB.

2025-02-26 20:01 UTC, moosebuild commented on large_media
> +Subproject commit e37b91d3f54703f5efcf52bc5166a632e50768c1
**Caution!** This contains a submodule update

2025-02-26 20:01 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/2714885/), step Size check on cc5ae35 wanted to post the following:

Warning: This PR changes repo size by 17.87 MiB.

2025-02-26 20:02 UTC, moosebuild commented on large_media
> +Subproject commit e37b91d3f54703f5efcf52bc5166a632e50768c1
**Caution!** This contains a submodule update

2025-02-26 20:02 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/2714885/), step Size check on cc5ae35 wanted to post the following:

Warning: This PR changes repo size by 17.87 MiB.

2025-02-26 20:08 UTC, moosebuild commented on large_media
> +Subproject commit e37b91d3f54703f5efcf52bc5166a632e50768c1
**Caution!** This contains a submodule update

2025-02-26 20:09 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/2714951/), step Size check on 4a46e39 wanted to post the following:

Warning: This PR changes repo size by 17.87 MiB.

2025-02-27 00:30 UTC, moosebuild commented on large_media
> +Subproject commit e37b91d3f54703f5efcf52bc5166a632e50768c1
**Caution!** This contains a submodule update

2025-02-27 00:30 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/2716299/), step Size check on d09e9a2 wanted to post the following:

Warning: This PR changes repo size by 17.87 MiB.

2025-02-27 16:39 UTC, moosebuild commented on large_media
> +Subproject commit e37b91d3f54703f5efcf52bc5166a632e50768c1
**Caution!** This contains a submodule update

2025-02-27 16:39 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/2717940/), step Size check on c8fb2b2 wanted to post the following:

Warning: This PR changes repo size by 17.87 MiB.

2025-02-27 17:39 UTC, moosebuild commented on large_media
> +Subproject commit e37b91d3f54703f5efcf52bc5166a632e50768c1
**Caution!** This contains a submodule update

2025-02-27 17:39 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/2718315/), step Size check on 2ff5ac2 wanted to post the following:

Warning: This PR changes repo size by 17.87 MiB.

2025-02-27 17:48 UTC, moosebuild commented on large_media
> +Subproject commit e37b91d3f54703f5efcf52bc5166a632e50768c1
**Caution!** This contains a submodule update

2025-02-27 17:48 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/2718432/), step Size check on 021c1b3 wanted to post the following:

Warning: This PR changes repo size by 17.87 MiB.

2025-02-27 17:50 UTC, GiudGiud commented on modules/subchannel/examples/ABTR/ABTR_core/wrapper.i
> +# [MultiApps]
todo still

2025-02-27 17:52 UTC, GiudGiud commented on modules/subchannel/examples/ABTR/ABTR_core_transient/abtr_core_mesh.i
> +# following Advanced Burner Test Reactor Preconceptual Design Report
todo

2025-02-27 18:15 UTC, GiudGiud commented on modules/subchannel/examples/ABTR/ABTR_core/core.i
> +    type = FunctorHexagonalLatticeHTC
will be removed

2025-02-27 18:15 UTC, GiudGiud commented on modules/subchannel/examples/ABTR/ABTR_core/wrapper.i
> +# [MultiApps]
will be removed

2025-02-27 18:28 UTC, GiudGiud commented on modules/subchannel/examples/EBR-II/TTC17_nominal.csv
still todo

2025-02-27 18:33 UTC, moosebuild commented on large_media
> +Subproject commit e37b91d3f54703f5efcf52bc5166a632e50768c1
**Caution!** This contains a submodule update

2025-02-27 18:33 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/2718870/), step Size check on c5fa6d6 wanted to post the following:

Warning: This PR changes repo size by 17.87 MiB.

2025-02-27 18:46 UTC, GiudGiud commented on modules/subchannel/include/mesh/TriInterWrapperMesh.h
> +  friend class TriInterWrapperMeshGenerator;
create an issue for doing later

2025-02-27 18:50 UTC, GiudGiud commented on modules/subchannel/include/userobjects/PBSodiumFluidProperties.h
> +  Real _Cp_Tmin;
todo still

2025-02-27 21:02 UTC, moosebuild commented on large_media
> +Subproject commit e37b91d3f54703f5efcf52bc5166a632e50768c1
**Caution!** This contains a submodule update

2025-02-27 21:02 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/2719476/), step Size check on d072b1e wanted to post the following:

Warning: This PR changes repo size by 17.87 MiB.

2025-02-27 21:24 UTC, GiudGiud commented on modules/subchannel/src/base/SubChannelApp.C
> +const std::string SubChannelApp::DISPLACEMENT = "displacement";
Todo

2025-02-27 21:26 UTC, GiudGiud commented on modules/subchannel/src/ics/QuadInterWrapperFlowAreaIC.C
> +    // Need to modify later to include the specific side
please create an issue

2025-02-27 21:28 UTC, GiudGiud commented on modules/subchannel/test/tests/problems/interwrapper/tests
> +  [quad_interwrapper]
yes that is taken into account by the custom exodiff comparison file

2025-02-27 21:29 UTC, GiudGiud commented on modules/subchannel/test/tests/problems/psbt/tests
> +[Tests]
gold with one, allow some tolerance on the others

2025-02-27 21:31 UTC, GiudGiud commented on modules/subchannel/examples/ABTR/ABTR_core_low_flow/core.i
> +    type = FunctorLinearPecletHexagonalLatticeKappaFluid
to be removed

2025-02-27 21:32 UTC, GiudGiud commented on modules/subchannel/include/base/SubChannelApp.h
> +  /// mass flow rate
ok coming over in a few

2025-02-27 21:32 UTC, GiudGiud commented on modules/subchannel/include/ics/QuadInterWrapperBaseIC.h
> +  QuadInterWrapperMesh & _mesh;
solved byu having a const getter and a non-const one

2025-02-27 21:34 UTC, GiudGiud commented on modules/subchannel/include/mesh/QuadSubChannelMesh.h
> +  friend class QuadSubChannelMeshGenerator;
sure. is there an issue?

2025-02-27 21:34 UTC, GiudGiud commented on modules/subchannel/scripts/index.py
todo

2025-02-27 21:36 UTC, GiudGiud commented on modules/subchannel/src/userobjects/PBSodiumFluidProperties.C
> +  Real A42 = 2.5156e-6;
resolving, just a suggestion

2025-02-27 21:41 UTC, GiudGiud commented on modules/subchannel/src/transfers/InterWrapperSolutionTransferBase.C
> +    mooseError("This transfer works only into multi-app. Correct the 'direction' parameter.");
todo

2025-02-27 21:45 UTC, GiudGiud commented on modules/subchannel/src/postprocessors/SubChannelPointValue.C
> +    _mesh(libMesh::cast_ref<SubChannelMesh &>(_fe_problem.mesh())),
todo, use SCM::getMesh

2025-02-27 21:48 UTC, GiudGiud commented on modules/subchannel/src/postprocessors/SCMPinSurfaceTemperature.C
> +    _mesh(libMesh::cast_ref<SubChannelMesh &>(_fe_problem.mesh())),
todo

2025-02-27 21:48 UTC, GiudGiud commented on modules/subchannel/src/outputs/QuadSubChannelNormalSliceValues.C
> +  InputParameters params = FileOutput::validParams();
todo

2025-02-27 21:52 UTC, GiudGiud commented on modules/subchannel/src/meshgenerators/TriPinMeshGenerator.C
> +  sch_mesh._pin_mesh_exist = true;
todo later as part of friend class rework

2025-02-27 21:53 UTC, GiudGiud commented on modules/subchannel/src/meshgenerators/DetailedQuadSubChannelMeshGenerator.C
> +      Real offset_y = (_ny - 1) * _pitch / 2.0;
todo

2025-02-27 22:01 UTC, GiudGiud commented on modules/subchannel/src/problems/SubChannel1PhaseProblem.C
> +
please document this

2025-02-27 22:02 UTC, GiudGiud commented on modules/subchannel/scripts/index.py
todo

2025-02-27 22:03 UTC, GiudGiud commented on modules/subchannel/doc/content/modules/subchannel/general/subchannel_theory.md
> +### Algorithm variations
maybe later

2025-02-27 22:04 UTC, GiudGiud commented on modules/subchannel/doc/content/modules/subchannel/general/subchannel_theory.md
> +\end{equation}
todo

2025-02-27 22:06 UTC, GiudGiud commented on modules/subchannel/doc/content/source/ics/SCMQuadPowerIC.md
> +This kernel assigns the axial heat rate ([!param](/ICs/SCMQuadPowerIC/variable) = `q_prime`) on the subchannels or pins in the case of a problem with subchannels/pins in a
remove kernel

2025-02-27 22:07 UTC, GiudGiud commented on modules/subchannel/src/problems/TriSubChannel1PhaseProblem.C
> +          auto S_up = 0.5 * ((*_S_flow_soln)(node_top) + (*_S_flow_soln)(node_center)); // TODO:
add

2025-02-27 22:12 UTC, GiudGiud commented on modules/subchannel/src/problems/TriSubChannel1PhaseProblem.C
> +      auto ReT = 10000.0 * std::pow(10.0, 0.7 * (pitch / pin_diameter - 1));
but that is not what you are doing here. you are using the mesh standard pitch and diameter in all cases

2025-02-27 22:13 UTC, GiudGiud commented on modules/subchannel/src/problems/TriSubChannel1PhaseProblem.C
> +TriSubChannel1PhaseProblem::computeFrictionFactor(_friction_args_struct friction_args)
todo

2025-02-27 22:13 UTC, GiudGiud commented on modules/subchannel/src/problems/TriSubChannel1PhaseProblem.C
> +  auto w_over_d = (pin_diameter + gap) / pin_diameter;
add a comment in case we want to revisit this

2025-02-27 22:14 UTC, GiudGiud commented on modules/subchannel/src/problems/TriSubChannel1PhaseProblem.C
> +  auto ws_t = -11.0 * std::log(wire_lead_length / pin_diameter) + 19.0;
todo

2025-02-27 22:16 UTC, GiudGiud commented on modules/subchannel/src/problems/InterWrapper1PhaseProblem.C
> +          auto Nu = 0.023 * std::pow(Re, 0.8) * std::pow(Pr, 0.4);
is it in the docs now?

2025-02-27 22:17 UTC, GiudGiud commented on modules/subchannel/src/problems/InterWrapper1PhaseProblem.C
> +        PetscScalar Pe = 0.5;
delete

2025-02-27 22:18 UTC, GiudGiud commented on modules/subchannel/src/problems/InterWrapper1PhaseProblem.C
> +        auto time_term = _TR * ((*_rho_soln)(node_out)-_rho_soln->old(node_out)) * volume / _dt;
todo in the problem

2025-02-27 22:19 UTC, GiudGiud commented on modules/subchannel/src/problems/InterWrapper1PhaseProblem.C
> +  {
todo later, create an issue please

2025-02-27 22:19 UTC, GiudGiud commented on modules/subchannel/src/problems/InterWrapper1PhaseProblem.C
> +  return params;
add an issue

2025-02-27 22:27 UTC, GiudGiud commented on modules/subchannel/src/userobjects/PBSodiumFluidProperties.C
> +    _console << "Warning - minimum temperature in thermal conductivity caluclation bounded to "
todo

2025-02-27 22:28 UTC, GiudGiud commented on modules/subchannel/include/mesh/QuadInterWrapperMesh.h
> +  const Real & getGap() const { return _side_bypass_length; }
delete the const. returning by const value does not do anything yes

2025-02-27 22:30 UTC, GiudGiud commented on modules/subchannel/doc/content/modules/subchannel/v&v/pnnl_12_pin.md
> +The experimental maximum values measured at the subchannel centers are less than the analytically predicted value of $U_{max} = 2 \times U_{average}$ for laminar flow inside a circular pipe. Where a
ok let s have that in the text

2025-02-27 22:31 UTC, GiudGiud commented on modules/subchannel/doc/content/modules/subchannel/v&v/pnnl_12_pin.md
> +| Case number | Initial Flow $[GPM]$  | Final Flow $[GPM]$ | time $[sec]$ |Power Gradient| $Q_H [kW/pin]$| $Q_L [kW/pin]$ | Re {initial/final} |
broken still. needs a space around |

2025-02-27 22:42 UTC, moosebuild commented on large_media
> +Subproject commit e37b91d3f54703f5efcf52bc5166a632e50768c1
**Caution!** This contains a submodule update

2025-02-27 22:42 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/2719788/), step Size check on 78b93cd wanted to post the following:

Warning: This PR changes repo size by 17.87 MiB.

2025-03-04 21:44 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/2729090/), step Size check on 5029c51 wanted to post the following:

Warning: This PR changes repo size by 17.88 MiB.

2025-03-04 23:10 UTC, kyriv1980 commented on modules/subchannel/src/problems/TriSubChannel1PhaseProblem.C
> +      auto ReT = 10000.0 * std::pow(10.0, 0.7 * (pitch / pin_diameter - 1));
No

2025-03-04 23:10 UTC, moosebuild commented on large_media
> +Subproject commit 1191583486c0aa2ecfb9b276dfd50fe942ecf258
**Caution!** This contains a submodule update

2025-03-04 23:11 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/2729417/), step Size check on f3ba19d wanted to post the following:

Warning: This PR changes repo size by 17.88 MiB.

2025-03-04 23:11 UTC, kyriv1980 commented on modules/subchannel/src/problems/TriSubChannel1PhaseProblem.C
> +      auto ReT = 10000.0 * std::pow(10.0, 0.7 * (pitch / pin_diameter - 1));
I use different coefficients for different types of subchannel.

2025-03-04 23:31 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/2729599/), step Size check on 56c9afd wanted to post the following:

Warning: This PR changes repo size by 17.88 MiB.

2025-03-04 23:35 UTC, GiudGiud commented on modules/subchannel/src/problems/TriSubChannel1PhaseProblem.C
> +      auto ReT = 10000.0 * std::pow(10.0, 0.7 * (pitch / pin_diameter - 1));
how so?
you can see here we get the pitch and pin_diameter for the mesh, not for the channel type. 
```

void
TriSubChannel1PhaseProblem::computeWijPrime(int iblock)
{
  unsigned int last_node = (iblock + 1) * _block_size;
  unsigned int first_node = iblock * _block_size + 1;
  const Real & pitch = _subchannel_mesh.getPitch();
  const Real & pin_diameter = _subchannel_mesh.getPinDiameter();
  const Real & wire_lead_length = _tri_sch_mesh.getWireLeadLength();
  const Real & wire_diameter = _tri_sch_mesh.getWireDiameter();
  for (unsigned int iz = first_node; iz < last_node + 1; iz++)
  {
    auto z_grid = _subchannel_mesh.getZGrid();
    auto dz = z_grid[iz] - z_grid[iz - 1];
    for (unsigned int i_gap = 0; i_gap < _n_gaps; i_gap++)
    {
      auto chans = _subchannel_mesh.getGapChannels(i_gap);
      unsigned int i_ch = chans.first;
      unsigned int j_ch = chans.second;
      auto subch_type1 = _subchannel_mesh.getSubchannelType(i_ch);
      auto subch_type2 = _subchannel_mesh.getSubchannelType(j_ch);
      auto * node_in_i = _subchannel_mesh.getChannelNode(i_ch, iz - 1);
      auto * node_out_i = _subchannel_mesh.getChannelNode(i_ch, iz);
      auto * node_in_j = _subchannel_mesh.getChannelNode(j_ch, iz - 1);
      auto * node_out_j = _subchannel_mesh.getChannelNode(j_ch, iz);
      auto Si_in = (*_S_flow_soln)(node_in_i);
      auto Sj_in = (*_S_flow_soln)(node_in_j);
      auto Si_out = (*_S_flow_soln)(node_out_i);
      auto Sj_out = (*_S_flow_soln)(node_out_j);
      auto S_total = Si_in + Sj_in + Si_out + Sj_out;
      auto Si = 0.5 * (Si_in + Si_out);
      auto Sj = 0.5 * (Sj_in + Sj_out);
      auto w_perim_i = 0.5 * ((*_w_perim_soln)(node_in_i) + (*_w_perim_soln)(node_out_i));
      auto w_perim_j = 0.5 * ((*_w_perim_soln)(node_in_j) + (*_w_perim_soln)(node_out_j));
      auto avg_mu = (1 / S_total) * ((*_mu_soln)(node_out_i)*Si_out + (*_mu_soln)(node_in_i)*Si_in +
                                     (*_mu_soln)(node_out_j)*Sj_out + (*_mu_soln)(node_in_j)*Sj_in);
      auto avg_hD = 4.0 * (Si + Sj) / (w_perim_i + w_perim_j);
      auto avg_massflux =
          0.5 * (((*_mdot_soln)(node_in_i) + (*_mdot_soln)(node_in_j)) / (Si_in + Sj_in) +
                 ((*_mdot_soln)(node_out_i) + (*_mdot_soln)(node_out_j)) / (Si_out + Sj_out));
      auto Re = avg_massflux * avg_hD / avg_mu;
      // crossflow area between channels i,j (dz*gap_width)
      auto gap = _subchannel_mesh.getGapWidth(iz, i_gap);
      auto Sij = dz * gap;
      // Calculation of flow regime
      auto ReL = 320.0 * std::pow(10.0, pitch / pin_diameter - 1);
      auto ReT = 10000.0 * std::pow(10.0, 0.7 * (pitch / pin_diameter - 1));
```
and the ReL and ReT are computed there, with the same value for all gaps

2025-03-04 23:39 UTC, moosebuild commented on large_media
> +Subproject commit 1191583486c0aa2ecfb9b276dfd50fe942ecf258
**Caution!** This contains a submodule update

2025-03-05 16:45 UTC, moosebuild commented on large_media
> +Subproject commit 1191583486c0aa2ecfb9b276dfd50fe942ecf258
**Caution!** This contains a submodule update

2025-03-05 16:45 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/2730891/), step Size check on 26baefe wanted to post the following:

Warning: This PR changes repo size by 17.87 MiB.

2025-03-05 19:25 UTC, kyriv1980 commented on modules/subchannel/src/outputs/QuadSubChannelNormalSliceValues.C
> +  InputParameters params = FileOutput::validParams();
I don't understand what you mean here?

2025-03-05 19:33 UTC, kyriv1980 commented on modules/subchannel/src/problems/InterWrapper1PhaseProblem.C
> +  {
This has been fixed.

2025-03-05 19:40 UTC, GiudGiud commented on modules/subchannel/src/problems/InterWrapper1PhaseProblem.C
> +  {
it has not. you can still see it in the Interwrapper1PhaseProblem

2025-03-05 20:18 UTC, kyriv1980 commented on modules/subchannel/src/problems/TriSubChannel1PhaseProblem.C
> +      auto ReT = 10000.0 * std::pow(10.0, 0.7 * (pitch / pin_diameter - 1));
pin_diameter and pitch are assembly parameters. The rest of the coefficients depend on the subchannel type. ReL and ReT are the Re limits of the transient regime.

2025-03-05 20:22 UTC, kyriv1980 commented on modules/subchannel/src/problems/SubChannel1PhaseProblem.C
> +          auto Nu = 0.023 * std::pow(Re, 0.8) * std::pow(Pr, 0.4);
I added info in the .md files.

2025-03-05 20:38 UTC, GiudGiud commented on modules/subchannel/src/problems/TriSubChannel1PhaseProblem.C
> +      auto ReT = 10000.0 * std::pow(10.0, 0.7 * (pitch / pin_diameter - 1));
now I dont recall well, but from when I checked T&K, I might have seen that ReL and ReT depend on the channel, through the local pitch and diameters

2025-03-05 21:02 UTC, moosebuild commented on large_media
> +Subproject commit 1191583486c0aa2ecfb9b276dfd50fe942ecf258
**Caution!** This contains a submodule update

2025-03-05 21:02 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/2732870/), step Size check on 65cc5ee wanted to post the following:

Warning: This PR changes repo size by 17.87 MiB.

2025-03-05 22:52 UTC, GiudGiud commented on modules/subchannel/src/problems/SubChannel1PhaseProblem.C
> +
See issue #30037

2025-03-05 22:54 UTC, GiudGiud commented on modules/subchannel/examples/EBR-II/TTC17_nominal.csv
@kyriv1980

2025-03-05 22:54 UTC, GiudGiud commented on modules/subchannel/include/mesh/QuadInterWrapperMesh.h
> +  friend class QuadPinMeshGenerator;
See #30027

2025-03-05 22:55 UTC, GiudGiud commented on modules/subchannel/include/mesh/TriInterWrapperMesh.h
> +  friend class TriInterWrapperMeshGenerator;
see #30027

2025-03-05 22:58 UTC, GiudGiud commented on modules/subchannel/src/auxkernels/SCMRZPinQPrimeAux.C
> +}
@kyriv1980

2025-03-05 22:59 UTC, GiudGiud commented on modules/subchannel/src/ics/QuadInterWrapperFlowAreaIC.C
> +    // Need to modify later to include the specific side
See #30030

2025-03-05 22:59 UTC, GiudGiud commented on modules/subchannel/src/ics/QuadInterWrapperWettedPerimIC.C
> +    // Need to consider specific side - will add later
see #30030

2025-03-05 22:59 UTC, GiudGiud commented on modules/subchannel/test/tests/problems/interwrapper/tests
> +  [quad_interwrapper]
see #30031

2025-03-05 22:59 UTC, GiudGiud commented on modules/subchannel/test/tests/problems/psbt/tests
> +[Tests]
see #30031

2025-03-05 22:59 UTC, GiudGiud commented on modules/subchannel/test/tests/problems/discretizations/tests
> +[Tests]
see #30031

2025-03-05 23:00 UTC, GiudGiud commented on modules/subchannel/test/tests/problems/SFR/sodium-19pin/tests
> +[Tests]
see #30031

2025-03-05 23:01 UTC, GiudGiud commented on modules/subchannel/include/mesh/QuadSubChannelMesh.h
> +  friend class QuadSubChannelMeshGenerator;
see #30027

2025-03-05 23:01 UTC, GiudGiud commented on modules/subchannel/scripts/index.py
see #30032

2025-03-05 23:04 UTC, GiudGiud commented on modules/subchannel/src/meshgenerators/DetailedQuadSubChannelMeshGenerator.C
> +      Real offset_y = (_ny - 1) * _pitch / 2.0;
@kyriv1980 
it would be good for the documentation to mention if the mesh is centered on (0,0,0), sort starts with its left bottom corner at 0,0,0

2025-03-05 23:04 UTC, kyriv1980 commented on modules/subchannel/src/auxkernels/SCMRZPinQPrimeAux.C
> +}
I made an issue for that.

2025-03-05 23:04 UTC, GiudGiud commented on modules/subchannel/src/outputs/QuadSubChannelNormalSliceValues.C
> +  InputParameters params = FileOutput::validParams();
@kyriv1980

2025-03-05 23:08 UTC, GiudGiud commented on modules/subchannel/src/auxkernels/SCMRZPinQPrimeAux.C
> +}
this is two  lines of code but ok
which one is it? I dont see it

2025-03-05 23:13 UTC, GiudGiud commented on modules/subchannel/src/userobjects/PBSodiumFluidProperties.C
> +    _console << "Warning - minimum temperature in thermal conductivity caluclation bounded to "
See #30034

2025-03-05 23:14 UTC, GiudGiud commented on modules/subchannel/src/problems/TriInterWrapper1PhaseProblem.C
> +    g_new(i_ch) = std::pow(dpz_ave / dpz(i_ch), 0.3) * mass_flux_i(i_ch);
Get a hold of @tanoret to make a decision or create an issue for documenting these boundary conditions in the problem please

2025-03-05 23:15 UTC, GiudGiud commented on modules/subchannel/src/problems/InterWrapper1PhaseProblem.C
> +  return params;
See #30033

2025-03-05 23:15 UTC, kyriv1980 commented on modules/subchannel/src/auxkernels/SCMRZPinQPrimeAux.C
> +}
#30029

2025-03-05 23:15 UTC, GiudGiud commented on modules/subchannel/src/problems/InterWrapper1PhaseProblem.C
> +  {
create an issue for fixing use of enums in interpolation schemes please

2025-03-05 23:18 UTC, GiudGiud commented on modules/subchannel/src/auxkernels/SCMRZPinQPrimeAux.C
> +}
right. So it s more about the coordinate system, which is a block-by-block quantity rather than a mesh quantity.

2025-03-05 23:19 UTC, GiudGiud commented on modules/subchannel/src/problems/InterWrapper1PhaseProblem.C
> +        auto time_term = _TR * ((*_rho_soln)(node_out)-_rho_soln->old(node_out)) * volume / _dt;
see #30035

2025-03-05 23:21 UTC, GiudGiud commented on modules/subchannel/src/problems/InterWrapper1PhaseProblem.C
> +          auto Nu = 0.023 * std::pow(Re, 0.8) * std::pow(Pr, 0.4);
done

2025-03-05 23:21 UTC, moosebuild commented on large_media
> +Subproject commit 1191583486c0aa2ecfb9b276dfd50fe942ecf258
**Caution!** This contains a submodule update

2025-03-05 23:21 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/2733527/), step Size check on 2ba5844 wanted to post the following:

Warning: This PR changes repo size by 17.87 MiB.

2025-03-05 23:29 UTC, GiudGiud commented on modules/subchannel/src/problems/QuadSubChannel1PhaseProblem.C
> +    auto ReL = std::pow(10, (p_over_d - 1)) * 320.0;
documented as "  /// Todreas-Kazimi NUCLEAR SYSTEMS, second edition, Volume 1, 2011"

it s findable even without the page luckily

2025-03-05 23:30 UTC, GiudGiud commented on modules/subchannel/src/problems/TriSubChannel1PhaseProblem.C
> +          displaced_area = (*_displacement_soln)(node)*pitch;
where did you add the doco?

2025-03-05 23:32 UTC, GiudGiud commented on modules/subchannel/src/problems/TriSubChannel1PhaseProblem.C
> +TriSubChannel1PhaseProblem::computeFrictionFactor(_friction_args_struct friction_args)
@kyriv1980 a struct should follow camel case for the type
```
struct ElemArgThis;
```

2025-03-05 23:33 UTC, GiudGiud commented on modules/subchannel/src/problems/TriSubChannel1PhaseProblem.C
> +          auto S_up = 0.5 * ((*_S_flow_soln)(node_top) + (*_S_flow_soln)(node_center)); // TODO:
still missing

2025-03-05 23:33 UTC, GiudGiud commented on modules/subchannel/doc/content/source/ics/SCMQuadPowerIC.md
> +This kernel assigns the axial heat rate ([!param](/ICs/SCMQuadPowerIC/variable) = `q_prime`) on the subchannels or pins in the case of a problem with subchannels/pins in a
still todo it's not an IC kernel just an IC

2025-03-05 23:34 UTC, GiudGiud commented on modules/subchannel/doc/content/modules/subchannel/general/subchannel_theory.md
> +\end{equation}
where is it addressed?

2025-03-05 23:35 UTC, GiudGiud commented on modules/subchannel/scripts/index.py
see #30032

2025-03-05 23:51 UTC, kyriv1980 commented on modules/subchannel/src/problems/TriSubChannel1PhaseProblem.C
> +          auto S_up = 0.5 * ((*_S_flow_soln)(node_top) + (*_S_flow_soln)(node_center)); // TODO:
fixed that.

2025-03-05 23:55 UTC, kyriv1980 commented on modules/subchannel/doc/content/modules/subchannel/general/subchannel_theory.md
> +\end{equation}
I link the papers that i took the correlations from.

2025-03-06 00:02 UTC, kyriv1980 commented on modules/subchannel/examples/EBR-II/TTC17_nominal.csv
There is an issue for this.

2025-03-06 00:04 UTC, kyriv1980 commented on modules/subchannel/src/outputs/QuadSubChannelNormalSliceValues.C
> +  InputParameters params = FileOutput::validParams();
we created  an issue for this.

2025-03-06 00:04 UTC, moosebuild commented on large_media
> +Subproject commit 1191583486c0aa2ecfb9b276dfd50fe942ecf258
**Caution!** This contains a submodule update

2025-03-06 00:04 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/2733865/), step Size check on a0d33a2 wanted to post the following:

Warning: This PR changes repo size by 17.87 MiB.

2025-03-06 00:07 UTC, kyriv1980 commented on modules/subchannel/src/meshgenerators/DetailedQuadSubChannelMeshGenerator.C
> +      Real offset_y = (_ny - 1) * _pitch / 2.0;
the index location/convention is shown in the user notes.

2025-03-06 00:08 UTC, GiudGiud commented on modules/subchannel/src/outputs/QuadSubChannelNormalSliceValues.C
> +  InputParameters params = FileOutput::validParams();
which one> I dont see it

2025-03-06 00:08 UTC, GiudGiud commented on modules/subchannel/doc/content/modules/subchannel/general/subchannel_theory.md
> +\end{equation}
in which file did you add these links?

2025-03-06 00:09 UTC, GiudGiud commented on modules/subchannel/src/meshgenerators/DetailedQuadSubChannelMeshGenerator.C
> +      Real offset_y = (_ny - 1) * _pitch / 2.0;
the indexing scheme is there, the location is not in the user notes?

2025-03-06 00:11 UTC, kyriv1980 commented on modules/subchannel/src/problems/TriInterWrapper1PhaseProblem.C
> +    g_new(i_ch) = std::pow(dpz_ave / dpz(i_ch), 0.3) * mass_flux_i(i_ch);
I am going to delete those cause nobody is using them.

2025-03-06 00:19 UTC, kyriv1980 commented on modules/subchannel/src/problems/InterWrapper1PhaseProblem.C
> +  {
params.addParam<MooseEnum>(
      "interpolation_scheme", schemes, "Interpolation scheme used for the method.");
      
      PetscScalar
InterWrapper1PhaseProblem::computeInterpolationCoefficients(PetscScalar Peclet)
{
  if (_interpolation_scheme == "upwind")
  {
    return 1.0;
  }
  else if (_interpolation_scheme == "downwind")
  {
    return 0.0;
  }
  else if (_interpolation_scheme == "central_difference")
  {
    return 0.5;
  }
  else if (_interpolation_scheme == "exponential")
  {
    return ((Peclet - 1.0) * std::exp(Peclet) + 1) / (Peclet * (std::exp(Peclet) - 1.) + 1e-10);
  }
  else
  {
    mooseError(name(),
               ": Interpolation scheme should be a string: upwind, downwind, central_difference, "
               "exponential");
  }
}

Its already implemented???? NO???

2025-03-06 00:23 UTC, kyriv1980 commented on modules/subchannel/src/problems/TriSubChannel1PhaseProblem.C
> +          displaced_area = (*_displacement_soln)(node)*pitch;
In user notes.

2025-03-06 00:31 UTC, kyriv1980 commented on modules/subchannel/src/problems/TriSubChannel1PhaseProblem.C
> +TriSubChannel1PhaseProblem::computeFrictionFactor(_friction_args_struct friction_args)
fixed

2025-03-06 00:32 UTC, kyriv1980 commented on modules/subchannel/src/problems/TriSubChannel1PhaseProblem.C
> +      auto ReT = 10000.0 * std::pow(10.0, 0.7 * (pitch / pin_diameter - 1));
There is no such thing as local pitch and diameter. These are only defined assembly-wise. p_over_d is defined for inner subchannels and for outer.

2025-03-06 00:33 UTC, GiudGiud commented on modules/subchannel/src/problems/InterWrapper1PhaseProblem.C
> +  {
it s a mooseEnum that's good

but the way you are comparing it to strings is super slow / low performance. that snwhat my original comment was about

2025-03-06 00:36 UTC, kyriv1980 commented on modules/subchannel/doc/content/modules/subchannel/general/subchannel_theory.md
> +\end{equation}
subchannel_theory.md

2025-03-06 00:42 UTC, moosebuild commented on large_media
> +Subproject commit 1191583486c0aa2ecfb9b276dfd50fe942ecf258
**Caution!** This contains a submodule update

2025-03-06 00:42 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/2734016/), step Size check on bbc857c wanted to post the following:

Warning: This PR changes repo size by 17.86 MiB.

2025-03-06 15:34 UTC, GiudGiud commented on modules/subchannel/doc/content/modules/subchannel/general/subchannel_theory.md
> +### Turbulent enthalpy diffussion
still to fix

2025-03-06 15:35 UTC, GiudGiud commented on modules/subchannel/doc/content/modules/subchannel/general/subchannel_theory.md
> +\end{equation}
you mean this?
```
Additional turbulent mixing parameters are implemented as follows:

- Quadrilateral assembly with bare pins: A scale analysis of the turbulent mixing rate for various Prandtl number flow fields in rod bundles eq 25,Kim and Chung (2001) [!cite](kim2001scale), Modeling of flow blockage in a liquid metal-cooled reactor subassembly with a subchannel analysis code eq 19, Jeong et. al (2005)[!cite](jeong2005modeling).
- Triangular assembly with bare pins: A scale analysis of the turbulent mixing rate for various Prandtl number flow fields in rod bundles eq 25,Kim and Chung (2001) [!cite](kim2001scale).
- Triangular assembly with wire-wrapped pins: Hydrodynamic models and correlations for bare and wire-wrapped hexagonal rod bundles—bundle friction factors, subchannel friction factors and mixing parameters, Cheng and Todreas [!cite](cheng1986hydrodynamic).
```

it's in a different subsection

2025-03-06 16:20 UTC, kyriv1980 commented on modules/subchannel/doc/content/modules/subchannel/general/subchannel_theory.md
> +\end{equation}
Yes.

2025-03-06 16:21 UTC, kyriv1980 commented on modules/subchannel/doc/content/modules/subchannel/general/subchannel_theory.md
> +\end{equation}
That's where all the closure correlations come from.

2025-03-06 16:40 UTC, kyriv1980 commented on modules/subchannel/src/outputs/QuadSubChannelNormalSliceValues.C
> +  InputParameters params = FileOutput::validParams();
https://github.com/idaholab/moose/issues/30033

2025-03-06 16:40 UTC, GiudGiud commented on modules/subchannel/src/meshgenerators/DetailedQuadSubChannelMeshGenerator.C
> +      Real offset_y = (_ny - 1) * _pitch / 2.0;
works for me

2025-03-06 16:41 UTC, moosebuild commented on large_media
> +Subproject commit 1191583486c0aa2ecfb9b276dfd50fe942ecf258
**Caution!** This contains a submodule update

2025-03-06 16:41 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/2735809/), step Size check on d4ddc01 wanted to post the following:

Warning: This PR changes repo size by 17.86 MiB.

2025-03-06 16:41 UTC, GiudGiud commented on modules/subchannel/src/outputs/QuadSubChannelNormalSliceValues.C
> +  InputParameters params = FileOutput::validParams();
This is unrelated. The need here is to suppress parameters, not create groups

2025-03-06 16:51 UTC, kyriv1980 commented on modules/subchannel/src/problems/TriSubChannel1PhaseProblem.C
> +      auto ReT = 10000.0 * std::pow(10.0, 0.7 * (pitch / pin_diameter - 1));
<img width="362" alt="Screenshot 2025-03-06 at 9 51 02 AM" src="https://github.com/user-attachments/assets/ccc5ead1-976e-44d6-a3c0-063910fda88d" />

2025-03-06 16:57 UTC, GiudGiud commented on modules/subchannel/src/problems/TriSubChannel1PhaseProblem.C
> +      auto ReT = 10000.0 * std::pow(10.0, 0.7 * (pitch / pin_diameter - 1));
yes this is the exact proof of what I am saying

Read what you just screenshotted. It should not be a uniform P/D it should be gap dependent because it is different for edge and corner channels

2025-03-06 17:03 UTC, kyriv1980 commented on modules/subchannel/src/problems/TriSubChannel1PhaseProblem.C
> +      auto ReT = 10000.0 * std::pow(10.0, 0.7 * (pitch / pin_diameter - 1));
<img width="415" alt="Screenshot 2025-03-06 at 10 03 26 AM" src="https://github.com/user-attachments/assets/5f86c74a-7372-4432-80ff-3536443c433b" />

2025-03-06 17:04 UTC, kyriv1980 commented on modules/subchannel/src/problems/TriSubChannel1PhaseProblem.C
> +      auto ReT = 10000.0 * std::pow(10.0, 0.7 * (pitch / pin_diameter - 1));
There are only bulk Reynolds number limits defined.

2025-03-06 17:30 UTC, moosebuild commented on large_media
> +Subproject commit 1191583486c0aa2ecfb9b276dfd50fe942ecf258
**Caution!** This contains a submodule update

2025-03-06 17:30 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/2736245/), step Size check on 6db7c5c wanted to post the following:

Warning: This PR changes repo size by 17.86 MiB.

2025-03-06 18:31 UTC, GiudGiud commented on modules/subchannel/src/problems/TriSubChannel1PhaseProblem.C
> +      auto ReT = 10000.0 * std::pow(10.0, 0.7 * (pitch / pin_diameter - 1));
For transition region: f_i = ..... depends on phi_i
phi_i = log(Re_i / Re_iL)/ log(Re_iT  / Re_iL)

these are Reynolds number limits with a i indexing, where i standard for bundle average, interior, edge and corner subchannel. 

This is not implemented fully. It was ok for your cases which were clearly turbulent, it is not for the general case that anyone in MOOSE could encounter.

please create an issue and move on

2025-03-06 18:33 UTC, GiudGiud commented on modules/subchannel/src/problems/TriSubChannel1PhaseProblem.C
> +          auto S_up = 0.5 * ((*_S_flow_soln)(node_top) + (*_S_flow_soln)(node_center)); // TODO:
I still see this
```
          auto S_up = 0.5 * ((*_S_flow_soln)(node_top) + (*_S_flow_soln)(node_center)); // TODO:
```
did you not upload it yet?

2025-03-06 18:53 UTC, kyriv1980 commented on modules/subchannel/src/problems/TriSubChannel1PhaseProblem.C
> +      auto ReT = 10000.0 * std::pow(10.0, 0.7 * (pitch / pin_diameter - 1));
There are no local Re number limits defined for each subchannel type. It makes no sense to make an issue.

2025-03-06 21:49 UTC, moosebuild commented on large_media
> +Subproject commit 1191583486c0aa2ecfb9b276dfd50fe942ecf258
**Caution!** This contains a submodule update

2025-03-06 21:49 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/2737192/), step Size check on 013c5bb wanted to post the following:

Warning: This PR changes repo size by 17.86 MiB.

2025-03-06 23:26 UTC, kyriv1980 commented on modules/subchannel/src/problems/TriSubChannel1PhaseProblem.C
> +      auto ReT = 10000.0 * std::pow(10.0, 0.7 * (pitch / pin_diameter - 1));
fixed it.

2025-03-06 23:35 UTC, kyriv1980 commented on modules/subchannel/src/problems/TriSubChannel1PhaseProblem.C
> +          auto S_up = 0.5 * ((*_S_flow_soln)(node_top) + (*_S_flow_soln)(node_center)); // TODO:
sorry, there was the same issue in a few lines above. Now i Have fixed all.

2025-03-06 23:35 UTC, kyriv1980 commented on modules/subchannel/doc/content/source/ics/SCMQuadPowerIC.md
> +This kernel assigns the axial heat rate ([!param](/ICs/SCMQuadPowerIC/variable) = `q_prime`) on the subchannels or pins in the case of a problem with subchannels/pins in a
fixed

2025-03-06 23:36 UTC, kyriv1980 commented on modules/subchannel/doc/content/modules/subchannel/general/subchannel_theory.md
> +### Turbulent enthalpy diffussion
fixed

2025-03-06 23:41 UTC, moosebuild commented on large_media
> +Subproject commit 1191583486c0aa2ecfb9b276dfd50fe942ecf258
**Caution!** This contains a submodule update

2025-03-07 23:54 UTC, GiudGiud commented on modules/subchannel/src/outputs/QuadSubChannelNormalSliceValues.C
> +  InputParameters params = FileOutput::validParams();
see #30043

2025-03-08 00:04 UTC, GiudGiud commented on modules/subchannel/src/problems/InterWrapper1PhaseProblem.C
> +  {
created #30056

2025-03-08 00:08 UTC, GiudGiud commented on modules/subchannel/src/problems/TriSubChannel1PhaseProblem.C
> +          displaced_area = (*_displacement_soln)(node)*pitch;
This is not saying that the displacement is only normal to the surface of the assembly ? 

```
The 'displacement' variable is used as a way to model a deformed duct. It's a per subchannel variable that affects the calculation of the geometric parameters (wetted perimeter, flow area) [!cite](kyriakopoulos2024validation) of the subchannels next to the duct.
```

Also how is the displacement set? I dont see code to set it. Do you use a special transfer or something?

2025-03-08 02:08 UTC, GiudGiud commented
unless I missed something, this should now pass SQA & tests, except for its interaction with pronghorn

2025-03-08 02:10 UTC, moosebuild commented on large_media
> +Subproject commit 1191583486c0aa2ecfb9b276dfd50fe942ecf258
**Caution!** This contains a submodule update

2025-03-08 02:10 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/2739703/), step Clang format on 06bd1d3 wanted to post the following:

Your code requires style changes.  

A patch was auto generated and copied [here](https://mooseframework.inl.gov/docs/PRs/29384/clang_format/style.patch)  
You can directly apply the patch by running, in the top level of your repository:

`curl -s https://mooseframework.inl.gov/docs/PRs/29384/clang_format/style.patch | git apply -v`  

Alternatively, with your repository up to date and in the top level of your repository:

`git clang-format ca02577acdbfe8866af8b01c08df0e349069965d`

2025-03-08 02:10 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/2739703/), step Size check on 06bd1d3 wanted to post the following:

Warning: This PR changes repo size by 17.86 MiB.

2025-03-08 05:32 UTC, moosebuild commented on large_media
> +Subproject commit 1191583486c0aa2ecfb9b276dfd50fe942ecf258
**Caution!** This contains a submodule update

2025-03-08 05:32 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/2739897/), step Size check on ec9d02f wanted to post the following:

Warning: This PR changes repo size by 17.86 MiB.

2025-03-10 16:06 UTC, moosebuild commented on large_media
> +Subproject commit 1191583486c0aa2ecfb9b276dfd50fe942ecf258
**Caution!** This contains a submodule update

2025-03-10 16:49 UTC, GiudGiud commented
Raised #30065 and #30056 for further needs.

2025-03-10 19:16 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/2742214/), step Clang format on 82967e2 wanted to post the following:

Your code requires style changes.  

A patch was auto generated and copied [here](https://mooseframework.inl.gov/docs/PRs/29384/clang_format/style.patch)  
You can directly apply the patch by running, in the top level of your repository:

`curl -s https://mooseframework.inl.gov/docs/PRs/29384/clang_format/style.patch | git apply -v`  

Alternatively, with your repository up to date and in the top level of your repository:

`git clang-format 8ca331362f19f33b2aef9ebee5fcd5437d71ee2b`

2025-03-10 19:23 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/2742277/), step Size check on 83dd5fc wanted to post the following:

Warning: This PR changes repo size by 17.86 MiB.

2025-03-10 19:31 UTC, moosebuild commented on large_media
> +Subproject commit 1191583486c0aa2ecfb9b276dfd50fe942ecf258
**Caution!** This contains a submodule update

2025-03-10 19:33 UTC, GiudGiud commented
Raised #30067 per a discussion with Lise

2025-03-10 19:40 UTC, GiudGiud commented
Raised #30068 for the missing coverage that was requested but not added

2025-03-10 19:48 UTC, GiudGiud commented on modules/subchannel/src/problems/TriSubChannel1PhaseProblem.C
> +          displaced_area = (*_displacement_soln)(node)*pitch;
Raised #30069

2025-03-10 19:56 UTC, GiudGiud approved these changes
At this point, there are no issues that we have not documented following the INL SQA plan. A lot has already been addressed, and the validation basis has been preserved so ongoing work should be able to proceed with no difficulty. 

I look forward to the resolution of these issues for a general capability that will benefit the community at large, here mostly reactor analysis, and not just the targeted application. 

Big thanks to @loganharbour for handling with expert craft the infrastructure side of things

2025-03-10 20:53 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/2742769/), step Size check on 07f43ec wanted to post the following:

Warning: This PR changes repo size by 17.46 MiB.

2025-03-11 00:45 UTC, cticenhour approved these changes
My outstanding SQA comments have been addressed, or will be addressed in subsequent documented issues. I see no issues.

2025-03-11 14:30 UTC, loganharbour commented
Failures are unrelated except pronghorn, which will be patched.

2025-03-11 14:30 UTC, merged