Adding LinearFVEnthalpyFunctorMaterial #29531
idaholab/moose pull request #29532
Opened 2024-12-12 16:28 UTC by freiler

Closes #29531.

2024-12-12 16:30 UTC, freiler commented
@grmnptr will help with the modification of some of the existing classes in LinearFV to make this PR work properly.
Thanks!

2024-12-12 16:36 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/2596269/), step Clang format on 2171172 wanted to post the following:

Your code requires style changes.  

A patch was auto generated and copied [here](https://mooseframework.inl.gov/docs/PRs/29532/clang_format/style.patch)  
You can directly apply the patch by running, in the top level of your repository:

`curl -s https://mooseframework.inl.gov/docs/PRs/29532/clang_format/style.patch | git apply -v`  

Alternatively, with your repository up to date and in the top level of your repository:

`git clang-format f46a73c68d5b5b22ae0f32d9761a2d13dc8dea15`

2024-12-12 16:41 UTC, GiudGiud reviewed
I think this PR will make more sense once the kernels are introduced. It's not obvious how you want to make this work to me yet

2024-12-12 16:41 UTC, GiudGiud commented on modules/navier_stokes/include/functormaterials/LinearFVEnthalpyFunctorMaterial.h
> +#include "Function.h"
```suggestion
```

2024-12-12 16:41 UTC, GiudGiud commented on modules/navier_stokes/include/functormaterials/LinearFVEnthalpyFunctorMaterial.h
> +class Function;
```suggestion
```

2024-12-12 16:41 UTC, GiudGiud commented on modules/navier_stokes/include/functormaterials/LinearFVEnthalpyFunctorMaterial.h
> +  const SinglePhaseFluidProperties * _fluid;
docstrings

2024-12-12 16:41 UTC, GiudGiud commented on modules/navier_stokes/src/functormaterials/LinearFVEnthalpyFunctorMaterial.C
> +    mooseError(false,
```suggestion
    mooseError(
```

2024-12-12 16:41 UTC, GiudGiud commented on modules/navier_stokes/src/functormaterials/LinearFVEnthalpyFunctorMaterial.C
> +                                { return (*_h_from_p_T_functor)(r, t); });
I m not sure we need this. This new "h_from_p_T" functor could just be replaced by the one the user made ?

2024-12-12 18:13 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/2596605/), step Clang format on 9097b5a wanted to post the following:

Your code requires style changes.  

A patch was auto generated and copied [here](https://mooseframework.inl.gov/docs/PRs/29532/clang_format/style.patch)  
You can directly apply the patch by running, in the top level of your repository:

`curl -s https://mooseframework.inl.gov/docs/PRs/29532/clang_format/style.patch | git apply -v`  

Alternatively, with your repository up to date and in the top level of your repository:

`git clang-format f46a73c68d5b5b22ae0f32d9761a2d13dc8dea15`

2024-12-12 19:23 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/2596880/), step Clang format on f6923d8 wanted to post the following:

Your code requires style changes.  

A patch was auto generated and copied [here](https://mooseframework.inl.gov/docs/PRs/29532/clang_format/style.patch)  
You can directly apply the patch by running, in the top level of your repository:

`curl -s https://mooseframework.inl.gov/docs/PRs/29532/clang_format/style.patch | git apply -v`  

Alternatively, with your repository up to date and in the top level of your repository:

`git clang-format f46a73c68d5b5b22ae0f32d9761a2d13dc8dea15`

2024-12-13 01:43 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/2598863/), step Clang format on bd0ad90 wanted to post the following:

Your code requires style changes.  

A patch was auto generated and copied [here](https://mooseframework.inl.gov/docs/PRs/29532/clang_format/style.patch)  
You can directly apply the patch by running, in the top level of your repository:

`curl -s https://mooseframework.inl.gov/docs/PRs/29532/clang_format/style.patch | git apply -v`  

Alternatively, with your repository up to date and in the top level of your repository:

`git clang-format f46a73c68d5b5b22ae0f32d9761a2d13dc8dea15`

2024-12-17 21:08 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/2605345/), step Clang format on dd1f014 wanted to post the following:

Your code requires style changes.  

A patch was auto generated and copied [here](https://mooseframework.inl.gov/docs/PRs/29532/clang_format/style.patch)  
You can directly apply the patch by running, in the top level of your repository:

`curl -s https://mooseframework.inl.gov/docs/PRs/29532/clang_format/style.patch | git apply -v`  

Alternatively, with your repository up to date and in the top level of your repository:

`git clang-format 38207e829fa6e8719263c8ab300526f41a2bc77e`

2024-12-18 19:23 UTC, tanoret commented
Please remember to add the testing that we previously talked about. These tests are:

- [ ] 1D problem with cp=a+bT and verification against analytical solution
- [ ] 2D problem with wall heating and verifying enthalpy balances (h_dot_out = h_dot_in + q''_wall * A_wall)
- [ ] Equivalent problem in 3D and test against the previous 2D problem
- [ ] Body with variable cp and rho cooling at a fixed heat rate and verify against the analytical solution

Thank you!

2024-12-19 21:15 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/2610052/), step Clang format on 58b6daf wanted to post the following:

Your code requires style changes.  

A patch was auto generated and copied [here](https://mooseframework.inl.gov/docs/PRs/29532/clang_format/style.patch)  
You can directly apply the patch by running, in the top level of your repository:

`curl -s https://mooseframework.inl.gov/docs/PRs/29532/clang_format/style.patch | git apply -v`  

Alternatively, with your repository up to date and in the top level of your repository:

`git clang-format d9397150e6e61be3c4dd09f2fec52867a7fdd489`

2024-12-19 22:43 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/2610740/), step Clang format on 792fcee wanted to post the following:

Your code requires style changes.  

A patch was auto generated and copied [here](https://mooseframework.inl.gov/docs/PRs/29532/clang_format/style.patch)  
You can directly apply the patch by running, in the top level of your repository:

`curl -s https://mooseframework.inl.gov/docs/PRs/29532/clang_format/style.patch | git apply -v`  

Alternatively, with your repository up to date and in the top level of your repository:

`git clang-format d9397150e6e61be3c4dd09f2fec52867a7fdd489`

2024-12-20 03:31 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/2611368/), step Clang format on 5085b85 wanted to post the following:

Your code requires style changes.  

A patch was auto generated and copied [here](https://mooseframework.inl.gov/docs/PRs/29532/clang_format/style.patch)  
You can directly apply the patch by running, in the top level of your repository:

`curl -s https://mooseframework.inl.gov/docs/PRs/29532/clang_format/style.patch | git apply -v`  

Alternatively, with your repository up to date and in the top level of your repository:

`git clang-format d9397150e6e61be3c4dd09f2fec52867a7fdd489`

2024-12-20 18:56 UTC, moosebuild commented
Job [Documentation](https://civet.inl.gov/job/2611847/), step Docs: sync website on 066b4b4 wanted to post the following:

View the site [here](https://mooseframework.inl.gov/docs/PRs/29532/site)

This comment will be updated on new commits.

2025-01-27 16:40 UTC, grmnptr requested changes
Nice work! I have a few comments.

2025-01-27 16:40 UTC, grmnptr commented on modules/navier_stokes/doc/content/source/functormaterials/LinearFVEnthalpyFunctorMaterial.md
> +This Functor Material class is needed when the user wants to solve for the enthalpy conservation equation for the incompressible/weakly-compressible finite-volume implementation of the Navier-Stokes
```suggestion
This Functor Material class is needed when the user wants to solve for the enthalpy conservation for the incompressible/weakly-compressible linear finite-volume implementation of the Navier-Stokes equations.
```

2025-01-27 16:40 UTC, grmnptr commented on modules/navier_stokes/include/functormaterials/LinearFVEnthalpyFunctorMaterial.h
> +  const Moose::Functor<ADReal> & _h;
```suggestion
  const Moose::Functor<Real> & _pressure;
  const Moose::Functor<Real> & _T_fluid;
  const Moose::Functor<Real> & _h;
```

2025-01-27 16:40 UTC, grmnptr commented on modules/navier_stokes/include/functormaterials/LinearFVEnthalpyFunctorMaterial.h
> +  const Moose::Functor<ADReal> & _h;
There is a capability to do this now if I remember correctly (got merged in the break).

2025-01-27 16:40 UTC, grmnptr commented on modules/navier_stokes/include/functormaterials/LinearFVEnthalpyFunctorMaterial.h
> + * be used with AD.
Very nice comment!

2025-01-27 16:40 UTC, grmnptr commented on modules/navier_stokes/src/functormaterials/LinearFVEnthalpyFunctorMaterial.C
> +  params.addClassDescription("Creates functor fluid properties using a (P, T) formulation");
```suggestion
  params.addClassDescription("Creates an enthalpy-temperature (both directions) converter functor material.");
```

2025-01-27 16:40 UTC, grmnptr commented on modules/navier_stokes/src/functormaterials/LinearFVEnthalpyFunctorMaterial.C
> +    _h(getFunctor<ADReal>("h")),
```suggestion
    _pressure(getFunctor<Real>(NS::pressure)),
    _T_fluid(getFunctor<Real>(NS::T_fluid)),
    _h(getFunctor<Real>("h")),
```

2025-01-27 16:40 UTC, grmnptr commented on modules/navier_stokes/src/functormaterials/LinearFVEnthalpyFunctorMaterial.C
> +    _h(getFunctor<ADReal>("h")),
If you rebase on next/devel this should work. Let us know if it doesn't.

2025-01-27 16:40 UTC, grmnptr commented on modules/navier_stokes/src/functormaterials/LinearFVEnthalpyFunctorMaterial.C
> +        { return _fluid->h_from_p_T(raw_value(_pressure(r, t)), raw_value(_T_fluid(r, t))); });
```suggestion
        { return _fluid->h_from_p_T(_pressure(r, t), _T_fluid(r, t)); });
```

2025-01-27 16:40 UTC, grmnptr commented on modules/navier_stokes/src/functormaterials/LinearFVEnthalpyFunctorMaterial.C
> +        { return _fluid->T_from_p_h(raw_value(_pressure(r, t)), raw_value(_h(r, t))); });
```suggestion
        { return _fluid->T_from_p_h(_pressure(r, t), _h(r, t)); });
```

2025-01-27 16:40 UTC, grmnptr commented on modules/navier_stokes/test/tests/finite_volume/wcns/enthalpy_equation/1d_test_h.i
> +  [../]
```suggestion
  []
```

2025-01-27 16:40 UTC, grmnptr commented on modules/navier_stokes/test/tests/finite_volume/wcns/enthalpy_equation/1d_test_h_fp.i
> +  [../]
```suggestion
  []
```

2025-01-27 16:40 UTC, grmnptr commented on modules/navier_stokes/test/tests/finite_volume/wcns/enthalpy_equation/1d_test_h_fp.i
> +    elementid = ${fparse nx-1}
this might not work if you have a distributed mesh (the numbering can be local). Trying a point value postprocessor might be better in that sense

2025-01-27 16:40 UTC, grmnptr commented on modules/navier_stokes/test/tests/finite_volume/wcns/enthalpy_equation/enthalpy_equation.i
> +    ny = 30
```suggestion
    nx = 20
    ny = 10
```

2025-01-27 16:40 UTC, grmnptr commented on modules/navier_stokes/test/tests/finite_volume/wcns/enthalpy_equation/enthalpy_equation.i
> +    ny = 30
Just the make the tests faster and less troublesome to regold.

2025-01-27 16:40 UTC, grmnptr commented on modules/navier_stokes/test/tests/finite_volume/wcns/enthalpy_equation/enthalpy_equation.i
> +    # type = FlibeFluidProperties
```suggestion
```

2025-01-27 16:40 UTC, grmnptr commented on modules/navier_stokes/test/tests/finite_volume/wcns/enthalpy_equation/saline_custom.prp
> +// System      , id , Mol Mass , Mol Frac             , Melt(K) , Var(%) , Reference   , Boil(K) , Var(%) , Reference      , rho_a     , rho_b     , range(K)      , Var(%) , Reference     , mu1_a
I think you can remove this, or add a test that uses saline.

2025-01-27 16:40 UTC, grmnptr commented on modules/navier_stokes/test/tests/finite_volume/wcns/enthalpy_equation/tests
> +    [Analytical_Outlet_Temperature_userdefined]
```suggestion
    [analytical_outlet_temperature_userdefined]
```

2025-01-27 16:40 UTC, grmnptr commented on modules/navier_stokes/test/tests/finite_volume/wcns/enthalpy_equation/tests
> +    [Analytical_Outlet_Temperature_fp]
```suggestion
    [analytical_outlet_temperature_fp]
```

2025-01-27 16:40 UTC, grmnptr commented on modules/navier_stokes/test/tests/finite_volume/wcns/enthalpy_equation/tests
> +[Tests]
I noticed that `enthalpy_equation.i` is not used anywhere. Is that file important? If yes, please add a test for it.

2025-02-05 18:18 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/2673595/), step Clang format on 905bbee wanted to post the following:

Your code requires style changes.  

A patch was auto generated and copied [here](https://mooseframework.inl.gov/docs/PRs/29532/clang_format/style.patch)  
You can directly apply the patch by running, in the top level of your repository:

`curl -s https://mooseframework.inl.gov/docs/PRs/29532/clang_format/style.patch | git apply -v`  

Alternatively, with your repository up to date and in the top level of your repository:

`git clang-format e5db198fdde4c8655f483c28e129107b678f240b`

2025-02-05 18:27 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/2673649/), step Clang format on 208d545 wanted to post the following:

Your code requires style changes.  

A patch was auto generated and copied [here](https://mooseframework.inl.gov/docs/PRs/29532/clang_format/style.patch)  
You can directly apply the patch by running, in the top level of your repository:

`curl -s https://mooseframework.inl.gov/docs/PRs/29532/clang_format/style.patch | git apply -v`  

Alternatively, with your repository up to date and in the top level of your repository:

`git clang-format e5db198fdde4c8655f483c28e129107b678f240b`

2025-02-05 19:03 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/2673727/), step Clang format on 4926558 wanted to post the following:

Your code requires style changes.  

A patch was auto generated and copied [here](https://mooseframework.inl.gov/docs/PRs/29532/clang_format/style.patch)  
You can directly apply the patch by running, in the top level of your repository:

`curl -s https://mooseframework.inl.gov/docs/PRs/29532/clang_format/style.patch | git apply -v`  

Alternatively, with your repository up to date and in the top level of your repository:

`git clang-format e5db198fdde4c8655f483c28e129107b678f240b`

2025-02-06 00:53 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/2675006/), step Clang format on 32054aa wanted to post the following:

Your code requires style changes.  

A patch was auto generated and copied [here](https://mooseframework.inl.gov/docs/PRs/29532/clang_format/style.patch)  
You can directly apply the patch by running, in the top level of your repository:

`curl -s https://mooseframework.inl.gov/docs/PRs/29532/clang_format/style.patch | git apply -v`  

Alternatively, with your repository up to date and in the top level of your repository:

`git clang-format e5db198fdde4c8655f483c28e129107b678f240b`

2025-02-06 00:59 UTC, freiler commented on modules/navier_stokes/test/tests/finite_volume/wcns/enthalpy_equation/1d_test_h.i
> +    cp = 1.
This was taken care thanks.

2025-02-06 01:00 UTC, freiler commented on modules/navier_stokes/test/tests/finite_volume/wcns/enthalpy_equation/1d_test_h_fp.i
> +[]
```suggestion
  allow_renumbering = false
[]
```

2025-02-06 01:01 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/2675057/), step Clang format on e6043b4 wanted to post the following:

Your code requires style changes.  

A patch was auto generated and copied [here](https://mooseframework.inl.gov/docs/PRs/29532/clang_format/style.patch)  
You can directly apply the patch by running, in the top level of your repository:

`curl -s https://mooseframework.inl.gov/docs/PRs/29532/clang_format/style.patch | git apply -v`  

Alternatively, with your repository up to date and in the top level of your repository:

`git clang-format e5db198fdde4c8655f483c28e129107b678f240b`

2025-02-06 01:27 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/2675116/), step Clang format on 3ca67bf wanted to post the following:

Your code requires style changes.  

A patch was auto generated and copied [here](https://mooseframework.inl.gov/docs/PRs/29532/clang_format/style.patch)  
You can directly apply the patch by running, in the top level of your repository:

`curl -s https://mooseframework.inl.gov/docs/PRs/29532/clang_format/style.patch | git apply -v`  

Alternatively, with your repository up to date and in the top level of your repository:

`git clang-format e5db198fdde4c8655f483c28e129107b678f240b`

2025-02-06 01:29 UTC, freiler commented on modules/navier_stokes/test/tests/finite_volume/wcns/enthalpy_equation/tests
> +[Tests]
added an exodiff test

2025-02-06 01:30 UTC, freiler commented on modules/navier_stokes/test/tests/finite_volume/wcns/enthalpy_equation/saline_custom.prp
> +// System      , id , Mol Mass , Mol Frac             , Melt(K) , Var(%) , Reference   , Boil(K) , Var(%) , Reference      , rho_a     , rho_b     , range(K)      , Var(%) , Reference     , mu1_a
removed thanks

2025-02-06 01:30 UTC, freiler commented on modules/navier_stokes/test/tests/finite_volume/wcns/enthalpy_equation/enthalpy_equation.i
> +    ny = 30
decreased the nx and ny

2025-02-06 01:34 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/2675167/), step Clang format on 52e771f wanted to post the following:

Your code requires style changes.  

A patch was auto generated and copied [here](https://mooseframework.inl.gov/docs/PRs/29532/clang_format/style.patch)  
You can directly apply the patch by running, in the top level of your repository:

`curl -s https://mooseframework.inl.gov/docs/PRs/29532/clang_format/style.patch | git apply -v`  

Alternatively, with your repository up to date and in the top level of your repository:

`git clang-format e5db198fdde4c8655f483c28e129107b678f240b`

2025-02-07 19:59 UTC, grmnptr requested changes
Just some minor cosmetics, this is the final review from my side.

2025-02-07 19:59 UTC, grmnptr commented on modules/navier_stokes/doc/content/source/functormaterials/LinearFVEnthalpyFunctorMaterial.md
> +When solving the enthalpy conservation equation and obtaining the specific enthalpy ${h} as the solution, two functors are required.
```suggestion
When solving the enthalpy conservation equation and obtaining the specific enthalpy ($h$) as the solution, two functors are required.
```

2025-02-07 19:59 UTC, grmnptr commented on modules/navier_stokes/doc/content/source/functormaterials/LinearFVEnthalpyFunctorMaterial.md
> +In this input, a `LinearFVEnthalpyFunctorMaterial` is defined to solve for a 1D heated channel using Lead fluid properties with a fixed mass flux.
```suggestion
In this input, a `LinearFVEnthalpyFunctorMaterial` is defined to solve for a 1D heated channel using lead fluid properties with a fixed mass flux.
```

2025-02-07 19:59 UTC, grmnptr commented on modules/navier_stokes/doc/content/source/functormaterials/LinearFVEnthalpyFunctorMaterial.md
> +## Example input syntax 1: Fluid Properties
Beautiful example!

2025-02-07 19:59 UTC, grmnptr commented on modules/navier_stokes/include/functormaterials/LinearFVEnthalpyFunctorMaterial.h
> +/**e
```suggestion
/**
```

2025-02-07 19:59 UTC, grmnptr commented on modules/navier_stokes/include/functormaterials/LinearFVEnthalpyFunctorMaterial.h
> +  /// Materials inherit from ADFunctorInterface
```suggestion
  /// Variables, treated as functors
```

2025-02-07 19:59 UTC, grmnptr commented on modules/navier_stokes/include/functormaterials/LinearFVEnthalpyFunctorMaterial.h
> +  /// The fluid properties that containt the h from Tconversion routines
```suggestion
  /// The fluid properties that contain the h from T conversion routines
```

2025-02-07 19:59 UTC, grmnptr commented on modules/navier_stokes/include/physics/WCNSLinearFVFluidHeatTransferPhysics.h
> +  bool _solve_for_enthalpy;
```suggestion
  /// User-selected option to solve for enthalpy
  const bool _solve_for_enthalpy;
```

2025-02-07 19:59 UTC, grmnptr commented on modules/navier_stokes/src/functormaterials/LinearFVEnthalpyFunctorMaterial.C
> +  params.addRequiredParam<MooseFunctorName>("h", "Specific Enthalpy");
```suggestion
  params.addRequiredParam<MooseFunctorName>(NS::specific_enthalpy, "Specific Enthalpy");
```

2025-02-07 19:59 UTC, grmnptr commented on modules/navier_stokes/src/functormaterials/LinearFVEnthalpyFunctorMaterial.C
> +    _h(getFunctor<Real>("h")),
```suggestion
    _h(getFunctor<Real>(NS::specific_enthalpy)),
```

2025-02-07 19:59 UTC, grmnptr commented on modules/navier_stokes/src/functormaterials/LinearFVEnthalpyFunctorMaterial.C
> +
```suggestion
```

2025-02-07 19:59 UTC, grmnptr commented on modules/navier_stokes/src/functormaterials/LinearFVEnthalpyFunctorMaterial.C
> +  // Set material properties functors
```suggestion
  // Set material property functors
```

2025-02-07 19:59 UTC, grmnptr commented on modules/navier_stokes/src/linearfvkernels/LinearFVEnergyAdvection.C
> +    paramError("cp", "cp should be specified for temperature advection");
Nice error check!

2025-02-07 19:59 UTC, grmnptr commented on modules/navier_stokes/test/tests/finite_volume/ins/channel-flow/linear-segregated/steady-transient-compare/common-blocks.i
> +    advected_quantity = temperature
Just a note for the future: at some point we can try to detect this automatically.

2025-02-07 19:59 UTC, grmnptr commented on modules/navier_stokes/test/tests/finite_volume/wcns/enthalpy_equation/tests
> +    [../]
```suggestion
    []
```

2025-02-07 20:07 UTC, freiler commented on modules/navier_stokes/test/tests/finite_volume/ins/channel-flow/linear-segregated/steady-transient-compare/common-blocks.i
> +    advected_quantity = temperature
The inital plan was defining special variables right?

2025-02-07 20:07 UTC, freiler commented on modules/navier_stokes/src/linearfvkernels/LinearFVEnergyAdvection.C
> +    paramError("cp", "cp should be specified for temperature advection");
Thanks!

2025-02-07 20:37 UTC, grmnptr requested changes
Cool

2025-02-07 20:37 UTC, grmnptr commented on modules/navier_stokes/doc/content/source/linearfvkernels/LinearFVEnergyAdvection.md
> +This kernel currently supports the advection of specific enthalpy $h$ or temperature $T$. Important consideration: Temperature advection is only supported for constant specific heat, where $h$ can be
```suggestion
This kernel currently supports the advection of specific enthalpy $h$ or temperature $T$. Important consideration: Temperature advection is only supported for constant specific heat, where $h$ can be defined as $h=c_p T$. For variable $c_p$, the user should use the enthalpy formulation. Parameter [!param](/LinearFVKernels/LinearFVEnergyAdvection/advected_quantity) lets the user select "enthalpy" or "temperature".
```

2025-02-07 21:12 UTC, GiudGiud commented on modules/navier_stokes/test/tests/finite_volume/ins/channel-flow/linear-segregated/steady-transient-compare/common-blocks.i
> +    advected_quantity = temperature
this isnt great (advected is cp T not T) but in the optics of using Physics instead anyway I dont mind

2025-02-07 21:13 UTC, GiudGiud commented on modules/navier_stokes/test/tests/finite_volume/ins/channel-flow/linear-segregated/steady-transient-compare/common-blocks.i
> +    advected_quantity = temperature
this isnt great (advected is cp T not T) but in the optics of using Physics instead anyway I dont mind

2025-02-11 01:39 UTC, GiudGiud requested changes

2025-02-11 01:39 UTC, GiudGiud commented on modules/navier_stokes/doc/content/source/functormaterials/LinearFVEnthalpyFunctorMaterial.md
> +  h(T) = \int_{T_{ref}}^{T} c_p(T)dT + h_{ref},
```suggestion
  h(T) = \int_{T_{ref}}^{T} c_p(p, T')dT' + h_{ref},
```

2025-02-11 01:39 UTC, GiudGiud commented on modules/navier_stokes/doc/content/source/functormaterials/LinearFVEnthalpyFunctorMaterial.md
> +This Functor Material class is needed when the user wants to solve for the enthalpy conservation for the incompressible/weakly-compressible linear finite-volume implementation of the Navier-Stokes eq
```suggestion
This [FunctorMaterial](syntax/FunctorMaterials/index.md) class is needed when the user wants to solve for the enthalpy conservation for the linear finite-volume implementation of the incompressible/weakly-compressible Navier-Stokes equations.
```

2025-02-11 01:39 UTC, GiudGiud commented on modules/navier_stokes/doc/content/source/functormaterials/LinearFVEnthalpyFunctorMaterial.md
> +- $c_p(T)$ is the temperature-dependent specific heat
```suggestion
- $c_p(p, T)$ is the pressure and temperature-dependent specific heat
```

2025-02-11 01:39 UTC, GiudGiud commented on modules/navier_stokes/src/functormaterials/LinearFVEnthalpyFunctorMaterial.C
> +      "Creates an enthalpy-temperature (both directions) converter functor material.");
```suggestion
      "Creates functors for conversions between specific enthalpy and temperature");
```

2025-02-11 01:39 UTC, GiudGiud commented on modules/navier_stokes/src/functormaterials/LinearFVEnthalpyFunctorMaterial.C
> +               "no `fp` and `h_from_p_T_functor` and `T_from_p_h_functor`.");
```suggestion
               "no `fp` and  both`h_from_p_T_functor` and `T_from_p_h_functor` are provided.");
```

2025-02-11 01:39 UTC, GiudGiud commented on modules/navier_stokes/doc/content/source/functormaterials/LinearFVEnthalpyFunctorMaterial.md
> +
```suggestion

!alert warning
If using user-defined properties, it is the responsibility of the user to update these properties often enough. For example auxiliary variable properties would only be updated at the end of every time step by default, which would introduce a lag. 
```

2025-02-11 01:39 UTC, GiudGiud commented on modules/navier_stokes/test/tests/finite_volume/wcns/enthalpy_equation/tests
> +    [2D_enthalpy_channel]
wrong nesting. The requirement says 1D

2025-02-11 05:50 UTC, freiler commented on modules/navier_stokes/test/tests/finite_volume/wcns/enthalpy_equation/tests
> +    [2D_enthalpy_channel]
added 2D

2025-02-11 05:51 UTC, GiudGiud commented on modules/navier_stokes/test/tests/finite_volume/wcns/enthalpy_equation/tests
> +    [2D_enthalpy_channel]
still nested under 1D

2025-02-11 05:52 UTC, GiudGiud commented on modules/navier_stokes/test/tests/finite_volume/wcns/enthalpy_equation/tests
> +    [2D_enthalpy_channel]
ok

2025-02-11 05:52 UTC, GiudGiud submitted a review, later dismissed

2025-02-12 21:28 UTC, GiudGiud commented on framework/src/userobjects/UserObject.C
> -              "We expect the system to conceptually be nonlinear or linear.");
this is for a solution user object (or similar?) that would be working on an auxvariable

2025-02-12 21:28 UTC, GiudGiud approved these changes

2025-02-12 21:44 UTC, grmnptr commented on framework/src/userobjects/UserObject.C
> -              "We expect the system to conceptually be nonlinear or linear.");
I can raise this error to the less abstract levels for sure. But at this point PF was using user objects on auxkernels and we just didn't see it because we defaulted to the 0th solversystem at object creation.

2025-02-12 21:49 UTC, GiudGiud commented on framework/src/userobjects/UserObject.C
> -              "We expect the system to conceptually be nonlinear or linear.");
it s fine for me to allow UOs on auxvariables.

2025-02-12 21:55 UTC, grmnptr commented on framework/src/userobjects/UserObject.C
> -              "We expect the system to conceptually be nonlinear or linear.");
@lindsayad , hey we needed this to be able to do BCs on auxvariables. What is your opinion on this? It is mostly the changes in the FEProblemBase class.

2025-02-12 22:26 UTC, moosebuild commented
Job [Conda (ARM Mac)](https://civet.inl.gov/job/2686470/) on 048e9cb : invalidated by @grmnptr

2025-02-13 19:28 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/2688828/), step Clang format on 637fd72 wanted to post the following:

Your code requires style changes.  

A patch was auto generated and copied [here](https://mooseframework.inl.gov/docs/PRs/29532/clang_format/style.patch)  
You can directly apply the patch by running, in the top level of your repository:

`curl -s https://mooseframework.inl.gov/docs/PRs/29532/clang_format/style.patch | git apply -v`  

Alternatively, with your repository up to date and in the top level of your repository:

`git clang-format c8ca621a331f92c50b52b8db2eb5c4f89fc38ba1`

2025-02-13 19:35 UTC, lindsayad submitted a review, later dismissed

2025-02-13 19:35 UTC, lindsayad commented on framework/src/problems/FEProblemBase.C
> +      parameters.set<SystemBase *>("_sys") = _aux.get();
```suggestion
      parameters.set<SystemBase *>("_sys") = _displaced_problem->auxSys();
```

2025-02-13 19:35 UTC, lindsayad commented on framework/src/userobjects/UserObject.C
> -              "We expect the system to conceptually be nonlinear or linear.");
I guess it's fine if nothing else is breaking

2025-02-13 20:09 UTC, lindsayad reviewed
I approve the framework level changes

2025-02-13 20:59 UTC, grmnptr approved these changes

2025-02-13 23:59 UTC, grmnptr commented
Failures are unrelated.

2025-02-14 00:04 UTC, merged