Parameter groups and suppressions for a few systems
idaholab/moose pull request #29608
Opened 2024-12-23 21:47 UTC by GiudGiud

2024-12-24 01:16 UTC, moosebuild commented
Job [Documentation](https://civet.inl.gov/job/2616194/), step Docs: sync website on 5deebec wanted to post the following:

View the site [here](https://mooseframework.inl.gov/docs/PRs/29608/site)

This comment will be updated on new commits.

2024-12-25 16:47 UTC, moosebuild commented
Job [Coverage](https://civet.inl.gov/job/2617812/), step Generate coverage on 0686b46 wanted to post the following:


## Framework coverage

<table>
  <thead>
    <tr>
      <th></th>
      <th>2974c5</th>
      <th colspan=4>#29608 0686b4</th>
    </tr>
    <tr>
      <th></th>
      <th>Total</th>
      <th>Total</th>
      <th>+/-</th>
      <th>New</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><b>Rate</b></td>
      <td>85.25%</td>
      <td>85.26%</td>
      <td>+0.00%</td>
      <td>96.88%</td>
    </tr>
    <tr>
      <td><b>Hits</b></td>
      <td>108007</td>
      <td>108022</td>
      <td>+15</td>
      <td>31</td>
    </tr>
    <tr>
      <td><b>Misses</b></td>
      <td>18682</td>
      <td>18682</td>
      <td>-</td>
      <td>1</td>
    </tr>
  </tbody>
</table>

[Diff coverage report](https://mooseframework.inl.gov/docs/PRs/29608/coverage_diff/framework)

[Full coverage report](https://mooseframework.inl.gov/docs/PRs/29608/coverage/framework)


## Modules coverage

### Fluid properties

<table>
  <thead>
    <tr>
      <th></th>
      <th>2974c5</th>
      <th colspan=4>#29608 0686b4</th>
    </tr>
    <tr>
      <th></th>
      <th>Total</th>
      <th>Total</th>
      <th>+/-</th>
      <th>New</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><b>Rate</b></td>
      <td>85.19%</td>
      <td>85.20%</td>
      <td>+0.01%</td>
      <td>100.00%</td>
    </tr>
    <tr>
      <td><b>Hits</b></td>
      <td>7777</td>
      <td>7783</td>
      <td>+6</td>
      <td>7</td>
    </tr>
    <tr>
      <td><b>Misses</b></td>
      <td>1352</td>
      <td>1352</td>
      <td>-</td>
      <td>0</td>
    </tr>
  </tbody>
</table>

[Diff coverage report](https://mooseframework.inl.gov/docs/PRs/29608/coverage_diff/fluid_properties)

[Full coverage report](https://mooseframework.inl.gov/docs/PRs/29608/coverage/fluid_properties)

### Solid properties

<table>
  <thead>
    <tr>
      <th></th>
      <th>2974c5</th>
      <th colspan=4>#29608 0686b4</th>
    </tr>
    <tr>
      <th></th>
      <th>Total</th>
      <th>Total</th>
      <th>+/-</th>
      <th>New</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><b>Rate</b></td>
      <td>84.51%</td>
      <td>84.75%</td>
      <td>+0.24%</td>
      <td>100.00%</td>
    </tr>
    <tr>
      <td><b>Hits</b></td>
      <td>382</td>
      <td>389</td>
      <td>+7</td>
      <td>7</td>
    </tr>
    <tr>
      <td><b>Misses</b></td>
      <td>70</td>
      <td>70</td>
      <td>-</td>
      <td>0</td>
    </tr>
  </tbody>
</table>

[Diff coverage report](https://mooseframework.inl.gov/docs/PRs/29608/coverage_diff/solid_properties)

[Full coverage report](https://mooseframework.inl.gov/docs/PRs/29608/coverage/solid_properties)

### Thermal hydraulics

<table>
  <thead>
    <tr>
      <th></th>
      <th>2974c5</th>
      <th colspan=4>#29608 0686b4</th>
    </tr>
    <tr>
      <th></th>
      <th>Total</th>
      <th>Total</th>
      <th>+/-</th>
      <th>New</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><b>Rate</b></td>
      <td>88.34%</td>
      <td>88.35%</td>
      <td>+0.01%</td>
      <td>100.00%</td>
    </tr>
    <tr>
      <td><b>Hits</b></td>
      <td>13919</td>
      <td>13922</td>
      <td>+3</td>
      <td>2</td>
    </tr>
    <tr>
      <td><b>Misses</b></td>
      <td>1837</td>
      <td>1836</td>
      <td>-1</td>
      <td>0</td>
    </tr>
  </tbody>
</table>

[Diff coverage report](https://mooseframework.inl.gov/docs/PRs/29608/coverage_diff/thermal_hydraulics)

[Full coverage report](https://mooseframework.inl.gov/docs/PRs/29608/coverage/thermal_hydraulics)

## Full coverage reports

<details>
<summary>Reports</summary>

- [`framework`](https://mooseframework.inl.gov/docs/PRs/29608/coverage/framework)
- [`chemical_reactions`](https://mooseframework.inl.gov/docs/PRs/29608/coverage/chemical_reactions)
- [`combined`](https://mooseframework.inl.gov/docs/PRs/29608/coverage/combined)
- [`contact`](https://mooseframework.inl.gov/docs/PRs/29608/coverage/contact)
- [`electromagnetics`](https://mooseframework.inl.gov/docs/PRs/29608/coverage/electromagnetics)
- [`external_petsc_solver`](https://mooseframework.inl.gov/docs/PRs/29608/coverage/external_petsc_solver)
- [`fluid_properties`](https://mooseframework.inl.gov/docs/PRs/29608/coverage/fluid_properties)
- [`fsi`](https://mooseframework.inl.gov/docs/PRs/29608/coverage/fsi)
- [`functional_expansion_tools`](https://mooseframework.inl.gov/docs/PRs/29608/coverage/functional_expansion_tools)
- [`geochemistry`](https://mooseframework.inl.gov/docs/PRs/29608/coverage/geochemistry)
- [`heat_transfer`](https://mooseframework.inl.gov/docs/PRs/29608/coverage/heat_transfer)
- [`level_set`](https://mooseframework.inl.gov/docs/PRs/29608/coverage/level_set)
- [`misc`](https://mooseframework.inl.gov/docs/PRs/29608/coverage/misc)
- [`navier_stokes`](https://mooseframework.inl.gov/docs/PRs/29608/coverage/navier_stokes)
- [`optimization`](https://mooseframework.inl.gov/docs/PRs/29608/coverage/optimization)
- [`peridynamics`](https://mooseframework.inl.gov/docs/PRs/29608/coverage/peridynamics)
- [`phase_field`](https://mooseframework.inl.gov/docs/PRs/29608/coverage/phase_field)
- [`porous_flow`](https://mooseframework.inl.gov/docs/PRs/29608/coverage/porous_flow)
- [`ray_tracing`](https://mooseframework.inl.gov/docs/PRs/29608/coverage/ray_tracing)
- [`rdg`](https://mooseframework.inl.gov/docs/PRs/29608/coverage/rdg)
- [`reactor`](https://mooseframework.inl.gov/docs/PRs/29608/coverage/reactor)
- [`richards`](https://mooseframework.inl.gov/docs/PRs/29608/coverage/richards)
- [`scalar_transport`](https://mooseframework.inl.gov/docs/PRs/29608/coverage/scalar_transport)
- [`solid_mechanics`](https://mooseframework.inl.gov/docs/PRs/29608/coverage/solid_mechanics)
- [`solid_properties`](https://mooseframework.inl.gov/docs/PRs/29608/coverage/solid_properties)
- [`stochastic_tools`](https://mooseframework.inl.gov/docs/PRs/29608/coverage/stochastic_tools)
- [`thermal_hydraulics`](https://mooseframework.inl.gov/docs/PRs/29608/coverage/thermal_hydraulics)
- [`xfem`](https://mooseframework.inl.gov/docs/PRs/29608/coverage/xfem)

</details>



This comment will be updated on new commits.

2025-01-09 15:00 UTC, joshuahansel requested changes

2025-01-09 15:43 UTC, GiudGiud commented
thanks for the review! We'll need to wait for subchannel to be merged

2025-01-27 22:18 UTC, GiudGiud commented
This should be ready for review. Subchannel testing will be removed so this failure will be removed

2025-01-27 23:27 UTC, joshuahansel commented
Looks fine, so I'll approve when green. Are the subchannel related testing/failures going to go away before merge?

2025-01-27 23:32 UTC, moosebuild commented
Job [Controlled app tests](https://civet.inl.gov/job/2629896/) on f056e43 : invalidated by @GiudGiud

looks like new SAM failures, Ill push a patch

2025-01-27 23:33 UTC, GiudGiud commented
> Are the subchannel related testing/failures going to go away before merge?

should be once we stop testing subchannel (as part of its migration)

2025-01-28 21:46 UTC, GiudGiud commented
The pronghorn failure is tied to subchannel testing btw. 
@loganharbour can we remove that one too?

2025-01-29 13:22 UTC, joshuahansel approved these changes

2025-03-11 15:57 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/2743416/), step Clang format on c12ecc0 wanted to post the following:

Your code requires style changes.  

A patch was auto generated and copied [here](https://mooseframework.inl.gov/docs/PRs/29608/clang_format/style.patch)  
You can directly apply the patch by running, in the top level of your repository:

`curl -s https://mooseframework.inl.gov/docs/PRs/29608/clang_format/style.patch | git apply -v`  

Alternatively, with your repository up to date and in the top level of your repository:

`git clang-format c7f393de9a0cad674b301523e3690a9e536e79d2`

2025-03-12 21:15 UTC, GiudGiud commented
Internal apps passed on civet, reported erroneously as failing on this page
Modules parallel failure is unrelated

2025-03-12 21:15 UTC, merged