Add a Physics for linear FV + mixture model
idaholab/moose pull request #29614
Opened 2024-12-24 21:42 UTC by GiudGiud

Requires #29177 and maybe #29516 to try out transients

One difficulty is likely that the two phase equation needs to be an "active" scalar, not a passive one, and be solved inside the pressure-velocity-energy picard iteration

2024-12-24 21:48 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/2617091/), step Clang format on 213f26e wanted to post the following:

Your code requires style changes.  

A patch was auto generated and copied [here](https://mooseframework.inl.gov/docs/PRs/29614/clang_format/style.patch)  
You can directly apply the patch by running, in the top level of your repository:

`curl -s https://mooseframework.inl.gov/docs/PRs/29614/clang_format/style.patch | git apply -v`  

Alternatively, with your repository up to date and in the top level of your repository:

`git clang-format 2974c54c5269c9b763547954236d33e3a55a8710`

2024-12-24 21:48 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/2617091/), step Fixup commit check on 213f26e wanted to post the following:

The following commit(s) contain fixups:

- e246047cd0: fixup! Add a Physics for linear finite volume for two phase flow

2024-12-24 23:36 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/2617448/), step Clang format on 8248e8f wanted to post the following:

Your code requires style changes.  

A patch was auto generated and copied [here](https://mooseframework.inl.gov/docs/PRs/29614/clang_format/style.patch)  
You can directly apply the patch by running, in the top level of your repository:

`curl -s https://mooseframework.inl.gov/docs/PRs/29614/clang_format/style.patch | git apply -v`  

Alternatively, with your repository up to date and in the top level of your repository:

`git clang-format 2974c54c5269c9b763547954236d33e3a55a8710`

2024-12-25 01:59 UTC, moosebuild commented
Job [Documentation](https://civet.inl.gov/job/2617495/), step Docs: sync website on c7c56d2 wanted to post the following:

View the site [here](https://mooseframework.inl.gov/docs/PRs/29614/site)

This comment will be updated on new commits.

2025-02-01 02:03 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/2664725/), step Clang format on 4586129 wanted to post the following:

Your code requires style changes.  

A patch was auto generated and copied [here](https://mooseframework.inl.gov/docs/PRs/29614/clang_format/style.patch)  
You can directly apply the patch by running, in the top level of your repository:

`curl -s https://mooseframework.inl.gov/docs/PRs/29614/clang_format/style.patch | git apply -v`  

Alternatively, with your repository up to date and in the top level of your repository:

`git clang-format 32662f974835a45bece8bcfc734f7bf5d5ec5ea1`

2025-02-01 06:47 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/2664853/), step Clang format on f8dc1b6 wanted to post the following:

Your code requires style changes.  

A patch was auto generated and copied [here](https://mooseframework.inl.gov/docs/PRs/29614/clang_format/style.patch)  
You can directly apply the patch by running, in the top level of your repository:

`curl -s https://mooseframework.inl.gov/docs/PRs/29614/clang_format/style.patch | git apply -v`  

Alternatively, with your repository up to date and in the top level of your repository:

`git clang-format 32662f974835a45bece8bcfc734f7bf5d5ec5ea1`

2025-02-01 06:57 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/2664904/), step Clang format on 63f46dd wanted to post the following:

Your code requires style changes.  

A patch was auto generated and copied [here](https://mooseframework.inl.gov/docs/PRs/29614/clang_format/style.patch)  
You can directly apply the patch by running, in the top level of your repository:

`curl -s https://mooseframework.inl.gov/docs/PRs/29614/clang_format/style.patch | git apply -v`  

Alternatively, with your repository up to date and in the top level of your repository:

`git clang-format 32662f974835a45bece8bcfc734f7bf5d5ec5ea1`

2025-02-09 19:14 UTC, tanoret commented
Once the PR is ready, please consider adding a technical reviewer as per our suggested merge standards to NS. Thanks!

2025-02-12 22:25 UTC, grmnptr requested changes
Nice, just a few comments!

2025-02-12 22:25 UTC, grmnptr commented on modules/navier_stokes/src/physics/WCNSLinearFVTwoPhaseMixturePhysics.C
> +  }
```suggestion
    if (_flow_equations_physics->densityName() != "rho_mixture")
      mooseError("Density name should for Physics ,",
                 _flow_equations_physics->name(),
                 "' should be 'rho_mixture'");
```

2025-02-12 22:37 UTC, GiudGiud commented on modules/navier_stokes/src/executioners/LinearAssemblySegregatedSolve.C
> +    if (_has_active_scalar_systems && simple_iteration_counter > 1)
is the lag preferred over trying to get the slip velocity updated straight away? this 1 iteration difference will remain throughout

2025-02-12 22:38 UTC, GiudGiud commented on modules/navier_stokes/src/executioners/LinearAssemblySegregatedSolve.C
> +  Real norm_factor = std::max(1e-10, NS::FV::computeNormalizationFactor(solution, mmat, rhs));
will do

2025-02-12 22:39 UTC, GiudGiud commented on modules/navier_stokes/include/linearfvkernels/LinearFVScalarAdvection.h
> +
if I do that I cant do `  WCNSLinearFVScalarTransportPhysics::addFVKernels();` in the lienarFV2phasemixutrephysics

2025-02-12 22:39 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/2686576/), step Clang format on b6d1d9d wanted to post the following:

Your code requires style changes.  

A patch was auto generated and copied [here](https://mooseframework.inl.gov/docs/PRs/29614/clang_format/style.patch)  
You can directly apply the patch by running, in the top level of your repository:

`curl -s https://mooseframework.inl.gov/docs/PRs/29614/clang_format/style.patch | git apply -v`  

Alternatively, with your repository up to date and in the top level of your repository:

`git clang-format cd66266a7dec6c2ec22f5902dba3e2ab6eeb8b19`

2025-02-13 04:06 UTC, moosebuild commented
Job [Coverage](https://civet.inl.gov/job/2687164/), step Generate coverage on 1dd4433 wanted to post the following:


## Framework coverage

<table>
  <thead>
    <tr>
      <th></th>
      <th>cd6626</th>
      <th colspan=4>#29614 1dd443</th>
    </tr>
    <tr>
      <th></th>
      <th>Total</th>
      <th>Total</th>
      <th>+/-</th>
      <th>New</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><b>Rate</b></td>
      <td>85.29%</td>
      <td>85.29%</td>
      <td>-0.00%</td>
      <td>73.91%</td>
    </tr>
    <tr>
      <td><b>Hits</b></td>
      <td>108457</td>
      <td>108466</td>
      <td>+9</td>
      <td>17</td>
    </tr>
    <tr>
      <td><b>Misses</b></td>
      <td>18702</td>
      <td>18711</td>
      <td>+9</td>
      <td>6</td>
    </tr>
  </tbody>
</table>

[Diff coverage report](https://mooseframework.inl.gov/docs/PRs/29614/coverage_diff/framework)

[Full coverage report](https://mooseframework.inl.gov/docs/PRs/29614/coverage/framework)


## Modules coverage

### Navier stokes

<table>
  <thead>
    <tr>
      <th></th>
      <th>cd6626</th>
      <th colspan=4>#29614 1dd443</th>
    </tr>
    <tr>
      <th></th>
      <th>Total</th>
      <th>Total</th>
      <th>+/-</th>
      <th>New</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><b>Rate</b></td>
      <td>84.83%</td>
      <td>83.97%</td>
      <td>-0.86%</td>
      <td>25.08%</td>
    </tr>
    <tr>
      <td><b>Hits</b></td>
      <td>17777</td>
      <td>17827</td>
      <td>+50</td>
      <td>75</td>
    </tr>
    <tr>
      <td><b>Misses</b></td>
      <td>3178</td>
      <td>3403</td>
      <td>+225</td>
      <td>224</td>
    </tr>
  </tbody>
</table>

[Diff coverage report](https://mooseframework.inl.gov/docs/PRs/29614/coverage_diff/navier_stokes)

[Full coverage report](https://mooseframework.inl.gov/docs/PRs/29614/coverage/navier_stokes)

## Full coverage reports

<details>
<summary>Reports</summary>

- [`framework`](https://mooseframework.inl.gov/docs/PRs/29614/coverage/framework)
- [`chemical_reactions`](https://mooseframework.inl.gov/docs/PRs/29614/coverage/chemical_reactions)
- [`combined`](https://mooseframework.inl.gov/docs/PRs/29614/coverage/combined)
- [`contact`](https://mooseframework.inl.gov/docs/PRs/29614/coverage/contact)
- [`electromagnetics`](https://mooseframework.inl.gov/docs/PRs/29614/coverage/electromagnetics)
- [`external_petsc_solver`](https://mooseframework.inl.gov/docs/PRs/29614/coverage/external_petsc_solver)
- [`fluid_properties`](https://mooseframework.inl.gov/docs/PRs/29614/coverage/fluid_properties)
- [`fsi`](https://mooseframework.inl.gov/docs/PRs/29614/coverage/fsi)
- [`functional_expansion_tools`](https://mooseframework.inl.gov/docs/PRs/29614/coverage/functional_expansion_tools)
- [`geochemistry`](https://mooseframework.inl.gov/docs/PRs/29614/coverage/geochemistry)
- [`heat_transfer`](https://mooseframework.inl.gov/docs/PRs/29614/coverage/heat_transfer)
- [`level_set`](https://mooseframework.inl.gov/docs/PRs/29614/coverage/level_set)
- [`misc`](https://mooseframework.inl.gov/docs/PRs/29614/coverage/misc)
- [`navier_stokes`](https://mooseframework.inl.gov/docs/PRs/29614/coverage/navier_stokes)
- [`optimization`](https://mooseframework.inl.gov/docs/PRs/29614/coverage/optimization)
- [`peridynamics`](https://mooseframework.inl.gov/docs/PRs/29614/coverage/peridynamics)
- [`phase_field`](https://mooseframework.inl.gov/docs/PRs/29614/coverage/phase_field)
- [`porous_flow`](https://mooseframework.inl.gov/docs/PRs/29614/coverage/porous_flow)
- [`ray_tracing`](https://mooseframework.inl.gov/docs/PRs/29614/coverage/ray_tracing)
- [`rdg`](https://mooseframework.inl.gov/docs/PRs/29614/coverage/rdg)
- [`reactor`](https://mooseframework.inl.gov/docs/PRs/29614/coverage/reactor)
- [`richards`](https://mooseframework.inl.gov/docs/PRs/29614/coverage/richards)
- [`scalar_transport`](https://mooseframework.inl.gov/docs/PRs/29614/coverage/scalar_transport)
- [`solid_mechanics`](https://mooseframework.inl.gov/docs/PRs/29614/coverage/solid_mechanics)
- [`solid_properties`](https://mooseframework.inl.gov/docs/PRs/29614/coverage/solid_properties)
- [`stochastic_tools`](https://mooseframework.inl.gov/docs/PRs/29614/coverage/stochastic_tools)
- [`thermal_hydraulics`](https://mooseframework.inl.gov/docs/PRs/29614/coverage/thermal_hydraulics)
- [`xfem`](https://mooseframework.inl.gov/docs/PRs/29614/coverage/xfem)

</details>

## Warnings

- `framework` new line coverage rate 73.91% is less than the suggested 90.0%
- `navier_stokes` new line coverage rate 25.08% is less than the suggested 90.0%



This comment will be updated on new commits.

2025-02-13 05:29 UTC, GiudGiud commented
any preferred test case on this? It s only 1 model for mixture. no solidification or any refinement.
and any volunteer for technical review? (once I clean up the tests etc, not now)

2025-02-13 05:37 UTC, GiudGiud commented
@tanoret I can try to reproduce the rayleigh-bernard convection input with Physics & linear FV. Is that enough ? Is there a particular flow test bed input you would like to see?

2025-02-14 06:42 UTC, GiudGiud commented on modules/navier_stokes/include/linearfvkernels/LinearFVScalarAdvection.h
> +
also that's not what we did for nonlienar FV

2025-02-14 06:47 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/2690546/), step Clang format on bfd72a5 wanted to post the following:

Your code requires style changes.  

A patch was auto generated and copied [here](https://mooseframework.inl.gov/docs/PRs/29614/clang_format/style.patch)  
You can directly apply the patch by running, in the top level of your repository:

`curl -s https://mooseframework.inl.gov/docs/PRs/29614/clang_format/style.patch | git apply -v`  

Alternatively, with your repository up to date and in the top level of your repository:

`git clang-format c8ca621a331f92c50b52b8db2eb5c4f89fc38ba1`

2025-02-14 06:51 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/2690597/), step Clang format on 77536ed wanted to post the following:

Your code requires style changes.  

A patch was auto generated and copied [here](https://mooseframework.inl.gov/docs/PRs/29614/clang_format/style.patch)  
You can directly apply the patch by running, in the top level of your repository:

`curl -s https://mooseframework.inl.gov/docs/PRs/29614/clang_format/style.patch | git apply -v`  

Alternatively, with your repository up to date and in the top level of your repository:

`git clang-format c8ca621a331f92c50b52b8db2eb5c4f89fc38ba1`

2025-02-14 19:53 UTC, GiudGiud commented
The results are not a great match for the two test cases between linear and nonlinear.

2025-02-23 14:42 UTC, GiudGiud commented on modules/navier_stokes/src/executioners/LinearAssemblySegregatedSolve.C
> +    if (_has_active_scalar_systems && simple_iteration_counter > 1)
the lagging was removed

2025-02-26 23:15 UTC, grmnptr requested changes
Nice! Just a few questions.

2025-02-26 23:15 UTC, grmnptr commented on modules/navier_stokes/src/physics/WCNSLinearFVTwoPhaseMixturePhysics.C
> +  // Re-create the phase interface term from existing kernels
```suggestion
  // Recreate the phase interface term from existing kernels
```

2025-02-26 23:15 UTC, grmnptr commented on modules/navier_stokes/src/utils/SegregatedSolverUtils.C
> +  return (A_times_average_solution->l2_norm() + 1e-2 * libMesh::TOLERANCE);
```suggestion
  return (A_times_average_solution->l2_norm() + 1e-8);
```

2025-02-26 23:15 UTC, grmnptr commented on modules/navier_stokes/test/tests/finite_volume/two_phase/mixture_model/segregated/mixture_physics_diff.cmp
> +	phase_1_out relative 1e-2
Could you just gold them separately? Obviously the two are not the same.

2025-02-26 23:15 UTC, grmnptr commented on modules/navier_stokes/test/tests/finite_volume/two_phase/mixture_model/segregated/rayleigh-bernard-two-phase-physics.i
> +[]
Do we need this?

2025-02-27 04:48 UTC, GiudGiud commented on modules/navier_stokes/doc/content/source/physics/WCNSLinearFVTwoPhaseMixturePhysics.md
> +# Navier Stokes Two Phase Mixture using a Linear Finite Volume discretization / WCNSLinearFVTwoPhaseMixturePhysics
the actual object names arent present in the input so I chose to be descriptive in the titles instead

2025-02-27 04:51 UTC, GiudGiud commented on modules/navier_stokes/include/linearfvkernels/LinearWCNSFV2PMomentumDriftFlux.h
> +class LinearWCNSFV2PMomentumDriftFlux : public LinearFVFluxKernel
the nonlinear kernels and functor materials use 2P

2025-02-27 04:52 UTC, GiudGiud commented on modules/navier_stokes/src/linearfvkernels/LinearFVMomentumFriction.C
> +      "Navier Stokes i-th momentum equation in Rhie-Chow (incompressible) contexts.");
```suggestion
      "Navier Stokes i-th momentum equation.");
```

2025-02-27 04:52 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/2716780/), step Clang format on 6113b53 wanted to post the following:

Your code requires style changes.  

A patch was auto generated and copied [here](https://mooseframework.inl.gov/docs/PRs/29614/clang_format/style.patch)  
You can directly apply the patch by running, in the top level of your repository:

`curl -s https://mooseframework.inl.gov/docs/PRs/29614/clang_format/style.patch | git apply -v`  

Alternatively, with your repository up to date and in the top level of your repository:

`git clang-format 5adf17aea9f3318f9617b10e7be1c26d1a99eca9`

2025-02-27 04:53 UTC, GiudGiud commented on modules/navier_stokes/src/linearfvkernels/LinearWCNSFV2PMomentumDriftFlux.C
> +                  _f_d(makeCDFace(*_current_face_info), state);
```suggestion
    face_rho_fd = _rho_d(face_arg, state) *
                  _f_d(face_arg, state);
```

2025-02-27 04:54 UTC, GiudGiud commented on modules/navier_stokes/src/linearfvkernels/LinearWCNSFV2PMomentumDriftFlux.C
> +    return _face_flux * _current_face_area;
```suggestion
    return - _face_flux * _current_face_area;
```

2025-02-27 04:55 UTC, GiudGiud commented on modules/navier_stokes/src/linearfvkernels/LinearWCNSFV2PMomentumDriftFlux.C
> +    return _face_flux * _current_face_area;
good point the two if clauses are not consistent here

2025-02-27 04:55 UTC, GiudGiud commented on modules/navier_stokes/src/linearfvkernels/LinearWCNSFV2PMomentumDriftFlux.C
> +    return _face_flux * _current_face_area;
```suggestion
    return -_face_flux * _current_face_area;
```

2025-02-27 04:55 UTC, GiudGiud commented on modules/navier_stokes/src/linearfvkernels/LinearWCNSFV2PMomentumDriftFlux.C
> +  return _face_flux * _current_face_area;
```suggestion
  return -_face_flux * _current_face_area;
```

2025-02-27 04:56 UTC, GiudGiud commented on modules/navier_stokes/test/tests/finite_volume/two_phase/mixture_model/segregated/rayleigh-bernard-two-phase-physics.i
> +[]
```suggestion
```

2025-02-27 04:59 UTC, GiudGiud commented on modules/navier_stokes/src/linearfvkernels/LinearWCNSFV2PMomentumDriftFlux.C
> +                  _f_d(makeCDFace(*_current_face_info), state);
changing now

2025-02-27 05:00 UTC, GiudGiud commented on modules/navier_stokes/test/tests/finite_volume/two_phase/mixture_model/segregated/mixture_physics_diff.cmp
> +	phase_1_out relative 1e-2
1% on the phase over the whole domain is pretty good?

2025-02-27 05:04 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/2716839/), step Clang format on 5691759 wanted to post the following:

Your code requires style changes.  

A patch was auto generated and copied [here](https://mooseframework.inl.gov/docs/PRs/29614/clang_format/style.patch)  
You can directly apply the patch by running, in the top level of your repository:

`curl -s https://mooseframework.inl.gov/docs/PRs/29614/clang_format/style.patch | git apply -v`  

Alternatively, with your repository up to date and in the top level of your repository:

`git clang-format 5adf17aea9f3318f9617b10e7be1c26d1a99eca9`

2025-02-27 05:13 UTC, GiudGiud commented on modules/navier_stokes/doc/content/source/physics/WCNSLinearFVTwoPhaseMixturePhysics.md
> +two-phase mixture. If specified with the [!param](/Physics/NavierStokes/TwoPhaseMixtureSegregated/WCNSLinearFVTwoPhaseMixturePhysics/add_phase_transport_equation)
ah yeah I tried suppressing the parameter that gets renamed into this param. 
I ll unsuppress it

2025-02-27 21:11 UTC, GiudGiud commented on modules/navier_stokes/test/tests/finite_volume/two_phase/mixture_model/segregated/rayleigh-bernard-two-phase-physics.i
> +[]
deleted

2025-02-27 21:12 UTC, GiudGiud commented on modules/navier_stokes/src/linearfvkernels/LinearFVMomentumFriction.C
> +      "Navier Stokes i-th momentum equation in Rhie-Chow (incompressible) contexts.");
removed

2025-03-01 05:27 UTC, GiudGiud commented
@tanoret or @MengnanLi91 can you please do the technical review / validation?

2025-03-04 17:27 UTC, MengnanLi91 commented on modules/navier_stokes/doc/content/source/physics/WCNSLinearFVTwoPhaseMixturePhysics.md
> +!equation
This equation doesn't seem right. We don't have a advection-diffusion equation for phase variable in mixture model. Do you get it from other documentation?

2025-03-05 16:27 UTC, GiudGiud commented on modules/navier_stokes/doc/content/source/physics/WCNSLinearFVTwoPhaseMixturePhysics.md
> +!equation
I ll double check the equation but I think we do solve for the other phase advection in the two phase mixture model

2025-03-05 16:34 UTC, MengnanLi91 commented on modules/navier_stokes/doc/content/source/physics/WCNSLinearFVTwoPhaseMixturePhysics.md
> +!equation
We have a advection equation for phase volume/void fraction, but no diffusion. I assume here you mean `INSFVScalarFieldAdvection`, right?

2025-03-05 23:02 UTC, MengnanLi91 commented on modules/navier_stokes/doc/content/source/physics/WCNSLinearFVTwoPhaseMixturePhysics.md
> +!equation
This is different from the scalar field used in mixture model. I think it may use for other models. But this equation definitely doesn't show up in the governing equations of mixture model for sure.

2025-03-05 23:06 UTC, MengnanLi91 commented on modules/navier_stokes/doc/content/source/physics/WCNSLinearFVTwoPhaseMixturePhysics.md
> +!equation
I only saw this parameter from `lid-driven-two-phase-physics.i`, not `lid-driven-two-phase.i`.  I probably miss something here?

2025-03-05 23:09 UTC, GiudGiud commented on modules/navier_stokes/doc/content/source/physics/WCNSLinearFVTwoPhaseMixturePhysics.md
> +!equation
`lid-driven-two-phase.i` does not use the Physics syntax

but it does have diffusion
```
  [phase_2_time]
    type = FVFunctorTimeKernel
    variable = phase_2
  []
  [phase_2_advection]
    type = INSFVScalarFieldAdvection
    variable = phase_2
    u_slip = 'vel_slip_x'
    v_slip = 'vel_slip_y'
  []
  [phase_2_diffusion]
    type = FVDiffusion
    variable = phase_2
    coeff = 1e-3
  []
```

2025-03-05 23:10 UTC, GiudGiud commented on modules/navier_stokes/doc/content/source/physics/WCNSLinearFVTwoPhaseMixturePhysics.md
> +!equation
> This is different from the scalar field used in mixture model.

this could very well be true. I am writing the Physics to replicate what was done with the kernel, I am not starting from the equations and the literature

2025-03-05 23:12 UTC, MengnanLi91 commented on modules/navier_stokes/doc/content/source/physics/WCNSLinearFVTwoPhaseMixturePhysics.md
> +!equation
> `lid-driven-two-phase.i` does not use the Physics syntax
> 
> but it does have diffusion
> 
> ```
>   [phase_2_time]
>     type = FVFunctorTimeKernel
>     variable = phase_2
>   []
>   [phase_2_advection]
>     type = INSFVScalarFieldAdvection
>     variable = phase_2
>     u_slip = 'vel_slip_x'
>     v_slip = 'vel_slip_y'
>   []
>   [phase_2_diffusion]
>     type = FVDiffusion
>     variable = phase_2
>     coeff = 1e-3
>   []
> ```

I didn't notice this before. I'll do some search about it. Maybe you are right

2025-03-05 23:22 UTC, MengnanLi91 commented on modules/navier_stokes/doc/content/source/physics/WCNSLinearFVTwoPhaseMixturePhysics.md
> +!equation
Now I remember, `lid-driven-two-phase.i` doesn't follow mixture model formulation. It only uses `slip_velocity`, which is a more simple assumption than mixture model. It doesn't have the `drift_flux` kernel in the momentum equation. Both are valid but we should make the documentation more clear on this. I'll do a PR for that

2025-03-23 04:19 UTC, grmnptr commented
Can we merhe this @tanoret, @MengnanLi91 ?

2025-03-23 04:29 UTC, MengnanLi91 commented
> Can we merge this @tanoret, @MengnanLi91 ?

Maybe wait a bit? @tanoret mentioned he has something to change for the mixture model.

2025-05-27 16:32 UTC, GiudGiud commented
Agreement with nonlinear FV is quite good now with these changes
- extrapolated pressure at the inlet in linear FV
- pressure drop computation fix for the pressure face interpolation

2025-05-27 16:32 UTC, GiudGiud commented
Rebased on #30288 which should be merged first

2025-05-30 23:14 UTC, GiudGiud commented
@tanoret the linear FV. two phase mixture will now error with skewed meshes. This should address your concern. 

BTW, I ran a few single phase cases on skewed meshes without skewness correction and got really bad results, which turned into really good results with skewness correction. Maybe the check I have here should just go in all our FV code as well to request skewness correction.

2025-06-02 16:01 UTC, GiudGiud commented
@grmnptr did you want to re-review this?

2025-06-04 18:33 UTC, GiudGiud commented
@grmnptr @tanoret last commit is a bug fix on gravity for the flow physics. 
We should make a decision on this PR so this bug fix makes it in regardless.

2025-06-18 17:45 UTC, tanoret commented
Good for me to merge once the test are passing. Thank you for the work @GiudGiud!

Edit: Sorry, could we please add at least one test using kernels? Currently this only use physics and this is not the main way in which our users currently interact with the models. Thank you for understanding

2025-06-22 23:33 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/2972838/), step Clang format on 4d5c223 wanted to post the following:

Your code requires style changes.  

A patch was auto generated and copied [here](https://mooseframework.inl.gov/docs/PRs/29614/clang_format/style.patch)  
You can directly apply the patch by running, in the top level of your repository:

`curl -s https://mooseframework.inl.gov/docs/PRs/29614/clang_format/style.patch | git apply -v`  

Alternatively, with your repository up to date and in the top level of your repository:

`git clang-format 35394b6db8be5ebcb26fdaf6275671a8032b47a9`

2025-06-27 17:24 UTC, grmnptr requested changes
Nice!

2025-06-27 17:24 UTC, grmnptr commented on modules/navier_stokes/src/linearfvkernels/LinearWCNSFV2PMomentumDriftFlux.C
> +    addMooseVariableDependency(&_fe_problem.getVariable(_tid, fraction_name));
Considering that this is a segregated solver, do we need this dependency?

2025-06-27 17:24 UTC, grmnptr commented on modules/navier_stokes/src/linearfvkernels/LinearWCNSFV2PMomentumDriftFlux.C
> +  const auto normal = _current_face_info->normal();
```suggestion
  const auto & normal = _current_face_info->normal();
```

2025-06-27 17:24 UTC, grmnptr commented on modules/navier_stokes/src/linearfvkernels/LinearWCNSFV2PMomentumDriftFlux.C
> +  const auto normal = _current_face_info->normal();
Not sure if this will copy construct here, probably will be able to interpret the reference coming from the return value of FaceInfo.

2025-06-27 17:24 UTC, grmnptr commented on modules/navier_stokes/src/linearfvkernels/LinearWCNSFV2PMomentumDriftFlux.C
> +  // Note: We should use Rhie Chow coefficients here, because the way we split the flux is:
Not sure I understand this comment, we do Rhie Chow for the face fluxes. You are saying we should use rhie chow to interpolate the advecting flux within `computeFlux`? This interpolation is for the advected slip velocity. So technically it is the advected interpolation here.

2025-06-27 17:24 UTC, grmnptr commented on modules/navier_stokes/src/physics/WCNSLinearFVTwoPhaseMixturePhysics.C
> +                 "' should be 'rho_mixture'");
```suggestion
      mooseError("Density name for Physics '",
                 _fluid_energy_physics->name(),
                 "' should be 'rho_mixture'");
```

2025-06-27 17:24 UTC, grmnptr commented on modules/navier_stokes/src/physics/WCNSLinearFVTwoPhaseMixturePhysics.C
> +      mooseError("Specific heat name should for Physics '",
```suggestion
      mooseError("Specific heat name for Physics '",
```

2025-06-27 17:24 UTC, grmnptr commented on modules/navier_stokes/src/physics/WCNSLinearFVTwoPhaseMixturePhysics.C
> +      mooseError("Density name should for Physics ,",
```suggestion
      mooseError("Density name for Physics ,",
```

2025-06-27 17:24 UTC, grmnptr commented on modules/navier_stokes/src/physics/WCNSLinearFVTwoPhaseMixturePhysics.C
> +                   "developer if you require this.");
Very nice!

2025-06-27 17:24 UTC, grmnptr commented on modules/navier_stokes/src/utils/SegregatedSolverUtils.C
> +  return (A_times_average_solution->l2_norm() + 1e-8);
Why 1e-8?

2025-06-27 17:24 UTC, grmnptr commented on modules/navier_stokes/test/tests/finite_volume/materials/flow_diode/gold/flow_based.csv
> +0.03,-1.6742083957845,8.3257916043696,-8.3257916042968,-5,1473.5567884307,2117.8984073536,-2130.4684783336
Is this due to the change in the interpolation method?

2025-06-27 17:24 UTC, grmnptr commented on modules/navier_stokes/test/tests/finite_volume/two_phase/mixture_model/segregated/channel-drift-flux.i
> +    solver_sys = phi_system
```suggestion
    type = MooseLinearVariableFVReal
    solver_sys = phi_system
```

2025-06-27 17:24 UTC, grmnptr commented on modules/navier_stokes/test/tests/finite_volume/two_phase/mixture_model/segregated/channel-drift-flux.i
> +mu = 1.0
The Variables, FM, LFVKernels and LFVBC blocks have been split into two, is it because it is easier for the user to follow?

2025-06-27 17:24 UTC, grmnptr commented on modules/navier_stokes/test/tests/finite_volume/two_phase/mixture_model/segregated/channel-drift-flux.i
> +  []
```suggestion
  [vel_x]
    type = MooseLinearVariableFVReal
    solver_sys = u_system
    initial_condition = 1
  []
  [vel_y]
    type = MooseLinearVariableFVReal
    solver_sys = v_system
  []
  [pressure]
    type = MooseLinearVariableFVReal
    solver_sys = pressure_system
  []
```

2025-06-27 17:24 UTC, grmnptr commented on modules/navier_stokes/test/tests/postprocessors/pressure_drop/gold/diverging_insfv_quad_rz.csv
> +1,0,16.532795382978,13.012263194174,3.2691214213913,0.25141076741277,16.532795382978,16.532795382978
This is a significant change, is this expected?

2025-06-28 14:52 UTC, GiudGiud commented on modules/navier_stokes/src/linearfvkernels/LinearWCNSFV2PMomentumDriftFlux.C
> +    addMooseVariableDependency(&_fe_problem.getVariable(_tid, fraction_name));
Removing it. I ll add a note

2025-06-28 14:52 UTC, GiudGiud commented on modules/navier_stokes/src/linearfvkernels/LinearWCNSFV2PMomentumDriftFlux.C
> +  const auto normal = _current_face_info->normal();
le problem with auto. changing

2025-06-28 14:53 UTC, GiudGiud commented on modules/navier_stokes/src/utils/SegregatedSolverUtils.C
> +  return (A_times_average_solution->l2_norm() + 1e-8);
too old right now I dont remember. I can try the old threshold see what went wrong that I had to change it

2025-06-28 19:46 UTC, GiudGiud commented on modules/navier_stokes/test/tests/finite_volume/materials/flow_diode/gold/flow_based.csv
> +0.03,-1.6742083957845,8.3257916043696,-8.3257916042968,-5,1473.5567884307,2117.8984073536,-2130.4684783336
yup. all the tests using pressure drops needed a regold

2025-06-28 19:47 UTC, GiudGiud commented on modules/navier_stokes/test/tests/finite_volume/two_phase/mixture_model/segregated/channel-drift-flux.i
> +mu = 1.0
in a way. this is what happens when you output the Physics syntax to a regular input

2025-06-28 19:48 UTC, GiudGiud commented on modules/navier_stokes/test/tests/postprocessors/pressure_drop/gold/diverging_insfv_quad_rz.csv
> +1,0,16.532795382978,13.012263194174,3.2691214213913,0.25141076741277,16.532795382978,16.532795382978
The change in interpolation is the only change. So to me this regold is correct.

2025-06-28 19:57 UTC, GiudGiud commented on modules/navier_stokes/src/linearfvkernels/LinearWCNSFV2PMomentumDriftFlux.C
> +  // Note: We should use Rhie Chow coefficients here, because the way we split the flux is:
my reasoning was this is the `_velocity_interp_coeffs` so it s used to get the velocity at the face, which is then multiplied by the face flux (face flux is interpolated with the advected interpolation)

in `LinearWCNSFV2PMomentumDriftFlux::computeElemMatrixContribution()` we see this coefficient multiple the face flux (already interpolated) because the term is v_elem/v_old * coeff * face_flux.

imo we should be fine here? we can decide that we do this v_elem / v_old trick with either interpolation schemes

2025-06-28 20:07 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/2993489/), step Clang format on 5f47a7a wanted to post the following:

Your code requires style changes.  

A patch was auto generated and copied [here](https://mooseframework.inl.gov/docs/PRs/29614/clang_format/style.patch)  
You can directly apply the patch by running, in the top level of your repository:

`curl -s https://mooseframework.inl.gov/docs/PRs/29614/clang_format/style.patch | git apply -v`  

Alternatively, with your repository up to date and in the top level of your repository:

`git clang-format 0215c4d571eff0b3766b500498b9050c07da8afc`

2025-06-29 11:45 UTC, GiudGiud commented on modules/navier_stokes/src/utils/SegregatedSolverUtils.C
> +  return (A_times_average_solution->l2_norm() + 1e-8);
reverted and it passed fine

2025-06-29 11:45 UTC, GiudGiud commented
@grmnptr

2025-06-30 14:33 UTC, grmnptr requested changes
Last two tiny comments.

2025-06-30 14:33 UTC, grmnptr commented on modules/navier_stokes/src/linearfvkernels/LinearWCNSFV2PMomentumDriftFlux.C
> +  // Note: We should use Rhie Chow coefficients here, because the way we split the flux is:
Traditionally, the advecting flux is interpolated with average/rc and the advected quantity uses coeff/(1-coeff). That flux is lagged, while the advected quantity interpolation is treated implicitly. It feels like we have it backwards here. Especially that in the other advection kernels we have it flipped.

2025-06-30 14:33 UTC, grmnptr commented on modules/navier_stokes/test/tests/finite_volume/two_phase/mixture_model/segregated/channel-drift-flux.i
> +mu = 1.0
Could you get them into one block each please?

2025-07-01 00:03 UTC, GiudGiud commented
> That flux is lagged, while the advected quantity interpolation is treated implicitly. It feels like we have it backwards here. 

That's out of necessity. Writing the linearization of the slip velocity is not easy. See WCNSFV2PSlipVelocityFunctorMaterial we would need to get the dfriction term/du (friction term could be from anything), dgrad_u/du etc. 

Both terms are implicit here. 

> Traditionally, the advecting flux is interpolated with average/rc and the advected quantity uses coeff/(1-coeff).

The "velocity interp coeffs" here is only for the "trick" of multiplying by u/u_old. 
The face flux is: -face_rho_fd * uslipdotn * u_slip_vel_vec(_index);

face_rho_d is using the expected interpolation method.
uslip is using the same functor material as used in nonlinear wcnsfv. There are quite a few terms there. There is possibly one term (advection) that could use RC interpolation, but we were not doing that for nonlinear wcnsfv

We could also try to lag the slip velocity (again the "trick" does not matter imo) since it's effectively the advecting velocity. But that would be different from the nonlinear WCNSFV implementation

>  That flux is lagged, while the advected quantity interpolation is treated implicitly.

for momentum we treat both implicitly I think. Since this is in the momentum equation we might be in line here?

2025-07-01 00:06 UTC, GiudGiud commented on modules/navier_stokes/test/tests/finite_volume/two_phase/mixture_model/segregated/channel-drift-flux.i
> +mu = 1.0
done!

2025-07-01 16:36 UTC, grmnptr approved these changes
Nice!

2025-07-01 20:53 UTC, moosebuild commented
Job [Coverage](https://civet.inl.gov/job/3002824/), step Verify coverage on 6d72f22 wanted to post the following:


The following coverage requirement(s) failed:
- Failed to generate `framework` coverage rate (required: 81.0%)

2025-07-01 21:37 UTC, merged

2025-07-01 23:54 UTC, GiudGiud commented
Thanks for the reviews!