Regenerate hit.cpp with cython 3.0.11
idaholab/moose pull request #29624
Opened 2024-12-30 16:48 UTC by nmnobre

So we can build against Python 3.13.

2024-12-30 19:14 UTC, moosebuild commented
Job [Documentation](https://civet.inl.gov/job/2619151/), step Docs: sync website on 9f4bc6e wanted to post the following:

View the site [here](https://mooseframework.inl.gov/docs/PRs/29624/site)

This comment will be updated on new commits.

2024-12-30 20:02 UTC, moosebuild commented
Job [Coverage](https://civet.inl.gov/job/2619167/), step Generate coverage on 9f4bc6e wanted to post the following:


## Framework coverage

<table>
  <thead>
    <tr>
      <th></th>
      <th>90a291</th>
      <th colspan=4>#29624 9f4bc6</th>
    </tr>
    <tr>
      <th></th>
      <th>Total</th>
      <th>Total</th>
      <th>+/-</th>
      <th>New</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><b>Rate</b></td>
      <td>85.25%</td>
      <td>85.25%</td>
      <td>-0.00%</td>
      <td>-</td>
    </tr>
    <tr>
      <td><b>Hits</b></td>
      <td>108011</td>
      <td>108009</td>
      <td>-2</td>
      <td>0</td>
    </tr>
    <tr>
      <td><b>Misses</b></td>
      <td>18681</td>
      <td>18683</td>
      <td>+2</td>
      <td>0</td>
    </tr>
  </tbody>
</table>

[Diff coverage report](https://mooseframework.inl.gov/docs/PRs/29624/coverage_diff/framework)

[Full coverage report](https://mooseframework.inl.gov/docs/PRs/29624/coverage/framework)


## Modules coverage

Coverage did not change

## Full coverage reports

<details>
<summary>Reports</summary>

- [`framework`](https://mooseframework.inl.gov/docs/PRs/29624/coverage/framework)
- [`chemical_reactions`](https://mooseframework.inl.gov/docs/PRs/29624/coverage/chemical_reactions)
- [`combined`](https://mooseframework.inl.gov/docs/PRs/29624/coverage/combined)
- [`contact`](https://mooseframework.inl.gov/docs/PRs/29624/coverage/contact)
- [`electromagnetics`](https://mooseframework.inl.gov/docs/PRs/29624/coverage/electromagnetics)
- [`external_petsc_solver`](https://mooseframework.inl.gov/docs/PRs/29624/coverage/external_petsc_solver)
- [`fluid_properties`](https://mooseframework.inl.gov/docs/PRs/29624/coverage/fluid_properties)
- [`fsi`](https://mooseframework.inl.gov/docs/PRs/29624/coverage/fsi)
- [`functional_expansion_tools`](https://mooseframework.inl.gov/docs/PRs/29624/coverage/functional_expansion_tools)
- [`geochemistry`](https://mooseframework.inl.gov/docs/PRs/29624/coverage/geochemistry)
- [`heat_transfer`](https://mooseframework.inl.gov/docs/PRs/29624/coverage/heat_transfer)
- [`level_set`](https://mooseframework.inl.gov/docs/PRs/29624/coverage/level_set)
- [`misc`](https://mooseframework.inl.gov/docs/PRs/29624/coverage/misc)
- [`navier_stokes`](https://mooseframework.inl.gov/docs/PRs/29624/coverage/navier_stokes)
- [`optimization`](https://mooseframework.inl.gov/docs/PRs/29624/coverage/optimization)
- [`peridynamics`](https://mooseframework.inl.gov/docs/PRs/29624/coverage/peridynamics)
- [`phase_field`](https://mooseframework.inl.gov/docs/PRs/29624/coverage/phase_field)
- [`porous_flow`](https://mooseframework.inl.gov/docs/PRs/29624/coverage/porous_flow)
- [`ray_tracing`](https://mooseframework.inl.gov/docs/PRs/29624/coverage/ray_tracing)
- [`rdg`](https://mooseframework.inl.gov/docs/PRs/29624/coverage/rdg)
- [`reactor`](https://mooseframework.inl.gov/docs/PRs/29624/coverage/reactor)
- [`richards`](https://mooseframework.inl.gov/docs/PRs/29624/coverage/richards)
- [`scalar_transport`](https://mooseframework.inl.gov/docs/PRs/29624/coverage/scalar_transport)
- [`solid_mechanics`](https://mooseframework.inl.gov/docs/PRs/29624/coverage/solid_mechanics)
- [`solid_properties`](https://mooseframework.inl.gov/docs/PRs/29624/coverage/solid_properties)
- [`stochastic_tools`](https://mooseframework.inl.gov/docs/PRs/29624/coverage/stochastic_tools)
- [`thermal_hydraulics`](https://mooseframework.inl.gov/docs/PRs/29624/coverage/thermal_hydraulics)
- [`xfem`](https://mooseframework.inl.gov/docs/PRs/29624/coverage/xfem)

</details>



This comment will be updated on new commits.

2025-01-02 15:49 UTC, loganharbour requested changes
Not ready for this until conda infrastructure changes are complete

2025-01-02 22:11 UTC, nmnobre commented
> Not ready for this until conda infrastructure changes are complete
> 
> @nmnobre this will also require a bump to conda packages, as the `moose-pyhit` conda package relies on this.

I'm a bit confused... I bumped the version in `conda/pyhit/meta.yaml` but as far as I can tell, that points to https://github.com/milljm/moose-pyhit.git anyway, which seems severely outdated? It both points to an old moose commit (which will of course not have the changes here to `hit.cpp` - and it's missing some previous changes too) but also doesn't seem to be up to date with `python/pyhit/pyhit.py` in this repo?

But, surely the apptainer/docker failures are unrelated to conda?

Cheers!

2025-01-04 00:10 UTC, nmnobre commented
@loganharbour All green. Thanks for the help and apologies for messing up #29589. Can I get this in before #29104? 😇

2025-01-07 13:54 UTC, milljm commented
Changing Python versions requires a change to the entire stack. You'll need to start at the beginning with `moose-mpi`:

https://github.com/idaholab/moose/blob/1e17680adfcc2117439231c38b5bb9cb3a102636/conda/mpi/meta.yaml#L100

From experience, I can tell you I had issues getting our TestHarness to work with Python 3.12. So 3.13 may be quite the project!

2025-01-07 14:01 UTC, nmnobre commented
> Edit: My mistake, I thought we were attempting to bump Python, not make something else compatible with Python 3.13...

Yes!
It's just I've got 3.13 on my machine and had to keep 3.12 around just because of MOOSE, in particular `hit.cpp`.
I tried regenerating with the latest Cython and it just worked, so that's all I need. :)

2025-01-07 14:04 UTC, milljm commented on conda/pyhit/meta.yaml
> +{% set version = "2025.01.07" %}
FYI, Changing anything in conda/pyhit is no longer necessary, as PyHIT is now being built as an output package in conda/wasp. Changes in this recipe will actually be ignored by Civet.

Ideally we should remove conda/pyhit. I would support and help in its removal if you would like to make that a part of this PR?

```bash
git rm -rf conda/pyhit
```

2025-01-07 14:09 UTC, milljm commented on conda/pyhit/meta.yaml
> +{% set version = "2025.01.07" %}
We can also ignore my request, and I will remove it in another PR another day :)

2025-01-07 14:14 UTC, nmnobre commented on conda/pyhit/meta.yaml
> +{% set version = "2025.01.07" %}
No, this makes sense and explains my confusion above with conda/pyhit and https://github.com/milljm/moose-pyhit.

2025-01-07 14:23 UTC, milljm requested changes
Need to address versioner.yaml file

2025-01-07 14:23 UTC, milljm commented on scripts/tests/versioner_hashes.yaml
> +  moose-dev: 12cd548
We need to list all libraries here. There is an argument you can supply to `./versioner.py` simplify the process:

- Commit all your changes, then
- run versioner as so: `./versioner.py --summary`

Append those results to this file, and commit those changes as the last separate commit to your PR. Keeping it separate allows for easy cherry-picking when making additional edits to your PR.

> [!TIP]
> There is also another feature of versioner.py that you may find useful:
> `./versioner.py --verify 1e17680a`
> _where `1e17680a` is an upstream hash of some kind_
> It will supply a summary of changes, and hints of invalid entries or changes required and not detected.

2025-01-07 14:32 UTC, milljm commented on conda/pyhit/meta.yaml
> +{% set version = "2025.01.07" %}
I can imagine! Plus having it be my own personal repository... gross.

My apologies not removing this when I moved PyHIT into the WASP Conda package.

2025-01-07 16:08 UTC, moosebuild commented
Job [Conda build (Intel Mac)](https://civet.inl.gov/job/2627116/) on 50b545d : invalidated by @milljm

2025-01-07 20:56 UTC, milljm approved these changes

2025-02-10 17:30 UTC, milljm commented on scripts/tests/versioner_hashes.yaml
> +  moose-dev: 5a18091
❤️

2025-02-19 14:19 UTC, milljm commented
Fenix documentation test failures are unrelated. Merging...

2025-02-19 14:35 UTC, loganharbour approved these changes

2025-02-19 14:39 UTC, merged