RadialDisplacementAux
idaholab/moose pull request #7607
Opened 2016-08-23 23:10 UTC by bwspenc

closes #7604

2016-08-23 23:10 UTC, bwspenc commented
@jiangwen84

2016-08-24 01:33 UTC, dschwen commented on modules/tensor_mechanics/include/auxkernels/RadialDisplacementAux.h
> +   * Calcualtes the radial displacement for cylindrical or spherical
Typo calculates

2016-08-24 02:10 UTC, dschwen commented on modules/tensor_mechanics/src/auxkernels/RadialDisplacementAux.C
> +  }
This loop should be factored out. I just wrote one like it in the tensor mechanics action.

2016-08-24 02:13 UTC, dschwen commented
I think the design could be simplified by tossing out most parameters and the have origin (just set it to 0 by default and get rid of the extra coffee path)

2016-08-24 14:09 UTC, permcody commented
On another note - it'd be nice if a BISON person would take a look at the failed test here:
```zrh_formation.zrh_formation```

It exodiffs quite regularly.

2016-09-26 19:05 UTC, bwspenc commented on modules/tensor_mechanics/src/auxkernels/RadialDisplacementAux.C
> +  }
My new version still has this.  We discussed this, and agreed that we would create a separate issue to address this.

2016-09-26 19:24 UTC, dschwen commented on modules/tensor_mechanics/include/auxkernels/RadialDisplacementSphereAux.h
> +   */
This comment needs to be right before the class, not the constructor. (same with the other class)

2016-09-26 19:25 UTC, dschwen commented on modules/tensor_mechanics/src/auxkernels/RadialDisplacementCylinderAux.C
> +  _disp_vals.resize(_ndisp);
these two lines should be replaced by initializer list entries.

2016-09-26 19:26 UTC, dschwen commented on modules/tensor_mechanics/src/auxkernels/RadialDisplacementCylinderAux.C
> +    }
no braces here

2016-09-26 19:27 UTC, dschwen commented on modules/tensor_mechanics/src/auxkernels/RadialDisplacementCylinderAux.C
> +  if (_coord_system == Moose::COORD_XYZ)
usually we use a switch rather than an if else if else

2016-09-26 19:28 UTC, dschwen requested changes

2016-09-26 20:05 UTC, bwspenc commented
@dschwen I addressed all of your comments, but they're not going away like they used to. Maybe that's a new feature of github -- it's been a few weeks since I've used it.

2016-09-26 20:15 UTC, jiangwen84 commented
@bwspenc  This works for nodal variable. I think it will be good to check if isNodal() is true in the constructor?

2016-09-26 20:19 UTC, dschwen commented on modules/tensor_mechanics/src/auxkernels/RadialDisplacementSphereAux.C
> +    Point current_point (*_current_node);
I think @jiangwen84 is right. For elemental aux vars this will derefernce a null pointer. Also: space.

2016-09-26 20:19 UTC, dschwen requested changes

2016-09-26 22:39 UTC, bwspenc commented on modules/tensor_mechanics/src/auxkernels/RadialDisplacementSphereAux.C
> +    Point current_point (*_current_node);
Yeah, good point, @jiangwen84.  That would prevent the issue we had when we accidentally used this on an element AuxVariable.  I put a check in the constructor.

2016-09-27 14:47 UTC, dschwen approved these changes

2016-09-27 14:47 UTC, merged