Modified RigidBodyMultiKernelAction
idaholab/moose pull request #7731
Opened 2016-09-13 00:52 UTC by SudiptaBiswas

- Modified RigidBodyMultiKernelAction to reflect updates of the rigidbodymotion objects
- Added test for the object 

- closes #7730

2016-09-13 15:16 UTC, permcody commented on modules/phase_field/src/action/RigidBodyMultiKernelAction.C
> +      params.set<UserObjectName>("grain_tracker_object") = {getParam<UserObjectName>("grain_tracker_object")};
You should probably drop the curly braces in all of these statements. It looks like the new initializer_list syntax but it's not in this context. You just have an anonymous scope which is unecessary here.

2016-09-13 15:45 UTC, SudiptaBiswas commented on modules/phase_field/src/action/RigidBodyMultiKernelAction.C
> +      params.set<UserObjectName>("grain_tracker_object") = {getParam<UserObjectName>("grain_tracker_object")};
okay

2016-09-13 18:12 UTC, dschwen commented on modules/phase_field/src/action/MatVecRealGradAuxKernelAction.C
> +      MaterialPropertyName _div_prop = getParam<MaterialPropertyName>("divergence_property");
No. You are making this a local variable that immediately goes out of scope!

2016-09-13 18:31 UTC, SudiptaBiswas commented on modules/phase_field/src/action/MatVecRealGradAuxKernelAction.C
> +      MaterialPropertyName _div_prop = getParam<MaterialPropertyName>("divergence_property");
Yeah, I realized that. Will fix this.

2016-09-19 22:28 UTC, dschwen commented on modules/phase_field/src/action/MultiAuxVariablesAction.C
> +          std::string var_name = _var_name_base[val] + Moose::stringify(gr) + Moose::stringify(x);
I think it would be better to have `_x`, `_y`, and `_z` as suffixes (to improve the experience with visualization software like Paraview)

2016-09-19 22:29 UTC, dschwen commented on modules/phase_field/src/base/PhaseFieldApp.C
> -  registerAction(MatVecRealGradAuxKernelAction, "add_aux_kernel");
if you are deregistering this object you may as well delete it

2016-09-19 22:31 UTC, dschwen requested changes
Looks mostly good except for the two small comments.

2016-09-19 22:39 UTC, SudiptaBiswas commented on modules/phase_field/src/base/PhaseFieldApp.C
> -  registerAction(MatVecRealGradAuxKernelAction, "add_aux_kernel");
I meant to deprecate this object not delete completely. I should not have deregister this.

2016-09-19 22:44 UTC, dschwen commented on modules/phase_field/src/base/PhaseFieldApp.C
> -  registerAction(MatVecRealGradAuxKernelAction, "add_aux_kernel");
Ok, but then you should not change/remove its functionality in the class source.

2016-09-19 22:56 UTC, SudiptaBiswas commented on modules/phase_field/src/base/PhaseFieldApp.C
> -  registerAction(MatVecRealGradAuxKernelAction, "add_aux_kernel");
okay.

2016-09-20 15:39 UTC, dschwen approved these changes

2016-09-20 15:39 UTC, merged