Span and Wagner EOS for CO2
idaholab/moose pull request #7743
Opened 2016-09-16 01:36 UTC by cpgr

This implements the Span and Wagner EOS for CO2 in the `fluid_properties` module. This is one of the main fluids that we use in our work, and this formulation (Span and Wagner) is considered the 'gold standard'.

Adds tests of all properties.

Note: This EOS requires iteration to find density given pressure and temperature. We have typically used Brent's method to find this root, so I have implemented a version in this PR. 

pinging @andrsd - I've only got one more fluid to add after this one so I'll stop making you find all of my formatting errors soon
Refs #6972

2016-09-19 13:41 UTC, andrsd commented on modules/fluid_properties/include/userobjects/CO2FluidProperties.h
> +
No empty line

2016-09-19 13:45 UTC, andrsd commented on modules/fluid_properties/src/userobjects/CO2FluidProperties.C
> +  for (unsigned int i =0; i < _n4.size(); ++i)
space after `=`

2016-09-19 13:46 UTC, andrsd commented on modules/fluid_properties/src/userobjects/CO2FluidProperties.C
> +      std::exp( - std::pow(delta, _c2[i]));
No space after `(`

2016-09-19 13:47 UTC, andrsd commented on modules/fluid_properties/src/userobjects/CO2FluidProperties.C
> + for (unsigned int i = 0; i < _n4.size(); ++i)
Indent by 2 spaces

2016-09-19 13:48 UTC, andrsd commented on modules/fluid_properties/src/userobjects/CO2FluidProperties.C
> +    }
This has too much indentation, should be 2 spaces...

2016-09-19 13:49 UTC, andrsd commented on modules/fluid_properties/src/userobjects/CO2FluidProperties.C
> +  || ((temperature < _triple_point_temperature) && (pressure > sublimationPressure(temperature))))
Either add indentation or move `||` to the previous line

2016-09-19 13:51 UTC, andrsd commented on modules/fluid_properties/src/userobjects/CO2FluidProperties.C
> +std::vector<Real>
`const std::vector<Real> &` will be better unless you plan on changing the constants...

2016-09-19 13:54 UTC, andrsd commented on modules/fluid_properties/tests/co2/partial_density.i
> +     property = partial_density
Indent by 2 spaces

2016-09-19 13:54 UTC, andrsd commented on modules/fluid_properties/tests/co2/sublimation.i
> +     property = sublimation_pressure
Indent by 2 spaces

2016-09-19 13:55 UTC, andrsd commented on modules/fluid_properties/tests/co2/sweos.i
> +     property = c
Indent by 2 spaces in all these blocks

2016-09-19 13:55 UTC, andrsd commented on modules/fluid_properties/tests/co2/thermalcond.i
> +     property = k
Indent by 2 spaces

2016-09-19 13:56 UTC, andrsd commented on modules/fluid_properties/tests/co2/vapour.i
> +     property = saturated_liquid_density
Indent by 2 spaces in all 3 blocks

2016-09-19 13:58 UTC, andrsd commented on modules/fluid_properties/include/materials/CO2FluidPropertiesTestMaterial.h
> +  /// Vapour pressure (Pa)
Let's go with the AE spelling: vapor. I am putting the comment only here, but it is on several other lines below

2016-09-19 13:58 UTC, andrsd requested changes

2016-09-19 21:40 UTC, cpgr commented on modules/fluid_properties/src/userobjects/CO2FluidProperties.C
> +  || ((temperature < _triple_point_temperature) && (pressure > sublimationPressure(temperature))))
I think I'll put the `||` on the previous line

2016-09-19 21:41 UTC, cpgr commented on modules/fluid_properties/src/userobjects/CO2FluidProperties.C
> +std::vector<Real>
I'll make this `const`

2016-09-19 21:42 UTC, cpgr commented on modules/fluid_properties/include/materials/CO2FluidPropertiesTestMaterial.h
> +  /// Vapour pressure (Pa)
I'll change these to the American spelling, and also the function with vapour in its name as well.

2016-09-19 21:48 UTC, andrsd commented on modules/fluid_properties/include/materials/CO2FluidPropertiesTestMaterial.h
> +  /// Vapour pressure (Pa)
Yes, that's what I had in mind, not only variable names, but also methods, comments, etc... 👍

2016-09-20 00:39 UTC, cpgr commented on modules/fluid_properties/src/userobjects/CO2FluidProperties.C
> +std::vector<Real>
If I change this return type to `const std::vector<Real> &` I get a `warning: returning reference to local temporary object`. Is `const std::vector<Real>` ok instead?

2016-09-20 02:50 UTC, andrsd commented on modules/fluid_properties/src/userobjects/CO2FluidProperties.C
> +std::vector<Real>
You would have to do something like:
```
static std::vector<Real> hc{-8.55445, 4.01195, 9.52345};
return hc;
```
Or you could make the constants a static member of this class and return that.

2016-09-21 13:59 UTC, andrsd commented on modules/fluid_properties/src/userobjects/CO2FluidProperties.C
> + for (unsigned int i = 0; i < _n4.size(); ++i)
Looks like we missed this one: indent by 2 space...

2016-09-21 14:01 UTC, andrsd requested changes

2016-09-21 23:26 UTC, cpgr commented on modules/fluid_properties/src/userobjects/CO2FluidProperties.C
> + for (unsigned int i = 0; i < _n4.size(); ++i)
I've fixed this one, and also added a `mooseError` in beta as it isn't implemented. Thanks again for looking at these

2016-09-22 14:38 UTC, andrsd approved these changes

2016-09-22 14:38 UTC, merged

2016-09-22 14:39 UTC, andrsd commented
Thanks for the contribution @cpgr