Split heat conduction time derivative kernel
idaholab/moose pull request #7761
Opened 2016-09-21 22:23 UTC by dschwen

This includes a rewrite of the `JvarMapInterface` with a more elegant mapping method call. Let's see if the App tests pass.

Closes #7759

2016-09-21 23:25 UTC, dschwen commented
I'll work on a fix for Marmot. Should be easy.

2016-09-22 14:54 UTC, dschwen commented
I've mate this a compatible change (by leaving the old call in there). I'll update marmot and then do a follow up PR to remove the method.

2016-09-22 16:09 UTC, dschwen commented
I've implemented your suggestion @andrsd

2016-09-22 16:42 UTC, aeslaughter commented
You need to update the tutorials for this change, including the content on the current wiki.

2016-09-22 16:45 UTC, dschwen commented
@aeslaughter I may need to do that in the future. I've let the current kernel as it is (it is used heavily). My plan is to remove the heat capacity additions to simplify it and then migrate all tutorial files to the new `HeatCapacityConductionTimeDerivative`. Let's do this in a follow up PR.

2016-09-22 18:32 UTC, aeslaughter commented on modules/heat_conduction/src/base/HeatConductionApp.C
>    registerNamedKernel(HeatConductionKernel, "HeatConduction");
This should be changed to `registerDeprecatedObjectName` if you really plan to remove this eventually.

2016-09-22 18:32 UTC, aeslaughter commented on modules/heat_conduction/src/kernels/HeatCapacityConductionTimeDerivative.C
> +}
Please add `addClassDescription`

2016-09-22 18:33 UTC, aeslaughter commented on modules/heat_conduction/src/kernels/SpecificHeatConductionTimeDerivative.C
> +}
Please add `addClassDescription`

2016-09-22 18:35 UTC, aeslaughter requested changes
Are you interested in being a beta tester for markdown documentation for heat_conduction. If so, I can get a PR merged that adds the configuration, then you could add the markdown files with this.

2016-09-22 18:54 UTC, dschwen commented on framework/include/utils/JvarMapInterface.h
>    JvarMapInterface(const InputParameters & parameters);
It is an `Interface class ("Veneer") to provide a mapping from 'jvar' in` `computeQpOffDiagJacobian into the _coupled_moose_vars array`.

2016-09-22 18:57 UTC, dschwen commented on modules/heat_conduction/src/base/HeatConductionApp.C
>    registerNamedKernel(HeatConductionKernel, "HeatConduction");
I'm not touching that Kernel. It is a different part of the residual! Since it is not deprecated I think this is the right registration call.

2016-09-22 19:47 UTC, dschwen commented
Ok, adding `override` to the `JvarMapInterface` class revealed an issue. The class is templated on integrated boundary conditions as well, and those don't have `computeOffDiagJacobian`.

2016-09-22 19:52 UTC, permcody commented
Freakin' awesome. Override rules!

2016-09-22 23:12 UTC, dschwen commented
Oh man, I tried so hard to make this override the correct function only (using `std::conditional` to determine some intermediate base class etc.). At the end the compiler gave up and flat out lied to me about some class not being a base class of my final derived object. This had nested templates like an onion though...

2016-09-22 23:13 UTC, dschwen commented
Oh, yeah, no way to keep this compatible with Marmot now. I have a fix ready.

2016-09-23 14:22 UTC, aeslaughter approved these changes

2016-09-23 14:22 UTC, merged

2016-09-23 14:54 UTC, bwspenc commented
Hold on -- I discussed this with @dschwen the other day, and I thought we came to the conclusion that this was kind of a bad idea.  We originally had `HeatConductionTimeDerivative`, which took the heat capacity and density as inputs. That was hacked up about a year ago to add an option to only input specific heat, and as I understand it, the only reason for that was for a tutorial problem.

I thought the better solution was to undo the changes to `HeatConductionTimeDerivative` (so it would only take density and specific heat). If someone really wanted to just input specific heat, they could input 1 for the density, or if that wasn't good enough, we could put this `SpecificHeatConductionTimeDerivative` class in the directory with that tutorial problem.

In my opinion, this is now kind of a mess. We have three classes that basically do the same thing.  The one with the most logical name has more options than it should and is implemented in a messy way. The two clean simple ones have weird names. If I want this term in the heat equation, why would I think to look for an object called `HeatCapacityConductionTimeDerivative`?  I think one would assume that kernel would need the heat capacity.  Why should that be in the name of the object?

2016-09-23 17:19 UTC, aeslaughter commented
I was un-aware of descent, perhaps we can work this out in the MOOSE cube later today.