Add some docs for the recent heat time kernel split
idaholab/moose pull request #7766
Opened 2016-09-23 16:40 UTC by dschwen

Let's see how this goes...

Refs #7759

2016-09-23 17:23 UTC, moosebuild commented
Job `Moose Documentation:linux-clang` on 2330730 wanted to post the following:

View the site at http://mooseframework.org/docs/PRs/43674/site

2016-09-23 18:00 UTC, moosebuild commented
Job `Moose Documentation:linux-clang` on d50b2a0 wanted to post the following:

View the site at http://mooseframework.org/docs/PRs/43683/site

2016-09-23 21:01 UTC, aeslaughter commented on docs/content/framework/interfaces/DerivativeMaterialInterface.md
> +
Did you want ``` on these guys? This creates an inline code block. You can use single ticks and get monospaced text that is a bit more integrated with the next, in my opinion.

2016-09-23 21:04 UTC, aeslaughter commented on docs/content/framework/interfaces/DerivativeMaterialInterface.md
> +[..]
Can you just include a reference to actual code here? That way if something changes this doesn't become out-dated. You can grab pieces of code with clang (slow) or with 'start' and 'end' tag.

```
!text /path/to/MyExampleClass.C end=something in the text that denotes the end
```

2016-09-23 21:09 UTC, aeslaughter commented on docs/content/modules/heat_conduction/systems/Kernels/HeatCapacityConductionTimeDerivative.md
> +!devel /Kernels/HeatCapacityConductionTimeDerivative float=right width=auto margin=20px padding=20px background-color=#F8F8F8
You might want to put this somewhere else or remove for these two classes, the links are two long. Maybe the links should only have the class name? What do you think? I had the whole path so people would know where the class lives, but if you click the file you would no where it lives.

2016-09-23 21:09 UTC, aeslaughter requested changes

2016-09-23 21:18 UTC, dschwen commented on docs/content/framework/interfaces/DerivativeMaterialInterface.md
> +[..]
uhm, I like this in theory, but I'd have a hard time finding an uncluttered example like the one I pasted in.

2016-09-23 21:19 UTC, dschwen commented on docs/content/modules/heat_conduction/systems/Kernels/HeatCapacityConductionTimeDerivative.md
> +!devel /Kernels/HeatCapacityConductionTimeDerivative float=right width=auto margin=20px padding=20px background-color=#F8F8F8
?

2016-09-23 21:20 UTC, dschwen commented on docs/content/framework/interfaces/DerivativeMaterialInterface.md
> +
Sure, uf single tick is the convention I'll go ahead and change this.

2016-09-23 21:50 UTC, dschwen commented
I left keywords, class and method names with three ticks and changed the rest to single tick. When there is a clear convention we can go over this again. I will leave the code as it is. Sorry, but I don't want to create two new classes just for the minimal snippets (which use ellipses to reduce clutter - which the source inclusion cannot do currently).

2016-09-23 21:57 UTC, moosebuild commented
Job `Moose Documentation:linux-clang` on 063bec1 wanted to post the following:

View the site at http://mooseframework.org/docs/PRs/43729/site

2016-09-26 14:14 UTC, aeslaughter commented on docs/content/framework/interfaces/DerivativeMaterialInterface.md
> +[..]
//...

2016-09-26 14:14 UTC, aeslaughter commented on docs/content/framework/interfaces/DerivativeMaterialInterface.md
> +[..]
//...

2016-09-26 14:16 UTC, aeslaughter reviewed
Looks good except for you forgot to update your snippets with //... in a two spots.

2016-09-26 14:23 UTC, dschwen commented on docs/content/framework/interfaces/DerivativeMaterialInterface.md
> +[..]
This is fixed now. Again GitHub is not picking up this change :-/

2016-09-26 14:25 UTC, aeslaughter commented on docs/content/framework/interfaces/DerivativeMaterialInterface.md
> +[..]
It showed up for me.

2016-09-26 14:29 UTC, moosebuild commented
Job `Moose Documentation:linux-clang` on 526fed5 wanted to post the following:

View the site at http://mooseframework.org/docs/PRs/43785/site

2016-09-26 14:31 UTC, permcody commented on docs/content/framework/interfaces/DerivativeMaterialInterface.md
> +[..]
Well I think you guys are talking about different things. The "outdated diff" stuff seems to have disappeared which is unfortunate. The change is there if you click on the commit. This is a step back as far as I'm concerned.

2016-09-26 21:06 UTC, aeslaughter approved these changes

2016-09-26 21:06 UTC, merged