executioner: move solver related params into FEProblem
idaholab/moose pull request #7776
Opened 2016-09-26 21:01 UTC by rwcarlsen

This is cleanup and preparation for more work on #5229.

2016-09-26 22:46 UTC, rwcarlsen commented
Hints welcome if anybody knows at a glance what might be the issue.  Otherwise, I'll do some debugging tomorrow.

2016-09-27 14:57 UTC, friedmud commented
Can you say a bit more about why you want to do this?  You're going to have to update every input file on the planet... and I'm not sure it gains us anything.

I'm not necessarily against it... but I think there needs to be some serious justification for this.  Every input file since the beginning of time has specified these parameters in the `Executioner` block...

Also: if we're going to move them out of `Executioner` then there needs to be a debate about _where_ to move them.  I don't necessarily think the `Problem` block is the right block either (most people don't even know that that block exists... and most input files don't define it).

2016-09-27 14:59 UTC, friedmud commented
I see what you've done... you're trying to parse the parameters in the `Executioner` block but store them on the `Problem`?

I'm not for that change.

If the parameters don't belong with the `Executioner`... then let's move them.  If they do... then keep them there.

2016-09-27 15:00 UTC, friedmud commented
Also: as a general rule: we need to move stuff OUT of `FEProblem`... not INTO it!  😄

2016-09-27 15:15 UTC, YaqiWang commented
That is what I am about to say: FEProblem is too big...

2016-09-27 16:21 UTC, rwcarlsen commented
Discussion with @permcody suggested that there was a disconnect between what "executioner" means in the input file and in the code.  I am much less acquainted with MOOSE history and can't strongly defend either side particularly well.  I agree that the much more elegant (for code) solution would be to maintain direct association between params in input file blocks and params in code.  In this chain:

```
Input-file ==> parameter spec/init ==> parameter usage
```

that association is broken between parameter spec/init and parameter usage.  This refactor doesn't fix the breakage, but moves the breakage to be between input file and parameter spec/init instead.  My opinion is that this is a less bad place to break the association.  Breaking every input file ever seems like not worth it, unless we are ready to make MOOSE 2.0.

This PR does not move those parameters from the Executioner block (I see you noticed that now).  Even though the solver parameters might not belong in FEProblem (which I definitely agree is too large), that is where they are now.  If someone comes along later and refactors the actual solver parameters out of the FEProblem class, they will probably want to have all the associated InputParameters with the new code (class) and actual member variables.  This preemptively decouples those InputParameters from the Executioner class where they were never stored/used already and makes them sit along-side the actual code they affect.

This also selfishly makes it easier for me to discover/see the actual executioner functionality free of things that were not super strongly related to the services it provides to the framework.

2016-09-27 16:49 UTC, friedmud commented
If we're going to move them out... let's not move them to `FEProblem` directly.  And, I definitely understand not wanting to break every input file.

We've kind of been needing a `[Solver]` block for quite a while... but we've just continued sticking stuff in `Executioner` for now.

How about, as a start, we at least create a `SolverParams` (or whatever) object to stuff these parameters into.  For now, that object can hang off of `FEProblem` (or maybe even better: `NonlinearSystem` since that's where the solver is).

2016-09-27 17:02 UTC, rwcarlsen commented
So FEProblem already has a ``SolverParams _solver_params`` member variable.  Currently it doesn't have much in it:

```c++
class SolverParams
{
public:
  SolverParams();

  Moose::SolveType _type;
  Moose::LineSearchType _line_search;
};
```

Would these options fit together well?  They currently live in several places already :/

```c++
  EquationSystems & esys = es();
  esys.parameters.set<Real> ("linear solver tolerance")= params.get<Real>("l_tol");
  esys.parameters.set<Real> ("linear solver absolute step tolerance") = params.get<Real>("l_abs_step_tol");
  esys.parameters.set<unsigned int> ("linear solver maximum iterations") = params.get<unsigned int>("l_max_its");
  esys.parameters.set<unsigned int> ("nonlinear solver maximum iterations") = params.get<unsigned int>("nl_max_its");
  esys.parameters.set<unsigned int> ("nonlinear solver maximum function evaluations") = params.get<unsigned int>("nl_max_funcs");
  esys.parameters.set<Real> ("nonlinear solver absolute residual tolerance") = params.get<Real>("nl_abs_tol");
  esys.parameters.set<Real> ("nonlinear solver relative residual tolerance") = params.get<Real>("nl_rel_tol");
  esys.parameters.set<Real> ("nonlinear solver absolute step tolerance") = params.get<Real>("nl_abs_step_tol");
  esys.parameters.set<Real> ("nonlinear solver relative step tolerance") = params.get<Real>("nl_rel_step_tol");

  getNonlinearSystem()._compute_initial_residual_before_preset_bcs = params.get<bool>("compute_initial_residual_before_preset_bcs");
  getNonlinearSystem()._l_abs_step_tol = params.get<Real>("l_abs_step_tol");
  getNonlinearSystem().setDecomposition(params.get<std::vector<std::string> >("splitting"));

  FileNameNoExtension restart_file_base(params.get<FileNameNoExtension>("restart_file_base"));
  if (!restart_file_base.empty())
    setRestartFile(restart_file_base);
```

Some in equation system, some in FEProblem's _app and _resurector members, some in nonlinear system member, etc.  Maybe just the EquationSystem params would fit in the SolverParams class?

2016-09-27 17:43 UTC, friedmud commented
I think most of those would fit together rather well.

The `setDecomposition()` doesn't really belong there... I don't even know
what that's doing... it should be set as data on MooseMesh.

On Tue, Sep 27, 2016 at 1:03 PM Robert Carlsen <notifications@github.com>
wrote:

> So FEProblem already has a SolverParams _solver_params member variable.
> Currently it doesn't have much in it:
>
> class SolverParams
> {public:
>   SolverParams();
>
>   Moose::SolveType _type;
>   Moose::LineSearchType _line_search;
> };
>
> Would these options fit together well? They currently live in several
> places already :/
>
>   EquationSystems & esys = es();
>   esys.parameters.set<Real> ("linear solver tolerance")= params.get<Real>("l_tol");
>   esys.parameters.set<Real> ("linear solver absolute step tolerance") = params.get<Real>("l_abs_step_tol");
>   esys.parameters.set<unsigned int> ("linear solver maximum iterations") = params.get<unsigned int>("l_max_its");
>   esys.parameters.set<unsigned int> ("nonlinear solver maximum iterations") = params.get<unsigned int>("nl_max_its");
>   esys.parameters.set<unsigned int> ("nonlinear solver maximum function evaluations") = params.get<unsigned int>("nl_max_funcs");
>   esys.parameters.set<Real> ("nonlinear solver absolute residual tolerance") = params.get<Real>("nl_abs_tol");
>   esys.parameters.set<Real> ("nonlinear solver relative residual tolerance") = params.get<Real>("nl_rel_tol");
>   esys.parameters.set<Real> ("nonlinear solver absolute step tolerance") = params.get<Real>("nl_abs_step_tol");
>   esys.parameters.set<Real> ("nonlinear solver relative step tolerance") = params.get<Real>("nl_rel_step_tol");
>
>   getNonlinearSystem()._compute_initial_residual_before_preset_bcs = params.get<bool>("compute_initial_residual_before_preset_bcs");
>   getNonlinearSystem()._l_abs_step_tol = params.get<Real>("l_abs_step_tol");
>   getNonlinearSystem().setDecomposition(params.get<std::vector<std::string> >("splitting"));
>
>   FileNameNoExtension restart_file_base(params.get<FileNameNoExtension>("restart_file_base"));
>   if (!restart_file_base.empty())
>     setRestartFile(restart_file_base);
>
> Some in equation system, some in FEProblem's _app and _resurector members,
> some in nonlinear system member, etc. Maybe just the EquationSystem params
> would fit in the SolverParams class?
>
> —
> You are receiving this because you commented.
>
>
> Reply to this email directly, view it on GitHub
> <https://github.com/idaholab/moose/pull/7776#issuecomment-249929315>, or mute
> the thread
> <https://github.com/notifications/unsubscribe-auth/AA1JMZ9p2vOhbb8hpOlS3cvxAk8d2_UOks5quUw6gaJpZM4KG_Vo>
> .
>

2016-09-27 18:52 UTC, fdkong commented
> The `setDecomposition()` doesn't really belong there... I don't even know
> what that's doing... it should be set as data on MooseMesh.

`setDecomposition()` is used to set a flag to tell MOOSE we want to use the fieldSplit preconditioner and to do some preparation.

2016-09-27 18:53 UTC, friedmud commented
Ah - I was thinking it was setting _mesh_ decomposition.  Maybe that method
needs to be a little more explanatory (`setFieldSplitType()` ?)

On Tue, Sep 27, 2016 at 2:52 PM Fande Kong <notifications@github.com> wrote:

> The setDecomposition() doesn't really belong there... I don't even know
> what that's doing... it should be set as data on MooseMesh.
>
> setDecomposition() is used to set a flag to tell MOOSE we want to use the
> fieldSplit preconditioner and to do some preparation.
>
> —
> You are receiving this because you commented.
>
>
> Reply to this email directly, view it on GitHub
> <https://github.com/idaholab/moose/pull/7776#issuecomment-249961303>, or mute
> the thread
> <https://github.com/notifications/unsubscribe-auth/AA1JMXpLETJcFfOTPkNUHjT5Wnl8U5HBks5quWXQgaJpZM4KG_Vo>
> .
>

2016-09-27 19:08 UTC, fdkong commented
> Ah - I was thinking it was setting _mesh_ decomposition. Maybe that method needs to be a little more explanatory (`setFieldSplitType()` ?)

`setFieldSplitTopLevel()`? The function will store where is the starting point of splitting.

2016-09-27 19:23 UTC, friedmud commented
Sounds good to me.

On Tue, Sep 27, 2016 at 3:08 PM Fande Kong <notifications@github.com> wrote:

> Ah - I was thinking it was setting *mesh* decomposition. Maybe that
> method needs to be a little more explanatory (setFieldSplitType() ?)
>
> setFieldSplitTopLevel()? The function will store where is the starting
> point of splitting.
>
> —
> You are receiving this because you were mentioned.
>
>
> Reply to this email directly, view it on GitHub
> <https://github.com/idaholab/moose/pull/7776#issuecomment-249966269>, or mute
> the thread
> <https://github.com/notifications/unsubscribe-auth/AA1JMfsrAdeQ6hlgZt_aqs-Yxv-0u7bfks5quWmegaJpZM4KG_Vo>
> .
>

2017-01-06 14:22 UTC, friedmud requested changes
Good progress...

2017-01-06 14:22 UTC, friedmud commented on framework/src/base/FEProblem.C
> +FEProblem::executionerValidParams()
I understand what you're up to here... but having returned to this after a few months it still feels like `FEProblem` is not the right place for this stuff.

It really feels like we need a `SolverParams` object... and this function would go there.

2017-01-06 14:22 UTC, friedmud commented on framework/src/base/FEProblem.C
> +FEProblem::executionerValidParams()
* other than `restart_file_base`... that's not a "solver" parameter.

2017-01-10 00:02 UTC, rwcarlsen commented
Agree this isn't a great solution.  We probably should hold on this until
we have a better idea about if/when/what we are going to do w.r.t.
executioner refactor.  That is why I haven't been actively working on this
anyway.

On Fri, Jan 6, 2017 at 7:22 AM, Derek Gaston <notifications@github.com>
wrote:

> *@friedmud* requested changes on this pull request.
>
> Good progress...
> ------------------------------
>
> In framework/src/base/FEProblem.C
> <https://github.com/idaholab/moose/pull/7776#pullrequestreview-15494644>:
>
> > @@ -98,6 +98,93 @@ InputParameters validParams<FEProblem>()
>    return params;
>  }
>
> +//
> +InputParameters
> +FEProblem::executionerValidParams()
>
> I understand what you're up to here... but having returned to this after a
> few months it still feels like FEProblem is not the right place for this
> stuff.
>
> It really feels like we need a SolverParams object... and this function
> would go there.
> ------------------------------
>
> In framework/src/base/FEProblem.C
> <https://github.com/idaholab/moose/pull/7776#pullrequestreview-15494644>:
>
> > @@ -98,6 +98,93 @@ InputParameters validParams<FEProblem>()
>    return params;
>  }
>
> +//
> +InputParameters
> +FEProblem::executionerValidParams()
>
>
>    - other than restart_file_base... that's not a "solver" parameter.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/idaholab/moose/pull/7776#pullrequestreview-15494644>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/ABSeSpW8d6P2sN5thyskjaR2sxOJcbIXks5rPk4qgaJpZM4KG_Vo>
> .
>

2017-01-10 00:06 UTC, friedmud commented
Ok - should we close this for now then?

2017-01-10 00:22 UTC, fdkong commented
> It really feels like we need a SolverParams object... and this function would go there.

@friedmud, we do have an object called `SolverParams` in the folder: framework/src/base.  The object has two members only, namely `solvetyper` and `linesearch`.  It is not a bad idea if we like to move some parameters there.

2017-01-10 14:57 UTC, rwcarlsen commented
closed. created #8294 as reminder.

2017-01-10 14:57 UTC, closed without merging

2017-01-10 22:50 UTC, friedmud commented
Thanks @rwcarlsen 

@fdkong : Right, I agree that that's the right thing to do... but I think we also need a `Solver` block in the input file to go with it as well.

2017-01-10 23:13 UTC, YaqiWang commented
Does solver here mean PETSc? I thought executioner is the solver of moose applications.

2017-01-11 11:48 UTC, friedmud commented
Solver means "linear / nonlinear solver"

In my mind the Executioner is not a "solver"... but I know that in your case that's a bit more blurry.