Documentation fixes and clean up
idaholab/moose pull request #7794
Opened 2016-09-29 19:37 UTC by aeslaughter

* Makes markdown extensions more consistent with paths. the Mastodon page wasn't working correctly because of some hard-coded paths, this fixes that problem and cleans up the markdown extensions to be more consistent
*  Add some extra information when copying js/css directories from MOOSE when running in an application

(refs #6699)

2016-09-29 19:38 UTC, aeslaughter commented
@sveerara This should correct the problem with including images.

2016-09-29 19:45 UTC, moosebuild commented
Job `Moose Documentation:linux-clang` on f2bb363 wanted to post the following:

View the site at http://mooseframework.org/docs/PRs/44601/site

2016-09-29 19:53 UTC, sveerara commented
@aeslaughter, Thanks!

2016-09-29 20:00 UTC, moosebuild commented
Job `Moose Documentation:linux-clang` on 484ffc0 wanted to post the following:

View the site at http://mooseframework.org/docs/PRs/44624/site

2016-09-29 20:08 UTC, moosebuild commented
Job `Moose Documentation:linux-clang` on 4c3be31 wanted to post the following:

View the site at http://mooseframework.org/docs/PRs/44633/site

2016-10-10 16:15 UTC, milljm requested changes
Please see comments about message=. Other than that, looks good!

2016-10-10 16:15 UTC, milljm commented on python/MooseDocs/extensions/MooseImageFile.py
> +            el = self.createErrorElement(message='File not found: {}'.format(rel_filename))
You got rid of message=, So I think this here needs to follow suite?

```python
el = self.createErrorElement('File not found: {}'.format(rel_filename))
```

2016-10-10 16:15 UTC, milljm commented on python/MooseDocs/extensions/MoosePackageParser.py
> +            el = self.createErrorElement(message='Invalid MOOSEPACKAGE markdown syntax. Requires arch=, return=link|name')
message= no longer needed?

2016-10-10 16:15 UTC, milljm commented on python/MooseDocs/extensions/MoosePackageParser.py
> +                el = self.createErrorElement(message='"arch" not found in packages.yml')
message= no longer needed?

2016-10-10 16:29 UTC, aeslaughter commented on python/MooseDocs/extensions/MooseImageFile.py
> +            el = self.createErrorElement(message='File not found: {}'.format(rel_filename))
Good catch, I made the "message" argument a required item.

2016-10-10 16:51 UTC, moosebuild commented
Job `Moose Documentation:linux-clang` on 0ef9d1b wanted to post the following:

View the site at http://mooseframework.org/docs/PRs/45893/site

2016-10-10 18:16 UTC, milljm approved these changes

2016-10-10 18:21 UTC, milljm requested changes
Last issue with 'message=' I could find...

2016-10-10 18:21 UTC, milljm commented on python/MooseDocs/extensions/MooseCppMethod.py
> +            el = self.createErrorElement(message="Failed to load python clang python bindings.")
I think this is the last one

2016-10-10 19:36 UTC, moosebuild commented
Job `Moose Documentation:linux-clang` on 3140bec wanted to post the following:

View the site at http://mooseframework.org/docs/PRs/45957/site

2016-10-10 22:27 UTC, aeslaughter commented
@milljm I fixed all the "message=" stuff you located, so this is ready to go. Thanks.

2016-10-11 12:57 UTC, merged