Tests for incremental small strain and finite strain formulations for gps model
idaholab/moose pull request #7836
Opened 2016-10-07 19:41 UTC by hchen139

closes #7835

2016-10-07 19:43 UTC, hchen139 commented
@bwspenc @jiangwen84 @sapitts this PR is for the regression tests of generalized plane strain model using incremental small strain and finite strain formulations.

2016-10-10 14:42 UTC, bwspenc requested changes
Overall, looks good.  Just a couple of minor issues to work out as noted and then I think it's ready to go.

2016-10-10 14:42 UTC, bwspenc commented on modules/tensor_mechanics/src/materials/ComputeAxisymmetricRZFiniteStrain.C
> -ComputeAxisymmetricRZFiniteStrain::computeDeformGradZZ()
I don't think these functions make any sense for axisymmetric cases. The out of plane strain (theta theta) is computed as a function of the radial displacement.

2016-10-10 14:42 UTC, bwspenc commented on modules/tensor_mechanics/src/materials/ComputeAxisymmetricRZIncrementalStrain.C
> -ComputeAxisymmetricRZIncrementalStrain::computeDeformGradZZ()
Same as the comment about the other axisymmetric case.

2016-10-10 14:42 UTC, bwspenc commented on modules/tensor_mechanics/src/materials/Compute2DFiniteStrain.C
> +    // Compute the displacement gradient (2,2) value for plane strain, generalized plane strain, or axisymmetric problems
We should discuss the name of this function.  It seems to me like the old name was fine, but you must have had a reason for changing it, so I'd like to hear your thoughts.

2016-10-10 19:15 UTC, bwspenc approved these changes

2016-10-10 19:15 UTC, bwspenc commented on modules/tensor_mechanics/src/materials/Compute2DFiniteStrain.C
> +    // Compute the displacement gradient (2,2) value for plane strain, generalized plane strain, or axisymmetric problems
OK, we discussed this and I agree.

2016-10-10 19:15 UTC, bwspenc commented on modules/tensor_mechanics/src/materials/ComputeAxisymmetricRZFiniteStrain.C
> -ComputeAxisymmetricRZFiniteStrain::computeDeformGradZZ()
Never mind about this as well.  After looking at more context, I see what's going on here, and this is fine.

2016-10-10 19:15 UTC, bwspenc commented on modules/tensor_mechanics/src/materials/ComputeAxisymmetricRZIncrementalStrain.C
> -ComputeAxisymmetricRZIncrementalStrain::computeDeformGradZZ()
Never mind here as well.

2016-10-10 19:16 UTC, bwspenc commented
@aeslaughter I'm good with these changes and it's ready to go as far as I'm concerned.

2016-10-11 14:09 UTC, aeslaughter approved these changes
@bwspenc Approves these changes.

2016-10-11 14:09 UTC, merged