Optimize RBM objects in PhaseField
idaholab/moose pull request #7841
Opened 2016-10-10 17:30 UTC by SudiptaBiswas

- Provides optimization option in NonlocalKernel
- Corrects advection velocity formulation
- Updates RBM kernels
- Corrects coupled variables in RBM kernel action
- Closes #7837

2016-10-11 17:04 UTC, permcody reviewed
This looks mostly OK. I'll have @dschwen take a look too.

2016-10-11 17:04 UTC, permcody commented on framework/src/kernels/NonlocalKernel.C
> +{
Most of this code is copied directly out of Kernel. I wonder if there's a better way of implementing these algorithms in terms of the existing code. I realize that they are not 100% the same.

2016-10-11 17:04 UTC, permcody commented on modules/phase_field/src/action/RigidBodyMultiKernelAction.C
> +      v[i++] = _var_name_base + Moose::stringify(j);
Why not use `j` on the lhs too?

2016-10-11 17:04 UTC, permcody commented on modules/phase_field/src/action/RigidBodyMultiKernelAction.C
> +    v.resize(_op_num);
No need to have a resize operation here. You can size the vector as you create it.

2016-10-11 17:12 UTC, SudiptaBiswas commented on framework/src/kernels/NonlocalKernel.C
> +{
I gave it some thought actually. My initial intention was to keep these in Kernel itself. However, for optimization purpose I had to alter few things and I did not want to disturb the Kernel class.

2016-10-11 17:13 UTC, permcody commented on framework/src/kernels/NonlocalKernel.C
> +{
At the very least could you put documentation in each of these methods letting maintainers know that this code is copied from Kernel. That way if somebody comes in here and makes a change, they can check the other implementation as well.

2016-10-11 17:15 UTC, SudiptaBiswas commented on framework/src/kernels/NonlocalKernel.C
> +{
Okay, will do that.

2016-10-11 17:21 UTC, SudiptaBiswas commented on modules/phase_field/src/action/RigidBodyMultiKernelAction.C
> +      v[i++] = _var_name_base + Moose::stringify(j);
Yeah, I should do that.

2016-10-17 14:18 UTC, dschwen requested changes

2016-10-17 14:18 UTC, dschwen commented on framework/include/kernels/NonlocalKernel.h
> +   * jocobinas of the integral term from userobject once per dof
"jocobinas"

2016-10-17 14:18 UTC, dschwen commented on framework/include/kernels/NonlocalKernel.h
> +   * jocobina calculations only for nonlocal dofs that has nonzero jacobian contribution.
"jocobina"

2016-10-17 14:18 UTC, dschwen commented on modules/phase_field/src/userobjects/ComputeGrainForceAndTorque.C
> +            const RealGradient compute_torque =_JxW[_qp] * _coord[_qp] * (_current_elem->centroid() - centroid).cross(_dF[_qp][j]);
Why this change?

2016-10-17 14:45 UTC, SudiptaBiswas commented on modules/phase_field/src/userobjects/ComputeGrainForceAndTorque.C
> +            const RealGradient compute_torque =_JxW[_qp] * _coord[_qp] * (_current_elem->centroid() - centroid).cross(_dF[_qp][j]);
This helps in optimization while calculating the velocities later. Change in this userobject is done just to keep the formulation consistent everywhere.

2016-10-20 19:26 UTC, dschwen approved these changes

2016-10-21 14:49 UTC, merged