Merged  SystemTmpl into SystemBase
idaholab/moose pull request #7848
Opened 2016-10-11 19:26 UTC by fdkong

### Complete each of the following items before creating a PR

After disccussed with @andrsd, we have the following modification to allow me bring EigenSystem from Libmesh. 

```
             +--> DisplacedSystem
            | 
SystemBase ->+--> AuxiliarySystem
            |
             +-->NonlinearSystemBase+--> NonlinearSystem
                                    |
                                    +--> NonlinearEigenSystem
```

```
ProblemBase +--> FEProblem
            |
            +--> EigenProblem
```

This PR merges SystemTmpl into SystemBase.

2016-10-11 20:58 UTC, friedmud commented
Acknowledging that I see this.  I won't be able to review it until tomorrow though.

2016-10-11 22:25 UTC, fdkong commented
> Acknowledging that I see this. I won't be able to review it until tomorrow though.

Thanks @friedmud.

2016-10-12 18:54 UTC, fdkong commented
@friedmud, @andrsd do you guys have a chance to look at this? Thanks.

2016-10-12 20:23 UTC, andrsd requested changes

2016-10-12 20:23 UTC, andrsd commented on framework/include/base/AuxiliarySystem.h
> +  virtual void addVariable(const std::string & var_name, const FEType & type, Real scale_factor, const std::set< SubdomainID > * const active_subdomains = NULL) override;
remove the spaces inside `<...>`.

2016-10-12 20:23 UTC, andrsd commented on framework/include/base/SystemBase.h
> +struct VarCopyInfo {
`{` should be on a separate line

2016-10-12 20:23 UTC, andrsd commented on framework/include/base/SystemBase.h
> +  virtual void addVariable(const std::string & var_name, const FEType & type, Real scale_factor, const std::set< SubdomainID > * const active_subdomains = NULL);
`<SubdomainID>`

2016-10-12 20:23 UTC, andrsd commented on framework/include/base/SystemBase.h
> +  virtual void addScalarVariable(const std::string & var_name, Order order, Real scale_factor, const std::set< SubdomainID > * const active_subdomains = NULL);
`<SubdomainID>`

2016-10-12 20:23 UTC, andrsd commented on framework/include/base/SystemBase.h
> +  virtual void computeVariables(const NumericVector<Number> & /*soln*/){ };
`) {`.

2016-10-12 20:23 UTC, andrsd commented on framework/src/base/SystemBase.C
> +void SystemBase::saveOldSolutions()
Return types on a separate line. Everywhere in this file...

2016-10-12 20:23 UTC, andrsd commented on framework/src/base/SystemBase.C
> +void SystemBase::addVariable(const std::string & var_name, const FEType & type, Real scale_factor, const std::set< SubdomainID > * const active_subdomains)
`<SubdomainID>`

2016-10-12 20:23 UTC, andrsd commented on framework/src/base/SystemBase.C
> +void SystemBase::addScalarVariable(const std::string & var_name, Order order, Real scale_factor, const std::set< SubdomainID > * const active_subdomains)
`<SubdomainID>`

2016-10-13 15:23 UTC, fdkong commented
@friedmud, could you take a look at this before we merge?

2016-10-13 16:24 UTC, friedmud commented
Yes.
On Thu, Oct 13, 2016 at 11:23 AM Fande Kong <notifications@github.com>
wrote:

> @friedmud <https://github.com/friedmud>, could you take a look at this
> before we merge?
>
> —
> You are receiving this because you were mentioned.
>
>
> Reply to this email directly, view it on GitHub
> <https://github.com/idaholab/moose/pull/7848#issuecomment-253546467>, or mute
> the thread
> <https://github.com/notifications/unsubscribe-auth/AA1JMRhGNJqzK6DTbIeb4AYqJ3iTQBooks5qzk0EgaJpZM4KUAke>
> .
>

2016-10-17 14:46 UTC, fdkong commented
> Yes.

Pinging @friedmud. Thanks.

2016-10-17 17:24 UTC, friedmud commented
I will review this today.
On Mon, Oct 17, 2016 at 10:46 AM Fande Kong <notifications@github.com>
wrote:

> Yes.
>
> Pinging @friedmud <https://github.com/friedmud>. Thanks.
>
> —
> You are receiving this because you were mentioned.
>
>
> Reply to this email directly, view it on GitHub
> <https://github.com/idaholab/moose/pull/7848#issuecomment-254228752>, or mute
> the thread
> <https://github.com/notifications/unsubscribe-auth/AA1JMT85-nrRxRJzBtVYIEhl7OfRgxtRks5q04pNgaJpZM4KUAke>
> .
>

2016-10-18 00:05 UTC, friedmud commented
Reviewing

2016-10-18 00:30 UTC, friedmud reviewed
Overall: I'm ok with this.  It's just good, old fashioned PCOI.

Like I mention... I don't care for the idea of having `sys()` and `system()`... but I can cope if there really isn't a better idea (I don't have any).

I _do_ like the removal of `SystemTempl`... it was always kind of a pain... and since it was templated it means more code had to be in headers... now all of that has been moved to the .C files which is definitely better.

2016-10-18 00:30 UTC, friedmud commented on framework/include/base/NonlinearSystem.h
> +  virtual System & system() override { return _sys; }
I gotta say - I'm not too happy about having `sys()` and `system()`... both with different return types.  I understand the reason for it... but I don't like the naming... I'll always forget which is which...

2016-10-18 00:42 UTC, friedmud commented
BTW: This causes my own code to fail to compile (I have a `SystemTempl` specialization).

Just a heads up that this might not go through smoothly for everyone...

2016-10-18 14:38 UTC, fdkong commented
> I gotta say - I'm not too happy about having sys() and system()... both with different return types. I understand the reason for it... but I don't like the naming... I'll always forget which is which...

@friedmud, How about we change  `sys()` to `transientLibmeshSystem()`, and `system()` to `libmeshSystem()`? Because we also have our own `systems` (`NonlinearSystem`, `NonlinearEigenSystem`, `AuxiliarySystem`, et.c ). This naming  distinguishes  moose `systems` from libmesh `systems`.

2016-10-18 14:44 UTC, fdkong commented
> BTW: This causes my own code to fail to compile (I have a SystemTempl specialization).
> 
> Just a heads up that this might not go through smoothly for everyone...

What causes this problem? I  moved four functions only down to sub-classes. It should not be difficult to change any users they have a XXXsystem derived from SystemTmpl.

2016-10-18 14:48 UTC, fdkong commented
> I gotta say - I'm not too happy about having sys() and system()... both with different return types. 

I did not see any easy way to merge those two functions together. The reason is that TransientSystem in libmesh is a class template not a class so that it can not serve as a super-class. 

>I understand the reason for it... but I don't like the naming... I'll always forget which is which...

2016-10-19 14:18 UTC, fdkong commented
@andrsd, could you please approve my changes, if you are fine with that?

@friedmud, are we going to merge this one? Do you have any better idea on naming ?

2016-10-19 14:38 UTC, friedmud commented
@fdkong It fails because I have a new "System" class that inherits from `SystemTempl`!

It can be fixed up... I just wanted to make you aware that anyone that has done anything similar will get a failure from this PR.

2016-10-19 14:42 UTC, fdkong commented
> @fdkong It fails because I have a new "System" class that inherits from SystemTempl!
> 
> It can be fixed up... I just wanted to make you aware that anyone that has done anything similar will get a failure from this PR.

@friedmud, gotta.

2016-10-19 15:50 UTC, andrsd approved these changes

2016-10-19 15:52 UTC, fdkong commented
> I gotta say - I'm not too happy about having sys() and system()... both with different return types. I understand the reason for it... but I don't like the naming... I'll always forget which is which...
> 
> @friedmud, How about we change sys() to transientLibmeshSystem(), and system() to libmeshSystem()? Because we also have our own systems (NonlinearSystem, NonlinearEigenSystem, AuxiliarySystem, et.c ). This naming distinguishes moose systems from libmesh systems.

@friedmud, do you like me to make this change?

2016-10-19 15:54 UTC, fdkong commented
@permcody, @YaqiWang do you guys have any comments  on this?

2016-10-19 16:38 UTC, merged

2016-10-20 23:26 UTC, mangerij commented
Just curious, do you think this PR may have changed how PETSc builds a matrix for a problem with periodic boundary conditions?

I've been on `6f016fb` and just updated today and now I'm finding some issues with incompatible vector lengths (PETSc error) when I apply PBC to some variables. Unfortunately, Ferret doesn't have a test for this sort of thing yet (a work in progress) so it never broke in CIVET.

2016-10-21 09:40 UTC, andrsd commented
The most of the low-level PETSc calls are in libMesh, especially the ones for building matrices and vectors. We did not touch that in this PR, so I'd say this PR did not cause it...