Add BoundingValue Damper and support for NodalDamper ref #7856
idaholab/moose pull request #7860
Opened 2016-10-12 19:19 UTC by bwspenc

2016-10-12 19:34 UTC, bwspenc commented
A few comments/questions about this:
- The code in NonlinearSystem and MooseVariable for computing the increment needs to different things for nodal and element dampers. What I've done doesn't feel like a very elegant solution.
- The solution increment vector seems to actually be the negative of the solution increment. I could set the value of _increment to the negative of that value when I'm setting it, or use the negative of _increment when I'm using it if the sign matters in the damper. I did the latter, but it could be done either way.
- Both the BoundingValue and the MaxIncrement Damper could be implemented as either nodal or element dampers. I'm not sure whether it makes any sense to make versions of these that do it both ways, e.g. ElementBoundingValue, NodalBoundingValue. My opinion is that's probably getting a little carried away.
- I added a bit of code that prints to the console the value of the damping is if it's ever less than 1. That seems pretty helpful for the user to understand what's going on.
- I still need to add a test for this, which is a little tricky, but I have ideas. I wanted to get feedback on the code first.

2016-10-12 20:08 UTC, andrsd requested changes

2016-10-12 20:08 UTC, andrsd commented on framework/src/base/MooseVariable.C
> +  _increment[0] =  increment_vec(_dof_indices[0]);
one space after `=`

2016-10-12 20:08 UTC, andrsd commented on framework/src/base/NonlinearSystem.C
> +      _nodal_dampers.addObject(nd,tid);
This is a copy and paste, but add a space after `,`.

2016-10-12 20:08 UTC, andrsd commented on framework/src/base/ComputeNodalDampingThread.C
> +  _nl.reinitIncrementAtNodeForDampers(_tid,damped_vars);
Add a space after  `,`.

2016-10-12 20:08 UTC, andrsd commented on framework/src/base/ComputeElemDampingThread.C
> +  _nl.reinitIncrementAtQpsForDampers(_tid,damped_vars);
A space after `,`

2016-10-12 22:25 UTC, bwspenc commented on framework/src/base/MooseVariable.C
> +  _increment[0] =  increment_vec(_dof_indices[0]);
Fixed

2016-10-12 22:26 UTC, bwspenc commented on framework/src/base/NonlinearSystem.C
> +      _nodal_dampers.addObject(nd,tid);
Fixed

2016-10-12 22:26 UTC, bwspenc commented on framework/src/base/ComputeNodalDampingThread.C
> +  _nl.reinitIncrementAtNodeForDampers(_tid,damped_vars);
Fixed

2016-10-12 22:27 UTC, bwspenc commented
I addressed the comments of @andrsd and added a test.

2016-10-13 14:02 UTC, andrsd requested changes

2016-10-13 14:02 UTC, andrsd commented on test/tests/dampers/bounding_value/bounding_value_test.i
> +#  [../]
Let's remove this commented out section

2016-10-13 14:02 UTC, andrsd commented on test/tests/dampers/bounding_value/bounding_value_test.i
> +  active = 'u'
I'd remove this

2016-10-13 14:02 UTC, andrsd commented on test/tests/dampers/bounding_value/bounding_value_test.i
> +  active = 'left right'
Remove this as well

2016-10-13 14:04 UTC, andrsd commented
After cleaning up the input file, this looks good to me.

@friedmud Since you built dampers, I would not mind a second opinion on this.  What @bwspenc did is he mimicked what we do for elemental dampers, but he does it for nodal values.

2016-10-13 14:31 UTC, bwspenc commented
@andrsd I made the changes you suggested to that test. While I was at it, I made the same changes to the test that I based it on, updated the comments at the top of the input file, and made a second version of the test that tests the min_value (the original one just tested max_value).

2016-10-17 15:34 UTC, andrsd approved these changes
I will let this sit here till like lunch. If nobody objects, I will merge then...

2016-10-17 16:00 UTC, dschwen commented
Shouldn't this be called `BoundingValueNodalDamper` rather than `BoundingValue`? The latter is awfully general. We have an element damper in Marmot that does almost the same thing (but more specific) and could be replaced by a more general `BoundingValueElementDamper`.

2016-10-17 17:19 UTC, bwspenc commented
@dschwen I was thinking the same thing (although I wouldn't put `Damper` at the end: how about `BoundingNodalValue`?).  Along those lines, it seems like the existing `MaxIncrement` Damper shoulde also be re-named (which will be a pain because it's so widely used), and that there probably should be a nodal version of that. That's an issue for another time, but I'm happy to re-name this.

2016-10-17 19:29 UTC, bwspenc commented
@dschwen per our discussion, I renamed this to `BoundingValueNodalDamper` and added `BoundingValueElementDamper`, as well as versions of the tests for the new element version of this.

2016-10-18 13:35 UTC, merged