Disallow nan and inf and allow strings in csv files
idaholab/moose pull request #7872
Opened 2016-10-13 22:52 UTC by YaqiWang

Close #6298.

2016-10-17 17:29 UTC, YaqiWang commented
Anybody has comments on this? I need this in my csv tests.

2016-10-17 18:34 UTC, andrsd requested changes

2016-10-17 18:34 UTC, andrsd commented on python/TestHarness/CSVDiffer.py
> +            self.addError(fname, "The values in column \"" + key.strip() + "\" is nan")
1. The comment seems to be misleading. You are not allowing `NaN`s in both files. Typically the first one is the gold file (IIRC)
1. "Values is a NaN" is not correct English. You can say "Column XYZ contains NaN".

Similarly below...

2016-10-17 18:43 UTC, YaqiWang commented
@andrsd comments are addressed. Any further comments?

2016-10-17 20:48 UTC, andrsd approved these changes

2016-10-18 13:36 UTC, merged

2016-10-18 15:07 UTC, YaqiWang commented
Can this be merged?