PorousFlow relative permeability
idaholab/moose pull request #7878
Opened 2016-10-17 10:55 UTC by cpgr

- Refactor PorousFlowRelativePermeabilityBase
- Adds residual saturations to Corey relative permeability
- Adds van Genuchten relative permeability formulation
- Adds tests of all relative permeability relations
- Includes a python script to generate plots of relative permeability vs saturation for each of the tests for including in docs

Closes #7877

2016-10-18 20:54 UTC, cpgr commented
The failed modules test is an unrelated timeout - the tests that are included in this PR pass

2016-10-20 14:47 UTC, moosebuild commented
Job `modules debug:linux-gnu` on e430e97 : invalidated by @permcody

Timeout in solid_mechanics:rate_dep_smear_crack.sent_test

2016-10-20 14:58 UTC, andrsd requested changes

2016-10-20 14:58 UTC, andrsd commented on modules/porous_flow/doc/tests/relperm.py
> +s0 = np.linspace(0,1,200)
spaces after commas

2016-10-20 14:58 UTC, andrsd commented on modules/porous_flow/doc/tests/relperm.py
> +    relperm = np.sqrt(seff) * (1 - np.power(1 - np.power(seff, 1.0/m), m))**2
spaces around `/`

2016-10-20 14:58 UTC, andrsd commented on modules/porous_flow/doc/tests/relperm.py
> +def vg(s, sr, sls, m) :
no space between `)` and `:`

2016-10-20 20:46 UTC, cpgr commented on modules/porous_flow/doc/tests/relperm.py
> +s0 = np.linspace(0,1,200)
All fixed. Thanks again @andrsd

2016-10-21 09:32 UTC, andrsd approved these changes

2016-10-21 09:33 UTC, merged