Rename classes and functions related to eigenstrain calculation
idaholab/moose pull request #7898
Opened 2016-10-18 23:30 UTC by bwspenc

ref #7815

2016-10-20 17:28 UTC, bwspenc commented
@dschwen Can you take a look at this?  I think it's ready to go. I will need to submit some application patches to address the API incompatibilities.

2016-10-20 19:07 UTC, dschwen requested changes
Please also rename the .md files in the new documentation system and adjust the pages.yml files.

2016-10-20 19:07 UTC, dschwen commented on modules/tensor_mechanics/include/materials/ComputeEigenstrainBase.h
> +#include "RankTwoTensor.h"
Please use a forward declaration here and move the include into .C file

2016-10-20 19:07 UTC, dschwen commented on modules/tensor_mechanics/include/materials/ComputeThermalExpansionEigenstrain.h
> +class RankTwoTensor;
same here

2016-10-20 19:07 UTC, dschwen commented on modules/tensor_mechanics/include/materials/ComputeThermalExpansionEigenstrain.h
> +  MaterialProperty <RankTwoTensor> & _thermal_expansion_tensor;
no space before `<`

2016-10-20 19:20 UTC, moosebuild commented
Job `App tests:linux-gnu` on 85f5fc8 : invalidated by @brianmoose

Bison fix is in and we allow mammoth to fail

2016-10-20 19:59 UTC, bwspenc commented on modules/tensor_mechanics/include/materials/ComputeThermalExpansionEigenstrain.h
> +class RankTwoTensor;
Huh? It's already a forward declaration here.

2016-10-20 20:03 UTC, dschwen commented on modules/tensor_mechanics/include/materials/ComputeThermalExpansionEigenstrain.h
> +class RankTwoTensor;
🍻 😵 🍻

2016-10-20 20:07 UTC, bwspenc commented
Ok, I addressed all of the issues.

2016-10-20 20:25 UTC, dschwen approved these changes

2016-10-21 05:19 UTC, bwspenc commented
Latest version is a minor tweak to fix the build issues -- there were a couple of derived classes that had member `RankTwoTensor` objects that got messed up by the change to forward declaration of that in the base class.

2016-10-21 14:52 UTC, dschwen commented
```
tensor_mechanics:generalized_plane_strain.generalized_plane_strain_squares: Deprecated Object: ComputeThermalExpansionEigenStrain
```

2016-10-21 14:52 UTC, dschwen requested changes
Remove use of deprecated object in test.

2016-10-21 16:36 UTC, bwspenc commented
Fixed that test with the deprecated object.

2016-10-21 19:28 UTC, dschwen approved these changes

2016-10-21 19:29 UTC, dschwen commented
I'll go ahead and merge this regardless of the ongoing (unrelated) Yak breakage. @bwspenc is working on the Bison and Marmot PRs now.

2016-10-21 19:29 UTC, merged

2016-10-21 19:39 UTC, permcody commented
Sigh... This is a bad idea in general. Integration testing is important and if we have multiple PRs that require patches to applications at the same time we start to lose control on testing those changes individually. We now five PRs merged two of which cause "expected" breakage. I'd prefer that we space this out a little more in the future. We now have no way of getting submodule updates of these effects separately.

2016-10-24 01:50 UTC, moosebuild commented
Job `App tests:linux-gnu` on fd12e48 : invalidated by @moosebuild

Yak fixed