Phase field docs
idaholab/moose pull request #7909
Opened 2016-10-19 21:41 UTC by dschwen

Start working on the phase field module documentation.

Refs #7409

2016-10-19 23:10 UTC, moosebuild commented
Job `Moose Documentation:linux-clang` on 2f1ac4c wanted to post the following:

View the site at http://mooseframework.org/docs/PRs/7909/site

2016-10-19 23:40 UTC, moosebuild commented
Job `Moose Documentation:linux-clang` on c16be47 wanted to post the following:

View the site at http://mooseframework.org/docs/PRs/7909/site

2016-10-20 13:33 UTC, moosebuild commented
Job `App tests:linux-gnu` on c16be47 : invalidated by @dschwen

Incompatible change from @sapitts PR

2016-10-20 13:34 UTC, dschwen commented
@aeslaughter , why: http://mooseframework.org/docs/PRs/7909/site/UserObjects/DiscreteNucleationMap

2016-10-20 13:37 UTC, aeslaughter commented
Why what, you sent me a link that is wrong.

http://mooseframework.org/docs/PRs/7909/site/content/modules/phase_field/systems/UserObjects/DiscreteNucleationMap/

On Thu, Oct 20, 2016 at 7:34 AM, Daniel Schwen <notifications@github.com>
wrote:

> @aeslaughter
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_aeslaughter&d=CwMCaQ&c=54IZrppPQZKX9mLzcGdPfFD1hxrcB__aEkJFOKJFd00&r=h7heP8xwI1i_HikChvhFbEBurKirgfOCdwgBxB9lM8c&m=mEbqRuBZjFRnNWZyGoN0oGbTSn_P_K8MofjMbNyRhUQ&s=q4LAbAq_t9zjrEA70qKsiSn8T7vCe6cY2NG-PbYsKrk&e=>
> , why: http://mooseframework.org/docs/PRs/7909/site/UserObjects/
> DiscreteNucleationMap
> <https://urldefense.proofpoint.com/v2/url?u=http-3A__mooseframework.org_docs_PRs_7909_site_UserObjects_DiscreteNucleationMap&d=CwMCaQ&c=54IZrppPQZKX9mLzcGdPfFD1hxrcB__aEkJFOKJFd00&r=h7heP8xwI1i_HikChvhFbEBurKirgfOCdwgBxB9lM8c&m=mEbqRuBZjFRnNWZyGoN0oGbTSn_P_K8MofjMbNyRhUQ&s=h0z2h9VSiBGQL7hRKpCU0K5sfvWG-owWBk134ImJqTo&e=>
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_idaholab_moose_pull_7909-23issuecomment-2D255107109&d=CwMCaQ&c=54IZrppPQZKX9mLzcGdPfFD1hxrcB__aEkJFOKJFd00&r=h7heP8xwI1i_HikChvhFbEBurKirgfOCdwgBxB9lM8c&m=mEbqRuBZjFRnNWZyGoN0oGbTSn_P_K8MofjMbNyRhUQ&s=zeQ7nEBVoNcuUvnOffMvjN0jb1DEv19WA0Rowe778no&e=>,
> or mute the thread
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AAU1VU-2DO-5FbAIW5vJlzeCP0WpT8uNhhEQks5q123rgaJpZM4KbfPc&d=CwMCaQ&c=54IZrppPQZKX9mLzcGdPfFD1hxrcB__aEkJFOKJFd00&r=h7heP8xwI1i_HikChvhFbEBurKirgfOCdwgBxB9lM8c&m=mEbqRuBZjFRnNWZyGoN0oGbTSn_P_K8MofjMbNyRhUQ&s=igNYrYxkhDKDCXuquGCHi9Xjx8Df6VEoR9N_5Ry3i_A&e=>
> .
>

2016-10-20 14:48 UTC, dschwen commented
Ok, those were missing the `.md` in the link, causing the auto linking not to work. Should be fixed now.

2016-10-20 15:03 UTC, moosebuild commented
Job `Moose Documentation:linux-clang` on 6a12260 wanted to post the following:

View the site at http://mooseframework.org/docs/PRs/7909/site

2016-10-20 17:56 UTC, moosebuild commented
Job `Moose Documentation:linux-clang` on 1e3b8dc wanted to post the following:

View the site at http://mooseframework.org/docs/PRs/7909/site

2016-10-20 19:17 UTC, moosebuild commented
Job `App tests:linux-gnu` on 1e3b8dc : invalidated by @brianmoose

Bison fix is in and we allow mammoth to fail

2016-10-20 19:29 UTC, dschwen commented
All _Systems_ links in Phase Field and Tensor Mechanics in this PR are broken in the Civet generated version linked above. Those links do work fine if I generate the docs locally.

2016-10-20 23:14 UTC, moosebuild commented
Job `Moose Documentation:linux-clang` on 157d019 wanted to post the following:

View the site at http://mooseframework.org/docs/PRs/7909/site

2016-10-21 16:33 UTC, aeslaughter requested changes
Nice work, thanks for beta testing and writing docs.

2016-10-21 16:33 UTC, aeslaughter commented on docs/content/modules/phase_field/introduction/ExpressionBuilder.md
> +## Documentation
Use "Introduction" or something similar here, "Documentation" doesn't seem like the right word.

2016-10-21 16:33 UTC, aeslaughter commented on docs/content/modules/phase_field/introduction/ExpressionBuilder.md
> +
optimize, [an"d"](https://www.youtube.com/watch?v=CoAzqf7GpFU)

2016-10-21 16:33 UTC, aeslaughter commented on docs/content/modules/phase_field/introduction/FAQ.md
> +\coordinate system you have chosen. So if you were to keep the system dimensions
"\" should be removed, I also think there should be a "," after "So"

2016-10-21 16:33 UTC, aeslaughter commented on docs/content/modules/phase_field/introduction/FunctionMaterialKernels.md
> +Kernels `CahnHilliard`, `CahnHilliardAniso`, `SplitCHParsed`, and `AllenCahn` solve
These should probably be link to the Kernel pages.

2016-10-21 16:33 UTC, aeslaughter commented on docs/content/modules/phase_field/introduction/FunctionMaterials.md
> +Function materials describe a family of MOOSE material classes that are derived from the `FunctionMaterialBase`
`[Moose material classes](/Materials/Overview.md)`

2016-10-21 16:33 UTC, aeslaughter commented on docs/content/modules/phase_field/introduction/JITCompile.md
> +- using `dlsym()` to bind the compiled function to the FParser object
I think you left in a bunch of "-" signs.

2016-10-21 16:33 UTC, aeslaughter commented on docs/content/modules/phase_field/introduction/PhaseFieldEquations.md
> +The goal of the MOOSE phase field module is to facilitate the development of advanced phase field models by taking advantage of their common structure, i.e.\ their usage of the Cahn-Hilliard and Alle
There is a "\" after i.e.

2016-10-21 16:33 UTC, aeslaughter commented on docs/content/modules/phase_field/introduction/PhaseFieldEquations.md
> +The free energy functional is the basis of the evolution of the phase field variables. However, the free energy itself is never used directly in the phase field Eqs, rather derivatives of the free en
You should probably just write "equations" rather than use "Eqs"

2016-10-21 16:33 UTC, aeslaughter commented on docs/content/modules/phase_field/introduction/PhaseFieldEquations.md
> +Free energies can also be combined with the deformation energy calculated using the Tensor Mechanics module.
I think you should make this a bullet as well, it is just hanging down here and looks lonely.

2016-10-21 16:33 UTC, aeslaughter commented on docs/content/modules/phase_field/systems/Materials/DerivativeParsedMaterial.md
> +This material class does everything the `ParsedMaterial` does, plus automatic symbolic differentiation of the function expression. The function material property derivatives follow a naming scheme de
The classes should be links

2016-10-21 16:33 UTC, aeslaughter commented on docs/content/modules/phase_field/systems/Materials/DerivativeSumMaterial.md
> +This material generates new material properties that sum up the values and derivatives of a specified set of function materials. Using `args` argument the union of all sets of dependent variables has
Class should probably be a link.

2016-10-21 16:33 UTC, aeslaughter commented on docs/content/modules/phase_field/systems/Materials/DerivativeTwoPhaseMaterial.md
> +For two phase models the `DerivativeTwoPhaseMaterial` can be used to combine two phase
link

2016-10-21 16:33 UTC, aeslaughter commented on docs/content/modules/phase_field/systems/Materials/ElasticEnergyMaterial.md
> +This material generates an elastic free energy contribution consistent with the TensorMechanics stress divergence kernels. This allows for proper coupling of the phase field problem and the mechanics
links to Derivative... objects

2016-10-21 16:33 UTC, aeslaughter commented on docs/content/modules/phase_field/systems/Materials/ElasticEnergyMaterial.md
> +This material generates an elastic free energy contribution consistent with the TensorMechanics stress divergence kernels. This allows for proper coupling of the phase field problem and the mechanics
I bet we can do this automatically, look for "`ClassName`" and create the link if it finds a unique match.

2016-10-21 16:33 UTC, aeslaughter commented on docs/content/modules/phase_field/systems/UserObjects/DiscreteNucleationMap.md
> +The map objects builds a smooth map of nucleation sites in the simulation domain, expanding the point description from the ```DiscreteNucleationInserter``` to a description in which nucleation sites
link to inserter

2016-10-21 16:33 UTC, aeslaughter commented on docs/content/modules/phase_field/systems/UserObjects/SolutionRasterizer.md
> +```puppet
This should just be a test and you include the file.

2016-10-21 22:34 UTC, dschwen commented on docs/content/modules/phase_field/systems/Variables/pages.yml
> +#- CHPFCRFFSplitVariables: !include content/modules/phase_field/systems/Variables/CHPFCRFFSplitVariables/pages.yml
Yes

2016-10-21 22:39 UTC, dschwen commented on docs/content/modules/phase_field/introduction/FunctionMaterials.md
> +Function materials describe a family of MOOSE material classes that are derived from the `FunctionMaterialBase`
Is that a thing? Which overview will that link to? Framework?

2016-10-21 22:44 UTC, dschwen commented on docs/content/modules/phase_field/systems/UserObjects/SolutionRasterizer.md
> +```puppet
Right, this already exists as a test. Fixed.

2016-10-21 23:04 UTC, moosebuild commented
Job `Moose Documentation:linux-clang` on efb67db wanted to post the following:

View the site at http://mooseframework.org/docs/PRs/7909/site

2016-10-24 14:32 UTC, aeslaughter approved these changes

2016-10-24 14:32 UTC, merged