Proper base classes for PorousFlow porosity, permeability
idaholab/moose pull request #7927
Opened 2016-10-24 00:37 UTC by cpgr

Provides base classes for porosity and permeability material in the `porous_flow` module, removing the double up of unused `Unity` versions and `Const` versions that can also provide material properties = 1. Previously there were some materials with base classes, some inheriting from `Unity` materials etc - a bit of a mess.

Also move the `PorousFlowRelativePermeabilityUnity` class to a `PorousFlowRelativePermeabilityConst` for consistency with other material properties.

Closes #7962

2016-10-24 14:08 UTC, andrsd requested changes

2016-10-24 14:08 UTC, andrsd commented on modules/porous_flow/src/materials/PorousFlowPorosityHM.C
> +  for (unsigned int i = 0 ; i < _ndisp ; ++i)
No space in front of `;`

2016-10-24 14:08 UTC, andrsd commented on modules/porous_flow/src/materials/PorousFlowPorosityHM.C
> +    _dporosity_nodal_dgradvar[_qp][v] = - (_porosity_nodal[_qp] - _biot) * _dvol_strain_qp_dvar[_qp][v];
We don't pad unary operators with spaces.

2016-10-24 22:59 UTC, cpgr commented on modules/porous_flow/src/materials/PorousFlowPorosityHM.C
> +  for (unsigned int i = 0 ; i < _ndisp ; ++i)
Fixed

2016-10-24 22:59 UTC, cpgr commented on modules/porous_flow/src/materials/PorousFlowPorosityHM.C
> +    _dporosity_nodal_dgradvar[_qp][v] = - (_porosity_nodal[_qp] - _biot) * _dvol_strain_qp_dvar[_qp][v];
Oops - mustn't have been concentrating when I put those in. Fixed now.

2016-10-25 14:07 UTC, andrsd approved these changes

2016-10-25 17:21 UTC, moosebuild commented
Job `App tests:linux-gnu` on 4af718d : invalidated by @brianmoose

Bison, Marmot, Mammoth fixed

2016-10-25 18:35 UTC, moosebuild commented
Job `modules debug:linux-gnu` on 4af718d : invalidated by @brianmoose

Modules debug should be fixed now

2016-10-25 19:21 UTC, merged