Add a mesh modifier for adding sidesets using parsed condition
idaholab/moose pull request #7931
Opened 2016-10-24 22:17 UTC by snschune

A mesh modifier that adds element's sides to a new sideset based on the following conditions:
1.  the centroid of the face satisfies the parsed condition
2. (optional) the owning element belongs to a listed subdomain
3. (optional) normal is to some tolerance equal to the provided normal

2016-10-25 05:03 UTC, dschwen commented on framework/include/meshmodifiers/ParsedAddSideset.h
> + * MeshModifier for defining a Sideset by
look like this comment stops mid sentence

2016-10-25 05:04 UTC, dschwen commented on framework/include/meshmodifiers/ParsedAddSideset.h
> +#endif //SUBDOMAINBOUDINGBOX_H
That comment needs to be updated

2016-10-25 05:04 UTC, dschwen commented on framework/include/meshmodifiers/ParsedAddSideset.h
> +#endif //SUBDOMAINBOUDINGBOX_H
That comment needs to be updated

2016-10-25 05:07 UTC, dschwen commented on framework/src/meshmodifiers/ParsedAddSideset.C
> +    _check_normal(isParamValid("normal")),
you could do the isParamSetByUser check here and give it a a default value of `Point()` for one less check below

2016-10-25 17:21 UTC, moosebuild commented
Job `App tests:linux-gnu` on d2bbff8 : invalidated by @brianmoose

Bison, Marmot, Mammoth fixed

2016-10-25 18:36 UTC, moosebuild commented
Job `modules debug:linux-gnu` on d2bbff8 : invalidated by @brianmoose

Modules debug should be fixed now

2016-10-25 19:55 UTC, permcody requested changes
Please add this call to your `modify()` method:

```
_mesh_ptr->errorIfDistributedMesh("ParsedAddSideset");
```

This modifier won't work with ParallelMesh. You'll also need to restrict your new test so it won't run on the parallel mesh tests.

2016-10-25 21:16 UTC, permcody approved these changes

2016-10-25 22:09 UTC, snschune commented
I need to fix the test before this is merged. The correct thing to do is to add

```
mesh_mode = REPLICATED
```

and I just added a cli.

2016-10-25 22:43 UTC, permcody commented
I missed that! Thanks for self disclosing. I'll hold off on merging until this is in.

2016-10-25 23:46 UTC, friedmud commented
This whole thing feels a bit specific to me.  I'm not sure it should actually be in MOOSE.  It sounds like a MeshModifier that should really just be in your app... or, at the most, in modules?

Someone else might have a different idea of how they would want to add sidesets based on parsed functions.  This one is a bit specific to your use-case

2016-10-26 02:48 UTC, WilkAndy commented
Commenting on @friedmud 's comment that this MeshModifier is rather specific....  I'll probably use this particular MeshModifier, as I'm always mucking around adding sidesets to meshes (i often use VTK to build my meshes and it doesn't have good exodus support in this regard).  So, if you decide to move this contribution out of MOOSE, please put it in modules rather than in an App.

2016-10-26 05:05 UTC, snschune commented
Hmmmm, it really doesn't fit into any module (since they separate by physics) except maybe misc. I'd be okay to have it in Yak or any other app I have access to. I have use for it in one particular application right now and that's it. I thought there might be a broader applicability to the mesh modifier the more I thought about it. @WilkAndy seems to confirm that this might be the case. In any case, I don't feel too strongly either way...

2016-10-26 14:06 UTC, permcody commented
I suggest we keep it in the framework despite it being a little specific. If two completely different applications can use it, that's general enough.

2016-10-26 15:51 UTC, friedmud commented
My vote was just that: a vote... if it's generally useful then go ahead and
put it in MOOSE.

It's hard to draw the line... but MOOSE will get HUGE if we don't curate it
somewhat...

On Tue, Oct 25, 2016 at 10:48 PM Andy Wilkins <notifications@github.com>
wrote:

> Commenting on @friedmud <https://github.com/friedmud> 's comment that
> this MeshModifier is rather specific.... I'll probably use this particular
> MeshModifier, as I'm always mucking around adding sidesets to meshes (i
> often use VTK to build my meshes and it doesn't have good exodus support in
> this regard). So, if you decide to move this contribution out of MOOSE,
> please put it in modules rather than in an App.
>
> —
> You are receiving this because you were mentioned.
>
>
> Reply to this email directly, view it on GitHub
> <https://github.com/idaholab/moose/pull/7931#issuecomment-256235778>, or mute
> the thread
> <https://github.com/notifications/unsubscribe-auth/AA1JMfl7-1GQDxWbztjCfvSQw1UcqdZRks5q3r9igaJpZM4KfWSW>
> .
>

2016-10-26 16:12 UTC, merged