Compute neighbor element volume on demand
idaholab/moose pull request #7942
Opened 2016-10-25 20:55 UTC by andrsd

MOOSE was computing the neighbor element volume even though it was not
really needed. The computation is quite expensive and shows up in
profiling.  If the volume is needed in a DG kernel, users can obtain it
by:

```
.h:
const Real & _neighbor_volume;

.C:
_neighbor_volume(getNeighborElemVolume())
```

This will tell MOOSE to compute the volume. The same holds for `InternalSideUserObject`s.

Refs #3661, #6788

2016-10-25 21:11 UTC, permcody approved these changes

2016-10-25 21:11 UTC, permcody commented on framework/include/base/Assembly.h
> +  const Real & neighborVolume() { _need_neighbor_elem_volume = true; return _current_neighbor_volume; }
I suppose this is ok. This method is probably getting big enough to move to the .C file.

2016-10-25 21:14 UTC, andrsd commented on framework/include/base/Assembly.h
> +  const Real & neighborVolume() { _need_neighbor_elem_volume = true; return _current_neighbor_volume; }
I can move it to .C, that's not a problem...

2016-10-26 03:28 UTC, friedmud requested changes
There are a bunch of objects being dynamically allocated here...

2016-10-26 03:28 UTC, friedmud commented on framework/src/base/Assembly.C
> +    FEType fe_type(neighbor->default_order(), LAGRANGE);
This is why this is showing up in timing... there are a BUNCH of temporaries here.  These should all get moved to member variables.

2016-10-26 03:28 UTC, friedmud commented on framework/src/base/Assembly.C
> +    std::unique_ptr<FEBase> fe(FEBase::build(neighbor->dim(), fe_type));
This one too

2016-10-26 03:28 UTC, friedmud commented on framework/src/base/Assembly.C
> +    QGauss qrule(neighbor->dim(), fe_type.default_quadrature_order());
And here

2016-10-26 03:28 UTC, friedmud commented on framework/src/base/Assembly.C
> +    MooseArray<Real> coord;
And this one

2016-10-26 14:47 UTC, permcody commented on framework/src/base/Assembly.C
> +    FEType fe_type(neighbor->default_order(), LAGRANGE);
![image](https://cloud.githubusercontent.com/assets/3036960/19730859/c4413412-9b58-11e6-8556-eed997e5b63e.png)

2016-10-26 17:22 UTC, friedmud commented
I have no doubt it was my code!  I certainly wasn't blaming you!  I was just pointing out the real problem.  :-)

2016-10-26 17:24 UTC, friedmud approved these changes
Looks really good.  Did you happen to do any before/after timing (not necessary - just wondering if/how much it helped)

2016-10-26 17:24 UTC, friedmud commented on framework/include/base/Assembly.h
> +  std::map<unsigned int, FEBase **> _holder_fe_neighbor_helper;
Good

2016-10-26 17:24 UTC, friedmud commented on framework/src/base/Assembly.C
> +    _holder_fe_neighbor_helper[dim] = &_fe_neighbor[dim][FEType(FIRST, LAGRANGE)];
Looks good

2016-10-26 17:25 UTC, friedmud commented
BTW: Do we have any test coverage of this?  If not - we need to add one.

2016-10-26 17:29 UTC, andrsd commented
> BTW: Do we have any test coverage of this? If not - we need to add one.

I did not find anything that would use this, that's why I made it into a subscription based API. If nobody needs it, let's not spend time doing it at all ;-)

Not sure how we could test it, nothing obvious comes to mind. A unit test would be good, but probably quite a bit of code to actually get down to that call...

2016-10-26 17:32 UTC, andrsd commented
> Did you happen to do any before/after timing

Some timing is already [here](https://github.com/idaholab/moose/issues/6788#issuecomment-256176659), I will do one more with the neighbor element volume computation enabled with this latest optimization...

2016-10-27 15:35 UTC, friedmud commented
What kind of object is triggering that whole function right now?  Is it
Mortar stuff?

On Wed, Oct 26, 2016 at 1:29 PM David Andrs <notifications@github.com>
wrote:

> BTW: Do we have any test coverage of this? If not - we need to add one.
>
> I did not find anything that would use this, that's why I made it into a
> subscription based API. If nobody needs it, let's not spend time doing it
> at all ;-)
>
> Not sure how we could test it, nothing obvious comes to mind. A unit test
> would be good, but probably quite a bit of code to actually get down to
> that call...
>
> —
> You are receiving this because you commented.
>
>
> Reply to this email directly, view it on GitHub
> <https://github.com/idaholab/moose/pull/7942#issuecomment-256420255>, or mute
> the thread
> <https://github.com/notifications/unsubscribe-auth/AA1JMbNgmBZ6tdsolKKupVRohBqniPu2ks5q344CgaJpZM4KgeVZ>
> .
>

2016-10-27 15:39 UTC, andrsd commented
> What kind of object is triggering that whole function right now?

Nothing in the MOOSE universe needs the computation of neighbor volume. That's why the app test passed without patching anything. The computation is off by default and when something needs it, they can enable it via an API call. That was the primary purpose of this PR.

2016-10-27 16:08 UTC, permcody commented
@friedmud - I'm satisfied with this PR. Feel free to merge it, otherwise I'll get to it later today.

2016-10-27 16:51 UTC, merged