ComputeCappedWeakPlaneStress made more robust
idaholab/moose pull request #7962
Opened 2016-10-27 05:39 UTC by WilkAndy

(1) A check for precision-loss is made during the return-map process.  If precision loss is detected, convergence is assumed.
(2) The constructor checks that tensile_strength + compressive_strength > smoothing_tol (previously the rhs of this inequality was zero).

Fixes #7960

2016-10-27 20:06 UTC, WilkAndy commented
This PR failed due to unrelated fails in two tests using PETSc alt:

porous_flow:dirackernels.theis3.............................................................. FAILED (ERRMSG)
combined:contact_verification/patch_tests/cyl_3.frictionless_kin............................ FAILED (CSVDIFF)

@cpgr and/or I should investigate the theis3 test.

@acasagran wrote the cyl_3.frictionless_kin test, i think, so perhaps he/she would like to investigate?

2016-10-27 20:33 UTC, acasagran commented
The cyl_3.frictionless_kin test is just diffing slightly. You can loosen the tolerances in the tests file to get it to pass. I would suggest changing abs_zero to 1e-4 and rel_err to 2e-5.

2016-10-27 20:44 UTC, WilkAndy commented
OK, i will do that, thanks @acasagran

2016-10-27 23:39 UTC, WilkAndy commented
I have modified the two offending tests.  We shall have to see if they pass now.

2016-10-27 23:46 UTC, cpgr commented on modules/porous_flow/tests/dirackernels/theis3.i
>    [../]
Is a 'hooley dooley' appropriate here?

2016-10-28 00:01 UTC, permcody commented
Hooley Dooley is always appropriate!
On Thu, Oct 27, 2016 at 5:46 PM Chris Green <notifications@github.com>
wrote:

> *@cpgr* commented on this pull request.
> ------------------------------
>
> In modules/porous_flow/tests/dirackernels/theis3.i
> <https://github.com/idaholab/moose/pull/7962#pullrequestreview-6166912>:
>
> > @@ -171,8 +171,9 @@
>    [./smp]
>      type = SMP
>      full = true
> -    petsc_options_iname = '-ksp_type -pc_type -snes_atol -snes_rtol'
> -    petsc_options_value = 'gmres asm 1e-8 1e-10'
> +    petsc_options = '-snes_converged_reason -ksp_diagonal_scale -ksp_diagonal_scale_fix -ksp_gmres_modifiedgramschmidt -snes_linesearch_monitor'
> +    petsc_options_iname = '-ksp_type -pc_type -sub_pc_type -sub_pc_factor_shift_type -pc_asm_overlap -snes_atol -snes_rtol -snes_max_it'
> +    petsc_options_value = 'gmres      asm      lu           NONZERO                   2               1E-8       1E-10 20'
>    [../]
>
> Is a 'hooley dooley' appropriate here?
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/idaholab/moose/pull/7962#pullrequestreview-6166912>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AC5XIA0xf5exl0aovhzerVWVBgQKzrrQks5q4TfBgaJpZM4Kh9mx>
> .
>

2016-10-28 00:04 UTC, WilkAndy commented on modules/porous_flow/tests/dirackernels/theis3.i
>    [../]
Heheheh, this is a secret Andy recipe that always seem to work so far.

2016-10-28 05:14 UTC, WilkAndy commented
@mangerij and @fdkong  , your new "periodic_boundary" test is failing with PETSc alt, and TBB .   I'm not sure whether we want to fix that in this PR, or create a new PR.  It's up to you what's easier for you.

2016-10-31 15:11 UTC, fdkong commented
> @mangerij and @fdkong , your new "periodic_boundary" test is failing with PETSc alt, and TBB . I'm not sure whether we want to fix that in this PR, or create a new PR. It's up to you what's easier for you.

@WilkAndy, I will be making a simple example to replace the old one. I am sorry on this.

2016-10-31 20:21 UTC, moosebuild commented
Job `App tests:linux-gnu` on 13c5c6f : invalidated by @brianmoose

Yak is fixed now

2016-11-01 20:44 UTC, jwpeterson requested changes
Please fix Python spacing, otherwise the changes look OK.

2016-11-01 22:12 UTC, WilkAndy commented
Thanks @jwpeterson - python indentation is fixed.

2016-11-02 14:35 UTC, jwpeterson approved these changes

2016-11-02 14:35 UTC, merged

2016-11-02 20:45 UTC, WilkAndy commented
Thanks everyone for your input here,

a