Add pressure convergence plot for Jeffery-Hamel flow.
idaholab/moose pull request #7970
Opened 2016-10-27 21:53 UTC by jwpeterson

Previously we demonstrated 3rd-order (optimal) convergence rates for
the velocity components, this PR shows that we also get 2nd-order
(optimal) convergence rates for pressure.

Refs #3036, #7904.

Updated convergence plot:
[jeffery_hamel.pdf](https://github.com/idaholab/moose/files/557127/jeffery_hamel.pdf)

2016-10-27 22:03 UTC, andrsd requested changes

2016-10-27 22:03 UTC, andrsd commented on modules/navier_stokes/src/tests/WedgeFunction.C
> +  params.addRequiredRangeCheckedParam<unsigned int>("var_num", "var_num<3", "The variable (0=vel_x, 1==vel_y, 2==p) we are computing the exact solution for.");
A mix of `=` and `==` in the doco string

2016-10-27 22:03 UTC, andrsd commented on modules/navier_stokes/tests/ins/jeffery_hamel/jeffery_hamel.py
> +  K.append(-1./(4. * alpha * alpha) * (alpha * Re * solution[i]**2 + second_deriv[i]) - solution[i])
spaces around `/`

2016-10-27 22:03 UTC, andrsd commented on modules/navier_stokes/src/tests/WedgeFunction.C
> +  params.addRequiredRangeCheckedParam<unsigned int>("var_num", "var_num<3", "The variable (0=vel_x, 1==vel_y, 2==p) we are computing the exact solution for.");
Maybe even consider using `MooseEnum` of it makes more sense...

2016-10-27 22:07 UTC, jwpeterson commented on modules/navier_stokes/src/tests/WedgeFunction.C
> +  params.addRequiredRangeCheckedParam<unsigned int>("var_num", "var_num<3", "The variable (0=vel_x, 1==vel_y, 2==p) we are computing the exact solution for.");
I thought about that, but this is only for a test, and I also use it to index into a vector, so I think it makes more sense as an int.

2016-10-31 15:02 UTC, andrsd approved these changes

2016-10-31 15:02 UTC, merged