Implement cumulative postprocessor value postprocessor
idaholab/moose pull request #7981
Opened 2016-10-31 21:40 UTC by joshuahansel

Implements the cumulative postprocessor value postprocessor and adds a test for it.

closes #7976

2016-10-31 21:56 UTC, andrsd requested changes

2016-10-31 21:56 UTC, andrsd commented on framework/include/postprocessors/CumulativePostprocessorValue.h
> +#ifndef CUMULATIVEPOSTPROCESSORVALUE_H
This will need the standard MOOSE header

2016-10-31 21:56 UTC, andrsd commented on test/tests/postprocessors/cumulative_postprocessor_value/cumulative_postprocessor_value.i
> +      variable = u
2 levels of indentation

2016-10-31 22:05 UTC, dschwen commented on framework/src/postprocessors/CumulativePostprocessorValue.C
> +#include "CumulativePostprocessorValue.h"
This needs a header, too!

2016-10-31 22:25 UTC, YaqiWang commented
I personally think this is not necessary or at least on the application side. It can be achieved by doing a grep to the screen outputs or any csv file manipulator. This will slow down the compiling further. My rule is not to assume users non-creative. We need to draw a line to stop supporting every single request from users. I have to admit that I violated this rule before by creating a `ScalingPostprocessor`.

2016-10-31 22:31 UTC, dschwen commented
It's a bit odd to draw the line right here. There are conceivable applications where after the fact CSV massaging cannot do the job. For example if you want to use a terminator (based on a total number of certain events that occurred - measured by a PP)

2016-10-31 22:36 UTC, joshuahansel commented
To be clear, no user requested this feature (that I know of); it's just
something I implemented in my own studies and thought I'd share. Compile
time is a valid point that I hadn't considered when sharing, so if others
deem the feature not worth the compile time, then I wouldn't be offended in
dropping the merge.

On Mon, Oct 31, 2016 at 4:31 PM, Daniel Schwen <notifications@github.com>
wrote:

> It's a bit odd to draw the line right here. There are conceivable
> applications where after the fact CSV massaging cannot do the job. For
> example if you want to use a terminator (based on a total number of certain
> events that occurred - measured by a PP)
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_idaholab_moose_pull_7981-23issuecomment-2D257440024&d=CwMFaQ&c=54IZrppPQZKX9mLzcGdPfFD1hxrcB__aEkJFOKJFd00&r=xTMJ9Q3PQVWWIpr9UWvnvWPrbmJOt-aOIf2FbRLBNpc&m=kr2I6gnd8ahn4hkl6eWCiRl9Wg4mzZjaRYucDxgUmsI&s=wC-J3RhPiycqn1PtQfiDsah1ye_es_u_AC9wqr5Wq_0&e=>,
> or mute the thread
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AWCcRNKbrnK1jXryE4vfRKNUmm4kxzMmks5q5mwygaJpZM4KliTq&d=CwMFaQ&c=54IZrppPQZKX9mLzcGdPfFD1hxrcB__aEkJFOKJFd00&r=xTMJ9Q3PQVWWIpr9UWvnvWPrbmJOt-aOIf2FbRLBNpc&m=kr2I6gnd8ahn4hkl6eWCiRl9Wg4mzZjaRYucDxgUmsI&s=P1cbf-tBWalw32CtuUvJjnfqb-PHdWpIWCHvmY7R3qw&e=>
> .
>



-- 
Joshua Hansel
Post Doctorate Research Associate
Idaho National Laboratory

2016-10-31 22:41 UTC, YaqiWang commented
@dschwen presented a good argument. Making users create their own pp and link it into their applications sounds not very good. How about moving this into misc module? Then users can choose to link against it easily.

2016-11-01 11:51 UTC, friedmud commented
I think this is fine in MOOSE.

But: it could use a rename to CumulativeValuePostprocessor

Derek
On Mon, Oct 31, 2016 at 6:41 PM Yaqi <notifications@github.com> wrote:

> @dschwen <https://github.com/dschwen> presented a good argument. Making
> users create their own pp and link it into their applications sounds not
> very good. How about moving this into misc module? Then users can choose to
> link against it easily.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/idaholab/moose/pull/7981#issuecomment-257441814>, or mute
> the thread
> <https://github.com/notifications/unsubscribe-auth/AA1JMcrmtw7GiK8T1P2W6hdV8BrsmU3Tks5q5m6OgaJpZM4KliTq>
> .
>

2016-11-01 15:33 UTC, andrsd approved these changes

2016-11-01 19:26 UTC, merged