Unit tests of methane fluid properties
idaholab/moose pull request #8010
Opened 2016-11-03 22:20 UTC by cpgr

The last of the unit tests for fluid properties. Removes remaining test materials that were in the `fluid_properties` module to mimic unit testing.

Closes #7972

2016-11-03 22:29 UTC, andrsd requested changes

2016-11-03 22:29 UTC, andrsd commented on unit/include/MethaneFluidPropertiesTest.h
> +  CPPUNIT_TEST_SUITE( MethaneFluidPropertiesTest );
No spaces inside `(...)`. Also below...

2016-11-04 13:37 UTC, andrsd approved these changes

2016-11-04 13:37 UTC, merged

2016-11-04 21:39 UTC, cpgr commented
Thanks @andrsd - the fluid properties module looks much cleaner now without those test materials

2016-11-05 18:52 UTC, andrsd commented
👍