Error out for multiply declared material property
idaholab/moose pull request #8044
Opened 2016-11-09 22:41 UTC by bwspenc

closes #8043

2016-11-10 16:02 UTC, bwspenc commented
@aeslaughter It looks like you set up the tests for this warning (`tests/materials/declare_overlap`).  It looks like this was very intentionally set up to treat this as a warning rather than an error.  What was the rationale for that?

2016-11-14 20:47 UTC, permcody commented
If you have two materials (same type, same name) active on the same block (which is possible) then the value you get in the memory location would be based on the execution order which isn't deterministic for the general case. Now, you should be able to declare the same property on different materials, that works fine. What exactly are you trying to change and why?

2016-11-14 21:09 UTC, bwspenc commented
I accidentally declared a property twice with the same name on the same block, and was surprised that the code didn't give an error. As you say, the value you get for that material would be execution order dependent, so it seems like we should only allow one material to write to a material property.

This seems like something that should be elevated from a warning to an error because I can't think of a reason to want to do this. Warnings should be to let the user know that they can get in trouble for something that is still OK in some circumstances.  Are there ever circumstances when this is OK?

2016-11-14 21:33 UTC, permcody commented
Not that I can think of... @aeslaughter?
On Mon, Nov 14, 2016 at 2:09 PM Ben Spencer <notifications@github.com>
wrote:

> I accidentally declared a property twice with the same name on the same
> block, and was surprised that the code didn't give an error. As you say,
> the value you get for that material would be execution order dependent, so
> it seems like we should only allow one material to write to a material
> property.
>
> This seems like something that should be elevated from a warning to an
> error because I can't think of a reason to want to do this. Warnings should
> be to let the user know that they can get in trouble for something that is
> still OK in some circumstances. Are there ever circumstances when this is
> OK?
>
> —
> You are receiving this because you commented.
>
>
> Reply to this email directly, view it on GitHub
> <https://github.com/idaholab/moose/pull/8044#issuecomment-260463316>, or mute
> the thread
> <https://github.com/notifications/unsubscribe-auth/AC5XIK0MjHwyDnOJRrFLv3w5qUeGutMYks5q-M4MgaJpZM4KuEdi>
> .
>

2016-11-14 22:19 UTC, aeslaughter commented
I don't think it is a good idea, but I can certainly come up with some
crazy scenario where one material may optionally overwrite a property. I
probably made it a warning b/c it breaks someone if it isn't, you could try
to make in an error and see what happens in a PR.

On Mon, Nov 14, 2016 at 2:33 PM, Cody Permann <notifications@github.com>
wrote:

> Not that I can think of... @aeslaughter?
> On Mon, Nov 14, 2016 at 2:09 PM Ben Spencer <notifications@github.com>
> wrote:
>
> > I accidentally declared a property twice with the same name on the same
> > block, and was surprised that the code didn't give an error. As you say,
> > the value you get for that material would be execution order dependent,
> so
> > it seems like we should only allow one material to write to a material
> > property.
> >
> > This seems like something that should be elevated from a warning to an
> > error because I can't think of a reason to want to do this. Warnings
> should
> > be to let the user know that they can get in trouble for something that
> is
> > still OK in some circumstances. Are there ever circumstances when this is
> > OK?
> >
> > —
> > You are receiving this because you commented.
> >
> >
> > Reply to this email directly, view it on GitHub
> > <https://github.com/idaholab/moose/pull/8044#issuecomment-260463316>,
> or mute
> > the thread
> > <https://github.com/notifications/unsubscribe-auth/
> AC5XIK0MjHwyDnOJRrFLv3w5qUeGutMYks5q-M4MgaJpZM4KuEdi>
> > .
>
> >
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_idaholab_moose_pull_8044-23issuecomment-2D260469529&d=CwMFaQ&c=54IZrppPQZKX9mLzcGdPfFD1hxrcB__aEkJFOKJFd00&r=h7heP8xwI1i_HikChvhFbEBurKirgfOCdwgBxB9lM8c&m=wNNIquKrD7FSN6CJDFsEMDkqsNipC4PQq9bjQdn4vNI&s=F2hxiKMOo3DYFCTtdWnQB-DzmWXTZQPRM98hYU499E0&e=>,
> or mute the thread
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AAU1VZ-5FcWOk0cpPK7oDRtnsEdSyUx-5Fy-5Fks5q-2DNOigaJpZM4KuEdi&d=CwMFaQ&c=54IZrppPQZKX9mLzcGdPfFD1hxrcB__aEkJFOKJFd00&r=h7heP8xwI1i_HikChvhFbEBurKirgfOCdwgBxB9lM8c&m=wNNIquKrD7FSN6CJDFsEMDkqsNipC4PQq9bjQdn4vNI&s=MPDB9VHeetTBEam5Nmr9_W6gFKBx2FhmpXK_F_WxR4M&e=>
> .
>

2016-11-14 22:21 UTC, aeslaughter commented
I probably made it warning because of these:
```
meso_thcond_test.fissiongas_test............................................................. FAILED (ERRMSG) [0.052s]
meso_thcond_test.graingrowth_test............................................................ FAILED (ERRMSG) [0.053s]
failurecladHT9/ccg_short.ccgtest............................................................. FAILED (ERRMSG) [0.080s]
un_swelling.U3Si5UN_test..................................................................... FAILED (ERRMSG) [0.071s]
```

2016-11-14 22:30 UTC, permcody commented
Well if those are valid, that use case should be captured and documented. If not, then Ben's ticket is valid and those tests should be removed. Ideally if they are valid, is there a way to separate them from the normal accidental double declaration case?

2016-11-14 22:35 UTC, aeslaughter commented
Well, we could always add some sort of flag that allows this behavior.

```
[Problem]
  type = FEProblem
  sloppy_material_properties=True
[]

```

2016-11-14 22:58 UTC, friedmud commented
I'm for making this an error... but I'm interested in what those test cases
are up to.  It's possible that we haven't thought of the usage scenario
yet...

On Mon, Nov 14, 2016 at 5:35 PM Andrew E Slaughter <notifications@github.com>
wrote:

> Well, we could always add some sort of flag that allows this behavior.
>
> [Problem]
>   type = FEProblem
>   sloppy_material_properties=True
> []
>
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/idaholab/moose/pull/8044#issuecomment-260485721>, or mute
> the thread
> <https://github.com/notifications/unsubscribe-auth/AA1JMWwaPCZSII5nmhFxBZUiUr7yj7fkks5q-OIcgaJpZM4KuEdi>
> .
>

2016-11-14 23:41 UTC, bwspenc commented
Oh -- I'll look into those BISON tests.  I kind of doubt that double declaring those properties was intentional.

2016-11-15 01:24 UTC, permcody commented
Right, "sloppy material properties" is a bad idea if the behavior isn't
well defined or intentional. It should be an error unless there's a reason
for it.

On Mon, Nov 14, 2016 at 4:41 PM Ben Spencer <notifications@github.com>
wrote:

> Oh -- I'll look into those BISON tests. I kind of doubt that double
> declaring those properties was intentional.
>
> —
> You are receiving this because you commented.
>
>
> Reply to this email directly, view it on GitHub
> <https://github.com/idaholab/moose/pull/8044#issuecomment-260500364>, or mute
> the thread
> <https://github.com/notifications/unsubscribe-auth/AC5XIBtWypVpnZLW6FfjVOne2LTVSd-rks5q-PG3gaJpZM4KuEdi>
> .
>

2017-01-05 22:31 UTC, rwcarlsen commented on framework/src/base/FEProblem.C
>          oss << "\nThis will result in ambiguous material property calculations and lead to incorrect results.\n";
This part of the message can probably be removed if we switch this to an error.

2017-01-16 21:30 UTC, rwcarlsen commented
The declare_overlap tests will need to be tweaked a bit too.

2017-01-19 15:00 UTC, moosebuild commented
Job `App tests:linux-gnu` on 894cf8f : invalidated by @rwcarlsen

bison updates should fix failures

2017-01-19 15:19 UTC, rwcarlsen commented
Needs a rebase.

2017-01-19 15:42 UTC, bwspenc commented
@rwcarlsen You might say it needed a rebase.  FEProblem disappeared from under me!

2017-01-19 22:51 UTC, rwcarlsen commented
@bwspenc - you need to remove the ``materials/declare_overlap/warning`` test in moose tests (since it is an error now).  And still a couple of duplicate props in 3 BISON tests.

2017-01-19 22:59 UTC, bwspenc commented
@rwcarlsen Yeah, I'm actually fixing the MOOSE test right now.  I'll look into the BISON tests -- I though I fixed those issues yesterday, but maybe not.

2017-01-23 21:08 UTC, bwspenc commented
@rwcarlsen I just got a fix to those BISON tests merged, so this round of tests ought to pass.

2017-01-23 22:57 UTC, moosebuild commented
Job `App tests:linux-gnu` on 771feaa : invalidated by @bwspenc

Didn&#39;t run against version of BISON with fix

2017-01-23 23:51 UTC, rwcarlsen requested changes
Just the one inline comment and then good to merge.

2017-01-23 23:51 UTC, rwcarlsen commented on framework/src/base/FEProblemBase.C
>          oss << "\nThis will result in ambiguous material property calculations and lead to incorrect results.\n";
Could you remove this line of the message?  It doesn't make much sense since we are now disallowing duplicate props altogether.

2017-01-24 04:08 UTC, bwspenc commented
@rwcarlsen -- I removed that line of the error message as suggested.

2017-01-24 15:19 UTC, rwcarlsen approved these changes

2017-01-24 15:22 UTC, merged