Generalized plane strain for axisymmetric 1D problems
idaholab/moose pull request #8049
Opened 2016-11-10 00:50 UTC by hchen139

closes #8045

2016-11-10 00:51 UTC, hchen139 commented
@bwspenc @jasondhales Axisymmetric 1D problems

2016-11-14 22:35 UTC, dschwen commented on modules/combined/tests/1D_axisymmetric/axisymmetric_gps_incremental.i
> +  scalar_strain_yy = scalar_strain_yy
I don't think we should hard code a coordinate direction into this parameter name.

2016-11-15 00:00 UTC, bwspenc commented on modules/combined/tests/1D_axisymmetric/axisymmetric_gps_incremental.i
> +  scalar_strain_yy = scalar_strain_yy
@dschwen I kind of agree -- what should we call it?  `scalar_out_of_plane_strain`? `scalar_generalized_strain`?

In all of the cases we have so far, there is only one of these strains, but there is a potential for a 1D simulation where we would do this treatment in both the yy and zz directions.  We're not currently doing that, but I would like the name we choose to permit that case.

2016-11-16 22:49 UTC, hchen139 commented on modules/combined/tests/1D_axisymmetric/axisymmetric_gps_incremental.i
> +  scalar_strain_yy = scalar_strain_yy
Any conclusion on the naming?

2016-11-21 23:24 UTC, hchen139 commented
@dschwen @bwspenc Any comments on the updated PR? I have submitted a patch for the BISON app failure.

2016-11-22 00:22 UTC, bwspenc requested changes
This is getting close and looking really good.  Address these minor things, and I think this is good to go.  I would still like to discuss the name of `variable_strain` a little more.

2016-11-22 00:22 UTC, bwspenc commented on modules/tensor_mechanics/src/kernels/GeneralizedPlaneStrainOffDiag.C
> +  params.addCoupledVar("scalar_strain", "Scalar variable for 1D Axisymmetric problem");
'Scalar variable for out-of-plane strain'

2016-11-22 00:22 UTC, bwspenc commented on modules/tensor_mechanics/src/materials/Compute1DFiniteStrain.C
> +    // Deformation gradient calculation for 2D problems
These comments don't apply for 1D

2016-11-22 00:22 UTC, bwspenc commented on modules/tensor_mechanics/src/materials/ComputeAxisymmetric1DFiniteStrain.C
> +  params.addCoupledVar("variable_strain", "Nonlinear variable for axisymmetric 1D problem");
I don't think there's any need for this option (variable_strain) for 1D axisymmetric models. I'd remove it completely from all those models.

2016-11-22 00:22 UTC, bwspenc commented on modules/tensor_mechanics/src/materials/ComputeAxisymmetricRZSmallStrain.C
> +  if (!MooseUtils::relativeFuzzyEqual(_q_point[_qp](0), 0.0))
The `absolueFuzzyEqual()` function is more appropriate here since we're checking for the case where it is about zero.

2016-11-22 00:22 UTC, bwspenc commented on modules/tensor_mechanics/src/materials/ComputePlaneFiniteStrain.C
> +  params.addCoupledVar("variable_strain", "Nonlinear variable for plane stress");
I'm struggling with the name "variable_strain", but I don't have a better alternative.
Regardless of what name we use, use this for the description: "Nonlinear variable for the out-of-plane strain (used to model plane stress conditions)"

2016-11-22 00:22 UTC, bwspenc commented on modules/tensor_mechanics/src/materials/ComputePlaneIncrementalStrain.C
> +  params.addCoupledVar("variable_strain", "Nonlinear variable for plane stress");
Change description here too.

2016-11-22 00:22 UTC, bwspenc commented on modules/tensor_mechanics/src/materials/ComputePlaneSmallStrain.C
> +  params.addCoupledVar("variable_strain", "Nonlinear variable for plane stress");
here too

2016-11-22 15:49 UTC, hchen139 commented on modules/combined/tests/generalized_plane_strain_tm_contact/generalized_plane_strain_tm_contact_field.i
>    order = FIRST
This test was renamed by removing the word 'field'. And I realived this test using the new formulation but without 'quadrature' option. Now this test was passed.

2016-11-22 15:50 UTC, hchen139 commented on modules/tensor_mechanics/src/materials/ComputeAxisymmetric1DFiniteStrain.C
> +  params.addCoupledVar("variable_strain", "Nonlinear variable for axisymmetric 1D problem");
Will do this and I need to update all the 1D classes and tests in BISON using the new formulation.

2016-11-22 16:01 UTC, bwspenc commented on modules/combined/tests/generalized_plane_strain_tm_contact/generalized_plane_strain_tm_contact_field.i
>    order = FIRST
Does it work with 'quadrature = true'? If it does, we should switch to running it that way because that is preferable.

2016-11-22 16:58 UTC, bwspenc commented on modules/tensor_mechanics/src/materials/ComputeAxisymmetric1DFiniteStrain.C
> +  params.addCoupledVar("variable_strain", "Nonlinear variable for axisymmetric 1D problem");
Hold on -- on second thought don't do that!

2016-11-22 21:52 UTC, bwspenc commented on modules/tensor_mechanics/src/userobjects/GeneralizedPlaneStrainUserObject.C
> +  params.addParam<FunctionName>("traction", "0", "Function used to prescribe traction in the out-of-plane direction");
For consistency, I think this needs to be "out_of_plane_pressure".

2016-11-22 22:00 UTC, bwspenc commented
@permcody We were wondering why the tests didn't get re-run when he pushed an update to this.  Is it because merging was blocked by the change request that hadn't yet been run?

2016-11-22 22:07 UTC, permcody commented
No, I just looked at the Github log and there was some sort of server response problem. These are really rare but not zero. I could have manually triggered the rebuild but it looks like he repushed so it's rebuilding now. The approvals don't interfere with builds.

2016-11-22 22:23 UTC, bwspenc approved these changes

2016-11-23 00:06 UTC, bwspenc commented
This breaks the BISON tests, but @hchen139 has a commit ready for that.  Are you ready for me to merge this, @hchen139 ?

2016-11-23 00:07 UTC, hchen139 commented
I'm ready. Just go ahead. @bwspenc

2016-11-23 00:13 UTC, merged