Mesh functors
idaholab/moose pull request #8100
Opened 2016-11-20 22:40 UTC by permcody

This PR adds the basic ghosting functor capability to MOOSE. I also fixed up some low hanging fruit with "regular_orthogonal_mesh" check that affects a ton of `MeshModifiers` and the phase-field module. There are probably many more but we'll get those as we start doing better DistributedMesh testing.

For testing I added a new GhostUserObject that figures out what elements are geometrically ghosted (NOT algebraically ghosted) so this UO is not useful with ReplicatedMesh as a result. It's just a test object and we can flesh it out more later.

2016-11-20 22:41 UTC, permcody commented
![3d_ghost](https://cloud.githubusercontent.com/assets/3036960/20466837/c7e15cbc-af37-11e6-8deb-6450dde323a4.png)
![3d_ghost_2](https://cloud.githubusercontent.com/assets/3036960/20466838/c7e5be1a-af37-11e6-8832-0885feee26f7.png)

2016-11-20 22:46 UTC, permcody commented
@roystgnr, I just add a few new input file options in MOOSE to turn on the edge and point neighbor functors. I tried for awhile, but couldn't successfully create a test that can verify correct operation of the point neighbor functor. I tried all of the 3D element types and there was no difference for any of the 3D meshes versus just running the problem normally without any functors. Perhaps I'll have to make a mesh manually where there's a node that has several elements attached to it? If you have any good ideas for how I can manufacture a test case, let me know.

2016-11-20 22:49 UTC, permcody commented on framework/src/mesh/MooseMesh.C
> +    }
@roystgnr - This logic allows me to add both "point" and "edge" functors to the `MeshBase` object. However, when I tested them together, it appears that the second one didn't run (i.e. I received the output below with the thinner banding between partitions). I might be making a mistake somewhere, but I wanted to make sure I was using these correctly before digging in.

2016-11-20 22:52 UTC, permcody commented on framework/src/mesh/MooseMesh.C
> +                       " when DistribuedMesh is used. Value is ignored in ReplicatedMesh mode");
New `[Mesh]` options are here

2016-11-20 23:20 UTC, friedmud commented
Noted
On Sun, Nov 20, 2016 at 5:52 PM Cody Permann <notifications@github.com>
wrote:

> *@permcody* commented on this pull request.
> ------------------------------
>
> In framework/src/mesh/MooseMesh.C
> <https://github.com/idaholab/moose/pull/8100#pullrequestreview-9375420>:
>
> > @@ -97,11 +100,16 @@ InputParameters validParams<MooseMesh>()
>
>    // Note: This parameter is named to match 'construct_side_list_from_node_list' in SetupMeshAction
>    params.addParam<bool>("construct_node_list_from_side_list", true, "Whether or not to generate nodesets from the sidesets (usually a good idea).");
> +  params.addParam<unsigned short>("num_ghosted_edge_neighbors", 1, "Parameter to specify the number of geometric edge neighers"
> +                                 " that will be available when DistribuedMesh is used. Value is ignored in ReplicatedMesh mode");
> +  params.addParam<bool>("ghost_point_neighbors", false, "Boolean to specify whether or not all point neighbors are ghosted"
> +                       " when DistribuedMesh is used. Value is ignored in ReplicatedMesh mode");
>
> New [Mesh] options are here
>
> —
> You are receiving this because you were assigned.
>
>
> Reply to this email directly, view it on GitHub
> <https://github.com/idaholab/moose/pull/8100#pullrequestreview-9375420>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AA1JMddglQAjffLlWoRgT27ncwmnQsI_ks5rAM9BgaJpZM4K3rql>
> .
>

2016-11-20 23:20 UTC, friedmud commented
Thanks for working on this!
On Sun, Nov 20, 2016 at 6:19 PM Derek Gaston <friedmud@gmail.com> wrote:

> Noted
> On Sun, Nov 20, 2016 at 5:52 PM Cody Permann <notifications@github.com>
> wrote:
>
> *@permcody* commented on this pull request.
> ------------------------------
>
> In framework/src/mesh/MooseMesh.C
> <https://github.com/idaholab/moose/pull/8100#pullrequestreview-9375420>:
>
> > @@ -97,11 +100,16 @@ InputParameters validParams<MooseMesh>()
>
>    // Note: This parameter is named to match 'construct_side_list_from_node_list' in SetupMeshAction
>    params.addParam<bool>("construct_node_list_from_side_list", true, "Whether or not to generate nodesets from the sidesets (usually a good idea).");
> +  params.addParam<unsigned short>("num_ghosted_edge_neighbors", 1, "Parameter to specify the number of geometric edge neighers"
> +                                 " that will be available when DistribuedMesh is used. Value is ignored in ReplicatedMesh mode");
> +  params.addParam<bool>("ghost_point_neighbors", false, "Boolean to specify whether or not all point neighbors are ghosted"
> +                       " when DistribuedMesh is used. Value is ignored in ReplicatedMesh mode");
>
> New [Mesh] options are here
>
> —
> You are receiving this because you were assigned.
>
>
> Reply to this email directly, view it on GitHub
> <https://github.com/idaholab/moose/pull/8100#pullrequestreview-9375420>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AA1JMddglQAjffLlWoRgT27ncwmnQsI_ks5rAM9BgaJpZM4K3rql>
> .
>
>

2016-11-21 14:52 UTC, roystgnr commented on framework/src/mesh/MooseMesh.C
> +    }
You'll probably want to be adding these as algebraic coupling functors too, later, but that wouldn't explain reduced ghosting now.  I assume those plots were made by looping over ghosted elements, not over evaluable elements?

2016-11-21 16:30 UTC, permcody commented
The logic is really simple and can be seen in the "GhostUserObject" in this
PR. I'm looping over "active elements" and keeping track of any elements
with a different processor ID from the current processor.
On Mon, Nov 21, 2016 at 7:52 AM roystgnr <notifications@github.com> wrote:

> *@roystgnr* commented on this pull request.
> ------------------------------
>
> In framework/src/mesh/MooseMesh.C
> <https://github.com/idaholab/moose/pull/8100>:
>
> > @@ -191,6 +199,21 @@ MooseMesh::MooseMesh(const InputParameters & parameters) :
>        _partitioner_name = "parmetis";
>        _partitioner_overridden = true;
>      }
> +
> +    // Add geometric ghosting functors to mesh if running with DistributedMesh
> +    if (getParam<bool>("ghost_point_neighbors"))
> +      _ghosting_functors.emplace_back(libmesh_make_unique<GhostPointNeighbors>(*_mesh));
> +
> +    auto num_edge_neighbors = getParam<unsigned short>("num_ghosted_edge_neighbors");
> +    if (num_edge_neighbors > 1)
> +    {
> +      auto default_coupling = libmesh_make_unique<DefaultCoupling>();
> +      default_coupling->set_n_levels(num_edge_neighbors);
> +      _ghosting_functors.emplace_back(std::move(default_coupling));
> +    }
>
> You'll probably want to be adding these as algebraic coupling functors
> too, later, but that wouldn't explain reduced ghosting now. I assume those
> plots were made by looping over ghosted elements, not over evaluable
> elements?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/idaholab/moose/pull/8100>, or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AC5XIFNPjmap8j9_YrQvtA-fPjzunhQfks5rAbAQgaJpZM4K3rql>
> .
>

2016-11-21 16:41 UTC, friedmud commented
@permcody You should easily be able to tell the different between point neighbors and not.  I would think that the test case you have here should show it.  If you're not seeing any difference then maybe something isn't working right...

2016-11-21 17:06 UTC, permcody commented
I suppose it's not working then. I ran exodiff on several cases with a
without that new option and exodiff always reported no differences.
On Mon, Nov 21, 2016 at 9:41 AM Derek Gaston <notifications@github.com>
wrote:

> @permcody <https://github.com/permcody> You should easily be able to tell
> the different between point neighbors and not. I would think that the test
> case you have here should show it. If you're not seeing any difference then
> maybe something isn't working right...
>
> —
> You are receiving this because you were mentioned.
>
>
> Reply to this email directly, view it on GitHub
> <https://github.com/idaholab/moose/pull/8100#issuecomment-261992798>, or mute
> the thread
> <https://github.com/notifications/unsubscribe-auth/AC5XIGU7w6rAMdN9xP5ej-9dfa8WxEdjks5rAcmhgaJpZM4K3rql>
> .
>

2016-11-23 21:21 UTC, permcody commented
I know that @jwpeterson has run into this before but Parmetis gives us different partitions on Mac/Linux. It appears that the partitions are consistent on a given platform, just different. For these tests I checked in different gold files for each platform, the input file is the same. Hopefully this passes all tests and can be merged.

2016-11-23 23:53 UTC, friedmud submitted a review, later dismissed
The testing could use an option to only "view" the ghosts for one particular processor.  Right now you're getting the union of the ghosts for all processors.  Some things could be hiding in there.

2016-11-23 23:53 UTC, friedmud commented on test/include/userobjects/GhostUserObject.h
> + * An Elemental user object tha uses built-in Random number generation.
Is it?  Really?

2016-11-23 23:53 UTC, friedmud commented on framework/src/mesh/MooseMesh.C
> +  params.addParam<unsigned short>("num_ghosted_edge_neighbors", 1, "Parameter to specify the number of geometric edge neighers"
@permcody and I discussed changing this to `num_ghosted_layers`

2016-11-28 17:15 UTC, permcody commented
@jwpeterson - I don't know @friedmud's availability, could you perhaps review this PR? All comments have been addressed. I'd like to get it in along with my other distributed mesh PR (but one of them will need to be rebased after the other since they both made the same change on two lines.

2016-11-28 17:51 UTC, jwpeterson requested changes

2016-11-28 17:51 UTC, jwpeterson commented on framework/src/mesh/MooseMesh.C
> +                       " when DistribuedMesh is used. Value is ignored in ReplicatedMesh mode");
This indentation seems to be off by 1 compared to the indentation on line 111.

2016-11-28 17:51 UTC, jwpeterson commented on framework/src/mesh/MooseMesh.C
> +                                 " that will be available when DistribuedMesh is used. Value is ignored in ReplicatedMesh mode");
This indentation seems to be off by 1 compared to the indentation on line 111.

2016-11-28 17:51 UTC, jwpeterson commented on test/include/auxkernels/GhostAux.h
> + * An AuxKernel that uses built-in Random number generation.
Copy-pasted doco is wrong.

2016-11-28 17:51 UTC, jwpeterson commented on test/src/auxkernels/GhostAux.C
> +  params.addParam<UserObjectName>("ghost_user_object", "The GhostUserObject where this Aux pulls values from");
Please add `classDescription()`

2016-11-28 17:51 UTC, jwpeterson commented on test/src/userobjects/GhostUserObject.C
> +  params.addParam<unsigned int>("rank", DofObject::invalid_processor_id, "The rank for which the ghosted elements are recorded (Default: ALL)");
Please add `classDescription()`.

2016-11-28 17:51 UTC, jwpeterson commented on test/include/userobjects/GhostUserObject.h
> + * User object to show Ghosted User Objects on ALL processors or a single processor.
Not sure I follow this comment.  Do you mean "show ghosted elements" or "show ghosted geometric entities"?

2016-11-28 20:10 UTC, permcody commented
All comments addressed.

2016-11-28 20:20 UTC, jwpeterson commented on test/include/userobjects/GhostUserObject.h
> + * User object to calculate ghosted elemnts on a single processor or the union across all processors.
"elemnts"

2016-11-28 20:21 UTC, jwpeterson commented on test/include/userobjects/GhostUserObject.h
> + * User object to calculate ghosted elemnts on a single processor or the union across all processors.
Other than that, looks good.

2016-11-28 20:54 UTC, jwpeterson approved these changes

2016-11-28 22:17 UTC, merged