Pf_frac_8197#Issue Number 8197
idaholab/moose pull request #8206
Opened 2016-12-12 16:38 UTC by zhangsf2015

### Complete each of the following items before creating a PR

- Include any relevant design information for your change
- Follow [Coding Standards](http://mooseframework.org/wiki/CodeStandards/)
- Submit one or more [Test Cases](http://mooseframework.org/wiki/MooseTraining/testing/) or modify existing test cases
- Reference or close a specific issue (refs # or closes #)

2016-12-12 16:48 UTC, dschwen commented on modules/combined/tests/phase_field_fracture_viscoplastic/crack2d.i
> +  file_base = crack_2d_out
Please do not use file base.

2016-12-12 16:48 UTC, dschwen commented on modules/phase_field/include/kernels/PFFracBulkRate.h
> +  // std::string _base_name;
Remove, it is uncommented below

2016-12-12 16:48 UTC, dschwen commented on modules/phase_field/include/kernels/PFFracBulkRate.h
> +  unsigned int _ndisp;
Const

2016-12-12 16:48 UTC, dschwen commented on modules/phase_field/src/kernels/PFFracBulkRate.C
> +  _disp_var(3),
Size with _ndisp

2016-12-12 16:48 UTC, dschwen commented on modules/phase_field/src/kernels/PFFracBulkRate.C
> +    for (unsigned int i = 0; i < _ndisp; ++i)
Indentation

2016-12-12 16:49 UTC, dschwen commented
Please use a more meaningful pull request title and move the issue number in the pr body.

2016-12-12 17:09 UTC, dschwen commented
Pleas squash your first five commits together and clean up the commit messages. Look at other commits in the MOOSE repository. No need to repeat _"Issue number"_ or mention the names of the files you change. Please describe _what_ the change does.

2016-12-12 18:38 UTC, zhangsf2015 commented on modules/phase_field/include/kernels/PFFracBulkRate.h
> +  // std::string _base_name;
Okay, I will remove it. Thanks.

2016-12-12 18:40 UTC, zhangsf2015 commented on modules/phase_field/include/kernels/PFFracBulkRate.h
> +  unsigned int _ndisp;
Okay. Thank you!

2016-12-12 18:40 UTC, zhangsf2015 commented on modules/phase_field/src/kernels/PFFracBulkRate.C
> +  _disp_var(3),
That's better. Thanks!

2016-12-12 18:41 UTC, zhangsf2015 commented on modules/phase_field/src/kernels/PFFracBulkRate.C
> +    for (unsigned int i = 0; i < _ndisp; ++i)
It helps. Thank you.

2016-12-12 19:18 UTC, zhangsf2015 commented on modules/combined/tests/phase_field_fracture_viscoplastic/crack2d.i
> +  file_base = crack_2d_out
Okay, I will fix it.

2016-12-12 23:09 UTC, dschwen commented on modules/combined/tests/phase_field_fracture/void2d.i
> +    displacements = 'disp_x disp_y'
I suggest moving those to GlobalParams as well

2016-12-12 23:11 UTC, dschwen commented on modules/phase_field/src/kernels/PFFracBulkRate.C
> +      Real x =   _l * _betaval[_qp] + 2.0*(1-c) * _G0_pos[_qp]/gc - c/_l;
undo this change and add whitespace around the operators

2016-12-12 23:12 UTC, dschwen commented on modules/phase_field/src/kernels/PFFracBulkRate.C
> +  Real x = _l * _betaval[_qp] + 2.0*(1 - c) * (_G0_pos[_qp]/gc) - c/_l;
undo all changes `1.0` -> `1`. The one is not an integer and I would very much prefer if we explicitly add the decimal `.0` to floating point literals.

2016-12-12 23:12 UTC, dschwen commented on modules/phase_field/src/kernels/PFFracBulkRate.C
> +  // // Contribution of displacements to off diag Jacobian of c
remove one `//`

2016-12-12 23:13 UTC, dschwen commented on modules/tensor_mechanics/src/materials/LinearIsoElasticPFDamage.C
> +    _dstress_dc[_qp] = -stress0pos * 0;
just `0.0`

2016-12-12 23:14 UTC, dschwen commented
:+1: for changing this over to the `displacements` vector coupling! I'll take another look once you address the comments.

2016-12-13 17:45 UTC, zhangsf2015 commented on modules/combined/tests/phase_field_fracture/void2d.i
> +    displacements = 'disp_x disp_y'
Okay, no problem

2016-12-13 17:45 UTC, zhangsf2015 commented on modules/combined/tests/phase_field_fracture/void2d.i
> +  file_base = void2d_out
Sure, thanks.

2016-12-13 17:46 UTC, zhangsf2015 commented on modules/phase_field/src/kernels/PFFracBulkRate.C
> +      Real x =   _l * _betaval[_qp] + 2.0*(1-c) * _G0_pos[_qp]/gc - c/_l;
Great, it is true. Thanks

2016-12-13 17:47 UTC, zhangsf2015 commented on modules/phase_field/src/kernels/PFFracBulkRate.C
> +  // // Contribution of displacements to off diag Jacobian of c
Okay. No problem

2016-12-13 17:47 UTC, zhangsf2015 commented on modules/tensor_mechanics/src/materials/LinearIsoElasticPFDamage.C
> +    _dstress_dc[_qp] = -stress0pos * 0;
Okay, I will try this.

2016-12-13 21:17 UTC, dschwen requested changes

2016-12-13 21:17 UTC, dschwen commented on framework/include/utils/RankTwoTensor.h
>    /// performs _vals *= a
Please fix the comment to actually describe the operator. I'm not convinced that we should implement this overload at all. It is not obvious what it should do. Should it maybe rather set the tensor to I*a (I being the identity matrix)? 

Are you using this for anything other than `tensor = 0.0`? If not then please use `tensor.zero()` and remove this method.

2016-12-13 21:17 UTC, dschwen commented on modules/phase_field/src/kernels/PFFracBulkRate.C
> +  }
indentation is off here as well

2016-12-13 21:17 UTC, dschwen commented on modules/phase_field/src/kernels/PFFracBulkRate.C
> +
rm extra blank line

2016-12-13 21:17 UTC, dschwen commented on modules/phase_field/src/kernels/PFFracBulkRate.C
> +      Real x = _l * _betaval[_qp] + 2.0 * (1.0-c) * _G0_pos[_qp] / gc - c / _l;
operator spacing around `-`

2016-12-13 21:17 UTC, dschwen commented on modules/phase_field/src/kernels/PFFracBulkRate.C
> +  // Contribution of displacements to off diag Jacobian of c
add empty line above the comment

2016-12-13 21:17 UTC, dschwen commented on modules/phase_field/src/kernels/PFFracBulkRate.C
> +
remove extra empty line here

2016-12-13 21:17 UTC, dschwen commented on modules/tensor_mechanics/src/materials/LinearIsoElasticPFDamage.C
> +    _dstress_dc[_qp] = 0.0;
use `_dstress_dc[_qp].zero()` here

2016-12-13 21:21 UTC, dschwen commented on framework/include/utils/RankTwoTensor.h
>    /// performs _vals *= a
Actually I'm pretty convinced that we should _not_ add this operator overload @tonkmr

2016-12-15 23:14 UTC, dschwen commented
Closing in favor of #8227, which has the requested fixes added.

2016-12-15 23:14 UTC, closed without merging