Gradient continuity InterfaceKernel
idaholab/moose pull request #8212
Opened 2016-12-13 19:51 UTC by dschwen

Add InterfaceKernel to enforce gradient continuity.

Closes #8211

2016-12-14 00:04 UTC, fdkong requested changes

2016-12-14 00:04 UTC, fdkong commented on modules/phase_field/src/interfacekernels/InterfaceGradientMatch.C
> +  mooseError("Internal error.");
Could we add something meaningful like: "do not support DGJacobianType %s"?

2016-12-14 00:04 UTC, fdkong requested changes

2016-12-14 00:04 UTC, fdkong commented on modules/phase_field/tests/misc/interface_flux.i
> +
Remove comments?

2016-12-14 00:20 UTC, dschwen commented on modules/phase_field/src/interfacekernels/InterfaceGradientMatch.C
> +  mooseError("Internal error.");
There is no unsupported option. The error is only needed to satisfy gcc. Clang is smart enough to realize that line is unreachable and the function always returns. And I could not convert that enum into a string anyways.

2016-12-14 00:22 UTC, dschwen commented on modules/phase_field/tests/misc/interface_flux.i
> +
See top comment in that file. I'd like to retain the objects that reproduce the same result. But I didn't want to bloat the gold file :-/

2016-12-14 15:55 UTC, fdkong commented on modules/phase_field/src/interfacekernels/InterfaceGradientMatch.C
> +
More general way is to subtract along the normal direction of the surface, I guess. Do you assume that the boundary will be aligned  with one of axis directions?

2016-12-14 15:58 UTC, fdkong commented on modules/phase_field/examples/interfacekernels/interface_gradient.i
> +  [../]
How these two boundary conditions coexist? Will we get a totally different solution if we remove the second condition  `diffusion_surface_term`.
 I am  curious.

2016-12-14 16:00 UTC, fdkong commented on modules/phase_field/tests/misc/interface_grad.i
> +
This makes sense.

2016-12-14 16:01 UTC, dschwen commented on modules/phase_field/src/interfacekernels/InterfaceGradientMatch.C
> +
I assume that I have to apply _n_ kernels for each of the gradient components (to get the periodicity of the entire strain tensor for example).

2016-12-14 18:28 UTC, dschwen commented on modules/phase_field/src/interfacekernels/InterfaceDiffusionFlux.C
> +      return -_D * _grad_u[_qp] * _normals[_qp] * _test[_i][_qp];
I would like to keep this as a simple example that demonstrates the relation between integrated BCs and interface kernels.

2016-12-14 18:51 UTC, YaqiWang commented on modules/phase_field/src/interfacekernels/InterfaceDiffusionFlux.C
> +      return -_D * _grad_u[_qp] * _normals[_qp] * _test[_i][_qp];
Interface kernels should be closely related with DG kernels, except they allow the variables change on the two sides and do not necessarily operate on all internal sides.

2016-12-14 18:53 UTC, dschwen commented on modules/phase_field/src/interfacekernels/InterfaceDiffusionFlux.C
> +      return -_D * _grad_u[_qp] * _normals[_qp] * _test[_i][_qp];
Where are you going with that comment?

2016-12-15 00:01 UTC, fdkong approved these changes

2016-12-15 00:02 UTC, merged