Volumetric locking tensor
idaholab/moose pull request #8236
Opened 2016-12-19 04:20 UTC by sveerara

@bwspenc , @sapitts : There are three commit in this merge request. 

First commit has the tensor mechanics kernels and the materials code changes. Volumetric locking correction is set to false by default. In 1-D cases, an error would be shown if volumetric locking correction is set to true. 

In the second commit, new tests have been added. These tests check the volumetric locking correction implementation for the basic mechanics tests. Also one element tests have been added to check the hand coded jacobian against the finite difference jacobian. 

In the third commit, earlier tests which used finite strain calculation have been edited. The earlier implementation of finite strain calculation had volumetric locking correction turned on by default. 

closes #8235

2016-12-19 17:45 UTC, sveerara commented
Bison patch is ready. 

One tests in Grizzly is failing. I don't have access to Grizzly. @bwspenc can you please take a look at the grizzly test. Setting volumetric_locking_correction = true in GlobalParams got rid of most of the Bison errors. 

Mastodon is failing because libmesh must be compiled with VTK. I am not sure why Mammoth is failing.

2016-12-19 20:34 UTC, dschwen requested changes

2016-12-19 20:34 UTC, dschwen commented on framework/include/utils/RankFourTensor.h
> +  Real sum_3x3() const;
This is at odds with our naming convention. I suggest removing the `_`

2016-12-19 20:34 UTC, dschwen commented on modules/tensor_mechanics/include/kernels/StressDivergenceTensors.h
> +  /// Parameters for volumetric locking correction
please use `@{` `@}` to have the doxygen comment apply to each parameter or give each parameter its own comment. This way only the first parameter will have the given documentation and the remaining two will be undocumented.

2016-12-19 20:34 UTC, dschwen commented on modules/tensor_mechanics/src/actions/TensorMechanicsAction.C
> +    if (volumetric_locking_correction)
do 

```
if (_ndisp == 1 && getParam<bool>("volumetric_locking_correction"))
  mooseError("Volumetric locking correction should be set to false for 1D problems.");
```

2016-12-19 20:34 UTC, dschwen commented on modules/tensor_mechanics/src/actions/TensorMechanicsAction.C
> +    params.set<bool>("volumetric_locking_correction") = getParam<bool>("volumetric_locking_correction");
No! This line is not needed. I'm using `applyParameters`

2016-12-19 20:34 UTC, dschwen commented on modules/tensor_mechanics/src/actions/TensorMechanicsAction.C
> +  params.set<bool>("volumetric_locking_correction") = getParam<bool>("volumetric_locking_correction");
No, remove this as well (see above)

2016-12-19 20:34 UTC, dschwen commented on modules/tensor_mechanics/src/kernels/DynamicStressDivergenceTensors.C
> +
rm empty line

2016-12-19 20:34 UTC, dschwen commented on modules/tensor_mechanics/src/kernels/DynamicStressDivergenceTensors.C
> +               + (_alpha * _zeta/_dt) * _stress_older[_qp]. trace()) / 3.0 * (_avg_grad_test[_i][_component] - _grad_test[_i][_qp](_component));
make indentation consistent

2016-12-19 20:34 UTC, dschwen commented on modules/tensor_mechanics/src/kernels/StressDivergenceRZTensors.C
> +
rm empty lines

2016-12-19 20:34 UTC, dschwen commented on modules/tensor_mechanics/src/kernels/StressDivergenceRZTensors.C
> +  for (_i = 0; _i < _test.size(); _i++)
we use pre increment `++_i` pretty consistently in TM

2016-12-19 20:34 UTC, dschwen commented on modules/tensor_mechanics/src/kernels/StressDivergenceRZTensors.C
> +
rm empty line

2016-12-19 23:27 UTC, sveerara commented
I have addressed the comments. Thanks!

2016-12-20 22:08 UTC, bwspenc commented
So is this ready to go?  @sveerara, you said that you have a fix ready for BISON, right?  I can fix the Grizzly test diff.

2016-12-20 22:10 UTC, sveerara commented
Yes, I have the bison fix ready.

2016-12-20 22:11 UTC, dschwen approved these changes

2016-12-20 22:23 UTC, dschwen commented on framework/include/utils/RankFourTensor.h
> +
rm extra line

2016-12-20 22:23 UTC, dschwen commented on modules/tensor_mechanics/src/kernels/StressDivergenceTensors.C
> +        phi(2,1) = _grad_phi[_j][_qp](1);
could be simplified to 
```
for (unsigned int i = 0; i < 3; ++i)
  phi(_component, i) = _grad_phi[_j][_qp](i);
```

removing 16 lines of code

2016-12-20 22:28 UTC, dschwen commented
@bwspenc is standing by to fix Bison and Grizzly. Merging now.

2016-12-20 22:28 UTC, merged

2017-01-03 16:02 UTC, brianmoose commented
This seems to have caused the heavy test `combined:j2_plasticity_vs_LSH.j2_hard1_mod` to fail with a CSVDIFF. See https://www.moosebuild.org/job/58993/

2017-01-03 20:59 UTC, sveerara commented
@brianmoose, thanks for the information. I will correct the test and submit a merge request.