Fixup GeneralizedPlaneStrainAction
idaholab/moose pull request #8260
Opened 2016-12-22 20:11 UTC by dschwen

In preparation for TensorMechanicsAction work I need this action to be smart enough to handle temperature as an AuxVariable. I've also added comments and trimmed down the parameter passing using `applyParameters()`

Refs #7987

2016-12-22 21:27 UTC, bwspenc approved these changes

2016-12-22 21:28 UTC, bwspenc commented
The code looks fine, although it apparently still has some issues that still need to be worked out since it's breaking some tests.

2017-01-09 16:58 UTC, dschwen commented
I assume `combined:generalized_plane_strain_tm_contact.generalized_plane_strain_tm_contact` is an unrelated failure that was mentioned earlier in the standup, @bwspenc @sapitts ?

2017-01-09 17:15 UTC, bwspenc commented
@dschwen The test failing here is not due to that issue we were talking about.  This is the error from exodiff:
exodiff: WARNING .. specified element variable "strain_zz" is not in the first file.
It sounds like you are adding strain_zz, but it's not in the gold file.

2017-01-09 17:23 UTC, dschwen commented
Ah, got it thanks. This is probably due to the `aux_strain_zz` -> `strain_zz` renaming

2017-01-12 17:12 UTC, jwpeterson commented on framework/src/functions/MooseParsedFunction.C
> +/*          Prepared by Battelle Energy Alliadnce, LLC           */
wut

2017-01-12 17:13 UTC, permcody commented on framework/src/functions/MooseParsedFunction.C
> +/*          Prepared by Battelle Energy Alliadnce, LLC           */
😆

2017-01-12 17:43 UTC, permcody requested changes
Let's fix this comment before we merge.

2017-01-12 18:00 UTC, dschwen commented on framework/src/functions/MooseParsedFunction.C
> +/*          Prepared by Battelle Energy Alliadnce, LLC           */
Ugh, I was testing the spell check after you asked me about spellchecking in code comments :-/

2017-01-12 19:27 UTC, permcody commented
RunException interleaved output error - ignoring.

2017-01-12 19:27 UTC, permcody approved these changes

2017-01-12 19:28 UTC, merged