Minor fixup for #8293
idaholab/moose pull request #8305
Opened 2017-01-11 15:04 UTC by permcody

Just tweaking the changes Andy made to modules.mk for him. This supersedes #8293.

2017-01-11 16:30 UTC, permcody commented
Looks like Github won't let me review my own PR (even though it's almost all Andy's). Assigning to @dschwen

2017-01-11 22:39 UTC, WilkAndy commented
Aha, thank you for fixing the makefile stuff, @permcody .  Hopefully next time i'll be able to do it on my own.

a

2017-01-12 16:37 UTC, jwpeterson requested changes

2017-01-12 16:37 UTC, jwpeterson commented on unit/Makefile
> +CHEMICAL_REACIONTS := yes
Typo on this line!  "REACIONTS"

2017-01-12 16:39 UTC, permcody commented on unit/Makefile
> +CHEMICAL_REACIONTS := yes
Nice catch!

2017-01-12 19:39 UTC, dschwen commented on modules/porous_flow/include/kernels/PorousFlowDesorpedMassTimeDerivative.h
> +#ifndef PORFLOWDESORPEDMASSTIMEDERIVATIVE_H
why not `POROUSFLOWDESORPEDMASSTIMEDERIVATIVE_H` like in all the other files?

2017-01-12 22:27 UTC, WilkAndy commented on modules/porous_flow/include/kernels/PorousFlowDesorpedMassTimeDerivative.h
> +#ifndef PORFLOWDESORPEDMASSTIMEDERIVATIVE_H
Hmmm.  i'll change this

2017-01-12 22:32 UTC, WilkAndy commented
@permcody , i think i just made a PR to your wilk_pr2 branch that changes PORFLOW to POROUSFLOW in 2 header files (to address @dschwen comment above).  Could you tell me if i've done the wrong thing?

2017-01-12 22:32 UTC, WilkAndy commented
Oh, you're too fast for me @permcody , thanks.

2017-01-17 17:45 UTC, permcody commented
@jwpeterson - perhaps you can review this PR since I'm now an author. It's been up here for awhile now.

2017-01-17 18:00 UTC, jwpeterson approved these changes

2017-01-17 18:01 UTC, merged