Ported all CNSFV codes from Bighorn to Navier-Stokes
idaholab/moose pull request #8344
Opened 2017-01-18 21:27 UTC by yidongxiainl

CNSFV stands for Compressible Navier-Stokes by Finite Volume

closes #8228

### Complete each of the following items before creating a PR

- Include any relevant design information for your change
- Follow [Coding Standards](http://mooseframework.org/wiki/CodeStandards/)
- Submit one or more [Test Cases](http://mooseframework.org/wiki/MooseTraining/testing/) or modify existing test cases
- Reference or close a specific issue (refs # or closes #)

2017-01-18 21:58 UTC, permcody commented
Will this break Bighorn build?

2017-01-18 21:58 UTC, permcody commented
@andrsd, @jwpeterson - would you rather we import history?

2017-01-18 21:59 UTC, yidongxiainl commented
@permcody Yes and No. I have made relevant changes in Bighorn too, but not committed yet.

2017-01-18 22:00 UTC, andrsd commented
Since we test bighorn with the latest MOOSE, it will break.

We do not need to import the history, CNSFV is very young and 95% was done by @yidongxiainl

2017-01-18 22:01 UTC, yidongxiainl commented
@permcody This will again be a long effort to its final shape. I am doing early testing just because I want to eliminate bugs in the codes first. Then I will work on the new online documentation within this PR.

2017-01-19 19:05 UTC, moosebuild commented
Job `App tests:linux-gnu` on 89d04df : invalidated by @andrsd

bighorn should be fixed

2017-02-09 21:47 UTC, moosebuild commented
Job `Moose Documentation:linux-clang` on 1d6a1c4 wanted to post the following:

View the site at http://mooseframework.org/docs/PRs/8344/site

2017-02-09 22:22 UTC, moosebuild commented
Job `Precheck:linux-gnu` on 1d6a1c4 : invalidated by @rwcarlsen

2017-02-10 18:08 UTC, moosebuild commented
Job `Moose Documentation:linux-clang` on e3b6dda wanted to post the following:

View the site at http://mooseframework.org/docs/PRs/8344/site

2017-02-10 18:18 UTC, andrsd commented
@yidongxiainl You will need to add MOOSE module header to all `.h` and `.C` files

2017-02-10 21:54 UTC, moosebuild commented
Job `Moose Documentation:linux-clang` on 8fb1e80 wanted to post the following:

View the site at http://mooseframework.org/docs/PRs/8344/site

2017-02-10 22:29 UTC, moosebuild commented
Job `Moose Documentation:linux-clang` on d885cd2 wanted to post the following:

View the site at http://mooseframework.org/docs/PRs/8344/site

2017-02-11 00:00 UTC, moosebuild commented
Job `Moose Documentation:linux-clang` on 200b197 wanted to post the following:

View the site at http://mooseframework.org/docs/PRs/8344/site

2017-02-11 00:50 UTC, moosebuild commented
Job `Moose Documentation:linux-clang` on d5d63ba wanted to post the following:

View the site at http://mooseframework.org/docs/PRs/8344/site

2017-02-12 05:04 UTC, yidongxiainl commented
@andrsd Added MOOSE module header to all source code files. Passed all checks. Need peer review now.

2017-02-13 17:28 UTC, andrsd requested changes

2017-02-13 17:28 UTC, andrsd commented on modules/navier_stokes/src/userobjects/CNSFVLeastSquaresSlopeReconstruction.C
> +  const Elem* elem = _current_elem;
Spaces around `*`

2017-02-13 17:28 UTC, andrsd commented on modules/navier_stokes/src/userobjects/CNSFVLeastSquaresSlopeReconstruction.C
> +//      ugrad[iv] = 0.;
Do we need this?

2017-02-13 17:28 UTC, andrsd commented on modules/navier_stokes/src/userobjects/CNSFVSlopeLimitingOneD.C
> +    break;
The proper indebtantion is:
```
case 0:
  code;
  more_code;
  break;
```

2017-02-13 17:28 UTC, andrsd commented on modules/navier_stokes/tests/cnsfv/1d_double_rarefaction_wave.i
> + kernel_coverage_check = false
2 spaces...

2017-02-13 17:28 UTC, andrsd commented on modules/navier_stokes/tests/cnsfv/2d_bump_impl_ref2.i
> +[]
No empty blocks...

2017-02-13 17:28 UTC, andrsd commented on modules/navier_stokes/tests/cnsfv/2d_bump_impl_ref3.i
> +  implicit = true
`implicit` is `true` by default, we do not need it...

2017-02-13 17:28 UTC, andrsd commented on modules/navier_stokes/tests/cnsfv/2d_bump_impl_ref3.i
> +    implicit = true
This is most likely copy and paste from an explicit solve, `implicit = true` by default, no need for it.

2017-02-13 17:28 UTC, andrsd commented on modules/navier_stokes/tests/cnsfv/2d_cyln_expl_lv3.i
> +    #type = ExplicitTVDRK2
Remove...

2017-02-13 17:28 UTC, andrsd commented on modules/navier_stokes/tests/cnsfv/2d_cyln_impl_lv2.i
> +  #dt = 1.
Remove

2017-02-13 17:28 UTC, andrsd commented on modules/navier_stokes/tests/cnsfv/2d_obliqueshock_expl_weno.i
> +#[]
Remove this.

2017-02-13 17:57 UTC, yidongxiainl commented on modules/navier_stokes/include/bcs/CNSFVBC.h
> + *   1. This BC kernel itself does not do any complex calculation.
Fixed

2017-02-13 17:57 UTC, yidongxiainl commented on modules/navier_stokes/include/dgkernels/CNSFVKernel.h
> + *   2. In general, a approximate Riemann solver should be used
Fixed

2017-02-13 17:58 UTC, yidongxiainl commented on modules/navier_stokes/include/userobjects/CNSFVGreenGaussSlopeReconstruction.h
> +    public SlopeReconstructionMultiD
Fixed

2017-02-13 18:15 UTC, yidongxiainl commented on modules/navier_stokes/src/auxkernels/CNSFVEntropyProductionAux.C
> +    AuxKernel(parameters),
All fixed.

2017-02-13 18:18 UTC, yidongxiainl commented on modules/navier_stokes/src/auxkernels/CNSFVSpecificTotalEnthalpyAux.C
> +     return params;
All fixed.

2017-02-13 18:18 UTC, yidongxiainl commented on modules/navier_stokes/include/materials/CNSFVMaterial.h
> +  const VariableValue & _rhoc;  /// density
All fixed.

2017-02-13 18:21 UTC, yidongxiainl commented on modules/navier_stokes/src/bcs/CNSFVBC.C
> +                             _rhoe1[_qp]};
All fixed.

2017-02-13 18:23 UTC, yidongxiainl commented on modules/navier_stokes/src/dgkernels/CNSFVKernel.C
> +    _rhouc1(coupledValue("rhou")),
All fixed.

2017-02-13 18:28 UTC, yidongxiainl commented on modules/navier_stokes/src/dgkernels/CNSFVKernel.C
> +    break;
Fixed.

2017-02-13 18:29 UTC, yidongxiainl commented on modules/navier_stokes/src/postprocessors/CNSFVIdealGasEntropyL2Error.C
> + return diff * diff;
Fixed.

2017-02-13 18:29 UTC, yidongxiainl commented on modules/navier_stokes/src/userobjects/CNSFVFreeInflowBoundaryFlux.C
> +  //Real rhoe1 = uvec1[4];
Yes. Need to denote the correct correspondence from uvec1

2017-02-13 18:30 UTC, yidongxiainl commented on modules/navier_stokes/src/userobjects/CNSFVFreeOutflowBoundaryFlux.C
> +  //Real enth1 = (rhoe1 + pres1) / rho1;
No. Removed.

2017-02-13 18:31 UTC, yidongxiainl commented on modules/navier_stokes/src/userobjects/CNSFVGreenGaussSlopeReconstruction.C
> +  const Elem* elem = _current_elem;
Fixed.

2017-02-13 19:16 UTC, yidongxiainl commented on modules/navier_stokes/src/userobjects/CNSFVHLLCInflowOutflowBoundaryFlux.C
> +        , name() , ": " , __FUNCTION__ , "\n"
All fixed.

2017-02-13 19:16 UTC, yidongxiainl commented on modules/navier_stokes/src/userobjects/CNSFVHLLCInflowOutflowBoundaryFlux.C
> +    , "mach1 = " , mach1 , "\n");
All fixed.

2017-02-13 19:16 UTC, yidongxiainl commented on modules/navier_stokes/src/userobjects/CNSFVLeastSquaresSlopeReconstruction.C
> +  const Elem* elem = _current_elem;
Fixed.

2017-02-13 19:17 UTC, yidongxiainl commented on modules/navier_stokes/src/userobjects/CNSFVLeastSquaresSlopeReconstruction.C
> +//      ugrad[iv] = 0.;
No. Removed.

2017-02-13 19:18 UTC, yidongxiainl commented on modules/navier_stokes/src/userobjects/CNSFVSlopeLimitingOneD.C
> +    break;
Fixed.

2017-02-13 19:24 UTC, yidongxiainl commented on modules/navier_stokes/tests/cnsfv/2d_bump_impl_ref3.i
> +    implicit = true
All fixed.

2017-02-13 19:26 UTC, yidongxiainl commented on modules/navier_stokes/tests/cnsfv/2d_cyln_expl_lv3.i
> +    #type = ExplicitTVDRK2
Done.

2017-02-13 19:26 UTC, yidongxiainl commented on modules/navier_stokes/tests/cnsfv/2d_cyln_impl_lv2.i
> +  #dt = 1.
Done

2017-02-13 19:26 UTC, yidongxiainl commented on modules/navier_stokes/tests/cnsfv/2d_obliqueshock_expl_weno.i
> +#[]
Done.

2017-02-13 19:29 UTC, yidongxiainl commented on docs/content/documentation/modules/navier_stokes/tmp.md
> +
No use. Will delete it.

2017-02-13 20:46 UTC, moosebuild commented
Job `Moose Documentation:linux-clang` on f039d73 wanted to post the following:

View the site at http://mooseframework.org/docs/PRs/8344/site

2017-02-14 15:34 UTC, moosebuild commented
Job `Moose Documentation:linux-clang` on 7ef84b7 wanted to post the following:

View the site at http://mooseframework.org/docs/PRs/8344/site

2017-02-14 17:57 UTC, andrsd requested changes

2017-02-14 17:57 UTC, andrsd commented on modules/navier_stokes/src/auxkernels/CNSFVEntropyProductionAux.C
> +    return (_pres[_qp] / _inf_pres)
2 spaces here...

2017-02-14 17:57 UTC, andrsd commented on modules/navier_stokes/src/auxkernels/CNSFVSpecificTotalEnthalpyAux.C
> +    return _enth[_qp];
2 spaces.

2017-02-14 17:57 UTC, andrsd commented on modules/navier_stokes/src/postprocessors/CNSFVIdealGasTotalEnthalpyL2Error.C
> + return diff * diff;
2 spaces.

2017-02-14 17:57 UTC, andrsd commented on modules/navier_stokes/src/userobjects/CNSFVHLLCInternalSideFlux.C
> +  Real sm = (rho2 * vdon2 * dsv2 - rho1 * vdon1 * dsv1 + pres1 - pres2)/
`) /` (missing space)

2017-02-14 17:57 UTC, andrsd commented on modules/navier_stokes/src/userobjects/CNSFVHLLCInternalSideFlux.C
> +  Real rhoer = omeg2 * (dsv2 * rhoe2 - pres2 * vdon2 + prsta*sm);
spaces around `*`.

2017-02-14 17:57 UTC, andrsd commented on modules/navier_stokes/src/userobjects/CNSFVHLLCInternalSideFlux.C
> +    Real rhoer = omeg2 * (dsv2 * rhoe2 - pres2 * vdon2 + prsta *sm );
space after `*`

2017-02-14 17:57 UTC, andrsd commented on modules/navier_stokes/src/userobjects/CNSFVNoSlopeReconstruction.C
> +  const Elem* elem = _current_elem;
space before `*`

2017-02-14 17:57 UTC, andrsd commented on modules/navier_stokes/tests/cnsfv/1d_sedov_blast_wave.i
> + kernel_coverage_check = false
2 spaces

2017-02-14 17:57 UTC, andrsd commented on modules/navier_stokes/tests/cnsfv/1d_sod_shock_tube.i
> + kernel_coverage_check = false
2 spaces

2017-02-14 17:57 UTC, andrsd commented on modules/navier_stokes/tests/cnsfv/1d_square_wave_mc_limiter.i
> + kernel_coverage_check = false
2 spaces

2017-02-14 17:57 UTC, andrsd commented on modules/navier_stokes/tests/cnsfv/1d_square_wave_minmod_limiter.i
> + kernel_coverage_check = false
2 spaces

2017-02-14 17:57 UTC, andrsd commented on modules/navier_stokes/tests/cnsfv/1d_square_wave_superbee_limiter.i
> + kernel_coverage_check = false
2 spaces

2017-02-14 17:57 UTC, andrsd commented on modules/navier_stokes/tests/cnsfv/1d_woodward_colella_blast_wave.i
> + kernel_coverage_check = false
2 spaces

2017-02-14 17:57 UTC, andrsd commented on modules/navier_stokes/tests/cnsfv/2d_bowshock_expl_lv0.i
> + kernel_coverage_check = false
2 spaces

2017-02-14 17:57 UTC, andrsd commented on modules/navier_stokes/tests/cnsfv/2d_bowshock_expl_lv0.i
> +[]
Remove

2017-02-14 17:57 UTC, andrsd commented on modules/navier_stokes/tests/cnsfv/2d_bowshock_expl_lv1.i
> + kernel_coverage_check = false
2 spaces

2017-02-14 17:57 UTC, andrsd commented on modules/navier_stokes/tests/cnsfv/2d_bowshock_expl_lv1.i
> +[]
Remove the empty block

2017-02-14 17:57 UTC, andrsd commented on modules/navier_stokes/tests/cnsfv/2d_bowshock_expl_lv2.i
> + kernel_coverage_check = false
2 space

2017-02-14 17:57 UTC, andrsd commented on modules/navier_stokes/tests/cnsfv/2d_bowshock_expl_lv2.i
> +[]
Empty block -> remove.

2017-02-14 17:57 UTC, andrsd commented on modules/navier_stokes/tests/cnsfv/2d_bump_impl_ref1.i
> + kernel_coverage_check = false
2 spaces

2017-02-14 17:57 UTC, andrsd commented on modules/navier_stokes/tests/cnsfv/2d_bump_impl_ref1.i
> +[]
Empty block -> remove.

2017-02-14 17:57 UTC, andrsd commented on modules/navier_stokes/tests/cnsfv/2d_bump_impl_ref3.i
> + kernel_coverage_check = false
2 spaces

2017-02-14 17:57 UTC, andrsd commented on modules/navier_stokes/tests/cnsfv/2d_bump_impl_ref3.i
> +[]
Empty block -> remove.

2017-02-14 17:57 UTC, andrsd commented on modules/navier_stokes/tests/cnsfv/2d_bump_impl_ref4.i
> + kernel_coverage_check = false
2 spaces

2017-02-14 17:57 UTC, andrsd commented on modules/navier_stokes/tests/cnsfv/2d_bump_impl_ref4.i
> +[]
Empty block -> remove

2017-02-14 17:57 UTC, andrsd commented on modules/navier_stokes/tests/cnsfv/2d_bump_impl_ref5.i
> + kernel_coverage_check = false
2 spaces

2017-02-14 17:57 UTC, andrsd commented on modules/navier_stokes/tests/cnsfv/2d_bump_impl_ref5.i
> +[]
Empty block -> remove.

2017-02-14 17:57 UTC, andrsd commented on modules/navier_stokes/tests/cnsfv/2d_cyln_expl_lv1.i
> + kernel_coverage_check = false
2 spaces

2017-02-14 17:57 UTC, andrsd commented on modules/navier_stokes/tests/cnsfv/2d_cyln_expl_lv1.i
> +[]
Empty block -> remove

2017-02-14 17:57 UTC, andrsd commented on modules/navier_stokes/tests/cnsfv/2d_cyln_expl_lv2.i
> + kernel_coverage_check = false
2 spaces

2017-02-14 17:57 UTC, andrsd commented on modules/navier_stokes/tests/cnsfv/2d_cyln_expl_lv2.i
> +[]
Empty block -> remove

2017-02-14 17:57 UTC, andrsd commented on modules/navier_stokes/tests/cnsfv/2d_cyln_expl_lv3.i
> + kernel_coverage_check = false
2 spaces

2017-02-14 17:57 UTC, andrsd commented on modules/navier_stokes/tests/cnsfv/2d_cyln_expl_lv3.i
> +[]
Empty block -> remove

2017-02-14 17:57 UTC, andrsd commented on modules/navier_stokes/tests/cnsfv/2d_cyln_expl_lv4.i
> + kernel_coverage_check = false
2 spaces

2017-02-14 17:57 UTC, andrsd commented on modules/navier_stokes/tests/cnsfv/2d_cyln_expl_lv4.i
> +[]
Empty block -> remove

2017-02-14 17:57 UTC, andrsd commented on modules/navier_stokes/tests/cnsfv/2d_cyln_impl_lv1.i
> + kernel_coverage_check = false
2 spaces

2017-02-14 17:57 UTC, andrsd commented on modules/navier_stokes/tests/cnsfv/2d_cyln_impl_lv1.i
> +[]
Empty block -> remove

2017-02-14 17:57 UTC, andrsd commented on modules/navier_stokes/tests/cnsfv/2d_cyln_impl_lv2.i
> + kernel_coverage_check = false
2 spaces

2017-02-14 17:57 UTC, andrsd commented on modules/navier_stokes/tests/cnsfv/2d_cyln_impl_lv2.i
> +[]
Empty block -> remove

2017-02-14 17:57 UTC, andrsd commented on modules/navier_stokes/tests/cnsfv/2d_cyln_impl_lv3.i
> + kernel_coverage_check = false
2 spaces

2017-02-14 17:57 UTC, andrsd commented on modules/navier_stokes/tests/cnsfv/2d_cyln_impl_lv3.i
> +[]
Empty block -> remove

2017-02-14 17:57 UTC, andrsd commented on modules/navier_stokes/tests/cnsfv/2d_cyln_impl_lv4.i
> + kernel_coverage_check = false
2 spaces

2017-02-14 17:57 UTC, andrsd commented on modules/navier_stokes/tests/cnsfv/2d_cyln_impl_lv4.i
> +[]
Empty block -> remove

2017-02-14 17:57 UTC, andrsd commented on modules/navier_stokes/tests/cnsfv/2d_lax_shock_tube.i
> + kernel_coverage_check = false
2 spaces

2017-02-14 17:57 UTC, andrsd commented on modules/navier_stokes/tests/cnsfv/2d_mach3step.i
> + kernel_coverage_check = false
2 spaces

2017-02-14 17:57 UTC, andrsd commented on modules/navier_stokes/tests/cnsfv/2d_mach3step.i
> +[]
Empty block -> remove

2017-02-14 17:57 UTC, andrsd commented on modules/navier_stokes/tests/cnsfv/2d_obliqueshock_expl_weno.i
> + kernel_coverage_check = false
2 spaces

2017-02-14 17:57 UTC, andrsd commented on modules/navier_stokes/tests/cnsfv/2d_obliqueshock_expl_weno.i
> +[]
Empty block -> remove

2017-02-14 17:57 UTC, andrsd commented on modules/navier_stokes/tests/cnsfv/2d_sod_shock_tube.i
> + kernel_coverage_check = false
2 spaces

2017-02-14 17:57 UTC, andrsd commented on modules/navier_stokes/tests/cnsfv/2d_sod_shock_tube_parallel2.i
> + kernel_coverage_check = false
2 spaces

2017-02-14 17:57 UTC, andrsd commented on modules/navier_stokes/tests/cnsfv/2d_sod_shock_tube_parallel4.i
> + kernel_coverage_check = false
2 spaces

2017-02-14 17:57 UTC, andrsd commented on modules/navier_stokes/tests/cnsfv/2d_square_wave_gg_minmax.i
> + kernel_coverage_check = false
2 spaces

2017-02-14 17:57 UTC, andrsd commented on modules/navier_stokes/tests/cnsfv/2d_square_wave_gg_minmax.i
> +[]
Empty block -> remove

2017-02-14 18:50 UTC, moosebuild commented
Job `Moose Documentation:linux-clang` on 31ff56a wanted to post the following:

View the site at http://mooseframework.org/docs/PRs/8344/site

2017-02-14 19:18 UTC, moosebuild commented
Job `Moose Documentation:linux-clang` on 4c1bd23 wanted to post the following:

View the site at http://mooseframework.org/docs/PRs/8344/site

2017-02-14 19:24 UTC, andrsd approved these changes

2017-02-14 20:41 UTC, yidongxiainl commented
@permcody would you take an overview and see if there is anything noticeable that you would like me to revise?

2017-02-15 00:12 UTC, moosebuild commented
Job `Moose Documentation:linux-clang` on 7f324eb wanted to post the following:

View the site at http://mooseframework.org/docs/PRs/8344/site

2017-02-15 04:51 UTC, yidongxiainl commented
@permcody @andrsd  One test failed in Test Heavy, which though is not in the navier_stokes module.

2017-02-15 14:22 UTC, brianmoose commented
The heavy test that failed is a known failure and has nothing to do with this PR.

2017-02-15 15:17 UTC, permcody approved these changes

2017-02-15 15:17 UTC, merged

2017-02-15 15:43 UTC, brianmoose commented
@yidongxiainl You have patches for wolverine and moltres right?

2017-02-15 16:41 UTC, brianmoose commented
This also broke the 64bit build https://www.moosebuild.org/job/68808/

2017-02-15 19:23 UTC, andrsd commented
I will take care of the 64 bit fix...

2017-02-15 20:05 UTC, andrsd commented
@brianmoose I do not think this broke the wolverine build. The missing symbols are coming from rDG module (but this PR does not touch that). It almost looks like there are some stale object files that the build system picks up. I verified that wolverine builds fine with current devel on my machine (Mac). Maybe `git clean` the build box and resubmit the test?

2017-02-15 20:44 UTC, andrsd commented
I used wrong version of MOOSE. Now, it does not build with the right version...

I will have a patch ready in a moment.