Additionally testing and improvments to MooseDocs
idaholab/moose pull request #8363
Opened 2017-01-19 22:23 UTC by aeslaughter

@jwpeterson This includes a patch that will re-build when the executable is changed, so you can now change class descriptions, re-compile, and the live site should update.

(refs #8329)

2017-01-19 22:34 UTC, moosebuild commented
Job `Moose Documentation:linux-clang` on 0b97bb8 wanted to post the following:

View the site at http://mooseframework.org/docs/PRs/8363/site

2017-01-19 23:13 UTC, jwpeterson commented
Looks fine to me, although I wouldn't know if anything was wrong...

2017-01-19 23:13 UTC, jwpeterson approved these changes

2017-01-19 23:26 UTC, moosebuild commented
Job `Moose Documentation:linux-clang` on 103bd3e wanted to post the following:

View the site at http://mooseframework.org/docs/PRs/8363/site

2017-01-20 00:25 UTC, moosebuild commented
Job `Moose Documentation:linux-clang` on 4976783 wanted to post the following:

View the site at http://mooseframework.org/docs/PRs/8363/site

2017-01-20 00:37 UTC, moosebuild commented
Job `Moose Documentation:linux-clang` on 89c1cb8 wanted to post the following:

View the site at http://mooseframework.org/docs/PRs/8363/site

2017-01-23 17:32 UTC, moosebuild commented
Job `Moose Documentation:linux-clang` on f616f08 wanted to post the following:

View the site at http://mooseframework.org/docs/PRs/8363/site

2017-01-23 18:12 UTC, brianmoose requested changes
The phase_field/index.html doesn't get generated.
There is actually an exception happening on the "build docs" step on CIVET involving phase_field. There isn't any error though.

2017-01-23 22:13 UTC, moosebuild commented
Job `Moose Documentation:linux-clang` on 63fd4bf wanted to post the following:

View the site at http://mooseframework.org/docs/PRs/8363/site

2017-01-23 23:12 UTC, moosebuild commented
Job `Moose Documentation:linux-clang` on 534f684 wanted to post the following:

View the site at http://mooseframework.org/docs/PRs/8363/site

2017-01-24 00:31 UTC, aeslaughter commented on python/MooseDocs/commands/MooseDocsMarkdownNode.py
@permcody This should be more better than the try-except, I was just being lazy.

2017-01-24 17:18 UTC, brianmoose commented on python/MooseDocs/commands/MooseDocsMarkdownNode.py
Maybe use the lock as a context manager so that if `makedirs` raises an exception then the lock will be released.

2017-01-24 18:08 UTC, aeslaughter commented on python/MooseDocs/commands/MooseDocsMarkdownNode.py
@brianmoose Something like this?

```
with multiprocessing.Lock():
   blah blah blah
```

2017-01-24 18:12 UTC, brianmoose commented on python/MooseDocs/commands/MooseDocsMarkdownNode.py
Yeah, that is what I had in mind.

2017-01-24 20:05 UTC, permcody commented on python/MooseDocs/commands/MooseDocsMarkdownNode.py
Agreed, please implement that change. This looks better though.

2017-01-24 20:05 UTC, permcody requested changes
Implement the scoped lock

2017-01-24 21:11 UTC, moosebuild commented
Job `Moose Documentation:linux-clang` on 3115cdd wanted to post the following:

View the site at http://mooseframework.org/docs/PRs/8363/site

2017-01-24 21:18 UTC, brianmoose approved these changes

2017-01-24 21:58 UTC, permcody approved these changes

2017-01-24 21:58 UTC, merged