Add Atom and Jupyter setup instructions work on Phase Field landing page
idaholab/moose pull request #8372
Opened 2017-01-23 22:09 UTC by dschwen

This has some small changes to `moose.css` @aeslaughter (to render bold text and bring back bullets)

Refs #8368

2017-01-23 22:19 UTC, moosebuild commented
Job `Moose Documentation:linux-clang` on ca52f7c wanted to post the following:

View the site at http://mooseframework.org/docs/PRs/8372/site

2017-01-23 23:11 UTC, moosebuild commented
Job `Moose Documentation:linux-clang` on ff924c3 wanted to post the following:

View the site at http://mooseframework.org/docs/PRs/8372/site

2017-01-23 23:33 UTC, moosebuild commented
Job `Moose Documentation:linux-clang` on 34abdaa wanted to post the following:

View the site at http://mooseframework.org/docs/PRs/8372/site

2017-01-24 00:23 UTC, moosebuild commented
Job `Moose Documentation:linux-clang` on b1b18e3 wanted to post the following:

View the site at http://mooseframework.org/docs/PRs/8372/site

2017-01-24 00:43 UTC, moosebuild commented
Job `Moose Documentation:linux-clang` on f0969da wanted to post the following:

View the site at http://mooseframework.org/docs/PRs/8372/site

2017-01-24 15:20 UTC, aeslaughter commented
Let me know when you are done adding content to this PR, I don't want to start reviewing if you plan to keep adding commits. Thanks.

2017-01-24 16:48 UTC, dschwen commented
@aeslaughter I'm trying to fix the docs build errors, but it seems like the docs system does not pick up any mesh classes! Are you working from home? Can you come into the gitter chat?

2017-01-24 17:46 UTC, moosebuild commented
Job `Moose Documentation:linux-clang` on 5db496f wanted to post the following:

View the site at http://mooseframework.org/docs/PRs/8372/site

2017-01-26 17:24 UTC, moosebuild commented
Job `Moose Documentation:linux-clang` on 4070ece wanted to post the following:

View the site at http://mooseframework.org/docs/PRs/8372/site

2017-01-26 19:38 UTC, aeslaughter requested changes

2017-01-26 19:38 UTC, aeslaughter commented on docs/content/documentation/modules/phase_field/ICs/EBSD.md
> +The user object reads in the data file, using the name supplied in the mesh block,
UserObject?

2017-01-26 19:38 UTC, aeslaughter commented on docs/content/documentation/modules/phase_field/ICs/EBSD.md
> +  [./ebsd]
I think you should include the [UserObjects] block as well so people no where to put this.

2017-01-26 19:38 UTC, aeslaughter commented on docs/content/documentation/modules/phase_field/ICs/EBSD.md
> +```
Let it be known that I would prefer that this was imported from an actual input file, but you can do what you want.

2017-01-26 19:38 UTC, aeslaughter commented on docs/content/documentation/modules/phase_field/ICs/EBSD.md
> +* `phi1` - The average first Euler angle $$\phi_1$$
Use a single $ to make this inline

2017-01-26 19:38 UTC, aeslaughter commented on docs/content/documentation/modules/phase_field/Multi Phase/KKS Analytical.md
> +!text modules/phase_field/examples/kim-kim-suzuki/kks_example_noflux.i max-height=300px strip-extra-newlines=True overflow-y=scroll
The input files seem like they should go after the text.

2017-01-26 19:38 UTC, aeslaughter commented on docs/content/documentation/modules/phase_field/Multi Phase/KKS Analytical.md
> +where we use the switching function $h(\eta) = \eta^3(6\eta^2-15\eta+10)$, the gradient energy coefficient $\epsilon^2 = 1$ and the barrier function height $w=1$. (Note that there is a typo in Eq. (4
"the paper" should be an actual ref. using bibtex

2017-01-26 19:38 UTC, aeslaughter commented on docs/content/documentation/modules/phase_field/Multi Phase/KKS Analytical.md
> +where $u$ is the analytical solution, $u_h$ is the equilibrium solution from simulation, and $\Omega$ is the domain. The $L^2$ norm can be obtained in the MOOSE framework using the `ElementL2Error` p
```
[/ElementL2Error.md](ElementL2Error)
```

2017-01-26 19:38 UTC, aeslaughter commented on docs/content/documentation/modules/phase_field/Multi Phase/KKS Analytical.md
> +(In performing this comparison between the analytical solution and simulation results, if a no-flux boundary condition is used in the simulation, the order parameter and composition profiles may shif
This probably doesn't need to be in parentheses.

2017-01-26 19:38 UTC, aeslaughter commented on docs/content/documentation/modules/phase_field/Multi Phase/KKS Derivations.md
> +* [KKS] S.G. Kim, W.T. Kim, and T. Suzuki, Phys. Rev. E 60 (1999) 7186
Utilize the bibtex feature. http://www.mooseframework.org/docs/moose_docs/site/utilities/documentation/moose_flavored_markdown/index.html

2017-01-26 19:38 UTC, aeslaughter commented on docs/content/documentation/modules/phase_field/Multi Phase/KKS Derivations.md
> +This is the split version. In this kernel, we calculate the chemical potential $\mu$ from $\frac{\partial F}{\partial c}$. The non-linear variable for this Kernel is the concentration $c$. To calcula
You have references to objects throughout this document, they should probably link to the markdown files.

2017-01-26 19:38 UTC, aeslaughter commented on docs/content/documentation/modules/phase_field/Multi Phase/KKS Derivations.md
> +# KKS Model Definitions
I hope your math is right, there is no way I can check it.

2017-01-26 19:38 UTC, aeslaughter commented on docs/content/documentation/modules/phase_field/Multi Phase/KKS.md
> +1. Kim et al., Phys. Rev. E, 60 (1999) 7186-7197
Use bibtex

2017-01-26 19:38 UTC, aeslaughter commented on docs/content/documentation/modules/phase_field/Multi Phase/WBM.md
> +Material objects that internally derive from ```DerivativeFunctionMaterialBase``` ([Doxygen](http://mooseframework.org/docs/doxygen/modules/classDerivativeFunctionMaterialBase.html)), like the materi
Parsed Function Kernels link is not right

2017-01-26 19:38 UTC, aeslaughter commented on docs/content/documentation/modules/phase_field/Multi Phase/WBM.md
> +!parameters /Materials/DerivativeMultiPhaseMaterial
This seems strange just plopped in the middle of the text

2017-01-26 19:38 UTC, aeslaughter commented on docs/content/documentation/modules/phase_field/Multi Phase/WBM.md
> +The gradient interface energy term for multiphase models with _n_>2 is derived [here](ACMultiInterface) and provided by the ```ACMultiInterface``` kernel.
here link is not correct

2017-01-26 19:38 UTC, aeslaughter commented on docs/content/documentation/modules/phase_field/Multi Phase/WBM.md
> +Note that the phase free energies are single wells. The global free energy landscape will however have a double well character in this example.
Should this be a admonition

```
!!! note
    blah blah...
```

2017-01-26 19:38 UTC, aeslaughter commented on docs/content/documentation/modules/phase_field/Solving.md
>  * `NEWTON` - Direct solution of the system of equations using Newton's method. The full and accurate Jacobian is required. Thus, the [Preconditioner](../../../framework/systems/Preconditioning/Overvi
[Preconditioner] link needs update

2017-01-26 19:40 UTC, aeslaughter commented
I went through this rather quickly and found some basic things, I won't be much help checking your math. Also, you include a lot of input file syntax that I think should be updated to reference actual input files, but this is your code you can do what you want.

2017-01-26 20:52 UTC, dschwen commented on docs/content/documentation/modules/phase_field/Multi Phase/KKS Derivations.md
> +# KKS Model Definitions
Trust me, I know what I'm...

nevermind.

Jacobian check says that at least the second half is correct :-)

2017-01-26 21:24 UTC, moosebuild commented
Job `Moose Documentation:linux-clang` on 14af8e3 wanted to post the following:

View the site at http://mooseframework.org/docs/PRs/8372/site

2017-01-26 22:28 UTC, moosebuild commented
Job `Moose Documentation:linux-clang` on 5afac27 wanted to post the following:

View the site at http://mooseframework.org/docs/PRs/8372/site

2017-01-27 23:41 UTC, aeslaughter approved these changes

2017-01-27 23:41 UTC, merged