Documentation for volumetric locking correction #8386
idaholab/moose pull request #8387
Opened 2017-01-25 05:53 UTC by sveerara

Markdown documentation for the tensor mechanics volumetric locking correction. 

closes #8386

2017-01-25 06:05 UTC, moosebuild commented
Job `Moose Documentation:linux-clang` on 929603f wanted to post the following:

View the site at http://mooseframework.org/docs/PRs/8387/site

2017-01-25 16:38 UTC, dschwen commented on docs/content/documentation/modules/tensor_mechanics/VolumetricLocking.md
> +Volumetric locking is the over stiffening of elements when the material is close to being incompressible (Poisson's ratio $\nu$ nearing 0.5). This happens when a fully integrated element (such as Hex
a doi link would be nicer here

2017-01-25 16:51 UTC, dschwen commented on docs/content/documentation/modules/tensor_mechanics/VolumetricLocking.md
> +Volumetric locking is the over stiffening of elements when the material is close to being incompressible (Poisson's ratio $\nu$ nearing 0.5). This happens when a fully integrated element (such as Hex
Even better would be http://mooseframework.org/docs/PRs/8387/site/utilities/documentation/moose_flavored_markdown/index.html#bibliographies !

2017-01-25 17:59 UTC, moosebuild commented
Job `Moose Documentation:linux-clang` on 8c4fc60 wanted to post the following:

View the site at http://mooseframework.org/docs/PRs/8387/site

2017-01-25 18:33 UTC, dschwen commented on docs/content/documentation/modules/tensor_mechanics/VolumetricLocking.md
> +Volumetric locking is the over stiffening of elements when the material is close to being incompressible (Poisson's ratio $\nu$ nearing 0.5). This happens when a fully integrated element (such as Hex
round parenthesis maybe?.. sorry for being a pain in the neck

2017-01-25 18:34 UTC, dschwen commented on docs/content/documentation/modules/tensor_mechanics/VolumetricLocking.md
> +More details about this method can be found in [Bower(2012)](http://solidmechanics.org/Text/Chapter8_6/Chapter8_6.php#Sect8_6_1).
can we use bib for that as well? It will make generating nice PDFs much easier going forward

2017-01-26 16:10 UTC, bwspenc approved these changes
Aside from the minor issues with the citations, this is good to go.

2017-01-26 16:10 UTC, bwspenc commented on docs/content/documentation/modules/tensor_mechanics/VolumetricLocking.md
> +Volumetric locking is the over stiffening of elements when the material is close to being incompressible (Poisson's ratio $\nu$ nearing 0.5). This happens when a fully integrated element (such as Hex
Just change it to:
... correction \cite{hughes1987finite} is implemented...

2017-01-26 16:31 UTC, dschwen requested changes
fix citations

2017-01-26 17:01 UTC, dschwen approved these changes

2017-01-26 17:25 UTC, moosebuild commented
Job `Moose Documentation:linux-clang` on 79d658a wanted to post the following:

View the site at http://mooseframework.org/docs/PRs/8387/site

2017-01-26 17:40 UTC, merged