Issue 7951
idaholab/moose pull request #8393
Opened 2017-01-25 20:20 UTC by permcody

Don't disable logging if it's needed elsewhere.

2017-01-25 23:54 UTC, jwpeterson requested changes

2017-01-25 23:54 UTC, jwpeterson commented on framework/src/outputs/Console.C
> +#ifdef LIBMESH_ENABLE_PERFORMANCE_LOGGING
I realize you didn't add this code block in this PR, but I don't think it needs to be wrapped in the `ifdef`.  The global `perflog` object exists no matter what, the `ifdef` only controls the behavior of the `START_LOG`, `STOP_LOG`, etc. macros.

2017-01-25 23:54 UTC, jwpeterson commented on test/tests/postprocessors/print_perf_data/tests
> +    absent_out = '(\s(\S+)\s\|\n)[^\n]*\1'
As a regex-challenged person, I don't really understand why this regex works.  Can you maybe give an example in the comments of the output you are trying to make sure is absent?

2017-01-26 15:27 UTC, aeslaughter commented on framework/include/base/MooseApp.h
> +
Just to reduce adding more stuff to MooseApp, should these just go into OutputWarehouse? The Console and PerformanceData have access to the OutputWarehouse from _app, but if you prefer this I don't mind that much.

2017-01-26 15:46 UTC, permcody commented on framework/src/outputs/Console.C
> +#ifdef LIBMESH_ENABLE_PERFORMANCE_LOGGING
I'll strip all these in another commit.

2017-01-26 15:46 UTC, permcody commented on test/tests/postprocessors/print_perf_data/tests
> +    absent_out = '(\s(\S+)\s\|\n)[^\n]*\1'
👍

2017-01-26 16:07 UTC, permcody commented on framework/include/base/MooseApp.h
> +
will do

2017-01-26 16:29 UTC, aeslaughter approved these changes

2017-01-26 17:03 UTC, jwpeterson approved these changes

2017-01-26 21:03 UTC, merged