Skip Analyzejacobian tests if numpy is not present
idaholab/moose pull request #8397
Opened 2017-01-25 21:34 UTC by dschwen

This lets test inspect the `checks` structure and make decisions on whether they should run independently of the user.

Closes #8395

2017-01-25 22:27 UTC, permcody requested changes
I'm not sure if I'm crazy about changing the public API for this new check. I like the idea of passing more information down to the Tester to make decisions but it's not necessary to get this done. 

All of the existing "configuration" checks occur in Tester.py since I figured many of them would be independent of the Testers (which they often are). Why not just move the numpy check into Tester.py? We can change the interface separately.

2017-01-25 22:32 UTC, dschwen commented
Hmm, most of the checks in tester are for user supplied criteria that describe features needed by the moose executable to execute a specific input. The numpy check is a hard dependency of the tester. I suppose I could just remove the entry in `checks` and do the try import straight up in the AnalyzeJacobian.py class. That would be a far smaller change!

2017-01-25 22:36 UTC, dschwen commented
Yeah, that's much better. While working on the first iteration I was still learning how the skip logic works...

2017-01-25 22:38 UTC, permcody commented
Oh yeah, I like that better. Maybe we can augment that interface later.

2017-01-25 22:41 UTC, milljm commented on python/TestHarness/testers/AnalyzeJacobian.py
> +
👍

2017-01-26 16:38 UTC, permcody approved these changes

2017-01-26 16:38 UTC, merged