Adding BoundingBoxVectorPostProcessor
idaholab/moose pull request #8425
Opened 2017-01-27 21:42 UTC by permcody

Adding a Postprocessor to output bounding boxes for all features.

2017-01-27 21:43 UTC, permcody commented
Tag @aeslaughter - see the CSV file included in this PR. Note that the feature ID may be duplicated. This isn't super important to you, it just shows you that some features have more than one bounding box (when periodic boundary conditions are applied). Later we can add additional columns for color, etc.

2017-01-27 22:59 UTC, aeslaughter requested changes

2017-01-27 22:59 UTC, aeslaughter commented on modules/phase_field/include/vectorpostprocessors/FeatureBoundingBoxVectorPostprocessor.h
> +  VectorPostprocessorValue & _feature_id;
This should get a /// comment

2017-01-27 22:59 UTC, aeslaughter commented on modules/phase_field/include/vectorpostprocessors/FeatureBoundingBoxVectorPostprocessor.h
> +  VectorPostprocessorValue & _max_z;
You should wrap these all in a doxygen comment

///@{
/// Min, max ....
VectorPostprocessorValue ...
///@}

2017-01-27 22:59 UTC, aeslaughter commented on modules/phase_field/include/vectorpostprocessors/FeatureBoundingBoxVectorPostprocessor.h
> +  const std::vector<MooseVariable *> & _vars;
docs

2017-01-27 22:59 UTC, aeslaughter commented on modules/phase_field/src/vectorpostprocessors/FeatureBoundingBoxVectorPostprocessor.C
> +
addClassDescription

2017-02-09 22:05 UTC, moosebuild commented
Job `Precheck:linux-gnu` on 3326eb8 : invalidated by @rwcarlsen

2017-02-09 22:29 UTC, aeslaughter commented
@permcody Do you still want me to work on this capability?

2017-02-09 23:22 UTC, permcody commented
Maybe... Clearly it's not a high priority for me at the moment since this PR is still sitting here.

2017-05-23 15:58 UTC, permcody commented
@dschwen - Any interest in me fixing up this PR? I thought I wanted it for visualization but never got around to using it. It could go in with minimal effort but I don't know if anyone actually cares. It might just get killed.

2017-06-21 15:28 UTC, aeslaughter commented
@permcody You don't seem to need this anymore, we can re-visit when needed again.

2017-06-21 15:29 UTC, aeslaughter commented
@permcody You don't seem to need this anymore, we can re-visit when needed again.

2017-06-21 15:29 UTC, closed without merging