NumElemes postprocessor defaults to active elems
idaholab/moose pull request #8427
Opened 2017-01-30 17:34 UTC by rwcarlsen

fixes #8421

2017-01-31 14:33 UTC, permcody requested changes

2017-01-31 14:33 UTC, permcody commented on framework/include/postprocessors/NumElems.h
> +  enum ElemType
I'd prefer to see C++11 style enums.

2017-01-31 15:50 UTC, rwcarlsen commented
Should be ready.

2017-01-31 15:51 UTC, moosebuild commented on libmesh
> +Subproject commit 91f574130bdd9779b3e51cc56a245748aa0432e0
**Caution!** This contains a submodule update

2017-02-01 15:09 UTC, permcody approved these changes

2017-02-01 15:09 UTC, merged