Read Split Checkpoint Files
idaholab/moose pull request #8472
Opened 2017-02-03 23:39 UTC by friedmud

Initial capability for reading split checkpoint files.

Also slightly modifies how Nemesis files are read by removing the `nemesis` option in favor of a common `pre_split` option.

2017-02-03 23:45 UTC, friedmud commented
This is somewhat tied to https://github.com/libMesh/libmesh/pull/1228

Anyone trying to use this PR should use the libMesh branch in https://github.com/libMesh/libmesh/pull/1228 to split the mesh.

2017-02-04 01:46 UTC, friedmud commented
Hmm - I don't understand the test failure - it works fine on my system...

Maybe a difference  in how libMesh is configured?

2017-02-04 01:54 UTC, permcody commented
Do you _require_ a special branch of libmesh or even just a newer version
than the submodule? If so, make sure that's also part of your commit.
On Fri, Feb 3, 2017 at 6:46 PM Derek Gaston <notifications@github.com>
wrote:

> Hmm - I don't understand the test failure - it works fine on my system...
>
> Maybe a difference in how libMesh is configured?
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/idaholab/moose/pull/8472#issuecomment-277408402>, or mute
> the thread
> <https://github.com/notifications/unsubscribe-auth/AC5XIK3l69dBH75wYQsI0Hu4xmIDWYy6ks5rY9hngaJpZM4L27vR>
> .
>

2017-02-04 02:08 UTC, friedmud commented
Good point!  I don't think so - but let me double check...

On Fri, Feb 3, 2017 at 8:54 PM Cody Permann <notifications@github.com>
wrote:

> Do you _require_ a special branch of libmesh or even just a newer version
> than the submodule? If so, make sure that's also part of your commit.
> On Fri, Feb 3, 2017 at 6:46 PM Derek Gaston <notifications@github.com>
> wrote:
>
> > Hmm - I don't understand the test failure - it works fine on my system...
> >
> > Maybe a difference in how libMesh is configured?
> >
> > —
> > You are receiving this because you are subscribed to this thread.
> > Reply to this email directly, view it on GitHub
> > <https://github.com/idaholab/moose/pull/8472#issuecomment-277408402>,
> or mute
> > the thread
> > <
> https://github.com/notifications/unsubscribe-auth/AC5XIK3l69dBH75wYQsI0Hu4xmIDWYy6ks5rY9hngaJpZM4L27vR
> >
> > .
> >
>
> —
> You are receiving this because you authored the thread.
>
>
> Reply to this email directly, view it on GitHub
> <https://github.com/idaholab/moose/pull/8472#issuecomment-277409110>, or mute
> the thread
> <https://github.com/notifications/unsubscribe-auth/AA1JMT9e4kl7rnCzxkWJrmbOVM1laFfHks5rY9o_gaJpZM4L27vR>
> .
>

2017-02-04 03:00 UTC, friedmud commented
@permcody you were right - the test doesn't pass with the current libMesh sub-module.

It doesn't need that PR - but it does need the parallel checkpoint stuff that @jwpeterson got merged into libMesh a little while ago

2017-02-04 03:01 UTC, friedmud commented
I think I'll wait until libMesh/libmesh#1228 gets merged before updating the submodule in this PR.

2017-02-05 01:57 UTC, moosebuild commented on libmesh
> +Subproject commit cc49a536e66ef481f6229805656987cb87db6465
**Caution!** This contains a submodule update

2017-02-05 02:01 UTC, friedmud commented
It looks like something is wrong with the civet recipe (or did I mess up the module update?).

Any advice?

2017-02-05 03:16 UTC, permcody commented
Can't scroll through all that on my phone. I'll have to look using my
laptop.
On Sat, Feb 4, 2017 at 7:01 PM Derek Gaston <notifications@github.com>
wrote:

> It looks like something is wrong with the civet recipe (or did I mess up
> the module update?).
>
> Any advice?
>
> —
> You are receiving this because you were mentioned.
>
>
> Reply to this email directly, view it on GitHub
> <https://github.com/idaholab/moose/pull/8472#issuecomment-277492024>, or mute
> the thread
> <https://github.com/notifications/unsubscribe-auth/AC5XIGtv9S6vupP6BJIkrLTyaa5X8Om0ks5rZS2PgaJpZM4L27vR>
> .
>

2017-02-05 03:33 UTC, permcody commented
Submodule looks ok, it's definitely isolated to your PR though. Mike's is
building just fine. You can see the environment and the exact command we
run in the output. I don't see the problem right this second...

On Sat, Feb 4, 2017 at 7:01 PM Derek Gaston <notifications@github.com>
wrote:

> It looks like something is wrong with the civet recipe (or did I mess up
> the module update?).
>
> Any advice?
>
> —
> You are receiving this because you were mentioned.
>
>
> Reply to this email directly, view it on GitHub
> <https://github.com/idaholab/moose/pull/8472#issuecomment-277492024>, or mute
> the thread
> <https://github.com/notifications/unsubscribe-auth/AC5XIGtv9S6vupP6BJIkrLTyaa5X8Om0ks5rZS2PgaJpZM4L27vR>
> .
>

2017-02-05 18:20 UTC, permcody requested changes

2017-02-05 18:20 UTC, permcody commented on scripts/update_and_rebuild_libmesh.sh
> +#  make -j ${JOBS:-$LIBMESH_JOBS} && \
I'm going to guess the problem with the reason this PR didn't work has nothing at all to do with CIVET...

2017-02-05 18:21 UTC, friedmud commented on scripts/update_and_rebuild_libmesh.sh
> +#  make -j ${JOBS:-$LIBMESH_JOBS} && \
lol!

Whoops - that slipped in there. 😆

2017-02-05 18:28 UTC, moosebuild commented on libmesh
> +Subproject commit cc49a536e66ef481f6229805656987cb87db6465
**Caution!** This contains a submodule update

2017-02-07 16:21 UTC, permcody commented
![image](https://cloud.githubusercontent.com/assets/3036960/22700141/d28bf358-ed16-11e6-8fbe-805d9f12a4c2.png)

2017-02-07 16:25 UTC, permcody commented
![image](https://cloud.githubusercontent.com/assets/3036960/22700271/50418628-ed17-11e6-82d9-cba994433724.png)

2017-02-15 17:00 UTC, permcody commented
@friedmud - Do you want us to take this over? I'd like to get it in.

2017-02-28 20:38 UTC, snschune commented
How operational is this patch?

2017-02-28 20:53 UTC, permcody commented
I rebased it in #8557. It seems to work on some problems but it also fails the very simple test checked in here on Linux, not sure why.

2017-03-01 15:37 UTC, snschune commented
I was testing this patch on a triangular mesh created with @YaqiWang mesh generator in instant. 
It fails with messages as below on multiple (or all) processors. I can share the input off-thread.  

```
*** ERROR ***
there are 210 side(s) uncovered by local side sets
```

2017-03-01 21:39 UTC, permcody commented
Oh! mesh modifiers are going to need a complete overhaul. Many of them
aren't going to work at all in their current form.

Longer term, we may be able to apply mesh modifiers in the checkpoint
splitter if it's incorporated into MOOSE. Ideally we'd run all modifiers
before splitting the mesh. Have you tried running --mesh-only first then
running the splitter?

On Wed, Mar 1, 2017 at 10:37 AM Sebastian Schunert <notifications@github.com>
wrote:

> I was testing this patch on a triangular mesh created with @YaqiWang
> <https://github.com/YaqiWang> mesh generator in instant.
> It fails with messages as below on multiple (or all) processors. I can
> share the input off-thread.
>
> *** ERROR ***
> there are 210 side(s) uncovered by local side sets
>
> —
> You are receiving this because you were mentioned.
>
>
> Reply to this email directly, view it on GitHub
> <https://github.com/idaholab/moose/pull/8472#issuecomment-283374464>, or mute
> the thread
> <https://github.com/notifications/unsubscribe-auth/AC5XIMdatSrpwYUyXxHgIhvmBX2Hjv5fks5rhZCvgaJpZM4L27vR>
> .
>

2017-03-01 22:18 UTC, snschune commented
I am planning to use mesh modifiers to extrude this mesh, but I would do it _before_ in a `--mesh-only` step and then split. 

In this case, I am using a 2D triangular mesh and I do not apply any mesh modifiers.

2017-03-01 22:21 UTC, permcody commented
Then I guess this thing is still pretty broken!

On Wed, Mar 1, 2017 at 5:18 PM Sebastian Schunert <notifications@github.com>
wrote:

> I am planning to use mesh modifiers to extrude this mesh, but I would do
> it *before* in a --mesh-only step and then split.
>
> In this case, I am using a 2D triangular mesh and I do not apply any mesh
> modifiers.
>
> —
> You are receiving this because you were mentioned.
>
>
> Reply to this email directly, view it on GitHub
> <https://github.com/idaholab/moose/pull/8472#issuecomment-283489397>, or mute
> the thread
> <https://github.com/notifications/unsubscribe-auth/AC5XII6IFU9moZFKxHGzqBeGfvKYOwobks5rhe6ogaJpZM4L27vR>
> .
>

2017-03-01 22:22 UTC, snschune commented
@permcody  I'm curious, why do you suspect I was using mesh modifiers? Maybe I am missing something here.

2017-03-01 22:45 UTC, permcody commented
I just assumed.
On Wed, Mar 1, 2017 at 5:22 PM Sebastian Schunert <notifications@github.com>
wrote:

> @permcody <https://github.com/permcody> I'm curious, why do you suspect I
> was using mesh modifiers? Maybe I am missing something here.
>
> —
> You are receiving this because you were mentioned.
>
>
> Reply to this email directly, view it on GitHub
> <https://github.com/idaholab/moose/pull/8472#issuecomment-283490328>, or mute
> the thread
> <https://github.com/notifications/unsubscribe-auth/AC5XIPwTm3i4eNatL_Z3zR3rVXd7pucmks5rhe-UgaJpZM4L27vR>
> .
>

2017-03-10 00:15 UTC, snschune commented
Does anyone has a compiled version of this, maybe @friedmud or @permcody? 
I tested this on another problem and failed with the same error message. I am wondering
if I set it up correctly. I'd provide the input files off-list.

2017-03-10 00:23 UTC, permcody commented
Fails for me too. Something is wrong with it.
On Thu, Mar 9, 2017 at 5:15 PM Sebastian Schunert <notifications@github.com>
wrote:

> Does anyone has a compiled version of this, maybe @friedmud
> <https://github.com/friedmud> or @permcody <https://github.com/permcody>?
> I tested this on another problem and failed with the same error message. I
> am wondering
> if I set it up correctly. I'd provide the input files off-list.
>
> —
> You are receiving this because you were mentioned.
>
>
> Reply to this email directly, view it on GitHub
> <https://github.com/idaholab/moose/pull/8472#issuecomment-285529046>, or mute
> the thread
> <https://github.com/notifications/unsubscribe-auth/AC5XIAza8HFgoWcVqf47qGIjjPaRMpWWks5rkJY_gaJpZM4L27vR>
> .
>

2017-03-10 05:49 UTC, YaqiWang commented
This error message is from an internal Rattlesnake sanity check. Is it possible that the ghost elements are not set up properly causing the checker to think the processor interface is boundary but no side sets covering it?

2017-03-10 13:20 UTC, snschune commented
That is the error message I encounter, but I am not sure @permcody encounters the same problem. I've never provided him with my inputs so I assume @permcody ran the tests included in this PR with
MOOSE.

2017-03-16 16:44 UTC, snschune commented
@friedmud @permcody  Is this currently on anyone's radar? It's sort of a biggie for us.

2017-03-16 16:47 UTC, permcody commented
Not on my radar. Roy may get to it before I do. I have no idea what's going
on with Derek these days

On Thu, Mar 16, 2017 at 10:44 AM Sebastian Schunert <
notifications@github.com> wrote:

> @friedmud <https://github.com/friedmud> @permcody
> <https://github.com/permcody> Is this currently on anyone's radar? It's
> sort of a biggie for us.
>
> —
> You are receiving this because you were mentioned.
>
>
> Reply to this email directly, view it on GitHub
> <https://github.com/idaholab/moose/pull/8472#issuecomment-287118384>, or mute
> the thread
> <https://github.com/notifications/unsubscribe-auth/AC5XII4zZeW_Hx3zLN4d17Q9K8LwOgkaks5rmWcIgaJpZM4L27vR>
> .
>

2017-03-16 16:59 UTC, snschune commented
Bummer. If I can help in any way, let me know. Any estimate of how long @roystgnr @friedmud or @permcody would need to get to this?

2017-03-16 21:41 UTC, friedmud commented
I'm just currently swamped with stuff here.  I don't have any plans to get
to this for the next week at least.

On Thu, Mar 16, 2017 at 12:59 PM Sebastian Schunert <
notifications@github.com> wrote:

> Bummer. If I can help in any way, let me know. Any estimate of how long
> @roystgnr <https://github.com/roystgnr> @friedmud
> <https://github.com/friedmud> or @permcody <https://github.com/permcody>
> would need to get to this?
>
> —
> You are receiving this because you were mentioned.
>
>
> Reply to this email directly, view it on GitHub
> <https://github.com/idaholab/moose/pull/8472#issuecomment-287122868>, or mute
> the thread
> <https://github.com/notifications/unsubscribe-auth/AA1JMbvFMgrzpYp8mG9lRRp-GmGAVTfbks5rmWpggaJpZM4L27vR>
> .
>

2017-04-03 03:54 UTC, roystgnr commented
Someone want to fill me in on the desired semantics here?  If https://github.com/libMesh/libmesh/pull/1291 is working the way it's intended, then CheckpointIO should be able to operate more seamlessly now.  You'll still want to set parallel() etc. when writing a CheckpointIO file, but when reading one in it'll autodetect whether the file is serial or parallel and will do reads (and if necessary, broadcasts) accordingly.

2017-04-03 14:49 UTC, permcody commented
Our ideal usage would be to switch back and forth between different formats and modes with minimal changes to our input files. This PR added 

1. Run with a serial exodus input mesh in replicated mode - DONE
2. Run with a serial exodus input mesh in distributed mode - DONE
3. Run with a distributed nemesis input mesh in distributed mode - CHANGING SYNTAX
4. Run with a serial checkpoint mesh in replicated mode - NOT DONE
5. Run with a serial checkpoint mesh in distributed mode - NOT DONE
6. Run with a distributed checkpoint mesh in distributed mode - NOT DONE

I believe this PR does some of that if not all of that (if it was working properly). When we were in College Station we talked about having a Boolean in our Mesh block that tells MOOSE whether or not the mesh is "pre-split". When that option is on, we look for file names with the per processor suffix. When it's not on, we don't so it makes it easy to switch between input serial and distributed meshes. Likewise, we already have a `distribution` option which tells the framework which mode to run in.  

I'm not sure if I've fully answered your question. This PR should be a good start as I think the semantics are already in here. We just need to get it working.

2017-04-12 01:33 UTC, friedmud commented
@permcody has this right.

2017-06-21 19:48 UTC, permcody commented
Superseded by #8557.

2017-06-21 19:48 UTC, closed without merging