Use less memory for stateful material storage
idaholab/moose pull request #8477
Opened 2017-02-06 18:17 UTC by permcody

I'm dropping TBB concurrent map because it seems to use way, way more memory than it should. We are going to just use std::unordered_map until somebody comes up with something better.

2017-02-06 19:29 UTC, andrsd requested changes

2017-02-06 19:29 UTC, andrsd commented on framework/include/utils/HashMap.h
>  class HashMap : public std::unordered_map<Key, T> /*, Hash, Pred, Allocator >*/
Those `/*, Hash, Pred, Allocator >*/` comments can probably go away as well...

2017-02-06 19:29 UTC, andrsd commented on test/src/materials/StatefulTest.C
> +    mooseError("Number of prop_names must match the number of prop_values for a GenericConstantMaterial!");
How is this related to `GenericConstantMaterial`?

2017-02-06 19:29 UTC, andrsd commented on test/tests/materials/stateful_prop/many_stateful_props.i
> +  # Preconditioned JFNK (default)
We need to stop copying this comment around...

2017-02-06 19:29 UTC, andrsd commented on test/tests/materials/stateful_prop/many_stateful_props.i
> +# map which saves us 6x to 8x on memory.
Maybe a better place for this performance discussion would be the actual commit message that changed from TBB map to unordered map.

2017-02-06 21:36 UTC, rwcarlsen commented
I'd prefer that we just manually change the use of ``HashMap`` to ``std::unordered_map`` for the stateful property handling rather than a typedef which just adds indirection.

2017-02-07 14:58 UTC, andrsd commented
True, `HashMap` can actually go away. It was created to have different thread-safe hash maps for different threading models.

2017-02-07 15:24 UTC, permcody commented
Well it does serve one important purpose. It currently has the thread lock in it. If we remove this class we'll have to carefully find all threaded access to the map and put the lock in each of those locations. I think we may only have three (ComputeMaterialsThread, prolongStatefulProps, restrictStatefulProps) but it'll take some time to go through and verify all of that. Plus it'll be error prone as people work on the code and accidentally add insertions in threaded regions. 

Still, it may be the right solution but not for this PR. I'll address the other comments and we'll get this in as-is #8487

2017-02-07 21:45 UTC, permcody commented on test/tests/materials/stateful_prop/many_stateful_props.i
> +# map which saves us 6x to 8x on memory.
Maybe, However I think our test files should be much more descriptive of what they are testing. Users/Developers should be able to access this information without diving into commit messages.

2017-02-08 14:34 UTC, andrsd approved these changes

2017-02-08 14:34 UTC, merged