Add checks for extra variables in NS module
idaholab/moose pull request #8491
Opened 2017-02-07 17:29 UTC by Chuban

A new function, `isNSVariable()`, has been added to `NSKernel.C` and `NSIntegratedBC.C`.  This checks that a given variable belongs to the NS module.  It is called before `mapVarNumber()` in the off diagonal jacobian calculations for kernels and boundary conditions.  If the variable does not belong to the NS module, a 0 is returned for insertion into the jacobian.  Otherwise, the module's behavior is unchanged.  This closes #8475.

This branch has passed all Moose and NS module tests along with stylistic checks in `./scripts/moose-format.sh`.

2017-02-07 20:26 UTC, andrsd requested changes

2017-02-07 20:26 UTC, andrsd commented on modules/navier_stokes/src/bcs/NSEnergyInviscidSpecifiedBC.C
> +
I'd rather see this:
```
if (isNSVariable(jvar))
  return this->computeJacobianHelper(mapVarNumber(jvar));
else
  return 0.0;
```

And everywhere else...

2017-02-07 20:26 UTC, andrsd commented on modules/navier_stokes/src/bcs/NSIntegratedBC.C
> +  }
No `{`, `}` for single line statements...

2017-02-07 20:26 UTC, andrsd commented on modules/navier_stokes/src/kernels/NSKernel.C
> +  }
No `{`, `}` for single line statements...

2017-02-08 19:32 UTC, andrsd approved these changes

2017-02-08 22:15 UTC, andrsd commented on modules/navier_stokes/src/kernels/NSMomentumInviscidFluxWithGradP.C
> +    }
it needs:
```
else
  return 0;
```

that's what the test system complains about...

2017-02-09 16:10 UTC, Chuban commented
Am I correct in thinking that the test system is complaining about not having a return statement for the default case in `NSEnergyViscousFlux::computeQpOffDiagJacobian`?

2017-02-09 16:29 UTC, andrsd commented
> Am I correct in thinking that the test system is complaining about not having a return statement for the default case in NSEnergyViscousFlux::computeQpOffDiagJacobian?

Yes.

2017-02-09 22:06 UTC, moosebuild commented
Job `Precheck:linux-gnu` on ec3308d : invalidated by @rwcarlsen

2017-02-10 15:09 UTC, merged