Add TestHarness testers from chigger
idaholab/moose pull request #8530
Opened 2017-02-13 20:41 UTC by brianmoose

refs #7451 
These are copied over from `chigger/scripts/TestHarness/testers`

This also adds a `run_tests` to the `python` directory to allow to run unit tests.

The `RunPythonApp` and `RunPythonException` are not named all that great since they mostly don't have anything specific to python in them. The exception would be the `unittest` parameter which looks for a specific string in the output. @aeslaughter Is there a reason why we are checking the output and not the return code for unittests?

2017-02-13 21:10 UTC, aeslaughter commented
> Is there a reason why we are checking the output and not the return code for unittests?

I don't know what I am doing.

2017-02-13 21:23 UTC, brianmoose commented
Well, I think I originally put it in there...I vaguely recall some issue...otherwise we would not even need to put `unittest=True` in the `tests` file.

2017-02-13 23:49 UTC, permcody requested changes
Maybe I'm missing something but there's a lot of duplicate code here with the existing Tester structure. I think we can rethink this whole thing a bit. Let's chat about it tomorrow and see if we can consolidate.

2017-02-13 23:49 UTC, permcody commented on python/TestHarness/testers/ImageDiff.py
> +        if self.specs['delete_output_before_running'] == True:
We've abstracted this method into the base class. See the implementations in ExoDiff and CSVDiff classes.

2017-02-13 23:49 UTC, permcody commented on python/TestHarness/testers/RunPythonApp.py
> +        return (reason, output)
This is going to conflict with @milljm's PR...

2017-02-13 23:49 UTC, permcody commented on python/TestHarness/testers/RunPythonApp.py
> +                reason = 'NO EXPECTED OUT'
This looks like a small subset of the code in Tester.py. Maybe we can factor this out? I realize that it's slightly different but on the other hand a process is a process. Let's take a look at this.

2017-02-13 23:49 UTC, permcody commented on python/TestHarness/testers/RunPythonApp.py
> +    def checkOutputForPattern(self, output, re_pattern):
This already exists

2017-02-13 23:49 UTC, permcody commented on python/TestHarness/testers/RunPythonApp.py
> +    def checkOutputForLiteral(self, output, literal):
Lots of code duplication, this method exists

2017-02-14 01:31 UTC, aeslaughter commented
@permcody I know there is a lot of duplicate code, but the location of the code is too far up the process chain for running MOOSE applications and I wasn't interested in re-factoring the test harness classes. However, we could maybe make some stand-alone functions for this stuff.

2017-02-14 18:24 UTC, permcody commented
Assigning to @milljm

2017-02-21 22:17 UTC, permcody commented
Superseded by #8591.

2017-02-21 22:17 UTC, closed without merging