Add top level common parameters
idaholab/moose pull request #8558
Opened 2017-02-15 23:40 UTC by dschwen

Add the ability to specify common parameters for subblocks in the TensorMechanics Master action.

Refs #7987

2017-02-17 17:06 UTC, bwspenc reviewed
I really like what this does to the input syntax, and I'm generally happy with this.  I'm still just struggling a little bit to see the purpose of having both `CommonTensorMechanicsAction` and `TensorMechanicsActionBase`.  If we could get by with just having one of them, I think it would make the code easier to understand.

2017-02-17 17:06 UTC, bwspenc commented on modules/tensor_mechanics/src/base/TensorMechanicsApp.C
> +  syntax.registerActionSyntax("CommonTensorMechanicsAction", "Modules/TensorMechanics/Master");
Couldn't you just register `TensorMechanicsActionBase` here and get rid of `CommonTensorMechanicsAction`?

2017-02-17 19:18 UTC, dschwen commented
I don't think we can do this. And if we figure out how to do it it will
make the code even more complicated. Let's talk on Monday.

On Fri, Feb 17, 2017, 10:06 AM Ben Spencer <notifications@github.com> wrote:

> *@bwspenc* commented on this pull request.
>
> I really like what this does to the input syntax, and I'm generally happy
> with this. I'm still just struggling a little bit to see the purpose of
> having both CommonTensorMechanicsAction and TensorMechanicsActionBase. If
> we could get by with just having one of them, I think it would make the
> code easier to understand.
> ------------------------------
>
> In modules/tensor_mechanics/src/base/TensorMechanicsApp.C
> <https://github.com/idaholab/moose/pull/8558#discussion_r101800739>:
>
> > @@ -380,6 +381,7 @@ TensorMechanicsApp::associateSyntax(Syntax & syntax, ActionFactory & action_fact
>    syntax.registerActionSyntax("PressureAction", "BCs/Pressure/*");
>
>    syntax.registerActionSyntax("GeneralizedPlaneStrainAction", "Modules/TensorMechanics/GeneralizedPlaneStrain/*");
> +  syntax.registerActionSyntax("CommonTensorMechanicsAction", "Modules/TensorMechanics/Master");
>
> Couldn't you just register TensorMechanicsActionBase here and get rid of
> CommonTensorMechanicsAction?
>
> —
> You are receiving this because you authored the thread.
>
>
> Reply to this email directly, view it on GitHub
> <https://github.com/idaholab/moose/pull/8558#pullrequestreview-22543213>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AAMWPqO9rVzxfiJO7zD11dbX6oYaEOcPks5rddN7gaJpZM4MCZVs>
> .
>

2017-02-17 19:20 UTC, dschwen commented on modules/tensor_mechanics/src/base/TensorMechanicsApp.C
> +  syntax.registerActionSyntax("CommonTensorMechanicsAction", "Modules/TensorMechanics/Master");
I don't know if the action fetching works if I do that! The TM action will also dynamic cast to tmbase.

2017-02-20 19:11 UTC, permcody requested changes
This PR looks OK but there's no new documentation here for this important capability. I'd suggest putting in detailed comments in the test for a start but also documenting how this works in the higher level documentation too.

2017-02-20 19:11 UTC, permcody commented on modules/tensor_mechanics/src/base/TensorMechanicsApp.C
> +  syntax.registerActionSyntax("CommonTensorMechanicsAction", "Modules/TensorMechanics/Master");
Yeah that doesn't work. The Action system needs to know what kind of instance to build when encountering a piece of syntax. Having the Base registered means the Action system would try to build the base type directly.

2017-03-07 16:46 UTC, moosebuild commented
Job `App tests:linux-gnu` on 4a6f530 : canceled by @dschwen

2017-03-07 16:46 UTC, moosebuild commented
Job `External App tests:linux-gnu-external-apps` on 4a6f530 : canceled by @dschwen

2017-03-07 16:46 UTC, moosebuild commented
Job `Pthreads test:linux-gnu` on 4a6f530 : canceled by @dschwen

2017-03-07 16:46 UTC, moosebuild commented
Job `TBB test:linux-gnu` on 4a6f530 : canceled by @dschwen

2017-03-07 16:46 UTC, moosebuild commented
Job `Test intel:linux-intel` on 4a6f530 : canceled by @dschwen

2017-03-07 18:39 UTC, moosebuild commented
Job `Moose Documentation:linux-clang` on ee2eaea wanted to post the following:

View the site at http://mooseframework.org/docs/PRs/8558/site

2017-03-07 21:00 UTC, bwspenc approved these changes

2017-03-07 21:15 UTC, bwspenc commented
@permcody he added some documentation. I'm good with the code as it is now.  If you're good with it, can you accept those changes?

2017-03-07 21:26 UTC, permcody approved these changes

2017-03-07 21:26 UTC, merged