Refactor Chigger tests
idaholab/moose pull request #8569
Opened 2017-02-16 22:46 UTC by milljm

Refactor a few things. Use the status bucket. Use the enumerated statuses instead of literals.

Refs #8530

2017-02-16 23:05 UTC, brianmoose requested changes

2017-02-16 23:05 UTC, brianmoose commented on python/TestHarness/testers/RunPythonApp.py
> +from util import *
`import util`

2017-02-16 23:05 UTC, brianmoose commented on python/TestHarness/testers/RunException.py
> +from util import *
`import util`

2017-02-16 23:05 UTC, brianmoose commented on python/TestHarness/testers/CheckFiles.py
> +from util import *
It is usually better to do `import util` then use `util.checkOutputForPattern`

2017-02-16 23:05 UTC, brianmoose commented on python/TestHarness/testers/ImageDiff.py
> +        if self.specs['delete_output_before_running'] == True:
This logic also exists in the differ testers

2017-02-16 23:05 UTC, brianmoose commented on python/TestHarness/testers/RunApp.py
> +from util import *
`import util`

2017-02-20 19:59 UTC, brianmoose requested changes

2017-02-20 19:59 UTC, brianmoose commented on python/TestHarness/testers/ImageDiff.py
> +            util.deleteFilesAndFolders(self.specs['test_dir'], self.specs['imagediff'], self.specs['delete_output_folders'])
`delete_output_folders` doesn't seem to be defined

2017-02-20 19:59 UTC, brianmoose commented on python/TestHarness/testers/AnalyzeJacobian.py
>  import re, os, sys
`re` isn't used

2017-02-20 19:59 UTC, brianmoose commented on python/TestHarness/testers/CSVDiff.py
>  import os
`os` isn't used

2017-02-20 19:59 UTC, brianmoose commented on python/TestHarness/testers/RunPythonApp.py
> +import os, re
`re` isn't used

2017-02-20 19:59 UTC, brianmoose commented on python/TestHarness/testers/RunPythonException.py
> +            self.setStatus(self.success_message, self.buck_success)
`buck_success` doesn't seem to be defined.

2017-02-20 19:59 UTC, brianmoose commented on python/TestHarness/testers/Tester.py
>  from InputParameters import InputParameters
Not used

2017-02-21 19:13 UTC, permcody commented
Migrating to #8591

2017-02-21 19:13 UTC, closed without merging