don't use epsilon for range checked input params
idaholab/moose pull request #8612
Opened 2017-02-22 23:05 UTC by rwcarlsen

fixes #8586.

2017-02-23 00:00 UTC, permcody commented
Cool! Will you add a few unit tests for this? We have unit tests for the InputParameters object and you could put in a several different expressions including the one in the original email thread.

2017-02-23 14:49 UTC, permcody commented
I thought a bit about your new directory structure you are starting for the test in the PR and don't think it's the direction we want to go. Here's why

1. First we don't have any history doing this so the first ~8500 tickets don't have any linkage to tests by number in the repository. This makes this new structure very inconsistent with what we have today.
2. There's not a good way to navigate from the repository number back to Github. If you are on the command line, you have to type the issue number into a web browser. If you are online browsing, you can't click on the directory and link to the ticket, you have to search for it. So there's really not good linkage back from the directory structure.
3. There's no meaning in the directory name. If we do this for any length of time, we'll have dozens or perhaps hundreds of directories with numbers that have no meaning. 

From a quality perspective, we need to move towards the required documents and structure around those instead. MOOSE will have the following SRS (Requirements), SDD (Design), RTM (Testing/Traceability), and STP (Test Plan). Issues don't fit neatly into this structure. They represent bugs, feature requests that can turn into requirements and feature enhancements that can just be changes or just robustness improvements to existing requirements.

You may have encountered tests that reference a requirement number. That's more the direction I want to take but it's not perfect either. We still have to incorporate design linkage into the test as well. In any case linking to the raw ticket isn't the right solution. For this PR, I might suggest that you just remove the new test case altogether and handle this feature completely with unit testing.

2017-02-23 14:51 UTC, permcody requested changes

2017-02-23 14:51 UTC, permcody commented on test/tests/issues/i8586/test.i
> +# This tests for the bug https://github.com/idaholab/moose/issues/8586.
Linking to the test here is fine, I just don't like the directory name

2017-02-23 14:51 UTC, permcody commented on framework/include/utils/InputParameters.h
> +  fp.setEpsilon(0);
I think you really need a comment here. It's very unintuitive why this line of code is here. Anyone else looking at this might think it's unecessary.

2017-02-23 14:54 UTC, dschwen approved these changes
Besides Cody's comments this looks good.

2017-02-23 15:15 UTC, rwcarlsen commented
@permcody - to your points:


> 1. First we don't have any history doing this so the first ~8500 tickets don't have any linkage to tests by number in the repository. This makes this new structure very inconsistent with what we have today.

Good point.

> 2. There's not a good way to navigate from the repository number back to Github. If you are on the command line, you have to type the issue number into a web browser.

This is really easy.  I type in issue url's not infrequently.

> If you are online browsing, you can't click on the directory and link to the ticket, you have to search for it. So there's really not good linkage back from the directory structure.

Just type over the [whatever] your url bar that is already at the moose repo site ( ``github.com/idaholab/moose/[whatever]``) with ``issue/8586``.  Plus the full url inside the test file.

> 3. There's no meaning in the directory name. If we do this for any length of time, we'll have dozens or perhaps hundreds of directories with numbers that have no meaning.

True.  But the directory/file names usually contain a negligible amount of meaning about the original problem that prompted the test in the first place.  The mailing list discussion and issue comments, etc. have the necessary context.  Certainly not all issues' tests belong in this sort of place.  It wasn't made clear at all here, but I was intending the ``issues`` subdirectory to only be for fixed bugs.  So things like the auto-stateful property promotion tests would not belong there.  And certainly all the basic material functionality tests belong better together in a materials directory.  But I think something like this for fixed bugs could be helpful.  But I don't feel strongly enough about it if others are opposed - just thought it would be worth offering the idea.

2017-02-23 15:22 UTC, permcody commented
I value your new ideas and I take your point about this structure being strictly for bug fixes. However, even that's kind of embarrassing over time as this directory grows... 

My biggest opposition to this is that I don't want to have competing organization going on, even if this has a clear role (i.e. bug fixes only). I'm all for reorganizing tests as I think the current structure has some good and some bad parts in it. Let's table this particular restructuring idea for right now and address it once we start developing our design and testing matrix documents. We might decide on a whole new structure at that time.

2017-02-23 15:35 UTC, rwcarlsen commented
I don't think it is embarrasing - it is honest, neat, and useful.  Holding for a bigger discussion about testing organization in general sounds good to me.

2017-02-23 16:09 UTC, andrsd commented
I think tests should be testing features not issues that were possibly fixed and therefore do not exist any more...

2017-02-23 16:20 UTC, rwcarlsen commented
Are you suggesting we don't have tests for fixed bugs or are you suggesting
we don't treat them the same way as "feature" tests?  No tests for bugs is
a very bad idea.  Regressions (of bugs) are very common in software
development.  Cody was surprised that cyclic stateful material properties
became broken over the last year or so after he had already fixed it once.

On Thu, Feb 23, 2017 at 9:09 AM, David Andrs <notifications@github.com>
wrote:

> I think tests should be testing features not issues that were possibly
> fixed and therefore do not exist any more...
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/idaholab/moose/pull/8612#issuecomment-282037380>, or mute
> the thread
> <https://github.com/notifications/unsubscribe-auth/ABSeSlf1IPOKNfxVfAaHubxuGW4mZxdxks5rfa9EgaJpZM4MJUEi>
> .
>

2017-02-23 16:28 UTC, andrsd commented
I am suggesting to use different terminology. If I see a test that is testing issue XYZ, that suggests the issue is in the code even though it was fixed.  Obviously you want to test that the fix works, but you are testing a feature then...

2017-02-23 16:33 UTC, permcody commented
I agree with David here. if you want to get down to a pure Software Engineering aspect a bug happens because of an incomplete design, or incorrect implementation of a complete design. When you fix a bug you are adding to an incomplete implementation or correcting an incorrect implementation. it then becomes a feature. 

Now what's up for debate is whether or not every tiny little bug fix becomes a tracked feature or not (i.e. edits to the SRS and SDD). We could go that direction, and in that case the "fix" would be given a new feature number from the SRS and we'd use that in the test description or organization.

2017-02-23 19:51 UTC, rwcarlsen commented
The epsilon seems to be globalish and requires being reset back to its original value after we are done doing the range checked parameters :-/

2017-02-23 20:43 UTC, rwcarlsen commented
ping ready.

2017-02-24 15:37 UTC, permcody commented
I really don't like this proposed directory name at all. Again, We are going to be working on requirements to design to testing traceability soon. That's the proper way to test each feature. As bugs are fixed, we should be updating the design documents and providing a traceable test for the improved design. I'm not interested in tracking tests for bug fixes.

2017-02-24 16:20 UTC, rwcarlsen commented
I renamed the directory here just for good measure, but it really isn't
part of this pull request - it came in on an earlier one.  If you want, I
can find a new home for the test in the directory here, or I can roll back
the directory rename and resolve it in a different PR.  Whatever you prefer.

On Fri, Feb 24, 2017 at 8:37 AM, Cody Permann <notifications@github.com>
wrote:

> I really don't like this proposed directory name at all. Again, We are
> going to be working on requirements to design to testing traceability soon.
> That's the proper way to test each feature. As bugs are fixed, we should be
> updating the design documents and providing a traceable test for the
> improved design. I'm not interested in tracking tests for bug fixes.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/idaholab/moose/pull/8612#issuecomment-282321742>, or mute
> the thread
> <https://github.com/notifications/unsubscribe-auth/ABSeStlZVCXrddcAidsAhFp-sHhTIMFgks5rfvk1gaJpZM4MJUEi>
> .
>

2017-02-24 17:58 UTC, permcody commented
Oh I see... Leave it for now. Let's just not continue this pattern moving forward.
Thanks

2017-02-24 17:58 UTC, permcody approved these changes

2017-02-24 17:58 UTC, merged