Variable moduli for elasticity tensor
idaholab/moose pull request #8613
Opened 2017-02-22 23:25 UTC by bwspenc

This implements a material that computes elastic moduli that depend on other materials.  I'm following this approach instead of my previous one that used functions and was specific to temperatures per feedback from @dschwen.

Because we have piecewise linear functions that describe the dependence of these moduli on temperature, I also implemented a general Material that incorporates a LinearInterpolation object to define the moduli within the Material, rather than using a Function.

@WilkAndy This is the code we discussed yesterday.

2017-02-22 23:49 UTC, bwspenc commented on framework/src/materials/PiecewiseLinearInterpolationMaterial.C
> +/****************************************************************/
Any thoughts on the name for this?  @permcody? There are a couple of other materials of this nature in this directory with names that start with 'Generic', but I didn't include that to keep the name shorter.

2017-02-23 00:04 UTC, WilkAndy commented
Thanks for this, @bwspenc .   I hope we can do some heterogeneous rock modelling with it.

2017-02-23 00:07 UTC, moosebuild commented
Job `Moose Documentation:linux-clang` on 2950829 wanted to post the following:

View the site at http://mooseframework.org/docs/PRs/8613/site

2017-02-23 14:40 UTC, permcody commented on framework/src/materials/PiecewiseLinearInterpolationMaterial.C
> +/****************************************************************/
This is fine. If others are in favor of dropping generic from the existing similar objects. I'm also fine with that.

2017-03-07 21:36 UTC, permcody commented
Ping @dschwen

2017-03-07 21:43 UTC, dschwen requested changes
Looks good otherwise

2017-03-07 21:43 UTC, dschwen commented on framework/include/materials/PiecewiseLinearInterpolationMaterial.h
> +  // Value of the coupled variable to be used as the abscissa in the piecewise linear interpolation
make both `///`

2017-03-07 21:43 UTC, dschwen commented on framework/src/materials/PiecewiseLinearInterpolationMaterial.C
> +    for (unsigned int i=0; i<xy_size/2; ++i)
operator spacing

2017-03-07 22:05 UTC, dschwen commented on modules/combined/tests/thermal_elastic/thermal_elastic.i
> +    block = '1 2 3 4 5 6 7'
if you omit the block parameter no restriction is applied (which is what the `all` name seems to indicate you want)

2017-03-08 00:30 UTC, bwspenc commented
@dschwen I addressed the issues you pointed out.

2017-03-08 01:06 UTC, dschwen approved these changes

2017-03-08 01:38 UTC, moosebuild commented
Job `Moose Documentation:linux-clang` on bdd11e9 wanted to post the following:

View the site at http://mooseframework.org/docs/PRs/8613/site

2017-03-08 18:26 UTC, bwspenc commented
@permcody The documentation build is failing for an unrelated reason (recent deprecation of StressDivergencePFFracTensors in another commit?).  Do we need that to build cleanly before we merge this, or has someone already addressed this problem?  Since @dschwen isn't available today, can you help me get this merged?

2017-03-08 18:31 UTC, permcody commented
As far as process goes, we do not require a clean build in order to merge. That's just too restrictive. All you *should* do is describe why you are merging with a broken build for auditing purposes.

2017-03-08 20:35 UTC, permcody commented
Only the Documentation target is breaking for unrelated reasons. Merging...

2017-03-08 20:35 UTC, merged