Volumetric material
idaholab/moose pull request #8617
Opened 2017-02-23 04:06 UTC by bwspenc

2017-02-23 04:27 UTC, moosebuild commented
Job `Moose Documentation:linux-clang` on c70903f wanted to post the following:

View the site at http://mooseframework.org/docs/PRs/8617/site

2017-02-23 05:33 UTC, dschwen requested changes

2017-02-23 05:33 UTC, dschwen commented on modules/tensor_mechanics/src/materials/ComputeEigenstrainBase.C
> +  Real volumetric_strain_comp = std::cbrt((volumetric_strain + 1.0)) - 1.0;
why the double parenthesis and why subtract 1 if you add on the next code line?

2017-02-23 05:33 UTC, dschwen commented on modules/tensor_mechanics/src/materials/ComputeVolumetricEigenstrain.C
> +    validateCoupling<Real>("vmn");
no quotes around `vmn`

2017-02-23 06:21 UTC, moosebuild commented
Job `Moose Documentation:linux-clang` on 8187d50 wanted to post the following:

View the site at http://mooseframework.org/docs/PRs/8617/site

2017-03-01 18:51 UTC, bwspenc commented
@dschwen I addressed all of your comments.  Could you please accept them if you're OK with them?  I can have someone else review this if needed.

2017-03-07 21:03 UTC, dschwen approved these changes

2017-03-07 21:41 UTC, moosebuild commented
Job `Moose Documentation:linux-clang` on 33cfa89 wanted to post the following:

View the site at http://mooseframework.org/docs/PRs/8617/site

2017-03-08 00:17 UTC, bwspenc commented
@dschwen I removed those underscores, so I think this is good to go.

2017-03-08 01:06 UTC, merged