Add memory usage diagnostic Postprocessor
idaholab/moose pull request #8676
Opened 2017-03-07 15:55 UTC by dschwen

Works in Linux and macOS. See demo graphs in the issue thread.

Closes #8619

2017-03-07 21:44 UTC, moosebuild commented
Job `Moose Documentation:linux-clang` on 70ac724 wanted to post the following:

View the site at http://mooseframework.org/docs/PRs/8676/site

2017-03-08 15:29 UTC, permcody requested changes

2017-03-08 15:29 UTC, permcody commented on framework/src/postprocessors/MemoryUsage.C
> +#undef RUSAGE_AVAILABLE
What's this little guy?

2017-03-08 15:29 UTC, permcody commented on framework/src/postprocessors/MemoryUsage.C
> +  std::array<unsigned long, 21> val;
What's the significance of this integer? Can we use a constant expression instead? Possibly below as well where you access the 20th item.

2017-03-08 15:29 UTC, permcody commented on framework/include/postprocessors/MemoryUsage.h
> +  enum class MemType {
bracket at the end of a line?

2017-03-08 15:29 UTC, permcody commented on framework/include/postprocessors/MemoryUsage.h
> +  enum class ValueType {
another bracket at the end of a line

2017-03-08 15:29 UTC, permcody commented on test/tests/postprocessors/memory_usage/print_memory_usage.i
> +  petsc_options_value = 'lu'
Do you want "lu" here? How did this not fail testing when we ran in parallel?

2017-03-10 15:31 UTC, dschwen commented on framework/src/postprocessors/MemoryUsage.C
> +  std::array<unsigned long, 21> val;
Yeah, that is the number of values I parse from the /proc file. I'll add constant to name this.

2017-03-10 15:42 UTC, dschwen commented on test/tests/postprocessors/memory_usage/print_memory_usage.i
> +  petsc_options_value = 'lu'
let me make this `asm lu`. I wanted something that actually affects memory use noticeably.

2017-03-10 18:20 UTC, moosebuild commented
Job `Moose Documentation:linux-clang` on d95759b wanted to post the following:

View the site at http://mooseframework.org/docs/PRs/8676/site

2017-03-10 22:11 UTC, permcody approved these changes

2017-03-10 22:11 UTC, merged

2017-03-13 13:14 UTC, brianmoose commented
Looks like this has a memory issue https://www.moosebuild.org/job/74312/

2017-03-13 13:15 UTC, permcody commented
Ironic that the memory tool has memory issues!
On Mon, Mar 13, 2017 at 7:14 AM brianmoose <notifications@github.com> wrote:

> Looks like this has a memory issue https://www.moosebuild.org/job/74312/
>
> —
> You are receiving this because you modified the open/close state.
>
>
> Reply to this email directly, view it on GitHub
> <https://github.com/idaholab/moose/pull/8676#issuecomment-286103129>, or mute
> the thread
> <https://github.com/notifications/unsubscribe-auth/AC5XIE-dFLsMdJ6IYTsHr2JO3CqlW5y6ks5rlUEcgaJpZM4MVqXj>
> .
>

2017-03-13 13:34 UTC, dschwen commented
It is not a memory issue, it is an uninitialized variable in output. I guess the postprocessor value is undefined in some cases. I will investigate.