New integer exponent pow
idaholab/moose pull request #8705
Opened 2017-03-11 15:12 UTC by dschwen

Closes #8704

2017-03-12 01:05 UTC, friedmud commented
Have you tested to see whether your `pow()` is faster than the template metaprogramming `pow()` in libMesh: https://github.com/libMesh/libmesh/blob/master/include/utils/utility.h#L194

2017-03-12 02:53 UTC, dschwen commented
Ha, of course not. It will be slower, but the template version needs the exponent specified at compile time and I need a version that takes the exponent at run time!

2017-03-12 03:17 UTC, friedmud commented
Gotcha - makes sense!

On Sat, Mar 11, 2017 at 9:53 PM Daniel Schwen <notifications@github.com>
wrote:

> Ha, of course not. It will be slower, but the template version needs the
> exponent specified at compile time and I need a version that takes the
> exponent at run time!
>
> —
> You are receiving this because you commented.
>
>
> Reply to this email directly, view it on GitHub
> <https://github.com/idaholab/moose/pull/8705#issuecomment-285917893>, or mute
> the thread
> <https://github.com/notifications/unsubscribe-auth/AA1JMerTbO4jlJ05NcLFOG03sldxentvks5rk14ogaJpZM4MaOpY>
> .
>

2017-03-13 15:43 UTC, andrsd requested changes
There are lots of operators missing spaces around them. I understand that it is a copy-n-paste thing and it does make the code a little bit more legible (somewhere), but the anticipated code formating script will undo that.

2017-03-13 15:43 UTC, andrsd commented on modules/phase_field/src/utils/MathUtils.C
> +Real poly1Log(Real x, Real tol, int deriv)
return type on a new line, and below as well...

2017-03-13 15:43 UTC, andrsd commented on modules/phase_field/src/utils/MathUtils.C
> +  Real c1 = 1.0/tol;
Spaces around `/` and below as well...

2017-03-13 15:43 UTC, andrsd commented on modules/phase_field/src/utils/MathUtils.C
> +  Real value=0.0;
Spaces around `=` and below in the other function(s).

2017-03-13 15:43 UTC, andrsd commented on modules/phase_field/src/utils/MathUtils.C
> +      value = c1*x + c2;
Spaces around `*` and below as well...

2017-03-13 15:43 UTC, andrsd commented on modules/phase_field/src/utils/MathUtils.C
> +    if (x<tol)
Spaces around `<`.

2017-03-13 15:43 UTC, andrsd commented on unit/include/MathUtilsTest.h
> +  CPPUNIT_TEST_SUITE( MathUtilsTest );
This is a copy-n-paste, but it is against the code standard. The code formatting script would remove those space...

The same thing in `.C`.

2017-03-13 15:54 UTC, dschwen commented
I'll run clang-format over this, but those are all old issue unrelated to this PR.

2017-03-13 16:22 UTC, andrsd approved these changes

2017-03-13 16:31 UTC, permcody commented
One overall comment: @rwcarlsen suggested that we move towards lower case namespace names. His argument is that it's more standard, i.e all the standard namespaces are lowercase and it helps to differentiate a namespace from a class name. I think it's actually a pretty good idea. This utilities is in MathUtils which is fine for the time being. Just starting the discussion.

2017-03-13 16:44 UTC, dschwen commented
Yeah, we might want to have that discussion in a separate ticket, but I am in favor of UpperCase namespace names. It differentiates MOOSE code from standard lib code, it makes them look like static class members. But I don't feel strongly about it.

2017-03-13 16:55 UTC, moosebuild commented
Job `Test intel:linux-intel` on 58014cf : invalidated by @dschwen

Unrelated failure

2017-03-13 19:31 UTC, merged