extend xfem to second-order elements. 2D: TRI6, QUAD8, QUAD9. 3D: TET…
idaholab/moose pull request #8711
Opened 2017-03-13 16:20 UTC by jiangwen84

Closes #8709

2017-03-13 18:57 UTC, jiangwen84 commented
@bwspenc Ben, could you review this PR? Thanks.

2017-03-14 00:09 UTC, bwspenc commented
@jiangwen84 Yes, I'll look at it.

2017-03-14 15:58 UTC, bwspenc requested changes
I've only had a chance to go through the 2D code so far, but I imagine most of my comments also apply to the 3D code.  It's close -- just needs a few things cleaned up.

2017-03-14 15:58 UTC, bwspenc commented on modules/xfem/src/efa/EFAElement2D.C
> +        else if (origin_to_point * normal < 1.0e-10 && origin2_to_point * normal2 < 1.0e-10)
This probably needs a comment to explain what's going on here.  Also, we should replace all of these usages of 1e-10 with a set tolerance variable.  It seems like we might already have one somewhere.

2017-03-16 17:42 UTC, bwspenc requested changes
Just a few minor changes.  Otherwise, I think it's ready to go.

2017-03-16 17:42 UTC, bwspenc commented on modules/xfem/src/efa/EFAElement3D.C
> +  setLocalCoordinates (_num_faces);
Remove extra space. Also, no need to pass _num_faces in since it's a member.

2017-03-16 17:42 UTC, bwspenc commented on modules/xfem/src/efa/EFAElement3D.C
> +      EFAError("In EFAelement3D the support TET element types are TET4 and TET10");
"support" -> "supported" (there are several cases of this to fix)

2017-03-16 17:42 UTC, bwspenc commented on modules/xfem/src/efa/EFAElement3D.C
> +          4/        :   16/             5/   |  / |
You've got an extra space that's messing up your otherwise awesome ASCII art!

2017-03-16 17:42 UTC, bwspenc commented on modules/xfem/src/efa/EFAElement3D.C
> +    _local_node_coor.push_back(EFAPoint(0.0, 0.0, 0.0));
Better to do something like this:
_local_node_coor.resize()
_local_node_coor[0] = EFAPoint(0.,0.,0.);
_local_node_coor[1] = EFAPoint(1.,0.,0.);
etc.

2017-03-16 17:42 UTC, bwspenc commented on modules/xfem/src/efa/EFAElement3D.C
> +    _local_node_coor.push_back(EFAPoint(0.0, 0.0, 0.0));
Also, you may as well only size these for the number of nodes you actually have (20 rather than 27 for HEX20).

2017-03-16 20:15 UTC, bwspenc approved these changes

2017-03-16 20:15 UTC, merged

2017-03-20 14:24 UTC, brianmoose commented
Looks like a memory leak was introduced in this PR: see https://www.moosebuild.org/job/76103/

2017-03-20 14:42 UTC, jiangwen84 commented
@brianmoose I will take care of it. Thanks.

2017-03-20 14:44 UTC, permcody commented
The FEM module could benefit from using smart pointers. There's a lot of raw memory handling in that module in general. You guys may want to look into that.

2017-03-20 17:46 UTC, bwspenc commented
Thanks, @jiangwen84.  @permcody I agree that there are a lot of opportunities here to use smart pointers to avoid issues like this.