Show file and line information in json output
idaholab/moose pull request #8732
Opened 2017-03-15 16:03 UTC by brianmoose

This stores file and line information in `Factory`, `ActionFactory`, and `Syntax` by modifying the various register macros.
To get the info for `Syntax` I added a couple of macros that can be used instead of the `syntax.registerActionSyntax()`.
I made it so that this is not required so that existing code should still work.
This is mainly for #7855 . @aeslaughter Does this work for you?

2017-03-16 14:12 UTC, aeslaughter reviewed
This should probably include a test of some sort.

2017-03-16 14:12 UTC, aeslaughter commented on framework/src/parser/Parser.C
> +    // _syntax.getLineInfo(act_info._action, act_info._task)));
Do you need these?

2017-03-16 14:14 UTC, aeslaughter commented
@permcody You should probably look at this before it is merged, it is messing with registration. I will also probably pull this down and use it a bit to see how it will work with MooseDocs.

2017-03-16 14:48 UTC, permcody requested changes
This looks OK to me. I think the use of maps with pairs as both keys and values is a little over-clever though. I'd prefer a slightly cleaner design.

2017-03-16 14:48 UTC, permcody commented on framework/include/actions/ActionFactory.h
> +      _name_to_line.insert(std::make_pair(std::make_pair(name, task), std::make_pair(file, line)));
Holy Dooley!

2017-03-16 14:48 UTC, permcody commented on framework/include/actions/ActionFactory.h
> +  std::map<std::pair<std::string, std::string>, std::pair<std::string, int>> _name_to_line;
At what point do you finally decide to build a small struct? 😆

2017-03-16 14:48 UTC, permcody commented on framework/src/parser/Parser.C
> +    const std::string act_name = act_names.first;
Yeah... Starting to think a little struct would be cleaner.

2017-03-16 14:48 UTC, permcody commented on framework/src/parser/Parser.C
> +      for (auto && t : tasks)
Universal reference: We looked at this when we first transitioned and decided we didn't like them for some reason. We've been just using normal references and marking the type as const when possible. I may have to revisit this and rethink why we didn't like them.

2017-03-16 14:48 UTC, permcody commented on framework/src/parser/Syntax.C
> +        return std::make_pair(std::get<2>(it->second), std::get<3>(it->second));
This syntax is new for me. Are you digging out part of the second pair here?

2017-03-16 14:48 UTC, permcody commented on framework/src/utils/JsonSyntaxTree.C
> +    auto & fi = json[action]["file_info"];
Bracket access on RHS: This is our infamous "accidental insertion" pattern for std::map. Is this access OK here if the json object is empty? If not can you add a MOOSE assert or something?

2017-03-16 14:48 UTC, permcody commented on framework/src/utils/JsonSyntaxTree.C
> +  auto & fi = json[action]["tasks"][task_name]["file_info"];
Again more brackets on RHS: Please verify that this is always OK.

2017-03-16 15:54 UTC, brianmoose commented on framework/src/utils/JsonSyntaxTree.C
> +    auto & fi = json[action]["file_info"];
Yes, this and the other one are intentional. This always puts a `file_info` in the json, it just might be `null` if there is no information. This allows the parser to not have to check if the key exists. But I can remove it if you like.

2017-03-16 15:57 UTC, brianmoose commented on framework/src/parser/Syntax.C
> +        return std::make_pair(std::get<2>(it->second), std::get<3>(it->second));
In `Syntax` we store a tuple, so these are just getting access to each value.
I think another structure would be good here too, especially given how this map is currently accessed.

2017-03-16 15:57 UTC, brianmoose commented on framework/src/parser/Parser.C
> +    const std::string act_name = act_names.first;
Agreed.

2017-03-20 20:53 UTC, brianmoose commented
@aeslaughter So I added a test and it revealed a difference in how gcc and clang process `__FILE__` in c++. Clang seems to place the full path name there while gcc places the filename as specified on the command line (ie just `src/parser/Parser.C`). Is that going to be a problem?

2017-03-20 22:09 UTC, brianmoose commented
Upon further investigation this doesn't seem to be a gcc vs clang thing. Probably a mac vs linux thing? Anyway, on mac with clang we get the full source file path. On linux, with gcc or clang, we get the path relative to where `make` was called.

2017-03-21 12:54 UTC, aeslaughter commented
I can deal with the relative path stuff.

2017-03-21 13:04 UTC, aeslaughter requested changes

2017-03-21 13:04 UTC, aeslaughter commented on framework/include/utils/FileLineInfo.h
> +  void addInfo(const std::string & key0, const std::string & file, int line);
Is it possible to use C++11 variadic arguments for the keys? Just to avoid having three definitions for the add and get methods.

2017-03-21 13:04 UTC, aeslaughter commented on framework/src/parser/Parser.C
> +                                           _syntax.getLineInfo(act_name, action, ""));
Should the addParameters just accept "act_info" from which it can do the extraction of the various parts?

2017-03-21 14:20 UTC, permcody commented on framework/include/utils/FileLineInfo.h
> +  void addInfo(const std::string & key0, const std::string & file, int line);
Even if that worked, it's probably not the best solution. You could use a tuple, or small struct instead though. However, I don't think having several overloads is bad. They have the same semantic meaning and the implementations are clean. Trying to condense them will likely make the code more difficult to understand.

2017-03-21 14:22 UTC, permcody commented on framework/src/parser/Parser.C
> +                                           _syntax.getLineInfo(act_name, action, ""));
Probably not, That would be spreading encapsulation from the Parser into InputParameters which is unrelated. This is a better design even if the call looks messier.

2017-03-24 15:03 UTC, brianmoose commented on framework/src/parser/Parser.C
> +                                           _syntax.getLineInfo(act_name, action, ""));
Also, there is another call to addParameters below this that doesn't use information from act_info.

2017-03-24 15:07 UTC, aeslaughter approved these changes

2017-03-24 15:07 UTC, aeslaughter commented
@permcody If you are happy with this, then you can merge away.

2017-03-24 15:34 UTC, permcody approved these changes

2017-03-24 15:35 UTC, merged