Convert elastic tests to use tensor mechanics
idaholab/moose pull request #8766
Opened 2017-03-20 22:24 UTC by hchen139

refs #8642

2017-04-03 20:35 UTC, dschwen requested changes

2017-04-03 20:35 UTC, dschwen commented on modules/combined/tests/check_error/contact_displacements.i
> +    displacements = 'disp_x disp_y disp_z'
This is already in GlobalParams!

2017-04-03 20:35 UTC, dschwen commented on modules/combined/tests/check_error/contact_displacements.i
> +    displacements = 'disp_x disp_y disp_z'
ditto - please remove all those

2017-04-03 20:35 UTC, dschwen commented on modules/combined/tests/check_error/contact_displacements_sm.i
> +    disp_y = disp_y
This is deprecated syntax now and will fail the tests. Pleas put a `displacements = ` into GlobalParams and remove the `disp_[xyz]` from Contact, Pressure, and Density everywhere.

2017-04-03 20:48 UTC, moosebuild commented
Job `modules debug:linux-gnu` on 7285f31 : invalidated by @dschwen

Re-run after recent MOOSE updates

2017-04-04 05:06 UTC, moosebuild commented
Job `Precheck:linux-gnu` on 4814ac0 wanted to post the following:

Your code requires style changes.
In the top level of your repository, you can run:

`git clang-format 604680ab15fce501b197616714454fb655cb3c16`

Alternatively, apply the patch found [here](http://mooseframework.org/docs/PRs/8766/style.patch).
You can directly apply the patch by running:

`curl -s http://mooseframework.org/docs/PRs/8766/style.patch | git apply -v`

2017-04-04 05:08 UTC, hchen139 commented on modules/combined/tests/check_error/contact_displacements.i
> +    displacements = 'disp_x disp_y disp_z'
The test will fail with "unable to find nearest node!" if put the displacements in the GlobalParams block.

2017-04-04 05:21 UTC, moosebuild commented
Job `Precheck:linux-gnu` on fad99f1 wanted to post the following:

Your code requires style changes.
In the top level of your repository, you can run:

`git clang-format 604680ab15fce501b197616714454fb655cb3c16`

Alternatively, apply the patch found [here](http://mooseframework.org/docs/PRs/8766/style.patch).
You can directly apply the patch by running:

`curl -s http://mooseframework.org/docs/PRs/8766/style.patch | git apply -v`

2017-04-04 05:24 UTC, moosebuild commented
Job `Precheck:linux-gnu` on d00fb9c wanted to post the following:

Your code requires style changes.
In the top level of your repository, you can run:

`git clang-format 604680ab15fce501b197616714454fb655cb3c16`

Alternatively, apply the patch found [here](http://mooseframework.org/docs/PRs/8766/style.patch).
You can directly apply the patch by running:

`curl -s http://mooseframework.org/docs/PRs/8766/style.patch | git apply -v`

2017-04-04 14:53 UTC, dschwen commented on modules/tensor_mechanics/src/materials/ComputeIsotropicElasticityTensor.C
> +  int num_elastic_constants = _bulk_modulus_set + _lambda_set + _poissons_ratio_set +
should be `unsigned int` unless you expect a negative number of elastic constants...

2017-04-04 15:38 UTC, hchen139 commented on modules/combined/tests/check_error/contact_displacements.i
> +    displacements = 'disp_x disp_y disp_z'
I looked at the ContactAction.C, and turned out that the intend of this test is to check whether the displacements is set in the mesh block.

2017-04-04 15:39 UTC, hchen139 commented on modules/tensor_mechanics/src/materials/ComputeIsotropicElasticityTensor.C
> +  int num_elastic_constants = _bulk_modulus_set + _lambda_set + _poissons_ratio_set +
will update this.

2017-04-04 16:19 UTC, moosebuild commented
Job `Precheck:linux-gnu` on 6e7b688 wanted to post the following:

Your code requires style changes.
In the top level of your repository, you can run:

`git clang-format 4f877a63034ec0bcf71cbf488375fece1eafe5b5`

Alternatively, apply the patch found [here](http://mooseframework.org/docs/PRs/8766/style.patch).
You can directly apply the patch by running:

`curl -s http://mooseframework.org/docs/PRs/8766/style.patch | git apply -v`

2017-04-04 16:55 UTC, hchen139 commented
@bwspenc do you have an idea why the xfem init_solution_propagation test failed?

2017-04-04 16:58 UTC, bwspenc commented
Ugh!  I just added that test.  It passed in my initial PR, and I assume it would have run on the same platforms.  I'll look into that.  Maybe I need to skip it or something.

2017-04-04 18:06 UTC, moosebuild commented
Job `TBB test:linux-gnu` on 2e10828 : invalidated by @bwspenc

Another PR just passed this test without any issues.  Retry.

2017-04-05 14:47 UTC, dschwen commented on modules/combined/tests/check_error/contact_displacements.i
> +    displacements = 'disp_x disp_y disp_z'
Ok, I see that now.

2017-04-05 14:49 UTC, dschwen approved these changes

2017-04-05 15:16 UTC, merged