Parameter fix when using PBS options
idaholab/moose pull request #8779
Opened 2017-03-21 20:40 UTC by milljm

While using PBS options, custom test parameters were not being correctly
populated in the pbs_template file. Arguments such as --timing for example
would not appear in the PBS cluster file.

Refs #8778

2017-03-21 20:42 UTC, permcody requested changes
Since you are refactoring all this code, why not just get the actual command from the getCommand() method. That'll take care of most of this logic. Sure you'll still need to do a few extra things for PBS but start with the fact that the command to execute and all that logic is already handled for you.

2017-03-22 19:18 UTC, permcody requested changes

2017-03-22 19:18 UTC, permcody commented on python/TestHarness/testers/RunApp.py
> +            specs['cli_args'] = '"' + ' '.join(specs['cli_args']) + '"'
Getting closer. However we are still doing one or two things in both major branches here. Building the actual command cli_args appears to be one of those things that's duplicated. Can this be captured from the other branch (i.e. factor it out and do cli_args in one place only).

2017-03-22 19:55 UTC, milljm commented on python/TestHarness/testers/RunApp.py
> +            specs['cli_args'] = '"' + ' '.join(specs['cli_args']) + '"'
Sorry, I am not following. I need to squash this into itself, and encapsulate it in quotes so when the replace routine occurs:
```python
            # Do all of the replacements for the valid parameters
            for spec in specs.valid_keys():
                if spec in specs.substitute:
                    specs[spec] = specs.substitute[spec].replace(spec.upper(), specs[spec])
                content = content.replace('<' + spec.upper() + '>', str(specs[spec]))
```
It writes the correct thing in the cluster file (not a list):
```bash
[Jobs]
  [./xda_re_05]
    ...
    cli_args = "--error --no-gdb-backtrace --timing"
  [../]
[]
```
I suppose I can remove this all together and then fix it in the cluster_launcher.py script instead?

2017-06-21 19:45 UTC, permcody commented
Closing due to inactivity.

2017-06-21 19:45 UTC, closed without merging