Working toward improving Peacock sizing
idaholab/moose pull request #8855
Opened 2017-04-03 22:53 UTC by aeslaughter

@brianmoose See if you can improve the sizing of the VTKWindow in the Input tab to not get cut-off initially. And, if you are bored you can try to figure out why the block selector is so wide.

2017-04-04 13:54 UTC, brianmoose requested changes
The test_PeacockCollapsibleWidget was not added to the tests file.

In low resolution it still doesn't work right. Expanding a widget can still lead to everything scrunched up.

On the input file viewer, I think I liked the placement the other way. The Mesh, Background, and Clipping widgets use more horizontal space than a single block of the "Block Selection" widget. The old way had more room for the mesh on lower resolutions.

2017-04-04 13:54 UTC, brianmoose commented on python/peacock/base/MediaControlWidgetBase.py
> +        edit.setSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
Why is this Expanding?

2017-04-04 14:10 UTC, aeslaughter commented on python/peacock/base/MediaControlWidgetBase.py
> +        edit.setSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
These are the time and timestep edit boxes, they should get as much space as available because there could be large numbers in them.

2017-04-05 19:58 UTC, aeslaughter commented
@brianmoose This is all sorts of changes toward improving sizing as well as other basic changes, mainly cleaning up the TabPlugin initialization. However, I can't figure out the PeacockApp tests, there are 3 failing, could you take a look?

2017-04-05 21:39 UTC, moosebuild commented
Job `Python testing:linux-gnu` on 49fd5e6 : invalidated by @aeslaughter

2017-04-06 15:56 UTC, brianmoose requested changes

2017-04-06 15:56 UTC, brianmoose commented on python/peacock/ExodusViewer/plugins/VTKWindowPlugin.py
> +        if not self.isVisible():# or not file_exists:
Can probably get rid of the comment

2017-04-06 20:48 UTC, brianmoose approved these changes

2017-04-06 20:49 UTC, merged