Improve the procedure for setting the solution
idaholab/moose pull request #8865
Opened 2017-04-04 19:50 UTC by bwspenc

ref #8763

2017-04-04 19:53 UTC, permcody commented
Wait, does this fix that test? I just put up a PR to skip it.

2017-04-04 19:54 UTC, bwspenc commented
@permcody I think the problems with getting the unique_id may have originated from the code that this replaces, so I'm hopeful that this might fix that flaky test.  Regardless, this should be far more efficient because it just involves a single loop over the nodes and the elements.

2017-04-04 21:13 UTC, moosebuild commented
Job `TBB test:linux-gnu` on 2e9f1f5 : invalidated by @bwspenc

Re-run since I skipped the flaky test.

2017-04-04 22:16 UTC, permcody commented
So what are we doing with this PR? Are you going to work on it more, or would you like it reviewed and merged?

2017-04-05 13:41 UTC, bwspenc commented
@permcody I'd like this to be reviewed and merged.  This is a better way to do things regardless of that test.

2017-04-05 14:58 UTC, permcody requested changes
A few types are wrong. The dof_id_type in particular we need to get right or it breaks the 64-bit indices build.

2017-04-05 14:58 UTC, permcody commented on modules/xfem/include/base/XFEM.h
> +                          const std::vector<unsigned int> & stored_solution_dofs,
`unsigned int` -> `dof_id_type`

2017-04-05 14:58 UTC, permcody commented on modules/xfem/src/base/XFEM.C
> +  for (auto node_it = _mesh->local_nodes_begin(); node_it != _mesh->nodes_end(); ++node_it)
I'd move the `nodes_end()` call out of the loop. The libMesh iterators can be slow to evaluate.

2017-04-05 14:58 UTC, permcody commented on modules/xfem/src/base/XFEM.C
> +      std::vector<unsigned int> stored_solution_dofs = getNodeSolutionDofs(node, sys);
`dof_id_type`

2017-04-05 14:58 UTC, permcody commented on modules/xfem/src/base/XFEM.C
> +  for (auto elem_it = _mesh->local_elements_begin(); elem_it != _mesh->local_elements_end();
Move end iterator out of loop

2017-04-05 14:58 UTC, permcody commented on modules/xfem/src/base/XFEM.C
> +      std::vector<unsigned int> stored_solution_dofs = getElementSolutionDofs(elem, sys);
`dof_id_type`

2017-04-05 14:58 UTC, permcody commented on modules/xfem/src/base/XFEM.C
> +                         const std::vector<unsigned int> & stored_solution_dofs,
`dof_id_type`

2017-04-05 14:58 UTC, permcody commented on modules/xfem/src/base/XFEM.C
> +  const unsigned int old_solution_offset = stored_solution_dofs.size();
wrong type here too - It'll be a `std::size_t`, you might just use auto.

2017-04-05 14:58 UTC, permcody commented on modules/xfem/src/base/XFEM.C
> +  const unsigned int older_solution_offset = old_solution_offset * 2;
Same here

2017-04-05 14:58 UTC, permcody commented on modules/xfem/src/base/XFEM.C
> -      for (unsigned int i = 0; i < stored_solution_dofs.size(); ++i)
Pedantic, but wrong type

2017-04-05 14:58 UTC, permcody commented on modules/xfem/src/base/XFEM.C
> +  for (unsigned int i = 0; i < stored_solution_dofs.size(); ++i)
Wrong type

2017-04-05 20:15 UTC, bwspenc commented
@permcody Thanks for the review. I changed those types as you suggested.

Are we running the tests in a configuration where dof_id_type would have been different from unsigned int (maybe with 64 bit indices)?  I'm just wondering if that might be why that test is flaky.

2017-04-05 20:32 UTC, permcody commented
We have a 64-bit build. If you look through the list of targets, you'll see it. It does break with some regularity due to improper use of types but it's not part of the tests we run on a PR so no, not this particular issue.

2017-04-05 22:59 UTC, permcody approved these changes

2017-04-05 23:00 UTC, merged