Allow halos to bleed over periodic BCs
idaholab/moose pull request #8926
Opened 2017-04-12 22:17 UTC by permcody

This is another non-trivial update to the GrainTracker that allows halos to bleed over a periodic BC. This works by employing some of the "topological neighbor" methods in libMesh for getting halos. However, it's tricky to do this correctly with mesh adaptivity and recursion. I'm maintaining a separate list of IDs that are "disjoint" from the regular halos. I have to run a "connected component" algorithm on those halos to put them into separate buckets, then build new bounding boxes around those regions.

Including a new test and images showing the difference.

2017-04-12 22:17 UTC, permcody commented
![grains_near_edge](https://cloud.githubusercontent.com/assets/3036960/24981791/7dfe788a-1f9b-11e7-824b-f98010c2358e.png)

BEFORE:
![halos_no_bleed](https://cloud.githubusercontent.com/assets/3036960/24981794/822d4f8a-1f9b-11e7-9df6-481567703681.png)

AFTER:
![halos_bleed_across_bc](https://cloud.githubusercontent.com/assets/3036960/24981800/89b0db6e-1f9b-11e7-9343-321e4c23b555.png)

2017-04-13 14:46 UTC, permcody commented
With @dschwen likely out for a little while, I may need to have @jwpeterson review this and merge. While I don't necessarily need this for the _next_ PR I have lined up (to overhaul polycrystal ICs). My two PRs are changing logic in several of the same areas so if this PR requires changes on its own, it'll be a rebasing challenge.

2017-04-13 19:23 UTC, jwpeterson requested changes
I do like how that one crazy ass if-statement is gone now...

2017-04-13 19:23 UTC, jwpeterson commented on modules/phase_field/src/postprocessors/FeatureFloodCount.C
> +areElemListsMergeable(std::list<dof_id_type> elem_list1,
Do you really want to pass these lists to this function by value? Seems like they could be (const?) references...

2017-04-13 19:23 UTC, jwpeterson commented on modules/phase_field/include/postprocessors/FeatureFloodCount.h
> +     * The routine called to see if two features are mergable:
I don't know how "mergeable" is actually spelled, but the documentation spelling should at least agree with the code spelling.

2017-04-13 20:53 UTC, permcody commented on modules/phase_field/src/postprocessors/FeatureFloodCount.C
> +areElemListsMergeable(std::list<dof_id_type> elem_list1,
Definitely don't want to make copies!

2017-04-13 21:27 UTC, jwpeterson approved these changes

2017-04-13 21:55 UTC, merged

2017-04-18 14:01 UTC, brianmoose commented
Looks like this causes the `phase_field/examples/grain_growth.grain_growth_2D_graintracker` test to fail on mac (in opt mode). Seems to be fine on linux.
https://www.moosebuild.org/job/82567/

2017-04-18 14:19 UTC, permcody commented
Yes I am aware. The issue that "check_syntax" does a lot more than parse syntax. So when a test was put in there to check the syntax and change the problem to make it a little smaller, this issue was triggered. I have another PR that will take care of this once I shake out the failures it caused #8948.