Add an adjustable framerate to the media player
idaholab/moose pull request #8935
Opened 2017-04-13 18:10 UTC by brianmoose

Adds a widget to the media control player to adjust the framerate (in milliseconds).

I also added validation on the Time* input boxes so that you can't enter "foo" in the box and cause things to crash.

@aeslaughter I uncommented your code to not update the Time* input boxes if they have focus. This allows me to actually edit them without it being immediately overwritten. But I assume there was a reason it was commented out...

closes #8922

2017-04-13 18:13 UTC, brianmoose commented
@permcody Maybe you can try this out to find the framerate that you want to be the default.

2017-04-13 20:34 UTC, aeslaughter commented
Whatever reason I had for commenting that out it probably long since dealt with.

2017-04-17 14:58 UTC, permcody commented
Love it, doesn't work.

2017-04-17 15:04 UTC, permcody requested changes
I can change the number but nothing happens. I tried up to 10000 and the movie still plays the same speed.

2017-04-18 13:01 UTC, brianmoose commented
Hmm, works for me. Are you tabbing out of the box after you change the number and before hitting play?

2017-04-18 14:22 UTC, permcody commented
Well if that's it, we should probably make hitting play, re-read the value. I tried it several times and probably didn't tab out of it once. Users won't either.

2017-04-20 16:11 UTC, permcody commented
Works now, let's change the name "Framerate" to "frame delay"

2017-04-20 20:05 UTC, permcody approved these changes

2017-04-20 20:05 UTC, merged