adds barebones RankThreeTensor support (general fill method only) for…
idaholab/moose pull request #8972
Opened 2017-04-20 01:08 UTC by mangerij

Closes #8963

I'm going to be adding to this class as I'm developing its use in Ferret. Currently, we only are going to have `general` `fill_method` but more fill methods will be added as they are needed, perhaps depending on material point symmetries. 

Note it is basically the same structure as RankTwo and RankFour tensor classes but I removed things like inverting since I'm not sure its possible to invert these n x m objects elegantly.

2017-04-20 01:09 UTC, moosebuild commented
Job `Precheck:linux-gnu` on 4a6fa15 wanted to post the following:

Your code requires style changes.
In the top level of your repository, you can run:

`git clang-format 6345403d76095d13b54906775448b99f91fd7086`

Alternatively, apply the patch found [here](http://mooseframework.org/docs/PRs/8972/style.patch).
You can directly apply the patch by running:

`curl -s http://mooseframework.org/docs/PRs/8972/style.patch | git apply -v`

2017-04-21 03:01 UTC, dschwen commented on framework/include/utils/RankThreeTensor.h
> +  /// Print the rank four tensor
Three

2017-04-21 03:01 UTC, dschwen commented on framework/include/utils/RankThreeTensor.h
> +   * the Rank-4 tensor.
Three

2017-04-21 03:01 UTC, dschwen commented on framework/include/utils/RankThreeTensor.h
> +  /// Dimensionality of rank-four tensor
Three

2017-04-21 03:02 UTC, mangerij commented
Oh yes, many of the comments! I thought i got all of them, but i was
rushing. Ill fix this up tomorrow.

On Apr 20, 2017 11:01 PM, "Daniel Schwen" <notifications@github.com> wrote:

> *@dschwen* commented on this pull request.
> ------------------------------
>
> In framework/include/utils/RankThreeTensor.h
> <https://github.com/idaholab/moose/pull/8972#discussion_r112600836>:
>
> > +  //  static RankThreeTensor Identity() { return RankThreeTensor(initIdentity); }
> +  //  static RankThreeTensor IdentityFour() { return RankThreeTensor(initIdentityFour); };
> +
> +  /// Gets the value for the index specified.  Takes index = 0,1,2
> +  Real & operator()(unsigned int i, unsigned int j, unsigned int k);
> +
> +  /**
> +   * Gets the value for the index specified.  Takes index = 0,1,2
> +   * used for const
> +   */
> +  Real operator()(unsigned int i, unsigned int j, unsigned int k) const;
> +
> +  /// Zeros out the tensor.
> +  void zero();
> +
> +  /// Print the rank four tensor
>
> Three
> ------------------------------
>
> In framework/include/utils/RankThreeTensor.h
> <https://github.com/idaholab/moose/pull/8972#discussion_r112600882>:
>
> > +   * r_ijk = R_im R_in R_ko r_mno
> +   */
> +  void rotate(const RealTensorValue & R);
> +
> +  /**
> +   * Rotate the tensor using
> +   * r_ijk = R_im R_in R_ko R_lp r_mno
> +   */
> +  void rotate(const RankTwoTensor & R);
> +
> +  /// Static method for use in validParams for getting the "fill_method"
> +  static MooseEnum fillMethodEnum();
> +
> +  /**
> +   * fillFromInputVector takes some number of inputs to fill
> +   * the Rank-4 tensor.
>
> Three
> ------------------------------
>
> In framework/include/utils/RankThreeTensor.h
> <https://github.com/idaholab/moose/pull/8972#discussion_r112600907>:
>
> > +   * @param input the numbers that will be placed in the tensor
> +   * @param fill_method this can be:
> +   *             antisymmetric (use fillAntisymmetricFromInputVector)
> +   *             symmetric9 (use fillSymmetricFromInputVector with all=false)
> +   *             symmetric21 (use fillSymmetricFromInputVector with all=true)
> +   *             general_isotropic (use fillGeneralIsotropicFrominputVector)
> +   *             symmetric_isotropic (use fillSymmetricIsotropicFromInputVector)
> +   *             antisymmetric_isotropic (use fillAntisymmetricIsotropicFromInputVector)
> +   *             axisymmetric_rz (use fillAxisymmetricRZFromInputVector)
> +   *             general (use fillGeneralFromInputVector)
> +   *             principal (use fillPrincipalFromInputVector)
> +   */
> +  void fillFromInputVector(const std::vector<Real> & input, FillMethod fill_method);
> +
> +protected:
> +  /// Dimensionality of rank-four tensor
>
> Three
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/idaholab/moose/pull/8972#pullrequestreview-33928784>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AHPulDe0SkwVa-ZOPuvCz0vlNXOjjRcfks5ryBwHgaJpZM4NCa4P>
> .
>

2017-04-21 16:25 UTC, mangerij commented
Should be ready now @dschwen

2017-04-21 16:40 UTC, dschwen commented on framework/src/utils/RankThreeTensor.C
> +                                            // just use general (at most 18 components)
Uhm, why not 27 components?

2017-04-21 16:44 UTC, dschwen commented on framework/src/utils/RankThreeTensor.C
> +        ind = i * N * N + j * N + k;
2*3*3+2*3+2 = 26 that's out of bounds. Of course a 3x3x3 tensor has 27 entries. I thought I was losing my mind...

2017-04-21 16:44 UTC, dschwen requested changes
Except for the 18 input values gaffe this looks good!

2017-04-21 16:46 UTC, mangerij commented
Hmm for some reason I was looking at the 3x6 representations which has 18
entries. You are right, it should be 27.

On Fri, Apr 21, 2017 at 12:44 PM, Daniel Schwen <notifications@github.com>
wrote:

> *@dschwen* requested changes on this pull request.
>
> Except for the 18 input values gaffe this looks good!
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/idaholab/moose/pull/8972#pullrequestreview-34071425>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AHPulGk3cy_vXDi20gMgeyu5dxv_Ueaiks5ryNz5gaJpZM4NCa4P>
> .
>

2017-04-21 18:46 UTC, mangerij commented
That test fail is unrelated right?

2017-04-21 19:12 UTC, dschwen commented
No, unfortunately it is not!

```
value_type {aka class RankThreeTensor}’ has no member named ‘mixedProductRankFour‘
```

Let me look into this

2017-04-21 22:40 UTC, dschwen commented
@bwspenc there already is a `RankThreeTensor` in Grizzly. Would you mind taking a look if we can drop it in favor of this one? @mangerij would need to implement the mixed product with a rank four tensor though.

2017-04-24 16:39 UTC, bwspenc commented
This looks almost identical to the `RankThreeTensor` in Grizzly, except that the Grizzly one supplies a couple of methods that don't exist in this one. I think the best solution is to re-name the Grizzly one so that this PR can go through, and then add those missing methods to the one in MOOSE, and get rid of the Grizzly one.  I'll re-name the Grizzly one right now  -- it should be easy since there's only one model that uses it.

2017-04-24 16:50 UTC, bwspenc commented
@dschwen I just submitted a PR to Grizzly to rename its RankThreeTensor.

2017-04-24 18:27 UTC, dschwen commented
I merged the Grizzly PR and will invalidate teh app test once it trickles through to master.

2017-04-25 02:15 UTC, moosebuild commented
Job `App tests:linux-gnu` on 977fc30 : invalidated by @dschwen

Grizzly object has been renamed

2017-04-25 14:51 UTC, dschwen commented
@mangerij, just a reminder that you have two more spots where you mention "18" components. Please change that to reflect the fact that you are storing and initializing with 27 components.

2017-04-25 14:58 UTC, mangerij commented
OK, fixed that.

Thanks everyone.

2017-04-25 15:00 UTC, dschwen approved these changes

2017-04-25 16:13 UTC, merged