implementing two-phase grain growth model
idaholab/moose pull request #8989
Opened 2017-04-21 17:36 UTC by karim86

closes #8837

2017-04-21 17:40 UTC, karim86 commented
@dschwen I had to close the old PR and open a new one (basically I created a new branch) for some strange behavior with git push

2017-04-21 22:28 UTC, moosebuild commented
Job `modules debug:linux-gnu` on 9a4930a : invalidated by @dschwen

levelset test fail

2017-04-23 16:37 UTC, dschwen requested changes
The design is not right yet

2017-04-23 16:37 UTC, dschwen commented on modules/phase_field/include/action/PolycrystalKernelAction.h
> +  unsigned int _phase_num;
No, this only belongs in the derived class!

2017-04-23 16:37 UTC, dschwen commented on modules/phase_field/src/action/PolycrystalKernelAction.C
> +    kernel_type = "TwoPhaseACGrGrPoly";
No, this logic needs to be implemented using a virtual name function

2017-04-23 16:37 UTC, dschwen commented on modules/phase_field/include/action/PolycrystalKernelAction.h
> +  unsigned int _phase_num;
If this is done right this member is not needed at all

2017-04-23 16:37 UTC, dschwen commented on modules/phase_field/src/action/PolycrystalKernelAction.C
>        params.set<NonlinearVariableName>("variable") = var_name;
use `applyParameters` to simplify this

2017-04-27 21:06 UTC, moosebuild commented
Job `App tests:linux-gnu` on 044f7aa : invalidated by @dschwen

Action fixed in Marmot

2017-04-27 21:52 UTC, dschwen requested changes
I cannot merge a new model without a .md file to document it (with equations). Have you used the new documentation system at all? I can show you.

2017-04-27 21:52 UTC, dschwen commented on modules/phase_field/src/action/PolycrystalTwoPhaseKernelAction.C
> +    _mob_ratio(getParam<Real>("mob_ratio"))
all these members can be removed!

2017-04-27 21:52 UTC, dschwen commented on modules/phase_field/src/kernels/ACTwoPhaseGrGrPoly.C
> +
rm line

2017-04-27 21:56 UTC, karim86 commented
I have not used yet, I'll stop by

On Thu, Apr 27, 2017 at 3:52 PM, Daniel Schwen <notifications@github.com>
wrote:

> *@dschwen* requested changes on this pull request.
>
> I cannot merge a new model without a .md file to document it (with
> equations). Have you uses the new documentation system at all? I can show
> you.
> ------------------------------
>
> In modules/phase_field/src/action/PolycrystalTwoPhaseKernelAction.C
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_idaholab_moose_pull_8989-23discussion-5Fr113811317&d=DwMCaQ&c=54IZrppPQZKX9mLzcGdPfFD1hxrcB__aEkJFOKJFd00&r=nhScyjGW-UG7fBfM7LNyTofBdOEwu-Evh358cPutz28&m=KOzEFeajphUNNJjdyCR7w39YSjM6k_ww-KKJ-3fNQJg&s=75v7U8xqoegl5xIBRKK5E9odKBdSFOiAkshxaSEjloU&e=>
> :
>
> > +      1,
> +      "specifies the total number of grains/variants of the second phase");
> +  params.addParam<Real>(
> +      "en_ratio", 1.0, "Ratio of surface energy to GB energy, e.g., interphase energy");
> +  params.addParam<Real>(
> +      "second_phase_en_ratio", 1.0, "Ratio of second-phase to parent-phase GB energy");
> +  params.addParam<Real>("mob_ratio", 1.0, "Ratio of surface energy to GB mobility");
> +  return params;
> +}
> +
> +PolycrystalTwoPhaseKernelAction::PolycrystalTwoPhaseKernelAction(const InputParameters & params)
> +  : PolycrystalKernelAction(params),
> +    _second_phase_op_num(getParam<unsigned int>("second_phase_op_num")),
> +    _en_ratio(getParam<Real>("en_ratio")),
> +    _second_phase_en_ratio(getParam<Real>("second_phase_en_ratio")),
> +    _mob_ratio(getParam<Real>("mob_ratio"))
>
> all these members can be removed!
> ------------------------------
>
> In modules/phase_field/src/kernels/ACTwoPhaseGrGrPoly.C
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_idaholab_moose_pull_8989-23discussion-5Fr113811355&d=DwMCaQ&c=54IZrppPQZKX9mLzcGdPfFD1hxrcB__aEkJFOKJFd00&r=nhScyjGW-UG7fBfM7LNyTofBdOEwu-Evh358cPutz28&m=KOzEFeajphUNNJjdyCR7w39YSjM6k_ww-KKJ-3fNQJg&s=3PTY9CpJ2XTwR0EnZz7Y1ZsU6YsDb2IUczJJNcA8hxU&e=>
> :
>
> > +      "en_ratio", 1.0, "Ratio of surface energy to GB energy, e.g., interphase energy");
> +  params.addParam<Real>(
> +      "second_phase_en_ratio", 1.0, "Ratio of second-phase to parent-phase GB energy");
> +  params.addParam<Real>("mob_ratio", 1.0, "Ratio of surface energy to GB mobility");
> +  return params;
> +}
> +
> +ACTwoPhaseGrGrPoly::ACTwoPhaseGrGrPoly(const InputParameters & parameters)
> +  : ACGrGrBase(parameters),
> +    _gamma(getMaterialProperty<Real>("gamma_asymm")),
> +    _op_index(getParam<unsigned int>("op_index")),
> +    _second_phase_op_num(getParam<unsigned int>("second_phase_op_num")),
> +    _en_ratio(getParam<Real>("en_ratio")),
> +    _second_phase_en_ratio(getParam<Real>("second_phase_en_ratio")),
> +    _mob_ratio(getParam<Real>("mob_ratio"))
> +
>
> rm line
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_idaholab_moose_pull_8989-23pullrequestreview-2D35233398&d=DwMCaQ&c=54IZrppPQZKX9mLzcGdPfFD1hxrcB__aEkJFOKJFd00&r=nhScyjGW-UG7fBfM7LNyTofBdOEwu-Evh358cPutz28&m=KOzEFeajphUNNJjdyCR7w39YSjM6k_ww-KKJ-3fNQJg&s=BaOS6cXfzDhsEp1LaJYbTHC5mbxxfyDcbnGKOi1kwjA&e=>,
> or mute the thread
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AOW-5F85CcrHx8amxNbJHFjvjQ-2D6NSlrz8ks5r0Q4mgaJpZM4NEldh&d=DwMCaQ&c=54IZrppPQZKX9mLzcGdPfFD1hxrcB__aEkJFOKJFd00&r=nhScyjGW-UG7fBfM7LNyTofBdOEwu-Evh358cPutz28&m=KOzEFeajphUNNJjdyCR7w39YSjM6k_ww-KKJ-3fNQJg&s=8jg0pmk9f1zK6s6eOKkLlr9irL7WRmzmntGUyKCSjKE&e=>
> .
>



-- 
Karim El-Sayed Ahmed, PhD
Postdoctoral Research Associate
Fuel Modeling & Simulation Department
Idaho National Laboratory

2017-05-17 23:02 UTC, permcody commented
#9145 is incompatible with this PR. Depending on which one goes in, we'll have to update this PR. The new system is already merged though so these new tests can be updated. @karim86 - let me know if need help.

2017-05-18 16:46 UTC, karim86 commented
Yeah I am going to rebase anyway to add the documentation. I will look at the new system and see how to modify the test. I will let you guys know if I needed help.

2017-05-25 15:38 UTC, dschwen commented
@karim86 do you need any help with this?

2017-05-25 16:19 UTC, karim86 commented
@dschwen thanks Daniel I think I got it I just got busy working on different stuff last couple of weeks. I should finish this soon.

2017-06-28 20:16 UTC, dschwen commented
Ping @karim86

2017-07-11 17:54 UTC, dschwen commented
@karim86 has not reacted on here for 47 days. Policy is to close after 30days of inactivity. I'd rather see this get finished though...

2017-07-31 20:10 UTC, permcody commented
@dschwen - With @karim86 gone this is going to remain open indefinitely unless somebody else is assigned. What would you like to do with this PR?

2017-07-31 21:44 UTC, karim86 commented
I will update it in the next few days. 

> On Jul 31, 2017, at 2:10 PM, Cody Permann <notifications@github.com> wrote:
> 
> @dschwen - With @karim86 gone this is going to remain open indefinitely unless somebody else is assigned. What would you like to do with this PR?
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.
>

2017-08-31 16:08 UTC, permcody commented
Closing due to inactivity.

2017-08-31 16:08 UTC, closed without merging