Add missing methods to RankThreeTensor
idaholab/moose pull request #9025
Opened 2017-04-28 13:08 UTC by bwspenc

closes #8963

2017-04-28 13:09 UTC, moosebuild commented
Job `Precheck:linux-gnu` on b21c09c wanted to post the following:

Your code requires style changes.
In the top level of your repository, you can run:

`git clang-format 96013fe0b11729e798ca447d0799eaf5e37c00c8`

Alternatively, apply the patch found [here](http://mooseframework.org/docs/PRs/9025/style.patch).
You can directly apply the patch by running:

`curl -s http://mooseframework.org/docs/PRs/9025/style.patch | git apply -v`

2017-04-28 13:12 UTC, moosebuild commented
Job `Precheck:linux-gnu` on 3f80f1b wanted to post the following:

Your code requires style changes.
In the top level of your repository, you can run:

`git clang-format 96013fe0b11729e798ca447d0799eaf5e37c00c8`

Alternatively, apply the patch found [here](http://mooseframework.org/docs/PRs/9025/style.patch).
You can directly apply the patch by running:

`curl -s http://mooseframework.org/docs/PRs/9025/style.patch | git apply -v`

2017-04-29 23:32 UTC, dschwen commented on framework/src/utils/RankThreeTensor.C
> +RankThreeTensor::fillFromPlaneNormal(const TypeVector<Real> & input)
Why not RealVectorValue?

2017-04-29 23:35 UTC, dschwen requested changes

2017-04-29 23:35 UTC, dschwen commented on framework/src/utils/RankThreeTensor.C
> +RankThreeTensor::fillFromPlaneNormal(const TypeVector<Real> & input)
In moose `TypeVector<Real>` is used 15 times, whereas `RealVectorValue` is used 838 times. I'd suggest to drop the odd one out.

2017-05-01 16:40 UTC, bwspenc commented
@dschwen I addressed your changes and the tests just passed.

2017-05-01 16:51 UTC, dschwen approved these changes

2017-05-01 16:51 UTC, merged