CNSFV block restriction
idaholab/moose pull request #9046
Opened 2017-05-02 18:03 UTC by Chuban

Let's try this again.

A change to CNSFVLeastSquaresSlopeReconstruction.C redefines an internal side to be a boundary for which a neighboring element exists and is a member of the subdomain. Internal boundaries between subdomains are now handled in the same manner as external boundaries. This permits CNSFV variables to be restricted to specific subdomains of the problem.

closes #8851

2017-05-03 15:16 UTC, andrsd requested changes

2017-05-03 15:16 UTC, andrsd commented on modules/navier_stokes/src/userobjects/CNSFVLeastSquaresSlopeReconstruction.C
> +    if (elem->neighbor(is) != NULL && hasBlocks(elem->neighbor(is)->subdomain_id()))
Notice that `elem->neighbor(is)` is obtained on the first line in the body of this if-statement. So let's do:
```
    if (elem->neighbor(is) != NULL)
    {
      const Elem * neig = elem->neighbor(is);
      if (this->hasBlocks(neig->subdomain_id()))
      {
        <original body>
      }
```

2017-05-06 11:16 UTC, Chuban commented
I made this change rather blindly as I thought it was only stylistic, but that's not so.  We have three cases to handle: (1) the neighbor is defined and in the subdomain, (2) the neighbor is defined and out of the subdomain, and (3) the neighbor is not defined.  We need the outer else statement (line 202) to run for cases 2 and 3.  The proposed change only allows it to run for cases 3 and completely skips over a large section of code in case 2.  I think we need to revert back to the original construction.

Please block this PR until this has been resolved.

2017-05-08 15:06 UTC, moosebuild commented
Job `test debug:linux-gnu` on 336b81d : invalidated by @andrsd

timeout

2017-05-10 15:25 UTC, Chuban commented
This should be ready to go now.

2017-05-10 15:56 UTC, andrsd approved these changes

2017-05-10 15:56 UTC, merged