scripts: fix stork in-repo check. add clang-format files.
idaholab/moose pull request #9066
Opened 2017-05-04 20:16 UTC by rwcarlsen

Fix bug where stork.sh script failed to recognize when it was in the
MOOSE (or any other) git repository. stork.sh now adds .clang-format and
pre-commit hook install script files to new users' app repositories.

fixes #9064

2017-05-05 15:37 UTC, permcody requested changes

2017-05-05 15:37 UTC, permcody commented on scripts/stork.sh
> +    mkdir -p $dir/scripts
I know this isn't the first place in this script where you "write" but what does this script do if you don't have write permissions where you are running (trust me, users do this....). Perhaps that should be added as another up front check?

2017-05-05 15:37 UTC, permcody commented on scripts/stork.sh
> +    echo "To automatically enforce MOOSE C++ code style in your commits, run:"
👍

2017-05-08 14:49 UTC, rwcarlsen commented on scripts/stork.sh
> +    mkdir -p $dir/scripts
I added an earlier abort that should cover this failure mode.

2017-05-08 17:27 UTC, friedmud commented
I used this this weekend and it seems like it fails to add a .gitignore as
well.

Other than that: worked great!
On Mon, May 8, 2017 at 10:49 AM Robert Carlsen <notifications@github.com>
wrote:

> *@rwcarlsen* commented on this pull request.
> ------------------------------
>
> In scripts/stork.sh
> <https://github.com/idaholab/moose/pull/9066#discussion_r115266512>:
>
> > @@ -85,11 +83,14 @@ if [[ "$kind" == "module" ]]; then
>  fi
>
>  if [[ "$kind" == "app" ]]; then
> -    (
> -        cd $dir
> -        git init
> -        git add *
> -    )
> +    # copy clang-format related files
> +    mkdir -p $dir/scripts
>
> I added an earlier abort that should cover this failure mode.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/idaholab/moose/pull/9066#discussion_r115266512>, or mute
> the thread
> <https://github.com/notifications/unsubscribe-auth/AA1JMYBQ3dktgi-5fwoDEmvy10P8-y-pks5r3yuMgaJpZM4NRKn1>
> .
>

2017-05-08 19:47 UTC, rwcarlsen commented
good catch - .gitignore is now added.

2017-05-08 20:55 UTC, friedmud commented
Cool - thanks!

On Mon, May 8, 2017 at 3:47 PM Robert Carlsen <notifications@github.com>
wrote:

> good catch - .gitignore is now added.
>
> —
> You are receiving this because you commented.
>
>
> Reply to this email directly, view it on GitHub
> <https://github.com/idaholab/moose/pull/9066#issuecomment-299971122>, or mute
> the thread
> <https://github.com/notifications/unsubscribe-auth/AA1JMd7vLdWN6X_ZFgkthakktbEU9V5Qks5r33FcgaJpZM4NRKn1>
> .
>

2017-05-08 20:56 UTC, permcody approved these changes

2017-05-08 20:56 UTC, merged