Improvements to Controls for connecting paramaters
idaholab/moose pull request #9088
Opened 2017-05-09 18:16 UTC by aeslaughter

This makes the name objects a bit more restrictive and adds a test that mimics the behavior you are looking for.

(closes #9087)

2017-05-09 23:12 UTC, moosebuild commented
Job `Moose Documentation:linux-clang` on f568bcb wanted to post the following:

View the site at http://mooseframework.org/docs/PRs/9088/site

2017-05-09 23:14 UTC, aeslaughter commented
Controls docs: http://mooseframework.org/docs/PRs/9088/site/documentation/systems/Controls/index.html

2017-05-09 23:15 UTC, aeslaughter commented
Marmot will fail, but I have a patch waiting.

2017-05-10 14:28 UTC, andrsd requested changes

2017-05-10 14:28 UTC, andrsd commented on docs/content/documentation/systems/Controls/index.md
> +method in your custom object. within this method the following methods are generally used to get
Within (capital letter).

2017-05-10 14:28 UTC, andrsd commented on docs/content/documentation/systems/Controls/index.md
> +  This will method allows for a controllable parameter to be changed, in the case that multiple
This method allows (drop "will").

2017-05-10 14:28 UTC, andrsd commented on docs/content/documentation/systems/Controls/index.md
> +There are additional methods as well is overloaded versions of these methods that allow for the
"methods with(?) overloaded versions of these methods" - "is" there does not make sense to me.

Maybe you wanted to say: "There are additional overloaded methods that allow...". The sentence does not read well...

2017-05-10 14:28 UTC, andrsd commented on docs/content/documentation/systems/Controls/index.md
> +g[`TimePeriod`](framework/TimePeriod.md)) object. In this case, the general name scheme is the same
The leading `g` should not be there, I suppose...

2017-05-10 14:28 UTC, andrsd commented on docs/content/documentation/systems/Controls/index.md
> +`base::object/name`. In the this case "base" is the [MOOSE] base class that the object belongs.
"In this case", drop the "the".
"the object belongs **to**" (?)

2017-05-10 14:29 UTC, andrsd commented
I see a change on the doco, so I guess I will go read the newer version...

2017-05-10 14:32 UTC, aeslaughter commented
@andrsd There shouldn't be any changes since yesterday evening.

2017-05-10 14:34 UTC, andrsd commented
I guess, I just had an older version of the page loaded. Well, my review comments seems to be still valid...

2017-05-10 15:22 UTC, moosebuild commented
Job `Moose Documentation:linux-clang` on 63292e3 wanted to post the following:

View the site at http://mooseframework.org/docs/PRs/9088/site

2017-05-10 15:49 UTC, andrsd approved these changes

2017-05-10 16:34 UTC, merged