Add name() method to fluid_properties
idaholab/moose pull request #9095
Opened 2017-05-10 03:22 UTC by cpgr

Closes #9094

2017-05-10 03:54 UTC, moosebuild commented
Job `Moose Documentation:linux-clang` on 54ef56a wanted to post the following:

View the site at http://mooseframework.org/docs/PRs/9095/site

2017-05-10 04:36 UTC, cpgr commented
Of course, calling this member `name()` wasn't such a good idea...

2017-05-10 05:17 UTC, moosebuild commented
Job `Moose Documentation:linux-clang` on 36ee116 wanted to post the following:

View the site at http://mooseframework.org/docs/PRs/9095/site

2017-05-10 14:53 UTC, permcody commented
What if you could retrieve the stringified type itself from the base class? We could make that available. I'm fine merging this in, just want to make sure you've chosen the right design before clicking the big green button.

2017-05-10 16:00 UTC, andrsd commented
That would not work for the case where CO2 properties are provided by either `TabulatedFluidProperties` or `CO2FluidProperties`. This setup (specific class vs tabulated version) can be used for any fluid...

2017-05-10 16:39 UTC, permcody commented
@andrsd - feel free to merge if you think this is fine.

2017-05-10 17:11 UTC, andrsd requested changes

2017-05-10 17:11 UTC, andrsd commented on modules/fluid_properties/src/userobjects/TabulatedFluidProperties.C
> +
And `clang-format` did not remove this empty line?

2017-05-10 21:41 UTC, cpgr commented on modules/fluid_properties/src/userobjects/TabulatedFluidProperties.C
> +
Apparently not.

2017-05-10 22:07 UTC, moosebuild commented
Job `Moose Documentation:linux-clang` on e5b67fa wanted to post the following:

View the site at http://mooseframework.org/docs/PRs/9095/site

2017-05-11 13:35 UTC, andrsd approved these changes

2017-05-11 13:36 UTC, merged