Add an inputfile for phase transition with Landau free energy
idaholab/moose pull request #9100
Opened 2017-05-10 17:55 UTC by yipenggao

Add an input file for phase transition with Landau free energy (with multi-variants caused by symmetry breaking during phase transition). 

closes #9098

### Complete each of the following items before creating a PR

- Include any relevant design information for your change
- Follow [Coding Standards](http://mooseframework.org/wiki/CodeStandards/)
- Submit one or more [Test Cases](http://mooseframework.org/wiki/MooseTraining/testing/) or modify existing test cases
- Reference or close a specific issue (refs # or closes #)

2017-05-11 00:02 UTC, moosebuild commented
Job `Moose Documentation:linux-clang` on c39f817 wanted to post the following:

View the site at http://mooseframework.org/docs/PRs/9100/site

2017-05-11 01:02 UTC, dschwen commented
Please expand the file name. LD means very little.

2017-05-11 14:34 UTC, yipenggao commented
@dschwen 

Yes. The file name is changed. Thanks.

2017-05-11 14:46 UTC, moosebuild commented
Job `Moose Documentation:linux-clang` on fea03b6 wanted to post the following:

View the site at http://mooseframework.org/docs/PRs/9100/site

2017-05-11 15:08 UTC, dschwen requested changes

2017-05-11 15:08 UTC, dschwen commented on modules/combined/examples/phase_field-mechanics/LandauPhaseTrans.i
> +      type = RndBoundingBoxIC
any reason you are not just using a `RandomIC`? The box seems to cover the entire domain anyways.

2017-05-11 15:08 UTC, dschwen commented on modules/combined/examples/phase_field-mechanics/LandauPhaseTrans.i
> +    family = LAGRANGE
FIRST/LAGRANGE are the default values

2017-05-11 15:08 UTC, dschwen commented on modules/combined/examples/phase_field-mechanics/LandauPhaseTrans.i
> +#
you can remove this comment

2017-05-11 15:08 UTC, dschwen commented on modules/combined/examples/phase_field-mechanics/LandauPhaseTrans.i
> +    function = A2/2*(eta1^2+eta2^2)+A3/3*(eta1^3+eta2^3)+A4/4*(eta1^2+eta2^2)^2
if you enclose the function in `''` you can use spaces to improve readability

2017-05-11 15:08 UTC, dschwen commented on modules/combined/examples/phase_field-mechanics/LandauPhaseTrans.i
> +[]
This is probably all copy pasted from the existing example (which I'm actually updating right now). There is a more elegant/compact way of doing this now.

2017-05-11 15:08 UTC, dschwen commented on modules/combined/examples/phase_field-mechanics/LandauPhaseTrans.i
> +    boundary = 'left'
you can specify multiple boundaries in a BC section, that will make this section musch smaller

2017-05-11 15:08 UTC, dschwen commented on modules/combined/examples/phase_field-mechanics/LandauPhaseTrans.i
> +    type = SolutionTimeAdaptiveDT
look at https://github.com/idaholab/moose/compare/devel...dschwen:examples_9011?expand=1 for my pending changes. We should be using `IterationAdaptiveDT` here.

2017-05-11 15:08 UTC, dschwen commented on modules/combined/examples/phase_field-mechanics/LandauPhaseTrans.i
> +    displacements = 'disp_x disp_y'
displacements should always be in GlobalParams (see link to my in-flight changes)

2017-05-11 15:56 UTC, yipenggao commented on modules/combined/examples/phase_field-mechanics/LandauPhaseTrans.i
> +    type = SolutionTimeAdaptiveDT
@dschwen 
Thanks for your review. It has been updated according to your comments. (except the IterationAdaptiveDT, of which the convergence is much worse than as SolutionTimeAdaptiveDT, seems dt is greatly enlarged after each step, leading to non-convergence)

I will also revise other input file according to this.

2017-05-11 16:04 UTC, moosebuild commented
Job `Moose Documentation:linux-clang` on 8e62683 wanted to post the following:

View the site at http://mooseframework.org/docs/PRs/9100/site

2017-05-11 16:13 UTC, dschwen commented on modules/combined/examples/phase_field-mechanics/LandauPhaseTrans.i
> +    type = SolutionTimeAdaptiveDT
The growth and cutback factors can tune this. There is no reason IterationAdaptiveDT should perform intrinsically worse and it is more stable on systems with heterogeneous load.

2017-05-11 16:25 UTC, mangerij commented
We also use the adaptive stepper for Landau problems with elasticity. Seems
to be most efficient

https://bitbucket.org/mesoscience/ferret/src/9f4532db4972a4630388998621b1df
ebb6abe788/inputs/PTOepitaxy_09_20_10_10_G1.i?at=master&
fileviewer=file-view-default

:)

On May 11, 2017 12:13 PM, "Daniel Schwen" <notifications@github.com> wrote:

> *@dschwen* commented on this pull request.
> ------------------------------
>
> In modules/combined/examples/phase_field-mechanics/LandauPhaseTrans.i
> <https://github.com/idaholab/moose/pull/9100#discussion_r116033886>:
>
> > +
> +  # this gives best performance on 4 cores
> +  solve_type = 'PJFNK'
> +  petsc_options_iname = '-pc_type  -sub_pc_type '
> +  petsc_options_value = 'asm       lu'
> +
> +  l_max_its = 30
> +  nl_max_its = 10
> +  l_tol = 1.0e-4
> +  nl_rel_tol = 1.0e-8
> +  nl_abs_tol = 1.0e-10
> +  start_time = 0.0
> +  num_steps = 10
> +
> +  [./TimeStepper]
> +    type = SolutionTimeAdaptiveDT
>
> The growth and cutback factors can tune this. There is no reason
> IterationAdaptiveDT should perform intrinsically worse and it is more
> stable on systems with heterogeneous load.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/idaholab/moose/pull/9100#discussion_r116033886>, or mute
> the thread
> <https://github.com/notifications/unsubscribe-auth/AHPulMBkzNcosIIX02hsMEx9ezNST0A_ks5r4zOggaJpZM4NXA1R>
> .
>

2017-05-11 16:26 UTC, permcody commented on modules/combined/examples/phase_field-mechanics/LandauPhaseTrans.i
> +    type = SolutionTimeAdaptiveDT
SolutionTimeAdaptive does not take predictable time step increments. It measures wall time to make decisions about step size so cannot be used for any kind of integration test.

2017-05-11 16:39 UTC, yipenggao commented
Thanks all. It has been updated :).

2017-05-11 16:58 UTC, moosebuild commented
Job `Moose Documentation:linux-clang` on 8c29660 wanted to post the following:

View the site at http://mooseframework.org/docs/PRs/9100/site

2017-05-22 15:43 UTC, dschwen approved these changes
Looks good!

2017-05-22 15:43 UTC, merged

2017-05-22 15:44 UTC, dschwen commented
I squashed the 4 commits into one.