Add a new type of switching function with an adjustable weight parameter
idaholab/moose pull request #9116
Opened 2017-05-11 23:11 UTC by yipenggao

Add a new type of switching function (MIX) with an adjustable weight parameter (mix_weight).

Add a new inputfile (modified from DerivativeMultiPhaseMaterial.i) to the new function.

closes #9042

2017-05-11 23:14 UTC, yipenggao commented
This my first time to change the source code file. Please let me know if it is not within the code standard. :)

Thanks.

2017-05-11 23:17 UTC, yipenggao commented
Ok. It fails all the checks.... I will work on it next weekend... :(

2017-05-12 01:17 UTC, dschwen commented
You need to activate the new test by putting it into the tests file. I have more comments later.

2017-05-15 15:05 UTC, yipenggao commented
@dschwen
Should I put create a new folder under /tests/ and put the input and output file there? Also a file named "tests" is needed, right?

2017-05-15 15:08 UTC, dschwen commented
No new directory. Look where the other modes of the switching function are tested and make your test input similar to those.

2017-05-15 15:09 UTC, dschwen commented on modules/phase_field/src/materials/SwitchingFunctionMaterial.C
> +  Real mix_weight = 1;
remove this variable

2017-05-15 15:10 UTC, dschwen commented on modules/phase_field/src/materials/SwitchingFunctionMaterial.C
> +      _mix_weight = _mix_weight > 1 ? 1 : (_mix_weight < 0 ? 0 : _mix_weight);
No. Range limit the parameter, set it in the initializer list, and naver change it again. In fact make it `const` in the declaration.

2017-05-15 15:11 UTC, dschwen commented
No new directory. Look where the other modes of the switching function are tested and make your test input similar to those.

2017-05-15 15:12 UTC, dschwen commented
I'd actually rather see this implemented in a derived class. The mix weight parameter is only used for the one new h order option.

2017-05-16 19:58 UTC, dschwen commented
Why did you close this?

2017-05-16 20:05 UTC, yipenggao commented
@dschwen 
... Sorry, I reset it to previous version (then push....), and right now I am working on adding a new class files. I didn't realize that the PR closed automatically...

Can we reopen it or we have to make a new PR?

2017-05-17 17:35 UTC, yipenggao commented
It still fails the check... Any hint about why?

2017-05-17 18:03 UTC, permcody commented
Click on the precheck target details. It'll take you to CIVET where you can open the results to look at them. You just need a ticket reference in one or more of your commits in this PR.

2017-05-17 18:30 UTC, permcody commented
Also we prefer "rebase" strategy with MOOSE development, not "merge" strategy.

2017-05-17 19:02 UTC, moosebuild commented
Job `Precheck:linux-gnu` on 3cb3dc6 wanted to post the following:

Your code requires style changes.
In the top level of your repository, you can run:

`git clang-format 40a9dac5d3df30c8b3278c9b8163aebb2cf9128c`

Alternatively, apply the patch found [here](http://mooseframework.org/docs/PRs/9116/style.patch).
You can directly apply the patch by running:

`curl -s http://mooseframework.org/docs/PRs/9116/style.patch | git apply -v`

2017-05-17 19:49 UTC, moosebuild commented
Job `Moose Documentation:linux-clang` on 069af20 wanted to post the following:

View the site at http://mooseframework.org/docs/PRs/9116/site

2017-05-17 21:01 UTC, yipenggao commented
@permcody 
Thanks for your help!

Most of the fail information are "Missing gold file".

I have put the inputfile in .../phase_field/tests/MultiPhase/ , and the output file in .../phase_field/tests/MultiPhase/gold/

Is that the correct way to do it?

2017-05-17 21:36 UTC, permcody commented on modules/phase_field/tests/MultiPhase/tests
> +    exodiff = 'DerivativeMultiPhaseMaterial_SwithcingMix_out.e'
The problem is spelling 'Swithcing' -> 'Switching'

2017-05-17 21:41 UTC, yipenggao commented
@permcody 

Many thanks for your review. I will be more careful.

2017-05-17 21:54 UTC, moosebuild commented
Job `Moose Documentation:linux-clang` on f56162e wanted to post the following:

View the site at http://mooseframework.org/docs/PRs/9116/site

2017-05-17 22:38 UTC, yipenggao commented
It is said "Failed(exodiff)".

Is that because I use incorrect type option in the tests file?
type = 'Exodiff'

2017-05-17 22:54 UTC, permcody commented
No, it's because it actually is diffing. Scroll up in the output and look at the differences. They are very tiny (in the e-10 range) which is right near our absolute zero value. The Exodiff tolerances can be adjusted but you generally shouldn't change them. The defaults are listed in the Exodiff object itself. There's a relative tolerance and an absolute floor.

Instead you might re-evaluate your test and decide whether or not you need that many steps to actually test your physics (over 30). The first 20 or so are identical (this is all in the output). You start to get a little numerical round-off as the small differences accumulate. There are many ways to make all of these things go away. If you have any questions about the Exodiff output don't hesitate to ask. It's not too difficult to look through though. 

What you are experiencing is common by the way. You are probably creating tests on a Mac but the test systems are mostly Linux.

2017-05-17 23:51 UTC, moosebuild commented
Job `Moose Documentation:linux-clang` on 876d95a wanted to post the following:

View the site at http://mooseframework.org/docs/PRs/9116/site

2017-05-18 13:51 UTC, permcody commented
@yipenggao - As you shorten up the test, you'll need to update the gold file too. Exodiff complains if the number of output steps don't match.

2017-05-18 14:02 UTC, moosebuild commented
Job `Moose Documentation:linux-clang` on 903a0c5 wanted to post the following:

View the site at http://mooseframework.org/docs/PRs/9116/site

2017-05-18 15:15 UTC, dschwen commented on modules/phase_field/include/materials/SwitchingFunctionMaterialMix.h
> +class SwitchingFunctionMaterialMix : public OrderParameterFunctionMaterial
Please rename to `MixedSwitchingFunctionMaterial`; this should end on Material for consistency.

2017-05-18 15:22 UTC, dschwen requested changes

2017-05-18 15:22 UTC, dschwen commented on modules/phase_field/include/materials/SwitchingFunctionMaterialMix.h
> +  Real _weight;
make `const`

2017-05-18 15:22 UTC, dschwen commented on modules/phase_field/src/materials/SwitchingFunctionMaterialMix.C
> +  params.addParam<MooseEnum>(
remove the `h_order` parameter. No point in having a single option parameter.

2017-05-18 15:22 UTC, dschwen commented on modules/phase_field/src/materials/SwitchingFunctionMaterialMix.C
> +  switch (_h_order)
if `_h_order` is removed the switch block becomes unnecessary

2017-05-18 15:22 UTC, dschwen commented on modules/phase_field/tests/MultiPhase/DerivativeMultiPhaseMaterial_SwitchingMix.i
> +[Mesh]
model you test based on `switchingfunction3phasematerial.i` for example. You do not need a solve to test this material. Please try to keep to the standard for filename capitalization and use of underscores for at least the directory the file is located in.

2017-05-18 15:40 UTC, moosebuild commented
Job `Moose Documentation:linux-clang` on a757943 wanted to post the following:

View the site at http://mooseframework.org/docs/PRs/9116/site

2017-05-18 15:59 UTC, dschwen commented
Oh, right, before this becomes mergeable it needs a documentation file! I can show you how to get going on that.

2017-05-23 18:01 UTC, moosebuild commented
Job `Moose Documentation:linux-clang` on b69768a wanted to post the following:

View the site at http://mooseframework.org/docs/PRs/9116/site

2017-05-23 19:04 UTC, moosebuild commented
Job `Moose Documentation:linux-clang` on b41601e wanted to post the following:

View the site at http://mooseframework.org/docs/PRs/9116/site

2017-05-23 20:53 UTC, moosebuild commented
Job `Precheck:linux-gnu` on 220ee25 wanted to post the following:

Your code requires style changes.
In the top level of your repository, you can run:

`git clang-format 150c068c96bbd7a8d1b72e7dba57d492069362f1`

Alternatively, apply the patch found [here](http://mooseframework.org/docs/PRs/9116/style.patch).
You can directly apply the patch by running:

`curl -s http://mooseframework.org/docs/PRs/9116/style.patch | git apply -v`

2017-05-23 20:56 UTC, dschwen commented
When you apply the style fixes please _squash_ your commits as much as it makes sense.

2017-05-23 21:41 UTC, moosebuild commented
Job `Moose Documentation:linux-clang` on 412f863 wanted to post the following:

View the site at http://mooseframework.org/docs/PRs/9116/site

2017-05-23 23:12 UTC, yipenggao commented
Great! It finally passes all checks.

Then how to make documentation file. Any online instruction?

2017-05-30 14:33 UTC, moosebuild commented
Job `Moose Documentation:linux-clang` on 5667ad1 wanted to post the following:

View the site at http://mooseframework.org/docs/PRs/9116/site

2017-05-30 15:02 UTC, dschwen commented on docs/content/documentation/systems/Materials/phase_field/MixedSwitchingFunctionMaterial.md
> +
please at least mention MIX234 and MIX246 here. Just two terms is a bit weak for documentation.

2017-05-30 15:30 UTC, moosebuild commented
Job `Moose Documentation:linux-clang` on e10b37c wanted to post the following:

View the site at http://mooseframework.org/docs/PRs/9116/site

2017-06-05 19:53 UTC, dschwen approved these changes

2017-06-05 19:53 UTC, merged