Work around case where no author is in the bibtex entry.
idaholab/moose pull request #9155
Opened 2017-05-18 23:12 UTC by jasondhales

### Complete each of the following items before creating a PR
Closes #9154 

@tolman42

2017-05-18 23:43 UTC, moosebuild commented
Job `Moose Documentation:linux-clang` on 58869aa wanted to post the following:

View the site at http://mooseframework.org/docs/PRs/9155/site

2017-05-19 14:05 UTC, aeslaughter commented
I would like a test for this before it is merged. The test should be added to python/MooseDocs/tests/bibtex/test_bibtex.py

2017-05-19 14:49 UTC, jasondhales commented
I'm happy to add a test.  How do I run the doc tests?

2017-05-19 14:50 UTC, aeslaughter commented
```
cd moose/python
./run_tests -j12 --re MooseDocs
```

2017-05-19 16:52 UTC, moosebuild commented
Job `Moose Documentation:linux-clang` on e2500bc wanted to post the following:

View the site at http://mooseframework.org/docs/PRs/9155/site

2017-05-19 17:02 UTC, aeslaughter requested changes

2017-05-19 17:02 UTC, aeslaughter commented on python/MooseDocs/tests/bibtex/gold/test_no_author.html
> +<p><span data-moose-cite="\cite{noAuthorTestKey}"><a href="#noAuthorTestKey">ABC (2017)</a></span>\n<ol class="moose-bibliography" data-moose-bibfiles="[u'/Users/halejd/gitProjects/moose/docs/bib/tes
{{ROOT_DIR}}//moose/docs/bib/test.bib

2017-05-19 17:42 UTC, jasondhales commented on python/MooseDocs/tests/bibtex/gold/test_no_author.html
> +<p><span data-moose-cite="\cite{noAuthorTestKey}"><a href="#noAuthorTestKey">ABC (2017)</a></span>\n<ol class="moose-bibliography" data-moose-bibfiles="[u'/Users/halejd/gitProjects/moose/docs/bib/tes
All the others used CWD, and so I changed it to that.

2017-05-19 18:06 UTC, moosebuild commented
Job `Moose Documentation:linux-clang` on 0ebf249 wanted to post the following:

View the site at http://mooseframework.org/docs/PRs/9155/site

2017-05-19 18:21 UTC, aeslaughter approved these changes

2017-05-19 18:21 UTC, merged