Adding new reverse dependency util and tests
idaholab/moose pull request #9164
Opened 2017-05-19 19:54 UTC by permcody

closes #9163

2017-05-19 20:07 UTC, moosebuild commented
Job `Moose Documentation:linux-clang` on 711694f wanted to post the following:

View the site at http://mooseframework.org/docs/PRs/9164/site

2017-05-19 20:42 UTC, moosebuild commented
Job `Moose Documentation:linux-clang` on b341c14 wanted to post the following:

View the site at http://mooseframework.org/docs/PRs/9164/site

2017-05-19 21:41 UTC, moosebuild commented
Job `Moose Documentation:linux-clang` on d6b224f wanted to post the following:

View the site at http://mooseframework.org/docs/PRs/9164/site

2017-05-22 14:18 UTC, aeslaughter requested changes

2017-05-22 14:24 UTC, brianmoose commented on python/TestHarness/util.py
> +            self.dependency_dict.setdefault(value, set(key)).add(key)
This should be `self.dependency_dict.setdefault(value, set()).add(key)`
`set("abc")` results in a set with `['a', 'b', 'c']`

2017-05-22 14:27 UTC, brianmoose commented on python/TestHarness/util.py
> +            self.dependency_dict.setdefault(value, set(key)).add(key)
@milljm found that the tests didn't work when the keys are multiple characters and all the tests use single characters...

2017-05-22 15:08 UTC, moosebuild commented
Job `Moose Documentation:linux-clang` on 4600d8c wanted to post the following:

View the site at http://mooseframework.org/docs/PRs/9164/site

2017-05-22 15:08 UTC, brianmoose commented on python/TestHarness/util.py
> +            self.dependency_dict.setdefault(value, default_set).add(key)
Why not `self.dependency_dict.setdefault(value, set()).add(key)` and get rid of the previous 2 lines?
If the key "value" doesn't exist it just creates an empty set and adds value "key" to it, which is what your previous 2 lines do.

2017-05-22 16:03 UTC, aeslaughter commented on python/TestHarness/util.py
> +            self.dependency_dict.setdefault(value, default_set).add(key)
You could also use: `self.dependency_dict = collections.defaultdict(set)` then just add the key.

2017-05-22 17:17 UTC, permcody commented on python/TestHarness/util.py
> +            self.dependency_dict.setdefault(value, default_set).add(key)
Fixed

2017-05-22 17:34 UTC, moosebuild commented
Job `Moose Documentation:linux-clang` on 834ec62 wanted to post the following:

View the site at http://mooseframework.org/docs/PRs/9164/site

2017-05-22 19:38 UTC, aeslaughter approved these changes

2017-05-22 19:38 UTC, merged