Nonlinear eigenvalue solver interfaces
idaholab/moose pull request #9208
Opened 2017-06-01 18:52 UTC by fdkong

The implementation of nonlinear eigenvalue solvers is in SLEPc, and we have the interface only at the moose side.  Keep moose simple by avoiding having logic algebra calculations  in moose.  

We already merged nonlinear inverse power into SLEPc, and the Newton-based should be ready soon.    Hopefully, all these solvers come up in the next release.

2017-06-01 19:15 UTC, moosebuild commented
Job `Precheck:linux-gnu` on 4b5bb07 wanted to post the following:

Your code requires style changes.
In the top level of your repository, you can run:

`git clang-format 5d8a7794ee5f92e638a4231789989efbffbd3366`

Alternatively, apply the patch found [here](http://mooseframework.org/docs/PRs/9208/style.patch).
You can directly apply the patch by running:

`curl -s http://mooseframework.org/docs/PRs/9208/style.patch | git apply -v`

2017-06-01 19:54 UTC, moosebuild commented
Job `Moose Documentation:linux-clang` on 0294cf3 wanted to post the following:

View the site at http://mooseframework.org/docs/PRs/9208/site

2017-06-01 22:19 UTC, moosebuild commented
Job `Moose Documentation:linux-clang` on f4b2d9e wanted to post the following:

View the site at http://mooseframework.org/docs/PRs/9208/site

2017-06-01 22:55 UTC, moosebuild commented
Job `Moose Documentation:linux-clang` on 4d79b96 wanted to post the following:

View the site at http://mooseframework.org/docs/PRs/9208/site

2017-06-01 23:27 UTC, moosebuild commented
Job `Moose Documentation:linux-clang` on a654da2 wanted to post the following:

View the site at http://mooseframework.org/docs/PRs/9208/site

2017-06-02 15:46 UTC, moosebuild commented
Job `Moose Documentation:linux-clang` on d6aae8e wanted to post the following:

View the site at http://mooseframework.org/docs/PRs/9208/site

2017-06-06 21:23 UTC, andrsd requested changes

2017-06-06 21:23 UTC, andrsd commented on framework/src/utils/SlepcSupport.C
> +      mooseError("Nonlinear Inverse Power requires SLEPc 3.7.3 or higher  \n");
We do not the trailing spaces and `\n`.

And below

2017-06-06 21:23 UTC, andrsd commented on framework/include/utils/SlepcSupport.h
> +PetscErrorCode moose_slepc_eigen_formFunctionB(SNES snes, Vec x, Vec r, void * ctx);
If this is our function, then `camelCaseStyle`.

2017-06-06 21:23 UTC, andrsd commented on python/TestHarness/testers/Tester.py
> +        params.addParam('slepc_version', [],"A list of slepc versions for which this test will run on, supports normal comparison operators ('<', '>', etc...)")
Space after `,`

What is the reason for not having `'ALL'`?

2017-06-06 21:23 UTC, andrsd commented on python/TestHarness/testers/Tester.py
> +                reasons['slepc_version'] = 'SLEPc does not exist'
Did you mean `SLEPc is not installed`?

2017-06-06 21:23 UTC, andrsd commented on python/TestHarness/util.py
> +    # These does not exist SLEPc
I do not understand this comment

2017-06-06 21:23 UTC, andrsd commented on python/TestHarness/util.py
> +    # If any version of slepc works, return true immediately
s/slepc/SLEPc/ and below

2017-06-06 21:23 UTC, andrsd commented on test/tests/problems/eigen_problem/ne.i
> +  active = 'u'
Not needed

2017-06-06 21:23 UTC, andrsd commented on test/tests/problems/eigen_problem/ne.i
> +  which_eigen_pairs =  LARGEST_MAGNITUDE
1 space after `=`

2017-06-06 21:23 UTC, andrsd commented on test/tests/problems/eigen_problem/ne_deficient_b.i
> +#    cof = 1.0
remove

2017-06-06 21:23 UTC, andrsd commented on test/tests/problems/eigen_problem/ne_deficient_b.i
> +  petsc_options_iname = '-eps_power_snes_mf_operator '
Remove that extra space inside `'...'`

2017-06-06 21:23 UTC, andrsd commented on test/tests/problems/eigen_problem/ne_coupled.i
> +# this coefficient will affect the eigenvalue.
Indent the comment, this is not Fortran.

2017-06-06 21:23 UTC, andrsd commented on test/tests/problems/eigen_problem/tests
> +
Extra empty line

2017-06-19 21:37 UTC, moosebuild commented
Job `Precheck:linux-gnu` on 3a10f9f wanted to post the following:

Your code requires style changes.
In the top level of your repository, you can run:

`git clang-format 82aeca1a340abda68fe0f241f070986b9ca167b8`

Alternatively, apply the patch found [here](http://mooseframework.org/docs/PRs/9208/style.patch).
You can directly apply the patch by running:

`curl -s http://mooseframework.org/docs/PRs/9208/style.patch | git apply -v`

2017-06-19 21:49 UTC, fdkong commented
Moved to  #9343

2017-06-19 21:49 UTC, closed without merging