MooseDocs update to allow including multiple markdown sources
idaholab/moose pull request #9211
Opened 2017-06-01 23:20 UTC by aeslaughter

* Updates MooseDocs to use --json
* Allows documentation from Apps to be included
* Remove duplicate docs for PPs and UOs
* Updates app_syntax extension to use a single command (`!syntax`)

This doesn't address all the issues from #8329, but I think that this eliminates the major concerns and short comings found by users. Therefore I am closing the issue and a bunch of others that have been addressed already or by this PR.

(closes #8329)
(closes #9140)
(closes #9077)
(closes #9044)
(closes #8792)
(closes #7892)
(closes #6907)

2017-06-02 15:10 UTC, moosebuild commented
Job `Moose Documentation:linux-clang` on 30875f4 wanted to post the following:

View the site at http://mooseframework.org/docs/PRs/9211/site

2017-06-12 17:54 UTC, moosebuild commented
Job `Moose Documentation:linux-clang` on 8d32319 wanted to post the following:

View the site at http://mooseframework.org/docs/PRs/9211/site

2017-06-12 20:42 UTC, moosebuild commented
Job `Moose Documentation:linux-clang` on 8362acd wanted to post the following:

View the site at http://mooseframework.org/docs/PRs/9211/site

2017-06-12 22:57 UTC, moosebuild commented
Job `Moose Documentation:linux-clang` on 8362acd : invalidated by @aeslaughter

2017-06-12 23:09 UTC, moosebuild commented
Job `TBB test:linux-gnu` on 8362acd : invalidated by @aeslaughter

2017-06-12 23:36 UTC, moosebuild commented
Job `Moose Documentation:linux-clang` on 8362acd wanted to post the following:

View the site at http://mooseframework.org/docs/PRs/9211/site

2017-06-14 20:12 UTC, moosebuild commented
Job `Moose Documentation:linux-clang` on 6dc6ea5 wanted to post the following:

View the site at http://mooseframework.org/docs/PRs/9211/site

2017-06-27 22:54 UTC, moosebuild commented
Job `Precheck:linux-gnu` on 7621a80 wanted to post the following:

Warning: This PR changes repo size by 53.47 MiB.

2017-06-28 16:12 UTC, moosebuild commented
Job [Documentation](https://www.moosebuild.org/job/97805/) on 2632495 wanted to post the following:

View the site [here](http://mooseframework.org/docs/PRs/9211/site)

2017-06-28 16:26 UTC, dschwen commented
> Job Precheck:linux-gnu on 7621a80 wanted to post the following:
> Warning: This PR changes repo size by 53.47 MiB.

Love that check @brianmoose , is it a new thing?

2017-06-28 16:32 UTC, brianmoose commented
@dschwen Yes, I put that in after the "BISON incident".

2017-06-28 16:47 UTC, gardnerru commented
HAHA! @acasagran @zahom @bwspenc every procedure change is a scar.

2017-06-28 17:35 UTC, moosebuild commented
Job [Documentation](https://www.moosebuild.org/job/97865/) on 6cfeb3d wanted to post the following:

View the site [here](http://mooseframework.org/docs/PRs/9211/site)

2017-06-29 13:48 UTC, moosebuild commented
Job [Documentation](https://www.moosebuild.org/job/97865/) on 6cfeb3d wanted to post the following:

View the site [here](http://mooseframework.org/docs/PRs/9211/site)

2017-07-05 23:19 UTC, moosebuild commented
Job [Test Intel](https://www.moosebuild.org/job/99329/) on 4465fb8 : invalidated by @aeslaughter

2017-07-06 19:57 UTC, aeslaughter commented
I have an update for Mastodon ready for these changes.

2017-07-06 20:46 UTC, brianmoose requested changes
Some minor typos and print usage.
I didn't look through the second commit as it has 1600+ files and GitHub doesn't handle it well.
I hope you had a script to edit all those files....
I did go over the website and things looked fine.

2017-07-06 20:46 UTC, brianmoose commented on python/MooseDocs/common/moose_docs_file_tree.py
> +        # Move along if path not in list of filesg
files

2017-07-06 20:46 UTC, brianmoose commented on python/MooseDocs/common/nodes.py
> +            filter[function]: A filter function, if it returns true keep the node.  If not supplied
`filter_`

2017-07-06 20:46 UTC, brianmoose commented on python/MooseDocs/extensions/app_syntax.py
> +                                     "shared syntax such as BCs/Pressue).")
Pressure

2017-07-06 20:46 UTC, brianmoose commented on python/MooseDocs/extensions/app_syntax.py
> +                                     "shared syntax such as BCs/Pressue).")
Pressure

2017-07-06 20:46 UTC, brianmoose commented on python/mooseutils/mooseutils.py
> +        print 'Using pip:\n    pip install package-name-here --user'
Probably want to use `print()` here and elsewhere.

2017-07-06 20:46 UTC, brianmoose commented on python/MooseDocs/commands/build.py
> +        print builder
`print()`

2017-07-06 20:46 UTC, brianmoose commented on python/MooseDocs/commands/check.py
> +        print syntax
`print()`

2017-07-06 22:21 UTC, brianmoose approved these changes

2017-07-06 22:22 UTC, merged