Copy bulk/shear modulus methods to ElasticityTensorTools
idaholab/moose pull request #9217
Opened 2017-06-02 16:53 UTC by bwspenc

ref #9215

This is the first step.  After I have removed all usages of the one
in RadialReturnStressUpdate in apps, I will remove these from that
class.

2017-06-02 16:56 UTC, dschwen commented on modules/tensor_mechanics/src/utils/ElasticityTensorTools.C
> +    mooseError("Check to ensure that your Elasticity Tensor is truly Isotropic");
The correct isotropy check is much more complicated and it is implemented in R4T. Do we want to keep this hack here?

2017-06-02 17:00 UTC, bwspenc commented on modules/tensor_mechanics/src/utils/ElasticityTensorTools.C
> +    mooseError("Check to ensure that your Elasticity Tensor is truly Isotropic");
Maybe it is best to just remove the check here entirely and assume that anyone using this has already done the more expensive check.

2017-06-02 17:26 UTC, moosebuild commented
Job `Moose Documentation:linux-clang` on 0a77766 wanted to post the following:

View the site at http://mooseframework.org/docs/PRs/9217/site

2017-06-02 22:19 UTC, moosebuild commented
Job `Precheck:linux-gnu` on 51cbb66 wanted to post the following:

Your code requires style changes.
In the top level of your repository, you can run:

`git clang-format 7b42590210c295326eb7069e9f090a9cb4dcd5dd`

Alternatively, apply the patch found [here](http://mooseframework.org/docs/PRs/9217/style.patch).
You can directly apply the patch by running:

`curl -s http://mooseframework.org/docs/PRs/9217/style.patch | git apply -v`

2017-06-02 22:27 UTC, bwspenc commented
@WilkAndy Would you mind taking a look at the changes I made to your models?  I'm adding a method that all classes that derive from StressUpdateBase must overwrite that is used to see whether the model requires the elasticity tensor to be isotropic.

The RadialReturnStressUpdate models require isotropic tensor, but I'm not sure about your models.  The Cosserat models definitely do not require an isotropic tensor, but I'm not sure about the DruckerPrager and WeakPlane models.

The reason for adding this check is that I'm removing the check from the function that these models call to get the shear modulus, so it should be checked somewhere else.  Your models are not calling that function, but they could.  It looks like they require other characteristics of the tensor, and it might be good to add similar checks for those.

2017-06-02 22:28 UTC, moosebuild commented
Job `Moose Documentation:linux-clang` on b70a0ad wanted to post the following:

View the site at http://mooseframework.org/docs/PRs/9217/site

2017-06-03 08:08 UTC, WilkAndy requested changes
Thanks @bwspenc

2017-06-03 08:08 UTC, WilkAndy commented on modules/tensor_mechanics/include/materials/CappedWeakInclinedPlaneStressUpdate.h
> +  bool requiresIsotropicTensor() override { return true; }
should be ```false```

2017-06-03 08:08 UTC, WilkAndy commented on modules/tensor_mechanics/include/materials/CappedWeakPlaneStressUpdate.h
> +  bool requiresIsotropicTensor() override { return true; }
should be ```false```

2017-06-03 12:22 UTC, bwspenc commented
Thanks for taking a look, @WilkAndy.  I fixed those two models.

2017-06-03 12:31 UTC, moosebuild commented
Job `Moose Documentation:linux-clang` on 14a6810 wanted to post the following:

View the site at http://mooseframework.org/docs/PRs/9217/site

2017-06-05 18:34 UTC, bwspenc commented
@dschwen I addressed @WilkAndy's comment, and I think this is ready to go.

2017-06-05 19:52 UTC, dschwen approved these changes

2017-06-05 19:52 UTC, merged