Output gap conductivity as a material property
idaholab/moose pull request #9229
Opened 2017-06-02 22:04 UTC by gambka

Closes #9226.

2017-06-02 22:05 UTC, moosebuild commented
Job `Precheck:linux-gnu` on 3f9beea wanted to post the following:

Your code requires style changes.
In the top level of your repository, you can run:

`git clang-format 7b42590210c295326eb7069e9f090a9cb4dcd5dd`

Alternatively, apply the patch found [here](http://mooseframework.org/docs/PRs/9229/style.patch).
You can directly apply the patch by running:

`curl -s http://mooseframework.org/docs/PRs/9229/style.patch | git apply -v`

2017-06-02 22:39 UTC, moosebuild commented
Job `Moose Documentation:linux-clang` on 36ad324 wanted to post the following:

View the site at http://mooseframework.org/docs/PRs/9229/site

2017-06-03 17:40 UTC, dschwen commented
Just a question: I do not understand this conceptually. The gap is an _unmeshed_ region. So how can you have a material property describe some gap property? The material property can only live where the gap is _not_. What is meaning of the property at the points where it is defined?

2017-06-04 18:30 UTC, gambka commented
We already output the gap conductance as a material property that is defined on the slave surface in thermal contact and zero elsewhere.  Conceptually this is done so we can visualize what the value of the gap conductance is or use the value elsewhere.  However, in my case I need the thermal conductivity of the gas within the gap for use in another material property and thus I followed the same procedure as the gap conductance.

2017-06-05 14:42 UTC, permcody commented on modules/heat_conduction/include/materials/GapConductance.h
> +  MaterialProperty<Real> & _gap_conductivity_property;
Minor: Do you really want the suffix `_propery` on there? We don't typically do this.

2017-06-05 14:43 UTC, permcody requested changes

2017-06-05 14:43 UTC, permcody commented on modules/heat_conduction/src/materials/GapConductance.C
> +    _gap_conductivity_property(declareProperty<Real>("gap_conductivity")),
Would you mind either adding a new test or updating an existing test so we can keep this small change working?
Thanks

2017-06-05 14:57 UTC, gambka commented on modules/heat_conduction/include/materials/GapConductance.h
> +  MaterialProperty<Real> & _gap_conductivity_property;
I would use _gap_conductivity as the member variable name but this name is already used in this class. I could use _gap_thermal_conductivity as the name instead.

2017-06-05 14:58 UTC, gambka commented on modules/heat_conduction/src/materials/GapConductance.C
> +    _gap_conductivity_property(declareProperty<Real>("gap_conductivity")),
I'll make a test.

2017-06-05 15:00 UTC, permcody commented on modules/heat_conduction/include/materials/GapConductance.h
> +  MaterialProperty<Real> & _gap_conductivity_property;
Oh! Well you might consider changing the other member. It's just there as a bulk property right? Do what you think is best.

2017-06-05 16:18 UTC, moosebuild commented
Job `Moose Documentation:linux-clang` on 2eaa36c wanted to post the following:

View the site at http://mooseframework.org/docs/PRs/9229/site

2017-06-05 21:35 UTC, permcody approved these changes

2017-06-05 21:35 UTC, merged