Option to set stress free temperature with AuxVariable
idaholab/moose pull request #9300
Opened 2017-06-14 18:56 UTC by reverendbedford

Modifies TensorMechanics thermal strain materials to allow users to set
some non-uniform thermal strain distribution via an AuxVariable,
initialized with an AuxKernel

closes #9291

2017-06-14 18:58 UTC, moosebuild commented
Job `Precheck:linux-gnu` on 890429a wanted to post the following:

Your code requires style changes.
In the top level of your repository, you can run:

`git clang-format 82aeca1a340abda68fe0f241f070986b9ca167b8`

Alternatively, apply the patch found [here](http://mooseframework.org/docs/PRs/9300/style.patch).
You can directly apply the patch by running:

`curl -s http://mooseframework.org/docs/PRs/9300/style.patch | git apply -v`

2017-06-14 19:05 UTC, dschwen requested changes

2017-06-14 19:05 UTC, dschwen commented on modules/tensor_mechanics/src/materials/ComputeThermalExpansionEigenstrainBase.C
> +  params.addCoupledVar("stress_free_aux",
No. Sorry, I may not have been clear enough. But please do not add all this complexity. Replace `params.addParam<Real>("stress_free_temperature"` with `params.addCoupledVar("stress_free_temperature"`!

MOOSE allows users to still specify a number value, so all old input files would still work. Ditch your helper function and just replace `_stress_free_temperature` with `_stress_free_temperature[_qp]`!

This should be a three line change!

2017-06-14 19:26 UTC, moosebuild commented
Job `Precheck:linux-gnu` on 050bc99 wanted to post the following:

Your code requires style changes.
In the top level of your repository, you can run:

`git clang-format 82aeca1a340abda68fe0f241f070986b9ca167b8`

Alternatively, apply the patch found [here](http://mooseframework.org/docs/PRs/9300/style.patch).
You can directly apply the patch by running:

`curl -s http://mooseframework.org/docs/PRs/9300/style.patch | git apply -v`

2017-06-14 19:34 UTC, moosebuild commented
Job `Precheck:linux-gnu` on 78037ff wanted to post the following:

Your code requires style changes.
In the top level of your repository, you can run:

`git clang-format 82aeca1a340abda68fe0f241f070986b9ca167b8`

Alternatively, apply the patch found [here](http://mooseframework.org/docs/PRs/9300/style.patch).
You can directly apply the patch by running:

`curl -s http://mooseframework.org/docs/PRs/9300/style.patch | git apply -v`

2017-06-14 19:37 UTC, moosebuild commented
Job `Precheck:linux-gnu` on 80df174 wanted to post the following:

Your code requires style changes.
In the top level of your repository, you can run:

`git clang-format 82aeca1a340abda68fe0f241f070986b9ca167b8`

Alternatively, apply the patch found [here](http://mooseframework.org/docs/PRs/9300/style.patch).
You can directly apply the patch by running:

`curl -s http://mooseframework.org/docs/PRs/9300/style.patch | git apply -v`

2017-06-14 19:39 UTC, moosebuild commented
Job `Precheck:linux-gnu` on 0e00b66 wanted to post the following:

Your code requires style changes.
In the top level of your repository, you can run:

`git clang-format 82aeca1a340abda68fe0f241f070986b9ca167b8`

Alternatively, apply the patch found [here](http://mooseframework.org/docs/PRs/9300/style.patch).
You can directly apply the patch by running:

`curl -s http://mooseframework.org/docs/PRs/9300/style.patch | git apply -v`

2017-06-14 19:41 UTC, reverendbedford commented
Apologies for all the failed formatting checks.  For some reason running clang-format -i over the changes on my machine doesn't put everything in compliance with the formatting  hook.

I also merged everything down to a single commit.

2017-06-14 19:42 UTC, dschwen requested changes
Yeah! Looks much better!

2017-06-14 19:42 UTC, dschwen commented on modules/tensor_mechanics/src/materials/ComputeThermalExpansionEigenstrainBase.C
> +                       "Reference temperature at which there is no "
I'd drop that change. The metadata provided by MOOSE automatically makes this redundant.

2017-06-14 19:42 UTC, dschwen commented on modules/tensor_mechanics/src/materials/ComputeMeanThermalExpansionEigenstrainBase.C
> +  // be neglected
would you mind reflowing these comments?

2017-06-14 19:48 UTC, moosebuild commented
Job `Precheck:linux-gnu` on 711d032 wanted to post the following:

Your code requires style changes.
In the top level of your repository, you can run:

`git clang-format 82aeca1a340abda68fe0f241f070986b9ca167b8`

Alternatively, apply the patch found [here](http://mooseframework.org/docs/PRs/9300/style.patch).
You can directly apply the patch by running:

`curl -s http://mooseframework.org/docs/PRs/9300/style.patch | git apply -v`

2017-06-14 19:50 UTC, dschwen commented on modules/tensor_mechanics/include/materials/ComputeThermalExpansionEigenstrainBase.h
> +   * expansion
This one, too

2017-06-14 19:52 UTC, moosebuild commented
Job `Precheck:linux-gnu` on a73155b wanted to post the following:

Your code requires style changes.
In the top level of your repository, you can run:

`git clang-format 82aeca1a340abda68fe0f241f070986b9ca167b8`

Alternatively, apply the patch found [here](http://mooseframework.org/docs/PRs/9300/style.patch).
You can directly apply the patch by running:

`curl -s http://mooseframework.org/docs/PRs/9300/style.patch | git apply -v`

2017-06-14 19:54 UTC, moosebuild commented
Job `Precheck:linux-gnu` on 5c4019a wanted to post the following:

Your code requires style changes.
In the top level of your repository, you can run:

`git clang-format 82aeca1a340abda68fe0f241f070986b9ca167b8`

Alternatively, apply the patch found [here](http://mooseframework.org/docs/PRs/9300/style.patch).
You can directly apply the patch by running:

`curl -s http://mooseframework.org/docs/PRs/9300/style.patch | git apply -v`

2017-06-14 20:00 UTC, reverendbedford commented on modules/tensor_mechanics/src/materials/ComputeThermalExpansionEigenstrainBase.C
> +                       "Reference temperature at which there is no "
OK

2017-06-14 20:58 UTC, dschwen approved these changes
Looks good to me now. Thanks!

2017-06-14 20:59 UTC, moosebuild commented
Job `Moose Documentation:linux-clang` on 03029fb wanted to post the following:

View the site at http://mooseframework.org/docs/PRs/9300/site

2017-06-14 21:26 UTC, dschwen requested changes
We'll also need an app patch for Bison. I can put that in.

2017-06-14 21:26 UTC, dschwen commented on modules/tensor_mechanics/src/materials/ComputeMeanThermalExpansionEigenstrainBase.C
> +  meanThermalExpansionCoefficientDerivative(_stress_free_temperature[_qp]);
This needs to be removed now. `_qp` is not set (and the variables not prepared) in `initialSetup` and we might just as well error out later.

2017-06-15 21:57 UTC, reverendbedford commented
I made the change to meanThermalExpansionCoefficientDerivative.

2017-06-16 13:40 UTC, dschwen requested changes

2017-06-16 13:40 UTC, dschwen commented on modules/tensor_mechanics/src/materials/ComputeMeanThermalExpansionEigenstrainBase.C
> -      _alphabar_stress_free_temperature * (_stress_free_temperature - referenceTemperature());
Waaaait a minute, now you are not initializing those two members, but you still use them below. The solution here is to remove these member variables and compute these values on the fly below.

2017-06-16 13:41 UTC, dschwen commented
Ha, this ends up being a bit more than 3 lines :-D. Thanks for sticking with it!

2017-06-16 13:46 UTC, moosebuild commented
Job `Moose Documentation:linux-clang` on d294ade wanted to post the following:

View the site at http://mooseframework.org/docs/PRs/9300/site

2017-06-16 16:36 UTC, moosebuild commented
Job `Precheck:linux-gnu` on 1bbc43d wanted to post the following:

Your code requires style changes.
In the top level of your repository, you can run:

`git clang-format 1990a2ae8f6a1824862d6d5c5036b0fbc8ccf7a1`

Alternatively, apply the patch found [here](http://mooseframework.org/docs/PRs/9300/style.patch).
You can directly apply the patch by running:

`curl -s http://mooseframework.org/docs/PRs/9300/style.patch | git apply -v`

2017-06-16 16:40 UTC, reverendbedford commented on modules/tensor_mechanics/src/materials/ComputeMeanThermalExpansionEigenstrainBase.C
> -      _alphabar_stress_free_temperature * (_stress_free_temperature - referenceTemperature());
I should probably take the time to understand what I'm doing before I do it.  Anyway, made the fix.

2017-06-16 18:20 UTC, moosebuild commented
Job `Moose Documentation:linux-clang` on 5dc24d3 wanted to post the following:

View the site at http://mooseframework.org/docs/PRs/9300/site

2017-06-16 19:42 UTC, dschwen approved these changes
I think this looks good now. @bwspenc, want to give it a look over?

2017-06-16 20:11 UTC, bwspenc approved these changes
Looks good to me.  I'll merge this now and get a fix for BISON in the pipeline.

2017-06-16 20:11 UTC, merged