Compliance tensor calculation added and used in TensorMechanics
idaholab/moose pull request #9323
Opened 2017-06-16 06:11 UTC by WilkAndy

Fixes #9149 

Could @bwspenc or @dschwen look at the code carefully?  I'm not convinced this is a super awesome thing to do, but it doesn't look too disastrous.

2017-06-16 06:13 UTC, moosebuild commented
Job `Precheck:linux-gnu` on 99e1d8c wanted to post the following:

Your code requires style changes.
In the top level of your repository, you can run:

`git clang-format 9b325b8b535fb5bcf2cfc4b68220dc2099be22b4`

Alternatively, apply the patch found [here](http://mooseframework.org/docs/PRs/9323/style.patch).
You can directly apply the patch by running:

`curl -s http://mooseframework.org/docs/PRs/9323/style.patch | git apply -v`

2017-06-16 06:33 UTC, moosebuild commented
Job `Moose Documentation:linux-clang` on ecc7a6c wanted to post the following:

View the site at http://mooseframework.org/docs/PRs/9323/site

2017-06-16 13:32 UTC, dschwen requested changes
I would really like to see that in a derived class. It adds a level of complexity that most people will probably not want to deal with.

2017-06-16 13:32 UTC, dschwen commented on modules/tensor_mechanics/src/materials/ComputeMultipleInelasticStress.C
> +    _has_compliance(hasMaterialProperty<RankFourTensor>(_base_name + "compliance_tensor")),
Uhm, you are doing `hasMaterialProperty` in the constructor again. This introduces a construction order dependence which we really want to avoid!

2017-06-16 21:36 UTC, WilkAndy commented on modules/tensor_mechanics/src/materials/ComputeMultipleInelasticStress.C
> +    _has_compliance(hasMaterialProperty<RankFourTensor>(_base_name + "compliance_tensor")),
Yes!  This really bugged me, but i don't know how to get around it.   While writing this PR i was pretty unconvinced of its usefulness and robustness and unless this issue can be resolved in a simple way, the PR should probably be terminated.

2017-06-20 13:54 UTC, bwspenc reviewed
I assume when @dschwen is referring putting this into a derived class, he's talking about the part of this that computes the elasticity tensor, and I agree with that sentiment.  The changes to `ComputeMultipleInelasticStress` seem pretty minimal and reasonable.

I could see either putting the code that computes the compliance into a derived class that computes both the elasticity and compliance tensors, or maybe making a separate material model that only computes the compliance tensor.

2017-06-20 13:54 UTC, bwspenc commented on modules/tensor_mechanics/src/materials/ComputeMultipleInelasticStress.C
> +    _has_compliance(hasMaterialProperty<RankFourTensor>(_base_name + "compliance_tensor")),
You can call `hasMaterialProperty()` in `initialSetup()` to get around this.

2017-06-20 14:49 UTC, dschwen commented on modules/tensor_mechanics/src/materials/ComputeMultipleInelasticStress.C
> +    _has_compliance(hasMaterialProperty<RankFourTensor>(_base_name + "compliance_tensor")),
No, he can **not**. He can not get the material property after construction. And `hasMaterialProperty` will not return the correct (expected) result if he is using the `getDefaultMaterialProperty` call.

2017-06-20 15:04 UTC, dschwen commented on modules/tensor_mechanics/src/materials/ComputeMultipleInelasticStress.C
> +    _has_compliance(hasMaterialProperty<RankFourTensor>(_base_name + "compliance_tensor")),
This needs to be a user supplied parameter unfortunately.

2017-06-20 15:45 UTC, bwspenc commented on modules/tensor_mechanics/src/materials/ComputeMultipleInelasticStress.C
> +    _has_compliance(hasMaterialProperty<RankFourTensor>(_base_name + "compliance_tensor")),
Oh yeah, we had this same conversation a few days ago.  I think I've got that in my head now.

2017-06-20 22:56 UTC, WilkAndy commented
Thanks guys.  i think i'm going to close this PR and issue.  I don't see much point in creating a separate class that computes the elasticity tensor and compliance tensor.  The compliance tensor is really only used in earnest in ComputeMultipleInelasticStress and only when you have multiple inelastic models each constructing its own consistent tangent operator.  Because i can't use "has_compliance" in the constructor, i think any other way of doing this (like creating another version of ComputeMultipleInelasticStress that uses the compliance tensor) will add unnecessary complications to the code.

2017-06-21 16:23 UTC, dschwen commented
Let's close for now. I might have an idea how to approach this, but it will be a while until I get to it.

2017-06-21 16:23 UTC, closed without merging