Imrpove documentation for 3-phase KKS phase-field model
idaholab/moose pull request #9334
Opened 2017-06-16 22:49 UTC by laagesen

Closes #9318

2017-06-16 23:00 UTC, dschwen requested changes

2017-06-16 23:00 UTC, dschwen commented on docs/content/documentation/systems/Kernels/phase_field/KKSMultiPhaseConcentration.md
>  # KKSMultiPhaseConcentration
Please remove the `<!-- MOOSE Documentation Stub: Remove this when content is added. -->` comments

2017-06-16 23:11 UTC, moosebuild commented
Job `Moose Documentation:linux-clang` on 7fa3eb4 wanted to post the following:

View the site at http://mooseframework.org/docs/PRs/9334/site

2017-06-19 15:01 UTC, moosebuild commented
Job `Moose Documentation:linux-clang` on 28bc3b9 wanted to post the following:

View the site at http://mooseframework.org/docs/PRs/9334/site

2017-06-21 16:20 UTC, dschwen commented
Ping @laagesen

2017-06-21 16:41 UTC, laagesen commented
There were two changes we talked about, first generalizing some statements in the MultiPhaseConcentration kernel and second adding a page that ties all the kernels for this model together. I think the second step is going to take longer, so how about if I just do the first thing for now and we can merge this? Then I'll open a different issue to add a new page to tie all the kernels together later.

2017-06-21 21:32 UTC, moosebuild commented
Job `Moose Documentation:linux-clang` on 7dddb45 wanted to post the following:

View the site at http://mooseframework.org/docs/PRs/9334/site

2017-06-21 22:44 UTC, dschwen approved these changes

2017-06-21 22:45 UTC, merged