Error-check split, simplify code
idaholab/moose pull request #9405
Opened 2017-06-28 19:22 UTC by dschwen

Closes #9404

2017-06-28 19:34 UTC, dschwen commented
Btw. this adds a new `Moose::stringify` specialization

```
template <typename T>
std::string
stringify(const std::vector<T> & v)
```

Which allows me to save quite a bit of code in `Split`. It generates a comma separated list of stringified vector entries. Might be useful in other places as well.

2017-06-28 19:40 UTC, moosebuild commented
Job [Documentation](https://www.moosebuild.org/job/97933/) on 651502c wanted to post the following:

View the site [here](http://mooseframework.org/docs/PRs/9405/site)

2017-06-28 20:56 UTC, permcody commented on framework/include/utils/Conversion.h
> +std::string stringify(const std::string & t);
We have an "infix iterator" header: https://github.com/idaholab/moose/blob/devel/framework/include/utils/InfixIterator.h that allows you to do this kind of thing in a very generic context. @aeslaughter was also trying to add a `join()` method to MooseUtils, but with the iterator and the STL you can insert commas between items in any context pretty easily. 

We certainly don't need two (or any 😉).
https://github.com/idaholab/moose/pull/9242/files#diff-b667c5b178211dc59f0967396aeaf061R399

2017-06-28 21:33 UTC, dschwen commented on framework/include/utils/Conversion.h
> +std::string stringify(const std::string & t);
`infix_iterator` is not used in MOOSE. I suggest we just delete that one.

2017-06-28 21:39 UTC, permcody commented on framework/include/utils/Conversion.h
> +std::string stringify(const std::string & t);
That's true, but `infix_ostream_iterator` is used all over the place!

2017-06-29 17:21 UTC, permcody requested changes
Per our discussion, we'd like a more general capability for this operation since we already have one. I should take as input the delimiter and work with more containers.

2017-06-29 17:58 UTC, moosebuild commented
Job [Documentation](https://www.moosebuild.org/job/98176/) on eb82e9e wanted to post the following:

View the site [here](http://mooseframework.org/docs/PRs/9405/site)

2017-06-29 18:07 UTC, dschwen commented
Have you seen the unit test?!

2017-06-29 20:40 UTC, permcody approved these changes
👍

2017-06-29 20:40 UTC, merged