Scalar scaling fix
idaholab/moose pull request #9451
Opened 2017-07-05 22:29 UTC by roystgnr

I believe this should fix #9450 if my understanding of the problem is correct.

The second commit here trips _GLIBCXX_DEBUG assertion failures on the perverse N_proc > N_elem + 1 case, verifying an attempt to access uninitialized data, and the third commit fixes that failure, so there's at least a little justification for my belief.

We should change that second commit to be more robust (NaNs in opt mode?) before merging this, but I'll wait for a bit of discussion on exactly how we should do so; for now I just want to make sure that Civet doesn't think I've broken anything else.

2017-07-05 22:31 UTC, moosebuild commented
Job [Precheck](https://www.moosebuild.org/job/99279/) on e173806 wanted to post the following:

Your code requires style changes.
In the top level of your repository, you can run:

`git clang-format 0c2822da3529ba3d36a72b1b1b603b538da6643b`

Alternatively, apply the patch found [here](http://mooseframework.org/docs/PRs/9451/style.patch).
You can directly apply the patch by running:

`curl -s http://mooseframework.org/docs/PRs/9451/style.patch | git apply -v`

2017-07-05 22:56 UTC, moosebuild commented
Job [Documentation](https://www.moosebuild.org/job/99294/) on ef18030 wanted to post the following:

View the site [here](http://mooseframework.org/docs/PRs/9451/site)

2017-07-06 16:34 UTC, roystgnr commented
1e-5 absolute error is kind of borderline; too small to be sure it's a bug, too big to ignore unless we can be sure it's not a solver tolerance issue.  I'll look into it.

2017-07-06 18:28 UTC, moosebuild commented
Job [Precheck](https://www.moosebuild.org/job/99604/) on d5ad750 wanted to post the following:

Your code requires style changes.
In the top level of your repository, you can run:

`git clang-format 0c2822da3529ba3d36a72b1b1b603b538da6643b`

Alternatively, apply the patch found [here](http://mooseframework.org/docs/PRs/9451/style.patch).
You can directly apply the patch by running:

`curl -s http://mooseframework.org/docs/PRs/9451/style.patch | git apply -v`

2017-07-06 23:55 UTC, roystgnr commented
Do we have an "App tests debug" test that we can manually run?  That _GLIBCXX_DEBUG trick caught a corner-case bug in the ScalarVariable postprocessor, and it would be nice to ensure that there aren't any similar problems in user code.

2017-07-06 23:58 UTC, roystgnr commented
I can replicate the generalized_plane_strain_tm_contact.generalized_plane_strain_tm_contact bug, BTW, but I don't yet understand it.  I've ruled out "test is running with too low a solver tolerance", and I hope to soon confirm or deny "gold standard was generated with too low a solver tolerance", but if neither theory is correct I've got no leads.

2017-07-10 18:53 UTC, permcody commented
I'm not entirely sure that your change is necessarily a bug. We've tripped these tests several times over the last few years with diffs that look like yours. Sometimes it's just the differences in the way we calculate things that cause these issues. Many of these tests are very sensitive. Rather than you continuing to look for the reason perhaps we could tackle it from the other end (i.e. involve one of the test builders to look at the new solutions to see if they still look reasonable). I'm happy to tag someone...

2017-07-10 19:53 UTC, roystgnr commented
Yeah, I'd appreciate it.  I don't get any other regression test failures (after I rooted out a weird MKL red herring), but I'm not understanding this one.  The diffs are around 1e-5, in a field whose peak solution is around 2e3, so I'd normally laugh and chalk that up to solver tolerance, but futzing with tolerances hasn't fixed anything for me, and I'm loathe to just crank up a huge abs tolerance floor on a test case I'm unfamiliar with.

2017-07-10 19:59 UTC, permcody commented
@bwspenc, or @hchen139 maybe one of you can shed some light on this test. Looking at the history it looks like it has given us fits before. The L2 norm of the residual of some of the timesteps is 1e-5-1e-6 so I'm surprised it doesn't diff more often. I really don't want Roy to try to figure out why his change is only breaking one or two of these very sensitive test when the rest of the suite passes.

2017-07-10 20:00 UTC, permcody commented
@fdkong - previously skipped this test: https://github.com/idaholab/moose/commit/c88bc1a6ffeca97ae6785b5eb9463c98e5acbc47

2017-07-13 19:02 UTC, permcody commented
@bwspenc and @hchen139 - Can one of you take a look at the test results here and see if you think these diffs are significant. You can read the comments above and the original issue but we are stuck trying to figure out if we've broken something here. Unless you are completely sure about the results in this test, it might actually be a fix. Any help would be appreciated, we'd like to get his patch in.

2017-07-17 20:35 UTC, bwspenc commented
@hchen139 is looking into this.  I doubt this is a problem with the code.  It looks like the test is just a little too sensitive to small numerical issues.  We'll plan on just submitting a separate PR to improve the test, unless we hear otherwise.

2017-07-21 18:13 UTC, roystgnr commented
We should kick those tests to see if they work now that #9531 is in.

I've got to handle those robustness issues, too, so I'll do that shortly and we can just wait for that push to trigger new tests.

2017-07-21 21:10 UTC, roystgnr commented
Ah, hell.  I just rebased on master rather than devel, didn't I...

2017-07-21 21:11 UTC, moosebuild commented
Job [Precheck](https://www.moosebuild.org/job/102826/) on 480965b wanted to post the following:

Your code requires style changes.
In the top level of your repository, you can run:

`git clang-format 669f0516bb387a2bc55900114d73ec47baad83e8`

Alternatively, apply the patch found [here](http://mooseframework.org/docs/PRs/9451/style.patch).
You can directly apply the patch by running:

`curl -s http://mooseframework.org/docs/PRs/9451/style.patch | git apply -v`

2017-07-21 21:17 UTC, roystgnr commented
That should fix it.  If this passes tests now then IMHO it's good to go.

2017-07-21 21:18 UTC, moosebuild commented
Job [Precheck](https://www.moosebuild.org/job/102835/) on 912f1ad wanted to post the following:

Your code requires style changes.
In the top level of your repository, you can run:

`git clang-format 669f0516bb387a2bc55900114d73ec47baad83e8`

Alternatively, apply the patch found [here](http://mooseframework.org/docs/PRs/9451/style.patch).
You can directly apply the patch by running:

`curl -s http://mooseframework.org/docs/PRs/9451/style.patch | git apply -v`

2017-07-21 21:38 UTC, roystgnr commented
Oh, come on!  My formatting looks better before the demanded patch.

2017-07-24 14:02 UTC, andrsd requested changes

2017-07-24 14:02 UTC, andrsd commented on framework/src/postprocessors/ScalarVariable.C
> +// libMesh includes
cpt. Obvious.

2017-07-24 14:02 UTC, andrsd commented on framework/src/postprocessors/ScalarVariable.C
> +  this->comm().min(returnval);
use `gatherMin(...)`

2017-07-24 14:02 UTC, andrsd commented on framework/src/base/MooseVariableScalar.C
> +// C++
Remove this line, it is cpt. Obvious.

2017-07-24 14:12 UTC, roystgnr commented on framework/src/postprocessors/ScalarVariable.C
> +  this->comm().min(returnval);
Will do.

2017-07-24 14:18 UTC, roystgnr commented on framework/src/base/MooseVariableScalar.C
> +// C++
```
roystgnr@leela:(roys_junk3) ~/git/moose-fresh
$ egrep -i '// (system|C\+\+)' framework/include/*/*.h | wc
     35     118    2112
roystgnr@leela:(roys_junk3) ~/git/moose-fresh
$ egrep -i '// libMesh includes' framework/include/*/*.h | wc
     70     210    4668
```

Should I get the other hundred instances while I'm at it?  That should probably be a separate PR.

I'd rather not remove any of them at all.  When I was removing unnecessary header dependencies, I discovered that dependency-tracking best practices (e.g. https://stackoverflow.com/a/2762596 ) were followed less often than not.  I'd like to have *some* comments that express "This isn't random order; someone put these headers below those headers for a reason, and here's what category they were sorted by".

2017-07-24 14:25 UTC, roystgnr commented
Looks like we're still seeing exodiffs on the same test, even after #9531 cranked down the solver tolerance?  I'll see if I can still replicate.

2017-07-24 14:50 UTC, bwspenc commented
@roystgnr Maybe we need to also loosen up the exodiff tolerances a bit on that test.  I'll look at the results after this round of tests runs.

2017-07-24 15:20 UTC, andrsd commented on framework/src/base/MooseVariableScalar.C
> +// C++
I understand that grouping header files is a good thing, but I also think people already do that. That's why I think we do not need comments like "Put C++/libmesh headers here"...

2017-07-24 17:48 UTC, moosebuild commented
Job [TBB Test](https://www.moosebuild.org/job/102866/) on 8ddc378 : invalidated by @bwspenc

retest after fixing problematic test

2017-07-24 17:48 UTC, moosebuild commented
Job [TBB Test](https://www.moosebuild.org/job/102866/) on 8ddc378 : invalidated by @bwspenc

retest after fixing problematic test

2017-07-24 17:48 UTC, moosebuild commented
Job [Pthreads Test](https://www.moosebuild.org/job/102865/) on 8ddc378 : invalidated by @bwspenc

retest after fixing problematic test

2017-07-24 17:49 UTC, moosebuild commented
Job [Modules debug](https://www.moosebuild.org/job/102863/) on 8ddc378 : invalidated by @bwspenc

retest after fixing problematic test

2017-07-24 18:28 UTC, roystgnr commented on framework/src/base/MooseVariableScalar.C
> +// C++
I still disagree, but I'd rather get this merged than argue, so I'll push one more commit stripping those two comments just as soon as these retests finish.

That said,
```
roystgnr@zappa:(scalar_scaling_fix) ~/git/moose/modules
$ git blame ../framework/src/base/MooseVariableScalar.C | tail -n +22 | head -n 5
e4501c55 (David Andrs       2012-02-06 08:48:49 +0000  22) // libMesh
ff8a0bdc (Cody Permann      2013-02-07 12:33:07 +0000  23) #include "libmesh/numeric_vector.h"
02f63040 (John W. Peterson  2015-11-03 10:18:43 -0700  24) #include "libmesh/dof_map.h"
e4501c55 (David Andrs       2012-02-06 08:48:49 +0000  25) 
b99fd8ac (Roy H. Stogner    2017-07-05 17:16:21 -0500  26) // C++
```

https://en.wikipedia.org/wiki/I_learned_it_by_watching_you!   ;-)

2017-07-24 18:45 UTC, andrsd commented on framework/src/base/MooseVariableScalar.C
> +// C++
Well, originally the code looked like this:
```
// libMesh
#include "numeric_vector.h"
#include "dof_map.h"
```
Then, you guys in libmesh added "libmesh/", see `git show ff8a0bdc` for the change. At that point we should have dropped `// libMesh` comments, but they stayed. I really do think they are cpt. Obvious.  With the same logic, I do not think we need `// C++`

2017-07-24 18:57 UTC, roystgnr commented
Tests passed, so this should be good to merge.  That last commit was just comment deletions.

2017-07-24 18:59 UTC, andrsd approved these changes

2017-07-24 22:00 UTC, merged