Refactor Tensor Mechanics Guarantees
idaholab/moose pull request #9484
Opened 2017-07-11 22:05 UTC by dschwen

This adds one enum class and two new classes that can be inherited from in addition to the MOOSE base classes

* `Guarantee` is an `enum class` that contains the set of valid guarantees. This can be expanded as necessary.
* `GuaranteeProvider` can be added to Material classes and provides the `void issueGuarantee(MaterialPropertyName, Guarantee)` function that add guarantee metadata to a material property declared by the class.
* `GuaranteeConsumer` can be added to Materials and kernels and provides the `bool hasGuaranteedMaterialProperty(MaterialPropertyName, Guarantee)` method that checks if all materials on each block that provide a given material property issue the required guarantee.

Closes #8881 (because this as close as we will ever get this)

2017-07-11 22:06 UTC, moosebuild commented
Job [Precheck](https://www.moosebuild.org/job/100524/) on ec70e10 wanted to post the following:

Your code requires style changes.
In the top level of your repository, you can run:

`git clang-format f4c4a81b4d488a58866818e7ab3208783f8aff9b`

Alternatively, apply the patch found [here](http://mooseframework.org/docs/PRs/9484/style.patch).
You can directly apply the patch by running:

`curl -s http://mooseframework.org/docs/PRs/9484/style.patch | git apply -v`

2017-07-11 23:22 UTC, moosebuild commented
Job [Documentation](https://www.moosebuild.org/job/100539/) on da922ea wanted to post the following:

View the site [here](http://mooseframework.org/docs/PRs/9484/site)

2017-07-11 23:44 UTC, sapitts commented
I vaguely remember _someone_ telling @bwspenc that using Atom would prevent these sorts of clang formatting errors....
But in seriousness, this line with the error message, which has obviously been formatted via clang format once, caught me on a merge request too; is there a way to prevent clang format from complaining about changes which it made itself on a previous commit?

2017-07-12 00:56 UTC, moosebuild commented on libmesh
> +Subproject commit 9a3100a84c2d5f16126c6d8df57d068c19f15e45
**Caution!** This contains a submodule update

2017-07-12 16:06 UTC, dschwen commented
Bison PR is standing by.

2017-07-12 17:12 UTC, bwspenc requested changes
This looks good.  Just a few very minor things to address.

2017-07-12 17:12 UTC, bwspenc commented on modules/tensor_mechanics/src/utils/GuaranteeConsumer.C
> +    // If block materials exist, look if any declare the elasticity tensor
This has general applicability beyond the elasticity tensor, so I'd change "elasticity tensor" to "material property"

2017-07-12 17:12 UTC, bwspenc commented on modules/tensor_mechanics/src/utils/GuaranteeConsumer.C
> +          auto elastic_mat = dynamic_cast<GuaranteeProvider *>(mat.get());
Per the above comment, 'elastic_mat' probably isn't a great variable name here.

2017-07-12 17:12 UTC, bwspenc commented on modules/tensor_mechanics/include/utils/Guarantee.h
> +/****************************************************************/
Would it be better to name this something like 'PropertyGuarantee' just to be a little more descriptive about what it does?  I don't want to make everything have huge names, and I'm not that set on renaming it, so I'll leave that up to you.

2017-07-12 21:31 UTC, dschwen commented
@sapitts are you waiting for #9484 to use the new guarantees system to implement this?

2017-07-12 22:34 UTC, bwspenc approved these changes

2017-07-12 22:35 UTC, bwspenc commented
This breaks BISON and MASTODON, but we have patches ready.

2017-07-12 22:35 UTC, merged