DG material coverage check
idaholab/moose pull request #9495
Opened 2017-07-13 21:14 UTC by YaqiWang

Close #9482.

2017-07-13 21:15 UTC, moosebuild commented
Job [Precheck](https://www.moosebuild.org/job/101084/) on 09f0728 wanted to post the following:

Your code requires style changes.
In the top level of your repository, you can run:

`git clang-format e312dc46f6b83ee9a6d03a9d934f0548df0f2ecc`

Alternatively, apply the patch found [here](http://mooseframework.org/docs/PRs/9495/style.patch).
You can directly apply the patch by running:

`curl -s http://mooseframework.org/docs/PRs/9495/style.patch | git apply -v`

2017-07-13 21:34 UTC, moosebuild commented
Job [Documentation](https://www.moosebuild.org/job/101099/) on 0d2253f wanted to post the following:

View the site [here](http://mooseframework.org/docs/PRs/9495/site)

2017-07-14 13:59 UTC, permcody commented
@lindsayad - I see that this check breaks one of your tests. Could you confirm that there is indeed a problem?

2017-07-14 15:46 UTC, YaqiWang commented
I cannot see the test?

2017-07-14 16:45 UTC, permcody commented
@YaqiWang - Log in, if you still can't see it, let us know.

2017-07-14 19:27 UTC, moosebuild commented
Job [Precheck](https://www.moosebuild.org/job/101403/) on f52b270 wanted to post the following:

Your code requires style changes.
In the top level of your repository, you can run:

`git clang-format e312dc46f6b83ee9a6d03a9d934f0548df0f2ecc`

Alternatively, apply the patch found [here](http://mooseframework.org/docs/PRs/9495/style.patch).
You can directly apply the patch by running:

`curl -s http://mooseframework.org/docs/PRs/9495/style.patch | git apply -v`

2017-07-14 19:32 UTC, YaqiWang commented on framework/src/dgkernels/DGKernel.C
> +    TwoMaterialPropertyInterface(this, boundaryRestricted() ? std::set<SubdomainID>() : blockIDs(), boundaryIDs()),
I checked the failing test in Zapdos. Nothing wrong there. For interface kernels, the coverage check is much more complicated. We need to call `markMatPropRequested` differently in `getMaterialProperty` and `getNeighborMaterialProperty` based on the subdomains attaching the internal boundary. The material property could be provided by block or boundary materials on the master side, which makes things more complicated. @permcody has an idea in his mind that we the coverage check in front by looping though elements and sides and deprecated the current checking method.

Thus, I have `boundaryRestricted() ? std::set<SubdomainID>() : blockIDs(), boundaryIDs()` here as a heck to enable the check for `DGKernel` and `InternalSideUserObject` but skip the check for `InterfaceKernel`. I think this is worthwhile to be pushed into framework, but need to have others' opinion.

2017-07-14 19:34 UTC, YaqiWang commented on framework/src/dgkernels/DGKernel.C
> +        this, boundaryRestricted() ? std::set<SubdomainID>() : blockIDs(), boundaryIDs()),
I checked the failing test in Zapdos. Nothing wrong there. For interface kernels, the coverage check is much more complicated. We need to call markMatPropRequested differently in `getMaterialProperty` and `getNeighborMaterialProperty` based on the subdomains attaching the internal boundary. The material property could be provided by block or boundary materials on the master side, which makes things more complicated. @permcody has an idea in his mind that we the coverage check in front by looping though elements and sides and deprecated the current checking method.

Thus, I have `boundaryRestricted() ? std::set<SubdomainID>() : blockIDs(), boundaryIDs()` here as a heck to enable the check for `DGKernel` and `InternalSideUserObject` but skip the check for InterfaceKernel. I think this is worthwhile to be pushed into framework, but need to have others' opinion.

2017-07-14 20:30 UTC, permcody commented on framework/src/dgkernels/DGKernel.C
> +        this, boundaryRestricted() ? std::set<SubdomainID>() : blockIDs(), boundaryIDs()),
At the very least you need to document the hack in the source code so we can find it later and remove it.

2017-07-14 22:59 UTC, YaqiWang commented
@permcody This fix is good now. I do not think we have complete boundary material coverage test, but that can be done in the two places I marked with `FIXME` in this PR.

2017-07-14 23:53 UTC, moosebuild commented
Job [Precheck](https://www.moosebuild.org/job/101579/) on 1c6bca1 wanted to post the following:

Your code requires style changes.
In the top level of your repository, you can run:

`git clang-format e312dc46f6b83ee9a6d03a9d934f0548df0f2ecc`

Alternatively, apply the patch found [here](http://mooseframework.org/docs/PRs/9495/style.patch).
You can directly apply the patch by running:

`curl -s http://mooseframework.org/docs/PRs/9495/style.patch | git apply -v`

2017-07-16 22:33 UTC, lindsayad commented
There must have been a force push here because it looks like all Zapdos tests are working...?

2017-07-17 15:34 UTC, YaqiWang commented
@lindsayad Yes.

2017-08-02 04:39 UTC, YaqiWang commented
@permcody, I will fix the failing test caused by a mesh modifier not supporting distributed mesh. Other than this, this PR is good for review.

2017-08-02 15:35 UTC, permcody requested changes

2017-08-02 15:35 UTC, permcody commented on framework/src/materials/MaterialPropertyInterface.C
> +    _block_restricted(block_ids.find(Moose::ANY_BLOCK_ID) == block_ids.end()),
This doesn't seem like the correct design. MaterialPropertyInterface shouldn't have these block/boundary restrictable Booleans as members. It's just an interface class. Can they not be moved to the TwoMaterialPropertyInterface class which is intended to understand block/boundary restriction? At the very least, you should be obtaining this information from the Block/Boundary restrictable objects directly, not recoding it here.

2017-08-02 15:35 UTC, permcody commented on framework/src/materials/MaterialPropertyInterface.C
> +    _block_restricted(block_ids.find(Moose::ANY_BLOCK_ID) == block_ids.end()),
Yeah, looking through this PR, I don't see where these Booleans are used in this class. Only the derived class where you have access to the other objects for this information.

2017-08-31 16:10 UTC, permcody commented
This PR is just about ready to hit our 30 day inactivity limit.

2017-08-31 16:21 UTC, YaqiWang commented
Although the check is necessary, the fix proposed here may not be right. I will let it die and leave the issue open.

2017-08-31 16:35 UTC, YaqiWang commented
BTW, those three tests here have value and can be used with the right fix.

2017-09-05 18:53 UTC, permcody commented
@aeslaughter - Just pinging you on this. I don't think @YaqiWang is going to work on this further and I'm not sure it's critical for anybody to jump on at the moment. Probably will close for now.

2017-09-21 17:06 UTC, permcody commented
@aeslaughter - Any interest in fixing this? Perhaps your other change will help here?

2017-09-21 17:29 UTC, aeslaughter commented
This line should fix this: https://github.com/idaholab/moose/blob/devel/framework/src/dgkernels/DGKernel.C#L81

2017-09-21 17:29 UTC, closed without merging

2017-09-21 19:05 UTC, YaqiWang commented
Look like the two tests I added in my last commit 18e60a2 do not error out still. Do I miss something? The DG test in 5c033e6 properly errors out.

2017-09-21 19:58 UTC, aeslaughter commented
@YaqiWang You are correct, your tests do not throw an error.

You have created a "block" material, but are using them in a boundary restricted object (BC). This is a separate issue I will need to investigate to understand better. I am not sure what we are doing in this case.