Add revokeGuarante, add constant in time ro ComputeElasticityTensor
idaholab/moose pull request #9517
Opened 2017-07-17 19:07 UTC by dschwen

This fixes the broken Falcon test. We can guarantee that tensors created by `ComputeElasticityTensor` are constant in time. However, the derived class `ComputeElasticityTensorCP` can rotate over time. I had to add a `revokeGuarantee` method to `GuaranteeProvider` to take back guarantees given in parent classes.

Refs #8881

2017-07-17 19:18 UTC, moosebuild commented
Job [Documentation](https://www.moosebuild.org/job/101758/) on 837c67f wanted to post the following:

View the site [here](http://mooseframework.org/docs/PRs/9517/site)

2017-07-17 19:19 UTC, sapitts requested changes
The code looks good to me, I have just a couple of comments on the comments.

2017-07-17 19:19 UTC, sapitts commented on modules/tensor_mechanics/src/materials/ComputeElasticityTensorCP.C
> +  // tensor might rotate over time
Might is probably the wrong word here--once the crystal plasticity model hits plasticity, the lattice will be rotated

2017-07-17 19:19 UTC, sapitts commented on modules/tensor_mechanics/src/utils/GuaranteeProvider.C
> +  // intentional insertion
Should this comment be updated?

2017-07-17 23:46 UTC, sapitts approved these changes
Looks good to me!

2017-07-18 01:31 UTC, dschwen commented
@permcody, it would be great to get this merged as it will remove the ugly yellow label from all those PRs...

2017-07-18 03:43 UTC, WilkAndy commented
Hang, on, i think that the broken FALCON test is just because it uses

> [./elasticity_tensor]
    type = ComputeElasticityTensor
    C_ijkl = '8.65E9 5.77E9' # young = 15GPa, poisson = 0.3
    fill_method = symmetric_isotropic
  [../]

which could use ```ComputeIsotropicElasticityTensor``` instead.

2017-07-18 13:27 UTC, brianmoose commented
FYI, Cody is on vacation for the next couple of weeks...

2017-07-18 17:28 UTC, dschwen commented
@WilkAndy , Yes, that test could use `ComputeIsotropicElasticityTensor`, but that is an orthogonal issue. This is not about an _isotropy_ guarantee, it is about a _constant in time_ guarantee. And `ComputeElasticityTensor` should issue that one, too!

2017-07-18 19:57 UTC, jwpeterson commented on modules/tensor_mechanics/src/utils/GuaranteeProvider.C
> +    it->second.erase(guarantee);
@dschwen If this is the last `guarantee` for a particular `prop_name` do you also want to remove `prop_name` from the map entirely, or is it OK for it to be there with an empty `std::set`?

2017-07-18 20:39 UTC, jwpeterson approved these changes

2017-07-18 20:39 UTC, merged