Remove an extra  matrix evaluation for nonlinear eigenvalue problems
idaholab/moose pull request #9527
Opened 2017-07-18 18:46 UTC by fdkong

For linear problems, it is unnecessary to attach the compute Jacobian and residual
callbacks.

For nonlinear problems, we should not assembly the matrix at the beginning of solve.
The Jacobian matrix and the residual are assembled by the callbacks.

Refs #7398

2017-07-18 19:02 UTC, moosebuild commented
Job [Documentation](https://www.moosebuild.org/job/101968/) on 78107e0 wanted to post the following:

View the site [here](http://mooseframework.org/docs/PRs/9527/site)

2017-07-18 19:37 UTC, andrsd requested changes

2017-07-18 19:37 UTC, andrsd commented on framework/src/base/EigenProblem.C
> +         solverParams()._eigen_solve_type == Moose::EST_MF_MONOLITH_NEWTON;
Notice that you are not using `_is_nonlinear_eigenvalue_solver` at all. If you know `solverParams()._eigen_solve_type` during construction, then I say set `_is_nonlinear_eigenvalue_solver` there and have this method return its value.

If you have to wait for `solverParams()._eigen_solve_type` to be set, then get rid of `_is_nonlinear_eigenvalue_solver`.

2017-07-18 19:43 UTC, fdkong commented on framework/src/base/EigenProblem.C
> +         solverParams()._eigen_solve_type == Moose::EST_MF_MONOLITH_NEWTON;
`solverParams()._eigen_solve_type` is set at the beginning of` solve()`, and so I will get rid of `_is_nonlinear_eigenvalue_solver`

Thanks, @andrsd

2017-07-19 19:44 UTC, fdkong commented
@andrsd, more comments?

2017-07-19 21:07 UTC, andrsd approved these changes

2017-07-19 21:08 UTC, merged