Add body force back in
idaholab/moose pull request #9529
Opened 2017-07-18 19:31 UTC by dschwen

Closes #9528

2017-07-18 19:59 UTC, jwpeterson commented
Looks like you are in conflict (lowers shades) with yourself.

2017-07-18 20:17 UTC, moosebuild commented
Job [Precheck](https://www.moosebuild.org/job/102019/) on cbc5ed1 wanted to post the following:

Your code requires style changes.
In the top level of your repository, you can run:

`git clang-format 20823f9635864c8ac0bbdb048455e4c3f93aa01e`

Alternatively, apply the patch found [here](http://mooseframework.org/docs/PRs/9529/style.patch).
You can directly apply the patch by running:

`curl -s http://mooseframework.org/docs/PRs/9529/style.patch | git apply -v`

2017-07-18 20:19 UTC, jwpeterson commented
Wait, why all the `const` additions? Seems extraneous to this PR, should at the very least be in a separate commit.

2017-07-18 20:59 UTC, dschwen commented
So that first clang-format failure was the result of clang-format needing two iterations to reach a stable configuration.

2017-07-18 21:07 UTC, moosebuild commented
Job [Documentation](https://www.moosebuild.org/job/102053/) on 68e6ff1 wanted to post the following:

View the site [here](http://mooseframework.org/docs/PRs/9529/site)

2017-07-18 22:23 UTC, jwpeterson requested changes
Need to fix bug in body force residual contribution.

2017-07-18 22:23 UTC, jwpeterson commented on modules/navier_stokes/src/kernels/INSMomentumBase.C
> +  const Real body_force_part = -_rho[_qp] * _gravity(_component);
I'd do a fixup commit on this one multiplying by the test function...

2017-07-18 22:29 UTC, jwpeterson commented
Oh, and we need to add the hydrostatic test case that exercises the term you uncommented...

2017-07-19 14:40 UTC, jwpeterson approved these changes

2017-07-19 14:41 UTC, merged