adding trilinear interpolation class
idaholab/moose pull request #9532
Opened 2017-07-19 16:45 UTC by CiCixP

closes #9516

2017-07-19 17:14 UTC, moosebuild commented
Job [Documentation](https://www.moosebuild.org/job/102348/) on 6746eb0 wanted to post the following:

View the site [here](http://mooseframework.org/docs/PRs/9532/site)

2017-07-19 19:14 UTC, moosebuild commented
Job [App tests](https://www.moosebuild.org/job/102347/) on 6746eb0 : invalidated by @andrsd

2017-07-19 19:18 UTC, andrsd submitted a review, later dismissed

2017-07-19 20:15 UTC, andrsd commented
Hold on with merging this, we need to add a few `const`s.

2017-07-19 20:31 UTC, moosebuild commented
Job [Precheck](https://www.moosebuild.org/job/102405/) on daebe66 wanted to post the following:

Your code requires style changes.
In the top level of your repository, you can run:

`git clang-format fb990476e151324c2f42d0290adc3d2011d3a6b4`

Alternatively, apply the patch found [here](http://mooseframework.org/docs/PRs/9532/style.patch).
You can directly apply the patch by running:

`curl -s http://mooseframework.org/docs/PRs/9532/style.patch | git apply -v`

2017-07-19 21:19 UTC, dschwen requested changes

2017-07-19 21:19 UTC, dschwen commented on framework/include/utils/TrilinearInterpolation.h
> +#ifndef TRILINEARINTERPOLATION_H
Needs a header

2017-07-20 16:36 UTC, andrsd commented
@dschwen Your comments were addressed

2017-07-20 16:56 UTC, dschwen approved these changes

2017-07-20 17:27 UTC, merged