Add FunctionDiracSource and test
idaholab/moose pull request #9555
Opened 2017-07-25 23:18 UTC by snschune

As title. 
Test switches off a constant point source at `t=1`. Total integral of `u` stays constant after that.

2017-07-25 23:47 UTC, moosebuild commented
Job [Documentation](https://www.moosebuild.org/job/103198/) on d64da0e wanted to post the following:

View the site [here](http://mooseframework.org/docs/PRs/9555/site)

2017-07-27 13:46 UTC, jwpeterson requested changes

2017-07-27 13:46 UTC, jwpeterson commented on framework/src/dirackernels/FunctionDiracSource.C
> +    _point_param(getParam<std::vector<Real>>("point"))
This is probably copied from `ConstantPointSource` but it's really the old way of reading in Points. Just use `getParam<Point>` instead.

2017-07-27 17:10 UTC, moosebuild commented
Job [Precheck](https://www.moosebuild.org/job/103518/) on b240ea7 wanted to post the following:

Your code requires style changes.
In the top level of your repository, you can run:

`git clang-format f83040c3976ab38df6f39f3c80a694678bb44a06`

Alternatively, apply the patch found [here](http://mooseframework.org/docs/PRs/9555/style.patch).
You can directly apply the patch by running:

`curl -s http://mooseframework.org/docs/PRs/9555/style.patch | git apply -v`

2017-07-27 17:21 UTC, dschwen commented
@snschune you can avoid the clang-format issue, by going into the settings of the _clang-format_ Atom plugin and changing the _Executable_ setting to what `which clang-format` returns in your terminal (probably `/opt/moose/llvm-3.9.0/bin/clang-format`).

2017-07-27 18:05 UTC, jwpeterson approved these changes

2017-07-27 21:15 UTC, merged