Calculate q without auxvariables and auxkernels
idaholab/moose pull request #9568
Opened 2017-07-27 00:19 UTC by liuusu

Calculate q on the fly without auxvariables and auxkernels. Option is given for users to output q. Tests are added.

Ref #9559

2017-07-27 00:20 UTC, moosebuild commented on libmesh
> +Subproject commit 9a3100a84c2d5f16126c6d8df57d068c19f15e45
**Caution!** This contains a submodule update

2017-07-27 15:00 UTC, moosebuild commented
Job [Documentation](https://www.moosebuild.org/job/103445/) on 29742e8 wanted to post the following:

View the site [here](http://mooseframework.org/docs/PRs/9568/site)

2017-07-27 16:20 UTC, moosebuild commented on libmesh
> +Subproject commit 9a3100a84c2d5f16126c6d8df57d068c19f15e45
**Caution!** This contains a submodule update

2017-07-27 17:55 UTC, moosebuild commented on libmesh
> +Subproject commit 9a3100a84c2d5f16126c6d8df57d068c19f15e45
**Caution!** This contains a submodule update

2017-07-27 21:19 UTC, jwpeterson requested changes
@liuusu This PR can't be merged because you have inadvertently checked in a libmesh submodule update with your branch (moosebuild is trying to warn you about this).

Since you only have 1 commit, it should be pretty easy for you to fix, let us know if you require assistance.

2017-07-28 15:55 UTC, liuusu commented
@bwspenc For testing, I did "mpiexec -n 2 moose_test-opt --n-threads=1 -i time-adaptive.i --distributed-mesh --error --no-gdb-backtrace" on my local computer and it worked fine.  The input file "time-adaptive.i" does not seem to relate to my changes.

2017-07-28 18:10 UTC, moosebuild commented
Job [Test Intel](https://www.moosebuild.org/job/103763/) on 5f8aed3 : invalidated by @bwspenc

Test timeout -- unrelated to commit

2017-07-28 19:16 UTC, bwspenc requested changes
Just a few issues as noted

2017-07-28 19:16 UTC, bwspenc commented on modules/solid_mechanics/src/postprocessors/InteractionIntegral.C
> +InteractionIntegral::computeQpIntegralPhi(const std::vector<std::vector<Real>> & phi,
Per our discussion, let's do this all in `computeQpIntegral()`

2017-07-28 19:17 UTC, bwspenc commented
@jwpeterson He fixed the libmesh submodule issue you requested changes on.

2017-07-28 19:44 UTC, jwpeterson submitted a review, later dismissed

2017-07-28 20:53 UTC, moosebuild commented
Job [Precheck](https://www.moosebuild.org/job/104120/) on b282e50 wanted to post the following:

Your code requires style changes.
In the top level of your repository, you can run:

`git clang-format cd27df19f5d0fba047eeae7296bb7b8d0135632d`

Alternatively, apply the patch found [here](http://mooseframework.org/docs/PRs/9568/style.patch).
You can directly apply the patch by running:

`curl -s http://mooseframework.org/docs/PRs/9568/style.patch | git apply -v`

2017-07-28 21:54 UTC, bwspenc approved these changes

2017-07-28 21:56 UTC, bwspenc commented
@liuusu You're going to need to clang-format the code.

2017-07-28 21:59 UTC, bwspenc requested changes
Just a couple of little things to clean up while you're doing the clang-format. Otherwise, I think it's good to go.

2017-07-28 21:59 UTC, bwspenc commented on modules/solid_mechanics/include/postprocessors/InteractionIntegral.h
> +class QBase;
Did you determine that you needed these?

2017-07-28 21:59 UTC, bwspenc commented on modules/solid_mechanics/include/postprocessors/InteractionIntegral.h
> +  std::vector<Real> _q_elem;
How about calling these `_q_curr_elem`, `_phi_curr_elem`, etc, just to be a little more clear.

2017-07-28 21:59 UTC, bwspenc commented on modules/solid_mechanics/src/actions/DomainIntegralAction.C
> +    params.set<MultiMooseEnum>("execute_on") = "initial timestep_end"; // was "initial nonlinear"
Just remove the comment at the end of this line.

2017-07-31 15:14 UTC, bwspenc approved these changes

2017-07-31 15:14 UTC, merged