Updating the MOOSE docs getting started
idaholab/moose pull request #9639
Opened 2017-08-10 16:58 UTC by permcody

refs #9638

2017-08-10 17:09 UTC, moosebuild commented
Job [Documentation](https://www.moosebuild.org/job/106752/) on 6351e87 wanted to post the following:

View the site [here](http://mooseframework.org/docs/PRs/9639/site)

2017-08-10 22:38 UTC, aeslaughter requested changes

2017-08-10 22:38 UTC, aeslaughter commented on docs/content/utilities/moose_docs/setup.md
>  pip install python-markdown-math bs4 pybtex jinja2 livereload lxml pylatexenc anytree
can you add "pandas" to this please, this is something that I should of done a while ago.

2017-08-10 22:57 UTC, permcody commented on docs/content/utilities/moose_docs/setup.md
>  pip install python-markdown-math bs4 pybtex jinja2 livereload lxml pylatexenc anytree
Yep - right next to liver-eload! Got it

2017-08-11 14:29 UTC, permcody commented on docs/content/utilities/moose_docs/setup.md
>  pip install python-markdown-math bs4 pybtex jinja2 livereload lxml pylatexenc anytree
Done

2017-08-11 14:57 UTC, aeslaughter approved these changes

2017-08-11 14:57 UTC, merged