Deprecate UserForcingFunction
idaholab/moose pull request #9879
Opened 2017-09-19 21:09 UTC by aeslaughter

(closes #9876)

2017-09-21 19:57 UTC, moosebuild commented
Job [Documentation](https://www.moosebuild.org/job/118314/) on 3300846 wanted to post the following:

View the site [here](http://mooseframework.org/docs/PRs/9879/site)

This comment will be updated on new commits.

2017-09-22 14:10 UTC, moosebuild commented
Job [App tests](https://www.moosebuild.org/job/118353/) on 3e1ff4a : invalidated by @aeslaughter

Fix is in marmot

2017-09-22 16:34 UTC, moosebuild commented
Job [Documentation](https://www.moosebuild.org/job/118343/) on 3e1ff4a : invalidated by @aeslaughter

2017-09-22 18:50 UTC, aeslaughter commented
This is ready.

2017-09-22 19:54 UTC, permcody requested changes

2017-09-22 19:54 UTC, permcody commented on docs/content/documentation/systems/Distributions/stochastic_tools/LognormalDistribution.md
> -# LognormalDistribution
You probably don't want to delete this!

2017-09-22 19:54 UTC, permcody commented on framework/src/base/Factory.C
> +  std::set<std::string>::iterator iter = _deprecated.find(obj_name);
`auto`

2017-09-22 19:54 UTC, permcody commented on framework/src/base/Factory.C
> +  std::map<std::string, std::string>::iterator name_it = _deprecated_with_replace.find(obj_name);
`auto`

2017-09-22 19:54 UTC, permcody commented on test/tests/misc/block_boundary_material_check/dgkernel_check_block.i
> -[Mesh]
Did you mean to delete this?

2017-09-22 19:54 UTC, permcody commented on test/tests/misc/block_boundary_material_check/dgkernel_check_boundary.i
> -[Mesh]
Did you mean to delete this?

2017-09-22 19:54 UTC, permcody commented on test/tests/misc/block_boundary_material_check/tests
> -[Tests]
Did you mean to delete this?

2017-09-22 19:54 UTC, permcody commented on test/tests/vectorpostprocessors/csv_reader/transfer/master.i
> -[Mesh]
Did you mean to delete this?

2017-09-22 19:54 UTC, permcody commented on test/tests/vectorpostprocessors/csv_reader/transfer/sub.i
> -[Mesh]
Did you mean to delete this?

2017-09-22 19:54 UTC, permcody commented on test/tests/vectorpostprocessors/csv_reader/transfer/tests
> -[Tests]
Did you mean to delete this?

2017-09-25 16:07 UTC, permcody approved these changes

2017-09-25 16:08 UTC, merged