Improving file tree building for markdown import
idaholab/moose pull request #9952
Opened 2017-09-27 23:42 UTC by aeslaughter

(closes #9951)

2017-09-27 23:43 UTC, aeslaughter commented
I still need to work on integrating this with the apps, this is just to see how far I got w/r/t MOOSE.

2017-09-28 14:34 UTC, moosebuild commented
Job [Documentation](https://www.moosebuild.org/job/120679/) on fe66827 wanted to post the following:

View the site [here](http://mooseframework.org/docs/PRs/9952/site)

This comment will be updated on new commits.

2017-09-28 17:35 UTC, aeslaughter commented
This is ready, I have patches waiting for applications.

2017-09-28 18:41 UTC, permcody requested changes
I'd like to see some docs on the complex regexes you are using. This method doesn't even say what it's doing anywhere.

2017-09-28 18:41 UTC, permcody commented on python/MooseDocs/common/moose_docs_import.py
> +    out = re.sub(r'(?!<^|/)(\*{2})(?=/|$)', r'(?:.*?)', out, flags=re.MULTILINE)
I really think you should document these. This is pretty complex and will be difficult to maintain later. You can be pretty extreme with how you break them up: 
https://github.com/idaholab/moose/blob/devel/modules/chemical_reactions/src/actions/AddCoupledEqSpeciesAction.C#L51-L59

2017-09-28 19:14 UTC, brianmoose approved these changes

2017-09-28 19:20 UTC, permcody approved these changes

2017-09-28 19:20 UTC, merged